### PR TITLE
User settings page

### LINKED ISSUE #2796: PLANNING ISSUE: Subscription Settings
Subscription Settings would be a part of **Settings** page. I would be creating a settings page where Subscription settings will be a section but I think after this we would like to add more things to the settings page for giving users more power. 

Checklist for start:
* [ ] Migration for generating `digest:weekly` or any other to all profiles
* [x] Method in `user_controller.rb`  for accepting the response from settings page
* [x] Creating a view for the settings page
* [x] Procedure for getting settings page using tags

I would be adding more points shortly.
  
@jywarren @steviepubliclab @ebarry

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2796 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
I think this error is intermittent and unrelated -- there's an issue at #2824 ?

Restarted it!

**Comment by jywarren** [comment]
Great, just a CodeClimate thing - want to approve it?

**Comment by Gauravano** [comment]
hi @jywarren looks you have to `Class UsersController has 21 methods (exceeds 20 allowed)` . Thanks.

**Comment by ViditChitkara** [comment]
Great work @Gauravano !! However, we need to come up with a minimum number of tags which need to be added for which a cron job is to be made in scheduler.rb . e.g digest:daily, digest:monthly, digest:daily and so on..Could you have a look at #2772 . I have used def customize_digest(type) method to add and remove these tags. You might want to use them in the controllers, once it gets merged. @jywarren any ideas??

**Comment by Gauravano** [comment]
hi @ViditChitkara , I will adjust my view according to your controller function after your PR will be merged. Thanks.

**Comment by ViditChitkara** [comment]
Cool :+1:

**Comment by Gauravano** [comment]
Hey @jywarren , @ViditChitkara and I was just discussing whether a user should be able to select only one type of digest from `weekly digest` and `daily digest` or not. what do you think about this?

**Comment by jywarren** [comment]
Ah, like not both? Is there an efficiency or code simplicity reason to not allow both? If there isn't, i guess we can let people get a daily AND weekly digests... odd but maybe someone would like it?

**Comment by ViditChitkara** [comment]
I thought of it a bit and came to a conclusion that, if we allow both, every week user would get 2 digest mails which is kind of inappropriate (and daily mails too). However, if a user opts for daily digest, he we automatically get weekly mails. While if a user chooses weekly, then most probably he/she wants only weekly mails and not daily. Makes sense??

**Comment by Gauravano** [comment]
As we don't have digest template or any final preparation. I think I should close this one for now. I will make the settings page based on current settings in #2985 .Thanks!

**Pull request closed without merging**
