### PR TITLE
Added non empty validation for search form Closes #2181

### LINKED ISSUE #2181: Add search validation
### Please describe the problem (or idea)
Currently we can perform submission of search form even when input field is empty which leads to opening of another page which have no content since our input was empty.
So what we can do is that we can add validation that input mush not be blank or empty.

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Closes #2181 
* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Whoa, cool -- where does `setCustomValidity` come from? Is that a new feature of JavaScript? Can you link to some docs so I can catch up? 

It does look like perhaps that caused a JavaScript test error:

```

ERROR: TypeError: null is not an object (evaluating 'document.getElementById("searchform_input").setCustomValidity')
TRACE:
 -> file:///app/tmp/jasmine/assets/jasmine-specs.js: 34695
 -> file:///app/tmp/jasmine/assets/jasmine-specs.js: 3120 (in function "fire")
 -> file:///app/tmp/jasmine/assets/jasmine-specs.js: 3232 (in function "fireWith")
 -> file:///app/tmp/jasmine/assets/jasmine-specs.js: 3444 (in function "ready")
 -> file:///app/tmp/jasmine/assets/jasmine-specs.js: 3475 (in function "completed")
```

Do we need to include something to make such a validation work?

**Comment by namangupta01** [comment]
Hey @jywarren 
Here's the link https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/setCustomValidity

**Comment by namangupta01** [comment]
This validation working fine on my local machine.
screen shot 2018-02-03 at 1 12 23 am

**Comment by namangupta01** [comment]
@jywarren I included the script with html because this new api `setCustomValidity` of JavaScript return null but the jasmine is looking for some object to return that's why it was failing. But now it's working correctly.

**Comment by jywarren** [comment]
This is cool. I wonder if we could use it to fix #2085 by locally validating title/body fields? Want to chime in over there with this idea?

**Pull request merged**
