### PR TITLE
camelCase atwho_autocomplete.js filename

### LINKED ISSUE #9143: camelCase atwho_autocomplete.js filename
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### ❓ Why are we doing this?

See Issue #9140 for more information!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** these files below:

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below are some "diffs" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add for each file:

`/app/views/comments/_form.html.erb`
```diff
+ <script src="/assets/atWhoAutoComplete.js" type="text/javascript"></script>
- <script src="/assets/atwho_autocomplete.js" type="text/javascript"></script>
```

`/config/initializers/assets.rb`:
```diff
+ 'atWhoAutoComplete.js', 
-  'atwho_autocomplete.js',
```

`/app/assets/javascripts`:
```diff
+ atWhoAutoComplete.js
- atwho_autocomplete.js
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by shadowoflight**
Fixes #9143  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravahlawat81** [comment]
Hey @shadowoflight , great work with the PR :confetti_ball:, just one minor suggestion, could you please edit the first line in PR description. It currently says `Fixes #0000`, you might want to change it to `Fixes #9143`. This helps in automatically closing the issue once the PR gets merged.

**Comment by cesswairimu** [comment]
restarting build

**Comment by noi5e** [comment]
@shadowoflight Great job! It looks like we can't merge this until the codeclimate issues are either fixed or skipped.

I'll take a closer look soon. I doubt this is your fault... The code in `atWhoAutoComplete.js` is pretty old, and codeclimate hasn't been run on it yet. 

Would you be up to making some of the codeclimate changes in the file?

**Comment by noi5e** [comment]
Looked into the codeclimate issues. I'm glad I researched this! I discovered that the code in `atWhoAutoComplete.js` introduces auto-fill suggestion for typing emojis, usernames, and topic tags. Amazing!

The code is a little bit wonky. Only typing emojis works, and the emojis don't show in markdown preview for some reason. Usernames and topic tags suggestion doesn't work. Maybe something wrong with the API calls?

I feel motivated to work on this one, will come back to it later.

**Comment by noi5e** [comment]
Anyway, all the above is unrelated and out-of-scope with this PR.

I think the best thing to do is to merge this one as is. And then I can readdress the actual content of this file in another PR.

@jywarren, can you override the codeclimate to merge this one please?

Congrats @shadowoflight!!!

**Review by noi5e — APPROVED** [review]

**Review by cesswairimu — APPROVED** [review]
:tada:

**Review by jywarren — APPROVED** [review]
Just bypassed the CodeClimate, and this looks great, thank you!!!!

**Comment by jywarren** [comment]
I also resolved a small merge conflict that came from an upstream change; this is ready to merge after tests pass again!

**Comment by jywarren** [comment]
Congrats!!!

**Pull request merged**
