### PR TITLE
Preserve `return_to` param when switching from /login to /signup

### LINKED ISSUE #4893: Preserve `return_to` param when switching from /login to /signup
Related to #4759: Note that when going to: 

`https://stable.publiclab.org/subscribe/multiple/tag/arduino,games`, you then get redirected to: 

`https://stable.publiclab.org/login?return_to=/subscribe/multiple/tag/arduino,games`

However, if you then click "Sign up" you then just see `https://stable.publiclab.org/signup`. Let's do a follow-up issue to ensure that if you click Sign up, it preserves the `return_to` parameter!

We'd love help with this!

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #4893 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@gauravano @jywarren I think this is ready to be merged. Can you please review it?

**Comment by gauravano** [comment]
Okay, tried this for multiple cases. Results are as:
Although, we open login modal if someone clicks on subscribe button but yes, it will help in cases where the link is pressed from email?

The return_to is maintained from /login  to /signup but after signing up user has to press on the **here** link present in the alert which leads to return_to path. So, should we also try to solve that or we are good here?

Thanks!

**Comment by SidharthBansal** [comment]
Press to start from where you left is solved in other PR.
This PR is just for switching from login to signup.

**Comment by jywarren** [comment]
This looks good. Would you like to try writing a simple system test for it? The system tests can include interactions like clicking, and then confirming things appear, even with JS interactions! See https://github.com/publiclab/plots2/pull/5525

**Comment by jywarren** [comment]
Just want to say ❤️ this series of PRs is GREAT

**Comment by SidharthBansal** [comment]
Sure. I will write a system test for this. Thanks.

**Pull request merged**
