### PR TITLE
Remove Less and less-rails gems, including the-ruby-racer

### LINKED ISSUE #8199: Remove Less and less-rails gems, including the-ruby-racer and v8?
Do we use Less? It requires v8 and the-ruby-racer, which are pretty heavy. 

https://github.com/publiclab/plots2/tree/main/app/assets/stylesheets doesn't have any .less files

https://github.com/publiclab/plots2/tree/main/app/assets/less hasn't changed in 6 years and i think we don't use lightbox anymore. Shall we just remove it and get both `the-ruby-racer` and `less` out of our Gemfile?

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #8199  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
@jywarren @cesswairimu I've removed `less-rails` and `therubyracer` from the Gemfile and removed all associated dependencies. Please let me know if this is fine. Thanks in advance!

**Review by Tlazypanda — COMMENTED** [review]
@Manasa2850 LGTM! :100: Let's wait for @jywarren if there are some other areas of the codebase we need to check this for

**Review by cesswairimu — APPROVED** [review]
Looks great, thanks

**Review by jywarren — APPROVED** [review]
AWESOME!! Thank you so much!!!!

**Pull request merged**
