### PR TITLE
First timers nav bar

### LINKED ISSUE #6995: Make the main navigation bar responsive
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 🔥 Problem:

Screenshot_20191217_175103

Screenshot_20191217_175206

As you can see from the pictures above, the current navigation bar has some problems :(
Search bar splits up on screens width  990 - 1110 & 768 - 860.
On mobile devices, the hamburger menu is not aligned with the logo. 

### 🚩 Goal:

nav

Screenshot_20191217_180357

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Work**

**1)** Open plots2/app/views/layouts/_header.html.erb

- Remove inline styles from the input element on line 20 plots2/app/views/layouts/_header.html.erb

- On line 149 change the class `d-xl-none` to `d-lg-none` to make the hamburger menu disappear on the large screens

**2)** Open plots2/app/assets/stylesheets/style.css

- On line 221 - 229, remove `padding-top`, add `margin-top: 0.3125rem;` and set `margin-bottom: 0;` like this:

```css
@media (max-width: 768px) {
  #header #brand,
  #header #brand-compact {
    margin-top: 0.3125rem;
    padding-bottom: 0;
    padding-right: 4px;
  }
}
```

- After line 128, `#pl_pad` selector add this code:

```css
#header .navbar .input-group {
  flex-wrap: nowrap;
}

#header .navbar #searchform_input {
  cursor: text;
  min-width: 190px;
}
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by polygonart6777**
Fixes #6995  (<=== Add issue number here)

I am not able to run rake test and was not able to complete the second checkbox.  I also am not sure if there are any merge conflicts.  Any help with this would be greatly appreciated.

Thank you.

Best,

Dina

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this is awesome. Thanks! Can you show us a screenshot of the page at
the width that was causing the issue?

Thanks again!

**Comment by polygonart6777** [comment]
Hi Jeffrey,

It looks like the navigation bar splits at screens of width 990 - 1110 &
768 - 860 as stated on the issue description.  On the description they have
provided a screenshot of the split navigation bar and the misaligned
hamburger menu on the mobile version of the site.
[image: image.png]

If necessary, I can also provide screenshots of both issues with my own
computer and phone.

**Comment by jywarren** [comment]
Oh awesome! Actually image attachments sadly don't get copied in by email, can you attach them directly? Thanks!!

**Comment by polygonart6777** [comment]
Please let me know if more screenshots of the previous issue are needed.

**Comment by polygonart6777** [comment]
screenshotofissue

**Comment by ananyaarun** [comment]
Hey @polygonart6777 are you a GCI participant ? If so I shall add this issue to the dashboard for you.
Thanks !

**Comment by VladimirMikulic** [comment]
@jywarren We can merge this.

**Comment by VladimirMikulic** [comment]
@polygonart6777 sometimes styles differ between the development version and the production version.
Just keep that in mind for the future :)

**Comment by polygonart6777** [comment]
What is GCI?  I'm not participant.

**Comment by jywarren** [comment]
Hi, this looks good! Can you share with the menubar included too, it just looks like perhaps the menubar got much wider in the second screenshot but I can't tell if it's the right scale without some size reference. I think this is good but just being sure! Thanks!

**Comment by Uzay-G** [comment]
Hey @polygonart6777, the [Google CodeIn](https://codein.withgoogle.com) is a contest for young coders to learn more about opensource and learn more alongside public orgs like Publiclab.

**Comment by VladimirMikulic** [comment]
@jywarren A [video](https://streamable.com/cf2jy) is worth a thousand words :)

**Comment by jywarren** [comment]
Omg beautiful and so true!!!! Great collaboration here folks! Merging now and great job @polygonart6777!!!!

**Comment by VladimirMikulic** [comment]
@polygonart6777 congratulations on your first merged PR :rocket: :rocket: :rocket:

**Comment by jywarren** [comment]
Agree!!!!! 👏🏽👏🏽👏🏽

**Comment by polygonart6777** [comment]
Thank you thank you!!!

**Pull request merged**
