### PR TITLE
Tooltip placement position moved to top

### PR DESCRIPTION
**Pull request by gettinDrikkieWithIt**
Fixes #[9836](https://github.com/publiclab/plots2/issues/9836) (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gettinDrikkieWithIt** [comment]
Hi @cesswairimu, think you can give this a review 😃

**Review by cesswairimu — APPROVED** [review]
wow that was fast! Thanks @gettinDrikkieWithIt for working on this :tada: :tada:

**Comment by gettinDrikkieWithIt** [comment]
> wow that was fast! Thanks @gettinDrikkieWithIt for working on this 🎉 🎉

Awesome, thanks 😄. Just the Codecove giving some issues...about a parent commit it can't find 🤷. 
Once I'm done setting up my environment I'll start helping with some issues

**Comment by cesswairimu** [comment]
the error seems unrelated to the changes, I will close and reopen to invoke the checks rerun

**Comment by cesswairimu** [comment]
that fixed it...merging now. thanks again

**Pull request merged**
