### PR TITLE
Modified navigation-bar

### PR DESCRIPTION
**Pull request by simransia**
I have fixed the alignment of the "About us" nav-link and have also made the widths of both the "Store" and "Donate" buttons equal. Also, I have changed the about_title present in the en.yml file from "About us" to "About Us".
This will make the navigation bar look better 😇

**Here is the screenshot:**

Screenshot **(127)

**Here is the video:**

https://user-images.githubusercontent.com/88017902/163303441-23dddd13-85c9-4d1b-b0d8-410efac9a385.mp4

**Fixes** #11049 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
HI @simransia, can you add screenshots? Thanks!!

**Comment by simransia** [comment]
> HI @simransia, can you add screenshots? Thanks!!

Hello @TildaDares I have attached the screenshot and video of the navbar.

Thank you so much for guiding me patiently about my mistakes!

**Comment by TildaDares** [comment]
@simransia The navbar items are misplaced on smaller screens

Screenshot 2022-04-14 at 17 23 01

**Comment by simransia** [comment]
> @simransia The navbar items are misplaced on smaller screens
> 
> Screenshot 2022-04-14 at 17 23 01

Hello @TildaDares, I have fixed this issue by using media queries and sorry for not recognizing this issue before.
Now the nav-links are looking fine on smaller screens also and the buttons are having a little space between them. You can view it in the screenshot below:

Screenshot (143)

Thank You.

**Comment by TildaDares** [comment]
@simransia From screen size 576px - 768px, the `store` and `donate` buttons don't show.

**Comment by simransia** [comment]
> @simransia From screen size 576px - 768px, the `store` and `donate` buttons don't show.

@TildaDares mam, On the mention screen sizes, those buttons were already not showing from starting even before I have started modifying the navigation bar. 

This is the screenshot of the present working website of public lab:

Screenshot (152)

**Comment by TildaDares** [comment]
@simransia You're right. Do you think you could add them? Thank you!!

**Comment by simransia** [comment]
> @simransia You're right. Do you think you could add them? Thank you!!

Yes @TildaDares mam, I can add them. I have just now tried adding them and they are occupying the full width of the page after getting added. So, I want to know your preference. You can choose one from the below images:

**Are they looking good like this:**

Screenshot (157)


**Or should I make their width smaller like this:**

Screenshot (156)

**Comment by TildaDares** [comment]
@simransia The first image is better. Thanks!!

**Comment by simransia** [comment]
> @simransia The first image is better. Thanks!!

Hello @TildaDares. I have added the 'store' and 'donate' buttons on the mentioned screen sizes successfully. And I am ready to do any further modifications if needed.

Thank You so much!

**Review by TildaDares — APPROVED** [review]
Thanks for working this @simransia!!

**Comment by TildaDares** [comment]
Thank you @simransia!!

**Comment by simransia** [comment]
> Thank you @simransia!!

It's my pleasure @TildaDares !
I am so happy working on this! 🤩

**Pull request merged**
