### PR TITLE
[WIP] Fix ask and comment tabs on profile and contributor pages

### LINKED ISSUE #5958: The `answered` and `asked` tab doesn't work
#### Description

The answered and asked tab seems to have broken and is not working.

Screenshot from 2019-06-28 17-39-19

### PR DESCRIPTION
**Pull request by michelelong**
Fixes #5958

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by michelelong** [comment]
@CleverFool77  and @jywarren 

I fixed the broken tabs links, but there seems to be another problem here.

Questions with comments show 0 answers (see pic) and there doesn't seem to be a way to accept a comment as having answered the question, which results in the answered tab always being empty.

contrib-answers

contrib-ask

contrib-empty-answers

**Comment by CleverFool77** [comment]
The unit test failure is not related to this PR at all but I guess we need to fix the functional tests.

**Comment by gauravano** [comment]
Hi, I restarted the build for unit test and it passed. Now, functional tests need to be fixed.

**Comment by cesswairimu** [comment]
Hey @CleverFool77. I fixed the failing tests here but when doing rebase I realized you changed the design of `app/views/users/profile.html.erb` which looks great :+1: ..Do we still need this implementation? Thanks

**Comment by jywarren** [comment]
Hi, I believe enough has changed on later PRs that we are good here. I appreciate your contribution and hope you're doing well!

**Pull request closed without merging**
