### PR TITLE
change .length to .size in views/editors.newsletter #8580

### PR DESCRIPTION
**Pull request by tawahpeggy**
Fixes https://github.com/publiclab/plots2/issues/8572

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by tawahpeggy** [comment]
@jywarren @cesswairimu i made a new pull request for this issue cause i could'nt seem to figure out what went wrong before, please review. sorry for stressing you up.

**Review by Tlazypanda — COMMENTED** [review]
Hey @tawahpeggy the changes in _newsletter file looks great :tada: can you remove the other file that is also changed here _form.html.erb ?

**Comment by tawahpeggy** [comment]
okay @Tlazypanda thanks for your response. there happen to be 2 files in the pull request cause i fixed two issues and made a single pull request for both

**Comment by cesswairimu** [comment]
Hi  @tawahpeggy we normal have 1 pull request per issue. You could remove the changes for the other issue and open a new pull request for the other issue. Thanks

**Comment by cesswairimu** [comment]
> I just merged another PR that fixes this #8576. Sorry @tawahpeggy I will get another issue for you. Closing this. Thanks all

I left a link for another issue for you on the issue. Ping me if its already taken. Sorry again

**Pull request closed without merging**
