### PR TITLE
warning on deletion of last wiki revision

### LINKED ISSUE #2647: Urgent: Home down because of invalid record (?)
```
Started GET "/" for 47.31.242.72 at 2018-04-21 19:46:30 +0000
Processing by HomeController#home as HTML
Read fragment views/feature_home-carousel (0.3ms)                                                                                                              Read fragment views/feature_home-banners (0.1ms)                                                                                                               Read fragment views/home-activity (0.1ms)                                                                                                                      Read fragment views/trending-tags (0.1ms)                                                                                                                        Rendered dashboard/_node_comment.html.erb (9.2ms)                                                                                                              Rendered dashboard/_node_meta.html.erb (3.2ms)                                                                                                                 Rendered dashboard/_node_wiki.html.erb (7.5ms)                                                                                                                 Rendered dashboard/_node_wiki.html.erb (2.0ms)                                                                                                                 Rendered dashboard/_activity.html.erb (22.7ms)
  Rendered home/home.html.erb within layouts/application (25.9ms)
Completed 500 Internal Server Error in 37ms (ActiveRecord: 3.4ms)

ActionView::Template::Error (undefined method `author' for nil:NilClass):
    3:                                                                                                                                                             4:     <% if node.is_a?(Node) %>
    5:       <div class="header-icon"><i class="fa fa-book"></i></div>
    6:       <p class="meta"><span><%= t('dashboard._node_wiki.new_page_by') %></span> <a href="/profile/<%= node.latest.author.name %>"><%= node.latest.author.name %></a></p>                                                                                                                                                   7:     <% else %>
    8:       <div class="header-icon"><i class="fa fa-pencil"></i></div>
    9:       <p class="meta"><%= t('dashboard._node_wiki.new_edit_by') %> <a href="/profile/<%= node.author.try(:name) %>"><%= node.author.try(:name) %></a></p>
  app/views/dashboard/_node_wiki.html.erb:6:in `_app_views_dashboard__node_wiki_html_erb___2292190031077852178_69979555127840'
  app/views/dashboard/_activity.html.erb:67:in `block in _app_views_dashboard__activity_html_erb__2360015329309354006_69979556424080'
  app/views/dashboard/_activity.html.erb:65:in `each'
  app/views/dashboard/_activity.html.erb:65:in `each_with_index'
  app/views/dashboard/_activity.html.erb:65:in `_app_views_dashboard__activity_html_erb__2360015329309354006_69979556424080'
  app/views/home/home.html.erb:118:in `block in _app_views_home_home_html_erb__1339280168507799139_35544200'
  app/views/home/home.html.erb:117:in `_app_views_home_home_html_erb__1339280168507799139_35544200'
  app/controllers/home_controller.rb:18:in `home'
```

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2647 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
hey @jywarren, I have kept redirect to  @node.path. Should I change the redirect path ?

**Comment by jywarren** [comment]
Hmm I guess that works! Do you want to try merging this into my PR to see
if it fixes my new tests?

**Comment by Gauravano** [comment]
ok I will try

**Comment by Gauravano** [comment]
Commit added in #2648

**Pull request closed without merging**
