### PR TITLE
[WIP] Update_path of "# research notes" on the dashboard to notes/author

### LINKED ISSUE #5274: Change the path of "# research notes" on the dashboard from profile to notes/author
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file app/views/dashboard/_header.html.erb in the plots2 repository. The "# research note" link with the welcome user (below Dashboard) directs the user to their profile page, instead it should direct the user to the notes page.

In the line 16, change
`<a href="/profile/<%= current_user.username %>">`
to
`<a href="/notes/author/<%= current_user.username %>">`

Screen Shot 2019-03-27 at 7 37 12 PM

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

### PR DESCRIPTION
**Pull request by AnthoniaOkafor**
Publiclab_dashboardPath_gif

Fixes #5274 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by AnthoniaOkafor** [comment]
Please @gauravano, I need your help.

I went to my fork https://github.com/AnthoniaOkafor/plots2/ and on the drop-down list labelled 'Branch:master', I added a new fork named 'patch-4'. then I went to cloud9, checked-out master, updated the local branch with git pull command, solved the requested issue and created a new feature-branch by running the following command:
git checkout -b patch-4 
Then I pushed with:
git push origin patch-4

Coming to https://github.com/publiclab/plots2, I created a pull request but the file in the 'File changed' menu is the file from my first PR on Publiclab.

This approach is different from the approach used in my first PR on Publiclab, then I edited on github but now I chose to use the terminal. Please help.

**Comment by gauravano** [comment]
Ah, have you merged your previous branch with master? You can reset the master branch using https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch and then create a new branch from the synced master or rebase your PR. Thanks!

**Comment by AnthoniaOkafor** [comment]
> Ah, have you merged your previous branch with master? You can reset the master branch using https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch and then create a new branch from the synced master or rebase your PR. Thanks!

I'm still not getting it. I followed the directions to rewind and rebase the master branch from the link you gave me but the file from my first PR is still attached to this. I also created a new branch called 'patch-5' and wanted to create a new PR from it but stopped when I noticed the same previous file is being attached instead of the '_header.html.erb' file from /app/views/dashboard/_header.html.erb
Kindly help me @gauravano .

**Comment by gauravano** [comment]
See, the changes you made in your last PR would be there in master branch as we have merged your last PR. The thing is, the git shouldn't track them as commits in this PR so you can run `git log` after following https://github.com/publiclab/plots2/pull/5302#issuecomment-478039190 and see if the top commits are same as https://github.com/publiclab/plots2/commits/master . If yes, you can form new branch using `git branch -b branch-name` and can do changes, commit them and lastly push the branch. Thanks!

**Comment by AnthoniaOkafor** [comment]
> See, the changes you made in your last PR would be there in master branch as we have merged your last PR. The thing is, the git shouldn't track them as commits in this PR so you can run `git log` after following [#5302 (comment)](https://github.com/publiclab/plots2/pull/5302#issuecomment-478039190) and see if the top commits are same as https://github.com/publiclab/plots2/commits/master . If yes, you can form new branch using `git branch -b branch-name` and can do changes, commit them and lastly push the branch. Thanks!

Hello @gauravano . With your help, I was able to resolve it, however when I formed a new branch, I opened a new PR for it https://github.com/publiclab/plots2/pull/5335. Many thanks

**Comment by gauravano** [comment]
Ok, closing this PR then. Thanks!

**Pull request closed without merging**
