### PR TITLE
Suggestion for a text edit on the signup page #5227

### LINKED ISSUE #5227: Suggestion for a text edit on the signup page
Hey team,

A suggestion for an edit to the signup page to make the Code of Conduct/Privacy Policy more visible. If we could move the following line of text above the sign up button it will be more prominent for new users & (in theory) more widely read. 
Text: "By signing up, you agree to the Code of Conduct, which applies to all online and in-person spaces managed by the Public Lab community and non-profit. You also agree to our Privacy Policy."
See below for current setup and the proposed setup from a different site. 

Screen Shot 2019-03-21 at 11 49 35 AM

Screen Shot 2019-03-21 at 11 50 11 AM

### PR DESCRIPTION
**Pull request by edwd42**
…estion for a text edit on the signup page #5227

Fixes #5227 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
#5227 
@publiclab/reviewers - I completed the task and got the green check Able to merge on the PR page.
But the signup form looks nothing like the screenshot above. How can I be sure I have the right page? I clicked the link above and edited plots2/app/views/users/_create_form.html.erb
here's a screenshot of the sign up form after my changes
Signup_form_issue_5227

### CODE REVIEW

**Comment by gauravano** [comment]
@jywarren locally it's working fine with both recaptcha and spamaway:

Screenshot from 2019-08-23 01-18-01

but on unstable, the feature is not appearing. So, should we merge this one?

**Comment by jywarren** [comment]
Thanks!!!! This is great.

**Comment by gauravano** [comment]
Hey @jywarren, stable.publiclab.org is not loading so can't verify if this fix worked or not. Can you see why it's down?

**Comment by jywarren** [comment]
I'm not sure if we have an issue open but our build server is offline now
and we need to investigate, in person, i think. :-/ but will update as soon
as we can!

**Pull request merged**
