### PR TITLE
Add css to 'Subscribe to answer questions' button #5462

### LINKED ISSUE #5462: Add css to 'Subscribe to answer questions' button
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_question.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/show/_questions.html.erb) in the `plots2` repository.
Use the css of the 'Ask a question' button for the 'Subscribe to answer' button.
Updated look:

newlook

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by johnmidavis**
The partial /app/views/tag/show/_questions.html.erb pulls the button html from a localized string tag.show.or_subscribe_to_answer. Fix was therefore in the config/locales/en.yml instead.  

Fixes #5462  (<=== Add issue number here)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

BEFORE

Screenshot-before

AFTER

Screenshot-after

### CODE REVIEW

**Comment by johnmidavis** [comment]
hey @publiclab/reviewers this is my first review so there are probably things done incorrectly, please tell me about them.

**Comment by johnmidavis** [comment]
The 'files changed' is showing another pull https://github.com/publiclab/plots2/pull/5477 which has been merged into master. I thought I had faithfully followed   [the git flow](https://publiclab.org/notes/warren/11-22-2017/use-git-and-github-to-contribute-and-improve-public-lab-software). The command line [diff across forks](https://stackoverflow.com/questions/4927519/diff-a-git-fork) show only the one small change in config/locales/en.yml. I don't know quite how to fix this but I am looking.

**Comment by johnmidavis** [comment]
Thanks @ananyaarun .  I should pay better attention to @plotsbot in the future, who told me exactly how to fix my merge.

**Comment by gauravano** [comment]
Hi @johnmidavis, there's a merge conflict here, please resolve it. Thanks!

**Comment by gauravano** [comment]
Also, you followed all the necessary steps(or best practices we listed in the checklist). Good job!

**Comment by gauravano** [comment]
Okay, I resolved the conflict this time. Thanks!

**Comment by gauravano** [comment]
Merged :tada: :balloon: :+1:

**Pull request merged**
