### PR TITLE
fix return_to anomaly

### LINKED ISSUE #4898: Return_to anomaly
image
Can you see the url and the link to join to even though the user is logged in?
Rails is working as it should but from users point of view there is an error.

### PR DESCRIPTION
**Pull request by Anjalizi**
Fixes #4898 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Now the **/login** page
r1

takes us to **/dashboard**
r2

Thanks!

### CODE REVIEW

**Comment by Anjalizi** [comment]
@SidharthBansal @gauravano i have made the necessary changes. it works for me locally though the checks do not pass. please review. thanks.

**Comment by Anjalizi** [comment]
@gauravano i think i have fixed it now. please check.

**Comment by Anjalizi** [comment]
sure I will. thanks. 
Also, codeclimate is repeatedly showing me the error "Avoid too much nesting of statements", how can I avoid that?

**Comment by jywarren** [comment]
CodeClimate is mostly a recommendation, so we can ignore minor issues.
Let's resolve that when you're otherwise ready, ok? Thank you!

**Comment by Anjalizi** [comment]
@gauravano i did as you directed. please check.

**Comment by jywarren** [comment]
Hi, this is super! Do you think we might write a test to protect this behavior in the future? Would you have any interest in trying to add a test to confirm this -- you could, if interested, work from this example integration test:

https://github.com/publiclab/plots2/blob/f8e7cab2a82f7f5bd31ee1c2cf0872aa17a6c1a7/test/integration/login_flow_test.rb#L33-L41

**Comment by Anjalizi** [comment]
i have never written a test before. would take me time to figure it out. till then you could open it as a new issue. @jywarren

**Comment by jywarren** [comment]
OK, that sounds good!!!

**Pull request merged**
