### PR TITLE
Lines of header improved #7312

### LINKED ISSUE #7312: Line on header at width 768px
### Please describe the problem (or idea)
1. A line is showing on the header of grey colour which is not looking good in terms of UI and need to be fixed.
2. The menu icon is difficult to see so the border width should be more.
> What did you expect to see that you didn't?
The line should not be there.
Icon menu should be clearly seen.
### Please show us where to look

https://publiclab.org/
On the header at width of the device = 768px.

### What's your PublicLab.org username?
nitin_tech
> This can help us diagnose the issue: 
Need to check the UI at width equals to 768 px and need to fix
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders
Screenshot from 2020-01-20 20-57-19

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes #7312
Line on header at width 768px #7312
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 
Screenshot from 2020-01-20 20-57-38

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@cesswairimu  can you approve and merge this pr please?

**Comment by NitinBhasneria** [comment]
@nstjean Can you have a look at this and review this, please.

**Comment by nstjean** [comment]
I do see the slight line in the header. However I'm not sure adjusting the media query is the best tactic. It is better to figure out what's causing that line to appear, it could be something that pops up again down the road.

**Comment by NitinBhasneria** [comment]
> I do see the slight line in the header. However I'm not sure adjusting the media query is the best tactic. It is better to figure out what's causing that line to appear, it could be something that pops up again down the road.

I think the media query is the reason because the navbar of width less then 576 and greater then 576px both appears at 576px due to this the line appears

**Comment by nstjean** [comment]
But we don't know what CSS is causing the line. A media query doesn't do anything by itself, it just tells the browser which CSS to use. If there's a line then something is creating it.

**Comment by NitinBhasneria** [comment]
Then I will look at it once more.

**Comment by SidharthBansal** [comment]
Ping me when done!
Thanks all

**Comment by NitinBhasneria** [comment]
@nstjean I got the CSS error and I have removed the unnecessary CSS. Review it @SidharthBansal @cesswairimu @nstjean

**Comment by cesswairimu** [comment]
Sorry @NitinBhasneria I now understand the line you were talking about. Can we get a screenshot after this change? Also please rebase so that travis can pass. Thanks

**Comment by NitinBhasneria** [comment]
Here is the screenshot, also I am done with rebasing.
Screenshot from 2020-03-02 23-48-45

**Comment by cesswairimu** [comment]
Great, thanks

**Comment by cesswairimu** [comment]
Thanks @NitinBhasneria

**Pull request merged**
