### PR TITLE
iFrame button for embedding map.

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Continued from https://github.com/publiclab/leaflet-environmental-layers/issues/274 .

@jywarren , review please 😄

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Screenshot 2019-11-28 at 10 47 14 PM
Screenshot 2019-11-28 at 10 47 20 PM
Screenshot 2019-11-28 at 10 47 31 PM

**Comment by sagarpreet-chadha** [comment]
NEW URL :

http://localhost:3000/map/Unearthing,eonetFiresLayer,odorreport,asian#lat=30.600093873550072&lon=52.03125&zoom=3

**Comment by sagarpreet-chadha** [comment]
@jywarren , the tests failing are unrelated to this PR.

**Comment by sagarpreet-chadha** [comment]
aha passing now 🎉  ! @jywarren , let's merge this if it looks fine to you.

**Comment by jywarren** [comment]
This is AWESOME!!! Thanks Sagarpreet!!!!

**Pull request merged**
