### PR TITLE
Put yarn before precompile step

### PR DESCRIPTION
**Pull request by icarito**
Also added precompile to test-container make sequence.
We were having issues precompiling assets before they were installed.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Whoa what is sentry saying?

**Comment by icarito** [comment]
It was me! On Sentry one could link a Github issue so I linked it! :+1:

**Comment by jywarren** [comment]
Noting that one of the Travis had this error:

```
ReferenceError: Can't find variable: module
  # debounce/index.self-2be1b4e8a2646f67c540dc7cb7fc167f9b219fdddbc64e8ebd753202b1389385.js:71 -- global code
.Faked response to: /likes/node/1/create
```

but not the other???

**Comment by jywarren** [comment]
Aha! I think i got it. debounce is trying to be `require()` compatible. we need a `module` variable. fixing...

**Pull request merged**
