### PR TITLE
Testing: Post Replies with Multiple Comment Boxes Open

### PR DESCRIPTION
**Pull request by noi5e**
I have another PR open at #8879, merge that one first!

- Made new fixtures for question, wiki, note -- each with multiple comments on them.
  - I tried adding comments to the existing fixtures, but the assertions for earlier tests throw errors because Capybara expects to find just one element, but finds several.
  - It seemed a lot easier to just make new fixtures, rather than rewrite the old tests... For now.
- Because of the new fixtures, I also had to alter the assertions in unit tests that count questions, wikis, notes. We ran into this problem before (I'll rewrite these someday!)

(This PR is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

### CODE REVIEW

**Comment by jywarren** [comment]
> It seemed a lot easier to just make new fixtures, rather than rewrite the old tests... For now.

Another way to do it is to add the comments within the test, using `@node.add_comment(...)` - esp if they're only going to be used in these tests. But, it's a stylistic or maintainability-related preference and your approach sounds great! This looks good and we can wait on #8879 before merging this but it looks super to me!!

**Review by jywarren — APPROVED** [review]

**Comment by noi5e** [comment]
Thank you @jywarren, I didn't know about `@node.add_comment(...)`, will definitely look into that. 

I'll make some time toward the end of the internship to clean up all the tests and fixtures I'm making, will probably use that if these fixtures don't get much use.

**Comment by noi5e** [comment]
Oh yeah this is ready to merge too!

**Comment by jywarren** [comment]
Yay!!!

**Pull request merged**
