### PR TITLE
Move i18n library to bower dependencies (fix #771)

### LINKED ISSUE #771: move I18N library into bower dependency
This library is included directly in the codebase:

https://github.com/publiclab/plots2/blob/master/public/javascripts/i18n.js

...but we should instead include it in our `bower.json` file and include it in our application.js file: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/application.js

then `bower update` will include it.

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
#771

**Comment by jywarren** [comment]
You can keep pushing new commits here to rerun the tests. If you're having trouble with your local js setup, this can work.

**Comment by ryzokuken** [comment]
@jywarren All I wanted was to run the tests, and now that they've passed, I suppose everything must be working properly (the Jasmine tests passing must've meant that the i18n-js module is working, right?)

Please review this PR and give feedback on this so that I can jump to my next task :D 
Thanks

**Comment by jywarren** [comment]
But I don't think there's a test that actually uses the i18n js lib, is
there? Maybe im wrong...

**Comment by ryzokuken** [comment]
@jywarren Here's the log from Travis:

```
Running jasmine tests headlessly
Running `"/usr/local/bin/phantomjs" "" "/usr/local/lib/ruby/gems/2.1.0/gems/jasmine-rails-0.14.1/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///app/tmp/jasmine/runner.html?spec="`
Running: file:///app/tmp/jasmine/runner.html?spec=
Starting...
Finished
-----------------
0 specs, 0 failures in 0.002s.
```

The tests were completely nondescript, so I have no idea if it tested against that particular library.

How do you propose I proceed from here? Run the server locally and try using the app in such a way that it makes use of the library, perhaps?

**Comment by jywarren** [comment]
Hi, an example test is here: https://github.com/publiclab/plots2/blob/master/spec/javascripts/tagging_spec.js#L21-L34

I believe that the TravisCI results mean that the JS tests are actually not being run, which is troublesome, and I'll look into that. 

I think we should better document this stuff, but for starters, the JavaScript translations themselves are stored here: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/application/i18n/translations.js

And code using them is present here: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dashboard.js#L94-L102

So, in the test, you could ensure that:

```js
expect(I18n.t('js.dashboard.selected_updates')).toBe('Selected updates')
```

Which should work in default, which is english. I'm not sure how the language switching logic works to test German as well, but that'd be a start. 

If you're interested, I'd also be happy to accept a PR (or an addition to this one) adding this information to the README section on internationalization!

Thanks.

**Comment by jywarren** [comment]
It's odd -- look at this test run for contrast: https://travis-ci.org/publiclab/plots2/builds/158112155

**Comment by jywarren** [comment]
And oddly, I see that that test was run with this set of tasks: https://github.com/ananyo2012/plots2/blob/fed38e36bfcc2b2652ed6a28ee1fc1a82c7ad1f0/lib/tasks/test.rake which isn't that different from the current setup. I'm not really sure what's wrong here.

**Comment by jywarren** [comment]
It actually seems that Travis is getting a ways further than I am, and that it's actually trying to run the tests, but that it doesn't seem to actually find any. I think we may need to look back at the builds history to see when they stopped getting run: https://travis-ci.org/publiclab/plots2/builds/

**Comment by jywarren** [comment]
It's between build 302 and build 288... getting closer!

**Comment by jywarren** [comment]
OK, between build 290 and 291, the Jasmine tests stopped running:

* 291: https://travis-ci.org/publiclab/plots2/builds/167442889
* 290: https://travis-ci.org/publiclab/plots2/builds/167431923

Here's the commit that did it. I'm going to comment it out for now and open a PR for that. Once that's done, any new tests you add should run on Jasmine. Sorry for the trouble!

**Comment by jywarren** [comment]
See #943

**Comment by jywarren** [comment]
That was merged -- and now in master!

**Comment by ryzokuken** [comment]
@jywarren So I need to update my master and rebase my own changes on top of it, right?

**Comment by ryzokuken** [comment]
@jywarren Here's the new log:

```
Running jasmine tests headlessly
Running `"/usr/local/bin/phantomjs" "" "/usr/local/lib/ruby/gems/2.1.0/gems/jasmine-rails-0.14.1/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///app/tmp/jasmine/runner.html?spec="`
Running: file:///app/tmp/jasmine/runner.html?spec=
Starting...
Second post First post
Third post First post
Third post Second post
rows
0 
1 
2 
Faked response to: /likes/node/1/create
4
Finished
-----------------
4 specs, 0 failures in 0.049s.
```

I suppose this mean that the test did run and passed. Are we good to go?

**Comment by ryzokuken** [comment]
@jywarren On my local computer (I had to install another operating system) the mysql issue has resurfaced.

**Comment by ryzokuken** [comment]
@jywarren Herein lies the problem: https://github.com/publiclab/plots2/blob/master/config/database.yml.example

uses mysql2 for all purposes, including testing and development. I suppose sqlite3 should've been used in it's place, right?

**Comment by jywarren** [comment]
Yes - sqlite3 is preferred (and simpler) for development use. And yes, your
JS tests look to be running properly, great!

**Comment by ryzokuken** [comment]
@jywarren I suppose that means the PR works as intended :) 

Also, if sqlite3 should be used for development, shouldn't we make some changes?

**Comment by jywarren** [comment]
Hi -- what kinds of changes? Sqlite is mentioned in the README and there's a default database supplied with the app, do you think we could be more clear about it? 

As for the PR, I'd like to see an additional interface test to verify that the library is working; could you add one with:

```js
expect(I18n.t('js.dashboard.selected_updates')).toBe('Selected updates')
```

as I mentioned above? Thanks!

**Comment by ryzokuken** [comment]
@jywarren shouldn't https://github.com/publiclab/plots2/blob/master/config/database.yml.example use sqlite3 for development and testing atleast? 

Currenntly, it is:

```
# Warning: The contents of the database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  username: plots
  password: plots
  database: plots
  host: db
  encoding: utf8
  pool: 5
  timeout: 5000

# This database will be used by default when running `passenger start`
development:
  adapter: mysql2
  username: 
  password: 
  encoding: utf8
  database: publiclaboratory

production:
  adapter: mysql2
  username: 
  password: 
  encoding: utf8
database: publiclaboratory
```

I think this is perhaps the reason my computer always attempts to shoot up mysql2 and fails. What do you think?

**Comment by jywarren** [comment]
Yes, we can change that -- we'd provided a separate
database.yml.sqlite.example, but I see no reason why we shouldn't make the
distinction in the base example as well. If you want to add that to this
PR, I'm fine with it, thanks!

**Comment by ryzokuken** [comment]
@jywarren Thanks for that, I'm sorry I copied the wrong database.yml

**Comment by ryzokuken** [comment]
@jywarren Also, shouldn't bower use `vendor/` instead of 'public/lib/'?

**Comment by jywarren** [comment]
Ideally yes, however, some assets we rely upon (images used by Bootstrap, I
believe) need to be world-readable, so that's part of the complexity of
bower/Rails asset pipeline integration. Good eye, however!

**Comment by ryzokuken** [comment]
@jywarren Tried testing it manually, worked perfectly (I don't know German that well, but it did translate the page) 
screenshot from 2016-11-04 08 36 45

Also, you mentioned something about adding an integration test: 
```
expect(I18n.t('js.dashboard.selected_updates')).toBe('Selected updates')
```
Rails has a test for i18n, but looking at it, it looks like a JavaScript test. 

The `spec/javascripts/` directory has three subdirectories, `fixtures/`, `helpers/` and `support/` are the three tests outside the integration tests? Do I make a new spec, or do I add this test to `plots2_spec.js`? 

Thanks

**Comment by jywarren** [comment]
Hi, yes, I do mean a javascript test, thanks! Yes, you can add it to
plots2_spec.js, that works fine. Super!

**Comment by ryzokuken** [comment]
@jywarren I did add the test, please look into it if possible

**Comment by ryzokuken** [comment]
@jywarren The build threw an error but while installing stuff, so could we redo the tests?

**Comment by jywarren** [comment]
No worries I restarted the build.

**Comment by ryzokuken** [comment]
Thanks :) The build number is 420 though. :stuck_out_tongue: :sunglasses:

**Comment by jywarren** [comment]
Passed and merged, thanks!!!

**Comment by ryzokuken** [comment]
:D Will need to look for another help-wanted bug now.

**Pull request merged**
