### PR TITLE
comment now added when giving a note a barnstar so the giver gets emails

### PR DESCRIPTION
**Pull request by chongr**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added (no changes)

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!
screenshot from 2016-07-02 16-10-13

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, this looks super! @ebarry can you offer input -- it says now "Awards a barnstar to X" -- is that adequate wording or would you like something else?

I'd like to write a test for this, and can do this unless @chongr is interested in doing so? It would go in here: https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb

And you can test for a comment being added using:

```ruby
assert_difference 'DrupalComment.count' do
  # wrap the action in this block
end
```

There are other ways to test, but this is pretty simple.

**Comment by chongr** [comment]
Thanks for the response, I'll wait for input from @ebarry for the message content, but in the meantime I will write a test for this.

**Comment by ebarry** [comment]
How about "Wowzers! [PersonX] awarded you a barnstar for your contribution [title of research note]! Barnstars are a symbol of community appreciation, read more at publiclab.org/wiki/barnstars."

**Comment by jywarren** [comment]
I think we can excerpt [title of research note] since it'll be a comment on
the note itself. But the text should be in italic (markdown) or it'll look
like the person wrote it themselves. And we could cut [, read more at xxxx]
and just link the word Barnstars to that wiki page?

**Comment by dhenrygithub** [comment]
Aw shucks, I thought you were going to give "Wowzers" the Gong Show gong.
;) Explaining and linking to barnstars is a nice touch.

**Comment by chongr** [comment]
I was thinking of combining all your suggestions and making the message something like "current_user awards a barnstar(as link) to author for their awesome contribution to research_notes_title".  Also is there anyway I can test this without having to run the server (such as through a test to see what the comment text becomes)? Thanks!

**Comment by jywarren** [comment]
Thanks! I think we could leave out "to research_notes_title" as we're on the page with the note itself, so that would be redundant. 

Yes, I think you could add: 

```ruby
assert_equal "Expected comment text here, with #{inline_variable_substitution}", DrupalComment.last.body
```

Good idea!

**Comment by chongr** [comment]
The problem I am running into is the fact the barnstar function in the tag controller uses current_user, so when I post to that route in the test I get an error of `undefined method `drupal_user' for nil:NilClass` since current_user is not defined in the test, so I was wondering how you got around this in tests since it seems like you don't have rspec or another library to mock stub functions?

**Comment by chongr** [comment]
ah ok I figured it out haha, let me know if you the message works.  Thanks for the help!

**Comment by jywarren** [comment]
Oh super! Sorry we are doing an event this weekend, the Barnraising, and I
may not get to this until Monday. Thanks a million and looking forward to
checking it out!

**Comment by jywarren** [comment]
Super, running tests now and then I'll merge. One request for future pull requests -- if you could rebase your changes on top of the latest master (even doing it again after adding new changes) that's really helpful, as we like to keep a linear commit history. Thanks again, Ryan, this is great!

**Comment by jywarren** [comment]
Done! Oh, and one more thing -- it can be much easier to rebase on top of the latest master if you keep your changes in a named feature branch, like "barnstar-comments" or something. That way, when you want to rebase, you can commit your changes, check out your master branch, run `git pull` from the main publiclab/plots2 master, then check out your named branch again and run `git rebase master` -- and it'll play your changes on top of the most recent version of the codebase. That makes merging much easier for me, too! 

There's more about this "flow" here: https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks again!

**Comment by jywarren** [comment]
Closing as I've merged manually in https://github.com/publiclab/plots2/commit/9ccfae8c322103296cad3a19a76a20868f89deeb

**Pull request closed without merging**
