### PR TITLE
Updated wiki/_wikis

### LINKED ISSUE #6704: Change function t to translation in wiki/_wikis
We need to change the function t to translation in lines 10,12,13,14,15 of wiki/_wikis

### PR DESCRIPTION
**Pull request by Abhinav1299**
Fixes #6704 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Abhinav1299** [comment]
@publiclab/reviewers

**Comment by Abhinav1299** [comment]
@SidharthBansal Please review :)

**Comment by SidharthBansal** [comment]
Superb!Please provide screenshots for the above changes.

**Comment by Abhinav1299** [comment]
@SidharthBansal

**Comment by SidharthBansal** [comment]
Sorry for the misunderstanding. I am asking a screenshot of the localhost
Thanks
Sidharth

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
