### PR TITLE
Redundancy removal from login

### LINKED ISSUE #4456: Combine app/views/user_sessions/_new.html.erb and new.html.erb
These two files are very similar except for the form url. Please keep new.html.erb but have it render _new.html.erb as a partial. 

We can figure out which url to use possibly by passing a local into the partial.

### PR DESCRIPTION
**Pull request by Dsxv**
Fixes #4456  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Thanks.
Please paste all 5 gifs here.

**Comment by Dsxv** [comment]
Sign up  with modal :
user_session

Login with modal :
user_session1

Login with `/login` page : 
login_user-session

Sign up with `/signup` page : 
sign_in_usersession

Edit profile via login page : 
edit_prof_user-session
Thanks!

**Comment by SidharthBansal** [comment]
Please have descriptive title for the PR.

**Comment by Dsxv** [comment]
@SidharthBansal 
Should I remove the partial and keep a single file named `new.html.erb` and change the locations where partials are called ?

**Comment by SidharthBansal** [comment]
It will better to have title
"Redundancy removal from login"

**Comment by SidharthBansal** [comment]
Yes correct

**Comment by SidharthBansal** [comment]
@Dsxv please untrack unwanted unrelated changes to this issue.

**Comment by Dsxv** [comment]
@SidharthBansal I am not sure how to do that. Can you please help me ? 
Thanks!

**Comment by SidharthBansal** [comment]
You can either open up new PR OR rebase your changes.

**Comment by Dsxv** [comment]
I also think opening up a new PR would be better as this one has become a bit complex , I'll do it now Thanks !

**Comment by Dsxv** [comment]
moved to : https://github.com/publiclab/plots2/pull/4605

**Pull request closed without merging**
