### PR TITLE
Moved test to integration test files

### LINKED ISSUE #3428: Move an integration test to integration test folder which is present in Unit test file [PART 2]
Currently some integration tests are present in unit test folder, so we can move them from this folder and add them to integration test folder.
https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/test/unit/comment_test.rb#L321

### PR DESCRIPTION
**Pull request by CodeSarthak**
Fixes #3428 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by CodeSarthak** [comment]
@publiclab/reviewers Please review. @jywarren @SidharthBansal @namangupta01

**Comment by namangupta01** [comment]
Nice work!

**Comment by jywarren** [comment]
Hi! i updated the title -- descriptive titles are very helpful! I'm worried someone else may have resolved this, but even if not, it looks like it needs a rebase, since we recently merged in some new changes to the master branch.

So, you need to rebase your work on top of the latest master. You can do that by following the process outlined here, but you may be able to skip step 2 if your master is still in sync with publiclab's master: https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

Thanks!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
