### PR TITLE
Adding ellipsis on cards in people's page

### LINKED ISSUE #5707: UI Improvements Planning Issue : People Section
## Description
The basic Card UI of people section is already on halfway.
Now the further improvements are left.
As we were told during proposal that we should start off with easier ones first. And they should be given beginning of time in timeline. So we will start off with people section first which is the easiest.
The final UI for the people's page : 

Screen Shot 2019-05-19 at 2 41 35 AM

@gautamig54 We will add checklists here
#### card ui of users 
- [x] Vertical to horizontal cards @CleverFool77 
- [x] Add tags on cards @CleverFool77 
- [x] Add ellipsis which contains the user details as shown in the design @gautamig54 

#### location
- [x] Add user's location. @gautamig54 

#### search by
- [ ] Add search by various places option below maps. 

#### others
 - [ ] Make the map sticky. 
 - [x] position map on the top instead of bottom, in the mobile view @CleverFool77 
 - [x] Fix overflow of tags @CleverFool77

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5707  (<=== Add issue number here)

Screen Shot 2019-05-30 at 3 53 37 AM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
@jywarren @CleverFool77 @gauravano Kindly review this PR. Thanks!

**Comment by gauravano** [comment]
Hi @gautamig54, I like the change you did about the position of the menu button `...`, but let's hear from @jywarren about it. 

Are the menu items links? Also, how about adding the read more button as proposed in the original design? Thanks!

**Comment by gautamig54** [comment]
Hi @gauravano!
No, the menu items are not links. The "Ban" button is only visible to admins and moderators, which allows them to ban any member. Also, I did not add the read more button as it will direct the user to the member's profile page which is happening by clicking on the member's name also. 
Should I add it then?

**Comment by gauravano** [comment]
yes, please add the read-more button as we know that user can see profile by clicking on the name but I guess for making things crystal clear for everyone, let's add it.

Please make menu items links too. Thanks!

**Comment by jywarren** [comment]
Hi all! Actually, perhaps we should establish what should be hidden under
the ellipsis menu in the Style Guide discussion:
https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab

One of the priorities is a very minimal page layout, so we may be able to
achieve that by hiding even the "spam" buttons under the ellipsis menu. And
perhaps we can refine the design to indicate that the name and photo are
links, and note this in the style guide as well to have a clean but
understandable look! I realize the style guide doesn't specify what it
actually the link to the profile -- great point, thanks folks!

**Comment by gautamig54** [comment]
Sure @jywarren! Let's discuss about what all should be inside ellipsis and what on the cards.

**Comment by gautamig54** [comment]
@gauravano I have added the links and the read more button. Kindly review!

Screen Shot 2019-06-05 at 2 16 02 AM

Also, as @jywarren mentioned about the few styles for the ellipses. I'll update them after discussion and then this PR will be ready for merge. Thanks!

**Comment by jywarren** [comment]
This looks great; maybe `Read more` could be `See full profile`?

Could we make the lines that are /not/ links greyed out? I think there is a `disabled` style in Bootstrap for this. 

And i suppose we should leave all text in the popover the same size -- what do you think?

My preference is for the ellipses to be in the upper right corner of the box, and to be horizontal. But happy to discuss more. I'll reply in the style guide too.

**Comment by gautamig54** [comment]
Thanks @jywarren! I'll make the suggested changes.

**Comment by jywarren** [comment]
OK, i built on some of @CleverFool77's suggestions to try to make a guideline for buttons and `...` menus; it's in the style guide now and interested to hear what you think!

image

**Comment by jywarren** [comment]
Thanks both of you!!!

**Comment by gautamig54** [comment]
I have made the suggested changes. How does this look?

Screen Shot 2019-06-06 at 11 51 31 PM

Screen Shot 2019-06-06 at 11 52 19 PM

**Comment by jywarren** [comment]
Super nice! I guess I'd go for maybe 4-5px more margin around the circular
image. But it's just tiny details -- shall we merge and we can tweak later?
(This is my former designer self showing :-P)

**Comment by jywarren** [comment]
The menu shows on click, not hover, right? I'll add this detail to the
style guide too. Thanks!!

**Comment by CleverFool77** [comment]
> I have made the suggested changes. How does this look?
> 
> Screen Shot 2019-06-06 at 11 51 31 PM
> 
> Screen Shot 2019-06-06 at 11 52 19 PM

Looks Great tbh :+1:

**Comment by gautamig54** [comment]
Yes @jywarren the menu shows up on click. 
I think this is ready for merge. Thank you!

**Comment by CleverFool77** [comment]
Hi @gautamig54 The popup would be like this only ? It's over both the cards. How about we do some `float` to one direction. So it would be in over the card whose data it's showing only.

**Comment by gautamig54** [comment]
@CleverFool77 I don't think it is much of a problem as of now. We can modify the minor tweaks here and there later.

**Comment by jywarren** [comment]
Hooray! And please check out the latest screenshots system -- now all PRs will generate screenshots; I'm expanding the list of pages that get screenshots in a series of PRs, like this one: https://github.com/publiclab/plots2/pull/5880

**Comment by jywarren** [comment]
This will be really great for not needing to upload screenshots as much. We can also automate performing JavaScript actions and then uploading screenshots; see #5316 for more on this, for screenshotting things like hovers, clicks, modals. Wheeeee!!! 🚀

**Pull request merged**
