### PR TITLE
Cloud9 fix

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

#479 is solved with this PR. Also added test.sqlite to gitignore.

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren Please review the PR. I have made the cloud9 fixes. I have also added test.sqlite file in gitignore.

**Comment by ananyo2012** [comment]
@jywarren I am facing a **rvm** related problem in cloud9 deployment. The `rvm 2.1.2` command won't work in the install_cloudnine.sh script. I am getting this error

`RVM is not a function, selecting rubies with 'rvm use ...' will not work.`

Though when I run the same command in the terminal it works fine and running the installation script runs the deployment.

I have looked up for the solutions and found it is happening because the console is not running as login shell. Solutions for gnome terminal is given [here](https://rvm.io/integration/gnome-terminal). But such a thing is not possible in cloud9(I guess so).

**Comment by jywarren** [comment]
Hi, @ananyo2012 - good troubleshooting, this is a common issue with RVM. I believe it's possible that we could solve it by running:

    [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

This is what RVM puts into your `~/.profile` and seems relevant. Can you try this? Is this a concern before I merge this PR?

I also see that you haven't checked "passes tests" -- does it? I look for that to be checked before merging in PRs, so please check it if they do, even if this code isn't something that'd be expected to break tests. Thanks!

**Comment by jywarren** [comment]
Also, I don't believe we should add `rake db:migrate` -- it's preferred to simply commit a freshly `rake db:setup`'ed database file with the latest schema. I can do this or you can, but please do remove the `migrate` command unless you have a reason to think it'd be better. Thanks!

**Comment by ananyo2012** [comment]
@jywarren Actually I think `rake db:migrate` should be added since there may be migrations that will be added over course of time and the current sqlite database file doesn't contain all of them. I simply face this issue while running the installation script now as there is the last migration that is not present in the sqlite database file and I am prompted to run that migration while starting the server. For first timers I think it would be best if they would see the deployment running just after the running the installation script. So what do you think now? Should I keep that line?

**Comment by ananyo2012** [comment]
@jywarren Fixed the problem of setting Ruby version using `source $(rvm 2.1.2 do rvm env --path)`. But for setting the ruby version after the script runs we have to run the script as `source ./install_cloudnine.sh` or `. ./install_cloudnine.sh` since it is an environment variable. Otherwise it won't persist after running the script and the server won't start. I have include it in the Readme instructions.

Optionally we could use the line `source "/usr/local/rvm/scripts/rvm"` since cloud9 has rvm installed in its root. `source "$HOME/.rvm/scripts/rvm"` won't work as rvm is not installed in cloud9  home. This also involves running the script in the same manner as stated above.

**Comment by ananyo2012** [comment]
@jywarren I have also checked the tests passing. Actually the tests were not passing in the sqlite database. So I was waiting for your fixes before I checked. Now they will pass as expected.

**Comment by jywarren** [comment]
I think that we could include the `rake db:migrate` as a backup, but that we should always include an up-to-date version of development.sqlite.example. But to prove your point, I forgot to do that in the sqlite test fixes I made -- so I'll do that now, and maybe we should add a checklist item to the pull request template for updating it? 

Anyhow, for your pull request, I'd like to see 

1. commits squashed
2. rebase over latest master
3. some explanation in the README for the option of `source` or not, because if we simply say "or", some folks may be confused as to why there is an option. Since you've included the `source` in the `install_cloudnine.sh` file, can't we skip it in the README?

Thanks, I appreciate the extra effort in this PR.

**Comment by ananyo2012** [comment]
@jywarren Ok I will remove the `source` line from the README. Using `source` or `.` gives the same result. Since I have already mentioned unless we run the script with `source` or `.` the ruby version won't persist after execution of the script. The `source` included in the `install_cloudnine.sh` file ensures that the environment is set while running the script but it doesn't persist after the execution ends. If you run `ruby -v` after running the script(when you haven't use `source` or `.` to run the script) you will get the default ruby version.

**Comment by ananyo2012** [comment]
@jywarren Ok then I will remove the `rake db:migrate` line from the script. Yes that is a better idea. We can tell people to include changes in development.sqlite.example when there is a new migration. But again there are always chances that there are additional changes in the database file while the user is working in the development environment and since it is a binary file we can't really see the changes made. So it is best for the maintainer to make such changes. What are your thoughts on it?

**Comment by jywarren** [comment]
Ah, i didn't realize that it was `source` or `.` - i read too quickly and thought it was just `source` or nothing. Thanks for the clarification!

I think we just have to be rigorous about keeping the development.sqlite.example file up to date. I'll add it as a step in the PR template to remind ourselves. 

Great, I think this can be merged on Friday.

**Pull request merged**
