### PR TITLE
Stats per tag

### LINKED ISSUE #4140: Stats on a per-tag basis
Implement display of stats on a per-tag basis, via standard model functions with unit tests
* [ ] Move tag graphs to an individual page(this page) #4646 
* [ ] Display stats for each tag

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #4140 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
tag_line
tag_graph1
tag_bar

**Comment by cesswairimu** [comment]
tag
Here is a gif

**Comment by jywarren** [comment]
Wow this looks amazing! I have a slight preference for the line graph but defer to @ebarry on other input! Does it need a more specific graph title maybe?

**Comment by cesswairimu** [comment]
@jywarren I agree the graph title is quite vague I will find a better name.
What else would be want to have in this page besides the graph? Thanks

**Comment by jywarren** [comment]
Maybe eventually a time selector, but that may be quite a bit of work...
What do you think?

**Comment by cesswairimu** [comment]
Yeah that would be nice. Let me see if it can be a quick implementation if not I will create a follow up ticket.

**Comment by jywarren** [comment]
Wow cess! Awesome! This generates a range url?

**Comment by jywarren** [comment]
We could have multiple types of data graphed on this period for this tag,
like notes, wikis, comments, maybe? Would we be able to duplicate or extend
the same functions from the general stats pages?

**Comment by cesswairimu** [comment]
Thanks @jywarren its not really a range, the graph is plotted against an year so you select a date and the graph is plotted an year back from the date you select.  I will look into separating the types of data. As for the stats page I am working on it and I am conflicted if we should have one stacked graph or different graphs as it is. I will paste some screenshots on the PR so I can get your input.

**Comment by cesswairimu** [comment]
screencapture-localhost-3000-tag-suscipit-stats-2019-01-25-04_17_32

**Comment by sagarpreet-chadha** [comment]
This looks rad :tada: :smile:  !!!

**Comment by ebarry** [comment]
Looking soooooooooo soooooooooo good! If we used the line style graph (by removing the solid green fill), would we be better able to see the multiple types of data (like notes, wikis, comments) stacked in a single graph?

This would be an incredible perfect feature to then re-use on the main Stats page. 
Thanks Cess!!!!! 💃

**Comment by cesswairimu** [comment]
Thanks @sagarpreet-chadha  @ebarry

**Comment by cesswairimu** [comment]
liz
@ebarry you meant a graph like this?

**Comment by ebarry** [comment]
Yes that looks really cool @cesswairimu ! Do you think it conveys the "pulse" of content by type? I think it's maybe a little hard to read, but overall a big step forward in an integrated "at-a-glance" look at activity on the site. What do you think?

**Comment by cesswairimu** [comment]
Yeah I agree its kinda hard to read. @publiclab/reviewers any ideas how I can improve the readability of the above graph?

**Comment by jywarren** [comment]
I wonder if it's for some reason going back to zero between values? Or are
those actually periods with no activity?

I think it's possible if we reduce the average slope of the graph by
padding with some extra space above (or setting a minimum vertical span of,
say, 15 units?) then the jumpiness will be smoothed out a bit and it may be
easier to read.

**Comment by cesswairimu** [comment]
Yeah @jywarren the periods with zeros have no activity. I wonder maybe my values do not display what it will look like on the site..Do we have a test environment with data where we can deploy see how that looks like and rollback?

**Comment by jywarren** [comment]
Yes you should be able to push to unstable and just announce it in the
chatroom so others know... Then it'll build at http://unstable.publiclab.org
within 10m. We just coordinate because there's only one server we all
share.

On Jan 29, 2019 2:26 PM, "Cess" <notifications@github.com> wrote:

Yeah @jywarren <https://github.com/jywarren> the periods with zeros have no
activity. I wonder maybe my values do not display what it will look like on
the site..Do we have a test environment with data where we can deploy see
how that looks like and rollback?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/pull/4693#issuecomment-458630046>, or mute
the thread

**Comment by cesswairimu** [comment]
Cool thanks

**Comment by cesswairimu** [comment]
@ebarry  @jywarren  I could not get the line graphs to look better. 
Thoughts on this :point_down: 
tagg
:thinking:

**Comment by ebarry** [comment]
They are looking really cool @cesswairimu ! i am not quite sure what to do, maybe slight transparency, so let me punt to @jywarren and his design eye.

**Comment by jywarren** [comment]
Hi! If these are stacked, let's say so in the labeling, but otherwise let's
just go with this and we can refine later! Thanks, Cess!

**Comment by cesswairimu** [comment]
@jywarren cool, I have just added the stack note
stacked-note

**Comment by jywarren** [comment]
great, ready to merge then? Thanks!

**Comment by cesswairimu** [comment]
Yes its ready

**Pull request merged**
