### PR TITLE
Changed value of Finder in constants.rb

### LINKED ISSUE #8947: External links containing an `@` at symbol currently parse as public lab usernames
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [constants.rb](https://github.com/publiclab/plots2/blob/main/config/initializers/constants.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
module Callouts
- FINDER = /([^`\w]|^)\@([\w-]+)/
+ FINDER = /([^`\w]|^)(?<!\/)\@([\w-]+)\b(?!\/)/
  HASHTAG = /(\s)\#([:a-zA-Z0-9_-]+)/
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by frappelatte28**
Fixes #8947 

* [x ] PR is descriptively titled 📑 and links the original issue above 🔗
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by frappelatte28** [comment]
@cesswairimu Kindly review the changes :-)

**Comment by cesswairimu** [comment]
Thanks @frappelatte28 for working on this..so the failing test is this
```
Progress: | FAIL["test_graph", #<Minitest::Reporters::Suite:0x000055ca495503e8 @name="TagSelectionTest">, 0.4641045020000547]
 test_graph#TagSelectionTest (0.46s)
        Expected: 16
          Actual: 20
        test/unit/tag_selection_test.rb:14:in `block in <class:TagSelectionTest>'
        ```
which doesn't seem to be related to this...I will reopen the PR see if that solves it.

**Comment by cesswairimu** [comment]
That did the trick @gauravahlawat81 kindly review this. Thanks

**Review by gauravahlawat81 — APPROVED** [review]

**Comment by gauravahlawat81** [comment]
@cesswairimu This can be merged now, all the tests have passed and the changes looks good to me. Thanks @frappelatte28 for working on this!

**Review by cesswairimu — APPROVED** [review]

**Comment by cesswairimu** [comment]
Thanks @gauravahlawat81  :tada:

**Comment by gauravahlawat81** [comment]
Thanks @cesswairimu , and congratulations @frappelatte28 for getting your first PR merged. Welcome to Public lab :100:

**Comment by gauravahlawat81** [comment]
@cesswairimu We can close #7675 as well.

**Comment by frappelatte28** [comment]
Thank you @cesswairimu @gauravahlawat81 for your support!

**Comment by cesswairimu** [comment]
yeah @gauravahlawat81 just waiting to test on https://stable.publiclab.org/

**Pull request merged**
