### PR TITLE
removed error in styles for note erb

### LINKED ISSUE #4113: Recenter 'Read more' button for note previews
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem
The 'notes' previews across the site are aligned right instead of centered! 
[https://publiclab.org/search/notes/balloon](https://publiclab.org/search/notes/balloon)

screen shot 2018-12-03 at 10 47 06 pm

## Solution
This is a pretty easy one -- let's remove the CSS declarations from the notes HTML file that are overwriting the button's previously centered alignment:

1) 
Delete line 69 (and line 70, which is overwritten by the declaration directly under it anyway):
https://github.com/publiclab/plots2/blob/c204b268cd8dc1a713aeae15cc4222f0099d4d73/app/views/notes/_notes.html.erb#L66-L72

2) 
Delete the entire inline `style` attribute.
https://github.com/publiclab/plots2/blob/c204b268cd8dc1a713aeae15cc4222f0099d4d73/app/views/notes/_notes.html.erb#L51

Thanks!!

## Steps to Fix
 
- [x] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [x] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [x] Create a new feature branch with a unique name descriptive to the issue
- [x] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [x] Reference this issue in the pull request body
- [x] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬  Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by uzorjchibuzor**
Fixes #4113 

I have made the changes as described on the issues page. 
Kindly merge if certified.

Thanks.

### CODE REVIEW

**Comment by uzorjchibuzor** [comment]
@publiclab/reviewers Travis CI test is failing and I have no idea why..

**Comment by uzorjchibuzor** [comment]
I removed them and now codeclimate is not passing

**Comment by SidharthBansal** [comment]
I mean you need to untrack the changes for these two files. you don't have to delete them

**Comment by uzorjchibuzor** [comment]
@SidharthBansal Thanks for your help. all tests are passing now.

**Comment by SidharthBansal** [comment]
You missed 
image
Please do the necessary changes and ping me

**Comment by uzorjchibuzor** [comment]
Grab

this is the state of the code on the branch that I am trying to merge, I have removed the lines as instructed.

**Comment by SidharthBansal** [comment]
Thanks for the screenshot. They were really helpful.
Merging this issue as soon as travis passes.

**Comment by SidharthBansal** [comment]
@uzorjchibuzor thanks for contributing at Public Labs. You can work on other tasks to help us.

**Pull request merged**
