### PR TITLE
Move sidebar to right side of research note and wiki pages #3091

### LINKED ISSUE #3091: Move sidebar to right side of research note and wiki pages
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

We had a great UI analysis by Siyuan a while back, suggesting the sidebar should be on the right side:

> we could look at some of what Siyuan suggested re: moving sidebar to the right side (see the last comment): https://publiclab.org/notes/siyuan/06-12-2017/a-questions-page-to-encourage-discussions-through-better-ux

The templates are here, starting with notes:

https://github.com/publiclab/plots2/blob/5c94fe54e1a3fed19fb0de2c910d5478f03d2391/app/views/notes/show.html.erb#L3

Wiki pages:

https://github.com/publiclab/plots2/blob/5c94fe54e1a3fed19fb0de2c910d5478f03d2391/app/views/wiki/show.html.erb#L28-L40

Question page: 

https://github.com/publiclab/plots2/blob/5c94fe54e1a3fed19fb0de2c910d5478f03d2391/app/views/questions/show.html.erb#L7

Watch out for the proper nesting of the Bootstrap `col-md-md` class divs! https://getbootstrap.com/docs/3.3/

Once we complete this, we can replace the "related content" in the "related" sidebar with a simpler tag listing, like this:

https://user-images.githubusercontent.com/24359/37424326-8ff2290c-2796-11e8-9620-54c6d5667d62.png

So let's break that out as its own issue once this is done. 

Any help appreciated!

### PR DESCRIPTION
**Pull request by derek-allen**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!
-------

This PR fixes #3091, which is about moving the sidebar on research notes, questions, and wiki pages.

### CODE REVIEW

**Comment by derek-allen** [comment]
@publiclab/reviewers aside from creating a PR from master (sorry, still getting used to non-SVN style source control), I think this is good to go!

**Comment by derek-allen** [comment]
@jywarren also tagging issue author because I'm not sure if the reviewer team mention worked.

**Comment by jywarren** [comment]
Oh wow this is great! Would you be able to share a screenshot? Thanks!!

**Comment by derek-allen** [comment]
Absolutely! And while in the process of taking the screenshots, I found out i accidentally broke the sidebar:none powertag :/ went ahead and fixed that, so now it should reflect the original behavior, where the sidebar:none took president over the other sidebar tags.
**Note**
note-sidebar
**Question**
question-sidebar
**Wiki - Feature**
wiki-sidebar-featured
**Wiki - Related**
wiki-sidebar-related
**Wiki - None**
wiki-sidebar-none

**Comment by jywarren** [comment]
This looks great. Restarting the tests as there's an unrelated issue stopping them. 

Once we complete this, we can replace the "related content" in the "related" sidebar with a simpler tag listing, like this:



We'd love your help with that too if you're interested! Thanks so much!

**Comment by jywarren** [comment]
For reference, the tagging template is here: https://github.com/publiclab/plots2/blob/master/app/views/tag/_tagging.html.erb

**Comment by jywarren** [comment]
OK! This looks perfect, thank you so much! We'd love to have more help if you're interested!

**Comment by derek-allen** [comment]
@jywarren yeah I'm interested! Is there an issue for this?

**Comment by jywarren** [comment]
Not yet but if you want to open it I can help tag it appropriately. Go
ahead, thank you!!!

**Pull request merged**
