### PR TITLE
Last created blog post shown instead of last updated, fixes #2443

### LINKED ISSUE #2443: Leading dashboard blog post is an old one for some reason
### Please describe the problem (or idea)

Our dashboard at http://publiclab.org/dashboard shows a single blog post

It's supposed to be the most recent one from http://publiclab.org/blog

> What did you expect to see that you didn't?

Instead, it's an older post -- https://publiclab.org/notes/Shannon/07-06-2016/public-lab-code-of-conduct

Not sure why! The code to grab this post (that's apparently going wrong) is here:

https://github.com/publiclab/plots2/blob/5ac99163ee3a3ce47a52b3a9ccff0e0bf89aa6a2/app/controllers/home_controller.rb#L91

That goes to these lines, which haven't been touched in months -- so it seems unlikely to be the culprit! 

https://github.com/publiclab/plots2/blame/master/app/models/tag.rb#L85-L104

I'm actually a bit mystified at this. The dashboard ought to show the very first post from https://publiclab.org/blog

****

Aha! That page was recently updated. It looks like we use updating as the ordering. We should switch it to creation for this particular instance:

```
2.3.4 :003 > n.updated_at
 => 2018-03-06 15:24:47 +0000 
```

### PR DESCRIPTION
**Pull request by 500swapnil**
fixes #2443 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this looks good, but for wikis, I think we do want to sort by last updated. Could we add some logic that makes notes sort by created, but wikis by last updated?

Thanks! This is great!!!

**Comment by 500swapnil** [comment]
dash

@jywarren Which wiki page list do you mean exactly? On the dashboard, as you can see, the last created blog post is shown and below it, the notes are sorted by creation time. The wikis in the sidebar shows sorted edits. And on the /wiki/ page, it's already in last updated order.

**Comment by 500swapnil** [comment]
@jywarren One thing we could do is, just show the last updated wikis once each on the sidebar and not repeat for every edit. Would make it more clean.

**Comment by jywarren** [comment]
Oh gosh, i missed this! Sorry!!!

I think that the generic method `find_nodes_by_type` may just be used in different places, and across the board, it makes sense to display wikis by last updated, but other notes by last created. Could we insert an `orderBy = ____` variable before line 98, and then use it on line 101 in the `.order(orderBy)` line below? That way we can say:

```ruby
orderBy = (type == 'page') ? 'node_revisions.timestamp DESC' : 'created DESC'
```

**Comment by 500swapnil** [comment]
Great! That worked. Sorry I missed this!!

**Pull request merged**
