### PR TITLE
Fix follow button bug on tags

### LINKED ISSUE #6570: Clicking the 'follow' button on a tag does not change it to 'unfollow'
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

On clicking the follow button, the button text does not change. Only after the page is refreshed the button changes from 'follow' to 'unfollow'.
publiclab org_tags_page=2 (1)

> What did you expect to see that you didn't?

I expected the button to show the text 'unfollow' instead of 'follow' when clicked.
publiclab org_tags_page=2 (2)

### Please show us where to look

https://publiclab.org/tags?page=2

### What's your PublicLab.org username?
christie_reni
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome, version 77.0.3865.120 (Official Build) (64-bit),  windows10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by crisner**
Fixes #6570 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @crisner this is really nice..maybe we can do a toggle or an ajax for that so that we don't need to refresh after following/unfollowing...what do u think? Thanks

**Comment by crisner** [comment]
Thank you @cesswairimu. Do you mean that we should display the unfollow button without a manual refresh? If so, then wouldn't the 'following' link become inaccessible to the user?

**Comment by crisner** [comment]
Right now if we move away to another page and hit the back browser button the displayed page is not updated and the follow button remains unchanged unless we manually refresh the page. I'll try implementing ajax to see if this can be avoided. Thank you!

**Comment by crisner** [comment]
@cesswairimu I've come up with a couple of UI behaviors. Please take a look at the gifs below and let me know which one we can proceed with.

Here the state is saved so that the information persists:
behaviorwithstate

Here the url is replaced simulating a redirect.
With setTimeout:
behaviorwithredirect

Without setTimeout:
sanssettimeout

**Comment by crisner** [comment]
@cesswairimu Attached below is the gif from the latest commit. Please review. Thank you.
currentBehavior

**Comment by crisner** [comment]
@cesswairimu Could you please offer some advice with this? I went to https://stable.publiclab.org/ to test this as suggested in the 'welcome bot' message but the [tags](https://stable.publiclab.org/tags) page is not displaying any tags for me to test the work. Have attached the screenshot below. Thanks!
stable publiclab org_tags

**Comment by cesswairimu** [comment]
Hi @crisner oh yeah, sorry, seems like the database was reset recently and I guess data has not been generated yet...I created one tag https://stable.publiclab.org/tags check and see if you can see the changes...Thanks

**Comment by crisner** [comment]
Thank you @cesswairimu ! 😃  I can now see the changes I made.

**Comment by cesswairimu** [comment]
Awesome :+1:

**Pull request merged**
