### PR TITLE
Redesigns /tool page

### PR DESCRIPTION
**Pull request by carolineh101**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
I just wanted to apologize for the delay in merging this week; we're still working through a very frustrating merge process in #810 for the new search service, and are holding off on merges until we solve that. We are making some progress and hope to resume regular merges in the next few days. 

Thanks for your patience!

By the way, we've been highlighting new contributors' work on our twitter account (twitter.com/publiclab) and were curious if you wanted us to mention your own handle or if it's OK to link to @carolineh101 (your profile)? Thanks.

**Comment by carolineh101** [comment]
No problem!  And yes, it's ok to link to my Github profile (I don't have a Twitter).

**Comment by jywarren** [comment]
We tweeted it! https://twitter.com/PublicLab/status/778239629380157440

Also, the `solr` branch is passing all tests and we anticipate pulling it in today, and then your work. Thanks again.

**Comment by jywarren** [comment]
I added a conditional so this only displays on the tools page (`if params[:action] == "tools"`) but otherwise this was great and I manually rebased and merged in 37f25039594afa20ecdaca79787313c46955073d. Thanks! We hope to get this out on the live site on Thursday!

**Comment by jywarren** [comment]
Anyhow, we're very grateful for your help on this one -- it's really going to help drive interest in our new Activities system -- we've been writing a lot about it here: https://publiclab.org/tag/activity-grids

There are a lot of issues open related to the new system: https://github.com/publiclab/plots2/milestone/5

Actually, one in particular is kind of like a list-form version of the /tools page, so perhaps you'd be interested: https://github.com/publiclab/plots2/issues/827

We're not sure yet, but are thinking that a series of different shortened activity grids could be displayed on this page, organized by topic, in such a way as to help people choose activities to get involved in. It needs some sort of larger design thinking on it, though, and there are plenty of others that are more concrete and fleshed out.

Thanks!

**Comment by carolineh101** [comment]
Glad to help on this issue, and thanks for featuring me on the Public Lab Twitter!  I'll take a look at the other issues.

**Comment by jywarren** [comment]
Caroline - I actually forget if I mentioned to you, but just a note, the new tool page went online and it looks GREAT!!! https://publiclab.org/tools

and other staff are really excited about it. Thanks again!

**Comment by carolineh101** [comment]
Thanks for letting me know!  Glad to help.  I just started school a couple of weeks ago, so I'm quite a bit busier, but I hope to contribute more when I have time!

**Comment by jywarren** [comment]
Sounds great -- good luck with school!

**Pull request closed without merging**
