### PR TITLE
Inserted a partial template to display topic cards on tags search results page

### LINKED ISSUE #8530: Display topic cards on tags search results page
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/search/tags.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/search/tags.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

The results page for tag based search is rendering tags poorly -- they're just raw Ruby objects: https://publiclab.org/search/tags/one

image

Let's reformat the template a bit and insert a partial template to display them as we do on https://publiclab.org/tags

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

(Noting that the diff is a little hard to read, so [here is a link](https://github.com/publiclab/plots2/blob/608aaf03b6977ca2764c58c613063564e7a48914/app/views/search/tags.html.erb) to what the file would look like AFTER these changes are applied!)

```diff
@@ -1,30 +1,29 @@
-<%= render :partial => "search/nav" , :locals => { :section => "search-tags" }%>
+<div class="col-md-2">
+  <%= render partial: "search/nav" , locals: { section: "search-tags" } %>
+</div>
 
-<div class="container">
-  <% if @tags.present? %>
-    <div class="container">
-      <h2> Results for <%= @search_criteria.query %></h2>
-      <p> <strong> Searched notes that contain the tag</strong></p>
-      <hr>
+<div class="col-md-10">
+  <div class="container">
+    <% if @tags.present? %>
+      <div class="container">
+        <h2> Results for <%= @search_criteria.query %></h2>
+        <p> <strong> Searched notes that contain the tag</strong></p>
+        <hr>
 
-      <div class="row">
-        <% @tags.each do |tag| %>
-          <p><a href=<%= "#{tag}" %>><%= tag %></a></p>
+        <div class="row">
+          <%= render partial: "tag/topicCard" %>
+        </div>
+      </div>
+      <div class="text-center">
+        <% if @pagy %>
+          <%= raw  pagy_bootstrap_nav @pagy %>
+        <% else %>
+          <%= will_paginate @tags, renderer: WillPaginate::ActionView::BootstrapLinkRenderer unless @unpaginated %></div>
         <% end %>
       </div>
-    </div>
-  <% else %>
-    <h4>
-      No results found for <%= params[:query] %> :-(
-      <p> Searched notes that contain the tag</p>
-      </br>
-      Try searching <a href="/search">for another topic</a> or looking for our items tagged with <a href="/tag/<%= params[:query] %>"><%= params[:query] %></a>
-    </h4>
-  <% end %>
+    <% else %>
+     <p>No results found for "<b><%= params[:query] %></b>" :-(</p>
+     <p>Try searching for another topic or looking for our items tagged with <a href="/tag/<%= params[:query] %>"><%= params[:query] %></a>
+    <% end %>
+  </div>
 </div>
-<div class="text-center">
-  <% if @pagy %>
-    <%= raw  pagy_bootstrap_nav @pagy %>
-  <% else %>
-  <%= will_paginate @tags, renderer: WillPaginate::ActionView::BootstrapLinkRenderer unless @unpaginated %></div>
-  <% end %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by dldisha**
Fixes #8530  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
Screenshot from 2020-10-12 04-02-44

* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by Tlazypanda — COMMENTED** [review]
Hey @dldisha seems like there is a merge conflict here :sweat_smile: can you please resolve that? https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github This might be of help :v:

**Comment by dldisha** [comment]
@Tlazypanda Thank you for reviewing and yeah that link was helpful. Please check if there's anything that I'm missing out, thank you.

**Comment by jywarren** [comment]
This looks super! There's just one small thing - not sure what it causing it, but see how the tag cards are quite narrow? Compare it to:


https://publiclab.org/tags

image

Do you think there's a small change we could make to ensure that column is wider? Thank you!!!

**Comment by jywarren** [comment]
Whoa, actually, i believe you, perhaps mistakenly? Solved this in https://github.com/publiclab/plots2/pull/8532/files already! Can you confirm? 

If so, we should soon see it in the test server at https://stable.publiclab.org/search/tags/test

-- indeed, it just published there!!!

image

So, i believe you're already done! It's possible you created both PRs from the same git branch state, instead of building both off of the `main` branch, separately. That's OK, but just watch out next time in case you get other projects tangled up! These look great though. Thank you!!!

**Comment by dldisha** [comment]
Ohh yaa, my bad, thanks for pointing out. Will keep that in my mind from the next time :)

**Pull request closed without merging**
