### PR TITLE
changed the drop-down follow btn text color to white

### LINKED ISSUE #7813: Change button text color to white
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

Here, the Follow button in the drop-down has black text but it should be white.

66944281-e008cd80-f01a-11e9-891d-bfdf1c7c88a5

**Note** that this only occurs when the user is logged out.

It's viewable on pages like: https://publiclab.org/tag/dust

## Solution

Where to find the relevant lines of code: https://github.com/publiclab/plots2/blob/dc6a61f60761eb5731f4e1d27f25ee572352ba44/app/views/tag/_tags_popover.html.erb#L18

What to change them to:

1. Add an id="subscription" to the `a` tag linked above, so that it has the same `margin-top` as the when the user is logged in.

2. Change "btn-white" at the end of the class to "fa-white"

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by DerekChristy**
Fixes #7813  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by DerekChristy** [comment]
Fixed issue #7813

**Comment by sashadev-sky** [comment]
thanks! can you attach a screenshot of these changes run locally in your browser?

**Comment by sashadev-sky** [comment]
@DerekChristy did you close this on accident?

**Comment by DerekChristy** [comment]
yes

**Comment by DerekChristy** [comment]
> thanks! can you attach a screenshot of these changes run locally in your browser?

I have not set up the ruby environment. 
I have attached the screenshot of the line changed tough. Is it fine?
fix

**Comment by sashadev-sky** [comment]
@DerekChristy half the battle of contributing to a rails repo is to get the initial setup complete - that's what we create these issues for. Have you tried setting up / need any help?

**Comment by sashadev-sky** [comment]
Also some feedback on your PR, please link the original issue you are completing so that your PR will be linked there. I fixed this for you in your PR body above so you can see what I mean 👍

**Comment by DerekChristy** [comment]
@sashadev-sky I have an issue setting up the local environment.
> bundle install
ERROR: There was an error while trying to write to
`/home/derekchristy/Code/plots2/.bundle/config`. It is likely that you need to
grant write permissions for that path.

**Comment by DerekChristy** [comment]
> thanks! can you attach a screenshot of these changes run locally in your browser?

Screenshot from 2020-04-16 05-33-12

**Comment by DerekChristy** [comment]
@sashadev-sky What's the next step? I'm not authorized to merge this pull request. Show I close the pr now?

**Comment by sashadev-sky** [comment]
@DerekChristy leave it open and someone from @publiclab/maintainers can merge :)

**Pull request merged**
