### PR TITLE
update on user.rb

### PR DESCRIPTION
**Pull request by phyleria**
Fixes #9857  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by TildaDares** [comment]
> Fixes #0 (<=== Add issue number here)

@phyleria Can you add the issue number in your comment above? Thanks!

**Comment by phyleria** [comment]
Hey @TildaDares it says current head differs from pull request most recent head

**Comment by TildaDares** [comment]
@phyleria That's not an issue.

**Comment by TildaDares** [comment]
@phyleria You added the PR number not the issue number.

**Review by TildaDares — APPROVED** [review]
LGTM🎉

**Comment by phyleria** [comment]
Ok, thank you @TildaDares what should I do from here then

**Comment by phyleria** [comment]
oh sorry, how do I know the issue number

**Comment by TildaDares** [comment]
@phyleria The issue number is on the top of the issue where you were assigned.

**Comment by RuthNjeri** [comment]
Thanks @phyleria 🎉  This is the issue number https://github.com/publiclab/plots2/issues/9796

**Pull request merged**
