### PR TITLE
fixes Issue 2646 - made changes to cloud9 install instructions

### PR DESCRIPTION
**Pull request by rtrunkhill**
fixed `rvm use 2.3.7` and added `gem install bundler` step

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] code is in uniquely-named feature branch and has no merge conflicts
* [x ] PR is descriptively titled
* [ x] PR body includes `fixes #0000`-style reference to original issue #
* [x ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by rtrunkhill** [comment]
huh?  this passed my local `rake test` and i made very minor changes to an sh file.  Im wicked confused by this eror

**Comment by jywarren** [comment]
A test issue unrelated to your work was just fixed. I'm going to close and reopen to let it run again!

**Comment by jywarren** [comment]
Sorry! Hopefully this works. If not, you may need to rebase it... ask for help if you get stuck! Thank you!

**Comment by jywarren** [comment]
Super, this worked well!

**Pull request merged**
