### PR TITLE
Added login modal for answers at /questions

### LINKED ISSUE #4157: Link Login Modal to Answers page on /questions
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Answers page on /questions
[publiclab.org/questions/](url)
`app/views/questions/_answers.html.erb`

screenshot 55

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #4157 
@publiclab/reviewers Please review..

`Basic flow`
answer on question

`Alternative flow`
answer on question login errorgif

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Please claim the task.
Awesome well done.

**Comment by oorjitchowdhary** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5618364249538560/
Please approve.. Thanks a lot

**Comment by SidharthBansal** [comment]
>>Correct login 
Use better words like ``Basic flow`` for corrected login.
>>login error
Use ``Alternative Flow``.

**Comment by SidharthBansal** [comment]
Approved

**Comment by oorjitchowdhary** [comment]
> > > Correct login
> > > Use better words like `Basic flow` for corrected login.
> > > login error
> > > Use `Alternative Flow`.

Changed it.. Thanks a lot for teaching me these..

**Comment by SidharthBansal** [comment]
I approved your pr.
I am going for a sleep. You can push the remaining work. I will review it
after 6 hours or may be in between. I will review it collectively. I hope
you will be able to do the stuff in my absence.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Yess sure.. take your time.. Sleep tight.. Gn 💤

**Comment by SidharthBansal** [comment]
Merging them now.

**Pull request merged**
