### PR TITLE
Check if duplicate trends error crops up in 5.7 mysql version 

### PR DESCRIPTION
**Pull request by ValentinaTironi**
Fixes #4266 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by ValentinaTironi** [comment]
@jywarren @milaaraujo Ready! waiting now

**Comment by ValentinaTironi** [comment]
OK, the error is not about the test. It says that can found `mysql:5.7`
screen shot 2018-12-12 at 2 34 01 am
Maybe I'm doing something wrong. What do you think? @jywarren @milaaraujo

**Comment by milaaraujo** [comment]
I think you should use `mysql:5.7` not `mariadb:5.7`.

**Comment by ValentinaTironi** [comment]
Let's check now

**Comment by milaaraujo** [comment]
>The command "docker-compose exec web bash -c "rake db:setup"" failed and exited with 1 during .

@jywarren, do you know what is happening here? :/

**Comment by jywarren** [comment]
Hmm...

```
Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused")
Couldn't create 'plots' database. Please check your configuration.
rake aborted!
Mysql2::Error::ConnectionError: Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused")
```

**Comment by jywarren** [comment]
Just digging into this a little bit -- comparing:

* 
 https://github.com/publiclab/plots2/blob/be761117a1991fb01875bf5fc40c0f23a91d4937/containers/docker-compose-testing.yml
* https://github.com/publiclab/plots2/blob/3a6287c4694c073ab0a6cc5ac8f5e5df7b6ba728/docker-compose.yml

and looking at the blame view: https://github.com/publiclab/plots2/blame/be761117a1991fb01875bf5fc40c0f23a91d4937/containers/docker-compose-testing.yml

Not sure what's going on!

**Comment by jywarren** [comment]
Hmm, maybe we need `mysql-5.7-trusty` as in this comment: https://github.com/travis-ci/travis-ci/issues/5122#issuecomment-355403249

Obscure, but the last comment about that was Jan 2018, and more docs here: https://docs.travis-ci.com/user/database-setup/#mysql-57

It says we may need these in `travis.yml`: 

```
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - libmysqlclient-dev
      - libmysqlclient20
      - mysql-community-client
      - mysql-common
      - mysql-community-server
```

**Comment by jywarren** [comment]
One thing to consider, although it may add considerable complexity, might be to have Travis run all tests in 3 different builds, one for `mysql`, one for `mariadb` and one for `sqlite` -- this is described here: https://docs.travis-ci.com/user/database-setup/#multiple-database-builds

**Comment by jywarren** [comment]
Let's think about that after resolving this issue.

**Comment by jywarren** [comment]
Hmm, this still shows `Mysql2::Error::ConnectionError: Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused")`

@icarito no rush here but do you have any idea why it won't find mysql or connect to it? We're looking to see if our latest code still runs on mysql 5.7, and considering expanding Travis tests to account for this too. Thanks!

**Comment by milaaraujo** [comment]
>We're looking to see if our latest code still runs on mysql 5.7, and considering expanding Travis tests to account for this too. 

Not sure if it is a good idea to merge a change like this, because right now a lot of tests fail running mysql.

**Comment by jywarren** [comment]
That's fine -we don't have to merge this anytime soon, but I think it's something we might pursue longer-term to keep our code flexible and compatible. We could think of it as a long-term maintenance goal; I'll open an issue accordingly to track this. 

Thanks for your help, everyone! I do think it'd get us one step closer if anyone could figure out what's going on with the connection to MySQL, and we could then build on that to re-achieve MySQL compatibility and run our tests on both db platforms, sometime in the future. Let's leave this open in the meantime.

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab
cc @jywarren @gauravano

**Pull request closed without merging**
