### PR TITLE
Create a config for WelcomeBot #2709

### PR DESCRIPTION
**Pull request by emv**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by emv** [comment]
@publiclab/reviewers Code Climate has one issue, in app/models/user.rb, which I didn't edit. Is there something I need to do?

**Comment by jywarren** [comment]
No, we're not sure why it complains about unrelated code... i'll approve that now!

I'm not yet sure how to enable WelcomeBot to read this! Will have to look into it later today or tomorrow. Great start, many thanks!!!

**Comment by emv** [comment]
Awesome, thank you! This is a really cool project. 😁

**Comment by jywarren** [comment]
The install info is here -- i think we just have to merge this and try it out! 

https://github.com/organizations/publiclab/settings/installations/60577

**Comment by jywarren** [comment]
Want to try opening a new issue and see? Wow, it just worked!!!

**Comment by jywarren** [comment]
@publiclab/reviewers check out WelcomeBot -- just added by @emv !!!

**Comment by Gauravano** [comment]
Looking great!

**Comment by stefannibrasil** [comment]
Awesome!

**Pull request merged**
