### PR TITLE
Wrote tests for exclusion of autoreplies to comment-by-email to address issue #5842

### LINKED ISSUE #5842: Email auto replies are auto-posting to research notes.
### This has happened before, but email auto replies are showing up as comment responses in threads on the site. 

This particular email posted about 70 times, and contains information about the poster's personal schedule as well as contact information for another person. 

AutoReplyPost

Can we disable auto comments in comment by email?

### PR DESCRIPTION
**Pull request by enviro3**
Fixes #5842 https://github.com/publiclab/plots2/issues/5842

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ x] code is in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by jywarren** [comment]
Oh wow! This looks really good, but it seems to be based on an old branch. Could you try rebasing it over the latest `master` branch to address the conflicts here? And if you need any help with that, here are some resources, and we're happy to help out! 

https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

Thanks!

**Comment by enviro3** [comment]
Thanks @jywarren , can you help me in identifying what is the latest master commit I should be rebasing with?

**Comment by jywarren** [comment]
Sure - you should be able to do:

```
git checkout master
git pull https://github.com/publiclab/plots2.git master
git checkout email_auto_replies_attemptfix#1
git rebase master
```

This may cause some conflicts, which you may need to work through one by one. Before starting everything, you could run `git branch email_auto_replies_backup` just in case, to keep an unrebased copy of your code. 

I hope that helps!

**Comment by jywarren** [comment]
OK, I tried using `git cherry-pick` to isolate just your commits, and opened a new PR at https://github.com/publiclab/plots2/pull/6289 - take a look! If that passes, great! But even if not we can work from there. If you like you can pull from that branch and then force push here to get a clean new PR that you can keep pushing to. 

Sorry this took me so long to get back to you on! We're really excited for the fixes you've worked on here. Thanks a ton.

**Comment by jywarren** [comment]
Solved in #6289!

**Pull request closed without merging**
