### PR TITLE
Added is_verified column to users with default value false

### LINKED ISSUE #3849: Add is_verified to user model with default value False
Subpart of #3798

You have to add `is_verified` to the user model. That field will signify that user's email is not verified. This field will default to "False".

### PR DESCRIPTION
**Pull request by shubhscoder**
Fixes #3849

1. Added is_verified column to users to with default value false

Thanks!

### CODE REVIEW

**Comment by shubhscoder** [comment]
@Radhikadua123 I am deleting the previous PR and as you said I have made this PR for #3849 
Now I will start working on #3848 
I am thinking of using the following method:

1. Add a column to the users table to store the unique token that is generated for the user.
2. Implement a function generate_token(user,expiry_time) that will generate a randomized token for the user. This function also stores the generated token in the database.
3.  Implement a function validate_token(user,token) that will validate the token and also clear it from the database as the link would be a one time link. This function will also update the is_verified field for the user.

What I am not getting is how are we using the expiry time?

**Comment by shubhscoder** [comment]
Also, I need some help on finding out why did the test fail and what can be done to fix it. Thanking you in advance.

**Comment by Radhikadua123** [comment]
@shubhscoder The approach which you are following, needs saving token into the db. But it would be better if we don't save token in db at all. To know how to implement that up, you can check out approach 2 on this comment https://github.com/publiclab/plots2/issues/3522#issuecomment-433109387

Do let me know in case you have any doubts regarding that approach. 

About the failing test, @jywarren can you please help us out ? I'm not much aware of the environment, but shouldn't the travis CI delete db before running `rake db:setup` ?

**Comment by shubhscoder** [comment]
Okay so we can use the second approach. It won't require the addition of one more column. We will have to use some gem to get the encryption and decryption done.

**Comment by Radhikadua123** [comment]
@shubhscoder Encryption/Decryption was added in https://github.com/publiclab/plots2/pull/3801

**Comment by Radhikadua123** [comment]
Deferred to https://github.com/publiclab/plots2/pull/3907

**Comment by Radhikadua123** [comment]
I saw that you removed these changes from #3907 

That's a good practice to make atomic changes in the PR. 

So, I'm reopening this PR.

**Comment by Radhikadua123** [comment]
@jywarren Since I'm new to rails, I'm inexperienced with db changes. Though the column addition definition seems fine to me.

Can you please review this PR ? 

Also will it cause down time during the time migration will be ran on the db ? Is that a concern for us ? Any idea ? Also may be @icarito knows about it.

**Comment by jywarren** [comment]
Hi, no, it won't create significant downtime, no worries! So, now you have to update the `/db/schema.rb.example` file to reflect the new changes (just those related to your updates) and this should build properly. 

Thanks!!!

**Pull request closed without merging**
