### PR TITLE
Remove requirement for mysql2 adapter when mysql database is not in use

### LINKED ISSUE #4936: "mysql2 is not part of bundle" error while running rails server
Hi!

I updated my local master, ran `bundle install` and got the below error on running `rails s`

mysql2_error

I also ran ` bundle install --without production mysql` after deleting Gemfile.lock but got same error. 

**Solution which worked for me:**

I added gem 'activerecord-mysql2-adapter' to the gemfile, deleted Gemfile.lock, ran `bundle install`, ran `rails s` and error gone. 

Here's a snippet from Gemfile 

gemfile

which states running ` bundle install --without production mysql` should not require need to include the activerecord-mysql2-adapter but it didn't worked. 

Any idea @jywarren @siaw23 @publiclab/reviewers @publiclab/plots2-reviewers?

@siddhishree has also reported the same error in the Gitter channel:
> I've been trying to setup local plots2 development environment while follwing https://github.com/publiclab/plots2#installation, and while on step 7 I face issue https://pastebin.com/AbL6a7Cw, I tried installing mysql2 on gem but no changes, I'm a bit inexperienced in ruby, so if anyone can help

### PR DESCRIPTION
**Pull request by madeofhuman**
Fixes #4936 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by madeofhuman** [comment]
@gauravano could you please review this, thank you.

**Comment by gauravano** [comment]
I tried the PR locally and it's resolving the error reported in https://github.com/publiclab/plots2/issues/4936. @siaw23 @icarito and @jywarren your review is essential here. Thanks!

**Comment by jywarren** [comment]
Super!!!

**Comment by jywarren** [comment]
Amazing, thank you!!!!

**Pull request merged**
