### PR TITLE
New vocabulary for plot2

### LINKED ISSUE #11117: Extend cz.yml file
I extended the file in `config/locales/cz.yml` to support the new language for PublicLab.org.

The file contains main key-value pairs (home-dashboard-sidebar) and is prepared for further contribution.

**Please describe the desired behavior.**
Describe the solution you'd like.

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

### PR DESCRIPTION
**Pull request by illyShelly**
Add new vocabulary to .yml file to support more languages.

Fixes #11117 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Review by cesswairimu — APPROVED** [review]
Fantastic :tada: thanks @illyShelly

**Comment by illyShelly** [comment]
Thank you @cesswairimu  I'll slowly continue on it 💯

**Comment by cesswairimu** [comment]
please let me know if/when its ready to be merged :). Thanks

**Comment by jywarren** [comment]
It took a lot of scrolling but here is the error!

https://github.com/publiclab/plots2/runs/6437218263?check_suite_focus=true#step:9:96

```
ERROR QuestionTest#test_posting_a_question (94.57s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find visible css ".alert-success"
            test/system/post_question_test.rb:66:in `block in <class:QuestionTest>'
```

I think this one is an intermittent one unrelated to your code which we can get past by restarting the test!

**Comment by jywarren** [comment]
Looks like it passed!! Is it ready for a final review?

**Comment by illyShelly** [comment]
@jywarren sorry, I missed your message. I will add some more to be able to 'launch' new language on the website. Size +/- the French translation. Thank you 🙂

**Pull request closed without merging**
