### PR TITLE
fix pluralization logic II

### LINKED ISSUE #6809: Fix pluralization logic II
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

image

The pluralization in the screenshot above is incorrect (ie. should be "1 person" not "1 people")

## Solution

This is a simple one -- lets find the relevant line of code first:

https://github.com/publiclab/plots2/blob/a5d3392c3d6f5f4daaa56d5a4431e1bc0de5c46c/app/views/tag/show/_header.html.erb#L44-L49

As you can see, this line has no conditional and people will always just be plural.

Let's correct this: - Rails gives us a really convenient way to resolve it through the [pluralize method](https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize).

Update both `div` elements to the following:

```ERB
 <div class="bottom-right"><%= pluralize(Tag.follower_count(params[:id]), 'person') %> discussing</div>
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by gireeshcse**
fix_pluralization_logic_II commit

Fixes #6809   (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gireeshcse** [comment]
Hi @sashadev-sky. I have followed the steps in the issue.It will be very helpful if you let me know any thing i have done wrong.
Thanks in advance.

**Comment by gireeshcse** [comment]
> Thanks for opening this pull request! This space is [protected by our Code of Conduct](https://publiclab.org/conduct) - and we're here to help.
> `Dangerbot` will test out your code and reply in a bit with some pointers and requests.
> Also please refer [here](https://github.com/publiclab/plots2/issues/3840) for installation help 
> There may be some errors, **but don't worry!** We'll work through them with you! 
> It would be great if you can tell us your Twitter handle so we can thank you properly?

My twitter handle is gireeshcse

**Comment by sashadev-sky** [comment]
@gireeshcse thanks for this pull request! 

If you were just looking for practice, this is perfect 👍but can't be merged because another contributor was already assigned (see the comments \ `assigned` label on issue). As mentioned in the issue itself we only let someone else take over if it has been abandoned (no communication for a week).

If that happens I will come back to merge this and let you know!

**Comment by gireeshcse** [comment]
@sashadev-sky Thanks for the info

**Comment by gireeshcse** [comment]
Thanks @sashadev-sky

**Comment by cesswairimu** [comment]
Great thanks all :tada:

**Pull request merged**
