### PR TITLE
Show default profile picture instead of grey circle on sign up page.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Fixes: #5373

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

## Screenshots
Screenshot from 2019-04-05 13-04-06

### CODE REVIEW

**Comment by CleverFool77** [comment]
LGTM :+1: @Anupam-dagar 

But it made me realise @gauravano @jywarren , We have lots of space below email. Isn't it ?

**Comment by Anupam-dagar** [comment]
@CleverFool77 Thanks for your review :smile:

**Comment by gauravano** [comment]
Yes @CleverFool77,  we should work for removing that space and if possible redesign of the modal? Thanks!

**Comment by gauravano** [comment]
Thanks @Anupam-dagar :tada: :balloon:

**Pull request merged**
