### PR TITLE
fix post views in small screens

### PR DESCRIPTION
**Pull request by Nimmyjv**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
@Nimmyjv is this PR related to #2397? Also it would be great if you post a screenshot of the webpage. And please remove the Gemfile.lock from the PR

**Comment by jywarren** [comment]
And thank you for your contribution!!! :+1:

**Comment by Nimmyjv** [comment]
PR related to issue #2397 Removed gemfile.lock. Will post the screenshot.

**Comment by jywarren** [comment]
Hi, @Nimmyjv -- this looks great, and I think no screenshot needed as it's pretty simple. But I did want to ask - do you think it's possible to, using JavaScript, make the extra information visible only when you click a `...` button? This could be done with, say (i think this'd work):

```js
<a class="hidden-lg hidden-md" href="javscript:$('node-extras').toggleClass('hidden-xs hidden-sm');">
  <i class="fa fa-ellipsis-h"></i>
</a>
```

This would show the extras 'button' only on small screens, and that button (if I wrote the code right... it might take some testing out) should toggle the hiding of the extras. 

We'd also have to add 'node-extras' as a class on this line:

```html
<span class="hidden-xs hidden-sm hidden-print">
```

What do you think of this? See how it might work? 

Also i don't know if you were able to try this out but you can test it by just narrowing and widening the browser window. Much easier than using a phone!

**Comment by SidharthBansal** [comment]
Hi @Nimmyjv ,do you need any help? We are here to help.

**Comment by Abhiramvv** [comment]
Hi..sorry for the late reply..i will try out this with JavaScript.

**Comment by Nimmyjv** [comment]
Sorry for the late reply..Will try out that with js.

**Comment by Gauravano** [comment]
No issue @Nimmyjv , please let us know if you need any help.Thanks !!!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR.
Thanks for contributing at Public Lab

**Pull request closed without merging**
