### PR TITLE
Amarachi nwokocha patch 1 1

### PR DESCRIPTION
**Pull request by amarachi-nwokocha**
Fixes #0000 (<=== https://github.com/publiclab/plots2/issues/6767)
my solution is https://github.com/publiclab/plots2/pull/8651/commits/d238e3d063d11ede82dde52c70d5b6c4223243c8
I added styles on line  47 to 49 in order to break the link and make the page more responsive 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hey @amarachi-nwokocha, thanks for opening this, could you please make the description to describe the issue you are solving. Also I see two pull requests for the same issue. Kindly combine the two into one pull request. Thanks

**Comment by amarachi-nwokocha** [comment]
hi Cess I've made the comment i don't know how to merge them so I closed one the open one is the one i want to merge

**Comment by cesswairimu** [comment]
@amarachi-nwokocha if you have all the change on one branch, sure feel free to close this one and open one that has all the changes. Thanks

**Comment by cesswairimu** [comment]
@amarachi-nwokocha , if you navigate here https://github.com/amarachi-nwokocha/plots2/tree/amarachi-nwokocha-patch-1-1 and edit each other file that you need to, commit, the commits will appear on this branch. You can do each file at a time until you have all the files edited. Makes sense? Ping me if you get stuck. Thanks

**Comment by cesswairimu** [comment]
Hey @amarachi-nwokocha, I understand you might be held up..but  if you ever get all the changes on one branch feel free to open a new PR. Closing this. Thanks

**Pull request closed without merging**
