### PR TITLE
Fix missing styling on profile comments page

### LINKED ISSUE #4174: Styling missing on 2nd page of comments on profile
This looks like the layout is being suppressed in the `user_controller`!

https://publiclab.org/profile/comments/423961?page=4

image

### PR DESCRIPTION
**Pull request by madeofhuman**
Fixes #4174 (<=== Add issue number here)

Before:
Screenshot 2019-03-15 at 3 17 36 AM

After:
_(as user)_
Screenshot 2019-03-15 at 3 17 09 AM

_(as moderator/admin)_
Screenshot 2019-03-15 at 2 25 30 AM
Screenshot 2019-03-15 at 3 18 40 AM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by madeofhuman** [comment]
@jywarren could you please review this and let me know if it's how it's supposed to function? Thanks.

**Comment by CleverFool77** [comment]
The UI looks good but maybe we could shift the icons in moderator in between :thinking: or for consistency let it remain aligned to left.

**Comment by madeofhuman** [comment]
> The UI looks good but maybe we could shift the icons in moderator in between 🤔 or for consistency let it remain aligned to left.

Yeah, those are some valid options, but I feel it would be better to maintain consistency across the site.

**Comment by madeofhuman** [comment]
Test passed! 🎆 🍾 🎉 

@jywarren, @gauravano could you please review this? Thank you.

**Comment by gauravano** [comment]
Will revisit here in an hour. Thanks @madeofhuman!

**Comment by gauravano** [comment]
Ok, I guess the issue was introduced in this PR - https://github.com/publiclab/plots2/pull/4740/files :sweat_smile: While fixing /comments. I forgot to check /profile/comments/1 :see_no_evil: 

@madeofhuman let me know if you need any help.

**Comment by madeofhuman** [comment]
Sure thing, @gauravano

**Comment by madeofhuman** [comment]
@gauravano I've fixed it. Kindly review and give feedback. Thanks.
Screenshot 2019-03-19 at 4 07 15 PM

**Comment by gauravano** [comment]
the comments on page 1 look good but on going to the page 2, the view is distorted, see -https://drive.google.com/open?id=1-AzUwWQ0xu8QMbNtm3x0f3iC4oMpZOBp

**Comment by madeofhuman** [comment]
Oops! Can you check again, @gauravano? I've pushed a fix for that. Thank you.

Screenshot 2019-03-21 at 12 41 12 AM

**Comment by gauravano** [comment]
Pushed on `unstable`

**Comment by gauravano** [comment]
Comments view is good at both places now - /comments and /profile/username?page=# but the user has to select comments tab whenever they change page. I think we can improve UX, maybe in another PR? 

@jywarren please review. Thanks!

**Comment by madeofhuman** [comment]
> Comments view is good at both places now - /comments and /profile/username?page=# but the user has to select comments tab whenever they change page. I think we can improve UX, maybe in another PR?
> 
> @jywarren please review. Thanks!

I noticed this behaviour on other tabs in other pages. I'm thinking, will it be a priority to fix this now given that we're going to revamp the UI soon?

**Comment by jywarren** [comment]
Agreed, the UI/UX could be improved in a new issue! Thanks!

**Pull request merged**
