### PR TITLE
Default_markers added in maps page

### LINKED ISSUE #3165: [Continued] Integrating Leaflet-environmental-library to /maps .
Continued from #3094 !

TO-DO : 

- [x] Restrict infinite scrolling and panning .

- [x]  Adding Hash .

- [x]  Integration .

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #3165 !

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Strange --- the default marker image was not getting loaded from bower-leaflet library . So currently default markers are there but image is not getting loaded .

**Comment by sagarpreet-chadha** [comment]
This PR explicitly gives URL of blue markers and resolves the issue .

SCREEN SHOT :  
screen shot 2018-08-02 at 8 57 05 pm

**Comment by jywarren** [comment]
i'll restart travis on that last one!

**Comment by jywarren** [comment]
Looks great! Thanks!

**Pull request merged**
