### PR TITLE
Refactor old `error_messages` usage and added errorMessage partial

### LINKED ISSUE #4622: Refactor old `error_messages` usage in form helpers
I found some very old code in #4575 which I removed, but realized that we still use the `f.error_messages` code in our form error templates; you can see it in all these search results:

https://github.com/publiclab/plots2/search?q=error_messages&unscoped_q=error_messages

Errors should instead be in format:

```ruby
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
```

I believe this will resolve https://github.com/publiclab/plots2/issues/4521 as well because the duplicate "email already taken" error will be better handled with a modern Rails error reporting approach, as in the docs here: 

https://guides.rubyonrails.org/active_record_validations.html#displaying-validation-errors-in-views

If it helps, see when the old plugin code was originally added here:

https://github.com/publiclab/plots2/commit/4f13238a4837356d3bbf4cfffd7d14a24e7e42dc

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #4622 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
@jywarren @cesswairimu I've created a partial to remove occurrences of `error_messages` from `app/views/features/edit.html.erb` and `app/views/features/new.html.erb`
If this PR is fine, I'll create first timer issues for the rest of the files. 
Thanks in advance!

**Comment by Manasa2850** [comment]
@jywarren @cesswairimu could you please review this? If this PR is fine, I'll create first timer issues for the rest of the files to use the partial. Thanks in advance!

**Comment by Uzay-G** [comment]
This seems good. Could you maybe take a screenshot of the error messages rendering correctly?

**Review by cesswairimu — CHANGES_REQUESTED** [review]
Hey @Manasa2850  thanks a lot for opening this...love the error partial, we could refactor all the other views after this is merged. I would like to pint out that we are planning to remove the dynamic gem and that is already done here https://github.com/publiclab/plots2/pull/4575/, you could merge this branch with yours and then we can start from there...what do you think?

**Comment by cesswairimu** [comment]
there are also a few files left, would you like to change those ones too?  Its also okay if you would like to handle only the features templates and I can create a breakout issue for that alone and you wouldn't need to worry about the PR I mentioned above...its totally up to you let me know what you feel would be best for you. Thanks again

**Comment by Manasa2850** [comment]
Hi @cesswairimu I thought of creating first timer issues for the refactoring in the remaining files. So I think we'll be able to remove the dynamic gem only after changes have been made in all those files.

**Comment by cesswairimu** [comment]
Great sounds good, let me create a issue we can link to this and have it merged..looks good from gitpod thanks

**Review by cesswairimu — APPROVED** [review]

**Comment by cesswairimu** [comment]
@Manasa2850 when you do create the ftos kindly link them to the main issue for organization. thanks @Uzay-G  for the review :tada:

**Comment by Manasa2850** [comment]
Sure I'll do that @cesswairimu. Thank you!

**Pull request merged**
