### PR TITLE
Fix map position to above in mobile responsiveness

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5707 part (<=== Add issue number here)

abovemap

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @jywarren After fixing the horizontal cards , we can go for this PR.
Thanks !!!

**Comment by jywarren** [comment]
awesome, ready for review/merge here? Thanks!!!

**Comment by CleverFool77** [comment]
Hi @jywarren This is ready for merge.
thanks !!!!

**Comment by jywarren** [comment]
Awesome!

**Pull request merged**
