### PR TITLE
Change redirect URL of spam marking action #2761

### LINKED ISSUE #2761: Change redirect URL of spam marking action
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/controllers/admin_controller.rb](https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -108,7 +108,7 @@ def mark_spam
         @node.author.ban
         AdminMailer.notify_moderators_of_spam(@node, current_user).deliver_now
         flash[:notice] = "Item marked as spam and author banned. You can undo this on the <a href='/spam'>spam moderation page</a>."
-        redirect_to '/dashboard'
+        redirect_to '/dashboard' + '?_=' + Time.now.to_i.to_s
       else
         flash[:notice] = "Item already marked as spam and author banned. You can undo this on the <a href='/spam'>spam moderation page</a>."
         redirect_to '/dashboard'
@@ -135,7 +135,7 @@ def mark_comment_spam
     else
       flash[:error] = 'Only moderators can moderate comments.'
     end
-    redirect_to '/dashboard'
+    redirect_to '/dashboard' + '?_=' + Time.now.to_i.to_s
   end
 
   def publish_comment
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by chanjess**
fixes #2761 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [✔️  ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️  ] code is in uniquely-named feature branch and has no merge conflicts
* [ ✔️ ] PR is descriptively titled
* [ ✔️ ] PR body includes `fixes #0000`-style reference to original issue #
* [✔️  ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oof! Haha - sorry, more errors than I thought! 

But see how each one is like:

`Expected “http://test.host/dashboard” to be === “http://test.host/dashboard?_=1528080114”.`

That's because our new change introduces these timestamps so that the browser cache gets cleared (the URL doesn't match any previous one so it really re-loads the page). So each of the tests that failed needs the timestamp added to the end of the redirected-to URL, similarly to how it's been added to the end of this one:

https://github.com/chanjess/plots2/blob/923092ab5fc8673cb2b8b77e6d1c913259463a33/test/functional/admin_controller_test.rb#L34

Make sense?

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by chanjess** [comment]
@jywarren sorry! been a little hectic, but I'll get to this by tomorrow or Saturday!

**Comment by chanjess** [comment]
@jywarren interesting how i got errors from a previous pull request...about updating talk page with link to chatroom

**Comment by jywarren** [comment]
Ah, indeed -- I believe this may be because you've been working in your master branch, rather than a feature branch, and then it goes a bit out of sync with the main master branch. Check out the link at the bottom of @plotsbot's comment -- it shows a workflow that can avoid this. But we can also work around it?

**Comment by chanjess** [comment]
@jywarren ok i'll try that!

**Comment by SidharthBansal** [comment]
Do you need any help?
We are there to help you.

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR.
Thanks for contributing at Public Lab

**Pull request closed without merging**
