### PR TITLE
Fixes for responding to html get request while adding comment to an answer

### LINKED ISSUE #3051: 500 error on posting comment on an answer
@Souravirus I'm not sure if this is a routing error or what, but do you think you could take a look?

`https://publiclab.org/comment/answer_create/1068?type=question&body=Ah%2C+ok.+Thanks+for+such+a+careful+look+at+this.+So+we+no+longer+get+separate+modified+lenses+--+we+just+get+whole+modified+and+unmodified+cameras+from+the+factory.+It%27s+very+helpful+to+know+that+the+loose+lenses+don%27t+work+well+for+the+latest+Mobius+camera+bodies%2C+so+we%27ll+probably+be+retiring+that+option+and+just+selling+whole+modified+and+unmodified+Mobius+cameras.+If+you%27d+like+to+exchange%2C+please+send+it+back+to+Kits+at%3A%0D%0A%0D%0APublic+Lab%0D%0A55+Cromwell+St+1C%0D%0AProvidence+RI+02907%0D%0A%0D%0ASorry+for+the+trouble+and+thank+you+x1000000+for+your+help+with+this+issue.+It+really+makes+a+difference.%0D%0A%0D%0AWe%27ll+add+in+a+free+extra+lens+with+different+geometry+if+you%27d+like+to+try+that+too+on+a+newer+Mobius+body.+Just+discussed+this+with+%40amanda+--+thanks+again!&_=1531320597441`

On this page:

https://publiclab.org/questions/tuomas_j_mattila/07-01-2018/mobius-lens-out-of-focus

Note that the comment actually gets posted, so i guess that means it's not a routing issue... @ViditChitkara perhaps this could be related to the comment form submission? Just trying to figure it out, any help appreciated:

screen shot 2018-07-11 at 11 00 48 am

### PR DESCRIPTION
**Pull request by Souravirus**
Fixes #3051 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
Hi @jywarren I have added an comment/create.html.erb file for responding to html requests while adding a comment to an answer and its working fine. Please check it.

**Comment by Souravirus** [comment]
Hi @jywarren, before you go please see this as I have fixed the error while making a comment on answer. Thank you!!

**Comment by Souravirus** [comment]
Hi @jywarren see if its perfect.

**Comment by jywarren** [comment]
Awesome!!!! 👍

**Pull request merged**
