### PR TITLE
Profile api test PR

### PR DESCRIPTION
**Pull request by jywarren**
Just testing something for #3134!

### CODE REVIEW

**Comment by jywarren** [comment]
Locally, this gives me, on mysql:

```sql
ActiveRecord::StatementInvalid:         ActiveRecord::StatementInvalid: Mysql2::Error: Expression #1 of ORDER BY clause is not in SELECT list, references column 'plots.node_revisions.timestamp' which is not in SELECT list; this is incompatible with DISTINCT: SELECT DISTINCT `node`.`nid` FROM `node` LEFT OUTER JOIN `node_revisions` ON `node_revisions`.`nid` = `node`.`nid` LEFT OUTER JOIN `community_tags` ON `community_tags`.`nid` = `node`.`nid` LEFT OUTER JOIN `term_data` ON `term_data`.`tid` = `community_tags`.`tid` WHERE (`node`.`nid`) IN (1, 8, 1, 2, 8, 9, 10, 15) AND ((created >= 1533839387 AND created <= 1533846587) OR (timestamp >= 1533839387  AND timestamp <= 1533846587)) ORDER BY node_revisions.timestamp DESC
            test/unit/user_test.rb:97:in `block in <class:UserTest>'

  23/23: [================================================] 100% Time: 00:00:07, Time: 00:00:07
```

**Comment by jywarren** [comment]
That's related to this terrible obscure issue: https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

**Comment by jywarren** [comment]
Er, wait, not that one. But something similar, let me look...

**Comment by jywarren** [comment]
The error is on this line:  (line 97)

`nodes_time = bob.content_followed_in_period(2.hours.ago,Time.now).pluck(:nid)`

**Comment by jywarren** [comment]
Huh... what do you know... a pretty similar error to in #3217... 

https://github.com/publiclab/plots2/blob/04d5bbca4f47066e9628c1dc78e9961ef32c20f7/app/models/user.rb#L371-L376

**Comment by jywarren** [comment]
The Travis tests are failing on the functional test for `search_api_test.rb` -- 

```
There was a test error at: Failure: test_search_profiles_without_order_by_and_default_sort_direction(Minitest::Result) [/app/test/functional/search_api_test.rb:95]: NoMethodError: undefined method ‘[]’ for nil:NilClass test/functional/search_api_test.rb:95:in ‘block in '
--
```

on requesting: `get '/api/srch/profiles?srchString=steff'

I'm going to try this locally...

**Comment by jywarren** [comment]
OK, locally, on mysql, i get, for `http://localhost:3000/api/srch/profiles?srchString=jeff`:

```json
{"items":[{"docId":0,"docType":"user","docUrl":"/profile/jeffrey","docTitle":"jeffrey","docSummary":"","docScore":0},{"docId":0,"docType":"user","docUrl":"/profile/jeff","docTitle":"jeff","docSummary":"","docScore":0}],"srchParams":{"srchString":"jeff","seq":null,"showCount":null,"pageNum":null,"tagName":null}}
```

**Comment by jywarren** [comment]
OK, so I tried putting a `puts` error logging statement just before this, so we see what's really in there:

```
                                                         
+  93 puts '#####################'                                                             
+  94 puts last_response.body                                                                  
   95      json = JSON.parse(last_response.body)                                               
   96                                                                                          
+  97 puts json                                                                                
+  98 puts '#####################'                                                             
   99      assert_equal "/profile/steff3",   json['items'][0]['docUrl']                        
  100      assert_equal "/profile/steff2",   json['items'][1]['docUrl']                        
  101      assert_equal "/profile/steff1",   json['items'][2]['docUrl']   
```

If this doesn't work, i'll test against just `last_response.body`  first

**Comment by stefannibrasil** [comment]
@jywarren that was the error, yeah... if you also change this line https://github.com/publiclab/plots2/blob/master/test/unit/user_test.rb#L37

to 'jeff' or any other username on fixtures, it will show the same error.

**Comment by stefannibrasil** [comment]
Let me know anything that you find, I have to work now so I'll get back to this later, thanks for the help!

**Comment by jywarren** [comment]
ok, trying on the unit test as it's a simpler usage of the code, so maybe
we can track it there...

**Comment by jywarren** [comment]
Restarting this build as it errored for unrelated reasons.

**Comment by stefannibrasil** [comment]
can I close this one? :) @jywarren

**Comment by jywarren** [comment]
yes please!

**Comment by stefannibrasil** [comment]
closed via #3134

**Pull request closed without merging**
