### PR TITLE
Added pagy to following route

### LINKED ISSUE #8574: Add pagy for following route
**Please describe the desired behavior.**
Pagy is a pagination gem used for its peak performance over other pagination tools. As mentioned #8426  we have been trying to migrate our codebase from will_paginate to pagy gem and would love your help with it! :tada:  

Here is how you may implement pagy for this: - 

- Select action `following` under `users_controller`
- Since here pagination is already implemented using `will_paginate` as `.paginate(page: params[:page], per_page: 10)` you can remove this line so that the method now looks like 

    `@users = @user.following_users`

- Now add the pagy method in this action as - 
`@pagy, @users = pagy(@user.following_users, items: 10)`

Here 10 represents the items to be displayed on each page. This is the most basic way we can use pagy over any action: -
` @pagy, @records = pagy(Product.some_scope)`

- Now move to the html code which is generated for this controller `users/show_follow.html` 
- Search for the `will_paginate` line and replace it with - 

`<% if @pagy %>
        <%= raw pagy_bootstrap_nav @pagy %>
<% else %>
        <%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
 <% end %>`

- This will now check if `@pagy` variable is available or not and then if present will generate pagination using pagy.
- Awesome, create a pull request for the same and add screenshots if relevant! 

**Additional context (optional)**
In case of queries please checkout the following links  for help: - 
https://ddnexus.github.io/pagy/how-to
https://ddnexus.github.io/pagy/migration-guide
https://github.com/publiclab/plots2/pull/8428
https://github.com/publiclab/plots2/pull/8326

### PR DESCRIPTION
**Pull request by stacytonui**
Fixes #8574 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by KarenEfereyan** [comment]
Waow @stacytonui nice one.

**Review by Tlazypanda — APPROVED** [review]
@stacytonui LGTM! 💯

**Comment by stacytonui** [comment]
Yay thankyou! @Tlazypanda .. @KarenEfereyan Thankyouu

**Comment by KarenEfereyan** [comment]
> Yay thankyou! @Tlazypanda .. @KarenEfereyan Thankyouu

Anytime dear. Well done

**Review by jywarren — APPROVED** [review]
Great collaboration here! Looks perfect, thanks so much! Merging!

**Comment by KarenEfereyan** [comment]
> Great collaboration here! Looks perfect, thanks so much! Merging!

Yay! Congrats to you @stacytonui

**Comment by stacytonui** [comment]
Thankyouu!! @KarenEfereyan

**Pull request merged**
