### PR TITLE
change deliver_now to deliver_later in answer_like_controller

### LINKED ISSUE #5311: (not working yet) Change deliver_now to deliver_later for all emails
We just successfully converted the admin_controller to use `deliver_later` to enqueue email sending, which should really help keep the website running smoother -- it uses Redis automatically to send emails on another thread. 

https://github.com/publiclab/plots2/pull/4967/files shows how we did it -- it did involve wrapping all failing tests with:

```ruby
perform_enqueued_jobs do 
  # all test contents
end
```

Let's do this for each controller, and each time we use `deliver_now` -- you can find all instances using this search:

https://github.com/publiclab/plots2/search?q=deliver_now

We'd love help with this, and it's fine for it to be over a series of pull requests, one at a time!
- [ ] users_controller (@divyabaid16)
- [ ] answer_like_controller(@AnthoniaOkafor)
- [ ] notes_controller
- [ ] user_sessions_controller
- [x] answers_controller
- [x] admin_controller

### PR DESCRIPTION
**Pull request by AnthoniaOkafor**
Fixes #5311 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by AnthoniaOkafor** [comment]
@publiclab/plots2-reviewers  kindly see my PR

**Comment by gauravano** [comment]
Hey @AnthoniaOkafor, this test https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L279-L296 is failing so wrap up the code in `perform_enqueued_jobs` like mentioned here - https://github.com/publiclab/plots2/issues/5311#issue-427301202

Thanks!

**Comment by AnthoniaOkafor** [comment]
Hello @gauravano, I have wrapped the code in  test/functional/answer_like_controller_test.rb with
'perform_enqueued_jobs do', but the Travis Cl build for my PR is still failing.

**Comment by AnthoniaOkafor** [comment]
> Hey @AnthoniaOkafor, this test https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L279-L296 is failing so wrap up the code in `perform_enqueued_jobs` like mentioned here - [#5311 (comment)](https://github.com/publiclab/plots2/issues/5311#issue-427301202)
> 
> Thanks!

Hello @gauravano,  for the answer_like controller I am working on, you want me to wrap the code in https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L279-L296 with 'perform_enqueued_jobs do'. I thought it was a mistake so wrapped the code in test/functional/answer_like_controller_test.rb. If you say so, I can restore answer_like_controller_test.rb and change notes_controller_test.rb#L279-L296 instead.

**Comment by gauravano** [comment]
Hey @AnthoniaOkafor, first of all, let's remove changes from answer_like_controller_test as we are not checking any email sending there so no need of it there. 

After that, let's see if we encounter the error again as I am not getting the error when running the individual test file. Thanks!

**Comment by AnthoniaOkafor** [comment]
@publiclab/reviewers please see my PR

**Comment by jywarren** [comment]
Great, thank you!!!

**Pull request merged**
