### PR TITLE
Adds configurable header text to publiclab.org/questions

### LINKED ISSUE #2697: Add configurable header text to publiclab.org/questions
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/questions/index.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/questions/index.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -10,12 +10,9 @@
   <h2>Liked Questions <small class="hidden-sm">Most liked questions</small></h2>
   <% else %>
   <div class="text-center">
-  <h2>Questions and Answers<br /><small class="hidden-sm">Use Public Lab's community knowledge base</small>
-  </h2>
-  <h4><small><%= t('questions.index.explanation') %></small></h4>
-  <% end %>
-
-  <p>New to Public Lab? <a href="/wiki/public-lab-q-and-a">Learn how this works &raquo;</a></p>
+    <% cache('feature_questions-header', skip_digest: true) do %>
+      <%= feature('questions-header') %>
+    <% end %>
   </div>
 
   <hr />
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by chitra591**
Fixes #2697

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, @chitra591 -- thanks! No worries, we'll help you through these errors. Great to see this PR get started! 👍 👍 👍 

Hi @publiclab/reviewers is anyone available to help out here? I've gone through a number of PRs but would love some help in supporting @chitra591 on this one. Thank you!!!!

**Comment by Gauravano** [comment]
hi @chitra591, there was a merge conflict as the new code was also deleting the end statement, I have resolved that let's see what result comes up now.

**Comment by Gauravano** [comment]
ok errors gone :smile:

**Comment by Gauravano** [comment]
@chitra591 as this PR is changing the view, could you please attach a screenshot of http://localhost:3000/questions/ . Also, update your local branch first. Thanks.

**Comment by chitra591** [comment]
Thanks @Gauravano and @jywarren for the help!

Here is the screenshot
screen shot 2018-05-10 at 8 56 47 am

**Comment by jywarren** [comment]
Looks great. The feature should indeed be blank until it's set at `/features`. Great, merging now! Thank you so much, we're very pleased to have your assistance and would love to support if you want to try another! 👍 👍 🎉

**Comment by chitra591** [comment]
This is the first open source project that I have worked on. And working with you guys is the best experience that I have had.. 
Thank you so much!

And sure, I would love to solve more issues!

**Comment by jywarren** [comment]
Great! @publiclab/soc @publiclab/reviewers does anyone have a small project they'd like to break out for @chitra591 to try out? Something to welcome in a newcomer?

Thank you!!! 👍 👍 🎉

**Pull request merged**
