### PR TITLE
Remove flot js library

### PR DESCRIPTION
**Pull request by cesswairimu**
#4884 
Removing flot plotting library and dependent pages since its not being used anymore.

### CODE REVIEW

**Comment by jywarren** [comment]
Whoa, really great! 

Was `app/views/tag/contributors.html.erb ` totally unused??? 😂

**Comment by cesswairimu** [comment]
@jywarren I couldn't find another place that it was being uses expect for the '/contributors' page...But I have restored it back just in case

**Comment by jywarren** [comment]
OK - well, maybe we should mark it for deletion anyways... we can do it in
another PR though. But yeah, i think it was the result of some confusion
and actually may not be used anymore!

**Comment by cesswairimu** [comment]
okay cool

**Comment by jywarren** [comment]
🎉

**Pull request merged**
