### PR TITLE
drupal_node to node & DrupalNode to Node

### PR DESCRIPTION
**Pull request by aayushgupta1**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ykl7** [comment]
Hi @aayushgupta1 please try to send a PR from your fork's feature branch. This allows you to make changes to your branch and keep the work on the same PR

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? I think @ykl7's suggestion is good, and that you need to rebase it on top of master:

* first, save a copy of your work in a named feature branch with `git branch node-refactor`
* then, follow instructions here to rewind your master branch: https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch
* run `git pull https://github.com/publiclab/plots2.git master` to get the latest version of the master branch
* then checkout your new feature branch with `git checkout node-refactor`
* run `git rebase master` and follow the prompts to rerun your new code over the latest master
* push up your newly rebased changes with `git push origin node-refactor`
* open a new pull request with your new named feature branch

Make sense? I'm happy to offer more input if you run into trouble.

Thanks!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? I know this is a big and complex project.

Thanks!

**Comment by jywarren** [comment]
Hi, have you had any chance to take a new look at this? We'd love to have your contribution!

**Comment by aayushgupta1** [comment]
Hi. Yeah. I created a new PR #1319 . Kindly check that.

**Comment by jywarren** [comment]
Will do, thanks!

**Pull request closed without merging**
