### PR TITLE
Added first timers badge to README as per GCI task - Fixes #1012 

### LINKED ISSUE #1012: Add "first-timers-only" badge to our README
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

http://www.firsttimersonly.com/ has a great badge for projects to advertise that they're friendly to first-timers:

badge

It'd be great to add this to our README, right next to our "build passing" badge, linking to our new first-timers landing page (https://github.com/publiclab/plots2/projects/2)

```
![badge](http://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)
```

### PR DESCRIPTION
**Pull request by aryanbhasin**
As per the GCI task: https://codein.withgoogle.com/dashboard/task-instances/4907900732440576/

Added the "first timers" badge next to the "build passing" badge to the README from http://www.firsttimersonly.com/

Before: 
screen shot 2016-12-01 at 12 25 58 pm

After:
screen shot 2016-12-01 at 12 25 25 pm

### CODE REVIEW

**Comment by ananyo2012** [comment]
Thank you so much for your contribution. There is a build failure here but this is probably due to Travis Ci installation problems. Not your fault. We are reviewing this and responding asap. Thanks for choosing this task. We appreciate your interest.

**Comment by ananyo2012** [comment]
In the mean time let me tell you some good things that you should follow while making a PR. First is that you should make a new branch whenever you work on a feature or fix. You can create a new branch using `git branch branchname` and then checkout using `git checkout branchname`. Consider reading https://publiclab.org/wiki/contributing-to-public-lab-software#A+sample+git+workflow. It has a good guide on how to work while working on a new issue. This will really help you in future.

**Comment by ananyo2012** [comment]
Also write good commit messages for your work. Mention the issue no like `Fixes #1012` Here #1012 is the issue no. Use the imperative mood in commit messages. Here is a guide on writing good commit messages http://chris.beams.io/posts/git-commit/

**Comment by ananyo2012** [comment]
@jywarren All checks have passed now. This can be merged now. 
@aryanbhasin After this is merged you can tweet about this task and just submit this PR link in the task page and we will approve it!

**Comment by aryanbhasin** [comment]
@ananyo2012 Thank you for the tips! I am new at using Git and I appreciate all your help. I have tweeted about the task.
As soon as you merge the PR I'll add the links and send the task for review.

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. 

Thanks!

**Pull request merged**
