### PR TITLE
Persist display format

### LINKED ISSUE #9412: Retain gallery/list view state when we move from one filter to another in the questions page
**Please describe the desired behavior.**
Currently, irrespective of whether we're in the gallery view or in the list view in https://publiclab.org/questions/ if we go to `Recently Asked`, `Recently Commented` etc it switches to gallery view. It would be good if the same state is retained when we click on one of the columns i.e if we are in list view in `Recently Asked` and then go to `Recently Commented`, list view should be retained there.

**Additional context (optional)**
ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by TildaDares**
Fixes #9412

https://user-images.githubusercontent.com/63427719/116676894-743d4a00-a99f-11eb-9b03-80fa76c49bbd.mov

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
LGTM @TildaDares! :tada: :100:

**Review by RuthNjeri — APPROVED** [review]
This looks good to me @TildaDares. I like the idea of using the session storage 🎉

**Comment by RuthNjeri** [comment]
Tested it on https://stable.publiclab.org/questions/ and it is working as expected, thanks @TildaDares!

**Comment by cesswairimu** [comment]
thanks @TildaDares :rocket:

**Pull request merged**
