### PR TITLE
Fix(Signup Modal): Link signup modal at questions-answers

### LINKED ISSUE #4415: Link Sign Up modal to the Question page
image
See last line's keyword: ``Sign up`` . Please link it to the sign up modal
Refer http://localhost:3000/questions/qwerty/12-15-2018/uihjn-m#post-answer

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #4415  (<=== Add issue number here)

Linked to Signup at Question-answers
Basic Flow:
linktosignupbasic

Alt Flow:
linktosignupalt

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] PR is descriptively titled 📑
* [X] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@kevinzluo do we require to create any ``requireSignup`` method as we created the `requirelogin` button?

**Comment by SidharthBansal** [comment]
@kevinzluo it will be grateful if you can add `OAuth` milestone to issues and prs whichever you find are related login/signup.
Thanks

**Comment by kevinzluo** [comment]
I don't feel we should do that. I am working on adapting requireLogin to take an extra argument to open the signin modal instead. It should only be one or two lines. Adding a requireSignup will use almost the exact same code. 



> @kevinzluo it will be grateful if you can add `OAuth` milestone to issues and prs whichever you find are related login/signup.
> Thanks

Got it. Thanks for telling me.

**Comment by SidharthBansal** [comment]
> I am working on adapting requireLogin to take an extra argument to open the signin modal instead.

Yeah I found. It is better approach. We should apply reusability.
Thanks

**Comment by SidharthBansal** [comment]
@kevinzluo it will be better to have title` Linked signup modal at questions-answers `.
No need of other text.

**Comment by SidharthBansal** [comment]
@kevinzluo thanks. Can you please check the recursive behaviour of the login as it was for signup which you solved in the last pr?

**Comment by kevinzluo** [comment]
@SidharthBansal I was actually looking at that yesterday. It seems that if the username is not found then return_to doesn't work. I will post an issue for it. 



> @kevinzluo it will be better to have title`Linked signup modal at questions-answers`.
> No need of other text.

Understood :+1: .

**Comment by SidharthBansal** [comment]
>It seems that if the username is not found then return_to doesn't work.

Please link me there once you create the issue.

I think you are talking about something else. I am talking about /loginreturn_to=/.../..../.../.../.../ like the sign up in #4445.

**Comment by kevinzluo** [comment]
That error doesn't occur on /login yet because /login and the login modal are rendered by two different files. So we are fine for now. However, I feel in the future we will probably combine them, so it might need to be fixed then.

**Comment by SidharthBansal** [comment]
>>That error doesn't occur on /login yet because /login and the login modal are rendered by two different files. So we are fine for now. However, I feel in the future we will probably combine them, so it might need to be fixed then.

Can you create a issue for this? 
Create common partial for it and do the required recursive login work.

**Comment by SidharthBansal** [comment]
Moved to #4456.

**Pull request merged**
