### PR TITLE
Caching bundler in .travis.yml

### PR DESCRIPTION
**Pull request by jywarren**
This may speed up Travis builds:

https://docs.travis-ci.com/user/caching/#Bundler

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer

### CODE REVIEW

**Comment by jywarren** [comment]
This doesn't seem to have actually reduced times much; 8:13 and 8:51 are about usual, in fact. Maybe should abandon this, as it does add some complexity?

**Comment by jywarren** [comment]
Reopening to see if the 2nd time they run, they're faster?

**Comment by jywarren** [comment]
Nope, 8:12 and 8:13. Closing this, it was a good test.

**Comment by ananyo2012** [comment]
@jywarren Maybe we should keep this one. I think since its the first time it takes time to cache the bundler dependencies. Once this is merged sunsequent builds take lesser time due to the cached dependencies.

**Comment by jywarren** [comment]
But I tested it twice -- you don't think it'd cache for my second test here?

**Pull request closed without merging**
