### PR TITLE
install_cloundnine.sh changes

### LINKED ISSUE #417: Imagemagick installation on a cloud9
### What happened just before the problem occurred
During the installation process on Cloud9, 
after ``` sudo apt-get install imagemagick ruby-rmagic ```
I get this in the bash terminal -

``` 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package imagemagick is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'imagemagick' has no installation candidate
E: Unable to locate package ruby-rmagick 
```

### Relevant URLs

https://

### PublicLab.org username
jiteshxyz
(to help reproduce the issue)

### Browser, version, and operating system
Firefox - 44
Ubuntu 15.04

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by jiteshjha**
This commit fixes #417

### CODE REVIEW

**Comment by jywarren** [comment]
This looks good but you've added your autosave file, ending in a ~. Can you remove that from the PR?

If there are PRs before yours I'll check them tomorrow and you may have to rebase after I merge them in. 

Thanks, this is super helpful!

**Comment by lalithr95** [comment]
This is awesome. Also can you squash commits ?

**Comment by jywarren** [comment]
I've merged this in, but in the future, squashing commits would be great, especially for a small change like this. Thanks, Jitesh! Glad to have your contributions.

**Comment by jiteshjha** [comment]
Sure, Jeff! Will keep in mind, thanks. :smile:

**Pull request merged**
