### PR TITLE
changed function "t" to "translation" on line 23 and 26.

### LINKED ISSUE #6736: change function t to translation of views/grids/_thumbnail
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
change the function t to translation in lines 23 and 26. After changing the lines should look like below:

```diff
<%= translation('notes._notes.last_edit_by') %> <a href="/profile/<%= node.latest.author.name %>"><%= node.latest.author.name %></a>
| <i class="fa fa-eye"></i> <%= number_with_delimiter(node.views) %> <span class="d-none d-md-inline"><%= translation('notes._notes.views') %></span>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by priyajitm**
changed function "t" to "translation" on line 23 and 26.

Fixes #6736 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by priyajitm** [comment]
this is my Twitter handle - @iampmukherjee

Thanks,
Priyajit M.

**Comment by nstjean** [comment]
I'm not sure why that's failing, it's been doing that a lot lately. It should be an issue, nothing you did!

Can you change the Issue # at the top in your post to the issue that this fixes? #6736 Thanks!

**Comment by jywarren** [comment]
Awesome! I'm working on another fix for the thumbnails file, so I'm going to hold off a little bit before merging this, but this looks great!

**Comment by SidharthBansal** [comment]
@jywarren what is the status of related PRs?

**Comment by jywarren** [comment]
I'm not sure, maybe @nstjean could offer an update and we could tidy up the
remaining open PRs?

**Comment by nstjean** [comment]
Hi @SidharthBansal ! The full list is here https://github.com/publiclab/plots2/issues/6579 - templates that have a FTO created are checked off with links to the issues. It is up to date. Do you want me to mark off which have been merged and which haven't?

**Comment by SidharthBansal** [comment]
yeah, please

**Comment by nstjean** [comment]
@SidharthBansal Ok I'll get that done!

**Comment by SidharthBansal** [comment]
Any progress on this?
Just checking... no hurry

**Comment by SidharthBansal** [comment]
Any progress on this?
Just checking... no hurry

**Comment by nstjean** [comment]
Ahh, sorry! I got caught up in testing issues. I'll go through it today!

**Comment by cesswairimu** [comment]
This PR has been open for a long time and no activity/ reviews requested has not been addressed. We understand you might be busy and engaged on other things. I am closing this for now...please  feel free to reopen if you get some time and would like to finish this. Rem to check if its still available before you reopen. Thanks

**Pull request closed without merging**
