### PR TITLE
Beginner fixes at line 23 and 25, h4 and p tag updates

### PR DESCRIPTION
**Pull request by pawan-nirpal-031**
This fix is a beginner level fix, I have no idea I am doing yet but hope to be learn as I go along.

### CODE REVIEW

**Comment by pawan-nirpal-031** [comment]
Does this mean, that my PR was approved, Please guide me with this.

**Comment by pawan-nirpal-031** [comment]
Does this mean, that my PR was approved, Please guide me with this.

**Comment by cesswairimu** [comment]
Hi @pawan-nirpal-031....we normally work on issues listed here https://github.com/publiclab/plots2/issues...I understand you are looking for a way to get started...we have the process for this outlined here https://code.publiclab.org/ ...please feel free to ping me if you need any help or if have any questions.. Closing this for now. Thanks

**Comment by pawan-nirpal-031** [comment]
> Hi @pawan-nirpal-031....we normally work on issues listed here https://github.com/publiclab/plots2/issues ... I understand you are looking for a way to get started...we have the process for this outlined here https://code.publiclab.org/ ...please feel free to ping me if you need any help or if have any questions.. Closing this for now. Thanks

Yes thanks for being patient and considerate, I will make sure to go as per requirements.

**Pull request closed without merging**
