### PR TITLE
testing exact username: query

### LINKED ISSUE #5775: Exact username MATCH addition on API profile search query
We need to ensure that the API profile search query returns exact match on username as well.  Right now, if a common name is entered in the search query it will return other names and not the exact query we're calling.

### PR DESCRIPTION
**Pull request by rarrunategu1**
Fixes #5775 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh oops, what happened to these commits? Thanks!

**Comment by gauravano** [comment]
Actually, it worked - https://jenkins.laboratoriopublico.org/job/Plots-Unstable/lastBuild/changes as @rarrunategu1's commit which has the query change is part of the push. See at build changes and you'll find their commit there.

**Comment by gauravano** [comment]
But, yeah, it's weird that file changes changed to 0. Digging further...

**Comment by gauravano** [comment]
Hmm, I checked the unstable workspace and changes are there - https://jenkins.laboratoriopublico.org/job/Plots-Unstable/ws/app/models/user.rb/*view*/ [search `def search` and you'll see query change].

**Comment by jywarren** [comment]
OK, this is not returning the exact match however:
https://unstable.publiclab.org/api/srch/profiles?query=warren

**Comment by jywarren** [comment]
Was this reverted, perhaps? I see this "force pushed" message just after the merge.

**Comment by jywarren** [comment]
er, wait, sorry -- it will be https://stable.publiclab.org/api/srch/profiles?query=warren but still, without being able to see the changed files, it's hard to know. 

Oh wait! This is a PR to unstable. Sorry. @rarrunategu1 you should be able to directly push to `unstable` with `git push git@github.com:publiclab/plots2.git HEAD:unstable` without opening a PR, i think?

**Comment by gauravano** [comment]
@jywarren please see - https://github.com/publiclab/plots2/issues/5775#issuecomment-499256751

**Comment by jywarren** [comment]
yes, saw it! Sorry!

**Comment by gauravano** [comment]
No issue!

**Pull request merged**
