### PR TITLE
Update bundler to 2

### PR DESCRIPTION
**Pull request by cesswairimu**
Stable build failing with this error 

``Step 12/17 : RUN bundle update --bundler &&     bundle install --jobs=4
 ---> Running in a4b0d1ce0579
You must use Bundler 2 or greater with this lockfile.
Service 'mailman' failed to build: The command '/bin/sh -c bundle update --bundler &&     bundle install --jobs=4' returned a non-zero code: 20
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE``

### CODE REVIEW

**Comment by Tlazypanda** [comment]
Hey @cesswairimu @jywarren  I don't think travis is setup for stable branch :sweat_smile:   
https://github.com/publiclab/plots2/blob/c60aaabb56c018962c76abf3f5f2d114f8492d15/.travis.yml#L74

**Comment by jywarren** [comment]
I repointed this at `main` - maybe that'll help??

**Comment by Tlazypanda** [comment]
> I repointed this at `main` - maybe that'll help??

Actually this change is already done in main :sweat_smile:  I think @cesswairimu was targeting this to stable inorder to rebuild the gemfile for stable

**Comment by jywarren** [comment]
Ah, ok - but the flow is that `main` (formerly `master`) builds and is published on the `stable` server -- then the code is merged to `stable`, and then published to the production server. So i think that change will already be present! 

Hmm, though - https://jenkins.laboratoriopublico.org/job/Plots-Stable/ is still not building. 

Strangely it still shows:

```
Step 12/17 : RUN bundle update --bundler &&     bundle install --jobs=4
 ---> Running in 8168371d806c
You must use Bundler 2 or greater with this lockfile.
Service 'mailman' failed to build: The command '/bin/sh -c bundle update --bundler &&     bundle install --jobs=4' returned a non-zero code: 20
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

https://jenkins.laboratoriopublico.org/job/Plots-Stable/lastBuild/console

It definitely has the latest changes... Hmm. I'll ask @icarito if he has any ideas!

**Comment by jywarren** [comment]
Hmm. @icarito confirmed by going back to Bundler 1 and it passed Jenkins but failed Travis 😄 

https://github.com/publiclab/plots2/pull/8100

Now he's just pushed a second attempt this time to actually update the bundler gem from Dockerfile, and will chime in here if it works!

**Comment by icarito** [comment]
Hi, so far I've been unable to get bundler2 to work, I've tried to run
```
gem install --default bundler
```

and this causes the following message:

```
Successfully installed bundler-2.1.4
1 gem installed
You must use Bundler 2 or greater with this lockfile.
```

It appears it is still using bundler 1.16.

**Comment by icarito** [comment]
By setting the bundler version after installing it, with the command
```
ENV BUNDLER_VERSION=2.1.4
```
in Dockerfile, I got further, but now I'm having issues with using a different version of `rake`.
Updating rake in the same way as bundler was updated...

**Comment by icarito** [comment]
I'm currently working on trying to update bundler here: https://github.com/publiclab/plots2/pull/8101
My latest try is failing at this step:
```
Installing scrypt 3.0.7 with native extensions
[91mGem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/ruby/2.4.0/gems/scrypt-3.0.7/ext/scrypt
/usr/local/bin/ruby -I/usr/local/lib/ruby/site_ruby/2.4.0/rubygems -rrubygems
/usr/local/lib/ruby/gems/2.4.0/gems/rake-13.0.1/exe/rake
RUBYARCHDIR\=/usr/local/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/scrypt-3.0.7
RUBYLIBDIR\=/usr/local/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/scrypt-3.0.7
/usr/local/bin/ruby: No such file or directory --
/usr/local/lib/ruby/gems/2.4.0/gems/rake-13.0.1/exe/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in
/usr/local/bundle/ruby/2.4.0/gems/scrypt-3.0.7 for inspection.
Results logged to
/usr/local/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/scrypt-3.0.7/gem_make.out

An error occurred while installing scrypt (3.0.7), and Bundler cannot continue.
Make sure that `gem install scrypt -v '3.0.7' --source 'https://rubygems.org/'`
succeeds before bundling.
```

**Comment by icarito** [comment]
Okay, it is resolved, I believe, please check https://github.com/publiclab/plots2/pull/8101 to merge, this allows building both in Jenkins and Travis.

**Comment by cesswairimu** [comment]
Thanks @icarito  @jywarren  and @Tlazypanda :tada:  :tada:

**Pull request closed without merging**
