### PR TITLE
follow-popover

### LINKED ISSUE #8171: 'Follow' pop up menu overlaps with navigation bar
When clicking on the arrow next to the 'Follow' button a menu appears. When scrolling down while this menu opens, it ends up overlapping with the navigational bar.

Image of bug:

Pop up menu overlapping with nav bar

Link to page with bug: https://publiclab.org/tag/water-quality?_=1595188617

I came across the bug while using Google Chrome. Mentioning just in case the issue is browser specific.

A possible fix is to try changing the element z-index to 0.

### PR DESCRIPTION
**Pull request by urvashigupta7**
Fixes #8171  
ezgif com-video-to-gif (4)

### CODE REVIEW

**Comment by urvashigupta7** [comment]
@cesswairimu Please review 😄

**Comment by cesswairimu** [comment]
Travis is taking a really long time here :thinking: I will take a look once its done

**Review by avats-dev — APPROVED** [review]
@urvashigupta7 looks good to me as I checked on gitpod. :tada: 
Also, travis checks have passed but idk why it's not showing here, but you can see on clicking `details` about the test.

@cesswairimu fyi!

**Comment by urvashigupta7** [comment]
Yes @avats-dev is right. Please take a look @cesswairimu  :)

**Comment by cesswairimu** [comment]
closing and reopening to restart travis

**Comment by avats-dev** [comment]
> closing and reopening to restart travis

@cesswairimu same as before, something else is happening here :laughing:

**Comment by urvashigupta7** [comment]
Travis in other PRs is running only one time. Why it is running two times here? 🤔🤔

**Comment by urvashigupta7** [comment]
@cesswairimu All checks are passing now :smile:

**Review by cesswairimu — APPROVED** [review]
This is awesome :tada: thanks a lot for working on this and the patience with travis :smile:

**Pull request merged**
