### PR TITLE
banned users are visible to /people page for admin

### LINKED ISSUE #2246: Banned users not visible on /people page
Banned users are currently not visible on /people page. It should at least be visible to admin or moderators.
lists-page-1
A user named 'user' is banned but not visible here

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #2246

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
list-page-fixed-1

**Comment by jywarren** [comment]
Great catch. Whoops! Once this is ready i'm eager to merge it in! 👍

**Comment by ViditChitkara** [comment]
Hi, don't really know why the tests are failing. I tried to close and reopen the pr but didn't resolve the problem.

**Comment by ViditChitkara** [comment]
`E: Failed to fetch ftp://ftp.us.debian.org/debian/pool/main/n/node-tunnel-agent/node-tunnel-agent_0.3.1-1_all.deb  Could not connect passive socket. [IP: 128.30.2.26 21]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update -qq && apt-get install -y bundler libmysqlclient-dev ruby-rmagick libfreeimage3 nodejs-legacy npm wget openjdk-7-jre openjdk-7-jdk procps' returned a non-zero code: 100
The command "docker-compose build" failed and exited with 1 during .
`
These are the travis logs

**Comment by ViditChitkara** [comment]
@jywarren the tests are fixed now. Please suggest any further changes if required.

**Comment by jywarren** [comment]
Awesome, thanks! 👍 👍

**Pull request merged**
