### PR TITLE
Consolidating ranges and stats

### LINKED ISSUE #4577: Consolidation existing "range pages" like with the main stats page
Consolidation/standardization of "range pages" like https://publiclab.org/stats/range/10-05-2015/10-05-2016/ with main stats page at https://publiclab.org/stats?time=September%2026,%202017%2022:43

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #4577

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
ooooohhhhh

Please post some screenshots once you're ready! Thanks Cess this is the biggest one in your project in some ways - the culmination of all your work into a single page type!!!! Great work!!!!!

**Comment by cesswairimu** [comment]
screencapture-localhost-3000-stats-2019-03-01-02_08_25
Here it is @jywarren but I am not quite satisfied with this. I am working on another design will open another PR so that we can compare. Thanks

**Comment by jywarren** [comment]
OK but let's not sweat the most detailed parts of the design -- let's focus
on first making sure everything is compatible -- for example, I see "over
the past year" on one part of the page, and "since 25 days ago" in another.
Both of these should be sourcing from the user-defined range/period of
time, and should say so. It's possible it's just a labeling issue so far?
But there may be things that need refactoring to properly display for the
given period under the new unified system. This'll be a bit complex so
let's focus on this and we can work on more aesthetic concerns in a
follow-up PR. I hope that makes sense?

Good going Cess!!!!!!

**Comment by cesswairimu** [comment]
Oh yeah I see...Yes it makes sense. Thanks

**Comment by jywarren** [comment]
you got it!!!

**Comment by cesswairimu** [comment]
@jywarren  thoughts? 
screencapture-unstable-publiclab-org-stats-2019-03-04-02_01_07
Thanks

**Comment by jywarren** [comment]
Wow it looks amazing. And it works for any time period selected?

**Comment by jywarren** [comment]
Any final tests you want to add, or is it good to merge? What do the URLs
look like?

**Comment by cesswairimu** [comment]
Yes it does...you can take a look on unstable pushed the code there

**Comment by cesswairimu** [comment]
The url is now `/stats` to get the range `/start?start=&end=`

**Comment by cesswairimu** [comment]
Oh, yeah let me add a test for the new `contribution_graph_making` method. Thanks

**Comment by jywarren** [comment]
While you're making final changes, can I request a couple small things?

1. Can you have the start and end inputs show the current selected period?
2. Is it possible to integrate the quick drop-down of preset ranges? What
was it called, I forget, but it had like past week, past month, past
year... It was great!
3. The filter period is like, to display grouped by week or month? If so, I
think in Shopify stats it's labelled "group by", could we call it that?

Thanks Cess! Tremendous!!!!

**Comment by jywarren** [comment]
screenshot_20190303-184636

**Comment by cesswairimu** [comment]
Thanks @jywarren. The `filter period` is the previously preset range...should I move it back just before the date-selector form?

**Comment by jywarren** [comment]
Oh really? When I select from it I get the URL

https://unstable.publiclab.org/stats?utf8=✓&options=Week

Wouldn't it be better to have it set start and end directly? And how does
utf8 get in there?

Also, perhaps if this is the preset ranges we should say "Past week" and
"Past year"?

Thanks Cess!

**Comment by cesswairimu** [comment]
Oh yeah it would make sense to remove the options parameter now and just have start and end set. Thanks fixing that. Will also try and remove the "utf8" not sure how it got there :thinking:

**Comment by jywarren** [comment]
🙌🏽🙌🏽🙌🏽

**Comment by cesswairimu** [comment]
@jywarren I managed to remove the `utf8`, have the date picker field data persist after post and also changed the preset periods to `past week, past month and past year`. However I was not able to do away with the `options` parameter. I tried to make the select options links but couldn't find a way even tried using javascripr listener but couldn't get it to work..If you have any suggestions please let me know. Thanks.
Here is the updated page
screencapture-localhost-3000-stats-2019-03-05-18_18_20 1

**Comment by cesswairimu** [comment]
I am using the `options` param to get what option is selected and set start_date using it. So if `past week` is selected I set `start_date` to `Time.now - 1.week`

**Comment by jywarren** [comment]
OK, that's fine - we can also think about refining the routes and such in a
follow-up. Is this ready to merge, do you think? It's so exciting!!!!

**Comment by cesswairimu** [comment]
yeah sure will create a follow-up. Yes its ready to merge :smiley:

**Comment by jywarren** [comment]
CONGRATS CESS!!!!!! 🎉 🎉 🎉 🎉

**Comment by gauravano** [comment]
Awesome work @cesswairimu :tada:

**Comment by cesswairimu** [comment]
Thanks @gauravano  :smiley:

**Pull request merged**
