### PR TITLE
Mysql upgrades

### PR DESCRIPTION
**Pull request by icarito**
This is to sync the container setup for the database with the code repository.
Note the mysql configuration and docker-compose are already in production.
This includes the bump in mysql version.
This PR supersedes #1384 and #1423, which I will close.

Additionally this PR comments out Solr and Web containers from docker-compose to make it on par with our production use pattern.

### CODE REVIEW

**Comment by jywarren** [comment]
Looks good -- did you want me to merge this to stable so we can observe it? Also -- remember we wanted to have Jenkins set up to build from a `testing` branch that can be force-pushed to in order to try out features without "committing" (in the non-Git sense) to them? That is, in order to test things currently, we have to merge them to the `stable` branch, which is essentially deciding to adopt the commits. If we wanted to try something out but not make a final decision, we could force push it to this hypothetical `testing` branch and see how it builds, then make a decision about whether to merge it into `master`. 

Is that something you'd like to try here, or should we try to do that later and just assume we can make a commitment to this if it passes tests?

**Comment by icarito** [comment]
Yes, except I seem to have mixed up a couple of commits, I'll fix this
PR and expect we can merge today, as this is already in production. (I
did it manually to look over the database conversion process).

Currently I did my testing directly on Tycho, without the web hook
auto-deploy. But this does not scale to other developers. I agree this
is needed, I've removed the /lowpriority/ tag on issue
https://github.com/jywarren/web/issues/80 ;-)

**Comment by icarito** [comment]
Okay now it should be ready for merge. Thanks!

**Comment by icarito** [comment]
Ah. We do need to uncomment docker-compose.yml to have tests run properly. I'll look at how to just run a single container in production without this hack to comment out the other containers.

**Comment by jywarren** [comment]
OK - well, i'd like to merge new things to stable and publish to production tonight, if possible (as i'll be in meetings tomorrow) so give me a heads up if this becomes ready to merge in! Although I guess it's not stopping anything?

Will I now have to rewind production to merge in from stable?

**Comment by icarito** [comment]
Hi,
The merge as I foresee it would be:
- Following file already exist untracked in production: `config/my.cnf`. Should be no conflict they are the same.
- Changes in `docker-compose.yml` really are only configuration for our production system, but they are making tests fail. 
 
One way to keep it simple would be to setup a separate `docker-compose-production.yml` file (untracked in git) to deal with tweaks in production. I'll research if there's a way to avoid to always remember to type 
`RAILS_ENV=production docker-compose -f docker-compose-production.yml ...` every single time, perhaps with a wrapper?

**Comment by icarito** [comment]
> One way to keep it simple would be to setup a separate docker-compose-production.yml file (untracked in git) to deal with tweaks in production. I'll research if there's a way to avoid to always remember to type RAILS_ENV=production docker-compose -f docker-compose-production.yml ... every single time, perhaps with a wrapper?

Of course, Makefile should do it ;-)

**Comment by icarito** [comment]
Also, to clarify, none of these changes are needed for today. The database is already running version 5.6 and mysql configuration files to be merged previously existed outside git anyway.

**Comment by jywarren** [comment]
Hi, @icarito - does this have an update since we've upgraded? Just checking!

**Comment by jywarren** [comment]
After today's changes, does that mean we're ready for this?

**Comment by jywarren** [comment]
Just a note that i am currently backing up and checking out docker-compose.yml before git pull when i publish on production.

**Comment by jywarren** [comment]
Is this still a change we'd like to merge in? Thanks!

**Comment by ryzokuken** [comment]
@icarito are you still working on this? What is the current status?

**Pull request closed without merging**
