### PR TITLE
Add font-awesome rails gem and remove other fontawesome packages from…

### LINKED ISSUE #7888: Remove fontawesome discrepancies and add it in the asset pipeline
Currently the font-awesome library is added twice in the package.json file version(4.7 and 5.12). It is also called in the file `app/views/csvfiles/new.html.erb` from a cdn. This leads to a slower load time on the website.

**Please describe the desired behavior.**
Replacing the font-awesome library with the font-awesome-rails [gem](https://github.com/bokmann/font-awesome-rails) is a good solution since on adding it to the asset pipeline, the resources will be automatically gzipped. Later support can be added for loading only critical css first and rest asynchronously.

**Additional context (optional)**
As we can see here both the versions are loaded on the first paint and also most of it is unused. (indicated by the red portion)
image

### PR DESCRIPTION
**Pull request by Tlazypanda**
… files

Fixes #7888 
Font awesome discrepanices removed by adding the font-awesome gem in the rails pipeline. Other installations removed from package.json and files demanding font-awesome from /lib edited.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

## Screenshots  
Tested by setting the config.assets.debug to false and config.assets.compile to true in development mode and then running the audit of Lighthouse. As you can see now the font-awesome is rendered from application.css thus removing the previous entries of fontawesome from render blocking elements.

Before  
https://developers.google.com/speed/pagespeed/insights/?url=publiclab.org

After  

image

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@jywarren @cesswairimu @emilyashley can you kindly review ? Thanks :v:

**Comment by Tlazypanda** [comment]
Yeah @Uzay-G Thanks a lot for the review :100:  I have to test it out properly I was thinking of pushing on the unstable branch.

**Comment by jywarren** [comment]
This looks great and I love the empirical test here! Super job.

Before merging, do we need to note anywhere the current version of FontAwesome, and/or how to check what version the gem is pegged to? So that when we look up icons (like at https://fontawesome.com/v4.7.0/icons/) we know which version we're working with? Thank you! This is good to merge but if you want to add a README entry or something that is also great. 

(or maybe a note in https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab ?)

**Comment by Tlazypanda** [comment]
@jywarren Thanks so much for the review :heart: The version used is v4.7.0 I have added a comment with the changes in the style guide slides :sweat_smile: And have also modified the gemfile comment to `add font awesome v4.7.0`

**Pull request merged**
