### PR TITLE
fix redirect to current page after login #711

### PR DESCRIPTION
**Pull request by petersowah**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by petersowah** [comment]
@ananyo2012 Hope this works. Thanks.

**Comment by ananyo2012** [comment]
Thanks for your contribution! This looks great. But just to say this is not the way to update the changes. You already made two PR earlier. Considering this is your first contribution this is really great and you could manage by redoing the changes again but had the changes been greater it would have been difficult to redo the changes. Instead squashing and amending the commit is the right way to do things.

But overall this looks great @petersowah Thanks!

**Comment by petersowah** [comment]
@ananyo2012 Thanks very much and noted. I won't be repeating these mistakes in my next contribution.

**Comment by jywarren** [comment]
Hello - Just catching up from #1157 and here... and just want to say thank you for your contribution! We know it's tough to come into a new project and really appreciate your hard work on this one. 

We'd love to have your help on another issue; there are a variety here: https://github.com/publiclab/plots2/labels/help-wanted or if you're looking for another smaller one to get your footing, you can try https://github.com/publiclab/plots2/labels/fto-candidates.

Please know that we're here to help! Thanks again.

**Comment by ebarry** [comment]
Wow thanks so much @petersowah !!! I scheduled a tweet to go out at the end of this week

**Comment by petersowah** [comment]
Thanks @ebarry. I do appreciate. Glad I could contribute. Unto the next one it is. 💯

**Pull request merged**
