### PR TITLE
added recent notes page

### LINKED ISSUE #2295: Unexpected behaviour of "notes" link on the dashboard welcome line
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

home-page-1
The link associated with "1 notes" in the above screenshot redirects to the dashboard page which is quite unexpected.

> What did you expect to see that you didn't?

There should be a separate recent notes page just like popular notes as shown in the following screenshot:-
popular-1

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

vidit

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #2295 

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
Certainly @jywarren , I'll add the tests. I'll take care of german translations in future. 
@SidharthBansal Thanks for the review, I'll add the screenshots

**Comment by ViditChitkara** [comment]
recent-notes-2
recent-notes-3
@jywarren I have written the tests and here are the screenshots

**Comment by jywarren** [comment]
Oh, sorry, looks like this needs one more conflict resolved! Ready to go once that's done! Thank you!!!!

**Comment by ViditChitkara** [comment]
@jywarren this should be working now!!! Please have a look

**Comment by jywarren** [comment]
Looks great. Thanks @ViditChitkara !!! Excellent work as always!

**Comment by ViditChitkara** [comment]
😃😃

**Pull request merged**
