### PR TITLE
added outreach note in email footers

### PR DESCRIPTION
**Pull request by ykl7**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ykl7** [comment]
Fix for #932 
Please check if outreach note has to be added to any other email templates or at a different position in the footer

**Comment by ykl7** [comment]
@jywarren Can you please help out with the notify_node_moderators test?

**Comment by jywarren** [comment]
Thank you, I'm sorry, there's a lot going on at the moment, and our annual
conference is beginning. But I'll do my best to find a moment to review and
provide feedback. Thanks.

**Comment by ykl7** [comment]
@jywarren I'll try to fix it myself. However, if you do get the time, I would appreciate your help.

**Comment by ykl7** [comment]
@jywarren I'm closing this PR and restarting the task afresh. It seems that Travis CI is detecting an error even if I add only the code you suggested in #932 
Hope that's ok

**Comment by jywarren** [comment]
Ah, you probably don't have to start a new Pr! You can just reopen this one
and it'll start running the tests again.

**Comment by ykl7** [comment]
@jywarren yeah I know but I wanted to restart clean. Please check #986 The same problem persists even though I just added the code suggested as a possible fix for #932

**Comment by jywarren** [comment]
Ok!

**Pull request closed without merging**
