### PR TITLE
add like feature for comments

### LINKED ISSUE #2498: add ability to like a comment
Just like on GitHub!

### PR DESCRIPTION
**Pull request by ViditChitkara**
closes #2498

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
 
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] PR body includes `fixes #0000`-style reference to original issue #
* [X] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Ooh, this is really nice. Almost ready to go, no? I see a test getting written -- i like this a lot! And i see you left the `likeable_type` over so we could specify emojis too 😄 🎉

**Comment by ViditChitkara** [comment]
Hi, sorry for the late reply--had an exam today. There are some changes to be made in tests, will ping once completed

**Comment by ViditChitkara** [comment]
@jywarren made certain test related changes. I guess, it is good to be merged now.

**Comment by ViditChitkara** [comment]
Don't know why the tests are failing. If you could have a look?

**Comment by jywarren** [comment]
Try rebasing over latest master; we just merged some fixes!

**Comment by ViditChitkara** [comment]
> Try rebasing over latest master; we just merged some fixes!

Thanks a ton!! So can we merge this if this looks good to you?

**Comment by jywarren** [comment]
Fantastic! Do you think we should think about refactoring the current Node like system? Don't have to think about this just yet. 

Maybe more pressing would be tests for the comment like system. Unit tests -- do you think you could add a few? Thanks!!

**Pull request merged**
