### PR TITLE
wip: refine print template

### PR DESCRIPTION
**Pull request by Tlazypanda**
Follow up pr to #8292 

- Opens the print in a new tab
- Remove the header/footer and other partials from print template

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi Sneha! Can you share a screenshot?

This looks great. For tests maybe some basic functional tests to confirm content on the page, and then perhaps some specific ones in a system test to look for how it handles dynamic content like inline grid tables, YouTube vids, things like that? That system test can be kind of a policy description of how we wish such content to be rendered for print. What do you think?

**Comment by Tlazypanda** [comment]
Hey @jywarren  @cesswairimu  while writing tests, I am facing this difficulty that my tests written are passing locally but on travis its showing wrong number of arguments (1,3) I looked it up and its a bug https://stackoverflow.com/questions/49151785/error-while-doing-escape-interpolation-inside-assert-select-in-rails-4-2 

Tests passing locally here 
Screenshot from 2020-08-30 22-34-39

Also for the system tests, right now I have just added a test to check a new tab is opened. For writing tests to check specific content, I will have to first add them to the revisions.yml file right? (like the video/inline table etc in markdown form) and then check for fetching those tags and if the styles are applied or not? :sweat_smile:  A bit new to this bit. Thanks :v:

**Comment by jywarren** [comment]
Hmm, is it a difference in the environment for Travis? I can dig into this more soon but could we either use a different kind of assertion or change the Travis config?

Yes, that's right we can change the fixture, or you could edit the node revision in Ruby in the test!

Finally, a functional test could work! However if we write a system test we can confirm if JavaScript works on the page as well, but it's up to you. I'm not sure if a functional test can test for a new tab though...? It might have to be an integration test. System tests are a little more expensive but much more powerful and closer to live usage. 

Thanks!!!

**Comment by Tlazypanda** [comment]
@jywarren Update here that changing the form of assertion from `assert_select` to` assert_equal` and` css_select` has resolved this issue and tests are passing now.

Now, will start working on inline tables and video tests :sweat_smile:

**Comment by jywarren** [comment]
This is awesome. Would you like to merge this and work progressively in add-on PRs? Or just wait a bit? Thanks a ton!!

**Comment by Tlazypanda** [comment]
Hey @jywarren Have added some more system tests to check blockquotes, videos, code blocks and tables. can you kindly review and let me know if this works? :sweat_smile: 

Also adding gif for showing the new tab change and also no nav bar 
print_new_tb

**Comment by jywarren** [comment]
I think this looks great! Let's merge it, what do you think?

**Comment by jywarren** [comment]
Can we keep headers in the same font, Junction light?

**Comment by Tlazypanda** [comment]
Yessss!! @jywarren if there are any more changes to be done please let me know I will take up in more follow up prs :sweat_smile:

**Comment by Tlazypanda** [comment]
Ohh yeah sure : sweat_smile: I will change that I used Arial because for printing it was the most suggested font

**Comment by Tlazypanda** [comment]
Hey @jywarren have changed the heading font to Junction light :sweat_smile:  sorry for the delay got busy with assignments

**Comment by jywarren** [comment]
No prob, and i think the fallback would be Arial if any issues occur with rendering Junction. Thanks! Merging!!!!

**Comment by jywarren** [comment]
Woohoo!!!

**Pull request merged**
