### PR TITLE
re-disable solr

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
ah, don't do this, it'll create a merge commit...

**Comment by jywarren** [comment]
yeah, it's weird, there's no fast-forward merge, so it creates a new commit in any of the options. too bad, because i'd like to see the tests run again...

**Comment by icarito** [comment]
I thought "rebase and merge" would do it.

**Comment by jywarren** [comment]
I believe it changes the commit hash, no? Maybe not...

**Comment by icarito** [comment]
I think that's the difference between squash and rebase?
I'll do it from the command line just to learn that.

**Pull request closed without merging**
