### PR TITLE
Fix overflow of tags in people section

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5857 https://github.com/publiclab/plots2/issues/5707 part

Screenshot from 2019-06-07 15-57-36

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @jywarren @Souravirus @gautamig54 I tried to fix the overflow of tags using css property. Is this okay? Or Is there any other method that you guys might have ?
Thanks !!

**Comment by CleverFool77** [comment]
Closing and opening PR for travis test

**Comment by jywarren** [comment]
Looks good!!!

**Comment by jywarren** [comment]
Great work!!!

**Pull request merged**
