### PR TITLE
User name Appearing Twice(#8687)

### LINKED ISSUE #8687: User name appears twice in the profile page
Make sure username doesn't  appear twice.

Screenshot from 2020-10-28 10-47-36

### PR DESCRIPTION
**Pull request by gauravahlawat81**
Fixes #8687

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Fixed the problem by using Bootstrap4 classes.

Screenshot from 2020-12-10 17-15-06

### CODE REVIEW

**Comment by gauravahlawat81** [comment]
@pydevsg Please review this PR and I am sorry for my last blunder, I humbly request for your guidance and patience as I am quite new to Git .Thanks !

**Comment by RuthNjeri** [comment]
This looks good to me @gauravahlawat81 😄

**Review by RuthNjeri — APPROVED** [review]

**Comment by cesswairimu** [comment]
Great :tada: , @gauravahlawat81  do you mind rebasing this so that the test-runner can rerun the tests? Please let me know if you need any help with that. Thanks for working on this

**Comment by gauravahlawat81** [comment]
@cesswairimu I don't know how to rebase, I have tried that once already and I couldn't do it properly. Do you mind telling me how can I rebase ? I am currently on branch `User-Name-Appearing-Twice`. Thanks!

**Comment by cesswairimu** [comment]
Yes sure.

Steps to Rebase
-----------------------------
assuming you have named the publiclab remote "upstream"
```
$ git checkout main
$ git pull upstream main
$ git checkout User-Name-Appearing-Twice
$ git rebase -i main 
```
The last command opens a editor  with your commits, save and exit 
Then push your branch back up. You might need to force push `$ git push -f origin User-Name-Appearing-Twice`
Ping me if you get any prob

**Comment by gauravahlawat81** [comment]
@cesswairimu I have successfully completed rebase. Thank you so much for your help. But my changes are failing tests, any idea how can I solve that? I have only changed one file and I don't see how I could have broken anything else. Can you help me here ?

**Comment by cesswairimu** [comment]
That is strange and its definately not your changes, seems like ci its failing before the tests are ran...I will take a deeper look  later today and get back to you. Thanks

**Comment by gauravahlawat81** [comment]
Oh, alright. Let me know if I can be of any help.

**Comment by cesswairimu** [comment]
I was just creating an issue for this here https://github.com/publiclab/plots2/issues/8873 but I see you were able to make them pass :tada: how did you do that?

But now looks like code climate is having an issue reporting the status :facepalm:

**Review by cesswairimu — APPROVED** [review]
:tada:

**Comment by cesswairimu** [comment]
I will just go ahead and try to merge this, code climate has passed successfully but somehow its not reporting the status above.

**Comment by cesswairimu** [comment]
Thanks for your patience and thanks a lot for working on this

**Comment by gauravahlawat81** [comment]
> I was just creating an issue for this here #8873 but I see you were able to make them pass  how did you do that?

Weirdly enough, I didn't do anything. I just rebased my local git repo again. Maybe that did something to pass the test. It might need further investigation, but for the time being I am happy that my first PR got merged. Hoping to make much more contributions. Thanks!

**Comment by cesswairimu** [comment]
Yeah that is weird, anyways, welcome to to PublicLab :balloon: and we would love your help. Thanks

**Pull request merged**
