### PR TITLE
FIX: signup form validation on page reload

### LINKED ISSUE #7618: Signup button gets disabled permanently after errors
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The signup button gets disabled permanently after we try to signup when some error occurs.

> What did you expect to see that you didn't?
it must not be disabled permanently
**Current Behaviour**
Untitled_ Mar 8, 2020 10_45 PM

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by shreyaa-s**
Fixes #7618 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

This PR fixes the sign up form validation. Earlier if the form encountered an error like email already registered, then even after changing the email the sign up button would remain disabled unless all input fields were changed. This PR fixes the issue.

Thanks!

### CODE REVIEW

**Comment by shreyaa-s** [comment]
simplescreenrecorder-2020-03-23_18 49 17
These are the implemented changes.

**Comment by shreyaa-s** [comment]
Please have a look at it when you have a moment. I messed up the last PR because of issues with my laptop and had to use someone else's.

**Comment by shreyaa-s** [comment]
@jywarren @cesswairimu @emilyashley @VladimirMikulic @SidharthBansal @govindgoel  please review it and convey the requested changes. I'm aware that I haven't used the best practice to check if email input is valid but I still have queries regarding how to access the returned result of queries. I'll fix this as soon as I get them cleared. Meanwhile, since this was an issue of high priority I've opened a PR with a possible solution.

**Comment by shreyaa-s** [comment]
@ananyaarun done! Thanks for mentioning it.

**Comment by SidharthBansal** [comment]
Can we write a system test to ensure this?
Thanks for working on this!

**Comment by shreyaa-s** [comment]
@SidharthBansal I don't have any prior experience with writing system tests. I would love to give it a try though. Could you brief me about it a little? Thanks!

**Comment by jywarren** [comment]
Hi, there are some good examples here; basically you can interact with the page using various commands, and it "autopilots" the browser to run through tests interactively:

https://github.com/publiclab/plots2/blob/master/test/system/sessions_test.rb

There is more documentation here! https://github.com/publiclab/plots2/blob/master/SYSTEM_TESTS.md

**Comment by jywarren** [comment]
Thank you so much!

**Comment by shreyaa-s** [comment]
I'm learning to write system tests on Ruby. I'm thinking along the lines of writing a system test that would first stimulate a user that is already registered, like 'Jeff', check if error is thrown and if so, it would then stimulate a newcomer and check for successful registration. Is this the right way? Correct me if I am wrong. And what are your expectations with the signup test?
Thanks!

**Comment by shreyaa-s** [comment]
@jywarren I've written the system test and tested it locally but the build is failing, can you help me figure out why? Thanks!

**Comment by shreyaa-s** [comment]
@jywarren  I found the error and fixed it. Please review. Thanks!

**Comment by jywarren** [comment]
Hi @shreyaa-s this is a really well written PR. Great work. Before merging it, I want to see if we need to think through some of the issues I've written up here: https://github.com/publiclab/plots2/issues/7816

Thanks, then we can make a call on merging this!

**Comment by shreyaa-s** [comment]
To address the issues discussed in #7816 , I've only changed how the individual validation functions are called rather than the function itself. Earlier the functions were called only when the respective input field witnessed a change. As for the above mentioned, `not the best practice`, since I didn't know how to access the result of server-side validation, I checked if the error messages at top mentioned `email`.

**Comment by cesswairimu** [comment]
restarting travis

**Comment by jywarren** [comment]
Ack, so sorry I missed this! All good here, many many thanks to everyone! 👍 🎉 🎉 🎉 🎉

**Comment by jywarren** [comment]
Would someone be able to test this out on https://stable.publiclab.org quickly once it's done building? Just to be sure as it's a critical system. Thanks!!!

**Comment by cesswairimu** [comment]
I just tested on stable, its working great. Thanks everyone :tada:

**Pull request merged**
