### PR TITLE
Reload fucntion added upon adding location tags

### LINKED ISSUE #7359: Refresh page upon adding location tags
I heard from someone who was confused as to why the map didn't appear upon adding location tags, so I think we should initiate a page refresh when that happens -- what do you think, @nstjean @crisner -- does this makes sense? We could just do this in JS after hearing a success for the tag POST? 

Thanks! Just a thought that this might be a better user experience!

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes #7359 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@nstjean Can you help me with this error?
Screenshot from 2020-02-17 15-09-04

**Comment by NitinBhasneria** [comment]
@nstjean I dont know but my travis test are failing do you know the reason.

**Comment by nstjean** [comment]
Ahhhh. Ok. So what's happening is that the test is looking for that badge to pop up immediately just like it usually does when you add a tag. They get added to the page using Javascript. Here's what it looks like when I add two tags without a refresh:
FireShot Capture 290 - 🎈 Public Lab_ Media - localhost

The problem is, we are now reloading the page which makes it look differently. After refresh:
FireShot Capture 291 - 🎈 Public Lab_ Media - localhost

When you click on the `...` button it shows all the tags:

FireShot Capture 293 - 🎈 Public Lab_ Media - localhost

So in the test we're going to tell it to click on the `...` button before checking for those tag badges.

Here is the test:
https://github.com/publiclab/plots2/blob/8d2efcb96e9643a74957d5cdde208f21d01360fb/test/system/post_test.rb#L195-L215

Right after `wait_for_ajax` we want to add this:
```
find('.tags-list a.show-more-tags').click()
```
That will click on the button to show all the badges! Then the test will be able to find the new tags and pass the test. :)

**Comment by NitinBhasneria** [comment]
Oh ok thanks @nstjean I will try this.

**Comment by NitinBhasneria** [comment]
@nstjean THanks all the checks have passed please review this @cesswairimu .

**Pull request merged**
