### PR TITLE
Update _comment.html.erb

### PR DESCRIPTION
**Pull request by marshatiisa**
Hey, can you review this? @TildaDares @jywarren

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @marshatiisa, can you add the issue number in the format `fixes #0000`? Thanks!

**Comment by marshatiisa** [comment]
This fixes #10955

**Comment by marshatiisa** [comment]
Fixes #10947

**Comment by TildaDares** [comment]
Thanks for working on this PR but #10947 has not been approved and when it is, it's reserved for first-timers only.

**Comment by marshatiisa** [comment]
Okay then @TildaDares

**Comment by TildaDares** [comment]
@marshatiisa Since you've worked on an FTO, you can try opening one for someone else. Some contributors are creating FTOs from https://github.com/publiclab/plots2/issues/10952. If you want, you can pick a task and create an FTO from it. If you don't understand anything or need help, feel free to reach out to me.

**Comment by marshatiisa** [comment]
@TildaDares okay thanks. Will do

**Comment by TildaDares** [comment]
I think you can close this PR now. Thanks!

**Pull request closed without merging**
