### PR TITLE
Updated 503.html

### PR DESCRIPTION
**Pull request by Crisoal**
changed <hr/> to <hr> tag in lines 46 & 62

Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @Crisoal, it’s better to open one PR for the changes that are required of you. Can you close the rest PRs and leave this one open? I’ll guide you on how to add the rest changes to this PR.

**Comment by Crisoal** [comment]
> Hi @Crisoal, it’s better to open one PR for the changes that are required of you. Can you close the rest PRs and leave this one open? I’ll guide you on how to add the rest changes to this PR.

I have closed the other pull requests

**Comment by TildaDares** [comment]
@Crisoal I recorded a video of how you're going to edit the remaining files. Go back to the issue you were assigned and check which lines you're supposed to change.

https://user-images.githubusercontent.com/63427719/164709052-01bb2244-86c0-4064-8450-326843829e4c.mp4

**Comment by TildaDares** [comment]
[404.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/404.html) (Line 62)

[422.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/422.html) (Lines 45 and 63)

[500.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/500.html) (Lines 43, 47, 65)

[502.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/502.html) (Lines 46, 62)

[503.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/503.html) (Lines 46, 62)

**Comment by Crisoal** [comment]
> @Crisoal I recorded a video of how you're going to edit the remaining files. Go back to the issue you were assigned and check which lines you're supposed to change.
> 
>  Untitled.mp4

ok, thank you

**Pull request closed without merging**
