### PR TITLE
remove "everything" tag from tag notifications -- fixes #1692

### LINKED ISSUE #1692: add an exception to list of users to be notified upon new tag addition, for those subscribed to 'everything'
### What happened just before the problem occurred

This is with reference to issue #1630 .
A user subscribed to 'everything' should not get email when a Tag is added to the content because they were already notified when the content was added .

### Relevant URLs

https://github.com/publiclab/plots2/blob/master/app/mailers/subscription_mailer.rb
https://github.com/publiclab/plots2/blob/master/app/models/tag_selection.rb
https://github.com/publiclab/plots2/blob/master/app/models/tag.rb

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
1.) Indentation done .
2.) Error removed
This solves the issue #1692 .

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Working on getting the errors fixed .

**Comment by jywarren** [comment]
Hey, it works! This looks great, good job! 

I do want to ask if you'd be willing to make one more addition. If you could add a test for this method, that would be great! Take a look at how testing is already done on this file here: 

https://github.com/publiclab/plots2/blob/master/test/unit/subscription_mailer_test.rb

I think it would not be too difficult to add an additional test that demonstrates that an "everything" follower doesn't get notified -- what do you think? Perhaps as a unique test at the end, named something informative?

**Comment by sagarpreet-chadha** [comment]
Yes sir...I would love to ! Thanks !

**Comment by sagarpreet-chadha** [comment]
As there is already a test that checks that whether users have already recieved email due to other Tags associated with that Node , so i just added line 72 , 73 to exclude those users also which are subscribed to 'everything' Tag .

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...kindly review this ! Thanks !

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...yes sir that makes sense ! Thank you for pointing that out !

**Comment by jywarren** [comment]
Super!!! Hey, you're doing some great work. Do you have any interest in helping to prepare some first-timers-only issues yourself, or respond to some other submissions to help others along? 

There's some guidance on this here, and we'd love to have your involvement: https://github.com/publiclab/plots2/projects/4

**Comment by sagarpreet-chadha** [comment]
Yes Sir...I would love to do that !! Thank you .

**Pull request merged**
