### PR TITLE
[testing] Remove sudo from npm install bower and add a note

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

Removed sudo from `npm install -g bower` and added a note for those struggling to use `npm install` without `sudo`. Also, added a warning listing possible threats.

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Please review. 

Also, do the PRs for hacktoberfest need to be labelled so or do any 4 PRs count?

**Comment by jywarren** [comment]
Hello - i hope to review and merge in the next two days -- apologies, but I'm currently in a staff retreat and won't be able to today! Thank you very much for your contribution. 

I did check why the tests failed, and sometimes they do simply during downloading of dependencies and not due to new code. I restarted it so we'll see if it runs properly. Thanks again!

**Comment by ryzokuken** [comment]
@jywarren Also, I was curious if you guys had an official gitter channel or maybe a slack for devs... 

That way, the devs would be able to get each other's statuses more efficiently, and newcomers like me would know where to go to in case I needed help from one of you.

**Comment by jywarren** [comment]
Hi, yes, this has come up multiple times recently and I'll bring it up with our community team this week. I agree that it'd be very helpful -- however we have a mailing list for questions (for the time being) at: https://groups.google.com/forum/#!forum/plots-dev

**Comment by ryzokuken** [comment]
Thanks! But personally, I feel a realtime chat beats everything else. Maybe repopulating the IRC channel?

**Comment by jywarren** [comment]
Thanks, I'll definitely forward the request.

**Pull request merged**
