### PR TITLE
Redesigning the search bar

### PR DESCRIPTION
**Pull request by divyabaid16**
From pull request #5121 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Fixed the issue in Google Chrome.
Selection_079

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
Google chrome view of page when I ran this PR
Screenshot from 2019-03-19 18-46-07

The thing in discussion at #5121 is the width of search bar right?

**Comment by divyabaid16** [comment]
@gauravano 
I had set the minimun width to 270 px. 
So I think that size of the search bar should increase.

**Comment by divyabaid16** [comment]
> The thing in discussion at #5121 is the width of search bar right?

@gauravano  Yes.

**Comment by gauravano** [comment]
I think it's fine to have the current size too?  Let's try by adding 50/60 px more, but yes see mobile-view too along the changes. Thanks @divyabaid16

**Comment by divyabaid16** [comment]
@gauravano when I decrease the screen size upto the size of mobile view, 270px is the maximum value that can be allowed that is compatible with the small screen.

**Comment by divyabaid16** [comment]
after the change, the gif that is getting is as follows @gauravano @jywarren 
Peek 2019-03-20 17-43

**Comment by jywarren** [comment]
Hi! just chiming in to mention that several related changes were merged, so we'll need to be sure this works on top of those changes:

https://publiclab.org/tags

It's looking great! Thank you!

**Comment by divyabaid16** [comment]
@jywarren Now the changes are in sync with the master branch.

**Comment by SidharthBansal** [comment]
There are some conflicts in your pr. It will be great if you can rebase your pr.
Thanks for the work done here at PL

**Comment by divyabaid16** [comment]
I will do it very soon @SidharthBansal 
Thanks!

**Comment by divyabaid16** [comment]
Hi!!!
This issue has been fixed in the PR #5483 by @gautamig54 hence I'm closing it down.
Thanks!

**Comment by gauravano** [comment]
Ok. Thanks @divyabaid16!

**Pull request closed without merging**
