### PR TITLE
Create update_issue_#11009

### PR DESCRIPTION
**Pull request by ayish1998**
Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by ayish1998** [comment]
@TildaDares can u review on this please

**Comment by Somya-Singhal** [comment]
Hello @ayish1998, you have to mention the issue number which is linked with this pull request in place of #0000. Thank you!
image

I am attaching a sample screenshot below, you can refer to it
image

**Comment by ayish1998** [comment]
hello @Somya-Singhal thank you

**Comment by TildaDares** [comment]
Hi @ayish1998, can you add the issue link to the description above? The issue number is at the top of the page(next to the issue title) you were assigned and starts with `#`. Thanks!

**Comment by TildaDares** [comment]
Hi @ayish1998, you are not supposed to replace the entire content of the file. The lines in red should be removed and the ones in green should be added. Can you take a look at the issue again and read the description? Thanks!!

**Comment by ayish1998** [comment]
@TildaDares that's exactly what I actually did. I removed the ones with red highlights and replaced them with the green.

**Comment by TildaDares** [comment]
@ayish1998 Actually it looks like you copied everything.

**Comment by TildaDares** [comment]
Hi @ayish1998, do you need help with this?

**Comment by ayish1998** [comment]
@TildaDares I think so because I don't really know if the instruction I followed is not what is expected.

**Comment by TildaDares** [comment]
- [ ] Go to the file https://github.com/publiclab/plots2/blob/main/app/views/spam2/_queue.html.erb
- [ ] Remove lines 2 - 22 and replace with this https://pastebin.com/98ve5E5S
- [ ] Remove line 88 and replace with `notyNotification('relax', 3000, 'danger', 'topRight', 'Node deleted');
`
- [ ] Save and push

**Comment by TildaDares** [comment]
Hi @ayish1998, any updates on this?

**Comment by ayish1998** [comment]
> ### All checks have passed
> 11 successful checks

**Comment by ayish1998** [comment]
@TildaDares sorry for the late response, I was having exams. Yes, I think I need help.

**Comment by TildaDares** [comment]
Hi @ayish1998, just follow the steps I outlined here https://github.com/publiclab/plots2/pull/11044#issuecomment-1099517557.

**Comment by ayish1998** [comment]
@TildaDares Please on the project timeline, do you have a specific comment on this?

**Comment by TildaDares** [comment]
@ayish1998 You’re expected to break down the project tasks into smaller parts for each week.

**Comment by ayish1998** [comment]
@TildaDares Please do that means I will choose my timing?

**Comment by TildaDares** [comment]
Yes you choose your timing.

**Comment by ayish1998** [comment]
Thank you @TildaDares

**Pull request closed without merging**
