### PR TITLE
bios made searchable in user.rb

### PR DESCRIPTION
**Pull request by ekeast**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, looks like you deleted a few files by mistake? But the changes look great! So fast!

**Comment by ekeast** [comment]
Sorry! I am not sure how that happened, I'm still new at this

**Comment by jywarren** [comment]
No problem at all! This is why we're here to help. I believe you can follow
this guide:

https://stackoverflow.com/questions/7147270/hard-reset-of-a-single-file

**Comment by jywarren** [comment]
Hey, this looks super! Thanks so much! Merging now.

**Comment by jywarren** [comment]
Very helpful! 🎉 

If you're interested, we'd love to have your help with other issues! 

https://publiclab.github.io/community-toolbox/

**Comment by ekeast** [comment]
I definitely will! Thanks a lot, Jeff.

**Pull request merged**
