### PR TITLE
Routes for sorting tags changed

### PR DESCRIPTION
**Pull request by Gauravano**
I am attempting to make routes for sorting tags user-friendly as suggested by @jywarren in https://github.com/publiclab/plots2/pull/2139#issuecomment-362709390

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! In keeping with our new ideas at #2231, i'm going to request one more review! Thank you!!!

**Comment by SidharthBansal** [comment]
@Gauravano can you please link to the issue number or if it is a small bug fix then explain it in the pr's body??

**Comment by Gauravano** [comment]
Hi @SidharthBansal please see https://github.com/publiclab/plots2/pull/2139#issuecomment-362709390 for reference.Thanks.

**Comment by Gauravano** [comment]
Hey, @SidharthBansal it would be really helpful if you can have a look as its ready.Thanks.

**Comment by SidharthBansal** [comment]
Sorry for replying late. I was a little busy with college work

**Comment by Gauravano** [comment]
No problem

**Comment by Gauravano** [comment]
@jywarren I guess its ready now.please have a final review.Thanks.

**Comment by jywarren** [comment]
Ooh, this is a nice implementation. I like it! 👍 👍 👍

**Pull request merged**
