### PR TITLE
testing inconsistencies tests

### PR DESCRIPTION
**Pull request by jywarren**
Followup to #1058

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren all other PRs are failing as well. This looks confusing.

**Comment by jywarren** [comment]
I think it could be the **order** of the tags in `assigns(:notes)` ...? But should also check on the `node.tags` method, which is just an alias for an ActiveRecord relation to `drupal_tag`.

**Comment by jywarren** [comment]
Yes, that's why this is urgent, apologies!

**Comment by jywarren** [comment]
By comparison, my local shows:

```ruby
[#<DrupalNode nid: 1, vid: 0, type: "note", language: "", title: "Canon A1200 IR conversion at PLOTS Barnraising at L...", uid: 2, status: 1, created: 1480961718, changed: 1480961718, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 0, path: "/notes/jeff/12-05-2016/canon-a1200-ir-conversion-at...", main_image_id: nil, slug: "jeff-12-05-2016-canon-a1200-ir-conversion-at-plots-...">, #<DrupalNode nid: 13, vid: 0, type: "note", language: "", title: "Blog post", uid: 2, status: 1, created: 1480961718, changed: 1480961718, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 0, path: "/notes/jeff/12-05-2016/blog-post", main_image_id: nil, slug: "jeff-12-05-2016-blog-post">]
```

And Travis:

```ruby
[#<DrupalNode nid: 1, vid: 0, type: "note", language: "", title: "Canon A1200 IR conversion at PLOTS Barnraising at L...", uid: 2, status: 1, created: 1480961344, changed: 1480961344, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 0, path: "/notes/jeff/12-05-2016/canon-a1200-ir-conversion-at...", main_image_id: nil, slug: "jeff-12-05-2016-canon-a1200-ir-conversion-at-plots-...">, #<DrupalNode nid: 13, vid: 0, type: "note", language: "", title: "Blog post", uid: 2, status: 1, created: 1480961344, changed: 1480961344, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 0, path: "/notes/jeff/12-05-2016/blog-post", main_image_id: nil, slug: "jeff-12-05-2016-blog-post">]
```

**Comment by jywarren** [comment]
It really is that in local, you get the tag `spectrometER`, and in Travis, you get `spectrometRY`. Aaaahhhh!

**Comment by jywarren** [comment]
OK - i think i may be making progress. I checked and my (and everyone else's, maybe? @ashleypt @ryzokuken ?) local tests are running on `sqlite`, but Travis runs them on `mysql` -- and this line of `drupal_node` uses a "LIKE" match: 

https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L424-L429

I'm running tests with mysql now to check this theory.

**Comment by jywarren** [comment]
Nope - at least with `mysql2` in `config/database.yml`, my local gets `spectrometER`, unlike the latest build https://travis-ci.org/publiclab/plots2/builds/181437468 which gets `spectrometRY`. 

Hmmmmmmm.

**Comment by jywarren** [comment]
OK, as close as I can see, this method: 

```ruby
     tags = DrupalTag.includes(:drupal_node_community_tag)
                     .where("community_tags.nid = ? AND name LIKE ?", self.id, tagname)
```

in `node.get_matching_tags_without_aliasing()` returns something different between local and travisci, not sure why. 

I just commented out the new `can_tag` code and tests to see if it fails even then... we could roll all the way back if need be?

**Comment by jywarren** [comment]
OK -- what do you know? Removing the code makes it pass. Now i'll re-enable one by one.

**Comment by jywarren** [comment]
Aaaaah! this code passes! So the problem is in the unit tests, somehow: https://travis-ci.org/publiclab/plots2/builds/181505988

**Comment by jywarren** [comment]
Great, one test back on -- i'm going to do this test by test.

**Comment by jywarren** [comment]
OK @ashleypt @ryzokuken -- found the two tests that cause the other test to fail and commented them out. I'm going to merge this and open a new issue for the remaining ones, once this squashed commit builds.

**Comment by jywarren** [comment]
Followup in #1064

**Pull request merged**
