### PR TITLE
Update not working issue

### LINKED ISSUE #2905: Editing of research note giving 500
Saving an edit to the research note is throwing error 500. Logs for the same are 

logs

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2905 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
`render text:` is deprecated in Rails 5.1 and above, so it was also giving error at other places too like during tag deletion. So, I have changed it to `render plain:` at other places too. @Souravirus please review it. Thanks.

**Comment by jywarren** [comment]
Oh cool! Are there any tests we could add to have caught this? Thanks!!!

**Comment by Gauravano** [comment]
yes, we can add tests for future! Will ping you after adding some tests. Thanks!

**Comment by Souravirus** [comment]
Hi @jywarren, in the image_controller, we want to test for the `render plain: 'The image could not be saved.'`  on line 39. But the thing is that we can't find a way for testing it. It can only be tested if the new image object is not saved in database. In the test we tried to change the path of photo as well as removed as many as attributes as we can. But the photo attribute is necessary in the test otherwise it gives error. So, how to test this?

**Comment by jywarren** [comment]
Should I merge this now and we can add tests in follow-up?

**Comment by Souravirus** [comment]
Yeah merge this as some users might need editing of research note. Thank you!!

**Pull request merged**
