### PR TITLE
fixed popup width error

### LINKED ISSUE #7714: Width refinement to map popup display in CSS
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

You can now see this mapping library on by default at:

https://stable.publiclab.org/map#7/41.14399650184958/-71.81762695312501

I'd like to suggest we narrow the popups a bit, to maybe 300px? They seem excessively wide. Is there a way to let them auto-size, or use the default?

image

Citing @jessibreen below:

It looks like the width of the popup is set in the css for that page. It has an important flag on it, so it is overriding the leaflet default of 300.

The bug is at lines 20 and 21 in https://github.com/publiclab/plots2/tree/master/app/assets/map.css

Get rid of this:

```css
.leaflet-popup-content {
width: 800px !important;
}
```
...and the popup boxes will default to their usual 300 px width.

### PR DESCRIPTION
**Pull request by jessibreen**
Fixes #7714 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jessibreen** [comment]
@publiclab/reviewers Hi, first try doing this. I made this pull request into master because I didn't know about the feature branch process before the checklist came up in response to the pull request. Let me know if there's something I need to do to make this work better!

**Comment by jessibreen** [comment]
@sagarpreet-chadha I tested it out on my locally hosted copy of the site and it doesn't appear to cause any new problems. It worked as expected on the maps located under Community > People and Community > Places. 

It was an odd little snippet of code. Everything else in that css file was setting a z-level for various elements and that one piece was altering the popup widths.

**Comment by jessibreen** [comment]
@pydevsg Do you mean the code? Or the popups themselves?

**Comment by pydevsg** [comment]
I mean the pop up @jessibreen , thanks.

**Comment by jessibreen** [comment]
Before:
Screen Shot 2020-03-25 at 12 23 11 PM

After:
Screen Shot 2020-03-25 at 12 21 08 PM

**Comment by sagarpreet-chadha** [comment]
Awesome thanks!!!

**Comment by jessibreen** [comment]
@pydevsg @sagarpreet-chadha @jywarren Anything else I need to do to get this merged?

**Comment by pydevsg** [comment]
No, you don't @jessibreen .
cc- @jywarren , @cesswairimu

**Comment by cesswairimu** [comment]
Wooh! was solving merge conflicts and accidentally merged the branch.. @jessibreen in future, please create a new branch for the issue. Thanks for working on this

**Comment by cesswairimu** [comment]
Welcom to PublicLab @jessibreen :balloon:

**Comment by jessibreen** [comment]
@cesswairimu Thanks!

**Comment by jywarren** [comment]
This is very awesome. Thank you @jessibreen and all!!! 🎉

**Pull request merged**
