### PR TITLE
Added "Reply to this email to post a response" to various email templates

### LINKED ISSUE #3323: Add "Reply to this email to post a response" to various email templates
Now that we have the fabulous new reply by email system and it's running pretty reliably, we should actually tell people that they can respond by email!

A message like in the title could fit in multiple places. 

image

The various comment templates where we need to add this message (which could be broken into separate issues, so several people can solve this one!) can be found here:

https://github.com/publiclab/plots2/tree/master/app/views/comment_mailer

For each, the current message that says `Do NOT reply...` should be changed to show that `You can reply by email OR visit this link ______`:

https://github.com/publiclab/plots2/blob/60c95f0764036de8a6cac9732fb24896260e517b/app/views/comment_mailer/notify.html.erb#L1-L7

### PR DESCRIPTION
**Pull request by geekychaser**
Fixes #3323

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Just remember to commit from a new branch created instead of master. You can do this from next time.

Thanks for contributing at Public Lab. We really appreciate your time at our community.

**Comment by SidharthBansal** [comment]
Patches looks good to me. @jywarren can you kindly review this and merge this one?

Thanks all.

**Comment by jywarren** [comment]
This looks great. I'm going to make a small change to "reply to THIS email" just in case it's unclear. Then i'll merge! This is fantastic -- great job! 👍 🎉 🎈

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Pull request merged**
