### PR TITLE
Post your work

### LINKED ISSUE #4194: Link login modal to 'post your work' under 'Get Involved' tab
Link the newly added login modal here at `Post your work` under the `Get Involved` tab.

publiclab_adiyenvironme

### PR DESCRIPTION
**Pull request by JonathanXu1**
Fixes #4194

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

When the user clicks **Post your work** under the **Get Involved tab**, a login modal pops up if the user is not logged in.
Gif demo:
ezgif com-video-to-gif

I can't demo logging in on the modal because I'm on cloud 9 and the localhost redirect link won't work. But here you can see that when login is completed, the user gets automatically routed to /post .

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Fix seems to be correct. But there is some problem on code climate. I think you can take this task. I will approve it.

**Comment by JonathanXu1** [comment]
Thanks. Can I get a link to the task name?
image

**Comment by SidharthBansal** [comment]
try searching post keyword

**Comment by JonathanXu1** [comment]
image

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/5382165610102784/

**Comment by kevinzluo** [comment]
@SidharthBansal @JonathanXu1 I was wondering how you managed to get the page to redirect to Post and tried it on my own computer, but it didn't redirect me to Post. I think it does in your gif because the last request was to the Post page. 

I think you might need to create an AJAX request like I did in https://github.com/publiclab/plots2/pull/4239 (the `getJSON` request`) or modify the return_to.

shownotworking

**Comment by SidharthBansal** [comment]
Jonathan might help you in this regard

**Comment by kevinzluo** [comment]
@SidharthBansal I was stating that this PR was not redirecting, not my own. Sorry for the confusion.

**Comment by JonathanXu1** [comment]
@kevinzluo hmm thanks for pointing it out. I'm looking into it.

**Comment by JonathanXu1** [comment]
@SidharthBansal You can click on the gif for a better quality rendering. Do you need another screenshot for something else? I'm using c9 by the way
@kevinzluo is this the line that changes the url and loads the page to a specific link?     
```
anchor.on('click', function() {
      $.getJSON(href);
    });
```

**Comment by SidharthBansal** [comment]
@JonathanXu1 can you provide another gif for the behaviour at the localhost?

**Comment by JonathanXu1** [comment]
@SidharthBansal this is what happens when I login with the modal:
ezgif com-video-to-gif
Not sure why it works when I login through the login page..

**Comment by gauravano** [comment]
@JonathanXu1 see the URL carefully. You are trying to login to localhost from cloud9, it will give error as server is not running at localhost. Makes sense?

**Comment by kevinzluo** [comment]
Yep that is the line @JonathanXu1 . Sorry for the late reply.

**Comment by JonathanXu1** [comment]
@gauravano I think it has to do with the routing of the login, which would be unnoticeable when testing on localhost. Not sure where to look to fix this issue though..

**Comment by gauravano** [comment]
Change login route for posting screenshot.

**Comment by SidharthBansal** [comment]
@JonathanXu1 can you please make your branch consistent with the current master and try out it again.
There might be some deletions and some additions in this pr too. Please send the changes whenever you get time.

**Comment by JonathanXu1** [comment]
Sorry I was working on uni apps. I'm able to look at it now.

**Comment by kevinzluo** [comment]
@JonathanXu1 
Try out the changes from https://github.com/publiclab/plots2/pull/4334 but no need to commit them.

**Comment by SidharthBansal** [comment]
@JonathanXu1 how is it going ?

**Comment by SidharthBansal** [comment]
>>I cannot verify that the redirect works because the cloud 9 server still redirects to the localhost link.

We have solved this issue. You can try again.
Thanks

**Comment by JonathanXu1** [comment]
@SidharthBansal on cloud 9 it is still reloading to localhost. I'm currently installing plots2 on Ubuntu on Windows on another computer. I'll let you know how it goes. Thanks for your patience.

**Comment by oorjitchowdhary** [comment]
Hi all, after the updates on `requireLogin`, I think this will work now...
@JonathanXu1 Can you please test out the behaviour?
Thanks

**Comment by SidharthBansal** [comment]
@jywarren tested it on local host so merging it up.
Thanks all

**Pull request merged**
