### PR TITLE
[WIP] Replace markdown parser rdiscount with redcarpet

### LINKED ISSUE #3889: Replace markdown renderer in ruby
We are using RDiscount for rendering markdown to html but it's quite old and unmaintained library. We should switch to better one like https://github.com/vmg/redcarpet or https://github.com/github/markup

### PR DESCRIPTION
**Pull request by Radhikadua123**
Replacing out dated markdown parser 

Fixes #3889

### CODE REVIEW

**Comment by Radhikadua123** [comment]
@jywarren I was thinking if we should switch to gfm markdown ? https://github.github.com/gfm/

It's exact same one used by github README files, PR/Issues comments etc.

**Comment by jywarren** [comment]
That'd be great... Maybe worth checking on unstable that a lot of our more
complex markdown gets properly displayed? Pages with tables, code ```
stuff, maybe you can use the search function to find such pages for testing
purposes?

**Comment by Radhikadua123** [comment]
> Pages with tables, code ``` stuff, maybe you can use the search function to find such pages for testing purposes?

True. I also faced the same problem with code. That's why I created that issue and after using redcarpet, I got to know the MD format it supports, it's different from gfm standard.

I'll try to incorporate it and test it out.

**Comment by jywarren** [comment]
awesome!

**Comment by dinaelhanan** [comment]
Hey! You've got a few conflicts @Radhikadua123 Also, be sure to check out PlotsBot's suggestion:
`This pull request doesn’t link to a issue number. Please refer to the issue it fixes (if any) in the body of your PR, in the format: Fixes #123.`

**Comment by SidharthBansal** [comment]
Can I offer you some help here @Radhikadua123 ?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
