### PR TITLE
Translation: Put single/double quotes around values in config/locales/controllers files

### LINKED ISSUE #4729: Putting single/double quotes around values in locale files
Hi! we are working on combining all the YAML files into language specific files at #4702. After combining the locales using the ruby script, a issue has came to our attention. The issue is the string values of the keys doesn't have double quotes around them. 

Although, some of the translations has been tested locally and they are working fine but for removing any unexpected issue in future, it's best to put the quotes around those string values which contained them originally. So, what needs to be done(in short, but lengthy work :package:)

Put quotes around the string values of this file - https://github.com/publiclab/plots2/pull/4716/files#diff-37c9b835927e3c363588f172de9bb6fa . You have to refer this folder to refer strings original form. Also, if during the process, if you find any key-val pair absent please make a list and comment below. Thanks!

### PR DESCRIPTION
**Pull request by akshaygupta533**
Fixes #4729 #4702

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by akshaygupta533** [comment]
@gauravano

**Comment by gauravano** [comment]
Hi @akshaygupta533, thanks for the work. Have you compared the quotes for the entire file or just after the line 756 because there is no change before that in your commit. 

I ran the PR locally and after running across Google searches, I found the error using YamlLint - https://github.com/adrienverge/yamllint. I am correcting the error. 

Thanks!

**Comment by akshaygupta533** [comment]
@gauravano I just compared the strings in the controller files. If there's anything else to do, let me know.

**Comment by gauravano** [comment]
Yes, comparison has to be done for all the files present in the locales
folder.

**Comment by gauravano** [comment]
Hi @akshaygupta533, is it possible for you to complete this PR by Monday as this combined file has to be tested and uploaded to Transifex too for the Translation & review process to begin?  Also, you can update the status here like which folders from the original file structure you have compared, and I can complete the remaining folders. What do you say?

Also, thanks for great work on it till now!!

**Comment by akshaygupta533** [comment]
@gauravano Sorry for the late response. I was caught up with my mid term exams. I can complete this by tomorrow(11th Feb) afternoon.

**Comment by gauravano** [comment]
Oh, no issue Akshay! All the best for your exams and if you want I can
complete the remaining bits? Thanks!

**Comment by akshaygupta533** [comment]
I'll do it. No worries, thanks:)

**Comment by akshaygupta533** [comment]
@gauravano pls check

**Comment by gauravano** [comment]
@akshaygupta533 I will take a look and solve the merge conflict too. Thanks for completing it in-between your exams.

**Comment by gauravano** [comment]
Hi @jywarren, the PR I opened at #4716 which intends to combine YML files is merged in this one only and   @akshaygupta533 and I have put quotes over the en translation values. I have also put double quotes at some places where it wasn't present before just to maintain the uniform syntax of the combined file.

Now, pushing this PR to `unstable` for final testing and then we can merge this. Thanks!

**Comment by gauravano** [comment]
@jywarren please review this PR and you can test the changes at unstable too. Thanks!

**Comment by jywarren** [comment]
Looks awesome everyone! Great work here. Thanks!!! 👍 👍 👍

**Comment by gauravano** [comment]
Thanks @jywarren! And, thanks @akshaygupta533 for working on this one :tada: !

**Comment by gauravano** [comment]
@akshaygupta533 , thanks for nice work. We would love to have more help from you. If you are interested in solving more issues then check here - https://code.publiclab.org/#r=all for a new issue. In case, you are unable to find an issue, feel free to comment here. Thanks!

**Comment by akshaygupta533** [comment]
@gauravano I would surely love to work on more issues. Meanwhile, if you find any issue, please mention me. Thanks! :smile:

**Pull request merged**
