### PR TITLE
Changed count and length to size

### PR DESCRIPTION
**Pull request by stacytonui**
Fixed issue #8518

### CODE REVIEW

**Review by avats-dev — CHANGES_REQUESTED** [review]
@stacytonui you've mentioned wrong issue in your PR, as #8500 is resolved already and even these changes do not correspond to that issue. 

Can you link the correct issue this PR is concerned with? Thanks.

**Comment by stacytonui** [comment]
@avats-dev My apologies, clicked on the wrong issue. I've fixed it. Thankyou

**Review by avats-dev — APPROVED** [review]
Looks good @stacytonui , thanks for contributing to publiclab :tada:. Welcome to the community. 

@cesswairimu for further actions.

**Review by jywarren — APPROVED** [review]
Super nice, well done!

**Comment by jywarren** [comment]
Thanks so much for your help!!!

**Pull request merged**
