### PR TITLE
Extend #5372 BSTRP Check Box fix to all check boxes

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #5372, #5102    (<=== Add issue number here)

============================================================

Apparently every check-box in our repo is error-prone when it comes cross-browser compatibility in text to box alignment. (See screenshot of log-in check box below)

In this PR I will extend the overrides I made in https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/btsp_checkbox_override.css.scss#L20-L40 for a checkbox on our editor page to cover all Plots2 checkboxes ☔️

=============================================================

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@shivam15 @divyabaid16 won't let me add you as reviewers but requesting for you to be my reviewers for this :)

**Comment by sashadev-sky** [comment]
also @shivam15 @divyabaid16 can you both check if the 'remember me' checkbox on the **login page** looks ok to you? it is using a different bootstrap class for checkboxes not specifically for forms. Want to make sure that class is ok!

**Comment by divyabaid16** [comment]
@sashadev-sky here is the screenshot for the login page after incorporating your changes.
Selection_122

**Comment by sashadev-sky** [comment]
Ohh wow! None of the changes I added affect this checkbox, but this makes me realize that the change should maybe applied to all checkboxes not just the one we tackled before? Does that checkbox not look misaligned to you??? My vision is becoming double crossed 😅

**Comment by divyabaid16** [comment]
The changes that you had made to the checkbox previously looks like:
Selection_124

Even I feel that this checkbox ```remember me``` of the login page is misaligned. We can apply those changes to all the checkbox. They were really super awesome :tada: :raised_hands:

**Comment by sashadev-sky** [comment]
Changing the name of this PR to apply fix to all checkboxes!

**Comment by shivam15** [comment]
@sashadev-sky after applying changes in login page it looks something like this

Capture

This was really a great experience to fix bootstrap bug. 👍

**Comment by sashadev-sky** [comment]
Ok I did the login page next i'm going to checkboxes under Activity -> All Updates

**Comment by sashadev-sky** [comment]
@divyabaid16 @shivam15 how do the forms on `localhost/dashboard` for the "All updates" and "subscribe+" dropdowns look to you?

**Comment by shivam15** [comment]
@sashadev-sky without your changes it looks like this 
Capture

**Comment by sashadev-sky** [comment]
@shivam15 will you post one with too?? I will teach you how to pull someone else's PR to your local machine:
- go to master branch
- `git fetch upstream pull/ID/head:BRANCHNAME`
   - upstream is the main repo link not your forked link! So https://github.com/publiclab/plots2.git
   - ID is the id of the PR so 5421
   - BRANCHNAME is anything you want I just name it the same as the ID so I'd put 5421 
    (basically  `git fetch https://github.com/publiclab/plots2.git pull/5421/head:5421`)
- `git checkout BRANCHNAME` (whatever you named the branch)

and thats it! 

If you want to be a reviewer you know the best trick for it now :)

**Comment by shivam15** [comment]
@sashadev-sky  working on it..

**Comment by sashadev-sky** [comment]
@shivam15 Thank you!! Let me know if you need any help!

**Comment by shivam15** [comment]
@sashadev-sky  are you familiar with below error :

ERROR:  Error installing mysql2:
        The last version of mysql2 (= 0.5.2) to support your Ruby & RubyGems was 0.5.2. Try installing it with `gem install mysql2 -v 0.5.2`
        mysql2 requires Ruby version >= 2.0, < 2.6. The current ruby version is2.6.1.33.


I think i screwed up my setup

**Comment by shivam15** [comment]
@sashadev-sky  i think after upgrading my ruby i am facing this issue https://github.com/brianmario/mysql2/issues/1021

**Comment by divyabaid16** [comment]
Yes @shivam15 you need to make your ruby version to ```2.4.4```
For this use can wrire ```rvm use runy-2.4.4```
Thanks!!

**Comment by sashadev-sky** [comment]
@shivam15 yes you need to do a few things
1) make sure your ruby version is the same: 
`rvm install 2.4.4`
`rvm use 2.4.4`
2) Don't install the other mysql version!! If you did I would recommend uninstalling. This gem has been causing trouble for installation lately for most users so don't get discouraged if you get more errors, just post them here! We'll help debug.
3) when in doubt I always try `bundle exec bundle install` instead of just `bundle install`

**Comment by sashadev-sky** [comment]
in the mean time @divyabaid16 do you think you could please pull it and check its aligned from your screen?

**Comment by shivam15** [comment]
@sashadev-sky with your changes

Capture

**Comment by sashadev-sky** [comment]
@shivam15 awesome thank you!! 

@jywarren this one is ready for merge. I only aligned 3 checkbox sections in this PR, not all the ones in the repo. I didn't want the PR to get too big. I also did some general css syntax cleanup (I double checked nothing got changed from it).

I can open a PR to do the rest, but only if fixing all of them is important to you. It's a little time consuming because, visually, I can't see any changes myself (there is no alignment bug on mac) so I have to get confirmation on changes.

**Pull request merged**
