### PR TITLE
added Bootstrap to editor

### LINKED ISSUE #7532: Including Bootstrap in plots2/editor
Bootstrap files are not included in plots2 Editor leading to various style issue like inconsistency in style of the toolbar , quoted text and code doesn't show the style

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #7532 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@VladimirMikulic @jywarren Please review!!!

**Comment by keshav234156** [comment]
Screenshot from 2020-02-18 14-00-36
Screenshot from 2020-02-18 14-00-28
Screenshot from 2020-02-18 14-00-23

**Comment by keshav234156** [comment]
The toolbar is now consistent and code,quote styles are working

**Comment by VladimirMikulic** [comment]
This works, but it breaks existing styles, like the bottom toolbar:

Screenshot_20200218_205610

**Comment by keshav234156** [comment]
@VladimirMikulic Are you saying box is not appearing around **...**.It because of extra class that we are having btn-outline-secondary in https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb#L295

**Comment by keshav234156** [comment]
@VladimirMikulic why are test failing? Can you please tell the command to run the test of plots2 locally?

**Comment by VladimirMikulic** [comment]
For some unknown reason, a test fails. I don't have admin access so I can't troubleshoot this further. The command for running tests is `rails test`.

**Comment by cesswairimu** [comment]
restarting travis

**Comment by keshav234156** [comment]
@cesswairimu @VladimirMikulic this test is failing https://github.com/publiclab/plots2/blob/master/test/system/post_test.rb#L157 .Can you please help me to rectify why it's failing ?

**Comment by VladimirMikulic** [comment]
@keshav234156 please read again my previous comment.

**Comment by cesswairimu** [comment]
@keshav234156 I don't think the travis failure has anything to do with your changes might be some of the travis inconsistency we are experiencing. Restarting travis again. Thanks

**Comment by keshav234156** [comment]
@cesswairimu Travis inconsistency is still present. It failed first time when I restarted it. It passed the test after I restarted it again

**Comment by keshav234156** [comment]
@VladimirMikulic Can you please re-review this and let me know inconsistencies present with respect to https://publiclab.github.io/PublicLab.Editor/examples/

**Comment by keshav234156** [comment]
@cesswairimu Failed again

**Comment by keshav234156** [comment]
restarting it again

**Comment by keshav234156** [comment]
@cesswairimu It Passed!!

**Comment by VladimirMikulic** [comment]
Hi @keshav234156.
Unfortunately, I don't have a local instance of the repo.

**Comment by cesswairimu** [comment]
:tada: :tada:

**Comment by cesswairimu** [comment]
@keshav234156 which buttons did you change? Can we please see the before and after change? Thanks

**Comment by keshav234156** [comment]
@cesswairimu 
Before changes
Screenshot from 2020-02-22 22-34-47
After changes
Screenshot from 2020-03-05 21-54-44

**Comment by cesswairimu** [comment]
@keshav234156 I don't get it, changing the button improve the blockquoting?

**Comment by keshav234156** [comment]
@cesswairimu As bootstrap was not included so styles for buttons and code,blockquote weren't appearing.so bootstrap is being added in the PR

**Comment by cesswairimu** [comment]
Thanks @keshav234156  for explaining all that :+1 this is ready :tada:

**Comment by cesswairimu** [comment]
Welcome to PublicLab @keshav234156 :balloon:

**Comment by jywarren** [comment]
Ah, thank you for the help! something weird happened here and we seem to be having some layout bugs now:

https://stable.publiclab.org/post

I'm going to open a new issue but we may have to do some part of this differently! No worries, we'll figure it out!

**Pull request merged**
