### PR TITLE
#6539 Updated t to translations.

### PR DESCRIPTION
**Pull request by marcin-wicha**
Fixes [#6539]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by nstjean** [comment]
@cesswairimu Can you check why the travis test is failing for this change?

**Comment by cesswairimu** [comment]
@nstjean restarted it...its fine now..Thanks...Do u mind giving a review on this?

**Comment by cesswairimu** [comment]
Never mind just saw your review.Thanks

**Comment by cesswairimu** [comment]
@marcin-wicha thanks for submitting this...Please add a screenshot of the changes. Thanks

**Comment by nstjean** [comment]
Here's a screenshot of the changes tested.

FireShot Capture 055 - 🎈 Public Lab_ New - localhost

@SidharthBansal This can be merged and closed now.

**Comment by SidharthBansal** [comment]
Thanks all

**Pull request merged**
