### PR TITLE
Changed redirect to revisions

### LINKED ISSUE #818: Moderating a wiki revision needs cache flush in URL
### What happened just before the problem occurred

After marking a wiki revision as spam (on a page [like this](https://publiclab.org/wiki/revisions/london-uk)), the revisions page doesn't show the new content; we should redirect back to the revisions page, not the dashboard, and append `'?_=' + Time.now.to_i.to_s` so the browser cache flushes. 

The code for this redirect is here: https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb#L143-L146

See an example of cache flushing of this sort here: https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb#L16

### PR DESCRIPTION
**Pull request by sandyvern**
Edited the redirect route and also fixed #818
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Ah - we actually should redirect to `"/wiki/revisions/<%= @node.slug %>"` -- not just `"/revisions"` -- so it's the revisions page for this wiki page. Sorry I wasn't clear enough! But it's a small change. 

Also, cool -- it actually broke the test that checked where the redirect goes, according to the test output:

```

================================================================================
Failure: Expected response to be a redirect to <"http://test.host/dashboard"> but was a redirect to <"http://test.host/revisions?_=1476121079">.
test_admin_user_should_be_able_to_spam_a_revision(AdminControllerTest)
test/functional/admin_controller_test.rb:324:in `block in <class:AdminControllerTest>'
================================================================================
```

This means you need to change the tested expectation in `test/functional/admin_controller_test.rb` to match the new functionality. In test-driven development, we could have made the test adjustment first, actually, looked to see the test fail, and then used the test as the 'metric' for when the new changes succeed. 

For now, if you change line 324 of the test, it should work! 

Also a note -- if you include the words `fixed #818` in the title or body of your PR, then when it's merged it'll auto-close and link back to the original issue #818. It's also just helpful to reference your issue number in case the conversation gets split up. 

Thanks!

**Comment by sandyvern** [comment]
Adjusted the redirect route and edit the test expectation as well

**Comment by jywarren** [comment]
Ah - looks like you need to add the `Time.now...` stuff to the test as well.

**Comment by sandyvern** [comment]
I may have misunderstood your correction.....was I supposed to remove the the ` + '?_=' + Time.now.to_i.to_s` ?

**Comment by sandyvern** [comment]
Seems to have worked this time :-)

**Comment by jywarren** [comment]
Awesome, thanks!!!

**Pull request merged**
