### PR TITLE
Added regex for the username validations

### LINKED ISSUE #6987: username should accept  the correct format
During Sign Up the publiclab site, the username box accepts any format, for an example  "_1234589"

The username definitely shouldn't contain special characters, but that should also yield to the rules of the system, those mainly being:

A username should consist of lowercase alphanumeric characters
A username must not contain special characters EXCEPT for _, but never at the start or end
A username must not start with a number

The default regex for it should be  ^[a-z][-a-z0-9]*\$

Screenshot from 2019-12-17 17-30-45

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by AnshitaVishwa**
Fixes #6987  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by EmirVatric** [comment]
Hi, @AnshitaVishwa 
I think we should keep the validations in the model rather than in the controller.
You can use something like this:

```
VALID_USERNAME_REGEX = ^[a-z][_a-z0-9]*$.freeze
  validates :username, format: { with: VALID_USERNAME_REGEX }
```

But you should wait to get the response from more senior developers. 👍

**Comment by AnshitaVishwa** [comment]
Basically a username that a new user enter should follow some conventions that are as follows 
A username should consist of lowercase alphanumeric characters
A username must not contain special characters EXCEPT for _, but never at the start or end
A username must not start with a number
so if the username does not matches the correct format , the controller will again redirect it to Register form page.

**Comment by AnshitaVishwa** [comment]
@EmirVatric  Sure . Thanks!

**Comment by AnshitaVishwa** [comment]
> Hi, @AnshitaVishwa
> I think we should keep the validations in the model rather than in the controller.
> You can use something like this:
> 
> ```
> VALID_USERNAME_REGEX = ^[a-z][_a-z0-9]*$.freeze
> validates :username, format: { with: VALID_USERNAME_REGEX }
> ```
> 
> But you should wait to get the response from more senior developers.

**Comment by cesswairimu** [comment]
Hi @AnshitaVishwa, thanks for opening this...I agree with @EmirVatric we should keep the validations on the model..its  the rails way and also whatever is in the controller as validations shall be overwritten by what is the model. @EmirVatric  don't hesitate to leave reviews..we help each other and learn...I am no senior dev too :smile:  Thanks all

**Comment by AnshitaVishwa** [comment]
@cesswairimu I'll go for it. Thanks!!

**Comment by AnshitaVishwa** [comment]
@EmirVatric I need your help, When I am trying to put those validations that you have giver in the above comment in the usermodel that is in app>models>user.rb it shows that it is an undefined method for Validates. 
Screenshot from 2019-12-19 22-50-28

**Comment by cesswairimu** [comment]
@AnshitaVishwa put the above validations in this file https://github.com/publiclab/plots2/blob/master/app/models/user.rb ?

**Comment by EmirVatric** [comment]
@AnshitaVishwa 
`VALID_USERNAME_REGEX = /^[a-z][_a-z0-9]*$/
  validates :username, format: { with: VALID_USERNAME_REGEX, multiline: true, message: 'must be formatted correctly' }`

Here is the correctly formated code, it should go to app/models/user/rb, line 70

sorry for sloppy instructions from before ✌️

**Comment by AnshitaVishwa** [comment]
@cesswairimu  Yes.

**Comment by AnshitaVishwa** [comment]
@EmirVatric Thanks a lot !! It worked perfectly fine. :)

**Comment by AnshitaVishwa** [comment]
@cesswairimu  @EmirVatric If anyone could tell me What does that red cross means?

**Comment by EmirVatric** [comment]
Hi @AnshitaVishwa 
Travis CI runs tests that can be found in the source code, now that we added new validation tests need to be updated. For example, the code below is testing signup and can be found at test/integration/signup_flow_test.rb

`  test 'display username character and length error messages' do
    post '/register', params: {
      user: {
        username: '^',
        email: @new_user[:email],
        password: @new_user[:password],
        password_confirmation: @new_user[:password],
      },
      spamaway: @spamaway
    }

    assert response.body.include? '2 errors prohibited this user from being saved'
    assert response.body.include? 'Username should use only letters, numbers, spaces, and .-_@+ please.'
    assert response.body.include? 'Username is too short (minimum is 3 characters)'
  end`

This test is expecting 2 errors but after adding new validation it should expect 3 errors that prohibit the user from being saved.

**Comment by jywarren** [comment]
Hi! Thanks for this great work! Actually we should get the tests fixed in
the same pr, or we won't be able to merge it... Thanks for identifying the
issue; I don't think the fix will be too tough!

**Comment by AnshitaVishwa** [comment]
@EmirVatric  Thanks for your great help ! I'll fix this and send the PR :)

**Comment by AnshitaVishwa** [comment]
@EmirVatric I tried running this test on local host. It worked, but I think some validations for the username are already there in that test Eg. 'Username should use only letters, numbers, spaces, and .-_@+ please.' this conflicts my validations for the username. So either I need to modify my assert statement or need to remove the above statement from the test.

**Comment by AnshitaVishwa** [comment]
@cesswairimu  I think someone has already worked on this issue before , either I should close the PR as it is showing merge conflicts or else I should overwrite my specifications for the username validation with the previous one...??????

**Comment by cesswairimu** [comment]
mmh..will take a look at the tests and current validations and get back to you. Thanks

**Comment by SidharthBansal** [comment]
What is the progress on this?

**Comment by SidharthBansal** [comment]
Can someone resolve the conflicts?

**Comment by emilyashley** [comment]
I got the conflicts resolved if that helps move this along 👍

**Comment by SidharthBansal** [comment]
@VladimirMikulic @Uzay-G I think you folks will be interested in reviewing this.

**Comment by Uzay-G** [comment]
The tests are failing only when an oauth user is created. This is because the `create_with_omniauth` function generates a random secure password here:

https://github.com/publiclab/plots2/blob/23e83cdc51a8496f23db932054cbe25ee329e821/app/models/user.rb#L424-L434

This password must not match the constraints of the validation added in this pr so the user cannot be saved.

**Comment by Uzay-G** [comment]
There are different ways we can fix this:
- Change the way the default password is created for omniauth so that it passes validation (would make the passwords less secure)
- Change validation so it works even with the random omniauth passwords

**Comment by SidharthBansal** [comment]
Omniauth is not related to password

**Comment by Uzay-G** [comment]
No but it does cause the tests to fail. Basically, when you create a user through omniauth, a random password is generated. This password does not match the validation created criteria in this pr, so when a new user is created with omniauth, it fails because the password is invalid

**Comment by SidharthBansal** [comment]
Correct

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
