### PR TITLE
Fixes #604

### LINKED ISSUE #604: Extract javascript from profile page into app/assets/profile.js
The user profile page's javascript is all inline -- we should take a crack at moving as much as possible into a new javascript file, and passing any necessary variables into a `profile()` function to simplify the profile page javascript? 

The profile page is here: https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb

We can shorten it by half and separate out the inline javascript into a file at `/app/assets/javascripts/profile.js`

Something like this:

```js
  <script>
    (function(){
      var profile = profile({
        user_id:       <%= @user.id %>
      })();
```

At the end of the profile template.

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

Move javascript code to users.js

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren Please review

**Comment by jywarren** [comment]
Hi, this looks good! Thanks!

**Comment by ananyo2012** [comment]
Hurray the travis-ci build passes!

**Comment by jywarren** [comment]
Merged in 0c73ae1 -- thanks! CI is great, huh?

**Comment by ananyo2012** [comment]
Yes it indeed is! :blush:

**Pull request closed without merging**
