### PR TITLE
Update docker-compose.yml for staging mail tests (WIP)

### PR DESCRIPTION
**Pull request by jywarren**
Re #2095!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, `ERROR: for web  Cannot create container for service web: conflicting options: host type networking can't be used with links. This would result in undefined behavior`

**Comment by jywarren** [comment]
Did I put it in the wrong place?

**Comment by jywarren** [comment]
@icarito what do you think? Thanks!

**Comment by icarito** [comment]
Yeah this should work. Checking the logs.

**Comment by icarito** [comment]
Oh I see. 
`ERROR: for plots2_web_1  Cannot create container for service web: conflicting options: host type networking can't be used with links. This would result in undefined behavior`
We'll have to drop the links but in that case we need to reach the database at `localhost` instead of `db`.

**Comment by jywarren** [comment]
Hmm, still not going... thanks for chipping away at this though!!!

**Comment by icarito** [comment]
Sorry I took so long. We might have to start tracking docker-compose variants for production and staging also. For now it works in testing, hopefully it will work in staging too.

**Comment by icarito** [comment]
I have also setup a SMTP server listening on localhost:25 on staging - but come to think of it, it still shouldn't be reached at 127.0.0.1 - the reason for this change in the first place. I had tried running everything under the host network and this exposed the SQL port so it was a security flaw. So I put the db port directly in the rails container.

**Pull request merged**
