### PR TITLE
Update README.md

### LINKED ISSUE #10950: Update README Table of Contents
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [README.md](https://github.com/publiclab/plots2/blob/main/README.md) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -45,11 +45,12 @@ A full description of the features, audiences, inter-relationships, and goals of
     - [Standard Installation](#standard-installation)
     - [Windows Installation](#windows-installation)
     - [Windows Subsystem for Linux 2 Installation](#windows-subsystem-for-linux-2-installation)
+    - [Redis Installation](#redis-installation)
 6. [SSL in Development](#ssl-in-development)
 7. [Login](#login)
 8. [Testing](#testing)
 9. [Maintainers](#maintainers)
-10. [API](https://github.com/publiclab/plots2/blob/main/doc/API.md)
+10. [How to start and modify cron jobs](#how-to-start-and-modify-cron-jobs)
 11. [Bundle Exec](#bundle-exec)
 12. [Reply-by-email](#reply-by-email)
 13. [Bugs and Support](#bugs-and-support)
@@ -123,7 +124,7 @@ We recommend you either work in a virtual environment, or on a dual booted syste
 2. [Dual Booting](https://www.tecmint.com/install-ubuntu-alongside-with-windows-dual-boot/amp/), [option2](https://askubuntu.com/questions/1031993/how-to-install-ubuntu-18-04-alongside-windows-10), [video guide](https://www.youtube.com/watch?v=qNeJvujdB-0&fbclid=IwAR0APhs89jlNR_ENKbSwrp6TI6P-wxlx-a0My9XBvPNAfwtADZaAXqcKtP4)
 3. [Setting up a Linux virtual env](https://itsfoss.com/install-linux-in-virtualbox/)
 
-## Windows Subsystem for Linux 2 Installation
+### Windows Subsystem for Linux 2 Installation
 
 Before continuing with the installation steps in this README, users of Windows Subsystem for Linux 2 (WSL 2) should open the WSL 2 Terminal and type out the commands below.
 
@@ -143,7 +144,7 @@ Before continuing with the installation steps in this README, users of Windows S
   * `rvm --default use ruby-x.x.x (replace x.x.x with this project's Ruby version)`
 5. For further reference, [read here](https://linuxize.com/post/how-to-install-ruby-on-ubuntu-20-04/)
 
-## Redis Installation
+### Redis Installation
 
 Public Lab uses Redis and may be required for some functionality when running the application locally.
 1. Install Redis if you haven't already:
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

### PR DESCRIPTION
**Pull request by michaelsandiegoviray**
Changes made in README.md 

+    - [Redis Installation](#redis-installation)
+10. [How to start and modify cron jobs](#how-to-start-and-modify-cron-jobs)
-10. [API](https://github.com/publiclab/plots2/blob/main/doc/API.md)
+### Windows Subsystem for Linux 2 Installation
-## Redis Installation
+### Redis Installation

Fixes #10950  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @michaelsandiegoviray, can you add the issue number in the format `fixes #0000`? Thanks!

**Comment by michaelsandiegoviray** [comment]
> Hi @michaelsandiegoviray, can you add the issue number in the format `fixes #0000`? Thanks!



> Hi @michaelsandiegoviray, can you add the issue number in the format `fixes #0000`? Thanks!

Just changed the issue number! Thanks!

**Comment by TildaDares** [comment]
Hi @michaelsandiegoviray, the number you added is that of the PR. To find the issue number, navigate to the issue you were assigned to, and next to the issue title you should find the issue number.

**Comment by michaelsandiegoviray** [comment]
> Hi @michaelsandiegoviray, the number you added is that of the PR. To find the issue number, navigate to the issue you were assigned to, and next to the issue title you should find the issue number.

Just updated it to the correct issue number, thanks!

**Review by TildaDares — APPROVED** [review]
Thanks @michaelsandiegoviray. This is perfect!!

**Comment by TildaDares** [comment]
Congratulations @michaelsandiegoviray 🎉

**Comment by michaelsandiegoviray** [comment]
> Congratulations @michaelsandiegoviray 🎉

Thank you for guiding me through the process! 💯

**Pull request merged**
