### PR TITLE
FULL screen added and common JS function used in people map

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
screen shot 2018-08-08 at 12 22 22 am

**Comment by sagarpreet-chadha** [comment]
Also this one to be merged after PR  #3211 gets ready and is merged .

**Comment by jywarren** [comment]
Hi, Sagarpreet, is this ready then? Thanks!

**Comment by jywarren** [comment]
Also, when I zoom in here, some of the layers don't show up. Is it running the latest code? https://publiclab.org/maps/#12/30.3477/-88.5156

**Comment by jywarren** [comment]
Awesome!

**Pull request merged**
