### PR TITLE
Refactor code for user's social links -- issue #1908

### PR DESCRIPTION
**Pull request by seafr**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] controller/model tests pass -- `rake test:controllers` and `rake test:models`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Hi @seafr...actually i have worked on this code before (PR #1816 ) and your updation looks perfect to me . Thank you !
@jywarren...i think running travis again may pass all the checks .

**Comment by seafr** [comment]
@sagarpreet-chadha you are welcome. And thanks for your comments. I hope you are right and there's no issue with the code. I'm waiting for @jywarren to add his 2 cents.

**Comment by jywarren** [comment]
OK, sorry for the delay - just triggered a rebuild -- i agree, this should pass! Thank you!

**Comment by jywarren** [comment]
Nice! Well done - thanks!

Merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Comment by seafr** [comment]
You're welcome!
OK I did, but saw nothing that seems easy enough (for a newcomer). Anyway, I'll hang around.

**Comment by jywarren** [comment]
There may also be some good ones listed at https://publiclab.github.io/community-toolbox/ -- yes, please do! We'll add some more soon, too!

I have some drafted here too: pad.publiclab.org/p/issues but we'd have to open a new issue for them first.

**Comment by jywarren** [comment]
Perhaps you have a good idea for how to show people that they can enter their social media login on their profile page, as in https://github.com/publiclab/plots2/issues/1802 ? Some kind of button or menu?

**Comment by seafr** [comment]
In issue #1805 you suggested this be done using JavaScript. But I'm not exactly familiar with JS. Text fields in the edit form perhaps?

**Comment by jywarren** [comment]
I put in a suggestion here: https://github.com/publiclab/plots2/issues/1933 -- hope that helps! Feel free to claim that one!

**Comment by jywarren** [comment]
And thank you!

**Comment by seafr** [comment]
Re: #1933, I'm afraid I'm going to pass on this one. Nice to see someone wants to claim it. I'll be waiting to see their solution. Thanks for your time.

**Comment by jywarren** [comment]
No problem, thanks for your help!!

**Pull request merged**
