### PR TITLE
Date picker modal for /tag/__ pages

### LINKED ISSUE #11198: Add a Bootstrap Modal for from and to date picker
Add a Bootstrap Modal for from and to date picker on /tag/__ pages.

### PR DESCRIPTION
**Pull request by KarishmaVanwari**
Added the date picker modal (UI) for /tag/__ pages that opens on clicking the "custom" option in the "Sort By" dropdown.

Fixes #11198 

Screenshot:
image

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by KarishmaVanwari** [comment]
Hi @jywarren @TildaDares @cesswairimu, 
Please have a look. Also do let me down if you would want the commits to be squashed. 
Thanks!

**Comment by jywarren** [comment]
Hi! Excited to see this! Would you mind posting a screenshot in a comment?
Thank you!

**Comment by KarishmaVanwari** [comment]
Sure. I've already added it in the PR description too. 

image

**Comment by jywarren** [comment]
Ah sorry, my connection isn't great and I've been following by email. I'll
check next time, thanks!

**Review by jywarren — APPROVED** [review]
It looks super. Does it render well on narrow screens like mobile phones? Thanks!

**Comment by KarishmaVanwari** [comment]
Yes, it does, @jywarren! I hope this works: 

image

**Comment by jywarren** [comment]
Excellent, thank you @KarishmaVanwari!!!

**Comment by KarishmaVanwari** [comment]
Thank you @jywarren!!

**Pull request merged**
