### PR TITLE
Hide sort dropdown for tag comments in show.html.erb

### PR DESCRIPTION
**Pull request by DhruvGala**
Hide sort dropdown for tag comments

Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @DhruvGala, can you do this? Thank you!

> One thing that can help to get started is to make sure you've included a link back to the original issue you're solving, in the format fixes #0000 (for example).

**Comment by TildaDares** [comment]
@jywarren Some of the tests are failing because of this error
```
Command: git
Arguments: ls-remote --tags --heads git://github.com/jywarren/imgareaselect.git
Directory: /home/runner/work/plots2/plots2
Output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

https://github.blog/2021-09-01-improving-git-protocol-security-github/
I found a possible solution for the problem in https://github.com/heroku/heroku-buildpack-nodejs/issues/959

**Review by TildaDares — APPROVED** [review]
Great job @DhruvGala! Thank you.

**Comment by DhruvGala** [comment]
Thanks @TildaDares

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Very nicely done, thank you!! 🎉

**Pull request merged**
