### PR TITLE
Use js libs from container in testing

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
ah, some conflicts still, but otherwise ready to merge? Would you mind resolving? Thanks!

**Comment by icarito** [comment]
Fixed conflicts, we should test this!

**Comment by gauravano** [comment]
hi @jywarren @icarito, can you please update the status of this PR. Thanks!

**Comment by icarito** [comment]
Hi @jywarren @gauravano I missed updating this, now catching up, fixed conflicts and made builds quite a bit faster, please confirm / review!

**Comment by jywarren** [comment]
Just need to get the Jenkins dot to turn green, so it doesn't look stuck! 👍

**Comment by icarito** [comment]
Hi I just published this to `unstable` and it seems to work... 

But I failed to publish a note - not sure if it's related. I'll check `unstable` by pushing main branch into it..

**Comment by icarito** [comment]
Unstable behaved the same as with the main branch ("master"). I'll look into fixnig that. Otherwise, I think this should work! :-) :tada:

**Comment by icarito** [comment]
:crossed_fingers: :surfing_man:

**Comment by jywarren** [comment]
🎉

**Pull request merged**
