### PR TITLE
Adding sort_by=recent as default in search/all-> profiles

### PR DESCRIPTION
**Pull request by milaaraujo**
Adding sort_by=recent as default in search/all-> profiles

### CODE REVIEW

**Comment by jywarren** [comment]
This looks good - ready to merge?

**Comment by jywarren** [comment]
Any worries that this won't return very active users before new users? Just thinking about the ideal ordering... if you search for `warren` you rarely get me (`@warren`) even though i post a lot:

image

just wondering! we can def. address this in a follow-up issue.

**Comment by jywarren** [comment]
I mean i guess this new default sorting may be better, i don't know!

**Comment by milaaraujo** [comment]
I think it is ready to merge.

With `sort_by=recent` it will return users with most recent activity (not the most recent/new users): https://github.com/publiclab/plots2/blob/f2082151f65254825594157028fcf56516725d93/app/services/search_service.rb#L51

**Comment by jywarren** [comment]
ah, ok perfect!

**Comment by jywarren** [comment]
🎉 !

**Pull request merged**
