### PR TITLE
Move question comment form div below comments #958

### PR DESCRIPTION
**Pull request by ashleypt**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X ] all tests pass -- `rake test:all`
* [X ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X ] pull request is descriptively named with #number reference back to original issue
* [X ] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [X] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Builds sometimes fail for unrelated reasons... I've restarted this one!

Thanks!

**Comment by ashleypt** [comment]
@jywarren thanks for the opportunity to contribute :)

**Comment by jywarren** [comment]
Thank **you**! I'm traveling but should have a chance to review this in the next day or two. 

Curious, how did you hear about us? We're working on better outreach to new contributors.

**Comment by ashleypt** [comment]
@jywarren found http://findanopensourceproject.com/ on https://www.reddit.com/r/programming/comments/5bi0sw/check_out_my_website_to_find_an_open_source/

and then I searched ruby experience low and yours was the first on the list so I just commented and dived in as soon as I saw it was just moving some simple template code

**Comment by ashleypt** [comment]
@jywarren I feel a bit lost now as I'm not a first timer anymore but I'm still a beginner so I'm not sure which issues to work on

**Comment by ashleypt** [comment]
@jywarren why didn't you merge the commits?

**Comment by jywarren** [comment]
Well once this is wrapped up, there are a number of first-timers-only "candidate" issues that could be a good fit and I'm happy to help you choose! 

https://github.com/publiclab/plots2/labels/fto-candidate

**Comment by jywarren** [comment]
Sorry im on my phone!

**Comment by jywarren** [comment]
Hit the wrong button ugh :-)

I won't be able to merge until I'm at a laptop... Probably tonight or tomorrow. Thanks!

**Comment by jywarren** [comment]
Hi! I just had a chance to look in at this.  It's almost there! But actually **all** of lines 52-70 need to be moved down, sorry if that wasn't clear enough!

https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L52-L70
If you can make that change I'll be happy to accept the PR, and thanks for your work on this!

**Comment by ashleypt** [comment]
@jywarren yeah sorry about that, fixed :)

I checked the failed check... apt-get failed fetching some package, not related to my changes :)

**Comment by jywarren** [comment]
Great - i'm going to sleep but i'll restart the build. I believe you can trigger it by closing and reopening the PR, too!

**Comment by ashleypt** [comment]
i didnt know that cool, thanks :)

**Comment by jywarren** [comment]
Perfect, passed all tests and the code looks just right. Thanks so much and congrats on your first contribution! Although really it's your second, after the README changes, so double thanks. 

We'd love to have your help on other issues as well, so if you're looking for a new challenge, check out:

https://github.com/publiclab/plots2/labels/help-wanted

**Comment by jywarren** [comment]
😁🐎🐇

**Pull request merged**
