### PR TITLE
Grammatical errors corrected

### LINKED ISSUE #4974: Grammatical mistakes in README.md
# Description
1. "It features a variety of features" can be replaced with "It showcases a variety of features".
2. "We :heart: Open Source and actively participates in various OSS programs" needs to be replaced with "We :heart: Open Source and actively participate in various OSS programs".

### PR DESCRIPTION
**Pull request by shreyateeza**
Fixes #4974  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by shreyateeza** [comment]
@SidharthBansal @Souravirus @gauravano Please merge this PR.

**Comment by SidharthBansal** [comment]
I think you missed to do the changes. Please check it once again.
Thanks

**Comment by gauravano** [comment]
Merged :tada: :balloon:

**Comment by shreyateeza** [comment]
> I think you missed to do the changes. Please check it once again.
> Thanks

I have done the two changes which I mentioned on the issue @SidharthBansal

**Pull request merged**
