### PR TITLE
Deprecate legacy views

### LINKED ISSUE #3531: Results are not sorted according to views
### Please describe the problem (or idea)
results are not sorted according to views in wikis

> What happened just before the problem occurred? Or what problem could this idea solve?
image

> What did you expect to see that you didn't?

the results should be sorted according to page views.

### Please show us where to look

https://publiclab.org/search/wikis/science+community?order=views

### What's your PublicLab.org username?
jradheyshyam96
> This can help us diagnose the issue: 

### Browser, version, and operating system
Windows 10 chrome 
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by alonpeer**
Fixes #3531 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by alonpeer** [comment]
@publiclab/reviewers @jywarren please review.

**Note:** 
This PR builds on top of #5248, so this can only get merged after the other one does.
Please only review the newest commit. The other two are from the other PR.

**Comment by SidharthBansal** [comment]
There are some conflicts. Please remove them so that we can review it.
Thanks for contributing at PL

**Comment by alonpeer** [comment]
@SidharthBansal it'll be easier for me to resolve the conflicts after #5338 is merged, since this PR depends on it. The conflicts are around the db schema, and since multiple PRs can change that file with migrations, I'd like to avoid chasing these conflicts and just do it once.
Once #5338 is merged, I'll follow up with resolving conflicts here.

**Comment by SidharthBansal** [comment]
OK thanks

**Comment by SidharthBansal** [comment]
The conflicts should be resolved once @gauravano you will review and merge the #5338. These prs have conflicting code snippets.
Thanks for the work @alonpeer. I really appreciate your help.

**Comment by jywarren** [comment]
It looked like a timestamp needed to be updated! I made the change, let's see how it does!

**Comment by alonpeer** [comment]
@jywarren 👍 thanks!
I would imagine that once #5338 is merged, it'll be nice to rebase this branch again on `master`, so we get a nice, clean history. I can do that once the other PR is merged.

**Comment by alonpeer** [comment]
@jywarren I've rebased and updated the migration file name. This should now be ready 👍

**Comment by jywarren** [comment]
Great!!! And.... done! Fantastic work, thank you @alonpeer !!!

**Comment by gauravano** [comment]
Hey @alonpeer, would you be interested in being a mentor for GSoC program -  https://github.com/publiclab/plots2/issues/4585?

Thanks!

**Comment by alonpeer** [comment]
Hey @gauravano ! Wow, thanks for this honour, I really appreciate it 😄 
I will, however, have to decline. Due to personal reasons, I’m going to have to take a break from contributing, since I will be quite busy in the next few months.
I will try to pop by and review a PR here and there, but can't promise more than that.

Cheers!

**Comment by gauravano** [comment]
Hey @alonpeer, it's fine. 

Also, like to mention that we really appreciate the awesome work you do with us and help us grow. I personally found your PRs very interesting and definitely learn from them :) 

Best, 
Gaurav

**Comment by alonpeer** [comment]
@gauravano you are VERY kind! I'm really happy to be part of this wonderful community 🎉

**Pull request merged**
