### PR TITLE
Make the /wiki page display unique results

### LINKED ISSUE #9591: Wikis don't display unique results
### Please describe the problem (or idea)
In reference to this [comment](https://github.com/publiclab/plots2/issues/9290#issuecomment-810771501).
Many rows are repeated multiple times in the wikis table which leads to there being 2067 pages.

Same thing is observed in the local environment too.
temp

### Please show us where to look

https://publiclab.org/wiki

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #9591 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
**Before**
temp


**After**
temp1

**Comment by RuthNjeri** [comment]
Thanks for working on this @Manasa2850, would you like to add tests for these changes?

**Comment by Manasa2850** [comment]
Sure @RuthNjeri I'll do that!

**Review by RuthNjeri — APPROVED** [review]
This looks good to me @Manasa2850, thank you! 🎉

**Comment by RuthNjeri** [comment]
@Manasa2850 I still see some duplicates for the wiki page on the stable site, perhaps you could investigate it?
 https://stable.publiclab.org/wiki
Screenshot 2021-05-07 at 21 49 17

**Comment by Manasa2850** [comment]
@RuthNjeri I'll try to find out why that's happening.
Thanks!

**Pull request merged**
