### PR TITLE
Inline map changes .

### LINKED ISSUE #4722: Make Tests for inline maps .
This page :  https://publiclab.org/wiki/inline-maps  shows the documentation of all the inline maps that we have . 

All Inline maps use the same partial `_leaflet.html.erb`  except people-inline-map which uses 
`_peopleleaflet.html.erb` .

- [ ]  Remove HASH from URL when using people-inline-map -> No sense of using URL HASH when having more than one inline map on a page .

- [ ] Multiple dependencies being loaded when more than 1 inline map used .

- [ ] Documentation needs to be updated on the page -  https://publiclab.org/wiki/inline-maps . 

- [ ]  Write test :  Leaflet Map is loaded --- check if `<div class="leaflet-map"...` is present or not . When 2 inline maps are used then 2 such div's should be present . Add fixture data which calls `self.notes_map_by_tag` function in `nodes_shared.rb` to demonstrate the test . 

- [ ] Another test : Check if the marker is being loaded on the map ! This can be done by checking if 
` name of map instance uses number in range [1 ,100] , more map on 1 page causes names to clash !

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #4722 !

Work in progress 😄 !

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Okay the branch is pushed to unstable . Thanks @gauravano !

@jywarren ...unstable showing the same error : `ReferenceError: google is not defined` .

**Comment by jywarren** [comment]
Ah unstable needs the keys let me add them!

On Jan 29, 2019 6:10 PM, "Sagarpreet Chadha" <notifications@github.com>
wrote:

Okay the branch is pushed to unstable . Thanks @gauravano
<https://github.com/gauravano> !

@jywarren <https://github.com/jywarren> ...unstable showing the same error
: ReferenceError: google is not defined .

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/pull/4725#issuecomment-458688933>, or mute
the thread

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren ! 
Yes it is working fine on unstable 👍 . See this page : 
https://unstable.publiclab.org/notes/sagarpreetchadha/01-30-2019/inline-map

**Comment by sagarpreet-chadha** [comment]
Okay so inline maps are working great in **NOTES** but are giving this error in **WIKI** : 

> TypeError: L.esri is undefined[Learn More]

/NOTE : https://publiclab.org/notes/sagarpreet/01-30-2019/inline-map-testing#2/42.0/-23.9/BL1
/WIKI : https://publiclab.org/wiki/inline-maps#

**Comment by jywarren** [comment]
Hmm, do you mean on production site live, now, or in this PR's code? I guess you mean production but I don't see that error on the wiki page. 

Is this ready to merge then? Thanks!

**Comment by sagarpreet-chadha** [comment]
Yes lets merge this :smile: !

**Pull request merged**
