### PR TITLE
Removed extra horizontal lines in the mobile views of the maps page

### LINKED ISSUE #3595: Remove extra horizontal lines in the mobile view
### Please describe the problem (or idea)
The page when seen in the mobile view gives some extra horizontal lines between the images ,which needs to be changed .
capture

solution : Remove this line
codelink:https://github.com/publiclab/plots2/blob/a74987812aec5435717044f76206892399c71ae6/app/views/map/_maps.html.erb#L23

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look
https://publiclab.org/maps?page=11#2/42.3/2.8

### What's your PublicLab.org username?
201651044

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by rohan2599**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
fixed #3595 
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #3595`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by rohan2599** [comment]
@publiclab/reviewers please review

**Comment by rohan2599** [comment]
@jywarren please review

**Comment by rohan2599** [comment]
before:
screenshot from 2018-10-04 19-55-22
after:
screenshot from 2018-10-04 19-49-39

**Comment by rohan2599** [comment]
@publiclab/reviewers  please review

**Comment by jywarren** [comment]
Hi, can you rename the issue please to describe it's function a bit more?
This helps us review and keep track. Thanks!

**Comment by rohan2599** [comment]
@jywarren  I have added the screenshots to review the progress and changed the name also.Please review

**Comment by jywarren** [comment]
Aha, great. But can you check if the horizontal lines are now missing from the non-mobile (wider) view, at 1000px or more? Thank you! 📸

**Comment by rohan2599** [comment]
appr

**Comment by avsingh999** [comment]
@rohan2599  great work 
@jywarren  I think it's ready to merge
thank you

**Comment by rohan2599** [comment]
@jywarren  its done .you can check.

**Comment by rohan2599** [comment]
@SidharthBansal  please review I have done the changes

**Comment by rohan2599** [comment]
@jywarren please review

**Pull request closed without merging**
