### PR TITLE
FIX: Post question button test

### PR DESCRIPTION
**Pull request by VladimirMikulic**
[PR explanation](https://github.com/publiclab/plots2/pull/7820#issuecomment-629391578)
Resolves #7820

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Of course, this fails with the current state of the Public Lab editor but will pass with 2.0.6.

**Comment by keshav234156** [comment]
@VladimirMikulic Can you please check by changing the version of the editor of 2.0.6 in this so that we are confirmed that this fixes the issue

**Comment by VladimirMikulic** [comment]
@keshav234156 sorry, I don't have a local version of the repos but I've tried it out in the browser console. I know it will work :)

**Comment by jywarren** [comment]
Oh, do you think you can open this PR against the branch in https://github.com/publiclab/plots2/pull/7820 and then we'll merge this and it'll deprecate that PR? THANK YOU SO MUCH @VladimirMikulic for your help!

**Comment by VladimirMikulic** [comment]
No problem @jywarren :+1: 
The new PR is #7929.

**Pull request closed without merging**
