### PR TITLE
Turbolinks events

### PR DESCRIPTION
**Pull request by jywarren**
re #2064

### CODE REVIEW

**Comment by jywarren** [comment]
This is running on https://unstable.publiclab.org/dashboard and is showing some oddness... some searches fail and once they do, they don't work at all. It's very close! Let's use this PR to document the issues and fix them one by one. We can continue to use the unstable container to test things out.

**Comment by namangupta01** [comment]
Hey! Yes sure! We will find all the bugs and will tests untill it becomes perfect. And it's good that we have https://unstable.publiclab.org/ so we can tests the things out.

**Comment by jywarren** [comment]
Can you keep trying on unstable -- my sequence was:

1. load a page
2. use turbolinks to load a 2nd page
3. clear JS error console
4. start a search, for example for `coqui`, in the menubar
5. i saw some error with "split" possibly in the response parsing with the typeahead library we use: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/restful_typeahead.js and we use this lib: https://github.com/bassjobsen/Bootstrap-3-Typeahead

Thanks!!!

**Comment by namangupta01** [comment]
Getting error on https://unstable.publiclab.org/
screen shot 2018-01-27 at 12 33 34 am

**Comment by jywarren** [comment]
@icarito not sure why but unstable is offline now; i restarted it in Jenkins but do you know why it goes offline like that? Thanks!

**Comment by namangupta01** [comment]
@jywarren i was trying to locate the bug for turbolinks in https://unstable.publiclab.org/ but its still not working

**Comment by jywarren** [comment]
Hi @icarito if you have a moment to take a look at unstable booting issues we'd appreciate it, thank you!

**Comment by icarito** [comment]
Sorry for the delay. In unstable, I don't know why it seems to crash? I've restarted it again and will keep an eye.

**Comment by icarito** [comment]
There it crashed again! I'll check the logs

**Comment by icarito** [comment]
Here I've filtered out the items involving `unstable.publiclab.org` and not `Connection refused` (error when crashed). Sounds like a permission problem? Could it bring down the app?


```                                                                                                                                                                                                                                                                                                       
2018/01/26 13:39:53 [error] 18098#0: *5997 no live upstreams while connecting to upstream, client: 49.201.207.93, server: unstable.publiclab.org, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "unstable.publiclab.org"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
2018/01/26 14:24:35 [crit] 18100#0: *6730 stat() "/srv/plots_unstable/plots2/public/system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg" failed (13: Permission denied), client: 47.31.28.3, server: unstable.publiclab.org, request: "GET /system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg HTTP/1.1", host: "unstable.publiclab.org", referrer: "https://unstable.publiclab.org/"                                                                                                                                                                                                                                                                                                   
2018/01/29 23:59:11 [error] 18100#0: *20369 no live upstreams while connecting to upstream, client: 120.56.227.46, server: unstable.publiclab.org, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "unstable.publiclab.org"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
2018/01/30 18:44:48 [error] 18100#0: *24668 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 181.64.124.93, server: unstable.publiclab.org, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5001/", host: "unstable.publiclab.org"                                                                                                                                                                                                                                                                                                                                                                                                                                            
2018/01/30 18:44:49 [error] 18100#0: *24668 no live upstreams while connecting to upstream, client: 181.64.124.93, server: unstable.publiclab.org, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "unstable.publiclab.org"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
2018/01/30 18:44:51 [error] 18100#0: *24668 no live upstreams while connecting to upstream, client: 181.64.124.93, server: unstable.publiclab.org, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "unstable.publiclab.org"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
2018/01/30 18:45:15 [error] 18100#0: *24668 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 181.64.124.93, server: unstable.publiclab.org, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5001/", host: "unstable.publiclab.org"                                                                                                                                                                                                                                                                                                                                                                                                                                            
2018/01/30 18:45:16 [error] 18100#0: *24668 no live upstreams while connecting to upstream, client: 181.64.124.93, server: unstable.publiclab.org, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "unstable.publiclab.org"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
2018/01/30 18:46:30 [crit] 18100#0: *24668 stat() "/srv/plots_unstable/plots2/public/system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg" failed (13: Permission denied), client: 181.64.124.93, server: unstable.publiclab.org, request: "GET /system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg HTTP/1.1", host: "unstable.publiclab.org", referrer: "https://unstable.publiclab.org/"                                                                                                                                                                                                                                                                                               
2018/01/30 18:53:24 [crit] 18100#0: *24706 stat() "/srv/plots_unstable/plots2/public/system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg" failed (13: Permission denied), client: 181.64.124.93, server: unstable.publiclab.org, request: "GET /system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg HTTP/1.1", host: "unstable.publiclab.org", referrer: "https://unstable.publiclab.org/"                                                                                                                                                                                                                                                                                               
2018/01/31 03:21:14 [crit] 18100#0: *25608 stat() "/srv/plots_unstable/plots2/public/system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg" failed (13: Permission denied), client: 150.107.8.201, server: unstable.publiclab.org, request: "GET /system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg HTTP/1.1", host: "unstable.publiclab.org", referrer: "https://unstable.publiclab.org/"                                                                                                                                                                                                                                                                                               
2018/01/31 07:49:08 [crit] 18100#0: *26196 stat() "/srv/plots_unstable/plots2/public/system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg" failed (13: Permission denied), client: 181.64.124.203, server: unstable.publiclab.org, request: "GET /system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg HTTP/1.1", host: "unstable.publiclab.org", referrer: "https://unstable.publiclab.org/home"                                                                                                                                                                                                                                                                                          
```

**Comment by icarito** [comment]
I'll start it up again and try to reproduce.

**Comment by icarito** [comment]
I've failed to trigger a crash. Started it up again in case you want to try.

**Comment by icarito** [comment]
It's crashed again, but I notice that the process itself is still alive, just not responding to requests.
Here's the logs from stdout (`docker-compose logs web`):
```
_1  | Started GET "/assets/dashboard-79157678e5ab138d58b9a4d64a473230.js" for 181.65.123.204 at 2018-02-01 17:25:44 +0000 
web_1  | Started GET "/system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg" for 181.65.123.204 at 2018-02-01 17:26:00 +0000 
web_1  |  
web_1  | ActionController::RoutingError (No route matches [GET] "/system/images/photos/000/021/592/large/harvey-5-gty-er-170825_16x9_992.jpg"): 
web_1  |   actionpack (4.1.16) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call' 
web_1  |   actionpack (4.1.16) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' 
web_1  |   railties (4.1.16) lib/rails/rack/logger.rb:38:in `call_app' 
web_1  |   railties (4.1.16) lib/rails/rack/logger.rb:20:in `block in call' 
web_1  |   activesupport (4.1.16) lib/active_support/tagged_logging.rb:68:in `block in tagged' 
web_1  |   activesupport (4.1.16) lib/active_support/tagged_logging.rb:26:in `tagged' 
web_1  |   activesupport (4.1.16) lib/active_support/tagged_logging.rb:68:in `tagged' 
web_1  |   railties (4.1.16) lib/rails/rack/logger.rb:20:in `call' 
web_1  |   request_store (1.4.0) lib/request_store/middleware.rb:19:in `call' 
web_1  |   actionpack (4.1.16) lib/action_dispatch/middleware/request_id.rb:21:in `call' 
web_1  |   rack (1.5.5) lib/rack/methodoverride.rb:21:in `call' 
web_1  |   rack (1.5.5) lib/rack/runtime.rb:17:in `call' 
web_1  |   activesupport (4.1.16) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call' 
web_1  |   rack (1.5.5) lib/rack/sendfile.rb:112:in `call' 
web_1  |   railties (4.1.16) lib/rails/engine.rb:514:in `call' 
web_1  |   railties (4.1.16) lib/rails/application.rb:144:in `call' 
web_1  |   railties (4.1.16) lib/rails/railtie.rb:194:in `public_send' 
web_1  |   railties (4.1.16) lib/rails/railtie.rb:194:in `method_missing' 
web_1  |   passenger (5.1.12) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request' 
web_1  |   passenger (5.1.12) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request' 
web_1  |   passenger (5.1.12) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop' 
web_1  |   passenger (5.1.12) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads' 
web_1  |   passenger (5.1.12) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception' 
web_1  |  
web_1  |  
```

**Comment by namangupta01** [comment]
@icarito I think the error is routing error? Isn't it?

**Comment by icarito** [comment]
It would seem so but the problem is it crashes the application. Perhaps the clue is `block in create_thread_and_abort_on_exception` ?
Looks similar to this https://github.com/phusion/passenger/issues/1478

**Comment by jywarren** [comment]
Hi, @namangupta01 -- we're going to keep thinking on this but in the meantime, do you think you could try this out locally (in production mode), and particularly look for the typeahead search working after accessing a turbolinks-generated page? 

I think we could probably merge this PR if it works even without Turbolinks on -- that's the point of the double event trigger on both `ready` and `turbolinks:load` -- what do you think?

**Pull request closed without merging**
