### PR TITLE
Shipcy banned users

### PR DESCRIPTION
**Pull request by nstjean**
Update fix for PR #7136, for Issue #6962 

@skilfullycurled @shipcy @jywarren

### CODE REVIEW

**Comment by jywarren** [comment]
I added a functional test... we still need to tweak the codecov thresholds, but this should help for now!

**Comment by Uzay-G** [comment]
Hey! I saw your change to the codecov file. If we make the threshold that high, don't you think we should just remove the `patch` status? What do you think @jywarren?

**Comment by jywarren** [comment]
Well, we may want to tweak it again, so let's leave that in there so it's
clear how to do this. Thanks!

**Comment by jywarren** [comment]
Ah this is perfect! I got a little confused but this is good to merge now. Thanks, all!

**Comment by shipcy** [comment]
@jywarren @nstjean @Uzay-G I did not understand what you guys did. Can you guys please explain this to me?

**Comment by Uzay-G** [comment]
No problem @shipcy! Basically, we want to make sure every pull request has clean, safe code and doesn't make other parts bug. To do this, when someone opens a pr, several tests are run to verify their changes.

In this case, the test that was failing is one named codecov that makes sure you have added tests to the codebase that verify your fixes.
But for codecov was a recent addition to our test suite, so we are still figuring out how to configure it. In this case, @jywarren lowered the strictness of the test so the pr would not fail.

Do you understand?

**Comment by skilfullycurled** [comment]
To expand on one concept that @Uzay-G mentioned

**Comment by skilfullycurled** [comment]
Wait!  Didn’t mean to press send.  One second, I wanted to find a file...

**Comment by skilfullycurled** [comment]
Okay, sorry.  Using a new phone client...

Anyway.

I wanted to expand a bit on the tests concept by showing you the test for this feature which I believe is located [here](https://github.com/publiclab/plots2/blob/460410dac565f2a2f341edbee38bebd152742072/test/functional/admin_controller_test.rb#L677)

As you might expect given the name, a test simply mimics the functionality and  automatically “tries out” the given feature. 

On the line I linked to, you’ll notice at the top of that particular test, it says what should happen, on the line I linked to, it says that banned equals True (the new feature) and what success and failure are.

To me, it’s weird to think that you’d write tests for the very thing you created.  Obviously if it didn’t work, you wouldn’t merge it.  But the goal (correct me if I’m wrong) is to anticipate what could happen.  You might have a test for a inputting an email address, and therefore you know it should have an @ symbol.  Then you might write a text which includes that failure to make sure the feature handles it correctly.  Also, as you find new bugs you can update the test.

If you back up out of that file into previous folders, you can explore all the different tests and personally I am always amazed at just how many tests a website like this can have!  

Have I got the concept right @Uzay-G?

**Comment by Uzay-G** [comment]
Yeah @skilfullycurled that's a really nice summary of how it works and I'll add a bit of additional explanation. 

In a big project like plots2, it's extremely important to have these tests because they are very important to help contributors efficiently maintain the codebase. For example, in plots2, there is a very intricate authentication system. So if contributor A added a feature to this delicate system without testing and just being satisfied that it works right now, there could be **huge bugs** later. Contributor B might open a new pull request after that changes a different part of the auth system. If contributor A did not create tests, we can't know if these changes will break the contributor A's feature and might even have worse consequences on the whole system. The only way to find the bug would be for  a user to report it.

**Comment by skilfullycurled** [comment]
Ahhhhhhhh...interesting.  So, crucially, its way way to ask "Does the thing which I developed now, integrate with the thing someone else developed in the past."  And this way, I don't have to find those other people to ask, the test functions as a sort of automated check list to any future developers.  Thanks!  That was really helpful for me, as I've wrote, testing has always seemed a bit circular, but that changes my understanding of their value.

**Comment by Uzay-G** [comment]
Awesome! I'm happy to have helped :smile:

**Comment by shipcy** [comment]
@Uzay-G  and @skilfullycurled What an explanation! I have understood everything very well. Now whenever I solve any issue, I will always keep in mind that according to codecov all my tests pass and create no bug. And now please tell me what I should do next. I am preparing for GSOC 2020. 
Any opinion of you people?

**Comment by skilfullycurled** [comment]
Gah!  I wrote a whole thing and lost it.  So I’ll be briefer than I want to.

I don’t know a ton about GSOC, but here are some ways to find out more:

First, I @mentioned you in the weekly check in.  Introduce yourself again (sorry!  I’ve made you do this three times now!) and when you do, mention you’re interested in GSOC and ask if there’s anyone you can talk to.

Second, here’s the GSOC wiki page.  On that page there’s a heading labeled “questions” with a blue button that says “ask a question”.  Click on it, ask your question, and tag it with GSOC.  Anyone following that tag with be alerted.  Also, @mention me as @bsugar (my username is different in the site) and I’ll keep an eye on it.

https://publiclab.org/wiki/gsoc

Finally, there’s our chat room:

https://publiclab.org/chat

You can use it through the public lab website, or you can search for Gitter and use the web interface or download the client.  But to be clear, you do not need to do that.  You can participate in the chat directly through the link I gave above.  I’d wait until after the weekend, it’s pretty quiet.  Also, you can at mention me, again (at)bsugar, and I’ll make sure you get connected with someone.

**Comment by jywarren** [comment]
:-) i love this thread. 🙌 

I wanted to say on testing:

Sometimes you can think of tests as a "promise" 🤞 that the code makes to everyone, about what it's supposed to do. But you know when the promise is broken, and it warns you! 

Tests can also be thought of as a narrative explanation 📘 of everything the website is supposed to do, that also literally "shows you" how it's supposed to work. 

They can also be a kind of signpost 📜 to future people, "don't break this! this is how it's supposed to work!" I guess this is like the 'promise' metaphor, a bit.

Finally, tests can be thought of as a shield 🛡 that literally prevents unanticipated breakages. One way that works is not that you'd see the tests and think "oh, i better not mess this up" but that you might've made a change that had a really unexpected affect on a totally different part of the system. The test then blocks that change until you account for the unintended consequences!

**Pull request merged**
