### PR TITLE
Replaced pipes in the typeahead method with 2 spaces (&nbsp;) - "in progress"

### PR DESCRIPTION
**Pull request by sandyvern**
Hi!
I have attempted to resolve this issue by replacing the pipes in the typeahead method with a 'few' spaces...I replaced each pipe with 2 &nbsp;. 

After responding to this issue with a request to give it a shot...I realized my local environment is apparently not setup correctly yet as I do not have rvm installed locally and tests did not seem to want to run either. So I apologize for jumping the gun and wanting to contribute without realizing whether or not my system was set up correctly!
Sandy

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, Sandy - thanks a lot for giving this a go -- as I guess you figured out, you don't necessarily need a development machine, since TravisCI runs your code through all the tests once you open a pull request, so for many less complex changes, that's enough to try out your additions. Let me read this over!

**Comment by jywarren** [comment]
This looks perfect! Thanks for the PR!

Also -- we're trying to improve on attracting new contributors -- may I ask:

* where/how you found us?
* whether it's OK if we tweet out our thanks, and if you have a preferred twitter handle or if your github page is OK?

Thanks again! We really appreciate your help!

**Comment by jywarren** [comment]
Merged in 60c9a62.

Sandy -- just a note, it's always a good idea to make your new changes in a named git feature branch, that way if the publiclab/plots2 master branch changes (like when I merge in changes from other contributors), you have a way to set your changes aside, switch to your own local master branch, pull in the new publiclab/plots2 master changes from Github, then ensure (with `git rebase`) your changes are made in relation to the latest version. 

Sounds complex, but there's a walkthrough here: 

https://publiclab.org/wiki/contributing-to-public-lab-software

I can always help out if you get stuck in some weird git state -- it can definitely happen, and git isn't the friendliest. But by keeping a "clean" local copy of master, and doing your work in another branch, named for your feature (this one could have been like `typeahead-pipes`, for example), you can sometimes avoid especially tough mixups. Thanks a lot!

**Comment by jywarren** [comment]
And if you're looking for another project to get involved in, we'd love to have your contributions! There's a list up at https://github.com/publiclab/plots2/labels/help-wanted of many we're looking for a hand with.

**Comment by sandyvern** [comment]
Thanks for putting up with my newbie faults!! I did figure out that the test got run after I submitted my pr and I did actually use a feature branch when I did the changes...but I think I ended up merging with mine before I figured out the rest of submitting the pr. Sorry about that! I found you from a FCC Medium blog post about finding your first open source bug to fix. And totally ok to tweet thanks...my twitter is @sandyvern or github is fine too!!!

**Comment by jywarren** [comment]
We tweeted our thanks: https://twitter.com/PublicLab/status/780850081201283072

Hope to continue working with you, and happy to suggest a new issue to tackle.

**Pull request closed without merging**
