### PR TITLE
Removed routing errors related to questions comment and answers

### LINKED ISSUE #2886: Error in posting comment on questions
Posting comments on questions is showing an error. 
Here is the screenshot
screenshot from 2018-06-22 01-37-51
@jywarren have a look

### PR DESCRIPTION
**Pull request by Souravirus**
Fixes #2886 and #2884 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
I guess we should merge this as soon as possible so, that there is no problem with users especially commenting to the questions. I will try to write the missing tests in the meanwhile.

**Comment by jywarren** [comment]
Great, thanks!

**Comment by Souravirus** [comment]
Hi @jywarren, are these changes published?

**Comment by jywarren** [comment]
Not yet, I hope to in the next hour. But did you see Stevie reported a new
comment-on-question bug?

**Comment by Souravirus** [comment]
No, I haven't seen.

**Comment by Souravirus** [comment]
Exactly where did Stevie reported. Is it a github issue?

**Pull request merged**
