### PR TITLE
Proposed fix for bio issue

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

@jywarren Don't know for sure as I did not get that issue locally.

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, can you paste in the exact output when you encounter the error, link to a build or something so we can better diagnose?

**Comment by ryzokuken** [comment]
@jywarren: @icarito pasted a snippet from the logs sometime ago in the chatroom, you could check that out. Whenever he comes back online, I would do the task again and ask him to give me the exact logs and post them here. :)

The whole issue arose because I could not recreate the issue on my local environment. Was staging a little old? Perhaps a fix has already been made?

**Comment by jywarren** [comment]
Staging looks OK now -- was new account creation the problem?
http://jenkins.laboratoriopublico.org/

Apart from the logs, what sequence of actions led to an error and what did
it look like? Thanks!

**Comment by ryzokuken** [comment]
@jywarren I will retry and let you know.

**Comment by ananyo2012** [comment]
I see a test failing. Probably it is taking an empty string to be nil. @ryzokuken  Can you fix the test and push the changes?

**Comment by ryzokuken** [comment]
@ananyo2012 maybe it's related to the change I made and the test needs to be changed?

**Comment by ananyo2012** [comment]
Yes now that an empty string is assigned it takes it as nil. Can you update
the test?

**Comment by jywarren** [comment]
Hi, Ryzokuken - i believe this is all addressed in #1553 which is almost ready. But if you can recount exactly what you did to discover this error and what exactly the error was (log output, 500 error, etc) we can be sure. Otherwise let's close this -- thanks for reporting!

**Comment by ryzokuken** [comment]
@jywarren pefect. All tokens work perfectly and user is created in staging. I am closing this now, thanks for all the help. Could you hop in the chatroom for a minute or two and guide me while testing if the commenting API function works? If it does, I could start working on a function to post a comment on plotsbot and make a few behaviors using this functionality.

**Comment by jywarren** [comment]
Hi, Ujjwal - sorry, i am just back and online today from my trip, so I'm
way behind on everything. Could we try to find a time tomorrow, or could
you coordinate with someone else on the soc team for now? I'll hope to be
caught up soon!

**Comment by ryzokuken** [comment]
Sure, Jeff. I would wait until tomorrow. If someone else shows up by then,
I'll try to co-ordinate with them, otherwise I will wait for you. Thanks.

**Pull request closed without merging**
