### PR TITLE
#7109 fixed by adding the text to body in contact moderators "mailto:…

### PR DESCRIPTION
**Pull request by sunguru98**
…" Link

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sunguru98** [comment]
For some reason, I couldnt merge it, could some one help me please?

**Comment by sunguru98** [comment]
Done after looking at the Travis CI documentation. I had to change the test as well.

**Comment by skilfullycurled** [comment]
Hey @sunguru98, only some members of the group have the ability to merge after they review your tests and code.  When you are ready to have someone take a look, ping the reviewers by using the following @publiclab/reviewers, which I'll do right now.  : )

Hi @publiclab/reviewers, can someone please take a look at this pull request when you have a chance?  It's an FTO so I'd love to provide the satisfaction of finishing one as soon as you are able to!

**Comment by skilfullycurled** [comment]
Oh also, @sunguru98, don't forget to add the number of the issue this is a fix for at the top:

> Fixes #0000 (<=== Add issue number here)

**Comment by jywarren** [comment]
Looks awesome! Thanks so much!!

**Comment by jywarren** [comment]
Fixed #7109 ! Thanks everyone!!!! Great work! 🎉

**Comment by sunguru98** [comment]
Oh my God Oh my God Oh my God ... Im literally in cloud nine

**Comment by cesswairimu** [comment]
Awesome job @sunguru98, Welcome to PublicLab :balloon:

**Pull request merged**
