### PR TITLE
[WIP] custom google search on /search, routing to other types of search as well

### LINKED ISSUE #5716: Try to intercept search terms from a Custom Google Search
We're looking at whether an embedded Google search would be useful for really deep text searching on the site. But if we did this, we'd have to be able to access the search terms so we could also display things like related tags, and potentially use the URL hash to save the search results page in a URL for copy/pasting/permalinking. So I found this code segment that seems promising: 

```js
    google.load('search', '1', {language : 'en'});

    function OnLoad()
    {
        var customSearchControl = new google.search.CustomSearchControl('***my key****');
        customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
       customSearchControl.draw('cse');
        customSearchControl.execute("$q");
    }
    google.setOnLoadCallback(OnLoad);
```

https://stackoverflow.com/questions/2298027/pass-variable-to-google-custom-search-engine

Here's our testing page: https://publiclab.org/wiki/search

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #5716

This needs inputs and work on other search types! WIP

### CODE REVIEW

**Comment by CleverFool77** [comment]
This looks super cool :tada: :tada: , guess I need to learn a lot. :')
Bookmarking it for my future backend contributions

**Comment by jywarren** [comment]
No worries! I realized there are a lot of different scenarios here, like if
the search query is set already or not, or if you want to switch between
types or sortings within one page, and how to "fall back" to the database
search from the google search. I hope I've got everything right here!

**Comment by jywarren** [comment]
`ActionController::UrlGenerationError:         ActionController::UrlGenerationError: No route matches {:action=>"all_content", :controller=>"search", :query=>"page"}`

**Comment by jywarren** [comment]
```

 FAIL["test_browse_/search/*", #<Minitest::Reporters::Suite:0x0000556246b6c4e0 @name="PublicPagesTest">, 236.32423620600008]
 test_browse_/search/*#PublicPagesTest (236.32s)
        Expected response to be a <2XX: success>, but was a <302: Found> redirect to <http://www.example.com/search?q=foo>
        Response body: <html><body>You are being <a href="http://www.example.com/search?q=foo">redirected</a>.</body></html>
        test/integration/public_pages_test.rb:74:in `block in <class:PublicPagesTest>'
```

**Comment by jywarren** [comment]
```

 FAIL["test_searching_an_item_from_the_homepage", #<Minitest::Reporters::Suite:0x00007f89ba2366a8 @name="SearchTest">, 77.10580974999993]
 test_searching_an_item_from_the_homepage#SearchTest (77.11s)
        expected to find visible css "h2" with text "Results for Canon" but there were no matches. Also found "", "Search", which matched the selector but not all filters. 
        test/system/search_test.rb:13:in `block in <class:SearchTest>'

```

**Pull request merged**
