### PR TITLE
Fixed README.md file

### PR DESCRIPTION
**Pull request by arsen1c**
Fixes #0000 (<=== Add issue number here)
#9466
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by NishantJawla** [comment]
Good!! work @arsen1c

**Comment by arsen1c** [comment]
@NishantJawla Thanks! Can please elaborate on what the bot it trying to say? Did I make any mistake?

**Comment by NishantJawla** [comment]
> @NishantJawla Thanks! Can please elaborate on what the bot it trying to say? Did I make any mistake?

No, you haven't made any errors. The bot ran some tests on your code, and your pull request passed, as shown below.

**Comment by arsen1c** [comment]
@NishantJawla Thanks for clarifying :)

**Comment by arsen1c** [comment]
Hey @NishantJawla,  if everything is fine, then can we close this issue and merge the code?

**Comment by NishantJawla** [comment]
> Hey @NishantJawla, if everything is fine, then can we close this issue and merge the code?

When a collaborator sees the pull request, he or she will merge it.

**Review by cesswairimu — APPROVED** [review]
Great :tada: 
thanks for working on this @arsen1c

**Comment by cesswairimu** [comment]
Thanks @NishantJawla  for the review

**Pull request merged**
