### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by avinash080**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by subhahu123** [comment]
@avinash080  show the screenshot of the changes please

**Comment by avinash080** [comment]
send me your email id

**Comment by subhahu123** [comment]
> send me your email id

sorry ?

**Comment by subhahu123** [comment]
> Fixes #0000 (<=== Add issue number here)
> 
> Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
> 
> * [ ]  PR is descriptively titled bookmark_tabs and links the original issue above link
> * [ ]  tests pass -- look for a green checkbox heavy_check_mark a few minutes after opening your PR -- or run tests locally with `rake test`
> * [ ]  code is in uniquely-named feature branch and has no merge conflicts file_folder
> * [ ]  screenshots/GIFs are attached paperclip in case of UI updation
> * [ ]  ask `@publiclab/reviewers` for help, in a comment below
> 
> > We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!
> 
> If tests do fail, click on the red `X` to learn why by reading the logs.
> 
> Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
> 
> Thanks!

also add the issue no. u r fixing

**Comment by avinash080** [comment]
for screenshot send me your email id so i can mail you

**Comment by subhahu123** [comment]
> for screenshot send me your email id so i can mail you

no need u can directly show that here on github itself

**Comment by avinash080** [comment]
Screenshot (36)

**Comment by subhahu123** [comment]
not this i m asking u the preview of website after ur changes done

**Comment by avinash080** [comment]
I am not getting how to run it. sorry! as i have done web development in django and i wasn't able to find manage.py so i just committed directly

**Comment by subhahu123** [comment]
have u tried readme.md

**Comment by cesswairimu** [comment]
Hi @avinash080, could you please add the link to the issue you are solving? Thanks

**Comment by avinash080** [comment]
#6524 and #6525 was the issue i was solving

**Comment by SidharthBansal** [comment]
Please install plots2 and run localhost:3000 on your laptop to obtain the screenshots.

**Comment by avinash080** [comment]
sir i tried installing rvm but everytime any sort of error occured . my laptop isn't capable of dual boot so plz if u can check that .

**Comment by SidharthBansal** [comment]
What kind of error are you seeing?

**Comment by cesswairimu** [comment]
Hi @avinash080 the links you provided are for the pull requests..could you please check again and provide a link to the issue...thanks

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
