### PR TITLE
Fix recent questions on shadow page

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/6318

This PR aims to solve these bugs -
- [x] Mobile width in small screens
- [x] wrapping up of data
- [x] circular profile picture

Thanks !!!

Screenshot from 2019-09-27 19-34-29
Screenshot from 2019-09-27 19-34-48
Screenshot from 2019-09-27 19-34-58

### CODE REVIEW

**Comment by jywarren** [comment]
This is looking really nice. Is it possible to get the circles to remain inline with the text, OR at least to have the circles line up along the left edge of the text? I think it'd be a matter of padding to do the latter. Awesome, @CleverFool77 !

**Comment by CleverFool77** [comment]
Hi Jeff. You mean inline in mobile device right ?

**Comment by jywarren** [comment]
Well, see how they are in the full width view, in the same line as the
text? Could we do that?

Thanks!!!

**Comment by CleverFool77** [comment]
Sure Jeff. I'll do it.
Thanks !!

**Comment by CleverFool77** [comment]
This is the update of the PR as requested.
cc: @jywarren 

Screenshot from 2019-10-02 15-40-54
Screenshot from 2019-10-02 15-41-42

Thanks !!

**Comment by jywarren** [comment]
Looks good! I'm restarting tests as i think the failures were unrelated!

**Pull request merged**
