### PR TITLE
Trending tags showing duplicates [WIP]

### PR DESCRIPTION
**Pull request by ValentinaTironi**
Fixes #3963 
I'm sure this works now! Check it out for you
screen shot 2018-12-11 at 1 30 05 am

I saw that the last time it didn't work so I would like try again :) Thank you!

### CODE REVIEW

**Comment by ValentinaTironi** [comment]
@jywarren

**Comment by milaaraujo** [comment]
@ValentinaTironi, I assigned #3188 to myself and leave a comment saying I would work on it 3 days ago. Don’t start working on something that another person is also working on without warning beforehand. This prevents us from wasting our time...

**Comment by milaaraujo** [comment]
Anyway I can review this later, I already have a few examples ready on my computer to test the problem.

**Comment by jywarren** [comment]
Hi, I just wanted to say this can happen, it's all right - and in this case, it's an interesting outcome because the solution proposed here was different. I think we have a potential path forward in #3188 but I am interested in whether the `distinct` being at the end is resulting in a different query that also works?

Thanks all for cooperating and your work is always valued here 👍 🙌

**Comment by milaaraujo** [comment]
It is ok, @ValentinaTironi! It was not my intention to discourage anyone from collaborating with the project! ;) Any collaboration is welcome, but it is always good to try to coordinate our work in order to make the most of each one.

Your solution is also working properly:
```
SELECT  DISTINCT `term_data`.`name` FROM `term_data` 
INNER JOIN `community_tags` ON `community_tags`.`tid` = `term_data`.`tid` 
INNER JOIN `community_tags` `node_tags_term_data_join` ON `node_tags_term_data_join`.`tid` = `term_data`.`tid` 
INNER JOIN `node` ON `node`.`nid` = `node_tags_term_data_join`.`nid` 
WHERE (node.status = 1) AND (node.created > 1541995976) AND (node.created <= 1544587976) 
GROUP BY `term_data`.`name`, node.nid, term_data.tid, community_tags.nid, community_tags.uid, community_tags.date 
ORDER BY count DESC LIMIT 5;
+------------------------+
| name                   |
+------------------------+
| first-time-poster      |
| lat:74.92979837188261  |
| lat:35.67314305234031  |
| lon:21.714137445587394 |
| lon:45.76772749324683  |
+------------------------+
```
I just think the solution in #4266 is better because it is simpler and removes "group by" that does not make much sense here. What do you think?

**Comment by ValentinaTironi** [comment]
I'm totally agree 💯 I left a comment in you PR already #4266

**Comment by milaaraujo** [comment]
After merging #4266 we will have an extra step to test it with MySQL:

>"then let's actually open a PR where we change the database back to mysql (but version 5.7) to see if the error crops up there again. [...]"

You can help with this if you want!

**Comment by ValentinaTironi** [comment]
That is a more efficient solution

**Pull request closed without merging**
