### PR TITLE
English locales combined into a single file

### LINKED ISSUE #4702: Combine all the YAML files present in config/locales in a single file
At https://github.com/publiclab/plots2/tree/master/config/locales we have all the YAML files in the directories. We want to combine all the files present in those directories with one file for each language. Let's start with English. 

Either we can do this task manually or can use some help from existing resources. I have found https://gist.github.com/branch14/1010381 to be useful and have tested it too. Yes, it works. 

@jywarren I think we can use above code first to combine and then run https://gist.github.com/branch14/5746d4f117f00490fea5 to count for conflicts. As a precaution, I will look at the combined file closely too for ensuring integrity. Sounds good?

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #4702 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
@jywarren should I delete the directories or we should keep it for a while? We can test on `unstable` if we decide on deleting directories containing en.yml files. 

Let me know, what do you think. Thanks!

**Comment by jywarren** [comment]
Let's go ahead and delete unless you think it'll cause us trouble somehow?

**Comment by gauravano** [comment]
I will delete the folders and push to the `unstable` for testing @jywarren. Thanks!

**Comment by gauravano** [comment]
Hi @jywarren, I deleted first directory and also tested some translation locally and they are working. There's one issue- after merging all en files into one, some of the values are copied without double quotes and some are in quotes. I tried some examples of running (without quotes) strings and all of them worked out. Do you think we should manually put the quotes on values?

**Comment by gauravano** [comment]
Also, here's something related to refer - https://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml

**Comment by gauravano** [comment]
Hi @jywarren, I have removed all locales and we just have 3 files now, for 3 languages. Your thoughts required here :arrow_right:  https://github.com/publiclab/plots2/pull/4716#issuecomment-458626174.

I checked Transifex's compatibility with quotes and both works there. The difference is Translation generated for double-quotes will be in double-quotes and for strings without quotes will generate without quotes translated values (most of the time, not sure as there's no official documentation found) 

In that stack-overflow link I pasted, there's a comment saying - https://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml#comment71756930_22235064

lol

I can feel this person's feeling :confused:. Also, as we have to work in 8 other languages too, so I think, we should put the quotes on strings where they were present before merge. What do you say?

This way we will also come to know about the presence of all the strings :sweat_smile:

**Comment by jywarren** [comment]
I like the answer on that SO post! Can we quote it in our docs and standardize to that policy for quotation marks?

**Comment by jywarren** [comment]
Ah I see. Well, I guess I think you're right here. As many languages will need quotes, let's just standardize them. We'll often need single quotes for apostrophes, so let's standardize to double then, if I understand you?

**Comment by gauravano** [comment]
Originally, we have double quotes so I think we should stay with it. Although, there are some string values which don't use quotes too. I will just change the string values to match our old system string pattern, so will put double-quotes where it were in old system and no quotes for those without quotes in old ones.

I have also opened an issue for the same - https://github.com/publiclab/plots2/issues/4729

cc @jywarren

**Comment by gauravano** [comment]
I have added the above commits to #4751 . So, closing this. Thanks!

**Pull request closed without merging**
