### PR TITLE
Fixed message consistency issues on the subscriptions page.

### LINKED ISSUE #4639: Message Consistency on the Subscriptions Page
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

On the [subscriptions](https://publiclab.org/subscriptions) page, we need to pluralize the word 'email' in the description around the 'Email Settings' button. While we're at, we can go ahead and standardize the styling to match that of the description above it. 

screen shot 2019-01-17 at 1 24 38 am

## Solution

Where to find the relevant lines of code: 

in `app/views/home/subscriptions.html.erb`, the code the description and link is all written on one line:
https://github.com/publiclab/plots2/blob/9f7cfc47ded41ed3a7370c66a9c4f7af9704af59/app/views/home/subscriptions.html.erb#L20

1) The link (`a` tag) is currently nested in the paragraph (`p` tag), lets move the paragraph below it instead of around it. 

2) Lets change the text to "Control which emails you want to receive." to make it more succinct. 

3) Add italics to the text with a `style` attribute and the declaration `font-style:italic;`

It should look something like this afterwards: 
`<p style="font-style:italic;">Control which emails you want to receive.</p>`

4) One last change. The 'Email Settings' button needs a margin under it. Add a `style` attribute onto the `a` tag with the declaration `margin-bottom:10px;`

The goal is for it to look just like the one above in the end: 
screen shot 2019-01-17 at 1 41 08 am

Thanks!!

## Steps to Fix
 
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by SashwatAnagolum**
Fixes #4639 

Makes the styling and placement of buttons and associated descriptions consistent.

### CODE REVIEW

**Comment by sashadev-sky** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by SashwatAnagolum** [comment]
Hi @sashadev-sky,

So sorry about the delay. Since the job was simple - just switching up HTML tags - I figured I could complete it straight in the browser.
I did try to set up the development environment required for plots2, but ran into a couple of issues with that regarding rvm. Nonetheless, I should have it up and running, and will upload the required screenshot by EOD.

**Comment by sashadev-sky** [comment]
@SashwatAnagolum No rush! Let me know if you run into more issues

**Comment by sashadev-sky** [comment]
@SashwatAnagolum hey just wanted to know if you were still working on this! 😊

**Comment by SashwatAnagolum** [comment]
Hi @sashadev-sky,

I have been working on getting plots2 set up over the last couple of days, but have faced a bunch of issues:

image

This has shown up repeatedly despite me being sure that nothing else is running on the http://localhost:3000/ port.

I am running the Linux subsystem on Windows 10, and have followed the instructions in the prerequisites file, then the installation instructions given at https://github.com/publiclab/plots2#standard-installation.

I really want this PR to close, and to continue contributing to plots2, so I would love it if you could help me out with this.

If neccessary, I can open a new issue. I would really appreciate any help on this!

**Comment by sashadev-sky** [comment]
@SashwatAnagolum I'm sorry you're having so much trouble with the set up. It's okay, it happens to everyone. This past week it took me 2 days to figure out why the server wasn't working for me.. Have you tried just running `rails s` instead of `passenger start`. Passenger start has never worked for me

**Comment by sashadev-sky** [comment]
@also did you check explicitly if you have any pids active. Then you will know for sure if you are running another server on. Sometimes if you close your terminal without killing the server in rails first, its pid continues to persist even though it appears nothings running

**Comment by jywarren** [comment]
Hi! There've been some resources for Windows use posted over here, and
maybe others have had similar troubles and could offer some advice there?

https://github.com/publiclab/plots2/issues/3840

Thanks for sticking with it!

**Comment by jywarren** [comment]
Great, thanks both of you!!! 🎉 🎉

**Comment by gauravano** [comment]
Hi @SashwatAnagolum , thanks for nice work. We would love to have more help from you. If you are interested in solving more issues then check here - https://code.publiclab.org/#r=all for a new issue. In case, you are unable to find an issue, feel free to comment here. Thanks!

**Pull request merged**
