### PR TITLE
Align Topic Card Images

### PR DESCRIPTION
**Pull request by nicobermudez**
Fixes #5999 

Aligns the images / gray circles within the Topic Cards inline with the post title and author. Also, fixes an uncaught bug in L6, changing the closing h3 tag to h4. 

Screen Shot 2019-07-11 at 09 29 07

### CODE REVIEW

**Comment by nicobermudez** [comment]
@CleverFool77 let me know if this is okay or if there is anything I should fix. This issue stems from the comments in the PR #5999.

**Comment by CleverFool77** [comment]
The screenshot looks good. Great!!!

**Comment by CleverFool77** [comment]
Hi @nicobermudez can you resolve the merge conflicts ?

**Comment by nicobermudez** [comment]
@CleverFool77 Yes, sorry! Should be all set now

**Comment by CleverFool77** [comment]
Awesome !! :tada: This is now ready @jywarren

**Comment by CleverFool77** [comment]
Hi @nicobermudez For further contribtuion, you can find the bug of project yourself and look for some issues with `help-wanted` label and etc.

**Comment by jywarren** [comment]
Oh, looks awesome!!! Thanks! 

I think the error in Travis is probably unrelated -- a timing issue... i'll try re-running it to see if i can get it to pass!

**Comment by jywarren** [comment]
Perfect. Merging it!!! 🎉

**Comment by nicobermudez** [comment]
Awesome!! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
