### PR TITLE
test 'incomplete spamaway test does not create new user record', and fix users controller to prevent user creation in this scenario

### PR DESCRIPTION
**Pull request by jywarren**
Re: #8463 and related to https://github.com/publiclab/plots2/blob/8c9c39da0152d5a965e7eb77697c056ca3d45111/test/system/signup_form_test.rb

### CODE REVIEW

**Comment by jywarren** [comment]
NIce! Hopefully failed for the right reason...

**Comment by jywarren** [comment]
Nice!

```
 FAIL["test_incomplete_spamaway_test_does_not_create_new_user_record,_returns_useful_validation", #<Minitest::Reporters::Suite:0x000000000e88ab68 @name="SignUpTest">, 223.629028694]
 test_incomplete_spamaway_test_does_not_create_new_user_record,_returns_useful_validation#SignUpTest (223.63s)
        "User.count" didn't change by 0.
        Expected: 19
          Actual: 20
        test/integration/signup_flow_test.rb:85:in `block in <class:SignUpTest>'
```

OK, now the fix...

**Comment by jywarren** [comment]
huh -- 

```
 FAIL["test_incomplete_spamaway_test_does_not_create_new_user_record,_returns_useful_validation", #<Minitest::Reporters::Suite:0x00000000147ae9f0 @name="SignUpTest">, 196.193361467]
 test_incomplete_spamaway_test_does_not_create_new_user_record,_returns_useful_validation#SignUpTest (196.19s)
        Expected false to be truthy.
        test/integration/signup_flow_test.rb:98:in `block in <class:SignUpTest>'
```

**Comment by jywarren** [comment]
trying in gitpod...

**Comment by jywarren** [comment]
Confirmed the message appears:

image

**Comment by jywarren** [comment]
aha, ok, i left the blank area filled, so we had 2 errors instead of 1... fixed!

**Comment by jywarren** [comment]
Hmm... now we get a failure on the next assertion:

```
 FAIL["test_incomplete_spamaway_test_does_not_create_new_user_record,_returns_useful_validation", #<Minitest::Reporters::Suite:0x000000000cafa760 @name="SignUpTest">, 21.407707958000003]
 test_incomplete_spamaway_test_does_not_create_new_user_record,_returns_useful_validation#SignUpTest (21.41s)
        Expected false to be truthy.
        test/integration/signup_flow_test.rb:99:in `block in <class:SignUpTest>'
```

**Comment by jywarren** [comment]
Same problem detecting text in `test/integration/signup_flow_test.rb:99:in `block in <class:SignUpTest>'` - testing manually in gitpod now...

**Comment by jywarren** [comment]
Oooh interesting... functional test failure, i'll try restarting it... -- a weird one!

```

/home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/uri/common.rb:739:in `URI': bad argument (expected URI object or URI string) (ArgumentError)
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/codecov-0.2.11/lib/codecov.rb:406:in `upload_to_v4'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/codecov-0.2.11/lib/codecov.rb:372:in `upload_to_codecov'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/codecov-0.2.11/lib/codecov.rb:470:in `format'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/simplecov-0.19.0/lib/simplecov/result.rb:51:in `format!'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/simplecov-0.19.0/lib/simplecov/configuration.rb:196:in `block in at_exit'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/simplecov-0.19.0/lib/simplecov.rb:189:in `run_exit_tasks!'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/simplecov-0.19.0/lib/simplecov.rb:179:in `at_exit_behavior'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/simplecov-0.19.0/lib/minitest/simplecov_plugin.rb:11:in `block in plugin_simplecov_init'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/minitest-5.14.2/lib/minitest.rb:64:in `reverse_each'
	from /home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.6.0/gems/minitest-5.14.2/lib/minitest.rb:64:in `block (2 levels) in autorun'
```

**Comment by jywarren** [comment]
Nice!!! Merging.

**Comment by cesswairimu** [comment]
Fantastic :tada:

**Pull request merged**
