### PR TITLE
Explaining why first-timers can't Save as Draft

### LINKED ISSUE #9977: Explain why new contributors can't save a post as draft
A new contributor on PublicLab cannot create drafts and there's no help text or guide in the post page that helps the user understand this. I remember being really confused when I wanted to save my proposal as a draft.

Screenshot 2021-07-09 at 09 55 30

A small text could be added at the bottom that says `New contributors are not allowed to create drafts`.

_Originally posted by @TildaDares in https://github.com/publiclab/plots2/issues/9888#issuecomment-877031292_

### PR DESCRIPTION
**Pull request by phyleria**
Fixes #9977  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by noi5e** [comment]
@phyleria Thanks for this! This looks good so far.

Would you be able to post some screenshots or videos of these changes so that we can see how it looks/behaves?

**Comment by phyleria** [comment]
@noi5e Thank you so much for the feedback I'll try and do so.

**Comment by noi5e** [comment]
Thanks @phyleria, let us know if you need any help! 

I don't know what your development environment is like, but you start by opening up this branch's Gitpod to see what the changes are like:

Screen Shot 2021-08-16 at 1 22 00 PM

**Comment by phyleria** [comment]
Thank you @noi5e , I was actually experiencing problems while trying to set up my development environment that's why I was unable to attach the images. I would really appreciate your help on setting it up.

**Comment by noi5e** [comment]
@phyleria Got it! Try opening up the Gitpod first, that should get you a fully functioning version of this site. If you get stuck, take a screenshot and post it here!

**Comment by phyleria** [comment]
Hi @noi5e I am experiencing a problem "Error starting web application" when I'm running the website. Please help

**Comment by noi5e** [comment]
Hmm interesting. When I start Gitpod currently, I get the following error:
Screen Shot 2021-08-17 at 9 20 11 AM

Is this what you were talking about @phyleria?

How were you able to work on this? Did you set it up locally? I mean, on your computer?

**Comment by phyleria** [comment]
image
Hi @noi5e that's my workspace if you can access or see it. I really don't know how to attach an image in the comments.

**Comment by phyleria** [comment]
That's how my workspace looks like. I don't know how to make the project run on the gitpod browser.

**Comment by noi5e** [comment]
@phyleria Thanks, that screenshot is helpful. Normally with GitPod, a "browser" will open up where you can see and interact with the website, like this:
Screen Shot 2021-08-19 at 6 31 46 PM

For some reason, that browser isn't opening up in GitPod here. That could be a problem with GitPod itself!

In the meantime, have you tried following the installation instructions [here](https://github.com/publiclab/plots2#installation) to set up the repository locally?

**Comment by phyleria** [comment]
Hi @noi5e Yes I had tried to follow the local installation process but for some reason my computer could not install ruby version 2.6.6

**Comment by noi5e** [comment]
@phyleria No worries, we can help you figure it out. Sometimes installation can be very complicated.

What's the error message you're getting? If you can, take a screenshot, or copy and paste the message from your terminal.

**Comment by phyleria** [comment]
This is the error that I'm getting while trying to install ruby version 2.6.6
x-special/nautilus-clipboard
copy
file:///home/phyllis/Pictures/Screenshot%20from%202021-08-18%2022-11-40.png

**Comment by noi5e** [comment]
> This is the error that I'm getting while trying to install ruby version 2.6.6

@phyleria I can't see that image, you can upload screenshots by clicking on the image and dragging and dropping it into the comment box on GitHub:

Screen Shot 2021-08-24 at 11 07 35 AM

**Comment by phyleria** [comment]
image

**Comment by phyleria** [comment]
Hi @noi5e that's what I'm getting. I've tried to install rvm to no avail

**Comment by noi5e** [comment]
Hmm, the `'rvm' command not found` sounds like you haven't installed rvm yet. 

It looks like rbenv might be available. What happens when you run a `rbenv install -l` command?

**Comment by phyleria** [comment]
Hi @noi5e I have rbenv installed but when I use it to install ruby 2.6.6 it fails. But it can install ruby 2.7.0

**Comment by noi5e** [comment]
Hi @phyleria sorry for the long wait! 

You will probably be able to solve this problem faster if you copy-and-paste the error messages you are seeing to see if anyone else has solved a similar problem.

You will also want to look at [the documentation for rbenv](https://github.com/rbenv/rbenv), and do your own research.

If you run `rbenv install -l` you can see what versions of ruby rbenv has installed. It might be that ruby 2.6.6 is not installed. Feel free to also look at [this cheatsheet](https://devhints.io/rbenv) and good luck!

**Comment by noi5e** [comment]
@phyleria Just checking in here, have you tried to install ruby 2.6.6? Here's a suggestion that I had:

> If you run rbenv install -l you can see what versions of ruby rbenv has installed. It might be that ruby 2.6.6 is not installed. Feel free to also look at this cheatsheet and good luck!

**Comment by phyleria** [comment]
Hey @noi5e I'm really sorry for replying this late. I have tried every solution you gave and even more suggestions online but I've not been successful. My laptop can't install the exact version of ruby 2.6.6. 
When I typed rbenv install -l the only version available was 2.6

**Comment by Tlazypanda** [comment]
Hey @phyleria if the version seems to be missing you should upgrade ruby-build using the command - 
if installed from git repository run this - 
```
$ cd ~/.rbenv/plugins/ruby-build
$ git pull
```

or if it's from MacOS
`
brew update && brew upgrade ruby-build`

And then try the same command
`rbenv install 2.6.6`

Hope this helps :v:

**Comment by phyleria** [comment]
Hi @jywarren @noi5e I was finally able to run my gitpod and I got the images of before and after I edited the file. My recent commits are changes I made to modify the first commit for PR. I'll continue editting meanwhile here are the images

x-special/nautilus-clipboard
copy
file:///home/phyllis/Downloads/Screenshot%20from%202021-10-17%2016-58-19.png
x-special/nautilus-clipboard
copy
file:///home/phyllis/Downloads/Screenshot%20from%202021-10-17%2016-59-35.png

**Comment by phyleria** [comment]
Hi @jywarren @noi5e I was finally able to run my gitpod and I got the images of before and after I edited the file. My recent commits are changes I made to modify the first commit for PR. I'll continue editting meanwhile here are the images
image
image

**Comment by cesswairimu** [comment]
Hi @phyleria the above screenshot is looking good, maybe we could make the text color gold or yellow?  what do you think? 
Also I notice you made the PR from your main branch kindly create it from a branch and we can get this merged. Thanks and sorry for the very late reply

**Comment by phyleria** [comment]
Thank you so much @cess I will follow your guidelines and push it. Thanks
for the suggestions 😊

**Comment by cesswairimu** [comment]
This PR has been open for a long time and no activity/ reviews requested has not been addressed. We understand you might be busy and engaged on other things. I am closing this for now...please  feel free to reopen if you get some time and would like to finish this. Rem to check if its still available before you reopen. Thanks

**Pull request closed without merging**
