### PR TITLE
View of Contributor page changed

### LINKED ISSUE #1736: apply same button treatment to all tabs on tag pages
hello everyone!

I noticed that this page https://publiclab.org/tag/pesticides has a very nice display of buttons for "Follow [topic]" "Ask a question about [topic]" and "Subscribe to answer questions on [topic]" that is consistent across most tabs (`Research Notes`, `Questions`, `Wiki pages`, `Maps` ):

screen shot 2017-10-27 at 8 59 37 am

....but not all tabs -- `Contributors` is very different, and I believe this may be an oversight:

screen shot 2017-10-27 at 8 59 20 am

Do we think this is fixable? Thanks!

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #1736 
Optimization of contributor page view

### CODE REVIEW

**Comment by Gauravano** [comment]
Updated view @jywarren 

logout

login

**Comment by Gauravano** [comment]
@jywarren these are the updated views - 

login

logout

Any more changes required?

**Comment by jywarren** [comment]
Amazing! Can we substitute "contributor" instead of "user"?

**Comment by jywarren** [comment]
Awesome!!!

**Pull request merged**
