### PR TITLE
Fix Error reporting and parsing (fixes #1852)

### LINKED ISSUE #1852: Fix Dangerbot parsing of Travis errors in Rails 4
Until recently, Dangerbot would repeat out errors and failures in each PR, like in this example:

https://github.com/publiclab/plots2/pull/1708#issuecomment-338683472 (see how Dangerbot actually reproduced the errors in its comment?)

In this recent one (after the Rails 4.1 upgrade), this no longer happens. This PR, which had the error:

```
TagNodeAssociationExtension was here
Started with run options --seed 66
 FAIL["test_should_return_error_for_wiki_pages_that_do_not_follow_/slug_format", WikiControllerTest, 60.372967383999935]
 test_should_return_error_for_wiki_pages_that_do_not_follow_/slug_format#WikiControllerTest (60.37s)
        Expected response to be a redirect to <http://test.host/404> but was a redirect to <http://test.host/wiki/invalid>.
        Expected "http://test.host/404" to be === "http://test.host/wiki/invalid".
        test/functional/wiki_controller_test.rb:274:in `block in <class:WikiControllerTest>'
  577/577: [===============================] 100% Time: 00:01:29, Time: 00:01:29
Finished in 89.24451s
577 tests, 1708 assertions, 1 failures, 0 errors, 0 skips
```

shown here: https://travis-ci.org/publiclab/plots2/builds/314000925?utm_source=github_status&utm_medium=notification

does not show any Danger-reported messages: https://github.com/publiclab/plots2/pull/1851

(you can open a new PR with failed tests to confirm this)

The Dangerfile is here:

https://github.com/publiclab/plots2/blob/master/Dangerfile

The error it generates is:

```
There was an error with Danger bot's Junit parsing:
undefined method `value' for nil:NilClass
```

Let's fix this! It may also involve the .travis.yml file here, which generates the output.xml files which Danger and Junit parse:

https://github.com/publiclab/plots2/blob/5ffd7c6b3f9d2a3a53946a3433970ce1590ceb15/.travis.yml#L22-L25

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren YAY! Let me know when you're okay with this one, and I'll remove the error.

**Comment by jywarren** [comment]
Looks perfect, fantastic fix thank you @ryzokuken!

**Comment by ryzokuken** [comment]
@jywarren so, here it is. Feel free to merge this.

**Comment by ryzokuken** [comment]
@jywarren this happened:

```
$ touch ./test/reports/TEST_.xml

touch: cannot touch ‘./test/reports/TEST_.xml’: Permission denied

The command "touch ./test/reports/TEST_.xml" exited with 1.
```

strange. Why are there permission issues to begin with? There weren't any earlier and we didn't change anything related to the directory permissions, did we?

Also, generally, I had no idea why were doing all the stuff in https://github.com/publiclab/plots2/blob/16e72792e6edf5ea4ea98da9e063abaa8acd8eb8/.travis.yml#L21-L26 in the first place... Specifically the lines in https://github.com/publiclab/plots2/blob/16e72792e6edf5ea4ea98da9e063abaa8acd8eb8/.travis.yml#L22-L24. We run the tests, generating reports on the way, join together all the reports in a single `output.xml` file and then run danger on the `output.xml`, parsing it and making a comment.

But why do we make an empty file in there? Why make the directory? Doesn't the directory already exist? What purpose does the empty file serve?

**Comment by jywarren** [comment]
I removed them -- let's see!

**Comment by ryzokuken** [comment]
@jywarren sure, gimme a second.

**Comment by ryzokuken** [comment]
@jywarren It worked! YAY!

**Comment by jywarren** [comment]
🥂 👍 💯

**Comment by ryzokuken** [comment]
@jywarren what next? Anything you specifically wanted me to work on?

**Pull request merged**
