### PR TITLE
Move donate button (resolves #1734)

### LINKED ISSUE #1734: Move donate button next to join button
This was brought up while working through #1710, but split into a separate issue due to additional complexities.

Currently, the 'Donate' and 'Store' buttons are hidden once the screen size gets too small. In addition to moving the 'Donate' button over to the right of the 'Join' button, make it responsive so that it doesn't simply hide on smaller windows, but rather moves with the 'Join' button into the dropdown.

Does this sound right  @jywarren ? If so, I will go ahead and get started on this once #1710 is merged.

### PR DESCRIPTION
**Pull request by ianroberts131**
This resolves #1734. What I decided to do was to put the donate link into the 'Get Involved' dropdown and the store link into the 'About' dropdown once the screen size got smaller and the buttons are hidden. Here's a gif showing what happens:

move-donate-button

Let me know if you think this is a good approach, or if you would like to see something different.

***********************

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Wow, this is clever and really cool. Let me check with @ebarry first though! Thanks!!

Liz check out the animated gif to see how this works!

**Comment by jywarren** [comment]
Hi, we've been gone doing a big event in Louisiana, then our staff retreat, so I'm sorry we haven't been online! We'll circle back to this at the start of next week; can you look at rebasing this over the most recent header changes? Thank you very much! 🎉

**Comment by jywarren** [comment]
Hi, @steviepubliclab @ebarry -- how does this look for preserving the donate and store buttons when the page is narrowed? The animated gif on this page shows how it works! 

@ianroberts131 -- apologies for our slowness on this -- we had a big event two weeks ago and then I've been traveling since, so I'm just catching up now. Many thanks for your work on this!

**Comment by jywarren** [comment]
Hi, I think we're good to go with this, i'm sorry we haven't been able to merge it earlier. Would you be able to rebase this so we can merge it? Thank you!!

**Comment by jywarren** [comment]
@ebarry this is the one we're hoping to merge in soon -- look good to you?

**Comment by jywarren** [comment]
OK -- i just resolved the conflicts here and we should be good to go. @ianroberts131 does this look right to you? 

https://github.com/publiclab/plots2/pull/1748/files

Sorry this took a while! We just got the upgrade to Rails 4.1 merged in! :-)

**Comment by jywarren** [comment]
🎉

**Comment by ebarry** [comment]
Hi everyone! I am SO SORRY i was missing these notifications. This looks great! So glad we can move ahead with this cool solution! Thank you for creatively addressing this!

I have another question, is there any blank space on the menu bar that is being held open, like where an old menu used to be? In the very helpful animation of the screenwidth decreasing, it seems like there's actually still plenty of room for the button at the moment when it disappears.

**Comment by jywarren** [comment]
I think one issue is that there are different Bootstrap "width classes" which we're designing with -- triggering at different widths. The one where the buttons disappear has enough space at the outer end of its width range, but at the smaller end of the range you see this happen:

screenshot 2017-12-11 at 1 55 38 pm

So we can develop a custom system for width management, with custom width definitions, but this does make the code a bit harder to maintain. Still possible!

**Comment by ryzokuken** [comment]
@jywarren yeah, I also had a problem how both of these buttons looked (hint: not consistent). Do you have a little time to talk about the bootstrap migration and I could work on that over the next few days (This semester is finally over and I have a few days at my disposal for working on plots2)

**Comment by ebarry** [comment]
Hi @ryzokuken ! Congrats on finishing another semester. Thanks for checking on this -- we'd love to work out the migration with you, i'll leave it to @jywarren to see when because i just checked and even if we start Open Call half an hour early tomorrow that's still 1 in the morning your time!

**Comment by ryzokuken** [comment]
Thanks @ebarry! I don't think time is going to be an issue, it's already 1:25 here. That said, I'm okay with whichever medium of communication works the best for you all.

**Comment by ebarry** [comment]
awesome! come on in at 12:45am your time! https://zoom.us/j/415220636

**Comment by ryzokuken** [comment]
@ebarry Zoom says it's bound to start after another 45 minutes...

**Pull request merged**
