### PR TITLE
Fix/grid scroll #1070 #1256

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren #1256

**Comment by jywarren** [comment]
This looks good, is it ready to merge? Thanks!

**Comment by mridulnagpal** [comment]
@jywarren Yeah then we can start the next issue

**Comment by jywarren** [comment]
Wow, fantastic. I'll try it out in staging in a bit.

**Comment by jywarren** [comment]
http://testing.laboratoriopublico.org/locations/form

Great, it autocompletes -- now, we'd want to update the map. Thanks, and great work!!!

**Pull request merged**
