### PR TITLE
added >> to 'add research note' button 

### LINKED ISSUE #2194: Same button treatment
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process
### Please describe the problem
On public lab we usually have buttons like this:
image
By mistake someone has made button like this
image
See on the https://publiclab.org/notes/warren/06-22-2017/balloon-mapping-stories-part-1
It lacks >> at the end which is not in analogy with the rest of buttons

### Solution
Add the  &raquo; symbol

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Add ` &raquo;` to https://github.com/publiclab/plots2/blob/00cc80b0bd7c7d6b3e02a9f6d81e039b3efef3d9/app/views/sidebar/_related.html.erb#L7 as done in
 https://github.com/publiclab/plots2/blob/00cc80b0bd7c7d6b3e02a9f6d81e039b3efef3d9/app/views/sidebar/_related.html.erb#L8

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

### PR DESCRIPTION
**Pull request by shannonnolan17**
Fixes #2194 
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
As the cases are failing I am closing the PR and then reoping it

**Comment by jywarren** [comment]
Yes, no worries, this is probably not related to your work -- sometimes our testing system has some issues and we have to wait a bit! 

Thanks for your help!!!

**Comment by ryzokuken** [comment]
The failing test:

```ruby
  test 'should choose i18n for sidebar/_related' do
    available_testing_locales.each do |lang|
      get '/change_locale/' + lang.to_s
      follow_redirect!

      get '/wiki/' + nodes(:organizers).title.parameterize
      assert_select 'a', I18n.t('sidebar._related.write_research_note')
    end
```

**Comment by ryzokuken** [comment]
The failure:

```
FAIL["test_should_choose_i18n_for_sidebar/_related", Minitest::Result, 57.47591724199992]
 test_should_choose_i18n_for_sidebar/_related#Minitest::Result (57.48s)
        <Write a research note> expected but was
        <Public Lab>.
        Expected 0 to be >= 1.
        test/integration/I18n_test.rb:351:in `block (2 levels) in <class:I18nTest>'
        test/integration/I18n_test.rb:346:in `each'
        test/integration/I18n_test.rb:346:in `block in <class:I18nTest>'
```

**Comment by ryzokuken** [comment]
@jywarren I cannot push commits to @shannonnolan17's fork. Strange.

**Comment by ryzokuken** [comment]
Okay, they still fail locally. Let's see what happens on Travis.

**Comment by ryzokuken** [comment]
Okay, now it works. Cheers.

**Comment by jywarren** [comment]
Awesome! Thanks everybody and especially @shannonnolan17 -- we really appreciate it! If you're looking to take on another, please check out https://github.com/publiclab/plots2/labels/help-wanted

**Comment by shannonnolan17** [comment]
Anytime! Glad you were able to fix all those issues! 😂

**Pull request merged**
