### PR TITLE
fixed issue where tag page wiki link was pointing to wrong address

### PR DESCRIPTION
**Pull request by Souravirus**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
Hi, @Souravirus just a few suggestions, the PR having the relevant name as issue ease the task when the workload is high and you can tag with the issue by writing in PR body as Fixes #issue-number.Although great work and thanks for fixing it so fast.

**Comment by Souravirus** [comment]
Fixed #2204

**Comment by Souravirus** [comment]
I have tagged this pr with issue @Gauravano and I have already wrote the pr with the issue name.

**Comment by Souravirus** [comment]
@Gauravano made the changes which you told

**Comment by jywarren** [comment]
Awesome, thank you both!!! 🎉 🎈 👍

**Comment by Souravirus** [comment]
thanks @jywarren

**Pull request merged**
