### PR TITLE
Commenting System for Q & A Project

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
Work is almost complete for the new commenting system. Only part left is the expandable textboxes for comments. @jywarren @ebarry have a look at the screenshots below. Your feedback is most welcome.

**Comment by ananyo2012** [comment]
This is the view of the answer comments. The **Comments** button is a toggle button that toggles the comment section.
answer_comment_1

**Comment by ananyo2012** [comment]
When you click on the View more button more comments are displayed. The comments are displayed in descending order of their creation. i.e. recent comments appear at the top and older ones are shown below.
answer_comment_2

**Comment by ananyo2012** [comment]
Here is a screenshot of the edit view using in-place edits.
answer_comment_3

**Comment by ananyo2012** [comment]
Finally this a view of the question comments. Comments for question are listed just after the tags section. It is similar to the answer comments. I didn't include a toggle button for question comments. It would be better to display the recent question comments. Similar as before more comments can be seen with the **View more** button.
question_comment

**Comment by ananyo2012** [comment]
I have used  three folding view for the View more button. Initially three comments will be shown. As you click on the View more button next three comments are shown and so on until you hit the end of list where the View more button disappears.

**Comment by jywarren** [comment]
Great -- could you use icons in addition to text for Edit and Delete
(pencil and trash icons)? You could make them #888 grey. Who can delete
comments? Do only they see "delete"?

Perhaps "View more" could be "View 5 more comments" based on the count?

Also, what do you think about making the blue area grey?

Thanks!!

**Comment by ananyo2012** [comment]
Implemented expanding comment boxes! This is how they look.
text-box-1
text-box

**Comment by ananyo2012** [comment]
@jywarren Included the icons for delete and edit buttons. See below.
answer buttons

Well users without a profile icon have a grey icon by default. A grey background will hinder visibility of those icons. I can try a lighter shade for blue if you suggest.

Admin, moderator, the question author and the comment author can delete comments. 

Well let us then show 3 comments initially and then 5 more comments sequentially as the view more button is clicked. What do you say?

**Comment by jywarren** [comment]
Thanks! I guess I'm more interested in the viewer being able to see how
many total comments there are (without having to click), and the number per
click is less important.

Can you right-align the buttons so the delete buttons line up? Sometimes if
you're moving too fast, and the button in a given position switches, you
might delete by accident, so consistency is important.

I'd like to try a lighter grey, maybe #eee, or white and use separator
lines and a left indent instead of color - but I can also try some design
tweaks myself after merging, so no worries on that unless you enjoy the
design work especially.

Thanks!

**Comment by ananyo2012** [comment]
@jywarren Almost ready for merge. Waiting for your feedback. I will update the development.sqlite.example after you confirm the changes.

**Comment by jywarren** [comment]
Ah, @ananyo2012 - did you see my last few comments? They're pretty small and i'm ready to merge once you've taken care of them. Thanks for all your hard work!

**Comment by ananyo2012** [comment]
@jywarren Yeah just looking at them. Implementing them asap.

**Comment by jywarren** [comment]
no rush! just making sure you weren't still waiting for input. Thanks again!

**Comment by ananyo2012** [comment]
Well sorry Jeff, have to hold onto this for a bit. I introduced a bug on the way. Just trying to solve it out.

**Comment by jywarren** [comment]
no problem! good luck!

**Comment by ananyo2012** [comment]
@jywarren Made the necessary changes.Please review. I will update the sqlite file after you confirm.

**Comment by ananyo2012** [comment]
Here is how the View more button looks now
comments_v1

On clicking the button more comments with **View x more comments**
comment_v2

**Comment by ananyo2012** [comment]
Delete and Edit buttons are right aligned now. I have used #eee for background. It looks well. If you still prefer lines after each comment with a white background I will make a quick change.

**Comment by jywarren** [comment]
Ah, it looks great and tests passed. But I shouldn't have merged without the sqlite file -- can you make a followup PR and I'll merge it? Sorry, end of a long day here :-)

**Comment by ananyo2012** [comment]
Ah I didn't yet update the schema and sqlite files. Should I update it with a short PR?

**Comment by ananyo2012** [comment]
Yeah that's what I was saying too. Making a quick PR on it.

**Comment by jywarren** [comment]
That would be perfect. Its ok as we won't publish until Friday, but it's
good to get the timestamp in order in the schema.rb file.

**Pull request merged**
