### PR TITLE
Error posting comment on answer

### LINKED ISSUE #1864: Error posting comment on answer
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I received an email with an exciting answer posted. 
screen shot 2017-12-11 at 10 31 30 am

I clicked the link to comment on the answer, and was brought to the correct comment box. I typed a short reply, and clicked submit and got an error: 

screen shot 2017-12-11 at 10 29 20 am

Next, i went to the URL, deleted everything after the `?` and reloaded the page. Manually, i scrolled down to the same comment box, put the same one-liner, and clicked submit. The same error occurred. 

FYI I have never seen this error before and that's saying a lot considering what a heavy site user i am. 

> What did you expect to see that you didn't?

I expected to be able to be able to hit submit and have it submit properly. 

### Please show us where to look

https://publiclab.org/questions/warren/09-19-2017/how-do-i-stabilize-smaller-balloons-and-prevent-them-from-being-blown-down-in-the-wind

https://publiclab.org/questions/warren/09-19-2017/how-do-i-stabilize-smaller-balloons-and-prevent-them-from-being-blown-down-in-the-wind#answer-644-comment

### What's your PublicLab.org username?

> This can help us diagnose the issue: liz

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome on mac.

### PR DESCRIPTION
**Pull request by Gauravano**
fixes #1864 
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hm, it looks like you have to adjust the test to provide `id` instead of `aid` -- but I think I may have resolved this error in a routes.rb fix last night. @Gauravano  @ebarry - can you look on publiclab.org to see if this is still an issue? 

Example question: https://publiclab.org/questions/warren/12-08-2017/where-can-microscope-lenses-objectives-be-bought

If it's now working, we may be able to close this PR and issue. But thanks for looking into this!!!

**Comment by Gauravano** [comment]
Yes, @jywarren it's working now so I am closing this PR.Thanks.

**Comment by ebarry** [comment]
thank you everyone!

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by jywarren** [comment]
Awesome, thank you!

**Pull request closed without merging**
