### PR TITLE
Reduce Travis runtime

### LINKED ISSUE #6225: Reduce Travis runtime with caching
Let's see if we can reproduce what Alax did here! 

https://github.com/publiclab/mapknitter/pull/794

**Before caching:**
image

**After caching:**
image

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #6225  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
@jywarren @cesswairimu is there a way to run unit, integration, functional and system tests in parallel? I tried build staging but I'm not sure why that too ran the tests in series

**Comment by cesswairimu** [comment]
Hi @Manasa2850, looks like we forgot to close Travis related issues...we moved from Travis and we are now using github actions for CI..so I am not sure there is a way we can test this or if we will ever go back to using Travis...as per your question I don't know of any. Thanks

**Comment by Manasa2850** [comment]
Oh okay @cesswairimu. I've added caching which reduces the build time by 4 mins. Will this PR be of any use? If not, I'll close it for now.
Thank you!

**Comment by cesswairimu** [comment]
we can merge it when its ready incase we wonna use Travis in the future...

**Comment by Manasa2850** [comment]
The build time has reduced by 4 minutes.

Before:
before

After:
after_caching

@cesswairimu this PR can be merged now! If I figure out a way to run tests in parallel sometime later on I'll make another PR for that. Thanks!

**Comment by cesswairimu** [comment]
The test runner does not use travis.yml(I think) and it looks like it fluctuates e.g on this PR here it ran in 13mins https://github.com/publiclab/plots2/pull/8928 ...I think we might not be able to test this and we might resolve to closing...so sorry for the confusion

**Comment by Manasa2850** [comment]
Oh okay @cesswairimu. No problem, I'll be closing this PR now. Thank you!

**Pull request closed without merging**
