### PR TITLE
Work in Progress - Jasmine test

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake spec:javascript`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren I managed to get the test passed. Using phantom gem v2.1.1 also runs the specs. For in browser  testing we need to mount the spec directory in the routes file as per https://github.com/travisjeffery/jasmine-jquery-rails/issues/4#issuecomment-29684484.

But I can't get the fake Ajax request to update the like-counts. I tried multiple methods and even with the `and.callThrough` function of jasmine_ajax. Getting some help in this part would be great.

**Comment by ananyo2012** [comment]
Another thing is there are some path mismatch in `jasmine gem` and `jasmine-rails gem`. The path og fixture directory are different. Though this isn't a big issue as we did not include the `rake jasmine` task in the readme. But it would be good if we remove the `gem jasmine` from the gemfile. Just to make it clear we are running tests only by `jasmine-rails gem` and not `jasmine-gem` .

**Comment by jywarren** [comment]
Ok, Ajax faking can be tough to get configured right; I'll take a look
today as I finish going through the other pull requests. And I guess I made
a mistake including the jasmine gem? Can you make the appropriate change
and add a commit here?

**Comment by ananyo2012** [comment]
Ah sure I will just amend my previous commit and make the changes
ᐧ

**Comment by ananyo2012** [comment]
@jywarren Removed the jasmine gem from gemfile

**Comment by jywarren** [comment]
OK, i have a local copy of this now and am going to give it a try while on the plane (5 hour flight). Will report back!

**Comment by ananyo2012** [comment]
Oh good luck on it!

**Comment by jywarren** [comment]
I have rebased your code onto master, and after running `bundle install` and getting the right gems, and navigating to `localhost:3000/specs`, I see your `sends a like request when like button is clicked` test pass. 

I also tried running `rake specs:javascript` though and got an odd error about the appropriate library for my platform, which I'll look at when I can get a moment:

````
(trusty)warren@localhost:~/sites/plots2$ rake spec:javascript
rake aborted!
Phantomjs::UnknownPlatform: Could not find an appropriate PhantomJS library for your platform (armv7l-linux-eabihf :( Please install manually.
/home/warren/.rvm/gems/ruby-2.1.2/gems/phantomjs-1.9.8.0/lib/phantomjs.rb:33:in `platform'
/home/warren/.rvm/gems/ruby-2.1.2/gems/phantomjs-1.9.8.0/lib/phantomjs.rb:25:in `path'
/home/warren/.rvm/gems/ruby-2.1.2/gems/jasmine-rails-0.12.2/lib/jasmine_rails/runner.rb:21:in `block in run'
/home/warren/.rvm/gems/ruby-2.1.2/gems/jasmine-rails-0.12.2/lib/jasmine_rails/runner.rb:50:in `override_rails_config'
/home/warren/.rvm/gems/ruby-2.1.2/gems/jasmine-rails-0.12.2/lib/jasmine_rails/runner.rb:9:in `run'
/home/warren/.rvm/gems/ruby-2.1.2/gems/jasmine-rails-0.12.2/lib/tasks/jasmine-rails_tasks.rake:9:in `block (2 levels) in <top (required)>'
/home/warren/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/home/warren/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spec:javascript
(See full trace by running task with --trace)
````

In any case, I got the mocked AJAX response working, and left a comment; my additional commit is here: https://github.com/jywarren/plots2/commit/379f9622d597145323e324dabbae4926dd338f6e

The issue with the test failing is that on line 52 of `like.js` is this:

    changelikecount(1, node_id);

So it only increments by one. I changed this to increment by the returned value, although I'm not sure that's correct either, since shouldn't it simply **set** it to the returned value, not increment it to that? 

In any case I think you can figure this out now!

**Comment by ananyo2012** [comment]
Thanks Jeff for your help. I can take over from here.
ᐧ

**Comment by jywarren** [comment]
Hi Ananyo - were you able to figure this out or can I help our any more? Thanks!

**Comment by jywarren** [comment]
Oh, super. Should I try to merge this one or wait? Thanks!

**Comment by ananyo2012** [comment]
No please don't merge this one. I will close this one and make a new one
soon.

**Comment by jywarren** [comment]
Ok great.

**Comment by ananyo2012** [comment]
@jywarren Closing this. Followed in #618.

**Comment by ananyo2012** [comment]
@jywarren With respect to your previous comment we are just stubbing the ajax response. Other processes are working as it is. So it gets incremented by the returned response by the `changelikecount() ` function.

**Pull request closed without merging**
