### PR TITLE
Test fix

### PR DESCRIPTION
**Pull request by siaw23**
Test fix for https://github.com/publiclab/plots2/issues/4891

### CODE REVIEW

**Comment by siaw23** [comment]
Hi @jywarren can we test this on unstable? I have deliberately commented out tests if it works then at least we know where to look next to have this fixed for good.

**Comment by siaw23** [comment]
So the idea is to merge this to unstable, and check if we can add mentors without it asking us to login.

**Comment by jywarren** [comment]
Yes, you should be able to `git push -f git@github.com:publiclab/plots2.git unstable` !

**Comment by siaw23** [comment]
That's not working. Is that correct?

**Comment by jywarren** [comment]
i have to head home now, but others in the chatroom use this a lot and can
help! that works for me, but I wonder if you are set up with the push
privileges?

**Comment by siaw23** [comment]
I guess not. I can't push to it.

**Comment by jywarren** [comment]
can you try now, i added you!

**Comment by siaw23** [comment]
No luck.

**Pull request closed without merging**
