### PR TITLE
Changed path for mailman build and app in docker-compose-*

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Trying this now!

**Comment by namangupta01** [comment]
Lets see!

**Comment by jywarren** [comment]
great, it passed. Trying to send an email to `notifications-staging@publiclab.org` now

**Comment by namangupta01** [comment]
Very Excited!

**Comment by namangupta01** [comment]
Check here: https://stable.publiclab.org/mailman.log
Some errors occured.

# Logfile created on 2018-06-21 20:07:33 +0000 by logger.rb/56815
I, [2018-06-21T20:07:33.880333 #1]  INFO -- : Mailman v0.7.0 started
I, [2018-06-21T20:07:33.880415 #1]  INFO -- : Rails root found in ., requiring environment...
D, [2018-06-21T20:07:38.661218 #1] DEBUG -- : Processing message from STDIN.
I, [2018-06-21T20:07:38.664819 #1]  INFO -- : Got new message from 'unknown' with subject ''.
E, [2018-06-21T20:07:39.908174 #1] ERROR -- : Exception occurred while receiving message:
Date: Thu, 21 Jun 2018 20:07:39 +0000
Message-ID: <5b2c058bd538e_12abb0108cf7875380@4caa2e38c189.mail>
Mime-Version: 1.0
Content-Type: text/plain
Content-Transfer-Encoding: 7bit


E, [2018-06-21T20:07:39.909742 #1] ERROR -- : undefined method `[]' for nil:NilClass
/app/app/models/comment.rb:208:in `receive_mail'
script/mailman_server:22:in `block (2 levels) in <main>'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `instance_exec'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `route'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:23:in `block in process'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:33:in `block in run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:38:in `run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:22:in `process'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:71:in `run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
script/mailman_server:17:in `<main>'

**Comment by namangupta01** [comment]
Checking this out.

**Comment by jywarren** [comment]
Hmm, i sent an email in the format `Re: [Public Lab] title here (#nid)` but it's not appearing. I'll check logs!

**Comment by jywarren** [comment]
Aha - also, we should move that log somewhere private (just into `/log/...`) before publishing to production!

**Comment by jywarren** [comment]
But cool to see something in there!!!

**Comment by namangupta01** [comment]
Yes, that was for testing.

**Comment by namangupta01** [comment]
Are we using pop3 protocol?
Because it look like this when i use pop3 protocol:
I, [2018-05-18T01:21:05.257948 #24093]  INFO -- : Mailman v0.7.3 started
I, [2018-05-18T01:21:05.258127 #24093]  INFO -- : Rails root found in .,
requiring environment...
I, [2018-05-18T01:21:13.360484 #24093]  INFO -- : POP3 receiver enabled
(railsprojects2018@gmail.com@pop.gmail.com).
I, [2018-05-18T01:21:13.379180 #24093]  INFO -- : Polling enabled. Checking
every 60 seconds.
I, [2018-05-18T01:22:21.820813 #24093]  INFO -- : Got new message from '
naman18996@gmail.com' with subject '(#47)'.
I, [2018-05-18T01:24:32.180620 #24093]  INFO -- : Got new message from '
naman18996@gmail.com' with subject 'tfgghhj vjghjb miubmn bh jb lknjk
(#47)'.

**Comment by jywarren** [comment]
Hmm, maybe? I don't know, it's whatever Google Apps provides. Should we be using pop3?

**Comment by namangupta01** [comment]
yes because the config is defined for pop3.
https://github.com/publiclab/plots2/blob/96bb99c9fcc183de66600765eb94fae667bb3bf6/script/mailman_server#L9

**Comment by jywarren** [comment]
Is it a matter of the server URL? We're using `SERVER_ADDRESS=mail.googlemail.com` so I don't think it matters?

Oh, if it's the wrong format, we're seeing `I, [2018-06-21T20:07:38.664819 #1] INFO -- : Got new message from 'unknown' with subject ''.`

i see...

**Comment by jywarren** [comment]
Can you look up config with Google Apps and see if we need to use a specific server to get pop3?

**Comment by jywarren** [comment]
like `pop3.googlemail.com`?

**Comment by jywarren** [comment]
I changed to pop3.googlemail and am rebuilding stable to see...

**Comment by jywarren** [comment]
Can you open a PR to move the log, so we can merge when we need to?

**Comment by namangupta01** [comment]
In http://railscasts.com/episodes/313-receiving-email-with-mailman uses `pop.gmail.com` which works for me.

**Comment by namangupta01** [comment]
yes, sure!

**Comment by jywarren** [comment]
Trying pop.googlemail.com...

**Comment by jywarren** [comment]
hmm, it seems like messages are arriving. But they're not in the encoding expected, maybe? And why are the addresses scrambled too?

**Comment by jywarren** [comment]
the results are pretty much the same btw

**Comment by jywarren** [comment]
i'll try `pop.gmail.com`

**Comment by namangupta01** [comment]
I think using `pop.gmail.com` instead of `pop.googlemail.com` won't make much difference.

**Comment by namangupta01** [comment]
Actually it is reading input from STDIN where it should be doing polling.
`I, [2018-05-17T23:33:10.371304 #22846]  INFO -- : Rails root found in ., requiring environment...
I, [2018-05-17T23:33:14.252953 #22846]  INFO -- : POP3 receiver enabled (railsprojects2018@gmail.com@pop.gmail.com).
I, [2018-05-17T23:33:14.263425 #22846]  INFO -- : Polling enabled. Checking every 60 seconds.
I, [2018-05-17T23:34:21.033026 #22846]  INFO -- : Got new message from '01namangupta@gmail.com' with subject 'new mail'.`

**Comment by jywarren** [comment]
yeah...

**Comment by jywarren** [comment]
oh huh... do you know how to fix that?

**Comment by namangupta01** [comment]
Reading about this in:
https://github.com/mailman/mailman/blob/ea6ed20de9b6cbfdfc4f7556eefdd3822bccd316/lib/mailman/application.rb#L74

**Comment by namangupta01** [comment]
Should we try this? 
https://github.com/mailman/mailman/blob/master/USER_GUIDE.md#standard-input

**Comment by namangupta01** [comment]
Yes i think this is the problem.
https://github.com/mailman/mailman/blob/master/USER_GUIDE.md#standard-input

**Comment by jywarren** [comment]
are we accidentally piping something to this command instead of just
running it? Maybe look up how to use docker-compose with the mailman gem?

**Comment by namangupta01** [comment]
cron jobs when running generate a mail inside the machine. I think that is
piping into the mailman app.
Making a pr to ignore stdin.

**Comment by namangupta01** [comment]
Hoping this could solve our problem. #2890

**Comment by jywarren** [comment]
Hey!

```
I, [2018-06-21T21:44:44.393270 #1]  INFO -- : Mailman v0.7.0 started
I, [2018-06-21T21:44:44.393422 #1]  INFO -- : Rails root found in ., requiring environment...
I, [2018-06-21T21:44:48.515498 #1]  INFO -- : POP3 receiver enabled (notifications-staging@publiclab.org@pop.gmail.com).
I, [2018-06-21T21:44:48.561754 #1]  INFO -- : Polling enabled. Checking every 60 seconds.
``` 

Looking good so far!

**Comment by namangupta01** [comment]
Yayy!!!!

**Comment by jywarren** [comment]
but it's been 60 seconds... what now?

**Comment by jywarren** [comment]
and is that email wrong?

**Comment by namangupta01** [comment]
No all the mail will come irrespective of the email. Can you check by logging into google mail account?

**Comment by jywarren** [comment]
image

**Comment by namangupta01** [comment]
I got it. Once i also got this problem. You have to open it for pop3
services --somewhere in the settings.

**Comment by jywarren** [comment]
ok, looking...

**Comment by namangupta01** [comment]
Checked the third mail. Google blocked sign-in attempt.

**Comment by jywarren** [comment]
ok i enabled "less secure apps" !

**Comment by jywarren** [comment]
let's wait 60 seconds...

**Comment by jywarren** [comment]
good eye!

**Comment by jywarren** [comment]
should we rebuild stable?

**Comment by namangupta01** [comment]
I don't think it will do much help. But we can try.

**Comment by namangupta01** [comment]
We can try rebuild.

**Comment by namangupta01** [comment]
Can i start rebuild?

**Comment by jywarren** [comment]
i just did via travis.

**Comment by jywarren** [comment]
i'd share login but we're soon going to start deploying production from there too, so not sure about permissions!

**Comment by namangupta01** [comment]
Yasssss! Finally It worked!

**Comment by jywarren** [comment]
ok it rebuilt

**Comment by jywarren** [comment]
ah! so much more info this time!!!

**Comment by jywarren** [comment]
yesssss!

**Comment by namangupta01** [comment]
Atleast mails are now receiving!
We have to look now for sql connectivity.

**Comment by jywarren** [comment]
```

--0000000000008442d1056f2de199
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<div dir="ltr">And again!</div>

--0000000000008442d1056f2de199--

E, [2018-06-21T22:14:34.497609 #1] ERROR -- : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:88:in `connection'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/model_schema.rb:471:in `load_schema!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/attributes.rb:233:in `load_schema!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/model_schema.rb:464:in `block in load_schema'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/model_schema.rb:461:in `load_schema'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/model_schema.rb:343:in `columns_hash'
/usr/local/bundle/gems/composite_primary_keys-10.0.3/lib/composite_primary_keys/core.rb:30:in `find'
/app/app/models/comment.rb:210:in `receive_mail'
script/mailman_server:24:in `block (2 levels) in <main>'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `instance_exec'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/router.rb:66:in `route'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:23:in `block in process'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:33:in `block in run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/middleware.rb:38:in `run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/message_processor.rb:22:in `process'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:43:in `block in get_messages'
/usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each'
/usr/local/lib/ruby/2.4.0/net/pop.rb:666:in `each_mail'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/receiver/pop3.rb:42:in `get_messages'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:133:in `block in polling_loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:83:in `run'
/usr/local/bundle/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
script/mailman_server:19:in `<main>'
I, [2018-06-21T22:14:34.561191 #1]  INFO -- : Got new message from '01namangupta@gmail.com' with subject 'HI'.
```

So, does the mailman process need access to the whole app somehow? How does it work?

**Comment by namangupta01** [comment]
I am not sure. Researching over it.

**Comment by jywarren** [comment]
Maybe we need `Mailman.config.rails_root` set -- 

it says:

```
I, [2018-06-21T22:14:27.253466 #1]  INFO -- : Rails root found in ., requiring environment...
```

but is it really there? Isn't it one dir up?

**Comment by namangupta01** [comment]
It could be related to this: https://github.com/mailman/mailman/issues/141
Should we also try by including this

puts Rails.env

in mailman_server file for confirming this is loading correct environment.

**Comment by namangupta01** [comment]
Is staging is using production database?

**Comment by namangupta01** [comment]
I think it doesn't? Am i right?

**Comment by namangupta01** [comment]
Moved to #2894

**Pull request merged**
