### PR TITLE
Change do-not-reply@ to notifications@

### LINKED ISSUE #2935: Change do-not-reply@ to notifications@
As we now supports `reply-by-email` and for it we have changed our email name to `notifications@`.

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
Fixes #2935 
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by namangupta01** [comment]
@jywarren Should we merge this?

**Comment by jywarren** [comment]
Were you able to test it locally to see that emails are generated? Or push it to unstable and we can check the logs to see that they're sent (they'll pile up locally and won't leave the server)

**Comment by namangupta01** [comment]
yes we can test it on unstable.

**Comment by namangupta01** [comment]
pushed to unstable

**Comment by namangupta01** [comment]
I think only you can check the logs. Please check and let me know.

**Comment by jywarren** [comment]
OK, it worked!

**Comment by jywarren** [comment]
Great job!

**Pull request merged**
