### PR TITLE
Moderated comment view for different users

### LINKED ISSUE #3331: Moderating first-timer comments
We currently moderate first-timer question, note for preventing spam. Now, comments are also becoming a issue, so it's decided in #2304 that we would be implementing the similar moderation system as that of nodes for comments too.

- [x] Check if the user is a first-time commenter or not, if the user has published a note before then he/she 
shouldn't be considered as the first-time commenter. Make a function in `comment.rb` for this. --- #3509

- [x] Make a function in `comment.rb` which will change the status of comment to 4 (status = 1 represent normal comment, status = 4 represent under moderation).

- [x] In `comment_controller.rb` check for the first-time commenter if it is, then changes status to 4 using the function build in 1

- [x] Add the view for moderated comment just we have for node

- [x] Make a comment_moderation mailer and add the tests for it

- [x] Make a comment approval/spammed mail and add the tests for it.
 
- [x] Call both mailers at appropriate places from `comment.rb` and `comment_controller.rb`

- [x] Add functional tests 

- [x] Write documentation about using extra status field

- [x] Moderated comments viewability to different users - (#4470)
 
- [ ] Append under-moderation comment in comments section using AJAX visible to author/moderator (--- followup)

@jywarren please review the steps. Thanks!

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #3331 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
Hi @jywarren, the last bit of Comment moderation system is done, with this PR:
* Moderated comments would be visible to moderators with buttons above comment in note or question
mod_view2

* Moderated comments wouldn't be visible to normal users or without session users. And, visible to comment author with the notice
mod_view1

Let me know what you think about the design. Thanks!

**Comment by jywarren** [comment]
Love it!!! Thanks Gaurav!!

**Comment by gauravano** [comment]
Final designs, just checking on `unstable` then it's ready to merge :smiley: 
new_design_2
design_mod_1

**Comment by gauravano** [comment]
@jywarren checked on `unstable`, working great. Feel free to merge it, if you find the changes right. Thanks!

**Comment by SidharthBansal** [comment]
Checking the changes on the unstable branch.

**Comment by jywarren** [comment]
This looks super. Go ahead and merge! Great work!!!!!

**Comment by gauravano** [comment]
Merged :tada: :balloon: :smile:

**Pull request merged**
