### PR TITLE
Replace .length with .size

### PR DESCRIPTION
**Pull request by pg00019**
Fixes #0000 (<=== Add issue number here)
https://github.com/publiclab/plots2/issues/8572

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
thanks so much for opening this :tada: could you please add the issue link to the issue this pull request fixes on your pull request on this line "Fixes issue_link" this will help other contributors while reviewing your changes. It also helps in automatically closing the issue when the pull request is merged. Thanks

**Comment by cesswairimu** [comment]
Hey @pg00019  kindly add the link to the issue you are solving so that we can be able to review. Thanks

**Comment by pg00019** [comment]
Hey !
Thanks for the opportunity
My twiiter handler is @Priya_Gupta019

Thank you.
Priya gupta .

**Comment by pg00019** [comment]
> Hey @pg00019 kindly add the link to the issue you are solving so that we can be able to review. Thanks

hey @cesswairimu I have added the link ! Thank You

**Comment by RuthNjeri** [comment]
Hi @pg00019 👋🏾  the changes look good to me 🎉 ...
I've just noticed the link you've added for the issue is not correct, when I click it, it opens this PR in another tab... 
The link you need to add is from the [issues](https://github.com/publiclab/plots2/issues) page, specifically the one you were assigned/chose to fix..let me know if this makes sense...

**Comment by pg00019** [comment]
> Hi @pg00019 👋🏾 the changes look good to me  ...
> I've just noticed the link you've added for the issue is not correct, when I click it, it opens this PR in another tab...
> The link you need to add is from the [issues](https://github.com/publiclab/plots2/issues) page, specifically the one you were assigned/chose to fix..let me know if this makes sense...


Hey @RuthNjeri I have updated the link again. Please check once again and revert back .
Thnak you.

**Review by cesswairimu — APPROVED** [review]

**Comment by cesswairimu** [comment]
Thanks you both :tada:

**Pull request merged**
