### PR TITLE
Fixes #7148 by showing top map for power tag place:xx

### LINKED ISSUE #7148: Top map only shows for tag "place" and not power tag "place:xx"
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_related.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Right now if you input the tag `place` the map shows properly as a map across the top of the page instead of in the sidebar.

FireShot Capture 187 - 🎈 Public Lab_ This is a post testing location - localhost

But if you input the power tag `place:xx` then it isn't showing properly.

FireShot Capture 186 - 🎈 Public Lab_ This is a post testing location - localhost

So let's cover our bases by checking both of those options. On this line here:
https://github.com/publiclab/plots2/blob/2365caabd15e4b7fa178e94e25b0bf4dd9b67f84/app/views/sidebar/_related.html.erb#L44

Change it to:
`<% if @node && (@node.has_tag("place") || @node.has_power_tag("place")) && @node.lat && @node.lon %>`

Now it works properly!

FireShot Capture 188 - 🎈 Public Lab_ This is a post testing location - localhost

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by sunguru98**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sunguru98** [comment]
@publiclab/reviewers Again, same Codecov problem haha, but other than that, completed it.

**Comment by nstjean** [comment]
This is great thank you!! Can you just update the number at the top of this page with the issue it is fixing: 7148? It helps us keep track of everything. :)

**Comment by sunguru98** [comment]
The issue number is present on the commit message if I am not wrong

**Comment by nstjean** [comment]
Ahh, yes, I see! The reason we ask for it in the pull request text is that it creates a link on the form to the issue: #7148 It's GitHub magic! :smile:

**Comment by sunguru98** [comment]
Got it .. haha .. Waiting for this to get mergedddddd lol

**Comment by nstjean** [comment]
I'm sure it will be merged soon! In the meantime I suggest reading our documentation and trying to get our repository downloaded and running on your system: https://github.com/publiclab/plots2#installation
If you have any problems you can post here to get support: https://github.com/publiclab/plots2/issues/3840 or post in our gitter chatroom
Here is our community toolbox with a bunch of info! https://code.publiclab.org/

**Comment by jywarren** [comment]
Hi all, thanks so much! Can you read through this issue and note if this PR is compatible with what we've laid out there? Thank you!

https://github.com/publiclab/plots2/issues/6953

**Comment by nstjean** [comment]
Yes it is! It doesn't completely solve the issue, but it's a step forward.

**Comment by jywarren** [comment]
Awesome. Thanks!!!!

**Comment by sunguru98** [comment]
Wowww .. again .. I did it .. I contributed something

**Pull request merged**
