### PR TITLE
Overflow of Title in Dashboard #1691

### LINKED ISSUE #1691: Overflow of Title in Dashboard
### What happened just before the problem occurred
As there is no limit on Title length and on the format of title so , a title for example : "This_is_an_example_title_which_will_overflow_in_the_dashboard_" will overflow as seen here :

screen shot 2017-10-14 at 7 08 17 pm

### Relevant URLs

https://github.com/publiclab/plots2/blob/master/app/controllers/home_controller.rb

### Browser, version, and operating system
Browser : Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
operating system : MacOS

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
fixes #1691

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
I'm not sure why this failed! I don't think it's at all related to your changes, which I like. Thanks! Restarting the tests now, let's see.

**Comment by jywarren** [comment]
Super, looks like it worked!

**Comment by jywarren** [comment]
Awesome, thank you so much!

**Comment by sagarpreet-chadha** [comment]
Thank you sir !!

**Pull request merged**
