### PR TITLE
Drupal node to node

### PR DESCRIPTION
**Pull request by jywarren**
Supercedes #1319 and #1320, #1105, #1100, relates to #956 and adds to lots of @aayushgupta1's work, thank you so much!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
OK, fingers crossed, I found another circular reference.

**Comment by aayushgupta1** [comment]
@jywarren kindly check your forked repository in the branch. I made some changes that I forgot to make I think. Kindly look into it. Thanks

**Comment by jywarren** [comment]
@aayushgupta1 omg it ran! I'm going to look through everything to be sure.

**Comment by jywarren** [comment]
It's great. I found we can dump a couple locale files and that should pass too. Then I'll merge -- fantastic work, @aayushgupta1 !!!

**Comment by aayushgupta1** [comment]
@jywarren That's great. Thanks for the help and the support. It's a great feeling of getting a merged PR of such a big topic. Learnt a lot from my mistakes and hope to not repeat again. Will keep working. Thanks

**Pull request merged**
