### PR TITLE
Fixes for #676 and #677

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren This is ready for merge now.

**Comment by ananyo2012** [comment]
For #676 I extracted the anchor text and if any anchor text matches the format`answer-#{answer id}-comment` the entire comments chain open up and the comment can thus can be found.

**Comment by ananyo2012** [comment]
For #677 I separately found the answer comments and added it to the activity feed. For answer comments the text shows `[user] commented on a answer about [question title]` and the `# comments` button link to the answer comments instead of the note comments.

**Comment by jywarren** [comment]
Tested, rebased and merged in c171551. Thanks!

**Pull request closed without merging**
