### PR TITLE
Added "comment" and "barnstar" headings to profile nav

### LINKED ISSUE #2165: Add "comment" and "barnstar" headings to profile nav
### Please describe the problem (or idea)

profile-tabs-1
Some of the nav-tabs on the profile page contains only icons(e.g comments, barnstars) which makes it hard to guess thieir functionality.

### Please show us where to look

https://publiclab.org/profile/vidit

### What's your PublicLab.org username?

vidit

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #2165

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Awesome!

**Comment by SidharthBansal** [comment]
As per @jywarren suggestions I have liked it and approved it.
Thanks

**Comment by ViditChitkara** [comment]
Cool! :+1:

**Comment by jywarren** [comment]
Super. Thank you!!!

**Pull request merged**
