### PR TITLE
unique nids in revisions.yml

### PR DESCRIPTION
**Pull request by jywarren**
fixes https://github.com/publiclab/plots2/issues/8864 i hope!

### CODE REVIEW

**Comment by jywarren** [comment]
OK, so now we probably have to create nodes for nid 39-51, based on copies of the most minimal version of this possible:

https://github.com/publiclab/plots2/blob/5b387b674530afd13110bfc4c6e10eab7ed8a705/test/fixtures/nodes.yml#L1-L11

**Comment by noi5e** [comment]
@jywarren Would it still help to have someone work on this? I'm not sure how urgent this is now that we've switched CI over from Travis... Catching up on this thread just now.

I can probably give this a shot if it makes sense for me to do it (since I'm working with fixtures and adding a bunch of new ones). I'm thinking I would do something like below:
```
one: # vary this title
   nid: 1 # vary these from 39 - 51
   uid: 2 
   title: # probably good to vary this
   path: # will match this with title
   cached_likes: 0 
   slug: # will match this with path and title, just to be safe
```

Let me know if there's anything else good to know!

**Comment by noi5e** [comment]
Just played around with this, pushed some commits. There's still some **new** failing tests to figure out, so more work should be done on this.

I think it makes sense to add new nodes to match the new revisions, if we're going to go this route... I ran the tests on both scenarios, and it seems easier to untangle if there are new nodes matching the revisions.

Honestly, this might be a red herring-- I still basically get the same 7 failures, 12 errors running the tests. So I'm not sure if the fix will solve any of those outstanding testing issues.

**Comment by noi5e** [comment]
Currently test-runner is catching four errors in `notes_controller_test.rb`. They're all kind of similar, so here's just one of them:

https://github.com/publiclab/plots2/blob/9c409ec6bee43b95dfe52191cb5069f4199a4524/test/functional/notes_controller_test.rb#L657-L664

I think what's going on is that get :index is only pulling the first 20 notes due to pagination, maybe? That's why `nodes(:one)` doesn't appear in the array as expected. Possible fix would be to:
- Get `nodes(:one)` to appear in the first 20 results, perhaps by playing around with timestamps?
- Rewrite the test entirely?

Any ideas or suggestions?

**Comment by jywarren** [comment]
I would love help, to be honest, i didn't manage to get to this today! Pls note that we seem to be pretty far from synced with the `main` branch though.

The failure mode here, which may help with your Qs, is that different databases and environments can /order/ fetched records differently, especially if they have the same `created_at` value, and in this case, if they have the same `nid` which otherwise would make their ordering predictable. So, absent something to order them, they get jumbled in order, which could account for your observed issue on the index page, (as it might move in and out of the first 20?).

That said, this may not solve other issues, not sure -- but it hopefully will reduce the incidence of some tests passing in one environment but failing in another due to subtle differences in how databases sort un-sortable data (i.e. how they handle a bunch of records with identical fields). 

Hope this makes sense -- thank you!!!!

**Comment by jywarren** [comment]
OK, this will take a lot of work. But we should also try to incorporate a `home-intro` explanatory feature in nodes.yml and revisions.yml to ensure something more friendly shows up to developers when first booting the front page:

https://github.com/publiclab/plots2/blob/2c6807032309c93d6ff7dfa4e8909db47f6a73ff/app/views/home/home.html.erb#L2

**Comment by jywarren** [comment]
This needs a rebase! But also, let's add comments at the bottom of nodes.yml, revisions.yml, and other relevant files that clearly explain how we need unique nids.

**Comment by noi5e** [comment]
Ugh, the commit history for this PR was awful before! Sorry, that was my bad, it was an attempt gone wrong at `git rebase`. 

But I just did another `git rebase` with the current `main` branch and it looks a lot better now.

Let's see how the tests do. There were four merge conflicts that were a little funny that I undid manually. But I'm sure the tests will be more revealing if I did the merge conflicts wrong.

If I recall correctly, this can't be merged as is. There's a system test that was failing that I mentioned [above here](https://github.com/publiclab/plots2/pull/8865#issuecomment-754299916), that I believed at the time had to do with results pagination on `:index`. But we'll see.

**Comment by jywarren** [comment]
Also noting the functional test failures were:

```

========== FAIL NotesControllerTest#test_should_list_only_research_notes_with_status_1_in_index (81.68s)
        Expected false to be truthy.
        test/functional/notes_controller_test.rb:665:in `block in <class:NotesControllerTest>'

 FAIL NotesControllerTest#test_should_list_only_research_notes_with_status_1_in_liked (81.97s)
        Expected false to be truthy.
        test/functional/notes_controller_test.rb:704:in `block in <class:NotesControllerTest>'

 FAIL NotesControllerTest#test_should_list_only_research_notes_with_status_1_in_popular (82.26s)
        Expected false to be truthy.
        test/functional/notes_controller_test.rb:685:in `block in <class:NotesControllerTest>'

 FAIL NotesControllerTest#test_should_list_research_notes_with_status_1_&_4_in_index_if_admin_is_logged_in (82.65s)
        Expected false to be truthy.
        test/functional/notes_controller_test.rb:675:in `block in <class:NotesControllerTest>'
```

**Comment by jywarren** [comment]
OK let's just rewrite those 4 to actually assert exactly what they say - that in the first one, all results are status == 1, for example. That should solve it and the current assertions aren't very good anyways!

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/a291fe0fff97d030e7b6f3aab1765bad1bc251a2/test/functional/notes_controller_test.rb#L665-L704

**Comment by jywarren** [comment]
OK, narrowed the test assertions a bit. Let's see. There may be other issues.

**Comment by jywarren** [comment]
We may need to push the "first-time-poster" node to the end so it shows up. But, maybe we are OK with it not appearing on the `/notes` index route anymore anyways.

**Comment by jywarren** [comment]
OK, so the functional test could be fixed by #9321 -- let's rebase over. 

```
======= FAIL NotesControllerTest#test_should_list_research_notes_with_status_1_&_4_in_index_if_admin_is_logged_in (30.38s)
        Expected false to be truthy.
        test/functional/notes_controller_test.rb:669:in `block in <class:NotesControllerTest>
```

System tests...

```
ERROR DashboardTest#test_User_can_flag_a_node_from_dashboard (974.95s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css "#flag_node1"
            test/system/dashboard_test.rb:34:in `block in <class:DashboardTest>'
```

I bet it's a reordering issue related to the nids. Let's check...

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/04f5093248aa8ffd2e9b5c79d0391f8c93ca44d2/test/system/dashboard_test.rb#L26-L36

**Comment by jywarren** [comment]
I bet that's pagination. Let's adjust that so it uses the last node.

**Comment by jywarren** [comment]
Rebased over the fix...

**Comment by jywarren** [comment]
ALMOSTTTTTT

**Comment by jywarren** [comment]
Even after these NID fixes, this still went wrong:

```
Progress: | FAIL TagSelectionTest#test_graph (0.33s)
        Expected: 18
          Actual: 23
        test/unit/tag_selection_test.rb:14:in `block in <class:TagSelectionTest>'

====================================================================|
```

I wonder if that's a different issue, non-NID? We can follow up in a new issue.

**Comment by jywarren** [comment]
Yes, the tag test seems totally unrelated:

https://github.com/publiclab/plots2/blob/d70efef8b13bdba3e39ab710f4a48b36c1778f12/test/unit/tag_selection_test.rb#L5-L16

**Pull request merged**
