### PR TITLE
shifted the locknote to dropdown

### LINKED ISSUE #9988: Move "Lock note" link into sidebar "advanced tagging" dropdown menu
The new link prompting admins and mods to lock a note is currently in the main column of notes, as shown here:

image

Let's move it into the sidebar "advanced tagging" dropdown menu shown here:

image

This could be a nice FTO! Thanks!

### PR DESCRIPTION
**Pull request by Ash-KODES**
Fixes #9988  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Ash-KODES** [comment]
Screenshot from 2021-09-01 23-44-07

**Comment by Ash-KODES** [comment]
@noi5e please review my code :)))

**Comment by jywarren** [comment]
Hi! I want to say i think this is the same as #10023, so I'll close this and we can work over there! But let me know if I misunderstood!

**Comment by Ash-KODES** [comment]
ok

**Pull request closed without merging**
