### PR TITLE
removed ambiguous behaviour of 'Add one now' on local server

### LINKED ISSUE #4465: ambiguous behaviour of 'Add one now' on local server
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

add-one

> What did you expect to see that you didn't?

### What's your PublicLab.org username?

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by geekychaser**
Fixes #4465

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Hi @gauravano @jywarren we are getting ``The command "docker-compose build" failed and exited with 1 during .`` again. This error is present in many prs.
Happy new year everyone.

**Comment by geekychaser** [comment]
@SidharthBansal should i close this one and post PR again?

**Comment by SidharthBansal** [comment]
Please wait Gaurav or Jeff can help us here.

**Comment by SidharthBansal** [comment]
Closing and opening the pr to restart the build. It worked in other pr after doing it 3 times.
Hopefully it should work here also.

**Comment by SidharthBansal** [comment]
@geekychaser please remove the conflicts.

**Comment by geekychaser** [comment]
@SidharthBansal i guess this is completely fine now

**Comment by SidharthBansal** [comment]
Please provide the gifs to demonstrate that is working fine now.

**Comment by SidharthBansal** [comment]
Please remove conflicts

**Comment by geekychaser** [comment]
share

@SidharthBansal it looks fine

**Comment by SidharthBansal** [comment]
Awesome!!!

**Pull request merged**
