### PR TITLE
Login modal edit wiki

### LINKED ISSUE #4242: Link login modal to edit wiki button
### Problem
On wiki posts such as this https://publiclab.org/wiki/environmental-estrogen-testing there is an option to edit the page:

image

### 📋Solution
Currently when clicked, the user is directed to a login page. We want the button to open a login modal if the user is not logged in.
/app/views/wiki/_header.html.erb

### PR DESCRIPTION
**Pull request by okonek**
Fixes #4242  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
editwiki

### CODE REVIEW

**Comment by okonek** [comment]
@SidharthBansal I think it works well.

**Comment by SidharthBansal** [comment]
Approved on the GCI dashboard

**Comment by okonek** [comment]
Thanks!

**Comment by SidharthBansal** [comment]
>>@okonek does it open the edit prompt once the user is logged in?

@okonek can you please provide an answer to the query of @JonathanXu1

**Comment by SidharthBansal** [comment]
@okonek can you please make your branch consistent with the current master and try out it again.
There might be some deletions and some additions. @kevinzluo  and @JonathanXu1  proposed a solution in that pr so that we need to work less in other prs.

**Comment by SidharthBansal** [comment]
Hi, now we need to use requireLogin instead of the previous changes suggested by you @okonek 
@okonek please do the required changes.
Thanks

**Comment by SidharthBansal** [comment]
@okonek are you stuck?
 Need any help?

**Comment by SidharthBansal** [comment]
Closing this PR as requireLogin is created. These changes are no longer needed.
Thanks for your hardwork

**Pull request closed without merging**
