### PR TITLE
Upgraded install_cloudnine.sh to Gemfile's current ruby version (fixes #2901)

### LINKED ISSUE #2901: install_cloudnine.sh not working
This happened because the install_cloudnine.sh was not updated along with the recent gemfile update to rails 5.1. More importantly, it means that I can't run `rails s -b $IP -p $PORT` on cloud9 while trying to fix another issue.

### PR DESCRIPTION
**Pull request by imacubsfan23**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by imacubsfan23** [comment]
@publiclab/reviewers In the future, how do I add labels to my issues/pr ?

**Comment by jywarren** [comment]
This is failing for reasons unrelated to your code; restarting! Thanks!!!

**Comment by jywarren** [comment]
Oof, i'm sorry, i merged another suggestion at https://github.com/publiclab/plots2/pull/2879/files and it caused a conflict! Would you mind rebasing and making adjustments and I can merge this in? Thank you!!!

**Comment by imacubsfan23** [comment]
I had a tough time rebasing, because I lost the branch I used for #2901. I made a new pr on another branch. should fix the issue.

**Comment by jywarren** [comment]
Ah, is it this one? https://github.com/publiclab/plots2/pull/2970

**Comment by imacubsfan23** [comment]
Yeah it's that one

**Comment by jywarren** [comment]
Ok thanks!!!

**Pull request closed without merging**
