### PR TITLE
Simple UI improvement for blockquote responses. 

### LINKED ISSUE #3425: Simple UI improvement for blockquote responses in reply by email comment
For conversation threads, when we click on the toggle button, the reply comments show up in a larger font size than the original comments.

So we can have some basic improvement in this such as: 
 Border padded blockquotes with a light background colour and a smaller font size to differentiate with the original comments.

whatsapp image 2018-09-24 at 11 45 23 pm

### PR DESCRIPTION
**Pull request by shivani-kapania**
Here, I modified the CSS for blockquote responses to easily differentiate it from the original comments. 

The files modified are: 
* app/assets/stylesheets/comments.css 
* app/views/notes/_comment.html.erb

Fixes #3425 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
Please share the screenshot.
Thanks!

**Comment by shivani-kapania** [comment]
Here. 

Earlier, the responses showed up this way: 

screen shot 2018-09-25 at 7 14 51 pm

Now, after adding border padding and background colour, it looks like this: 

screen shot 2018-09-25 at 7 13 05 pm

Thanks! 👍

**Comment by namangupta01** [comment]
Good Job!

**Comment by jywarren** [comment]
Oh, this is so lovely! Thank you!

**Pull request merged**
