### PR TITLE
Fix csv download bug for users and refactor and functional tests

### LINKED ISSUE #5255: https://publiclab.org/stats/users.csv not loading
Hi @cesswairimu  -- sorry to bother, but I noticed this wasn't loading, do you think you could take a peek at it? Thanks!!!

https://publiclab.org/stats/users.csv

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #5255 and #5264 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
users_csv

**Comment by jywarren** [comment]
Hi @cesswairimu -- what do you think is up with CodeClimate saying there are similar blocks of code? But they're for different models, right? Can we ignore?

https://codeclimate.com/github/publiclab/plots2/pull/5257

Thank you!!!

**Comment by cesswairimu** [comment]
Hey @jywarren I am looking into refactoring this also working on tests of the same as you suggested. Thanks

**Comment by cesswairimu** [comment]
@jywarren got carried away with the  refactoring......refactored the controller too :smile: Its hard to add tests and run them since I am still experiencing #5207  this with my test suite. Created a follow-up issue for this here #5264 as soon as I fix this error locally will implement the tests. Thanks

**Comment by cesswairimu** [comment]
@jywarren implemented tests on this...kindly take a look

**Comment by jywarren** [comment]
This looks awesome @cesswairimu thank you! Sorry when I am a bit slow -- thanks for requesting a review from someone else -- a good idea! I just read through and this looks super!

**Pull request merged**
