### PR TITLE
Rearranging tabs on profile page

### LINKED ISSUE #2920: Section for Drafts OR Inclusion in current tabs
Hi @publiclab/community-reps,
 
Based on the question raised by a Public Lab user here https://publiclab.org/questions/Delaney/06-25-2018/how-to-retrieve-a-draft-of-a-research-note-on-pl-org

I guess we need to make drafts more accessible to users, currently, drafts can only be accessed by the user only through their dashboard.

We can opt one of the two options:-

1. Adding a new tab for Draft notes

option_1

2. Including Draft notes in the present research, co-authored sections

Please provide your thoughts on this. Thanks!

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2920 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
Other's profile view:
nologin_and_other_user

Own profile view:
draft_section

Is any change required @jywarren ? thanks!

**Comment by jywarren** [comment]
Do you think questions should go in there as well? And shall we think about
the total count for each being displayed?

But this looks fantastic. We could do the additional steps in a separate PR
if you want. Thanks!!!!

**Comment by Gauravano** [comment]
I don't think we should include questions tab inside Research as for us its node but for users, both questions and research note represent totally different entity. What do you think? 

Regarding count, yes! we can display count for each tab. I will display the count in this one only as it's not that big issue. Thanks!

**Comment by jywarren** [comment]
Ok sounds good!

**Comment by Gauravano** [comment]
Here's the view after displaying count:

draft_prof_view2

Any change @jywarren ?

**Comment by jywarren** [comment]
Perfect!!!

**Comment by Gauravano** [comment]
@jywarren don't you think barnstars and liked should be carrying different icons :sweat_smile: ?

icon_ambi

**Comment by Gauravano** [comment]
how about star for liked?

**Comment by jywarren** [comment]
🌟👍🏼😄

**Comment by Gauravano** [comment]
@jywarren this one is ready. Thanks!

**Comment by Gauravano** [comment]
Also, I have started on this old issue https://github.com/publiclab/plots2/issues/2304 and left some comments there. Thanks!

**Comment by jywarren** [comment]
:+1:

**Pull request merged**
