### PR TITLE
fixed sorting on tags index page

### LINKED ISSUE #4271: Sorting of '# of people subscribed' on /tags doesn't work
### Please describe the problem (or idea)
Sorting of `# of people subscribed` doesn't work.. 
The `ascending` and `descending` is broken and doesn't show up correctly..

sorting people error

> What did you expect to see that you didn't?

By clicking on it, the sorting should have shown proper sequence of `ascending` and `descending`.

### Please show us where to look

https://publiclab.org/tags?sort=followers&order=desc

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by shubhscoder**
Fixes #4271

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

sorting

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
Hi, can you upload a better GIF.. I'm unable to view it properly.. 
Thanks for your PR

**Comment by shubhscoder** [comment]
Okay I ll do that !

**Comment by oorjitchowdhary** [comment]
Hi @shubhscoder .. I think the problem still persists... I can see the sorting order in desc is 2,1,0,0,2,1 ... Please upload a slower GIF.. I may have not seen it correctly...

**Comment by shubhscoder** [comment]
Slower gif - 
sort_final
 @oorjitchowdhary this gif would probably make it clear. Thank you so much!

**Comment by oorjitchowdhary** [comment]
Oh I'm sorry couldn't see it in the first time.. 
Great work @shubhscoder  🎉 

@SidharthBansal @jywarren I think this can be merged!

**Comment by shubhscoder** [comment]
Yes sure @jywarren , that sounds great. Thank you so much ! I will definitely take that into consideration!
Should I write unit tests now ? I can open another issue for this, and fix that right away?

**Comment by jywarren** [comment]
you can if you'd like! You can see (probably too much info) about test
coverage here: https://coveralls.io/github/publiclab/plots2

**Comment by shubhscoder** [comment]
Yes sure I ll do that right away! Thank you so much !

**Pull request merged**
