### PR TITLE
Fixing Save Functionality of /profile/edit

### PR DESCRIPTION
**Pull request by kunalvaswani123**
(<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kunalvaswani123** [comment]
@SidharthBansal could you review this ?

**Comment by kunalvaswani123** [comment]
gift?

**Comment by SidharthBansal** [comment]
You need to untrack the gemfile.lock
You don't have to delete it.

**Comment by kunalvaswani123** [comment]
yeah I saw my mistake

**Comment by kunalvaswani123** [comment]
I'll create another pull request

**Comment by SidharthBansal** [comment]
Gif means screen recording to show the behaviour. It is video of the screen.

**Comment by kunalvaswani123** [comment]
ok

**Comment by SidharthBansal** [comment]
No problem.
Please tag me in the upcoming PR so that I can help you.

**Pull request closed without merging**
