### PR TITLE
Make the hover drop downs in the navbar instead of click.

### LINKED ISSUE #5019: Make the hover drop downs in the navbar instead of click.
The main navbar has dropdowns which open when clicked. I suggest that it will be better if there is hover dropdowns as it is more convenient and user friendly. 
Screen Shot 2019-03-11 at 11 02 09 PM

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5019  (<=== Add issue number here)

I have added the following piece of code in app/assets/stylesheets/question.css
Screen Shot 2019-03-12 at 3 17 50 PM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
@jywarren I have resolved the stated issue. Kindly look into it. Thanks!

**Comment by shubhscoder** [comment]
@gautamig54 Thank you so much for this. Just a few suggestions. Don't need to post the screenshot of the changed code , instead post the screenshot of the page reflecting the change that your code does. Can you please do that? Thank you !

**Comment by gautamig54** [comment]
Sure! The dropdown opens when hovered.

Screen Shot 2019-03-11 at 11 02 09 PM

**Comment by jywarren** [comment]
Thanks!!!!!

**Pull request merged**
