### PR TITLE
Removed Donate under Get Involved completely

### LINKED ISSUE #3449: Improve  navbar for short resolution or mobile view Part 1
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
there are also changes in nav bar,

- Click on get Involved

 in this section when  get Involved Drop down then It's also show Donate option so there is twice donate option

nav4

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome ubutnu 16
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #3449  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* \[x] code is in uniquely-named feature branch and has no merge conflicts
* \[x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 
 
This removes the redundant Donate option under Get Involved completely. Please tell me if any changes must be made.

Thank you,
Kevin Luo

### CODE REVIEW

**Comment by avsingh999** [comment]
@kevinzluo  great work,
please add a screenshot in short resolution like  mobile view
thanks :smile:

**Comment by avsingh999** [comment]
@SidharthBansal  @jywarren  it looks good to me, I think ready to merge
thanks :)

**Comment by jywarren** [comment]
I believe this may be present so that as the menubar gets narrower in size, the items are removed from the bar and added to the menu. Can you try resizing the window horizontally to confirm if that's what this style is for? If so, we appreciate your work a lot! But we would need to keep this in there. Does that make sense? As the window narrows, fewer items are shown, so they are added into the dropdown menu as they disappear. 

I hope other menu items haven't been removed!

**Comment by kevinzluo** [comment]
@jywarren 
I believe I understand what you mean. So as the screen gets smaller, the bottom items of the menu are no longer able to be shown, so they are added into the dropdown menu. Might I ask why the other items are not added into the dropdown menu then?

Thank you,
Kevin Luo

**Comment by jywarren** [comment]
Maybe we have already broken this feature a little bit? Or maybe it wasn't fully implemented. But you have it exactly right! You can see the original feature implementation here:

`Navbar runs out of space (#3491)`

https://github.com/publiclab/plots2/commits/e278882550c501cee6efa3d457661a9244cf6476/app/views/layouts/_header.html.erb

I wonder, to complete this PR, would you mind checking if any others have been removed and shouldn't have been? Then we can mark this task complete, as you've done exactly as it was written. We don't have to merge anything if we decide not to. Thank you!

**Comment by kevinzluo** [comment]
After looking for a bit I believe I have discovered the source of this issue:

PR #1748 (issue #1734) moved the Donate button under the Get Involved menu because the Donate button was disappearing on small screen sizes.
Then after a few months the PR you mentioned (#3491) created the dropdown menu that allowed Donate to stay on the screen under a new menu.
After this more recent PR I don't think there is a need for the fix the first created, which was to move Donate to under the Get Involved dropdown.
I have also looked and I don't think any other items were removed.

Thank you,
Kevin Luo

**Comment by jywarren** [comment]
OK, sorry, finally merging this one! Thank you!!!

**Pull request merged**
