### PR TITLE
Basic Makefile functionality and rename database.yml.sqlite.example

### LINKED ISSUE #1383: Add Makefile
### What happened just before the problem occurred

Today I was re-reading the README.md and found this:
```
Installation
In the console, download a copy of the source with git clone https://github.com/publiclab/plots2.git.
Enter the new plots2 directory with cd plots2.
Install gems with bundle install --without production mysql from the rails root folder, to install the gems you'll need, excluding those needed only in production. You may need to first run bundle update if you have older gems in your environment from previous Rails work. 
Make a copy of db/schema.rb.example and place it at db/schema.rb.
Make a copy of config/database.yml.sqlite.example and place it at config/database.yml
Run rake db:setup to set up the database
Install static assets (like external javascript libraries, fonts) with bower install
(optional, not recommended) Install solr engine rails generate sunspot_rails:install
(optional, not recommended) Start the solr server in foreground by using bundle exec rake sunspot:solr:start
(optional, not recommended) Index your search database in solr server using bundle exec rake sunspot:reindex
Start rails with passenger start from the Rails root and open http://localhost:3000 in a web browser.
Wheeeee! You're up and running! Log in with test usernames "user", "moderator", or "admin", and password "password".
Run rake test to confirm that your install is working properly. For some setups, you may see warnings even if test pass; see this issue we're working to resolve.
```
Which looks much like `.travis.yml`, `install_cloudnine.sh` and parts of `Dockerfile`. It hit me that @ryzokuken also said, we could collapse all of these into a Makefile with different build targets.
These come to mind
```
make # build (default)
make dev
make test
```
I'm sure we'll come up with a few for containers as well.
I'll look into this in coordination with @ryzokuken who first proposed it.

### Relevant URLs

`README.md`, `install_cloudnine.sh`, `.travis.yml`

### PR DESCRIPTION
**Pull request by ryzokuken**
Closes #1383 

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren @icarito Please look into this one whenever possible. Will appreciate feedback. Also, I have no idea about the steps involved into setting the app up in production, so I would need your help for that. I tried setting up from scratch using this, and it works.

**Comment by ryzokuken** [comment]
Also, had no idea you guys had already fixed the .sqlite.example file

@icarito Its strange that it doesn't throw any mysql errors for me.

**Comment by icarito** [comment]
Very promising indeed!
At first naive try on cloud9 bumped into https://github.com/publiclab/plots2/issues/1392.
It's unrelated of course. Since this doesn't affect anything, I think we should merge it!

**Comment by icarito** [comment]
@jywarren is it squash and merge or rebase and merge? :tada:

**Comment by jywarren** [comment]
Squash and merge also rebases!

**Comment by jywarren** [comment]
OK -- would the next step be to get the Docker process to use this Makefile? That way we can ensure it's working whenever tests run, and less redundancy (which is your point after all, of course)?

**Comment by ryzokuken** [comment]
@jywarren @icarito Please tell me the exact way you guys setup Docker and staging and I would add that to the Makefile as well. Thanks.

**Comment by jywarren** [comment]
OK, i'm going to merge this, but please open a new issue outlining how we might get the other setup systems to use this makefile, so as to include it in testing processes and also to reduce the number of redundant ways we set things up. For example:

* install_cloudnine.sh
* docker
* travis

**Comment by jywarren** [comment]
Thanks!!

**Pull request merged**
