### PR TITLE
Standardize tooltips on row of icons

### LINKED ISSUE #9812: Standardize tooltips on row of icons
**Please describe the desired behavior.**
Describe the solution you'd like.

I'd like to see consistency in the tooltips on this series of icons: 
inconsistent-tooltips

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

This occurs on all notes and all wikis. 

Thank you for reading!

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #9812 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
ezgif com-gif-maker

**Review by Tlazypanda — APPROVED** [review]
Hey @Manasa2850 this looks good :tada: 

Just looping in @ebarry for feedback if any :v: Thanks for working on this!

**Comment by ebarry** [comment]
this looks PERFECT
WONDERFUL
THANK YOU

**Comment by jywarren** [comment]
Looks great, thank you!!!

**Pull request merged**
