### PR TITLE
Create function to test yahoo quote present 

### LINKED ISSUE #4112: Move .yahoo_quoted class checking to new function
Here, we are checking for the presence of `.yahoo_quoted` https://github.com/publiclab/plots2/blob/ff870dea11781ab5ed50a806a55f362210f3a638/app/models/comment.rb#L300
We can improve this by moving this checking into the new function just like we have for gmail.
https://github.com/publiclab/plots2/blob/ff870dea11781ab5ed50a806a55f362210f3a638/app/models/comment.rb#L291

### PR DESCRIPTION
**Pull request by kimcheung**
Fixes #4112 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [X] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kimcheung** [comment]
@publiclab/reviewers looks like the Travis CI here failed during build setup of downloading dependencies. How do I retrigger the run?

**Comment by tawahpeggy** [comment]
@kimcheung did everything go well on your machine or did you only notice errors during the PR?

**Comment by kimcheung** [comment]
I didn't run any tests locally... just when I created the PR. How do I run the tests locally?

**Comment by tawahpeggy** [comment]
am not really sure but  try this it might work Run : rails test to confirm that your install is working properly. Or rails test:system for system tests

**Comment by kimcheung** [comment]
@tawahpeggy But I think since this is more a dependency downloading issue, I think retriggering the Travis CI should resolve the issue?

**Comment by tawahpeggy** [comment]
you are welcome please let me know when it woks, am eager to find out

**Comment by kimcheung** [comment]
@tawahpeggy that did it; now it's properly failing on the tests

**Comment by kimcheung** [comment]
@publiclab/reviewers please review :)

**Review by cesswairimu — APPROVED** [review]
:tada:

**Comment by cesswairimu** [comment]
Thanks @kimcheung for working on this :tada:

**Pull request merged**
