### PR TITLE
Header button toolbar fix for responsive layouts

### LINKED ISSUE #9342: Fix "Insert Header" Toolbar Button Responsive Styling
In the legacy editor, the "Insert Header" toolbar button's icon completely disappears when you resize the window.
Specifically, if the window's width is greater than 700px and less than 1000px.

## Video
(The Header button is the H in the video below)

https://user-images.githubusercontent.com/4361605/111892783-b005ec80-89bb-11eb-81e6-14d68b3a9422.mov

## How to Reproduce
Go to any place that uses the legacy editor on our site. This includes notes, wikis, and questions. 
It also includes `/wiki/new`.

1. For example, go to [this note](https://stable.publiclab.org/notes/noi5e/01-06-2021/post-note-before-wiki) on our testing server at stable.
2. Resize the window as above, and notice how the H disappears.

## Suggested Fixes
You'll have to do some research in the codebase and the CSS stylesheets.

The partial for the toolbar is at `/app/views/editor/_toolbar.html.erb`:
https://github.com/publiclab/plots2/blob/07a243da39702501d0f5d4de8a3683a24d680a38/app/views/editor/_toolbar.html.erb#L29-L44

I notice that the icon is wrapped in a `span` with class `d-md-none`, so that might be it. But definitely play around with this and see what you find!

This is a great issue for someone who just completed an FTO and wants something a little more challenging.

Post a comment here to claim this issue, and afterward, feel free to post a comment asking for help if you get stuck!

### PR DESCRIPTION
**Pull request by waridrox**
Fixes #9342 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Screenshot 2021-03-21 at 7 58 51 PM

@noi5e kindly review this. Thanks :)

### CODE REVIEW

**Comment by govindgoel** [comment]
@waridrox Can you share a screenshot or recording of changes

**Comment by waridrox** [comment]
> @waridrox Can you share a screenshot or recording of changes

I've shared those in the issue itself...Here's the final output ^^

**Review by noi5e — APPROVED** [review]
Looks great! Thank you! :tada:

**Review by cesswairimu — COMMENTED** [review]
Great :tada: thanks for working on this @waridrox 

Thanks @noi5e and @govindgoel  for the reviews

**Review by cesswairimu — APPROVED** [review]

**Pull request merged**
