### PR TITLE
Add share option for Question page

### LINKED ISSUE #3653: Add share option for questions page
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$_answer.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb) in the `$REPO` repository (press the little pen Icon) and edit after the line 60 as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
+ <a href="#a<%= answer.id %>" class="btn btn-default btn-sm "><i class="fa fa-share"></i></a> &nbsp;
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by agam-kashyap**
Fixes #3653 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by agam-kashyap** [comment]
I put in the issue number. 
But I didnt understand what was meant by checking the checkboxes?
could I get some help with that?
Thanks.

**Comment by Dhiraj240** [comment]
@agam-kashyap  Have you read this : 
```
It looks like you haven’t marked all the checkboxes. Help us review and accept your suggested changes by going through the steps one by one. If it is still a ‘Work in progresss’, please include ‘[WIP]’ in the title.
```
This is the reply of plots bot.
Also i please write just Fixes issue_number at front with some short extensions of the issue you solved instead of using these phrases ```I have made the necessary change. PLease review it.```
Also you haven't changed this ```Fixes #[Add issue number here.]``` use ```Fixes #issue_number ``` inside PR template.

**Comment by agam-kashyap** [comment]
@publiclab/reviewers I made the changes in the title as suggested. Could you please take a look for issues?

**Comment by Dhiraj240** [comment]
@agam-kashyap you haven't changed this ```Fixes #[Add issue number here.]``` inside your PR body

**Comment by igniteeng000** [comment]
make your commit name descriptive.

**Comment by agam-kashyap** [comment]
@igniteeng000 Could you review my code again? I made the necessary changes. Also, what should I write to in my commit name to make it more descriptive?

thanks

**Comment by gauravano** [comment]
Hi all, I think link icon is fine as using share icon can create confusion in mind of users, so closing this issue. Thanks all!

**Pull request closed without merging**
