### PR TITLE
DrupalNode to Node and drupal_node to node

### PR DESCRIPTION
**Pull request by aayushgupta1**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, it looks like some tests ended up failing-- can you have a look and see what went wrong? You can click on "Details" in the Travis area above to see the output.

**Comment by ryzokuken** [comment]
@aayushgupta1 Please rebase your branch on top of latest master and re-push your changes.

**Comment by ryzokuken** [comment]
@aayushgupta1 The DB seed code failed. Please look into it.

**Comment by aayushgupta1** [comment]
Yeah. I am looking into it.

Regards,

Aayush Gupta

**Comment by jywarren** [comment]
And please ask for help if you get stuck! thanks! 👍

**Comment by aayushgupta1** [comment]
Hi. I was just going through the error. But I just changed the following:

https://github.com/aayushgupta1/plots2/blob/master/db/seeds.rb#L31
https://github.com/aayushgupta1/plots2/blob/master/db/seeds.rb#L41
https://github.com/aayushgupta1/plots2/blob/master/db/seeds.rb#L55
 where I changed DrupalNode to Node, which has been defined in https://github.com/aayushgupta1/plots2/blob/master/app/models/node.rb and has been changed everywhere in each file.

**Comment by aayushgupta1** [comment]
Kindly help.

**Comment by ryzokuken** [comment]
@aayushgupta1 `NameError: uninitialized constant Node::DrupalNodeCounter` was `DrupalNodeCounter` renamed to something else?

**Comment by jywarren** [comment]
I see the error here: 

```
NameError: uninitialized constant Node::DrupalNodeCounter
/app/app/models/node.rb:174:in `setup'
```

That's this line: https://github.com/aayushgupta1/plots2/blob/master/app/models/node.rb#L174

I think if you rebase over the latest master, this should go away, since we've gotten rid of that line in the latest version. Make sense?

**Comment by jywarren** [comment]
See for example in the latest version: https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L128-L131

**Comment by jywarren** [comment]
Hi, Ayush! Here are some resources on rebasing and squashing!

https://help.github.com/articles/about-git-rebase/

https://shinglyu.github.io/web/2016/11/08/servo-rebase-and-squash-guide.html

I hope that helps!

**Comment by aayushgupta1** [comment]
@jywarren @ryzokuken It's showing some kind of conflict. At the positiion where it is showing the conflict, I need it to be changed to *Node* from *DrupalNode*

**Comment by jywarren** [comment]
Hi, yes -- i think you need to rebase on top of the latest master -- i don't see that your latest commits are. If you think you'll be able to in the next day, I can try to hold off on merges for 12-24 hours to make your rebasing easier?

**Comment by jywarren** [comment]
That's weird -- error was `SystemStackError: stack level too deep` -- not sure what's happened. Running it again.

**Comment by jywarren** [comment]
I think I found it and fixed it! Let's see!

**Comment by jywarren** [comment]
Still a few more errors -- https://travis-ci.org/publiclab/plots2/builds/211537898

But getting really close! Remember to `git pull` from your master branch to get my additions before you keep going on this!

A couple places I see in the errors:

* https://github.com/aayushgupta1/plots2/blob/master/config/locales/models/drupal_node/en.yml#L4
* The name of this file and class: https://github.com/aayushgupta1/plots2/blob/master/test/unit/drupal_node_test.rb
* A bunch of instances of "drupal_node" in app/models/node_selection.rb
* A few in this file: https://github.com/aayushgupta1/plots2/blob/master/app/views/dashboard/_node_wiki.html.erb#L4


Try running `grep -r DrupalNode app` and `grep -r drupal_node app` to find more instances, and check your errors when you add a new commit. 

Thanks for your hard work!

**Comment by aayushgupta1** [comment]
This is in reference to #956

**Comment by jywarren** [comment]
Hmm, checks still failing. Let me take a look at the errors.

**Comment by jywarren** [comment]
Another ` SystemStackError: stack level too deep` -- checking for a circular reference...

**Comment by jywarren** [comment]
Wait, not sure why this got closed... uh, i just pushed a rebased version. Hang on a sec!

**Comment by jywarren** [comment]
OK, you know, it's because you were developing on your master branch. I've now forced your master branch to sync with the publiclab master branch, apologies -- but this is one reason not to develop new features on your master branch. However, i'll open a new PR and link to it here with the rebased code.

**Comment by jywarren** [comment]
OK, I moved it here: #1342 and you can fork that branch to keep working. But I'm adding a few changes too to try to get it to run! It's so close!

**Pull request closed without merging**
