### PR TITLE
Get numerical hashes like #123 to link to notes, not generate tag links #1825

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks super!!! Do you think we could add a simple test for this to https://github.com/publiclab/plots2/blob/43dcbcd8601e8a4fa23bef9eda7030b8e60a61e7/test/unit/constants_test.rb ?

Essentially running a test string like `hello #42` through `finder.gsub(Callouts.const_get(:HASHTAGNUMBER), Callouts.const_get(:NODELINKMD)) `

What do you think?

Thanks so much, this is really exciting!

**Comment by jywarren** [comment]
Great, thanks! Merging now.

**Comment by jywarren** [comment]
Solved #1825

**Comment by sagarpreet-chadha** [comment]
Thank You :)

**Pull request merged**
