### PR TITLE
Added Correct form validation 

### LINKED ISSUE #3646: Display message to enter login details.
### Please describe the problem (or idea)
If a user do not enter any information in the email and password fields then it should, display a message to enter it.Instead of following.

> What happened just before the problem occurred? Or what problem could this idea solve?
screenshot 173

> What did you expect to see that you didn't?
A simple form message to ask for details.

### Please show us where to look

I need to investigate

### What's your PublicLab.org username?
Dhiraj24

> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, latest and OS is Windows 8.1

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #3646 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### Some GIFs to show the working
- Case with Null user name and password followed by correct username and password

login

- Case to show wrong username and password

login1

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
@gauravano , i have added the required clause for username and password. Hence the form is never submitted with null values and the wrong alert never shows up. Kindly review :) Thanks !

**Comment by gauravano** [comment]
Hey @ananyaarun , can't see null value part in the Gif

**Comment by ananyaarun** [comment]
Hey @gauravano , Sorry the first part of the first gif was unclear. My bad!!
Here is a better gif.
new

**Comment by jywarren** [comment]
Hmm, is there any way to make it appear more urgently, like with a red highlight? If not, I'm fine merging this! I just don't want people to get confused as to why the button isn't working, and maybe not noticing the messages. Thanks!

**Comment by ananyaarun** [comment]
@jywarren , There is a pop up that says "pls enter this field" when login doesnt work. So i dont think the user will be confused ?

**Comment by jywarren** [comment]
Ok, I think this works then! I was just worried maybe it wasn't noticable enough but you're probably right and we can do some user testing to be sure. Thanks, merging now!!!

**Pull request merged**
