### PR TITLE
Testing comment sanitizing -- help wanted!

### PR DESCRIPTION
**Pull request by jywarren**
This should fail, then we should fix it!

This demonstrates a vulnerability documented in #3549 -- that issue now should build on this one to eliminate the vulnerability. Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
```
/app/test/unit/comment_test.rb:2:in `<top (required)>': uninitialized constant ActionView::Helpers::ApplicationHelper (NameError)
```

But also now #3555 has moved it so we can use `comment.render_body` instead in the test!

**Comment by gauravano** [comment]
@jywarren please update the status of this PR. Thanks!

**Comment by jywarren** [comment]
This needs rebasing, then we need to add `ApplicationController.helpers.sanitize()` to this line:

https://github.com/publiclab/plots2/blob/a95ba1f4cba03afc3f94b6c874793411d7dcb08a/app/models/comment.rb#L478

However we'll want to allow (whitelist) a fairly wide range of attributes following documentation here:

https://guides.rubyonrails.org/security.html#html-javascript-injection-countermeasures

Here are some sources for whitelists of HTML attributes:

https://help.manuscript.com/12064/embedding-html-in-wiki-articles

https://github.com/rickpmartin/sanitize-html#what-are-the-default-options

I would guess at least:

`href, class, id, width, height, border, src, placeholder, title` and quite a few more...

**Comment by SidharthBansal** [comment]
@jywarren we can include this in GCI if you want
cc\ @VladimirMikulic @Uzay-G 
GCI students are advised to focus on the tasks on which they are working. Don't get overwhelmed by the emails.

**Comment by jywarren** [comment]
That would be great, thank you!

**Comment by SidharthBansal** [comment]
Who is willing to grab this issue?

**Comment by VladimirMikulic** [comment]
I and @Uzay-G will come up with something.

**Comment by SidharthBansal** [comment]
Oh you both are distributing issues at Gitter. I forget. Sorry

**Comment by VladimirMikulic** [comment]
:+1:

**Comment by VladimirMikulic** [comment]
This can be closed. #7282 resolved this.

**Pull request closed without merging**
