### PR TITLE
Fix Like count error

### LINKED ISSUE #2298: Like count error on profile page
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem
The like count on the profile page does not correspond to the number of liked notes shown on /profile/user/likes' page
like-count-1
like-page-1

### Solution

https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/models/drupal_user.rb#L97-L106

Like_count method could be similar to liked_notes method. We could replace 
https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/models/drupal_user.rb#L98 with something like:-
`
Node.includes(:node_selections).references(:node_selections).where("type = 'note' AND node_selections.liking = ? AND node_selections.user_id = ? AND 
node.status = 1", true, uid).count
`

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

### PR DESCRIPTION
**Pull request by aamarill**
Fixes issue #2298 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by aamarill** [comment]
@publiclab/reviewers Can you help me understand this error on Travis 😅 
screen shot 2018-05-25 at 9 59 13 pm

**Comment by ViditChitkara** [comment]
Hi, I see a lot of changes in your schema.rb.example which are not related to the migration you made. The only change that should reflect in schema.rb.example is the schema version. 
If this doesn't help too, rebase to the latest master. There were some recent changes related to this.

**Comment by aamarill** [comment]
@ViditChitkara Awesome! Looks like your recommendation worked. I am not sure why simply running the new migration made those changes on the schema... 

Anyway, let me know if there's anything else we need 😄 

Thank you! 🙏

**Comment by jywarren** [comment]
Hi! I've done a small merge commit to resolve a conflict. But I think this should be ready otherwise! Let's see if it passes tests again. Thanks so much!!!

**Comment by jywarren** [comment]
We're tracking some kind of issue with the test runner - not related to your work! Thanks for your patience!

**Comment by aamarill** [comment]
No worries @jywarren Thanks for the notice, I was about to get in there and try to fix stuff 😅

**Comment by jywarren** [comment]
Ok! Restarted the tests now we're fixed the bug. Let's see!!!

**Comment by jywarren** [comment]
Awesome! Thanks all!!!!!

**Pull request merged**
