### PR TITLE
Refactors mail parse test to integration from unit

### LINKED ISSUE #3432: Move an integration test to integration test folder which is present in Unit test file [PART 5]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Currently some integration tests are present in unit test folder, so we can move them from this folder and add them to integration test folder.
https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/test/unit/comment_test.rb#L260

### PR DESCRIPTION
**Pull request by kopecs**
Fixes #3432 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kopecs** [comment]
Hey @publiclab/reviewers, any help would be great!

**Comment by rockstar777** [comment]
@jywarren @SidharthBansal need help here in review?

**Comment by kopecs** [comment]
I've made those requested changed @namangupta01, anything else before this can be merged?

**Comment by jywarren** [comment]
Awesome work and thanks for the help, everyone!!

**Pull request merged**
