### PR TITLE
DrupalNode.activities tests -- fixes #834

### LINKED ISSUE #834: Test DrupalNode.activities with activity node fixtures
We need to test the new `DrupalNode.activities` and `DrupalNode.upgrades` methods at the bottom of `drupal_node.rb`:

https://github.com/publiclab/plots2/tree/master/app/models/drupal_node.rb

We should create fixtures in:

https://github.com/publiclab/plots2/tree/master/test/fixtures/node.yml
https://github.com/publiclab/plots2/tree/master/test/fixtures/tags.yml
https://github.com/publiclab/plots2/tree/master/test/fixtures/community_tags.yml

to create dummy nodes that have tags `activity:foo` and `upgrade:foo` and then check if `DrupalNode.activities` and such actually return those nodes. This can be a unit test in:

https://github.com/publiclab/plots2/tree/master/test/unit/drupal_node_test.rb

### PR DESCRIPTION
**Pull request by prabhagharan**
Fix for issue https://github.com/publiclab/plots2/issues/834

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by prabhagharan** [comment]
Seems build is failing. Let me know if I am doing something wrong or need to re-trigger the build ?

**Comment by jywarren** [comment]
Yes, sometimes builds fail due to a broken connection or install hiccup that's not related to new code, and that's what seems to have happened here. 

This looks great, and I hope to merge in once the build runs again. Thanks a lot - very cleanly implemented and we appreciate your contribution! May I ask how you found our project? 

If you're looking for a new challenge, there are lots open at https://github.com/publiclab/plots2/labels/help-wanted

Thanks again!

**Comment by jywarren** [comment]
Ah, ok -- now seeing an actual test error:

`Error: test_view_notes_for_an_author(PublicPagesTest): ActionView::Template::Error: undefined method `totalcount' for nil:NilClass`

This is because each node requires a matching node_counter fixture in https://github.com/publiclab/plots2/blob/master/test/fixtures/node_counter.yml

However, that's kind of a silly requirement, esp. since those fixtures are empty. If you could change the way `totalcount` works on these two lines:

* https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L447
* https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L454

perhaps by adding a check for `self.drupal_node_counter` before using `.totalcount`, we could avoid needing that entire fixture file. That'd benefit everyone -- willing to give it a try?

**Comment by prabhagharan** [comment]
Thanks you, I found this project through up-for-grabs.net.
I have fixed the issues and updated other tests which were failing because of my update.
Yes, I can implement the changes related to `totalcount` :)

Not sure whether this is right place ask, when I run tests locally getting error like `RSolr::Error::ConnectionRefused: Connection refused ` how can I fix it ?

**Comment by jywarren** [comment]
Hi -- if you have latest version of the code and you run just `rake test` instead of `rake test:all` you'll only run the tests that do /not/ rely on RSolr, so you shouldn't get that error. Thanks!

**Comment by jywarren** [comment]
I still see a few test failures in the latest build -- would you mind taking a look? You can see them by pressing "Details" next to the TravisCI tests, below.

**Comment by prabhagharan** [comment]
Yeah I got it, now I am able to see the failures more clearly. Fixed all the errors, seems build is again broke. May I know how to re-trigger build upon such failures

**Comment by jywarren** [comment]
Yes - you can force push the same commit back to the branch this PR is based on and it'll re-trigger. But i can do it manually - will do so now.

**Comment by prabhagharan** [comment]
Great ! thank you.

**Comment by jywarren** [comment]
Perfect -- merging now; thanks for your help! If you're looking for a new challenge, do take a look at https://github.com/publiclab/plots2/labels/help-wanted

**Comment by prabhagharan** [comment]
Awesome !!

**Comment by prabhagharan** [comment]
Hi Jeff,
Thought of fixing the 'totalcount' related issue and added a check for self.drupal_node_counter before using .totalcount and got into below issue. (just one of many)
`ActionView::Template::Error: SQLite3::ConstraintException: UNIQUE constraint failed: node_counter.nid: INSERT INTO "node_counter" ("daycount", "nid", "timestamp", "totalcount") VALUES (?, ?, ?, ?)
app/models/drupal_node.rb:455:in 'totalcount'
app/views/notes/show.html.erb:46:in 'app_views_notes_show_html_erb__1858748580900999487_70152961672520'
test/functional/notes_controller_test.rb:44:in 'block in <class:NotesControllerTest>'`
So my query is, do we actually need a save at [totalcount](https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L453) ? 
The comment says it is just a 'view count'. Let me know your thoughts.

**Comment by jywarren** [comment]
Oh, hmm, I'm not sure I follow -- could you push up a PR with your code so I can follow along better? Thanks!

**Comment by jywarren** [comment]
Hi, @prabhagharan -- i like the check you added -- but can you link to the issue you're working on, so we can discuss in that issue and not here in a closed PR? I'm just getting confused as to what problem you're working on. If there is not yet an issue, please do open a new one so we have a more appropriate place to discuss the solution. Thanks!!!

**Pull request merged**
