### PR TITLE
Changing column type in Csvfiles table

### LINKED ISSUE #6171: Simple Data Grapher error ActiveRecord::ValueTooLong: Mysql2
Got this error in Sentry -- looks like reasonably easy to diagnose?

Sentry Issue: [PLOTS2-DG](https://sentry.io/organizations/publiclab/issues/1174855841/?referrer=github_integration)

```
Mysql2::Error: Data too long for column 'filepath' at row 1
  app/controllers/csvfiles_controller.rb:35:in `add_graphobject'
    @newfile.save
...
(149 additional frame(s) were not displayed)

ActiveRecord::ValueTooLong: Mysql2::Error: Data too long for column 'filepath' at row 1: INSERT INTO `csvfiles` (`uid`, `filetitle`, `filedescription`, `filepath`, `filename`, `filestring`, `created_at`, `updated_at`, `graphobject`) VALUES (612325, '', '', '{\"completeCsvMatrix\":[[1,6,11,16,21,26,null],[2,7,12,17,22,27,null],[3,8,14,18,23,28,null],[4,9,14,19,24,29,null],[5,10,15,20,25,30,null]],\"csvHeaders\":[\"A1\",\"B1\",\"Column3\",\"C1\",\"Column5\"],\"csvSampleData\":[[1,6,11,16,21],[2,7,12,17,22],[3,8,14,18,23],[4,9,14,19,24],[5,10,15,20,25]],\"csvValidForYAxis\":[\"A1\",\"B1\",\"Column3\",\"C1\",\"Column5\"],\"completeCsvMatrixTranspose\":[[\"A1\",\"B1\",\"Column3\",\"C1\",\"Column5\"],[1,2,3,4,5],[6,7,8,9,10],[11,12,14,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[null,null,null,null,null]]}', 'file1566401573', 'data:text/csv;charset=utf-8,A1,B1,Column3,C1,Column5%0A1,2,3,4,5%0A6,7,8,9,10%0A11,12,14,14,15%0A16,17,18,19,20%0A21,22,23,24,25%0A26,27,28,29,30%0A,,,,', '2019-08-21 15:32:53', '2019-08-21 15:32:53', '{\"hash\":{\"x_axis_labels\":[3,8,14,18,23,28,null],\"y_axis_values0\":[1,6,11,16,21,26,null],\"y_axis_values1\":[2,7,12,17,22,27,null],\"labels\":[\"Column3\",[\"A1\",\"B1\"]]},\"graphType\":\"Horizontal\",\"length\":2}')

ActiveRecord::ValueTooLong: Mysql2::Error: Data too long for column 'filepath' at row 1: INSERT INTO `csvfiles` (`uid`, `filetitle`, `filedescription`, `filepath`, `filename`, `filestring`, `created_at`, `updated_at`, `graphobject`) VALUES (612325, '', '', '{\"completeCsvMatrix\":[[1,6,11,16,21,26,null],[2,7,12,17,22,27,null],[3,8,14,18,23,28,null],[4,9,14,19,24,29,null],[5,10,15,20,25,30,null]],\"csvHeaders\":[\"A1\",\"B1\",\"Column3\",\"C1\",\"Column5\"],\"csvSampleData\":[[1,6,11,16,21],[2,7,12,17,22],[3,8,14,18,23],[4,9,14,19,24],[5,10,15,20,25]],\"csvValidForYAxis\":[\"A1\",\"B1\",\"Column3\",\"C1\",\"Column5\"],\"completeCsvMatrixTranspose\":[[\"A1\",\"B1\",\"Column3\",\"C1\",\"Column5\"],[1,2,3,4,5],[6,7,8,9,10],[11,12,14,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[null,null,null,null,null]]}', 'file1566401573', 'data:text/csv;charset=utf-8,A1,B1,Column3,C1,Column5%0A1,2,3,4,5%0A6,7,8,9,10%0A11,12,14,14,15%0A16,17,18,19,20%0A21,22,23,24,25%0A26,27,28,29,30%0A,,,,', '2019-08-21 15:32:53', '2019-08-21 15:32:53', '{\"hash\":{\"x_axis_labels\":[3,8,14,18,23,28,null],\"y_axis_values0\":[1,6,11,16,21,26,null],\"y_axis_values1\":[2,7,12,17,22,27,null],\"labels\":[\"Column3\",[\"A1\",\"B1\"]]},\"graphType\":\"Horizontal\",\"length\":2}')
```

### PR DESCRIPTION
**Pull request by IshaGupta18**
Fixes #6171 

@jywarren @gauravano please merge this, and let's see if this issue gets resolved!

### CODE REVIEW

**Comment by IshaGupta18** [comment]
@jywarren @gauravano good to go?

**Comment by jywarren** [comment]
Looks like you may need to update the timestamp in schema.rb.example?
Thanks Isha!

**Comment by IshaGupta18** [comment]
I have updated the timestamp?

**Comment by IshaGupta18** [comment]
Can I do it just after a little bit of testing? I really need to make sure that things work, that's why I am pressing you to merge it!

**Comment by gauravano** [comment]
Actually, please merge it in this PR only as it's just a small change.

**Comment by IshaGupta18** [comment]
@gauravano moving to #6192

**Pull request closed without merging**
