### PR TITLE
PL.editor shows map if lat,lon passed in URL.

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Can be merged after  https://github.com/publiclab/PublicLab.Editor/pull/349 is merged and published to npm.

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
@jywarren , codeclimate issue says to use `&&` instead of `and` but this is giving error!
Let's merge this if this PR looks good!

**Comment by sagarpreet-chadha** [comment]
Unrelated error to my PR:
`prockets::FileNotFound: couldn't find file 'debounce/index.js' with type 'application/javascript'`

**Comment by jywarren** [comment]
Ah, cc @cesswairimu!

**Comment by jywarren** [comment]
OK published on NPM... i've seen this error before, it may be worth
searching the plots2 issues history for it... @cesswairimu @gauravano i
don't know if you remember this "Sprockets::FileNotFound: couldn't find
file 'debounce/index.js' with type 'application/javascript'" error?

Why would it be missing the debounce lib? I believe it's an external yarn
dependency related to autocomplete.

**Comment by cesswairimu** [comment]
I believe the fix was `yarn install`

**Comment by sagarpreet-chadha** [comment]
Aha passed tests :)

**Comment by jywarren** [comment]
Awesome. I should have remembered yarn.lock!

Merging!!

**Pull request merged**
