### PR TITLE
Fixed border shadow for input box on focus

### LINKED ISSUE #9624: Changing search input box shadow style
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Basics of box shadow styling in CSS. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### What will you be working upon 

The current focus state of the search bar at http://publiclab.org/ has blue border shadow around the area.

Current behaviour:
test1

This may be hard for the user to recognise since the blue border doesn't contrast well with the dark theme of the background. This should be enhanced to provide a good user experience. 

After working, changes should reflect:
test

Target the `input` field of type `text` under `focus` state and change the default `box-shadow` property from `none` to `inset` to reflect the changes. You can take a look at the following code for reference: 
```css
box-shadow: 0 0 0 3px rgba(21, 156, 228, 0.4) inset;
```

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [style.css](https://github.com/publiclab/plots2/blob/main/app/assets/stylesheets/style.css) in the `plots2` repository.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

This issue came up into existence after discussion at #9593 
CC: @Priyaraj17 @Elukoye @cesswairimu

### PR DESCRIPTION
**Pull request by Dandu-Rajeev**
Fixes #9624 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [✔️] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by TildaDares — CHANGES_REQUESTED** [review]
This looks really great @Dandu-Rajeev but the comment you added is not necessary. Would you mind removing it and then add a screenshot of the changes you made. 

Thanks.

**Review by Dandu-Rajeev — COMMENTED** [review]
Updated the code as per review comments.

**Review by TildaDares — APPROVED** [review]
Thanks.

**Comment by Dandu-Rajeev** [comment]
What's next, @TildaDares?

**Comment by TildaDares** [comment]
@Dandu-Rajeev We'll wait for a reviewer to approve this. Could you add a screenshot of the change(s) you made?

**Comment by Dandu-Rajeev** [comment]
image
I believe you're asking for code changes @TildaDares.

**Comment by TildaDares** [comment]
@Dandu-Rajeev I'm sorry if I wasn't clear enough. I meant an image of the search box after you applied the changes.

**Comment by Dandu-Rajeev** [comment]
@TildaDares I have checked the changes using GitPod and observed that the changes are not getting reflected. I also observed that the styles in app/assets/stylesheets/styles.css are not getting applied. Request you to check and let me know how to proceed. Thanks

**Comment by TildaDares** [comment]
@Dandu-Rajeev Is your local env set up?

**Comment by Dandu-Rajeev** [comment]
@TildaDares No. I faced few issues and got confused during setup. :(

**Comment by TildaDares** [comment]
@Dandu-Rajeev Okay

**Comment by cesswairimu** [comment]
Looking great from gitpod...Thanks everyone :tada: :tada:

**Review by cesswairimu — APPROVED** [review]
Lovely :tada: :tada:

**Comment by Dandu-Rajeev** [comment]
Thank you for merging my pull request. Learnt a lot!

**Pull request merged**
