### PR TITLE
Edited `line 26` of show.html.erb

### PR DESCRIPTION
**Pull request by Abdulrahim2567**
An attempt to fix issue #10982  Added space  to the question for a better user experience on `line 26`

Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by illyShelly** [comment]
@Abdulrahim2567 Great FTO 👍 Just next time you can put number of issue to the next line looking like this: `Fixes #0000`

**Review by TildaDares — APPROVED** [review]
Thanks for working on this @Abdulrahim2567!!

**Comment by TildaDares** [comment]
Congratulations @Abdulrahim2567 🎉

**Comment by Abdulrahim2567** [comment]
@TildaDares thank you very much for the support :). Is there any issue which I could work on next?

**Comment by TildaDares** [comment]
@Abdulrahim2567 You can look out for issues with the [help-wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) or [bug](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22bug%22) tag or create FTOs for another first-timer.

**Comment by Abdulrahim2567** [comment]
okay thanks a lot I will do just that :)

**Pull request merged**
