### PR TITLE
Update "like" list URL on notes and wiki pages ~ Issue#1405

### LINKED ISSUE #1405: Fix "like" list URL on notes and wiki pages
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

What's supposed to happen: 

When you click the "like" menu, you see folks who've "liked" a note, like on this page: https://publiclab.org/wiki/hydrogen-sulfide-sensor

screenshot 2017-05-09 at 5 03 47 pm

When you click on their names, you should go to their profiles. 

What actually does happen (screenshot if helpful!): 

Unfortunately you go to a page showing their likes -- this isn't right -- at the URL (for example) https://publiclab.org/profile/warren/likes

## Solution

We should remove the trailing `/likes` from the end of that URL in this file:

https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L17

```ruby
  <i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>/likes'><%= user.username %></a><br />
```

What to change them to:

```ruby
  <i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>'><%= user.username %></a><br />
```

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

### PR DESCRIPTION
**Pull request by alanunruh**
This PR `Fixes #1405 `. 

*Removed the trailing /likes for the end of the URL in in file:

https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L17

Please review.

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this is looking great, but would you mind removing the Gemfile.lock from your PR, as I think it's just a version tweak? https://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git

Thanks! Exciting!

**Comment by alanunruh** [comment]
@jywarren Sorry for the multiple commits on such a simple task! I think I've successfully removed the Gemfile.lock file from this pull request. However, I now noticed the Travis CI build failed....

**Comment by alanunruh** [comment]
@jywarren Sorry for the multiple commits for such an easy task! I think I've successfully removed the Gemfile.lock file from the pull request. However, now I noticed the Travis CI build has failed....

**Comment by jywarren** [comment]
Ah, that's ok - GitHub can squash all your commits so that's not a big deal. But it looks like you actually removed the Gemfile.lock entirely, not just your own changes. What you can do now is just copy the Gemfile.lock from the master repository and re-add it, and push up one more commit. Check this URL (there's a tab on this page) to see if you will then have left Gemfile.lock untouched:

https://github.com/publiclab/plots2/pull/1468/files

Happy to help and thanks for your patience!

**Comment by jywarren** [comment]
There's still an odd end of file newline change, but it's not substantive, so this looks great; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Comment by alanunruh** [comment]
3rd times a charm! Sorry for the confusion, I thought you wanted the file completely removed and then thought that might be an odd request after I committed it. Sorry for the hassle. This is exactly what I was looking for though - trying to become more familiar with git!

**Comment by jywarren** [comment]
No problem at all! The Gemfile is kind of a pain and we're hoping to figure
out how to smooth that out. I'm going to try adding it to .gitignore...
#1471

Glad it was helpful to you too!

**Pull request merged**
