### PR TITLE
[Outreachy Comment Editor] New Test: Respond to Note Comment

### PR DESCRIPTION
**Pull request by noi5e**
## Prerequisite: Merge #8809 First!

- Add new fixtures for testing note comments:
  - node.yml
  - comment.yml
  - revision.yml
- New test:
  - find first comment ID (the new comment fixture)
  - POST new comment with addComment
  - assert that comment text exists

```
test 'note: respond to existing comment' do
  visit nodes(:comment_note).path
  # find comment ID of the first comment on page
  parent_id = "#" + page.find('#comments-list').first('.comment')[:id]
  # comment ID format is id="c9834"
  # regex to find everything after the "c"
  parent_id_num = /c(\d+)/.match(parent_id)[1] 
  # parameters for addComment: addComment(comment text, submitURL, comment's parent ID)
  page.evaluate_script("addComment(\"I admire you\", '/comment/create/#{nodes(:comment_note).nid}', #{parent_id_num})")
  # check for comment text
  assert_selector("#{parent_id} .comment .comment-body p", text: 'I admire you')
end
```

(This PR is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

### CODE REVIEW

**Comment by jywarren** [comment]
Once we merge #8809, and resolve any conflicts here, can you confirm that this passes locally so we can do a final review before merging (and bypassing Travis for now)? Thank you!

**Comment by jywarren** [comment]
We can mark this with `readytomerge` as soon as we get conflicts resolved and local test passing confirmed. Thanks!

**Comment by noi5e** [comment]
@jywarren Thanks, just resolved the conflicts and ran all tests locally again, looks good on my end (no additional/distinct failures)

**Comment by jywarren** [comment]
Awesome, one more conflict resolution here, and we should be good to merge! Thank you! With all this happening, are you able to track the changes (i.e. check off items) in your main project issue as well? Just to keep us organized. Thanks @noi5e !!!

**Comment by jywarren** [comment]
Ah i see each PR has a line and they're getting crossed off in https://github.com/publiclab/plots2/issues/8775 - perfect!!

**Comment by noi5e** [comment]
Did another conflict resolve, so it should be ready! 

I know it's getting a bit messy, I'll do a big organization and renaming of things after I have a decent set of tests.

**Comment by jywarren** [comment]
Awesome. Thanks again!!!! Probably best to run local tests one more time just to confirm after all the merging, deconflicting, etc. 

Thanks a ton! I appreciate the extra time it took to get these organized given the Travis outage. 🙌

**Pull request merged**
