### PR TITLE
Fix ActiveRecord::RecordNotFound when clicking on 'step-by-step activity'

### LINKED ISSUE #9475: ActiveRecord::RecordNotFound in EditorController#post
### Problem
When choosing "Share a step-by-step activity" from the "Share your work" menu, an error results because (presumably) a node cannot be found
image

Full trace:
```rb
composite_primary_keys (11.2.0) lib/composite_primary_keys/core.rb:44:in `find'
app/controllers/editor_controller.rb:70:in `template'
app/controllers/editor_controller.rb:57:in `rich'
app/controllers/editor_controller.rb:28:in `post'
actionpack (5.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.3) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.3) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
react-rails (2.6.1) lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
activesupport (5.2.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sentry-raven (3.1.2) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.3) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.3) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.3) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.3) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.3) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.3) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.3) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:840:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/builder.rb:64:in `call'
http_accept_language (2.1.1) lib/http_accept_language/middleware.rb:14:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (5.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
sentry-raven (3.1.2) lib/raven/integrations/rack.rb:51:in `call'
webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
railties (5.2.3) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.3) lib/rails/railtie.rb:190:in `method_missing'
passenger (6.0.7) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
passenger (6.0.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
passenger (6.0.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (6.0.7) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
passenger (6.0.7) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

### Browser, version, and operating system

Firefox 87.0 (64-bit)
Arch Linux x86 (64-bit) w/standard generic kernel

### PR DESCRIPTION
**Pull request by aliciapaz**
Fixes #9475
This fixes the error by removing the missing id from the URL. However, I'm concerned about this not being a solution but just a workaround.

It would be helpful to understand: 
What does this id do in that URL? why is that node missing? 

Thanks in advance 😸

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @aliciapaz ,  looks likes there are some failing tests on tags that do not seem to be related to your changes
```
===ERROR I18nTest#test_should_choose_i18n_for_tag/show (209.45s)
Minitest::UnexpectedError:         ActionView::Template::Error: missing interpolation argument :search in "Aucun résultat trouvé en cherchant \"%{search}\"" ({:tag=>"some-tag"} given)
            app/helpers/application_helper.rb:158:in `translation'
            app/views/tag/show/_tab_content.html.erb:10:in `_app_views_tag_show__tab_content_html_erb__2599195840854876495_47384223172900'
            app/views/tag/show.html.erb:158:in `block in _app_views_tag_show_html_erb___2792876303108153280_47384223051420'
            app/views/tag/show.html.erb:149:in `_app_views_tag_show_html_erb___2792876303108153280_47384223051420'
            app/controllers/tag_controller.rb:161:in `block (2 levels) in show'
            app/controllers/tag_controller.rb:160:in `show'
            test/integration/I18n_test.rb:415:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:411:in `each'
            test/integration/I18n_test.rb:411:in `block in <class:I18nTest>'

=ERROR I18nTest#test_should_choose_i18n_for_tag/widget (210.08s)
Minitest::UnexpectedError:         ActionView::Template::Error: missing interpolation argument :search in "Aucun résultat trouvé en cherchant \"%{search}\"" ({:tag=>"some-tag"} given)
            app/helpers/application_helper.rb:158:in `translation'
            app/views/tag/widget.html.erb:14:in `_app_views_tag_widget_html_erb__1813037706612507661_47384203707320'
            app/controllers/tag_controller.rb:250:in `widget'
            test/integration/I18n_test.rb:425:in `block (2 levels) in <class:I18nTest>'
            test/integration/I18n_test.rb:421:in `each'
            test/integration/I18n_test.rb:421:in `block in <class:I18nTest>'

= FAIL I18nTest#test_should_choose_i18n_for_user/_form_+_user/new (211.99s)
        <Nom d'utilisateur·ice> expected but was
        <Nom d'utilisat⋅eur·ice>..
        Expected 0 to be >= 1.
        test/integration/I18n_test.rb:198:in `block (2 levels) in <class:I18nTest>'
        test/integration/I18n_test.rb:194:in `each'
        test/integration/I18n_test.rb:194:in `block in <class:I18nTest>'
        ```

I will try and restart the build. Thanks for working on this

**Review by RuthNjeri — APPROVED** [review]
Thanks, @aliciapaz. This looks good to me. You can rebase/squash to reduce the number of commits.

**Comment by RuthNjeri** [comment]
I have actually done a squash through the merge. Thanks again @aliciapaz

**Comment by RuthNjeri** [comment]
Please have a look at https://github.com/publiclab/plots2/pull/9511, it would seem that removing the nid would remove a reference to the node that inserts pre-existing text.

**Pull request merged**
