### PR TITLE
Fix multiple pagination on tag list page

### LINKED ISSUE #6387: multiple page tab bars
I was on this page https://publiclab.org/questions/tag/pm?page=2 scrolling through questions, when I saw it has two scroll bar arrows to toggle between pages: 
Screen Shot 2019-10-03 at 10 34 56 AM

### PR DESCRIPTION
**Pull request by nstjean**
Fixes #6387 (<=== Add issue number here)

There was an extra /div closing tag in this file, causing the page code to get skewed, resulting in duplicate pagination showing at the bottom of the page. The code was not indented correctly so I formatted it for readability so I could find the error.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
@nstjean Nice job !
You can add more commits to this PR to fix the actual multiple page tab bars problem too.
Feel free to ask for help :)

**Comment by nstjean** [comment]
Thanks!

Should I be concerned about the Junit parsing warning?

I just need to know what logic was expected with the "Asked" and "Answered" tabs. Is Answered any question node that has more than one comment? Or is there another data value it should check?

**Comment by nstjean** [comment]
> @nstjean Nice job !
> You can add more commits to this PR to fix the actual multiple page tab bars problem too.
> Feel free to ask for help :)

After re-reading this message I think the wording of my PR was confusing. The pagination is the "multiple page tab bars". It is all set and fixed.

Next I'll open a new PR to handle the tab buttons that don't work.

**Comment by jywarren** [comment]
Hi! This is looking great. Just to confirm since the changes are considerable, would you mind sharing a screenshot of this working? Thanks!!!

**Comment by nstjean** [comment]
Sure! This shows the bottom of the page where the pagination bar is now correctly showing.

FireShot Capture 007 - 🎈 Public Lab_ question_general - localhost

**Comment by cesswairimu** [comment]
Hi @nstjean, could you please rebase/fix the conflicting files on this? Thanks for working on this :+1:

**Comment by nstjean** [comment]
I fixed the conflict, made a small chance, and figured out how to force push it up. :)

Here's a pic of the change, just adding a margin above the paginator on the /questions/ page.

FireShot Capture 059 - 🎈 Public Lab_ Questions and Answers - localhost

**Comment by SidharthBansal** [comment]
There are some conflicts. Kindly rebase

**Comment by jywarren** [comment]
I'm sorry, i think this is now resolved due to our `pagy` migrations! #8426 thank you and apologies for letting this sit so long!!!

**Pull request closed without merging**
