### PR TITLE
Added RAILS_ENV in environment in mailman service

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
@jywarren Should we merge this so that we can check ?

**Comment by jywarren** [comment]
Want to push it to unstable which is now set up with a mailbox!? Thanks!!!!

**Comment by namangupta01** [comment]
Thanks! Pushing to unstable.

**Comment by namangupta01** [comment]
@jywarren Is it open for less secure apps because i am not getting mails in logs.

**Comment by jywarren** [comment]
Yes it is set up... Let me check mail is arriving - it's
notifications-unstable@publiclab.org

On Jun 23, 2018 10:44 AM, "Naman Gupta" <notifications@github.com> wrote:

@jywarren <https://github.com/jywarren> Is it open for less secure apps
because i am not getting mails in logs.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/pull/2899#issuecomment-399696331>, or mute
the thread

**Comment by jywarren** [comment]
Yes I see your email in the inbox!

**Comment by namangupta01** [comment]
Strange not getting mail receiving logs in
https://unstable.publiclab.org/mailman.log

**Comment by jywarren** [comment]
Hmm, no! Did we change the docker files in another PR? Check the history
for those files on master branch?

**Comment by namangupta01** [comment]
Hey @jywarren!!! Error is now removed. Please check it out. And one more thing `mail.googlemail.com` won't work so we should use `pop.gmail.com`. 
Error resolve in another pr #2912. So closing this.
Thanks!!!!!

**Comment by namangupta01** [comment]
Done in #2912

**Pull request closed without merging**
