### PR TITLE
Removed inconsistency in wiki/new toolbar icon. Icon and Text colour changed to #222 and hover color to white .

### LINKED ISSUE #6519: What color should toolbar buttons be?
Currently the toolbar when you are typing a comment looks inconsistent:
FireShot Capture 025 - 🎈 Public Lab_ Do stinkbugs actually stink_ - localhost

What do you think the color should be? Grey?
FireShot Capture 023 - 🎈 Public Lab_ Do stinkbugs actually stink_ - localhost

Or black?
FireShot Capture 024 - 🎈 Public Lab_ Do stinkbugs actually stink_ - localhost

Once I get some feedback I'll turn this into a FTO. :)

### PR DESCRIPTION
**Pull request by smarty1palak**
Fixes #6519 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 
Screenshot from 2019-12-12 21-21-31
Screenshot from 2019-12-12 21-26-09

Thanks!

### CODE REVIEW

**Comment by smarty1palak** [comment]
@nstjean  can you guide me here? What could be the reason of failure? I am unable to figure out.

**Comment by nstjean** [comment]
@smarty1palak Sure! Let's take a look!

**Comment by nstjean** [comment]
Ahh, these are issues that are unrelated to your code, this is popping up on pull requests and I'm not sure why. I know they are working on it! So if you can just be patient, once that's fixed this will be merged, but this looks good! Thank you!! :)

**Comment by smarty1palak** [comment]
Sure thanks !

**Comment by smarty1palak** [comment]
Okay sure will make the changes .

**Comment by jywarren** [comment]
Thanks all! This is fabulous! 🎉

**Pull request merged**
