### PR TITLE
Update install_cloudnine.sh for AWS Cloud9 for Amazon Linux Platform

### LINKED ISSUE #6773: install_cloud9.sh needs to be updated for AWS Cloud9 with Amazon Linux Platform
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The problems occur during the installation of the commands in the script shell all the way up until you have logged in as the user/moderator/admin. To break down each point of occurrence:
1. During installation, the terminal will prompt - 
* `RVM is not a function, selecting rubies with 'rvm use ...' will not work.`
* `sudo: apt-get: command not found`
* The top right-hand corner will display: `On Amazon Linux use yum instead of apt-get`
2. After installation, after runnning `rails s -b $IP -p $PORT`, the terminal will prompt - 
* `Could not find proper version of railties (5.2.3) in any of the sources`
* ``Run `bundle install` to install missing gems.``
3. Once you are using the correct ruby version and correctly start the rails server, the following error will occur after you have logged in as either the user/moderator/admin. Any attempt to view a webpage **after** being directed to your dashboard will shut down your rails server -

plots2

* The server log displays - 
``/home/ec2-user/.rvm/gems/ruby-2.4.4/gems/redis-4.1.0/lib/redis/client.rb:353:in `rescue in establish_connection': Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)``

> What did you expect to see that you didn't?

Ideally, no errors during the installation. Practically, I would have liked to see the page regarding the link that I clicked after logging in.

### Please show us where to look

https://github.com/publiclab/plots2/blob/master/install_cloudnine.sh

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

Since this occurs in the development environment, the username is either of these three:
1. user
2. moderator
3. admin

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

browser

windows

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by nicoleiocana**
Fixes #6773 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [✔️ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [✔️ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [N/A ] screenshots/GIFs are attached 📎 in case of UI updation
* [N/A ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! Thanks so much! A lot of people are using Codenvy.io now instead of
cloud9. And we refactored this to ensure compatibility with that platform.
Just checking if your changes are still codenvy.io compatible, or if you
could check this? Thanks!

**Comment by nicoleiocana** [comment]
I'll check it. It would be best to rename the shell script file install_aws_cloudnine then have a separate install_codenvy file to allow users to utilize whichever IDE of their choosing. Also, the documentation would need to reflect this. If allowed, I'd also like to update that.

**Comment by jywarren** [comment]
that would be great, although if they could be unified, that would make
maintenance/updating easier. Thanks for your help!

**Comment by nicoleiocana** [comment]
I tried to create a new codenvy account to test the compatibility. The directions state that in order to have an codenvy account, I must first create an account on OpenShift. I did that. I am able to go to my OpenShift dashboard, yet those same credentials won't allow me to login to codenvy. Am I missing something?

codenvy

**Comment by jywarren** [comment]
Hmm, i guess Codenvy.io is getting converted into something else? https://che.eclipse.org/eclipse-che-7-is-now-available-40ae07120b38 https://che.openshift.io and Dec 8th everything will be moved there... i guess this isn't a stable business model since these services keep getting shifted!

What do you recommend we do? Is the Codenvy.io workflow still usable at all? Thank you!

**Comment by seabl** [comment]
Has anybody looked into Codeanywhere?

**Comment by jywarren** [comment]
Not I, is it recent?

**Comment by nicoleiocana** [comment]
> Hmm, i guess Codenvy.io is getting converted into something else? https://che.eclipse.org/eclipse-che-7-is-now-available-40ae07120b38 https://che.openshift.io and Dec 8th everything will be moved there... i guess this isn't a stable business model since these services keep getting shifted!
> 
> What do you recommend we do? Is the Codenvy.io workflow still usable at all? Thank you!

I believe that since Cloud9 had a huge user base, most of those same individuals transitioned to AWS Cloud9. I would still recommend my AWS C9 instructions; then, implement a different set of instructions for another cloud IDE **only if the directions were completely distinguishable.** Most users would be able to allude to the specific commands that only differ by one or two words.

**Pull request closed without merging**
