### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by CoderJolly**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] ask `@publiclab/reviewers` for help, in a comment below
* [ ] PR is descriptively titled

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by CoderJolly** [comment]
Raised PR #3922

**Comment by jywarren** [comment]
Great job here. Nice clean PR. I will close #3922 now!

**Comment by jywarren** [comment]
Oh oops, would you mind linking to the original issue and marking it complete too? Thank you!!

**Comment by CoderJolly** [comment]
Yeah Sure.....would love to help, bt I dont understand what you are trying to convey in the second part....I would be willing to do as u explain

**Comment by jywarren** [comment]
So just include the number of the issue which this was based on, with the # before it -- then it'll create a link between the two!

**Comment by CoderJolly** [comment]
Ooww, Not an issue...I will do this right away

**Comment by CoderJolly** [comment]
Raised PR #3922 for Issue #3920

**Comment by jywarren** [comment]
Perfect. You can actually (in future PRs) add the text `fixes #0000` but with the correct number in there, and when the PR is merged, the issue automatically closes! Magic! 🔮

**Comment by CoderJolly** [comment]
Would definitely do so in future, Thnks for the advice and help 😄

**Comment by jywarren** [comment]
thank you too!!!

**Pull request merged**
