### PR TITLE
Modify unit test to make sure token isn't nil

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

@jywarren I'm sorry I pushed to a branch on publiclab/plots2 instead of ryzokuken/plots2 by mistake.

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Locally, I get all the authlogic tests failing.

**Comment by ryzokuken** [comment]
@jywarren Perfect, the error is:

```
Failure: <nil> expected to not be nil.

test_user_creation(UserTest)

test/unit/user_test.rb:18:in `block in <class:UserTest>'
```

Now in order to make the tests pass, all we need to do is to make sure the token is set properly.

Maybe we could set the token inside `create_drupal_user` method?

**Comment by jywarren** [comment]
Actually could we do it outside that method since we may eventually deprecate that once we move away from `DrupalUsers` completely? Is there another `before_save` method or could we add a new one?

**Comment by ryzokuken** [comment]
@jywarren I will make it inside a function called `set_token` add it to to `:before_create`. We can also use this function to later implement a "Reset Token" feature if we would like.

**Comment by ryzokuken** [comment]
@jywarren It must be working perfectly I think, but because `User.create` isn't being invoked in this instance (it will be in the normal workflow), Our method inside `before_create` isn't being triggered. I would change it to `before_save` instead, and it should work. However, I think that might be counterproductive because then it would be called everytime the user is updated, making the token reset a side-effect of an update of data.

**Comment by ryzokuken** [comment]
@jywarren It worked. (YAY!)

Maybe we should implement the "Reset Token" functionality too so that all users with their tokens set to `nil` can use that to set it instead?

**Comment by jywarren** [comment]
I think you are right that before_save will cause a token reset on any update -- can you try another event like after_create or something? Why isn't before_create triggered? It should be in the users_controller create method. 

Alternatively you could have the create token only occur if the token is nil.

**Comment by jywarren** [comment]
Sorry for my slow response - I'm still not all caught up and am in meetings all day for this week. But if you can resolve this last issue I'll try to publish this tonight. Worst case I can generate you a token randomly.

**Comment by ryzokuken** [comment]
I think before_create isn't being called because we aren't calling the
create method in the first place, we are creating it manually by calling
User.new and user.save 😅

You're right, a good options seems to be to add a condition inside the
before_save method or to change the token right inside User.new. I will add
the condition for now, but will make appropriate changes if you request.

**Comment by jywarren** [comment]
Let's do the conditional; that keeps the logic inside the model.

**Comment by ryzokuken** [comment]
@jywarren Added the condition; Take a look.

**Comment by jywarren** [comment]
:-)

**Comment by jywarren** [comment]
Ok, published to the live site! Have fun! 🎈

**Comment by ryzokuken** [comment]
@jywarren should I delete the user and then remake one, or trigger the save
method by changing the bio or something instead?

**Comment by jywarren** [comment]
Change your bio! Good to know if that works.

**Pull request merged**
