### PR TITLE
Fix image upload in comments as well as preview

### LINKED ISSUE #5229: Comment image uploading not working
I think this may be related to the new reply-to-comment feature -- @ViditChitkara could you take a look at this one? I don't see any error message but I did see this warning:

```
Found 35 elements with non-unique id #comment-form: (More info: https://goo.gl/9p2vKq) 
```

Related? I was testing both dragging an image into the comment field (not a reply) and also clicking "choose an image" in the bottom bar of the comment field, and neither triggered any reaction. Thank you !!!

### PR DESCRIPTION
**Pull request by ViditChitkara**
Fixes #5229

### CODE REVIEW

**Comment by jywarren** [comment]
Oh awesome! Can you share a gif? Thanks Vidit!!!

**Comment by ViditChitkara** [comment]
I'll do, it's working fine with 'choose upload' button.
But, dragging and dropping an image causes it to be uploaded multiple times.

**Comment by ViditChitkara** [comment]
Here is a preview of the fixed bug
test

**Comment by jywarren** [comment]
Fantastic! Ready to merge?

**Comment by ViditChitkara** [comment]
Yes!

**Comment by gauravano** [comment]
Great work Vidit :100:

**Comment by ViditChitkara** [comment]
Thanks a lot Gaurav!

**Comment by jywarren** [comment]
:tada: :-)))

**Pull request merged**
