### PR TITLE
Add warning message re wildcard search

### LINKED ISSUE #2029: Contributors Page with Powertag searches
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem
Contributors page available at www.publiclab.org/contributors/tagname works fine when tagname is a normal tag like balloon but when it is a powertag having wildcard character asterisk, eg tagname is balloon* then it shows no contributors.
We supply tagname as balloon* to get all the tags starting by balloon eg balloon-mapping ,balloon etc in the url at Public Labs
### Solution
A message to indicate the users that for a wildcard search, contributors cannot be listed. So, requesting users to not enter wildcards.
Message like
> This is a *wildcard tag search*. 
>  Wildcard tag searches use the * asterisk in their URLs, and do not show contributor listings. 

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
Add  `` @wildcard = true if params[:id][-1..-1] == '*' `` in https://github.com/publiclab/plots2/blob/e606fc2da577aaab45cb83e96f7c3f56457c6f99/app/controllers/tag_controller.rb#L294
Also add the custom message in the if-else statement in the view. Make the ``if @wildcard`` as the first condition of the if-else loop in
https://github.com/publiclab/plots2/blob/e606fc2da577aaab45cb83e96f7c3f56457c6f99/app/views/tag/contributors.html.erb#L60-L62

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

### PR DESCRIPTION
**Pull request by ina-mastabba**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

Fixes #2029

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
**PLEASE NOTE:**
// pulled the latest original(plots2 repo) master into my local repo,
// rebased my feature branch on top of my local master,
// resolved conflicts indicated during the rebase,
// force pushed my local feature to my remote feature.
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, hi, @ina-mastabba -- it looks like you need to resolve some conflicts after other changes were merged and this has drifted from the master branch state. Do you need help with that? 

Thanks, this is looking good so far!

**Comment by ina-mastabba** [comment]
I think I understand and can resolve.  A few questions:

Are the conflicts on this pull request's "files changed" tab updated in real-time?  
What I mean is, I created the pull request 3 days ago, can I assume that this pull request has been updated with any conflicts that have resulted from merges to the original  master between then and now? 

Also, It's telling me that the changes are too complex to resolve in the github editor.  So I'm thinking I'll change them locally on my feature and make another commit.  Will this existing pull request point to that new commit or will I need to create another pull request?

Thank you for your help and patience with this.

**Comment by jywarren** [comment]
Hi, super -- the conflicts are calculated as the page is loaded, so they should be up to date. It can auto-resolve past smaller issues, so it doesn't need to be perfectly up to date, but it'll often show an issue if there are changes to the same file, for example. 

I think locally makes sense too. You should be able to rebase your work over the latest master and `git push -f origin add_warning_message_re_wildcard_search` to overwrite this PR's commits. Make sense? 

There is some guidance here that may help! https://publiclab.org/wiki/developers#Resources

**Comment by ina-mastabba** [comment]
So I 
switched to my local master,
pulled the latest original(plots2 repo) master into my local repo, 
rebased my feature branch on top of my local master,
resolved conflicts indicated during the rebase,
force pushed my local feature to my remote feature.
I _think_ I should be good to go.  Please let me know.  
Thanks again.

**Comment by ina-mastabba** [comment]
Hi, 
Just wondering if anything else needs to be done with this as it hasn't been merged yet?
-Thanks

**Comment by jywarren** [comment]
Hi, sorry, I was away for a few days and am just getting back to this now. Thanks so much for your contribution!

**Comment by ina-mastabba** [comment]
No problem.  Thanks for helping me to make my first contribution.

**Comment by jywarren** [comment]
OK! I've compacted your changes a bit to just be extra sure we've separated out the changes and I think this'll be good to go! Just be sure to base any new changes off of the latest master -- for some help and guides on this, see:

* https://publiclab.org/wiki/contributing-to-public-lab-software
* https://publiclab.org/wiki/developers

Thanks!!!

**Comment by jywarren** [comment]
I went ahead and merged this - looks great, and thank you! We'd be happy to have more help if you're interested. 👍 👍 🎉

**Comment by ina-mastabba** [comment]
Thanks. I will definitely help very soon.  It seems like a really interesting project.

**Pull request merged**
