### PR TITLE
Update tag_controller.rb

### LINKED ISSUE #8209: Replace .count and .length in the tag controller with .size
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file https://github.com/publiclab/plots2/blob/main/app/controllers/tag_controller.rb, replace the instances of `.count` and `.length` with `.size`

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by yusufatalay**
replaced the instances of .count and .length with .size

Fixes #8209

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by yusufatalay** [comment]
I've done my task.Thank you for giving me the oppurtunity to do this. can you rewiev the code and give some feedback to me ?.

**Comment by cesswairimu** [comment]
thanks so much @yusufatalay  for opening this :tada: could you please add the issue link to the issue this pull request fixes on your pull request on this line "Fixes issue_link" this will help other contributors while reviewing your changes. It also helps in automatically closing the issue when the pull request is merged. Thanks

**Comment by cesswairimu** [comment]
@yusufatalay please update the link to the issue you are solving. Thanks

**Comment by yusufatalay** [comment]
I am on it

**Comment by avats-dev** [comment]
> I am confused can you walk me through it ?

Hey @yusufatalay , thanks for your contribution and welcome to publiclab community. It's very important to link your PR to the issue that it intends to resolve, as this can:
- help others check if PR is any good for what it is intended.
- automatically close that issue when the PR is merged.
- help in better workflow of the codebase.

To link your PR to the issue, edit your comment (the first one, i.e. one with which you have opened this PR) and you'll see something like "**Fixes #0000 (<=== Add issue number here)**".  This is even the first line of your comment. You have to replace **0000** here with the issue number concerned with your PR, and leave everything else as it is. **Don't remove the # as it is crucial and creates the link in between.**

If you're still unsure and having problems, watch this as an example.
Peek 2020-08-22 23-58

**Review by avats-dev — CHANGES_REQUESTED** [review]
@yusufatalay , nice work. There're remaining instances of `.count` still in https://github.com/publiclab/plots2/blob/ce68627ccb452f2aed1f536fa6ad7fd01d31e57c/app/controllers/tag_controller.rb#L545-L565

and similarly I've seen that there are some remaining instances of `.length` also in code. 

**TIP:** Use `Ctrl+F` after you've done editing and search for `.count` and `.length` keywords to see if there're any.
**CAUTION:** There're chances that similar keywords are present like `counts` or even the `count` word in some variable or string. You should not edit them. I think these would be rare, if you search with the `.` in front.

Thanks, keep up the good work! 👍

**Comment by avats-dev** [comment]
Hey @yusufatalay , you've linked this PR with your PR, while you need to link the concerned issue to this PR. I checked and saw that the issue concerned with your PR is #8209. So, your comment should be like "**Fixes #8209**". 

Thanks, good work. 👍

**Comment by avats-dev** [comment]
Also, @cesswairimu , review this when you're free.

**Comment by yusufatalay** [comment]
Thank you for guiding me it really helps me improve myself. Those .counts must be added after I edit the code , if not please let me know.

**Comment by avats-dev** [comment]
Hey @yusufatalay , these instances are not added after you've edited the code as these are also present in your fork https://github.com/yusufatalay/plots2/blob/patch-1/app/controllers/tag_controller.rb. 

Now, you should checkout to your `patch-1` branch and edit the changes needed. After that just commit and push the changes to your branch, and this PR will get updated itself. 

Feel free to ping back if you're stuck or need any help. 👍

**Comment by yusufatalay** [comment]
I figure it out that on github ctrl+f won't work for whole code. So I copied it to a text editor then I've edited it there thank you for your help , I've learned alot from this.

**Comment by avats-dev** [comment]
> I figure it out that on github ctrl+f won't work for whole code. So I copied it to a text editor then I've edited it there thank you for your help , I've learned alot from this.

@yusufatalay it's good to hear that you learnt a lot. Could you push your changes so that we can review it? 
> You've to push changes on this branch, then only this PR would self update itself. 

Thanks :+1:

**Comment by avats-dev** [comment]
@yusufatalay close this PR as you've opened #8360 for the same issue. Thanks :+1:

**Review by avats-dev — APPROVED** [review]
Looks all good now @yusufatalay . :tada:  Thanks for the contribution.

@cesswairimu for review and merge!

**Comment by avats-dev** [comment]
@yusufatalay close #8360, as this PR is gonna solve the issue and would be merged hopefully! Thanks

**Comment by avats-dev** [comment]
@yusufatalay don't close this PR, this is good and it's working. Also tests have passed. Reopen this PR.

Close #8360, the new one that you've opened.

**Review by avats-dev — APPROVED** [review]
Looks all good to me :tada: 

@cesswairimu check this one and merge when you're free!

**Comment by yusufatalay** [comment]
Thank you for patiently teaching me.

**Comment by cesswairimu** [comment]
Really love the collaboration that has gone on here . Great job :tada:  :tada:

**Review by cesswairimu — APPROVED** [review]
:rocket:

**Comment by cesswairimu** [comment]
Welcome to the community @yusufatalay  :balloon:

**Comment by avats-dev** [comment]
Welcome to the community @yusufatalay :rocket: and thanks @cesswairimu :smile:

**Pull request merged**
