### PR TITLE
Fixes #4244 Input fields in Login Modal

### LINKED ISSUE #4244: Issues with Input Fields in Login Modal
Currently at a specific width, the Login Modal errors and the input fields stick out of the body.

issueswithwidth

I believe this is a CSS issue but I am not too familiar with it.
Perhaps looking into the code here  (plots2/app/views/user_sessions/_new.html.erb) will give some answers.
      
Chrome Ubuntu

### PR DESCRIPTION
**Pull request by IshaGupta18**
Fixes #4244 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by IshaGupta18** [comment]
I am unable to resolve this conflict, what should I do? @SidharthBansal

**Comment by SidharthBansal** [comment]
You can open up a new PR with your current changes.
or pulling changes will result in conflicts. You can resolve then at your
text editor.

**Comment by IshaGupta18** [comment]
I have incorporated the line that was causing the conflict in this pull request.

**Comment by SidharthBansal** [comment]
Which is the new PR upon which you are working?

**Comment by IshaGupta18** [comment]
I haven't created one as of now, I will create one and resolve the conflict here on github only. Will that be okay?

**Comment by SidharthBansal** [comment]
I think you have closed this. So please open it up.

**Comment by IshaGupta18** [comment]
I was thinking of creating a new one, but I'll reopen this if you want.

**Comment by IshaGupta18** [comment]
I think I have resolved the conflict now, is it okay?

**Comment by IshaGupta18** [comment]
Hey @SidharthBansal is it okay now? I didn't about the warning, otherwise I wouldn't have merged from master, but I hope it won't create much problem will it?

**Comment by SidharthBansal** [comment]
Ignore the warning.

**Comment by SidharthBansal** [comment]
Looks good. Can you please check the behaviour again after you have merged the changes and post a new gif?

Thanks

**Comment by IshaGupta18** [comment]
inputfieldsnew

Does this look good? Thank you!

**Comment by gauravano** [comment]
Merged :tada: :balloon:

**Comment by SidharthBansal** [comment]
Awesome folks

**Pull request merged**
