### PR TITLE
[WIP] : Add featured questions for shadow questions page

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5733

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! Can you share a screenshot? Exciting!!!!!

**Comment by jywarren** [comment]
And @gautamig54 can you offer a review? Thanks a lot both of you!

**Comment by CleverFool77** [comment]
Hi @jywarren The work is still in progress. I'll do upload the Screenshot as soon as it's done.
Thanks !!

**Comment by CleverFool77** [comment]
opened a new PR. Closing this one.
Thanks !

**Pull request closed without merging**
