### PR TITLE
Corrected position of Deep links load content

### LINKED ISSUE #2093: Deep links load content hidden underneath our menu bar and ribbon
### Please describe the problem (or idea)

> What happened just before the problem occurred?

I clicked the timestamp to a particular comment i needed to link to, and it created this URL that loaded the content so high that it was completely hidden under the menu bar or the ribbon. Luckily, I knew what i was expecting to see , so i knew to scroll up to find it, but someone who doesn't know what to expect when clicking the link could get completely confused because of this. 

> What did you expect to see that you didn't?

I expected to see the top of the content i linked to. 

### Please show us where to look

https://publiclab.org/questions/warren/11-14-2017/what-s-one-thing-that-could-be-better-for-newcomers-about-the-public-lab-website#answer-0-comment-17687

Here's an example matching the screenshot below: https://publiclab.org/wiki/public-comment#What+is+Public+Comment?

screenshot 2018-01-24 at 1 16 13 pm

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Closes #2093 
* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
ezgif com-video-to-gif 2

**Comment by jywarren** [comment]
Aha, this is cool -- but I want to note that people may arrive at this URL also by simply clicking on a URL like this one --

https://publiclab.org/questions/asnow/01-23-2018/prefered-slit-size#a733

See how the `#a733` leads directly to the answer? So it's not as much about animating on a click, as making sure the page scrolls down. Do you think this could also be triggered on pageload, so as to ensure this loads then too? 

Thanks for the animation, it really helps here!

**Comment by SidharthBansal** [comment]
Hi @jywarren  #2512 is merged now and #2093 is closed so can we close this also??

**Comment by patcon** [comment]
Whoa! Hey @namangupta01, I was the one who submitted that other PR without seeing yours (sorry for not collaborating!), but I just wanted to say that your GIF tactic is really inspiring. I'm going to try to do that more :)

**Comment by namangupta01** [comment]
Haha!

**Pull request closed without merging**
