### PR TITLE
Tag page bugfix and pagination fixes

### PR DESCRIPTION
**Pull request by SidharthBansal**
A few more pagination changes and a change that has reversed the previous pr.

### CODE REVIEW

**Comment by SidharthBansal** [comment]
There were a few places which have .page(params) that I forget to fix in the "pagination improved "pull request. At that time, I only changed the .paginate() ones. Today found the other ones so changed them.
I have checked each URL which has the paginate thing. The ones which have the list view only, that I have not changed.
Also the commit which you pulled yesterday, I accidentally, deleted the version for disabling the author section when there are wildcard searches, so I have fixed that.
I have removed the file.

**Comment by jywarren** [comment]
Ok super. Tell me when this is ready, then! Thanks!

On Jan 13, 2018 11:25 AM, "Sidharth Bansal" <notifications@github.com>
wrote:

There were a few places which have .page(params) that I forget to fix in
the "pagination improved "pull request. At that time, I only changed the
.paginate() ones. Today found the other ones so changed them.
I have checked each URL which has the paginate thing. The ones which have
the list view only, that I have not changed.
Also the commit which you pulled yesterday, I accidentally, deleted the
version for disabling the author section when there are wildcard searches,
so I have fixed that.
I have removed the file.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/pull/1995#issuecomment-357447471>, or mute
the thread

**Comment by SidharthBansal** [comment]
This is ready

**Comment by SidharthBansal** [comment]
@jywarren It is ready

**Comment by SidharthBansal** [comment]
@fastie told about a bug. I shall push in the changes here soon. It is again in progress

**Comment by SidharthBansal** [comment]
@jwarren I have fixed the bug.

**Comment by jywarren** [comment]
:-) great. Next time maybe title `Tag page bugfix and pagination fixes` -- i'm changing this now just so it shows up in a list of PRs for easy skimming. Thanks!

**Comment by SidharthBansal** [comment]
Thanks, I will improve on giving titles

**Pull request merged**
