### PR TITLE
Tags added by banned users are not displayed

### PR DESCRIPTION
**Pull request by Manasa2850**
Part of #9694

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
@jywarren currently I'm not displaying the tags added by the banned users but they still exist in the database. I've done this because if the admin bans a user by mistake, un-banning them will bring back their tags on the notes page.
Is deleting the tags from the database a better option? Please let me know your views on this. 
Thanks!

**Comment by RuthNjeri** [comment]
Hi @Manasa2850, thanks for working on this, maybe you could create a dedicated issue for this? If this PR is merged, it will closed the main issue that you are using to plan your work. You could create another one, similar to #9709

**Review by RuthNjeri — APPROVED** [review]
Looks good to me, great work @Manasa2850

**Comment by jywarren** [comment]
Not deleting from the DB sounds great! Thanks for watching for a
destructive step.

**Review by pydevsg — APPROVED** [review]
Good work @Manasa2850 🎉

**Comment by jywarren** [comment]
Great work everyone, and especially @Manasa2850!!

**Pull request merged**
