### PR TITLE
Welcome notification on dashboard made persistent

### LINKED ISSUE #3673: Signed In notification doesn't fade away automatically
### Please describe the problem (or idea)
After signing in to `publiclab.org`, an alert box appears telling that you're successfully Signed in, but it stays there unless you manually remove it (by clicking on the cross in alert box) or the page gets reloaded. That's not the kind of information that should be persistent in UI.

> What happened just before the problem occurred? Or what problem could this idea solve?

screenshot from 2018-10-11 15-58-57

### Please show us where to look

https://publiclab.org/

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by champagnepappi**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

Before 

fadehello

After

signed-in

### CODE REVIEW

**Comment by champagnepappi** [comment]
@Rishabh570 yes it does. maybe leme change the title. 
About my changes,all the alert boxes have the alert-success class meaning even the "Hello welcome to Public Lab" also fades away. But to fix it I had to change it's class to alert-info.

Meaning the JS script now works for  signed-up notification which has alert-success class

**Comment by Rishabh570** [comment]
> all the alert boxes have the alert-success class meaning even the "Hello welcome to Public Lab" also fades away. But to fix it I had to change it's class to alert-info.

Sorry but I don't understand this, do you mean that *alert-success* class is responsible for *fade-out* nature of alert notifications...? If this is the case, then why would you change that to *alert-info*? Can you please explain?
Thanks!

@champagnepappi Sorry for the late reply :)

**Comment by champagnepappi** [comment]
@Rishabh570  To fade out the notifications you have to target the classes in which the notifications are wrapped in. In our case the the notifications have a general 'alert' class incase we wanted to style all the notifications and custom classes derived from the flash itself. 

For example a _flash[:notice]_ will have the _'alert-notice'_ class and _flash[:success]_ will have _alert-success_ class.
In our case the two notifications you see in the GIF above  have alert-success meaning they both fade away. To fix it we have to change the notification class so that it doesn't fade away.

**N/B**  Seems this issue was created when before [THIS PR](https://github.com/publiclab/plots2/pull/3662) was merged. With this PR, all notifications with alert-success class e.g logout, sign-up are fading away including the notification below the signup notification("Hello welcome to Public Lab")

**Comment by Rishabh570** [comment]
@champagnepappi Yes, that PR seems to have an effect on every notification. Okay, so you've changed the class of "Hello, welcome to publiclab..." to make it persistent in the UI...Great!
But as this PR was about #3673, is that issue resolved by these changes? If not, please remove `Fixes #3673` from your PR description in order let that issue remain open.

Thanks!! :+1:

**Comment by champagnepappi** [comment]
@Rishabh570 yes, #3673 is resolved by [this PR.](https://github.com/publiclab/plots2/pull/3662).
This PR though fixes the "Hello, welcome to publiclab..." notification fading away. 

Maybe you can create an issue on the "Hello, welcome to publiclab..." notification fading away. And the fix to that would be this PR

**Comment by Rishabh570** [comment]
@champagnepappi I think there's no need for a separate issue just for this, maybe you can just make the commit message more precise i.e., tell in the message what this commit is about.
That would suffice I think :)

But remove `Fixes #3673` part from your description as it will close that issue also. I'll manually close that issue with a link to that PR.

**Comment by Rishabh570** [comment]
As there is no issue for this PR, your commit message should be self-explanatory enough so that anyone could understand its purpose just by reading it :)
I think "Welcome notification on dashboard made persistent" would do the job...

Everything is good, just change the commit message and this PR is good to go :+1:

**Comment by champagnepappi** [comment]
@Rishabh570 I've changed the commit message

**Comment by SidharthBansal** [comment]
@jywarren I think we should close this as @champagnepappi is inactive since a long time and I don't think it is a correct way to do things.

**Comment by jywarren** [comment]
ok!

**Pull request closed without merging**
