### PR TITLE
Make sure invalid date tags aren't added (fixes #1209)

### LINKED ISSUE #1209: BUG: "event" posts don't generate correct power tags
### What happened just before the problem occurred

I posted an event https://publiclab.org/notes/liz/01-20-2017/edgi-foia-event-at-cuny-in-new-york-city-online#comments but it showed up as a regular post, not as an event with the RSVP feature. 

While composing this post, i choose "post an event" from the dropdown, however, the published event did not include the powertags "event:rsvp" and "date:YYYY-MM-DD". I had to look up what those tags were on https://publiclab.org/wiki/power-tags#Automated+power+tags,+not+for+manual+adding and add them myself with the actual date.

### Relevant URLs

See above! Thanks :)

### PublicLab.org username

liz
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Please look into this one whenever possible.

**Comment by ryzokuken** [comment]
@jywarren *PING*

**Comment by jywarren** [comment]
Awesome, merging now.

**Comment by jywarren** [comment]
Thank you, @ryzokuken !!! 🎈

**Pull request merged**
