### PR TITLE
Sidebar items del

### PR DESCRIPTION
**Pull request by nataliyah123**
@jywarren

### CODE REVIEW

**Comment by nataliyah123** [comment]
@gauravano .why am i getting the conflicting files issues . i deleted that branch .so why now

**Comment by Gauravano** [comment]
Hi @nataliyah123 it looks you have merged the previous commit in your master branch, that's why your new branch is also carrying the changes. You can follow this link for rewinding your master branch https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch . Thanks!

**Comment by nataliyah123** [comment]
the issue is already dealt with in #3142

**Comment by Gauravano** [comment]
Great! @nataliyah123 if you interested, you can help us with #3159 . Thanks!

**Pull request closed without merging**
