### PR TITLE
camelCase textbox_expand.js filename

### PR DESCRIPTION
**Pull request by Nagsenwaghmare**
I worked on Issue #9152

### CODE REVIEW

**Comment by noi5e** [comment]
@Nagsenwaghmare Thanks for making this PR!

A few things:
1. Make a comment in issue #9152 just so that people know that you are working on this.
2. It looks like the system tests are failing. The other fixes look good, but it looks like you need to actually rename the file textbox_expand.js to textBoxExpand.js. Can you make this change, and put it in another commit.
3. Edit your pull request comment, and make sure to put the issue number, 9152, where "Fixes #0000" is here:

Screen Shot 2021-02-07 at 12 33 19 PM

That way GitHub knows that your PR is linked to this issue :)

Please reach out if you have any questions about this!

**Review by gauravahlawat81 — CHANGES_REQUESTED** [review]
I think `textboxExpand` name will make more sense than `textBoxExpand`. What do you think @Nagsenwaghmare ?

**Comment by noi5e** [comment]
@gauravahlawat81 @Nagsenwaghmare Either should be fine! @Nagsenwaghmare was just following the prompt that I left in the original issue write-up. 

It looks like this is ready to merge! Great job!!! 🥳

**Review by gauravahlawat81 — APPROVED** [review]

**Comment by Nagsenwaghmare** [comment]
I think all checks have passed is it ready to merge ?
Thanks !

**Review by Sagarpreet — APPROVED** [review]
Nice 🎉

**Comment by cesswairimu** [comment]
Thanks everyone :tada: :tada: , merging now :rocket:

**Pull request merged**
