### PR TITLE
Style "Add your location" button on /people/ #6899

### LINKED ISSUE #6899: Style "Add your location" button on /people/
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [list.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/list.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

On https://publiclab.org/people the "Add your location" button looks like this:
FireShot Capture 091 - 🎈 Public Lab_ List - localhost

It should be styled like the style guide specifies:
69657369-138e3d00-1048-11ea-9180-de0ac3659d48

To change the icon color change this line:
https://github.com/publiclab/plots2/blob/dd06555246fd8ef17ead4037f13af3e68c65fc1e/app/views/users/list.html.erb#L13

to this:
``` <a class="btn btn-outline-secondary blurred-location-input" style="color:#666;" onmouseover="this.style.background='white';" submit_to="/profile/tags/create/<%= current_user.uid %>"><i class="fa fa-map-marker" style="color:#c40;"></i> Add your location</a>```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by mikepetridisz**
Changed icon color in plots2/app/views/users/list.html.erb
Fixes #6899

### CODE REVIEW

**Comment by mikepetridisz** [comment]
@jywarren is the PR failure related to Stalebot preventing Jenkins build?

**Comment by jywarren** [comment]
I don't think so, Travis has been running fine. It's just Jenkins!

**Comment by mikepetridisz** [comment]
Should I close this one? Maybe give it another shot to see if it goes through?

**Comment by jywarren** [comment]
Let's read the error text - see what is failing! i bet we can fix it.

**Comment by mikepetridisz** [comment]
I've checked the log: 

[0m[1000D[K[31m FAIL[0m["test_graph", #<Minitest::Reporters::Suite:0x00005600ffd542a0 @name="TagSelectionTest">, 0.2436444120000374]
 test_graph#TagSelectionTest (0.24s)
        Expected: 16
          Actual: 21
        **test/unit/tag_selection_test.rb:12:in `block in <class:TagSelectionTest>'**

warnings:
- already initialized constant TagNodeAssociationExtension
- the previous definition of TagNodeAssociationExtension was here ( #2365 )

**Comment by mikepetridisz** [comment]
Resolved! 👍

**Comment by jywarren** [comment]
Hooray! I guess it wasn't related! I had just restarted it one more time.

**Comment by jywarren** [comment]
Great work!

**Pull request merged**
