### PR TITLE
(don't merge yet) Removal of email/username field for MK & SWB

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes https://github.com/publiclab/mapknitter/issues/576
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@jywarren kindly review and merge this. I have removed the username and the related redundant tests too.
Thanks

**Comment by jywarren** [comment]
So this looks amazing, but I can't quite follow how you did it! After racking my brain i thought we have to have username to initiate the openid request from MapKnitter. Does this bounce back and forth, or how do we know what openid request to initiate once we're logged in on PL.org? Thank you!

**Comment by SidharthBansal** [comment]
@jywarren You are correct. We do require username for the openid to work Without username openid will not work. This was the main problem which I faced since 3 weeks.

What I did?
Answer: I passed the user X always to the openid_url and made session from the hash returned from the openid hash.
So, our purpose is solved. It is not the best solution but solution is working.

**Comment by jywarren** [comment]
Oh whoa, so, but, what are the drawbacks here? Is this not true OpenID, because we are authenticating user X instead of the actual user?

**Comment by SidharthBansal** [comment]
At the MK we are trying to authenticate user X but we logged in user Y at PL and get hash for user Y. We created the account/logged in for account Y at MK.
As in the frontend nobody sees user x, nor at database level user x has no role, so we never require to authenticate user X.

**Comment by jywarren** [comment]
Wait, so we generate an OpenID request for User "x" (literally that username, not just a variable), but PL responds with a session for the real username?

**Comment by SidharthBansal** [comment]
It is similar to the OAuth, we sign up at provider FB, get logged into Plots with same user as FB
We don't require anything for authentication of user X and user Y
In mk, we sign up at Plots, get logged in the MK.

So, both models are analogous to me.

**Comment by jywarren** [comment]
Sorry, can you walk through this step by step? I want to be sure I understand clearly! Thank you!

**Comment by SidharthBansal** [comment]
We initiated requested for username = 'x' from the pl but user y created a session at pl.
Openid returns hash of username, name, status, role etc at MK.
I took username from the hash and created a session. openid does not return sessions. It just returns the hash of values like OAuth does.

**Comment by jywarren** [comment]
ok, and MK is OK with receiving a hash of values with a username that
doesn't match the one it requested? Does it even know that the request
didn't originate from MK, but was generated by PL?

Thank you!

**Comment by SidharthBansal** [comment]
> MK is OK with receiving a hash of values with a username that
doesn't match the one it requested?

Yes

**Comment by SidharthBansal** [comment]
>Does it even know that the request
didn't originate from MK, but was generated by PL?

https://github.com/publiclab/mapknitter/blob/2ee9eb7b8d1b90bfb8f9e4a10ce23c8389d9ee6d/app/controllers/sessions_controller.rb#L24
and https://github.com/publiclab/mapknitter/blob/2ee9eb7b8d1b90bfb8f9e4a10ce23c8389d9ee6d/app/controllers/sessions_controller.rb#L7
indicates that MK accepts only requests from Publiclab.org

The request for login was generated from the MK but the user is logged in from the hash returned from plots2.

**Comment by jywarren** [comment]
OK - do we need to confirm this with a test in https://github.com/publiclab/mapknitter/pull/575 or can you highlight where we can confirm that MK will accept the corrected username, in a test? Just wondering. This is also not critical as we said, just trying to provide good documentation as it's a bit of a customization. Thank you!

**Comment by SidharthBansal** [comment]
> Sorry, can you walk through this step by step? I want to be sure I understand clearly! 

Client: Person who is using the application and does not know any computing language, web and database stuff.
Developer: Person who knows database, web and all the stuff going on.

Let's talk this in detail to remove all sort of ambiguities.

Client point of view is as follows:
Let provider can be {"login", "github", "fb","twitter"or"google"} button
Step 1: User clicks on any provider
Step 2: User validates the form provider by provider with username "sidharth" and password "ilovecompetitiveprogramming"
Step 3: User logs into the MK successfully with the session created with the username "sidharth"

Does client point of view makes sense Jeff?
Then we will move to the developers point of view?

**Comment by SidharthBansal** [comment]
> can you highlight where we can confirm that MK will accept the corrected username

`registration['nickname'] ` is the username received from the plots2.

**Comment by SidharthBansal** [comment]
For the developer's point of view:
1.Developer wants to create a user with username = "x". (not viewable in frontend)
2. Developer clicks on any of the provider button.
3. Developer logs into the plots2 with username = "bansal_sidharth2996" and password = "abrakadabra"
4. Developer receives hash named registration as `{nickname: bansal_sidharth2996, status = "normal " .....}`
5. MK creates a user session with the username as registration[nickname]
6. Developer sees the user with username = bansal_sidharth2996 is logged in at MK website.

**Comment by SidharthBansal** [comment]
Please don't merge this.

**Comment by SidharthBansal** [comment]
This pr can be merged after similar pr to https://github.com/publiclab/mapknitter/pull/575 in SWB is merged. This pr at plots2 just removed the redundant code.

**Comment by SidharthBansal** [comment]
> just trying to provide good documentation as it's a bit of a customization. 
thanks for pushing the documentation at MK

**Comment by SidharthBansal** [comment]
This plots2 pr is pushed to the unstable branch for testing.
@jywarren please tell where shall I push the MK branch for testing? 
I am new to mapknitter branches.

**Comment by SidharthBansal** [comment]
image

**Comment by jywarren** [comment]
Ah, i think that's an @icarito question on pushing to stable/unstable MapKnitter servers. Thanks!

OK, I get this, I think. Can you add, for each step above, what domain name we're at, like: 

1. _______ (mapknitter.org)
2. ________ (publiclab.org)

That'd really help provide extra clarification for me. Thanks again!

**Comment by SidharthBansal** [comment]
Unstable.publiclab.org
I don't know for mapknitter. Sorry

**Comment by jywarren** [comment]
Sorry, i meant for your step-by-step explanations -- so I know like:

1.Developer wants to create a user with username = "x". (not viewable in frontend) (mapknitter)

...

4. Developer receives hash named registration as {nickname: bansal_sidharth2996, status = "normal " .....} (mapknitter.org)

Thanks!

**Comment by SidharthBansal** [comment]
For the developer's point of view:
1.Developer wants to create a user with username = "x". (not viewable in frontend) 
2. Developer clicks on any of the provider button.(mapknitter.org)
3. Developer logs into the plots2 with username = "bansal_sidharth2996" and password = "abrakadabra"(publiclab.org/github.com/facebook.com/twitter.com/google.com)
4. Developer receives hash named registration as {nickname: bansal_sidharth2996, status = "normal " .....}(not shown in frontend)
5. MK creates a user session with the username as registration[nickname] (not shown in frontend)
6. Developer sees the user with username = bansal_sidharth2996 is logged in at MK website.(mapknitter.org)

Does it makes sense?

**Comment by jywarren** [comment]
yes, ok! Thank you!

**Comment by SidharthBansal** [comment]
Cool

**Comment by SidharthBansal** [comment]
How we shall push the mapknitter?
We need to push them to stable or unstable branch?

**Comment by SidharthBansal** [comment]
@jywarren the core dump will help you to better understand it. I created a new account to help you understand the sequence
image

**Comment by SidharthBansal** [comment]
IMPORTANT Sequence of workflow:
Step 1: Review and merge https://github.com/publiclab/spectral-workbench/pull/454
Step 2: Review and merge the following prs SIMULTANEOUSLY (after checking them on any branch stable/unstable/local.... I will prefer you to do it on your local so that we can be quick) 
https://github.com/publiclab/spectral-workbench/pull/450
https://github.com/publiclab/plots2/pull/5640 and https://github.com/publiclab/mapknitter/pull/575
https://github.com/publiclab/mapknitter/pull/575
These three prs are dependent. They can't be made independent.
Step 3: Deploy the changes for MK, SWB and Plots2 on the production SIMULTANEOUSLY.
Step 4: Check the functionality at the production level.
Thanks Jeff

**Comment by jywarren** [comment]
Great, i've just made checkboxes for this. Thanks, Sidharth! Finding the right moment to publish all of these together is going to take coordination. Is it possible to wait on this for some days, until the moment is right, to begin the checklist?

**Comment by jywarren** [comment]
And, at which steps may we stop the process? Like, could we do Step 1, wait a few days, then Step 2, or does this whole set need to be done at once? Thanks!

**Comment by jywarren** [comment]
Re MapKnitter, you should be able to push to unstable, check at https://jenkins.laboratoriopublico.org

then see it publish at http://mapknitter-unstable.laboratoriopublico.org

**Comment by SidharthBansal** [comment]
I have pushed the changes to unstable mk
We need to set step 2 to last in single shot.
Thanks

**Comment by SidharthBansal** [comment]
@jywarren it will be great if you can change https://github.com/publiclab/spectral-workbench/blob/9f9ca3cf759678e00b3283054cdf78d51d364d43/app/controllers/sessions_controller.rb#L5 and https://github.com/publiclab/mapknitter/blob/ccd6317f7752dc5c86259c40d4854cee423bfe85/app/controllers/sessions_controller.rb#L7 to localhost:3000/people at YOUR LOCAL BRANCH and test the system instead of unstable branch pushing and checking.

I am asking you to run mapknitter at localhost:3002, plots2 at localhost:3000 and swb at localhost:3004 instead of unstable branches as there is some routing constraint which routes openid request at unstable.publiclab.org to publiclab.org and we are not able to test our system at unstable branch.

Changes are pushed to the unstable branches of MK, SWB and plots2.
You can check the functionality whenever you get some time. Thanks

**Comment by jywarren** [comment]
Uh oh, what did I break?

**Comment by SidharthBansal** [comment]
I have restarted the build as the following is breaking
image

**Comment by jywarren** [comment]
Ah yes, i extended the wait time on that in the master branch. thanks.

**Pull request merged**
