### PR TITLE
[testing][WIP] Add tests for pages with bad date formatting (fixes #1209)

### LINKED ISSUE #1209: BUG: "event" posts don't generate correct power tags
### What happened just before the problem occurred

I posted an event https://publiclab.org/notes/liz/01-20-2017/edgi-foia-event-at-cuny-in-new-york-city-online#comments but it showed up as a regular post, not as an event with the RSVP feature. 

While composing this post, i choose "post an event" from the dropdown, however, the published event did not include the powertags "event:rsvp" and "date:YYYY-MM-DD". I had to look up what those tags were on https://publiclab.org/wiki/power-tags#Automated+power+tags,+not+for+manual+adding and add them myself with the actual date.

### Relevant URLs

See above! Thanks :)

### PublicLab.org username

liz
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Finally did get it to pass. Look into the code whenever possible.

**Comment by jywarren** [comment]
Hmm, passing? In theory the tag should be in format: `date:01-06-2017` ([from here](https://publiclab.org/notes/neilh20/01-06-2017/envirodiy-workshop-jan-26-27-2017))

So i'm not sure why `date:bad` wouldn't trigger a problem. 

`DateTime.strptime(node.power_tag('date'),'%m- %d-%Y').to_date.to_s(:long)`

should fail it, i'd think? Error was:

`ActionView::Template::Error (invalid date):`

Hmm. In the Rails console, does this fail:

```ruby
DateTime.strptime('bad','%m- %d-%Y').to_date
```

**Comment by jywarren** [comment]
That is, it's **supposed** to fail, as we're (at this point) trying to reproduce the error before we fix it.

**Comment by ryzokuken** [comment]
Yeah, it's surprising that it didn't. Will try it on the console.

**Comment by ryzokuken** [comment]
@jywarren Rails console working as expected:

```
2.1.2 :002 > DateTime.strptime('bad', '%m-%d-%Y').to_date
ArgumentError: invalid date
	from (irb):2:in `strptime'
	from (irb):2
	from /home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/commands/console.rb:47:in `start'
	from /home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/commands/console.rb:8:in `start'
	from /home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/railties-3.2.22.4/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by jywarren** [comment]
hmmmm. is it possible the node already has a "date" tag that /does/ work,
and is only fetching the first one?

**Comment by ryzokuken** [comment]
@jywarren I'll try making a new node... Is that possible? How should I achieve that?

**Comment by jywarren** [comment]
take a look at examples in the wiki controller, higher up. Or -- you could
test that node.power_tag('date') == "bad" to ensure it's actually getting
that string

**Comment by ryzokuken** [comment]
@jywarren Couldn't find an example for creating a new wiki page, added an assertion for the time-being.

**Comment by ryzokuken** [comment]
@jywarren It passed with both assertions in place. This means that it does not throw an error even though the power_tag is infact set to `'bad'`. Will look more into this tomorrow morning, feel free to leave notes.

**Comment by jywarren** [comment]
We could also assert the output of:

```ruby
assert_equal "some expectation", DateTime.strptime(node.power_tag('date'),'%m- %d-%Y').to_date.to_s(:long)
```

**Comment by ryzokuken** [comment]
@jywarren Strange that I cannot migrate locally:

```
==  NodePageviews: migrating ==================================================
-- add_column(:node, :legacy_views, :integer, {:default=>0})
   -> 0.0037s
-- add_column(:node, :views, :integer, {:default=>0})
   -> 0.0006s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant NodePageviews::DrupalNodeCounter/home/ryzokuken/code/plots2/db/migrate/20170111153001_node_pageviews.rb:5:in `up'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:410:in `block in migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:389:in `migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:528:in `migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:775:in `call'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/transactions.rb:208:in `transaction'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:775:in `ddl_transaction'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:719:in `block in migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:700:in `each'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:700:in `migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:570:in `up'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:551:in `migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
NameError: uninitialized constant NodePageviews::DrupalNodeCounter
/home/ryzokuken/code/plots2/db/migrate/20170111153001_node_pageviews.rb:5:in `up'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:410:in `block in migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:389:in `migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:528:in `migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:775:in `call'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/transactions.rb:208:in `transaction'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:775:in `ddl_transaction'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:719:in `block in migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:700:in `each'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:700:in `migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:570:in `up'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/migration.rb:551:in `migrate'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.4/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/home/ryzokuken/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by ryzokuken** [comment]
@jywarren Here it is!

```
Error: test_Pages_with_invalid_date_formatting_still_render(WikiControllerTest): ArgumentError: invalid date
test/functional/wiki_controller_test.rb:493:in `strptime'
test/functional/wiki_controller_test.rb:493:in `block in <class:WikiControllerTest>'
```

I suppose the other test was not working as expected because the error page was being rendered, and the test only checked if the request returned 200?

**Comment by jywarren** [comment]
oh great, yes! I think you can then add a check if it's a valid date... not
sure how that's done but it's probably not too hard.

did you get past that migration? I had some trouble with that too, not sure
why exactly

**Comment by ryzokuken** [comment]
@jywarren No, I cannot seem to get past that migration :disappointed:. I will try to write a validation that avoid invalid dates to be evaluated.

**Comment by jywarren** [comment]
Are you rebased on the latest master? I dropped a table in the most recent one, and you may be going out of sync because you're in a feature branch, no?

**Comment by ryzokuken** [comment]
@jywarren Tried everything possible with no luck at all. Here's what goes wrong: `NameError: uninitialized constant NodePageviews::DrupalNodeCounter`

**Comment by jywarren** [comment]
Hey, I think it may make sense to clear your database or backup and delete your database and schema files and start fresh... Clearly it is in a state where you've either run the migration to drop DrupalNode cunter, or you have the schema reflecting that, while /db/migrate/20170111153001_node_pageviews.rb still hasn't run. 

I think one possibility is that you need to run that migration and have that schema.rb state before actually git pulling the next migration and schema ... You can't do them in one go, and need two separate rake db: migrate commands. 

But just the same it may be easier to just get the latest database state and use the initial install instructions to constitute a new database without having to rake db: migrate through each one.

**Comment by ryzokuken** [comment]
@jywarren Got it to run.

**Comment by ryzokuken** [comment]
@jywarren It now throws this while testing, though: 

```
Failure:
  <"Error: only the author may use that powertag."> expected but was
  <"Error: cannot find that username.">.
test_won't_add_disallowed_tags(TagControllerTest)
test/functional/tag_controller_test.rb:66:in `block in <class:TagControllerTest>'
```

**Comment by jywarren** [comment]
Can you push a commit? I think you need to be sure you're using
add_tag(tagname, username) with a valid user who's the same as the node
author.

**Comment by ryzokuken** [comment]
@jywarren Should we really use a regex to do this? Most people on stackoverflow feel that we should rather handle the exception and that'd be more graceful.

**Comment by jywarren** [comment]
Sure, we could do both -- would you handle it on the create action of the
tag controller? We have a UI already to return errors, like the one
demanding the user be the author in order to make the tag.

Also - how did you solve the issue? Others may encounter the same.

**Comment by ryzokuken** [comment]
I deleted the following:
`config/database.yml`, `db/schema.rb`, '*.sqlite' 

and then ran `rake db:setup`

**Comment by ryzokuken** [comment]
The test fails on publiclab/plots2/master (strange?)

**Comment by jywarren** [comment]
That is odd. Are you sure your commit hash matches the most recent one on publiclab/plots2#master? 

It would imply that the fixture for the user "bob" doesn't exist - you could try to confirm that.

Can you push up a new commit with your own changes, rebased? I think that even if we do set a validation on record creation to catch bad dates, we should also screen them on display. If you handle the exception at display time (as opposed to at record creation time), that's fine as long as it doesn't stop page rendering!

Thanks, @ryzokuken!

**Comment by ryzokuken** [comment]
@jywarren merged upstream/master again, it failed again. Maybe resetting the db did something bad. I tried running `rake db:migrate` again, let's see.

**Comment by ryzokuken** [comment]
UPDATE: doesn't work.

**Comment by jywarren** [comment]
Hmm, well hey, you can just re-install the whole local copy and pull down the PR commit from here -- 

```
git checkout -b ryzokuken-fix/1209 master
git pull https://github.com/ryzokuken/plots2.git fix/1209
```

**Comment by jywarren** [comment]
Still stuck? Sorry, this sounds like a pain!

**Comment by ryzokuken** [comment]
@jywarren Sorry, this has been a hectic week as I have been relocating. Will try recloning this ASAP. Thanks for your patience.

**Comment by jywarren** [comment]
No worries and good luck relocating - just checking in to be sure you're
all right!

**Comment by ryzokuken** [comment]
@jywarren :(

Reset everything, still this happens.

```
Failure:
  <"Error: only the author may use that powertag."> expected but was
  <"Error: cannot find that username.">.
test_won't_add_disallowed_tags(TagControllerTest)
test/functional/tag_controller_test.rb:66:in `block in <class:TagControllerTest>'
```

**Comment by jywarren** [comment]
But we don't see that in the latest commit on this branch, right? Can you
push up a new commit and we can look at exactly what's changed and how the
Travis tests respond?

I'm sure we'll solve this!

**Comment by ryzokuken** [comment]
rebased to publiclab#master and ran `git clean`. Regenerating DB now.

**Comment by ryzokuken** [comment]
@nope, still not working properly. Could you try running `git clean -xdf` (if you don't have important data in your local DB) and then trying setting it up all over again? Maybe because you don't generate the DB over and over again, yours might have data mine is not getting. If its something wrong with the current DB generating code, then every new contributor will face this problem again. This probably arose in my case because I keep changing my distribution regularly.

**Comment by jywarren** [comment]
But Travis does this from scratch each time -- so that's why I'm suggesting
you push up a commit to see what it does. It'll also help me understand the
problem because I'll be able to see the full output.

**Comment by ryzokuken** [comment]
@jywarren wew, i am so stupid :stuck_out_tongue:  did get it work finally, and the reason is so obvious.
screenshot from 2017-01-31 23-55-26
someone has obviously changed `bob`'s username to `Bob`, thus making the test fail. Changing

```
post :create,
         name: 'with:bob',
         nid: node(:one).nid # authored by jeff, not bob
```
to
```
post :create,
         name: 'with:Bob',
         nid: node(:one).nid # authored by jeff, not bob
```

made all tests pass for me. It's time for me to go to bed, but I'll try my best to leave a PR so that you can look into it.

**Comment by ryzokuken** [comment]
@jywarren Rebased this on top of my fix-db branch.

**Comment by ryzokuken** [comment]
```
Failure:
  Expected at least 1 element matching "table", found 0.
  <false> is not true.
test_shows_embeddable_grid_of_tagged_content(TagControllerTest)
test/functional/tag_controller_test.rb:383:in `block in <class:TagControllerTest>'
```

**Comment by jywarren** [comment]
Sorry that's related to an error I accidentally introduced this morning.  A rebase should solve it -- thanks! So glad you've figured out the issue.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L782

on that line, we search using the tag -- and SQLite is case-dependent

**Comment by ryzokuken** [comment]
@jywarren Looks like I wasn't entirely wrong.

```
~/code/plots2 on master [⇡] via ⬢ v6.9.4 via 💎  ruby-2.1.2
➔ rails c test
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (called from <class:Image> at /home/ryzokuken/code/plots2/app/models/image.rb:12)
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (called from <class:User> at /home/ryzokuken/code/plots2/app/models/user.rb:21)
Loading test environment (Rails 3.2.22.4)
irb: warn: can't alias context from irb_context.
2.1.2 :001 > User.find_by_username("Bob")
  User Load (27.1ms)  SELECT "rusers".* FROM "rusers" WHERE "rusers"."username" = 'Bob' LIMIT 1
 => #<User id: 1, username: "Bob", email: "bob@publiclab.org", crypted_password: "53a9b83d6175f3a891c3073c3823f41f7ca7ff29c2441e96958...", password_salt: "77f06fd6725276cf1eae192229a029c3d27404a1d0b8f44d114...", persistence_token: "fab40b03ad6c1e5427fbb52b29bb8dd0386af43291b6a3a9f63...", login_count: 0, failed_login_count: 0, last_request_at: "2017-02-07 19:28:58", current_login_at: nil, last_login_at: nil, current_login_ip: nil, last_login_ip: nil, created_at: "2017-02-07 19:28:58", updated_at: "2017-02-07 19:28:58", openid_identifier: nil, role: "basic", reset_key: nil, photo_file_name: nil, photo_content_type: nil, photo_file_size: nil, location_privacy: true> 
2.1.2 :002 > User.find_by_username("bob")
  User Load (0.3ms)  SELECT "rusers".* FROM "rusers" WHERE "rusers"."username" = 'bob' LIMIT 1
 => nil 
```

**Comment by jywarren** [comment]
Great, so it is that line. Any progress on disabling case-dependency for an sqlite query?

**Comment by ryzokuken** [comment]
IMO, the best option is to keep usernames lowercase (because tags contain lowercase letters only and they are supposed to hold usernames)

**Comment by jywarren** [comment]
Unfortunately, many users already have capitals in their names, so I think we should consider the case-insensitivity-sqlite option, to avoid dealing with migrating legacy data.

**Comment by jywarren** [comment]
If we don't make progress on that approach, we can revisit the idea of migrating all users to be lower-cased-named. Sound good?

**Comment by ryzokuken** [comment]
@jywarren `user = User.where('lower(username) = ?', username.downcase).first` would work.

**Comment by ryzokuken** [comment]
@jywarren Here's a snippet I got from somewhere: 

```
def self.search_by_name(name)
  if Rails.env.development?
    where("LOWER(name) LIKE ?", "%#{name.downcase}%").take
  else
    where("LOWER(name) ILIKE ?", "%#{name}%").take
  end       
end
```

**Comment by jywarren** [comment]
That sounds great -- will that run on both sqlite and mysql? 

Maybe we should add an sqlite TravisCI check too; it's possible to have two checks run at once. https://github.com/publiclab/PublicLab.Editor/blob/master/.travis.yml (but let's think about that later)

**Comment by jywarren** [comment]
Can you add that in here and push a commit? And i guess close #1226.

**Comment by jywarren** [comment]
@ryzokuken did we finish this and integrate lower()?

**Comment by ryzokuken** [comment]
@jywarren I'd be honest, I totally forgot this one. I guess the other PR (which was required to fix the inconsistency) was merged. Will look into this one over the weekend and try to finish it. Thanks.

**Comment by jywarren** [comment]
No problem, thanks! Just trying to clear out some older PRs.

**Comment by ryzokuken** [comment]
@jywarren Fixed it in https://github.com/publiclab/plots2/pull/1290. Closing this one.

**Pull request closed without merging**
