### PR TITLE
Added @mentioned notification feature for node

### LINKED ISSUE #3122: Send @mentioned people notifications on note publication
People are increasingly used to mentioning people like @jywarren and triggering an email notification to that person when commenting on PublicLab.org. But when you do this in the body of a note, it doesn't send a notification like it does in a comment. 

The comment "mentions" are done in this code:

https://github.com/publiclab/plots2/blob/e95d89351e9d352ffa5dafe2209c4713b1f7453d/app/models/comment.rb#L100-L115

We have a list of mentioned users here: 

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L745

But we don't use it to trigger a notification.

This issue may need multiple parts:

* [ ] a `notify_callout_users` method in node.rb, like the one in comment.rb
* [ ] a `NodeMailer.notify_callout` or a re-use of the `CommentMailer` from the comment code above (to reduce redundancy -- although the mailer template may have to be changed not to say "mentioned in a comment" but just simply "mentioned"
* [ ] a test to show that on node `creation` (not update! because it might send twice?) that the appropriate emails are sent - like this test: https://github.com/publiclab/plots2/blob/master/test/unit/comment_mailer_test.rb#L34

Any help appreciated!

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
Closes #3122
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@namangupta01 can this pr be closed or you will be doing more work in this pr?

**Comment by gauravano** [comment]
hey @namangupta01, want to continue with this PR or we can close this? Thanks!

**Comment by namangupta01** [comment]
Hi Gaurav, I will continue to work in this after optimization of reply by
tweet. I am just focusing there but I will work on this as well soon.

**Comment by gauravano** [comment]
Ok. Thanks!

**Comment by namangupta01** [comment]
@jywarren I think this is good to merge.
Thanks!!

**Comment by namangupta01** [comment]
@jywarren Done! Have a loook!!

**Comment by jywarren** [comment]
This is super!!!! Thanks for closing up this old issue!

**Pull request merged**
