### PR TITLE
Add green checkmark to answered questions #1624

### LINKED ISSUE #1624: Add checkmark icon instead of (Answered) to questions display in pages
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Questions grids, generated by the inline shortcode `[questions:TAGNAME]` ([documented here](https://publiclab.org/wiki/power-tags)) now show questions that have been answered with a nice prefix, `(Answered)` -- which is helpful to tell which have been answered! But it takes up a lot of space:

https://publiclab.org/wiki/harvey#Questions

screenshot 2017-09-19 at 12 13 57 pm

### Solution

This display is set on these lines of code in the grids templates: https://github.com/jywarren/plots2/blob/double-inline-shortcodes/app/views/grids/_notes.html.erb#L37

What we should do is change this:

```html
      <td class="title"><% if node.answered %><b>(Answered)</b> <% end %><a href="<%= node.path %>"><%= node.title %></a></td>
```
so that instead of `<b>(Answered)</b>` it says `<i class="fa fa-"></i> ` (note the trailing space!) 

### Extra credit!

I found the checkbox icon (http://fontawesome.io/icon/check-square/) from http://fontawesome.io/icons/, which accounts for the `fa fa-___` classes. We have FontAwesome installed, so that makes this easier!

There are other checkbox icons there, so if you're opinionated about it, you could try another. Or turn it green with `<i style="color:#0c8;" ...`.

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

### PR DESCRIPTION
**Pull request by haleymnatz**
IN PROGRESS - errors with running tests locally to be examined in PR.

Green font awesome checkmark added to answered wiki questions.

Fixes #1624.

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, Haley - sorry I didn't get to this today -- very busy day! I'll look at it first thing tomorrow.

**Comment by jywarren** [comment]
This is so weird -- it seems like a problem with the Travis service, not anything to do with your or our work here... i'll try to restart this test i guess?

**Comment by jywarren** [comment]
OK i restarted it and will check in the morning! Sorry for the trouble!

**Comment by jywarren** [comment]
That's so weird, it stopped again. I'm going to close and reopen this PR to see if I can get it to retrigger.

**Comment by jywarren** [comment]
Hmm, i tried adding a new change to see if I could get it to run. I also made a small tweak from:

`<i class="fa fa-check-square" <i style="color:#0c8;"></i>`

to

`<i class="fa fa-check-square" <i style="color:#0c8;"></i>`

see how I got the `<i>` tag to have a clear open and close? Sorry if the original issue was oddly written!

**Comment by jywarren** [comment]
Hmm, for whatever reason the build seems to be running now. I guess we can look out and see if it passes tests in the morning. Thanks again! Great work on this despite the technical difficulties on our end!

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Comment by jywarren** [comment]
We should be able to publish this in the next day or two.

**Comment by haleymnatz** [comment]
@jywarren - Thanks for taking the time to deal with that, and sorry about the extra opening `<i` tag. The issue made sense - I think I copied my code wrong (had to start a new branch because I made a mistake with a push). I'd like to continue adding to the plots2 codebase, so for the future, if you have any ideas regarding what might be making the tests not finish running locally for me, that would be helpful! Thanks again!

**Comment by jywarren** [comment]
This is live now!!! https://publiclab.org/wiki/harvey#Questions

**Pull request merged**
