### PR TITLE
Profile page count

### LINKED ISSUE #3083: Counts on profiles incorrect.
Hi,
The counts on the number of research notes/questions on profile pages is a bit misleading. I think that's because it's counting the number of times people edit pages as well? Here are some examples:

- https://publiclab.org/profile/cheneyshreve (says 2 research notes/edits, but only one post shows up)
- https://publiclab.org/profile/pojij_85  (says 2 research notes/edits, but only one post shows up)
- https://publiclab.org/profile/amenzel8  (says 2 research notes/edits, but only one post shows up)

I'm wondering if we could differentiate between posts and edits. Maybe it could show up like this: "4 posts and 2 edits". If this is too complicated for the system, could we change the text on the profile pages so it says "posts" instead of "research notes" since posts now include questions and comments?

Thanks!
-Stevie

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #3083 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, looks like a conflict from the sidebar move -- but shouldn't be too big a deal!

**Comment by Gauravano** [comment]
Hi @jywarren please review this one

Updated pages count:

sec_count
first_count

Also, Jeff your suggestions are required at https://github.com/publiclab/plots2/issues/3137, https://github.com/publiclab/plots2/issues/1610 and https://github.com/publiclab/plots2/pull/3140 . Thanks!

**Comment by steviepubliclab** [comment]
This is great! much more clear. Thanks!

**Comment by jywarren** [comment]
🎉 !!!

**Pull request merged**
