### PR TITLE
Move quiz stats to stats page

### LINKED ISSUE #4748: Moving question stats to a new area
Hi @cesswairimu i moved this down the page and I wanted to suggest we could move it to the /stats page, maybe? I'm just trying to consolidate all these interfaces. Or do you think we could even incorporate the question stats into the range-based pages alongside the notes, comments, etc?

https://github.com/publiclab/plots2/blob/08d0f7d4e9b7c1e0d4d9d2e30c4b68c40162751e/app/views/questions/index.html.erb#L94-L106

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #4748  

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
quiz-stats
@jywarren how does this look?

**Comment by jywarren** [comment]
This is great. Shall we remove it from the previous location too?

**Comment by cesswairimu** [comment]
Yeah sound good. on it

**Comment by cesswairimu** [comment]
@jywarren this one is ready.

**Pull request merged**
