### PR TITLE
Added style color blue

### PR DESCRIPTION
**Pull request by newbazz**
fixes https://github.com/publiclab/plots2/issues/5865

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by newbazz** [comment]
@gauravano sorry for closing the previous pr, i made a mess in it. Please review this one.

**Comment by cesswairimu** [comment]
Hey @newbazz could you please provide a screenshot

**Comment by newbazz** [comment]
image

@cesswairimu here is the screenshot

**Comment by cesswairimu** [comment]
Looking good but that shade of blue doesn't quite blend with the others...could we try #007bff; or #0088cc ? Thanks

**Comment by newbazz** [comment]
image

@cesswairimu this looks decent i guess

**Comment by cesswairimu** [comment]
yeah that looks great. Thanks

**Comment by newbazz** [comment]
@cesswairimu what is the warning given by bot? and who will merge the pull request?

**Comment by jywarren** [comment]
Awesome!!! Thank you!

**Pull request merged**
