### PR TITLE
changed id "#username-signup" in #toLogin function to "#username-login"

### LINKED ISSUE #4680: Fix same CSS Id "#username-signup"
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: It looks like we have rather two different elements with the same Ids! I think replacing one of these with some other Id and fixing the snippet where it's being used should fix the problem.
plots2id

The Ids are created in these two files.

````
./app/views/user_sessions/new.html.erb:
   16      <div class="form-group">
   17        <label for="username"><%= t('user_sessions.new.username') %></label>
   18:       <%= f.text_field :username, { tabindex: 1, placeholder: "Username", class: 'form-control', id: 'username-signup', style: 'width: 85%' } %>
   19        <label for="password"><%= t('user_sessions.new.password') %></label>
   20        <%= f.password_field :password, { tabindex: 2,placeholder: "Password",class: 'form-control', id: 'password-signup', style: 'width: 85%', onpaste: 'return false;' } %>

./app/views/users/_create_form.html.erb:
   32        <div class="form-group col-sm-12" id="username_div">
   33          <label for="username"><%= t('user_sessions.new.username') %></label>
   34:         <%= f.text_field :username, { tabindex: 1, placeholder: "Username", class: 'form-control', id: 'username-signup' } %>
   35        </div>
   36  
````

And the DOM manipulation is done here, which needs to replaced properly with the two seperate Ids accordingly (in place of **#username-signup**).

````
./app/views/layouts/_header.html.erb:
  225  
  226      $("#toLogin").click(function(){ //Function runs when the "login" buttin in the signup modal is clicked
  227:       var user = $("#signupContainer").find("#username-signup").val(); //Username and password data is transferred to the other partial
  228        var pass = $("#signupContainer").find("#password").val();
  229        showLogin(); // Modal switches to login view
  230:       $("#loginContainer").find("#username-signup").val(user);
  231        $("#loginContainer").find("#password-signup").val(pass);
  232      });
  233  
  234      $("#toSignup").click(function(){ //Function runs when the "sign up to join" link in the login modal is clicked
  235:       var user = $("#loginContainer").find("#username-signup").val(); //Username and password data is transferred to the other partial
  236        var pass = $("#loginContainer").find("#password-signup").val();
  237        showSignup(); // Modal switches to sign up view
  238:       $("#signupContainer").find("#username-signup:visible").val(user);
  239        $("#signupContainer").find("#password").val(pass);
  240        ;
````

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by jdevo23**
Fixes #4680

* [✔️ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✔️] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [✔️] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jdevo23** [comment]
Hi, is it necessary to add screenshots here?

**Comment by geekychaser** [comment]
@jdevo23 Hii, it is not necessary to add screenshots but it is good practice to add one as it becomes easy to review UI related issues.
Thank you

**Comment by gauravano** [comment]
@jywarren @SidharthBansal tested on `unstable` and locally too. 

sign_login_switch

Merging now!

**Comment by gauravano** [comment]
Merged :tada: :balloon:!

Hi @jdevo23, thanks for nice work. We would love to have more help from you. If you are interested in solving more issues then check here - https://code.publiclab.org/#r=all for a new issue. In case, you are unable to find an issue, feel free to comment here. Thanks!

**Pull request merged**
