### PR TITLE
Reload function added upon adding location tags

### LINKED ISSUE #7359: Refresh page upon adding location tags
I heard from someone who was confused as to why the map didn't appear upon adding location tags, so I think we should initiate a page refresh when that happens -- what do you think, @nstjean @crisner -- does this makes sense? We could just do this in JS after hearing a success for the tag POST? 

Thanks! Just a thought that this might be a better user experience!

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes #7359 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
Ok @nstjean will follow you.

**Comment by NitinBhasneria** [comment]
@nstjean can you help with this error.

**Comment by nstjean** [comment]
Ahh, it wants us to take out the `!!` in there.

**Comment by NitinBhasneria** [comment]
@nstjean please review

**Comment by nstjean** [comment]
Are you having troubles with this? Can you reopen it so I can see the error?

Also, just a mention, for the commit messages try to put something descriptive so you know in the future what you did. :) "Improved" will be confusing later.

**Comment by NitinBhasneria** [comment]
@nstjean   please see #7520

**Comment by nstjean** [comment]
Thanks, I see the new one now. :)

**Pull request closed without merging**
