### PR TITLE
Fix new system tests for adding tags to node and user

### LINKED ISSUE #6904: new system test fails due to probably timing issue
https://github.com/publiclab/plots2/blob/3c0273364cb9b2a22169bea32af6f11aad3ade91/test/system/tag_test.rb#L27-L46

These lines seem to fail - esp `assert_selector('.tags-list .card-body h5', text: 'roses')`, in what I think is just a timing failure - that we should wait longer for it to complete, as it's an AJAX request. 

I've seen a failure for this on https://github.com/publiclab/plots2/pull/6758 (which I restarted) and on https://github.com/publiclab/plots2/pull/6858#issuecomment-561337577 (which resolved on restart, but the error output is there):

```
 FAIL["test_adding_a_tag_via_javascript_with_url_only", #<Minitest::Reporters::Suite:0x00007fc289832e00 @name="TagTest">, 116.16007206999996]
 test_adding_a_tag_via_javascript_with_url_only#TagTest (116.16s)
        expected to find css ".tags-list .card-body h5" but there were no matches
        test/system/tag_test.rb:44:in `block in <class:TagTest>'
[Screenshot]: tmp/screenshots/test_viewing_the_dropdown_menu.png
[Screenshot]: tmp/screenshots/test_viewing_the_dropdown_menu.png
[Screenshot]: tmp/screenshots/test_viewing_the_settings_page.png
  43/43: [=================================] 100% Time: 00:03:05, Time: 00:03:05
```

We could lengthen `  Capybara.default_max_wait_time = 60` but there are other subtle ways to fix timings. Oddly, one is to add an `assert_select` as it is supposed to naturally keep looking for up to 60 seconds for stuff to appear on the page when looking for specific CSS/HTML with that method. Here, that doesn't seem to be working.

Referencing some previous timing-related issues which don't seem so helpful, but maybe:

https://github.com/publiclab/plots2/issues/5683 and #6179 (maybe?)

This is an odd one! I wonder what's going on, @nstjean !? Stumped!

### PR DESCRIPTION
**Pull request by nstjean**
Fixes #6904  (<=== Add issue number here)

I have added some logic to the updating of the page after adding tags so now tags added via URL (instead of the form) will also be updated immediately on the page, just like it did when tags were added by the form. I also added a check so that it would only show on the page if you were adding a tag to the same node/user as the one that's being displayed.

I have updated the system tests to check for this instead of refreshing the page. Hopefully this will stop the timing issue we were seeing!

@jywarren

### CODE REVIEW

**Comment by nstjean** [comment]
I did have to modify the controllers by sending back the node or user id in the response on success... otherwise there was no way to check if it should be displayed or not! I have updated the tests for those controllers.

**Comment by jywarren** [comment]
Huh, i wonder what happened? These seem unrelated; i'll try restarting them?

``` FAIL["test_that_NodeShared_can_be_used_to_convert_short_codes_like_[map:content:lat:lon]_into_maps_which_display_notes", #<Minitest::Reporters::Suite:0x0000555dec4a74d8 @name="NodeSharedTest">, 14.961872337999978]
 test_that_NodeShared_can_be_used_to_convert_short_codes_like_[map:content:lat:lon]_into_maps_which_display_notes#NodeSharedTest (14.96s)
        Expected: 1
          Actual: 0
        test/unit/node_shared_test.rb:153:in `block in <class:NodeSharedTest>'
 FAIL["test_that_NodeShared_can_be_used_to_convert_short_codes_like_[map:tag:blog:lat:lon]_into_maps_which_display_notes,_but_only_those_tagged_with_\"blog\"", #<Minitest::Reporters::Suite:0x0000555dec165090 @name="NodeSharedTest">, 14.988351848999969]
 test_that_NodeShared_can_be_used_to_convert_short_codes_like_[map:tag:blog:lat:lon]_into_maps_which_display_notes,_but_only_those_tagged_with_"blog"#NodeSharedTest (14.99s)
        Expected: 1
          Actual: 0
        test/unit/node_shared_test.rb:160:in `block in <class:NodeSharedTest>'
```

**Comment by jywarren** [comment]
@sagarpreet-chadha any ideas here? This is layers stuff i guess, but what's going on? Could it be related to #6910 ?

**Comment by nstjean** [comment]
These are the same tests that are failing for others https://github.com/publiclab/plots2/issues/6950

**Comment by jywarren** [comment]
Awesome work! Thanks!

**Pull request merged**
