### PR TITLE
Configurable email settings

### LINKED ISSUE #213: configurable email notification preferences
We are having settings at /settings as we might wanna add more settings in future. Below are the settings which would be added to settings page: 

Asking: Do you want to be notified by email for (with toggles):

- [x] comments on your posts
- [x] comments on all posts you've commented on
- [x] likes on your posts
- [x] notes on a topic (we have this already!)
- [ ] notifications for wiki page edits: https://github.com/publiclab/plots2/issues/396 (after all the rest!)
- [ ] The monthly blog would be everything tagged `blog` once per
month? What user tag would that be? (by @jywarren )
- [x] Digest- weekly
- [x] Digest - daily

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #213

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
Hi @jywarren please review this one 

Settings Menu look:
update_setting1


Here's demo for Like setting:
 https://drive.google.com/open?id=1f8BDYdLr7pZj1zQZkQ3VQ8xuR7xQkD3B

Demo for Indirect comment setting: 
https://drive.google.com/open?id=1Cj-vVST7AL4kPo8_FVoIJFzJUfiibRvN

Thanks!

**Comment by jywarren** [comment]
Wow, this is great. Is there a place we can document the defaults and behaviors in a centralized location and link to there from various parts of the codebase which touch this? Since the defaults aren't obvious maybe. 

Thanks, Gaurav!!!

**Comment by jywarren** [comment]
Fixes #1610 too, right?

**Comment by Gauravano** [comment]
yes, @jywarren we should surely document this! I am a little confused about the location. Would you mind pointing some locations where a "Email Settings" can reside? Thanks!

**Comment by jywarren** [comment]
sure, do you mean the location in the documentation? Or location in the
interface?

**Comment by Gauravano** [comment]
Location in the documentation :sweat_smile:

**Comment by Gauravano** [comment]
@jywarren I would like to open a separate PR for documentation. What do you think? Thanks!

**Comment by jywarren** [comment]
It sounds good. In general I prefer that docs and code be in the same PR as it's easier to trace what happened, and the docs can serve as explanation. But it's fine -- just something to aim for! 👍 👍 👍

**Pull request merged**
