### PR TITLE
Fix 'Contributor count on tag pages not reflecting number of contributors #6675'

### LINKED ISSUE #6675: Contributor count on tag pages not reflecting number of contributors
I was looking for the number of posts and contributors to this tag (https://publiclab.org/tag/oil-and-gas) and saw that the number was listed here as Zero: 
Screen Shot 2019-11-04 at 11 59 38 AM

But there are actually 73 contributors and 38 posts. This can be found here https://publiclab.org/contributors/oil-and-gas: 
Screen Shot 2019-11-04 at 12 00 54 PM

### PR DESCRIPTION
**Pull request by nicoleiocana**
Fixes #6675

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [✔️ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [✔️ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✔️ ] screenshots/GIFs are attached 📎 in case of UI updation
6675-fix

* [N/A ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@jywarren looks good according to me. 
As you were discussing it with him, can you please Take a look.
Thanks for contributing at PL

**Comment by jywarren** [comment]
Ah, i think `test.sqlite-journal` needs to be removed? Would you mind? Thank you!!!

**Comment by cesswairimu** [comment]
@nicoleiocana, there are is none conflicting file...could you please solve that..actually you can just undo the changes u did on `test.sqlite-journal` they shouldn't be there. Ping me to merge this while done. Thanks again.

**Comment by nicoleiocana** [comment]
@cesswairimu Sorry this is taking a long time, I am kinda lost and I'm not above asking for help from you guys. So, my train of thought was to go into the **files changed** tab and I could edit the file; it usually shows me what was once there before versus was was added/deleted. But, for some reason, all I got was this in my drop-down menu:

edit_missing

Then, I noted at the top, for some reason, it doesn't show my name as I forked the plots2 repo; it know reads _unknown repo_. 

unknown_repo

I don't want to make this more work than is unnecessary, but could you (or anyone willing to help) guide me in what I need to do so that I can undo the changes and get this PR merged? Thanks in advance.

**Comment by cesswairimu** [comment]
It seems like we commented the same time with Jeff :laughing: No worries @nicoleiocana, mmh yeah that is strange...  I tried to pull your changes and it is showing its from  `unknown repository`. what is the name of the branch that you worked on maybe I could try and check it out from the branch on your fork?

**Comment by nicoleiocana** [comment]
missing_branch

Weird. I created a branch that matched the name of my PR. For some reason, it is no longer there. But my other branches that I worked on are showing... ='(

**Comment by cesswairimu** [comment]
wierd :thinking: could be easy to open anther pr from one of your existing branches? without the  `test.sqlite-journal`?

**Comment by nicoleiocana** [comment]
I was thinking the same thing. But if I created a new PR from one of my existing branches, how would we tie it up to this PR? Or am I understanding your recommendation incorrectly?

Also, am I misunderstanding the issue: you guys are stating that the test.sqlite-journal should be deleted? Because isn't it deleted in my PR?

**Comment by cesswairimu** [comment]
We will just close this and merge the other one. makes sense?...It is showing you made some changes to that file...what we are suggesting is you do not commit that file...so that on "files changed" you will have just one file..I hope this helps

**Comment by cesswairimu** [comment]
But no worries if you do it from a branch I can view I can help if you are unable to remove the file

**Comment by nicoleiocana** [comment]
No, that totally makes sense. Okay, I'll go ahead and:

1. git pull so that my repo is updated to the head of plots2's master branch.
2. Then I'll create a new branch call **contributor-count-on-tag-pages-not-reflecting-number-of-contributors**,
3. make the same fixes to the app/views/tag/show.html.erb file.
4. Only commit that file.
5. Add the commit message to be the same as this: _Fix 'Contributor count on tag pages not reflecting number of contributors_,
6. then submit a new PR and call it: Fix 'Contributor count on tag pages not reflecting number of contributors'

Thanks for the help =). Sorry for any inconvenience.

**Comment by nicoleiocana** [comment]
Here is the new PR:

#6952

**Comment by nicoleiocana** [comment]
Updated PR with my repo's commit's with same head as plots2's  Dec. 11 updates:

#6954

**Pull request closed without merging**
