### PR TITLE
Update style.css fixes #5059

### LINKED ISSUE #5059: Footer not sticking to the bottom of the screen on pages with little content on large displays
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
* [ ]  🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
* [ ]  📝 **Update** edit thw [stylesheets](https://github.com/publiclab/plots2/tree/master/app/assets/stylesheets) folder to add styles that address this issue. You can check out [this article](https://css-tricks.com/couple-takes-sticky-footer/) for help.

**Current Behavior**
Visiting the following pages: _https://publiclab.org/settings_, _https://publiclab.org/subscriptions (when you have little or no subscriptions)_, _https://publiclab.org/subscriptions/digest (when you have little or no subscriptions)_, _https://pubiclab.org/:user/likes (when you have little or no liked content)_ will show a footer that is pushed up and does not stick to the bottom of the page.

![Screenshot 2019-03-14 at 12 23 12 AM](https://user-images.githubusercontent.com/7345686/54321715-85c20d00-45f2-11e9-9140-d9e8bdf46fc7.png)
![Screenshot 2019-03-14 at 12 23 29 AM](https://user-images.githubusercontent.com/7345686/54321722-8e1a4800-45f2-11e9-8c18-9ddd6843b446.png)
![Screenshot 2019-03-14 at 12 23 36 AM](https://user-images.githubusercontent.com/7345686/54321736-9a9ea080-45f2-11e9-9068-122585eeadfb.png)
![Screenshot 2019-03-14 at 12 23 42 AM](https://user-images.githubusercontent.com/7345686/54321744-a1c5ae80-45f2-11e9-9a7b-0a8341f73834.png)

The above images are the only pages with little content I could find on production, but note that the behaviour will be replicated on any page with little content, as evidenced by this screenshot of a page on development:

![Screenshot 2019-03-14 at 12 55 00 AM](https://user-images.githubusercontent.com/7345686/54322055-f3bb0400-45f3-11e9-9389-38020db0761c.png)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
**Expected Behavior**
The footer should stick to the bottom of the screen, no matter the height of the content.

![Screenshot 2019-03-14 at 1 01 54 AM](https://user-images.githubusercontent.com/7345686/54322375-37623d80-45f5-11e9-8b45-5d6823f07d1a.png)
![Screenshot 2019-03-14 at 1 04 45 AM](https://user-images.githubusercontent.com/7345686/54322376-37623d80-45f5-11e9-84ab-8bdcce4ab754.png)


* [ ]  💾 **Commit** your changes
* [ ]  🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

* [ ]  🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### PR DESCRIPTION
**Pull request by fabsar**
I have set the position of the footer as absolute and the distance from bottom as zero.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [✔] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ✔] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by fabsar** [comment]
@sargam52921036

**Comment by fabsar** [comment]
Thank you!!

**Comment by fabsar** [comment]
There is some problem with the checkboxes. I am unable to mark them

**Comment by fabsar** [comment]
Sure! I have updated the checkboxes.

**Comment by ananyaarun** [comment]
@fabsar Hi, Can u pls add a link to the issue number ? Great work so far. Thanks :)

**Comment by fabsar** [comment]
Oh I am so sorry I missed that, here is the link for the issue: https://github.com/publiclab/plots2/issues/5059

**Comment by ananyaarun** [comment]
@fabsar No problem ! Just add it her on the issue template.
Fixes #0000 (<=== Add issue number here)
Instead write Fixes #5059 
Thanks !

**Comment by fabsar** [comment]
Working on it @gauravano.

**Comment by fabsar** [comment]
sorry I didn't get you. where do I login as admin? @gauravano

**Comment by ananyaarun** [comment]
@fabsar , On the main page click on Login. Username is admin and password is password. Doing so u will be able to login as admin. I hope this helps :)

**Comment by ananyaarun** [comment]
@fabsar , Have do u have a local set up in ur system ? Firstly you need to follow the instructions given in readme.md to set up publiclab.org locally on ur system. After doing so u can run the app and login as i said. Here are the instructions. Feel free to ask for help if you get stuck anywhere :) 
https://github.com/publiclab/plots2#installation

**Comment by fabsar** [comment]
I have been trying setting up in my system. It is giving me the following error on running the command bundle update:
Could not locate Gemfile
I have done gem install bundle.
Please help out! thanks:)

**Comment by ananyaarun** [comment]
@fabsar , Can u post a screenshot of the actual error msg ? I think you are running bundle update from a different directory. You need to be in the same directory as that of ur gemfile while running bundle update.
Do a "ls" and check if gemfile is in that directory or not. Then run bundle update and u r good to go !! :)

**Comment by fabsar** [comment]
oh yes it was a differnt directory and also I was running a different version of Ruby than the one specified in the gemfile. Figured that out .Thanks  a lot:)

**Comment by fabsar** [comment]
I was just completed the setup. Will fix the issue ASAP now.

**Comment by fabsar** [comment]
I don't see any footer in the setup I am running on the local host. What do I do?

**Comment by gauravano** [comment]
You can add footer by following this - https://github.com/publiclab/plots2/pull/5124#pullrequestreview-215353427

**Comment by fabsar** [comment]
How do I create a feature?

**Comment by gauravano** [comment]
You can make feature by following this :point_down: 
making_feature

Code for footer - https://gist.github.com/gauravano/1124fff46ae156537e6fb712bff9e980
 and create feature by name `footer-notice` only

**Comment by fabsar** [comment]
I had been doing this. But when i went to /features it redirected to the http://localhost:3000/home?return_to=%2Flogin and a message read- You must be logged out to access this page

**Comment by gauravano** [comment]
when you login as admin, it will not redirect you

**Comment by fabsar** [comment]
I logged in as admin still it redirected me.

**Comment by gauravano** [comment]
copy gif here

**Comment by fabsar** [comment]
s1

**Comment by fabsar** [comment]
I have not been able to figure out the issue till now. please help!! Thanks:)

**Comment by gauravano** [comment]
Hey @fabsar, please try to go on /dashboard first and then /features. It's really confusing that why you aren't able to browse /features even when logged in as admin :confused:

**Comment by SidharthBansal** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
