### PR TITLE
[WIP] Welcome text added to dashboard.html.erb

### LINKED ISSUE #511: Draft text to welcome newcomers to the dashboard
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

We need something like (but in HTML):

```
## Hello, welcome to Public Lab!

This is your dashboard, where recent updates from other community members show up. It's helpful to keep up to date with new progress, news, and recent developments.

But to get started at Public Lab, try:

* asking a question (/questions)
* exploring projects (/methods)
```

This would go in the Dashboard template, probably just above the Activity feed, in a box, perhaps with a light grey 1px border and rounded corners:

https://github.com/publiclab/plots2/blob/master/app/views/dashboard/dashboard.html.erb#L26

If you take this on, please share a screenshot of your work so we can see how it looks!

### PR DESCRIPTION
**Pull request by dristibutola**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

fixes #511

### CODE REVIEW

**Comment by dristybutola** [comment]
This pr is still in progress, would be making further commits,
#1315

**Comment by ryzokuken** [comment]
@dristybutola Are you stuck on this or something? Please feel free to ask for help. Also, if this PR is not ready yet, please mark it as such (maybe by prepending [WIP] to the title). Thank you for contributing to Publiclab.

**Comment by dristybutola** [comment]
@ryzokuken  , I just made a skeloton structure to build further on , can you suggest 
further required changes for dashboard.

**Comment by jywarren** [comment]
Oh, this looks so nice! Can you share a screenshot of it so we can see if it looks appropriate before publishing?

**Comment by dristybutola** [comment]
@jywarren sure !! But it may take some time for me, as I had some previous  problem with installation.
Thanks...

**Comment by jywarren** [comment]
OK, please reach out if you need help with installation, here or in our
chatroom at http://publiclab.org/chat

Thanks!

**Comment by jywarren** [comment]
Hi, just checking if we can help out at all?

**Comment by dristybutola** [comment]
The preview on c9 installation gives me error  http://dristy-dristybutola.c9users.io:8080/,
Please guide regarding this,
thnks

**Comment by jywarren** [comment]
Hi, I'm very sorry to not have checked in; since cloud 9 shuts down when it's not actively being used, I can't see the error. Could you paste it in here, or in a Gist (gist.github.com)?

**Comment by jywarren** [comment]
Also, did you see my suggestion for limiting this to display only to new users?

https://github.com/publiclab/plots2/issues/511#issuecomment-263180329

**Comment by jywarren** [comment]
Hi, I think we've resolved the cloud9 issues recently -- I think you can pull in the latest with `git pull https://github.com/publiclab/plots2.git master` and you'll get updated. Happy to help debug!

**Comment by AI-GAME-Engineer** [comment]
Hello, I did pull the updates but still gives error .
link : https://dristy-dristybutola.c9users.io/
screenshot from 2017-05-15 11-03-04

**Comment by dristybutola** [comment]
Hello, I did pull the updates but still gives error .
link : https://dristy-dristybutola.c9users.io/
screenshot from 2017-05-15 11-03-04

**Comment by jywarren** [comment]
Hi! I'm sorry you were having so much trouble. I'm going to close this now as I believe the original issue is solved, but I've also been seeing this type of error occasionally, and am not sure why. I'd like to try investigating this further if you would be able to open an issue describing it? Thank you so much!

**Pull request closed without merging**
