### PR TITLE
Add rich editor msg - fixes #971

### LINKED ISSUE #971: Add "try the new Rich Editor" message to /post page
### Relevant URLs

https://publiclab.org/post

Rich editor URL: https://publiclab.org/editor

The /post template is here: https://github.com/publiclab/plots2/blob/master/app/views/editor/post.html.erb

An `<div class="alert alert-success">Text</div>` with the text and link inside would be perfect. 

Perhaps it should say "beta Rich Editor"!

### PR DESCRIPTION
**Pull request by sandyvern**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, Sandy, I think you didn't base your change on the latest master branch -- I think I can help "cherry-pick" your new changes and replay them on the latest master, tomorrow! Thanks!!

**Comment by sandyvern** [comment]
Thanks! It seems somehow I am missing a step that sort of clears things from previous commits so everything ends up getting wonky when I start a new issue :(

**Comment by jywarren** [comment]
Thank you, I'm sorry, there's a lot going on at the moment, and our annual
conference is beginning. But I'll do my best to find a moment to review and
provide feedback. Thanks.

**Comment by jywarren** [comment]
Hi, back online but behind! 

OK - looking at this, it seems like you didn't run `git checkout master` (to switch back to master) and `git pull https://github.com/publiclab/plots2.git master` (to get the latest) before making your new feature branch, so your feature branch was then based on the last feature branch you made, rather than the latest master. 

Then, when Git complained at you (i'm guessing? it can be very unhelpful!) you merged master in, which is the "Getting latest version  …" messages in your commit log. The problem is that those merges back in are overwriting and reverting some of your earlier changes. 

I think at this point we could try to `git rebase -i master` over the lastest master (after `git checkout master` and `git pull https://github.com/publiclab/plots2.git master`) and choose which commits to keep (and prevent the merges from overwriting your changes). 

I think it's worth a try, but I worry that the rebase and conflict resolutions will be a bit convoluted. I've grabbed a copy of this whole branch, so I can try and deconflict it if you run into trouble! You can also always make a backup copy of what you're working on with `git branch feature-branch-name-backup` or some other such suitable name. 

Keep looking at the final changes (the aggregate of all your commits) at this link: https://github.com/publiclab/plots2/pull/975/files

If you do run into trouble, ping me and I'll try pulling out the additions without the overwrites based on the copy I just made. 

Thanks, and good luck!

And sorry I was so slow on this! I was at [the Barnraising](https://publiclab.org/barnraising), our annual conference, and am not normally out of touch for so long!

**Comment by jywarren** [comment]
Oh, also, in case this is helpful: https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/

**Comment by ryzokuken** [comment]
Hello! You must've noticed that the unit tests failed unexpectedly on your PR. This was due to some issue in the Travis CI testing configuration which was fixed by @jywarren later tonight. In order to make them work again, please rebase your work on top of the current master and then try pushing to your remote branch. Do this by:

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <my-branch>
$ git rebase master
$ git push origin <my-branch>
```

Thanks for bearing with us,
Ujjwal

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks and hope you're well!

**Comment by jywarren** [comment]
Hi, Sandy - just checking in here -- with #1091 almost complete, I think this PR will no longer be necessary, but we'd love to have your contribution on another issue from the list. 

https://github.com/publiclab/plots2/labels/help-wanted

Thanks for all your help!

**Pull request closed without merging**
