### PR TITLE
Update container definitions to match actual files used.

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
We need to expose actual docker-compose-unstable.yml for @ViditChitkara to be able to include redis.
Currently we have a local copy of docker-compose-unstable.yml in staging. Updating the version in the repo and then going to update jenkins config to use this yml file instead of the local copy.

**Comment by icarito** [comment]
Travis is failing on network timeout - these actually don't affect Travis so I'm going to merge them to unlock @ViditChitkara's work.

**Comment by icarito** [comment]
@ViditChitkara this is confirmed to build in `unstable`. Please rebase your PR and you should see your changes to `containers/docker-compose-unstable.yml` reflected in the staging service.

**Comment by ViditChitkara** [comment]
Cool I'll do!!

**Pull request merged**
