### PR TITLE
Fixed rubocop offences

### LINKED ISSUE #2125: Ruby Style Guide [Rubocop]
Plots2 has a `.rubocop_todo.yml`. Is someone willing to take up the following to fix them? If you need help with something please ask and we'll be happy to help.

For starters the following can be fixed first.

```
Layout/AccessModifierIndentation
Layout/AlignArray
Layout/AlignHash
```

Once you're done with your changes, please run `rake test` and `rubocop`. Create a PR when all passes.

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Closes #2125 

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
Let's finger X for tests 😅

**Comment by namangupta01** [comment]
@ryzokuken can you please have a look why first error is occurring in https://github.com/namangupta01/plots2/blob/rubocop/test/functional/comment_controller_test.rb#L350
While no error in https://github.com/namangupta01/plots2/blob/rubocop/test/functional/comment_controller_test.rb#L351

**Comment by ryzokuken** [comment]
Let me check. Meanwhile, could you please fix all those `.zero` errors so that I could troubleshoot the others.

**Comment by namangupta01** [comment]
@ryzokuken yes i have already fixed it and have updated the pr. Let's fingers X for tests

**Comment by namangupta01** [comment]
@ryzokuken All `.zero` errors are now removed

**Comment by ryzokuken** [comment]
@namangupta01 I saw.

The failing tests are:

```ruby
assert_equal html.scan('<a href="/profile/Bob">Bob</a> is suggesting an alternative title').length,1
```

Let's see how you changed that particular controller which broke this. IIRC, this feature was added recently.

**Comment by ryzokuken** [comment]
Okay, so @ViditChitkara made that PR.

@ViditChitkara any help?

**Comment by ryzokuken** [comment]
@namangupta01 I'd strongly advise you to use better commit messages. Please check out this guide: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message for more helpful tips.

**Comment by namangupta01** [comment]
@ryzokuken I am really sorry for this. I don't intend to push it here. I was merging one of my commit from one of my other branch locally but i mistakenly pushed it on remote branch. I'm really really sorry for this.

**Comment by ryzokuken** [comment]
No worries, I just wanted to make sure we end up with commits with descriptive messages when we merge, it really helps later on.

**Comment by ryzokuken** [comment]
@namangupta01 this is something that happens to the best of us, don't worry.

For good humor:

**Comment by namangupta01** [comment]
😂😂😂 That's So true! 😅

**Comment by namangupta01** [comment]
Yaaass, Finally tests passes :)

**Comment by jywarren** [comment]
🎉  Awesome!

**Pull request merged**
