### PR TITLE
Added login google button for OAuth

### LINKED ISSUE #2851: Google OAuth login view
Create view for login page for google provider to sign up/log in
url --> publiclab.org/login
Part of #2676 and #2771

Is this type of icons ok @jywarren?
image

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #2851 
image

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! Can you resolve the conflicts here and I can merge! Feel free to mark ready since thisooks GREAT!!!

**Comment by jywarren** [comment]
Oh weird, I thought I saw a conflict but it looks perfect now. Merging!!!

**Comment by jywarren** [comment]
Hmm, ok I see, when I click merge I get:

>  This branch has conflicts that must be resolved.
Use the command line to resolve conflicts before continuing. 

Maybe it needs a rebase?

**Comment by SidharthBansal** [comment]
I have resolved the conflicts. It's ready for merge

**Comment by jywarren** [comment]
Super!

**Pull request merged**
