### PR TITLE
Removed integration test from unit test folder

### LINKED ISSUE #3429: Move an integration test to integration test folder which is present in Unit test file [PART 3]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

Currently some integration tests are present in unit test folder, so we can move them from this folder and add them to integration test folder.
https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/test/unit/comment_test.rb#L226

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #3429 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Uzay-G** [comment]
I think you need to move it into the integration tests folder. Is it already there?

**Comment by Manasa2850** [comment]
Hi @Uzay-G. Yup it's already there in the integrations test folder

**Comment by Uzay-G** [comment]
Ok found it https://github.com/publiclab/plots2/blob/9c409ec6bee43b95dfe52191cb5069f4199a4524/test/integration/token_comment_test.rb#L21-L36.

**Review by Uzay-G — APPROVED** [review]
LGTM

**Comment by cesswairimu** [comment]
Great job  you both, thanks :tada:

**Review by cesswairimu — APPROVED** [review]
:rocket:

**Pull request merged**
