### PR TITLE
Fix - 3644 Fix  button colliding with the enter tag in the mobile view

### LINKED ISSUE #3644: Add button colliding with the enter tag in the mobile view
### Please describe the problem (or idea)
In the subscription page , when opening the mobile view , the add button is colliding with the enter tag which shows that the page is needed to be improved and made responsive.
Desktop view:
capture6
Mobile view:
capture7

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/subscriptions

### What's your PublicLab.org username?
201651044
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #3644 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

screenshot from 2018-10-09 11-29-24

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sk9331657** [comment]
@jywarren  @SidharthBansal  Please review. Task one completed.

**Comment by sagarpreet-chadha** [comment]
Hi @sk9331657 !
Thanks for opening the pull request . Can you link back to the issue it solves ? 
You can do it by typing :   Fixes #(the issue number) . 
😄

**Comment by sk9331657** [comment]
> Hi @sk9331657 !
> Thanks for opening the pull request . Can you link back to the issue it solves ?
> You can do it by typing : Fixes #(the issue number) .

Added Sir.

**Comment by sk9331657** [comment]
@sagarpreet-chadha  @SidharthBansal  Thanks for your review.

**Comment by sk9331657** [comment]
@jywarren  Please merge this.

**Comment by jywarren** [comment]
Amazing- thanks everyone!!!!

**Comment by sk9331657** [comment]
@jywarren  Please review my GCI application. Can't wait to join Mentors Team 😄.

**Pull request merged**
