### PR TITLE
Add activities variant of notes inline tag

### LINKED ISSUE #5308: Enable "activities" variant of [notes:grid:TAGNAME] inline tag
Now that we have inline image grids, like on this page: https://publiclab.org/wiki/coqui#Assemble+the+Coqui

image

...that can be made by inserting the following shortcode into a wiki page: `[notes:grid:coqui]` (for example),

We should make the `Add an activity` button appear if we use the alternate syntax:

`[activities:grid:coqui]`

image

Here's where we show the button:

https://github.com/publiclab/plots2/blob/e7d1315189f3e4b7ad0e1f50c1ed74c1d371c6bf/app/views/grids/_notes.html.erb#L68-L74

And here are lines of code where the current Activities grid is added:

https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb#L84

https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L190-L221

Here's the thumbnails grid code that would be copied to make an activities thumbnails grid:

https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L20-L56

We'd love help with this!

### PR DESCRIPTION
**Pull request by digitaldina**
Fixes #5308 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by dinaelhanan** [comment]
@publiclab/reviewers

**Comment by jywarren** [comment]
Oh this is cool!!! Can you share a screenshot of how it looks? Thanks!!!

**Comment by dinaelhanan** [comment]
@jywarren ofcourse 👍 
activitesshortcode

**Comment by jywarren** [comment]
Oh this looks great! Now, can you modify it so it displays a grid of
thumbnails instead of the table? I think you can render the grid template
instead of the table one, but you'll have to copy over the activity button
to the grid template the same way it's present in the table template. Make
sense?

Thank you!!!

**Comment by dinaelhanan** [comment]
@jywarren 
activitesshortcode

**Comment by dinaelhanan** [comment]
@jywarren let me know if it's good to go 👍 also if there's any other issues I can help out with I'd be happy to

**Comment by dinaelhanan** [comment]
@jywarren let me know what you think so we can get this merged :)

**Comment by dinaelhanan** [comment]
@gauravano thoughts?

**Comment by gauravano** [comment]
Hi @dinaelhanan, I think, what @jywarren meant from this comment - https://github.com/publiclab/plots2/pull/5463#issuecomment-482913349 was 

Currently, we show grid using [notes:grid:tagname] which shows thumbnail grid just like you shown in the above comment (where activity:coqui is tagname).

Now, we want to show the thumbnail grid of activities. I think, you'll be copying this code - https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L20-L56 in the function and then would be making changes to fetch activities so this code - https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L190-L221 will help you with that. 

@jywarren I am getting it right?

**Comment by dinaelhanan** [comment]
@gauravano I'm not understanding .. is what I changed in this PR correct? Where / what would I add? I don't get how I would copy those functions.

**Comment by gauravano** [comment]
Let's wait to hear from @jywarren about this [comment](https://github.com/publiclab/plots2/pull/5463#issuecomment-485579713) as I don't want to show you wrong direction. 

Also, you can work on another issue in the meantime. Thanks!

**Pull request closed without merging**
