### PR TITLE
Bypass GitPod SQL .group() error by grouping only in production

### PR DESCRIPTION
**Pull request by jywarren**
Re: #8177 as temp solution:

```
@tags.group(:name) unless Rails.env.development? # for GitPod compatibility; #8117
```

### CODE REVIEW

**Comment by cesswairimu** [comment]
I think the `group` has to come before the `order` and paginate

**Comment by jywarren** [comment]
Works! Can extend this to the users controller... any others too.

It shows duplicate data, but at least it loads:

Screen Shot 2020-10-08 at 4 22 06 PM

**Comment by jywarren** [comment]
o darn, we can't before the pagination:

```
ERROR["test_sort_according_to_followers_ascending", #<Minitest::Reporters::Suite:0x000000000f0f8138 @name="TagControllerTest">, 15.712504287000002]
 test_sort_according_to_followers_ascending#TagControllerTest (15.71s)
Minitest::UnexpectedError:         NoMethodError: undefined method `group' for #<WillPaginate::Collection:0x000000000f0ec158>
            app/controllers/tag_controller.rb:51:in `index'
            test/functional/tag_controller_test.rb:666:in `block in <class:TagControllerTest>'
ERROR["test_sort_according_to_followers_descending", #<Minitest::Reporters::Suite:0x000000000ef1cf30 @name="TagControllerTest">, 15.776017165000013]
 test_sort_according_to_followers_descending#TagControllerTest (15.78s)
Minitest::UnexpectedError:         NoMethodError: undefined method `group' for #<WillPaginate::Collection:0x000000000ef0cef0>
            app/controllers/tag_controller.rb:51:in `index'
            test/functional/tag_controller_test.rb:677:in `block in <class:TagControllerTest>'
 FAIL["test_tag_index", #<Minitest::Reporters::Suite:0x000000001090de30 @name="TagControllerTest">, 16.205822458]
 test_tag_index#TagControllerTest (16.21s)
        --- expected
        +++ actual
        @@ -1 +1 @@
        -["test", "test", "test", "test", "awesome", "awesome", "awesome", "awesome", "awesome", "awesome", "awesome", "awesome", "awesome", "everything", "chapter", "chapter", "chapter", "chapter", "blog", "spectrometer", "test_lego", "blog-featured", "place"]
        +["test", "awesome", "everything", "chapter", "blog", "spectrometer", "test_lego", "blog-featured", "place"]
        test/functional/tag_controller_test.rb:154:in `block in <class:TagControllerTest>'
```

**Comment by jywarren** [comment]
Hmm - `Minitest::UnexpectedError:         ActionView::Template::Error: undefined method `total_pages' for #<Tag::ActiveRecord_Relation:0x000000000f9d00a8>` -- i guess that didn't quite work. 

We could get around this with `pagy` probably, but let's see if we can do better here first...

**Comment by jywarren** [comment]
I'm going to close this as I believe we've resolved GitPod `sql_mode` in https://github.com/publiclab/plots2/pull/8856, now working the remaining gitpod test errors in https://github.com/publiclab/plots2/issues/8893

**Pull request closed without merging**
