### PR TITLE
Added translation to the questions index page.

### PR DESCRIPTION
**Pull request by YusufAbdelaziz**
Fixes issue #9033

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by RuthNjeri — APPROVED** [review]
Thanks @YusufAbdelaziz...this looks good!

@cesswairimu will merge it once she reviews it as well...

**Comment by YusufAbdelaziz** [comment]
Thanks so much!

**Comment by jywarren** [comment]
This is odd, the checks aren't passing -- i'll try to retrigger them by closing and reopening the PR!

**Comment by jywarren** [comment]
sorry, i meant they're not /running/ -- hopefully they will now!

**Comment by jywarren** [comment]
great, looks like they've started now!

**Comment by RuthNjeri** [comment]
@jywarren I think this PR can now be merged?

**Comment by cesswairimu** [comment]
Merging now...Thanks everyone :tada:

**Pull request merged**
