### PR TITLE
Publish Simple-Data-Grapher graphs as a Research Note on Public Lab

### PR DESCRIPTION
**Pull request by IshaGupta18**
For issue https://github.com/publiclab/simple-data-grapher/issues/65
This is the feature implementation for Publish as a Research Note feature 
Here's it's working!
researchnote
I would be explaining the flow in the README.md of SDG, but I have explained most of it in the issue above. I have tried to make bare minimum changes to the existing code, and only one `if-condition` in `editor_controller` and `rich.html.erb`, apart from that, a standard flow is followed. This has been a pretty challenging and time taking implementation! I hope it looks good!

@jywarren @namangupta01 @sagarpreet-chadha @gauravano please take a look!

PS: I would be fixing some of the linting in subsequent commits

### CODE REVIEW

**Comment by IshaGupta18** [comment]
@cesswairimu could you please help me out with the travis problem here? I did try to update my schema but it didn't have effect here

**Comment by cesswairimu** [comment]
Hey @IshaGupta18 I guess you need to change the timestamp here `ActiveRecord::Schema.define(version: 2019_07_08_141804` of `schema.rb.example` to be the same as the one of `schema.rb` that you  currently have locally

**Comment by IshaGupta18** [comment]
@cesswairimu I am trying this one out, let's see if it works! Thanks a ton!

**Comment by jywarren** [comment]
Hi! I will reply longer soon, but just referencing how the existing graphing system was done, which I think is a bit different than here; 

https://github.com/publiclab/PublicLab.Editor/pull/137/files

This uploaded a file and inserted an inline power tag into the node body in the database, not just in the edit template. But is that happening here too, by inserting it above the node body content? Does it work in both markdown and rich modes?

**Comment by jywarren** [comment]
Is this also integrated into #6113? Thanks!

**Comment by IshaGupta18** [comment]
Yes, closing this one too!

**Pull request closed without merging**
