### PR TITLE
Add tweet button to suscription share button

### LINKED ISSUE #2216: Add tweet button to subscription share
### Please describe the problem (or idea)

Currently, when we click on the subscription share button it actually not sharing, it is just showing us the link. 
See here: https://publiclab.org/subscriptions
screen shot 2018-02-04 at 12 44 30 am
We can add tweet button there :
screen shot 2018-02-04 at 12 45 41 am

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Closes #2216

### CODE REVIEW

**Comment by namangupta01** [comment]
How it looks now!
screen shot 2018-02-04 at 12 45 41 am

**Comment by namangupta01** [comment]
Test passed on my local instance. Why it is failing here?

**Comment by ryzokuken** [comment]
p[class=facebook-summary]

**Comment by ryzokuken** [comment]
The failure:

```bash
$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi
fatal: Couldn't find remote ref refs/heads/danger_base
fatal: Couldn't find remote ref refs/heads/danger_head
fatal: Couldn't find remote ref refs/heads/danger_base
fatal: Couldn't find remote ref refs/heads/danger_head
fatal: Couldn't find remote ref refs/heads/danger_base
fatal: Couldn't find remote ref refs/heads/danger_head
fatal: Couldn't find remote ref refs/heads/danger_base
fatal: Couldn't find remote ref refs/heads/danger_head
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/publiclab/plots2
 * [new tag]           v2.0.1     -> v2.0.1
 * [new tag]           v2.1.0     -> v2.1.0
 * [new tag]           v2.2       -> v2.2
/home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.5.9/lib/danger/scm_source/git_repo.rb:128:in `find_merge_base': Cannot find a merge base between danger_base and danger_head. (RuntimeError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.5.9/lib/danger/scm_source/git_repo.rb:16:in `diff_for_folder'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.5.9/lib/danger/danger_core/dangerfile.rb:261:in `setup_for_running'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.5.9/lib/danger/danger_core/dangerfile.rb:271:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.5.9/lib/danger/danger_core/executor.rb:28:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.5.9/lib/danger/commands/runner.rb:68:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.5.9/bin/danger:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/danger:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/danger:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ryzokuken** [comment]
Okay, it fails because https://github.com/danger/danger/issues/768

**Comment by ryzokuken** [comment]
also, https://github.com/publiclab/plots2/pull/1978#issuecomment-357397256

**Comment by ryzokuken** [comment]
Indeed, that is the issue.

screen shot 2018-02-04 at 1 46 40 am

**Comment by namangupta01** [comment]
@ryzokuken Thank you :)

**Comment by jywarren** [comment]
Awesome, thanks all!!! 🎉

**Pull request merged**
