### PR TITLE
Add '# posts by # contributors | # followers' to tag pages

### LINKED ISSUE #6305: Add `# posts by # contributors | # followers` to tag pages
We have 2 types of users we'd like to show counts for on pages like https://publiclab.org/tag/water-quality

1. `contributors` - who have posted using this topic or commented on this topic
2. `followers` - who are following this topic and will get notified when new content is posted to it

We'd like to list them just below the main image banner of the page, where it has small `by views` and `by likes` buttons:

Let's move the `By Views` and `By Likes` buttons to the right to be with the `By Type` dropdown.

They are here: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/views/tag/show.html.erb#L53-L56

We can move them over here: https://github.com/publiclab/plots2/blob/master/app/views/tag/show/_nav_tabs.html.erb

Then let's add this text to the left side where they had been:

`# posts by # contributors | # followers (?)`

of course, substituting counts for each. 

* For posts, use `Tag.find_nodes_by_type([tagname], 'note', false).count`: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/models/tag.rb#L105
* For contributors, use `Tag.contributors(tagname)`: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/models/tag.rb#L74
* For followers, use `Tag.follower_count(tagname)`: https://github.com/publiclab/plots2/blob/master/app/models/tag.rb#L174

Finally, we'd like to use the fontawesome icon `fa-question-circle-o` (https://fontawesome.com/v4.7.0/icon/question-circle-o) at the end of the line, and link that icon to: https://publiclab.org/wiki/contributors (a page which we'll create later!)

We'd love help with this one!

### PR DESCRIPTION
**Pull request by anthony-zhou**
Fixes #6305 (<=== Add issue number here)

Here is a screenshot of the page with the changes I made:
image
The 'by likes' and 'by views' buttons are on the right, and the number of contributors, posts, and followers are listed on the left.
I was unable to add tags on my local installation of the project; that's why number of posts and contributors is 0 in this screenshot. 
Also, I changed the capitalization and height of the buttons on the right side so that they match.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great! Tests return this screenshot:

68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f706c6f7473322d73637265656e73686f74732f363433312d746573745f7461675f706167652e706e67

**Comment by jywarren** [comment]
Could we make this text `#aaa` grey? Thanks a lot!

**Comment by jywarren** [comment]
Also looks like we may need to adjust this system test to the new design?

```
Capybara::ElementNotFound: Unable to find link or button "By Type"
            test/system/tags_controller_test.rb:11:in `block in <class:TagTest>'
```

**Comment by jywarren** [comment]
Thanks a lot!!!

**Comment by anthony-zhou** [comment]
I changed the text color and adjusted the tags_controller_test to fit the new lowercase text format.

**Comment by jywarren** [comment]
Looks perfect! Thanks so much!

**Pull request merged**
