### PR TITLE
Dynamic time increment for graphs

### LINKED ISSUE #4754: Dynamic incremental solution for graphs.
The new graph on stats page has a function https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L247-L264 we want to update this so the increment `x += 604800000;` is changed to get the next value from the array  `months`.

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #4754 

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
@rexagod I had to keep the decimal date format because js was getting it in decimal from ruby and also apexchartjs uses it to generate  `datetime` for the x-axis so that we can generate timeline series which help to get values when zooming in and out.  Take a look and let me know what you think. Thanks.

**Comment by jywarren** [comment]
Hmm, is this ready for merge? Cool!

**Comment by cesswairimu** [comment]
Yeah it is ready

**Comment by jywarren** [comment]
Great work!!!

**Pull request merged**
