### PR TITLE
Added translation key paths to navbar tems

### LINKED ISSUE #7416: Translation Missing for Navbar Items
### Please describe the problem (or idea)

What happened just before the problem occurred? Or what problem could this idea solve?
>The problem occurs when you hover over certain items of the NavBar.
All the items in the Community and Tools drop down menus are affected. Newsletter under the About Us menu is also affected.

Why this is happening:
>The path to the translation key within /config/locales/en.yml is referenced incorrectly for some of the menu items. 
The translation keys are missing for other menu items.

image

https://publiclab.org/

###Solution:
>Many of the Items already have keys in the /config/locales/en.yml 
I've added proper path references the items that already have keys.

****

### PR DESCRIPTION
**Pull request by z-arnott**
Fixes #7416 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by z-arnott** [comment]
Hi @publiclab/reviewers could you please let me know what you think?
Thank you!

**Comment by VladimirMikulic** [comment]
Could you please resolve this issues with Travis? Thanks.

**Comment by z-arnott** [comment]
Hi @VladimirMikulic ,

I've fixed the branch so that all the checks pass.
Are the coverage changes in the Codecov report an issue as well?

Please let me know!
Zoe

**Comment by cesswairimu** [comment]
@z-arnott can we please get a screenshot for this change?  Thanks

**Comment by z-arnott** [comment]
Hi @cesswairimu here is the image. The fix removes the missing translation popup

image

**Comment by SidharthBansal** [comment]
There are some conflicts kindly remove them

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
