### PR TITLE
Removal of read more button and corrected the pagination

### LINKED ISSUE #5618: Significance of "Read more" button on home page
The "Read more" button on homepage directs the user to /blog page.

Screen Shot 2019-04-25 at 4 40 18 PM

We also have a link "More of the blog" which also directs the user to /blog page

Screen Shot 2019-04-25 at 4 40 52 PM

Moreover, we are paginating the blogs. So is "Read more" button actually required?

### PR DESCRIPTION
**Pull request by AnshitaVishwa**
Fixes #5618  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by AnshitaVishwa** [comment]
@jywarren and @gauravano  Please review this PR. Thanks!!

**Comment by gauravano** [comment]
Hi @AnshitaVishwa, I tried your PR by pushing onto unstable.publiclab.org. The button is removed as issue demands but the pagination bar is not working. Would you like to look into that? Thanks!

**Comment by AnshitaVishwa** [comment]
@gauravano  would you please help me out in correcting the pagination fault?
Thank you.

**Comment by CleverFool77** [comment]
Hi @AnshitaVishwa Can I know that what problem you are coming across for pagination ?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
