### PR TITLE
Improved Profile dropdown to add a Font awesome icon

### LINKED ISSUE #5074: Improve the profile dropdown on navbar
# Description
Currently to go to users profile , one has to click on the profile option on navbar. This doesn't open up to profiles page though. However leads to another dropdown where user profile can be selected. This is misleading as the drop down has various other options as well one being profile.

# Current Behavior

presentprofile

# Expected Behavior

profilechange

Maybe something like this where we show just the username on navbar and clicking this opens all the other options like profile, edit profile etc.

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #5074 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### Final look

bestsize

### CODE REVIEW

**Comment by ananyaarun** [comment]
@jywarren , Updated to the icon. Kindly review :) Thanks !

**Comment by avsingh999** [comment]
@ananyaarun Great I really like this update :tada:  but  can you please confirm it's also working fine in short screen (mobile view).
thanks :smile:

**Comment by ananyaarun** [comment]
@avsingh999 , Here are some Mobile view screen shots.

mobile

mobile1

**Comment by jywarren** [comment]
Great work!!! 🙌🏽🎉

**Pull request merged**
