### PR TITLE
Track Dockerfiles accross instances.

### PR DESCRIPTION
**Pull request by icarito**
These are our actual compose files. We should track variants at the repo.
Also I'll look to add Jenkins configuration here too somehow.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Cool! is this ready for merging into master? Thanks!!!

**Comment by jywarren** [comment]
Hi @icarito this is still failing tests -- anything I can do to help it along?

**Comment by Gauravano** [comment]
hi @icarito I have been facing same error in #2744 but just now test got passed.

**Comment by Gauravano** [comment]
retriggering build

**Comment by icarito** [comment]
Yes we were hit by the same issue with the updated docker tag. This is ready to merge to start.

**Comment by jywarren** [comment]
This is ready to merge to master? Will this resolve the issues other people are seeing on running Travis tests?

**Comment by icarito** [comment]
Yes! This will resolve issues people are seeing in travis.

**Pull request merged**
