### PR TITLE
Updated README to Ruby 2.7.3

### PR DESCRIPTION
**Pull request by anirudhprabhakaran3**
Changes the README installation docs to mention Ruby 2.7.3 instead of Ruby 2.6.6

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
Thanks for updating the docs @anirudhprabhakaran3. Can you also update the one in https://github.com/publiclab/plots2/blob/c9581180042bb693a50562b512852182bd119925/doc/PREREQUISITES.md? Thank you!

**Comment by anirudhprabhakaran3** [comment]
yes, I've updated that.

I noticed that we are also specifying the rvm version in the `.travis.yml` file. Should I change the version there too?
https://github.com/publiclab/plots2/blob/c9581180042bb693a50562b512852182bd119925/.travis.yml#L5-L6

**Comment by TildaDares** [comment]
@anirudhprabhakaran3 I think you can update that too

**Comment by anirudhprabhakaran3** [comment]
Sorry for the late response! I've made the changes

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Great, thank you!!

**Pull request merged**
