### PR TITLE
Update _related.html.erb

### PR DESCRIPTION
**Pull request by aayushgupta1**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

This is for the problem #949. I am first timer and am interested in contributing.

### CODE REVIEW

**Comment by ryzokuken** [comment]
@aayushgupta1 Please close this one if you have made another PR for the same issue. Thanks :)

**Comment by aayushgupta1** [comment]
@ryzokuken sure

**Comment by jywarren** [comment]
Hi, I believe this was solved in a duplicate PR; thanks!

**Comment by aayushgupta1** [comment]
yeah @jywarren . I forgot to close this actually.

**Pull request closed without merging**
