### PR TITLE
Add css to set width of tooltip

### LINKED ISSUE #5045: Add css to set width of tooltip
Refer #5027 
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [wiki.css](https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/wiki.css) in the `plots2` repository to add css for the tooltip.
Added css should set the maximun width of the tooltip.
Code of this format can be followed -

`.tooltip-inner {
    max-width: 500px
}`

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by aggarwal19**
Fixes #5045(<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
set-width-of-tooltip

### CODE REVIEW

**Comment by aggarwal19** [comment]
Okay , I added the screenshot in previous comment , please have a view. 
Thank you

**Comment by ananyaarun** [comment]
@aggarwal19 , A screen shot of the changes in the local installation if possible ? That will help all of us see if these changes work right locally before merging.

**Comment by aggarwal19** [comment]
@ananyaarun I'm not able to understand  that from where I have to take a screen shot . Please tell me .
Thanks!

**Comment by ananyaarun** [comment]
@aggarwal19 , U'll have to locally install plots2 in ur system make changes and then view the changes on ur local host. Doing so you shall be able to see and check for urself if the css change for the tooltip works fine. After this take a screen shot of that and upload it here. Thanks :)
Feel free to ask for help if u face any issues during installations. The instructions are in readme.md

**Comment by aggarwal19** [comment]
@ananyaarun I already did the installation and I also did the login , but after that I was not able to understand that from where I have to take screen shot .  Means there are lots of project on that page , so exactly from where I have to take a screen shot.
Thanks!

**Comment by ananyaarun** [comment]
@aggarwal19 , check out this link http://localhost:3000/wiki/donate
and this http://localhost:3000/wiki/donate/comments

**Comment by aggarwal19** [comment]
okay

**Comment by aggarwal19** [comment]
setwidth

**Comment by ananyaarun** [comment]
@aggarwal19 Thanks You so much ! Can u also add a gif to show and check if the tooltip width is consistent across the popups on navbar ? This was the main issue actually, That the width was not consistent across popups.

**Comment by aggarwal19** [comment]
okay

**Comment by subhahu123** [comment]
@aggarwal19  please follow proper indentation also

**Comment by aggarwal19** [comment]
Yes , I will do it , but right now I'm busy as my exams are going on .
Sorry for this .

**Comment by gauravano** [comment]
No hurry here. All the best for your exams!

**Comment by SidharthBansal** [comment]
How your exams went?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab
cc/ @jywarren @gauravano

**Pull request closed without merging**
