### PR TITLE
Add some css transitions effect #4688

### PR DESCRIPTION
**Pull request by yash98gupta**
new

### CODE REVIEW

**Comment by gauravano** [comment]
Hey @yash98gupta, please add the issue number in the PR. Thanks!

**Comment by gauravano** [comment]
Some suggestions:
1. Raising PR on the separate feature branch, can help you in keeping your master branch clean.
2. Adding the `Fixes #[issue-number]` to the PR ensures that the tagged issue is closed when the PR gets merged so it's a good practice. 

Thanks!

**Comment by avsingh999** [comment]
@yash98gupta  I think It would be better if we can also add transitions when clicking for hiding.
sorry for late reply.
 thanks : )

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
