### PR TITLE
body_preview method

### PR DESCRIPTION
**Pull request by nickstaggs**
* [ ] All tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

This is just the opening of the pull request. I will hopefully have the method done tomorrow along with a unit test.

### CODE REVIEW

**Comment by jywarren** [comment]
Great, thanks!

**Comment by nickstaggs** [comment]
Hey @jywarren I have this which seems to work:

```ruby
def body_preview
	if !!(self.match(/#+.+\n+/))
		self.split(/#+.+\n+/,5)[1]
	else
		self
	end
end
```

Any thoughts and how would I go about creating the unit test?

**Comment by jywarren** [comment]
Sure -- you could do a test like:

```ruby
revision = node(:one).latest
revision.body = "## Introduction\n\nThis is my post"
assert_nil revision.body_latest.match("Introduction")
```

although I'm not sure `assert_nil` works that way... or what `match` returns if there's no match, but you get the idea.

I do notice though that you're using `self.match` -- but you might want to do `self.body.match` and `self.body.split(...)` since `self` returns the whole record and not just the body text.

**Comment by jywarren** [comment]
Hi, Nick - i also noticed you're working on your master branch -- it'll be easier if you move into a named feature branch -- [read more here](https://publiclab.org/wiki/contributing-to-public-lab-software). 

This will enable you to rebase changes on top of the latest master. It's not essential, but it's good practice.

**Comment by nickstaggs** [comment]
@jywarren should i delete this pull request and create another with a feature branch, then?

**Comment by jywarren** [comment]
If you're going to rebase it, which would be great, then yes.  But if you
get stuck, I'm happy to help you with the rebase using just this branch.
Thanks!

**Pull request closed without merging**
