### PR TITLE
Fix the question form and add test

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5839 part

### Earlier

58964309-4c9dd100-87cc-11e9-916a-3dae7e9f26b9

### After Changes

Screenshot from 2019-06-21 11-18-11

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by CleverFool77** [comment]
Maybe I should decrease the width ? But to what extent ?

**Comment by jywarren** [comment]
Very cool! If you want to add an automated screenshot of this to this PR, see this for how we sign in within a system test, so we can see stuff as a logged-in test user: 

https://github.com/publiclab/plots2/blob/251e548bf5bdcf13f8cbb89ec8f32460149fed5f/test/system/dashboard_test.rb#L6-L22

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by CleverFool77** [comment]
I'm haven't resolved it yet. I'm thinking of breaking this issue into two parts and making first timers for this.

**Comment by CleverFool77** [comment]
Or maybe I should resolve it myself?

**Comment by CleverFool77** [comment]
Hi @jywarren I'll fix this soon.

**Comment by CleverFool77** [comment]
Hi @jywarren 
Just added the screenshot test for question post form and pushed it in this PR.
If some pages are left, then I would like to add screenshot tests for them too.
Thanks !!

**Comment by CleverFool77** [comment]
The test which is failing doesn't seem to be related to this PR :thinking: 
```
 FAIL["test_graph", #<Minitest::Reporters::Suite:0x00005625f7a0bf40 @name="TagSelectionTest">, 0.2952704940000217]
 test_graph#TagSelectionTest (0.30s)
        Expected: 16
          Actual: 20
        test/unit/tag_selection_test.rb:12:in `block in <class:TagSelectionTest>'
```

**Comment by CleverFool77** [comment]
Now All checks have passed :tada: :tada:

**Comment by jywarren** [comment]
Awesome!!

**Pull request merged**
