### PR TITLE
Subscribers over time

### LINKED ISSUE #4925: Subscribers over time
Display the # of subscribers over time on tag stats pages like this: https://publiclab.org/tag/ui/stats

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #4925

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Oh wow! @skilfullycurled just a heads up on this. I wasn't sure if you and @cesswairimu were synced. This will be great! Also, if you rebase, you can add a screenshot test get automated screenshots!

**Comment by cesswairimu** [comment]
Will do, thanks @jywarren. Am sorry @skilfullycurled I had no idea you are working on this, please let me know how far along you are on this and I can close this or work on top of what you have thanks.

**Comment by skilfullycurled** [comment]
Oh, no no, @cesswairimu.  That's very thoughtful of you but I think @jywarren was giving me a heads up because a) I like stats! and b) I'm working on filtering out past spam from users.  I don't think that will effect this since it'll just change the figures but it will be nice to see places where the user count is unusually high.  Great work!

**Comment by skilfullycurled** [comment]
Oh, wait, @cesswairimu, he may be referring to #5793.  Does this PR mean we do not need the migration anymore?

**Comment by cesswairimu** [comment]
Oh, yeah, @skilfullycurled I had to add the migration before I could continue....did you get to write the migration yet?

**Comment by skilfullycurled** [comment]
No problem, @cesswairimu, it seems like it should not have been made a sepperate issue since if I'm understanding you correctly, this issue couldn't be closed without doing it.  

And the good news is that it confirms what I learned about how to add it which was one of my questions so thanks for the help! ; )

However, I still think this is worth discussing in #5793 for two reasons.

1) @jywarren thought there would have to be migrations for both tag_selections and term_node (I think?  There were two.)

2) Backfill options of which I wrote about a few of varying complexity.  Enhancing the backfill could become it's own issue.  Wouldn't time.now (or I forget the variable) make everything subscribed to today?

Anyway, would be great if you could chime in.

**Comment by cesswairimu** [comment]
Oh yeah thanks for bringing that up @skilfullycurled ...I updated all the existing records timestamps to have `Time.now`..what do you think about this? also quite not sure how we should display on the graph...maybe we can have a note that `we started tracking from....and only show the graph as from the next day  from that day. :thinking: but would love to your thoughts.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md may help some -- and I can't remember completely but I think it's possible I asked for timestamps on 2 models because we will need them for ordering pins as well, not just for subscriptions, so apologies if I added complexity; i just tend to think fewer migrations is a good thing. 👍 

I like "we've started tracking from"!

**Comment by jywarren** [comment]
And to clarify - I wanted to add timestamps to the `NodeTag` MODEL, not table name, which is `community_tags` - so that we can know when a node was pinned (which uses a NodeTag record). Sorry for the confusion there: https://github.com/publiclab/plots2/blob/master/app/models/node_tag.rb

**Comment by jywarren** [comment]
Thanks all!!!!

**Comment by cesswairimu** [comment]
Thanks Jeff. I understand `community_tags` has a `date` column do we want to remove this or should I just add the timestamps and leave the `date` column

**Comment by jywarren** [comment]
Oh! well, is it a timestamp? Sometimes the former Drupal tables have a timestamp but its not in a Rails native format, so we use a converter method. Could that work? If `community_tags` has valid date data, maybe we can use that?

**Comment by skilfullycurled** [comment]
@cesswairimu, regarding the `time.now` question, here are a few considerations:

For the sake of clarity, I am going to refer to `time.now` as `time.merge` since that will eventually be the "now".

1. Depends on the limitations put on the visualization on the page.  If the page doesn't allow you to query information from the day after whenever `time.merge` is run, then it's fine because in that technical sense, that day will be of the same value as 4000 BC.

2) However, there might be future situations where we want to have both the tag data as well as some other data that exists prior to `time.merge`. This is where I think it would be safer to use a date prior to all of the data we have such as 1/1/2000.  This way, no one can search for it, and it will never cause a load on the server.  That's a pretty small change code wise I think and it would simplify any potential future queries.

3) We could log a sepperate enhancement issue to actually give these tags dates using the following query.  Assuming that each `tag_selection` is attached to some content node, then we could use the `created_at` or `updated_at` of the attached content to approximate the `created_at` of the `tag_selection`. It's jut an approximation because they could have created the content with two tags and than added another later but it would be a good educated guess.

**Comment by skilfullycurled** [comment]
Oh, wait, @cesswairimu and @jywarren, before we merge the [community_tags commit](https://github.com/publiclab/plots2/pull/5875/commits/9e9d5688105a199dbfde7742b7ed624eb7bf2d2d), can check to see if the `date` field on `community_tags` actually has a date in it or if it's just empty?  If there is a date, then can we convert that to a timestamp instead of updating it to time.now?  This way we can have timestamps but we won't loose any fidelity on the data we already have.

**Comment by cesswairimu** [comment]
Aha! good idea... I just checcked the date data are nil(could be because they are invalid) but others have data not sure if the `date` column is updated during creation but I can look more into it this could be great if it is. Thanks...

> Oh, wait, @cesswairimu and @jywarren, before we merge the [community_tags commit](https://github.com/publiclab/plots2/pull/5875/commits/9e9d5688105a199dbfde7742b7ed624eb7bf2d2d), can check to see if the `date` field on `community_tags` actually has a date in it or if it's just empty? If there is a date, then can we convert that to a timestamp instead of updating it to time.now? This way we can have timestamps but we won't loose any fidelity on the data we already have.

**Comment by cesswairimu** [comment]
> @cesswairimu, regarding the `time.now` question, here are a few considerations:
> 
> For the sake of clarity, I am going to refer to `time.now` as `time.merge` since that will eventually be the "now".
> 
> 1. Depends on the limitations put on the visualization on the page.  If the page doesn't allow you to query information from the day after whenever `time.merge` is run, then it's fine because in that technical sense, that day will be of the same value as 4000 BC.
> 
> 1. However, there might be future situations where we want to have both the tag data as well as some other data that exists prior to `time.merge`. This is where I think it would be safer to use a date prior to all of the data we have such as 1/1/2000.  This way, no one can search for it, and it will never cause a load on the server.  That's a pretty small change code wise I think and it would simplify any potential future queries.
> 2. We could log a sepperate enhancement issue to actually give these tags dates using the following query.  Assuming that each `tag_selection` is attached to some content node, then we could use the `created_at` or `updated_at` of the attached content to approximate the `created_at` of the `tag_selection`. It's jut an approximation because they could have created the content with two tags and than added another later but it would be a good educated guess.

Awesome outline will implement this logic. Thanks so much @skilfullycurled

**Comment by cesswairimu** [comment]
@skilfullycurled the date column is not populated during create with a timestamp, by default it is `0`

**Comment by cesswairimu** [comment]
@skilfullycurled 
- For `tag_selections` I have changed the `created_at` of all of the existing records to 1/1/2000.
- For `community_tags` where `date` column has a value I have used that as the `created_at` value. Those without a date value I have used  `1/1/2000`.(Let me know what you think about this) Thanks

**Comment by cesswairimu** [comment]
If there are no subscriptions tracked during the period selected.
notrack

If there its a range that has subscriptions
track

Full page "tag/stats"
2019-06-14-14-47-unstable publiclab org

**Comment by skilfullycurled** [comment]
@cesswairimu, that sounds perfect.  Thanks for being open to that, I hope I didn't make life that much more difficult.  In line with 4000 BC I will be referring to 2000 as "10 BPL".  Anyway...great commit, looking forward to seeing the new features it will enable!

**Comment by cesswairimu** [comment]
@publiclab/reviewers kindly review

**Comment by jywarren** [comment]
Hooray!!! Merging, and we should be able to test it out on stable once it publishes. Thanks for a tremendous job!!!!! 🎉

**Comment by jywarren** [comment]
cc @ebarry once you get back!

**Pull request merged**
