### PR TITLE
Added div with class "text-center" on line 77

### PR DESCRIPTION
**Pull request by codesterlife**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by aSquare14** [comment]
Please add issue number

**Comment by aSquare14** [comment]
@codesterlife  Why is it showing `codesterlife wants to merge 2 commits into publiclab:master from unknown repository`
it should be `codesterlife wants to merge 2 commits into publiclab:master from yourrepo:yourbranch`

**Comment by aSquare14** [comment]
Also, you have two more similar PRs https://github.com/publiclab/plots2/pull/3771
https://github.com/publiclab/plots2/pull/3770
. Please close two and work on only one PR for a particular issue.

**Comment by SidharthBansal** [comment]
Thanks for contributing at Public Labs.
This issue seems to be completed by someone else. You can look at other issues to help us.
Thanks

**Pull request closed without merging**
