### PR TITLE
[Outreachy]Topic Cards Display And Count

### PR DESCRIPTION
**Pull request by RuthNjeri**
Fixes https://github.com/publiclab/plots2/issues/8997

To review changes from this PR, see last [commit ](https://github.com/publiclab/plots2/pull/9007/files/48d6b2cc52657fd620fd68ed4bd5bdd8b39dd018..6eda4870ecebccb757528bce495a7c8c431b21be)

PR https://github.com/publiclab/plots2/pull/9006 should be merged first then this one.

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Before
Screenshot 2021-01-13 at 17 03 45

After
Screenshot 2021-01-13 at 17 06 27

### CODE REVIEW

**Review by jywarren — APPROVED** [review]
This looks great. Love the tests -- is it ready to merge? Thank you!!!

**Comment by RuthNjeri** [comment]
Thanks @jywarren it's ready to merge now 🚀

**Comment by RuthNjeri** [comment]
But after the tests pass 😄

**Comment by jywarren** [comment]
Great!!!

**Pull request merged**
