### PR TITLE
Seeds for database

### PR DESCRIPTION
**Pull request by rarrunategu1**
Fixes #0000 (<=== Add issue number here)

Creates 20 unique users to db/seeds.rb for use in testing.  Tested it and all users were created.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by rarrunategu1** [comment]
Rewinded the master branch and rebased due to plotsbot error above

**Comment by rarrunategu1** [comment]
Hello @publiclab/reviewers ,
I received an error 
ActiveRecord::RecordInvalid: Validation failed: Email has already been taken, Username has already been taken, That username is already taken. If this is your username, you can simply log in to this site.

I followed someone's advice to drop the database and recreate it because I thought I had run the command multiple times and was now hitting uniqueness validation.  I used the commands rake db:drop:all and then rake db:create but now after seeding it, it tells me to rails db:migrate but that caused an error that i can't figure out now.  

SQLite3::SQLException: near "ENGINE": syntax error: CREATE TABLE "comments" ("cid" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "pid" integer DEFAULT 0 NOT NULL, "nid" integer DEFAULT 0 NOT NULL, "uid" integer DEFAULT 0 NOT NULL, "subject" varchar(64) DEFAULT '' NOT NULL, "comment" text(2147483647) NOT NULL, "hostname" varchar(128) DEFAULT '' NOT NULL, "timestamp" integer DEFAULT 0 NOT NULL, "status" integer(1) DEFAULT 0 NOT NULL, "format" integer(2) DEFAULT 0 NOT NULL, "thread" varchar NOT NULL, "name" varchar(60), "mail" varchar(64), "homepage" varchar) ENGINE=MyISAM

Would you be able to offer some direction on this?  I'm new to the rake db process and I'm not sure if I did something wrong there.

**Comment by CoderJolly** [comment]
rails db:setup (though this will load the seed as well, but you can run rake db:seed, just in case)
rails active_storage:install
rails db:setup
rails db:seed
rails db:migrate

I faced the same issue once, and doing this worked fine bt still I will look into the case with rake:db:drop:all

**Comment by cesswairimu** [comment]
Try running  `rake db:reset` That should drop, create and seed the database for you

**Comment by rarrunategu1** [comment]
Thank you.  Hopefully this solves the issue.

**Comment by rarrunategu1** [comment]
> rails db:migrate

Hello @CoderJolly,  Your method seems to created a new file in the database.  Is that what it's supposed to do?  Again I'm not to0 familiar with this process... I'm still learning.

**Comment by CoderJolly** [comment]
> > rails db:migrate
> 
> Hello @CoderJolly, Your method seems to have created a new file in the database. Is that what it's supposed to do? Again I'm not to0 familiar with this process... I'm still learning.

Actually what @cesswairimu suggested will do it faster, so no issues. There is nothing like my way or your way, I also learnt from here.
P.S. We all are learners

**Comment by rarrunategu1** [comment]
I did try both ways but with reset I still received the same error and with your suggestion I created a new file.  I didn't know if that's what it's supposed to do.  That was my question.  I googled but found no information regarding that.  Maybe the error is somewhere else.  I don't quite understand what it could be though.  I'll dig around some more.

**Comment by jywarren** [comment]
Hi @rarrunategu1 what file was created? Let me check your PR code, hang on a sec...

**Comment by jywarren** [comment]
Ah, the `ENGINE=MyISAM` error is because that's a directive for mysql, but it looks like you're running in `sqlite` -- can you check that your `database.yml` file is pointed at a `plots2` database or something like that? You may need to create such a database with `create database 'plots2';` (if I remember the sql correctly... in any case the same statement as what you created your `mapknitter` database with). I think that'll work!

**Comment by rarrunategu1** [comment]
Someone already updated the seeds.rb file to use faker and make 5 unique users.  I feel like this is no longer necessary.  What do you think @jywarren?  Close it?

**Comment by jywarren** [comment]
Sure, sounds good!

**Pull request closed without merging**
