### PR TITLE
add email validate

### PR DESCRIPTION
**Pull request by Paarmita**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

Solves #1996

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
We are glad to see your Pull request.
Thanks for the PR. I have mentioned some changes go for it.
Also, write a test to demonstrate that pratima@gmail will not lead to signup in the  plots2/test/unit/user_test.rb

**Comment by jywarren** [comment]
Hi! Looks like you're having some issues -- maybe @publiclab/reviewers can help out. You can always look through the output of the tests to see what the errors are, by clicking on the little red X next to your last commit:

https://travis-ci.org/publiclab/plots2/builds/328785772

Thanks for your contribution!! I'm sure we'll figure it out.

**Comment by ryzokuken** [comment]
Hi, @Paarmita! Thanks for being so patient and kudos for taking this step to improve publiclab. It really means a lot to all of us.

I see your pull request is getting an error, specifically: `SyntaxError: /app/app/models/user.rb:38: empty range in char class: /\A[\w+-.]+@[a-z\d-.]+.[a-z]+\z/i`

This most probably means that there's something wrong with the Regex, so I'd advise you to kindly take a look at it again.

**Comment by ryzokuken** [comment]
Spoiler alert: `\A[-\w+.]+@[\da-z-.]+.[a-z]+\z` seemed to work.

**Comment by jywarren** [comment]
http://rubular.com/ could be helpful to test out regex!! Thanks!

**Comment by Ankit-Singla** [comment]
@ryzokuken `\A[-\w+.]+@[\da-z-.]+.[a-z]+\z` doesn't work, because of the `.` that matches any character except for the newline character. It should be replaced by `[.]` for it to actually match the **.** character.

**Comment by ryzokuken** [comment]
@Ankit-Singla idk, you should use whatever works in the tests, I tried that Regex on rubular and it seemed to work.

**Comment by jywarren** [comment]
@Paarmita @Ankit-Singla @ryzokuken how's this coming along? Sorry this is a little more complex -- just a suggestion -- you can take a test string and input it in http://rubular.com with the regex you're using, like this: 

http://rubular.com/r/vKHN1A7H4k

@Ankit-Singla can you offer an example of why the above regex would fail, and how your proposed improvement would be better? Thank you!

**Comment by Ankit-Singla** [comment]
@jywarren The regex suggested by @ryzokuken ( `\A[-\w+.]+@[\da-z-.]+.[a-z]+\z` ) doesn't work because it doesn't match the `.` in the email address correctly.
http://rubular.com/r/YMcSHIJzAT
You can see here that it gives a **match** when the user email is "jeff@publiclab". Thus, it doesn't enforce the presence of `.` in the email address.
I suggested ( `\A[-\w+.]+@[\da-z-.]+.[a-z]+\z` ), replacing  the `.` by `\.` or `[.]`, which matches the `.` literally, and not the characters represented by `.`.

**Comment by ryzokuken** [comment]
@SidharthBansal was this already fixed in a PR?

**Comment by SidharthBansal** [comment]
Parmita left and ankit was doing this. So I closed this pr

**Pull request closed without merging**
