### PR TITLE
Sidebar powertag improvisations

### LINKED ISSUE #9776: Differentiate between tags and power tags
@publiclab/mentors  this is what I've thought of to differentiate between tags and power tags. Please let me know your views on this.

1. Change the location of power tags - currently we add normal tags and power tags in the same place. Instead, we can have another input box for power tags, hovering over which will tell us what a power tag is.
2. Prompt users to enter the type of power tag before adding it - this will help to add the power of the power tag to all the tags on the note and not just the one it is added with. (Ref #6593)

power_tag_mockup

3. Follow button should appear only on normal tags and not on power tags when not following. (Ref #6593)
4. Different bootstrap style for power tag cards - maybe have a different color and switch over to 'cards' from 'badges'.

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #9776 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
2 changes that I've made
1. The text `This is a power tag`in the small lozenge tags links to `https://publiclab.org/wiki/powertags`.
2. Added a favicon in the miniCard for power tags to explain what they are. It links to the wiki page on power tags.

t1

@jywarren @ebarry please let me know your views on this. Thanks!

**Comment by ebarry** [comment]
Looks great to me! @jywarren hoping you can comment / advise on the placement of icons on the minicard?

**Review by Tlazypanda — APPROVED** [review]
Hey @Manasa2850 LGTM :tada: Hmm...the placement can be tricky here this looks great  - just also suggesting some other options for placement but let's wait for @jywarren to comment. 
- might  may be next to the elipsis symbol 
- might be on the bottom right instead of left

Thanks for working on this :tada:

**Comment by jywarren** [comment]
I think we discussed this option but we might just be able to leave off followers counts for power tags, since they're not really used as "groups" or "forums" in the same way. What if we did that, then moved the (?) to the same line, for an all-in-one-line version like this?

**Comment by Manasa2850** [comment]
Done @jywarren!!
This is how it looks now

temp

**Review by Tlazypanda — APPROVED** [review]
@Manasa2850 LGTM :tada:

**Comment by ebarry** [comment]
looks gorgeous!

**Comment by jywarren** [comment]
Hooray!!!!

**Comment by jywarren** [comment]
Beautiful.

**Pull request merged**
