### PR TITLE
Added initial check for valid email on password reset

### PR DESCRIPTION
**Pull request by Souravirus**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
Solved bug #2315

**Comment by Souravirus** [comment]
@ryzokuken is this the correct way to show the invalid emails or should I show errors from model validations

**Comment by ryzokuken** [comment]
@Souravirus this would technically work thanks to HTML5, but I suppose we should aim for a better, more customized way to do this using custom javascript code. Given that we use jQuery, it should still be pretty simple.

**Comment by Souravirus** [comment]
okk I would try that @ryzokuken

**Comment by seafr** [comment]
@Souravirus please take a look at PR #2169 and consider @jywarren's comments on non-latin characters.

**Comment by Souravirus** [comment]
@seafr I would check that

**Comment by Souravirus** [comment]
@ryzokuken @seafr Please check the changes I have made through jquery

**Comment by jywarren** [comment]
Hi! Thanks -- could you upload a screenshot of what happens if your email doesn't validate? Thank you!

**Comment by Souravirus** [comment]
screenshot from 2018-02-15 21-35-06

**Comment by jywarren** [comment]
Awesome -- @publiclab/reviewers what do you think?

**Comment by jywarren** [comment]
This looks great. Thank you very much!

**Comment by Souravirus** [comment]
thanks @jywarren

**Pull request merged**
