### PR TITLE
OAuth status fix

### LINKED ISSUE #4522: OAuth Login fail and Form Login fail for some users
loginfail

I already had an account created through Github with username kevinz_qu.

Chrome, Windows 10

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #4522

### CODE REVIEW

**Comment by jywarren** [comment]
```

ActiveSupport::MessageVerifier::InvalidSignature
ERROR["test_user_creation_with_create_with_omniauth", #<Minitest::Reporters::Suite:0x000056441ee414f8 @name="UserTest">, 136.40173582]
 test_user_creation_with_create_with_omniauth#UserTest (136.40s)
NoMethodError:         NoMethodError: undefined method `[]' for nil:NilClass
            app/models/user.rb:405:in `create_with_omniauth'
            test/unit/user_test.rb:44:in `block in <class:UserTest>'
ERROR["test_user_with_duplicate_username_creation_with_create_with_omniauth", #<Minitest::Reporters::Suite:0x000056441ef8ded8 @name="UserTest">, 136.474044554]
 test_user_with_duplicate_username_creation_with_create_with_omniauth#UserTest (136.47s)
NoMethodError:         NoMethodError: undefined method `[]' for nil:NilClass
            app/models/user.rb:405:in `create_with_omniauth'
            test/unit/user_test.rb:57:in `block in <class:UserTest>'
```

**Comment by gauravano** [comment]
Error due to #4599 test which passed earlier! But giving error for build, I will revert that PR tomorrow. Retriggering build currently.

**Comment by jywarren** [comment]
Huh but why did the 3rd commit pass? I thought it's testing the problem...

**Comment by jywarren** [comment]
Oops I mean 4th

**Comment by gauravano** [comment]
Actually, the test in #4599 was responsible for the error in Camila's PR too some hours earlier. can you take a look at #4599

**Comment by gauravano** [comment]
Seems ready :tada: :100: !

**Comment by gauravano** [comment]
Merged :balloon: :balloon:

**Pull request merged**
