### PR TITLE
Update settings.html.erb translation line

### LINKED ISSUE #9361: Small change to notifications settings page to remove extra + character
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/users/settings.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/users/settings.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -64,7 +64,7 @@
   <% end %>
   
   <br />
-  +<h4><b><%=translation('users.settings.email_notifications')%> </b></h4>
+  <h4><b><%= translation('users.settings.email_notifications')%> </b></h4>
 
   <div style="display: inline-flex; justify-content: space-between; width: 90%;">
     <span><%=translation('users.settings.weekly_digest')%> </span>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by Onihani**
small change made

Fixes #9361 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Onihani** [comment]
@RuthNjeri please review my pull request

**Comment by RuthNjeri** [comment]
Hi @Onihani, which issue is this issue fixing? Please add the issue number on the description of the Pull Request, it will help us know what the fix is for. Thank you.

**Comment by Onihani** [comment]
@RuthNjeri I just added the issue number

**Comment by pydevsg** [comment]
@Onihani seems like you have added PR Issue no. instead of Issue No.
Please fix it.
Also, please add a screenshot to the UI change if any .

**Comment by Onihani** [comment]
Thanks @pydevsg, I just updated to the issue number

**Comment by pydevsg** [comment]
Cool

**Comment by Onihani** [comment]
Hi please can someone review my pull request

**Review by RuthNjeri — APPROVED** [review]
Thanks for working on this @Onihani and for the reviews @pydevsg 🎉

**Comment by RuthNjeri** [comment]
Not sure why I am unable to merge this PR... but I have added the `ready to merge` label.

**Comment by Onihani** [comment]
> Not sure why I am unable to merge this PR... but I have added the `ready to merge` label.

Can i create a new pull request for the issue

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Hi @RuthNjeri i think perhaps it requires 2 approvals? We can adjust that if it's coming up a lot, or if you're able to ask someone else in the chatroom to review, there's a relatively large group of people who can, and we can also recruit more reviewers in #9032  or https://github.com/publiclab/plots2/issues/4707 maybe. 

Or, because this PR probably doesn't need extra reviewing, we could ease the rules and decide we can bypass the 2 reviewers rule for some PRs! 

Thanks!!!

**Comment by jywarren** [comment]
Thanks @Onihani for your contribution, this looks great!!!

**Comment by RuthNjeri** [comment]
Thanks, @jywarren, I think for now, we can leave it as it is... since I can approve it and add the `ready to merge` label. If I keep encountering it, we can circle back to adding more reviewers or easing the rules.

No need for another PR @Onihani , thanks for helping us out 🎉

**Pull request merged**
