### PR TITLE
Fix emoji response for Bootstrap 4

### LINKED ISSUE #5647: Liking/emoji response updates for Bootstrap 4
Just noting that in Bootstrap 4, the emoji response systems need a little styling help!

https://stable.publiclab.org/notes/warren/03-04-2019/testing-post#c17743

image

### PR DESCRIPTION
**Pull request by dinaelhanan**
Fixes #5647 
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by dinaelhanan** [comment]
@publiclab/reviewers

**Comment by jywarren** [comment]
Awesome! Can you share a screenshot of your fixes? Thank you!!!

**Comment by dinaelhanan** [comment]
@jywarren I'm having issues on c9. When I click a note, this comes up:
image
any ideas?

**Comment by jywarren** [comment]
ah! I think you may have to run `rake db:migrate` there, since we've
modified the database!

**Comment by dinaelhanan** [comment]
@jywarren When I run rake db:migrate I get `I, [2019-05-14T23:05:45.669200 #5034]  INFO -- sentry: ** [Raven] Raven 2.9.0 configured not to capture errors: Not configured to send/capture in environment 'default'
W, [2019-05-14T23:05:46.353605 #5034]  WARN -- Skylight: [SKYLIGHT] [3.1.5] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)`

**Comment by jywarren** [comment]
I think that's all right! Are you on the latest master branch code?

**Comment by dinaelhanan** [comment]
@jywarren yes, I think so:
https://github.com/publiclab/plots2/compare/master...dinaelhanan:emojiFix

**Comment by sashadev-sky** [comment]
@dinaelhanan @jywarren I get the sentry / skylight notice too that isn't a problem. I was actually failing the same test that you're failing recently and I did a rebase (https://github.com/publiclab/plots2/pull/5659) and it fixed it. Perhaps this may fix it for you?

**Comment by sashadev-sky** [comment]
@dinaelhanan for the other issue I don't know about using c9 but when I get this type of error because of database updates i fix it by clearing my cache: `bundle exec rake tmp:cache:clear`

**Comment by ViditChitkara** [comment]
Hi @dinaelhanan , would you mind trying Comment.last.reply_to in 'rails console' in your terminal. There might be a case that the migration where the 'reply_to' column is added to comments may not have run.
Thanks

**Comment by dinaelhanan** [comment]
@ViditChitkara it's still doing the error above :(

**Comment by dinaelhanan** [comment]
@ViditChitkara that didn't work :( @sashadev-sky I am trying to rebase, but for some reason after I force pushed it's saying the PR is closed and merged?

**Comment by dinaelhanan** [comment]
@ViditChitkara I tried this but it didn't work :(

**Comment by dinaelhanan** [comment]
@sashadev-sky I tried your suggestion but when I force pushed, it closed the PR, it also says that it got merged??? I'd appreciate some help :/

**Comment by sashadev-sky** [comment]
Hmm thats really weird!! Sorry about that!! If you make any commit to the branch, I think it will reopen it. As for the lost work I think we can recover it ny doing a `$ git reflog` then `$ git reset --hard HEAD@{# of ref you want to go back to before this happened}` and force push that.

**Pull request closed without merging**
