### PR TITLE
empty wiki table header

### LINKED ISSUE #7531: remove headers when table is empty
Here in https://publiclab.org/wiki/tag/question:general?sort=page_views
Header can be removed when table is empty. A message can be displayed that table is empty.
Screenshot from 2020-02-18 16-47-49

### PR DESCRIPTION
**Pull request by keshavsethi**
Fixes #7531 
message added when wiki table is empty
Screenshot from 2020-02-20 01-36-49
@VladimirMikulic @cesswairimu @nstjean @SidharthBansal 
Thanks!

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
You could hide buttons "by type" & "Sort by", as well as "Related topics."

**Comment by keshavsethi** [comment]
> You could hide buttons "by type" & "Sort by", as well as "Related topics."

"By type" drop down is required for switching type thatswhy it is important but sort by and related topics can be hidden
Thanks!

**Comment by nstjean** [comment]
The "by type" button is used for filtering the results... if there are no results then you can't filter anything. So it can be safely hidden as well.

**Comment by keshavsethi** [comment]
@nstjean you are right, I will do this
Thanks!!

**Comment by SidharthBansal** [comment]
Great collab going here too

**Comment by cesswairimu** [comment]
Hi @keshavsethi, maybe I am missing something but I could see the message added from the screenshot

**Comment by SidharthBansal** [comment]
@keshavsethi please reply to @cesswairimu

**Comment by keshavsethi** [comment]
> Hi @keshavsethi, maybe I am missing something but I cannot see the message added from the screenshot

Hey @cesswairimu @SidharthBansal, Sorry for the late reply. I just reviewed it. The message is coming when wiki table is empty. Can you please share your screenshot or give me more details of whatever you are getting.
```
<p><%= raw translation('tag.show.no_results_found', tag: params[:id]) %>:</p>
        <p><a href="/search/<%= params[:id] %>">Search for "<%= params[:id] %>"</a></p>
```
Thnaks!!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Trying to re-trigger tests!!

**Comment by jywarren** [comment]
Nice, sorry this took so long!!!

**Pull request merged**
