### PR TITLE
user col removed from comments section in profile

### LINKED ISSUE #4446: Removal of Authors name in comment section from profile page
image
On the profile page of user U under the comment navbar, all the comments of user U will be listed. So it is redundant to display U.

### PR DESCRIPTION
**Pull request by geekychaser**
Fixes #4446

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by geekychaser** [comment]
@jywarren @gauravano @SidharthBansal please review.
image

**Comment by jywarren** [comment]
we could reverse the order so it shows the comment text first and then says
"on _______" to link to the parent post?

**Comment by geekychaser** [comment]
@jywarren can we divide it like this as per @gauravano suggestion ?
image

**Comment by jywarren** [comment]
This seems good but perhaps the comment body would go to the furthest left
-- and the "read more" link may be unnecessary if the node title also links
there?

**Comment by gauravano** [comment]
Actually "read more" here would link to the complete comment and not node. So, do you think we should remove the node title?

**Comment by gauravano** [comment]
@jywarren

**Comment by jywarren** [comment]
Sure!

**Comment by geekychaser** [comment]
@jywarren @gauravano so should i remove the node title or what changes can be done ?

**Comment by gauravano** [comment]
Remove the node title. Thanks!

**Comment by geekychaser** [comment]
image

@gauravano should it look ilke this ?

**Comment by gauravano** [comment]
Looks clean to me. @jywarren any suggestions? Thanks!

**Comment by jywarren** [comment]
Looks good! Thanks!

**Comment by gauravano** [comment]
@geekychaser is it ready for review? Thanks!

**Comment by geekychaser** [comment]
No i will push the changes in a while
Thank you

**Comment by gauravano** [comment]
Ok, please attach a GIF and mark the checklist too. Thanks!

**Comment by geekychaser** [comment]
image

please review @jywarren @gauravano

**Comment by geekychaser** [comment]
@jywarren @gauravano please review i think it is reday to merge.
thank you

**Comment by gauravano** [comment]
Sorry for delay @geekychaser. Reviewing now!

**Comment by gauravano** [comment]
@jywarren changes looks good to me. Do you want to add anything? I am not sure about the quotation mark. Please give final review. Thanks!

**Comment by jywarren** [comment]
Awesome!!! Great work! 👍

**Pull request merged**
