### PR TITLE
Fix aspect ratio 

### LINKED ISSUE #4524: Fix Aspect Ratio for thumbnail grid Images
Builds on #4198. There are a few things that PR missed. (The grid on /micro still has the aspect ratio issue) The grid on /micro is generated with this template:
https://github.com/publiclab/plots2/blob/master/app/views/grids/_thumbnail.html.erb
(Thanks to @jywarren, who located it :D) 

If there are any other places on the site were you find the images look a bit squashed or cut off, please link to that here. Thanks!

### PR DESCRIPTION
**Pull request by harsh1599**
Fixes #4524 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by harsh1599** [comment]
Please review this @publiclab/reviewers

**Comment by sashadev-sky** [comment]
@harsh1599 thank you for the PR! I wanted to get input from the people originally working on this issue before requesting this change

@jywarren @dinaelhanan:
I can confirm the changes @harsh1599 has made are correct, but there is already a css declaration for it in https://github.com/publiclab/plots2/blob/7bb6fac8909690e7a5d7c611824d944285c69a61/app/assets/stylesheets/style.css#L383-L393

I think the first declaration can just be deleted, and the styling for `.grid-image` declaration fixed to include @harsh1599's solution above. This could help the code base more maintainable to update incompatible styling instead of leaving it and overriding. 

from looking at the code repo and chrome dev tools this should not make any unexpected styling changes, but I'm having trouble gaining access to the server right now. 

What do you think @harsh1599?

**Comment by sashadev-sky** [comment]
@jywarren sounds good! @harsh1599 would you like to take this on?

**Comment by harsh1599** [comment]
@sashadev-sky  @jywarren  sorry for the late reply..was busy yesterday. I will commit the required changes.

**Comment by jywarren** [comment]
That's great! Can you upload a quick screenshot of it in action with a
couple images?

**Comment by harsh1599** [comment]
screenshot from 2019-01-29 19-01-38

**Comment by jywarren** [comment]
Ok, thanks!

**Comment by jywarren** [comment]
Great work!

**Comment by gauravano** [comment]
Hi @harsh1599 , thanks for nice work. We would love to have more help from you. If you are interested in solving more issues then check here - https://code.publiclab.org/#r=all for a new issue. In case, you are unable to find an issue, feel free to comment here. Thanks!

**Pull request merged**
