### PR TITLE
Fix bug in wiki root link

### PR DESCRIPTION
**Pull request by ananyo2012**
This solves the problem mentioned in Issue #401

### CODE REVIEW

**Comment by jywarren** [comment]
Hello, have you run `rake test` to confirm that this doesn't break anything? 

Thanks for your contribution!

**Comment by ananyo2012** [comment]
@jywarren Some tests fail for the notes controller which were also failing for the original code. But all tests for wiki controller pass.

**Comment by jywarren** [comment]
Which tests? All are passing on master, so perhaps you could pull in the
latest master and rebase your changes on top of it.

Thanks!

**Comment by jywarren** [comment]
Also, are you sure that these pages have paths like `/about` ? the difference by find_root_by_slug and find_by_slug is that find_root only finds those which have the url without "/wiki/xxx" for example -- just "/xxx". So I'm not sure this is a bug.

**Comment by jywarren** [comment]
Hi, ananyo - I think this can safely be called not a bug, as my response to #401 explains. Thanks!

**Pull request closed without merging**
