### PR TITLE
Fixed Dangerfile

### LINKED ISSUE #2086: PublicBot error
### Please describe the problem (or idea)
I was doing a pull request at plots. I wrote "Fixes #issue_number" but still it is showing me "You must enter like "fixes ..."
image
See the first and the last line of the image

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #2086

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren One important thing: don't we want the contributor to necessarily also mention the issue in a commit message?

**Comment by SidharthBansal** [comment]
@ryzokuken  I guess originally the proposed idea was to use the commit messages. But it will be better to have in the pr body for beginner friendly reasons.
Let's wait till @jywarren comments.

**Comment by ryzokuken** [comment]
In my opinion, teaching the beginner general open-source etiquettes in a friendly manner is better than having lax guidelines.

**Comment by jywarren** [comment]
Could you look both places? For commits maybe
git.commits.collect(&:message).match() or something like that? :-)

**Comment by ryzokuken** [comment]
@jywarren I believe this would work if an issue number is mentioned in either of the places, which is what I guess you wanted to ask for in the first place.

**Comment by ryzokuken** [comment]
```md
You used `puts` in your Dangerfile. To print out text to GitHub use `message` instead
All green. Well done.
Danger does not have write access to the PR to set a PR status.
Results:
Messages:
- [ ] @SidharthBansal Thank you for your pull request! I'm here to help with some tips and recommendations. Please take a look at the list provided and help us review and accept your contribution! And **don't be discouraged if you see errors** -- we're here to help.
```

**Comment by ryzokuken** [comment]
Looks like it works now.

**Pull request merged**
