### PR TITLE
removed _list partial and unwanted code [issue #2300]

### LINKED ISSUE #2300: Remove link to /lists from sidebars
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem
/lists from sidebars are no longer used
image

### Solution
Remove link to /lists from sidebars
:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
1. Remove  plots2/app/views/sidebar/_list.html.erb
2. Remove the lines
https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/views/sidebar/_user.html.erb#L9-L15

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.
This will help in completing the remaining parts of #2117

### PR DESCRIPTION
**Pull request by f3mshep**
Fixes #2300

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
  -8 tests use the removed sidebar partial.
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
hi @f3mshep, you were right the issue requires some more details.Can you please take another issue till it's confirmed by @jywarren and @SidharthBansal that we fully want to remove lists from our website.

**Comment by seafr** [comment]
Perhaps deleting only the contents of the partial while keeping the file itself could work as a **temporary** solution.

**Comment by Gauravano** [comment]
yes, it's fine for now.Thanks, @f3mshep  for your efforts.

**Comment by Gauravano** [comment]
Can you plz upload the screenshot of updated view? thanks.

**Comment by f3mshep** [comment]
I have attached an image with the updated view. The envelope is no longer there, however I noticed in the dropdown menu there is a reference to the /lists url.
labcrop

**Comment by jywarren** [comment]
Perfect! Thank you!! 👍 👍 👍

**Comment by ebarry** [comment]
Thank you!!!

**Comment by seafr** [comment]
Thank you @f3mshep for your first PR. :+1:

**Pull request merged**
