### PR TITLE
Makes Answering HTML responsive for smartphone use

### PR DESCRIPTION
**Pull request by carolineh101**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] All tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Super! I'll review tomorrow (we do a Tuesday Friday merge schedule). Thanks!

**Comment by jywarren** [comment]
Great, this is super -- merged in 66afd8d. 

One thing that may make it easier for you in the future (although it didn't come up in this PR) is to create a new, named branch like "responsive-answers" with `git checkout -b responsive-answers` -- and to do your work in that branch. That way, if you ever have to rebase your work back over the latest master, you can check out publiclab/plots2's master to your local master, then rebase your named branch. Sounds complicated but there's a walkthrough here: https://publiclab.org/wiki/contributing-to-public-lab-software

Again, this isn't required but it's a small extra step that can come in handy if there are every conflicts to resolve. 

Thanks again, and if you're interested in contributing more, we're actually going to start making more HTML related issues because we need help with that, so I'm sure there are other places we'd love to have your contribution.

**Comment by carolineh101** [comment]
Thanks! I'll definitely keep that in mind next time, and I'll be on the lookout for more HTML issues!

**Comment by jywarren** [comment]
There are some more issues here, though not as thoroughly documented as our `first-timers-only` issues:

https://github.com/publiclab/plots2/labels/help-wanted

I also cleaned up and reposted one here which involves some HTML and a bit of Ruby and JavaScript, but isn't too much more complex than what you just contributed. Just in case it looks interesting! https://github.com/publiclab/plots2/issues/705

**Comment by jywarren** [comment]
This change is now live on PublicLab.org -- thanks!

**Pull request closed without merging**
