### PR TITLE
Login modal styling inconsistencies #6933

### LINKED ISSUE #6933: Login modal styling inconsistencies
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### The Problem
As you can already see, something is not right about this login modal!
It's styling! Some elements are spaced too much and some elements are squished together.

modal2

Your task is to fix it by making it styles consistent, something like this.
You can also introduce you own ideas if you think that you can do better ;)

modal

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file plots2/app/assets/stylesheets/login_modal.scss, use margin to space out elements.

CSS that needs to be implemented:

```css
div.form-group {
    margin-top: 1rem;
}

div#socialIcons {
    margin-bottom: -2rem;
}

p.form-grey {
    margin-top: 1rem;
}
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by myungwoo-Y**
Fixes #6933 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Before(old)

이미지 2

After(new)

이미지 3

Thanks!

### CODE REVIEW

**Comment by Uzay-G** [comment]
Hey! Welcome to PublicLab :smile:! We are so thankful for your help and look forward to many more. Good work. @keshav234156 and @SidharthBansal we can merge this.

**Comment by VladimirMikulic** [comment]
Duplicate of #6937

**Comment by VladimirMikulic** [comment]
@myungwoo-Y before opening PR, you should've commented on the issue that you are interested in.

"After(new)" labelled picture should be before, that was the initial look of the modal and "Before(old)" is the actual new look. Also, you have a typo in your commit message.

Don't be worried though, we all make mistakes :)
We are here to help, you can also join us on [Gitter](https://gitter.im/publiclab/publiclab).

**Comment by SidharthBansal** [comment]
Folks whenever you meet any gci student ensure that they have visited
welcoming post and have written hello there. Tell them about installation
tasks and 2 ftos are needed before other tasks. Students can do as many
supportive tasks as possible.
Thanks 😊

**Pull request closed without merging**
