### PR TITLE
Permalinks to specific answers in Q&A

### PR DESCRIPTION
**Pull request by sandyvern**
Changed the span to a link tag, change comment.cid to answer.id
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
It looks like the most recent commit -- 3bfc088 -- does fail checks. Clicking on "Details" link above shows me (I think you can see this too? But actually not sure, sorry!) that part of the test install process didn't run correctly -- the "apt-get blablabla" stuff. So I re-triggered the tests, and let's see what happens! 

We ought to cache those dependencies in the tests so they don't have to get installed over again each time, which would make the occasional non-code-related test failures like this one less likely, and also just run tests faster. Apologies, it can sometimes be squirrely!

**Comment by sandyvern** [comment]
Thanks for looking into it! It looks like it worked this time :-)

**Comment by jywarren** [comment]
Oh, awesome -- is this ready for review, then? I can check it out later this afternoon if so. Thanks!

**Comment by sandyvern** [comment]
Yes, I think it is ready for review.

**Comment by jywarren** [comment]
First, just a note -- i see your first commit was from your previous work -- in app/controllers/questions_search_controller.rb -- and while that's OK -- i can rebase past it, it makes sense to see it in your /second/ PR. 

This time, you could follow these steps to add these changes on the latest publiclab master:

1. `git checkout master` - go back to your master branch (your work is saved in the feature branch)
2. `git reset --hard 24b67d65f2bd7ec915c83ccbde4566796fede0b3` -- rewind your master branch to a state before it diverged from our master
3. `git pull https://github.com/publiclab/plots2.git master` -- fetch publiclab's latest master
4. `git checkout permalinks-to-specific-answers` -- go back to your saved feature branch
5. `git rebase -i master` -- here, you can use your text editor to mark each commit -- delete the line to skip it (like the "replaced pipes" one), and you can do lots of other things here too, but that's all we need; this just detaches your latest changes (minus the deleted one) and reattaches or "replays" them onto the latest master
6. `git push -f origin permalinks-to-specific-answers` -- push up your newly re-based changes! (-f forces, to overwrite this PR)

Actually, while this is a useful process to know, this is a concise enough PR that I can just resolve these myself, so tell me if you'd like to give the above a try? If it doesn't work out, or if I've forgotten a step, we can default to just working with this version. 

****

One other small thing -- instead of `#c`, we should use `#a` -- since there will be both comments and answers on any given question page, we should make sure the "deep link" anchor codes are unique, in case by chance there's an answer and a comment with the same id #. And the [anchor on this line](https://github.com/sandyvern/plots2/blob/3bfc0880c488a3805840abe199cceac05a9cd343/app/views/questions/_answer.html.erb#L2) is set up with the letter `a` -- that's where the browser will scroll down to when we append `#a12345` to the URL.

Make sense? Thanks for your patience, this code is pretty dense!

**Comment by sandyvern** [comment]
I gave the steps above a try....and replaced the #c.

And thanks for the info on the 2nd thing....I wondered about the #c and thought maybe it should need to be changed cause probably referenced comments...but wasn't sure exactly and didn't want to mess things up too much :-)

**Comment by jywarren** [comment]
This looks perfect, thanks! 

Glad that process worked for you. Next time you probably won't have to `git reset` -- since unlike before, all your new work will be in named feature branches, your own `master` will never diverge from publiclab master, and you'll just be able to:

1. make your changes in a feature branch
2. check out master
3. pull latest from publiclab master
4. check out feature branch again
5. `git rebase master` will then run cleanly -- though it may prompt you to fix conflicts if you've edited the same file as one that's been changed.

Thanks! Merging now!

**Comment by sandyvern** [comment]
Awesome! Thank you for the opportunity to contribute!!

**Comment by jywarren** [comment]
We really appreciate your contribution, btw! Again, no rush but if you're looking for a new challenge to tackle, there are plenty, especially the ones here: https://github.com/publiclab/plots2/milestone/5 that [are marked](https://github.com/publiclab/plots2/labels/help-wanted) `help-wanted`.

If any are lacking clear line-of-code hints, i'm happy to add them. Thanks again!

**Pull request merged**
