### PR TITLE
changed the <hr/> tags to <hr> tag

### PR DESCRIPTION
**Pull request by Crisoal**
Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Review by TildaDares — CHANGES_REQUESTED** [review]
Hi @Crisoal, it looks like you changed the entire file. You were only supposed to change a few lines in each file 

> [404.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/404.html) (Line 62)
> 
> [422.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/422.html) (Lines 45 and 63)
> 
> [500.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/500.html) (Lines 43, 47, 65)
> 
> [502.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/502.html) (Lines 46, 62)
> 
> [503.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/503.html) (Lines 46, 62)

**Comment by Crisoal** [comment]
> Hi @Crisoal, it looks like you changed the entire file. You were only supposed to change a few lines in each file
> 
> > [404.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/404.html) (Line 62)
> > [422.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/422.html) (Lines 45 and 63)
> > [500.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/500.html) (Lines 43, 47, 65)
> > [502.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/502.html) (Lines 46, 62)
> > [503.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/503.html) (Lines 46, 62)

I copy the code and created another file, then I changed the line

**Comment by TildaDares** [comment]
Hi @Crisoal, you don't need to create a new file. All you have to do is go to the existing files and change the lines requested.

**Comment by Crisoal** [comment]
> Hi @Crisoal, you don't need to create a new file. All you have to do is go to the existing files and change the lines requested. Thanks!

i wasn't able to edit the files

**Comment by TildaDares** [comment]
@Crisoal Do you have a local env for this repo?

**Comment by Crisoal** [comment]
> @Crisoal Do you have a local env for this repo?

i am not sure

**Comment by TildaDares** [comment]
@Crisoal Navigate to this link https://github.com/publiclab/plots2/edit/main/public/404.html and change line 62 to `<hr>`. After doing that click the propose changes button.

**Comment by Crisoal** [comment]
> @Crisoal Navigate to this link https://github.com/publiclab/plots2/edit/main/public/404.html and change line 62 to `<hr>`. After doing that click the propose changes button.

okay, thanks

**Comment by Crisoal** [comment]
@TildaDares pls, could you pls review what i have done?

**Pull request closed without merging**
