### PR TITLE
Remove Duplicate Code in Spam2 flags

### PR DESCRIPTION
**Pull request by Tanushka11**
Remove Duplicate Code in Spam2 flags
Fixes #0000 
#10893 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Tanushka11** [comment]
Hii @TildaDares, please review.

**Review by TildaDares — APPROVED** [review]
Thanks @Tanushka11. Great work!!

**Comment by Tanushka11** [comment]
My pleasure @TildaDares Thank you!

**Comment by jywarren** [comment]
Great work, thank you so much!!

**Pull request merged**
