### PR TITLE
Toopltip added to show users who reacted on a comment

### PR DESCRIPTION
**Pull request by ViditChitkara**
screen shot 2018-06-27 at 1 06 43 am

### CODE REVIEW

**Comment by namangupta01** [comment]
@ViditChitkara can you share a gif or a photo?

**Comment by ViditChitkara** [comment]
@namangupta01, shared in pr description

**Comment by namangupta01** [comment]
Oh! this feature is much like github. Great

**Comment by ViditChitkara** [comment]
fixing code climate issues and writing tests now!

**Comment by namangupta01** [comment]
yup vidit i already saw the pr description but just want to look how it
will look. Great work!!!!!

**Comment by ViditChitkara** [comment]
> Oh! this feature is much like github. Great

@namangupta01 thanks!! Sure, it is.

**Comment by jywarren** [comment]
Yes, it does!!! :-)

**Pull request merged**
