### PR TITLE
grid added to location form, closes #1170

### LINKED ISSUE #1170: Get an integer lat/lon grid to show up on the map #1070
### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by mridulnagpal** [comment]
https://github.com/mridulnagpal/plots2.git
image

**Comment by jywarren** [comment]
Oh cool! Is it possible to make the squares transparent?

Also, although it now reads better in mobile, I think it's quite a bit too big in desktop view. Perhaps `vw` isn't quite what we need?

**Comment by mridulnagpal** [comment]
image
I have now used font-size: %

**Comment by mridulnagpal** [comment]
The squares are now transparent as well 
image

**Comment by jywarren** [comment]
Looks great, thanks -- do you think you could move the grid code into a JavaScript file, rather than it being inline? You could:

* wrap it in a `function addGrid(map) { ... }` method
* move the code itself to `/app/assets/javascripts/locationForm.js`
* include it via: `<%= javascript_include_tag "locationForm" %>`
* inline, just call that function with `addGrid(map);`

Does that makes sense? I'd have made a new issue for these steps, but I think it's fairly straightforward. 

Thank you!

**Comment by mridulnagpal** [comment]
@jywarren Made the changes

**Comment by jywarren** [comment]
This looks awesome, thank you! Merging.

**Pull request merged**
