### PR TITLE
@user made work after bullets #1751

### PR DESCRIPTION
**Pull request by SidharthBansal**

### CODE REVIEW

**Comment by jywarren** [comment]
Hi @SidharthBansal -- are you stuck on this? I really recommend using Rubular.com to help debug; having a great set of test strings and running them through Rubular can let you iterate quickly on getting a regular expression working quickly. If you get stuck, please share a Rubular.com link with us here and we can help out! Thank you!!!

**Comment by SidharthBansal** [comment]
First of all, I found that there are 2 errors instead of one.
First error is if there is a new line then the regular expression is not working
Second: If it is after a non-word character it is not working. May be bullet or '-' etc. Eg. Checkout my profile -@sidharth will not work
So, I tried the following:
I used a '^' for new line and \W for non word character.So, it should be   FINDER = /(^|\W)\@([\w-]+)/ instead of   FINDER = /(^|\s)\@([\w-]+)/ .
The rubular link is http://rubular.com/r/dKqYq2ZKbe
The tests are passing in rubular. 
Also I ran the server again after having changes, output is:
image
The earlier commit was not passing because I think there was a clash between email addresses and user tags. But now, I guess there isn't.
Thanks @jywarren

**Comment by SidharthBansal** [comment]
First of all, there are 2 errors instead of one.
First error is if there is a new line
Second: If there is a non-word character before @user_name. For example: Bullet point and a username or Checkout of profile at -@user or there is a space before the name
So I did the following
I replaced the space by non word character ie \s by \W
So finder should be 
  FINDER = /(^|\W)\@([\w-]+)/
It is passing test cases on rubular - http://rubular.com/r/dKqYq2ZKbe
Also 
image
Thanks @jywarren

**Comment by SidharthBansal** [comment]
I dont know why travis test cases are failing .
It is showing ================================================================================
Failure:
  <"REPLACE REPLACE `@StlMaris123`"> expected but was
  <"REPLACE REPLACE  REPLACE`">.

**Comment by jywarren** [comment]
The test string is here: https://github.com/publiclab/plots2/blob/43dcbcd8601e8a4fa23bef9eda7030b8e60a61e7/test/unit/constants_test.rb#L6

See how in this version it matches all 3 instances of 'StlMaris123': http://rubular.com/r/fh9glRXmpQ

It's not supposed to match the one with ``` ticks -- so I think if you can get that string to match only the first two instances of 'StlMaris123' and not the one in back-ticks, you'll be good!

Thanks!!!

**Comment by jywarren** [comment]
Moving to #1775 !

**Pull request closed without merging**
