### PR TITLE
Add last edited by to tools popover for notes and questions

### LINKED ISSUE #7586: Add 'Last Edited By' to tools popover of questions and notes
Currently only the Wiki tools popover has the last edited by field.We can extend this functionality to questions and notes in vorder to achieve uniform functionality across the website.

**Additional context (optional)**
Wiki-  
image
Questions and notes-  
image

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #7586 
Last edited by added to tools popover for notes and questions.
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

## Screenshots  
Screenshot from 2020-03-08 22-49-47
Screenshot from 2020-03-08 22-42-51

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@VladimirMikulic @publiclab/reviewers can you kindly review? Thanks :v:

**Comment by Tlazypanda** [comment]
@cesswairimu I think this is ready for a merge :smile: Can you kindly review? Thanks :v:

**Comment by jywarren** [comment]
I checked with Cess on this and it looks great. Merging!!! Thanks!!

**Comment by jywarren** [comment]
Thanks everyone!!!

**Pull request merged**
