### PR TITLE
removed auto-added aesterisk in boolean search

### LINKED ISSUE #3490: Boolean Full-Text Searches - add a link to more info on boolean searches
The boolean full-text search has the capability to support operators such as **+**, **-** and **\***. We are using the boolean full-text search [here](https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L39-L44), but with an auto-added asterisk:
```
        if type == :boolean
          query = connection.quote(query.to_s + "*")
          nids = Revision.select("node_revisions.nid, node_revisions.body, node_revisions.title, MATCH(node_revisions.body, node_revisions.title) AGAINST(#{query} IN BOOLEAN MODE) AS score")
            .where("MATCH(node_revisions.body, node_revisions.title) AGAINST(#{query} IN BOOLEAN MODE)")
            .limit(limit)
            .distinct
            .collect(&:nid)
```
So we need help to:
* [x] remove the auto-added asterisk on this line, and treat "boolean search" as an 
expert search type. - Done (#4022)
* [ ] **add a link to more info on boolean searches: https://dev.mysql.com/doc/refman/5.5/en/fulltext-boolean.html - TODO**

----------------------------

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

### PR DESCRIPTION
**Pull request by JonathanXu1**
Fixes #3490

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

I've removed the auto-added asterisk and added a link to the boolean-search info page as a comment above. I believe that's what's required to fix the issue, but I'm open to any suggestions!

### CODE REVIEW

**Comment by kevinzluo** [comment]
Hi @JonathanXu1 . I believe @milaaraujo made some suggestions for the previous PR for this issue. Maybe you could implement them in your fix?
> Hey @rohancl,
> 
> You shouldn't have indentation problems because of this. Can you put here what is the error you get when you try `query = connection.quote(query.to_s)`?
> 
> Actually, since you are no longer concatenating the string I think you don't need the `connection.quote()`. Something like this should be enough:
> 
> ```
> ...
> nids = Revision.select("node_revisions.nid, node_revisions.body, node_revisions.title, MATCH(node_revisions.body, node_revisions.title) AGAINST(? IN BOOLEAN MODE) AS score", query.to_s)
>                .where("MATCH(node_revisions.body, node_revisions.title) AGAINST(? IN BOOLEAN MODE)", query.to_s)
> ...
> ```

**Comment by milaaraujo** [comment]
@kevinzluo it is ok! It was just a suggestion, but @JonathanXu1 solution is also correct. :)

**Comment by milaaraujo** [comment]
@JonathanXu1, could you also claim the task in the GCI board?

**Comment by JonathanXu1** [comment]
Yep, I fixed the changes that codeclimate pointed out. I made a new pull request because I accidentally made a lot of changes on my old branch. Here it is: https://github.com/publiclab/plots2/compare/master...JonathanXu1:boolean-search

**Pull request closed without merging**
