### PR TITLE
Fix tools popover overflow issue

### LINKED ISSUE #7578: Tools popover overflows to the right of the screen
### Please describe the problem (or idea)
Currently the tools popover in the events page overflows to the right of the screen as shown below.It needs to be positioned so that it remains within the screen width.
image10

### Please show us where to look
/wiki/events

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #7578 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

# Screenshot  
Screenshot from 2020-03-02 13-53-10

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@VladimirMikulic here I have changed the data-placement attribute to bottom to prevent the overflow the ideal would have been to change it to left but it was covering the other options.Also if I would have added any fixed padding then it wouldn't have been ideal too for responsiveness.Kindly review :v: Thanks :smile:

**Comment by Uzay-G** [comment]
It looks good! Could u also send a screenshot of how the tooltip looks on mobile. You can verify in browser by using the developer tools

**Comment by Tlazypanda** [comment]
@Uzay-G Sure! and thanks for the review :v:   
image

**Comment by Tlazypanda** [comment]
@VladimirMikulic can you kindly review ? Thanks :v:

**Comment by VladimirMikulic** [comment]
These pop-ups are not really responsive. @Tlazypanda is there a way to make them smaller and fluidly scale? Thanks.

**Comment by Tlazypanda** [comment]
@VladimirMikulic went through the docs a bit but couldn't really find any way to make them responsive ...is there any workaround for the same? Thanks :v:

**Comment by VladimirMikulic** [comment]
@Tlazypanda it's alright then. Let's not write hacky code.

**Comment by Tlazypanda** [comment]
@cesswairimu @SidharthBansal can you kindly review? Thanks :v:

**Comment by cesswairimu** [comment]
Great thanks @Tlazypanda

**Pull request merged**
