### PR TITLE
Fixes#3838

### LINKED ISSUE #3838: add login prompt to questions page
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/questions/index.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/questions/index.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -21,14 +21,15 @@
   <div class="row">
     <div class="col-md-6">
       <h4>Ask a question here</h4>
+      <p>To ask a question, please <a href="/login?return_to=/questions">log in</a> or <a href="/signup?return_to=/questions">sign up</a> first.</p>
       <form id="questions_searchform" class="form-horizontal" role="search" autocomplete="off" action="/post">
         <div class="input-group">
-          <input tabindex="1" id="questions_searchform_input" type="text" name="title" class="form-control search-query typeahead" qryType="questions" placeholder="type your question">
+          <input tabindex="1" id="questions_searchform_input" type="text" name="title" class="<%= "disabled " if current_user %>form-control search-query typeahead" qryType="questions" placeholder="type your question">
           <input type="hidden" name="tags" value="question:general">
           <input type="hidden" name="template" value="question">
           <input type="hidden" name="redirect" value="question">
           <span class="input-group-btn">
-            <button type="submit" rel="tooltip" title="Ask a question with the entered title" class="btn btn-primary">Continue</button>
+            <button type="submit" rel="tooltip" title="Ask a question with the entered title" class="<%= "disabled " if current_user %>btn btn-primary">Continue</button>
           </span>
         </div>
       </form>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by akoopraba4**
Fixes #3838

### CODE REVIEW

**Comment by akoopraba4** [comment]
I hope I modified it correctly.

**Comment by akoopraba4** [comment]
@jywarren 
What should I do to make a patch file from the two commits?

**Comment by jywarren** [comment]
Ah, you can push additional commits to the same PR. But please retitle it so it's more descriptive -- i couldn't tell what this changed from the title. Thank you!!!

**Comment by jywarren** [comment]
Unfortunately I believe this was solved in the past few days... we'd love to work with you if you'd like to try another issue!

**Comment by jywarren** [comment]
Thanks and apologies!

**Pull request closed without merging**
