### PR TITLE
added profile pic column to /people

### LINKED ISSUE #2063: Add profile pictures to /people page
### Please describe the idea

> what problem could this idea solve?

Our existing top level page about Public Lab members is a little bland

screen shot 2018-01-22 at 12 46 19 pm

The Halt The Harm leader directory is on point for having profile pictures. 
screen shot 2018-01-22 at 12 44 00 pm

### Suggested steps

* Add profile pictures to /people
* Consider how to show profile tags on /people

### PR DESCRIPTION
**Pull request by ViditChitkara**
closes #2063

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
profile-picture-1
@jywarren @ebarry please have a look.

**Comment by jywarren** [comment]
Looks fantastic! 👍 👌 🙌

**Comment by ebarry** [comment]
Wow this looks really great!!! Thank you so much!!!!!!

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by jywarren** [comment]
Oops, hi @ViditChitkara -- Looks like we need to check to ensure there /is/ a profile before we display it. If you could get this tweak filed before tomorrow we can publish this then! Thank you!!!

Testing site: http://stable.publiclab.org/people

**Comment by jywarren** [comment]
https://publiclab.org/people Looks super!!!

**Comment by ViditChitkara** [comment]
Sorry for the late reply!!
Looks like this might have happened due to faulty image url on the stable site!! This is correctly handled in the code!!

**Pull request merged**
