### PR TITLE
Update send_digest.html.erb

### PR DESCRIPTION
**Pull request by jayshree1602**
Added full paths to email digest images

Re: #4732

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jayshree1602** [comment]
Hey! Kindly review this pull request.

**Comment by divyabaid16** [comment]
@jayshree1602 can you please add the issue number for which you have solved?
Also can you please make the title a little bit more descriptive.
Thanks!

**Comment by jywarren** [comment]
Was this for part of #4732 ?

**Comment by jywarren** [comment]
Looks awesome. Thanks for your help!!!

**Pull request merged**
