### PR TITLE
Remove duplicate ids in signin and signup page

### LINKED ISSUE #2237: non-unique username and password id
After going on page https://publiclab.org/signup if we open browser console we are getting error saying `non unique id` this is coming because we have a sign-up form on the page body and login page on the header and both have forms which are using same ids. `#username` `#password
`
Where to go: https://publiclab.org/signup

screen shot 2018-02-06 at 3 30 32 am

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Closes #2237 
* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Aha! Great work here. Does this still enable people to "save" their responses for these forms in the browser? I'm not sure how it works, but in Chrome/FF you know how it says "save this password" -- i always assumed that was based on the id, and just wondering  if this would affect that feature, either:

* by making people need to "save" the password twice for 2 different IDs
* by making people need to "re-save" the password over again because both IDs have changed from what they were before

If neither of these is a problem, I'm fine with merging this in -- thank you!

**Comment by jywarren** [comment]
Hi, @namangupta01 -- just checking in here -- what are your thoughts? Thank you!!!

**Comment by namangupta01** [comment]
@jywarren Hey, sorry for the late reply i was very busy from past two weeks. But i will check it right now.

**Comment by namangupta01** [comment]
@jywarren I just tried it on my local its working!

**Comment by namangupta01** [comment]
Check here: https://webmasters.stackexchange.com/questions/54569/how-to-make-browsers-offer-to-remember-passwords
Form with a field of password type is used.

**Comment by jywarren** [comment]
Great!!!! 👍

**Pull request merged**
