### PR TITLE
Configurable Email Settings

### LINKED ISSUE #213: configurable email notification preferences
We are having settings at /settings as we might wanna add more settings in future. Below are the settings which would be added to settings page: 

Asking: Do you want to be notified by email for (with toggles):

- [x] comments on your posts
- [x] comments on all posts you've commented on
- [x] likes on your posts
- [x] notes on a topic (we have this already!)
- [ ] notifications for wiki page edits: https://github.com/publiclab/plots2/issues/396 (after all the rest!)
- [ ] The monthly blog would be everything tagged `blog` once per
month? What user tag would that be? (by @jywarren )
- [x] Digest- weekly
- [x] Digest - daily

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #213 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
Hi, @jywarren do we have a comment system for the wiki pages or should this test be targeted on a note?

**Comment by jywarren** [comment]
Oooh, exciting!!! 👍

**Comment by Gauravano** [comment]
Ok, @ViditChitkara, I will add it. Thanks!

**Comment by Gauravano** [comment]
Hi @ViditChitkara, I have implemented digest settings in this PR as we have discussed, you can try at https://unstable.publiclab.org/ , I have pushed there. Let me know if any change is required. Thanks!

**Comment by Gauravano** [comment]
Hi @jywarren @ViditChitkara this PR is complete. I have incorporated 1 setting and 2 digest settings in this. Please review it, thanks!

**Comment by jywarren** [comment]
This is very exciting - can you post a screenshot once more so we can do a final look at it?

**Comment by Gauravano** [comment]
Here's default behavior when the setting is turned on: http://gauravsachdeva.me/default_behaviour.gif

Here's the GIF when setting is turned off: http://gauravsachdeva.me/no_comment.gif

**Comment by jywarren** [comment]
This is super. 🎉  Do you want to think with @ViditChitkara about how to ensure /settings and /subscriptions don't confuse people? Could they be on the same page, or could /settings be shown in the menu as `Digest settings`? Also maybe a link from /subscriptions to /settings ? I just imagine people wondering "what's the difference between /settings and /subscriptions"? 

Then we should be good to go on this.

**Comment by Gauravano** [comment]
Changing the name and adding a link then. Thanks!

**Comment by Gauravano** [comment]
Hi @jywarren here's addition in Subscriptions page 
design_1

Please suggest improvements. Thanks!

**Comment by jywarren** [comment]
This is super! Maybe not bold though? Awesome!

**Comment by jywarren** [comment]
Super, ready then? 😄

**Comment by Gauravano** [comment]
yes!

**Comment by jywarren** [comment]
Hooray!!! 🎉

**Pull request merged**
