### PR TITLE
Update _signupLoginModal.html.erb

### LINKED ISSUE #6175: Signup modal not showing up
Sign up modal not showing up at any place

@IshaGupta18 confirmed the existence of issue

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #6175

### CODE REVIEW

**Comment by jywarren** [comment]
This is a persistent unrelated error stopping some builds: 

image

**Comment by jywarren** [comment]
Broke that out into https://github.com/publiclab/plots2/issues/6179

**Comment by jywarren** [comment]
Now we have:

```

ERROR["test_login_modal", #<Minitest::Reporters::Suite:0x00007f02057e1810 @name="ScreenshotsTest">, 81.92492908799994]
 test_login_modal#ScreenshotsTest (81.92s)
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find link or button "Login"
            test/system/screenshots_test.rb:17:in `block in <class:ScreenshotsTest>'
[Screenshot]: tmp/screenshots/test_methods.png

...

[Screenshot]: tmp/screenshots/failures_test_signup_modal.png
ERROR["test_signup_modal", #<Minitest::Reporters::Suite:0x00007f0205f524a0 @name="ScreenshotsTest">, 146.03433200499995]
 test_signup_modal#ScreenshotsTest (146.03s)
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find link or button "Sign up"
            test/system/screenshots_test.rb:12:in `block in <class:ScreenshotsTest>'
```

**Comment by gauravano** [comment]
We can use safe navigation to solve that - https://github.com/publiclab/plots2/pull/6178#issuecomment-523641933 like `current_user&.id`

**Comment by jywarren** [comment]
OK we need to wait a bit for the screenshots to work. But i tested this locally and it's fine. Merging and republishing, and i'll do a follow-up for the screenshots.

**Pull request merged**
