### PR TITLE
Update Paperclip to v5

### PR DESCRIPTION
**Pull request by jywarren**
Will need Gemfile.lock too!

### CODE REVIEW

**Comment by jywarren** [comment]
I'm testing this out at https://unstable.publiclab.org!

**Comment by jywarren** [comment]
Hmm, @icarito No rush but it seems unstable is not booting?

**Comment by icarito** [comment]
Hey Jeff, just looked at this, I had messed with docker-compose-unstable.yml when working on #2495.
I updated the yml file, please confirm and I can deploy from master into staging and production.

I'll make a pr to include dockerfiles for different instances, it would be a pain to update this stuff in many places.

**Comment by jywarren** [comment]
Ok! Where are the changes I have to look at? Thanks!!!

**Comment by icarito** [comment]
Actually I was wondering too, do I deploy everything that is in /Master?
/

Currently /unstable/ doesn't carry the changes in mail configuration.

Unstable has this:

 1. Removed de.yml files from /config/locales/ (#2551) (detail
    <https://jenkins.laboratoriopublico.org/job/Plots-Unstable/70/changes#detail0> / githubweb
    <https://github.com/publiclab/plots2/commit/894fa33b348f97e4b269924ba8702e125a335023>)
 2. tags not shown on search resolved (#2578) (detail
    <https://jenkins.laboratoriopublico.org/job/Plots-Unstable/70/changes#detail1> / githubweb
    <https://github.com/publiclab/plots2/commit/82f2096354c7f56f15ad03b053202dbf647cf7e6>)
 3. Popup on tags display added (#2572) (detail
    <https://jenkins.laboratoriopublico.org/job/Plots-Unstable/70/changes#detail2> / githubweb
    <https://github.com/publiclab/plots2/commit/e1a186682302132cfa5a34c6a6b1bdf59693d140>)
 4. Upgrade to Rails 4.2  (#2533) (detail
    <https://jenkins.laboratoriopublico.org/job/Plots-Unstable/70/changes#detail3> / githubweb
    <https://github.com/publiclab/plots2/commit/979532802910dc035847b0efdc6e101e77fa7a6f>)
 5. [WIP] Adding Search bar to Maps . #2582 (#2585) (detail
    <https://jenkins.laboratoriopublico.org/job/Plots-Unstable/70/changes#detail4> / githubweb
    <https://github.com/publiclab/plots2/commit/35aeac4032d5bc5c7c74d52b9085c5f28335a382>)
 6. Update Gemfile (detail
    <https://jenkins.laboratoriopublico.org/job/Plots-Unstable/70/changes#detail5> / githubweb
    <https://github.com/publiclab/plots2/commit/cdab6978ac1892523b28573bd2ddf823870e9805>)
 7. updated Gemfile.lock (detail
    <https://jenkins.laboratoriopublico.org/job/Plots-Unstable/70/changes#detail6> / githubweb
    <https://github.com/publiclab/plots2/commit/b7e266e1f01a26b0b20d2292ce4092571353aa74>)

**Comment by jywarren** [comment]
This change has not been put into master. This is just the Paperclip upgrade, not the Rails 4.2 upgrade -- the latter has been put into master, and is ready for deployment. 

The mail configuration has been merged to master, and is ready for deployment and email testing, and is unrelated to either the Rails 4.2 upgrade or this Paperclip change (paperclip is just image uploading).

Here, I was trying to push this attempt at Paperclip image/file upload to unstable before merging it -- it's lower priority!

Thanks!

**Comment by jywarren** [comment]
So, you should be able to deploy everything to stable, then to production (email configs haven't been moved to stable yet because I wasn't sure if you'd finished with the stable email config)

**Comment by jywarren** [comment]
^ edited above to say "everything in master to stable" instead of just "everything"

**Comment by icarito** [comment]
Cool then I'll be testing the mail settings in stable to deploy and test
production.

**Comment by icarito** [comment]
Jeff, I deployed to production and to stable.
I did a bit of a trick, adding appropriate IP address for SMTP service to /etc/hosts file (by default plots looks for `smtp` hostname).

**Comment by jywarren** [comment]
Awesome thanks!

**Comment by jywarren** [comment]
Hmm, @icarito it looks like this took Unstable offline; https://unstable.publiclab.org/ is it related? 

I just want to test this out before merging to master, since it affects image upload. Thanks!

**Comment by jywarren** [comment]
Actually it looks more subtle -- see https://jenkins.laboratoriopublico.org/job/Plots-Unstable/74/console

I wasn't able to push this to unstable, it seems, at all?

**Comment by icarito** [comment]
It's deployed now!

**Comment by jywarren** [comment]
Oh super - tested and this works -- merging now!

**Comment by jywarren** [comment]
And our warning is gone! Super work, thanks!!!

**Pull request merged**
