### PR TITLE
post to editor rename

### LINKED ISSUE #1014: Redirect /post to /editor unless it's an event post
We're pretty much ready with our new rich editor (at https://publiclab.org/editor) except for event posting, so we should set a redirect now in the editor_controller, unless someone specifically wants the old one. So let's rename the `post` action to `legacy`:

Then, make a new `post` method which checks if we definitely want the legacy version, and if not, redirects to the new editor. 

But since we don't yet have the events widget working in the new editor, we should also go to the legacy editor if it's going to be an event:

```ruby
def post
  if params[:legacy] || params[:template] == "event"
    flash.now[:notice] = "This is the legacy editor. For the new rich editor, <a href='/editor?#{request.env['QUERY_STRING']}'>click here</a>."
    legacy
  else
    flash.now[:notice] = "This is the new rich editor. For the legacy editor, <a href='/post?#{request.env['QUERY_STRING']}&legacy=true'>click here</a>."
    rich
  end
end
```

I think that'll work, though it'll likely cause some test errors which will have to be adjusted for the new rich editor page.

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Closes #1014 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
OK, I see that there are a couple errors which we might expect:

https://travis-ci.org/publiclab/plots2/builds/178505020#L2658

This is because we're now changing the behavior of the `/post` action -- so in this test, the behavior is different here: 

https://github.com/publiclab/plots2/blob/master/test/functional/editor_controller_test.rb#L48

This is a little bit subtle -- we need to preserve the functionality of this line: https://github.com/publiclab/plots2/blob/master/app/controllers/editor_controller.rb#L15 which redirects question posts. Sorry I didn't anticipate this in my original description!

Also, I think it'd be best to add a new test for legacy vs. non-legacy requests to `/post` to confirm that those work properly. 

This test:

https://github.com/publiclab/plots2/blob/master/test/functional/editor_controller_test.rb#L14-L22

Should apply to the legacy form, so you might add to it to mark the request as such:

```ruby
    get :post,
        tags: 'one,two',
        legacy: true # <= here, we request the legacy version of the page
```

Then, we copy it and make a second /without/ the legacy parameter, but then the expectations for the HTML we'd encounter would be different; they'd be based on this page instead of the old post page:

https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb

So we'd want to update those assertions to match, on the lines lower down in that test. Make sense?

**Comment by ykl7** [comment]
@mridulnagpal if this is not being done at the moment, do you mind if i take a shot at it?

**Comment by mridulnagpal** [comment]
@ykl7 Yeah sure, anyways I am stuck up with some work already :) . Glad to see you here

**Comment by jywarren** [comment]
Oh great, thanks @ykl7 - and please base your work on this PR -- whether that means opening a new PR that references this one and uses its commits, or however. Thank you!

**Comment by ryzokuken** [comment]
Hello! You must've noticed that the unit tests failed unexpectedly on your PR. This was due to some issue in the Travis CI testing configuration which was fixed by @jywarren later tonight. In order to make them work again, please rebase your work on top of the current master and then try pushing to your remote branch. Do this by:

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <my-branch>
$ git rebase master
$ git push origin <my-branch>
```

Thanks for bearing with us,
Ujjwal

**Comment by ykl7** [comment]
@ryzokuken Thanks for the heads-up. I haven't started on this yet since I got some unexpected work come up. Will keep in mind when I get to it

**Comment by mridulnagpal** [comment]
@jywarren So you want the legacy editor on /post&legacy=true but what does it display on /post and once it is transferred to /editor there is no option to switch back to legacy editor. So what all specifications should it have (page wise).

**Comment by jywarren** [comment]
Thanks -- 

* /post should show what's currently shown at /editor
* /post?legacy=true should show what's currently shown at /post (so you have a way out if the new editor doesn't work for you)
* /editor should redirect to /post

Make sense?

**Comment by mridulnagpal** [comment]
#1091 Have a look please !

**Comment by jywarren** [comment]
Also, it's fine (even preferable) to make additional changes to the same PR -- that way the conversation is threaded and not spread over multiple pages. It's fine this time, but next time please do your best to push to the same PR -- you can use `git push -f origin <feature-branch-name>`

Thanks!

**Pull request closed without merging**
