### PR TITLE
Fixed CSS which caused button to collapse

### LINKED ISSUE #3581: Read more button is collapse on the image
### Please describe the problem (or idea)
Read more button of the highlighted blog is collapse on the image of another highlighted blog.
> What happened just before the problem occurred? Or what problem could this idea solve?

screenshot 206

> What did you expect to see that you didn't?
looklike

### Please show us where to look
https://publiclab.org/?_=1538558612

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit), Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by vanguard07**
Fixes #3581 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by vanguard07** [comment]
@publiclab/reviewers Kindly review.

**Comment by vanguard07** [comment]
@aSquare14 I guess, clear works only when there is floating element to the left or right of the target element. But this isn't the case here. Also I tried several other cases, removing the float centers the button and gives a gap between the next card(the one directly below it), no matter how much text is written in the card heading.

**Comment by SidharthBansal** [comment]
Travis test cases were not passing so closed and open the pull request.
Can you please give us a screenshot for your work?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab
cc @jywarren @gauravano

**Pull request closed without merging**
