### PR TITLE
fixed issue #800 and modified search routes

### PR DESCRIPTION
**Pull request by ujithaperera**
* [ ] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

### CODE REVIEW

**Comment by ujithaperera** [comment]
Fixed Issue #800

**Comment by jywarren** [comment]
Oh, thanks! Do you think you could write a test against this path, so we catch this in the future?

**Comment by ujithaperera** [comment]
Yes. Sorry I missed that

**Comment by jywarren** [comment]
Hi, Ujitha - I can throw one together real quick, but if you have it written and can add it here, that'd be great. I know you're busy with the main Solr search integration, so if I don't hear from you, I can do that later today.

**Comment by jywarren** [comment]
Oh, i see you merged this into #781 -- it's fine for now, but really i think it will be /much/ easier and cleaner to base bugfixes like this on the publiclab/plots2 master branch, and not to merge them into another project -- it has a big potential to complicate your rebase.

**Comment by ujithaperera** [comment]
hi Jeff,
I checked for tests and I found that basic path testings and view rendering tests are existing in searches_controller_test.rb. If you have better approach to tackle this down, it'll be great.

**Comment by jywarren** [comment]
Manually integrating the extra test; thanks!

**Pull request closed without merging**
