### PR TITLE
Issue 828 tests

### PR DESCRIPTION
**Pull request by sjones88**
@jywarren, how should I approach creating fixtures for these tests? In particular, I'm not sure how to create fixtures that simulate the association between a page and a tag.

### CODE REVIEW

**Comment by jywarren** [comment]
That'll be in community tags, which links a tag with a node via tid and
nid. If that doesn't make sense I can add some more details!

**Comment by sjones88** [comment]
Ahh, that explains a lot. Thanks!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck or need more input? Thanks!

**Comment by jywarren** [comment]
Just a suggestion here -- you could probably skip making a new fixture, and just add the new tag to an existing wiki page with:

```ruby
note.add_tag("redirect:#{node(:blog).nid}", rusers(:bob)) # create redirect to the blog page if you're a normal user
```

Such as done in this test: https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L328

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by jywarren** [comment]
Hi, @sjones88 - it's cool if you're busy (i've been, too!) but just checking if there's anything else I could do to help this along. Thanks again!

**Comment by ryzokuken** [comment]
Hello! You must've noticed that the unit tests failed unexpectedly on your PR. This was due to some issue in the Travis CI testing configuration which was fixed by @jywarren later tonight. In order to make them work again, please rebase your work on top of the current master and then try pushing to your remote branch. Do this by:

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <my-branch>
$ git rebase master
$ git push origin <my-branch>
```

Thanks for bearing with us,
Ujjwal

**Comment by jywarren** [comment]
Moving to #1150.

**Pull request closed without merging**
