### PR TITLE
fixed image drag and drop bug

### LINKED ISSUE #5229: Comment image uploading not working
I think this may be related to the new reply-to-comment feature -- @ViditChitkara could you take a look at this one? I don't see any error message but I did see this warning:

```
Found 35 elements with non-unique id #comment-form: (More info: https://goo.gl/9p2vKq) 
```

Related? I was testing both dragging an image into the comment field (not a reply) and also clicking "choose an image" in the bottom bar of the comment field, and neither triggered any reaction. Thank you !!!

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #5229 
Okay, I think this will solve the drag and drop bug. Also, there were some lines missing in form/comments partial which may have been caused due to some conflicting merging when bootstrap upgrade was done. Made some changes there as well. @jywarren kindly have a look.
Thanks

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great. Have you tested it on comment and wiki page editing?

**Comment by ViditChitkara** [comment]
Yes, tested it on my local machine. Working quite well. Attaching a gif in a minute.

**Comment by ViditChitkara** [comment]
Can we test it on unstable ?

**Comment by ViditChitkara** [comment]
Although the problem is solved for now but I think this is vulnerable to errors as we intend to add more features related to comments, should we think of a more stable method or maybe some improvement to dragdrop.js to make sure we don't face any frequent problems?

**Comment by ViditChitkara** [comment]
Preview of the corrected bug

**Comment by jywarren** [comment]
This is great. I think we should merge and start by protecting it well with
system tests. Mine is almost ready to go, did you see? I agree its fragile!
Testing Js and ruby at once is hard but system tests do this! +1!!! Thanks
Vidit!

**Comment by ViditChitkara** [comment]
Yes, I saw it. Great, will write tests for reply to comment as well.
Thanks!

**Pull request merged**
