### PR TITLE
Added alerts-container class

### LINKED ISSUE #8167: Alert boxes push down tag page image headings
When on pages like https://publiclab.org/tag/water-quality, if there is an alert box such as logging out, it pushes down the lead image. Haven't captured it but it's in this view:

Screenshot_20200718-075953

Should be easy to make them float!

### PR DESCRIPTION
**Pull request by avats-dev**
This adds `.alerts-container` to `<style>` inline to float the alert boxes instead of pushing down the page image headings.

Fixes #8167

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by avats-dev** [comment]
@jywarren review this..

**Comment by cesswairimu** [comment]
Hi @avats-dev could you please add a screenshot for this changes. Thanks for working on this

**Comment by avats-dev** [comment]
@cesswairimu , ok I would do so.

As changes were minor (as mentioned in the issue), I updated them on the browser, but now let me build it locally, then I will update.

**Comment by jywarren** [comment]
Hi @avats-dev you can also boot it up in GitPod by clicking the button in the comment above -- and then screenshot it then! Thank you so much!

**Comment by avats-dev** [comment]
@jywarren @cesswairimu , Here is a screenshot of the fix that I got using GitPod.

fix

**Comment by avats-dev** [comment]
> @jywarren @cesswairimu , Here is a screenshot of the fix that I got using GitPod.
> 
> fix

Is this right or do I need to change something?

**Comment by cesswairimu** [comment]
This looks good to me. Requesting a review from Jeff too. .Thanks @avats-dev..

**Comment by avats-dev** [comment]
Thanks @cesswairimu and @jywarren for all the support and help. :rocket:

**Pull request merged**
