### PR TITLE
Adding a followers column to tag page

### LINKED ISSUE #5089: Add followers list to Contributors pages
We should show 2 columns on pages like https://publiclab.org/contributors/ui; one for people who have posted ("contributors" -- these are already shown on the page) and one for people who are Following the tag/topic. We currently only show followers here:

Screen Shot 2019-03-15 at 12 38 19 PM

Let's also rename the tab "People"! 

I'd love help with this - it could be done by making 2 columns, one labelled `People who've posted` using the current table -- code here:

https://github.com/publiclab/plots2/blob/master/app/views/tag/contributors.html.erb#L66

And adding a 2nd column displaying a similar table but for `Tag.followers(params[:id])` -- that is, followers of the topic. 

The tab text could be changed in this file: https://github.com/publiclab/plots2/blob/master/app/views/tag/show/_nav_tabs.html.erb

### PR DESCRIPTION
**Pull request by IshaGupta18**
Fixes #5089 

Movie from #5353 after the bootstrap upgrade:

image

### CODE REVIEW

**Comment by IshaGupta18** [comment]
@gauravano here is the new PR after the bootstrap upgrade. Please review this one and let me know what else can be done!

**Comment by IshaGupta18** [comment]
Hey, what exactly am I supposed to fix here? Sorry didn't understand a little! Thanks!

**Comment by IshaGupta18** [comment]
@gauravano could you tell me what all is left in this so that I can finish it off and merge this PR?

**Comment by jywarren** [comment]
I think Gaurav thought perhaps that was a stray `1` character, but it's the count. So we should be good if you can resolve conflicts here? Thanks!

**Comment by jywarren** [comment]
Hi, Isha! Do you think this could be wrapped up pretty easily? Thank you!

**Comment by IshaGupta18** [comment]
Sure, can you please tell what else needs to be done? Let's get it closed!

**Comment by jywarren** [comment]
Just resolving the conflicts, so not much! Thanks!!!

**Comment by IshaGupta18** [comment]
@jywarren is it good to go?

**Comment by jywarren** [comment]
Sorry @ishaGupta18, this looks great! I'm just going to add a screenshot test so we can see it rendered on the new page style. Just a final check and it'll be good to get this in our screenshot tests system anyways!

**Comment by IshaGupta18** [comment]
Yes, absolutely!

**Comment by jywarren** [comment]
Unrelated timing issue! Let's see...

**Comment by IshaGupta18** [comment]
It passes @jywarren!

**Comment by jywarren** [comment]
Great! 

This is pending discussion by @ebarry and others but we should open a follow-up issue to this where we can redo the design of the page a bit -- but of course we can do this in a separate PR! Thank you!

screenshot

**Pull request merged**
