### PR TITLE
Setup continuous integration with Travis-CI.

### PR DESCRIPTION
**Pull request by icarito**
Tests are passing on: https://travis-ci.org/icarito/plots2 - will setup travis building.

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
wow!!!!
I'll pull this in *after* today's because none of them have been rebased on
top of it, but I'm eager to see how this works! Thanks!!

**Comment by icarito** [comment]
Yes finally it appears to be working :-)

**Comment by jywarren** [comment]
OK, I'm going to rebase it on top of the latest and open my own PR to test there. I don't think i can push to this one.

**Comment by icarito** [comment]
Basically I added 3 files, sorry I missed rebasing.

**Comment by jywarren** [comment]
no problem! I'm curious, does it run the `rake test:all` with the phantomjs tests too?

**Comment by jywarren** [comment]
oh cool, it's running again. nice, thanks.

**Comment by icarito** [comment]
Yes https://travis-ci.org/publiclab/plots2 - I just rebased and pushed to the PR, let's see.

**Comment by icarito** [comment]
Okay it's rebased and passing! :-)

**Comment by jywarren** [comment]
And i see it runs jasmine tests too. Perfect!!! Sebastian, you're a hero!

**Comment by ananyo2012** [comment]
Great! Good to see the green tick now :blush: Now we should include the build link in our readme.

**Pull request merged**
