### PR TITLE
(Preview - Hide Preview) Toggle Text Added for Post Comments in Questions

### LINKED ISSUE #3543: Preview Button Text to be changed in 'Post Comments'
screen shot 2018-09-30 at 2 51 18 pm
screen shot 2018-09-30 at 2 51 35 pm

When preview button is clicked, it's text must be changed to 'Hide Preview'.

### PR DESCRIPTION
**Pull request by YashishDua**
Fixes #3543

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
Hey @YashishDua, nice work!
BTW your git configuration are not properly set.
Use the following commands to set your git configuration so that your contributions would show up in contributors list.
`git config --global user.name "Your Name"`
`git config --global user.email "name@domain.example"`

**Comment by YashishDua** [comment]
@namangupta01 Thanks, I am done with the configuration.

**Comment by namangupta01** [comment]
Make some minor change and then push again would fix the issue. Since your configuration on this pr is old.

**Comment by YashishDua** [comment]
@gauravano I will take care of this from next time. Thanks!

**Comment by YashishDua** [comment]
Merge is still blocked here. What am I supposed to do?

**Comment by SidharthBansal** [comment]
Only @jywarren have rights to merge. So, please wait. He will review the PR
whenever he gets time

**Comment by YashishDua** [comment]
Alright, Thanks @SidharthBansal

**Comment by jywarren** [comment]
Perfect, thank you!!!!! 👍 🎈

**Pull request merged**
