### PR TITLE
"Browse other activities" next to "replicate this" prompt, fixes #754

### LINKED ISSUE #754: "Browse other activities" next to "replicate this" prompt
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

Or just solve it yourself!

****
A link next to the button would let people more easily horizontally browse activities: 

screenshot 2016-08-30 at 2 13 06 pm

It could go on this line of code, though you should break it up unto multiple lines so it's easier to read:

https://github.com/publiclab/plots2/blob/master/app/views/notes/_responses.html.erb#L8

To determine where the link should lead to, we look for the `tagname`, and go to the page with a tag such as `activities:<tagname>`, so:

```ruby
DrupalTag.where(name: "activities:" + @node.power_tag('activity')).first.nodes.first.path
```

However, we must account for the possibility that:

* the DrupalTag doesn't exist and we can't run `.first` on an empty returned array
* the DrupalTag does exist but has no nodes (say, they've been deleted) and we can't call `.first` on an empty `.nodes` array

So we'll have to add some `if` statements to protect against that possibility. 

But once you have the URL, you can just add it in a link, like `<a href="/...">Browser other activities</a>`

### PR DESCRIPTION
**Pull request by 500swapnil**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by 500swapnil** [comment]
@jywarren I have added the expectation. What changes do I make?

**Comment by jywarren** [comment]
Oh, did you merge in the remote master? I think it's best to make a feature branch and to pull from remote master into your own master, then submit your changes in the feature branch (whether or not you rebase it on top of the latest master).

Sorry, i think I've sent this a few times, but does this flow make sense?

https://publiclab.org/wiki/contributing-to-public-lab-software#A+sample+git+workflow

In general, we prefer that you not do any merge commits -- if you keep your feature branch and master separate, you can always rebase (or ask us to do it in the pull request) and no non-linear merges need to happen. This keeps the history much easier to understand, and if necessary, to disentangle!

Thanks -- does that make sense?

**Comment by 500swapnil** [comment]
Okay I'll close this pull request then start over. Ok?

**Comment by jywarren** [comment]
You could probably force push, but either way. Sometimes it's nice to have
all attempts in one pr so they're all in context but it's not a big deal
for this one. Thanks!

**Comment by 500swapnil** [comment]
Okay I'm closing this one and starting over. I merged from remote master because it said so before to make the tests pass. I shouldnt do all that checkout upstream and merge upstream?

**Comment by 500swapnil** [comment]
I started a new PR #1083. Lets continue from that! Thanks you!

**Pull request closed without merging**
