### PR TITLE
(WIP)Multi Tag Subscription routed to the return_to page

### LINKED ISSUE #5600: Redirect user to the same page after multi tag subscription
I think we should redirect the user to the same url after multi tag subscription, instead of /subscriptions so that the user will remain on the current research note or wiki page. Implemented the same in the pr.

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #5600
image

### CODE REVIEW

**Comment by jywarren** [comment]
This is great, @SidharthBansal - sorry for slow reply, i checked with @steviepubliclab and we think this is awesome, but maybe we can do 2 things:

1. can we make the message link each tag (instead of the `[]` formatting), like `You are now following _balloon-mapping_, _aerial-photography_`?
2. can it also say `You are now following _balloon-mapping_, _aerial-photography_. You've also created an account at PublicLab.org; _click here to see your new dashboard_.`

How does that sound? Thank you so much!

**Comment by SidharthBansal** [comment]
image

**Comment by SidharthBansal** [comment]
Completed!!!
Sorry I am from C/C++ backgrounds so I forgets to use `.to_s` method often.
Thanks,
Sidharth

**Comment by gauravano** [comment]
Actually, I want to make a design suggestion here: What if we show tag pills inside the alert instead of tag in quotes? Just a suggestion for future redesign to consider. Thanks!

@SidharthBansal the test failed due to a space _ 

Screenshot from 2019-04-30 17-54-46

Please fix that. Thanks!

**Comment by jywarren** [comment]
I fixed the space, it was such a small thing. Approving CodeClimate too.

**Comment by jywarren** [comment]
Oh, wait though - does this do: 

> can it also say `You are now following _balloon-mapping_, _aerial-photography_. You've also created an account at PublicLab.org; _click here to see your new dashboard_.`

I think this just goes to the dashboard, instead of to the return_to, but linking to dashboard? Just checking, maybe I misread?

**Comment by SidharthBansal** [comment]
Oh!!! I did mistake. Really sorry. Apologies!!!

**Comment by SidharthBansal** [comment]
@Uzay-G do we need this pr with your PR. I think your pr should fix #5600 too. What do you think?
I hope that your pr is generic

**Comment by Uzay-G** [comment]
Yeah ok I will add this to my pr

**Comment by SidharthBansal** [comment]
This should be fixed by your PR. I don't think you need any changes for it.

**Comment by Uzay-G** [comment]
Well actually for now I had kept the part that returned to the subscriptions page instead of the tag. I just need to remove that part for it to return correctly.

**Comment by SidharthBansal** [comment]
Ok. This can be a medium task as there is an existing pr made by me :-)

**Comment by SidharthBansal** [comment]
Kindly check whether we will require this pr or it is already solved or it is not required or we need a new pr with some changes.

**Comment by SidharthBansal** [comment]
@Uzay-G

**Comment by Uzay-G** [comment]
No this is not resolved for now. I think once we merge this one it should work :+1:

**Comment by SidharthBansal** [comment]
Can you open up a pr for this?

**Comment by SidharthBansal** [comment]
And close this pr?

**Comment by Uzay-G** [comment]
Yeah no problem. I will use the changes from this pull request and check if it works. You can close this one :+1:

**Pull request closed without merging**
