### PR TITLE
typo replace omment with comment

### PR DESCRIPTION
**Pull request by Uzay-G**
Fixes https://github.com/publiclab/plots2/issues/6290

I think there is an error here and the `omment` should be replaced with `comment` instead for the codecov configuration. 
I might be wrong but I think it might be something worth trying out to solve the codecov coverage issues.

Thanks!

### CODE REVIEW

**Comment by Uzay-G** [comment]
Hey @kaustubh-nair and @jywarren the codecov bot worked on this pr. I've been looking around a lot to figure things out but don't understand why the travis is failing although it mentions problems with the mysql server. I'm going to look at the `codecov` branch to debug. At least the codecov bot is finally functional right?

**Comment by Uzay-G** [comment]
What do you guys think @debck @ananyaarun @keshav234156?

**Comment by jywarren** [comment]
Wow amazing! Ready to merge?

**Comment by Uzay-G** [comment]
Thanks @jywarren! Yeah I think we can merge it :smile:

**Pull request merged**
