### PR TITLE
Added a preloading page [WIP]

### LINKED ISSUE #3734: a preloading page before every page loads
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

### Problem
Building a preloading page to enhance the behaviour of loading of html pages such that whenever a page loads a preloading page shows and on complete loading main html body shows.

## Solution
You may find solution here
http://www.marketingformavens.com/blog/create-a-page-loading-animation-with-ruby-on-rails-and-ajax

or here

https://stackoverflow.com/questions/31505506/how-to-show-page-loading-between-pages 
## Code here
https://github.com/publiclab/plots2/blob/cc2df02a63b72cca7b1129aa3044933abf614a50/app/views/layouts/application.html.erb#L57

## Thank you!

 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #3734  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
preloaderworking
Here's the working

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers pls review and approve... 😄

**Comment by oorjitchowdhary** [comment]
@Rishabh570 Yes, it appears before every page...

**Comment by Rishabh570** [comment]
Okay, that's good! BTW it seems there are some other things popping on the preloading page view...other than the loading wheel, shouldn't pre-loading page just show a loading spinner?

**Comment by oorjitchowdhary** [comment]
another_example
Another example... It shows nothing.. In the first gif, it was a VirtualBox error recorded...

**Comment by oorjitchowdhary** [comment]
> Okay, that's good! BTW it seems there are some other things popping on the preloading page view...other than the loading wheel, shouldn't pre-loading page just show a loading spinner?

Only the wheel is shown

**Comment by oorjitchowdhary** [comment]
@Rishabh570 Check it now...

**Comment by rockstar777** [comment]
@oorjitchowdhary it would be great if only a single page appears when loading instead of overlapping with other content.
Thanks

**Comment by oorjitchowdhary** [comment]
preloader_page
Ok.. now there is a page and the loading wheel is on it..

**Comment by oorjitchowdhary** [comment]
I think this would be great enough..

**Comment by oorjitchowdhary** [comment]
@rockstar777 @Rishabh570 @publiclab/reviewers Pls review and approve... Thanks... 
😃

**Comment by thesparks** [comment]
Maybe it will be better to make the CCS in a separate file?

**Comment by oorjitchowdhary** [comment]
@thesparks yes I could do that.. Just waiting for the mentors to review it first

**Comment by Paarmita** [comment]
@oorjitchowdhary Can you also improve the dark background(can be changed to white) when the wheel loads and as mentioned by @thesparks plz add the CSS separately. Thanks for the PR!

**Comment by oorjitchowdhary** [comment]
I'll change the background... 
I don't know how to use CSS in a code if its in a different file.. Pls help me out there

**Comment by oorjitchowdhary** [comment]
> I'll change the background...
> I don't know how to use CSS in a code if its in a different file.. Pls help me out there

Like where should I save the .css file then, in order to link it to the code?

**Comment by oorjitchowdhary** [comment]
I have changed the background to white but I'm unable to make a separate css file and link it to the html code...
What should I do..

**Comment by oorjitchowdhary** [comment]
Can i just keep the css in the html file only?

**Comment by oorjitchowdhary** [comment]
@Paarmita @Rishabh570 @rockstar777 @publiclab/reviewers

**Comment by abizerlokhandwala** [comment]
@oorjitchowdhary add the css to app/assets/stylesheets/, to it's corresponding file.
Also make sure your class/id names do not clash, as the preloader would be on every page, it should be unique. You can also encapsulate it with a unique id so that all it's children are referenced with respect to it.
Great job!

**Comment by oorjitchowdhary** [comment]
preloader
Here you go... 
1. White background
2. CSS in a separate file
3. Public Lab page with a loader...
😃 😅

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers pls review and approve my task... Thanks

**Comment by oorjitchowdhary** [comment]
@abizerlokhandwala Thanks a lot ... I was really stuck at that problem

**Comment by kevinzluo** [comment]
I don't believe you are supposed to delete the application.css file. 

I think you need to create a new file in app/assets/stylesheets, something like `loading_page.css` . 
Then, I'm not quite sure about this part, but you need to add `*= require loading_page.css` (like all the other files) to application.css to have it be precompiled. You can then remove your stylesheet link. Also, I think jquery is already being loaded, so you do not need to do that.

**Comment by oorjitchowdhary** [comment]
> 7 Errors
> 🚫	There was a test error at: Failure: test_admin_user_should_be_able_to_see_spam_comments_page(Minitest::Result) [(sass):3945]: ActionView::Template::Error: Invalid CSS after “”: expected selector, was “0%” (sass):3945 app/views/layouts/application.html.erb:19:in ‘_app_views_layouts_application_html_erb__3211687169761575470_47281483242020’ app/controllers/admin_controller.rb:109:in ‘spam_comments’ [test/functional/admin_controller_test.rb:563](https://github.com/oorjitchowdhary/plots2/tree/oorjitchowdhary-patch-1/test/functional/admin_controller_test.rb#L563):in ‘block in '
> 🚫	There was a test error at: Failure: test_admin_user_should_be_able_to_see_spam_page(Minitest::Result) [(sass):3945]: ActionView::Template::Error: Invalid CSS after “”: expected selector, was “0%” (sass):3945 app/views/layouts/application.html.erb:19:in ‘_app_views_layouts_application_html_erb__3211687169761575470_47281483242020’ [test/functional/admin_controller_test.rb:127](https://github.com/oorjitchowdhary/plots2/tree/oorjitchowdhary-patch-1/test/functional/admin_controller_test.rb#L127):in ‘block in '
> 🚫	There was a test error at: Failure: test_admin_user_should_be_able_to_see_spam_revisions_page(Minitest::Result) [(sass):3945]: ActionView::Template::Error: Invalid CSS after “”: expected selector, was “0%” (sass):3945 app/views/layouts/application.html.erb:19:in ‘_app_views_layouts_application_html_erb__3211687169761575470_47281483242020’ app/controllers/admin_controller.rb:97:in ‘spam_revisions’ [test/functional/admin_controller_test.rb:324](https://github.com/oorjitchowdhary/plots2/tree/oorjitchowdhary-patch-1/test/functional/admin_controller_test.rb#L324):in ‘block in '
> 🚫	There was a test error at: Failure: test_moderator_user_should_be_able_to_see_spam_comments_page(Minitest::Result) [(sass):3945]: ActionView::Template::Error: Invalid CSS after “”: expected selector, was “0%” (sass):3945 app/views/layouts/application.html.erb:19:in ‘_app_views_layouts_application_html_erb__3211687169761575470_47281483242020’ app/controllers/admin_controller.rb:109:in ‘spam_comments’ [test/functional/admin_controller_test.rb:554](https://github.com/oorjitchowdhary/plots2/tree/oorjitchowdhary-patch-1/test/functional/admin_controller_test.rb#L554):in ‘block in '
> 🚫	There was a test error at: Failure: test_moderator_user_should_be_able_to_see_spam_page(Minitest::Result) [(sass):3945]: ActionView::Template::Error: Invalid CSS after “”: expected selector, was “0%” (sass):3945 app/views/layouts/application.html.erb:19:in ‘_app_views_layouts_application_html_erb__3211687169761575470_47281483242020’ [test/functional/admin_controller_test.rb:118](https://github.com/oorjitchowdhary/plots2/tree/oorjitchowdhary-patch-1/test/functional/admin_controller_test.rb#L118):in ‘block in '
> 🚫	There was a test error at: Failure: test_moderator_user_should_be_able_to_see_spam_revisions_page(Minitest::Result) [(sass):3945]: ActionView::Template::Error: Invalid CSS after “”: expected selector, was “0%” (sass):3945 app/views/layouts/application.html.erb:19:in ‘_app_views_layouts_application_html_erb__3211687169761575470_47281483242020’ app/controllers/admin_controller.rb:97:in ‘spam_revisions’ [test/functional/admin_controller_test.rb:315](https://github.com/oorjitchowdhary/plots2/tree/oorjitchowdhary-patch-1/test/functional/admin_controller_test.rb#L315):in ‘block in '
> 🚫	There was a test error at: Failure: test_should_get_/admin/queue_if_moderator(Minitest::Result) [(sass):3945]: ActionView::Template::Error: Invalid CSS after “”: expected selector, was “0%” (sass):3945 app/views/layouts/application.html.erb:19:in ‘_app_views_layouts_application_html_erb__3211687169761575470_47281483242020’ app/controllers/admin_controller.rb:349:in ‘queue’ [test/functional/admin_controller_test.rb:391](https://github.com/oorjitchowdhary/plots2/tree/oorjitchowdhary-patch-1/test/functional/admin_controller_test.rb#L391):in ‘block in '
> 2 Messages
> 📖	@oorjitchowdhary Thank you for your pull request! I’m here to help with some tips and recommendations. Please take a look at the list provided and help us review and accept your contribution! And **don’t be discouraged if you see errors** – we’re here to help.
> 📖	Pull Request is marked as Work in Progress
> Generated by 🚫 [Danger](https://danger.systems/)

Can anyone help me with these errors.... @publiclab/reviewers

**Comment by oorjitchowdhary** [comment]
I am using the exact same code on localhost and it works there perfectly... Here, I'm unable to understand whats wrong

**Comment by HarshKhandeparkar** [comment]
Maybe you can refork the repo and then copy paste the code that you have edited.

**Pull request closed without merging**
