### PR TITLE
gitpod sprockets error fixes

### LINKED ISSUE #9211: Sprockets error on gitpod
- Gitpod  is showing the `Sprockets::FileNotFound in Home#home` on launching the browser
- Running yarn install from the gitpod terminal then refreshing the web page fixes the issue but we do have this command in the gipod docker file...maybe separate it and run it as separate?

Recent deprecation of  `bundle install --without production ` which is part of the script that also has the `yarn install` command could be the prob?  removing this on #9210 to see if the error persists

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #9211  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
running yarn install separately seems to have fix it @RuthNjeri @shadowoflight could you please confirm if gitpod starts correctly for you when you get a sec? thanks

**Comment by shadowoflight** [comment]
Yep checked it, the sprockets error seems to be fixed by yarn install. Although a new error seems to be thrown; Error:NameError in HomeController#home @cesswairimu

**Comment by cesswairimu** [comment]
@shadowoflight  do you get this on launching?

**Comment by cesswairimu** [comment]
I have noticed the db is empty maybe db:setup is not ran now :thinking:

**Comment by shadowoflight** [comment]
Yes this error popped up after yarn install fixed the sprockets error. I observed that on relaunching gitpod and running yarn install again everything seems to be working fine. I don't know why the commands didn't completely run first time resulting in the aforesaid error. @cesswairimu

**Comment by cesswairimu** [comment]
That's strange :confused: let me try to replicate Thanks

**Review by RuthNjeri — APPROVED** [review]
It is working correctly, thanks @cesswairimu  🎉

**Comment by RuthNjeri** [comment]
Screenshot 2021-02-17 at 20 28 28

It's working on my end but I tested it on this PR...these changes have not been merged to the main branch and we cannot test it on our respective PRs yet...

**Comment by cesswairimu** [comment]
@RuthNjeri  are you able to login?

**Comment by RuthNjeri** [comment]
I'm now getting an error... @cesswairimu 
Screenshot 2021-02-17 at 21 59 52

**Comment by jywarren** [comment]
Thanks for working this problem, everyone!!!!

**Comment by jywarren** [comment]
@RuthNjeri can you try again? i just tried it and didnt see that but maybe we need to debug it too... thanks!!

**Comment by RuthNjeri** [comment]
Hi @jywarren I have tested it and it is working fine now..

**Pull request merged**
