### PR TITLE
change the function t to translation

### PR DESCRIPTION
**Pull request by kushaggarwal**
change the function t to translation of app/views/users/_likes.html.erb  in reference to the issue no. #6880

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kushaggarwal** [comment]
Thanks @ananyaarun 
Happy to successfully complete my first contribution

**Comment by cesswairimu** [comment]
Great :tada: :tada: Thanks @ananyaarun and @nstjean for the reviews and feedback. Thanks @kushaggarwal for working on this and welcome to PublicLab :balloon:

**Comment by kushaggarwal** [comment]
Thank you  @nstjean @ananyaarun @cesswairimu  for your help and guidance
Really happy to have my pull request merge and becoming part of this organisation 
Will keep in my mind about merging of further pull requests

**Comment by jywarren** [comment]
Hooray!!!

**Pull request merged**
