### PR TITLE
Consolidating link icons to meta file

### PR DESCRIPTION
**Pull request by k-sau**
Fix for #3093
This includes: 
+ Consolidating link icons to meta file.
+ Added link icon to `/questions` route

Also don't know how my Gemfile.lock got updated. Is this a problem?

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this is looking great, but would you mind removing the Gemfile.lock from your PR, as I think it's just a version tweak? https://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git

**Comment by jywarren** [comment]
This looks great. Could we get a screenshot too?

**Comment by jywarren** [comment]
Lots of hard work here, amazing, by the way! So glad to have your help!

**Comment by k-sau** [comment]
Thanks!! Yeah that Gemfile.lock was the toughest one :3 

Here are the screenshots 
screenshot from 2018-09-14 08-54-03
screenshot from 2018-09-14 08-53-48

**Comment by jywarren** [comment]
Looks super!!! Thank you!!!

**Comment by jywarren** [comment]
If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Pull request merged**
