### PR TITLE
'Read More' button UI Improvement

### LINKED ISSUE #4990: Improve the UI of readmore blogs button
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* Change the UI of Readmore button so that it can be differentiated from individual notes Readmore button.

Screenshot from 2019-03-10 20-34-04

* Update will be done in plots2/app/views/home/home.html.erb
* Go for a design similar as given image in `ask a question` button but smaller in size.

Screenshot from 2019-03-10 23-08-48

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by coderbeetle**
Fixes #4990

I'm not a big fan of inline styling, but since I was prompted to only make changes in `plots2/app/views/home/home.html.erb`, here it goes!
image

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by coderbeetle** [comment]
Hey @ananyaarun ! I used the relevant class for most of the styling, but I had to use some inline CSS to tweak the button's size. The issue I was assigned to asked for the 'Read More' button to be similar in style to the other blue buttons, just smaller in size. 
Feel free to suggest any other solutions that come to mind!

**Comment by CleverFool77** [comment]
@coderbeetle It's always a good practice to create a different branch for the PR instead of master :). So that you can work on different issues separately

**Comment by CleverFool77** [comment]
You can ask for help if you come across any problem :wink: 
Thanks :)

**Comment by SidharthBansal** [comment]
I am closing this PR as the contributor is inactive since a long period of time
Feel free to reopen it if needed.

**Pull request closed without merging**
