### PR TITLE
Add solr changes to cloud9 installation script

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks pretty good, Ananyo, thanks -- you tried it out in cloud9 yourself?

**Comment by jywarren** [comment]
And do you think it's totally necessary after #861 -- i guess if it's just in the install file it's just as easy, but it as of that PR, solr is no longer necessary for running the app or tests, except for the special `rake test:solr` tests. Thoughts?

**Comment by jywarren** [comment]
I'm going to close this, as I don't think it's needed after #832 changes and README updates in #887 -- which help people do Solr testing in Cloud9 only if it's necessary (optional). Thanks!

**Comment by ananyo2012** [comment]
@jywarren Shouldn't we add the java dependencies in the cloud9 installation script? Since it bis required for testing. Perhaps I should reopen this one or make or make a new one?

**Comment by jywarren** [comment]
Hi, Ananya - we're not requiring people to run the Solr-specific tests in
their dev environments (I clarified this in the README but if it's not
clear enough please suggest changes, thanks!). I'd like to leave those
running just in TravisCI since it substantially increases the burden on new
contributors and slows the testing process.

**Comment by ananyo2012** [comment]
And two more things I mentioned earlier in https://github.com/publiclab/plots2/pull/861#issuecomment-251287929 and https://github.com/publiclab/plots2/pull/861#issuecomment-251292543. First is we can use `rake test TEST=test/solr/*_test.rb` to run any tests in the solr directory. And secondly the `rake sunspot:reindex` is failing due to the `disabled:true` in development in the sunspot config.

**Comment by ananyo2012** [comment]
Uh ok that's perfectly fine Jeff ! yes we can make this point bit more clearer. I see an incomplete in the [Testing](https://github.com/publiclab/plots2#testing) section inline 155. I think you wanted to mention 

> ... and solr tests

**Comment by jywarren** [comment]
thanks, yes please if you could at least open an issue that would be great
-- i'm scrambling with Solr production issues and other work at the moment
-- and a PR also would be welcome. And yes, there should be no need to run
reindex on development. Many thanks!

**Comment by ananyo2012** [comment]
Ok Jeff good luck with it. I will find any changes required in the readme to make it easier for first timers and make a PR.

**Pull request closed without merging**
