### PR TITLE
Fixed pluralization in Admin Page

### LINKED ISSUE #6828: Fix pluralization in admin page - I
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Problem
comment_section

The pluralization in the screenshot above is incorrect (i.e. it should be "1 comment" not "1 comments" )

### Code Snippet
https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb/#L256

In order to solve this problem we need to write a conditional statement to pluralize when the count>1 . In order to do this we will be using [pluralize method](https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize).

### Solution

```ERB
<li><h5><a href = "/profile/comments/<%= params[:id] %>"><%= pluralize(Comment.where(uid: @profile_user.id).count, 'comment', plural: 'comments') %></a></h5></li>
```
### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you until a certain duration  if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

##  💬   Get help
If you need any help - here are some options: 

- Comment below.
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by genesis331**
Fixes #6828 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Please attach the screenshots!
Thanks for doing a superb job

**Comment by chen-robert** [comment]
Great PR @genesis331, looks good to me. 

If you're part of GCI, be sure to check out the welcoming post at https://github.com/publiclab/plots2/issues/6808. You should also make sure that you've completed the installation task for `plots2` before working on any issues. 

Glad to have you here :tada:

**Comment by pydevsg** [comment]
Great work @genesis331 , please share a screenshot after the updated code , thanks :)

**Comment by SidharthBansal** [comment]
Please approve the pr after screenshots are viewed.

**Comment by genesis331** [comment]
No problem, please give me a second.

**Comment by SidharthBansal** [comment]
Hello, we just asked for screenshots. No need to close this pr

**Comment by genesis331** [comment]
So sorry, I closed this PR because I haven't complete the installation task. But these days I'm trying hard and having difficulties on installing the plots2. I've decided to give the chance to other GCI participants.

**Pull request closed without merging**
