### PR TITLE
Fixes #577

### LINKED ISSUE #577: Version control schema file for using development database
As mentioned in https://github.com/publiclab/plots2/pull/545#issuecomment-223821888 it would be better if we version control the schema file for using the development database as it would be efficient in many ways and reduce the hassle of updating the development.sqlite.example file each time a new migration is introduced.The steps involved in the process would be:
- Deleting the development.sqlite.example files from repository
- Renaming the schema.rb.example file to schema.rb
- Removing the schema.rb from .gitignore so it can be version tracked

For deployment we have to run `rake db:create` and then `rake db:setup`. That's all. I think we won't need any rake tasks as there re just two commands. The process is independent of any database used. The readme instructions will be correspondingly changed.

@jywarren If you approve this I can make a PR with the necessary changes.

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added

Modify cloud9 installation script

Update readme and pull request template

Update schema.rb.example

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren The installation script is working smoothly on cloud9. You can pull this branch and check it. I have also updated the schema.rb.example file. It was not updated since the last migration.

**Comment by jywarren** [comment]
Excellent, thanks, running tests now!

**Comment by ananyo2012** [comment]
@jywarren After this is merged we can safely remove the development.sqlite.example file from the repository.

**Comment by jywarren** [comment]
Actually i see nothing testable changed; thanks! We should do a screencast (or an asciicast -- https://asciinema.org/) of the cloud9 process sometime. It's very helpful to see working correctly!

**Comment by jywarren** [comment]
Great; I'll remove that in a followup commit.

**Comment by jywarren** [comment]
Manually  merged. Thank you! Closes #577.

**Comment by ananyo2012** [comment]
Oh I love the idea of a screencast! Will try to make one if I get time.
ᐧ

**Comment by jywarren** [comment]
cool! I have made them for MapKnitter, for example:
https://publiclab.org/wiki/developers#Installation+videos

But the asciicast is a really nice way to do it also, and I bet it can be
installed on a brand-new machine in cloud9.

**Pull request merged**
