### PR TITLE
Updated "What makes this project different" section and the section b…

### PR DESCRIPTION
**Pull request by Aneal-Sharma**
…efore it

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Aneal-Sharma** [comment]
@publiclab/reviewers

**Comment by Aneal-Sharma** [comment]
@jywarren @btakita @wakingweb

**Comment by gauravano** [comment]
Hi @Aneal-Sharma, please mention the issue number in this [comment](https://github.com/publiclab/plots2/pull/4877#issue-255645061) as highlighted, it will help us to know the relevant issue and the issue will be closed automatically after the PR gets merged. Thank you!

**Comment by SidharthBansal** [comment]
Can you please rebase your changes so that we can review and merge it?
Thanks for contributing at PL

**Comment by gauravano** [comment]
Closing this PR as the contributor is inactive and changes are minor. Thanks!

**Pull request closed without merging**
