### PR TITLE
ability to set wiki main image to none

### PR DESCRIPTION
**Pull request by jywarren**

### CODE REVIEW

**Comment by jywarren** [comment]
`Mysql2::Error::ConnectionError: Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused")`

Hmm, this is indicating that this can come from a change to docker-compose: https://stackoverflow.com/questions/55427429/rails-app-using-docker-compose-wont-connect-to-the-mysql-container but ours haven't changed in months... https://github.com/publiclab/plots2/tree/master/containers

**Comment by jywarren** [comment]
Maybe a policy changed upstream?

**Comment by ebarry** [comment]
This is a very cool PR! fixes a really old gap

**Comment by jywarren** [comment]
Thanks, Liz!

Upstream errors seem to be resolved from @icarito's work, here. Last issue is an actual test failure:

```

 FAIL["test_update_wiki_selecting_no_image", #<Minitest::Reporters::Suite:0x000056498423f860 @name="WikiControllerTest">, 80.43184560200007]
 test_update_wiki_selecting_no_image#WikiControllerTest (80.43s)
        Expected: 0
          Actual: nil
        test/functional/wiki_controller_test.rb:233:in `block in <class:WikiControllerTest>'
```

**Comment by jywarren** [comment]
```
ActionView::Template::Error:         ActionView::Template::Error: undefined method `main_image_id' for nil:NilClass
```

**Pull request merged**
