### PR TITLE
[WIP] Leaflet Environmental layers integration

### LINKED ISSUE #3094: Integrate leaflet-environmental-layers into PublicLab.org
We have to integrate leaflet-environmental-layers using npm : https://www.npmjs.com/package/leaflet-environmental-layers

Things to brainstorm : 
1.) Correct place to show ? A new page maybe ? 
2.) Which combinations of layers to show  ?

Follow ups : 

- [x]  Remove skytruth map layer from profile page .

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.
Fixes #3094 !

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Integration is successful ...but currently resolving the issue here that leaflet-menu is not scroll-able due to DOM scroll bar .

**Comment by sagarpreet-chadha** [comment]
`.leaflet-control-layers {
        max-height: 200px;
        overflow: auto; }`

The above line made the menu scroll-able 😄 !

**Comment by jywarren** [comment]
Awesome, ready to go, then?

**Comment by sagarpreet-chadha** [comment]
Yes Jeff :+1:

**Pull request merged**
