### PR TITLE
Combined wiki/note grids

### LINKED ISSUE #3758: Combined wiki/note grids using [node:_____] syntax, for inline grids
This may be a bit more complex, but we'd love some help. 

We have inline grids on pages like this: https://publiclab.org/wiki/air-sensors

This means we have different ways to include inline tables of other pages, using syntax like:

`[notes:______]` or `[wikis:________]`

The templates for these are here:

https://github.com/publiclab/plots2/tree/master/app/views/grids

But sometimes you want to have both wikis and notes displayed. It'd be great to have a combined grid type for any node (see our /docs/ folder and the DATA MODEL) - with format:

`[node:_____]`

See how I've kind of done a broken version of this by just using one grid tag after the other -- showing 2 tables one after the other (a hack! Not very nice but... kind of works):

image

One issue is that notes and wikis have different columns - like the timestamp or author column. Let's try to find what overlaps and display those columns so it makes some sense -- but we can tweak this later.

### PR DESCRIPTION
**Pull request by ValentinaTironi**
Fixes #3758 

Here is a gif showing how it works.
wiki_notes

### CODE REVIEW

**Comment by jywarren** [comment]
This is amazing!!! Fantastic work. I'm merging this now! If you'd like to contribute a follow-up, it could be helpful to implement a test similar to one of these: 

https://github.com/publiclab/plots2/blob/master/test/unit/node_shared_test.rb

**Comment by jywarren** [comment]
Awesome!!! 👍 👍 👍

**Comment by ValentinaTironi** [comment]
@jywarren Thank you so much! I can try do the test!

**Comment by jywarren** [comment]
awesome!

**Comment by ValentinaTironi** [comment]
@jywarren Hi! I had complications when I did `git push`, I had to do a `git rebase` so, when I did `git push` again github pushed all commits again. So, I had to do a new pull request with test and code. I'm so sorry for inconveniences. Here is the new pr: https://github.com/publiclab/plots2/pull/4056/

**Pull request merged**
