### PR TITLE
Remove styling for leaflet-marker-icon

### PR DESCRIPTION
**Pull request by nstjean**
Addresses problem mentioned in #6969

### CODE REVIEW

**Comment by nstjean** [comment]
This styling was originally in rich.html.erb for the /post/ location form. The style was causing an issue with some map layers, but wasn't doing anything to the color of the marker in /post/ .

**Comment by nstjean** [comment]
I am not understanding the codecov report. This patch affects 0% of the coverage, but it's showing project is -4.89%?

**Comment by jywarren** [comment]
Hmm. It's possible there is a problem with it... let's try restarting it. I'll take a screenshot so we can compare once it finishes again. 

image

**Comment by nstjean** [comment]
@jywarren It worked this time! All set to merge.

**Comment by jywarren** [comment]
Great! I assume @crisner sees this but just cc'ing in case. Thanks!

**Pull request merged**
