### PR TITLE
Updated TESTING.md with the requested changes - #3112.

### LINKED ISSUE #3112: Update the TESTING.md file
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [doc/TESTING.md](https://github.com/publiclab/plots2/blob/master/doc/TESTING.md) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -1,8 +1,8 @@
 (Moved from https://github.com/publiclab/plots2/wiki/Testing)
 
-Run all basic rails tests with `rake test`. This is **no longer required for submitting pull requests** (see [Pull Requests](#pull-requests), below), and to confirm you have a working local environment.
+Run all basic rails tests with `rails test -d`. This is **no longer required for submitting pull requests** (see [Pull Requests](#pull-requests), below), and to confirm you have a working local environment.
 
-`rake test:all` runs **all** tests. This includes Jasmine client-side tests and Solr-dependent tests -- not recommended for everybody!
+`rake test:all` runs Jasmine client-side tests and coverage reporting.
 
 ## Pull Requests
 
@@ -32,20 +32,20 @@ Solr (search) tests (generally not recommended!) require [installing the Solr se
 
 ****
 
-If you get stuck on testing at any point, you can _open a pull request with your changes_ -- please add the prefix `[testing]` to the title -- which will then be automatically tested by our TravisCI service -- which runs **all tests** with `rake test:all`. If your additions are pretty basic, and you write tests against them, this may be sufficient without actually running the whole environment yourself! 
+If you get stuck on testing at any point, you can _open a pull request with your changes_ -- please add the prefix `[testing]` to the title -- which will then be automatically tested by our TravisCI service -- which runs **all tests**. If your additions are pretty basic, and you write tests against them, this may be sufficient without actually running the whole environment yourself! 
 
 
 ## Running just one type of test
 
 If you want to run just unit tests, to save time, you can run:
 
-`rake test:units`
+`rails test test/unit`
 
 Likewise, for functional or integration tests:
 
-`rake test:functionals`
+`rails test test/functional`
 
-`rake test:integration`
+`rails test test/integration`
 
 
 ## Running just one test
@@ -54,11 +54,11 @@ Likewise, for functional or integration tests:
 
 To run one test file:
 
-`ruby -I test test/unit/some_file.rb`
+`rails test test/unit/some_file.rb`
 
 And to run just a single test within a file:
 
-`ruby -I test test/functional/some_file.rb --name=name_of_test`
+`rails test test/functional/some_file.rb:[line number of the test]`
 
 ### Testing mails in development envirmoment
 
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by codiusnomadus**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Fixes #3112

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
It looks good to me. @jywarren can you review this. Thanks @codiusnomadus

**Comment by Souravirus** [comment]
I think we should also change the jasmine commands to teaspoon mocha. Should we do this in this PR or make another issue for it. What do you think @jywarren?

**Comment by jywarren** [comment]
Let's do another issue! @Souravirus, do you think this one is ready to
merge? Thanks!

**Comment by Souravirus** [comment]
Yeah this is ready to merge

**Comment by jywarren** [comment]
Thanks, and super work! 🎉

**Comment by codiusnomadus** [comment]
Thanks!

**Pull request merged**
