### PR TITLE
Standardizing the results on tag pages

### LINKED ISSUE #1: tag page shows code instead of running code.
http://publiclab.org/tags

```

Research notes by location

    tid); if ($count) { /* don't show terms with 0 count */ echo("
    ".$term->name." (".$count.")
    "); } } /* end foreach */ ?> 

Research notes by tool

    tid); if ($count) { /* don't show terms with 0 count */ echo("
    ".$term->name." (".$count.")
    "); } } /* end foreach */ ?> 
```

### PR DESCRIPTION
**Pull request by P0NC1K**
Fixes https://github.com/publiclab/plots2/issues/9603

So I forked the repository, cloned it  , added an upstream then set my local upstream to a remote upstream(hope I said everything correct). In other words , had a lot of fun learning how to contribute to an open source. Although I am still not sure if I did it right )))

About the fixes, I am not sure what I really fixed )) , but from what I saw changed a little bug in the _contributors.html.erb 
image

As well in the en.yml perfected the no_contributors.
image

### CODE REVIEW

**Review by TildaDares — APPROVED** [review]
LGTM🎉🎉. Would it be possible for you to add a screenshot of the changes you made? Thanks.

**Comment by TildaDares** [comment]
Do you mind adding the issue number like this 'Fixes #1234' and then change the title of this PR to a more descriptive title? Also you can close the PRs you opened before.

Good job @P0NC1K.

**Comment by P0NC1K** [comment]
Thanks ,I'll do it right away.

**Review by cesswairimu — APPROVED** [review]
Fantastic :tada: thanks for working on this @P0NC1K

**Pull request merged**
