### PR TITLE
set image width to 100% for answers to questions

### PR DESCRIPTION
**Pull request by ykl7**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ykl7** [comment]
@jywarren As per your advice on #831 , I've opened a PR so that the maintainers can have a look and test. Please check and inform if I went wrong somewhere

**Comment by ykl7** [comment]
@jywarren Sorry, this violates the contributing guidelines of the repository. I have closed this PR and will open a new one.

**Comment by ykl7** [comment]
@jywarren As per your advice on #831 , I have sent a PR so that others may check the code and test. Please review and inform if any changes are to be made. Also, if there is any violation of contributing guidelines, I will send a new PR.

**Comment by jywarren** [comment]
Hi, this looks great and I expect to merge it in in a bit! Thanks.

**Comment by jywarren** [comment]
Thank you! I've merged your changes; much appreciated. If you're looking for a new project, please do take a look at our [help-wanted issues](https://github.com/publiclab/plots2/labels/help-wanted) -- and I'd be happy to add links to relevant lines of code to help flesh any of those out a bit.

**Comment by ykl7** [comment]
@jywarren I'll be sure to look through the issues and try to contribute more

**Pull request merged**
