### PR TITLE
DRY up emoji image urls in application helper

### PR DESCRIPTION
**Pull request by seabl**
No issue opened

### CODE REVIEW

**Comment by seabl** [comment]
@publiclab/reviewers review please. Thanks!

**Comment by seabl** [comment]
@jywarren Can you help me figure out why some checks are failing here? Thanks!

**Comment by jywarren** [comment]
Hm, I restarted it to see if it was a timing issue!

**Comment by seabl** [comment]
This one is a puzzle. Maybe an issue with Travis.

**Comment by SidharthBansal** [comment]
LGTM 🎉 
Can you please see if there is any remaining work in this PR?

**Comment by seabl** [comment]
@SidharthBansal I don't think so. There were some problems with the checks when I first pushed this. Did you find out what was the issue?
And thanks for review.

**Pull request merged**
