### PR TITLE
add comments to search

### LINKED ISSUE #1977: Add comments to search
Our new search system is real nice! We have basics of comment search built:

https://github.com/publiclab/plots2/blob/01fac7cda6ab3df0ee9ba492f489edeef741ece9/app/services/typeahead_service.rb#L35-L46

But it needs to be integrated. 

We'll need a `search_comments` function similar to this one:

https://github.com/publiclab/plots2/blob/01fac7cda6ab3df0ee9ba492f489edeef741ece9/app/services/typeahead_service.rb#L130-L143

which uses the above `comments` method instead of `notes`...

Then we can add a line after this one to include comments into search results!

https://github.com/publiclab/plots2/blob/01fac7cda6ab3df0ee9ba492f489edeef741ece9/app/services/typeahead_service.rb#L90-L92

I think that should work... let's try it out!

### PR DESCRIPTION
**Pull request by ViditChitkara**
closes #1977

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, awesome! 

What do you think about a functional test to look for comments? 

https://github.com/publiclab/plots2/blob/master/test/functional/typeahead_api_test.rb

It could be a pretty simple addition, no?

Thanks!!

**Comment by ViditChitkara** [comment]
@jywarren Sure thing!! Will do it asap

**Comment by ViditChitkara** [comment]
@jywarren this is ready too!

**Comment by jywarren** [comment]
Wow great!!!!! This is amazing.

**Comment by jywarren** [comment]
Hi, hmm, not sure -- https://publiclab.org/api/typeahead/all?srchString=unobtainable doesn't seem to be returning https://publiclab.org/notes/david_uwi/09-30-2016/homemade-spectrometer#c18110

What do you think? Shall we try to write a unit test for a comment to see if we can pin down what's missing? 

We could model on this:

https://github.com/publiclab/plots2/blob/ccd55b286d89742c9e96abec01612909be912f55/test/unit/node_test.rb#L21-L25

Or a functional test like in this file: 

https://github.com/publiclab/plots2/blob/master/test/functional/typeahead_api_test.rb

What do you think?

**Comment by ViditChitkara** [comment]
Well that's odd!! I'll check it out!! Will write a unit tests!

**Comment by jywarren** [comment]
awesome, thanks!

**Comment by ViditChitkara** [comment]
Probably found a fix for this!! Opening a pr for the changes

**Comment by jywarren** [comment]
Awesome, is there a related PR open already? Thanks!!

**Comment by ViditChitkara** [comment]
Yes, #2047

**Comment by jywarren** [comment]
Oops, i see -- over here: https://github.com/publiclab/plots2/pull/2047

**Comment by ViditChitkara** [comment]
No very sure whether the fix would work for mysql2 but let's hope for the best!!

**Pull request merged**
