### PR TITLE
Improved installation instructions

### PR DESCRIPTION
**Pull request by JanviMahajan14**
I have updated a minor change in docs to make it easy to copy one file to another. Please review this change.
Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@gauravano @jywarren 
can we merge here please :)

**Comment by JanviMahajan14** [comment]
@jywarren @nstjean @gauravano Please have a look. Looking forward to learn and contribute more in the community.Thanks!

**Comment by nstjean** [comment]
I think this travis test needs to be re-started, it gave me an error earlier as well.

**Comment by jywarren** [comment]
Fantastic, thank you!!!

**Pull request merged**
