### PR TITLE
Tag generated for questions

### LINKED ISSUE #3704: Add "from:____" tag to question breakout prompts
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/notes/_comment.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -126,7 +126,7 @@
     <% end %>
 
     <% if comment.body.include?('?') %>
-      <p class="alert alert-info">Is this a question? <a href="/questions/new?title=<%= comment.body %>">Click here</a> to post it to the <a href="/questions">Questions page</a>.
+      <p class="alert alert-info">Is this a question? <a href="/questions/new?title=<%= comment.body %>&tags=from:<%= comment.cid %>">Click here</a> to post it to the <a href="/questions">Questions page</a>.
       </p>
     <% end %>
     <% if comment.parent.has_power_tag('activity') && current_user && current_user.id == comment.uid %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by mardelvalle**
A tag which will be connected to the original comment where the question was generated from will be added.

Fixes #3704 **(writing issue number as Fixes #3704 in PR body automatically closes the issue after PR gets merged)**

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by mardelvalle** [comment]
@publiclab/reviewers hi guys! Does this change look ok?

**Comment by jywarren** [comment]
Hmm, it looks right but there seems to be an error! Can you open the Travis logs and scan down to the bottom to see what went wrong? I think you should be able to click the little red X...  but if you can't seem to find it i can dig in there and see the error by scrolling down a long ways:

image

In fact our bots are supposed to paste the errors back in, but occasionally they fail! 🤖 But we can look into this ourselves. Happy to help if you'd like! The log output can be very long. 📜 🔍

**Comment by gauravano** [comment]
Hi @jywarren @mardelvalle the build stopped due to unexpected error :( 

build_stop

I restarted it, just now. Let's see how it goes!

**Comment by gauravano** [comment]
@mardelvalle could you please write issue number so that we can review it. Thanks!

**Comment by mardelvalle** [comment]
Hi @jywarren! I don't think I am seeing the same thing you are seeing with the x.
verified

**Comment by mardelvalle** [comment]
@gauravano sure! #3704

**Comment by jywarren** [comment]
Oh, awesome work @mardelvalle and thanks for the help, Gaurav! 

Sometimes something mysterious goes wrong and it just needs to be restarted. I'll merge this now! Great work!

**Pull request merged**
