### PR TITLE
fixed issue #329 image size problem in post screen

### PR DESCRIPTION
**Pull request by ykl7**
#329 fixed by changing required lines of code

Following requirements completed:

1. all tests pass using `rake test`
2. code has been rebased on top of latest master after checking for new pull requests
3. pull request name describes the task accomplished i.e. the bug fixed, with the issue number referenced

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! This looks great, thank you so much for contributing!

A couple things before we merge. First, i see you've opened a pull request from your master branch. It's much easier for you (for reasons I'll mention in a moment) if you create a named feature-specific branch and open a pull request from there. You can do that and open a new PR with:

    git checkout -b new-feature-branch-name

...then make your changes, then:

    git push origin new-feature-branch-name

Then go to [your fork of the project](https://github.com/ykl7/plots2/) and there should be a yellow notice prompting you to open a pull request. 

The reason is that if you have to make more changes, or rebase them, it's really helpful to have a master branch in your local copy to refer to or rebase over. However, as this is a `first-timers-only` issue, and I'm very excited to integrate your contributions, I'll propose a simpler route:

I mention this because I see you've checked in changes to your `development.db` file, which shouldn't be part of your commit (they're anything that's been run in your local database). We're going to try to rearrange things so that database changes don't get picked up by git, but for now we just have to be careful not to commit those. Sorry for the trouble!

I've gone ahead and modified your commit with a rebase, preserving your author name, and will pull the commit in that way. All tests pass, and i'm closing this now. It's merged!

By the way, is this your first time contributing to an open source project? I'm just asking because we tagged the issue "first-timers-only" and I'm curious how you found out about the issue. We're working to make our code more welcoming and I hope it worked!

Thanks again,
Jeff

**Comment by ykl7** [comment]
Thanks for all the advice Jeff. I work primarily on the iOS platform, I've been working on it for about a year now. I've done various projects but this is my first foray into Web Development and I intend to pursue it. The README is very helpful and everything went off without a hitch. Sorry I forgot to remove the development.db file from the commit, it just slipped my mind. However, I thought I had to fork the master branch, work on a feature branch in my repository, rebase and merge and then send a PR, which is what I did. I'll create a branch and fork the next time I work on it.

**Comment by jywarren** [comment]
Ah, ok, that makes sense. Yes, you can just leave it in your own remote feature branch until merged. That way you have a place to pull the latest master to on your own machine, in case you have to rearrange/rebase things onto the latest again. 

Thanks again! Did you find us through http://firsttimersonly.com, or some other way?

**Comment by ykl7** [comment]
Actually, one of my friends told me about this organisation. So, I looked it up and also found a GitHub organisation page. The website seemed like a good way to start contributing, and here I am.

**Comment by jywarren** [comment]
Super, well, welcome again!

**Pull request closed without merging**
