### PR TITLE
#1776 tagged_by_author method added

### PR DESCRIPTION
**Pull request by SidharthBansal**

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Sorry for the wrong indentation. 
Currently, I don't know rails testing. I have never implemented testing on any of my existing projects. So, I am trying to learn it and make a commit.
Thanks

**Comment by jywarren** [comment]
Here are some good resources for Rails testing --

https://www.driftingruby.com/episodes/basic-testing-introduction-in-rails

https://www.benlcollins.com/rails/introduction-to-testing-in-rails/

For this, you can look at other tests in `/test/unit/node_test.rb`, as examples. Take a look at what @zhirschtritt is doing in this PR for a good example:

https://github.com/publiclab/plots2/pull/1796

A good first step would be to create a new test at the bottom of the file, and write your first assertion. It could be something as simple as `assert true` -- and then push up a commit to this PR. You'll see your test pass. Then you can start to create the scenario you'd like to be testing out, and add more meaningful assertions. Make sense?

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by SidharthBansal** [comment]
Sorry, it got too late. Yes, I am stuck. I have gone through both the links provided by you. Then I tried to use testing in one of my projects. 
I think the following could be 
  test "return nodes tagged by author and user_id" do
    jeff = rusers(:jeff)
    jeff_notes = node(:one)
    jeff_notes.add_tag('replication:123',jeff)
    tagged_note = Node.tagged_nodes_by_author('replication:123',2)
    assert_not_nil tagged_note
    assert_equal jeff_notes, tagged_note
  end
But it is showing undefined method tagged_nodes_by_author error. I tried to figure out but it was a futile attempt.

**Comment by SidharthBansal** [comment]
Sorry for replying too late. I have gone through both rails testing tutorials. I have also then used in one of my applications. I think the following can be a solution
  test "return nodes tagged by author and user_id" do
        jeff = rusers(:jeff)
        jeff_notes = node(:one)
        jeff_notes.add_tag('replication:123',jeff)
        tagged_note = Node.tagged_nodes_by_author('replication:123',2)
        assert_not_nil tagged_note
        assert_equal jeff_notes, tagged_note
  end
But it is showing undefined method. I tried a lot to combat this but I cant'.

**Comment by SidharthBansal** [comment]
Sorry for replying too late. I have gone through both rails testing tutorials. I have also then used in one of my applications. I think the following can be a solution
```test "return nodes tagged by author and user_id" do
jeff = rusers(:jeff)
jeff_notes = node(:one)
jeff_notes.add_tag('replication:123',jeff)
tagged_note = Node.tagged_nodes_by_author('replication:123',2)
assert_not_nil tagged_note
assert_equal jeff_notes, tagged_note
end
```
But it is showing undefined method. I tried a lot to combat this but I cant'.

**Comment by SidharthBansal** [comment]
Sorry for replying too late. I have gone through both rails testing tutorials. I have also then used in one of my applications. I think the following can be a solution
```Unit test
test "return nodes tagged by author and user_id" do
    jeff = rusers(:jeff)
    jeff_notes = node(:one)
    jeff_notes.add_tag('replication:123',jeff)
    tagged_note = Node.tagged_nodes_by_author('replication:123',2)
    assert_not_nil tagged_note
    assert_equal jeff_notes, tagged_note
end
```
Also, I have lost the fork. So, was trying to find a way to push changes into this pull request. But can't find any. I guess I need to close this pr and open another one that is the only solution.
But it is showing undefined method. I tried a lot to combat this but I cant'.

**Comment by jywarren** [comment]
Hey, glad to hear from you! No worries, we're here to help. It does look like the fork is no longer here, and that's weird; i've never seen that before. But no worries -- open a new one with this original contribution you've already made:

```ruby

  #select nodes by tagname and user_id
  def self.tagged_nodes_by_author(tagname, user_id)
  	Node.where('term_data.name = ?', tagname)
                .includes(:node_tag, :tag)
	              .where('node.uid = ?', user_id)
  end
```

Then add your test. Let's see how it goes in a PR and I can help debug from there. If you open a new PR (sounds like a good idea) then just link to it from here to be sure we connect this conversation. 

One thing that recently happened is we did a big upgrade to Rails 4.1, and some things have changed, so the errors you're seeing may not be at all related to your work! `rusers` has become `users` now, for example, and `node()` is now `nodes()`. So maybe that'll help -- but open a PR with your test and we can take a look together. Thanks!!!

**Comment by SidharthBansal** [comment]
Thanks a ton!!!

**Comment by SidharthBansal** [comment]
Pull request  #1831

**Pull request closed without merging**
