### PR TITLE
added spam-button #2732

### PR DESCRIPTION
**Pull request by dewanhimanshu**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by dewanhimanshu** [comment]
please look into this PR

**Comment by jywarren** [comment]
This looks super! Could you upload a screenshot? 

Thanks!!! 🎉

**Comment by dewanhimanshu** [comment]
can you plz tell me the route where i can find the added button?

**Comment by dewanhimanshu** [comment]
ok found out that
screenshot from 2018-07-10 01-44-44

**Comment by jywarren** [comment]
Aha, looking great! Actually maybe @ViditChitkara has some thoughts on this since there is an ongoing effort to simplify some of these -- in https://github.com/publiclab/plots2/pull/2983

However, this looks good except that the buttons could ideally be on the same line. I think we can probably merge this and then just be sure https://github.com/publiclab/plots2/pull/2983 rebases cleanly on top of it. We're very glad for your help!

**Comment by Gauravano** [comment]
Hi @dewanhimanshu , the preview is looking great but if you don't mind here is a slight change https://github.com/publiclab/plots2/pull/2733#discussion_r192030374 , with these changes we can have required buttons only.

**Comment by dewanhimanshu** [comment]
ok no problem . Do i have to make any changes in this PR ?

**Comment by Gauravano** [comment]
Actually change just require addition of an if statement so, doing this in this PR would be good. Thanks!

**Comment by dewanhimanshu** [comment]
sorry i have delete my forked repo . So should i open new PR for this

**Comment by Gauravano** [comment]
No issue! we can optimize this in another PR. Thanks for helping @dewanhimanshu !

**Comment by dewanhimanshu** [comment]
welcome @Gauravano

**Comment by dewanhimanshu** [comment]
can you take a look at my Edit icon swap #3014 PR

**Comment by ViditChitkara** [comment]
Hi @dewanhimanshu , we are actually trying to deprecate separate interfaces (such as questions/comment) and keeping just one to make it simple (notes/comment). With the changes being done, there are some inconsistencies with the buttons on top right corner of comment (edit, delete, etc.). The tooltip appears only for spam button, ideally it should be all 4. Would you like to have a go at it?
For reproducing, you can either have a look at comments of a research note or take the latest pull and it would be available for questions as well.

**Comment by dewanhimanshu** [comment]
@ViditChitkara  , I can try this issue

**Comment by ViditChitkara** [comment]
Cool 👍

**Comment by dewanhimanshu** [comment]
@ViditChitkara  can you tell me the issue number you were talking about?

**Comment by ViditChitkara** [comment]
@dewanhimanshu I have not made an issue for this yet. Could you make a new one for this?

**Comment by jywarren** [comment]
Hi, thanks for working together on this. What's the latest status -- shall we close this in favor of another PR, or is there something we can wrap up here? Thanks, all!!!

**Comment by jywarren** [comment]
I'm going to close this one for now as it looks like we have next steps. But re-open please if I've missed something!

**Pull request closed without merging**
