### PR TITLE
These changes to be able to run on GCLOUD

### PR DESCRIPTION
**Pull request by icarito**
This were changes required to deploy on GCLOUD.

They are pointing to environment variables mostly.
Beware that the SMTP_* variables break in production, we've tried this before.
We should agree if we can try to deliver directly to Google SMTP, and possibly build the array procedurally (the issue is that empty string changes the actionmailer default and causes issues with current setup).

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks good - do you think we should do this in stages, coordinated so we're watching this in production? Or are you OK merging this and monitoring the deployment asynchronously? Thank you, Sebastian!!!

**Comment by icarito** [comment]
> This looks good - do you think we should do this in stages, coordinated so we're watching this in production? Or are you OK merging this and monitoring the deployment asynchronously? Thank you, Sebastian!!!

I expect the SMTP variables will cause some trouble if deployed like this.
The default values of SMTP_USER, SMTP_PASS, SMTP_AUTH, and SMTP_STLS break current configuration.

We have two options:
 - figure out correct values of the above for current configuration (plain local MTA)
 - point directly to deliver mail thru google (which our MTA ultimately does too)

The tradeoff is our [`/smtp_test`](https://github.com/publiclab/plots2/blob/main/app/controllers/admin_controller.rb#L377) monitoring route, which we'll loose as it's currently implemented because it doesn't support TLS/SSL.

**Comment by jywarren** [comment]
Would you like me to try to refactor the smtp route for SSL? Is that at the Rails application level?

**Comment by icarito** [comment]
Hi Jeff,
I think what needs to be refactored is the way we build the `config.action_mailer.smtp_settings` hash.
The reason is that if we set `user_name` and `password`, `authentication` hash values to `''` the result is not the same as when we omit these hash values.
So something like pseudocode:
```
if ENV[key]:
  config.action_mailer.smtp_settings[key] = ENV[key]
```
For each instance.
About the SMTP test, I believe it is not very effective to be honest so I would just drop it. Sentry report *should* be enough.

**Review by jywarren — APPROVED** [review]

**Pull request merged**
