### PR TITLE
Fix double pagination on tags questions

### LINKED ISSUE #8674: Double pagination on tags questions
Double pagination here https://publiclab.org/questions/tag/blog, 
we should have a single pagination

Screenshot from 2020-10-24 15-32-04

### PR DESCRIPTION
**Pull request by Cadreia**
Fixes #8674 (<=== Add issue number here)

fix-double-pagination

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Cadreia** [comment]
@cesswairimu please is there any way I can narrow down on which functional tests are failing? It's been kind of challenging since the application builds locally without any errors

**Review by Tlazypanda — COMMENTED** [review]
Hey @Cadreia You can find the tests failing by checking the travis logs :sweat_smile: Click on the details link next to the travis pull request check and then navigate to functional tests For example your run is accessible here https://travis-ci.com/github/publiclab/plots2/jobs/414753485 So from this log you can see that the _should_have_a_active_asked_and_an_inactive_answered_tab_for_question_ and _wildcard_tag_should_have_a_active_asked_and_an_inactive_answered_tab_for_question_ tests are failing

**Comment by Cadreia** [comment]
Thank you @Tlazypanda. I'll get back to you if I face any further difficulties

**Comment by cesswairimu** [comment]
Did you manage to see the errors? here is an image
Screenshot from 2020-10-30 18-12-38

**Comment by jywarren** [comment]
Oh no! It looks like this and https://github.com/publiclab/plots2/pull/8479#discussion_r518235633 are both setting out to fix the same issue. @tyler-wel @Cadreia would you be able to work together to resolve this, or perhaps as @Cadreia has more recently been working on it, @Cadreia would like to take this one on? 

I'm sorry we didn't notice the overlap sooner - thank you for all your work, both of you!

**Comment by tyler-wel** [comment]
> Oh no! It looks like this and [#8479 (comment)](https://github.com/publiclab/plots2/pull/8479#discussion_r518235633) are both setting out to fix the same issue. @tyler-wel @Cadreia would you be able to work together to resolve this, or perhaps as @Cadreia has more recently been working on it, @Cadreia would like to take this one on?
> 
> I'm sorry we didn't notice the overlap sooner - thank you for all your work, both of you!

I'm fine with Cadreia taking oevr!

**Comment by jywarren** [comment]
OK, thank you and I appreciate your understanding ❤️ 

@Cadreia just notifying you too!

**Comment by Cadreia** [comment]
Okay, I'll try completing this as soon as possible.

**Comment by Cadreia** [comment]
Hi, @jywarren. I succeeded in getting the tests to pass for this. Can you please review it?

**Comment by cesswairimu** [comment]
@Cadreia I am getting 502 on gitpod..not sure why...do you minding adding a screenshot for this? 
thanks for working on this :tada:

**Comment by Cadreia** [comment]
Hi, @cesswairimu. I just opened this on gitpod, and I didn't come across a 502 error.
I added a screenshot in the PR description. Or would you prefer I include a gif instead?

**Comment by cesswairimu** [comment]
Hi @Cadreia , the screenshot is fine. Its late over here, I will take a look  tomorrow. Thanks

**Comment by jywarren** [comment]
This looks perfect, thank you!!!!

**Pull request merged**
