### PR TITLE
Update revisions.html.erb to update translation helpers

### PR DESCRIPTION
**Pull request by stefanosu**
Fixes https://github.com/publiclab/plots2/issues/6740
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [✔️ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [✔️ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✔️ ] screenshots/GIFs are attached 📎 in case of UI updation
* [✔️ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, goodness... @stefanosu you've opened something like 50 pull requests!

wow a lot of hard work
uh, i'm sorry @stefanosu we aren't able to respond to PRs that quickly

we appreciate your help
but your PRs don't reference the issue they are intended to fix, so we can't trace if they successfully complete the correct issue

I think they are related to @nstjean's translation helper changes -- maybe @stefanosu went down the whole list?

What shall we do? I want to be sure these changes don't overwrite another contributor's work
if someone else has claimed the FTO

@stefanosu would you be willing to close all your PRs and consider submitting them as one PR?

**Comment by jywarren** [comment]
Hi, after some discussion we'd like to ask you to focus on just one instance of this -- and can you link back to the issue it came from? @nstjean maybe you can help with the link. Let's get this PR ready to merge and we can close the others, as we are hoping to use them to help welcome in other contributors. I hope you understand, and know that we appreciate your contribution! Thank you!

**Comment by nstjean** [comment]
Here is the link!: https://github.com/publiclab/plots2/issues/6579

**Comment by stefanosu** [comment]
Hi @jywarren sorry for this mishap on that I thought I was referencing the issue correctly on each individual pr. Yea I did go down the whole list sorry for that. Yes, I could be able to do that. Sure of course no problem I understand.

**Comment by stefanosu** [comment]
> Looks good..@stefanosu could you please add a screenshot? Thanks

thanks, I'll add the screenshot but I'm having trouble running the server. I'm getting this error: 
```
`connect': Access denied for user 'stefanosugbit'@'localhost' (using password: NO) (Mysql2::Error::ConnectionError)
```

**Comment by nstjean** [comment]
@stefanosu Can you please post your problem in this thread about installing plots2? https://github.com/publiclab/plots2/issues/3840 It looks like it's not connecting to the mysql database on startup.

**Comment by cesswairimu** [comment]
Hey @stefanosu, You can try using sqlite3 for development if mysql is giving you a headache. 

You can replace your `config.database.yml` with
```
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3
```
Then run `rake db:setup`

**Comment by stefanosu** [comment]
> Hey @stefanosu, You can try using sqlite3 for development if mysql is giving you a headache.
> 
> You can replace your `config.database.yml` with
> 
> ```
> development:
>   adapter: sqlite3
>   database: development.sqlite
> 
> production:
>   adapter: sqlite3
>   database: production.sqlite
> 
> test:
>   adapter: sqlite3
>   database: test.sqlite
> ```
> 
> Then run `rake db:setup`

 @cesswairimu  Thanks that worked got the server up and running!

**Comment by cesswairimu** [comment]
awesome :+1:

**Comment by jywarren** [comment]
This looks super and I'm merging it now! Great work!

**Pull request merged**
