### PR TITLE
Update TESTING.md

### PR DESCRIPTION
**Pull request by ardyboy1**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
@LostLaser has also taken this issue and sent a PR. You should have asked in the issue first and then should have sent this PR.

**Comment by Souravirus** [comment]
Hi @jywarren, it would be great if you can merge this one. One less issue would be closed. Thank you!!

**Comment by jywarren** [comment]
Oops, looks like it has a conflict now... Someone else also committed to that file. Can one of you go through and resolve the conflicts? Thank you!

**Comment by Souravirus** [comment]
Hmm I got it someone has removed the Solr tests part. So, just remove the  Solr tests part and change the jasmine tests to teaspoon mocha.

**Comment by Souravirus** [comment]
You haven't updated anything @ardyboy1. Are you into it?

**Pull request closed without merging**
