### PR TITLE
Update README.md Fixes #1121

### LINKED ISSUE #1121: Add gitter chat button in Readme
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
Now that publiclab has its gitter channel at https://gitter.im/publiclab/publiclab we would love to have a gitter chat button in readme.

## Solution

Add this line to add the gitter chat button in readme
```
[![Join the chat at https://gitter.im/publiclab/publiclab](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/publiclab/publiclab)
```

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [x] set up a repository locally following the README instructions, and make sure that all tests pass
- [x] try to fix the issue following the steps above, but even before you're done, you can:
- [x] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [x] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

### PR DESCRIPTION
**Pull request by adarsh-ideal**
Added publiclab gitter channel in README.md

### CODE REVIEW

**Comment by ananyo2012** [comment]
@adarsh-ideal Thanks for your contribution! @jywarren This can be merged.

**Comment by ananyo2012** [comment]
Try making a new branch whenever you work on a feature or fix. You can create a new branch using `git branch branchname` and then checkout using `git checkout branchname`. Consider reading https://publiclab.org/wiki/contributing-to-public-lab-software#A+sample+git+workflow. It has a good guide on how to work while working on a new issue. This will really help you in future.

**Comment by ananyo2012** [comment]
Also write good commit messages for your work. Mention the issue no like `Fixes #1121` Here #1121 is the issue no. Use the imperative mood in commit messages. Here is a guide on writing good commit messages http://chris.beams.io/posts/git-commit/. Also a cool thing about mentioning the issue in the commit message or Pull request title auto closes the issue when merged!

**Comment by jywarren** [comment]
Thanks to @ananyo2012 for the excellent advice -- Ananyo, you're really doing a great job these past few days in GCI!

And thanks to @adarsh-ideal for your contribution -- merging now, and you can check out this guide to get your master branch back in sync:

https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

🎉 🎈

**Comment by jywarren** [comment]
screenshot 2016-12-18 at 11 32 42 am

Looks great!

**Comment by ananyo2012** [comment]
Thanks @jywarren Its my pleasure!

**Comment by adarsh-ideal** [comment]
@jywarren @ananyo2012 Thanks, Next time I'll keep it that way you described me.

**Pull request merged**
