### PR TITLE
Added whenever gem for easily writing and deploying cron jobs

### PR DESCRIPTION
**Pull request by namangupta01**
Added whenever gem for easily writing and deploying cron jobs
Sub-project part of Periodic Email Digests in #2104 
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Awesome! @icarito ?

**Comment by icarito** [comment]
Hi!
Great to see this moving forward! I guess we need to include cron daemon in the production container.
The issue with that is that cron will live in the same container and thus when we redeploy the cron jobs will be lost. In addition to adding `crond` to Dockerfile I think we'll need to figure out when to run the `whenever --update-crontab` command.

**Comment by icarito** [comment]
I've added the cron daemon to our Docker definition - so the gem should work - but we still need to figure out when to run `whenever --update-crontab`.

**Comment by namangupta01** [comment]
We can run the command whenever we redeploy or push to main branch on
server.
Can't we?

**Comment by icarito** [comment]
Yes! Thanks for clarifying when it needs to run.

**Comment by jywarren** [comment]
Should we test this by pushing it to `unstable` first? I mean, if it's not going to break anything, we can just merge it. But that's always an option. @namangupta01 what is the first time we'd actually see this thing start to run and how would we know? Can we, for example, have it do a cron job that puts a timestamp into a text file in a public folder like `/public/time.txt` so we can sort of confirm it's working in the staging server? (as a follow-up issue to this)?

**Comment by namangupta01** [comment]
yes we can have a cron job that put timestamp in the text file.

**Comment by namangupta01** [comment]
Should i add that example in this pr?

**Comment by jywarren** [comment]
it's as you like; we could do a follow-up PR if you want to keep things
simple. Would you add it in the code or in the description on GitHub?

**Comment by namangupta01** [comment]
After this we could also do testing for whenever using this gem https://github.com/rafaelsales/whenever-test

**Comment by jywarren** [comment]
Oh cool! Well, tell me if you want me to merge this or hold off a bit,
thank you!!!

**Comment by namangupta01** [comment]
I think we should merge this.. so that i can make a follow up pr for cron job discussed above based on this pr. Merging this pr won't affect anything as of now because there is currently no job. :)

**Comment by jywarren** [comment]
perfect!

**Pull request merged**
