### PR TITLE
[WIP] Fix Authlogic deprecation for email validation (#5125)

### LINKED ISSUE #5125: Remove Authlogic deprecation warning for email validation
Main issue #4624 
created specifically for @CubikMan47
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Problem**: 
There is this Authlogic deprecation warning currently
```
DEPRECATION WARNING: This Authlogic configuration option (validates_format_of_email_field_options) is deprecated. Use normal
ActiveRecord validation instead. 
```

 📝 **Update**: 
* Remove line https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L33
* Add this  line  `validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }` after https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L35 

After changing run the tests and make sure the deprecation warning is gone.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by CubikMan47**
Fixes #5125

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by CubikMan47** [comment]
Could you please review this? @publiclab/reviewers

**Comment by gauravano** [comment]
You need to change the error count at https://github.com/publiclab/plots2/blob/master/test/unit/user_test.rb#L172. Do this after identifying that both errors we are getting after making the change in user.rb are valid.

You can ask me or @cesswairimu for help

 Thanks!

**Comment by cesswairimu** [comment]
Hi @CubikMan47 I just debugged this locally somehow we are getting two email error messages on this test ` @messages={:email=>["should look like an email address.", "is invalid"]}>`

We can fix this by checking for email errors instead of asserting the specific count. You could change this line https://github.com/publiclab/plots2/blob/master/test/unit/user_test.rb#L172 to ` assert_not_nil user.errors[:email]` 
Thanks

**Comment by CubikMan47** [comment]
@cesswairimu Yeah, that's probably a good choice.

**Comment by CubikMan47** [comment]
I think I messed up something... I can't push commits to this PR anymore, don't know why, so I'm opening a new one at #5155

**Pull request closed without merging**
