### PR TITLE
Add follow button tags search dropdown 

### LINKED ISSUE #6337: "Follow" buttons in tags search dropdown
Building on #6026

image

Let's implement this! I believe it's generated here: 
https://github.com/publiclab/plots2/blob/158594acacb46a5416c72215716abd6c1b60f52d/app/assets/javascripts/async_tag_subscriptions.js#L3-L17

However, when the item is selected, the updater is run, so we'd need to distinguish between clicks on the item vs. clicks on the `Follow` button. This may take some testing out.

### PR DESCRIPTION
**Pull request by sharmamansi**
Fixes #6337

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sharmamansi** [comment]
hey @jywarren please review this i just interchanged contents of anchor and span tag as that was not working( even the follow button was not appearing that time).Also I'm new to developing so I don't have much idea about how things need to be done.Please guide me how to proceed further.
Screenshot from 2019-10-06 20-52-31

**Comment by jywarren** [comment]
Oh this looks wonderful! You've done a great job. 

Two thoughts- 

1. Does clicking on the menu item vs the button do two separate things?
2. Can you make the button class "btn-sm" as well to see if we can get it to fit more nicely in the menu item! 

Confirming both of these, we should be good here!

**Comment by sharmamansi** [comment]
@jywarren thanks.
 And the class btn-sm is already there and no clicking on the menu item vs the button redirect to same page only.

**Comment by jywarren** [comment]
Maybe `btn-xs` would make it even smaller, so it'd fit better?

**Comment by jywarren** [comment]
Thank you for your help!

**Comment by cesswairimu** [comment]
Hi @sharmamansi, whats the progress on this? stuck? let me know how we can help. Thanks

**Comment by jywarren** [comment]
I tried this out, let's see how it does!

**Comment by jywarren** [comment]
Hi, I've been working on this a good bit, and I'm sorry to say I think it may be almost impossible! I'm going to close this but I really appreciate your help on it. 🎉

**Pull request closed without merging**
