### PR TITLE
Replace http links with https in test file

### LINKED ISSUE #9245: http to https on note_controller test
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [test/functional/notes_controller_test.rb](https://github.com/publiclab/plots2/blob/main/test/functional/notes_controller_test.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -70,13 +70,13 @@ def teardown
     node = Node.where(type: 'note', status: 1).first
     assert node.comments.length > 0
     comment = node.comments.last(2).first
-    comment.comment = 'Test **markdown** and http://links.com'
+    comment.comment = 'Test **markdown** and https://links.com'
     comment.save!
 
     get :show, params: { id: node.id }
 
     assert_select 'strong', 'markdown'
-    assert_select 'a', 'http://links.com'
+    assert_select 'a', 'https://links.com'
 
     assert_response :success
   end
@@ -483,13 +483,13 @@ def teardown
     comment = Comment.new(nid: nodes(:one).nid,
                           uid: users(:bob).id,
                           thread: '01/')
-    comment.comment = '<iframe src="http://mapknitter.org/embed/sattelite-imagery" style="border:0;"></iframe>'
+    comment.comment = '<iframe src="https://mapknitter.org/embed/sattelite-imagery" style="border:0;"></iframe>'
     comment.save
     node = nodes(:one).path.split('/')
 
     get :show, params: { id: node[4], author: node[2], date: node[3] }
 
-    assert_select 'iframe[src=?]', 'http://mapknitter.org/embed/sattelite-imagery'
+    assert_select 'iframe[src=?]', 'https://mapknitter.org/embed/sattelite-imagery'
   end
 
   # test "should mark admins and moderators with a special icon" do
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by lagunasmel**
Fixes #9245
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updation
* [X] ask `@publiclab/reviewers` for help, in a comment below

@publiclab hi, can I get some help with this test result? I'm unsure if these are the expected results of `rake test`:

Results of `rake test` [here](https://imgur.com/a/zwQafek).

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @lagunasmel, looks like your PR is picking up commits from other contributors...rebasing should solve this...are you familiar with git rebasing?  here are some steps to follow if not 

#### Steps to Rebase
assuming you have named the publiclab remote "upstream"
and your fork "origin"
```
$ git checkout main
$ git pull upstream main
$ git checkout replace-http-links
$ git rebase -i main 
```
The last command opens a editor with your commits, save and exit
Then push your branch back up. You might need to force push `$ git push -f origin replace-http-links`
Ping me if you get any prob

**Comment by lagunasmel** [comment]
Hi @cesswairimu, thanks for your help. I think this may have happened because I was using the name `master` instead of `main` when I ran the rebasing commands. I have now run the commands you suggested, but I'm unsure of how to proceed, because I get the "Everything up to date" message after pushing my branch.

**Comment by cesswairimu** [comment]
Oh I see...maybe try creating a new branch off of the main branch, make the changes from there and make a new pull request?

**Comment by lagunasmel** [comment]
@cesswairimu sounds good, I'll try that instead.

**Pull request closed without merging**
