### PR TITLE
Header line removed and Menu icon made more visible for mobile view

### LINKED ISSUE #7312: Line on header at width 768px
### Please describe the problem (or idea)
1. A line is showing on the header of grey colour which is not looking good in terms of UI and need to be fixed.
2. The menu icon is difficult to see so the border width should be more.
> What did you expect to see that you didn't?
The line should not be there.
Icon menu should be clearly seen.
### Please show us where to look

https://publiclab.org/
On the header at width of the device = 768px.

### What's your PublicLab.org username?
nitin_tech
> This can help us diagnose the issue: 
Need to check the UI at width equals to 768 px and need to fix
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders
Screenshot from 2020-01-20 20-57-19

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes #7312 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Screenshot from 2020-01-21 17-30-24
Screenshot from 2020-01-21 17-30-22
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@jywarren @SidharthBansal can you please review this.

**Comment by SidharthBansal** [comment]
Can you please fix the travis? It is failing

**Comment by Uzay-G** [comment]
The travis is not @NitinBhasneria's fault. I have noticed that sometimes the system tests we have added are failing. Do you have any idea why @VladimirMikulic?

**Comment by VladimirMikulic** [comment]
We have 'wiki revisions' test failing. Logs are showing that "Are you sure" modal didn't show up.
An empty space before text "Revert"(like this " Revert") could have caused this.

I'll fix it again, in the meantime @NitinBhasneria you can force re-push to restart Travis.
@Uzay-G thanks for reporting this.

**Comment by NitinBhasneria** [comment]
Thanks, @VladimirMikulic  so should I close this pr and open another one

**Comment by VladimirMikulic** [comment]
@NitinBhasneria you don't have to close this PR, I've fixed the issue. Just rebase the branch and push again. `git rebase master; git push`

**Comment by NitinBhasneria** [comment]
@VladimirMikulic now also it is showing the error can you please review....

**Pull request closed without merging**
