### PR TITLE
Empty Search Validation ( Fixes #2181 )

### LINKED ISSUE #2181: Add search validation
### Please describe the problem (or idea)
Currently we can perform submission of search form even when input field is empty which leads to opening of another page which have no content since our input was empty.
So what we can do is that we can add validation that input mush not be blank or empty.

### PR DESCRIPTION
**Pull request by Ankit-Singla**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Ankit-Singla** [comment]
@namangupta01 Please review this pull request.

**Comment by namangupta01** [comment]
@Ankit-Singla Please don't open pr for the issue which already has a pr. There is no good in doing same thing multiple time. Instead of that you can focus on issue which doesn't have pr. :)

**Comment by namangupta01** [comment]
Closing since issue already have a pr #2182

**Comment by Ankit-Singla** [comment]
@namangupta01 Sorry, I thought no one was working on it since no one claimed the issue, and because checks failed in your PR #2182 .

**Comment by namangupta01** [comment]
@Ankit-Singla No issues! There are plenty of [fto-candidate](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Afto-candidate) issue if you want you can work on them since i think you are new to the codebase. Just comment there to claim the issue and to check if somebody is working on that or not.

**Pull request closed without merging**
