### PR TITLE
Fix rubocop offenses in app/helpers

### LINKED ISSUE #6436: Resolve rubocop lint offenses inside /app/helpers
Referenced from #6340

To do:

Use rubocop to resolve the linting errors from the ruby files inside the /app/helpers directory
Check #6340 for more information

### PR DESCRIPTION
**Pull request by JadeDickinson**
Fixes #6436

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by JadeDickinson** [comment]
There were a few Metrics/ offenses I left outstanding, as these seemed impossible to address without significantly changing the code:
Metrics/AbcSize
Metrics/MethodLength
Metrics/ModuleLength

**Comment by pydevsg** [comment]
@moki298 do give a review, though a few cases aren't running. Good work @JadeDickinson

**Comment by SidharthBansal** [comment]
There are some conflicts. Kindly fix them

**Comment by SidharthBansal** [comment]
Can you please make different prs instead of one pr?
That will be easy to review and merge
Thanks

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
