### PR TITLE
Add CSV drag and drop graph (#3979)

### LINKED ISSUE #3979: Get CSV drag and drop to insert a graph tag
After resolving https://github.com/publiclab/plots2/issues/3978, we can look at how you should be able to drag a CSV into a comment and have it display in the following format:

```
[graph:/i/27694.csv]
```

This (after #3978) will actually display it in a graph! See this working in wiki body text here: https://publiclab.org/wiki/sandbox-2

image

Sample CSV: https://publiclab.org/i/27694.csv

To make this work, we have to be able to detect the `.csv` ending, and render a different display on these lines:

https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/assets/javascripts/dragdrop.js#L64-L71

We'd love help with this!

### PR DESCRIPTION
**Pull request by DanielKim1**
Fixes #3979

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by DanielKim1** [comment]
Thanks! I haven't been able to get the graphs to work on comments, but they seem to be working for posts:
screen shot 2018-11-22 at 2 51 06 pm
screen shot 2018-11-22 at 2 50 53 pm

**Comment by DanielKim1** [comment]
@publiclab/reviewers Should I look into why the graphs aren't rendering in comments, or is that expected behavior? Currently, CSV files inflate into hyperlinks in comments, and if that's expected, I think this PR is good to go

**Comment by jywarren** [comment]
Ah, yes they should be inflating into graphs in comments as well, and actually as of recently merged code, i think that may be working now... can you try again based on the latest master branch? 

Your code to get it working in the dragdrop.js code also looks great. Note that dragdrop.js is for comments, not for the /post rich editor. But looks like your code will solve this -- just needs to be tried out. Thank you!!

**Comment by DanielKim1** [comment]
Thanks!

**Pull request merged**
