### PR TITLE
remove useless code in methods.html.erb

### LINKED ISSUE #3481: Remove  useless code
### Please describe the problem (or idea)
In this file, there is a useless code "Related topics " which is not showing this page  https://publiclab.org/methods this is good for First-time-only

https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/wiki/methods.html.erb

remove1

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/methods

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome ubuntu16
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by vikul1234**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

fixed #3481

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #3481-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by vikul1234** [comment]
@publiclab/reviewers please review

**Comment by avsingh999** [comment]
@vikul1234  great work ready to merge

**Comment by gauravano** [comment]
Closing this PR.

**Comment by gauravano** [comment]
Sorry for inconvenience @vikul1234. The issue was mistakenly created. But, we would love to have your help, please check more issues at https://code.publiclab.org/ . Thanks!

**Pull request closed without merging**
