### PR TITLE
Allow Login from username and Email

### PR DESCRIPTION
**Pull request by vaibhavgeek**
Hello, This is my first pull request on the public lab repository. I apologize in advance for any mistakes caused by me. I created an issue #1347 

Before the person could login from username only. Now the user can login from Username or Email.

### CODE REVIEW

**Comment by vaibhavgeek** [comment]
Following changes are made in views. 
Before: 
screenshot from 2017-03-19 16-06-12

Now: 
screenshot from 2017-03-19 16-06-43

**Comment by jywarren** [comment]
Hi, thank you very much for this PR! I think it's great.

I am interested in whether we could test it in our functional or
integration tests. This is a very fundamental function of the site and I'd
like to have very tight test coverage. Would you be willing to write a
functional or integration test for this?

Thank you!

**Comment by vaibhavgeek** [comment]
Hi @jywarren,
Thanks for going through the pull request. 

I will write a integration test to make sure this works out in all case scenarios. 

Regards, 
Vaibhav

**Comment by vaibhavgeek** [comment]
@jywarren I have created a unit test for the login with email as well as username. I also suggest having email indexed in the database schema.

**Comment by jywarren** [comment]
Hi, your functional test looks great, thank you. But I think you've checked in some of your database files; can you look and remove any that don't belong? Thank you!

**Comment by vaibhavgeek** [comment]
I have made the change (Sorry about the unnecessary file and the inconvenience).

**Comment by jywarren** [comment]
No problem! I do see a couple more binary files in the root directory, do you know what they are? Mind removing them too? Thank you!

**Comment by vaibhavgeek** [comment]
They came in because of my wrong experiments on git. They were not contributing to the code anyhow. After this Pull Requests gets merged. I would fork and clone the repo again. 

Thanks,

**Comment by jywarren** [comment]
Ok, thanks and great work here! Merging now and we'd love to have more contributions from you if you're interested.

**Pull request merged**
