### PR TITLE
Fixing 'Help wanted' link in 'first time only' issue template

### LINKED ISSUE #10112: 'Help wanted' link in 'first time only' issue template.
**The Issue**

**The link 'help wanted' in the 'first-timers only issue template isn't linked correctly.**

The link is over here:

image

**How is it functioning:**

It takes the user over here 

image

**How it should function:**

It should ideally be taking a user over here - 

image

**Proposed solution:**

Modify line 17 [over here.](https://github.com/publiclab/plots2/blob/main/.github/ISSUE_TEMPLATE/--first-timers-only.md)

Modify line 17:

`If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!`

To:

`If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!`

### PR DESCRIPTION
**Pull request by chicken-biryani**
The link 'help wanted' in the 'first-timers only issue template isn't linked correctly.

Fixes #10112 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by chicken-biryani** [comment]
Hey, @daemon1024 / @noi5e
Could you please review this?

[Ps: The previous commits hung around in my forked repo. Need to learn how to get rid of that :') But the files changed is 1.]

**Review by RuthNjeri — APPROVED** [review]
This looks good to me @chicken-biryani! Thank you!

**Review by Tlazypanda — APPROVED** [review]
LGTM @chicken-biryani :tada:

**Review by noi5e — APPROVED** [review]
@chicken-biryani Nice! This looks great! We should be merging this in the next couple of days.

> [Ps: The previous commits hung around in my forked repo. Need to learn how to get rid of that :') But the files changed is 1.]

I notice that you're working off the main branch on your local repo. Each time you make a new pull request, start a new branch.

So for example, you would have made a new branch `chicken-biryani:fix-help-wanted-fto` and push commits from that branch, instead of `chicken-biryani:main`. Each time you make a new branch, it should be on the most up-to-date version of `main`.

On this PR, you can still `git squash` all the commits, and collapse everything into one commit. How I like to do this is `git rebase -i` and `drop` all the commits I don't want. Definitely read up on it, it's super useful, and you'll probably use it a lot the more you program!

**Comment by chicken-biryani** [comment]
> @chicken-biryani Nice! This looks great! We should be merging this in the next couple of days.
> 
> > [Ps: The previous commits hung around in my forked repo. Need to learn how to get rid of that :') But the files changed is 1.]
> 
> I notice that you're working off the main branch on your local repo. Each time you make a new pull request, start a new branch.
> 
> So for example, you would have made a new branch `chicken-biryani:fix-help-wanted-fto` and push commits from that branch, instead of `chicken-biryani:main`. Each time you make a new branch, it should be on the most up-to-date version of `main`.
> 
> On this PR, you can still `git squash` all the commits, and collapse everything into one commit. How I like to do this is `git rebase -i` and `drop` all the commits I don't want. Definitely read up on it, it's super useful, and you'll probably use it a lot the more you program!

Hey @noi5e can I try it out over here itself? I'll learn. If it doesn't work out I'll close this PR and create a new one. Is that okay?

**Comment by noi5e** [comment]
> Hey @noi5e can I try it out over here itself? I'll learn. If it doesn't work out I'll close this PR and create a new one. Is that okay?

@chicken-biryani Not only is that okay, but I encourage it! That's great that you want to learn. (I just learned how to do this in the past year)

Here's a place to start reading:
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

If it doesn't work, no need to make a PR, just leave this one open! This PR can be merged just fine, but being able to edit your commit history is a really good programming skill for anyone to learn.

**Comment by chicken-biryani** [comment]
Hey, @noi5e

Thank you for your help.

I did figure it out after reading a little...
Just a little scared to try it out! 😅

But I'll face my tini-mini fear and try this out asap.

**Comment by noi5e** [comment]
@chicken-biryani You can do it!

**Comment by chicken-biryani** [comment]
@noi5e uh-oh I think I messed up. *nervous laughter* I think I didn't create a branch. Let me give it another shot.

**Comment by chicken-biryani** [comment]
Okay so, @noi5e (Sorry to bother you again)

I realized my mistake, I did not branch it, so all the changes came together. Now to fix it I re-dropped all the unwanted commits. How do I know if it worked or not?

**Comment by noi5e** [comment]
@chicken-biryani Great job, you did it!

Basically you can tell it worked if you look at the PR, and the list of commits is down to one. That seems to be the case here:

Screen Shot 2021-09-17 at 6 13 12 PM

Screen Shot 2021-09-17 at 6 13 25 PM

After the tests run, this will be ready to merge.

**Comment by chicken-biryani** [comment]
Ohhh!!! Thank you so much, @noi5e! I have wanted to learn this for such a long time. Next PR I am learning how to squash!

**Comment by noi5e** [comment]
Awesome! Tests passing! Congrats @chicken-biryani, you get a gold medal for learning something new 🥇

**Pull request merged**
