### PR TITLE
Removed Cloud9 scripts

### LINKED ISSUE #8516: Remove Cloud9 Scripts
I have noticed that there are other references to Cloud9 in:
[Rake Tasks](https://github.com/publiclab/plots2/blob/main/lib/tasks/cloud9.rake)
and 
[Bash Script](https://github.com/publiclab/plots2/blob/main/install_cloudnine.sh)

## Todo
Lets remove these two files https://github.com/publiclab/plots2/blob/main/lib/tasks/cloud9.rake and https://github.com/publiclab/plots2/blob/main/install_cloudnine.sh

_Originally posted by @RuthNjeri in https://github.com/publiclab/plots2/pull/8515#issuecomment-706319651_

### PR DESCRIPTION
**Pull request by adi-mohan**
Fixes #8516  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by adi-mohan** [comment]
@publiclab/reviewers are there any issues in codecov? Because I have just deleted two files which was not used anywhere as mentioned in #8516 and diff is showing about 54% .

**Comment by adi-mohan** [comment]
Hi @publiclab/reviewers ! Travis CI, Codecov and Gitpod has passed. Only codeclimate didn't pass as it was unable to fetch. Maybe some issues in SSH key config of the repo. I think the PR is now eligible for review and merge. Thanks!

**Comment by cesswairimu** [comment]
Hey @adi-mohan, could you please make a branch off your main and create a PR from that branch. Could be why codeclimate is not running correctly. Thanks

**Comment by adi-mohan** [comment]
> Hey @adi-mohan, could you please make a branch off your main and create a PR from that branch. Thanks

Sure. Just done that. I am curious about why is it needed this way. I am new to opensource collabs. #8663

**Comment by cesswairimu** [comment]
@adi-mohan its more of a good practice rather than a necessity but most open source projects do this. Ideally you would want to keep your main branch in sync with the upstream/main and create descriptive branches for the issue you are working on. e.g for this you could a branch named `remove-c9-scripts` .  Not sure if this really answers your question, but that's 2 cents :smile: 
And btw welcome to Open source :balloon:

**Pull request closed without merging**
