### PR TITLE
fixed search for comments

### PR DESCRIPTION
**Pull request by ViditChitkara**
updates #1977

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
@jywarren The problem was actually not due to comments but the notes method!! The problem regarding user search also seems to be fixed in this patch. Actually the default status for a user is '0' but we are searching for users with status 1. We may want to use DrupalUser instead of User!!
Please correct me if I am wrong! Do you think we could try this in production??

**Comment by seafr** [comment]
The if block (line 16) seems to evaluate to the same thing whether the condition is true or false.

**Comment by ViditChitkara** [comment]
Yes, I was actually trying to remove the failing tests that existed in the previous commit!! Will do the changes asap!! Thanks for the feedback.😊😊

**Comment by ViditChitkara** [comment]
Also I am not really sure if this would work properly in staging. So waiting for Jeff's input on this. Let's see if it works!! Fingers' crossed!!

**Comment by seafr** [comment]
You're welcome. I thought perhaps you have not noticed, but it seems that you have a reason for this. :+1:

**Comment by jywarren** [comment]
Oh, this looks really great, and super teamwork. We are trying to deprecate `DrupalUsers` in favor of `User` however, but we can use `user.username` instead of `drupal_user.name` -- in the `where()` filters. Both should have "status" the same, and i think a swap should work here! Timestamp field is also named differently

Thanks a lot!!

**Comment by ViditChitkara** [comment]
Oh alright, I'll do that!! I have another thing in mind, let's not filter the query using status: 1 (for the time being) since the default status of user is 0 and its not changed (however, status of drupal_user is used to determine a banned user). Let it be:-
`
 User.search(input).limit(limit).order('uid DESC')
`
What do you say?

**Comment by ViditChitkara** [comment]
Or currently just keep the changes to notes and leave user method as it was?

**Comment by ViditChitkara** [comment]
I just realised, the migration thing could also be applied to update the User status (which is 0 by default) in the searches perhaps would solve the problem related to username search! What do you think?

**Comment by jywarren** [comment]
Oh, ack... that's bad -- you're right, on this line, we're still only updating `drupal_user`: https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb#L108

we need to fix that actually. Can we think about how to address this in this or a separate PR?

**Comment by jywarren** [comment]
Yes, so we could do the migration for user status too, and then try to fix the code that should be using User instead of DrupalUser

**Comment by jywarren** [comment]
:-/ I think there's an advantage to doing only a single migration with both changes in it, since it simplifies deployment. But we'd have to rewire the `ban` method at the same time as we do the migration, otherwise it may go out of sync, right? 

Thanks for thinking through this!!!!

**Comment by ViditChitkara** [comment]
By both changes do you mean migrations related to answer_tag (pr #2045) too? So let's just tackle changes related to notes here and stash user related changes!! I'll open a separate pr for the user_related searches!! or should we do it here only?

**Comment by jywarren** [comment]
> let's just tackle changes related to notes here and stash user related changes!! I'll open a separate pr for the user_related searches!! 

this sounds perfect, thank you!

So then just tell me when this one is ready! :-)

**Comment by ViditChitkara** [comment]
I have removed the changes related to user, please have a look!! It's ready according to me!!

**Comment by ViditChitkara** [comment]
@jywarren made changes regarding user_status, please see!!

**Comment by jywarren** [comment]
Hi! I see there are still a few changes to user status in the PR -- I'm just not sure about it so perhaps we can remove those too and stash them for a later PR -- I did gather up some links related to that topic though:

https://github.com/publiclab/plots2/blob/master/db/schema.rb.example#L344

https://github.com/publiclab/plots2/blob/ed1ef3b72c8a45bfd1d7b842d1d747db391b2a7f/app/models/drupal_user.rb#L4-L7

I think we need to restructure that system completely around User and not DrupalUser, including:

1. [ ] a migration to copy all `DrupalUser` status records to `User` status records
2. [ ] ensure (as you do in the extra code in this PR) that banning/unbanning affects the `User` records
3. [ ] ensure (as you do in the extra code in this PR) `User` status is properly set on creation
4. [ ] ensure all references to `status` are to the newer `user.status`
5. [ ] leave some decent documentation on what the status codes are and how they work
6. [ ] in yet another follow-up PR, stop using the `DrupalUser` status column and remove it

We can copy this checklist into a new issue!

Thanks for your work on this - the status system needs some care and I appreciate your attention to it!

**Comment by ViditChitkara** [comment]
All right. let's do that in a new issue!!
So in this pr we remove all changes related to user and let's just keep the changes related to node search. Also let's keep the migrations in #2045 confined to add 'answered' tag only and remove user related changes. @jywarren please correct me if I am wrong!!

**Comment by ViditChitkara** [comment]
made the changes, let's see if it works or not!

**Comment by jywarren** [comment]
Great, i'll try to publish these changes later today. Thanks!

**Comment by jywarren** [comment]
Actually i'm pushing them to staging.publiclab.org now -- you'll be able to see them in that preview mode shortly.

**Comment by ViditChitkara** [comment]
Cool!!

**Pull request merged**
