### PR TITLE
Fixes #8175 - Update _editor.html.erb

### LINKED ISSUE #8175: Add an underline to the "choose one" link in wiki page image upload form
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/editor/_editor.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/editor/_editor.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -20,7 +20,7 @@
         <!-- http://stackoverflow.com/questions/11235206/twitter-bootstrap-form-file-element-upload-button -->
         <label class="" for="fileinput">
           <input id="fileinput" type="file" name="image[photo]" style="display:none;" />
-          <a class="d-none d-md-inline">choose one</a>
+          <a class="d-none d-md-inline text-underline">choose one</a>
           <span class="d-md-none">
             <i class="fa fa-upload"></i>
             <a>Upload image</a>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by aakanchha01**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
@aakanchha01 kindly link the issue you are solving as @sagarpreet-chadha  mentioned above :point_up: Thanks

**Comment by cesswairimu** [comment]
Oh wow thanks so much @avats-dev for going a step further and even including a gif for how to add the issue number :heart: 
Maybe we could include your gif in the Contribution documentation. @sagarpreet-chadha @jywarren  what do you think?

**Comment by cesswairimu** [comment]
The travis error was an old error that I believe we resolved. Reopening this should solve it,... Reopening

**Comment by avats-dev** [comment]
Well first timers do get stuck in these problems and I thought visual representation would help :smile:

**Comment by sagarpreet-chadha** [comment]
Yes @cesswairimu great idea 🎉 
@avats-dev would you like to add this gif in the Contribution Documentation? Thanks 💯

**Comment by avats-dev** [comment]
Well yeah, I'll do it @sagarpreet-chadha . I think we should add a whole first-timers section [here](https://github.com/publiclab/plots2/blob/main/CONTRIBUTING.md), and add various screenshots,references and gifs to get them started. 
Alternatively, we can also create a First-Timer.md, and link it to the contribution docs. What do you think?

**Comment by avats-dev** [comment]
Also, maybe we should merge this, and close the issue manually.

**Comment by avats-dev** [comment]
Also @cesswairimu , maybe we should merge this and close the issue manually.

**Comment by cesswairimu** [comment]
@avats-dev do you know the issue number for this?

**Comment by avats-dev** [comment]
Hey @cesswairimu , we should close this. This was concerned with #8175 , and as @aakanchha01 never linked this PR to that issue, someone else added a PR, and that issue is closed now. :+1:

**Comment by cesswairimu** [comment]
Thanks @avats-dev , closing this. @aakanchha01 let us know if you need another fto.

Thanks everyone

**Pull request closed without merging**
