### PR TITLE
Upgrade to Ruby 2.4.4 (fixes #2824)

### LINKED ISSUE #2824: Travis test gives error sometimes which gets removed by rebuild
Travis test sometimes gives this error `** Error in /usr/local/bin/ruby': free(): invalid next size (fast): 0x00000000098d3950 ***` which gets cleared out when tests get rebuilded. 

The reported error is `There was an error with Danger bot’s Junit parsing: undefined method `value’ for nil:NilClass` in PRs.

### PR DESCRIPTION
**Pull request by icarito**
I believe this should pass all tests now. I'ts building every 15 minutes at https://jenkins.laboratoriopublico.org/job/Plots-Test/ .
When it is consistently green we'll have fixed #2824. Very close now!

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
I believe we're back to green let's monitor https://jenkins.laboratoriopublico.org/job/Plots-Test/buildTimeTrend if it sticks let's merge this!

**Comment by icarito** [comment]
This PR includes a tweak to travis config that should make it run quicker! (Remove unneeded `bundle install`).

**Comment by jywarren** [comment]
Wow, how cool. here's the saved time, i think, in the graph -- some failures after that but then it stabilized (prob due to the additional commits?)

image

Are we good to merge then?

**Comment by jywarren** [comment]
Does this also reflect an overall improvement in build time from ~20m to ~5m?

**Comment by icarito** [comment]
I worked yesterday on debugging why builds were taking longer and longer - this was kind of a stress test for our container setup. After adding `tmp/` to `.dockerignore` we saved a bunch of time moving data around needlessly into the container.

Yes let's merge this! :-)

**Comment by jywarren** [comment]
Ah but do we have to remove the regular tests in Jenkins first? Would this run a zillion (on every PR) if we merge it as it is? Or is that a setting from the Jenkins side?

**Comment by jywarren** [comment]
Just want to clarify this last thing @icarito before merging. Tremendous work!

**Comment by icarito** [comment]
Jenkins is configured at the Jenkins side, currently it builds a specific branch (jenkins_strace).
Merging this won't affect Jenkins as it's configured at the Jenkins side.

**Comment by jywarren** [comment]
Merged! Very hopeful here!

**Pull request merged**
