### PR TITLE
Fix dropdown on small screens only

### PR DESCRIPTION
**Pull request by kunlefash**
Fixed display dropdown for small screens only

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @kunlefash, can you add a link to the issue this PR is resolving?

> One thing that can help to get started is to make sure you've included a link back to the original issue you're solving, in the format `fixes #0000`

**Comment by kunlefash** [comment]
@TildaDares #10845

**Review by TildaDares — APPROVED** [review]
Thanks @kunlefash!! Great work.

**Comment by kunlefash** [comment]
Thank you very much @TildaDares . What should I do next pls?

**Comment by TildaDares** [comment]
Congratulations @kunlefash 🎉

**Comment by TildaDares** [comment]
@kunlefash We usually encourage folks to try making a first-timers-only issue for someone else! And to begin digging more into the open issues, asking for clarifications, and, in the case of Infragram, sharing mockups and design ideas for discussion.

**Pull request merged**
