### PR TITLE
Added Service worker for notification on mobile phones

### LINKED ISSUE #6020: Make Browser Notification API work on phone
We recently merged the browser notification API implementation. It is working fine on computer browser however it is not working on a mobile browser on android. I am researching over this problem to find a way for this.
cc @jywarren @gauravano

### PR DESCRIPTION
**Pull request by namangupta01**
Closes #6020

### CODE REVIEW

**Comment by namangupta01** [comment]
@jywarren I guess this would work. Unable to test on mobile because on mobile it only works with https.

**Comment by namangupta01** [comment]
But Working on desktop.

**Comment by namangupta01** [comment]
Pushed to unstable but not able to test on unstable because of error while creating a comment. So can we merge this so that I can test for mobile on stable? Working on the desktop is tested.
Thanks!

**Comment by jywarren** [comment]
Sure, but we don't have https on stable either. Is there a way to test locally on https using a passenger setting?

**Comment by namangupta01** [comment]
I guess we have

**Comment by namangupta01** [comment]
Screen Shot 2019-08-20 at 2 24 38 AM

**Comment by namangupta01** [comment]
I tried with thin using force SSL but that was causing WebSocket upgrade error.

**Comment by jywarren** [comment]
oh whoa, it must be new!?

**Comment by jywarren** [comment]
OK! I'll merge this but please be careful to file any fixes swiftly before we publish to production in the next day or two! Thanks, Naman!

**Comment by namangupta01** [comment]
Sure! 👍

**Comment by namangupta01** [comment]
Let's check on stable. Hopefully, it will work.

**Comment by namangupta01** [comment]
Yayyy! It worked! 🎉 🎉

**Comment by namangupta01** [comment]
Screen Shot 2019-08-20 at 2 49 24 AM

**Comment by namangupta01** [comment]
I got two duplicate notifications on the phone. Here I have fixed it https://github.com/publiclab/plots2/pull/6159.
Thanks!

**Comment by jywarren** [comment]
whoa, awesome!!!

**Pull request merged**
