### PR TITLE
Add code coverage

### LINKED ISSUE #1191: Add code coverage to plots2
Its time that we did some analytics on our code. Add code coverage and test coverage to plots2. Trying in two different services - [codeclimate](https://codeclimate.com) and [coveralls](http://coveralls.io/)

### PR DESCRIPTION
**Pull request by ananyo2012**
Closes #1191

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Wow, this is pretty cool, Ananyo. Will it outright reject poorly-formatted code, or will it provide helpful feedback when run (and is there any way we can ensure it will)? Thanks!

**Comment by ananyo2012** [comment]
Well if we set a benchmark to the coverage then it will fail the build if test coverage falls below that. Otherwise it helps to show useful information like test coverage and linting errors, security warnings in the coverage link. I will add the badges in readme. I am using coveralls for the test coverage and code climate for other useful information.

**Comment by jywarren** [comment]
So for now it just shows helpful notes on formatting, but we haven't yet set benchmarks? 

So, i see this:

```
Started
................................................................................
............................................................
Finished in 2.887479313 seconds.
--------------------------------------------------------------------------------
140 tests, 425 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
--------------------------------------------------------------------------------
48.49 tests/s, 147.19 assertions/s
[Coveralls] Outside the CI environment, not sending data.
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (called from <class:Image> at /app/app/models/image.rb:12)
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (called from <class:User> at /app/app/models/user.rb:21)
Loaded suite /usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/rake_test_loader
Started
................................................................................
................................................................................
................................................................................
.............................................
Finished in 27.312740108 seconds.
--------------------------------------------------------------------------------
285 tests, 706 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
--------------------------------------------------------------------------------
10.43 tests/s, 25.85 assertions/s
[Coveralls] Outside the CI environment, not sending data.
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (called from <class:Image> at /app/app/models/image.rb:12)
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (called from <class:User> at /app/app/models/user.rb:21)
Loaded suite /usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/rake_test_loader
Started
......................................................................
Finished in 34.824472288 seconds.
--------------------------------------------------------------------------------
70 tests, 204 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
--------------------------------------------------------------------------------
2.01 tests/s, 5.86 assertions/s
[Coveralls] Outside the CI environment, not sending data.
```

([here](https://travis-ci.org/publiclab/plots2/builds/193614012#L2682))

Does that mean they didn't run in Travis?

**Comment by ananyo2012** [comment]
This is not ready yet. The CI isn't sending the coverage data as you can see in the line
``
[Coveralls] Outside the CI environment, not sending data.
``
Looking for possible solutions in these links: https://github.com/lemurheavy/coveralls-public/issues/190, https://github.com/lemurheavy/coveralls-public/issues/782

**Comment by ananyo2012** [comment]
@jywarren This is good to go. You can get coverage and other issues from the badges included in readme: https://github.com/ananyo2012/plots2/tree/coverage#publiclaborg

**Comment by ananyo2012** [comment]
The issues section in codeclimate shows various linting and security issues with the code. The test coverage is shown using coveralls.  I used coveralls for test coverage since codeclimate requires admin access to get the repo_token. Coverall only requires a write access to the repo.

Sorry for too many builds occuring in the CI for the same PR as I was getting a tough time to figure out what was causing coveralls not sending reports. I finally figured this was because we were using docker for running tests which set the `CI` environment to false.

**Comment by jywarren** [comment]
Oh cool, interesting, i'll check it out now!

**Comment by jywarren** [comment]
Oh neat:

> ConsoleReporter finished
> [Coveralls] Submitting to https://coveralls.io/api/v1
> [Coveralls] Job #5.1
> [Coveralls] https://coveralls.io/jobs/22246854
> Coverage is at 85.48%.
> Coverage report sent to Coveralls.

85% is higher than i'd expected!

**Comment by jywarren** [comment]
Thanks, Ananyo, fantastic work!! 🎉

**Comment by yukiisbored** [comment]
It would be really cool if we target 100% code coverage and enforce it once we reach it ;)

**Comment by jywarren** [comment]
agreed!

**Pull request merged**
