### PR TITLE
Add greek language to gr.yml, correct the faults 

### PR DESCRIPTION
**Pull request by ioampatzidis**

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @ioampatzidis  wow !1this is awesome :tada: :tada:  thanks a lot for opening this :rocket:

**Comment by cesswairimu** [comment]
Travis is detecting a syntax error  could you please take a look :point_down: Thanks

```
SimpleCov failed with exit 1
/home/travis/build/publiclab/plots2/vendor/.bundle/ruby/2.4.0/gems/i18n-1.8.2/lib/i18n/backend/base.rb:244:in `rescue in load_yml': can not load translations from /home/travis/build/publiclab/plots2/config/locales/gr.yml: #<Psych::SyntaxError: (/home/travis/build/publiclab/plots2/config/locales/gr.yml): mapping values are not allowed in this context at line 71 column 14> (I18n::InvalidLocaleData)
```

**Comment by ioampatzidis** [comment]
> Travis is detecting a syntax error could you please take a look 👇 Thanks
> 
> ```
>  can not load translations from /home/travis/build/publiclab/plots2/config/locales/gr.yml: #<Psych::SyntaxError: (/home/travis/build/publiclab/plots2/config/locales/gr.yml): mapping values are not allowed in this context at line 71 column 14> (I18n::InvalidLocaleData)
> ```

Hello! I already solve this problem, thank you!

**Comment by cesswairimu** [comment]
Great thanks

**Comment by ebarry** [comment]
Thank you @ioampatzidis !!!! This is so exciting!

**Comment by cesswairimu** [comment]
Thanks again @ioampatzidis and welcome to PublicLab :balloon:

**Pull request merged**
