### PR TITLE
Change deliver_now to deliver_later

### LINKED ISSUE #9311: Change deliver_now to deliver_later
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Part of #6126 Change deliver_now to deliver_later
https://github.com/publiclab/plots2/blob/8fe73233a83643c37ecc66bafc9aa6505ea80d5a/app/models/node.rb

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by itshady**
Fixes #9311 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by itshady** [comment]
This is my first pull request. Please let me know if there is anything I need to change! Thanks

**Comment by cesswairimu** [comment]
Hi @itshady,

I am sorry we have to change some tests after the implementation since our current tests expect the emails to be sent immediately...would you like to make these changes? this would involve wrapping the failing tests logic with `perform_enqueued_jobs do` e.g  [this block](https://github.com/publiclab/plots2/blob/main/test/unit/node_test.rb#L51-L64) would be 
```
 test 'notify_callout_users' do
  perform_enqueued_jobs do
    saved, node, revision = Node.new_note(uid: users(:naman).id,
                    title: 'Note with mentioned users',
                    body: '@naman18996 and @jeffrey are being mentioned in the body')
    node.notify_callout_users
    emails = []
    ActionMailer::Base.deliveries.each do |m|
      if m.subject == "(##{node.id}) You were mentioned in a note"
        emails = emails + m.to
      end
    end
    assert_equal 2, emails.count
    assert_equal ["naman18996@yahoo.com", "jeff@publiclab.org"].to_set, emails.to_set
  end
  end
```
makes sense?  please let me know if you get any issues or need any help with the changes.. 
Thanks a lot for working on this

**Comment by itshady** [comment]
Hey @cesswairimu,

Thanks for allowing me to work on this as my first pull request! 

In terms of what you said, would you just like me to replace the block of original code with the code you have just sent or do I have some coding to do?

**Comment by cesswairimu** [comment]
yes, please replace the original code on that test with the block I sent. Thanks

**Comment by itshady** [comment]
@cesswairimu sounds good. Just confirming, should the block of code you sent have both "end"s in the last 2 lines or only one of them?
Thanks again.

**Comment by cesswairimu** [comment]
yeah that's correct

**Comment by itshady** [comment]
@cesswairimu okay I created a new pull request with the wrapping around the code. Could you please let me know if it is good? I'm not sure if my old commits got removed from this new pull request. Hopefully, they did.

Thanks!

**Comment by cesswairimu** [comment]
Hey @itshady, looks like your changes did not reflect correctly..I will try to make the changes on this branch see if I will be able to commit

**Comment by cesswairimu** [comment]
Also it looks like you deleted a file that was not meant to be deleted

**Comment by cesswairimu** [comment]
@itshady I am sorry, that did not work, could you please make a branch from your main branch and make the changes you made initially from there and create a pull request from there....I will help fix the failing tests...looks like I cannot push to your main branch and its good practice to make  changes on a branch,,, thanks

**Comment by itshady** [comment]
@cesswairimu sounds good, I will retry the pull request. I will delete my old fork and fork the repo again so please check for my new pull request.

**Pull request closed without merging**
