### PR TITLE
Search field is made required

### LINKED ISSUE #3375: Improve in questions page when search  questions by topic
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

In Questions page when i search  nothing means when search input box is blank and then click search button It's giving this error page  and and when I type space in search input box it's also search for '  ' (space) tag 
public

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**Improve tags and search .Here should be messege when we didn't type anything and then message show ' required filed '

re

Code links….
https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/tag/_sorting.html.erb#L4
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by JonathanXu1**
Fixes #3375 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
image

### CODE REVIEW

**Comment by jywarren** [comment]
This looks good, but perhaps some tests are failing -- you can click through the X link above, or click https://travis-ci.org/publiclab/plots2/builds/457507071 to see what happened. IT's helpful to paste the error back in here to help debug! Thank you!

**Comment by JonathanXu1** [comment]
Near the end of the Travic CI log, starting from line 2589, there is an error:

```
$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi
fatal: Couldn't find remote ref refs/heads/danger_base
fatal: Couldn't find remote ref refs/heads/danger_head
fatal: Couldn't find remote ref refs/heads/danger_base
fatal: Couldn't find remote ref refs/heads/danger_head
fatal: Couldn't find remote ref refs/heads/danger_base
fatal: Couldn't find remote ref refs/heads/danger_head
fatal: Couldn't find remote ref refs/heads/danger_base
fatal: Couldn't find remote ref refs/heads/danger_head
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/publiclab/plots2
 * [new tag]           v2.0.1     -> v2.0.1
 * [new tag]           v2.1.0     -> v2.1.0
 * [new tag]           v2.2       -> v2.2
 * [new tag]           v3.0.0     -> v3.0.0
/home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.8.1/lib/danger/scm_source/git_repo.rb:128:in `find_merge_base': Cannot find a merge base between danger_base and danger_head. (RuntimeError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.8.1/lib/danger/scm_source/git_repo.rb:16:in `diff_for_folder'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.8.1/lib/danger/danger_core/dangerfile.rb:260:in `setup_for_running'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.8.1/lib/danger/danger_core/dangerfile.rb:270:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.8.1/lib/danger/danger_core/executor.rb:28:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.8.1/lib/danger/commands/runner.rb:70:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/danger-5.8.1/bin/danger:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/danger:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/danger:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi" exited with 1.
Done. Your build exited with 1.
```
I'm completely lost on what just happened or how to fix it 😅

**Comment by jywarren** [comment]
Ah, this was solved in another PR, so I'm going to close this one! Thank you!

**Comment by jywarren** [comment]
Ack, not this one! Got confused what page i was on -- reopening, apologies!!!!

**Comment by rishabhptr** [comment]
@JonathanXu1 Thank you for the PR! Can you please update your feature branch to fix the tests.:smile

Please try to follow the following link for getting the latest changes. You can skip step 2 in this.

https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

**Comment by jywarren** [comment]
Hmm, i don't see a commit listed in this PR - if you've pushed to `topic-search` you should see it appear in this thread with a commit hash. Are you sure you pushed to the right branch?

**Comment by JonathanXu1** [comment]
Oh my bad, I rebased the wrong branch. Sorry about the inconvenience!

**Comment by rishabhptr** [comment]
Rebase seems to have done correct, let's just try to retrigger CI. Closing and opening!

**Comment by jywarren** [comment]
Nice!!! Thanks!!

**Pull request merged**
