### PR TITLE
Include custom configuration for mysql container

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
Reference to internal sysadmin tracker: https://github.com/jywarren/web/issues/91

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
My bad, I need to rebase this, sorry.

**Comment by icarito** [comment]
Note that this is basically merging in the recent work on the database in production.

**Comment by jywarren** [comment]
Is this ready for merge as well? Thanks!

**Comment by icarito** [comment]
superseded by #1428

**Pull request closed without merging**
