### PR TITLE
Delete answer rb

### LINKED ISSUE #8512: Delete answer.rb (start with deleting related code)
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/models/answer.rb](https://github.com/publiclab/plots2/blob/main/app/models/answer.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -1,35 +0,0 @@
-class Answer < ApplicationRecord
-  include CommentsShared
-  include NodeShared
-  extend RawStats
-
-  belongs_to :node, foreign_key: 'nid'
-  belongs_to :user, foreign_key: 'uid'
-  has_many :answer_selections, foreign_key: 'aid'
-  has_many :comments, foreign_key: 'aid', dependent: :destroy
-
-  validates :content, presence: true
-
-  scope :past_week, -> { where("created_at > ?", (Time.now - 7.days)) }
-  scope :past_month, -> { where("created_at > ?", (Time.now - 1.months)) }
-
-  def body
-    finder = content.gsub(Callouts.const_get(:FINDER), Callouts.const_get(:PRETTYLINKMD))
-    finder = finder.gsub(Callouts.const_get(:HASHTAGNUMBER), Callouts.const_get(:NODELINKMD))
-    finder.gsub(Callouts.const_get(:HASHTAG), Callouts.const_get(:HASHLINKMD))
-  end
-
-  def body_markdown
-    RDiscount.new(body, :autolink).to_html
-  end
-
-  # users who like this answer
-  def likers
-    answer_selections
-      .joins(:user)
-      .references(:rusers)
-      .where(liking: true)
-      .where('rusers.status': 1)
-      .collect(&:user)
-  end
-end
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by nibble0101**
Fixes #8512 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by nibble0101** [comment]
@jywarren @sagarpreet-chadha I don't know what is going on here. Googling the error took me [here](https://github.com/houndci/hound/issues/1109). It could be same/similar problem.

**Review by Tlazypanda — COMMENTED** [review]
Hey @nibble0101 There seems to be one line left in this file as flagged by codeclimate bot in the comment :sweat_smile: ``@@ @@``

**Comment by cesswairimu** [comment]
Yes @Tlazypanda we should delete the file completely. @nibble0101 kindly update. Thanks you both

**Comment by nibble0101** [comment]
@Tlazypanda  and @cesswairimu  Thanks for the feedback. The initial instruction was actually to delete everything and replace it with that line of code.

**Comment by cesswairimu** [comment]
@nibble0101 kindly add back your changes we debug from there, Thanks

**Comment by nibble0101** [comment]
@cesswairimu  The equired changes have been added.

**Comment by cesswairimu** [comment]
great, will be on the lookout for travis report. Thanks

**Comment by cesswairimu** [comment]
These are some of the failing tests
Screenshot from 2020-10-22 19-25-33

It looks like we still have tests for the answer model, l will check if we can replace those or remove them.

**Comment by jywarren** [comment]
Hi all - this was my mistake, apologies. There are still references to Answer in other files. I removed them from /app/models/user.rb but will look for more too.

I'm starting here: https://github.com/publiclab/plots2/search?q=answer

Only the Ruby ones would be essential in a first round. I'm seeing:

https://github.com/nibble0101/plots2/tree/delete-answer-rb/test/functional/questions_controller_test.rb#L69

https://github.com/nibble0101/plots2/blob/6faac02ddadd6a2d4ee03a60dee498969124604a/test/unit/comment_test.rb#L157-L176

https://github.com/nibble0101/plots2/blob/6faac02ddadd6a2d4ee03a60dee498969124604a/app/controllers/stats_controller.rb#L66-L72

So we will have to remove many of these. @nibble0101 I'm so sorry this was a lot more involved than I'd thought! I'm happy to try making the changes, but if you'd like to give it a try we'd also be grateful and happy to help!

**Comment by nibble0101** [comment]
@jywarren  I can finish working on this but you need to point me in the right direction. Never worked with ruby before.

**Comment by jywarren** [comment]
Hi @nibble0101 my sincere apologies. I think we need to continue removing the mentions of "answers" from the code. I'm going to mark the orig issue as not a first-timers-only, and i'm so sorry this became much more complex. Please say hello in #9083 if you'd like to try another, and we're grateful for your help!

**Pull request closed without merging**
