### PR TITLE
Add test task to Makefile

### PR DESCRIPTION
**Pull request by icarito**
This adds a command that we use in Jenkins to build : `make test-container`.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
Closing and reopening to trigger CI...

**Comment by icarito** [comment]
Sorry for the noise, trying to get Jenkins to update commit status here.

**Comment by icarito** [comment]
This is bulding in Jenkins now too (can only be triggered by members of publiclab organization). The build is real fast too because it caches the docker image!

**Comment by jywarren** [comment]
Oh cool, is it the tests? Did it fail on the same issue?

**Comment by icarito** [comment]
Yes it runs the tests in Jenkins for pull requests and (currently)
test_makefile branch (we should switch to master when this is merged).
It triggers only on admins and publiclab gh organization members actions.

**Pull request merged**
