### PR TITLE
update likes with emoji_type: nil to emoji_type: ThumbsUp

### PR DESCRIPTION
**Pull request by ViditChitkara**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
want to try pushing to unstable? 🎉

**Comment by ViditChitkara** [comment]
Sure!

**Comment by ViditChitkara** [comment]
Pushing on unstable!

**Comment by ViditChitkara** [comment]
@jywarren the build went well on jenkins but it shows some wierd error--something related to memory

**Comment by ViditChitkara** [comment]
```*** Error in `/usr/local/bin/ruby': free(): invalid next size (fast): 0x000055a2341f9950 ***```
Here it is!!

**Comment by ViditChitkara** [comment]
@jywarren any ideas on this? The build went fine but shows error on travis. Locally this worked perfectly.

**Comment by jywarren** [comment]
aha - i've seen this one -- try restarting it!

**Comment by ViditChitkara** [comment]
tried already! Gives the same error!

**Comment by jywarren** [comment]
whoa... let me try one more time. Hmm.

**Comment by ViditChitkara** [comment]
Wohoo, passed this time!! That's really cool!

**Comment by jywarren** [comment]
Hm, I guess I'm still wondering if standardizing to the standard emoji short code value would be a good idea: https://www.emojibase.com/emoji/1f44d/thumbsupsign `:+1:`

I don't know though. If you think this is good, i'll merge! Thanks!

**Comment by ViditChitkara** [comment]
Sure, no problems. I'll make the changes.

**Comment by ViditChitkara** [comment]
Hi @jywarren, I tried replacing ThumbsUp with +1 which is when I realised that the logic becomes a lot more clumsy due to this. First of all the + in "+1" is ignored in query params, which makes it just " 1". It is also ignored when I try to use instance variables (e.g. '@likes') inside views. And I just realised github uses "ThumbsUp" too, maybe the reason being the same. This is doable but we might need to handle a lot of cases for this.
Your thoughts on this??

**Comment by jywarren** [comment]
ah, that makes a lot of sense! I'd say let's just do ThumbsUp - or maybe
:thumbs_up: since we see a lot in that syntax (:raised_hands: and such) --
thanks! And if there's a convenient place to note this in a comment, let's
do.

**Comment by ViditChitkara** [comment]
Cool, so shall we go forward with this?? Or any other changes I need to make? We need to make it ThumbsUp instead of +1 for comment autocomplete. Please correct me if I'm wrong.

**Comment by jywarren** [comment]
I think let's change it to `thumbs_up` but then go forward with this! Thanks, @ViditChitkara !!!

**Comment by ViditChitkara** [comment]
Hmm, I have kept it `thumbs_up` (helped to generalise the like function), however in emoji_type it is all in camel case (e.g, ThumbsUp, Laugh, etc.).

**Comment by jywarren** [comment]
ok awesome, good to go now? Thanks @ViditChitkara !!!

**Comment by ViditChitkara** [comment]
Yes!!

**Comment by jywarren** [comment]
Awesome!!! 🎉 🎉 🎉

**Comment by ViditChitkara** [comment]
Thanks a lot!

**Pull request merged**
