### PR TITLE
Changes Toggle button of LEL .

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Screenshots :

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
screenshot 2019-01-02 at 3 04 17 pm
screenshot 2019-01-02 at 3 04 05 pm


screenshot 2019-01-02 at 3 03 47 pm

**Comment by jywarren** [comment]
Hi, I'd like to ask for input from @ebarry @steviepubliclab and @edieblue
on this - what do you think of this wording? Also, in the narrower view,
perhaps we should just show the icon, or is there some shorter text we
could use in that limited space? Thanks Sagarpreet, for helping to make the
additional layers more obvious!

**Comment by siaw23** [comment]
Hi @jywarren is this good to go after the merge conflict?

**Comment by jywarren** [comment]
Hi, I think we'll close this in light of some of the recent UI development over at https://github.com/publiclab/leaflet-environmental-layers/issues/60 and https://github.com/publiclab/leaflet-environmental-layers/issues/134 -- thank you!!!

**Pull request closed without merging**
