### PR TITLE
chore: update README.md

### LINKED ISSUE #4749: Possible changes in README.md
Here, I am adding some possible changes that first timers can make to README in order to get started with contributing.

### PR DESCRIPTION
**Pull request by saumyag33**
Fixes #4749 (Task mentioned in the issue thread)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by saumyag33** [comment]
@publiclab/reviewers Should I check the boxes meant for UI updates as the PR is not related to any UI change?

**Comment by gauravano** [comment]
No need to mark the screenshot checkbox. Thanks @saumyag33

**Comment by gauravano** [comment]
@saumyag33 you want to make any other changes or it's ready for review?

**Comment by saumyag33** [comment]
@gauravano I think I don't have any changes in my mind. Do you have any other ideas for README?

**Comment by gauravano** [comment]
No issue from my side. Thanks, merging it now!

**Comment by gauravano** [comment]
Hey @saumyag33 , thanks for the nice work. We would love to have more help from you. If you are interested in solving more issues then check here - https://code.publiclab.org/#r=all for a new issue. In case, you are unable to find an issue, feel free to comment here. Thanks!

**Pull request merged**
