### PR TITLE
[Outreachy]Follow Page Links to Subscriptions

### LINKED ISSUE #8965: Ensure Follow Text at The Top and Bottom of The Page Links to /subscriptions
This is part of #8513

Ensure Follow Text at the top and  bottom of the page links to /subscriptions

Add mobile responsiveness to the section

### PR DESCRIPTION
**Pull request by RuthNjeri**
Fixes  #8965

PR #9030 should be merged first.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Screenshot 2021-01-18 at 20 49 23
Screenshot 2021-01-18 at 20 49 28

### CODE REVIEW

**Review by jywarren — CHANGES_REQUESTED** [review]
Hi @RuthNjeri can you rebase this so I can see the changes in isolation? Sorry, it's probably fine as this is a small PR (thanks!) but it's a bit hard to see what's new vs. #9030. I appreciate it!

**Comment by RuthNjeri** [comment]
Hi @jywarren 😄 
I've rebased the PR... it should be okay now..

**Comment by jywarren** [comment]
Wow that was fast! ⚡ 

OK, reviewing and the tests should take a little longer. Oh wait, they failed? But after 2m? Hmm. could there have been a syntax error or something?

**Review by jywarren — APPROVED** [review]
Yes, tests failed due to intermittent issue related to nids, i believe:

```

Progress: | FAIL["test_graph", #<Minitest::Reporters::Suite:0x000055d7db6f4c40 @name="TagSelectionTest">, 0.2764799499999526]
 test_graph#TagSelectionTest (0.28s)
        Expected: 18
          Actual: 22
        test/unit/tag_selection_test.rb:14:in `block in <class:TagSelectionTest>'
```

I restarted and hopefully we solve this in https://github.com/publiclab/plots2/pull/8865

but this PR should be fine! Thanks!

**Comment by RuthNjeri** [comment]
> Yes, tests failed due to intermittent issue related to nids, i believe:
> 
> ```
> 
> Progress: | FAIL["test_graph", #<Minitest::Reporters::Suite:0x000055d7db6f4c40 @name="TagSelectionTest">, 0.2764799499999526]
>  test_graph#TagSelectionTest (0.28s)
>         Expected: 18
>           Actual: 22
>         test/unit/tag_selection_test.rb:14:in `block in <class:TagSelectionTest>'
> ```
> 
> I restarted and hopefully we solve this in #8865
> 
> but this PR should be fine! Thanks!

oh, I cancelled it to restart it...let me re-restart it 😄

**Comment by jywarren** [comment]
ah oops, sorry - thanks!

**Comment by jywarren** [comment]
@RuthNjeri do you have an FTO on hand for someone in https://github.com/publiclab/plots2/issues/9023#issuecomment-761876013 ? If not i can dig one up, but in case you had some stored up?

Thanks!

**Comment by RuthNjeri** [comment]
@jywarren I could make this #8839 and FTO... I was to clarify if it is a needed feature....

**Comment by jywarren** [comment]
Oh, actually I'm not sure what that one means, is it so admins can easily
find the features system or is it to display a feature itself? Either could
be a nice FTO!

**Comment by RuthNjeri** [comment]
It's actually just adding a url to the features page for the admins on the dashboard page

**Comment by RuthNjeri** [comment]
I can add some translation ftos as well...let me create some...

**Comment by jywarren** [comment]
This passed, so merging it!!!

> It's actually just adding a url to the features page for the admins on the dashboard page

Sounds great, if only admins see it. Or it could be a navbar menu item, under the profile menu? Either works fine! Thanks, Ruth!

**Comment by RuthNjeri** [comment]
I added this one in the meantime https://github.com/publiclab/plots2/issues/9033 and shared it in #9023 (comment)

**Pull request merged**
