### PR TITLE
[Outreachy Comment Editor] New Test: Respond to Question Comment

### PR DESCRIPTION
**Pull request by noi5e**
## Prerequisite: Merge #8801 First!

- Add new fixtures for testing question comments (already exists in prerequisite PR):
  - node.yml
  - comment.yml
  - revision.yml
  - node_tags.yml
  - tags.yml
- New test:
  - find first comment ID (the new comment fixture)
  - POST new comment with addComment
  - assert that comment text exists

```
  test 'question page: respond to existing comment with addComment' do
    visit "/questions/jeff/12-07-2020/can-i-post-comments-here"

    # find comment ID of the first comment on page
    parent_id = "#" + page.find('#comments-list').first('.comment')[:id]
    parent_id_num = /c(\d+)/.match(parent_id)[1] # eg. comment ID format is id="c9834"

    # addComment(comment text, submitURL, comment's parent ID)
    page.evaluate_script("addComment(\"no you can't\", '/comment/create/37', #{parent_id_num})")

    # check for comment text
    assert_selector("#{parent_id} .comment .comment-body p", text: 'no you can\'t')
  end
```

(This PR is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

### CODE REVIEW

**Review by Sagarpreet — APPROVED** [review]
Awesome simple test 🎉 
Can you paste screenshot also after running test in gitpod if possible?

**Comment by noi5e** [comment]
@Sagarpreet thank you! I will test in GitPod as soon as it gets back up and running. 

@cesswairimu said she was working on getting it back up.

**Comment by jywarren** [comment]
In the short term if you can confirm no new test failures due to this (in comparison to `main`) we should be good to bypass Travis for now. Thank you!!! #8801 is merged, too!

**Comment by noi5e** [comment]
@jywarren Thanks, ran the tests locally, they look normal, and resolved the conflicts.

**Comment by jywarren** [comment]
Awesome!!!!

**Pull request merged**
