### PR TITLE
advanced tagging menu updated-lock note added

### LINKED ISSUE #9988: Move "Lock note" link into sidebar "advanced tagging" dropdown menu
The new link prompting admins and mods to lock a note is currently in the main column of notes, as shown here:

image

Let's move it into the sidebar "advanced tagging" dropdown menu shown here:

image

This could be a nice FTO! Thanks!

### PR DESCRIPTION
**Pull request by Ash-KODES**
Fixes #9988  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Ash-KODES** [comment]
can you please guide me where i went wrong again?
@Tlazypanda

**Comment by Manasa2850** [comment]
@Ash-KODES can you add screenshots / gif to make sure it's working fine? Thanks

**Comment by noi5e** [comment]
@Ash-KODES This looks pretty good so far! Would you mind posting some screenshots/video so we can see how this looks?

> can you please guide me where i went wrong again?

It looks like the earlier continuous integration run you were talking about failed, but not because of anything you did. Sometimes our CI can be a little buggy, apologies! 😅 I'm happy you figured out you can close and re-open the PR, that can usually help when PRs fail due to buggy CI.

**Comment by Ash-KODES** [comment]
I am facing some issues in running the project locally?
some times it runs and some of the times throw errors and last time when i made changes  it was running but now i am facing issues again can anyone please help me out?..
i am using a linux os(ubuntu)

..and sorry for the late reply i was  little busy with my university exams ..apologies

**Comment by Ash-KODES** [comment]
Screenshot from 2021-09-01 23-44-07

**Comment by jywarren** [comment]
This looks great! Thank you!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Great work @Ash-KODES!!! 🎉

**Comment by Ash-KODES** [comment]
> Great work @Ash-KODES!!!

thank you

**Pull request merged**
