### PR TITLE
Tags should not be created when string has #____ in it

### LINKED ISSUE #2426: Prevent auto-tagging of numerical inline tags like #1234
Needs more info! Soon, thanks!

https://github.com/publiclab/plots2/blob/2d43c7d908dd8b65d3ca7681cc35a107770e0f20/app/models/revision.rb#L43-L48

https://github.com/publiclab/plots2/blob/2d43c7d908dd8b65d3ca7681cc35a107770e0f20/config/initializers/constants.rb#L1-L11

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2426 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Ah, hi @Gauravano -- actually i think we want to not remove the hash-making altogether, but just to not match number-only tags. 

So I think this should be the fix -- this line:

https://github.com/publiclab/plots2/blob/2d43c7d908dd8b65d3ca7681cc35a107770e0f20/config/initializers/constants.rb#L3

Could become the regex expression `(\s)\#([:0-9_-]*[a-zA-Z]+[:0-9_-]*)` -- see? We do 1 or more of `a-z` and zero or more of everything else. So there has to be at least one alphabetic character. 

http://rubular.com/r/oIdklH3BaK

What do you think?

**Comment by Gauravano** [comment]
Sorry @jywarren , I was little busy, so can't do much here, but now as you have figured out the Regex for this too, it wouldn't take long. So, completing it now.Thanks.

**Comment by jywarren** [comment]
Oh awesome. And you may have been busy but also SUPER active the past few days -- thanks so much!

**Comment by jywarren** [comment]
Awesome, and with tests too! 👍 🎉 🎏

**Comment by seafr** [comment]
I've noticed @Gauravano can be counted on to bring along the tests. :+1:

**Pull request merged**
