### PR TITLE
feature: added notyNotification for comment emoji reaction notifications.

### LINKED ISSUE #9071: Display Notification for Emoji Reactions on a Comment
What do you all think about having a Noty Notification displayed when user reacts to a comment?

### Expected
**For example**, [here is a **video** that shows notification when user DELETEs a comment](https://user-images.githubusercontent.com/4361605/105646033-6339e580-5e52-11eb-9574-e535a9abe792.mov).

An image of **Delete Notification** below:
Screen Shot 2021-01-24 at 2 44 45 PM

We could have a similar notification for when user reacts to a comment. The notification could have a string like:
- _Reacted with "Hooray!_
- _Reacted with "Thumbs Down" to Comment_
- _Removed "Thumbs Down" Reaction_

### Actual
This [**video** shows what currently happens when the user emoji-reacts to a comment](https://user-images.githubusercontent.com/4361605/105646133-0559cd80-5e53-11eb-9776-06695455bcb4.mov)

- No notification at all
- Sometimes there can be a delay after the user clicks on the reaction, and before the reaction appears on the comment. This can be a little confusing sometimes. Maybe a notification would help this be less confusing?

On the other hand, I know that for example facebook doesn't flash notifications when a user likes a post. Is this something we even want to do? If so, I'm happy to help guide whoever takes this issue on.

### PR DESCRIPTION
**Pull request by iem-saad**
Fixes #9071  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Hi, I've completed task #9071. For Demo please find attached video and review the code if there is anything unusual please let me know i will be happy to help.
Thanks.

https://user-images.githubusercontent.com/54322326/184619736-8565760d-0a97-4c9b-b6a9-8d57b0d681d9.mp4

### CODE REVIEW

**Comment by iem-saad** [comment]
@publiclab/reviewers Please review this PR.
Thanks

**Review by cesswairimu — APPROVED** [review]
Hi @iem-saad this is looking great :tada: thanks for working on it

**Comment by iem-saad** [comment]
Thanks @cesswairimu :heart:

**Comment by iem-saad** [comment]
@noi5e Hi, can you please review this and merge so that I can close the PR.
Thanks

**Comment by cesswairimu** [comment]
I will go ahead and merge this, thanks you both

**Pull request merged**
