### PR TITLE
Popover hides if user clicks anywhere on screen

### LINKED ISSUE #4987: The popover does not close down unless clicked specifically again
I found this issue while trying to solve the issue #4985 #4986 
## Description 
The popover opens when tag pill is clicked, but it does not closes down unless clicked specifically again on same pill. If a new tag is added or user clicks on any other thing, it still doesn't close down. 

## Current Behaviour
Screenshot from 2019-03-10 19-37-59

hh

gg

## Expected Behaviour 
A popover should close down if the user clicks anywhere on screen. A user should not have need to click on tag pill again to close it.

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes #4987

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

## Earlier 
hh

## Current 
remain

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
I need help regarding this draft PR.
I don't seem to get that why the pop is showing blank.

**Comment by CleverFool77** [comment]
The earlier blank page problem I was facing is resolved. The PR is ready to be reviewed :).
@avsingh999

**Comment by gauravano** [comment]
@CleverFool77 I tried your PR locally and found  this 

color_bug

Also, do you think the opening and closing experience can be more smooth and consistent as currently-- sometimes clicking on other tag opens new popover and sometime it does'nt and also there's a kind of blurry effect in background
breaks

**Comment by CleverFool77** [comment]
@gauravano Sure I'll update it :).

**Comment by gauravano** [comment]
Closing this as per https://github.com/publiclab/plots2/issues/5072#issuecomment-472974341 . Thanks!

**Pull request closed without merging**
