### PR TITLE
Add co-author to blog index page

### LINKED ISSUE #8118: Update blog template to show co-authors
**Please describe the desired behavior.**
@joyofsoy would like to see co-authors displayed on https://publiclab.org/blog. This page has some fancy styling which is nice, and needs a little update to include the newer co-authoring feature on Research Notes. 

**Additional context (optional)**
The original note shows the co-author: 
screen_shot_2020-07-06_at_10 05 15_am_480

However, the blog only shows the first author: 
screen_shot_2020-07-06_at_10 03 51_am

### Thank you!

### PR DESCRIPTION
**Pull request by mronauli**
Fixes #8118  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Thank you so much! This was a really great, easy to review and well written fix. So appreciated! 🎉 💯

**Comment by mronauli** [comment]
@jywarren thanks for merging and the opportunities to contribute to your open source project!

**Comment by jywarren** [comment]
Of course! We'd love to work with you on another if you're interested.

**Comment by jywarren** [comment]
If you'd like to help someone else out on their first contribution, I just posted one here, and someone will probably show up to try to solve it soon! I'm sure they could use some encouragement if you're interested. :-)

https://github.com/publiclab/plots2/issues/8174

**Pull request merged**
