### PR TITLE
Update users_controller.rb to require login before edit

### LINKED ISSUE #2554: User must be logged in to access edit routes
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/controllers/users_controller.rb](https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -1,6 +1,6 @@
 class UsersController < ApplicationController
   before_filter :require_no_user, :only => [:new]
-  before_filter :require_user, :only => [:update]
+  before_filter :require_user, :only => [:edit, :update]
   before_action :set_user, only: [:info, :followed, :following, :followers]
 
   def new
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by rob4abcba**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

fixes #2554

### CODE REVIEW

**Comment by rob4abcba** [comment]
@sagarpreet-chadha @publiclab/reviewers ok, i think i now have made the pull request in the plot2 repository.  Let me know.  I also posted a bunch of questions, so I understand how git/github works.

**Comment by seafr** [comment]
The broken test above has been fixed in PR #2579.
@rob4abcba this PR is ready!

**Comment by jywarren** [comment]
Hi, all! @rob4abcba if you want to try `git pull https://github.com/seafr/plots2.git tests-5-routes` to pull in #2579, then we can get the two combined PRs to pass tests and then I can merge it in!

Looks great!!!

**Comment by jywarren** [comment]
@rob4abcba - I believe you can accept this pull request from @seafr and it should resolve your PR's tests!

https://github.com/rob4abcba/plots2/pull/2

**Comment by jywarren** [comment]
OK! I was able to do this on the command line. Let's see what happens!

**Comment by jywarren** [comment]
Perfect! Thanks everybody!!!! Glad this got fixed. 👍 🎉

**Pull request merged**
