### PR TITLE
Fix submit comment on control+enter bug

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5193 (<=== Add issue number here)

coment

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @jywarren @gauravano Please review.
thanks !!!!

**Comment by CleverFool77** [comment]
Hi @gauravano I haven't tried it on mac. :sweat_smile:

**Comment by CleverFool77** [comment]
@jywarren @gauravano Earlier the command key function was not added.
Should I add it now in this PR or next ?

**Comment by CleverFool77** [comment]
> @jywarren @gauravano Earlier the command key function was not added.
> Should I add it now in this PR or next ?

Hi @jywarren.
I had a question regarding this.
Thanks !!

**Comment by CleverFool77** [comment]
Hi @gauravano I didn't keycode for mac, Because i can't test it. So I'm not sure whether it will work even after adding the keycode.

**Comment by CleverFool77** [comment]
And Although I can add this after checking the keycode online, But need a reviewer to check whether its working or not.

**Comment by CleverFool77** [comment]
Hi @jywarren @gauravano Can we have a look into this PR.
Thanks !!

**Comment by gauravano** [comment]
Hi @CleverFool77, sorry for replying late. 

First, please rebase your PR.
Second, as we have nested comments now, so we need to test it there. Example: There are 3 comments on a note. So, each of that comment might be having a form. Check if this shortcut is affecting other forms, or submitting them. 
Third, I did the rebase locally and tried your PR but wasn't able to use any shortcut like ctrl+return or cmd+enter. So, if you can test the above case on your system, then we can make it work on Mac next. 

Thanks!!!

**Comment by CleverFool77** [comment]
Tanks for the reply gaurav. I'll look into this.

**Comment by SidharthBansal** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by VladimirMikulic** [comment]
Hi @CleverFool77. I've fixed this PR and added some additional features in #7301.
Thank you for working on this :+1:

**Pull request closed without merging**
