### PR TITLE
replace &amp; with and

### LINKED ISSUE #4681: Replace "&amp;" HTML Entity
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: There are many instances of code containing "`&amp;`" to implement the "&" character in the website, but instead it renders the "`&amp;`" string itself.

screenshot from 2019-01-22 01-30-28

In order to resolve this, we can replace the following "`&amp;`" instances by "and".

````
./app/views/editor/_editor.html.erb:
   17:           Drag &amp; drop to add an image or file, or 

./app/views/editor/_main_image.html.erb:
   17:         Drag &amp; drop to add an image, or 

./config/locales/views/comments/_edit/en.yml:
    7:       drag_and_drop: "Drag &amp; drop to add an image or file, or"

./config/locales/views/comments/_form/en.yml:
    7:       drag_and_drop: "Drag &amp; drop to add an image or file, or"

./config/locales/views/users/_photo/en.yml:
    7:       drag_and_drop_image: "Drag &amp; drop to add an image, or"
````

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #4681

Replaced all required occurrences of `&amp;` with `and`.

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached in case of UI updation

Updated Behavior 
now

### CODE REVIEW

**Comment by ananyaarun** [comment]
@gauravano pls review. I have replaced the required '&amp;' with 'and' as asked in the issue.

**Comment by ananyaarun** [comment]
@gauravano I think this PR is ready for review and can be merged if @Chrisyee22 is ok with it :)

**Comment by Chrisyee22** [comment]
Yeah that’s fine with me

**Comment by gauravano** [comment]
Great and thanks @Chrisyee22!

**Comment by gauravano** [comment]
@ananyaarun can you add the screenshot of the updated view?

**Comment by ananyaarun** [comment]
@gauravano Sorry i forgot !
Here it is.
## Previous behavior
previous

## After Changes
now

**Comment by gauravano** [comment]
Merged :tada: :balloon: 

If you are interested in helping us more, you can see more issues at https://github.com/publiclab/plots2/issues . Thanks!

**Comment by ananyaarun** [comment]
Thanks @gauravano :))

**Pull request merged**
