### PR TITLE
change links from dashboad2 to dashboard

### PR DESCRIPTION
**Pull request by lalithr95**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by lalithr95** [comment]
Minor PR which changes dashboard2 link to dashboard which reduces the number of redirects between dashboard2 and dashboard. 

I would like to remove the method dashboard2 which again redirects to dashboard method. All the links pointing to dashboard2 with be changed to dashboard.

**Comment by jywarren** [comment]
Hi, this looks good -- happy to merge it in tomorrow. I also want to eliminate the view for the old dashboard (in `home/dashboard.html.erb`) -- so if you want to add that too, I'll merge both tomorrow morning as per the schedule. Thanks!!

**Comment by jywarren** [comment]
This has been merged manually, thanks!

**Comment by lalithr95** [comment]
Thanks :)

**Pull request closed without merging**
