### PR TITLE
Center aligned the rich editor 

### LINKED ISSUE #5150: Center align the question form
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [questionRich.html.erb
](https://github.com/publiclab/plots2/blob/master/app/views/editor/questionRich.html.erb) in the `plots2` repository to add CSS to center align the form.
Code of this form can be added to the div.
`<div align="center">`

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #5150 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

editor

mobile

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
Also this doesnt affect the view on /post pages.

post

**Comment by jywarren** [comment]
Looks ok - i mean, as good as it was before you started, in mobile view! I
wonder, is it shorter in rich text mode? Anything we can do to make it a
little easier to use from a phone?

Thank you so much!!!

**Comment by ananyaarun** [comment]
Hmm can we decrease the height of the box ? Would that help ?

**Comment by jywarren** [comment]
sure, but we ought to do it only on narrower screens. Could you do so with
a @media css query?  https://developer.mozilla.org/en-US/docs/Web/CSS/@media

**Comment by ananyaarun** [comment]
Sure ill make that change :smiley:

**Comment by gauravano** [comment]
Hey @ananyaarun, want any help with this PR? Thanks!

**Comment by ananyaarun** [comment]
Hey @gauravano , There were some issues with the media query in mobile view, But I'll give this another try and get back to you asap. Thanks!

**Comment by gauravano** [comment]
Okay. Thanks @ananyaarun!

**Comment by ananyaarun** [comment]
@gauravano , sorry I haven't been able to look at this yet. Got caught up with college work. I have my final exams till may first week. I'll do this and other pending issues positively then :)
Thanks!

**Comment by gauravano** [comment]
No issue @ananyaarun. All the best for exams!

**Comment by SidharthBansal** [comment]
Please resolve the conflicts whenever you get some time.
Thanks

**Comment by gauravano** [comment]
Hi @ananyaarun, can you update the PR now if you are free?

**Comment by ananyaarun** [comment]
@gauravano , I resolved the conflicts but after the bootstrap update this page looks very different from what it was before when i started working on it and it looks more aligned to the left than before and narrowed down as well.

**Comment by jywarren** [comment]
Hi, I'm going to close this out to give someone else a chance at a fix, thanks so much!

**Pull request closed without merging**
