### PR TITLE
Return_to fixed

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@oorjitchowdhary or @JonathanXu1 can you please try these changes on your localhost:3000 and tell me whether it works for you guys?

**Comment by oorjitchowdhary** [comment]
image

I don't know how, but by adding this.. the login tab was shifted down..

And I'm unable to enter my password in the password field of the login modal so I can't really test it..

**Comment by SidharthBansal** [comment]
I don't know why you are not able to type in the password.
See on unstable, you are able to type the password correctly.

**Comment by oorjitchowdhary** [comment]
Yes, I saw on unstable.. The password field is working.. There's some error with my localhost

**Comment by SidharthBansal** [comment]
You can try on some other browser

**Comment by oorjitchowdhary** [comment]
Ok now it works with chrome..

**Comment by oorjitchowdhary** [comment]
> @oorjitchowdhary or @JonathanXu1 can you please try these changes on your localhost:3000 and tell me whether it works for you guys?

Okay.. it is working well...

**Comment by SidharthBansal** [comment]
You need to check the following
1. go to localhost:3000/questions
2. login through login modal
3. you must be on the localhost:3000/question.
If yes then please provide the screenshot for that.

**Comment by SidharthBansal** [comment]
Ensure that you are logged in.

**Comment by oorjitchowdhary** [comment]
On questions page when you log in through the login modal in the header.. you're redirected to /dashboard after logging in

**Comment by oorjitchowdhary** [comment]
oorjitrunningoraclevmvir 1

**Comment by SidharthBansal** [comment]
Have you made the changes in this pr to your local?

**Comment by oorjitchowdhary** [comment]
Yes I made the changes

**Comment by SidharthBansal** [comment]
Strange this is working on my pc, @okonek pc.
I asked you to help because on the unstable after logging it redirects from unstable.pl.org/questions to pl.org/quesions
It is not working on your pc. 
Make sure that you included         return_to=<%= params[:return_to] || request.path %> and have saved your changes.

**Comment by SidharthBansal** [comment]
ok, I did a mistake in pushing. Sorry. I was pushing some other work in this pr.
Now see the new files and change your files accordingly to check https://github.com/publiclab/plots2/pull/4197#issuecomment-445486447

**Comment by oorjitchowdhary** [comment]
It works now.. I'm just attaching a gif

**Comment by oorjitchowdhary** [comment]
oorjitrunningoraclevmvir 2

**Comment by SidharthBansal** [comment]
Awesome.

**Comment by SidharthBansal** [comment]
@okonek can you please review the changes once so that I can merge this?

**Comment by JonathanXu1** [comment]
Yep, it works on my end as well.

**Comment by SidharthBansal** [comment]
Great. This means I can merge this.

**Comment by SidharthBansal** [comment]
@JonathanXu1 @oorjitchowdhary @okonek please claim the task https://codein.withgoogle.com/dashboard/tasks/5291275109531648/
as you both have tested it you both should get credits.
@okonek helped in giving us potential solution

**Comment by SidharthBansal** [comment]
It is 3 instance count task for 3 of you

**Comment by okonek** [comment]
Ok, but I have to get my previous task approved. Will you accept me this one, when I'll finish my task with Wiki-liking?

**Comment by SidharthBansal** [comment]
Yeah sure.
But it will be great if you will get this task approved before that one. Tomorrow is deadline.

**Comment by okonek** [comment]
Yes I know.

**Comment by oorjitchowdhary** [comment]
> @JonathanXu1 @oorjitchowdhary @okonek please claim the task https://codein.withgoogle.com/dashboard/tasks/5291275109531648/
> as you both have tested it you both should get credits.
> @okonek helped in giving us potential solution

@SidharthBansal Please approve the task..Thanks

**Comment by SidharthBansal** [comment]
approved

**Comment by oorjitchowdhary** [comment]
Thanks a ton 😄

**Comment by SidharthBansal** [comment]
Moved to #4210

**Pull request merged**
