### PR TITLE
Rename dragdrop.js to editorToolbar.js (Outreachy)

### PR DESCRIPTION
**Pull request by noi5e**
Part of an OOP refactoring of editor.js (See #9004 for more details)

The big change here is that I renamed `dragdrop.js` to `editorToolbar.js`.

I did this because this eventListener for `.rich-text-button`s currently lives in `editor.js`:
https://github.com/publiclab/plots2/blob/f82a11c17404bae7b4307313b6890ca3169e8c90/app/assets/javascripts/editor.js#L1-L14

This is confusing, especially since if I'm going to refactor `editor.js` for OOP, I want that script to be a class definition for new `Editor` objects. It makes more sense for a `document.ready` eventListener like the one above to be grouped with similar eventListeners (for `.dropzone`s) in `dragdrop.js`.

But if it's combined with `dragdrop.js`, then that script no longer is dealing just with drag & drop listeners, hence the rename to `editorToolbar.js`&mdash;this script is basically going to be required everywhere that `editor/toolbar` is present.

A plus benefit is that I can move this function to `dragdrop.js`/`editorToolbar.js` and delete `editorHelper.js`:
https://github.com/publiclab/plots2/blob/f82a11c17404bae7b4307313b6890ca3169e8c90/app/assets/javascripts/editorHelper.js#L2-L20

**NOTE:** There are a bunch of places which historically depend on `dragdrop.js`/`editorToolbar.js` for the drag & drop functionality, and I've listed them in [this comment](https://github.com/publiclab/plots2/issues/9004#issuecomment-763204156).

---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

### CODE REVIEW

**Comment by noi5e** [comment]
@jywarren Tests passing, please take a look! Feedback welcome, and this is ready to merge.

**Comment by jywarren** [comment]
I saw CodeCov was showing `No coverage uploaded for pull request base ` and realized it was still configured for a `master` branch; fixed this and restarting tests to get a better coverage report!

**Review by jywarren — APPROVED** [review]
This looks great -- excellent work! To what degree are all these changes covered by tests, do you think? Have you looked into CodeCov to see what the code coverage is for the /app/assets/javascripts/FOO.js files touched here is? 

Thanks!!!

**Comment by noi5e** [comment]
@jywarren Just fixed the merge conflict, so this one's ready-to-merge again.

I took a look at CodeCov, but it looks like it's currently still saying `No coverage uploaded for pull request base`.
Screen Shot 2021-01-20 at 10 54 27 AM

I still haven't learned how to read the CodeCov output. Looking in the [app folder here](https://codecov.io/gh/publiclab/plots2/pull/9044/tree?path=app), but it looks like `assets` doesn't appear for some reason? Any thoughts?

**Comment by noi5e** [comment]
Oh yeah, just to answer your other question:

> To what degree are all these changes covered by tests, do you think?

Linking [the comment I left about `dragdrop.js` coverage](https://github.com/publiclab/plots2/issues/9004#issuecomment-763204156) again.

For this particular PR, I don't think there will be any significant problems because I'm just renaming the script and not changing the contents significantly. For this PR, what matters is that I make sure that every instance of `javascript_include_tag: 'dragdrop'` is changed to `editorToolbar`. 

As long as that's done, the places I've listed will still have eventListeners for `.dropzone` or `#side-dropzone` which is what matters.

I think it is important to have system tests in place for the legacy editor (which we're conversing about in #8858), in case the contents of this script change in the future.

**Comment by jywarren** [comment]
OK, great, and thanks for your answers! Merging this now!!! 🎉 🎉 🎉

**Pull request merged**
