### PR TITLE
add location button on the people's page

### LINKED ISSUE #5707: UI Improvements Planning Issue : People Section
## Description
The basic Card UI of people section is already on halfway.
Now the further improvements are left.
As we were told during proposal that we should start off with easier ones first. And they should be given beginning of time in timeline. So we will start off with people section first which is the easiest.
The final UI for the people's page : 

Screen Shot 2019-05-19 at 2 41 35 AM

@gautamig54 We will add checklists here
#### card ui of users 
- [x] Vertical to horizontal cards @CleverFool77 
- [x] Add tags on cards @CleverFool77 
- [x] Add ellipsis which contains the user details as shown in the design @gautamig54 

#### location
- [x] Add user's location. @gautamig54 

#### search by
- [ ] Add search by various places option below maps. 

#### others
 - [ ] Make the map sticky. 
 - [x] position map on the top instead of bottom, in the mobile view @CleverFool77 
 - [x] Fix overflow of tags @CleverFool77

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5707  (<=== Add issue number here)

User's people page :

Screen Shot 2019-05-21 at 8 33 22 PM

Admin's people page : 

Screen Shot 2019-05-21 at 8 34 16 PM

Mobile view : 

Screen Shot 2019-05-21 at 8 33 35 PM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Cool! Does the add location button pop up the modal dialog to do so?

Also, if possible, we should leave it default font, as per the style guide,
as the Junction font is only for headings. Thank you so much, this is
cool!!!!

**Comment by jywarren** [comment]
oh hmm, the default text font (for <p>) should be the Bootstrap default,
i'm not sure if that got misconfigured during the Bootstrap upgrade? The
style guide lays out some nice guidelines for this, however:
https://docs.google.com/presentation/d/1-XHlVn3KQxSjS5WzHgc1l1qvFwqUC5f3-7GXugUP9u4/edit?ts=5cab5403#slide=id.g58d9556a0e_1_523

**Comment by gautamig54** [comment]
Oh I get it! 
The style for the entire page has been set to Junction regular. That is why even the content on cards are of font junction. I will confine the junction font to only headings and change the rest to default.
Thanks @jywarren!!

**Comment by jywarren** [comment]
OK awesome!

**Comment by gautamig54** [comment]
Does the font style seem fine @jywarren ??

Screen Shot 2019-05-21 at 10 30 09 PM

**Comment by jywarren** [comment]
It's awesome, fantastic! Thanks!!!

**Pull request merged**
