### PR TITLE
Recaptcha signup

### LINKED ISSUE #899: Signup sequence overhaul
The signup interface is perhaps our most important design of the entire site -- if people can't get past it, all participation/contribution is limited. Let's take a thorough look at it, esp. the captcha, which we've heard reports of folks getting stuck at.

The captcha of the signup sequence looks like this now:

screen shot 2016-10-17 at 4 13 09 pm
### What happened just before the problem occurred

> didn’t like the selecting each question, picked wrong and each time she did it erased what she had already put in

When you get it wrong you get a new set of questions, and it deletes username/pwd fields as well.

@steviepubliclab suggests changing questions, I agree. avoid terms that require a sense of humor, which may not translate. Something more welcoming. 

Look into login via Facebook
### Relevant URLs

https://publiclab.org/signup
### New questions

Let's come up with some more translatable questions! Leave suggestions below.

### LINKED ISSUE #1201: Create swappable substitute for Spamaway class which uses new ReCaptcha
* Docs: https://www.google.com/recaptcha/

`<script src='https://www.google.com/recaptcha/api.js'></script>`

* [x] Develop swappable replacement for each instance of "spamaway" in this method:

https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb#L5-L48

In that controller, these will have to have substitutes based on Recaptcha.

* [x] Spamaway.new
* [x] Spamaway.new(params[:spamaway])
* [x] @spamaway.valid?
* [x] @spamaway.errors

### PR DESCRIPTION
**Pull request by jywarren**
closes #899, closes #1201 

Note that the Recaptcha isn't always just a "click the box" and can sometimes request the following tasks:

screenshot 2017-01-20 at 6 42 53 pm
screenshot 2017-01-20 at 3 54 36 pm

But I made it so that if you fail the Recaptcha, it offers to let you use the old spamaway system, which is preserved. Tested manually (since automated tests, obviously, can't do the test! They're robots.)

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] reviewed/confirmed/tested by another contributor or maintainer

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, @steviepubliclab and @ebarry - if you have a moment to check through this for a thumbs-up, or have questions, it's ready to merge in, and could be published later today if you're interested.

**Comment by steviepubliclab** [comment]
You finished!? Wow, yes merge away!! 
-Stevie

**Comment by jywarren** [comment]
These seem like reasonable potential requirements? The drawing one was a
pain.

**Comment by steviepubliclab** [comment]
Oh I see. are they all like that?? Can we phone for a min. before staff
call?

**Comment by jywarren** [comment]
Hi, Stevie - how about adding this one more thing to the "did you have trouble" message?

`or <a href='mailto:staff@publiclab.org'>ask staff for help</a>`

or is there a more appropriate address?

Last check before merging!

**Pull request merged**
