### PR TITLE
Renaming _form2 partial (https://github.com/publiclab/plots2/issues/4…

### LINKED ISSUE #4269: Extract out edit controller data from the form partial
Due to the signup and login modal integrations, I need to divide the users/_form.html.erb into two parts form2 and form partials. After #4209 is merged. We need to
- [x] Extract out edit controller data from the form partial 
- [ ] Change _form partial to some other name
- [ ] Similarly change name for _form2 partial.

### PR DESCRIPTION
**Pull request by kunalvaswani123**
…269) #4353

Fixes #4269  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Yeah please provide the screenshots.
I think you are missing something.

**Comment by kunalvaswani123** [comment]
I found the files the same way using git grep

**Comment by kunalvaswani123** [comment]
image
image
image
image

**Comment by kunalvaswani123** [comment]
image
image
image
image

**Comment by SidharthBansal** [comment]
Awesome!!!

**Comment by kunalvaswani123** [comment]
when I hit save on the edit route it gives:
image

**Comment by SidharthBansal** [comment]
Can you please send a quick patch for this?

**Comment by SidharthBansal** [comment]
patch means changes in the form of commit or Pull Request(PR)

**Comment by SidharthBansal** [comment]
Can you send a pull request for fixing this button on /profile/edit?

**Comment by kunalvaswani123** [comment]
ok let me try

**Comment by SidharthBansal** [comment]
Great Thanks!!!

**Comment by kunalvaswani123** [comment]
Is it okay if I change the button to a link?

**Comment by SidharthBansal** [comment]
You can link the button to route.
You can open up a PR, we will help you in the PR.

**Comment by kunalvaswani123** [comment]
ok.. I guess this will take me time ..

**Comment by SidharthBansal** [comment]
No problem. Once you are done. Open up PR.
Thanks

**Comment by kevinzluo** [comment]
Thank you for combining the two forms. That makes my work in #3984 a lot easer 😄 . 
Testing this out, it seems to have broken the link in stable.publiclab.org/login, as when you click the signup button it doesn't work. Posting an issue now.

**Pull request merged**
