### PR TITLE
Changed the hyperlink text in Login/Signup Model

### PR DESCRIPTION
**Pull request by amilaneni99**
Issue Number #6360

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

This is the screenshot of the edited modal

### CODE REVIEW

**Comment by seabl** [comment]
@amilaneni99 Thank you for your PR. This is almost complete. Please modify the text to match with @ebarry's suggestion: "Forgot your password? Reset here." Refer to the first comment on #6360

**Comment by amilaneni99** [comment]
@seabl Can you please review it now. I have changed the text. Thanks.

**Comment by seabl** [comment]
@amilaneni99 A little bit of modification is still needed if you don't mind. Please change the first half of the message to match `Forgot your password?`

**Comment by amilaneni99** [comment]
@seabl Please check if it is okay now. Thanks.

**Comment by seabl** [comment]
@amilaneni99 Yes, it's ready now. It will be merged soon. In the meantime, feel free to look around and, if you feel like it, tackle any other issue. Thanks!

**Comment by seabl** [comment]
@jywarren ready to merge

**Comment by ebarry** [comment]
Thanks so much all!

**Comment by ebarry** [comment]
Is this ready to go? I'd love to close #6360

**Comment by cesswairimu** [comment]
Yeah looks ready... Pinging @jywarren to take a look when you get a minute. Thanks

**Comment by jywarren** [comment]
Looks awesome, thanks all! @cesswairimu you have merge rights now, yes? Rad! 🙌

**Comment by cesswairimu** [comment]
Wow cool. Thanks @jywarren

**Pull request merged**
