### PR TITLE
Add documentation for Question page

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

Add modal view for Q & A help documentation

### CODE REVIEW

**Comment by ananyo2012** [comment]
Here goes another one Jeff! Perhaps one of the last ones for my GSoC Project. Following @steviepubliclab's idea on documentation I have made some documentation changes in the Questions so that it will be easier for everyone to get acquainted with the Q & A system right from the website. I am posting the screenshots one by one.

**Comment by ananyo2012** [comment]
q_a_doc

**Comment by ananyo2012** [comment]
This is the modal view part by part
q_a_doc_1

**Comment by jywarren** [comment]
Wow, this is really great. I'd like to make some tweaks to the text on `/questions`, and I apologize for not responding earlier but I think it may be best to put the contents of the popup onto a wiki page. I really like it, though! If you resubmit without the popup, i'll do another commit on top before merging.

**Comment by ananyo2012** [comment]
@jywarren Then should I just create a new wiki page with the same content and just Put the link in the Question Page?

**Comment by jywarren** [comment]
That sounds perfect. This will keep long texts in the codebase to a minimum
(we're generally moving slowly towards the site being more generic, and all
Public Lab text being content, rather than code), and make it easier to
edit/update too. Thanks -- but feel free to take a break after that
excellent fix! I certainly will be; it's late here too.

**Comment by ananyo2012** [comment]
@jywarren I have made a new wiki page on Q & A pages. You can see it here: https://publiclab.org/wiki/public-lab-q-and-a. I have also updated this PR. It contains very few changes now. Feel free to change it as you think it is suitable.

**Comment by ananyo2012** [comment]
I have some more documentation in the sidebar of the Question editor.

**Comment by ananyo2012** [comment]
@jywarren This is ready. Can you have a look and change any documentation that may be required?

**Comment by jywarren** [comment]
Tweaked and merged!

**Pull request merged**
