### PR TITLE
Navbar render on 404 only '/' link - Fixes #1211

### LINKED ISSUE #1211: BUG: Header dropdown menus are broken on 404 error page
Visit any invalid route (e.g. https://publiclab.org/invalidroute). The 404 "That page does not exist" partial loads and the dropdown menus and search form break in Chrome 54.0 on macOS Sierra. I haven't tried this with another browser or OS.

### PR DESCRIPTION
**Pull request by meganft**
This is an initial render of a 404 page with the limited navbar, per issue Fixes #1211 
See screenshot for below for feedback/ideas, as I know this is still an issue that still needs decision making before any merging.   Thank you for taking a look and I welcome any feedback!

screen shot 2017-02-24 at 9 21 44 am

* [x ] all tests pass -- `rake test:all`
* [x ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ x] pull request is descriptively named with #number reference back to original issue

### CODE REVIEW

**Comment by jywarren** [comment]
This looks really good. I wonder if we should center the Public Lab too, to
further distinguish it from a regular header.

**Comment by jywarren** [comment]
If you could remove the Gemfile.lock changes and apply this to the other
error pages, I think we'd be good to go!

Thanks so much!

**Comment by meganft** [comment]
Sure! Do you want the header centered like this? Or the one above?

screen shot 2017-02-24 at 11 22 36 am

**Comment by jywarren** [comment]
That looks great, I'm happy with it! If you push up that change for all the error pages, I'll merge it in. Thanks!

**Comment by meganft** [comment]
Awesome, will do!

**Comment by ryzokuken** [comment]
@meganft Are you stuck on this or anything? Just making sure if you're working on this. Thanks.

**Comment by meganft** [comment]
Hi @ryzokuken ! No im not stuck, it's been finished for a few days per the recommendations. If there are any changes requested, I'm happy to do them, but I've completed work on this as far as I know.

**Comment by jywarren** [comment]
Hi, sorry, i think this is complete, indeed -- but I'd like to remove the changes to the Gemfile.lock. I can do that on Monday or if you can follow these recommendations to revert that file, I can merge it in sooner: http://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git#215731

Thank you and sorry I forgot to check back in!

**Comment by meganft** [comment]
No problem! I will def get this taken care of tomorrow!

**Comment by meganft** [comment]
The changes to Gemfile.lock should be all taken care of now!

**Comment by jywarren** [comment]
Hmm, that's odd -- something in the tests failed. that hadn't in the last commit. You can click `Details` to see what -- let me see ...

**Comment by jywarren** [comment]
Ah, ok, there's a timestamp mismatch. Some tests occasionally fail when they fall on the boundary between two milliseconds. I can fix that in a subsequent commit, but for now we should be able to re-run the test and it is unlikely to happen twice. An odd issue but not related to your code. Merging as soon as that finishes, thanks!

**Comment by jywarren** [comment]
Done -- and it passed. Thank you! 🎈 

If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

**Comment by meganft** [comment]
Glad I was able to help and thanks for being so responsive! I'll check out the other issues you linked!

**Pull request merged**
