### PR TITLE
(On Hold) Locale profile tags

### PR DESCRIPTION
**Pull request by jiteshjha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
- [x] All tests pass -- `rake test:all`
- [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
- [ ] pull request are descriptively named
- [ ] if possible, multiple commits squashed if they're smaller changes
- [ ] reviewed/confirmed/tested by another contributor or maintainer
- [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jiteshjha** [comment]
Note : As the code for locale profile tags is almost completed, this PR can be completed and accepted after subdomains are implemented.

**Comment by jywarren** [comment]
Great, just ping me when that happens!

**Comment by ryzokuken** [comment]
Hello! You must've noticed that the unit tests failed unexpectedly on your PR. This was due to some issue in the Travis CI testing configuration which was fixed by @jywarren later tonight. In order to make them work again, please rebase your work on top of the current master and then try pushing to your remote branch. Do this by:

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <my-branch>
$ git rebase master
$ git push origin <my-branch>
```

Thanks for bearing with us,
Ujjwal

**Comment by jywarren** [comment]
Closing this for now - we'll be re-opening UserTagging soon!

**Pull request closed without merging**
