### PR TITLE
Some modification to user dropdown menu on navbar

### LINKED ISSUE #2174: User dropdown menu in header
### Please describe the problem (or idea)
Currently when we click the user dropdown menu on header we have several options like Dashboard, Profile and more. 
But dashboard option shows even when we currently on the page https://publiclab.org/dashboard but instead of this we can have **home** option there and dashboard otherwise.

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Closes #2174 
* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
Now when we are at dashboard page:
screen shot 2018-01-31 at 1 17 23 am

On other pages :
screen shot 2018-01-31 at 1 18 23 am

**Comment by SidharthBansal** [comment]
Great Catch @namangupta01, I can't find why all your tests are failing. My recent pr's all tests are also failing but working fine on my local and passing all test cases on my local

**Comment by ViditChitkara** [comment]
@SidharthBansal The tests were failing for me too and with the same error yours!! Perhaps re-running travis should solve the problem!! Maybe try and add a minor commit so that travis starts again and see if it works.

**Comment by SidharthBansal** [comment]
Yeah by running Travis Tests again it must disappear. Once I had this issue, @jywarren did reopen the pr after closing and then all tests got passed

**Comment by SidharthBansal** [comment]
I did the same for this hope here also, all tests will pass.

**Comment by jywarren** [comment]
Looks great. Thanks folks, esp. for the troubleshooting!!!

**Pull request merged**
