### PR TITLE
Updates made to h2 tags

### PR DESCRIPTION
**Pull request by pawan-nirpal-031**
Newbie updates and fixes.

### CODE REVIEW

**Comment by pawan-nirpal-031** [comment]
Feel like I am getting hold of this already.

**Comment by coder645** [comment]
Hey @pawan-nirpal-031 it's nice to see you contributing. 
But please don't make so many spam PRs. It would be great if you could select one issue at a time and make a PR for it.
Cheers!

**Comment by coder645** [comment]
Also, please mention the issue number in each PR.
Cheers!

**Comment by pawan-nirpal-031** [comment]
@coder645  Thanks for correcting me already, I am just getting started with open source contribution, I am getting this as I go, and my apologies if I did things I shouldn't do, I'll be careful with issue number and such, thanks again for correcting me.

**Comment by coder645** [comment]
@pawan-nirpal-031 another suggestion, please don't make a PR for issues that others have claimed or have already made a PR for. Because here we will assign those who comment first.
So please check the comments of an issue to check whether someone has said they want to work on.

**Comment by pawan-nirpal-031** [comment]
> @pawan-nirpal-031 another suggestion, please don't make a PR for issues that others have claimed or have already made a PR for. Because here we will assign those who comment first.
> So please check the comments of an issue to check whether someone has said they want to work on.

@coder645 Even if the code changes are different I mean the implementation is different still that PR won't be approved ?, I am new with this so please guide me with this.

**Comment by coder645** [comment]
> > @pawan-nirpal-031 another suggestion, please don't make a PR for issues that others have claimed or have already made a PR for. Because here we will assign those who comment first.
> > So please check the comments of an issue to check whether someone has said they want to work on.
> 
> @coder645 Even if the code changes are different I mean the implementation is different still that PR won't be approved ?, I am new with this so please guide me with this.

@pawan-nirpal-031 what do you mean by implementation? :laughing: 
You've just made changes suggested by Ruth right? PRs made by others also have the same changes. So just want to reiterate that the PR made earlier or by the person who's claimed it first will be approved.
Cheers!

**Comment by cesswairimu** [comment]
Hi @pawan-nirpal-031...this changes are not required and will not work with our current code base...please feel free to ping me if you need help getting finding a  valid issue to work on...we noirmally work on issues listed here https://github.com/publiclab/plots2/issues only. Closing this for now. Thanks

**Pull request closed without merging**
