### PR TITLE
Changed _like.html.erb

### LINKED ISSUE #10088: Add margin to flag button in tools section
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

Add margin top to flag button

Screenshot 2021-08-24 at 15 13 34

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file `app/views/like/_like.html.erb` in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -49,11 +49,13 @@
     <% end %>
 
     <span data-toggle="tooltip" data-placement="top" title="Tools" id="menu-btn" class="btn btn-outline-secondary btn-circle btn-sm" rel="popover" data-placement="left" data-html="true" style="overflow: auto; max-height: 500px" data-content="
-        <p><b>Users who liked this</b></p>
-        <% node.likers.each do |user| %>
-            <i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>/'><%= user.username %></a><br />
-        <% end %>
-        <% if node.likers.size == 0 %><i>None</i><% end %>
+        <div class='mb-3'>
+            <p><b>Users who liked this</b></p>
+            <% node.likers.each do |user| %>
+                <i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>/'><%= user.username %></a><br />
+            <% end %>
+            <% if node.likers.size == 0 %><i>None</i><% end %>
+        </div>
         <% if node.type == 'note' && current_user && node.uid != current_user.uid%>
             <hr style='margin-bottom:3px;' />
             <p><b>Award a Barnstar:</b></p>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by arnab-2001**
Fixes #10088  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
@arnab-2001 Could you add a screenshot of the UI change? Great work!

**Comment by arnab-2001** [comment]
Sure @TildaDares doing it right away

**Comment by arnab-2001** [comment]
Actually, I am new to this can you please help me with how can I add the screenshot of the UI change?
@TildaDares

**Comment by TildaDares** [comment]
@arnab-2001 Sure. Is your local env setup?

**Comment by arnab-2001** [comment]
Yea @TildaDares

**Comment by TildaDares** [comment]
@arnab-2001 Start up the rails server and then visit any note page

**Comment by arnab-2001** [comment]
ok doing @TildaDares

**Comment by TildaDares** [comment]
@arnab-2001 Have you done that?

**Comment by arnab-2001** [comment]
Yes I am doing just need few min more

**Comment by arnab-2001** [comment]
Yes, I did it what to do next?

**Comment by TildaDares** [comment]
Look for the `Tools` button and open it. Take a screenshot of that section

**Comment by arnab-2001** [comment]
Alright

**Comment by arnab-2001** [comment]
hey @TildaDares  I am facing some issues while running the ruby server can you point some resources ?

**Comment by TildaDares** [comment]
What kind of issues?

**Comment by arnab-2001** [comment]
when I am trying to run the Redis server it's not getting started rather it's raising an error, but the Redis CLI is working absolutely fine

**Comment by TildaDares** [comment]
Did you follow all of the steps here? https://github.com/publiclab/plots2#standard-installation

**Comment by arnab-2001** [comment]
Yes but while running rvm it's raising an error saying no commands found,

**Comment by arnab-2001** [comment]
but I was able to install Redis but only rvm is not getting installed

**Comment by TildaDares** [comment]
I don't think you need to install Redis

**Comment by arnab-2001** [comment]
ok then 
But I am unable to install rvm

**Comment by TildaDares** [comment]
If you have Ruby installed, then you should have rbenv or rvm installed too

**Comment by arnab-2001** [comment]
It's saying unable to locate package rvm

**Comment by arnab-2001** [comment]
Exactly @TildaDares There only I am getting stuck

**Comment by TildaDares** [comment]
What command did you enter that returned that error?

**Comment by arnab-2001** [comment]
rvm install 2.6.6

**Comment by TildaDares** [comment]
Do you use rvm or rbenv?

**Comment by arnab-2001** [comment]
rvm

**Comment by TildaDares** [comment]
Check if you have rvm installed?

**Comment by arnab-2001** [comment]
rvm 1.29.12 (manual)
it's showing this while running rvm -v
@TildaDares

**Comment by TildaDares** [comment]
I'm not sure I know how to deal with this issue. Don't worry about the screenshot, I'll add that myself. Thanks @arnab-2001

**Comment by Tlazypanda** [comment]
Hey @arnab-2001 have you installed the sql dev library? please check this out Thanks :) - 
https://stackoverflow.com/questions/45474191/an-error-occurred-while-installing-mysql2-0-4-8-and-bundler-cannot-continue

**Comment by Tlazypanda** [comment]
Hmm ...did you try the other steps listed in the above link? like  `sudo apt-get install libssl-dev` or `sudo apt-get install default-libmysqlclient-dev`
Also can you share the output of `gem list` If you are still facing the issue it might be worthwhile to open a fresh issue for this to help us debug. Thank you!

**Review by noi5e — APPROVED** [review]
Since the files changed matches what was required in the original FTO, and the change is small enough that it can be corrected in another PR, or reverted... I am going to go ahead and merge this one.

@arnab-2001 thanks so much for this PR, and I'm sorry you're running into so many config issues! We're happy to help you figure things out, feel free to ask for help in our Gitter channel.

**Pull request merged**
