### PR TITLE
wip: add print preview template

### LINKED ISSUE #8128: Print specific template for public lab content
**Please describe the desired behavior.**
Currently the publiclab website uses a set of css hiding strategies to only print important content from a note or wiki. We need to replace this with print specific template for public lab content. 

This print specific template can make use of js manipulation to only pull important part of content from the note and add css styling accordingly.

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #8128 

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
Hey @jywarren @cesswairimu can you kindly review? Thanks :v: I am not sure what all to check for in the tests so some pointers there would be useful :sweat_smile:

**Comment by cesswairimu** [comment]
@Tlazypanda is it possibleto get a gif for this?  Thanks

**Comment by Tlazypanda** [comment]
@cesswairimu @jywarren  Yeah sure! :+1: also I was thinking that can we push this first on unstable and test it out since I am not sure how it will perform with some specific scenarios I have tried with tables/blockquotes/code block/images/videos but still there will be many more to be tested out :sweat_smile: Also I just have added an option to the sidebar print options called "new print" without removing the other options for now since this is still in testing :sweat_smile: 

Note Gif 

note_print

**Comment by jywarren** [comment]
This looks super. Is it possible to hide the navbar too? I think we could either use a conditional, OR possibly we could pull out all the assets into their own partial and include only them, rendering this page with `render layout: false` (i think?)

Thank you, @Tlazypanda !!!

**Pull request merged**
