### PR TITLE
Implementing Inline commenting #1438

### PR DESCRIPTION
**Pull request by aspriya**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, @ananyo2012, did the dangerbot crash here?

**Comment by aspriya** [comment]
Hmm, fails again. travis log says I have a pending migration and should run `rake db:migrate` which I have done locally.  So what may be the issue here?

**Comment by jywarren** [comment]
Ah, you have to update the schema.rb.example with the new table and timestamp. Take a look at past updates to this file here:

https://github.com/publiclab/plots2/blame/master/db/schema.rb.example

**Comment by ananyo2012** [comment]
@aspriya Can you label this WIP if it is Work in Progress ?

**Comment by ananyo2012** [comment]
@jywarren Hmm the danger bot is showing some unusual behavior. The warning shoudn't have come after both schema and migrations are added.

**Comment by aspriya** [comment]
@ananyo2012, It's not a WIP progres. Thought of sending other parts in seperate PRs.

**Comment by ananyo2012** [comment]
Well I suggest you to make a PR for one feature. Just the migration doesn't justify its use.

**Comment by jywarren** [comment]
How are you doing on this? Getting ready to merge? Stuck on anything?

**Comment by aspriya** [comment]
Yes, I'm almost there. Now the inline comment form is submitable. Will update the PR with that commit also.

**Comment by aspriya** [comment]
And now I'm finding a way to show the entered inline comments

**Comment by jywarren** [comment]
Be sure to keep this updated - rebased on the latest master branch - to avoid merge conflicts! Great to see your work on it!

**Comment by jywarren** [comment]
How are things going here? Thanks!

**Comment by aspriya** [comment]
Hi @jywarren, things are working well. I hoping to record a video on how things work in here and share the link here.

**Comment by ananyo2012** [comment]
@aspriya Good job! Is this ready ? You can make a research note at https://publiclab.org/post to showcase your Work.

**Comment by aspriya** [comment]
@jywarren and @ananyo2012, Following link is a video discription for the things I have implemented above.

**Comment by aspriya** [comment]
@ananyo2012, yes I think this is good to go and I'm writing a research note about this feature to introduce it. Thanks

**Comment by jywarren** [comment]
@icarito can we test this on the new `unstable` branch to see how it works? Would you mind deploying it over there? Thanks!

**Comment by icarito** [comment]
Okay I missed this but let's push this to unstable and see how it goes.

**Comment by jywarren** [comment]
Whoa i didn't know you could switch branches in GitHub... so we'd open a new one to merge to master if this works? Thanks!

**Comment by jywarren** [comment]
And what is the link for unstable's instance? so we can try it out?

**Comment by jywarren** [comment]
Hm, next time maybe we should update stable from master first, because this PR now includes Aspriya's changes plus all previous PRs back to the last time stable was synced from master. That's OK -- i can open a new PR with the original intent? 

@aspriya -- you can still push to this feature branch, so that's fine. Can you think about writing functional tests for `create_inline_comment` and `inline_comments` in the comment controller?

**Comment by jywarren** [comment]
@icarito shall we open a new PR for the original => master merge, or can this one be switched back now that unstable is updated?

**Comment by aspriya** [comment]
@jywarren, sure I will start writing tests for those. Thanks :smiley:

**Comment by icarito** [comment]
Guys earlier today I went ahead and merged this into `unstable` branch from the Github interface. A few minutes later, voilá: http://unstable.publiclab.org/
I did not have to intervene.
The build log is at http://jenkins.laboratoriopublico.org/job/Plots-Unstable/lastBuild/ including the migration.
Hope it's useful!

**Comment by jywarren** [comment]
oh cool! But it's now 502... did it go down after a bit?

**Comment by icarito** [comment]
We're experimenting as you can see. I looked at the interface on Github
and I don't see an option because it's already resolved (merged). So I
guess a new PR is needed.

By the way the option to rebase the PR was hidden under the "EDIT" link
that is visible to change the PR title. I'll add a screenshot.

**Comment by icarito** [comment]
image

**Comment by icarito** [comment]
See the pull-down menu to pick the base under the editbox

**Comment by icarito** [comment]
Whoa, I don't know, I'll check the logs. We should publish the logs for
staging maybe thru jenkins.

**Comment by icarito** [comment]
And also change the 502 error with something useful such as the link to
the respective jenkins build queue.

**Comment by icarito** [comment]
I don't know! there was nothing obvious in the logs. I've restarted it
manually. Let's monitor it.

**Comment by jywarren** [comment]
Great -- @aspriya, can you test this out at
http://unstable.publiclab.org/wiki/kits?raw=true ?

**Comment by jywarren** [comment]
remember you'll have to log in

**Comment by jywarren** [comment]
I was able to open an inline comment box, but nothing happened when I pressed publish. 

Should the button become "depressed" like in the regular comment box?

Also, instead of the page title appearing in the inline comment box, maybe just "Comment"?

Looking good though!

**Comment by jywarren** [comment]
And yes, @aspriya, please open a new PR - though it can be from the same branch!

**Comment by ananyo2012** [comment]
I tested this too. There must be some error in submission as I too don't see the comment being published when I publish the comment button. Also I see when I try to edit the line in inline-markdown-editor the line is not updated immediately. I see it updated only when I refresh the page. The Ajax style implementation is not working.

**Comment by jywarren** [comment]
Any updates, Ashan? Thanks!

**Comment by aspriya** [comment]
@jywarren and @ananyo, Yes there seems to be a problem. But If you wait
about one minute after pressing the `publish` button, the comment get
submitted. But in my local machine all works fine. may be it's slow because
this is staging server?

As @jywarren stated, yes having the title of the form only as `Comment`
seems enough

Following is a inline comment I added to staging server. I waited about 1
min after pressing the publish button.

[image: Inline image 1]

**Comment by jywarren** [comment]
Hm, ok - (also you can't upload images by email but only on Github.com)

@icarito is unstable really quite slow and might this be working but really slowly? Is there any way to improve responsiveness on unstable? I've noticed slowness myself.

**Comment by icarito** [comment]
Just saw your message, I'll check it out. Perhaps we should expose app
logging from staging / unstable.

**Pull request merged**
