### PR TITLE
 update_issue_#11009

### PR DESCRIPTION
**Pull request by ayish1998**
Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by ayish1998** [comment]
@TildaDares please check if this is what is expected of me?

**Comment by ayish1998** [comment]
@TildaDares waiting for a review

**Review by TildaDares — APPROVED** [review]
Thank you @ayish1998 for sticking with this.

**Comment by TildaDares** [comment]
Congratulations @ayish1998🎉

**Comment by TildaDares** [comment]
Congratulations @ayish1998🎉

**Comment by TildaDares** [comment]
Congratulations @ayish1998🎉

**Comment by ayish1998** [comment]
Thank you @TildaDares for the guidance

**Pull request merged**
