### PR TITLE
Implement style guide

### LINKED ISSUE #1994: Implement Style Guide
I saw `rubocop` added in `development` group. I think it'll be a good idea to actually add it to to travis too so non-conforming PRs won't pass. In the mean time I'll go ahead and start the implementation first to put things in order. This will take some time. @jywarren

### PR DESCRIPTION
**Pull request by siaw23**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

Fixes #1994

### CODE REVIEW

**Comment by jywarren** [comment]
Cool! Can you share some of the kinds of alerts it's showing? @ryzokuken what do you think of this? 

Thanks!

**Comment by siaw23** [comment]
So an example warning is this:

```
test/functional/editor_controller_test.rb:89:9: C: Layout/AlignParameters: Use one level of indentation for parameters following the first line of a multi-line method call.
        tags: 'question:question', ...
```

and when we navigate to the offending part of the code we see double indentation. Fix is simple, make a single indentation.

**Comment by siaw23** [comment]
I don't see anyone having problems with this as these are mostly easy fixes. @jywarren

**Comment by ryzokuken** [comment]
This looks great! Any reasons we're specifically using Shopify's config?

**Comment by siaw23** [comment]
No reason using Shopify's config. they just have a good collection of the rules in one place. easier to get things done and started.

**Comment by ryzokuken** [comment]
That does sound fair. That said, do take a look into other good organizations who use Rails (GitHub, Basecamp etc.)

Perhaps there's a better alternative available?

**Comment by siaw23** [comment]
The others use them same style guide basically. it's a style guide from the Ruby community. It's the same everywhere, of course with customisations to suit preferences.

**Comment by ryzokuken** [comment]
If that's true, then that's awesome! I think we're good to go with this then.

**Comment by siaw23** [comment]
@jywarren are we good to go now? :)

**Comment by siaw23** [comment]
I can also divide some of the offences into pieces for first-timers to fix after we're done with this one. I think they are easy enough to encourage contribution while tidying up. @jywarren

**Comment by ryzokuken** [comment]
@siaw23 sounds like the perfect thing to do! Go ahead and make a few first timer issues guiding people over cleaning up the linter warnings and errors. Also, I think we should maintain a number of the number of linter issues (especially in the current master somewhere). That will help us review the progress we're making in tackling these issues as well as make sure that no new PR introduces more of these.

Once all of them have been taken care of (which is going to take a lot of time in itself), we could add linting to Travis and make sure nobody pushes unlinted code. This would be really helpful for newer people and will also improve the overall readability and legibility of the codebase.

**Comment by jywarren** [comment]
Yes, can we think of any way to generate a list of 2-3 style fixes from the linter, and create a first timers issue (semi-)automatically from them? Or jsut a template that some of the linting messages can be pasted into? FTO issues are written like this: https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors

One important part is how you can use a link like this:

`https://github.com/publiclab/plots2/blob/d342ad68caab7649991628380a5ba7e050ab91a9/app/controllers/questions_controller.rb#L4-L8`

To show a section of code that could/should be fixed -- this is really helpful for first-timers!

https://github.com/publiclab/plots2/blob/d342ad68caab7649991628380a5ba7e050ab91a9/app/controllers/questions_controller.rb#L4-L8

That would be the ideal, do you think it's possible?

**Comment by ryzokuken** [comment]
@jywarren judging by the sheer amount of the errors and warnings, I think the best course of action would be to spin up a simple ruby/python script that parses the output of the command and breaks it up into a few issues and then posts them online. We should put up a few such issues at a time to avoid flooding our GitHub, and then once majority of them are taken care of, post some more.

Just a wild thought, but what if I integrate this functionality into plotsbot instead? So, instead of executing a command and then possibly posting a bunch of stuff on GitHub every once a while, you and a few authorized others could just say 'plotsbot, lint' and it would lint the codebase afresh and make a few issues.

What do you think? Let me know.
Also, I wanted to talk to you regarding plotsbot, were you free today?

**Comment by jywarren** [comment]
That would be a cool option, indeed -- you could use this template, for
example:
https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md

I don't think i'll have a moment today to talk about plotsbot, but if you
can post an issue with your topics, i can write back between meetings -- or
perhaps meet tomorrow or friday! Thanks!

**Pull request merged**
