### PR TITLE
Adding main card tag to the individual tags page

### LINKED ISSUE #5890: UI Improvements Planning Issue : Individual tags page
Next we start with the implementation of individual tags page. 

Capture

**Checklist**

- [x] Divide the page into three sections(Main image and the introduction card, sidebar with map, activity cards) @gautamig54 
- [x] Adjust the main image and add the number of people following on to the right. @CleverFool77 
- [x] make an introduction card for the tag containing the subscribe and learn more options. @gautamig54 
- [x] Activity cards with new design of style guide @CleverFool77 
- [ ] ~Show map on the sidebar and people near options @gautamig54~
- [ ] Sort by name, users and people following  @CleverFool77  **Wait a bit**
- [ ] ~Post a question option with dropdown @gautamig54~
- [x] Implement type dropdown containing options for all, questions, wikis and notes related to the tag. @CleverFool77 
- [x] Add related tags @gautamig54 

cc : @CleverFool77

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5890  (<=== Add issue number here)

Screen Shot 2019-06-22 at 10 59 14 AM

Screen Shot 2019-06-22 at 10 59 23 AM

Mobile view : 

Screen Shot 2019-06-22 at 11 00 13 AM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
@CleverFool77 @jywarren Kindly have a look here. 
Minor tweeks remaining for the mobile view I guess.

**Comment by jywarren** [comment]
Looks fantastic! Here's the auto-generated screenshot too:

image

I was thinking the "Add one now" button doesn't seem clearly linked to the above statement 'has no wiki page'. Would it work better simply as a text link at the end of the sentence "has no wiki page"?

Also, the `...` menu may be better in the true upper right corner of the box. Is there a way to do that in the mobile view? 

Can the `Subscribe` button text be white?

Under `Learn more >>` - you can use this character: » -- which can be generated with the HTML special code `&raquo;`. 

What happens with a really long title? Does it wrap nicely?

**Comment by gautamig54** [comment]
Thanks @jywarren for your feedback. I'll make the suggested changes!

**Comment by gautamig54** [comment]
Instead of "Add one now" can we change the text saying, "add a wiki page" or something like this?

**Comment by gautamig54** [comment]
@jywarren I made the said changes. Have a look at these. Thanks!

Screen Shot 2019-06-26 at 1 50 34 PM

Screen Shot 2019-06-26 at 1 50 54 PM

**Comment by jywarren** [comment]
This looks great! Ready for a merge now?!

**Comment by gautamig54** [comment]
Yes @jywarren! I think it is ready for merge. Any feedbacks @CleverFool77 ?

**Comment by jywarren** [comment]
I thought about that but I think it's nice to see the image. Can we say
that if there is no image, then it does overlap, but if there is an image
we do?

Thanks!!! Good catch!

**Comment by CleverFool77** [comment]
It does makes sense. We can have main card overlap when there is no wiki page or wiki page doesn't have an image.

**Comment by gautamig54** [comment]
I will then implement this, that if there is no wiki image, then we can overlap the tag card.

**Comment by gautamig54** [comment]
I had a doubt. With the image, we are also showing the number of people discussing the topic. That will also be overwritten. 
Should we just leave it like this for now?

**Comment by jywarren** [comment]
Hmm. What if we make the number move to upper right corner for mobile size?
Is that weird?

**Comment by gautamig54** [comment]
I think that might be a bit weird. @CleverFool77 What do you think?

**Comment by CleverFool77** [comment]
I can't say it exactly regarding position gautami. How about having a a mockup first. Then only we can decide maybe.

**Comment by gautamig54** [comment]
@jywarren I am not able to understand how to move the number in the upper right corner. Can you help us with a mock up?
Also, I was thinking if we can have the number on the main card itself instead in the bottom right corner of the image. In that case this issue can easily be handled?

**Comment by CleverFool77** [comment]
Hi gautami,
Regarding that, you can set the position of div having people following as per the screen size.
Eg - in less than medium, it would be at different position. Like this.

**Comment by CleverFool77** [comment]
And another way is to play with Bootstrap4 visibility feature. You can do this through this too.
Have it visible at one position in one kind of screens and another position at different screen.

**Comment by jywarren** [comment]
I just merged https://github.com/publiclab/plots2/pull/5948, so we can do this next if it's ready? Thanks all, this is very exciting!!!

**Comment by jywarren** [comment]
I'm going to merge this as a short term solution and we can continue refining as you're discussing in a follow-up. That way we get to look at the whole tag page completed now!

**Comment by jywarren** [comment]
Coming up soon at http://stable.publiclab.org!!!

**Pull request merged**
