### PR TITLE
letter_opener gem is added

### LINKED ISSUE #1746: Mail catching gem
It would be easy to check mails if we have something that can easily access the mails. One such gem is letter_opener it will open the mail in new tab in development mode. For example it would be easy to reset password in development mode as one new tab will open with the reset password link and many more.

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Fixes #1746 
* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
Here the example of how its look now for reset password :

screen shot 2017-10-31 at 4 57 54 am

**Comment by namangupta01** [comment]
@jywarren Can you please have a look at this. Thanks :)

**Comment by jywarren** [comment]
Hi, my deepest apologies for slow response; we've been running an event and then I had 2 weeks of travel... I'm way behind but your contribution is so great -- thank you!!! 

So, how do we access the emails in the browser? Would you be able to write a couple sentences of guidance in the README or in `/docs/TESTING.md` on how to read email templates in the browser? I'm just not sure what the URLs would be. Does it just open a new browser window? And what if it sends like 20 emails, would it open 20 windows? 

Thank you!!!

**Comment by namangupta01** [comment]
Hey.
Whenever a email is sent then it will automatically catch by letter_opener and it will open in new window in development enviroment, nothing is to be done to run it, it will be done automatically.
Same links would work, no modification in links are required. 
It will also show us how our actual mail will look like.
It is same as actual mail.
Yes if 20 mails are sent then it will open 20 windows. But there is another gem that we can use instead of this which will open all the 20 mails in one tab just like gmail but using that gem is bit more complicated because for that gem we have to start a smtp server first where nothing is to be done for letter opener gem

**Comment by jywarren** [comment]
OK, if you could add a line to /docs/TESTING.md with the above text I can
go ahead and merge this, thank you!!!

**Comment by namangupta01** [comment]
sure 👍

**Comment by namangupta01** [comment]
@jywarren Its done have a look!

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Pull request merged**
