### PR TITLE
Updated lines 26,32, and 33 from t(...) to translations(...)

### LINKED ISSUE #6206: Create "first-timers-only" issues for newcomers 👋
(This issue is in continuation of https://github.com/publiclab/plots2/issues/4963)

Hi everyone!

We, at Public Lab, are known for welcoming new contributors into the Open Source world but a number of times, newcomers were not able to find `first-timers-only` issues to start their journey or face troubles making their first contribution with us. 

Reasons being:
1. Lack of `first-timers-only` issues
2. Struggle in finding the good issue to start and lack of enough support?

We are working on both of the above aspects to support and help the maximum number of people to take their first step in their OSS journey with us, through our various [projects](https://github.com/publiclab/) but we need more support for this. So, this is a call to all the Public Lab members to try and create a first-timers-issue for someone who wants to start their journey and waiting for an FTO being assigned to them.

**If you are interested in creating `first-timers-only` issue, follow these instructions:**
1. Browse through the publiclab.org and see if there's a bug which can be easily solved
2. Solve this issue but don't create a PR this time, instead create a FTO issue
3. Click on this [link](https://github.com/publiclab/plots2/issues/new) to start creating a new issue
4. We follow a specific template for FTO issues, so copy the template from [here](https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md) 
5. Edit the issue body to add the goal of the issue, code snippet required, file to be updated, add screenshots(if required). Don't add code snippet required to solve in case, the issue just requires minor HTML or CSS change or equivalent.
6. Add a catchy and relevant title to the issue but don't include "FTO" , "first-timers-only" or equivalent in title
7. Get the issue you just created labeled by mentioning @publiclab/reviewers or @publiclab/plots2-reviewers. 
- If you have labeling privileges, feel free to do so yourself but ensure that you have used FTO template. 
- If you are not able to mention the above-mentioned teams, and doesn't have labeling privileges, then drop a line in Gitter channel - https://gitter.im/publiclab/publiclab or mention @jywarren @gauravano @SidharthBansal and any one of us will surely follow-up with you. You can also mention any other member, you can think of with labeling privileges.
8. It's time to invite a new contributor to your issue. If there are unchecked names in the below list, then those people are still looking for FTO issue to start with, so mention them in your FTO by writing - `This issue is created for @[contributor-name]. Thanks!` 
Also, if you see, a new contributor is looking for an issue, feel free to point them to your FTO. 

### Contributors looking for `first-timers-only` (FTO) issues

- [x] @tauhir - #6359
- [x] @augustozanellato - https://github.com/publiclab/leaflet-environmental-layers/issues/238
- [x] @nstjean -https://github.com/publiclab/mapknitter/issues/1050
- [x] @stefanosu - https://github.com/publiclab/mapknitter/issues/1057
- [x] @alexido19 - https://github.com/publiclab/mapknitter/issues/1065
- [x] @Akashutreja - https://github.com/publiclab/mapknitter/issues/1066
- [x] @fadib - https://github.com/publiclab/mapknitter/issues/1067
- [x] @skai-ste - https://github.com/publiclab/plots2/issues/5047
- [x] @mahimahans111 - https://github.com/publiclab/plots2/issues/5215
- [x] @Lisa-Caton - https://github.com/publiclab/plots2/issues/5795
- [x] @pkayres - https://github.com/publiclab/plots2/issues/5137
- [x] @jeffogah - https://github.com/publiclab/plots2/issues/6080
- [x] @IvetaHron - https://github.com/publiclab/plots2/issues/6440
- [x] @Linda-Ikechukwu - https://github.com/publiclab/plots2/issues/5191
- [x] @crisner
- [x] @vishakhanihore - https://github.com/publiclab/plots2/issues/6444
- [x] @shailzaa
- [x] @saivoleti17 - https://github.com/publiclab/mapknitter/issues/1086
- [x] @chrisnorwood - https://github.com/publiclab/plots2/issues/6461
- [ ] @DanielKlys7
- [x] @Diegoafv - https://github.com/publiclab/mapknitter/issues/1094
- [x] @saramace
- [x] @lojosmit 
- [x] @kyebrowning
- [x] @jon-flores - https://github.com/publiclab/mapknitter/issues/1098
- [x] @textuallyactive
- [x] @Lafexlos
- [x] @anushtha1011
- [x] @ChamuMutezva
- [x] @anikerr
- [x] @megha070
- [x] @yagosansz
- [x] @aman-k334
- [x] @saivoleti17
- [x] @Him010
- [x] @aisayo
- [x] @boolean5
- [ ] @reginareynolds
- [x] @ivaibhavkr
- [ ] @satcasm
- [ ]  @preetiy 
- [ ]  @sap143
- [ ] @rojasTob 
- [ ] @giantthinker
- [ ] @AxelleDRouge
- [ ] @RaquelFilipaMendes
- [ ] @avinash080 
- [ ] @aviveller
- [ ] @AudreySchmook
- [ ] @ahrocha96 
- [ ] @jayg98 
- [x] @YuetChan 
- [ ] @infy815
- [ ] @MarieSell 
- [ ] @nyjackson
- [ ] @Thebohemiangeek 
- [ ] @loranazarenko 
- [ ] @mehnazyunus 
- [ ] @starkah 
- [ ] @jaywahr 
- [ ] @govgoel 
- [ ] @Anjalizi 
- [ ] @anuk79
- [ ] @ajitsinghkaler
- [] @puneeth2001

**To first-time contributors:** If you are looking for FTO and want your name to be added to the above list then, feel free to comment below to show your interest. If you are looking for working on a specific language/framework, mention that too in your comment.

**To Public Lab members who have comment edit privileges:** Please add names of newcomers who have shown into for FTO in the below comments. Also, add the names of other newcomers who are looking for FTO and shown their interest by commenting on other issues.

For any query, feel free to ask below or at Public Lab Gitter channel - https://gitter.im/publiclab/publiclab

Thank you and welcome to Public Lab 🎈😄

### PR DESCRIPTION
**Pull request by yagosansz**
Fixes #6206  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updation
* [X] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by yagosansz** [comment]
Hi,
What did I do wrong and how can I fix it?

**Comment by SidharthBansal** [comment]
There are some conflicts. Kindly remove them
Thanks for your work

**Comment by SidharthBansal** [comment]
Please provide screenshots for your changes

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
