### PR TITLE
Edit PR template to include original issue labeling checkbox

### PR DESCRIPTION
**Pull request by seafr**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by seafr** [comment]
Kind of related to #2422

**Comment by jywarren** [comment]
This is good, but unfortunately only project collaborators (like reviewers) can add labels. This is a tough limitation of GitHub, and projects like GitMate have tried to get around this with bots. So there may be some options...

we could have Danger scan... comments? can it do that? and add a label maybe?

http://danger.systems/ruby/

**Comment by jywarren** [comment]
@seafr - I wanted to ask, any interest in being a summer of code mentor? Or have you submitted a proposal, I didn't think I saw one but you've been so helpful in general I wondered if you're interested in being part of the program. Thanks!

**Comment by seafr** [comment]
@jywarren thank you for the kind words. But to be honest I think this is beyond my abilities. I'm very new to OSS. However, I'll be around and see if I can be of any help. Thanks for asking.

**Comment by jywarren** [comment]
I'm going to close this for now but open a new issue about how we might address it. Thanks!

**Pull request closed without merging**
