### PR TITLE
Added an I did this comment pop-up

### LINKED ISSUE #4093: Make "I did this" button open a comment form for faster posting
We have an "i did this" button which appears at the end of activity posts (learn more at https://publiclab.org/activities)

image

But it prompts you to make a whole new post. Let's make this easier by starting with a comment prepopulated with `I did this!` and asking people to post a photo if they like. If they want to follow up with more detail, notes, ideas, etc, we can follow up later -- in fact we already do at the bottom of each comment on an activity: 

image

Maybe it could pop open a comment window right there, like this:

image

The comment form could go right on this line:

https://github.com/publiclab/plots2/blob/master/app/views/notes/_responses.html.erb#L29

It could be included with this code:

```ruby
      <%= render :partial => "comments/form", :locals => { title: 'Add feedback, suggestions, or photos
', body: 'I did this!', comment: false } %>
``` 

This line will also have to be changed to preserve the "i did this" text: 

https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb#L18

It should be `body = body || params[:body]`

The newly inserted form should be in a `<div class="activity-comment">` with style `display:none;` and the `I did this` button should now run `$('.activity-comment').show();` when clicked. That'll make the new comment area show only when you click the button.

Finally, we could run `$('.activity-comment textarea').focus()` to activate the text area so you can start typing. 

This may require some testing to ensure the Preview button still works, but we can help you out with that when the time comes. We'd love help with this one!

### PR DESCRIPTION
**Pull request by okonek**
Fixes #4093 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

button

### CODE REVIEW

**Comment by okonek** [comment]
Now it should be all good.

**Comment by okonek** [comment]
@gauravano @jywarren Review please.

**Comment by jywarren** [comment]
This looks great, and wonderful Gif!

Have you checked around a bit to ensure all other comment forms still work normally, whether on this page or on a questions page, or even the comments tab on a wiki page? Our JavaScript is less tested than our Ruby, so just want to be sure about this before merging. Great work!

Eventually we should have a full JavaScript API for posting a comment, rather than mixing the UI and posting code. Could be a good follow-up if you're interested!

**Comment by okonek** [comment]
Yes, I've tested the other forms and they work normally. You can test it yourself if you want but I don't think there is need to.

**Comment by okonek** [comment]
Can we accept it?

**Comment by dinaelhanan** [comment]
@okonek be sure to tag them so they see it next time! @jywarren @namangupta01 @publiclab/reviewers

**Comment by jywarren** [comment]
Great, thank you - just a note on the timing, this is morning for me here, so often you won't hear from me overnight (got to sleep sometimes! 💤 ) -- thanks!

This looks great; merging it now!

**Comment by okonek** [comment]
Ok, thank you very much. I'll try to not be so insistent

**Comment by jywarren** [comment]
No problem, thanks! Left you a note at #786 which would be a cool next step; and your code from this PR is live at PublicLab.org, by the way!

**Pull request merged**
