### PR TITLE
Fix Icons (Google Code-In)

### PR DESCRIPTION
**Pull request by jmliu1417**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jmliu1417** [comment]
@publiclab/reviewers Is there any way I can authorize the merge for this pull request? The branch is protected.

**Comment by kevinzluo** [comment]
Hello fellow GCI participant! 😄 
Could you please add the issue number for your pull request first? That way the reviewers have a better idea of what you are fixing.
Also, I don't think we are supposed to merge the pull requests ourselves. Instead, after it is reviewed and approved, one of the members will merge it instead.

**Comment by jmliu1417** [comment]
Hello @kevinzluo!
 I don't think there is an issue number but I really appreciate your comment.

**Comment by shivani-kapania** [comment]
Hi, @jmliu1417 the issue number is #3328. Can you share please share before and after screenshots?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing at Public Lab

**Pull request closed without merging**
