### PR TITLE
Add modal to Add activity + secondary link

### LINKED ISSUE #4161: Link Login Modal to add an activity
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to add an activity 
image

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #4161  

I saw that most of the other PRs did this ( `<% if current_user %>` ) to check if it was a current user, but for some reason that did not work in my case (I am not that familiar with rails :disappointed: so I don't know why).

image

So this fix is implemented in Javascript.
To redirect to the correct page, an AJAX request is sent to the page that should be loaded after login. Here are the results:

My fix _would_ also work for the questions grid, but I cannot set the request path to the second link because it is actually accessible by non-users. 

Basic Flow For Button:
addactivitybasic

Basic Flow for second link:
addactivity2basic

Alternative Flow for Button:
addactivityalternate

Alternative Flow for second link:
addactivity2alternate

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kevinzluo** [comment]
@SidharthBansal Could you take a look?

**Comment by SidharthBansal** [comment]
Yeah sure

**Comment by SidharthBansal** [comment]
> saw that most of the other PRs did this ( <% if current_user %> ) to check

Please tell me PR number and file number so that I can review this behaviour

**Comment by kevinzluo** [comment]
Here is one: https://github.com/publiclab/plots2/pull/4216/files

**Comment by SidharthBansal** [comment]
Looks awesome.
You have done two tasks so you should create two separate PRS for two rewards.
Please close this one and open up 2 PRS. Also claim the tasks so that I can approve both of them.

**Comment by SidharthBansal** [comment]
Question is the first task.
Activity is the second.
Also two more tasks are interrelated to these. I will tag you to them so that you can send patches to them

They are very similar to these.

**Comment by SidharthBansal** [comment]
One reason of having separate PRS for separate issues is to have modularity enforced.

**Comment by kevinzluo** [comment]
@SidharthBansal My code doesn't work for the questions because of the issue I mentioned in the PR body. Sorry for the misunderstanding. It does work for the question button, but not the subscribe link.

**Comment by SidharthBansal** [comment]
@jywarren really likes modularity and me too

**Comment by kevinzluo** [comment]
Yeah. (@)Souravirus taught me to only change one thing for each PR in one of my first few tasks.

**Comment by SidharthBansal** [comment]
#2592

**Comment by kevinzluo** [comment]
@SidharthBansal 

> @SidharthBansal My code doesn't work for the questions because of the issue I mentioned in the PR body. Sorry for the misunderstanding. It does work for the question button, but not the subscribe link.

If you are referring to the second link which links to ask a question about the activity, I don't think I can split this into two PRs because they rely on the same function. But I can try :smile: .

**Comment by SidharthBansal** [comment]
#3656 #2592are two of the tasks which are related and you can work at as they are similar.
You can get scores easily there too

**Comment by kevinzluo** [comment]
Thank you for your guidance!

**Comment by SidharthBansal** [comment]
In total you can break this PR for 4 issues.

**Pull request closed without merging**
