### PR TITLE
Solve bug in reset password

### PR DESCRIPTION
**Pull request by rachaelkiteme**
fixes:#2122
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
okay so you opened new PR for #2122 .Great !!!

**Comment by Gauravano** [comment]
@rachaelkiteme please close your previous PR if you are working here. Thanks.

**Comment by rachaelkiteme** [comment]
Thank you so much am greatful.

Regards
Rachael

**Comment by Gauravano** [comment]
you can find more issues here https://publiclab.github.io/community-toolbox/#r=all , we would love to have your help on them. Thanks.

**Comment by jywarren** [comment]
This is great!!! It was a real journey, too! Great work, everybody!!! 👍 👍 👍 🎉

**Comment by jywarren** [comment]
Thanks for sticking with it, @rachaelkiteme !!!

**Comment by seafr** [comment]
Congrats @rachaelkiteme

**Pull request merged**
