### PR TITLE
Added User Room, UserNotificationRoom and Browser Notification for comment Addition

### PR DESCRIPTION
**Pull request by namangupta01**
#5970 
Added Browser Notification to get broadcast to the users subscribed to that node whenever a user comments.

### CODE REVIEW

**Comment by namangupta01** [comment]
ezgif com-video-to-gif (14)

**Comment by namangupta01** [comment]
@jywarren and @gauravano Have a look at this.

**Comment by jywarren** [comment]
Wow! So, how do you subscribe?

**Comment by namangupta01** [comment]
So subscribed users are the users to whom we send Email, i.e People who have commented, mentioned and all. In a general term I am calling them subscribed. Actually, we are sending notification to only those whom we send email as you can see in the `notify`.

Thanks

**Comment by namangupta01** [comment]
Let me know if anything more is required from this so that we can merge this asap.

**Comment by namangupta01** [comment]
@jywarren @gauravano any feedback?

**Comment by jywarren** [comment]
Hi @namangupta01 ! I wonder if we need a new type of subscribing, like on https://publiclab.org/settings that @gauravano made long ago (i think!). Because not everyone subscribed to email will want to get this type of notification. 

Currently this is driven by `user_tags` so that if you have the setting, user tags are created for it -- see https://publiclab.org/profile/warren -- like `digest:daily`

So if you created a conditional to look for that user tag, we could merge this, and manually create such tags, like `notifications:all` (for example). And later we can modify the /settings page to make managing such settings easier. What do you think?

**Comment by namangupta01** [comment]
Sure! Will do thanks!

**Comment by namangupta01** [comment]
@jywarren can we merge this?

**Comment by namangupta01** [comment]
All the required things are done!!

**Comment by jywarren** [comment]
Great. Can you write some documentation at http://publiclab.org/wiki/notifications that we could link to?

**Comment by jywarren** [comment]
And, let's test this out on stable!

**Comment by jywarren** [comment]
I tried this on stable, having added `notifications:all` user tag to myself and commented from a 2nd user (see https://stable.publiclab.org/notes/warren/05-23-2019/the-newsletter-of-all-time) but I didn't get a notification... is there something wrong?

**Comment by namangupta01** [comment]
It is weird. I am checking on this.

**Comment by namangupta01** [comment]
When you commented from your second user were you logged in from your 1st user in a different browser? If that is the case it should work. And also when you first opened your website did it asked for the notification permission?

**Comment by jywarren** [comment]
by different browser did you mean different application like Firefox Chrome
or a different device, or just a different browser window? I was logged in
on my phone and laptop on Chrome, and logged in as a 2nd user in Chrome
Incognito on my laptop.

**Comment by jywarren** [comment]
but I don't remember being prompted to accept use of notifications API...
when would that happen?

**Comment by namangupta01** [comment]
What do your settings look like for stable?
Can you send me a screenshot like this?
Screen Shot 2019-07-10 at 10 21 47 PM

**Comment by namangupta01** [comment]
I guess I got the problem, creating pr in 5 minutes. We can merge that and can test now.

**Comment by namangupta01** [comment]
And notification Api don't ask for permission in Chrome Incognito. Chrome simply blocks it. So it won't work in incognito.

**Comment by namangupta01** [comment]
Let's merge #6003 and test.

**Comment by jywarren** [comment]
ah but i was hoping for a notification in my non-incognito windows. I
created the comment with the incognito window. Thanks!

**Pull request merged**
