### PR TITLE
[WIP] Run bower update to get latest dependencies (fixes #2625)

### LINKED ISSUE #2625: Update Leaflet Blurred Location to v1.1.12
@mridulnagpal and I noticed PublicLab.org is running on v1.1.5 of Leaflet Blurred Location (https://github.com/publiclab/leaflet-blurred-location/):

https://publiclab.org/lib/leaflet-blurred-location/package.json

Although there's `v1.1.12` now available: https://github.com/publiclab/leaflet-blurred-location/releases

We're not pegged to a version, but to the master branch:

https://github.com/publiclab/plots2/blob/c763373a4004c8c346dbc344b18217bd3003722d/bower.json#L27

@icarito can you see if we need to run `bower update` to get the latest? Or do we need to peg to a version like `#~1.1.12` where it says `#master`?

Thanks all!

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
I pushed this to unstable to test it out!

**Comment by icarito** [comment]
This didn't work as I expected. I think it would work if we put `bower update` in the Jenkins script. I should put this script into the repository to keep track of it :-/

**Comment by jywarren** [comment]
Did you want to keep this one open?

**Comment by icarito** [comment]
No, thanks, we can close this one.

**Pull request closed without merging**
