### PR TITLE
Added test for login case #5410

### LINKED ISSUE #5415: Add test to protect login bug solution
https://github.com/publiclab/plots2/pull/5410 was a great solution for the bug identified in #5405, but I'd like to write a test to prevent this from happening again. It could be a system test:

#5316 

Or it could be an integration test, something like this:

https://github.com/publiclab/plots2/blob/3bef69c5927d91373d76049303b2f531c62814e2/test/integration/login_flow_test.rb#L15-L26

Basically we want to try logging in, like here: 

https://github.com/publiclab/plots2/blob/master/test/integration/login_flow_test.rb#L22

 but with the wrong password, then enter the right password, and show that it really redirects to the dashboard as the solution in #5410 changed. 

For anyone looking to learn more about testing, this is a good one!!!

### PR DESCRIPTION
**Pull request by 40404notfound**
Fixes #5415 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by 40404notfound** [comment]
@publiclab/reviewers Hi, please check the new test case which exposed the bug mentioned in # 5410.

**Comment by gauravano** [comment]
@jywarren any changes you think? Thanks!

**Comment by jywarren** [comment]
This is fantastic. Thank you!!!

**Comment by jywarren** [comment]
We're also attempting using system tests to do end-to-end tests of critical systems. Would you have any interest in giving one of these a try? https://github.com/publiclab/plots2/pull/5525 is an example. Thank you!!!

**Pull request merged**
