### PR TITLE
Small change to notifications settings page to remove extra + character #9361

### LINKED ISSUE #9361: Small change to notifications settings page to remove extra + character
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/users/settings.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/users/settings.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -64,7 +64,7 @@
   <% end %>
   
   <br />
-  +<h4><b><%=translation('users.settings.email_notifications')%> </b></h4>
+  <h4><b><%= translation('users.settings.email_notifications')%> </b></h4>
 
   <div style="display: inline-flex; justify-content: space-between; width: 90%;">
     <span><%=translation('users.settings.weekly_digest')%> </span>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by Onihani**
Fixes #9361 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Onihani** [comment]
@RuthNjeri please review my pull request

**Comment by Onihani** [comment]
@RuthNjeri please review my pull request

**Comment by Onihani** [comment]
@RuthNjeri please review my pull request

**Comment by waridrox** [comment]
@Onihani Please refrain from tagging people many times! People are busy and when they'll get time, they'll surely review your PR. 
Meanwhile kindly add the issue number that this PR resolves in the template section so that the issue gets referenced automatically. 
> Fixes #0 (<=== Add issue number here)
Instead of #0 add the issue number like #12345 which this PR resolves.

Also make sure that the PR title is related to the issue that it is resolving and is titled descriptively so that it's easier for the maintainers to review the work. Thanks :)

**Comment by Onihani** [comment]
@waridrox thanks alot fot the guide 
Please how do i rename the pull request

**Comment by waridrox** [comment]
> Please how do i rename the pull request

You can simply navigate to the top right section of the issue as well as the comment section to make any changes and save them :)

_To rename an issue_
Screenshot 2021-03-25 at 12 39 34 PM

_To edit the comment to add the issue numeber_
Screenshot 2021-03-25 at 12 39 59 PM

**Comment by Onihani** [comment]
@waridrox thanks a lot

**Comment by waridrox** [comment]
@Onihani great work on changing the title but still the issue is not referenced. You should probably draw some insights from https://github.com/publiclab/plots2/pull/9345 and see how the issue is referenced.

**Comment by Onihani** [comment]
thanks a lot once again @waridrox. I have been able to reference the issue now
Please can i have your twitter or instagram

**Comment by cesswairimu** [comment]
Thanks @Onihani for working on this..was there an issue for this if so, kindly point me to it

**Comment by RuthNjeri** [comment]
Hi @Onihani this issue was merged via https://github.com/publiclab/plots2/pull/9367/files that you worked on recently, I'll close this since the issue is now closed. Let me know if you have any concerns.

**Comment by RuthNjeri** [comment]
> @Onihani Please refrain from tagging people multiple times! People are busy and when they'll get time, they'll surely review your PR.
> Meanwhile kindly add the issue number that this PR resolves in the template section so that the issue gets referenced automatically.
> 
> > Fixes #0 (<=== Add issue number here)
> > Instead of #0 add the issue number like #12345 which this PR resolves.
> 
> Also make sure that the PR title is related to the issue that it is resolving and is titled descriptively so that it's easier for the maintainers to review the work. Thanks :)

Hi  @waridrox  and @Onihani, thanks for your patience as we learn to work together and get through the challenges of contributing. Let's remember to be extra kind and patient whenever possible, as we want to always be doing our best to ensure folks feel warmly welcomed and supported. Great work here - we're grateful for your time! 

@Onihani, you can always reach out via the Gitter channel as well https://gitter.im/publiclab/publiclab to get some additional h help. Thank you.

**Comment by waridrox** [comment]
> Please can i have your twitter or instagram

No worries 👍 and @Onihani, as rightly pointed out by @RuthNjeri, we all can together solve any doubts or issues you may have in the [Gitter](ttps://gitter.im/publiclab/publiclab) channel itself. I don't see the need to reach out and provide my socials to accomplish that :) Thanks ✌🏻

**Pull request closed without merging**
