### PR TITLE
Changing the no_contributors

### PR DESCRIPTION
**Pull request by P0NC1K**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by TildaDares** [comment]
@P0NC1K I'm guessing you didn't set up the local environment. If you didn't then make a new PR and add both changes to that PR.

**Comment by cesswairimu** [comment]
Hi @P0NC1K, you could also navigate to your branch using this link  https://github.com/P0NC1K/plots2/tree/patch-3, select the file you want to make changes from there and commit after updating the file. The changes will appear here too.

**Comment by TildaDares** [comment]
@P0NC1K Do you need help with this?

**Comment by P0NC1K** [comment]
So I decided to make another PR , if you see it let me know . 
P.S. - Srry for taking so long

**Pull request closed without merging**
