### PR TITLE
Facebook share button added

### LINKED ISSUE #3591: Add a Share button on questions page
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
There is no sharing feature to share questions.

### 📋Solution
Add a share button on questions page

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by dave-light**
Fixes #3591
Originally a general share button (across multiple sites) was to be inserted but now a twitter button exists so fb button is also being added.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by dave-light** [comment]
@publiclab/reviewers I have noticed the buttons aren't showing on my local host. I have tried posting a question and then approving it but no success. 

My local host is on the left, the publiclab website on the right.
image

I'd like to take a screenshot of the new button so I may tick this box.

**Comment by gauravano** [comment]
If I remember correctly, there was a condition to show social buttons in
production. So, send screenshot after changing the condition for once.
Thanks!

**Comment by dave-light** [comment]
Thank you for bringing my attention to the condition. The new button looks like this

image

Unsure why the colours are inverted but I'll play around to fix this.

**Comment by gauravano** [comment]
Pushing it on `unstable`

**Comment by gauravano** [comment]
Hi @dave-light the looks nice but I just tried sharing and got this result: (I haven't pushed this branch on `unstable` till now, just ran it locally)

share_content

It should share the page, so I guess there some more work needed. Thanks!

**Comment by dave-light** [comment]
@gauravano I've finally got to the bottom of it. No matter what I tried it wouldn't work on local host hence the delay. It does work on a web server and I've confirmed this by testing the code using my own site.

**Comment by gauravano** [comment]
I just tried your work on unstable.publiclab.org @dave-light and it's awesome and working :tada: :100:. You can also try it there :smile: .

Adding screenshot of your work 
fb_share

And, here's shared post
fb_share_working

**Comment by gauravano** [comment]
@jywarren please give final review. Thanks!

**Comment by jywarren** [comment]
:-) this looks wonderful. Great work! I noticed another facebook issue go up today if you're at all interested! https://github.com/publiclab/plots2/issues/4651

**Pull request merged**
