### PR TITLE
Text disappearance in small screen solved.

### LINKED ISSUE #7533: No text appearing in mobile view.
When we click on the button by type or by sort the dropdown appears in which the text is not appearing, there is space where the text can be shown but still, no text appears making it wired in looks.

text
text1

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes #7533 (<=== Add issue number here)

Screenshot from 2020-02-19 16-26-54
Screenshot from 2020-02-19 16-26-56

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@VladimirMikulic ok thanks will surely do this.

**Comment by nstjean** [comment]
Great thanks for making those changes! Do you have a screenshot after changing it?

I restarted the tests. hopefully it passes!

**Comment by nstjean** [comment]
The same test failed again. I'll take a look at it on my local later on.

**Comment by NitinBhasneria** [comment]
Ok, thanks @nstjean 
here are the screenshots
Screenshot from 2020-02-19 20-43-36

Screenshot from 2020-02-19 20-43-38

**Comment by NitinBhasneria** [comment]
@nstjean Do you know what this error is about?

**Comment by nstjean** [comment]
No, I don't understand why that is failing :(

**Comment by cesswairimu** [comment]
Restarting travis :disappointed:

**Comment by NitinBhasneria** [comment]
@cesswairimu @nstjean All checks passed kindly see this.

**Pull request merged**
