### PR TITLE
Show more/less in grids

### LINKED ISSUE #2150: Show more should change to Show less on clicking
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**
### Please describe the problem (or idea)
When clicking on the Show More button it does not change to Show less
image
image
> What happened just before the problem occurred? Or what problem could this idea solve?
The text should change on clicking the button

### Please show us where to look
https://publiclab.org/wiki/timelapse

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Ankit-Singla**
Fixes #2150 

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Please remove the user validation commits.

**Comment by Ankit-Singla** [comment]
@SidharthBansal I have made the required changes as you had asked. The PR is clean, with a single commit from a uniquely-named-feature-branch. Please review the PR.

**Comment by jywarren** [comment]
@SidharthBansal -- how was this looking, do you think it's something we could move ahead with? Thanks!!!

**Comment by SidharthBansal** [comment]
There must be changes to this. I think @ankit-singla has quit as he has not replied in the other PRS by him from Feb. The other PR's issues were tackled later on by other contributors at public lab.

**Comment by SidharthBansal** [comment]
Actually, my suggestion is to close this PR and look for other new comers to come and collaborate. If @ankit-singla would like to contribute he can reopen the PR.

**Comment by SidharthBansal** [comment]
Actually, my suggestion is to close this PR and look for other new comers to come and collaborate. If @ankit-singla would like to contribute he can reopen the PR.

**Comment by jywarren** [comment]
That's fair -- we'd love your help @Ankit-Singla -- thanks! We're going to close this for now but please reach out if you're able to take it back up. It looks very promising, though! 

Thanks again!

**Pull request closed without merging**
