### PR TITLE
Add feature to see followers / users following on Profile page

### LINKED ISSUE #3703: feature request to see user followers and following
### Please describe the problem (or idea)
No option to see, my followers on publiclab and which user I am following. this feature should be added to the user profile. if  it is valid 
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?
singhav
> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome ubuntu 16.04 lts
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by shubhangi-chauhan**
Fixes #3703 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by shubhangi-chauhan** [comment]
@publiclab/reviewers @jywarren
The commit adds a feature to view followes / users following on the Profile page as : 

follow-demo



____

Referring to an earlier [PR](https://github.com/publiclab/plots2/pull/3752) , which I closed since I realized I should've taken opinion before taking design decisions on my own, here's a suggestion which I think will looks good as a User Dashboard : 

user-dashboard

On a mobile display,

user-dashboard-mobile

Suggestions / changes for improvement are invited.

____

Further, as a proposal, I put forward a possible upgrade to the suggested User Dashboard to include User Statistics : 

user-stats

**Comment by jywarren** [comment]
Hi, this looks good, but would you mind trying to make the 6 icons a little smaller, and the backgrounds still white? I like the design but I feel like perhaps they don't need to be black, and the areas behind them could be more compact? 

Maybe you could find some design ideas here, as well: https://www.froala.com/design-blocks/#playground -- especially near the bottom, some of the more minimal ones? 

Thank you!!!

**Comment by jywarren** [comment]
I'm looking under Features in Froala Design Blocks -- something like this?

**Comment by SidharthBansal** [comment]
@shubhangi-chauhan do you need any help on this issue?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
