### PR TITLE
renamed from tools to methods

### LINKED ISSUE #857: Rename /tools to /methods, add redirect and change page title
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

This could be 2-3 first timers issues, or just solve it yourself!

****

Our `/tools` page is now being moved to `/methods`, and the title changed to Methods. We need to:

* change `def tools` method to be `def methods`: https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L60-L68
* add back a `def tools` which is just a redirect: `redirect_to '/methods'` in  https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L60
* change the title of the page. The template itself is at https://github.com/publiclab/plots2/blob/master/app/views/notes/tools_places.html.erb#L25, but it uses a locale file at https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/tools_places/en.yml#L6 and a matching German one at https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/tools_places/de.yml#L6

(See discussion on this question: https://publiclab.org/notes/liz/09-30-2016/should-tools-be-renamed-to-methods-techniques-or-something-else)

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.
Closes #857
Thanks!

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren I redirected tools to methods and it works fine on localhost. But I am getting 2 test fails. Please help..

**Comment by jywarren** [comment]
Hi, will try to provide some feedback but am quite busy with two events over the next 24-48 hours. Thanks for your patience and if @publiclab/reviewers can assist, that would be much appreciated. (but i know lots of people are in exams right now too).

Thanks! 👍

**Comment by ryzokuken** [comment]
@mridulnagpal What seems to be the problem? I'll try my best to help.

**Comment by mridulnagpal** [comment]
I just redirected the tools method to methods method and it shows test error

**Comment by ryzokuken** [comment]
yes, that's because you haven't configured the routes yet.

**Comment by mridulnagpal** [comment]
I updated the routes.rb file and put /methods => notes#methods

On 09-Dec-2016 4:00 PM, "Ujjwal Sharma" <notifications@github.com> wrote:

yes, that's because you haven't configured the routes yet.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/pull/1084#issuecomment-265982414>, or mute
the thread

**Comment by ryzokuken** [comment]
then perhaps you didn't commit and push your changes, because they don't show up here

**Comment by mridulnagpal** [comment]
I didnot push them but tested in my local remote still got the error

**Comment by ryzokuken** [comment]
perhaps you could push them so that I could look into them? Also, Travis will run tests automatically.

**Comment by mridulnagpal** [comment]
yeah sure

**Comment by mridulnagpal** [comment]
@ryzokuken Done

**Comment by mridulnagpal** [comment]
@ykl7 I reverted the changes

**Comment by mridulnagpal** [comment]
@jywarren @ryzokuken This one seems to work and my editor might have corrected the blank spaces between the lines

**Comment by mridulnagpal** [comment]
#1088

**Pull request closed without merging**
