### PR TITLE
Convert chars to unicode at spamaway

### LINKED ISSUE #4900: Error at Transifex new upload
I tried uploading the new file file to Transifex but it gave me error 

transifex_error

After inspecting, I came to know that error is due to  this section of code - 

https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L913-L925

Solving it right away by putting codes in-place of character but it need testing on unstable and notice so dropping here. Thanks!

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #4900 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
Here's the view after conversion, just the same :P 
 
unicode_conversion

**Comment by jywarren** [comment]
Oh, mine are currently in color; but probably they'll still be after this change? 

screen shot 2019-03-01 at 5 36 09 pm

**Comment by gauravano** [comment]
@jywarren which browser you use? 

I use Chrome and icons don't appear colored there, but colors shown in firefox 

pl_icon_color
**Production view of Signup at Chrome**

mozilla_view
**Productiob view of Signup in Firefox**

**Comment by jywarren** [comment]
Chrome Mac for that screenshot. I guess it's ok?

**Comment by gauravano** [comment]
yes!

**Comment by gauravano** [comment]
We need to check this on unstable, just to be sure, but builds are failing due to typeahead error

**Comment by SidharthBansal** [comment]
Hi Gaurav, can you please create a milestone for your project instead of labelling it with `Translation system' and add all ther stuff in the milestone. 
Milestones are for specific goals/ checkpoints. Labels are supposed to classify the issues and pr.
Thanks

**Comment by gauravano** [comment]
Hey Sidharth, I created a project in plots2 and as you can see this issue is also added to the project. Regarding 'Translation system' label, I used that just for clarity as not everyone uses Projec, so if a new contributor want to help with the details, they can just see issues tagged with the label.

**Comment by SidharthBansal** [comment]
Oh thanks for the descriptive response.

**Comment by jywarren** [comment]
I think we are OK with this. Thanks a lot Gaurav!

**Comment by gauravano** [comment]
Great! I will check the stable.publiclab.org if anything else is required and then upload the new en.yml on transifex.

**Pull request merged**
