### PR TITLE
Push footer below map in /map/

### LINKED ISSUE #7047: Push footer below map in /map/
Currently the footer text is all overlayed on top of the map. We want to push it below the map and set the map to approximately 90% of the screen height.

### PR DESCRIPTION
**Pull request by nstjean**
Fixes #7047 (<=== Add issue number here)

I tried using the class `inline-fullwidth-content` as suggested in https://github.com/publiclab/plots2/issues/6993 but for some reason the map won't go full-width no matter what I do. I can get it to go full-width using other methods, but it would be awful nice to be able to use one standard class to achieve it!

This currently has all kinds of footer info in layouts/_footer.html.erb just for testing purposes. I will remove it when I am done!

### CODE REVIEW

**Comment by nstjean** [comment]
This is what is happening when I use `inline-fullwidth-content`

FireShot Capture 130 - 🎈 Public Lab_ Map - localhost

**Comment by nstjean** [comment]
How it looks with my overrides:

FireShot Capture 148 - 🎈 Public Lab_ Map - localhost

FireShot Capture 149 - 🎈 Public Lab_ Map - localhost

**Comment by sagarpreet-chadha** [comment]
Yes it looks great! You can remove the testing data from this PR and this is ready to got then!

**Comment by nstjean** [comment]
@sagarpreet-chadha Removed the test data, this is all set to merge!

**Comment by jywarren** [comment]
This is AWESOMEEEEEEEE

**Pull request merged**
