### PR TITLE
FIX: Social icons alignment on PL posts

### LINKED ISSUE #7608: Social icons alignment is not proper in sidebar
**Please describe the desired behavior.**
In the current beahviour the questions sidebar social links alignment is not proper. The twitter icon is not placed on the same vertical level as other social icons.

**Additional context (optional)**

image

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #7608 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

## Screenshots  
Screenshot from 2020-03-08 21-43-54

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@VladimirMikulic @publiclab/reviewers can you kindly review? Thanks :v:

**Comment by Uzay-G** [comment]
I am not sure we should put it also in the sidebar. In the picture, you can see that now there are two areas with social links. What do you think?

**Comment by VladimirMikulic** [comment]
@Uzay-G I agree. Having social icons on 2 places is redundant. Anyways the Twitter icons should be vertically centred like others.

**Comment by Tlazypanda** [comment]
@VladimirMikulic yeah noticed the same was about to open an issue for it ...should I open a separate pr for this since this requires change in home/social partial which is rendered in multiple places? And should I close this pr if it is redundant :sweat_smile: Thanks :v:

**Comment by VladimirMikulic** [comment]
@Tlazypanda I renamed this PR accordingly, you don't need to open another PR, just continue on this one :)

**Comment by Tlazypanda** [comment]
@VladimirMikulic   is this alright? :sweat_smile: 
image

**Comment by VladimirMikulic** [comment]
@cesswairimu from the Travis log, SimpleCov failed.
https://travis-ci.org/publiclab/plots2/jobs/660144235?utm_medium=notification&utm_source=github_status

**Comment by Tlazypanda** [comment]
@cesswairimu @VladimirMikulic  should I remove adding the social links to sidebar and just fix the alignment of twitter icon in this pr? :sweat_smile:

**Comment by VladimirMikulic** [comment]
@Tlazypanda it's totally fine. You don't need to remove anything. We don't want a PR flood :)

**Comment by Tlazypanda** [comment]
@cesswairimu can we just do the twitter alignment only for this pr? :sweat_smile:

**Comment by cesswairimu** [comment]
Yeah we can do that @Tlazypanda, change the issue desc or create a new issue and remove the other code in this PR. Thanks

**Comment by jywarren** [comment]
I think the system test issue in https://github.com/publiclab/plots2/pull/7562 may be affecting the system tests here too...

Log excerpt here:

```
[0309/132027.199397:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 11
[0309/132027.205587:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 5
[0309/132029.647725:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 7
[0309/132029.649385:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 15
[0309/132046.538641:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 19
[0309/132048.041836:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 43
[0309/132058.126726:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 59
2020-03-09 13:21:02 +0000: Rack app error handling request { DELETE /tag/delete/11/40 }
Mysql2::Error
```

I'm restarting it though to try to get it to pass...

**Comment by Tlazypanda** [comment]
@cesswairimu @jywarren issue description changed and pr unrelated changes removed ..ready for a review :v:

**Comment by jywarren** [comment]
Awesome!!! Thanks!

**Pull request merged**
