### PR TITLE
Added public/public folder to gitignore

### PR DESCRIPTION
**Pull request by imajit**
a12
Added `public/public` folder to gitignore

### CODE REVIEW

**Review by noi5e — APPROVED** [review]
Looks fine to me. 

Why are we making this change again? :) I don't seem to have a `public/public` folder locally:

Screen Shot 2021-08-05 at 1 28 00 PM

I think I remember seeing something about this on chat or GitHub. Is there an issue open that we can link to here so that we can get some good documentation?

**Comment by imajit** [comment]
> Looks fine to me.
> 
> Why are we making this change again? :) I don't seem to have a `public/public` folder locally:
> 
> Screen Shot 2021-08-05 at 1 28 00 PM
> 
> I think I remember seeing something about this on chat or GitHub. Is there an issue open that we can link to here so that we can get some good documentation?

Hi! 
This folder was created when I ran system tests recently. It has some screenshots. I'm not sure if its an issue specific to my system. @noi5e  Can if verify this in your system?  I will close the PR if it's just a local issue.

**Comment by noi5e** [comment]
> This folder was created when I ran system tests recently. It has some screenshots. I'm not sure if its an issue specific to my system. @noi5e Can if verify this in your system? I will close the PR if it's just a local issue.

Hmm, yeah, I don't see it on my `main` branch. Let's leave this open for now. I'll request review from @Tlazypanda and @jywarren, maybe they have seen it locally

**Comment by noi5e** [comment]
Even though no one else weighed in, I'm going to go ahead and merge this one to clear the PRs. 

It's small enough it can be easily reverted, and I'm sure it will help if there are other people experiencing this! Thanks @imajit

**Comment by jywarren** [comment]
Thanks @imajit @noi5e -- much appreciated!

**Pull request merged**
