### PR TITLE
Fix/grid scroll #1070

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren I have made a tweak to fill cells as we scroll but if a cell is once scrolled over it stays filled. Please have a look.

**Comment by mridulnagpal** [comment]
@jywarren I checked now it works fine

**Comment by jywarren** [comment]
Super! Merging in now.

**Comment by jywarren** [comment]
Do you want to take a crack a the next one, now? Thanks for your hard work!

**Pull request merged**
