### PR TITLE
Setting i18n locale by subdomain

### PR DESCRIPTION
**Pull request by jiteshjha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
- [ ] All tests pass -- `rake test:all`
- [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
- [ ] pull request are descriptively named
- [ ] if possible, multiple commits squashed if they're smaller changes
- [ ] reviewed/confirmed/tested by another contributor or maintainer
- [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jiteshjha** [comment]
Subdomain for locales is now working on localhost, but all I18n-related tests fail. Probably will have to remove locale-switching dependency from "change_locale" method to something else.

**Comment by jiteshjha** [comment]
As for each view, "set_locale" method in the application_controller detects locale from the sub-domain and sets the language, maybe just changing the sub-domain could help in our tests. This looked interesting : http://stackoverflow.com/questions/598933/how-do-i-change-the-default-www-example-com-domain-for-testing-in-rails

**Comment by jywarren** [comment]
Hmm, did you need some help with this one, or are you still working on it?

**Comment by jiteshjha** [comment]
I've been trying to come up with various approaches of changing language in our I18n tests whilst maintaining the subdomain logic, with no luck yet. @ananyo2012 could you suggest something?

**Comment by jywarren** [comment]
Looking at this now. Are you talking about the subdomain logic in these two files:

https://github.com/publiclab/plots2/blob/0574ab66347916f4d48a9091e78db042bcbb1e4d/app/controllers/wiki_controller.rb#L7

https://github.com/publiclab/plots2/blob/master/config/routes.rb#L28-L33

I think these could be reworked too, honestly. Let's ask Liz.

**Comment by jywarren** [comment]
@ebarry, do we really ever use `nyc.publiclab.org` or `gulfcoast.publiclab.org` and do we need to preserve that functionality? Just trying to clear up what options we have for internationalization via subdomain, like `es.publiclab.org`

**Comment by ryzokuken** [comment]
Hello! You must've noticed that the unit tests failed unexpectedly on your PR. This was due to some issue in the Travis CI testing configuration which was fixed by @jywarren later tonight. In order to make them work again, please rebase your work on top of the current master and then try pushing to your remote branch. Do this by:

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <my-branch>
$ git rebase master
$ git push origin <my-branch>
```

Thanks for bearing with us,
Ujjwal

**Comment by ryzokuken** [comment]
@jywarren This one looks abandoned.

**Comment by jywarren** [comment]
Yes, I'm going to close it -- perhaps if someone requests this functionality again some of this code could be resurrected. Thanks!

**Pull request closed without merging**
