### PR TITLE
Refactor node_shared

### LINKED ISSUE #5679: Reduce redundancy in inline grids file
This file is very well tested, but has LOTS of redundancy:

https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb

CodeClimate gives a great overview of the level of code duplication here:

https://codeclimate.com/github/publiclab/plots2/app/models/concerns/node_shared.rb

Here you can see that we have tests covering all but the `notes_thumbnail_grid` code, which should give us good confidence in it being OK to rearrange things as long as they pass tests. We can hold off on the thumbnail code until we have a test for that, or we can test it manually:

https://coveralls.io/builds/23246122/source?filename=../models/concerns/node_shared.rb

### PR DESCRIPTION
**Pull request by emctackett**
Fixes #5679 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by emctackett** [comment]
This is a WIP-- I wanted to get a PR established & see Code Climate's evaluation of the code.

**Comment by jywarren** [comment]
Oh WOW! This looks really good! How do @publiclab/plots2-reviewers feel - my main question is whether it's still readable to someone new coming into this section of code? Would we want to make the method names even more descriptive perhaps?

**Comment by jywarren** [comment]
And, you may have been doing this already, but CodeClimate (though it's not very smart) tries to identify repeated sections of code, in case that's any help in identifying further optimizations: https://codeclimate.com/github/publiclab/plots2/pull/5813

**Comment by emctackett** [comment]
Thanks a bunch @jywarren , yeah certainly I don't want to impact readability negatively so interested in feedback about that.

I did see that CodeClimate had some more input about repeated sections of code and can work on those optimizations if you want me to/depending on what reviewers think.

**Pull request merged**
