### PR TITLE
Unban label for banned user

### LINKED ISSUE #7507: Enhance the unban functionality
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Currently if a user is banned the admin has to go to it's profile to unban the user.I would be better if the admin is provided with the unban option in the dropdown itself.
**Current Behaviour**
Untitled_ Feb 16, 2020 12_05 AM

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****
### Update from @jywarren 

Hi, i think one issue here is that we are aiming to have very maintainable code and so are a little hesitant to add complex interfaces in duplicate. I wonder if we could do 2 things:

1. could we format the `banned` label a bit? Off topic, but it looks a little funny, no?
2. could we have, on a second line in the popup, something that says `Unban on profile` and link to the profile? this wouldn't require a test to protect new functionality and is pretty simple.

### PR DESCRIPTION
**Pull request by imajit**
Fixes #7507 
I have changed the `See Full Profile` label to `Unban on profile` for banned users. I have also changed the background similar to `/spam`
Current working
unbannw

After changes
unbanw2

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @imajit, maybe we could have the the icon + the text in red for banning...and when banned have the unban text to green..something like what we have in `/spam` for consistency..you can check this locally if logged in as admin but it looks like this

Screenshot from 2021-02-25 21-13-08
Screenshot from 2021-02-25 21-13-29


thoughts?
Thanks for working on this

**Comment by imajit** [comment]
@cesswairimu @jywarren can you please review this

**Comment by cesswairimu** [comment]
Hi @imajit this is a good start..did you want to add tests for this functionality? No biggie if not, we could add a follow up issue for that after this is merged. Thanks

**Comment by cesswairimu** [comment]
Hi @imajit based on our conversation, I will go ahead and merge this and keep the issue open until the tests are implemented....feel free to pick it later if interested Thanks

**Review by cesswairimu — APPROVED** [review]
:tada:

**Pull request merged**
