### PR TITLE
[WIP] Validity checks for signin.

### LINKED ISSUE #3439: Success sign when Password match  with Confirmation password
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
This is a feature request  in Sign up (https://publiclab.org/register) Page when we sign up and  fill details but No success  message sign when confirming password  field and password filed match and no error sign when not match

It should look like this

pssword

### EDIT:
Let's do form validation for the whole sign-up form, so you need to check username, email, password, password_confirmation for their presence and their format. 

After that, if all the conditions are satisfied then user would be able to submit successfully otherwise sign-up button would just change the focus to error field. Any question?

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #3439  (<=== Add issue number here)

Continued from #3984 . Just rebased, still a work in progress.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@kevinzluo can you please paste the screenshots/gifs here?

**Comment by kevinzluo** [comment]
@SidharthBansal I am still working on it. The new changes might have caused some errors. I will post screenshots as soon as I feel it is working :+1: .

**Comment by SidharthBansal** [comment]
ok lets finish #4438 first.

**Comment by SidharthBansal** [comment]
I think we should wait for Jeff for this PR. In the meantime you can enjoy
the new year and do some other pending PRs/issues.
Thanks.

**Comment by jywarren** [comment]
Could you put a container div around the re-used portion, which has a distinct classname, and then be referencing specific fields only with that nested reference, like:

```js
$('.containerDiv input.username')...
```

What do you think? Thanks for being persistent and great with this one! I'm sure we'll be able to merge it soon and it will be great.

**Comment by SidharthBansal** [comment]
Closing this PR as Kevin is offline for many months. Kevin feel free to reopen it when you want to work on it again

**Pull request closed without merging**
