### PR TITLE
Fixes to order tag page by subscription

### PR DESCRIPTION
**Pull request by Gauravano**
Correction attempt for order by suscription

### CODE REVIEW

**Comment by Gauravano** [comment]
hey @jywarren, I guess in my PR last time I haven't given attention to pagination due to less number of tags in my localhost but when I checked this order_by_subscription on PublicLabs site then realized my mistake, Sorry for this.I hope it will work this time on production, although I have tested it for 2 pages and it's doing fine for them.

correction

**Comment by jywarren** [comment]
Ah, ok - thanks! Is this ready to be merged, then?

**Comment by Gauravano** [comment]
Yes Jeff

**Comment by jywarren** [comment]
🎉 🎈 !

**Pull request merged**
