### PR TITLE
Broken question-comment design fix. Fixes #977

### LINKED ISSUE #977: Broken design for question comment section
This is related to the fix in #958. Here is the screenshot of the comment section now.
design
The color of the comment section div should be same. Also the "View more comments" button is placed at the bottom after the comment input box. Since comments are arranged in the ascending order of their posting date the View more comments button should be placed at the top. Also the behavior of the button needs to be changed to load the previous comments. 

## Steps of Solution
- [ ] [This block](https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L52-L54) of code should come under [this div](https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L56). This solves the design issue.
- [ ] The "View more comments" button should be `prepended` instead of appending. So change `.append()` to `.prepend()` in [this line](https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L97). 
- [ ] Now the comments on submission should be appended at last of all comments. So the `.after()` should be changed to `.before()` in [this line](https://github.com/publiclab/plots2/blob/master/app/views/comment/create.js.erb#L1).
- [ ] Since we are listing recent comments the older comments should be hidden. The behavior of the "View more Comments" should be changed to "Load previous comments". To do this change the `expand_comments()` function. The `.slice(0,3)` should be changed to `.slice(-3)` in [this line](https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/comment_expand.js#L9). Also it should be changed in the [questions/show](https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L95) template.
- [ ] Finally you need to similar changes in [questions/answer](https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb) and [questions/answers](https://github.com/publiclab/plots2/blob/master/app/views/questions/_answers.html.erb) partials to reflect same behavior.

### PR DESCRIPTION
**Pull request by Pk13055**
#977 
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Pk13055** [comment]
@ananyo2012 Can you please review the changes and let me know if there's something I missed out.

**Comment by jywarren** [comment]
Also, exactly which parts of #977 does it resolve -- that way we can check it off. Thanks!

**Comment by ananyo2012** [comment]
Sorry for the late response. Reviewing this now.

**Comment by ananyo2012** [comment]
@Pk13055 You need to change [this line](https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/comment_expand.js#L9) too to change the behavior of the `comment_expand()` function. You can just amend the commit and add the changes.

**Comment by Pk13055** [comment]
@ananyo2012 I've updated the required line. Please review and tell me if anything else needs to be done.

**Comment by ananyo2012** [comment]
@Pk13055 Try to amend commit instead of adding a new one for small changes. Next you have to do the similar changes in the answer template too to replicate same behavior in answer comments section.

**Comment by Pk13055** [comment]
@ananyo2012 I made the requested changes; please review. (I tried appending but it didn't work; threw up some error)

**Comment by ananyo2012** [comment]
Also you have to put [these lines](https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L78-L80) at the beginning of the `answer-<%= answer.id %>-comment` div similar to that of the questions/show template. Also can you squash all these commits into one after you have done? I see you have merged the changes instead of rebasing adding a merge commit as well. If you need help in squashing you can ask in the gitter channel.

**Comment by jywarren** [comment]
Ah, interesting, this is a Jasmine error:

```
Plots2 shows expand comment button with remaining comment count
  Expected 'View 2 previous comments' to equal 'View 2 more comments'.
```

On this line:

https://github.com/publiclab/plots2/blob/master/spec/javascripts/plots2_spec.js#L95

If you've modified that line, you should expect to see that test fail, but you can update the test itself to reflect the new wording (in addition to the changes Ananyo asked about). Thank you! Almost there!

**Comment by jywarren** [comment]
Great -- @ananyo2012, does this look good to you then?

**Comment by ananyo2012** [comment]
Yes this looks good. But @Pk13055 Is probably trying to squash the commits. So we should probably.

**Comment by jywarren** [comment]
I'm going to go ahead and squash and merge -- I haven't had any trouble with it. Thanks! @Pk13055 - manual squashing appreciated in the future, but not essential! It's good to know how to do it.

**Pull request merged**
