### PR TITLE
Make user bio fallback to empty string (resolves #1521)

### LINKED ISSUE #1521: Add bio and token to seed data
Currently, the bio for the seed data is set to `nil` instead of `''`.

@jywarren what went wrong?

screenshot-2017-7-11 action controller_ exception caught

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Do you think this is worth writing a test specifically for?

**Comment by ryzokuken** [comment]
It does break the application, a test shouldn't hurt.

**Comment by jywarren** [comment]
aha, this is all good then?

**Comment by ryzokuken** [comment]
@jywarren yes from my side, merge this whenever it's okay. After this gets fixed, I will make a PR for making the token accessible to the user. What do you say? Should we make a button that says "email me my token"? Is that safe? Just displaying it sounds totally unsafe. Having a button that shows it in an alert does sound like a good middle ground.

**Comment by jywarren** [comment]
> button that shows it

Yes! Great!

**Pull request merged**
