### PR TITLE
Login modal for sidebar note and questions

### LINKED ISSUE #4151: Link Login Modal to Research Note
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to write a research note.
link- https://publiclab.org/post
plots2/app/views/sidebar/_related.html.erb

### LINKED ISSUE #4419: Link login modal to 'ask a related question'
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to `ask a related question`). For modularity, this is separate from linking the button.

image

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #4151, Fixes #4419 
First of all, @SidharthBansal I'm really very sorry and apologise for my casual behaviour. This won't happen again. 😢 

Basic flow for `research note`
research note login basic flow

Alt flow for `research note`
research note login alt flow

Basic flow for `questions`
question login basic flow

Alt flow for `questions`
question login alt flow

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
No need to apologize. You are mentee and you will err. It is great to see
that you are a fast learner. I really love this nature. Thanks for PR. I
will review after Travis tests.

**Comment by SidharthBansal** [comment]
You did 2 functionality questions and note but I found only one change in your commit. Are you missing something to push?
Also, it is handling two issues and you wrote a single issue in the PR body. It is much appreciated if we have two different PR of two different issues from future onwards. 
Please write both issue numbers in the PR body section. Thanks.

**Comment by oorjitchowdhary** [comment]
Hi, @SidharthBansal .. I've two changes.. Check the `class` of both the lines... In the first line the addition is getting highlighted but in the second line it is not I don't know why..

Also, I didn't find any issue for `ask a related question`, so I mentioned only one issue

**Comment by SidharthBansal** [comment]
Thanks. Please close up the issues related to this PR which are solved.

Great job as you do daily.

**Pull request merged**
