### PR TITLE
Jasmine tests

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake spec:javascript` as well as visiting `localhost:3000/specs/`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren I hope this can be merged for now. I have added two more tests and fixed the bug for updating like count that was happening due to changing the `jQuery.getJSON()` function. I hope I can add more JavaScript tests as we progress. Thanks!

**Comment by ananyo2012** [comment]
Not rebased. Rebasing within few minutes.

**Comment by ananyo2012** [comment]
Rebased on the latest master

**Comment by jywarren** [comment]
Great, testing now...

**Comment by jywarren** [comment]
I got an error (running this after rebasing on this morning's other PR merges), can you take a look? It might be related to a database boolean type error; sqlite and mysql store "true" differently (sqlite stores it as an integer).

````
Started
...........................................................................F
================================================================================
Failure:
  <"1"> expected but was
  <"true">.
test_create_like(LikeControllerTest)
test/functional/like_controller_test.rb:34:in `block in <class:LikeControllerTest>'
================================================================================
F
================================================================================
Failure:
  <"-1"> expected but was
  <"false">.
test_delete_like(LikeControllerTest)
test/functional/like_controller_test.rb:52:in `block in <class:LikeControllerTest>'
================================================================================
................................................................................
......................................
````

This was a pre-existing test, so I'm poking around to see if changes to fixtures caused it.

**Comment by jywarren** [comment]
Ah, whoops! We changed it to return a count, not a boolean, I forgot. So we have to update the tests to reflect this. I guess -1 is when you unlike something with count = 0. 

I'm going to just adjust the tests for now, to merge this. If you think we should deal with the obscure possibility of a negative like count (i think actual data wouldn't allow this), we could add more and adjust the tests accordingly in a separate PR.

**Comment by jywarren** [comment]
OK, done and manually rebased and merged!  60ded65

**Comment by ananyo2012** [comment]
@jywarren Thanks Jeff! I just overlooked the rails tests amidst the javascript tests. Sorry for it.

**Pull request closed without merging**
