### PR TITLE
en-translation missing

### LINKED ISSUE #7840: Titles on navbar dropdown links are all "translation missing..."
### Please describe the problem (or idea)

In the dropdown links in the site's navbar, all titles are "translation missing:...", example: "translation missing: en.Tools".

If you keep your mouse hovering for a couple of seconds on the link you'll see the title text.

### Please show us where to look

image

### Browser, version, and operating system

Chrome.

### PR DESCRIPTION
**Pull request by urvashigupta7**
Fixes #7840 

Screenshot from 2020-10-10 13-37-06

### CODE REVIEW

**Review by jywarren — CHANGES_REQUESTED** [review]
Hi, this looks awesome! Can you just share a screenshot of this change so we can confirm? Thank you!!!

**Comment by urvashigupta7** [comment]
Hi @jywarren  I have added the screenshot. Also, I have left some comment on #8373 . Can you please take a look ? Thanks!! :smile:

**Review by jywarren — APPROVED** [review]
This looks super! Thank you so much!!!!

**Comment by jywarren** [comment]
Great!!! Thank you so much!!!

**Pull request merged**
