### PR TITLE
fix for wiki update

### LINKED ISSUE #4941: Wiki editing seems to be broken
Hi all -- we seem to have a new bug with the wiki editing system; perhaps related to some recent changes to https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb ?

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #4941  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

wiki_working

### CODE REVIEW

**Comment by siaw23** [comment]
Maybe a test for this so it never happens in the future?

**Comment by gauravano** [comment]
I just checked tests are already there for update https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L141-L149 and some more in the same file. 

I ran the tests on master branch and got these errors, due to null assignment to node.vid

```
sachdevarockz@sachdevarockz-Latitude-E6430:~/Desktop/open source/Publiclab/plots2$ ruby -I test test/functional/wiki_controller_test.rb
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
DEPRECATION WARNING: Leaving `ActiveRecord::ConnectionAdapters::SQLite3Adapter.represent_boolean_as_integer`
set to false is deprecated. SQLite databases have used 't' and 'f' to serialize
boolean values and must have old data converted to 1 and 0 (its native boolean
serialization) before setting this flag to true. Conversion can be accomplished
by setting up a rake task which runs

  ExampleModel.where("boolean_column = 't'").update_all(boolean_column: 1)
  ExampleModel.where("boolean_column = 'f'").update_all(boolean_column: 0)

for all models and all boolean columns, after which the flag must be set to
true by adding the following to your application.rb file:

  Rails.application.config.active_record.sqlite3.represent_boolean_as_integer = true
 (called from <top (required)> at /home/sachdevarockz/Desktop/open source/Publiclab/plots2/config/environment.rb:5)
Emptying /home/sachdevarockz/Desktop/open source/Publiclab/plots2/test/reports
DEPRECATION WARNING: This Authlogic configuration option (validates_format_of_email_field_options) is deprecated. Use normal
ActiveRecord validation instead. Detailed instructions:
https://github.com/binarylogic/authlogic/blob/master/doc/use_normal_rails_validation.md
 (called from block in <class:User> at /home/sachdevarockz/Desktop/open source/Publiclab/plots2/app/models/user.rb:26)
You have selected Sha512 as your authlogic crypto provider. This algorithm
does not have any practical known attacks against it. However, there are
better choices.

Authlogic has no plans yet to deprecate this crypto provider. However,
we recommend transitioning to a more secure, adaptive hashing algorithm,
like scrypt. Adaptive algorithms are designed to slow down brute force
attacks, and over time the iteration count can be increased to make it
slower, so it remains resistant to brute-force search attacks even in
the face of increasing computation power.

Use the transition_from_crypto_providers option to make the transition
painless for your users.
Started with run options --seed 7364

/home/sachdevarockz/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.2/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension
/home/sachdevarockz/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.2/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here
ERROR["test_should_choose_I18n_for_wiki_controller", #<Minitest::Reporters::Suite:0x000055d529cb1278 @name="WikiControllerTest">, 2.6951628170063486]
 test_should_choose_I18n_for_wiki_controller#WikiControllerTest (2.70s)
ActiveRecord::NotNullViolation:         ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: node.vid: UPDATE "node" SET "vid" = ?, "title" = ?, "changed" = ? WHERE "node"."nid" = ?
            app/controllers/wiki_controller.rb:467:in `block in update_node_attributes'
            app/controllers/wiki_controller.rb:452:in `update_node_attributes'
            app/controllers/wiki_controller.rb:197:in `update'
            test/functional/wiki_controller_test.rb:426:in `block (2 levels) in <class:WikiControllerTest>'
            test/functional/wiki_controller_test.rb:415:in `each'
            test/functional/wiki_controller_test.rb:415:in `block in <class:WikiControllerTest>'

ERROR["test_update_root-path_(/about)_wiki", #<Minitest::Reporters::Suite:0x000055d529531700 @name="WikiControllerTest">, 4.606402018995141]
 test_update_root-path_(/about)_wiki#WikiControllerTest (4.61s)
ActiveRecord::NotNullViolation:         ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: node.vid: UPDATE "node" SET "vid" = ?, "title" = ?, "changed" = ? WHERE "node"."nid" = ?
            app/controllers/wiki_controller.rb:467:in `block in update_node_attributes'
            app/controllers/wiki_controller.rb:452:in `update_node_attributes'
            app/controllers/wiki_controller.rb:197:in `update'
            test/functional/wiki_controller_test.rb:195:in `block in <class:WikiControllerTest>'

ERROR["test_update_wiki_selecting_previous_image", #<Minitest::Reporters::Suite:0x000055d5293f5eb8 @name="WikiControllerTest">, 4.630522109000594]
 test_update_wiki_selecting_previous_image#WikiControllerTest (4.63s)
ActiveRecord::NotNullViolation:         ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: node.vid: UPDATE "node" SET "vid" = ?, "title" = ?, "changed" = ? WHERE "node"."nid" = ?
            app/controllers/wiki_controller.rb:467:in `block in update_node_attributes'
            app/controllers/wiki_controller.rb:452:in `update_node_attributes'
            app/controllers/wiki_controller.rb:197:in `update'
            test/functional/wiki_controller_test.rb:217:in `block in <class:WikiControllerTest>'

ERROR["test_update_wiki_uploading_new_image", #<Minitest::Reporters::Suite:0x000055d529347638 @name="WikiControllerTest">, 4.664758540995535]
 test_update_wiki_uploading_new_image#WikiControllerTest (4.66s)
ActiveRecord::NotNullViolation:         ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: node.vid: UPDATE "node" SET "vid" = ?, "title" = ?, "changed" = ? WHERE "node"."nid" = ?
            app/controllers/wiki_controller.rb:467:in `block in update_node_attributes'
            app/controllers/wiki_controller.rb:452:in `update_node_attributes'
            app/controllers/wiki_controller.rb:197:in `update'
            test/functional/wiki_controller_test.rb:206:in `block in <class:WikiControllerTest>'

ERROR["test_updating_wiki", #<Minitest::Reporters::Suite:0x000055d5292cd2c0 @name="WikiControllerTest">, 4.687289276000229]
 test_updating_wiki#WikiControllerTest (4.69s)
ActiveRecord::NotNullViolation:         ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: node.vid: UPDATE "node" SET "vid" = ?, "title" = ?, "changed" = ? WHERE "node"."nid" = ?
            app/controllers/wiki_controller.rb:467:in `block in update_node_attributes'
            app/controllers/wiki_controller.rb:452:in `update_node_attributes'
            app/controllers/wiki_controller.rb:197:in `update'
            test/functional/wiki_controller_test.rb:145:in `block in <class:WikiControllerTest>'

  54/54: [=================================] 100% Time: 00:00:04, Time: 00:00:04

Finished in 4.82390s
54 tests, 138 assertions, 0 failures, 5 errors, 0 skips
Writing XML reports to /home/sachdevarockz/Desktop/open source/Publiclab/plots2/test/reports
sachdevarockz@sachdevarockz-Latitude-E6430:~/Desktop/open source/Publiclab/plots2$ 
```

**Comment by siaw23** [comment]
Hmmm... this is weird. There's a test for update yet CI passed? Interesting.

**Comment by jywarren** [comment]
I'm merging this and publishing, thank you very much. Yeah it is a mystery to me, i wonder how CI passed in Travis? Gaurav, are you saying that locally it didn't pass but in Travis it did?

**Comment by gauravano** [comment]
> Gaurav, are you saying that locally it didn't pass but in Travis it did?

@jywarren yes!

As you can see this bug got in through https://github.com/publiclab/plots2/pull/4902 when `revision.save` was placed after `update_node_attributes` - https://github.com/publiclab/plots2/commit/40b6624af14b10027196b049e3a1ed8e11dd287e#diff-528416b5954756daa0b141666006dbcbR197. tests should've failed at that point but they didn't and that's why we didn't come to know about this bug there.

But, in local tests failed when I ran tests on wiki_controller_test.rb .

**Pull request merged**
