### PR TITLE
Fixes #11223: Added date picker Functionality

### LINKED ISSUE #11223: Display posts based on the date range (when selecting custom date range)

### PR DESCRIPTION
**Pull request by KarishmaVanwari**
On clicking the custom option in the sort dropdown, the user can select from and to dates and user is then displayed the posts within that date range.

Fixes #11223 

Screenshots:
Before selecting date range /tag/three consists of 4 posts (total posts).
After selecting the date range, one post is displayed:

image

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by KarishmaVanwari** [comment]
> Hi @KarishmaVanwari, this looks great!! Do you think maybe we could remove the time in the date range so that it looks more friendly?

Yes @TildaDares, we can do that by replacing `<%= @start.to_formatted_s(:long) %>` with `<%= @start.to_formatted_s(:long)[0...-6] %>` and same for end-date [here](https://github.com/publiclab/plots2/blob/73498e4bd816948d0a041d19bd18b03375ccf27d/app/views/tag/show/_tab_content.html.erb#L4) so as to trim the striing to omit the time. Also, the following change would remove time from 'past month' and 'past year' sorting options as well. Does this work then?

**Comment by KarishmaVanwari** [comment]
> Is there also a way to prevent a user from being able to click the `Save Changes` button until they've filled both the from & to fields? Thanks!
> 
> You're doing an amazing job @KarishmaVanwari!

Yes, I plan to add validations, in a follow-up PR, like:
1. From and to dates, both are mandatory to hit `Save changes`
2. From and to dates must be valid (from date should be strictly before than and end date)
3. None of the from and to dates must be after the current date.

I'm open to any suggestions on this. 

Thank you so much @TildaDares!!

**Comment by jywarren** [comment]
Excellent!! Great work!!

**Comment by KarishmaVanwari** [comment]
Thank you @TildaDares, @jywarren!! 😃

**Pull request merged**
