### PR TITLE
improve like count

### LINKED ISSUE #3524: Continuous like button press shows unexpected behavior
### Please describe the problem (or idea)
When like button is pressed continuously it shows unexpected behaviour. Like may go to negative values also. On refreshing page problem is solved.

> What happened just before the problem occurred? Or what problem could this idea solve?

like

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors

### What's your PublicLab.org username?
igniteeng000
> This can help us diagnose the issue: 

### Browser, version, and operating system
Windows 10, chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by avsingh999**
Fixes #3524  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by avsingh999** [comment]
@publiclab/reviewers  @jywarren @SidharthBansal @gauravano  please review 
Thanks : )
pr_like

**Comment by avsingh999** [comment]
@SidharthBansal  @gauravano  please tell me why these checks are not successful.
thank you

**Comment by gauravano** [comment]
Here's the error: 

test_fail

**Comment by sashadev-sky** [comment]
@gauravano @avsingh999 I think these errors might be the solution to issue #4589. I am unfamiliar with JS testing syntax altogether but the tests seem off to me at first glance. Looking into it more right now and could be completely wrong but just a heads up! And if you're more familiar with the testing and could let me know that would be great.

**Comment by gauravano** [comment]
Yes @sashadev-sky, #4589 is certainly related at some level. 

I haven't written a JS test too but would see if I could be of any help here. Thanks! You can ask @jywarren.

**Comment by sashadev-sky** [comment]
I solved the error #4589 when I ran the unstable branch and will open a PR about that shortly. But I realized it does not have to do with this issue here. The reason the errors are failing here is because they are written in a deprecated syntax. [https://github.com/hurrymaplelad/sinon-codemod](https://github.com/hurrymaplelad/sinon-codemod)

@avsingh999 would you be able to re-write them? 
This resource gives you the information you need:
1) https://sinonjs.org/releases/latest/stubs/ writes about the `var stub = sinon.stub(object, "method", func);` syntax being deprecated and has the new syntax plus other information about testing.

- Both tests are directly related to the updates you are working on so it would be good to get them fixed so we can confirm everything is working as expected, even if you didn't cause them. And you will be able to double check on your own work  👍

**Comment by sashadev-sky** [comment]
@avsingh999 your edit works for me on the unstable branch unless I click on the button very quickly. Then it starts acting out and counting up to really high numbers. Do you experience this is as well?

**Comment by avsingh999** [comment]
@

> @avsingh999 your edit works for me on the unstable branch unless I click on the button very quickly. Then it starts acting out and counting up to really high numbers. Do you experience this is as well?

@sashadev-sky  No, You can see in gif.
thank you  : )

**Comment by avsingh999** [comment]
> I solved the error #4589 when I ran the unstable branch, but it does not have to do with the error messages here. The reason the errors are failing here is because they are written in a deprecated syntax. https://github.com/hurrymaplelad/sinon-codemod
> 
> @avsingh999 would you be able to re-write them?
> This resource gives you the information you need:
> 
> 1. https://sinonjs.org/releases/latest/stubs/ writes about the `var stub = sinon.stub(object, "method", func);` syntax being deprecated and has the new syntax plus other information about testing.
> 
> * Both tests are directly related to the updates you are working on so it would be good to get them fixed so we can confirm everything is working as expected, even if you didn't cause them. And you will be able to double check on your own work  +1
> 
> @gauravano

Sorry to ask you but can you please tell me what I have to do? 
thanks : )

**Comment by sashadev-sky** [comment]
@avsingh999 yeah no problem. So even if you click like very fast like quadruple click it doesn’t glitch for you? 

Your tests are failing bc they’re deprecated so first step you need to re-write those. Testing the functionality of the like buttons. In development it is common practice to write the test before the code. Would be glad to work on this with you if you need! We can get on Gitter.  

Meanwhile I will look into ur code and let you know next steps there. The buttons are behaving weirdly in many different ways so I want to be sure that we figure out the root of the issue and your solution does not just patch up one part of the problem with a band aid if that makes sense. Because really clicking a button to like and unlike and updating the count should be simple. 

Does this sound good? 

I am getting set up on a new laptop right now and this may take a while longer but I can get on Gitter to chat if you want to discuss more.

**Comment by avsingh999** [comment]
pr_like

@jywarren  @SidharthBansal  @sashadev-sky  @gauravano 
we can if we click on like button then a node created for create like and if this process is not completing and then again click on like button it will also create like node and give an error because earlier node didn't complete the process The delete  node not created until and  unless  earlier like node complete the process.

I am confused what should I  do? please help me @jywarren  @SidharthBansal  @gauravano  @sashadev-sky 

Thank you
: )

**Comment by sashadev-sky** [comment]
@avsingh999 what does your server log in your terminal say?

**Comment by sashadev-sky** [comment]
@avsingh999 I found from your solution that it does not prevent the issue mentioned in #3524, but you can only tell this from looking at it in the unstable branch. In a localhost environment it always appears to be stable.

I made a workaround solution by chaining promises and disabling the button at certain points. Would you mind if I opened a different pull request for this? I want to address some other issues about likes all in one merge. And it would be great if you wanted to review it.

**Comment by sashadev-sky** [comment]
@avsingh999 I already opened it! let me know if you say any ways to refactor the code I feel as though its not very well written . Also did you manage to resolve the error you were receiving?

**Comment by avsingh999** [comment]
@sashadev-sky  I agree with you I also feel not written well. I was busy with my Academics so I didn't' try.
Thanks : )

**Comment by sashadev-sky** [comment]
@avsingh999 ahh need to fix that asap then. It was quite hard to refactor without changing around a lot of other code I think

**Comment by sashadev-sky** [comment]
@avsingh999 would you be okay with me closing this PR as I now have a separate one that addresses this issue and some others all in one place? As mentioned before any updates from you are welcome there :)

**Comment by avsingh999** [comment]
@sashadev-sky  Now I am closing this pr. And If any other issue for me please ping me. I want to work on this project 
thank you :smile:

**Pull request closed without merging**
