### PR TITLE
Update editor_controller.rb

### LINKED ISSUE #11502: replace "and" with "&&" editor-controller
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!

We know that the process of creating a pull request is one of the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [app/controllers/editor_controller.rb](https://github.com/publiclab/plots2/blob/main/app%2Fcontrollers%2Feditor_controller.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -35,12 +35,12 @@ def rich
       @main_image = Image.find_by(id: params[:main_image]).path
     end
 
-    if params[:tags]&.include? "lat:" and params[:tags]&.include? "lon:"
+    if params[:tags]&.include?("lat:") && params[:tags]&.include?("lon:")
       tags = params[:tags].split(',')
 
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in the comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

### PR DESCRIPTION
**Pull request by SylviaKaks**
Fixes #11502

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Hello, can you link us to the original issue for context? Thank you!

**Comment by SylviaKaks** [comment]
the original issue is #11502  @jywarren

**Comment by 7malikk** [comment]
> Fixes #0000
> 
> Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
> 
> * [ ]  PR is descriptively titled 📑 and links the original issue above 🔗
> * [ ]  tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
> * [ ]  code is in uniquely-named feature branch and has no merge conflicts 📁
> * [ ]  screenshots/GIFs are attached 📎 in case of UI updation
> * [ ]  ask `@publiclab/reviewers` for help, in a comment below

Hey there @SylviaKaks, I believe what @jywarren meant was you should include the issue number in its allocated spot i.e "Fixes #issue-number" in the initial PR

**Comment by SylviaKaks** [comment]
@7malikk thanks for the observation. I have rectified it.
 @jywarren kindly check out the code again, the issue link is included.

**Review by cesswairimu — APPROVED** [review]
Looks good :tada: thanks @SylviaKaks for working on this. Thanks Jeff and @7malikk for the reviews :heart:

**Comment by cesswairimu** [comment]
oh @SylviaKaks seems you already worked on a fto and someone else was already working on this here https://github.com/publiclab/plots2/pull/11507

**Comment by SylviaKaks** [comment]
@cesswairimu . I wanna try out working on more issues that may not be for first timers only but need to be rectified, just that i dont know where to find the code to work on when i open those issues

**Comment by cesswairimu** [comment]
@SylviaKaks do you have one that you are interested in and maybe we can try point you to the files? if so, ping me on the issue  comment with the question and we try figure them out.

**Comment by cesswairimu** [comment]
I will go ahead and close this

**Pull request closed without merging**
