### PR TITLE
Update seeds.rb

### LINKED ISSUE #8633: Change http to https in db/seeds.rb
🔊  **NOTE:** _(This issue is a part of Issue #8587 and has been claimed at the time of writing this issue. However, there are several places in the codebase where this change needs to happen, and issues haven't been made for each instance yet. If you are a first-time contributor, please refer to #8587 for more info on how to find instances of 'http' in the codebase. From there, you can make your own FTO issue and pull request to solve it.)_

Please see #8587 for more context behind this issue.

### PR DESCRIPTION
**Pull request by frankiefab100**
Update from http to https

Fixes #8633

### CODE REVIEW

**Comment by frankiefab100** [comment]
@cesswairimu please review

**Review by RuthNjeri — APPROVED** [review]
This looks good to me @frankiefab100

**Comment by cesswairimu** [comment]
Hey @frankiefab100, someone is already working on this issue here https://github.com/publiclab/plots2/pull/8597 
In future, kindly check if someone is working on an issue before you get started. You can get this info from the comments on the issue. If they have been working on an issue for a while and you can't find any pull request linked, ask them if you can take it up or if they are still working on it. Thanks

**Comment by frankiefab100** [comment]
Ok, thanks

**Review by cesswairimu — APPROVED** [review]
@frankiefab100 seems like the other contributor abandoned the PR. We will go ahead and merge this :tada: .
Thanks

**Pull request merged**
