### PR TITLE
Openid fix with post route and better alert texts

### LINKED ISSUE #2727: Fails to authenticate thru openid
### Please describe the problem (or idea)

Trying to login with spectralworkbench.org or mapknitter.org

> What happened just before the problem occurred? Or what problem could this idea solve?

Obtained error instead of authorization.

Logs:

```
Started POST "/openid/decision" for 190.113.212.64 at 2018-05-12 23:04:46 +0000
Processing by OpenidController#decision as HTML
  Parameters: {"authenticity_token"=>"mZGIfx021goan3ba1XNmpj2U3SJmEfAq7SaLO/rpyZTIhILocj420u+9P7ml+XGUWoU3bR3er9bccA==", "yes"=>"Yes"}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.5ms)

NoMethodError (undefined method `identity' for nil:NilClass):
  app/controllers/openid_controller.rb:182:in `decision'


```

****

Delaney originally wrote in to web@publiclab.org:

> Bug trying to log in to mapknitter.org with my publiclab log in!  "There was an error, sorry for the trouble" right after clicking "login".  womp.

Sebastian confirmed:

> I can confirm, I get "empty response" from here - and seeing the same thing at spectralworkbench.org.
> As if our openid endpoint were broken somehow.
> Also I see 500 error now.

### LINKED ISSUE #2813: Better testing for SpectralWorkbench/MapKnitter single-sign-on (OpenID)
Read about our OpenID-based signon system here: 

https://github.com/publiclab/plots2/blob/master/doc/OPENID.md

We should brainstorm ways to test these out with automated testing. 

Maybe we can capture from logs representative openid requests and use them to build tests?

### PR DESCRIPTION
**Pull request by jywarren**
Should fix #2727 I believe! And fixes #2813

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
Did this removed the no logged that was occuring @jywarren

**Comment by jywarren** [comment]
I believe so, I was able to log in locally using the new test steps in
/doc/OPENID.md

**Comment by jywarren** [comment]
Error: 

```
 FAIL["test_openid_authentication_request_goes_to_index_page", Minitest::Result, 13.438274217000014]
 test_openid_authentication_request_goes_to_index_page#Minitest::Result (13.44s)
        Expected response to be a redirect to <https://spectralworkbench.org/session/new?authenticity_token=RcLcGH3lzSTCC24UpPnNm56sllNaMrHg5%2FSrQzNxB%2B4%3D&back_to=&open_id=jeff&return_to=&openid.assoc_handle=%7BHMAC-SHA1%7D%7B5b1d6e45%7D%7Bs15kdQ%3D%3D%7D&openid.claimed_id=https%3A%2F%2Fspectralworkbench.org%2Fopenid%2Fjeff&openid.identity=https%3A%2F%2Fspectralworkbench.org%2Fopenid%2Fjeff&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.op_endpoint=http%3A%2F%2Fwww.example.com%2Fopenid&openid.response_nonce=2018-06-10T18%3A30%3A29Zecgnhd&openid.return_to=https%3A%2F%2Fspectralworkbench.org%2Fsession%2Fnew%3Fauthenticity_token%3DRcLcGH3lzSTCC24UpPnNm56sllNaMrHg5%252FSrQzNxB%252B4%253D%26back_to%3D%26open_id%3Djeff%26return_to%3D&openid.sig=soIlLug0jDZr3qOyDJSLGxMmik4%3D&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cns.sreg%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Csigned%2Csreg.email%2Csreg.nickname&openid.sreg.email=jeff%40pxlshp.com&openid.sreg.nickname=jeff> but was a redirect to <https://spectralworkbench.org/session/new?authenticity_token=RcLcGH3lzSTCC24UpPnNm56sllNaMrHg5%2FSrQzNxB%2B4%3D&back_to=&open_id=jeff&return_to=&openid.assoc_handle=%7BHMAC-SHA1%7D%7B5b1d7151%7D%7BeGEqFw%3D%3D%7D&openid.claimed_id=https%3A%2F%2Fspectralworkbench.org%2Fopenid%2Fjeff&openid.identity=https%3A%2F%2Fspectralworkbench.org%2Fopenid%2Fjeff&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.op_endpoint=http%3A%2F%2Fwww.example.com%2Fopenid&openid.response_nonce=2018-06-10T18%3A43%3A29ZnUDDmn&openid.return_to=https%3A%2F%2Fspectralworkbench.org%2Fsession%2Fnew%3Fauthenticity_token%3DRcLcGH3lzSTCC24UpPnNm56sllNaMrHg5%252FSrQzNxB%252B4%253D%26back_to%3D%26open_id%3Djeff%26return_to%3D&openid.sig=RHo3NwfUlkCz6TFxhQZDoBxvBgI%3D&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cns.sreg%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Csigned%2Csreg.email%2Csreg.nickname&openid.sreg.email=jeff%40pxlshp.com&openid.sreg.nickname=jeff>.
        Expected "https://spectralworkbench.org/session/new?authenticity_token=RcLcGH3lzSTCC24UpPnNm56sllNaMrHg5%2FSrQzNxB%2B4%3D&back_to=&open_id=jeff&return_to=&openid.assoc_handle=%7BHMAC-SHA1%7D%7B5b1d6e45%7D%7Bs15kdQ%3D%3D%7D&openid.claimed_id=https%3A%2F%2Fspectralworkbench.org%2Fopenid%2Fjeff&openid.identity=https%3A%2F%2Fspectralworkbench.org%2Fopenid%2Fjeff&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.op_endpoint=http%3A%2F%2Fwww.example.com%2Fopenid&openid.response_nonce=2018-06-10T18%3A30%3A29Zecgnhd&openid.return_to=https%3A%2F%2Fspectralworkbench.org%2Fsession%2Fnew%3Fauthenticity_token%3DRcLcGH3lzSTCC24UpPnNm56sllNaMrHg5%252FSrQzNxB%252B4%253D%26back_to%3D%26open_id%3Djeff%26return_to%3D&openid.sig=soIlLug0jDZr3qOyDJSLGxMmik4%3D&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cns.sreg%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Csigned%2Csreg.email%2Csreg.nickname&openid.sreg.email=jeff%40pxlshp.com&openid.sreg.nickname=jeff" to be === "https://spectralworkbench.org/session/new?authenticity_token=RcLcGH3lzSTCC24UpPnNm56sllNaMrHg5%2FSrQzNxB%2B4%3D&back_to=&open_id=jeff&return_to=&openid.assoc_handle=%7BHMAC-SHA1%7D%7B5b1d7151%7D%7BeGEqFw%3D%3D%7D&openid.claimed_id=https%3A%2F%2Fspectralworkbench.org%2Fopenid%2Fjeff&openid.identity=https%3A%2F%2Fspectralworkbench.org%2Fopenid%2Fjeff&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.op_endpoint=http%3A%2F%2Fwww.example.com%2Fopenid&openid.response_nonce=2018-06-10T18%3A43%3A29ZnUDDmn&openid.return_to=https%3A%2F%2Fspectralworkbench.org%2Fsession%2Fnew%3Fauthenticity_token%3DRcLcGH3lzSTCC24UpPnNm56sllNaMrHg5%252FSrQzNxB%252B4%253D%26back_to%3D%26open_id%3Djeff%26return_to%3D&openid.sig=RHo3NwfUlkCz6TFxhQZDoBxvBgI%3D&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cns.sreg%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Csigned%2Csreg.email%2Csreg.nickname&openid.sreg.email=jeff%40pxlshp.com&openid.sreg.nickname=jeff".
        test/integration/openid_test.rb:86:in `block in <class:LoginFlowTest>'
....*** Error in `/usr/local/bin/ruby': free(): invalid pointer: 0x000000000ca7c6b0 *** 
```

**Comment by jywarren** [comment]
Yay!!!

**Pull request merged**
