### PR TITLE
Removed de.yml files from /config/locales/

### LINKED ISSUE #2549: Remove German auto-translations until we can do true translation
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

The German translations, for example:

https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/_responses/de.yml

Are auto-translated, and we've received feedback from 

These were added originally to demonstrate our i18n system, which is great! However, I think we should remove them until we can develop a system for true translation, perhaps as part of #2530 

For now, if someone could remove the various `de.yml` files in `/config/locales/`, that would be great!

This could be made into a lot of first-timers issues with https://github.com/hoodiehq/first-timers-bot, potentially? Although I don't know how it handles file deletion. Could be worth a try!

### PR DESCRIPTION
**Pull request by bld456**
fixes #2549

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] code is in uniquely-named feature branch and has no merge conflicts
* [ x] PR is descriptively titled
* [x ] PR body includes `fixes #0000`-style reference to original issue #
* [x ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by bld456** [comment]
Hello @publiclab/reviewers 

This is my first contribution, please let me know if it all looks good.

**Comment by Gauravano** [comment]
hi @jywarren , can @bld456 also remove the "language" dropdown from the footer ?

**Comment by jywarren** [comment]
I removed it in #2565  -- so this looks super! Is it ready to go?

**Comment by bld456** [comment]
I've been ill. Hopefully I'll be able to continue my work over the weekend.

**Comment by jywarren** [comment]
Oh, i'm sorry to hear it! Best wishes and please don't worry about this until you're ready. Thank you!

**Comment by bld456** [comment]
Ok, I removed the one file I missed earlier

**Comment by Gauravano** [comment]
That's great !!! Thanks, @bld456 for completing this.

**Comment by Gauravano** [comment]
As @bld456 , if you are interested in solving more issues, you can find at https://publiclab.github.io/community-toolbox/#r=all .Thanks.

**Comment by jywarren** [comment]
Amazing!!! 👍 👍 🎉

**Pull request merged**
