### PR TITLE
Fixed duplicate pagination in search

### LINKED ISSUE #4079: Problems with the /search/notes
### Please describe the problem (or idea)
The `Read More` buttons aren't aligned uniformly.

screenshot 40
and
There are two `pagination bars` on the same page.

screenshot 41

I remember similar issues being open on the panel but I think they were opened for editing of different pages. @publiclab/mentors 

### Please show us where to look
https://publiclab.org/search/notes/balloon

### What's your PublicLab.org username?
oorjit_chowdhary
### Browser, version, and operating system
Chrome, Windows 10
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by conkytom**
Fixes #4079 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

The bottom of each search view had the `will_paginate` function, but the partials that the views rendered also contained the `will_paginate` function so there were duplicates.  I left the `will_paginate` in the partials and removed them from the various search views of notes, questions, and wikis.  Hope this does the trick.

### CODE REVIEW

**Comment by conkytom** [comment]
Hey @publiclab/reviewers, hoping you could prove that removing these duplicates works and makes sense.

**Comment by oorjitchowdhary** [comment]
@conkytom Great work.. Just attach a screenshot/gif for the mentors to approve the PR.

**Comment by conkytom** [comment]
Sure thing,

Before:
screen shot 2018-12-01 at 2 37 12 pm


After:
screen shot 2018-12-01 at 2 39 33 pm

**Comment by jywarren** [comment]
I think this one looks great - just looked carefully through the code. Thanks a lot!

**Pull request merged**
