### PR TITLE
Like with emoji

### LINKED ISSUE #2822: Ability to "like" comments with an emoji
https://github.com/publiclab/plots2/issues/2498 and the solution https://github.com/publiclab/plots2/pull/2591 allowd for comment likes that have a "type". 

Let's imagine how to use that field to represent an emoji response -- like "smile" :smile: or "tada" 🎉  or "+1" 👍 

Then people could choose one (we might just offer a few common ones like GitHub does in comments) and people could provide feedback the same way as here in GitHub! Very friendly!

screen shot 2018-06-11 at 12 28 10 pm

### PR DESCRIPTION
**Pull request by ViditChitkara**
closes #2822 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
emoji-like-3

**Comment by jywarren** [comment]
Ah, can you rebase, sorry! This looks AMAZING!!!

!

**Comment by jywarren** [comment]
And, anything you want to tweak from CodeClimate suggestions, or just approve it?

**Comment by jywarren** [comment]
Looking great! Ready to go? 😄

**Comment by ViditChitkara** [comment]
Yes!!

**Comment by jywarren** [comment]
So excited!!!

**Comment by ViditChitkara** [comment]
Me too!!

**Comment by jywarren** [comment]
screen shot 2018-06-20 at 6 33 29 pm

**Comment by jywarren** [comment]
on staging! we hope to publish tomorrow 😄

**Pull request merged**
