### PR TITLE
Hacktoberfest commit

### PR DESCRIPTION
**Pull request by kirtiwardhan-18**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by RuthNjeri — COMMENTED** [review]
Looks good to me @kirtiwardhan-18 !

**Review by Tlazypanda — COMMENTED** [review]
Hey @kirtiwardhan-18 This issue has already been claimed and worked on by @yashmohan100 in #8588  please check the thread before working on issues :sweat_smile: Thank you!

**Comment by kirtiwardhan-18** [comment]
ok

**Comment by cesswairimu** [comment]
Closing this.  @kirtiwardhan-18 feel free to comment here #7683 if you are still looking for a first-timer-issue. Thanks everyone.

**Pull request closed without merging**
