### PR TITLE
updated config/locales/en.yml

### PR DESCRIPTION
**Pull request by Tilakraj0308**
918          video: "Watch a 30 second video on posting research notes &raquo;"
+919      rich:
+920        drag_image: "Drag an image here to upload."

Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Tilakraj0308** [comment]
May I know why my merging is blocked?

**Comment by noi5e** [comment]
> May I know why my merging is blocked?

@Tilakraj0308, every pull request needs to be reviewed by someone that's not the author, before it can be merged.

Right now you have TWO pull requests open, one at #10181 and the other one at #10182.

What you actually want is ONE pull request. You need to close one of the PRs, and pick the other one.

Let's say you pick this one. You'll need to push another commit to the branch `Tilakraj0308:patch-2` updating `rich.html.erb`.

Let me know if you need any help figuring this out!

**Comment by noi5e** [comment]
Oh also, can you edit this number so that it says the number of the issue you are working on?

`Fixes #0`

Thank you!

**Comment by Tilakraj0308** [comment]
ooh okay I will do that thankyou

**Pull request closed without merging**
