### PR TITLE
Follow up to #9849 - 2 normal tag cards and 1 power tag card shows up in the sidebar

### PR DESCRIPTION
**Pull request by Manasa2850**
Follow up PR to #9849

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Sorry I had missed this in #9849. This change ensures that the number of tag cards in the sidebar is not more than 2, irrespective of whether they are power tags or normal tags.

### CODE REVIEW

**Review by jywarren — COMMENTED** [review]
Looking good so far! Is this ready for final review and merge? Thanks!

**Comment by Manasa2850** [comment]
No @jywarren this is not ready yet. There are some issues with the remaining tags getting displayed. I'm trying to fix that!

**Comment by jywarren** [comment]
OK, great. thank you!!!

**Comment by Manasa2850** [comment]
@jywarren this is how it looks now. We can have a maximum of 3 tags in the sidebar at any given time (2 normal tags + 1 power tag).

ezgif com-gif-maker

**Comment by jywarren** [comment]
> @jywarren this is how it looks now. We can have a maximum of 3 tags in the sidebar at any given time (2 normal tags + 1 power tag).
> 
> ezgif com-gif-maker

This looks good! Would it be possible to keep the small power tags grey? And I think a little more spacing may be needed as I see one of the tags gets inserted really close to the box below it. Would it be possible to make these tweaks and then we'll merge it? Thank you!!!

**Comment by jywarren** [comment]
image

**Pull request merged**
