### PR TITLE
Highlight section added

### PR DESCRIPTION
**Pull request by Gauravano**
solves #1777 
Hey @jywarren sir, as described by you in issue #1777 , I have added highlight section, please review it and suggest changes regarding CSS.Thank you.Here's the preview of page after addition 

pull_highlight

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great -- could we perhaps make each text area an `h3` and center them as well? Then this looks good to go, thanks so much!

**Comment by Gauravano** [comment]
@jywarren sir, here are the updated pics of profile page after changing to h3 tag and aligning to center
Also, for all screen sizes, highlight section will appear optimized.

pull_high5

pull_high4


pull_high3

pull_high1

**Comment by jywarren** [comment]
Oh, this is so cool! Thanks and the screenshots especially helped!

**Comment by jywarren** [comment]
Hey, you're doing some great work, and we really appreciate it! Do you have any interest in helping to prepare some `first-timers-only` issues yourself, or respond to some other submissions to help others along? 

There's some guidance on this here, and we'd love to have your involvement: https://github.com/publiclab/plots2/projects/4

**Comment by Gauravano** [comment]
I would love to help first-timers in solving their first issue and create issues too.Will see it too apart from contributing.

**Pull request merged**
