### PR TITLE
Using errorMessage partial

### LINKED ISSUE #4622: Refactor old `error_messages` usage in form helpers
I found some very old code in #4575 which I removed, but realized that we still use the `f.error_messages` code in our form error templates; you can see it in all these search results:

https://github.com/publiclab/plots2/search?q=error_messages&unscoped_q=error_messages

Errors should instead be in format:

```ruby
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
```

I believe this will resolve https://github.com/publiclab/plots2/issues/4521 as well because the duplicate "email already taken" error will be better handled with a modern Rails error reporting approach, as in the docs here: 

https://guides.rubyonrails.org/active_record_validations.html#displaying-validation-errors-in-views

If it helps, see when the old plugin code was originally added here:

https://github.com/publiclab/plots2/commit/4f13238a4837356d3bbf4cfffd7d14a24e7e42dc

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #4622 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
@jywarren @cesswairimu could you please help me out with the tests failing in `app/views/users/_create_form.html.erb` ?
The signup page looks fine. The tests are failing because of the error message `1 error prohibited this user from being saved`.  But I'm not really sure why there's an issue with just that particular error message and not anything else :thinking: 
Thanks!

**Comment by cesswairimu** [comment]
Hey @Manasa2850  its because in the new partial for error messages we do not have that phrase...adding it should fix this errors..maybe replace this line https://github.com/publiclab/plots2/blob/main/app/views/layouts/_errorMessages.html.erb#L3  with something like 
```
 <h2><%= pluralize(model.errors.count,"error")%> prohibited this <%= model.class.to_s.downcase %> from being saved </h2>
```
what do you think?

**Comment by Manasa2850** [comment]
Thanks a lot @cesswairimu! That worked :partying_face:

**Comment by cesswairimu** [comment]
Great :tada: I will create a fto follow up for that. Thanks...merging now

**Review by cesswairimu — APPROVED** [review]
:tada:

**Comment by Manasa2850** [comment]
Hi @cesswairimu, there is already a [PR](https://github.com/publiclab/plots2/pull/4575) for that made by @jywarren. I'll close and reopen that to check if that passes all the tests now. Thanks!

**Comment by cesswairimu** [comment]
awesome, thanks

**Pull request merged**
