### PR TITLE
Wiki link added to navbar closes #2167

### LINKED ISSUE #2167: Add wiki link to navbar
### Please describe the problem (or idea)
We currently don't have any link on the dashboard to directly access the wiki pages. It would be convenient for the user to have wiki page link directly on the heading bar 

### Please show us where to look

Any page after user have logged in:

### What's your PublicLab.org username?
namangupta
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Closes #2167 
* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
Hows it looks now!
screen shot 2018-01-30 at 11 46 41 pm

**Comment by SidharthBansal** [comment]
As suggested by @jywarren as he is busy and wants a quick merge process, I found that this is a need for public lab so I have approved the pr.
Great suggestion @namangupta01

**Comment by namangupta01** [comment]
Awesome, Thanks!

**Comment by jywarren** [comment]
Hi! I like the idea here, but we should coordinate changes to the navbar with @ebarry and the communities team; there's this issue to track various changes to it: #1621 

I wonder if they'd prefer we tuck this into one of the menus to be sure we don't crowd the top. Let's see what they say! 

Thanks!

**Comment by namangupta01** [comment]
@jywarren sure 👍

**Comment by jywarren** [comment]
Via @publiclab/community-reps I think we need to hold off on this a bit -- navbar space is precious and we're hoping to enable more ways into the wiki via the topics page! Thank you for your work on this, though!!!

**Pull request closed without merging**
