### PR TITLE
#fixes3493 Updated config.yml to add GIF

### PR DESCRIPTION
**Pull request by Dhiraj240**
Fixes https://github.com/publiclab/plots2/issues/3493

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Dhiraj240** [comment]
@publiclab/reviewer

**Comment by Dhiraj240** [comment]
@publiclab/reviewer Please Review

**Comment by SidharthBansal** [comment]
Please use @publiclab/mentors this is the new group

**Comment by SidharthBansal** [comment]
@Dhiraj240 just write the line #fixes ____ On the first line of PR body.
It is not compulsory to be at top but helps in reviewing a lot.
Thanks

**Comment by Dhiraj240** [comment]
Alright, i will follow this.

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. 👍 🎉  If you're looking for a new challenge, please take a look at https://code.publiclab.org#r=all; we prefer to leave `first-timers-only` issues for complete newcomers, but there are plenty of others we need help with! Thanks!

**Comment by Dhiraj240** [comment]
@jywarren Yes, i am looking for ```help wanted ``` issues.I will soon ask for assignment.

**Comment by Dhiraj240** [comment]
[@Dhirajking3](https://twitter.com/Dhirajking3) is my twitter handle.

**Pull request merged**
