### PR TITLE
Fix #1801 by adding performance tests

### LINKED ISSUE #1801: Add performance tests for leading pages, like / and /dashboard
https://github.com/publiclab/plots2/blob/8e6ec5a29a7ebb4c873cf5b953468addc1df6547/test/performance/browsing_test.rb#L10

This is documented at https://rubygems.org/gems/rails-perftest (as of Rails 4, which we're moving to shortly)

@icarito - just a note!

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
@bellvat @jywarren Testing it over here, let's see how it goes.

**Comment by ryzokuken** [comment]
@jywarren this must be failed for master as well, then, because clearly none of the changes here must've caused a problem like this.

**Comment by jywarren** [comment]
If you go to the Travis tests, it looks like they made some kind of change
to the Travis images today... upgrading to trusty or something. But I
haven't been able to google to find other people experiencing this...

**Comment by ryzokuken** [comment]
@jywarren This is what I feared. Our Dockerfile was way too old.

**Comment by jywarren** [comment]
These lines: https://github.com/publiclab/plots2/blob/2bac71401da712f1add4645c8eda56a1907e5730/test/test_helper.rb#L9-L12

**Comment by ryzokuken** [comment]
@jywarren how should I proceed? Should I just remove all the perf testing code? I could make another PR for the Dockerfile that you could merge before this.

**Comment by ryzokuken** [comment]
@jywarren okay, commented out the lines and got the exact same error, I think those lines are the root of our problem.

**Comment by jywarren** [comment]
Hi - I'd like to just update the Dockerfile with your fixes. Instead of unadding all the files here, i'm going to open a new PR with just that change, to disambigute it. Then the work in #1861 should proceed on top of that. #1881

**Pull request closed without merging**
