### PR TITLE
Unlike feature not working #1870

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

solves #1870

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
The fail here was due to some upstream dependencies not loading, unrelated to your code. I've restarted the tests!

**Comment by jywarren** [comment]
Hm, interesting! This tripped an error in Jasmine -- our JavaScript test framework:

```

Faked response to: /likes/node/1/create
4
Plots2 unlikes a request if already liked
  Expected '1' to equal '0'.
``` 

Take  look in the `/spec/` folder for these, maybe there's a clue related to your code changes?

**Comment by sagarpreet-chadha** [comment]
Test is failing in this line :
https://github.com/publiclab/plots2/blob/c9879a9c84a3e7de67cb204b8c96be25a6a58fad/spec/javascripts/plots2_spec.js#L86

**Comment by jywarren** [comment]
Cool -- happy new year -- i'm back from break and ready to get going again; how does this look? Ready to go?

**Comment by sagarpreet-chadha** [comment]
Happy new year sir ! Yes it solves the issue 👍

**Comment by jywarren** [comment]
No need for "sir"! Jeff will do fine -- glad to be back!

**Comment by sagarpreet-chadha** [comment]
Okay :)

**Pull request merged**
