### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #0000 (<=== Add issue number here)
@publiclab/mentors Basic change here which I thought could be added. Hope you'll like it!
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Thanks Oorjit

**Comment by SidharthBansal** [comment]
Can you please assist people in their PRs?
We are having a tough time in reviewing PRs. Let's try to reduce some PR backlog.
Thanks a lot!!! :100:

**Comment by SidharthBansal** [comment]
Only Jeff can grant permissions at PL. In the meantime you can just help
folks asking questions, just answer their questions and suggest changes to
their codes. Thanks Oorjit. You are really helpful.

@jywarren can you please give him required permissions?
Thanks Jeff for your time.

**Comment by oorjitchowdhary** [comment]
Yes sure, I'll do that.. 
@jywarren hats off to your commitment and energy!

**Pull request merged**
