### PR TITLE
PR to Hide profile bio content unless users have had some content approved

### LINKED ISSUE #6584: Planning issue: Hide profile bio content unless users have had some content approved
**Please describe the desired behavior:**

This is a planning issue to review the issue of spammy bio content in profile pages. 

**Problem:** many users create spam profiles with live links to illegal and harmful activities, links which may live on for years on our infrastructure. There is currently no "Gate" on creating profiles with bio content that instantly goes live. 

**Proposal:** to allow new profile creation, but to not display any profile bio content (including links, pictures) unless users have been approved for something. 

**How would this work?**

New people could still create a profile page, but the bio content would be hidden until they had some kind of post approved (comment, note, or question) and until that first approval, we could display a message in the place of the bio content explaining the status. 

Needs to further explore how to hold custom profile images in a queue, although it would be a little more complex as those are used around the site not just on the profile page. 

**Background**

While the presence of spammy profiles had long been regarded as irrelevant to the health of our website and safe to ignore, our position is this is now changing. Why? Because of the growing awareness of illegal and harmful activities which our infrastructure is hosting and allowing to be live on the internet. 

**Additional context**

A significant amount of work on detecting and screening for spam profiles has been undertaken here: https://github.com/publiclab/plots2/issues/5450

### PR DESCRIPTION
**Pull request by shubhankarsharma00**
Fixes #6584 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
(The system tests on the PR are probably failing because of UI changes to core features in profile but I'm not sure)
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
approved user:
image
unapproved user:
image

* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by shubhankarsharma00** [comment]
@publiclab/reviewers please help me with the CI fails :smiley:.
Thank you

**Comment by shubhankarsharma00** [comment]
Can someone please help me with the CI fails?

**Comment by nstjean** [comment]
@jywarren Maybe we can refactor this in the future, create a function to check if a user is approved to reduce code duplication?

**Comment by ebarry** [comment]
Thanks @nstjean!
I'd love to see this pull request make it all the way through to merge.

**Comment by ebarry** [comment]
Very excited about this PR!

**Comment by shubhankarsharma00** [comment]
> Very excited about this PR!

So am I given this is my first PR in PL :sweat_smile: 
Can the PR be merged or should I refactor it to reduce duplication.

**Comment by jywarren** [comment]
Hi, this is really great. I do think a little refactor would be nice though - could we make a variable like `@content_approved` in the controller for this view, probably users_controller.rb in `def profile`, and say, 

```ruby
@content_approved = !(Node.where(status: 1, uid: @profile_user.id).empty?) or !(Comment.where(status: 1, uid: @profile_user.id).empty?)
```

Then we can do it more efficiently? 

Or if you want, you could add `def content_approved` to `/app/models/user.rb` and we could, in the view, use it like:

```ruby
@profile_user.content_approved
```

Does this make sense?

Thanks!

**Comment by shubhankarsharma00** [comment]
I think making the variable on the controller page should do enough given we only want to hide data on the profile page.

**Comment by ebarry** [comment]
Thanks for working on this @shubhankarsharma00 and @jywarren !

**Comment by jywarren** [comment]
Very nicely done, thank you!

**Comment by shubhankarsharma00** [comment]
@jywarren I am not sure but I think my PR was failing because of some tests that made sure Profile Pic and Bio was displayed, don't we need new tests for this behavior?

**Comment by jywarren** [comment]
Hm, I don't see that any tests were removed or modified in your PR, so I think we are OK, but if you'd like to add additional tests that's always welcome! Thanks!

**Pull request merged**
