### PR TITLE
Browser Notification for like

### LINKED ISSUE #6152: Notification when someone likes your note
Currently, we are showing the notification to the users when they are mentioned in the comments we can extend this feature to receive a notification when any user likes any research note.

### PR DESCRIPTION
**Pull request by namangupta01**
Closes #6152

### CODE REVIEW

**Comment by jywarren** [comment]
Not sure what the test issue is here:

```
ERROR["test_posting_from_the_editor", #<Minitest::Reporters::Suite:0x00007f2128c0c218 @name="PostTest">, 152.30244121099997]
 test_posting_from_the_editor#PostTest (152.30s)
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find field "title-input" that is not disabled
            test/system/post_test.rb:17:in `block in <class:PostTest>'
[Screenshot]: tmp/screenshots/test_viewing_the_dashboard.png
[Screenshot]: tmp/screenshots/test_viewing_the_dashboard.png
[Screenshot]: tmp/screenshots/test_viewing_the_dropdown_menu.png
[Screenshot]: tmp/screenshots/test_viewing_the_dropdown_menu.png
[Screenshot]: tmp/screenshots/test_viewing_question_post.png
  26/26: [=================================] 100% Time: 00:02:39, Time: 00:02:39
```

Anyone else see this? Maybe a timing issue?

**Comment by namangupta01** [comment]
This time some other system task failed.
```
[Screenshot]: tmp/screenshots/test_viewing_the_settings_page.png
ERROR["test_viewing_the_settings_page", #<Minitest::Reporters::Suite:0x00007f1fe91a3938 @name="SettingsTest">, 87.68355271099995]
 test_viewing_the_settings_page#SettingsTest (87.68s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `id' for nil:NilClass
            app/views/users/settings.html.erb:10:in `_app_views_users_settings_html_erb___973123561756534354_69887415178400'
````

**Comment by namangupta01** [comment]
Different error this time :(
```
ERROR["test_blog_page_with_location_modal", #<Minitest::Reporters::Suite:0x000055bce9190180 @name="ScreenshotsTest">, 66.53775383100003]
 test_blog_page_with_location_modal#ScreenshotsTest (66.54s)
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find css "a.blurred-location-input"
            test/system/screenshots_test.rb:100:in `block in <class:ScreenshotsTest>'
```

**Comment by namangupta01** [comment]
Finally, it passed! Can we merge this?

**Comment by jywarren** [comment]
Yep! Looks great!

**Pull request merged**
