### PR TITLE
Added color style tag

### PR DESCRIPTION
**Pull request by newbazz**
fixes https://github.com/publiclab/plots2/issues/5865

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
Hi @newbazz, you can use this feature to replicate the view. This is a feature code. 

https://gist.github.com/gauravano/74bce8a56139d2c0037e1a07a3666f38  

So, you have to login as admin and then go to /features. And, create a new feature with the name `questions-header`. Hard refresh and then go to /questions page. You'll see the same view as shown in the issue screenshot. 

Now, try to solve the issue. Let me know if you need any help. Thank you!

**Comment by newbazz** [comment]
@gauravano i am still not getting where the bot is failing, it says, *i have to add color style tag* and that is what i have done.

**Comment by gauravano** [comment]
Hey @newbazz, please ignore that warning. You can see no test is failing. But, this issue needs to be solved by creating a feature and then working on it and adding style tag directly will not work.

**Comment by newbazz** [comment]
Yeah so i have 2 features here
image
So the issue is that they are not showing in the `/questions` url right?
I just wan to know if i have got the question or not

**Comment by newbazz** [comment]
@gauravano i have pushed changes, can you please have a look

**Pull request closed without merging**
