### PR TITLE
renaming tools to methods

### LINKED ISSUE #857: Rename /tools to /methods, add redirect and change page title
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

This could be 2-3 first timers issues, or just solve it yourself!

****

Our `/tools` page is now being moved to `/methods`, and the title changed to Methods. We need to:

* change `def tools` method to be `def methods`: https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L60-L68
* add back a `def tools` which is just a redirect: `redirect_to '/methods'` in  https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L60
* change the title of the page. The template itself is at https://github.com/publiclab/plots2/blob/master/app/views/notes/tools_places.html.erb#L25, but it uses a locale file at https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/tools_places/en.yml#L6 and a matching German one at https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/tools_places/de.yml#L6

(See discussion on this question: https://publiclab.org/notes/liz/09-30-2016/should-tools-be-renamed-to-methods-techniques-or-something-else)

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

closes #857 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks perfect -- but now the [test expectations](https://travis-ci.org/publiclab/plots2/builds/178503587#L2661) are not going to be quite right -- on this line, the automated tests expect a `success` (code `200`), but they're now being redirected. Let's update those tests to confirm a redirect for requests to `/tools` --

https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L95-L100

and add a new test below it for `success` for requests to `/methods`, sound good?

Testing for a redirect can be done with `assert_redirected_to('/methods')`

Also note [this error](https://travis-ci.org/publiclab/plots2/builds/178503587#L2681) in the internationalization tests, which fails on this line:

There, we can just change `/tools` to `/methods`: 

https://github.com/publiclab/plots2/blob/master/test/integration/I18n_test.rb#L530

Make sense? These tests ensure that these features aren't broken by future contributions, but when we change such a basic behavior as we're doing in this PR, we often have to update our test assertions to match. 

Thanks a lot, this is great!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by ryzokuken** [comment]
Hello! You must've noticed that the unit tests failed unexpectedly on your PR. This was due to some issue in the Travis CI testing configuration which was fixed by @jywarren later tonight. In order to make them work again, please rebase your work on top of the current master and then try pushing to your remote branch. Do this by:

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <my-branch>
$ git rebase master
$ git push origin <my-branch>
```

Thanks for bearing with us,
Ujjwal

**Comment by mridulnagpal** [comment]
@jywarren 
When I try to fetch upstream. This error appears

fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ryzokuken** [comment]
What's the output of `git remote`?

**Comment by jywarren** [comment]
Maybe we need input from @ryzokuken on this one -- i haven't actually used
`git fetch upstream` myself. I think it's just getting copies of all the
publiclab/plots2 branches, no? Does `upstream` need to be replaced with `
https://github.com/publiclab/plots2.git` ?

**Comment by ryzokuken** [comment]
Yes, upstream is a remote that points to `publiclab/plots`. You need to add the remote first in order to use it.

**Comment by mridulnagpal** [comment]
so I fetch https://github.com/publiclab/plots2.git first then what?

**Comment by ryzokuken** [comment]
And merge its master with local master, so that you can rebase your branch on top of master

**Comment by mridulnagpal** [comment]
So won't I directly do git pull https://github.com/publiclab/plots2.git when I am in master branch

**Comment by ryzokuken** [comment]
Adding a remote and then using it proves to be easier and less time-consuming. However, you may do it the way that works for you.

**Comment by mridulnagpal** [comment]
What would be my merge command if I use git fetch https://github.com/publiclab/plots2.git

**Comment by ryzokuken** [comment]
Sorry, but I have no idea. Try doing that and then execute `git branch -r`. I could probably help you when equipped with the output of that command.

**Comment by mridulnagpal** [comment]
git branch -r
  origin/Fix_solr_indexer
  origin/HEAD -> origin/master
  origin/ansible_wip
  origin/consolidate-tags
  origin/fix/post-to-editor
  origin/jywarren-patch-1
  origin/jywarren-patch-2
  origin/master
  origin/node-subscription-main-image
  origin/post-to-editor
  origin/response-count
  origin/revert-201-data-url-based-image-uploads
  origin/revert-550-q_and_a
  origin/separate-map-template
  origin/stable
  origin/tag-index-features
  origin/tag-index-wiki-preview-fix

**Comment by jywarren** [comment]
```ruby
Failure: Expected response to be a <:success>, but was <301>.
test_should_get_tools(NotesControllerTest)
test/functional/notes_controller_test.rb:98:in `block in <class:NotesControllerTest>'
```

and

```ruby

```

So the tests must be adjusted now to reflect the new redirect behaviors:

https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L95-L100

https://github.com/publiclab/plots2/blob/master/test/integration/I18n_test.rb#L529

See how they still presume `/tools` ? The functional test may need separate tests for the redirect and the new `/methods` action, and the integration test probably just needs to be adjusted to go to `/methods` instead of `/tools`. 

Hope that helps!

**Comment by 500swapnil** [comment]
@mridulnagpal Try using
git remote add upstream https://github.com/publiclab/plots2.git
Then follow the commands given and replace '<my-branch>' with 'master'

**Comment by jywarren** [comment]
Hi, yes -- i think @500swapnil is right --

But just to be clear, because we can squash/merge here, I think it's OK to just fix the test expectations as I outlined above, and add those commits. We'll be squashing the whole sequence into a single commit, so while this now has some slightly messy merge commits, those won't be reflected in the commit history once it's all squashed. We can tell this by looking at the "files" tab above and examining the changes that result from the whole set. 

Thanks!

**Comment by mridulnagpal** [comment]
@jywarren This also has multiple commits but the files changed are the same..

**Comment by mridulnagpal** [comment]
I restarted from scratch and put up another PR regarding the same #1084

**Pull request closed without merging**
