### PR TITLE
 [WIP] :  Fixes #299

### LINKED ISSUE #299: Codifying a callout codifies the callout link
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
I was writing a research note comment trying to refer to `@publiclab` on twitter. I used the code ticks to prevent `@publiclab` from turning into a link:

```
`@publiclab`
```

What happened instead was that the link for publiclab's profile in Markdown (`[@publiclab](/profile/publiclab)`) got codified. It wasn't a clickable link, but rather displayed just as shown here.

The callout replacement should not execute inside of any code or quote areas.

## Solution
The simplest way of fixing this is changing the regexp of the `FINDER` we are using for the callout. Here is the regexp for the finder https://github.com/publiclab/plots2/blob/master/config/initializers/constants.rb#L2

We should change the regexp to
```
/(^|\s)\@([\w-]+)/
``` 
i.e. use a `\s` instead of `\W` so that mentions like `@publiclab` are only recognized when there is a space before the `@` symbol. This also solves a issue that was occurring due to the wrong use of regexp where even if you used a non-word symbol before `@` it was recognized as a mention which shouldn't happen.

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

### PR DESCRIPTION
**Pull request by StlMaris123**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
OK, great, thanks! So, you asked about tests, and it's a great idea. The code is used like this:

```ruby
    usernames = self.body.scan(Callouts.const_get(:FINDER))
```

like on this line: https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L694

So, we could add to the `drupal_node` unit test, here:

https://github.com/publiclab/plots2/blob/master/test/unit/drupal_node_test.rb

Or we could make a new unit test file for just the constants. In either case, a test might start with some test strings and use the regex to ensure the expected action works:

```ruby
string = "@StlMaris123 @StlMaris123 `@StlMaris123`"
expect = "REPLACE REPLACE `@StlMaris123`"
assert_equal expect, string.gsub(Callouts.const_get(:FINDER), "REPLACE")
```

Does that make sense?

**Comment by jywarren** [comment]
Actually, a separate unit test just for the constants sounds like a good idea -- we could also later add some tests for the other constants. So you could copy `drupal_node_test.rb` and change the names and populate it with your new test, if you're willing?

Thank you!

**Comment by StlMaris123** [comment]
Oh yes, i would be glad to see it working. Am on it. Thanks☺

**Comment by StlMaris123** [comment]
@jywarren i have done the tests though i have twisted a little bit because of the spacing problem

**Comment by jywarren** [comment]
This looks perfect!!!! Thanks, merging and please consider taking up another issue from our "help-wanted" listings.

**Comment by StlMaris123** [comment]
I have already picked another one. Now working it. Thanks for your help😊

**Pull request merged**
