### PR TITLE
Resolve rubocop lint offenses inside /app/mailers #6509

### LINKED ISSUE #6509: Resolve rubocop lint offenses inside /app/mailers
Referenced from #6340

To do:

Use rubocop to resolve the linting errors from the ruby files inside the /app/mailers directory
Check #6340 for more information

### PR DESCRIPTION
**Pull request by rojasTob**
Fixes #6509 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by rojasTob** [comment]
@moki298 could you take a look, please?

**Comment by moki298** [comment]
> @moki298 could you take a look, please?

@rojasTob I see one fix made in the code, are there any other violations or just this one?

**Comment by rojasTob** [comment]
@moki298 you are right, after a second look I noticed I was only running `rubocop` with the default configuration file only, I ran the command again with the other configuration files and I got more warnings/errors that I'm planning to work on. I'll keep you posted.

**Comment by rojasTob** [comment]
Hi @moki298, the files on mailers folder were corrected according to the rules and the tests have passed, but in codeclimate not passed. There is an error about the use of %w literals with [ ], in codeclimate should be delimited %w literals by ( ).

**Comment by moki298** [comment]
> Hi @moki298, the files on mailers folder were corrected according to the rules and the tests have passed, but in codeclimate not passed. There is an error about the use of %w literals with [ ], in codeclimate should be delimited %w literals by ( ).

For some reason seems to be the linter did not correct this, can you manually replace '[]' with '()'. I think that should fix this.

**Comment by rojasTob** [comment]
> > Hi @moki298, the files on mailers folder were corrected according to the rules and the tests have passed, but in codeclimate not passed. There is an error about the use of %w literals with [ ], in codeclimate should be delimited %w literals by ( ).
> 
> For some reason the linter did not correct this, can you manually replace '[]' with '()'. I think that should fix this.

Replaced '[]' with '()'. I got the 3 green checks. Let me know @moki298 if I need to do something else related with this issue.

**Comment by rojasTob** [comment]
Hi @moki298. I would like to know if I need to do something else on this task. Any feedback? It will be merged?

**Comment by moki298** [comment]
> Hi @moki298. I would like to know if I need to do something else on this task. Any feedback? It will be merged?

@rojasTob I appreciate your work, at this moment it's up to the reviewers to review and merge this. Meanwhile please feel free to look into other pending issues. Thanks :)

**Comment by cesswairimu** [comment]
Thanks all

**Pull request merged**
