### PR TITLE
initial Rails 4.2 port

### PR DESCRIPTION
**Pull request by jywarren**
I've started this off, and got through the upgrade guide until section 4.10:

http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2

So there's just two sections left:

* [x] 4.10 Masked Authenticity Tokens -- done!
* [x] 4.11 Action Mailer

These don't look too bad, but there are probably lots of other small things to do here. If anyone wants to pitch in (@ryzokuken ? 😄 )  you're welcome to open a PR against this one!

### CODE REVIEW

**Comment by jywarren** [comment]
@icarito coming along here...

**Comment by jywarren** [comment]
https://stackoverflow.com/questions/24310178/rails-4-migration-mysql2error-data-too-long-for-column-xxxx#24313205 for this error

**Comment by jywarren** [comment]
Next would be trying `strict: false` in database.yml... and then maybe:

```ruby
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.
You can opt into the new behavior and remove this warning by setting:
  config.active_record.raise_in_transactional_callbacks = true
```

**Comment by ryzokuken** [comment]
@jywarren I'm wrapping up my end semester exams here. I'll join you in a day or two.

**Comment by jywarren** [comment]
OK, so we may want to remove the truncator from the model later. But for now:

1. lots of `RuntimeError:         RuntimeError: not a redirect! 200 OK` errors
2. `ActionView::Template::Error:         ActionView::Template::Error: undefined method `type_cast_from_database' for "string":String
            app/views/users/_form.html.erb:85:in `block (4 levels) in _app_views_users__form_html_erb__3109374887348557147_29709000'`

Lots of mailer issues, perhaps related to `deliver_now`.

**Comment by siaw23** [comment]
is this an attempt for an upgrade to 4.2? i can continue work from this branch so you care for other business if you don't mind. @jywarren

**Comment by jywarren** [comment]
Please! You can open PRs against my PRs, actually!

**Comment by siaw23** [comment]
would you rather have me open a fresh PR for 4.2? @jywarren or continue from what you have here? also can you check my other PR. the guide implementation will make things easier for me. when it's merged people won't have to follow it (for now).

**Comment by jywarren** [comment]
Hi @siaw23 I'd be happy for you to open a fresh PR, either against master or against my PR. Thank you!

**Comment by jywarren** [comment]
I'd LOVE to get this done, any help appreciated!!! 👍

**Comment by siaw23** [comment]
ok. i'm currently having problems with setup locally. let see if i can sort that out. @jywarren

**Comment by jywarren** [comment]
Rebased this! Almost ready. @siaw23 were you hoping to try this out after the style guide implementation? Thanks!!!

**Comment by siaw23** [comment]
yes that's what i wanted to do. but still not late if you finish this there's more upgrades to be done. what's the targer? @jywarren Rails 5.0?

**Comment by jywarren** [comment]
Yep!

**Comment by jywarren** [comment]
And I could definitely still use help getting this all the way there!

**Comment by siaw23** [comment]
ok if you're wrapping up with 4.2.0 then finish it, i'll carry on from there then.

**Comment by jywarren** [comment]
Oh, I meant that if you're able to help with 4.2 I could definitely use the
help! But either way I'd be grateful -- thanks!

**Comment by siaw23** [comment]
yeah of course no problem. btw can you check my other PR, got rid of the merge conflict @jywarren

**Comment by siaw23** [comment]
i'll pull this PR on Saturday and take of from where you started.

**Comment by jywarren** [comment]
awesome, thank you! :-)

On Fri, Jan 26, 2018 at 12:01 AM, Emmanuel Hayford <notifications@github.com

**Comment by jywarren** [comment]
Let's remember as a follow-up to upgrade Paperclip to `v5.2.0`!!

**Comment by jywarren** [comment]
Yes @namangupta01 please do! That would be WONDERFUL 👍 👍 👍

**Comment by Souravirus** [comment]
Hey @jywarren I have started working on this. I have also sent a PR at your fork of plots2. Here is the link: https://github.com/jywarren/plots2/pull/260

**Comment by namangupta01** [comment]
Hey Sourav, well i was looking to fix this but its awesome that you are
fixing it. You are doing some good work. Please, free to ask if you need
some help.

**Comment by Souravirus** [comment]
Okk that would be great @namangupta01 I would surely ask for your help when needed. Thanks !!

**Comment by jywarren** [comment]
This is looking good! I turned on travis builds for `jywarren` so you can see results of PRs against this branch 👍 👍 👍 

Very exciting, thanks everybody!!!

**Comment by jywarren** [comment]
ok -- latest at https://github.com/jywarren/plots2/pull/266 now by @sauravirus!

**Comment by jywarren** [comment]
Oh, i'm not sure what happened here @Souravirus -- has it gone out of sync again?

**Comment by Souravirus** [comment]
I would see why the conflicts are coming up and update to you shortly

**Comment by Souravirus** [comment]
@jywarren, when I tried to rebase these commits above the current state of plots2/master, I am getting two conflicts which are of answers_controller.rb and subscription_mailer.rb which I had changed during sending of this PR but when I see here there are more conflicts. I don't know how they are coming. I have no idea about it. Please see it once.

**Comment by jywarren** [comment]
I'm not sure, but I think it's possible these represent additional changes that are merged as PRs come in. In any case perhaps you should open your own PR against publiclab/master and link to it from here, and we can work from yours? That way there's one less step.

**Comment by Souravirus** [comment]
Okk I would do as you said.Thanks!!

**Comment by jywarren** [comment]
Complete in #2533 !!!

**Pull request closed without merging**
