### PR TITLE
Testing upgrade to Rails 4.2

### LINKED ISSUE #1102: Upgrade to Rails 4.2
We're starting to get warnings for the `paperclip` gem:

```
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (calle
d from <class:Image> at /home/warren/sites/plots2/app/models/image.rb:12)
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (calle
d from <class:User> at /home/warren/sites/plots2/app/models/user.rb:21)
```

Worth trying it out  in the Gemfile and Gemfile.lock and seeing how the tests do?

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.
Closes #1102 
Thanks!

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren Made the required changes please review

**Comment by jywarren** [comment]
OK -- hope to get a look at this soon, thanks!

**Comment by jywarren** [comment]
Actually the test failures seem to have been from unrelated timeouts -- restarting it now!

**Comment by jywarren** [comment]
I think the conflicts will be OK to resolve after -- we're just interested in seeing how this set runs through tests. But if you have a chance to rebase and make additional adjustments to Gemfile.lock, that'd be great, once these have run.

**Comment by jywarren** [comment]
Perhaps you have to rebase this to get the tests to run cleanly?

**Comment by jywarren** [comment]
Let's remove the fixed ruby version from Gemfile.lock to avoid this kind of issue? But in the short term you can probably run:

`git checkout Gemfile.lock`

to get the correct version of that file from the upstream master branch. Thanks!

**Comment by jywarren** [comment]
Also, just so you're aware, there is another person working on Rails 4.2; perhaps you two could collaborate? https://github.com/publiclab/plots2/pull/1160

**Pull request closed without merging**
