### PR TITLE
modal for location input

### PR DESCRIPTION
**Pull request by jywarren**
This integrates the blurred location form into the tag area, @mridulnagpal ! it also tweaks the styling of the button dropdown, @shelbyfirebaugh @lilliankorinek -- 

screenshot 2017-09-28 at 12 09 39 pm

Pretty cool and a great highlighting of all your work!

* [ ] all tests pass -- `rake test:all`

### CODE REVIEW

**Comment by jywarren** [comment]
I hope it looks OK -- i compacted things a little and turned off the hidden flags, so this will go live today or tomorrow! Very exciting.

**Comment by jywarren** [comment]
@icarito, if you're going to be publishing to production today, note that I just merged this and it'd be great to see it live as well, thanks!!

**Comment by icarito** [comment]
Okay in a short while I will deploy what is in master to stable and we
can see it in staging. Then to production.

**Comment by jywarren** [comment]
Awesome!

**Pull request merged**
