### PR TITLE
Added new graphs to main tag page

### PR DESCRIPTION
**Pull request by Souravirus**
fixing issue #2068 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
here is the screenshot of the new graphs added to the main tag page
screenshot from 2018-08-16 03-40-54
@jywarren @ebarry. Please review.

**Comment by Souravirus** [comment]
The tests are corrected @jywarren. Just check this once.

**Comment by jywarren** [comment]
This is looking good... are there areas where you think we could standardize the JS code we use in tag graphs across the site?

**Comment by jywarren** [comment]
i.e. use a common JS function?

**Comment by Souravirus** [comment]
Actually for these new graphs I have used this name i.e contribution graph making

**Comment by Souravirus** [comment]
Should i rename it?

**Comment by jywarren** [comment]
That name sounds fine, but it might change if we make a more generalized
function... what do you think? I guess all graphs are of contributions over
time, right?

Do you want to try it in this PR or open a new one and finish this first?

**Comment by Souravirus** [comment]
Yeah you are right. Let's make another PR for it. It would be more specifically for making new functions and renaming function names. I guess that would me much better.

**Comment by Souravirus** [comment]
Leaving that thing aside I think this PR is ready @jywarren

**Comment by jywarren** [comment]
This is great. Can you show a screenshot of it when there is a lead wiki page image? Where it becomes half-width column? Thanks!

**Comment by Souravirus** [comment]
ok when I try to add a lead wiki page this is coming 
screenshot from 2018-08-16 20-40-30
seeing how to add it.

**Comment by Souravirus** [comment]
ok got it here is the screenshot
screenshot from 2018-08-16 20-45-30
Is it ok @jywarren

**Comment by Souravirus** [comment]
This is how it looks in small screens.
screenshot from 2018-08-16 21-12-15

**Comment by Souravirus** [comment]
But I didn't understand what you meant by half-width column

**Comment by jywarren** [comment]
OK, this looks good!

**Comment by jywarren** [comment]
Thanks, @Souravirus !!!

**Pull request merged**
