### PR TITLE
Fix alerts for login flow

### LINKED ISSUE #4691: Refactor alerts for Login flow
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

At time of login via OAuth the notices are wrongly shown and sometimes delayed too. See this for reference - https://drive.google.com/open?id=1w9tc4kIkoLJ5tvceoyQ1-kO_yug2pMDR

The link to file which requires help with notice - https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb#L58 

Also, this issue - #4522 can be referenced where details/progress about resolving the Login issue is recorded.

Thanks!

### PR DESCRIPTION
**Pull request by Uzay-G**
Fixes #4691

Hey! I fixed the problems you exposed in the video:

1. Logging in as a banned user with oauth was flashing "User was logged in." although he has been banned and does not log in. I fixed this by adding a conditional statement to check whether or not the user is banned or moderated. If he is, it flashes the corresponding message instead.
2. When a moderator banned a user. two flashes would display saying "User has been banned". The first one is in the `users#profile` route: 
https://github.com/publiclab/plots2/blob/fd5683d47ba235ac38e0e16a0d8675b53a1f289/app/controllers/users_controller.rb#L221.
and in the `admins#ban` route:
https://github.com/publiclab/plots2/blob/fd5683d47ba235abc38e0e16a0d8675b53a1f289/app/controllers/admin_controller.rb#L289.
I removed the second one to fix this duplication.
3. In the video, I also noticed when the user logs in through oauth, the message `Signed in!` is displayed instead of the `locales` version: ` I18n.t('user_sessions_controller.logged_in')`. I replaced the message with the translatable version.

What do you think?
@SidharthBansal has allowed me to work on other tasks and submit pull request for them but I cannot claim the task yet. I will claim it when I can! :+1:

### CODE REVIEW

**Comment by Uzay-G** [comment]
@publiclab/reviewers

**Comment by SidharthBansal** [comment]
Please break it into multiple prs so that each pr will stand for a medium task.
Thanks

**Comment by SidharthBansal** [comment]
1 functional change in 1 pr 
1 functional change carries 3 points(medium)
Also attach tests with the PR.
Kindly close this PR
This way you will get extra points
I have posted more Login-signup issues. Feel free to engage yourself in them too.
Thanks a lot

**Comment by Uzay-G** [comment]
Thanks, what do you mean by attach tests? Should I make some?

**Comment by Uzay-G** [comment]
Hey @SidharthBansal I made the pull requests at #7074, #7073, #7072

**Comment by Uzay-G** [comment]
I will work on all the cool new tasks when these ones are completed. I also noticed some of the tasks I merged that I couldn't claim are no longer on the dashboard. Did you remove them or maybe someone claimed it? 
This is the one I can't find  https://github.com/publiclab/mapknitter/issues/1025.
Thanks a bunch!

**Comment by SidharthBansal** [comment]
Yeah you need to create minitest according to the enhanced functionality to demonstrate the correctness of your code.
Thanks

**Comment by SidharthBansal** [comment]
> This is the one I can't find publiclab/mapknitter#1025.
Please check once more
If issues, contact me again on my email bansal.sidharthcode@gmail.com

**Pull request closed without merging**
