### PR TITLE
Update username validation error message

### LINKED ISSUE #5829: Username with a space in it needs better validation error message
This is small but important - someone wrote in saying they got a "username invalid" message when trying to sign up; I tried, and realized that if you enter a space in a username, it says "invalid" but doesn't say why. 

Screen Shot 2019-06-03 at 6 42 29 PM

We should offer a validation error message specifying the formatting rules for usernames!

I think this should go here: 

https://github.com/publiclab/plots2/blob/faa5a12e86bf7944dca43134f649947f03ca96a6/app/models/user.rb#L60-L61

### PR DESCRIPTION
**Pull request by suretrust**
Fixes #5829  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
Hi @suretrust, you can see the test build by clicking on the "Details" link next to the test name. In this case, here's the build log - https://travis-ci.org/publiclab/plots2/jobs/541331956

Let me know if you need any help. Thanks!

**Comment by suretrust** [comment]
@gauravano thanks a lot for the help. Kindly review.

**Comment by gauravano** [comment]
Hi @suretrust, changes look good :100:. You want to add test for it as @jywarren mentioned - https://github.com/publiclab/plots2/issues/5829#issuecomment-498722364? Thanks!!

**Comment by jywarren** [comment]
I am so sorry to have missed this. Unfortunately a lot has changed since that time; I think this is now being addressed in a new PR. If you'd like to try another issue, we'd be grateful! Thank you!

**Pull request closed without merging**
