### PR TITLE
re-adding simpler versions of can_tag unit tests, step by step

### PR DESCRIPTION
**Pull request by jywarren**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Also need to review functionality of `rsvp:` powertag in `can't rsvp someone else` test.

**Comment by jywarren** [comment]
OK so the simpler version of these tests also cause the original error. Commenting them out again one by one.

**Comment by jywarren** [comment]
@ashleypt -- I've simplified and narrowed the tests, but a few still don't pass. I think I can merge this, but  it's still confusing to me... would you like to keep working on it at all, or shall we just leave some good in-line comments noting the problems it causes? It's a shame not to have these unit tests, you know?

**Comment by jywarren** [comment]
OK -- there's still uncertainty about the tests that are causing the error, but we can try to go line by line here and pin down what specifically causes a TravisCI testing error. See current state in https://github.com/jywarren/plots2/blob/4d457ff03afea12c177f1df4e5fecabbd462ded3/test/unit/drupal_node_tag_test.rb

**Comment by ryzokuken** [comment]
@jywarren :joy: I told them that the other user could be anyone, and they name it `jeff`. You're immortalized in the codebase :P

**Comment by jywarren** [comment]
haha yeah i was thinking we could all put our names into the fixtures...
it's nice to be in there!
https://github.com/publiclab/plots2/tree/master/test/fixtures

**Pull request merged**
