### PR TITLE
add codeclimate test coverage

### PR DESCRIPTION
**Pull request by jywarren**
https://docs.codeclimate.com/docs/travis-ci-test-coverage

### CODE REVIEW

**Comment by jywarren** [comment]
Goodness, why would this have any effect on a specific test like this?

```

 FAIL["test_contribution_graph_making", #<Minitest::Reporters::Suite:0x0000563e4480dda0 @name="NodeTest">, 12.947790247999933]
 test_contribution_graph_making#NodeTest (12.95s)
        Expected: 8
          Actual: 11
        test/unit/node_test.rb:440:in `block in <class:NodeTest>'
```
😕

**Comment by jywarren** [comment]
Resolved in another PR, so this might need a rebase to get past it...

**Comment by jywarren** [comment]
Hmm, don't see coverage, but it's not broken, so I'll try merging and see if CodeClimate starts reporting.

**Comment by jywarren** [comment]
Hmm, actually it should be showing up on CodeClimate, even in a branch, but it isn't... probably needs more tweaking?

**Comment by SidharthBansal** [comment]
@jywarren I think we can include this in GCI too
cc\ @VladimirMikulic @Uzay-G

**Comment by jywarren** [comment]
I'm not sure, because codeclimate integration may need admin privileges?
But i hope I'm wrong!

**Comment by VladimirMikulic** [comment]
@SidharthBansal to set up this, I would need admin privileges.

**Comment by Uzay-G** [comment]
Yeah, this would be an interesting issue to work on, but me and @VladimirMikulic cannot complete it without admin privileges

**Comment by SidharthBansal** [comment]
@jywarren I don't have admin privileges. Please ping him. Thanks

**Comment by jywarren** [comment]
I'm afraid we haven't yet figured out how to extend privileges on CodeClimate. But if this is sure to work, you could screenshot the changes we need to make in the admin dashboard and we can merge this and make the changes for you? Could that work?

**Comment by VladimirMikulic** [comment]
@jywarren I think that admins are able to this with only one click. You should have a button that says something like "Setup/Add test coverage" and when you click it, it should automatically modify your repo to support test coverage.

**Comment by jywarren** [comment]
It looks like this only works with SimpleCov, and only < v0.18--

https://docs.codeclimate.com/docs/configuring-test-coverage#supported-languages-and-formats

https://github.com/codeclimate/test-reporter/issues/413

So, let's abandon for now, thanks!

**Pull request closed without merging**
