### PR TITLE
updated _like.html.erb

### PR DESCRIPTION
**Pull request by Abhinav1299**
Fixes #6713 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gptshubham595** [comment]
@Abhinav1299 make your descriptions good enough like issue link i.e change #0000 and ticks accordingly

**Comment by Abhinav1299** [comment]
@publiclab/reviewers

**Comment by Abhinav1299** [comment]
I have done it by mistake, can you tell me how to revert it back.

**Comment by SidharthBansal** [comment]
I am really sorry to close this issue as @Abhinav1299 is working on https://github.com/publiclab/plots2/issues/6704
and #6713 doesn't need any fix. 
I will request @gptshubham595 to take permission from the existing reviewers/mentors before creating ftos.
Thanks

**Pull request closed without merging**
