### PR TITLE
Update tests breaking PR #2562 (Please merge along with said PR)

### PR DESCRIPTION
**Pull request by seafr**
This fixes the integration test broken by PR #2562 which is otherwise OK. A functional test affected by the same PR is also modified to pass.

This PR should be merged along with #2562. And Travis CI is expected to report errors for this until #2562 is merged.

"Fixes" PR #2562 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled

Thanks!

### CODE REVIEW

**Comment by seafr** [comment]
Failing check and errors expected.

**Comment by jywarren** [comment]
Ah, ok i actually can't merge to master from a test-failing PR, according to the repo settings -- could you open a PR from this against `rob4abcba:patch-1` and the merge this into that PR so I can merge that one (including both sets of changes)? Make sense?

Thank you!!!

**Comment by seafr** [comment]
@jywarren I've looked around and it seems there are a few different ways to do what you requested. Could you share a link to one specific way you have in mind. Thank you.

**Comment by jywarren** [comment]
Sure - I think if you click "open pull request" on https://github.com/rob4abcba/plots2/ and then choose the `patch-1` branch there, and propose a PR from your own fork's `tests-5-routes` branch. Then ask rob4abcba to merge it.

Alternatively I believe either you or I can push to rob4abcba's branch -- so you could just try `
git push https://github.com/rob4abcba/plots2.git HEAD:patch-1` while in your own local `tests-5-routes` branch, if you want to try that first.

**Pull request closed without merging**
