### PR TITLE
initial pagy install for tag page pagination, to solve will_paginate issues

### LINKED ISSUE #7334: Wrong wiki count in Dropdown by type
In https://publiclab.org/contributors/newsletter dropdown by type Wiki pages is showing 3 but on clicking it shows only 1
Image is shown below
Screenshot from 2020-01-23 17-47-30

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #7334 with guidance from https://ddnexus.github.io/pagy/migration-guide

@Tlazypanda check out https://github.com/ddnexus/pagy - it makes a strong case that this gem is vastly more efficient for pagination, and i wonder if this will help us overall on performance. Testing on this route first. 

https://ddnexus.github.io/pagy/index

### CODE REVIEW

**Comment by jywarren** [comment]
OK, looking all right here:

image

I'll push this to unstable!

**Comment by jywarren** [comment]
Pushed it here! https://unstable.publiclab.org/tag/water-quality

**Comment by jywarren** [comment]
Seeing some issues with wiki pages appearing on 2 subsequent pages. Checking on live site to see if that's unique: 

https://unstable.publiclab.org/wiki/tag/water-quality shows  `Tortuga Guardian`, `Oil and Gas Water Quality`, and `Simple Water Sensor Platform` on page 2 as well: https://unstable.publiclab.org/wiki/tag/water-quality?page=2

**Comment by jywarren** [comment]
Also https://unstable.publiclab.org/questions/tag/water-quality shows 2x pagination due to the Answers code, which we should remove.

**Comment by jywarren** [comment]
OK, we should be good to merge this. I don't know that it will fix #7334 -- but let's see.

**Comment by Tlazypanda** [comment]
Hey @jywarren Yess this was on my up-for-discussion list in #7883  :v: maybe I should open another pr with some more routes migrated to Pagy :sweat_smile:

**Comment by Tlazypanda** [comment]
Linking this work to migrate to pagy issue #8426

**Comment by cesswairimu** [comment]
Thanks Sneha :rocket:

**Pull request merged**
