### PR TITLE
#5270 Align checkbox with the text.

### LINKED ISSUE #5270: Align checkbox with the text.
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

**Update**
In [https://publiclab.org/post](https://publiclab.org/post) the checkbox is not aligned with `Blur my location`

It must be properly aligned.

Screenshot for the same:

Selection_090

- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by shivam15**
Fixes #5270  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by shivam15** [comment]
@publiclab/reviewers please review

**Comment by shivam15** [comment]
screenshot

**Comment by sashadev-sky** [comment]
@shivam15 on my view of `publiclab/post` both locally and on the production site the checkbox is already aligned. Is this not the case for you? I couldn't find any recent PR's that would've fixed this.

Screen Shot 2019-04-05 at 1 49 36 AM

tagging @divyabaid16 because they opened the issue!

**Comment by shivam15** [comment]
@sashadev-sky if you zoom the checkbox you can see checkbox and "Blur my location" is not in same line.
Screenshot 2019-04-05 at 12 23 50 PM

**Comment by divyabaid16** [comment]
@sashadev-sky this issue was present in Mozilla Firefox.

**Comment by sashadev-sky** [comment]
@divyabaid16 do you still see it there now? 

The screenshot @shivam15 posted above is not the same alignment issue as the one you originally opened the issue for. 

In Chrome or Firefox (v. 66.02) I also don't see either of these issues

What version of Firefox are you using? If it's browser specific I think it would make sense to apply a css rule for that specific browser that can be reusable rather than an inline style here

**Comment by shivam15** [comment]
@sashadev-sky whats the conclusion ?

**Comment by divyabaid16** [comment]
I will just check and let you know.

**Comment by divyabaid16** [comment]
I'm still getting this in Chrome as well as Firefox 
Selection_118

@sashadev-sky I am currently using Firefox version 67.0b2

**Comment by sashadev-sky** [comment]
@divyabaid16 @shivam15 I looked into it a bit but it's hard to say why unless we all spent some time collaborating to try to figure it out. 

I can confirm, though, that this PR doesn't have any negative impact on the UI for me so if it's improving alignment on other people's screens and @divyabaid16 confirms it improves hers I would say lets go forward with it.

**Comment by shivam15** [comment]
@sashadev-sky @divyabaid16 may be once try with the changes from the pull request and see if everything looks fine from your end.

**Comment by sashadev-sky** [comment]
@shivam15 Ok I will run your PR locally to double check!

**Comment by divyabaid16** [comment]
It's working for me @shivam15 
Thanks!

**Comment by sashadev-sky** [comment]
**With your changes**: 
**chrome on the left firefox on the right**

Chrome and firefox 1

**Without your changes**: 
**chrome on the left firefox on the right**

c   f 2

This is my view. @divyabaid16 can you please run his PR and post yours too

**Comment by shivam15** [comment]
@divyabaid16  @sashadev-sky Done and Done!

**Comment by sashadev-sky** [comment]
Float: left for me just brought the checkbox a lot closer to the text, is this what you wanted @divyabaid16?

Before:
Screen Shot 2019-04-06 at 9 14 06 PM

After:
Screen Shot 2019-04-06 at 9 14 19 PM

**Comment by sashadev-sky** [comment]
I think the mis-alignment discrepancy is occurring because windows and mac (and probably other OS's) size these checkboxes differently, but Bootstrap positions them with pixel offsets assuming they're a specific size. See [this issue](https://github.com/twbs/bootstrap/issues/27755) on the Bootstrap page.

If you visit the [bootstrap docs](https://getbootstrap.com/docs/4.3/components/forms/#default-stacked) and toggle the w/h of the example checkboxes you can see this.

I don't think float is the right solution here because it's dependent on the Bootstrap styling already applied, which is error prone. But I found another solution, I am going to commit it here and if it doesn't work for you guys I'll revert it!

**Comment by sashadev-sky** [comment]
@shivam15 @divyabaid16 Ok will you guys check if this fixes alignment for you?
@shivam15 you will need to do `git pull origin master` to pull in these changes,  then set up Rails and run the server following the README instructions

**Comment by shivam15** [comment]
@sashadev-sky  changes worked for me

Capture

Please merge the pull request if you are satisfied too.

**Comment by divyabaid16** [comment]
I'm also getting the same result as @shivam15 
It's working for me too @sashadev-sky 
Thanks!

**Comment by sashadev-sky** [comment]
@shivam15 @divyabaid16 woah how awesome guys! We just fixed a bootstrap bug they haven' fixed yet. 

mentioning @jywarren to review because I wrote a lot of styling with !important declarations and this is also an important change to note for future usage of these particular bootstrap classes

**Comment by jywarren** [comment]
This looks super. I love the inline comments explaining it. Thanks a lot everyone!!!!! 🎉

**Comment by gauravano** [comment]
Awesome work everyone!

Suggestion for @shivam15 - It's good to open PR using a separate feature-branch, as it will help you in keeping your `master` branch clean.

**Pull request merged**
