### PR TITLE
Reduce pool size to 8

### PR DESCRIPTION
**Pull request by icarito**
Because we're running low on ram and hitting Virtual Memory! This could contribute to the slowdowns we are seeing sometimes.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by igniteeng000** [comment]
Please include fixes #issue no

**Comment by jywarren** [comment]
Is this one ready to merge @icarito ?

@igniteeng000 thanks, that's always a good question! In this case, i think it's related to different optimizations in this collection of issues: https://github.com/publiclab/plots2/labels/systems

**Comment by icarito** [comment]
Here's some background from production why I think it's a good idea to reduce memory footprint:
image
In fact although this has been merged, it hasn't been deployed yet. So I'm going into production and restarting the `web` container with only 8 processes. Yesterday we had a brief downtime in the morning and I think this will help avoid it.

**Comment by jywarren** [comment]
Super!

**Pull request merged**
