### PR TITLE
Fix problem of duplicate posts in questions page and mapknitter image display

### LINKED ISSUE #503: image upload progress bar in/post editor broken
When uploading at http://publiclab.org/post, a progress bar no longer appears, though it still does when uploading into comment textareas.

Relevant code here: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js

Test at http://publiclab.org/post

### LINKED ISSUE #563: /questions/liked/ page shows doubled posts
@ananyo2012 -- https://publiclab.org/questions/liked/ page shows a post more than once; maybe the query needs to enforce uniqueness with a `.group(:nid)` addition to the query.

### LINKED ISSUE #570: mapknitter map display should show lead images, not whole maps
I know the RSS feed includes iframes of maps, but I think it may be too many to try to display in too small a space:

screenshot 2016-06-07 at 12 27 53 pm

I think rss feeds may offer a lead image, in the `<image>` tag, as in this feed: https://mapknitter.org/feeds/all

if so, can we show that? 

And/or, could we display a map of maps, as in https://mapknitter.org/archive ?

@ananyo2012 - are you very busy with your own project, or do you think you could try this, at least the main image one? Thanks!

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added

fixed #563 , fixed #570, fixed #503 

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren Also fixed #570.

**Comment by ananyo2012** [comment]
@jywarren 7c62b3e fixes #503

**Comment by jywarren** [comment]
Merged manually. Complete!

**Comment by ananyo2012** [comment]
@jywarren Just being curious did those keywords auto closed those issues?

**Comment by ananyo2012** [comment]
@jywarren Ok I get it now. The keyword should be a part of commit message or the Title of the PR. Mentioning it in the body of the PR won't help I guess. You will  see a note beside your reference mentioning it will be closed once it is merged in master branch as in #16.

**Comment by jywarren** [comment]
The body of the PR should work, but since I had to rebase them, Github
didn't manage the actual issue closing, so then it has to be done manually.
I think if it's rebased and I can just click "merge" then it would work.

**Comment by ananyo2012** [comment]
Ok I get it.

**Pull request closed without merging**
