### PR TITLE
Add comment if user is removed as co-author from note

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5427 (<=== Add issue number here)

comment

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, thank you @cleverfool77! I think this one may need some input
from @publiclab/community-reps -- Thanks!!!

**Comment by IshaGupta18** [comment]
Hey @jywarren @CleverFool77 what I think of this issue is that we c don't need to put it as a comment, we could send a notification kind of email to the co-author removed so that it doesn't look too bad as a comment. Get what I mean?

**Comment by CleverFool77** [comment]
Hi @IshaGupta18 If we are adding a comment when a user is tagged, then why not same for removal of user as -co-author.
And I don't think it would look bad. I didn't get it. Even on GitHub, when we unassigned a issue or close a issue , we show it directly. we do `unassigned`. That's not bad I guess.
Here in the code, it not just adds comment but the user is also getting notified about comments.

And if we just want a notification email for removal, then it should be same for addition too. The procedure for both methods should be same, considering they are the part of same event that is addition or deletion of `with` power tag.

@jywarren Sure. It would be great to have some inputs and discussion.

> Hey @jywarren @CleverFool77 what I think of this issue is that we c don't need to put it as a comment, we could send a notification kind of email to the co-author removed so that it doesn't look too bad as a comment. Get what I mean?

**Comment by jywarren** [comment]
Hi all, I was thinking more about this and think that for the time being, we dont' need to leave such a comment. But I appreciate your help! Thank you!!!

**Pull request closed without merging**
