### PR TITLE
Fixed Broken link in feed/authorname.rss ( fixes #1963 )

### LINKED ISSUE #1963: Broken link in API.md
https://publiclab.org/feed/authorname.rss is broken in the API.md file

### PR DESCRIPTION
**Pull request by Mujadded**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Great, I thought there was problem with RSS builder. But it was if else. Thanks for the catch

**Comment by jywarren** [comment]
Ooh, great catch and good teamwork. Could we add a test to this to ensure it doesn't break again? To the functional tests, i guess? Thank you!!!

**Comment by Mujadded** [comment]
okay!  I will add the test. Sorry for late was busy for personal reasons :).

**Comment by Mujadded** [comment]
@jywarren have added the test :)

**Comment by jywarren** [comment]
Hi!! I think there were some issues when merging from master -- in the future you can avoid this by rebasing your work over the latest instead of merging in from master. There's some guidance on this workflow here: 

* https://guides.github.com/introduction/flow/index.html
* https://publiclab.org/notes/warren/11-22-2017/use-git-and-github-to-contribute-and-improve-public-lab-software


I'm going to try to rebase this and squash it to remove the additional changes you added -- let's see!

**Comment by Mujadded** [comment]
@jywarren I am so sorry. I will from next time. Sorry again

**Comment by jywarren** [comment]
No problem at all! This happens from time to time - give me a minute to figure it out.

**Comment by jywarren** [comment]
There we go! Oh wait, still one more to rebase past.

**Comment by jywarren** [comment]
Whoops! Wait...

**Comment by jywarren** [comment]
Oh no! I made a mistake. Wait, can you run `git push -f origin broken-link-authrname-rss` please?

**Comment by jywarren** [comment]
I forgot a step, and need a new copy of your commits.

**Comment by jywarren** [comment]
apologies!

**Comment by jywarren** [comment]
or `git push -f https://github.com/Mujadded/plots2.git broken-link-authrname-rss`

**Comment by Mujadded** [comment]
@jywarren I did `git push -f https://github.com/Mujadded/plots2.git broken-link-authrname-rss` just now

**Comment by jywarren** [comment]
hmm, i don't see it -- can you open a new PR, please? sorry about this!!!

**Pull request closed without merging**
