### PR TITLE
Solve Problem of main image in initial wiki creation

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer

This solves Issue #188 

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren Please review this PR too. Problem of main image association during new wiki creation is solved now. I have also staged this branch over my previous branch so it won't be a problem to merge.

**Comment by jywarren** [comment]
Thanks, will wait for the previous one to be complete and then will try
this one too. It may need rebasing over the other one as a result. Thanks
again, this is a great bugfix I'm very happy to have (i hope) solved after
so long!

**Comment by ananyo2012** [comment]
@jywarren This branch passes all tests. Ready for merge!

**Comment by ananyo2012** [comment]
@jywarren  Hey Jeff I have included the fixes of Issue #465 in this branch in the last commit. Please review it.

**Comment by jywarren** [comment]
Rebased and merged manually -- I rebased it on top of #464, which was from a new contributor so I prioritized it. Thanks! This is so super!

**Comment by jywarren** [comment]
Sorry, typo in last comment; fixed.

**Pull request closed without merging**
