### PR TITLE
fixed pluralization

### LINKED ISSUE #5104: Fix Pluralization Conditionals
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem
As shown below, the pluralization rules we have in place are incorrect. We want 1 _note_ and 0 research  _notes_.
Screen Shot 2019-03-16 at 7 16 00 AM

## Solution

The pluralization should look like this:
Screen Shot 2019-03-16 at 7 59 34 AM

This is a simple one -- let's change the following code:

1) In the below code, change the `<= 1` to just be `=== 1`. We don't want to include 0 in that conditional. This will change `0 research note` to `0 research notes`

https://github.com/publiclab/plots2/blob/d083415283dd89e0644e5bfe5ceb8e30b75dbecf/app/views/dashboard/_header.html.erb#L16

2) The below code is missing a condition all together:

https://github.com/publiclab/plots2/blob/d083415283dd89e0644e5bfe5ceb8e30b75dbecf/app/views/dashboard/_header.html.erb#L15

We want to change the first half of the line (the entire `<a></a>` element) to look like this:

```HTML
 <a href="/notes/recent"><%= @note_count %> <% if @note_count === 1 %> <%= t('dashboard._header.note') %><% else %> <%= t('dashboard._header.notes') %><% end %></a>

```
this will update `1 notes` to instead say `1 Note`. 

3) Why is the Note capitalized? While in the first fix we were dealing with `_header.research_note`, in the second we have `_header.note` 

Checking in the `en.yml` file, we find that: under, `_header`, there is a `notes` but no `note`:

https://github.com/publiclab/plots2/blob/d083415283dd89e0644e5bfe5ceb8e30b75dbecf/config/locales/en.yml#L312-L314

add a `note: "note"` key-value pair right below `notes: "notes"`

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by themonster2015**
Fixes #5104  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ x] screenshots/GIFs are attached 📎 in case of UI updation
* [x ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
Hi @publiclab/reviewers, I tried to fix my last submit. I hope it's fine this time.

Screen Shot 2019-03-28 at 00 10 09

### CODE REVIEW

**Comment by themonster2015** [comment]
I just fixed it

**Comment by sashadev-sky** [comment]
@themonster2015 looks great thank you!! You need to rebase your branch to fix the merge conflicts. you can follow this [workflow](https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch)

let me know if you have any questions!

**Comment by themonster2015** [comment]
Hi. I followed the guide up till git rebase master
But then i got this error:

Cannot rebase: Your index contains uncommitted changes.

Please commit or stash them.


What do I need to do? Thanks

**Comment by sashadev-sky** [comment]
@themonster2015 if they are changes you don't want to commit like `gemfile.lock` you can stash them away with `git stash`. Then you will be able to rebase. You can reapply them afterwards with `git apply` but if it's something like `gemfile.lock` you don't need to do that

**Comment by themonster2015** [comment]
I just did it. Could you please check to see if things are fine now?

**Comment by sashadev-sky** [comment]
@themonster2015 I don't see a new commit here. Usually for a rebase it won't push your commit up unless you add a `-f` option. Try that!

**Comment by themonster2015** [comment]
Thanks. I tried and it created a new commit now.

**Comment by sashadev-sky** [comment]
I think somehow you might have somehow pushed the files that were recently merged into master onto this branch, because it's reading them as edits in your PR. (see "8 files changed"). Did you by any chance do the push from the master branch instead of your branch? 

Typically for a rebase it just puts your changes on top of the latest pull from master and doesn't commit anything new.

@gauravano can I get a 2nd opinion on this please!

**Comment by gauravano** [comment]
Agree with @sashadev-sky here. It's possible that rebase hasn't taken place correctly. the last commit on the branch `fix-pluralization` has those extra changes. So, run this `git reset --hard HEAD~1` to delete last commit locally. And, then run `git push -f origin fix-pluralization`

I think that would be sufficient to get this ready. Feel free to ask, if you have any questions @themonster2015 . Thanks!

**Comment by sashadev-sky** [comment]
@gauravano yes me too as long as the merge conflict doesn't come back then because thats the commit she used to get rid of it. But if it does we will resolve it don't worry!! @themonster2015

**Comment by sashadev-sky** [comment]
@themonster2015 I am going to fork your branch, run your PR locally and tell you exactly what commands you need to run to fix your conflicts.  ☺️

**Comment by sashadev-sky** [comment]
@themonster2015 note step 1 but you just need to do step2. Let me know if this makes sense to you and try it out!

**Comment by themonster2015** [comment]
Thanks so much for your help! I just completed step 2 following your instruction.

**Comment by sashadev-sky** [comment]
@themonster2015 no problem! did you make sure to not exit or refresh the page until it says it completed the commit? I don't see a new commit

**Comment by themonster2015** [comment]
I saw only a Merge branch button on the page so I clicked on that one.

**Comment by sashadev-sky** [comment]
@themonster2015 Ok perfect! So the merge conflicts are resolved but it still wants you to rebase.. I tried rebasing from your fork and for some reason I got the same results as you where it says I changed 8 files! 

I couldn't test this out locally but can you retry the [workflow](https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch) that you did earlier, but this time:
1) First pull remote changes here (the file with the merge conflict you just edited) into your local feature branch: `git pull origin fix-pluralization`
2) Then do step 1 in the workflow
2) You can skip step 2 in the workflow. 
3) Do step 3 then after can you try running `git push origin master` to update your local master branch too? 
4) Then do step 4 (checkout feature branch) onwards..

Thank you for sticking with this!! Hoping that works!

**Comment by sashadev-sky** [comment]
Hi @themonster2015. Due to lack of response I am closing this PR and reassigning to another contributor. I'm sorry we never got to finish working through this one! I encourage you to grab a new FTO and try again :)

**Pull request closed without merging**
