### PR TITLE
Fix #4971 Make move back and front arrows responsive

### LINKED ISSUE #4971: Make move back and front arrows responsive
Created specifically for @divyabaid16
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
At https://publiclab.org/stats the arrows are not aligned  well on smaller screens.
arrows

Update 
* Remove https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L97-L99 and replace with
```
 <div class="row">
<h5> Move back or forward using the buttons below </h5>
 <div class="col-md-4 col-md-offset-2">
```

* Change https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L130-L132 to 
```
</div>
<div class="col-md-3">
```

* Add two divs on https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L165
```
 </div>
</div>
```

After changing the view, also attach the screenshot of updated view in the PR. (You probably have to go on responsive design mode by pressing Ctrl+shift+M)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #4971 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

Before:
Selection_048

After:
Selection_047

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by divyabaid16** [comment]
@cesswairimu  Please review this.

**Comment by cesswairimu** [comment]
@divyabaid16 The changes look awesome. Good job :balloon:
Just one small thing.. your pull request is on the master your branch. Please make a separate branch something like `make-arrow-links-responsive` off of master then make a pull request from that branch I will approve the changes. Thanks

**Comment by cesswairimu** [comment]
@divyabaid16 are you doing the changes locally or on github?

**Comment by divyabaid16** [comment]
Actually, I just created a mess. I'm solving it.

**Comment by divyabaid16** [comment]
@cesswairimu can you please tell me how do I edit this pull request and change the branch in this pull request? 
Or I should create a seperate PR after changing the branch?

**Pull request closed without merging**
