### PR TITLE
[WIP]login modal linked to share-your-work

### LINKED ISSUE #4468: Link login modal to 'Share your work' at '/research'
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

share-your-work

> What did you expect to see that you didn't?

'Share your work' redirects to login page  

### What's your PublicLab.org username?

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by geekychaser**
Fixes #4468

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
Hi @geekychaser.. This would require changes in the sidebar buttons.. So you have to change the file in app/views/sidebar

**Comment by geekychaser** [comment]
@SidharthBansal @oorjitchowdhary the code for `Share your work` is present in header file and the changes are refelcted too.
please correct me if i am wrong.?
share_work

**Comment by SidharthBansal** [comment]
@oorjitchowdhary you are mistaken. @geekychaser is right. Sorry for misunderstanding @geekychaser. 
@oorjitchowdhary or @geekychaser can you please dig out the issue number for linking to app/views/sidebar if it exists else create an issue for it and link to the identification issue?

Thanks both of you.

**Comment by oorjitchowdhary** [comment]
Oh, I'm so sorry.. Thanks @geekychaser ..

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Can we move this file
https://github.com/publiclab/plots2/blob/491c6d3a07eed89bc9cadc1a70540af245ae8c2f/app/views/dashboard/_header.html.erb#L5-L19
to https://github.com/publiclab/plots2/blob/dd18e979e619005c28254fd129852602e0279dd7/app/views/dashboard/_sidebar.html.erb ?

**Comment by geekychaser** [comment]
@oorjitchowdhary it makes sense and locating the code would also be easier

**Comment by oorjitchowdhary** [comment]
Opened up an issue #4499

**Comment by geekychaser** [comment]
@oorjitchowdhary will you do that or shall i ? but after the confirmation of @SidharthBansal

**Comment by oorjitchowdhary** [comment]
I can do that but only after 9th Jan.. So if you wanna take that up you could..
Thanks

**Pull request merged**
