### PR TITLE
Locale consistency & organization to locale files

### PR DESCRIPTION
**Pull request by jiteshjha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

---

@jywarren , I made all the suggested modifications. What do you think?

### CODE REVIEW

**Comment by jywarren** [comment]
Incorporates changes from #580 (Jitesh, please try to link your work together like this so people can follow. Thanks!)

Testing this out now -- looks great, much improved!

**Comment by jiteshjha** [comment]
Thanks, Jeff! I'll keep that in mind. :smile:

**Comment by jywarren** [comment]
Tests passed; rebasing, as there've been a few more commits last week. Just a moment longer!

**Comment by jywarren** [comment]
Manually merged -- closing! Thanks, Jitesh; hope to publish on Thursday.

**Pull request closed without merging**
