### PR TITLE
Login modal spam wiki

### LINKED ISSUE #4165: Link Login Modal to Spam on wiki pages
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Spam on wiki pages
image
On clicking on the spam icon, modal should be shown

### PR DESCRIPTION
**Pull request by okonek**
Fixes #4165 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
spam

### CODE REVIEW

**Comment by okonek** [comment]
@SidharthBansal I've resolved it here, reusing code from my previous PR in liking wikis. Thanks for all your help and hope all tests pass.

**Comment by okonek** [comment]
The same codeclimate issues as before. We should ignore them.

**Comment by SidharthBansal** [comment]
@okonek thanks for your hardworking and patience.
Please remove the changes of other unmerged PRS. You need to only add changes for your patch.
Also please provide similar screenshots.

**Comment by SidharthBansal** [comment]
Or gifs as I asked you for the like button. You can also work on the other similar PRS simultaneously with this if you want. Subscribe with login is also similar to like and this PR you can give them a try.
All the PRS which require greater than 3 lines of code code updation should not be made into fto. They are big issues.
They will be counted separately from 10 linking modal tasks. So, even after this prs approval you can work on 10 more similar linking modal tasks. Does this makes sense?

**Comment by SidharthBansal** [comment]
I hope that the tests will pass once you will commit the suggested changes. 
Will you figure out the similar gifs from last PR or shall I tell you them in detail?

**Comment by okonek** [comment]
Sorry, but what changes should I remove? I dont understand.

**Comment by okonek** [comment]
Without this code, it wouldn't work at all.

**Comment by okonek** [comment]
I only merged my branch from unstable first.

**Comment by SidharthBansal** [comment]
You need to make your branch sync with the master. On top of that you have to do the changes.
You dont have to work on the unstable.

**Comment by okonek** [comment]
But now the redirect does not work. Help pls.

**Comment by SidharthBansal** [comment]
You can close and work on a new pr. In this pr you can no longer push because it has 0 commits now.
Please start the issue from solving.
Make master exactly same as the plots2:master. then create a new branch. Add your changes. commit. push....
I hope this will help

**Pull request closed without merging**
