### PR TITLE
Alignment for FA icons as noted in issue #7092

### LINKED ISSUE #7092: Social icons on sign up and login modal not centered
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

Screenshot_20200103_000552

### 🚩 Goal

Screenshot_20200103_000607

As you can see(hopefully) icons are not centred on login and sign up modals.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** the file plots2/app/assets/stylesheets/style.css

- Line 103, after `.fa-white` selector add this code:
```css
.fa-facebook,
.fa-twitter,
.fa-github,
.fa-google {
  vertical-align: middle;
}
```
[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by abdiclear**
Fixes #7092 

#7093 I messed up and pulled from my local master branch into the base master branch.

git1
git2

### CODE REVIEW

**Comment by abdiclear** [comment]
@ananyaarun 
I'm having a bit of an issue with running this. Do I have to have Ruby 2.4.4 installed or can later versions work?

**Comment by abdiclear** [comment]
Ok, the screenshots should be up. Sorry for taking so long.

**Comment by anthony-zhou** [comment]
@abdiclear No worries! Thanks for adding screenshots. 

Not sure why the codecov test is failing here, but it doesn't seem related.

**Comment by SidharthBansal** [comment]
🎉

**Pull request merged**
