### PR TITLE
Update routes.rb to fix embeddable features

### LINKED ISSUE #2817: 404 error for embeddable features
We have some content on other sites that are run through the Features system -- using urls like this one:

https://publiclab.org/features/embed/spectral-workbench-sidebar

I'm getting a 404 on that -- looks like a routing issue related to #2726  ?

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #2817 !

### CODE REVIEW

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/8b65e69f4a7d91e700d631b78fc50e4eda97fb08/app/controllers/features_controller.rb#L10

**Comment by jywarren** [comment]
@Souravirus if you get a chance to look before I do, that's the controller action!

**Comment by Souravirus** [comment]
ok I will look at it. Thanks

**Comment by Souravirus** [comment]
Added tests here for the feature#embed @jywarren.

**Comment by Souravirus** [comment]
This was the error which I was talking about previously `** Error in `/usr/local/bin/ruby': free(): invalid next size (fast): 0x00000000098d3950 ***`. But when I rebuild this test it will go all good.

**Comment by jywarren** [comment]
From searching around with that error, I believe that's a memory error, but didn't see much about how to fix it. 

Can you open a new issue for that? I restarted the Travis run in the meantime. Thanks!

**Comment by jywarren** [comment]
Looks great!

**Comment by Souravirus** [comment]
Ok I will create an issue for that error.

**Pull request merged**
