### PR TITLE
Added Links

### PR DESCRIPTION
**Pull request by namanjain323232**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

Fixes #[Add issue number here.]

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by namanjain323232** [comment]
Fixes #3625

**Comment by DivyeshPuri** [comment]
To which issue does this PR correspond to? 
You should have written issue number right after `Fixes` field, right now it is directing to your PR number.

**Comment by namanjain323232** [comment]
It just adds a few more useful links for beginners

**Comment by DivyeshPuri** [comment]
@namanjain323232 Is there any issue made corresponding to this PR?

**Comment by namanjain323232** [comment]
There is not an issue
It's just an added bit of information for newcomers

**Pull request merged**
