### PR TITLE
The search bar is inline with pagination

### LINKED ISSUE #5035: Some issues in the tags page
**Description**

In [https://publiclab.org/tags](https://publiclab.org/tags) 
* [ ] In Mozilla Firefox, some of the tags are overlapping each other
* [ ] Cursor in  ```show graph``` when hovered doesn't change to pointer
* [ ] The search bar is spread all across the horizontal screen

Selection_057

**Expected Behavior**
* [ ] In Mozilla Firefox, there must be some space between the tags
* [ ] Cursor changes to pointer in  ```show graph``` when hovered
* [ ] The search bar is inline with page pagination (at the bottom)

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #5035  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Screenshot for the same
screenshot

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
@divyabaid16 It's usually preferred to have one commit. :)

**Comment by gauravano** [comment]
@jywarren @ebarry @steviepubliclab  when we see the whole page :point_down: , it looks like this

tags_view

Do you like this?

**Comment by divyabaid16** [comment]
Actually, I proposed the idea to basically decrease the size of the search bar. Its length was too large and the button was far away.

**Comment by gauravano** [comment]
Agree that the search bar looks cleaner now. Design issues requires :+1: from @publiclab/community-reps

**Comment by jywarren** [comment]
Hi! I love the idea of making it narrower. However, I think we will be
changing the layout of this page pretty soon, so what I propose is making
the search bar smaller, but still left-justified.

If you'd like to dig into the new design tasks a bit, we'd love it! Here's
a new issue where I broke them out in detail:
https://github.com/publiclab/plots2/issues/5090

Thank you!!!

**Comment by divyabaid16** [comment]
@jywarren I have made the changes.
Please find the screenshot for the same and suggest any further changes.
Selection_068

**Comment by jywarren** [comment]
This looks super awesome. I'm going to merge it! Thank you so much!!! 👍 👍 🎉

**Pull request merged**
