### PR TITLE
RESTful typeahead display using standard bootstrap css

### PR DESCRIPTION
**Pull request by david-days**
* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Reworked data-list display to match existing application and bootstrap styles from .dropdown-menu>li>a.  Standard usage of $.css() and $.hide() to manipulate display UX.

Removed unused commented code.

### CODE REVIEW

**Comment by jywarren** [comment]
Great, i merged this and pushed it to stable, but just wanted to check the functionality with you -- unlike on https://publiclab.org/questions, when I down-arrow, I don't see the options highlight, and when I select one, it doesn't actually go to that post. Is that just on my instance, or is that the behavior you see too? Try out https://publiclab.org/questions -- I believe it's a standard bootstrap typeahead function. Can you point me at the code where this is done in the header typeahead now? I'd like to get the full typeahead set of interactions working. 

Thanks and enjoy your weekend!

**Comment by jywarren** [comment]
Ah, i see it here: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/restful_typeahead.js

Just curious, but was it not feasible to integrate the new API calls into a standard Bootstrap Typeahead? I'd hate for all of its fairly complex behavior to have to be reproduced manually here, but understand if there was a good reason why it didn't work. Also happy to take a closer look at integration. Thanks again!

**Comment by jywarren** [comment]
Just looking back at this: https://github.com/publiclab/plots2/blob/3ed96ba54532933e230dd4a53606304256a40755/app/assets/javascripts/search.js uses `$('#searchform_input').typeahead()` which has an API for several of these interactions. 

Sorry if I'm just catching up on this code -- the new code is so extensive it's taking me some time to drill down through it all.

**Comment by jywarren** [comment]
BTW the code is now live.

**Comment by david-days** [comment]
I went with a custom implementation for the client-side typeahead so it would be easier to customize the code for all the other things that we might want to do (it's just AJAX calls, html element creation, and placement) without having to dig too deeply into the bootstrap typeahead functionality.

It would be pretty simple to revert to that, if you wanted to.  Both client frameworks perform AJAX calls, both create html elements, and both have custom code to execute desired behavior.  Due to the (relatively) short timeframe of GSoC and my newness to Ruby, I went with a basic set of javascripts (which I could bang out from scratch) rather than add the overhead of digging deep into the the particular typeahead implementation that we had been using.

Adding to or changing the click behavior would be pretty simple, if you wish--for now, I was just implementing fill-in-the-input type of typeahead.

**Comment by jywarren** [comment]
OK, that makes sense -- I'm looking over this now -- your implementation is very clean and readable, so I'd like to try plugging its component modules into the Bootstrap one this morning.

**Comment by jywarren** [comment]
I'm also seeing an error in Ruby on local:

```
NoMethodError (undefined method `fromTypeahead' for TagResult:Class):
  app/services/typeahead_service.rb:169:in `block in textSearch_questions'
  app/services/typeahead_service.rb:168:in `textSearch_questions'
  app/services/typeahead_service.rb:83:in `textSearch_all'
  app/api/srch/typeahead.rb:30:in `block (2 levels) in <class:Typeahead>'
```

while testing. Checking...

**Comment by david-days** [comment]
Let me refresh my code and see what's going on there.  It wasn't changed on the typeahead-styles branch, but there might be some weak code that could break easily.

**Comment by jywarren** [comment]
Hmm, ok -- yeah, i wasn't able to find that method in any of your branches.

**Comment by jywarren** [comment]
If it's helpful, this was the commit where that method was introduced: https://github.com/publiclab/plots2/blame/master/app/services/typeahead_service.rb#L168

**Comment by jywarren** [comment]
and `fromTypeahead` doesn't appear elsewhere in that commit

**Comment by david-days** [comment]
Ok.  I think I can get that one figured out.  Not sure why it slipped past me on testing, but it's an easy fix.

**Comment by david-days** [comment]
Want me to test out and submit a bootstrap-typeahead component, also?  I wasn't sure from your statement if you were going to work on it yourself or not.

**Comment by jywarren** [comment]
OK, cool! I'm working through the typeahead code, and and doing ...

(comments crossed in cyberspace)

If you have time today, that would be great, but I'm also happy to give it a go. I was starting by doing a little reformatting (we're standardized on two-space-tabs, for example) so I can push a commit with that that you can pull in, maybe?

**Comment by jywarren** [comment]
Basically I was going to include in a comment or link to the example JSON output format in this file, to make it easier for people to work on it. I guess a link would be best if that format is documented elsewhere.

**Comment by jywarren** [comment]
My starting changes are here: https://github.com/jywarren/plots2/commit/37f0efd31e5f28106df1a455e71389892bc48760

**Comment by jywarren** [comment]
Hi, David - I'm going to be merging and publishing today, with new code on top of this PR (which does pass tests). Can I pitch in here as well?

**Comment by david-days** [comment]
Yes.  I've been tied up with other work, so if you want to, put everything
related here.

I'll catch up eventually.

**Comment by jywarren** [comment]
OK -- no problem, and sorry to pester. Just wanted to touch base in case there was something I could do to help.

**Comment by david-days** [comment]
No pestering at all, Jeffrey.  I've been able to put some time in last
week, but everything just hit the fan at once here (in a good way).

**Pull request merged**
