### PR TITLE
Add noreferrer attribute to link tags

### LINKED ISSUE #7410: Links to cross-origin destinations are unsafe
```
<a class="nav-link" target="_blank" href="//store.publiclab.org" >
```

When you link to a page on another site using the `target="_blank"` attribute, you can expose your site to performance and security issues:

- The other page may run on the same process as your page. If the other page is running a lot of JavaScript, your page's performance may suffer.

- The other page can access your window object with the `window.opener` property. This may allow the other page to redirect your page to a malicious URL.

**Adding `rel="noopener"` or `rel="noreferrer"` to your `target="_blank"` links avoids these issues.**

> `noreferrer`: It is used to Specify that the browser should not send an HTTP referer header if the user follows the hyperlink.

### PR DESCRIPTION
**Pull request by sakshi-2412**
Fixes #7410 

Add `rel=”noreferrer”` attribute to link tags with `target="_blank"` attribute.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
@sakshi-2412 `noreferrer` is used to hide referrer information when a link is clicked. Since most of the links with `target=_blank` are links to a public lab page, there's no point hiding referrer info. Maybe, you could add `noreferrer` to only external sites.

Also, just noting that most browsers have incorporated `rel=opener` on newly opened tabs https://chromestatus.com/feature/6140064063029248

**Comment by sakshi-2412** [comment]
Hey @TildaDares thanks for that information✨. I think that if most browsers have made this as default, then we should skip adding any nonreferrer links🤔 What do you say?

**Comment by TildaDares** [comment]
@sakshi-2412 I agree with you

**Comment by sakshi-2412** [comment]
Okay😄 I think this PR and issue can be closed now. Thanks!

**Pull request closed without merging**
