### PR TITLE
Add link to smtp for sidekiq

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
Do we have to add this to deploy-container as well?

**Comment by icarito** [comment]
Good catch @ViditChitkara !! Thank you!

**Comment by jywarren** [comment]
Whoa weird?

```

ERROR["test_create_a_user_with_omniauth_if_email_prefix_does_not_exist_in_db", Minitest::Result, 57.168834722999975]
 test_create_a_user_with_omniauth_if_email_prefix_does_not_exist_in_db#Minitest::Result (57.17s)
NoMethodError:         NoMethodError: undefined method `using_open_id?' for nil:NilClass
            lib/authlogic_openid/authlogic_openid/session.rb:78:in `authenticating_with_openid?'
            app/models/user.rb:441:in `block in create_with_omniauth'
            app/models/user.rb:435:in `create_with_omniauth'
            test/unit/user_test.rb:207:in `block in <class:UserTest>'
ERROR["test_user_creation", Minitest::Result, 58.106504889000064]
 test_user_creation#Minitest::Result (58.11s)
NoMethodError:         NoMethodError: undefined method `using_open_id?' for nil:NilClass
            lib/authlogic_openid/authlogic_openid/session.rb:78:in `authenticating_with_openid?'
            lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in `save'
            test/unit/user_test.rb:10:in `block in <class:UserTest>'

```

**Comment by jywarren** [comment]
I'm going to restart one more time because this doesn't seem related at all...?

**Comment by Souravirus** [comment]
Hmm, I also saw these errors while running tests locally. Lets open a new issue for this.

**Comment by ViditChitkara** [comment]
In the meantime shall we test it on staging?

**Comment by icarito** [comment]
Deploying to `stable.publiclab.org` now, then it will go to production!

**Comment by ViditChitkara** [comment]
Tried on stable, didn't get the error this time but didn't receive the mail.

**Comment by jywarren** [comment]
Yayyyyyy!!!

**Comment by jywarren** [comment]
Worked for me in production!

**Comment by ViditChitkara** [comment]
Did you get the mail?

**Comment by jywarren** [comment]
Yes!!!!!!

On Jul 12, 2018 4:49 PM, "Vidit" <notifications@github.com> wrote:

Did you get the mail?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/pull/3058#issuecomment-404645794>, or mute
the thread

**Comment by ViditChitkara** [comment]
Oh that's very cool!! I'll try too!

**Comment by ViditChitkara** [comment]
Woohoo!! I got the mail too!! It's a bit broken though. Should our next step be, improve it's UI?

**Comment by jywarren** [comment]
Yeah!

**Comment by ViditChitkara** [comment]
Cool, will make an issue for this!! Thanks a lot @icarito and @jywarren , very excited seeing this working!

**Pull request merged**
