### PR TITLE
Pass environment variables to cron jobs.

### LINKED ISSUE #3404: Digest email bug
The digest emails are currently not being sent. 
`ArgumentError: wrong number of arguments (given 0, expected 1)` is shown on Sidekiq dashboard (https://publiclab.org/sidekiq/retries).

### PR DESCRIPTION
**Pull request by icarito**
Fixes #3404 

This is an attempted fix following https://stackoverflow.com/questions/46084037/whenever-rails-gem-throwing-errors-to-cron-log

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
I just tried this in unstable and didn't work. :disappointed: 

```bundler: failed to load command: bin/rails (bin/rails)                                                                            Bundler::GemNotFound: Could not find rake-12.3.1 in any of the sources                                                              /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize'                           /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'                                         
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'       ```

**Comment by icarito** [comment]
A brief note that the way I tested this was to go into the staging server in unstable instance and then into the container ( `docker-compose exec web bash`) - install an editor (`apt install vim-tiny`) in order to edit the cron tab (`crontab -e`) to trigger the next minute.
Then monitor `public/crontab-log.txt`.

I'll do this again when we have another idea.

**Comment by icarito** [comment]
> I just tried this in unstable and didn't work. disappointed
> 
> `` bundler: failed to load command: bin/rails (bin/rails) Bundler::GemNotFound: Could not find rake-12.3.1 in any of the sources /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize' /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!' /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize' ``

I just tried alternatives (that didn't work) and realized I had pushed the wrong ref for this test. I'm pushing this one again.

**Comment by icarito** [comment]
Didn't work this time either. I think the latest comment is https://github.com/javan/whenever/issues/500#issuecomment-439582092 but we don't even use rbenv, so looking for more ideas...

**Comment by jywarren** [comment]
Did I hear that this was ready to merge? Or still stuck? Thanks!

**Comment by icarito** [comment]
Yes, ready! It won't fail at this step anymore, hopefully at all.

**Pull request merged**
