### PR TITLE
Fixed bug in notes display

### LINKED ISSUE #5076: Bug in Ordering of research notes
# Description
On clicking on research notes and applying the recent filter, the notes are not displayed in proper order moreover i noticed the old once show up first.

order

# Expected
The recent research notes should be displayed first.

### PR DESCRIPTION
**Pull request by ananyaarun**
Fixes #5076 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
The PR was already yesterday I guess. :thinking:

**Comment by ananyaarun** [comment]
@gauravano , Previously notes were displayed in dec order on clicking recent but now it has been updated to asc order.

Reference comment https://github.com/publiclab/plots2/pull/5078#issuecomment-473310269

**Comment by divyabaid16** [comment]
LGTM @ananyaarun @gauravano

**Comment by gauravano** [comment]
I pushed this PR to `unstable` but /notes/recent page is empty. @ananyaarun have you tried this PR locally?

**Comment by ananyaarun** [comment]
@gauravano , i can see notes (test notes) i have added myself in asc order in my local

notes

**Comment by ananyaarun** [comment]
@gauravano , Its not empty on my local i can see the recently posted notes in notes/recent. But just now adding more notes and testing a found that none of the orderings are working on my local idk why.

notes

For eg i liked a few notes but they didnt show up first when i click on sort by likes.
Similarly the order is not asc when sorted by recent. Any idea why this is happening ?

**Comment by ananyaarun** [comment]
The current screen shot shows posts with 0,1,2 likes but dont cm in order on notes/liked page on my local.

liked

And i just noticed no of likes are randomly displayed without any order on the main publiclab.org page too !

**Comment by ananyaarun** [comment]
@gauravano , I can see the notes in my local notes/recent page. 

recent

But while testing i found that the liked ie notes/liked page is not working as desired. Even in the main publiclab.org page the notes are displayed in random order.

Regarding this PR there is a change needed. I have given the order under wiki section by mistake in my commit which is why i think u couldnt see the notes/recent page. I'll change the commit right away.

**Comment by ananyaarun** [comment]
@gauravano , i removed the change i had accidentally made under the wiki section. (I'll report this separately as a issue if req). Now this ordering works on my local.

new

**Comment by ananyaarun** [comment]
@publiclab/plots2-reviewers , Anything else to be done ? Or any other suggestions to solve this ?

**Comment by gauravano** [comment]
@jywarren I pushed this PR to unstable but getting no data in notes/recent - https://unstable.publiclab.org/notes/recent

Any idea?

**Comment by ananyaarun** [comment]
@gauravano Interesting, I can see it on my local though. Is the notes/recent page empty on unstable ?

**Comment by gauravano** [comment]
Try the link @ananyaarun

**Comment by SidharthBansal** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by ananyaarun** [comment]
Hi @SidharthBansal , so the problem here is I am able to see the notes displayed in recent order in my local 
image
But pushing this to unstable is causing some problems.

**Comment by SidharthBansal** [comment]
What problem are you facing with unstable?

**Comment by ananyaarun** [comment]
> @jywarren I have pushed this PR to unstable but getting no data in notes/recent - https://unstable.publiclab.org/notes/recent
> 
> Any idea?

The notes/recent page seems to be empty

**Comment by SidharthBansal** [comment]
That means someone has created that page in production db

**Comment by jywarren** [comment]
This is being sorted by `created`, which seems ok! I'm going to close this, thank you!

**Pull request closed without merging**
