### PR TITLE
Fix : "First Timers Issue Template" linked a new path

### PR DESCRIPTION
**Pull request by AshSmah**

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @AshSmah, please add the issue number in the format `fixes #0000` (for example). Also, the issue you opened this PR for requires two changes to two different files. Can you take a look at the issue again to know what change is left? Thank you!

**Comment by AshSmah** [comment]
Sure, i will do that immediately and thank you for letting me know. 🙂

**Comment by AshSmah** [comment]
Hi @TildaDares, sorry for this but,
unknowingly I deleted all the content inside the file, now should I close the **current pull request and open a fresh new one ,**
**Waiting for your replay**.

**Comment by TildaDares** [comment]
Hi @AshSmah, you can open a new one.

**Comment by AshSmah** [comment]
ok

**Pull request closed without merging**
