### PR TITLE
Layouts and home translations

### PR DESCRIPTION
**Pull request by jiteshjha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jiteshjha** [comment]
Hi @jywarren , under views/home/_carousel, I see that carousel in-use is a feature, and the _carousal view is obsolete right now.

**Comment by jiteshjha** [comment]
@jywarren I notice that _carousel partial under `views/home/` is obsolete, as carousel is right now is used as a feature. What do you think?

**Comment by jiteshjha** [comment]
@jywarren I'm done with home and layout views, rebased branch with master and the PR ready for merge. Your thoughts on this PR?

**Comment by jywarren** [comment]
Hi, I'll be looking at it today, thanks! And yes, the carousel could be deleted; feel free to do so in another PR. Thanks!

**Comment by jywarren** [comment]
Running tests... but also boarding a plane, so I may only be able to reply in 3-4 hours.

**Comment by jywarren** [comment]
This looks good, thanks! Merged (and signing off for the time being :-P )

**Comment by jywarren** [comment]
Merged manually in https://github.com/publiclab/plots2/commit/aa53081f652e3ba2da8cb5f2f711f5f6c0ad15c8 (as I had to rebase).

**Comment by jiteshjha** [comment]
Haha @jywarren ! I was waiting for this PR to get merged just so that I could start another one. Thanks for your time! :smile:

**Comment by jywarren** [comment]
Super, although you can always start a new feature branch from the last
commit of an existing one. Thanks!

**Pull request closed without merging**
