### PR TITLE
LOGO of supporter UPDATED

### LINKED ISSUE #9971: Update our supporters
We have listed projects that support us at https://github.com/publiclab/plots2/blob/main/doc/SUPPORTERS.md

We have changed some of our projects, so we should update them in this page like `Coveralls` -> `Codecov`

### PR DESCRIPTION
**Pull request by Ash-KODES**
Fixes #9971 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by daemon1024 — APPROVED** [review]
LGTM 👍🏽 Thank You for the Pull Request 😄

**Comment by Ash-KODES** [comment]
> LGTM 👍🏽 Thank You for the Pull Request

anytime!

**Review by noi5e — APPROVED** [review]
Thanks @Ash-KODES, this is awesome! Thanks for looking up the logo!

We don't use Travis CI anymore, we moved to GitHub Actions this past year. Do you think you'd be able to make that change too?

I see there's a GitHub Actions logo [here](Thanks @Ash-KODES, this is awesome! Thanks for looking up the logo!)

If not that's okay too!

**Comment by Ash-KODES** [comment]
> Thanks @Ash-KODES, this is awesome! Thanks for looking up the logo!
> 
> We don't use Travis CI anymore, we moved to GitHub Actions this past year. Do you think you'd be able to make that change too?
> 
> I see there's a GitHub Actions logo [here](Thanks @Ash-KODES, this is awesome! Thanks for looking up the logo!)
> 
> If not that's okay too!

ok i am on it!!

**Comment by noi5e** [comment]
@Ash-KODES Oops, [here](https://www.google.com/search?q=github+actions&sxsrf=ALeKk01ms5xRgCcmf8lDpGk4tXy7HbU36w:1628228357692&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj27f2m15vyAhXDw4sBHVW8BjwQ_AUoA3oECAEQBQ&biw=1440&bih=725) is the Google Search I meant to copy and paste.

**Review by noi5e — APPROVED** [review]

**Comment by noi5e** [comment]
@Ash-KODES Nice work! Looks great to me. Merging now.

**Comment by Ash-KODES** [comment]
thank you!

**Pull request merged**
