### PR TITLE
Test for checking email notifications on wiki page comments works #1438

### PR DESCRIPTION
**Pull request by aspriya**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks good but can you check the subject line or body of the emails to be sure they're the right emails and not some unrelated ones?  Thanks!

**Comment by ryzokuken** [comment]
@aspriya avoid making all those merge commits, it adds too much noise.

**Comment by jywarren** [comment]
That's true, it can lead to some conflicts too! Best practice is to rebase; you can learn more about that here:

Great guide: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

Another good one: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by jywarren** [comment]
But in this case it looks pretty clean, i.e. if you look at "Files changed" the changes look correct to me. So if you could just add tests for the title or body of the email, we should be OK.

**Comment by aspriya** [comment]
@ryzokuken, I'm verry sorry will not happen from here after. Old habbits die hard :smile: . And thanks @jywarren for the tips, will follow according to them. And I'm modifying the test as you stated

**Comment by ryzokuken** [comment]
@aspriya you don't need to apologize to me, I was just trying to point this out so that you don't face issues later, glad to be of help.

**Comment by jywarren** [comment]
Looks great! merged! 🎈

**Pull request merged**
