### PR TITLE
Fixed issue #2324 problem in display of gliphicons for comments and wiki nodes

### LINKED ISSUE #2324: Problem with some of the gliphicons display
### Please describe the problem (or idea)
The gliphicons on some of the posts in activity area of dashboard is appearing below the upper boundary of post, making some part of the gliphicon being cut out. I have seen this problem not just in dashboard but also on other pages where posts with gliphicon exists.

#### What happened just before the problem occurred? Or what problem could this idea solve?

Solving this issue would solve some of the UI related issue specifically CSS related issue.

#### What did you expect to see that you didn't?

Ideally the gliphicon show completely appear on top of each post in dashboard area.

### Please show us where to look
Browse to https://www.publiclab.org/dashboard and see posts in activity area.

### What's your PublicLab.org username?
sukhbir

### PR DESCRIPTION
**Pull request by sukhbir-singh**
Fixed #2324 
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. 
* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
Thanks!

### CODE REVIEW

**Comment by sukhbir-singh** [comment]
Problems with nodes:-
screenshot from 2018-02-15 00-19-41

Screenshot after solving issue:-
screenshot from 2018-02-15 00-20-08

**Comment by jywarren** [comment]
Wow, great fix! I struggled with this and couldn't find a solution. Thanks!!! 👍 👍 👍

**Comment by jywarren** [comment]
Fantastic!!

**Comment by sukhbir-singh** [comment]
Thank you @jywarren

**Pull request merged**
