### PR TITLE
Display comments in tags per stats graphs

### LINKED ISSUE #4770: Display comments in per-tag stats graphs
Related to https://github.com/publiclab/plots2/issues/4541, I think it would be great to be able to see how many comments have been made on all posts which bear a given tag, sort of to see how much "chatter" there's been in a topic area. We could stack this over the existing graphs in #4693, which is where this would be especially useful!

@cesswairimu what do you think?

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #4770 

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
comment1

**Comment by cesswairimu** [comment]
@jywarren how does this look?

**Comment by jywarren** [comment]
This looks great. Would you be able to add a unit test for the new tag model method?

**Comment by cesswairimu** [comment]
@jywarren just pushed the code for tests kindly take a look

**Comment by jywarren** [comment]
Awesome Cess! Great work as usual!

**Pull request merged**
