### PR TITLE
Update_wiki-controller.rb

### PR DESCRIPTION
**Pull request by CoderJolly**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by CoderJolly** [comment]
Please look into this PR @Gauravano

**Comment by CoderJolly** [comment]
I had done the same as mentioned in the problem bt still none of the test cases have been passed, pls have a lot at it and help.

**Comment by Gauravano** [comment]
Hi @CoderJolly nice work! Yes, as I mentioned in the issue, test fixes would be required with this issue. So, no worries we'll fix the tests.

**Comment by Gauravano** [comment]
Just a suggestion - including `Fixes #[issue-number]` in the PR body will automatically close the tagged issue, so including it is a good practice. Thanks!

**Comment by Gauravano** [comment]
Hi @jywarren this build stopped due to the wrong indentation. And `plotsbot` doesn't even show any helping message. Thoughts?

**Comment by Gauravano** [comment]
hi @CoderJolly as PR for the same issue is open at #3036 . Would you like to contribute there, you can help in fixing tests?

**Comment by Souravirus** [comment]
Hi @Gauravano, I think this rubocop issue can be solved by `rubocop --auto-correct` command. Thanks!!

**Comment by Gauravano** [comment]
Thanks @Souravirus! @CoderJolly you can try this, it would show you the real test failures we want to fix. Thanks! 
Also, we should show the rubocop errors too just like we show for Travis. What do you think @Souravirus @jywarren ?

**Comment by Souravirus** [comment]
Yeah I was also thinking of it @Gauravano let's open a new issue for it. Thanks!!

**Comment by Souravirus** [comment]
Hi @Gauravano, I have opened an issue related to this in #3047.

**Comment by jywarren** [comment]
Great, folks, thank you. I agree!

**Comment by Gauravano** [comment]
Collaborating in https://github.com/publiclab/plots2/pull/3037 .Thanks all!

**Pull request closed without merging**
