### PR TITLE
Updated _tab_content.html.erb with translation helper

### LINKED ISSUE #10166: Add Strings to Translation Function Call in _tab_content.html.erb
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update the following TWO files** below in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

#### 1. `app/views/tag/show/_tab_content.html.erb`:
```diff
- <p>Displaying content from <%= @start.to_formatted_s(:long) %> to <%= @end.to_formatted_s(:long) %>. <a href="/tag/<%= params[:id] %>">View all</a></p>
+ <p><%= raw translation('tag.show.displaying_content') %> <%= @start.to_formatted_s(:long) %> to <%= @end.to_formatted_s(:long) %>. <a href="/tag/<%= params[:id] %>">View all</a></p>
```

#### 2. `config/locales/en.yml`:
```diff
 456  show:
+457    displaying_content: "Displaying content from"
 458    notes_tagged: "Notes tagged with <i style=\"color:#aaa;\">%{tag}</i>"
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by Tiwarisonal19**
Fixes #10166 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Tiwarisonal19** [comment]
@noi5e please review this pr.

**Review by Tlazypanda — CHANGES_REQUESTED** [review]
Hey @Tiwarisonal19 looks like you are missing the changes to be made in the other file en.yml can you please add those changes to this pull request?

**Comment by Tiwarisonal19** [comment]
@Tlazypanda I have committed the left changes through another PR kindly check it.

**Comment by Tlazypanda** [comment]
Hey @Tiwarisonal19 actually we require the changes to be through a single pr so the commit history looks clean so can you please add another commit to this pr with the other file? Thanks :v:

**Comment by jywarren** [comment]
I believe this is linked to https://github.com/publiclab/plots2/pull/10236 - just noting!

@Tiwarisonal19 I think you need to make the change to the same branch - open the file within the branch here:

https://github.com/Tiwarisonal19/plots2/blob/patch-1/config/locales/en.yml

And copy in your changes from https://github.com/publiclab/plots2/pull/10236, and save to the same branch, `patch-1`. Then they'll be added to this PR automatically!

**Comment by Tiwarisonal19** [comment]
@jywarren is there a way I can commit both the changes in a single pr? I can't find a way to do that. I'm quite new to GitHub.

**Review by TildaDares — APPROVED** [review]
Thank you so much @Tiwarisonal19

**Comment by TildaDares** [comment]
@Tlazypanda Since the requested changes have been added, I think we can approve this.

**Comment by jywarren** [comment]
> @jywarren is there a way I can commit both the changes in a single pr? I can't find a way to do that. I'm quite new to GitHub.

Looks like you figured it out, thank you! I'm sorry I didn't reply faster!

**Pull request merged**
