### PR TITLE
Added OAuth hash for testing Github provider

### PR DESCRIPTION
**Pull request by SidharthBansal**
I have created auth hash for testing of Github provider. This is part of #2676 issue's Github provider subissue

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@jywarren can you please review the changes? This is ready.
@jywarren I want to know whether I should start working on Bootstrap Upgrade along with the OAuth OR shall I wait until we are done with OAUTH.
I am eager to learn more about bootstrap but managing both projects simultaneously may be difficult.
I will do whatsoever seems best to you.
Thanks

**Comment by jywarren** [comment]
I think let's try to get this all wrapped up and debugged. I'll make time early this week to go through the setup steps for the additional OAuth systems. In the meantime if you have nothing on your hands, perhaps you could tackle some smaller issues, like tests, codeClimate, things like that? I'd really appreciate it. 

Perhaps especially the persistent issue we're seeing with tests not completing properly and needing to be restarted? #2824 i think...

Merging this! Very exciting!

**Comment by SidharthBansal** [comment]
OK, then we will move to Bootstrap once we are completely done with OAuth. I have found MANY bugs at publiclab.org. Will you mind if I will create issues for all of them? 
I will send patches to some of the issues as well.
I will see the Travis for sure. I want to work on ``Account Deletion`` feature. It fascinated me a lot.

**Comment by SidharthBansal** [comment]
I am right now working on tests for Github Provider

**Comment by jywarren** [comment]
I think if you have a very big list, you could start with a kind of
planning issue from which you gradually break out new issues. That way it
doesn't flood the issue tracker all at once?

Great, thank you!!!!

**Comment by SidharthBansal** [comment]
Do we need still RuboCop Continuous Integration as listed in https://github.com/publiclab/plots2/issues/2814#issuecomment-397358254. If yes, I am happy to work on this too.

**Comment by SidharthBansal** [comment]
OR were you referring to do the rubocop changes?

**Comment by SidharthBansal** [comment]
Opening a new issue
Thanks

**Pull request merged**
