### PR TITLE
Fix alignment in subscriptions

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5612

### Earlier
Screenshot from 2019-05-22 19-16-42

### After Changes : Desktop
Screenshot from 2019-05-22 19-16-06

### After changes : Mobile
Screenshot from 2019-05-22 19-16-31

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Aha! This failed due to system tests -- @gautamig54 just had this happen too, i think. 

See how only one test run failed, but the other succeeded?

image

I've restarted them! Hopefully this works, but we may need to re-open #5683 ...

**Comment by CleverFool77** [comment]
Hi @jywarren yes it worked.
Now all the checks has passed.
Thanks !!

**Comment by jywarren** [comment]
Awesome!!!!!

**Comment by jywarren** [comment]
Great work!!!

**Pull request merged**
