### PR TITLE
Updated Nav tabs with a margin style

### PR DESCRIPTION
**Pull request by theOpetunde**
Updated div drop-down class with a margin-right of 5px style.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by theOpetunde** [comment]
@steviepubliclab hello. Please will you be kind to check what I am doing wrong? My code did not pass the CI integration test. Thank you

**Comment by steviepubliclab** [comment]
Hi! Thanks for reaching out. I'm not a coder, just a user of this website. Let me ping in someone else who might be able to help you. @cesswairimu maybe you can help here?

**Comment by cesswairimu** [comment]
sure @steviepubliclab ,Hi  @theOpetunde, I don't think you are doing anything wrong...reopening this so that we can figure it out. Thanks for working on this

**Comment by cesswairimu** [comment]
All the checks are passing now :tada: .. @theOpetunde, could you kindly add the issue number on the description where it has "Fixes issue_number" so that we can review this, also helps to close the issue automatically when the PR is merged. Thanks

**Comment by cesswairimu** [comment]
Hi @theOpetunde, kindly link the issue number of the fix. Thanks

**Comment by theOpetunde** [comment]
@cesswairimu Thank you. I closed this issue already and opened a new issue to solve the same problem

**Comment by cesswairimu** [comment]
cool

**Pull request closed without merging**
