### PR TITLE
Added shortlink icon to Questions page.

### PR DESCRIPTION
**Pull request by k-sau**
# Partial fix for #3093

I have added the short link icon on the question pages, other pages(wiki & notes) already have that icon. I am stuck at other two problems:
+ For mobile styling do I have to remove the classes like: ``hidden-xs hidden-sm hidden-print`` for showing the shortlink icon?
+ There's no `comment activity` feed is showing on my dashboard. So can't work on this yet, but I think i can implement this easily once i start seeing the comments activities on my dashboard

Here is my dashboard snap: https://i.imgur.com/j7X9XGe.png

### CODE REVIEW

**Comment by Gauravano** [comment]
Hi @k-sau, you need to make copy of schema.rb.example and put it at schema.rb as mentioned here https://github.com/publiclab/plots2#installation .Thanks!

**Comment by k-sau** [comment]
hey @Gauravano, did a fresh install and followed the step as mentioned by you and installation note but still having the same issue. Comments activities are not showing on my dashboard.

**Comment by Gauravano** [comment]
Hi @k-sau, could you please let me know the console output of `Comment.all` ? Thanks!

**Comment by k-sau** [comment]
https://pastebin.com/JjChHWqA. Thanks!!

**Comment by Gauravano** [comment]
@k-sau please put byebug at `app/views/dashboard/dashboard.html.erb` and then then check for `comments` in terminal

**Comment by k-sau** [comment]
@Gauravano, nothing's happening :( 

+ I added <% byebug %> at the beginning. Nothing happened.
+ I added < % byebug %> at the end. Still nothing happened.

Here is the screenshot https://imgur.com/a/zDAowm4

**Comment by Gauravano** [comment]
Hi @k-sau if you want we can connect via teamviewer?

**Comment by jywarren** [comment]
Hi, this is looking great, but would you mind removing the changes to `schema.rb.example` from your PR, as I think it's unrelated to your changes? 

https://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git

Thanks!!!

**Pull request closed without merging**
