### PR TITLE
Fixed user email for reply by tweet bug

### LINKED ISSUE #6167: Fix different email issue in reply by tweet
As we discussed in https://github.com/publiclab/plots2/issues/6085, there is an issue with reply by tweet which is currently when a user does login via twitter from a different email and linked it with the public lab id with a different email. We are not able to find the linked email because it only searches for the twitter email in `UserTag data` and here our algo fails. So we need to fix this out.

### PR DESCRIPTION
**Pull request by namangupta01**
Fixes #6167

### CODE REVIEW

**Comment by namangupta01** [comment]
@jywarren Let get this merge?

**Comment by jywarren** [comment]
Great!

**Comment by namangupta01** [comment]
Can you deploy so we can check the reply you did earlier get added?

**Comment by jywarren** [comment]
Sure, I'll schedule a deploy now. Thanks!

**Comment by namangupta01** [comment]
Let me know when it's done?
And also can you delete /cron_log1.log -- I guess it was not deleted yesterday?

**Comment by jywarren** [comment]
I just started it - you can monitor here!
https://jenkins.laboratoriopublico.org/ under "Deploy plots2". Thanks, and
also just deleted the cron file! Sorry, i had deleted the wrong one before.

**Comment by namangupta01** [comment]
No problem!

**Comment by namangupta01** [comment]
Your reply got added. See here. 🎉

**Comment by namangupta01** [comment]
https://publiclab.org/notes/mimiss/08-05-2019/trawling-with-babylegs-in-new-orleans-city-park

**Comment by jywarren** [comment]
🎉 🎉 🎉 🎉 🎉 🎉

**Comment by jywarren** [comment]
I tweeted a response to this too! https://publiclab.org/notes/warren/07-26-2019/community-atlas-an-around-the-world-collaboration-on-mapknitter

**Comment by jywarren** [comment]
Should we try to get the original tweet to appear as a comment too? Maybe under a "publiclab" username account?

**Comment by namangupta01** [comment]
I see it got added 
Screen Shot 2019-08-21 at 3 20 55 AM

Yeah! We can also try with the original tweet. Let me do some research over it.

**Pull request merged**
