### PR TITLE
Edit unique title validation failure message

### LINKED ISSUE #8319: Odd wording on unique title validation failure message: "base: You have already used this title."
The wording on the title uniqueness validator for new notes is a little odd:

image

Aha - ok, we probably don't have to print the "key" line here on line 368 -- let's just remove that!:

https://github.com/publiclab/plots2/blob/c55e1ff6983041e197c9a4e168f107c78688cbaf/app/views/editor/rich.html.erb#L367-L370

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### PR DESCRIPTION
**Pull request by avats-dev**
Fixes #8319 

After this fix:
Screenshot from 2020-09-21 00-45-04

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by avats-dev** [comment]
@sagarpreet-chadha , could you review this?

**Comment by avats-dev** [comment]
@cesswairimu FOR REVIEW!

**Comment by avats-dev** [comment]
@jywarren , is this good? Also check this out https://github.com/publiclab/plots2/issues/8225#issuecomment-695827542 .

**Review by cesswairimu — APPROVED** [review]
Looks great :tada: thanks

**Comment by jywarren** [comment]
Ohhhhh this is super. Thanks so much!!

**Pull request merged**
