### PR TITLE
Fix rubocop errors in app/api & app/channels

### PR DESCRIPTION
**Pull request by yamiacat**
This is aimed at Issue #6416 - the issue mentions `/app/api/channels` but that folder doesn't exist. There are two separate folders, `app/api` and `app/channels`, so maybe that's what was meant?

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by yamiacat** [comment]
Looks like I didn't catch all the errors - I will keep working on this tomorrow!

**Comment by moki298** [comment]
@yamiacat thanks for working on this, I have changed the title for the issue accordingly.

**Comment by yamiacat** [comment]
Thanks @moki298 ! I didn't get a chance to work on it last night, but definitely will over the weekend!

I'm excited to contribute! 😁

**Comment by yamiacat** [comment]
Hi @publiclab/reviewers - I think this is ready for review!

**Pull request merged**
