### PR TITLE
Fix Case Sensitivity issues

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Please look into this as soon as feasible.

**Comment by jywarren** [comment]
I appreciate the modularity here, and I agree on using `find_by_username_case_insensitive` -- good idea -- but perhaps we can just use case insensitive for all environments, rather than switch on production vs. development? Or does that extra method not work in `mysql`?

It looks like `mysql` does have `lower()`: http://stackoverflow.com/questions/221774/is-there-a-mysql-command-to-convert-a-string-to-lowercase

**Comment by ryzokuken** [comment]
@jywarren Cool, I just did that thinking 
> If it ain't broke, don't fix it
:P Anyway, moving to case insensitive for all environments.

**Comment by jywarren** [comment]
Do you think it'd be a good idea to add a test to ensure two users can't get the same name with different capitalizations? A unit test? Or not necessary?

**Comment by ryzokuken** [comment]
@jywarren Is it not desirable for capitalizations to make names unique (definitely not in this case, but otherwise) if that's the case, we could just remove all hassles by making usernames lowercase only. That would also make the URLs more legible (dunno why, capitals look strange in URLs)

**Comment by jywarren** [comment]
I think that would have been easier to do at the beginning, but now we'd have to double check that there are no collisions, and also do some extra work to ensure that nothing would break if we shift everyone to lower-case... probably some testing, for starters. But for now, this is a good step -- if we do more, we should do it as a separate issue and PR. Thanks!

**Pull request merged**
