### PR TITLE
Update CT links in fto-issue-template

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@publiclab/plots2-reviewers this is done to prevent the page from being redirected to code.publiclab.org from publiclab.github.io/community-toolbox. Please review :)

**Comment by sashadev-sky** [comment]
@HarshKhandeparkar is it just a fix to make it link directly to the page instead of indirectly though the previous community toolbox link? In that case looks good to me!

**Comment by HarshKhandeparkar** [comment]
Yes it is. Earlier, i think, toolbox didn't have a domain of its own. It used to use the publiclab gh-pages. I have updated the links

**Comment by sashadev-sky** [comment]
@jywarren I think this one is small enough to merge without another review  👍

**Comment by gauravano** [comment]
Thanks @HarshKhandeparkar @sashadev-sky!

**Pull request merged**
