### PR TITLE
Fix add descriptive tags below link

### LINKED ISSUE #7846: Link needs updating or removal
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I saved a draft note, which went well. Then i noticed at the top of the draft, there was a link on the words "adding a descriptive tag below" which did not do anything when clicked. Here is what it displays: 

Screen Shot 2020-04-28 at 10 52 51 AM

descriptive-tags-broken-link

> What did you expect to see that you didn't?

I expected this link to do somewhere, or else for this text to not be hyperlinked. 

### Please show us where to look

https://publiclab.org/notes/show/23484/rbl4sGfcW8_ef_SWkHWhHg

### What's your PublicLab.org username?

Liz

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #7846 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

## GIFS  
descript

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@VladimirMikulic can you kindly review? Thanks :smile: also is the tag_selection_test problem back :cry: Travis logs say so :sweat_smile:

**Comment by Tlazypanda** [comment]
@VladimirMikulic Thanks for the review !! Please do have a look @Uzay-G  whenever free :sweat_smile:  Looping in @jywarren @cesswairimu the travis test issue is back it seems :cry:

**Comment by cesswairimu** [comment]
:facepalm: restarting travis

**Comment by cesswairimu** [comment]
Okay, that did the trick..will take a look if there is a way to make the test more dynamic

**Comment by jywarren** [comment]
Hooray! And sorry @cesswairimu but i did enjoy your emoji 🤦 ❤️

**Pull request merged**
