### PR TITLE
Unban functionality in dropdown

### LINKED ISSUE #7507: Enhance the unban functionality
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Currently if a user is banned the admin has to go to it's profile to unban the user.I would be better if the admin is provided with the unban option in the dropdown itself.
**Current Behaviour**
Untitled_ Feb 16, 2020 12_05 AM

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****
### Update from @jywarren 

Hi, i think one issue here is that we are aiming to have very maintainable code and so are a little hesitant to add complex interfaces in duplicate. I wonder if we could do 2 things:

1. could we format the `banned` label a bit? Off topic, but it looks a little funny, no?
2. could we have, on a second line in the popup, something that says `Unban on profile` and link to the profile? this wouldn't require a test to protect new functionality and is pretty simple.

### PR DESCRIPTION
**Pull request by sssash18**
Fixes #7507  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
**New Behaviour**
Untitled_ Feb 16, 2020 1_22 PM

### CODE REVIEW

**Comment by sssash18** [comment]
@cesswairimu Any update on this?

**Comment by cesswairimu** [comment]
sorry @sssash18, sorry this took a while but we got input from Jeff and Liz on the issue. Kindly take a look and see if its something you would be interested on implementing

**Comment by cesswairimu** [comment]
https://github.com/publiclab/plots2/issues/7507#issuecomment-668713711

**Comment by cesswairimu** [comment]
This PR has been open for a long time and no activity/ reviews requested has not been addressed. We understand you might be busy and engaged on other things. I am closing this for now...please  feel free to reopen if you get some time and would like to finish this. Rem to check if its still available before you reopen. Thanks

**Pull request closed without merging**
