### PR TITLE
Fixes to make Plots work easily in cloud9

### PR DESCRIPTION
**Pull request by icarito**
There was a dangling space after `database.yml.sqlite.example` which made it not found.
It's a tiny fix. However still there appears to be an issue with Mysql2 gem.

### CODE REVIEW

**Comment by jywarren** [comment]
Thanks!

**Comment by icarito** [comment]
Just a note that this still doesn't fix all issues on cloud9, currently I'm following the documentation and reaching:
```
icarito:~/workspace (fix_cloud9) $ rake db:setup --trace                                                                                        
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke rails_env (first_time)
** Execute rails_env
** Execute db:create
development.sqlite already exists
test.sqlite already exists
** Invoke environment (first_time)
** Execute environment
rake aborted!
Gem::LoadError: mysql2 is not part of the bundle. Add it to Gemfile.
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.4/lib/bundler/rubygems_integration.rb:350:in `block (2 levels) in replace_gem'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/mysql2_adapter.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/home/ubuntu/workspace/config/initializers/abstract_mysql2_adapter.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/engine.rb:592:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/engine.rb:592:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/application.rb:136:in `initialize!'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/ubuntu/workspace/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/application.rb:103:in `require_environment!'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-3.2.22.5/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.3.0/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
```

**Comment by jywarren** [comment]
But isn't mysql in the gemfile?

https://github.com/publiclab/plots2/blob/master/Gemfile#L8-L9

Oh, but on cloud9 we're assuming an sqlite install:
https://github.com/publiclab/plots2/blob/master/install_cloudnine.sh#L9

Why is it asking for mysql?

**Comment by icarito** [comment]
El 21/04/17 a las 09:46, Jeffrey Warren escribió:
> Oh, but on cloud9 we're assuming an sqlite install:
> https://github.com/publiclab/plots2/blob/master/install_cloudnine.sh#L9
>
> Why is it asking for mysql?
Exactly!
This is with database.yml.sqlite.example so it shouldn't need Mysql.

**Pull request merged**
