### PR TITLE
Increase maxWarmSearchers and enable Cold searchers

### PR DESCRIPTION
**Pull request by icarito**
...to try to improve performance addressing #1604

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

### CODE REVIEW

**Comment by icarito** [comment]
I'll merge this in order to test it on staging.

**Comment by jywarren** [comment]
Is Solr enabled on staging? I don't see https://publiclab.org/api/typeahead/all?srchString=precocious returning anything.

**Comment by icarito** [comment]
No, I think it's not enabled.

**Comment by icarito** [comment]
Actually, it was enabled :-)

**Pull request merged**
