### PR TITLE
(to unstable branch) Adjust opengraph tag to show scrapped image

### LINKED ISSUE #8273: adjust OpenGraph tags for questions/notes/wikis
### Please describe the problem (or idea)

adjust OpenGraph tags for questions/notes/wikis so that if no main image is available, openGraph lead image tags show a "scraped" lead image (see how we do this in card display, for example https://publiclab.org/tag/bucket-monitor shows a scraped lead image for https://publiclab.org/notes/kgradow1/07-03-2020/bucket-monitor-prototype)

will be making a PR for this soon

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
Fixes #8273 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
Hi @sagarpreet-chadha @jywarren @cesswairimu can you merge this? Using it to test https://github.com/publiclab/plots2/pull/8284

**Comment by jywarren** [comment]
Yep! Done! Thanks!!!!

**Comment by Shulammite-Aso** [comment]
This didn't work.🙊

I guess i'ld have to request from @cesswairimu or anybody who knows about how to access an image(preferably the first image) from the post's body from this file.

Also perhaps default to the public lab logo when the post has no image at all: main_image and post body image. Will this be okay.

**Comment by sagarpreet-chadha** [comment]
Hey @Shulammite-Aso , 
Can you look at this amazing data model representation to learn the relationships between tables in the DB: https://github.com/publiclab/plots2/blob/main/doc/DATA_MODEL.md
So from the image in the above link we can see that each node `has many` images which we can see in `node.rb`, line:

https://github.com/publiclab/plots2/blob/cc59cda67fe9de77179963c45c264a703e17277e/app/models/node.rb#L91

So once you have reference of that node ruby object, using images `getter` function we can get all the images, right.

Thanks! 😄 

Also in the documentation of twitter it is mentioned that the images size should be of certain size and ratio: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

We can test the images displayed using these tools provided by FB and twitter:
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
https://developers.facebook.com/docs/sharing/webmasters/

**Comment by sagarpreet-chadha** [comment]
Also you can use gitpod url to test instead of pushing to unstable:
https://3000-c5782e9a-bc16-446a-a16e-e2eaaaf4ab1c.ws-us02.gitpod.io/wiki/licenses

**Pull request merged**
