### PR TITLE
aligning stats page

### LINKED ISSUE #5577: Aligning stats page
Currently, the date input part on the stats page looks a bit broken. 

Screen Shot 2019-04-22 at 4 46 06 PM

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5577  (<=== Add issue number here)

Screen Shot 2019-04-22 at 4 44 14 PM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
@publiclab/reviewers Kindly review this PR. Thanks!

**Comment by gautamig54** [comment]
@publiclab/plots2-reviewers Kindly review this PR. Thanks!

**Comment by gauravano** [comment]
hey @gautamig54, can you also correct the alignment for /stats page as button seems a little misaligned  with the field?
 
Screenshot from 2019-04-23 02-20-10
 
Thanks!

**Comment by gautamig54** [comment]
@gauravano done!

Screen Shot 2019-04-23 at 2 34 26 AM

**Comment by gauravano** [comment]
Looks like mobile view for /tag/[tagname]/stats needs some work 
Screenshot from 2019-04-23 02-49-27

**Comment by gautamig54** [comment]
@gauravano I'll update the PR. Also, I was thinking if I could add Starting and Ending labels in /tag/[tagname]/stats?

**Comment by gauravano** [comment]
Sure!

**Comment by gautamig54** [comment]
@gauravano I made the required changes. Kindly check.

Screen Shot 2019-04-23 at 3 20 51 AM

**Comment by gautamig54** [comment]
@gauravano how is this?

Screen Shot 2019-04-23 at 3 20 51 AM

**Comment by gauravano** [comment]
Looks great!

**Comment by jywarren** [comment]
Awesome, thanks all! I've also added an automated screenshot for the stats page just now :-)

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/5880

**Pull request merged**
