### PR TITLE
Grammar fix  Issue 9451

### LINKED ISSUE #9451: Grammar fix
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [README.md](https://github.com/publiclab/plots2/blob/main/README.md) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -113,7 +113,7 @@ _kindly note if you choose to use sqlite some tests may fail. The project was se
 9. Install static assets (like external javascript libraries, fonts) with `yarn install`
 10. Setup React & webpacker by running `rails webpacker:install && rails webpacker:install:react && rails generate react:install`
 (for local SSL work, see [SSL](#ssl-in-development) below)
-11. Start the server with `passenger start` and navigate to `http://localhost:3000/` in your browser.
+11. Start the server with `passenger start` and navigate to `http://localhost:3000/` on your browser.
 12. Wheeeee! You're up and running! Log in with test usernames "user", "moderator", or "admin", and password "password".
 13. Run `rails test` to confirm that your install is working properly. You can also run `rails test:system` for system tests. (_Note: if you chose sqlite as your database, some tests may fail; Please ignore these, we are working to fix this. If your server starts correctly, you are all set_)
 
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by Elukoye**
fix grammatical error in the README file.

Fixes #9451  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by waridrox — APPROVED** [review]
LGTM 😄 🎉

**Comment by Elukoye** [comment]
@waridrox , can you please check if I have done the correct thing ?

**Comment by waridrox** [comment]
> @waridrox , can you please check if I have done the correct thing ?

Yes, I've checked it! 🚀

**Comment by govindgoel** [comment]
@Elukoye LGTM

**Comment by Elukoye** [comment]
@waridrox what happens next ? You merge 👍 ?

**Comment by waridrox** [comment]
@Elukoye, just be patient and reviewers with write access will get it merged asap 😄. Meanwhile you can try to solve other issues ✌️

**Comment by Elukoye** [comment]
@waridrox ok 😀

**Comment by NishantJawla** [comment]
@Elukoye  I was thinking of working on this issue and found some additional changes that can be made under this issue can we collaborate together and send an updated pull request

**Comment by waridrox** [comment]
Hi @NishantJawla 😄, I think it would better to open an issue addressing the changes that you are thinking of and make a PR accordingly rather than making changes in this PR. Thanks :)

**Comment by NishantJawla** [comment]
@waridrox  Thanks for the advice will do so

**Review by cesswairimu — APPROVED** [review]
:tada:

**Comment by cesswairimu** [comment]
Awesome :tada: thanks for working on this @Elukoye 
Thanks @govindgoel and @waridrox for the reviews :tada: :tada:

**Comment by Elukoye** [comment]
@NishantJawla, do you still want to collaborate?

**Comment by NishantJawla** [comment]
> @NishantJawla, do you still want to collaborate?

Yeah! You can contact me on Twitter (@jawla_nishant)

**Pull request merged**
