### PR TITLE
Add tooltips to follow button and tools dropdown on the like bar

### LINKED ISSUE #5820: Tooltips for interface consistency and clarity on wiki and blog
follow-tools

Similar to closed issue #2115 and open issue #5382.
The follow buttons and tools dropdown don't have tooltips on mouseover.

### PR DESCRIPTION
**Pull request by michelelong**
Fixes #5820 
tools-tooltip
follow-tooltip

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by michelelong** [comment]
System test failed on: FAIL["test_viewing_the_dashboard", #<Minitest::Reporters::Suite:0x00007fc2a55e7378 @name="DashboardTest">, 65.62211653899999] which looks to be the error from issue #5683. I don't know what to do now. @publiclab/reviewers

**Comment by gauravano** [comment]
Hi @michelelong, thanks for PR. Hmm, the test failure is not related to your code. We are trying to solve a issue #5683 with our system test runtime and it seems that's the reason here too. I will just restart the build. Sorry for the false alarm.

**Comment by michelelong** [comment]
inconsistant-fix

There was a weird inconsistency in the "flag as spam" and "like it" tooltips. On some pages like /blog they showed up underneath the button and without the arrow. Added data-tooltip and data-placement to them makes them show the same way on all pages.

space-problem

Under certain circumstances the author name was jammed up against the icon.  I just added a non-breaking space to fix it.

print-fix

A more descriptive tooltip for the dropdown menu.

**Comment by jywarren** [comment]
This looks awesome!!!

**Comment by gauravano** [comment]
Merged :tada: :balloon: :+1: 

Looking forward to more of your awesome contributions :smile:. And, let us know if you want to take on more complex tasks? Although, your help is very welcome with any of the https://github.com/publiclab/plots2/issues


Thanks!!

**Pull request merged**
