### PR TITLE
Font color change for "Profile" in header and alignment of buttons on Methods page

### LINKED ISSUE #3453: Improve navbar for short resolution or mobile view Part 2
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
 
-  Click on Profile
login wiht

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 
change text color
Code links….
https://github.com/publiclab/plots2/blob/fdf99c577d9ceeddc45c7726e9578d9af13418e0/app/views/layouts/_header.html.erb#L94
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by CodeSarthak**
Fixes #3453 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by CodeSarthak** [comment]
So, should I create a new pull request to a separate branch? 
Also, what checklist ? The one in the comments of the PR?

Sent from Mail for Windows 10

**Comment by CodeSarthak** [comment]
@igniteeng000 Hey, can you be more specific about the text style? Do you want me to change the font type?

**Comment by avsingh999** [comment]
@CodeSarthak  you need to change only text color
look this comment https://github.com/publiclab/plots2/issues/3453#issuecomment-426679510
thanks :)

**Comment by CodeSarthak** [comment]
Oh, thanks for the clarification @avsingh999. Going to start a new pull request.

**Comment by igniteeng000** [comment]
You have seen how public lab is visible in the header. Do something like that change font weight,font-color etc.

**Comment by CodeSarthak** [comment]
Sure @igniteeng000 Appreciate your suggestion.

**Comment by CodeSarthak** [comment]
The thing is that I cannot test the changes as I make them. I am not sure how to run .erb files but I have made another pull request.

**Comment by igniteeng000** [comment]
You can try your changes on chrome developer tools(ctrl+shift+i). Go give it a try

**Comment by CodeSarthak** [comment]
Thanks a ton! I love how we get to learn new things with each task.

**Comment by igniteeng000** [comment]
This is the motto of GCI. Learning is the main factor.

**Comment by CodeSarthak** [comment]
Updated it. It looks good according to me now,

**Comment by igniteeng000** [comment]
And thanks for your hard work! We really appreciate it, you're almost there! 😄 🎉

**Comment by CodeSarthak** [comment]
Thanks a lot, man! I will go and do more tasks for your organisation, love working with you guys.

**Comment by avsingh999** [comment]
@CodeSarthak can you please post a screenshot/gif it would be easy to us

**Comment by CodeSarthak** [comment]
Screenshot/Gif for what? The change in color?

**Comment by CodeSarthak** [comment]
I have a problem, in another issue. There was no response, so I thought I would put up the link here. 
https://github.com/publiclab/plots2/issues/3732

**Comment by avsingh999** [comment]
> Screenshot/Gif for what? The change in color?
@CodeSarthak 
yes, We'd like to see the text colors of the changes you've made.
thanks :)

**Comment by CodeSarthak** [comment]
updatedcolorscreenshot
PFA the screenshot of the updated color for "Profile".
Thanks and Regards.

**Comment by CodeSarthak** [comment]
These are commits for : https://github.com/publiclab/plots2/issues/3532

**Comment by CodeSarthak** [comment]
Please review @avsingh999 @SidharthBansal @jywarren

**Comment by avsingh999** [comment]
@CodeSarthak can you please add  that screenshot which I have added in this issue https://github.com/publiclab/plots2/issues/3453
thanks :)

**Comment by CodeSarthak** [comment]
That is a different issue which has already been resolved earlier.

**Comment by CodeSarthak** [comment]
This is for #3532

**Comment by avsingh999** [comment]
> That is a different issue which has already been resolved earlier.

Sorry I was confuse because you have added wrong issue number in pull request :smile:

**Comment by CodeSarthak** [comment]
Okay then. If it is all resolved and cleared, can the task be closed?

**Comment by jywarren** [comment]
I see -- this combines fixes for 2 issues. I've updated the title accordingly, and this is a great reason for PR titles to be more descriptive, so you can easily keep track of what change they implement. Less confusing! I'll merge this now, but I am still trying to find the other issue -- the navbar color change -- to mark as closed.

**Comment by jywarren** [comment]
OK, just clarifying that this solved both #3453 AND #3532 (such similar numbers!). @CodeSarthak should get GCI credit for both. I mistakenly unassigned CodeSarthak from the GCI task for #3532, but if they re-claim it, I will issue approval for that in GCI (as may any other mentor). 

Apologies for the mixup, hopefully clearly naming PR titles descriptively in the future will help avoid confusion! Thanks, everyone!!!

**Comment by CodeSarthak** [comment]
Hey, thanks a lot for clearing the confusion @jywarren.  I already claimed another task for Public Labs. I will claim the task after I am complete this one, so that it can be approved. I will be more careful regarding PR names from now on. 
Thanks.

**Comment by CodeSarthak** [comment]
Hi, I just checked and this task is not available anymore. Can I still get credit for it?

**Comment by CodeSarthak** [comment]
Hey, I have claimed the task again. Can it be accepted now, @jywarren? Thanks.

**Comment by gauravano** [comment]
@CodeSarthak please claim it again. Thanks! 

**Note: According to GCI rules, you can work on only one task at a time so please refrain from doing multiple tasks in a single PR or raising PR for a task which is not claimed. Thanks!**

**Pull request merged**
