### PR TITLE
fix toolbar jumping

### LINKED ISSUE #6251: toolbar positioning bug
Toolbar for the editor on https://publiclab.org/post has very sporadic behavior. Jumps to top and bottom of page. Should just stay relative to the markdown container. 

Below it goes to bottom - less obviously disruptive than when it jumps to top

pl

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #6251  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
**before:** - toolbar will jump to top and bottom of page -- doesn't belong there

pl

**after:** - toolbar stays relative to its markdown editor
plfix

**Comment by sashadev-sky** [comment]
@publiclab/reviewers @jywarren I had to use a very high specificity css selector to make this work:

```JS
div.wk-commands.btn-group {
  position: relative !important;
}
```

i couldn't figure out how to fix it otherwise because the code for it is coming from `PublicLab.Editor`, but in all of those demos the toolbar works fine. No idea if there is some sort of initializer option that could have been passed on the plots2 end to make it toggle btwn `relative` and `fixed`, or something with version control upstream. Definitely was not set on the element in runtime anywhere. 
@publiclab/plots2-reviewers
@rexagod I think I remember u used to work on this project!

**Comment by sashadev-sky** [comment]
note I bumped PublicLab.Editor but it had this bug in both versions anyway

**Comment by gauravano** [comment]
I don't remember the exact issue but I think, it was done on-purpose in some isssue. @jywarren @rexagod may remember

**Comment by sashadev-sky** [comment]
@gauravano would be good to see that! Im sure whatevr it was intended to do was not this

**Comment by jywarren** [comment]
Hi, the purpose was to have the toolbar stick to the bottom of the viewport
IF the contents of the textarea were so long that they became no longer
visible on the same page. What looks like happened was that now it appears
pegged to viewport even if the textarea is no longer on the screen.

So, I wonder if we can adapt this so that it only pegs if the textarea is
onscreen, but the bottom of the textarea is NOT?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
