### PR TITLE
Form UI change in different screens

### LINKED ISSUE #9285: Form UI Change in different screens
#### What happened just before the problem occurred? Or what problem could this idea solve?
In mobile view, there is no space between the two forms which makes the overall UI look bad.

Screenshot from 2021-03-11 23-22-30_3

When the user is not logged in, the two forms are not perfectly aligned.

Screenshot from 2021-03-11 23-22-06_2

#### What did you expect to see that you didn't?

Improve the alignment and overall UI of the forms.

### Please show us where to look

https://publiclab.org/questions

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
- Browser: Chromium Version 89.0.4389.82 (Official Build)
- OS: Ubuntu 20.04.1 LTS

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by sahilsaha7773**
Fixes #9285  

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### Screenshots
Screenshot from 2021-03-12 00-39-00
Screenshot from 2021-03-12 00-37-30

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @sahilsaha7773 and thanks for working on this...from your changes it doesn't seem like it should affect that failing test
```
======================================================= FAIL SearchControllerTest#test_search_question_at_/search/questions/question (110.95s)
        Expected: 8
          Actual: 15
        test/functional/search_controller_test.rb:51:in `block in <class:SearchControllerTest>
```
I will close and reopen the PR to see if the test passes the second time. Thanks

**Comment by sahilsaha7773** [comment]
> Hi @sahilsaha7773 ,thanks for working on this...from your changes it doesn't seem like it should affect that failing test
> 
> ```
> ======================================================= FAIL SearchControllerTest#test_search_question_at_/search/questions/question (110.95s)
>         Expected: 8
>           Actual: 15
>         test/functional/search_controller_test.rb:51:in `block in <class:SearchControllerTest>
> ```
> 
> I will close and reopen the PR to see if the test passes the second time. Thanks

yes, sure, I too am confused why the test is failing :worried:.

**Comment by cesswairimu** [comment]
yeah its confusing at times...we have some intermittent failing tests..we are working to them..sorry about that...looks like we are all green now :tada:

**Review by cesswairimu — APPROVED** [review]
The changes look great..thanks again for fixing this :tada:

**Comment by sahilsaha7773** [comment]
> yeah its confusing at times...we have some intermittent failing tests..we are working to fix them..sorry about that

it's fine 😄

**Pull request merged**
