### PR TITLE
ADD: Rich text editor image upload system tests

### PR DESCRIPTION
**Pull request by VladimirMikulic**
Part of #5316

### CODE REVIEW

**Comment by jywarren** [comment]
Restarting to see if CodeCov resolves differently :-/

**Comment by VladimirMikulic** [comment]
@jywarren it does :-)

**Comment by jywarren** [comment]
a little bit disconcerting, but i'm OK with it for now! Let's do think on how to fix it, though. First maybe we need to document it thoroughly.

**Comment by jywarren** [comment]
Thank you!!!

**Comment by VladimirMikulic** [comment]
Please ask and I will explain. The thing that I did here is that I refactored `drop_in_dropzone` to accept an additional parameter `dropzoneSelector`. This way function is reusable.

**Comment by VladimirMikulic** [comment]
I should have mentioned this in the commit message. I apologise.

**Comment by jywarren** [comment]
No, sorry, i was referring to the uncertainty about CodeCov! my bad! i think it must be some timing/ordering issue which is making it report in coverage non-deterministically. or at least inconsistently.

**Comment by VladimirMikulic** [comment]
Oh, so it's CodeCov. How can I help you with CodeCov?

**Comment by Uzay-G** [comment]
@jywarren what is wrong with the coverage?

**Comment by jywarren** [comment]
It seems to be quite inconsistent. We are bouncing between 60-80% coverage. And, re-running Travis can result in different outcomes, as happened here.

**Pull request merged**
