### PR TITLE
Trending tags showing duplicates: group only by name

### LINKED ISSUE #3188: Trending tags showing duplicates
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

I think we're missing a `group()` or something on the https://publiclab.org/dashboard's trending tags area - i'm seeing 5 of the same:

screen shot 2018-08-02 at 12 29 19 pm

Here's the code - 

https://github.com/publiclab/plots2/blob/0663ac5f7ad7d047fc47e2b5b9ae59c943f354bc/app/models/tag.rb#L268-L277

And here's the test, where i'm not sure but maybe we should test to be sure they're unique? 

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/test/unit/tag_test.rb#L131-L137

Any help appreciated!

### PR DESCRIPTION
**Pull request by milaaraujo**
Fixes #3188

### CODE REVIEW

**Comment by milaaraujo** [comment]
Hey @jywarren,
I think the problem here is the `group([:name, 'node.nid', 'term_data.tid', 'community_tags.nid', 'community_tags.uid', 'community_tags.date'])`. There is this note "ONLY_FULL_GROUP_BY, issue #3120", but I didn't understand why we need to group by all these columns if all we need is the name.

Locally, running the query with the `group([:name, 'node.nid', 'term_data.tid', 'community_tags.nid', 'community_tags.uid', 'community_tags.date'])` we have duplicates:
```
MariaDB [publiclab_dev]>   SELECT  node.nid, node.created, node.status, term_data.*, community_tags.* FROM `term_data` 
    ->   INNER JOIN `community_tags` ON `community_tags`.`tid` = `term_data`.`tid` 
    ->   INNER JOIN `community_tags` `node_tags_term_data_join` ON `node_tags_term_data_join`.`tid` = `term_data`.`tid` 
    ->   INNER JOIN `node` ON `node`.`nid` = `node_tags_term_data_join`.`nid` 
    ->   WHERE (node.status = 1) AND (node.created > 1541922310) AND (node.created <= 1544514310) 
    ->   GROUP BY `term_data`.`name`, node.nid, term_data.tid, community_tags.nid, community_tags.uid, community_tags.date 
    ->   ORDER BY count DESC LIMIT 5;
+-----+------------+--------+-----+-----+-------------------+-------------+--------+-------+--------+-----+-----+-----+------------+
| nid | created    | status | tid | vid | name              | description | weight | count | parent | tid | nid | uid | date       |
+-----+------------+--------+-----+-----+-------------------+-------------+--------+-------+--------+-----+-----+-----+------------+
|  44 | 1544511014 |      1 |  73 |   3 | first-time-poster |             |      0 |     2 | NULL   |  73 |  44 |   4 | 1544511017 |
|  44 | 1544511014 |      1 |  73 |   3 | first-time-poster |             |      0 |     2 | NULL   |  73 |  45 |   4 | 1544511072 |
|  45 | 1544511072 |      1 |  73 |   3 | first-time-poster |             |      0 |     2 | NULL   |  73 |  44 |   4 | 1544511017 |
|  45 | 1544511072 |      1 |  73 |   3 | first-time-poster |             |      0 |     2 | NULL   |  73 |  45 |   4 | 1544511072 |
|   8 | 1544077622 |      1 |   2 |   0 | blog              |             |      0 |     1 | NULL   |   2 |   8 |   1 |          0 |
+-----+------------+--------+-----+-----+-------------------+-------------+--------+-------+--------+-----+-----+-----+------------+
```
Running only with `.group([:name])` we don't have duplicates:
```
MariaDB [publiclab_dev]>   SELECT  node.nid, node.created, node.status, term_data.*, community_tags.* FROM `term_data` 
    ->   INNER JOIN `community_tags` ON `community_tags`.`tid` = `term_data`.`tid` 
    ->   INNER JOIN `community_tags` `node_tags_term_data_join` ON `node_tags_term_data_join`.`tid` = `term_data`.`tid` 
    ->   INNER JOIN `node` ON `node`.`nid` = `node_tags_term_data_join`.`nid` 
    ->   WHERE (node.status = 1) AND (node.created > 1541922310) AND (node.created <= 1544514310) 
    ->   GROUP BY `term_data`.`name`
    ->   ORDER BY count DESC LIMIT 5;
+-----+------------+--------+-----+-----+------------------------+-------------+--------+-------+--------+-----+-----+-----+------------+
| nid | created    | status | tid | vid | name                   | description | weight | count | parent | tid | nid | uid | date       |
+-----+------------+--------+-----+-----+------------------------+-------------+--------+-------+--------+-----+-----+-----+------------+
|  44 | 1544511014 |      1 |  73 |   3 | first-time-poster      |             |      0 |     2 | NULL   |  73 |  44 |   4 | 1544511017 |
|   8 | 1544077622 |      1 |   2 |   0 | blog                   |             |      0 |     1 | NULL   |   2 |   8 |   1 |          0 |
|   9 | 1544077623 |      1 |   4 |   0 | lon:1.44819439410508   | Desc 0      |      5 |     1 | NULL   |   4 |   9 |   1 |          0 |
|  10 | 1544077623 |      1 |   5 |   0 | lat:8.814665776391895  | Desc 1      |      5 |     1 | NULL   |   5 |  10 |   1 |          0 |
|  10 | 1544077623 |      1 |   6 |   0 | lon:17.365520433555464 | Desc 1      |      5 |     1 | NULL   |   6 |  10 |   1 |          0 |
+-----+------------+--------+-----+-----+------------------------+-------------+--------+-------+--------+-----+-----+-----+------------+
```

**Comment by milaaraujo** [comment]
desenho sem titulo 1

**Comment by SidharthBansal** [comment]
Hi @milaaraujo can you please see #4263. Thanks

**Comment by milaaraujo** [comment]
@Sidharth Bansal I will review the other PR later, if it is working we can merge it and I close this one.

**Comment by jywarren** [comment]
Yes, and thanks for being very thorough. It looks like @ValentinaTironi has implemented something different here -- a `.pluck(:name)` addition to the end of the ActiveRecord chain. I'm not sure what `pluck()` does, actually? 

What's so weird about the bug that was resolved by the addition of `group([:name, 'node.nid', 'term_data.tid', 'community_tags.nid', 'community_tags.uid', 'community_tags.date'])` is that it wasn't reproducible in Travis, and wasn't showing up in tests. So I fixed and tested it locally and left the note of #3120 for future documentation. 

Unfortunately this was to fix a recurring error which people had been experiencing in local copies (although not in the production site or Travis tests) -- notes in https://github.com/publiclab/plots2/issues/3120 and it looks like it was related to a change in default config for MySQL -- 5.7 in particular -- see [my comment here](https://github.com/publiclab/plots2/issues/3120#issuecomment-406808699) about `ONLY_FULL_GROUP_BY`. 

Maybe we don't have to worry about this anymore if we're now on `mariadb` 10.2 ([see versions here](https://github.com/publiclab/plots2/search?q=mariadb&unscoped_q=mariadb) what do you think? do enough people use MySQL still that we should remain backwards-compatible, and/or is there another way to fix this that wouldn't cause trouble on MySQL 5.7 and subsequent versions?

**Comment by milaaraujo** [comment]
I also don't know what `pluck()` does... I will review her PR later.

However this query doesn't look right to me, I think it is selecting and grouping more columns that are really necessary... I think we just need:   

```
    Tag.joins(:node_tag, :node)
       .where('node.status = ?', 1)
       .where('node.created > ?', start_date.to_i)
       .where('node.created <= ?', end_date.to_i)
       .group([:name])
       .order('count DESC')
       .limit(limit)
```
or maybe:
```
    Tag.select([:name])
          .joins(:node_tag, :node)
          .where('node.status = ?', 1)
         .where('node.created > ?', start_date.to_i)
         .where('node.created <= ?', end_date.to_i)
         .distinct
         .order('count DESC')
         .limit(limit)
```
I'm using `mariadb` so I don't know if we will have - MySQL - problems with these modifications. Do you have mysql installed?

**Comment by jywarren** [comment]
Hmm. So i totally agree that we are including too much, but had added that in to get `mysql` compatibility. How about this. Let's:

1. make a change here -- going back to the more minimal version without the extra grouping, but leaving in a link back to this PR discussion in case it breaks again. 
2. Then let's merge this, 
3. then let's actually open a PR where we change the database back to mysql (but version 5.7) to see if the error crops up there again. That'll require:

`    image: mysql:5.7`

to be added to this line: 

https://github.com/publiclab/plots2/blob/57a6b049490a8c83ccc6845698ec4cb7a11722d7/containers/docker-compose-testing.yml#L4

Let's do that as soon as this is merged. So if you could add the comments, i'll merge, and we can do the next steps. Thanks!!!

**Comment by ValentinaTironi** [comment]
`pluck` does the same of `map(&:name)`. I just did a fast solution but you both are doing a deeper solution and that is really great! 
I'm agree with @milaaraujo I also think that the query has a lot of unnecessary things. Maybe the solution is refactor it after check what of queries are really necessary 
@milaaraujo @jywarren

**Comment by ValentinaTironi** [comment]
So, we are going to change of mysql version?

**Comment by milaaraujo** [comment]
I think we just need to test if this solution works with MySQL, because some people still use MySQL for development... Right, @jywarren?
 
I'm using `mariadb`. Prodution and Travis also use `mariadb`

**Comment by ValentinaTironi** [comment]
Oh, I see. Which do you use? I thought that all use mysql :/

**Comment by jywarren** [comment]
Yes that sounds right Camila. Perhaps open a second PR with your latest
code but changing the MySQL version to 5.7 and see if it passes tests?

Thanks!

**Comment by ValentinaTironi** [comment]
Great! Please, let me know everything

**Comment by milaaraujo** [comment]
Yeah, I think that's it: open a second PR with your latest code but changing the MySQL version to 5.7 and see if it passes tests! 

@jywarren, this one is ready to merge.

**Comment by jywarren** [comment]
Fantastic, thanks all!

**Comment by ValentinaTironi** [comment]
Can I push a commit with new mysql version? 
Another question: How I can change the version of database? I see a lot of database files and I'm confused now. Maybe this one docker-compose-testing.yml?

**Comment by jywarren** [comment]
Yes I think that's the one. Did you see my comment above? Try opening a PR
with that one line changed! Thanks, Valentina!

**Comment by milaaraujo** [comment]
I think it's just doing what Jeff explained in one of his last comments (https://github.com/publiclab/plots2/pull/4266#issuecomment-446436297): 
>"...then let's actually open a PR where we change the database back to mysql (but version 5.7) to see if the error crops up there again. That'll require..."

**Comment by ValentinaTironi** [comment]
OK, I'll do that 👍

**Comment by ValentinaTironi** [comment]
I'm gonna close my PR #4263

**Pull request merged**
