### PR TITLE
Fix conditional in Node model

### PR DESCRIPTION
**Pull request by seabl**
No issue opened

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
```ruby
 # These are the same!
 node_type = 'note' if type == 'notes' || 'questions'
 node_type = 'note' if type == 'notes' || type == 'questions'
```

**Comment by Uzay-G** [comment]
Codeclimate suggests we refactor this to:
`node_type = 'note' if ["notes", "questions"].include? type`

Which is the same as:
`node_type = 'note' if w%(notes questions).include? type`

**Comment by seabl** [comment]
@VladimirMikulic Thank you for the review. 
I think these 2 are not the same as `'notes' || 'questions'` will always evaluate to `'notes'` and therefore `type == 'questions'` will never be `true`

**Comment by seabl** [comment]
@Uzay-G Do you think though that Codeclimate's suggestion is a good one in this case? 
Let's see what @jywarren thinks. Thank you.

**Comment by Uzay-G** [comment]
> @Uzay-G Do you think though that Codeclimate's suggestion is a good one in this case?
> Let's see what @jywarren thinks. Thank you.

I mean it's just syntax but codeclimate follows ruby style standards so I think we should follow the suggestion. It is a bit cleaner I find

**Comment by jywarren** [comment]
Is this true? Can we test this in a ruby console? 

I think @seabl is right, actually! I must've written this 😅

**Comment by jywarren** [comment]
Tested:

```ruby
irb(main):001:0> type = 'marshmallows'
=> "marshmallows"
irb(main):002:0> type == 'notes' || 'questions'
=> "questions"
irb(main):003:0> (type == 'notes' || 'questions') != false
=> true
```

**Comment by jywarren** [comment]
Thank you!!!!

**Comment by seabl** [comment]
So... I was not exactly right there... `==` has higher precedence than `||`, which means that the line as it is in our codebase will always evaluate to `true`.

**Comment by jywarren** [comment]
Cool. If you'd like to refactor that's fine too, but this at least addressed the logical error I'd made. Good catch!

**Comment by seabl** [comment]
@jywarren Thanks. 
Actually, I found this purely by chance. _For once_, I gave the test warnings a closer look.

**Pull request merged**
