### PR TITLE
Update _nav_tabs.html.erb

### LINKED ISSUE #9644: Correct HTML for tabs on author tag pages
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

We'll be modifying the HTML and CSS of a template file to fix the tab display. Tabs on [pages like this](https://publiclab.org/tag/effect-based-test/author/bhamster) are supposed to look like this:

image

See the line with tabs starting with "Research notes"? But instead they look like this:

image

We can compare to the correct rendering on this page type: https://publiclab.org/tag/effect-based-test/

Let's make some small but important changes!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/tag/show/_nav_tabs.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/tag/show/_nav_tabs.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -59,24 +59,31 @@
     <% else %>
 
       <% unless params[:id].match("question:") %>
-        <a class="nav-item" <% if @node_type == "note" %> class="active"<% end %> href="/tag/<%= params[:id] %>/author/<%= params[:author] %>"><i class="fa fa-file"></i> <span class="d-lg-inline"><%= raw t('tag.show.research_notes') %></span>
-        </a>
+        <li class="nav-item">
+          <a class="nav-link <% if @node_type == "note" %>active<% end %>" href="/tag/<%= params[:id] %>/author/<%= params[:author] %>">
+            <i class="fa fa-file"></i> 
+            <span class="d-lg-inline"><%= raw t('tag.show.research_notes') %></span>
+          </a>
+        </li>
       <% end %>
 
-      <a class="nav-item" <% if @node_type == "questions" %> class="active"<% end %> href="/questions/tag/<%= params[:id] %>/author/<%= params[:author] %>" >
-        <i class="fa fa-question-circle"></i> <span class="d-lg-inline"><%= t('tag.show.questions') %></span>
-      </a>
-      <a class="nav-item" <% if @node_type == "wiki" %> class="active"<% end %> href="/wiki/tag/<%= params[:id] %>/author/<%= params[:author] %>" >
-        <i class="fa fa-book"></i> <span class="d-lg-inline"><%= raw t('tag.show.wiki_pages') %></span>
-      </a>
-      <!--
-      <a class="nav-item" <% if @node_type == "maps" %> class="active"<% end %> href="/maps/tag/<%= params[:id] %>/author/<%= params[:author] %>" >
-        <i class="fa fa-map-marker"></i> <span class="d-lg-inline"><%= t('tag.show.maps') %></span>
-      </a>
-      -->
-      <a class="nav-item"<% if @node_type == "contributors" %> class="active"<% end %> href="#" rel="tooltip" title="Contributors can't be listed for tag searches with Authors" >
-        <i class="fa fa-user"></i> <span class="d-lg-inline"><%= raw t('tag.show.contributors') %></span>
-      </a>
+      <li class="nav-item">
+        <a class="nav-link<% if @node_type == "questions" %> active<% end %>" href="/questions/tag/<%= params[:id] %>/author/<%= params[:author] %>" >
+          <i class="fa fa-question-circle"></i> <span class="d-lg-inline"><%= t('tag.show.questions') %></span>
+        </a>
+      </li>
+
+      <li class="nav-item">
+        <a class="nav-link<% if @node_type == "wiki" %> active<% end %>" href="/wiki/tag/<%= params[:id] %>/author/<%= params[:author] %>" >
+          <i class="fa fa-book"></i> <span class="d-lg-inline"><%= raw t('tag.show.wiki_pages') %></span>
+        </a>
+      </li>
+
+      <li class="nav-item">
+        <a class="nav-link<% if @node_type == "contributors" %> active<% end %>" href="#" rel="tooltip" title="Contributors can't be listed for tag searches with Authors" >
+          <i class="fa fa-user"></i> <span class="d-lg-inline"><%= raw t('tag.show.contributors') %></span>
+        </a>
+      </li>
     <% end %>
   </ul>
 </div>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by 2201monesh**
@TildaDares I have made the suggested changes kindly review it.

Fixes #9644 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by aliciapaz** [comment]
Hello @2201monesh, kindly add the issue number above. Looks like this other PR https://github.com/publiclab/plots2/pull/9647/commits/9b3ba131d018a63f92fa7e324f11cd5c753bfb91 closes the same issue!

**Review by TildaDares — APPROVED** [review]
LGTM🎉

**Comment by 2201monesh** [comment]
@TildaDares added the issue number as mentioned.

**Comment by TildaDares** [comment]
@2201monesh You added the PR number instead of the issue number.

**Comment by 2201monesh** [comment]
@TildaDares so sorry doing it as suggested

**Comment by 2201monesh** [comment]
@TildaDares I have done the change is that correct?

**Comment by TildaDares** [comment]
@2201monesh Thanks :)

**Comment by 2201monesh** [comment]
@TildaDares can you please let me know if some changes has to be made to make this PR merge.

**Comment by TildaDares** [comment]
@2201monesh Give the maintainers some time :)

**Review by RuthNjeri — APPROVED** [review]
Thanks, @2201monesh, this looks good! And thanks for the reviews @TildaDares and @aliciapaz ❤️

**Pull request merged**
