### PR TITLE
Added mail parsing for other email domains using google mail service

### LINKED ISSUE #3062: Extend mail trimmed content filtering feature for domains which are using google email service
Sub issue of #3054 
Currently we only filter content from google mail when the sender's mail is of `gmail` domain. But there are custom domains which can also use gmail. So we need to extend this feature to domains using google mail service.

### PR DESCRIPTION
**Pull request by namangupta01**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
Closes #3062 
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
@jywarren Code climate issue is good to go?

**Comment by jywarren** [comment]
Cool, is this ready if it passes?

**Comment by namangupta01** [comment]
Yes!!! Its good to go. I have changed the email sender of gmail to jeff@publiclab.org in tests instead of using new emails.

**Comment by jywarren** [comment]
Fantastic!!!

**Pull request merged**
