### PR TITLE
Michelle/icons 1740

### LINKED ISSUE #1740: Confusion in icons of answers and comments in publiclab.org/questions
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step

- [ ]  🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ]  📝 Update the file [https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb) in the plots2 repository (press the little pen Icon) and edit the line as shown below. [See this page](https://github.com/publiclab/plots2/projects/2) for some help in taking your first steps!

- [ ]   💾 Commit your changes

- [ ]  🔀 Start a Pull Request. There are two ways how you can start a pull request:

### PROBLEM : 

There is a confusion between the icons of answers and comments of a question as they are similar - looking .

### SOLUTION :

On hovering the icon , a tooltip should be shown (as in image)
image

## STEPS :  

https://github.com/publiclab/plots2/blob/0e612563e4459b864f8bcb79998467fb859dee10/app/views/dashboard/_node_meta.html.erb#L16

This line should be replaced with : 

`<a href="<%= node.path(:question) %>#answers" title="Answers"><i class="fa fa-comments-o" style="color: #DAA583;"></i> <%= node.answers.length %></a>`

Similarly for other icons can be done .

### PublicLab link : 

https://publiclab.org/questions

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by mbrien12**
Updated one line in views/dashboard to add tooltips onto icons.

Fixes #1740

### CODE REVIEW

**Comment by jywarren** [comment]
Hey, looks good! But did your changes make it in? I see a change to the "title" but no icon changes... maybe they got lost while tweaking your branches?

**Comment by jywarren** [comment]
Or is that all that's needed to add a tooltip? I think maybe you can also add `rel="tooltip"` to make Bootstrap tooltips appear, no? 

https://getbootstrap.com/docs/3.3/javascript/#tooltips

**Comment by mbrien12** [comment]
I followed instructions in issue description which it said to just replace one line in a view/dashboard file so that's the only change I've made here. Let me know if there's more I should do?

**Comment by jywarren** [comment]
Ah, ok! That looks great then -- sorry, i just got back from traveling so I've been a bit slow here. I'm merging this now, thanks so much!

**Comment by jywarren** [comment]
Oops, it had a small conflict in Gemfile.lock, which I've resolved (pretty simple) and will just check to see that the tests pass now.

**Comment by jywarren** [comment]
Perfect; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks for your help! We really appreciate it!

**Comment by jywarren** [comment]
This is live on the site now: https://publiclab.org/questions/

Thank you! 🎉

**Pull request merged**
