### PR TITLE
Created LABELS.md

### LINKED ISSUE #2341: Update contribution guidelines
### Please describe the problem (or idea)
At public labs we are now using a new pr label and issue label system as discussed in #2231. One problem with the new label system is the newcomers are not having knowledge of our existing label system
> What happened just before the problem occurred? Or what problem could this idea solve?
I think one solution is to include the link to the contributors page (https://github.com/publiclab/plots2/blob/master/CONTRIBUTING.md) in all the first timers issue so that they will read and do the prs accordingly.
For that we need to change the contributors page 
This is a part of #2231 
@jywarren @ebarry what do you suggest??

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
This summarizes the various labels and tags used by the organization for faster reviews and keeping the repo organized.

Fixes #2341 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@SidharthBansal @jywarren @Souravirus This is the documentation regarding labels used in the organization... Pls review... and approve my task at the gci platform... 😃

**Comment by jywarren** [comment]
Oh this is nice!!! Actually i think you can use a single ` for making `sections like this` inline. Could you make that modification? instead of ```

**Comment by oorjitchowdhary** [comment]
> Oh this is nice!!! Actually i think you can use a single `for making`sections like this` inline. Could you make that modification? instead of ```

Okay done...

**Comment by oorjitchowdhary** [comment]
Pls merge and also approve my task at the GCI platform .. Thanks

**Comment by oorjitchowdhary** [comment]
@avsingh999 @Souravirus

**Comment by Souravirus** [comment]
Yeah really nice work @oorjitchowdhary, I will be approving this task if anyone hasn't approved this in GCI candidate. Thank you!!

**Pull request merged**
