### PR TITLE
[wip] #1951 Add "Join" button to people lists 

### PR DESCRIPTION
**Pull request by JahlHernandez**
Adds button to join people lists, as requested in #1951

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by JahlHernandez** [comment]
I'm working on issue #1951, but I've run into a problem while trying to access current_user from the partial located at views/grid/_people.html.erb, whenever I try an reference that variable it returns 
`undefined local variable or method `current_user'` (you can see the line in 008652b)
How can I access that variable from the partial?

Thanks a lot for any help you can provide

**Comment by JahlHernandez** [comment]
Hey there @jywarren, I tried that, but it throws the same error on the ```if```

**Comment by jywarren** [comment]
Can you commit that addition and let's see how it does on this PR? Thanks!

**Comment by JahlHernandez** [comment]
Done!
If it's worth something, if I use the defined? operator on the if, it always returns false, but doesn't throw any errors.

**Comment by jywarren** [comment]
Wow, i had to solve a similar issue today - yes, let's use `defined?` -- great idea!

**Comment by JahlHernandez** [comment]
Hey there, I still don't quite get when  would the `defined?` check return true, I'm logged in and it always returns false for current_user on that specific partial.

**Comment by jywarren** [comment]
Hmm, i think i see what's happening. That partial is actually rendered unusually to a string insider of `/app/models/concerns/node_shared.rb`, where `current_user` is not defined. And, although it's not ideal here, the model shouldn't really "know" about stuff in the user session. 

Here's some possible solutions: https://stackoverflow.com/questions/2513383/access-current-user-in-model

What do you think?

**Comment by jywarren** [comment]
I have a simpler idea. What if we just moved it to this line in the helper, where we /do/ have access to `current_user` -- 

https://github.com/publiclab/plots2/blob/ed1ef3b72c8a45bfd1d7b842d1d747db391b2a7f/app/helpers/application_helper.rb#L37

It's not quite as clean, but it'll just work and it'll be only one line. What do you think?

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by JahlHernandez** [comment]
Hey! sorry for the late reply.
I've done a couple more things:
89b0c2a I'm not sure if I understood what you meant by your previous comment, was I supposed to pass the `current_user` as a parameter like this?
4230f28 I added a button for when the user is not logged in, with a link to go to the login

**Comment by jywarren** [comment]
Ah, a great solution! Perfect. There are some merge conflicts since others have submitted changes in the interim -- if you'd like to try rebasing your work over the latest master branch, give it a try! Otherwise I'm happy to help. 

In case it's helpful, here's some guidance on rebasing! https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by jywarren** [comment]
OK, that was a real tough rebase! I resolved the issues and made a couple small tweaks to the capitalization. It looks good now and I'll merge if the tests pass! 

Thanks for working on this -- it's great to see this feature finally get built!

**Comment by jywarren** [comment]
Hmm, that caused some chaos in our tests, but I made some adjustments. Sorry this one ended up being more complex than we thought!

**Comment by jywarren** [comment]
Hmm. I'm getting stuck here! @publiclab/reviewers -- is anyone able to help us out? Much appreciated!!

**Comment by JahlHernandez** [comment]
I see, if there's anything else I can do to help, let me know!

**Comment by ryzokuken** [comment]
@jywarren 

> I’ve seen this over and over again. Helpers relying on instance variables. Now, I’m not saying that it doesn’t work cause it does. If the view has the instance variable defined, the helper being mixed into the view context can use it. But it’s bad practice so don’t do it.

> Just treat helper methods like you do any other methods and pass them arguments. Don’t rely on instance variables because you won’t be able to reuse those helpers and it will make the helper very hard to read, test and maintain. The fact that Rails mixes everything in one giant view context is not something particularly helpful in this case so try to keep instance variables away from helper methods.

**Comment by ryzokuken** [comment]
@jywarren better?

**Comment by ryzokuken** [comment]
@jywarren could you please take a look at this?

**Comment by jywarren** [comment]
Ooh, i agree! We've been gradually trying to move to more passed-in local arguments in partial templates as well. Any ideas on how to encourage this more?

Looking over this now.

**Comment by jywarren** [comment]
Awesome, thank you!!!

**Comment by ryzokuken** [comment]
@jywarren Perhaps we could add a rule in rubocop to enforce this behavior?

**Comment by jywarren** [comment]
Cool idea -- maybe we say "encourage" not "enforce" despite rubocop being a cop! Maybe we should fork and rename "ruboencourager" :-P

This is live now! Thanks all!

https://publiclab.org/wiki/education#Education+group

**Pull request merged**
