### PR TITLE
fixes #1198 - Tested email notifications to author on question answers

### LINKED ISSUE #1198: Test email notifications to author on question answers
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## Prerequisites

You don't really need to know anything in advance in order to tackle this issue. However, a little understanding about Ruby and how TDD (specifically functional tests) work.

Get started with Ruby:
1. https://www.codecademy.com/learn/ruby
2. http://rubylearning.com/
3. https://www.codeschool.com/learn/ruby
4. http://tryruby.org/levels/1/challenges/0
5. https://www.ruby-lang.org/en/documentation/quickstart/
6. https://learnrubythehardway.org/

## The problem

Currently, the mailer component does not test if the user who created a question is notified of proposed answers. In order to fix that, one needs to add a few more assertions.

## Solution

https://github.com/publiclab/plots2/blob/master/test/functional/answers_controller_test.rb#L12-L16 lines post the answer. It is during this phase that the user needs to be notified. In order to check if the above lines trigger such a behaviour, wrap them in the following assertion: 

```
assert_difference 'ActionMailer::Base.deliveries.size', 1 do
    # create the answer here
end
```

This would ensure that some notification is sent. But is it sent to the author?

We'd want to do:

`assert_equal node(:question).author.email, ActionMailer::Base.deliveries.last.to`

Just after the other check. 

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

### PR DESCRIPTION
**Pull request by djmgit**
Added test to make sure that user who created a question is notified of
proposed answers.

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by djmgit** [comment]
After adding the required test I am getting this following test failure in answers_controller_test.rb:

Failure:
  <"jeff@pxlshp.com"> expected but was
  <["admin@publiclab.org"]>.
test_should_get_create_if_user_is_logged_in(AnswersControllerTest)
test/functional/answers_controller_test.rb:18:in `block (2 levels) in <class:AnswersControllerTest>'
test/functional/answers_controller_test.rb:12:in `block in <class:AnswersControllerTest>'


how do I remove this failure?

**Comment by jywarren** [comment]
Hi! This is looking like a good start -- but why do you expect `ActionMailer::Base.deliveries.last` to be the question author's notification? I think there are a number of other notifications sent, so I think testing the final one may not reliably get you the question author. If you move that assertion outside the `assert_difference 'ActionMailer::Base.deliveries.size', 1 do` loop, you'll be able to check how many email notifications were actually sent.

You may need to collect all the new ones, and then scan through them to find the one to the author. 

But if you find that there's only one sent, or that even with multiple ones sent, that's actually the point of this issue -- to clearly reproduce the problem in #1198, as the first step towards a solution. So if you can make the changes I describe, we can take that next step - I'll guide you to find where notifications are made.

**Comment by jywarren** [comment]
And thanks!!!

**Comment by djmgit** [comment]
@jywarren  so outside the do loop i should run a loop over all the mail deliveries and I should check if any of that mail is sent to the author or not ?
I mean something like this:
```
assert_difference 'ActionMailer::Base.deliveries.size', 1 do
      assert_difference 'Answer.count' do
        xhr :post, :create,
                   nid: node.nid,
                   body: "Sample answer"
      end
end
ActionMailer::Base.deliveries.each do |mail|
  assert_equal node(:question).author.email, mail
```
There might be some problem in the syntax as I am learning rails

**Comment by jywarren** [comment]
I think the problem is that `assert_equal` failing will fail the whole test, and so you may need to collect a subset of them, like:

```ruby
count = ActionMailer::Base.deliveries.length

assert_difference 'ActionMailer::Base.deliveries.size', 1 do # (later, this test will probably fail, if more than 1 are sent)
      assert_difference 'Answer.count' do
        xhr :post, :create,
                   nid: node.nid,
                   body: "Sample answer"
      end
end

assert ActionMailer::Base.deliveries.collect(&:to).includes?('author@email.com')
```

See how I use `collect` to fetch the `to` field of each email, which actually results in an array of the "to" fields? 

Then i use `includes?()` to see if one of that array is the email we're looking for?

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by jywarren** [comment]
This was fixed in https://github.com/publiclab/plots2/issues/1321. Thanks!

**Pull request closed without merging**
