### PR TITLE
UI fix - tabs on questions page

### LINKED ISSUE #5850: Recently Commented Tab on questions page does not align
Screen Shot 2019-06-06 at 12 56 49 AM

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #5850 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@publiclab/reviewers @publiclab/plots2-reviewers 
Screen Shot 2019-06-06 at 1 16 34 AM

**Comment by jywarren** [comment]
@gautami_gg @cleverfool77 how does this look? Thanks!!!

**Comment by jywarren** [comment]
@gautamig54 oops sorry! How does this look?

**Comment by jywarren** [comment]
Awesome!!!

**Pull request merged**
