### PR TITLE
Refresh button

### PR DESCRIPTION
**Pull request by vaibhavmathur13**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by vaibhavmathur13** [comment]
Screenshot from 2019-10-13 17-10-11

Screenshot of tooltip to refresh button

**Comment by vaibhavmathur13** [comment]
I don't understand how to solve merge conflict.

**Comment by vaibhavmathur13** [comment]
@gauravano @IshaGupta18

**Comment by IshaGupta18** [comment]
Hey, this looks good. Can you please remove the change in the yarn lock file?

**Comment by vaibhavmatta** [comment]
@vaibhavmathur13 Everything looks good here. Just remove the change in the yarn lock file as suggested by @IshaGupta18. Rest all seems right as per the requirement. Thanks

**Pull request closed without merging**
