### PR TITLE
Renaming _form partial (https://github.com/publiclab/plots2/issues/4269)

### LINKED ISSUE #4269: Extract out edit controller data from the form partial
Due to the signup and login modal integrations, I need to divide the users/_form.html.erb into two parts form2 and form partials. After #4209 is merged. We need to
- [x] Extract out edit controller data from the form partial 
- [ ] Change _form partial to some other name
- [ ] Similarly change name for _form2 partial.

### PR DESCRIPTION
**Pull request by kunalvaswani123**
Fixes #4269  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kunalvaswani123** [comment]
@SidharthBansal could you review this pull request?
I am not sure about the other three check boxes

**Comment by kunalvaswani123** [comment]
I did a git grep "render 'form'" and git grep ""users/form"" to check the files from which the form partial was called.

**Comment by SidharthBansal** [comment]
Great !!!
Please provide the following screenshots.
1.Login modal
2.Signip modal
3./login page
4./signup page
5./profile/edit page
From local host. I need to ensure that these all are in working condition.

**Comment by kunalvaswani123** [comment]
screenshot from 2018-12-21 23-10-19
screenshot from 2018-12-21 23-10-08
screenshot from 2018-12-21 23-10-13

**Comment by kunalvaswani123** [comment]
screenshot from 2018-12-21 23-11-29
screenshot from 2018-12-21 23-11-46
screenshot from 2018-12-21 23-11-52
screenshot from 2018-12-21 23-12-54
screenshot from 2018-12-21 23-12-59

**Comment by kunalvaswani123** [comment]
@SidharthBansal I have uploaded the screenshots

**Comment by SidharthBansal** [comment]
Well done.
Can you please update your master with plots2 master and do the remaining renaming stuff.
Thanks

**Comment by kunalvaswani123** [comment]
ok now could I solve the third part too?

**Comment by SidharthBansal** [comment]
Yeah sure.
Please sync the master branch first of plots2 with your master branch. Then
raise a PR. At all places you need to change.
Thanks

**Comment by kunalvaswani123** [comment]
ok

**Pull request merged**
