### PR TITLE
Added _nav_tabs to Tags#comment Fixes (new PR) #10570

### PR DESCRIPTION
**Pull request by billymoroney1**
Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by billymoroney1** [comment]
@jywarren this is the new PR, just wanted to give you a headsup and make sure it looks good before i delete the old one

i followed the publiclabs github workflow doc and started from scratch, hopefully that will prevent the merge issues the other ticket had?

**Comment by TildaDares** [comment]
@billymoroney1 What branch did you create this branch from? Was it `main` or some other branch?

**Comment by billymoroney1** [comment]
@TildaDares oh lord - i did master because that was mentioned in the workflow doc, but now i'm remembering that github changed "master" to "main"?

**Comment by TildaDares** [comment]
@billymoroney1 That's fine, I've made the same mistake too. This article should help https://luisdalmolin.dev/blog/branched-off-the-wrong-branch-in-git/

**Comment by TildaDares** [comment]
Let me know if you need any more help.

**Pull request closed without merging**
