### PR TITLE
UI for new option for moderators to not receive moderation emails

### LINKED ISSUE #6282: For moderator accounts, add ability to turn off email at /settings
**Please describe the desired behavior.**

This feature request is part of improving the moderators workflow, and was written with @jywarren and @bronwen9. 

This feature request is to add the ability to turn of moderator emails per user at /settings. 

This feature should only be shown to /moderators and /admins. 

**Additional context (optional)**
Screen Shot 2019-09-12 at 4 58 58 PM

Thanks!

### PR DESCRIPTION
**Pull request by anthony-zhou**
Fixes #6282  (Not sure if there is an issue corresponding to just the UI for this feature, so I've listed the issue requesting the feature in general)

### Changes

In this PR, I assumed that PR #7183 was already functional. Therefore, I did three things:
1. In `settings.html.erb`, I created a switch that displays the existence of the `no-moderation-emails` tag in an option on the settings pages for moderators and admins. By default, it is on, indicating that `no-moderation-emails` is true... I guess this is backwards but I'd like to know what we want to be the default setting first.
2. To only show this option to moderators and admins, I wrapped this option in an `<%if logged_in_as(['admin', 'moderator']) %>` statement.
3. To update the settings according to the new UI, I modified the `user_controller.rb` file to include the `no-moderators-email` tag.

### Screenshots

Here's how it looks on a moderator's `/settings` page:
Screenshot_2020-01-10 🎈 Public Lab Settings

Here's how it looks on a regular user's `/settings` page:
Screenshot_2020-01-10 🎈 Public Lab Settings(1)

### Actions needed

What I'd like to know now is:
1. What do we want as the default setting for this option?
2. Is this the appropriate way to implement this UI or can it be improved?

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by anthony-zhou** [comment]
@publiclab/reviewers Please see above for the questions I have regarding this new feature.

**Comment by cesswairimu** [comment]
Hi @anthony-zhou could you please link the issue number. Restarting the build on the other PR tpo see if it passes. Thanks...

**Comment by jywarren** [comment]
This is looking really fantastic. Yes, so by default emails should be ON. Thank you!

**Comment by anthony-zhou** [comment]
@cesswairimu @jywarren After tracing through the logic, I believe the two file changes I made result in emails being on by default and changing to off by adding the "no-moderation-emails" tag when the field is unchecked. Please review this PR when you get the chance. Thanks!

**Comment by jywarren** [comment]
This looks super! Thank you so much!!! pinging @publiclab/community-reps because this seems to now be complete and once we publish the live site, we should double check this!

**Pull request merged**
