### PR TITLE
Fixes #6304: Added eye icon for contributors that are following too

### LINKED ISSUE #6304: Reorganize /contributors/___ pages
(follow-up to https://github.com/publiclab/plots2/pull/5632) cc @IshaGupta18 🙌 

We now show 2 types of users on our contributor pages like https://publiclab.org/contributors/water-quality

1. contributors - who have posted using this topic or commented on this topic
2. followers - who are following this topic and will get notified when new content is posted to it

They're a bit messily next to each other:

image

Let's:

* [ ] show contributors in a table on top, but in each row, mark if that person is ALSO following -- maybe, with an eye icon? In a column called `Following`, maybe?)
* [ ] then let's show people who are NOT in the first list, but ARE subscribed. This can be in a second table with the title `Following`. 

Should we have a short text explanation of the distinction?

### PR DESCRIPTION
**Pull request by KarishmaVanwari**
An eye icon now appears right beside the name of the contributor if it is following too.

Fixes #6304 

Screenshot:
image

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
This looks really good @KarishmaVanwari but I don't know if users would be able to understand what the eye icon means. Can we add a tooltip or something that explains what the icon is used for? What do you think?

**Comment by KarishmaVanwari** [comment]
@TildaDares That's a great idea! I can do that. Thanks!

**Comment by KarishmaVanwari** [comment]
@TildaDares I've added the tooltip saying "Following". How does it look?
image

**Comment by KarishmaVanwari** [comment]
@TildaDares I have a suggestion. The "Notes" link beside every contributor looks repetitive (especially when there are a large number of contributors), how about replacing it with a notes icon, using something like this `<i class="fa-solid fa-note-sticky"></i>` ? Does it sound like a potential change?

**Comment by TildaDares** [comment]
@KarishmaVanwari I think you're right about the repetition but I believe the `Notes` text was added to serve as a link to all of the user's notes for that particular tag. Using an icon probably has the same effect as the `Notes` text since we'll have to repeat it for each contributor row. Also, an icon won't properly communicate to the user that this links to the user's content. 

Do you see any other way we could improve this?

Also, another possible improvement would be to add a `See More` link at the bottom of the `People who've contributed` and `Following` sections when the number of contributors exceeds a particular limit. What do you think about this?

**Review by TildaDares — APPROVED** [review]
Great work @KarishmaVanwari. Thank you!!

**Comment by KarishmaVanwari** [comment]
> @KarishmaVanwari I think you're right about the repetition but I believe the `Notes` text was added to serve as a link to all of the user's notes for that particular tag. Using an icon probably has the same effect as the `Notes` text since we'll have to repeat it for each contributor row. Also, an icon won't properly communicate to the user that this links to the user's content.
> 
> Do you see any other way we could improve this?
> 
> Also, another possible improvement would be to add a `See More` link at the bottom of the `People who've contributed` and `Following` sections when the number of contributors exceeds a particular limit. What do you think about this?

Yes @TildaDares, I get your point of repetitive nature of icon too, maybe we can work out something else. I'll think over this. Thanks for considering my suggestion :)

Also, the idea of a `See More` link at botton seems a nice idea to be implemented. I'd love to implement it!

**Comment by KarishmaVanwari** [comment]
@TildaDares Another thought that striked me is that on this page, contributors and followers column seem a little non-uniform:
image


Maybe we can either:
1. Add `Contributors` title and remove both `People who've contributed` and `People who are following` subtitles since the words `Contributors` and `Followers` are self explanatory (or, if needed we can add a toolip or hover text to explain better) or,
2. We can simply remove `Followers` title.


Implementing either of the above two will bring uniformity to both columns. What do you think?

**Comment by TildaDares** [comment]
> 1. Add `Contributors` title and remove both `People who've contributed` and `People who are following` subtitles since the words `Contributors` and `Followers` are self explanatory

I like this! But we already have a `Contributors` heading so it'd be repetitive.

**Comment by TildaDares** [comment]
I think this is a better option!
> 2\. We can simply remove `Followers` title.

**Comment by jywarren** [comment]
Thank you!!!

**Pull request merged**
