### PR TITLE
Removed list and grid view for smaller screens

### LINKED ISSUE #3733: Remove the list and grid view button in the mobile view
### Please describe the problem (or idea)
The list and grid view button in the mobile view needs to be removed as it is not working and is just an additional problem whichs needs to be eliminated in the page where tags are being added .
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
capt

### Please show us where to look
https://publiclab.org/tag/code

### What's your PublicLab.org username?
201651044
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #3733 
@publiclab/reviewers Please check this out.. Thanks

`Desktop view`

screenshot 68

`Mobile view`

screenshot 69

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@oorjitchowdhary this same error is across many other web pages. Can you find them and create issues for them?
We can then have your work. Also, we will be able to create GCI tasks for that.

**Comment by oorjitchowdhary** [comment]
Okay sure.. I'll look for them..

**Comment by oorjitchowdhary** [comment]
Also, I'll claim the tasks once my #4144 is approved on gci.. Please take a look if you can

**Comment by SidharthBansal** [comment]
Please tag me in the issue itself. Writing issue number causes the issues to be linked. We don't want non related issues to be linked together

**Comment by SidharthBansal** [comment]
@jywarren merging this one. Hope you will like it.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal The buttons are used on `/tags`, `/questions` and `/notes`..
But they don't have any error now as I have fixed the error in the partial template..
Here are the views for them..

Desktop view for /questions

screenshot 71

Mobile view for /questions

screenshot 72

Desktop view for /notes

screenshot 73

Mobile view for /notes

screenshot 74

So we don't need to create any issues..

**Comment by SidharthBansal** [comment]
It's great that we don't have these types of errors anymore.
Thanks for your help

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Please create a task for this on gci.. Thanks a lot

**Comment by SidharthBansal** [comment]
I hope #3733 is present on the GCI. Please claim it. If it is not present. Inform me.

**Comment by oorjitchowdhary** [comment]
It isn't present .. Just searched.. Sorry to bother you so much..

**Comment by SidharthBansal** [comment]
Btw how do you search? I have never used the gci student's dashboard. It can be really tough to search at many times. Right?

**Pull request merged**
