### PR TITLE
Uid visible to admin and account holder

### LINKED ISSUE #3038: User Tag must be visible to admins or themselves
### Please describe the problem (or idea)
Currently the user tags are visible to all people. We need that the user_tags of OAuth providers be visible to only account holders or admins

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #3038 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@jywarren this is in progress

**Comment by SidharthBansal** [comment]
I am having 242 errors on recent git pull

**Comment by SidharthBansal** [comment]
I have tested this on my localhost:3000.
Where do we display the user_tags apart from the profile page?

**Comment by jywarren** [comment]
Nowhere else -- does this need the tests restarted or is there an error we can fix?

**Comment by SidharthBansal** [comment]
i am not having any error on my local machine. I have restarted the tests. Hope it passes

**Comment by SidharthBansal** [comment]
ERROR["test_digest_emails", Minitest::Result, 35.865290699999605]
 test_digest_emails#Minitest::Result (35.87s)
Redis::CannotConnectError:         Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
            app/controllers/users_controller.rb:308:in `test_digest_email'
            test/functional/users_controller_test.rb:252:in `block in <class:UsersControllerTest>'

  784/784: [===============================================================================================] 100% Time: 00:01:35, Time: 00:01:35

Finished in 95.34637s
784 tests, 2369 assertions, 0 failures, 1 errors, 0 skips

I am getting this error. is this error  related to my patch?

**Comment by Gauravano** [comment]
The error is about Junit. Restarting build!

**Comment by Gauravano** [comment]
ok, actual error revealed now.

**Comment by Gauravano** [comment]
Here it is @SidharthBansal 

error

**Comment by SidharthBansal** [comment]
Finally all tests passed.
@jywarren can you please suggest changes to this?

**Comment by jywarren** [comment]
Looks good but did I see that one of the tags starts with `oa-` instead of `oauth`? Let's be sure this is standard -- where should we look?

Also, if you want to replace the `select` assertion with an assertion that they do NOT exist, maybe that's a good idea... is there test fixture data including `oauth` related tags for that page so it's a good test of this? 

Thanks!!!

**Comment by SidharthBansal** [comment]
What are oa- tags used for?
My patch addresses that the user tags starting with oauth will be only visible to admin or user themselves ELSE if it is not starting with oauth we do what we were doing earlier. So there will be no conflict

**Comment by SidharthBansal** [comment]
Can we merge this one? I will write tests in next PR. I just want to hide the oauth based usertag as quickly as we can on production

**Comment by jywarren** [comment]
Sure! And I don't know what oa tags are for but there's one on my profile
that I didn't make... Want to look?

**Comment by jywarren** [comment]
👍

**Comment by SidharthBansal** [comment]
Looking at them

**Comment by SidharthBansal** [comment]
Initially in April when we were adjusting the usertag to behave as identity model we created some usertags on our profile to test the feature. They are now not needed. You can delete the following from your profile
* [ ] github:jywarren
* [ ] oa-twitter:jywarren
 I have deleted mine. No one else apart from you and me have created such tags.

**Comment by jywarren** [comment]
awesome!

**Pull request merged**
