### PR TITLE
Dont follow tags

### PR DESCRIPTION
**Pull request by StlMaris123**
related to #1421 

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
Hi @StlMaris123 Is there any issue regarding this? You could mention that in the PR description. As of now the title of the PR is unclear.

**Comment by jywarren** [comment]
Just changed this so it doesn't close the planning issue, but does get connected to it.

**Comment by jywarren** [comment]
But please mark this as WIP as the method is currently empty! Great work getting these started, StellaMaris!

**Comment by StlMaris123** [comment]
I have combined this PR in email when tag is added since they are related.

**Pull request closed without merging**
