### PR TITLE
Update drupal_node.rb

### PR DESCRIPTION
**Pull request by aayushgupta1**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

Removed the drupal as it was asked. If an error is recieved it would be because of /test and /app. Working on changing those too. Thanks for the support.

### CODE REVIEW

**Comment by jywarren** [comment]
Ah, actually I think we can't do Users just yet until we ensure all calls to DrupalUsers have User equivalents... That ones a little more complex. Beware @ashleypt if you're trying that one!

**Comment by aayushgupta1** [comment]
In this file I have ensured to have User equivalent for DrupalUser equivalents. I'm trying to do the same in other files, but it'll take some time.

**Comment by jywarren** [comment]
Ok, but given the complexity here, I /strongly/ recommend making only one
change at a time -- I.e. DrupalNode changes separate from DrupalUsers.

**Comment by aayushgupta1** [comment]
OKay @jywarren , for now i'll work at DrupalNodes. The rest I'll workout after that.

**Comment by jywarren** [comment]
OK -- thanks!!!

**Pull request closed without merging**
