### PR TITLE
Adjusted pagination (30 to 32) and removed map description from maps - fixes #982

### LINKED ISSUE #982: Adjust pagination and remove map description from /maps page
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!
## The Problem
The `/maps` page shows a set of 4 maps on each row. Per page 30 maps are shown presently. So the last row contains just 2 maps. We can adjust two more there. Also it is better to remove the map description from the page as it is overlapping over another at some places.

## Solution
By default 30 notes are displayed per page which is the default setting of the `will_paginate` gem. We just need to set the `:per_page` count to 32 to make the last row filled. You have to do it in the index action of map_controller. refer to this line https://github.com/publiclab/plots2/blob/master/app/controllers/map_controller.rb#L5. You can take help from the will_paginate [documentation](https://github.com/mislav/will_paginate#basic-will_paginate-use). 

Also remove the map description. Here is the line that has the map description https://github.com/publiclab/plots2/blob/master/app/views/map/_maps.html.erb#L17 

## Steps to Fix
- [x] claim this issue with a comment
- [x] set up a repository locally and make sure that all tests pass
- [x] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [x] fix the issue following the steps above
- [x] try the manual test listed above
- [x] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

### PR DESCRIPTION
**Pull request by abhishekzambre**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@abhishekzambre OK the tests pass successfully. Thanks for the PR. Please have some patience as everyone is busy with the Annual Barnraising at the moment. So we'll catch up soon. @jywarren Please review and merge this after you are back.

**Comment by jywarren** [comment]
Hi, this looks good, but what issue was it in response to? Can you link to it in the title or body, with "fixes #...."? Thank you!

**Comment by jywarren** [comment]
Ah, #982? Super -- checking that now too!

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. Thank you so much -- i changed the title, too, which will auto-close the related issue.

If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Pull request merged**
