### PR TITLE
Use include? to simplify helper method 'logged_in_as'

### PR DESCRIPTION
**Pull request by seabl**
No issue opened

### CODE REVIEW

**Comment by seabl** [comment]
Yay! All checks have passed.

**Comment by seabl** [comment]
@publiclab/reviewers please review. Thanks!

**Comment by jywarren** [comment]
Hi! Awesome! Can you link us back to the issue you started at? Thanks so much!

**Comment by seabl** [comment]
Hi @jywarren ! No issue was opened for this. Just an attempt to "delete a few lines of code".

**Comment by jywarren** [comment]
Awesome!

**Comment by jywarren** [comment]
Thank you so much!

**Comment by seabl** [comment]
@jywarren You're welcome.

**Comment by jywarren** [comment]
:-)

Would you be at all interested in taking on a new issue? We have a
relatively simple one here that gets a little into tests as well. I'd be
happy to help you with it: https://github.com/publiclab/plots2/issues/6190

**Comment by seabl** [comment]
What kind of tests are does this require? If no system tests are not involved, then OK.

**Comment by jywarren** [comment]
:-) i think probably following the suggestions and changing the
notifications will break some unit or functional tests. Then we'll just
have to update them to accommodate the new notifications we intend to be
sending.

**Comment by seabl** [comment]
OK, sounds within reach. I'll start working on it.

**Comment by jywarren** [comment]
Thanks so much!!!

**Comment by seabl** [comment]
You're welcome!
I've pushed a few lines. I'll now take a shot at the tests.

**Pull request merged**
