### PR TITLE
Align the enter tags input section in subscriptions #5191

### PR DESCRIPTION
**Pull request by techchic**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by techchic** [comment]
@jywarren I have added the config/database.yml.sqlite.example file. The Gemfile.lock is ignored in the git ignore file. Lemme know if this is fine

**Comment by gauravano** [comment]
Please mention the issue number at https://github.com/publiclab/plots2/pull/5221#issue-263261328 as mentioned in the checklist. Thanks!

**Comment by SidharthBansal** [comment]
@techchic please make the above suggested changes.

**Comment by SidharthBansal** [comment]
Thanks for your work

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month @jywarren @gauravano , I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing at Public Lab

**Pull request closed without merging**
