### PR TITLE
Upgraded Editform as per Bootstrap4

### LINKED ISSUE #5741: Upgrade editform as per bootstrap4
#### Currently 
editform

#### Description
Due to usage of bootstrap3 classes and features, The UI has distorted as now we are using bootstrap4.
Fix the UI as per bootstrap4.

### PR DESCRIPTION
**Pull request by dinaelhanan**
Fixes #5741  
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Souravirus** [comment]
Hi @dinaelhanan, can you send a screenshot of the changes you have done. That will be a lot helpful. Thank you!!

**Comment by CleverFool77** [comment]
Hi @dinaelhanan Are you still working on this ?

**Comment by dinaelhanan** [comment]
@CleverFool77 Hi, I'm having issues with my local dev environment - could you please try to run this branch on your end? I'd really appreciate it!

**Comment by CleverFool77** [comment]
Oh no problem. I'll check this.

**Comment by dinaelhanan** [comment]
hey @CleverFool77 , I'm not sure I get what you mean, can you point out the lines of code you're referring to? Thank you so much for your help :)

**Comment by CleverFool77** [comment]
If this is not understandable then I guess @jywarren @gautamig54 might help you in understanding better.

**Comment by gautamig54** [comment]
Hi @dinaelhanan. @CleverFool77 explained the solution pretty well. Reach out to us if you need more guidance. Great work!

**Comment by dinaelhanan** [comment]
@CleverFool77 Hi, I'm sorry I've left this unattended for some time, I started my internship and it was intense in the beginning, just starting to get back into the contributing habit! I've made the requested changes. Thank you for explaining this and let me know if there's any more issues.

**Comment by CleverFool77** [comment]
> @CleverFool77 Hi, I'm sorry I've left this unattended for some time, I started my internship and it was intense in the beginning, just starting to get back into the contributing habit! I've made the requested changes. Thank you for explaining this and let me know if there's any more issues.

No problem, Now having a ss would do.

**Comment by CleverFool77** [comment]
@dinaelhanan Are you still working on this ? Just having an update with screenshot would do ?

**Comment by CleverFool77** [comment]
@dinaelhanan Any updates ? OR I might close this issue ?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
