### PR TITLE
ADD: system tests for wiki edits

### PR DESCRIPTION
**Pull request by Uzay-G**
For part of #5316

I added a test that verifies that users can edit wikis and preview their contents. What do you think @VladimirMikulic?

### CODE REVIEW

**Comment by Uzay-G** [comment]
> On my server, the test fails. Let's wait for Travis though.

This is weird. It is working for me...

**Comment by Uzay-G** [comment]
There were differences between my fork and this repo. I need to find a way to select the edit button for the wiki. I will work on this tomorrow!

**Comment by VladimirMikulic** [comment]
@Uzay-G this will make your test work:
```ruby
    find('a.btn-circle:first-of-type .fa-pencil').click()
```

**Comment by Uzay-G** [comment]
> @Uzay-G this will make your test work:
> 
> ```ruby
> find('.like-buttons a.btn-circle:first-of-type .fa-pencil').click()
> ```
> 
> 100% precision :)

Thanks! I will try it out :+1:

**Comment by SidharthBansal** [comment]
4th test here

**Pull request merged**
