### PR TITLE
attempting to fix #992

### LINKED ISSUE #992: Solr test failures
On running tests, I see the following, though that doesn't cause a Travis failure:

```

===============================================================================
Failure:
  <"Notes or Wiki updates"> expected but was
  <nil>.
test_should_create_new_search(SearchesControllerTest)
test/solr/searches_controller_test.rb:48:in `block in <class:SearchesControllerTest>'
===============================================================================
.....F
===============================================================================
Failure:
  <"User Profiles"> expected but was
  <"Notes or Wiki updates">.
test_should_update_advanced_search(SearchesControllerTest)
test/solr/searches_controller_test.rb:65:in `block in <class:SearchesControllerTest>'
===============================================================================
```

See [full build here](https://github.com/publiclab/plots2/commit/50a33054d80c2f50d1377a0a8b53b005bf454aa7#diff-66694174e90422724c8c508d12a0f225L89).

The first error is on this line: https://github.com/publiclab/plots2/blob/master/test/solr/searches_controller_test.rb#L48

By looking at the corresponding controller code, I don't see a change to `assigns(:search).main_type`, but that refers to `@search` which is a method of SearchRecord: https://github.com/publiclab/plots2/blob/master/app/models/search_record.rb

But it's just a db column of that model, so then I did `grep -r main_type app` and saw that it's supposed to be set in the form template: https://github.com/publiclab/plots2/blob/master/app/views/searches/_form.html.erb#L8-L9

Something similar is happening in the second error, here: https://github.com/publiclab/plots2/blob/master/test/solr/searches_controller_test.rb#L65

It's not clear to me why this isn't working, or when it happened, but by looking at the "blame" view we can see what recent changes there are and who did them:

https://github.com/publiclab/plots2/blame/master/app/controllers/searches_controller.rb

I touched the form template about 14 days ago... https://github.com/publiclab/plots2/commit/50a33054d80c2f50d1377a0a8b53b005bf454aa7

Hmm. 

****

Looking further, those should be set on these lines: https://github.com/publiclab/plots2/blob/master/test/solr/searches_controller_test.rb#L42 in the tests. I'm going to hunt through [the old builds](https://travis-ci.org/publiclab/plots2/builds/) to find when this started. 

****

OK -- this commit did it: https://github.com/publiclab/plots2/commit/50a33054d80c2f50d1377a0a8b53b005bf454aa7

Probably the changes here, no? https://github.com/publiclab/plots2/commit/50a33054d80c2f50d1377a0a8b53b005bf454aa7#diff-66694174e90422724c8c508d12a0f225L89

```diff
 -      params.require(:search).permit(:key_words, :main_type, :note_type,
 -                                     :min_date, :max_date, :created_by, :language)
 +      params.permit( :key_words,
 +                     :main_type,
 +                     :note_type,
 +                     :min_date,
 +                     :max_date,
 +                     :created_by,
 +                     :language )
```

@david-days - any ideas on fixing this test?

### PR DESCRIPTION
**Pull request by jywarren**
* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, David - seeing an error here for `GrapeSwagger` -- wondering if 2.0 was just released, causing this with non-backwards compatible issues? 

```
Error: test_Swagger_doc_functionality(SwaggerDocTest): GrapeSwagger::Errors::SwaggerSpec: Empty model SearchRequest, swagger 2.0 doesn't support empty definitions.
test/functional/swagger_doc_test.rb:12:in `block in <class:SwaggerDocTest>'
```

My local machine doesn't show this, with gems:

```
grape (0.17.0)
grape-entity (0.5.1)
grape-swagger (0.23.0)
grape-swagger-entity (0.1.4)
grape-swagger-rails (0.2.2)
grape-swagger-ui (0.1.0)
```

Doesn't look like `grape-swagger`has any new updates: https://github.com/ruby-grape/grape-swagger/releases

Re-running the build, and if this happens again, i'll see if I can check the version #s of the `grape-swagger` version on TravisCI. But maybe we should pin the version numbers of the gems just in case, like this:

```ruby
gem 'mocha', '~> 1.1'
```

**Comment by jywarren** [comment]
Indeed, TravisCI uses: `Installing grape-swagger 0.25.0` which isn't identical but not far off. `0.x.0` in theory in SemVer shouldn't break any APIs, but grape-swagger is a fairly young project (only since April of this year) so that could be an issue?

**Comment by jywarren** [comment]
Ooh, it worked this time... false alarm i guess? But open to pinning the version number... it could make a good `first-timers-only` issue! 

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

**Comment by jywarren** [comment]
This is odd -- Actually it still says 0% passed, but it lists the tests it ran... why does it say 0%?

```
Started
.......
Finished in 1.394978605 seconds.
------
7 tests, 19 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
------
5.02 tests/s, 13.62 assertions/s
./solr: line 1066: ps: command not found
No process found for Solr node running on port 8981
turning off solr dependence at config/sunspot.yml
```

**Comment by david-days** [comment]
He @jywarren ,

I'm not sure why it's doing that--I'll try to pull the code and see what I can do.

The Grape code and implementations that I worked with were some of the most basic, on purpose.  You know how it is--try to go with the "coolest" features and you usually end up in a swamp of undefined errors and bugs.  While it's possible that it was a false alarm, I think there might be something else in there, too.

**Pull request merged**
