### PR TITLE
Update _related.html.erb, fixes #949

### LINKED ISSUE #949: incorrect "question:generalspectrometer" tag gets added to questions from somewhere
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

### What happened just before the problem occurred

This person posted a question: https://publiclab.org/questions/chuynh451/11-01-2016/intensity-for-spectra-too-low

But it was originally tagged with `question:generalspectrometer` -- it should've been `question:spectrometer` or `question:general`, so there must be an error in the input form somewhere. 

Indeed this page shows that tag when you click the `Ask a question` button: https://publiclab.org/wiki/spectrometer -- the link ends up being:

https://publiclab.org/post?template=question&tags=question:generalspectrometer

The template code for that is here: https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb#L8

and it's pretty tangled; could use simplification or better formatting, maybe breaking it up onto multiple lines. But the key section is:

`
href="/post<%= '?template=question&tags=question:general'+(@tagnames.uniq.delete_if{|x| x.match(":") }).join(',') if @tagnames %>
`

The simplest fix would be to just add a comma after `general` -- as that's being concatenated to the tag name from `@tagnames.uniq`.

### PR DESCRIPTION
**Pull request by aayushgupta1**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

This is for the problem #949. I am first timer and am interested in contributing.

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! Thanks so much! I'm about to board a plane and probably won't be able
to review this for a bit, but we really appreciate your contribution!

**Comment by ryzokuken** [comment]
Although, could you please appropriately name the PR (referencing the issue)? Something like adding a little "(fixes #494)" would be wonderful.
Thanks.

**Comment by aayushgupta1** [comment]
Hi,

I'll Do that. It's PR#966 and PR#969. Sorry for the incovenince. I didn't
know that.

Regards,

Aayush Gupta

**Comment by jywarren** [comment]
Hi -- i edited the title and this looks perfect; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

It can also be helpful to leave a comment claiming an issue before opening a Pr, in case two people try to work on a problem at the same time.

Thanks! 😀🎉

**Comment by aayushgupta1** [comment]
Okay, thank you sir.

**Comment by aayushgupta1** [comment]
I'll remember that the next time I do this.

**Pull request merged**
