### PR TITLE
Listing of recent likes

### LINKED ISSUE #610: Listing of recent likes
In #309, we see that spam users are liking things in order to get link visibility. We can ban them, and #309 will make their usernames disappear from page like listings, but there is no master listing of likes, organized by time, so that we can occasionally skim it for spammers. Like spam is accumulating. 

A page at `/likes` listing all recent likes would be great, also showing a `ban` button for admins. 

Ban button example can be found here: https://github.com/publiclab/plots2/blob/master/app/views/admin/users.html.erb#L28

Likes have a model called `node_selections` and an index method could go here: https://github.com/publiclab/plots2/blob/master/app/controllers/like_controller.rb

### PR DESCRIPTION
**Pull request by Diksha2008**
Fixes #610 
Preview: 

image

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

### CODE REVIEW

**Comment by jywarren** [comment]
Wow, this looks amazing! 

I'd like to make three additional small requests, if you're willing? 

1. could we add a functional test for this page similar to [this one](https://github.com/publiclab/plots2/blob/master/test/functional/like_controller_test.rb#L16)?
2. can you add a single line in `<p>` tags above, about what the red indicates? 
3. could we make (for moderators and admins only) a hover over so we can read peoples' profiles quickly to check if they're spammers? It could be like:

```html
<a rel="tooltip" class="user" href="/profile/<%= like.user.name %>" data-title="<%= like.user.bio %>"><i class="fa fa-user" aria-hidden="true" style="color: red"></i> <%= like.user.name %></a>
```

That way you could hover over the username and see if there are spam links in the bio. Make sense? Are you interested in adding this? If you'd like, we could merge this, and you could make a new issue for these tweaks, and try to engage another first-time contributor. Your choice!

**Comment by Diksha2008** [comment]
I would like to try the first task (adding functional test) myself and would definitely love to help out first-time contributors to make the other two changes! :) I hope that is fine?

**Comment by jywarren** [comment]
That would be super. Thank you!

**Comment by Diksha2008** [comment]
@jywarren please review the functional tests. I'll create new first-timer issue for the other two tasks once this is merged!

**Comment by jywarren** [comment]
Wow, this is perfect. Thanks so much! Merging!

**Pull request merged**
