### PR TITLE
PLpeopleLayer added to /people page

### LINKED ISSUE #5874: Add PLpeopleLayer from LEL .
I have earlier worked on this issue here : https://github.com/publiclab/plots2/pull/5358/files but this was added directly and not as a layer in LEL 😄 !

https://github.com/publiclab/leaflet-environmental-layers/pull/206 adds PLpeopleLayer to LEL 🗺 !

- [ ] Let's update LEL code here in plots2 .

- [ ] Default layer on /people page should be set to PLpeopleLayer .

### Thanks :)

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #5874 .

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Screenshot 2019-06-29 at 2 12 45 PM

**Comment by sagarpreet-chadha** [comment]
@jywarren ...how to wait for js to load in capybara ? 
`wait_until` is depreciated .

**Comment by sagarpreet-chadha** [comment]
Okay increasing `Capybara.default_max_wait_time` to 180 solved it :)

The screenshot from test looks like this : 

https://camo.githubusercontent.com/bdc398875d822623551856f71483176a07fcd56e/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f706c6f7473322d73637265656e73686f74732f353936312d746573745f4c424c445f677269645f69735f6c6f616465645f6f6e5f70656f706c655f6d61702e706e67

screenshot_test_LBLD


@jywarren ...should we merge this ?

**Comment by jywarren** [comment]
Hi, @sagarpreet-chadha -- when you click a grid square, what do you see? In the demo here: https://publiclab.github.io/leaflet-blurred-location-display/examples/index.html

image


... you just see how many markers. Sorry, just catching up here - in this implementation, do you see a list of people instead of a count of markers?

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren ,
No we do not show the list of people name , we show count of markers . If we wish to show the former , we can do that in next release of LBLD ? 
What do you say ?

**Comment by jywarren** [comment]
That sounds great. Let's wait here until that release! Thanks, Sagarpreet!

**Comment by jywarren** [comment]
Hi @sagarpreet-chadha would you mind linking to an issue in LEL for this? Thanks!

**Comment by jywarren** [comment]
Hi! just noting this now exists via the LEL people layer! Thank you!!!!

**Pull request closed without merging**
