### PR TITLE
Partitioning the individual tags page

### LINKED ISSUE #5890: UI Improvements Planning Issue : Individual tags page
Next we start with the implementation of individual tags page. 

Capture

**Checklist**

- [x] Divide the page into three sections(Main image and the introduction card, sidebar with map, activity cards) @gautamig54 
- [x] Adjust the main image and add the number of people following on to the right. @CleverFool77 
- [x] make an introduction card for the tag containing the subscribe and learn more options. @gautamig54 
- [x] Activity cards with new design of style guide @CleverFool77 
- [ ] ~Show map on the sidebar and people near options @gautamig54~
- [ ] Sort by name, users and people following  @CleverFool77  **Wait a bit**
- [ ] ~Post a question option with dropdown @gautamig54~
- [x] Implement type dropdown containing options for all, questions, wikis and notes related to the tag. @CleverFool77 
- [x] Add related tags @gautamig54 

cc : @CleverFool77

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5890  (<=== Add issue number here)

Screen Shot 2019-06-14 at 9 57 59 AM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @gautamig54 Should I start the work on nav tabs to dropdown ? Coz I don't think that it's associated with other parts.

**Comment by gautamig54** [comment]
Sure @CleverFool77. You can start creating that. We can position it once this PR gets merged. I have also started with the main tag card.

**Comment by gautamig54** [comment]
@jywarren This PR is ready for merge.

**Comment by gautamig54** [comment]
@CleverFool77 I would suggest that you start with the image first.It will be better if do things in order. What do you say? 
After you resize and position the image, I can position the tags card as well.
What do you say?

**Comment by CleverFool77** [comment]
I'm not yet clear regarding the image. 
So regarding the image, Should I remove all the data above nav tabs ?

**Comment by gautamig54** [comment]
The data above the nav tabs will be divided into other segments like, related tags will go to the sidebar,  the wiki info and the other options will go to the tag card. 
I think you need to resize the image. Also, as discussed by @jywarren, the tags with no image, will display a light grey background in place of the image.
Sounds fine?

**Comment by CleverFool77** [comment]
> The data above the nav tabs will be divided into other segments like, related tags will go to the sidebar, the wiki info and the other options will go to the tag card.
> I think you need to resize the image. Also, as discussed by @jywarren, the tags with no image, will display a light grey background in place of the image.
> Sounds fine?

Exactly. So for now, Should I remove them, later we will add them in sidebar or wherever they are needed.

**Comment by gautamig54** [comment]
Since it is not a shadow page, therefore I don't think removing them is a good idea. We can just change their location as we proceed to the tasks.

**Comment by CleverFool77** [comment]
> Since it is not a shadow page, therefore I don't think removing them is a good idea. We can just change their location as we proceed to the tasks.

Ohkk. I'll just let it remain like usual at it's position then. And for now I'll work on tag's wiki image adjustment to take full span and those with no wiki to have grey image. And over it to have people following data in right-bottom corner. Cool.

**Comment by gautamig54** [comment]
That sounds great !

**Comment by jywarren** [comment]
Ah but if we're not on a shadow page, should we be merging this with the Lorem Ipsum text on the side? Maybe best come up with a short term fix for that, or hold this and open PRs against it so we can merge to master only once it's ready for people to see? Thank you!

**Comment by gautamig54** [comment]
@jywarren Can we add the related tags section on the right side, removing the Lorem Ipsum text. It will good to go as for now, until we add the map. 
What do you think @CleverFool77 ?

**Comment by CleverFool77** [comment]
Hi @gautamig54 Does UI as per new style guide have related tags section in second column ? If yes, then we can add it. Or else lorem ipsum text for now would be good. or how about combining two parts of the issue here and adding map here only ? So we won't have empty space ?
Thanks !!!

**Comment by CleverFool77** [comment]
Hi @gautamig54 Juts added your PR to project `in-progress` card.
Thanks !!

**Comment by gautamig54** [comment]
There is no section for related tags in the new style guide. I thought it will be good to place them in the side section. This can be a temporary solution. 
I also like your idea of adding a map in this PR itself. Let do that only. What do you say?

**Comment by CleverFool77** [comment]
> There is no section for related tags in the new style guide. I thought it will be good to place them in the side section. This can be a temporary solution.
> I also like your idea of adding a map in this PR itself. Let do that only. What do you say?

great. :tada:

**Comment by jywarren** [comment]
Yes, the related tags or map would both work. I actually updated the style
guide with a small section below the main example showing how related tags
could work, after you suggested it! It looks good!

**Comment by gautamig54** [comment]
@jywarren I have placed the related tags on the sidebar. This PR is ready for merge.

**Comment by jywarren** [comment]
Nice! We have some issue where the parallel tests are now overwriting each others comments so the screenshots are harder to find but you can get them in the "revisions" of the Dangerbot comment. Here's what yours looks like!

image

**Comment by jywarren** [comment]
It looks great. Any idea why tests aren't passing? Thanks!

**Comment by gautamig54** [comment]
I removed the conflicts and rebased the code, I am try not able to understand why the tests aren't passing.

**Comment by aSquare14** [comment]
I saw that the tests are failing because the tests are not able to get the expected components. I think you will have tp rewrite the tests too. Additionally, please restart your Travis once to see which ones were flaky.

**Comment by gautamig54** [comment]
@jywarren This issue is pending to be merged. Kindly look into this. Thanks!

**Comment by jywarren** [comment]
Hmm. I've seen this before: https://travis-ci.org/publiclab/plots2/jobs/548813611#L4029

```
 FAIL["test_graph", #<Minitest::Reporters::Suite:0x0000559a12381380 @name="TagSelectionTest">, 0.3034094249999839]
 test_graph#TagSelectionTest (0.30s)
        Expected: 16
          Actual: 20
        test/unit/tag_selection_test.rb:12:in `block in <class:TagSelectionTest>'
```

I think it's unrelated. I'll restart this but we can also rebase if it fails again.

**Comment by jywarren** [comment]
Here, on the other hand, i haven't seen this. But we aren't changing controllers, are we?

https://travis-ci.org/publiclab/plots2/jobs/548813612#L4029-L4077

```

 FAIL["test_should_have_a_active_asked_and_an_inactive_answered_tab_for_question", #<Minitest::Reporters::Suite:0x00005582b7d9e740 @name="TagControllerTest">, 51.05422450999998]
 test_should_have_a_active_asked_and_an_inactive_answered_tab_for_question#TagControllerTest (51.05s)
        Expected: 2
          Actual: 1
        test/functional/tag_controller_test.rb:577:in `block in <class:TagControllerTest>'
 FAIL["test_should_have_active_Research_tab_for_notes", #<Minitest::Reporters::Suite:0x00005582b7a5c140 @name="TagControllerTest">, 51.17118526999997]
 test_should_have_active_Research_tab_for_notes#TagControllerTest (51.17s)
        Expected: 2
          Actual: 1
        test/functional/tag_controller_test.rb:440:in `block in <class:TagControllerTest>'
 FAIL["test_should_have_active_question_tab_for_question", #<Minitest::Reporters::Suite:0x00005582b743b9f0 @name="TagControllerTest">, 51.31611122600003]
 test_should_have_active_question_tab_for_question#TagControllerTest (51.32s)
        Expected: 2
          Actual: 1
        test/functional/tag_controller_test.rb:450:in `block in <class:TagControllerTest>'
 FAIL["test_should_have_active_question_tab_for_question_for_show_for_author", #<Minitest::Reporters::Suite:0x00005582b704bf20 @name="TagControllerTest">, 51.426479293]
 test_should_have_active_question_tab_for_question_for_show_for_author#TagControllerTest (51.43s)
        Expected: 2
          Actual: 1
        test/functional/tag_controller_test.rb:566:in `block in <class:TagControllerTest>'
 FAIL["test_should_show_a_featured_wiki_page_at_top,_if_it_exists", #<Minitest::Reporters::Suite:0x00005582b5744c98 @name="TagControllerTest">, 51.897871684999984]
 test_should_show_a_featured_wiki_page_at_top,_if_it_exists#TagControllerTest (51.90s)
        Expected exactly 1 element matching "#wiki-content", found 2..
        Expected: 1
          Actual: 2
        test/functional/tag_controller_test.rb:289:in `block in <class:TagControllerTest>'
 FAIL["test_tag_contributors", #<Minitest::Reporters::Suite:0x00005582b8377590 @name="TagControllerTest">, 53.44871669599996]
 test_tag_contributors#TagControllerTest (53.45s)
        Expected: 2
          Actual: 1
        test/functional/tag_controller_test.rb:361:in `block in <class:TagControllerTest>'
 FAIL["test_tag_show", #<Minitest::Reporters::Suite:0x00005582b6d89210 @name="TagControllerTest">, 53.86620479599998]
 test_tag_show#TagControllerTest (53.87s)
        Expected exactly 1 element matching "#wiki-content", found 2..
        Expected: 1
          Actual: 2
        test/functional/tag_controller_test.rb:171:in `block in <class:TagControllerTest>'
 FAIL["test_wildcard_tag_should_have_a_active_asked_and_an_inactive_answered_tab_for_question", #<Minitest::Reporters::Suite:0x00005582b757ec18 @name="TagControllerTest">, 54.965742990000024]
 test_wildcard_tag_should_have_a_active_asked_and_an_inactive_answered_tab_for_question#TagControllerTest (54.97s)
        Expected: 2
          Actual: 1
        test/functional/tag_controller_test.rb:246:in `block in <class:TagControllerTest>'
```

**Comment by jywarren** [comment]
OK - indeed, these functional tests are testing for things on the page: 

https://github.com/publiclab/plots2/blob/78fffffab235243d280bb7d55ced6f0db0a6ef71/test/functional/tag_controller_test.rb#L571-L579

So, here, some tabs, items have been removed, and we should go through them one by one by the line numbers of the failing tests, and update them to match the new design. Does that make sense? 

Then we should be good to go!

**Comment by gautamig54** [comment]
We are not making any changes in the controllers. Its just the view files.

**Comment by aSquare14** [comment]
Yes, but the controller expects certain UI components for which it is testing. Since the UI is changing, tests are failing. You'll need to update the tests. Feel free to ask for help !

**Comment by gautamig54** [comment]
I guess the issue is with the active tabs. That's where the cases are failing. 
@CleverFool77 We still have the tabs after building a dropdown right?

**Comment by jywarren** [comment]
Well, you may need to change the functional tests to look for and confirm
your new HTML instead of the previous UI HTML... does that make sense?

**Comment by CleverFool77** [comment]
> I guess the issue is with the active tabs. That's where the cases are failing.
> @CleverFool77 We still have the tabs after building a dropdown right?

Yes but dropdown PR https://github.com/publiclab/plots2/pull/5925 isn't merged yet. 
Maybe your failing is because of divs you added for new UI. I didn't check the tests yet. But it might be.

**Comment by jywarren** [comment]
#5925 is now merged, and 2 other related ones. Hopefully if this is rebased it'll now resolve? Thanks!

**Comment by jywarren** [comment]
Hmm, just checking in with some oddness from automated screenshots (i get them by mail even though they aren't showing here):

image

**Pull request closed without merging**
