### PR TITLE
Add loading spinner for comments. Fixes #132

### LINKED ISSUE #132: Add loading spinners to like btn, post btn, comment btn, etc
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

Take a look at the comment section in any of the research notes in publiclab.org. The Publish button shows a `loading...` text after you press the publish button until it gets posted. We need similar behavior for Answer comments and Like buttons in Answers as well. We want to use font awesome spinners like [this](http://fontawesome.io/icon/spinner/)

Start by inspecting the code for the Publish button for comments. Here is javascript code shows the loading text: https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb#L70

You need to use html code for including the spinners and then use appropriate javascript code to make them show up during ajax load and hide it on completion like it is done here using the `beforeSend` block: https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb#L68-L71

You need to similar thing for [Answer like button](https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L46) and [Answer Comment button](https://github.com/publiclab/plots2/blob/master/app/views/questions/_form.html.erb#L11) as well.

### PR DESCRIPTION
**Pull request by BrainBuzzer**
After user clicks on submit button, a spinner is shown for the ajax request to indicate the action is in process.

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@BrainBuzzer We are reviewing this. Please have some patience till we review this. It may take some time due to the holidays. Merry Christmas! :santa: :christmas_tree:

**Comment by ananyo2012** [comment]
@BrainBuzzer Great work! It works fine. Can you modify it a bit? Can you Give a `loading...` or `Submitting...` text while it is loading. Also put the spinner within the button with some different color ? Maybe `#fff` so that it is visible within the button.

**Comment by BrainBuzzer** [comment]
I have added those both things. Icon is still visible on the button so I did not change the color. Everything else works fine.

**Comment by BrainBuzzer** [comment]
Sorry. Creating a new PR as this one is getting some merge problems.

**Pull request closed without merging**
