### PR TITLE
Add unicode emoji into --first-timers-only.md template

### PR DESCRIPTION
**Pull request by carlos-osorio-developer**
# Fixes [#9626](https://github.com/publiclab/plots2/issues/9626)
 

> This branch will add a Unicode emoji into the --first-timers-only.md issue template.

## Files to update
* * .github/ISSUE_TEMPLATE/--first-timers-only.md

### CODE REVIEW

**Review by Priyaraj17 — APPROVED** [review]
Looks good to me

**Review by waridrox — APPROVED** [review]
🤞but this should hopefully work. Great job @carlos-osorio-developer for working on this!🎉🥳 @cesswairimu @RuthNjeri pls have a look. Thanks :)

**Comment by cesswairimu** [comment]
will try to rebuild see if the tests finish running

**Review by cesswairimu — APPROVED** [review]
Looks great :tada: 
Thanks @carlos-osorio-developer  for working on this

**Comment by cesswairimu** [comment]
Thanks @waridrox and @Priyaraj17 for the reviews :tada: :tada:

**Comment by cesswairimu** [comment]
Screenshot from 2021-05-18 16-44-39
these templates are looking great :tada: :tada: ... thanks again everyone !!

**Comment by carlos-osorio-developer** [comment]
Thank you @cesswairimu! I didn't understand why the tests failed... Could you please enlighten me on this?

**Comment by cesswairimu** [comment]
@carlos-osorio-developer yeah, it was weird..I didn't  check to see the error raised but it happens sometimes...closing the PR and reopening to initiate another build solves it most times...

**Pull request merged**
