### PR TITLE
fix question area in question shadow page

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #0000 (<=== Add issue number here)

Fixing the continue button on the question card. 

Screen Shot 2019-06-08 at 7 18 15 PM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
@CleverFool77 This solves the issue. Thanks!

**Comment by jywarren** [comment]
Hi! We have a few ways to cause a login modal to appear when things are
clicked, including links. Could this be helpful? Esp so people don't lose
what they type into the box?

https://github.com/publiclab/plots2/blob/b1c57446d016f8cd0ec149a75298711270e1643e/doc/LOGIN_SYSTEMS.md#how-to-setup-login-modal-on-various-locations

**Comment by jywarren** [comment]
Hi Gautami, just checking if you saw this? Thanks!

**Comment by gautamig54** [comment]
Yes @jywarren. Sorry for the late reply. I am looking into this.

**Comment by gautamig54** [comment]
I have implemented the modal here, but the issue is that it is redirected to the dashboard after login rather than on the shadow question's page. I am working on that. 

ezgif com-video-to-gif

**Comment by jywarren** [comment]
awesome, keep up the great work!

**Comment by aSquare14** [comment]
@gautamig54  Add an action which after login redirects to the shadow page. You could look at https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in this! Devise documentation mentions how to to this :)

**Comment by jywarren** [comment]
Hi all! How is this going? Thank you!

**Comment by gautamig54** [comment]
Hi @gauravano. Can you look into this and guide. We already have a after_sign_in path function defined in application controller. 
The modal works fine, but after login it is directed to the dashboard instead of the shadow page. What am I missing here?

**Comment by aSquare14** [comment]
Were you able to resolve the issue ?

**Comment by gauravano** [comment]
Hey @gautamig54, will look into this. Can you resolve conflicts here, so that I can fetch this PR locally and test it better. Also, this is the related issue right - https://github.com/publiclab/plots2/issues/5733 ? 

Also, have you set routes, yet?

**Comment by gautamig54** [comment]
Still facing this issue @aSquare14.

**Comment by gauravano** [comment]
You can use <%= link_to "", new_user_session_path( return_to: '/question_shadow' )%> for now and modify return_to according to the text.

**Comment by gauravano** [comment]
`<a class="btn btn-default" href="/login?return_to=/questions" role="button" aria-pressed="true"> Continue </a>` is also working

**Comment by gautamig54** [comment]
> `<a class="btn btn-default" href="/login?return_to=/questions" role="button" aria-pressed="true"> Continue </a>` is also working

Hi @gauravano! i tried doing this. The issue here is as soon as I click on login, the modal opens and then disappears and the login page opens up. This was the earlier implementation of the login/signup.
@jywarren wanted to implement modal here, so that the question written by user is retained even after logging in. Using this method returns the user to the questions_shadow page but deletes the content. 

ezgif com-video-to-gif (1)

**Comment by aSquare14** [comment]
Is the above issue resolved ? If not I could maybe test your code locally and help you figure out a solution .

**Comment by gautamig54** [comment]
Hi @aSquare14! I tried both the suggestions that @gauravano suggested. None of them seem to work here.

**Comment by gautamig54** [comment]
Hi! Can we merge this for now?
I will make a follow up issue for the same here.

**Comment by jywarren** [comment]
I think this can be merged now, but let's check the screenshots just to be sure, once this finishes building and testing! 🎉 Thanks for your patience, all!

**Comment by jywarren** [comment]
Hm. I think it got duplicated:

image

**Comment by jywarren** [comment]
🎉

**Pull request merged**
