### PR TITLE
Fix all 11 changes in plots2/app/views/home/subscriptions.html.erb from t(..) to translation (..)

### PR DESCRIPTION
**Pull request by sap143**
Fixes #6778 

Fix all the 11 changes  t(..) to translation (..) in line number 9,11,34,37,58,59,60 inside  plots2/app/views/home/subscriptions.html.erb

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by nstjean** [comment]
Thanks! While I'm reviewing the code can you add the issue # at the top?

**Comment by sap143** [comment]
@nstjean  I have mentioned issue # and title

**Comment by nstjean** [comment]
Here's a screenshot of the working code change.

FireShot Capture 063 - 🎈 Public Lab_ Subscriptions - localhost

**Comment by sap143** [comment]
@nstjean Thanks

**Comment by nstjean** [comment]
@SidharthBansal The error is that no language set one again, hopefully you can get that all set.

**Comment by SidharthBansal** [comment]
Please provide a descriptive title. 
Thanks for contributing at PL

**Comment by SidharthBansal** [comment]
Quick Suggestion: Go to the travis tests and check what error is happening.
See
image
First thing: we can remove that t->translation to other pr that causes this error
Second thing: we can solve that error in other pr by fixing the above test. 


Thanks

**Comment by nstjean** [comment]
@SidharthBansal Ahhh, ok, so it's test_graph in test/unit/tag_selection_test.rb that is causing it? I'll take a look at it.

**Comment by SidharthBansal** [comment]
Yep

**Comment by nstjean** [comment]
@SidharthBansal When I run that test in my local it passes. So what do I do next?

**Comment by SidharthBansal** [comment]
Please read https://github.com/publiclab/plots2/pull/6778#issuecomment-554416983

**Comment by nstjean** [comment]
"we can remove that t->translation to other pr that causes this error" I don't know what this means, can you clarify? How do we know what PR causes this error? I don't know much about testing.

**Comment by SidharthBansal** [comment]
To understand testing please refer https://hackernoon.com/your-guide-to-testing-in-ruby-on-rails-5-c8bd122e38ad OR https://guides.rubyonrails.org/testing.html
In short, testing is done to ensure the implementation of working properly.


Try to read the failing test in the screenshot provided above. Detect the line number and file from the failing test. Then move that line from this PR to new PR.


Thanks

**Comment by nstjean** [comment]
Ok thanks!

**Comment by nstjean** [comment]
I ran the test in my local and it's passing.

**Comment by SidharthBansal** [comment]
Which command are you using?

**Comment by nstjean** [comment]
`rails test test/system/screenshots_test.rb`

**Comment by SidharthBansal** [comment]
can you run all the tests and see what is failing?

**Comment by nstjean** [comment]
So when I run `rails test` I get 8 errors... but I'm seeing the same errors when I run the full tests on the master branch.

natalie@natalie-ubuntu: ~-Dev-Ruby-public-lab-plots2_007

natalie@natalie-ubuntu: ~-Dev-Ruby-public-lab-plots2_006

**Comment by SidharthBansal** [comment]
If errors are same in master and current changed branch, then I guess local
is not showing error. Tests are just failing at Production.
@gauravano @jywarren can you please help us in this. You both are working
on this since a long time
Thanks

**Comment by jywarren** [comment]
Hi, all, sorry can you catch me up on this? 

> @SidharthBansal The error is that no language set one again, hopefully you can get that all set.

I found I wasn't able to test this locally because i couldn't set the language locally. But the recent PRs doing this have all worked fine, so I think it's OK... let me review the PR.

**Comment by SidharthBansal** [comment]
Just catching you as you indicated!

**Comment by jywarren** [comment]
The error is odd -- 

```

 FAIL["test_graph", #<Minitest::Reporters::Suite:0x0000556c121340d8 @name="TagSelectionTest">, 0.3586234310000691]
 test_graph#TagSelectionTest (0.36s)
        Expected: 16
          Actual: 20
        test/unit/tag_selection_test.rb:12:in `block in <class:TagSelectionTest>'
  319/319: [===============================] 100% Time: 00:00:24, Time: 00:00:24
```

I'm not sure it's related. So I'm restarting that test, let's see if it passes... ?

**Comment by jywarren** [comment]
Yay! Merging this now, thanks for sticking with it, we appreciate your help! And thanks to everyone who helped make this happen!

**Pull request merged**
