### PR TITLE
Fix tag search results for maps

### LINKED ISSUE #5658: Tag variable is missing from search input
Screen Shot 2019-05-05 at 5 36 03 AM

Should say, "Sorry, no map is tagged with <%= params[:id] %>. ..." 

- <%= params[:id] %> isn't rendering
- remove the word "tag" at the end to shorten the message and improve its grammar

code link:
https://github.com/publiclab/plots2/blob/master/app/views/tag/show/_tab_content.html.erb#L50

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #5658 
 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

Screenshot of update:
Screen Shot 2019-05-05 at 5 40 53 AM

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@publiclab/reviewers

**Comment by sashadev-sky** [comment]
It looks like the link to the word "here" (/maps) is broken due to:

`uninitialized constant WillPaginate::ActionView::BootstrapLinkRenderer`

Could this be related to #5612 ?

**Comment by sashadev-sky** [comment]
@Souravirus reverting back to 
`<div class="text-center"><%= will_paginate @nodes, renderer: BootstrapPagination::Rails unless @unpaginated %></div> `
seems to  fix the error I mention above and I see you made an update to this line 11 days ago so maybe you can advise here?

**Comment by sashadev-sky** [comment]
@jywarren any idea why this is failing at post_test.rb? I'm not sure it has to do with my code and I saw you recently added that testing file

**Comment by jywarren** [comment]
Trying to fix a system test in https://github.com/publiclab/plots2/pull/5661 - now we've resolved it, this may need a rebase? Thanks!

**Comment by sashadev-sky** [comment]
The test passed after rebase! thank you @jywarren

**Pull request merged**
