### PR TITLE
Dashboard translation

### PR DESCRIPTION
**Pull request by jiteshjha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jiteshjha** [comment]
Hello, @jywarren !
I have integrated I18n into dashboard view.
Re-based and ready for merge!

**Comment by jywarren** [comment]
Running tests now. 

In the future, once you have a batch of related commits, you can use `git rebase --interactive master` and squash commits so that all your changes are in one batch, which makes the commit history easier to follow. 

BTW, please leave "reviewed/confirmed" unchecked, as it makes it easier for me to skim the pull requests list. Thanks.

OK -- love the tests you've included, but one more request before I merge any more work using JavaScript; can you connect with @ananyo2012 and see about using the [new Jasmine javascript test framework](https://github.com/publiclab/plots2/#testing) to test that the JavaScript internationalization is working? I'd like there to be one check on whether those successfully complete, if it's possible, especially as it touches high-visibility parts of the site, which we previously were able to rely on being static and stable. 

I'll merge this one now, however, as all tests passed. Thanks again!

**Comment by jiteshjha** [comment]
Great! I'll talk to @ananyo2012 and use Jasmine tests. 
Thanks!

**Comment by jywarren** [comment]
thank you! Publishing to the live site now...

**Pull request merged**
