### PR TITLE
added fa-icon 

### PR DESCRIPTION
**Pull request by tvibhu12**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
Hi @tvibhu12.. Please upload a screenshot/GIF showing your changes..
And please add the issue number in the PR body 
Thanks

**Comment by tvibhu12** [comment]
@oorjitchowdhary  thanks for helping.
@plotsbot   added `<i class="fa fa-shopping-cart" style="color: white" aria-hidden="true"></i>` [here](https://github.com/tvibhu12/plots2/blob/ecf3d830d8e6800b4f051bd8466bcaf1f987efa2/app/views/layouts/_header.html.erb#L70)
issue is #4440 

screenshot from 2019-01-07 16-27-08

**Comment by HarshKhandeparkar** [comment]
@trivibhu12 he meant  a screenshot of the local version of plots2 in actions which reflects the Changes in the browser.

**Comment by HarshKhandeparkar** [comment]
Also you can remove `#1000` in the pull request and add a link to the issue there like `https://github.com/publiclab/plots2/issues/4440`

**Comment by SidharthBansal** [comment]
Can you please tell the issue number so that we can review the PR?
Thanks for contributing at Public Lab.

**Comment by gauravano** [comment]
Thanks @tvibhu12 for working on this but issue is already claimed by other contributors. Thanks!

**Comment by gauravano** [comment]
https://github.com/publiclab/plots2/issues/4440

**Pull request closed without merging**
