### PR TITLE
Added  hover effects to the home link on navbar

### PR DESCRIPTION
**Pull request by malaikaIshtiaq**
I added a hover effect to the home link "Public Lab"

### CODE REVIEW

**Comment by malaikaIshtiaq** [comment]
Here is the gif for hover effect 
https://res.cloudinary.com/malaika/image/upload/v1579528522/ezgif-6-6d4a9e9eb0b7.gif

**Comment by ananyaarun** [comment]
@jywarren , Kindly review and merge !

**Comment by jywarren** [comment]
Hi, this is a great idea! Do you think we could dim the white text to something like #ddd; and not use the underline? Thank you!!!

**Comment by malaikaIshtiaq** [comment]
Yes it will look better

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
