### PR TITLE
Fixed position for back-to-top button #3387

### LINKED ISSUE #3387: Improving the back-to-top button
### Please describe the problem (or idea)
The Back-to-top button is present at the end of the webpage and is static there. Instead it can be present at the bottom-right corner of the screen all the time whenever someone scrolls down the page to make the user expirience better.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

There should have been a back-to-top button all the time at the bottom right corner whenever someone scrolls down the page.

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?
rbhatia46
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome Version 69.0.3497.100, Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by ckairen**
Fixes #3387  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

fixed_button_proof

### CODE REVIEW

**Comment by ckairen** [comment]
@publiclab/reviewers
Hi, I've updated a small portion of code for the fixed position back-to-top button. I've attached a gif to prove that it works and if this is acceptable, please approve my pull request.
Thank you!!

**Comment by gauravano** [comment]
I think, tooltip not required. Thanks!

**Comment by gauravano** [comment]
Although, we can think of some improvements like blurring/showing of button based on window distance from navbar, etc? But, in another PR.

Thanks!

**Comment by gauravano** [comment]
Merged :tada: :balloon: :+1:

**Pull request merged**
