### PR TITLE
Added tests for show_for_author

### PR DESCRIPTION
**Pull request by SidharthBansal**
These are the remaining tests in addition to #2108 for maps, wikis, and questions
Is there any need for the integration tests?
I have made some rearrangements in the controller so that it will be in analogy with the show method.
I have changed the model a bit in accordance with the show controller.
This is ready to be merged.

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, what do @publiclab/reviewers think of this one? It looks good to me; thanks @SidharthBansal !!!

**Comment by SidharthBansal** [comment]
@jywarren @sagarpreet-chadha has reviewed it. Can you please review it again?

**Comment by jywarren** [comment]
Super. Merging! and many thanks -- this is a big one. It makes me want to try to reduce the code complexity at some point... but glad to have all these tests to cover it!

**Comment by jywarren** [comment]
🎉 👍

**Pull request merged**
