### PR TITLE
Added SVG for outgoing moderation email

### LINKED ISSUE #3338: Display of an SVG at various places to show if user is banned or active
Display if someone's been banned or is still active in moderator emails (https://github.com/publiclab/plots2/blob/master/app/views/admin_mailer/notify_node_moderators.html.erb) using the SVG at the above URL so moderators can tell if something's already been moderated without opening a link

SVG preferred: https://gist.github.com/jywarren/ea0523a09f6f8660486b14eeea15de95

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #3338 
@publiclab/reviewers Please check this out!

Active user
screenshot 88

I'm not sure how will I check for the BANNED svg..
As the user will be banned, no emails about new posts from the user will be sent to moderators..
I'm just a little confused here..

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@gauravano @jywarren @SidharthBansal

**Comment by oorjitchowdhary** [comment]
This is correct.. Am I eligible for credits on this one? 20 mins to deadline

**Comment by SidharthBansal** [comment]
@jywarren or @gauravano can you please see it. I am afraid that I can do a mistake.
I can't review it sorry @jywarren

**Comment by oorjitchowdhary** [comment]
So I think I'll leave this one.. Was waiting for an approval but didn't get one.. I'll claim my last task on gci now

**Comment by jywarren** [comment]
No problem! Let's catch a break now that we passed this big milestone.
We'll add more detail later and circle back!

**Comment by oorjitchowdhary** [comment]
@jywarren Yess.. cheers to the achievement.. 
But I'm back to work.. 
Could you review it now perhaps...

**Comment by oorjitchowdhary** [comment]
@gauravano Could you please review this... I'd like to get this merged before today's deadline

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers

**Comment by jywarren** [comment]
Hi! This is a great start, and apologies for the slow reply! 

What we'd like, however, is a unique route (defined in config/routes.rb) which returns one SVG document, and nothing else. The route could be like:

https://publiclab.org/status/0000.svg (where 0000 is the nid)

This would show an SVG corresponding to the node status. That way we can point at the SVG in an image tag from the moderators email -- we don't have to do that part yet actually but you could include it since you've basically coded it already!

The only thing I'd like to see beyond this is a test that checks the response of the new controller action with a functional test. The action ought to probably be under the notes_controller.

Thank you, i hope this makes sense!

**Comment by oorjitchowdhary** [comment]
> What we'd like, however, is a unique route (defined in config/routes.rb) which returns one SVG document, and nothing else. The route could be like:
> 
> https://publiclab.org/status/0000.svg (where 0000 is the nid)
> 
> This would show an SVG corresponding to the node status. 

Hi, really sorry that this thread got neglected.
I'm trying to finish this up ASAP.

But I'm not really sure how can I configure a route for a SVG.
I haven't really done it before.
@gauravano could you help me here
Thanks

**Comment by jywarren** [comment]
I believe you should be able to render plain text... worth a try, something
like:

render plain: "<svg...></svg>"

Could that work?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab
@jywarren @gauravano

**Pull request closed without merging**
