### PR TITLE
Split create function into two login paths

### PR DESCRIPTION
**Pull request by Radhikadua123**
Part of #3879

No functionality change, just split function into two parts.

### CODE REVIEW

**Comment by Radhikadua123** [comment]
@jywarren Please have a look at #3884 and #3883 and merge them when you get time! :) 

About other parts of #3879 related to code cleaning, I'll create separate PRs.

**Comment by jywarren** [comment]
awesome!!!! great work and ping me when it's been tested a bit on unstable!

**Comment by Radhikadua123** [comment]
Hi @SidharthBansal,
Actually I had chosen base branch of #3884 to be this PR's branch.
So, once that gets merged into this one, I'll deploy this PR to unstable and test it out asap.
Thanks!!

**Comment by SidharthBansal** [comment]
Great!!!

**Comment by jywarren** [comment]
OK! Thanks!

**Pull request merged**
