### PR TITLE
Added 'Your Digest' button

### LINKED ISSUE #4399: Add a button for 'Digest' page
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
* [ ] 🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

screenshot 131

Add a `Your Digest` button here.

* [ ] 📝 Update the file `app/views/layouts/_header.html.erb` in the `plots2` repository (press the little pen Icon).
https://github.com/publiclab/plots2/blob/fefa4aa7ed91776a7b1b25902e804089de2f9d89/app/views/layouts/_header.html.erb#L110-L112

Add this line after L110

`<li><a href="/subscriptions/digest">Your Digest</a></li>`

* [ ] 💾 Commit your changes

* [ ] 🔀 Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.

* [ ] 🏁 Done Ask in comments for a review :)

🤔❓ Questions?
Leave a comment below!

Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. 
Thanks!

### PR DESCRIPTION
**Pull request by supasheva**
Fixes #4399 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
@supasheva this looks great. :balloon: Kindly provide a screenshot for the page from your localhost. Thanks

**Comment by supasheva** [comment]
hi @cesswairimu . Iam having a bit of trouble. i keep getting this error
 `The application encountered the following error: Error loading the 'mysql2' Active Record adapter. Missing a gem it depends on? mysql2 is not part of the bundle. Add it to your Gemfile`

I am not familiar with ruby on rails... Do i need to run the application to take the screenshot?

**Comment by supasheva** [comment]
@cesswairimu  Thanks. It turns our I copied  the contents of `database.yml.example` instead of `database.yml.sqlite.example`
screenshot 2018-12-27 at 12 03 00 pm

**Comment by cesswairimu** [comment]
Thanks @supasheva for working on this and welcome to PublicLab!! @SidharthBansal  this is ready to be merged.

**Comment by gauravano** [comment]
We would love to have more help from you, if you are interested in solving more issues, you can find look at https://code.publiclab.org/#r=all . Thanks @supasheva !

**Comment by gauravano** [comment]
Adding an additional screenshot for future reference: 
digest_record

**Pull request merged**
