### PR TITLE
Bump publiclab-editor from 2.2.0 to 3.0.1

### PR DESCRIPTION
**Pull request by Sagarpreet**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Sagarpreet** [comment]
Tests passing now 🎉

**Comment by Sagarpreet** [comment]
@jywarren we can finally merge this 💯  Kindly review 😄

**Comment by jywarren** [comment]
Looks amazing!!!! Great work. Can you test it on stable and then we'll publish to live tomorrow? Thanks Sagarpreet and great work!

**Comment by jywarren** [comment]
Hi! It looks like the styling of the toolbar is a little odd, i wonder if we need to adjust the plots2 css? 

image

**Pull request merged**
