### PR TITLE
Fix the arial label misspell

### LINKED ISSUE #9561: Fix misspelled aria labels
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] Change `aria-hiddden` to `aria-hidden` in these files https://github.com/publiclab/plots2/search?q=aria-hiddden

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by j-saurabh**
Fixes #9561 (Fix misspelled aria labels)

Fixed the spelling in the file https://github.com/publiclab/plots2/search?q=aria-hiddden.

The issue raised for this was : https://github.com/publiclab/plots2/issues/9561

Let me know in case of any issues

### CODE REVIEW

**Comment by TildaDares** [comment]
@j-saurabh This LGTM 🎉

**Review by TildaDares — APPROVED** [review]
This LGTM🎉

**Review by sahilsaha7773 — APPROVED** [review]
LGTM!

**Comment by jywarren** [comment]
This looks great! I'm not sure why the system tests failed; the error was pretty mysterious (see below). I just restarted the tests to see if it was just something random and unrelated. 🤷 

```
2021-04-27 09:53:01 +0000 Rack app ("POST /comment/create/56" - (127.0.0.1)): Mysql2::Error
=============[Screenshot]: tmp/screenshots/failures_test_post_note,_then_comment_on_FRESH_note.png
ERROR CommentTest#test_post_note,_then_comment_on_FRESH_note (323.54s)
Minitest::UnexpectedError:         Mysql2::Error: 
            app/models/tag.rb:430:in `update_tags_activity'
            app/models/node.rb:678:in `tag_activity'
            app/models/node.rb:671:in `add_comment'
            app/helpers/comment_helper.rb:6:in `create_comment'
            app/controllers/comment_controller.rb:26:in `create'
```

**Comment by jywarren** [comment]
Hooray, it was unrelated!!! Merging now. Thanks everyone!!!

**Comment by j-saurabh** [comment]
Thank you everyone!!! This is my first contribution, a very tiny contribution towards open source. But it is kind of an accomplishment to me. Looking forward to making more and more contribution in open source.

**Pull request merged**
