### PR TITLE
Absolute Beginner Contributor, Adding lines from 624 to 626

### PR DESCRIPTION
**Pull request by pawan-nirpal-031**
I look forward to any constructive criticism you might have.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by coder645** [comment]
@pawan-nirpal-031 why did you add this line "Yey this happens to be my first contribution looking forward to be an active contributor, thanks for the effort for this project for noobs like me"
Lol it's hilarious :rofl: :rofl:

**Comment by cesswairimu** [comment]
Hey @pawan-nirpal-031, we do not need any changes on this file as of now...kindly look for issues already created or create a new issue for any bugs you may get..Thanks and closing this.

**Comment by pawan-nirpal-031** [comment]
> @pawan-nirpal-031 why did you add this line "Yey this happens to be my first contribution looking forward to be an active contributor, thanks for the effort for this project for noobs like me"
> Lol it's hilarious :rofl: :rofl: 

 Well that was so stupid of me, please don't mind I think I was just supposed to write something and that's what I did, I'm a little embarrassed but I am getting good at it so please excuse me.😅

**Comment by ebarry** [comment]
oh, thank you @pawan-nirpal-031 and welcome! Your comment was absolutely not stupid—not at all. 
It was inappropriate for @coder645 to write that comment.

**Comment by pawan-nirpal-031** [comment]
@ebarry Thank you, no honestly it was my mistake I wrote that stupid line of code, I thought I was just supposed to write something and that this was a project for absolute beginners so they wouldn't mind if someone like me just starting out would screw things up a little bit, mess around and learn it that way, I'm extremely sorry for assuming that. Also thanks for understanding, I just wanted to appreciate whatever you guys did with in project and so it wasn't a silly thing to do write I thought. But anyways thanks for understanding.

**Pull request closed without merging**
