### PR TITLE
Add information to bot

### LINKED ISSUE #5179: Brainstorm list of supportive additions to Welcomebot
Our new welcomebot "expandable sections" are great for offering support without overwhelming:

https://github.com/publiclab/plots2/blob/master/.github/config.yml

Let's brainstorm more additions!

## Opening first PR

* [ ] ask people to join the weekly check-in
* [ ] put hints on Travis debugging
* [ ] installation help

## Merging first PR

* [x] help someone else

### PR DESCRIPTION
**Pull request by ananya**
Fixes #5179 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @ananya 
Maybe you pushed gemfile.lock by mistake. 🤔🤔

**Comment by ananya** [comment]
hey @gauravano we are already having a link for git in first time issue template, I am not quite sure about where it would be a good place to add it in bot message. 
And @CleverFool77 I haven't added the code of conduct because it was already there :sweat_smile:

**Comment by ananya** [comment]
@CleverFool77 oh yes :sweat_smile: Thank you. It is fixed now :stuck_out_tongue:

**Comment by divyabaid16** [comment]
@ananya 
@CleverFool77 is right and she is talking about the Gemfile.lock that you must have added by mistake. 
Now, I guess, you have accidentally deleted this file. 
You just need to ignore this file while creating a commit.

**Comment by ananya** [comment]
@divyabaid16 @CleverFool77 thankyou. I am closing this pr and opening a new file :stuck_out_tongue:

**Comment by CleverFool77** [comment]
Hi @ananya we could have resolved this. 😅😅

**Comment by CleverFool77** [comment]
You just need to reset.

**Comment by ananya** [comment]
@CleverFool77 @divyabaid16  just got into trouble with git :stuck_out_tongue: . I have made a new pr here #5242

**Pull request closed without merging**
