### PR TITLE
remove duplicate from assets.rb already present in application.js

### LINKED ISSUE #7889: Check for js files duplication in assets.rb and application.js
Currently many files which are already present in the application.js manifest file are present in assets.rb as well. Also if files mentioned in assets.rb are applicable for use throughout the application it is better to include them in application.js instead of augmenting the asset array in assets.rb.

**Please describe the desired behavior.**
The duplicates can be removed and also further js files used throughout the application can be moved from assets.rb to application.js manifest file. This will improve the performance greatly since the js file will be minified,gzipped and cached allowing loading only when modified.

**Additional context (optional)**
Please refer Best Practices in Rails Precompilation subsection [here](https://launchschool.com/blog/rails-asset-pipeline-best-practices).

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #7889 

Duplicate js files already present in application.js removed from assets.rb.

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@jywarren @cesswairimu @emilyashley @SidharthBansal @VladimirMikulic can you kindly review? Also since ics is already present as a package in /lib as well as in app/asssets/javascripts from where should I remove it? Since it is a library package it makes more sense to remove it from the /javascripts directory. Thanks :v:

**Comment by Tlazypanda** [comment]
@Uzay-G Thanks a ton for the review! :octocat:

**Comment by Tlazypanda** [comment]
> @jywarren @cesswairimu @emilyashley @SidharthBansal @VladimirMikulic can you kindly review? Also since ics is already present as a package in /lib as well as in app/asssets/javascripts from where should I remove it? Since it is a library package it makes more sense to remove it from the /javascripts directory. Thanks

Hey @jywarren @cesswairimu  Need your input on this :sweat_smile:

**Comment by Tlazypanda** [comment]
Hey @cesswairimu Can you kindly review? This shouldn't break anything but I am a bit worried :sweat_smile:

**Comment by cesswairimu** [comment]
I understand cool I am pulling this and will see if I can see anything locally..also @Tlazypanda if you come across any issue that can be an fto..kindly ping @nsachin08..I can also help converting it to a first-timer issue..haven't been able to get one yet.

**Comment by jywarren** [comment]
trying to restart these tests!!

**Comment by jywarren** [comment]
OK, we look good here! I'm not sure about `ics` -- i guess i trust your judgement!!! 🎉 

If you think this is good, let's move ahead! Do you want to try testing it out on stable?

**Comment by jywarren** [comment]
er, unstable?

**Comment by Tlazypanda** [comment]
Hey @jywarren have pushed on unstable now can you help me test just to be sure I don't miss anything? Thanks :v:

**Comment by Tlazypanda** [comment]
@jywarren @cesswairimu I have tested some routes out on unstable seems alright ...can you also crosscheck once because i might have missed something ? :sweat_smile:

**Comment by jywarren** [comment]
Rebased to check on GitPod!

**Pull request merged**
