### PR TITLE
Include needed environment variables

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Is this one ready to go? Thanks!

**Comment by icarito** [comment]
It was but now we need more env variables for the reply-by-mail feature. I'll add those to this PR to keep it in one place.

**Comment by SidharthBansal** [comment]
@icartio does this pr also contain environment variables of Google Authentication as discussed in pr #2771 ?
Thanks

**Comment by icarito** [comment]
I guess request.env is different from ENV.  From #2771:

2 config/initializers/omniauth.rb
<https://github.com/publiclab/plots2/pull/2771/files#diff-1fddd49878aa6e37e8f10f118cf67dfb>


@@ -1,4 +1,4 @@

Rails.application.config.middleware.use OmniAuth::Builder do

provider :google_oauth2, ENV["google_app_key"],ENV["google_app_secret"]
, skip_jwt: true

- provider :facebook, ENV["APP_ID"],ENV["APP_SECRET"], skip_jwt:true

+ provider :facebook, ENV["APP_ID"],ENV["APP_SECRET"], {
scope:"email,public_profile,user_likes"}



So we need "google_app_key" and "google_app_secret" or / and "APP_ID"
and "APP_SECRET".

Feel free to add the needed variables to #2771. You can follow the
example here. We'd need the in `containers/docker-compose-*.yml`.

I advise you to prepend "OAUTH" or some other prefix so that we known
which variables correspond to what component.

Also, by convention generally environment variables are usually uppercase.

As always thank you for your hard work.

Regards,
Sebastian

**Comment by SidharthBansal** [comment]
>So we need "google_app_key" and "google_app_secret" or / and "APP_ID" and "APP_SECRET".

For now, we need to set ``google_app_key`` and ``google_app_secret``. 
We will take care of "APP_ID" and "APP_SECRET". after facebook provider pr is done
Thanks

**Comment by SidharthBansal** [comment]
>I advise you to prepend "OAUTH" or some other prefix so that we known which variables correspond to what component. 
>Also, by convention generally environment variables are usually uppercase.

I will do them. Thanks for suggestion.

**Comment by SidharthBansal** [comment]
>I'll look at generating those app codes but only @jywarren has access to the google-apps administration panel in order to generate those tokens.

Anyone can generate app_tokens by their google accounts. But I don't know who takes cares of generation of app_tokens at public labs @icarito  or @jywarren 
Regards,
Sidharth

**Comment by SidharthBansal** [comment]
>It would be cool to summarize what variables are needed and we can add the either in this PR or in another similar to it.

OK I will push it as comments in the respective file

**Pull request merged**
