### PR TITLE
improve UI of digest email

### LINKED ISSUE #3061: Improve digest email template
The digest emails have some inconsistent links and broken css.

### PR DESCRIPTION
**Pull request by ViditChitkara**
closes #3061

### CODE REVIEW

**Comment by ViditChitkara** [comment]
Hi @jywarren, we can now have a view of the mailers on local machine by visiting localhost:3000/rails/mailers. Can you have a look at it?

**Comment by jywarren** [comment]
Very cool!

image

This looks great. Ready to merge?

**Comment by jywarren** [comment]
Maybe we should name it `[Public Lab] Your weekly digest` and have a link that says "click here to choose your followed topics" and "click here to change your subscription settings"?

**Comment by jywarren** [comment]
the links could be at the bottom...

**Comment by ViditChitkara** [comment]
```
[Public Lab] Your weekly digest
```
Hi @jywarren, exactly where should it be? In the email subject or should we replace Bob's digest (in above mail)? 
Thanks

**Comment by ViditChitkara** [comment]
Sure, we can put the links at bottom. Will do

**Comment by ViditChitkara** [comment]
@jywarren I have made the changes. I guess this is ready now!

**Comment by jywarren** [comment]
Awesome!

**Pull request merged**
