### PR TITLE
Updated Add location button

### LINKED ISSUE #6856: Style "add a location" button to match style guide
Pages like https://publiclab.org/wiki/london-uk have a prompt to add a location:

image

However, the [style guide](https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab) shows we should be showing them in a button like this:

image

The icon should be: `<i class="fa fa-map-marker" style="color:#c40;"></i>`

And the text should be (on this page) "Add a location" and not "Add your location". 

We'd love help fixing this!

The code for it is here: 

https://github.com/publiclab/plots2/blob/1cfd91a87c7333718960a20b560857c88920c0d3/app/views/sidebar/_related.html.erb#L48-L54

### PR DESCRIPTION
**Pull request by sssash18**
Fixes #6856  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x]  ask `@publiclab/reviewers` for help, in a comment below

**New Add Location Button**
Screenshot** 2020-01-12 at 3 44 27 PM

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sssash18** [comment]
@publiclab/reviewers Could you please share your views on this?

**Comment by SidharthBansal** [comment]
Great thanks. There are sme conflicts. kindly remove them

**Comment by SidharthBansal** [comment]
@VladimirMikulic kindly review

**Comment by sssash18** [comment]
Can you guide me about how to remove the conflicts

**Comment by SidharthBansal** [comment]
There are two ways to resolve them. First way is to sink the master onto the branch having the changes(pr) and resolve them on the editor.
Second way is to use the Github UI and resolve them. Then git pull the changes to your branch.
Thanks

**Comment by SidharthBansal** [comment]
@VladimirMikulic @Uzay-G can help you if you face any problems?

**Comment by Uzay-G** [comment]
@sssash18 the conflicts are probably happening because another pull request has edited this file in a different way. Could you provide a screenshot of what you see when you click `resolve conflicts`?

**Comment by VladimirMikulic** [comment]
@SidharthBansal I agree with @Uzay-G. We don't have the permissions to view the conflicts.
A screenshot or just pasted text would help.

**Comment by sssash18** [comment]
Actually I saw your comment after resolving the conflict, you could review my changes and suggest changes .

**Comment by Uzay-G** [comment]
Good job! I agree with @VladimirMikulic, could you follow this suggestion?

> Screenshot_20200112_162524
> 
> To keep styling consistent space out button from the "Learn about location privacy" text.
> Something like `margin-bottom: 0.7rem`.
> Thanks.

Thanks for your help!

**Comment by VladimirMikulic** [comment]
Alright, you've resolved the conflicts. It works, just add that margin :)

**Comment by sssash18** [comment]
@VladimirMikulic @Uzay-G  I added a space between the two

**Comment by VladimirMikulic** [comment]
It should look like this. @Uzay-G your opinion on this matter?

Screenshot_20200112_170821

**Comment by Uzay-G** [comment]
Oh yeah I agree that we should lessen that gap to look more like your mockup. Nice work @VladimirMikulic

**Pull request merged**
