### PR TITLE
Added missing css files to assets.rb file

### LINKED ISSUE #7529: Missing css files in assets.rb file
While trying to find a fix for the padding problem in the dropdown menu for `_card.html.erb` file,I noticed that some files are not included in`assets.rb` such as `notes.css` and some other css files.Thus the likely padding and ui issues across the app can just be fixed by importing these.

Am I missing something here ...are these css files imported from any other place? Not really sure can you help me out

For ex in file `_new_question.html.erb` has the following code which renders the dropdown without any padding issue:-

```
.ellipsis{
  cursor: pointer;
}

.dropdown-menu li a{
  display: inline-block;
  padding-bottom: 5px;
  padding-left: 14px;
  font-size: 13px;
}

```

But the same block of code present in `notes.css` is not rendered possible because it is not compiled.  
```
#notes .ellipsis {
  cursor: pointer;
}

#notes .dropdown-menu li a{
  display: inline-block;
  padding-bottom: 5px;
  padding-left: 14px;
  font-size: 13px;
}
```

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #7529 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@jywarren @VladimirMikulic can you kindly review this? Thanks :v:

**Comment by Tlazypanda** [comment]
@VladimirMikulic have moved the files to application.css ..there's only 1 file since remaining are present already in assets.rb and application.css.Can you kindly review? Thanks :v:

**Comment by Tlazypanda** [comment]
@cesswairimu not sure how to make travis pass :sweat_smile:

**Comment by cesswairimu** [comment]
We will just restart and restart again :laughing:..sorry travis can be frustrating

**Comment by Tlazypanda** [comment]
@cesswairimu travis passed this time but codecov failed :laughing: :stuck_out_tongue_closed_eyes:

**Comment by Tlazypanda** [comment]
@cesswairimu travis still failing :cry: can you help me out? :sweat_smile:

**Comment by VladimirMikulic** [comment]
@cesswairimu The line 12 of `tag_selection` unit test fails.
https://github.com/publiclab/plots2/blob/master/test/unit/tag_selection_test.rb

In the test file, we are doing math with "times".
If not done properly, this usually results in unstable tests.

Can we rewrite this test to preserve the functionality, but without "time" hacking?

@Tlazypanda your view on this?

**Comment by Tlazypanda** [comment]
@VladimirMikulic @cesswairimu Umm..going through this found these links might be helpful ...can you check it out?  Thanks :v: 
https://www.greyblake.com/blog/2018-02-19-how-to-fix-intermittent-test-failures/
https://github.com/travisjeffery/timecop

**Comment by cesswairimu** [comment]
@Tlazypanda I have restarted travis, the test are all green now.

**Comment by jywarren** [comment]
> @cesswairimu The line 12 of `tag_selection` unit test fails.
> https://github.com/publiclab/plots2/blob/master/test/unit/tag_selection_test.rb
> 
> In the test file, we are doing math with "times".
> If not done properly, this usually results in unstable tests.
> 
> Can we rewrite this test to preserve the functionality, but without "time" hacking?

Oh wow great catch @VladimirMikulic. Would you be able to open an issue with this insight?

**Comment by jywarren** [comment]
Awesome! Thanks a lot!!!

**Comment by jywarren** [comment]
🎉

**Comment by VladimirMikulic** [comment]
@jywarren I'll open the issue and try to solve this issue once and for all!

**Pull request merged**
