### PR TITLE
Dashboard SQLException and Travis system test fail

### PR DESCRIPTION
**Pull request by keshavsethi**
An error was coming in the dashboard and system tests were also failing.
Screenshot from 2020-07-24 19-06-48
I work fine after correcting the typo
Screenshot from 2020-07-24 19-08-47

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
Just saw the system failures on travis on the recent PRs...thanks for catching this @keshavsethi and opening this so quick :tada: :tada:

**Comment by keshavsethi** [comment]
Thanks!! @cesswairimu  it is because of some chrome driver version.
```
Minitest::UnexpectedError:         Selenium::WebDriver::Error::SessionNotCreatedError: session not created: Chrome version must be between 70 and 73
          (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-1077-gcp x86_64)
```

**Comment by cesswairimu** [comment]
Which is strange we haven't changed the version since February :thinking:

**Comment by keshavsethi** [comment]
@cesswairimu @jywarren @alaxalves @icarito System Tests are failing because of the chrome driver version issue. Please check!!
Thanks!!

**Comment by cesswairimu** [comment]
From the latest travis-ci update notes it shows that Google Chrome changed to 83.0.4103.116-1..and the driver for this should be used with ChromeDriver 83.0.4103.39 or  ChromeDriver 83.0.4103.14  but none of these seem to work :thinking: Not sure where we can get the exact chrome version that we are using

**Comment by keshavsethi** [comment]
@cesswairimu @jywarren I tried a few things but still, errors are coming :thinking: Please check!!
Thanks!!

**Comment by cesswairimu** [comment]
I am going to try a brute-force from version 73 upwards see if anything works...opening on a new PR https://github.com/publiclab/plots2/pull/8197

**Comment by jywarren** [comment]
Oh gosh, this is pretty bad. Thanks for looking into this! I will check it out too to see if we can figure it out. 

In the meantime, LOTS of info and guidance on Chromedriver here: https://github.com/publiclab/plots2/issues/6095

**Comment by jywarren** [comment]
This note refers to work by @alaxalves on this which helped us mitigate the chrome version moving target... perhaps related? 

> So the latest is that @alaxalves was able to pin to a 3rd party repository of Chrome versions, at https://github.com/webnicer/chrome-downloads, in #6099. It has Chrome 78, latest updated version 4 days ago, so this seems viable...

> So we're pinned at Chrome 75 ChromeDriver 74:

**Comment by jywarren** [comment]
Was this resolved? I see @cesswairimu closed this attempt: https://github.com/publiclab/plots2/pull/8197

**Comment by jywarren** [comment]
Ah i see finally in https://github.com/publiclab/plots2/pull/8203 - thanks!

**Pull request closed without merging**
