### PR TITLE
Fix typo in html tag

### PR DESCRIPTION
**Pull request by Crisoal**
Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Crisoal** [comment]
@TildaDares can you pls review what i have done?

**Review by TildaDares — APPROVED** [review]
Thanks @Crisoal! Great job.

**Comment by Crisoal** [comment]
> Thanks @Crisoal! Great job.

I really your guidance and help in completing this task. Thank you.

**Comment by Crisoal** [comment]
Is this regarded as a contribution?

**Comment by TildaDares** [comment]
@Crisoal Yes this counts as a contribution.

**Comment by TildaDares** [comment]
@Crisoal You can close #11090 and #11092 now.

**Comment by TildaDares** [comment]
Congratulations @Crisoal 🎉

**Pull request merged**
