### PR TITLE
[WIP]Adding recent questions in question shadow

### LINKED ISSUE #5733: UI Improvements PLanning Issue : Questions Page
cc : @gautamig54 

PublicLab_mockups

#### Checklists

- [x] Create shadow questions page @CleverFool77 
- [x] first design block with some relevant information @CleverFool77 
- [x] card of text area for questions with buttons and post options @gautamig54 
- [x] featured questions cards   @CleverFool77 
- [ ] Show recent questions on some topic - use same card as used in tags section @gautamig54 

Viewable at:

http://stable.publiclab.org/shadow_question

http://publiclab.org/shadow_question

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5733  (<=== Add issue number here)

Screen Shot 2019-06-18 at 1 21 26 AM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
This is just a PR for adding the recent questions. I am working on sorting it according to the topics. Thanks!

**Comment by CleverFool77** [comment]
Cool. 
Hi @gautamig54 
The cards seems pretty wide ? Isn't it ?

**Comment by IshaGupta18** [comment]
I think this looks pretty great @gautamig54! Maybe @CleverFool77 is right here, you can reduce the width of the card a little and align it in the center, just below the 2 other cards. What do you think?

**Comment by gautamig54** [comment]
Yes, the cards look a bit wide here. I'll reduce its size. Also, @CleverFool77 there is a minor change required with the alignment of the features question card.
Screen Shot 2019-06-21 at 11 52 49 PM

**Comment by aSquare14** [comment]
@gautamig54 I think the gap between the cards and the question shadow can bee decreased a bit vertically.

**Comment by aSquare14** [comment]
@gautamig54  Any updates on this PR ?

**Comment by aSquare14** [comment]
Could you please finish this up ?

**Comment by gautamig54** [comment]
Sorry for the delay on this one. Working on it!

**Comment by aSquare14** [comment]
Hey , any updates ? :)

**Comment by gautamig54** [comment]
Hi all! Sorry for leaving this unattended. I discussed the issue here with @jywarren.
Actually here we have to display the questions as per the featured tags. Now, the featured tags are a feature on the website which has been hardcoded. Is there any specific code with decides these featured tags, like depending in number of users or wikis etc?
Here I have implemented the recent questions but sorting them according to what is a bit confusing? How are we deciding upon these tags?

**Comment by jywarren** [comment]
Actually we can use a Feature to make these stored in the database, which
will reduce codebase bloat and make it more customizable:
https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#features

What do you think?

**Comment by jywarren** [comment]
And the featured tags list on the page can be distinct from featured questions or recent questions, no? Shall we go ahead and merge this then? Thanks @gautamig54 !

**Comment by gautamig54** [comment]
Sure. We already have a feature in the current design, which has the
featured tags.

**Comment by jywarren** [comment]
Great! Ready to merge here, then?

**Comment by gautamig54** [comment]
Yes. Thanks!

**Pull request merged**
