### PR TITLE
Order by subscription fix

### PR DESCRIPTION
**Pull request by Gauravano**
If there is no current_user then also the button was shown generating the error.Also, I can make table heading links so the button will no longer be needed.What you say @jywarren .

### CODE REVIEW

**Comment by jywarren** [comment]
> Also, I can make table heading links so the button will no longer be needed

That sounds super. Please do! Is this ready for merging though? Thanks!!!

**Comment by Gauravano** [comment]
@jywarren links added in table headings and Sort button removed.Here's the preview 

subscriptionfix
Do you think tooltip should be added? Also, plz suggest if any other changes are required.Thanks.

**Comment by jywarren** [comment]
This looks great! What do you think about making additional routes that are more readable -- like, `/tags/uses` `/tags/subscribers` -- or using a GET param like `/tags?sort=subscribers` -- to make the routes more readable? 

We could merge this and do that in a separate PR, if you think that's best? I'm open to either way. Thank you, this is so great.

👍

**Comment by Gauravano** [comment]
ok @jywarren, I will open a PR soon setting new routes

**Comment by jywarren** [comment]
Awesome. Thanks!!!

**Pull request merged**
