### PR TITLE
fixed search error

### LINKED ISSUE #2287: Search bar not properly working
search-error-1
Steps to reproduce:-
1) Type something in the searchbar
2) Click on the search icon just right to the search input (should actually redirect to /search/ with the search results)
3) Shows a validation message saying "Please! Type something to search"

### LINKED ISSUE #2372: menubar search "prompt" popover does not disappear
### Please describe the problem (or idea)

The menubar search "prompt" popover sometimes doesn't go away when you type in Chrome desktop:

screen shot 2018-02-20 at 4 17 56 pm

### Please show us where to look

https://publiclab.org/ (any page, top menubar)

That line of code is here: https://github.com/publiclab/plots2/blob/313848ae70baf221ce092870090f94088040b4a6/app/views/layouts/_header.html.erb#L74

@namangupta01 i think this was a change you made? Would you mind taking a look? I also found this to be the case on Firefox iOS (although that's harder to test out)

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #2287 fixes #2372

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
@ViditChitkara That was some weird behaviour of javascript api of `setcustomvalidation` but thanks! 👍

**Comment by ViditChitkara** [comment]
Yeah, it was actually setting just a validation message but not checking if
the search box was empty or not! However, 'required' in the input tag did
the trick!! Thanks for the review :+1

On Feb 9, 2018 11:51 PM, "Naman Gupta" <notifications@github.com> wrote:

@ViditChitkara <https://github.com/viditchitkara> That was some weird
behaviour of javascript api of setcustomvalidation but thanks! 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/pull/2288#issuecomment-364515476>, or mute
the thread

**Comment by namangupta01** [comment]
@ViditChitkara can you please find the way to set custom text maybe with the use of `setCustomValidation`?

**Comment by ViditChitkara** [comment]
We could customise the text, but wouldn't increase the code complexity a bit? I think "required" is doing an excellent job by providing all the logic we require as well as default text saying "Please fill in this field".
sol-1
@namangupta01 what do you think?

**Comment by namangupta01** [comment]
@ViditChitkara it wouldn't increase the code complexity i guess all we have to do is to pass the argument in `setCustomValidation`. So we can find a way to do so?

**Comment by ViditChitkara** [comment]
Cool, I'll try to find out!!! :+1

**Comment by jywarren** [comment]
oh awesome -- didn't see this at first! Thanks! Merging now.

**Comment by ViditChitkara** [comment]
:+1:

**Pull request merged**
