### PR TITLE
Removed sidebar instance in notes/show.html.erb

### LINKED ISSUE #9014: Remove sidebars from templates
We removed the sidebar methods in the controllers here https://github.com/publiclab/plots2/issues/8803. This is a follow up to identify and remove the instances where the sidebar is being rendered...we expect some tests to fail, so this might involve some rewriting of tests

### PR DESCRIPTION
**Pull request by Manasa2850**
Fixes #9014  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Manasa2850** [comment]
@cesswairimu some of the system tests are failing but they don't seem to be related to my PR. Could you please check them out?
Also, could you please let me know if what I've fixed in the `app/views/notes/show.html.erb` is fine? Earlier that page was breaking but it should be fine now.
Thank you!

**Comment by cesswairimu** [comment]
cool, lets try to rebuild again...closing and reopening

**Comment by cesswairimu** [comment]
So that did not work failing test
```
[Screenshot]: tmp/screenshots/test_viewing_the_dashboard.png
=============[Screenshot]: tmp/screenshots/failures_test_pages_tagged_with_place_get_a_full-width_map_across_the_top_of_the_page.png
 FAIL PlaceTagsTest#test_pages_tagged_with_place_get_a_full-width_map_across_the_top_of_the_page (220.10s)
        expected to find css "div.leaflet-layer" but there were no matches
        test/system/place_tags_test.rb:10:in `block in <class:PlaceTagsTest>'

=====[Screenshot]: tmp/screenshots/test_viewing_the_settings_page.png
[Screenshot]: tmp/screenshots/test_front_page_with_navbar_search_autocomplete.png
=[Screenshot]: tmp/screenshots/test_searching_an_item_from_the_homepage.png
=[Screenshot]: tmp/screenshots/test_simple-data-grapher_powertag.png
====[Screenshot]: tmp/screenshots/test_blog.png
[Screenshot]: tmp/screenshots/failures_test_blog_page_with_location_modal.png
ERROR ScreenshotsTest#test_blog_page_with_location_modal (442.67s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css "a#tags-open"
            test/system/screenshots_test.rb:219:in `block in <class:ScreenshotsTest>'
```

**Comment by Manasa2850** [comment]
Yes @cesswairimu. I guess I haven't changed any code related to these failing tests so I wasn't really sure why that was happening :thinking:

**Comment by Manasa2850** [comment]
@cesswairimu we don't have a div named `leaflet-layer` in our codebase due to which these tests are failing. I'll fix this in a new commit.
Thanks!

**Comment by cesswairimu** [comment]
I agree its strange...taking a deeper look

**Comment by cesswairimu** [comment]
aha great catch...we do use a leaflet library on the project maybe this was a check for a div from the library?...could it be we had the lib in the sidebar :thinking:

**Comment by Manasa2850** [comment]
I'm not sure if we had `leaflet-layer` in the sidebar code because I wasn't able to find it in the previous PR made related to this :thinking: 

Also @cesswairimu I think the `Unable to find css "a#tags-open"` error was because it was hidden in `app/views/tag/_tagging.html.erb`
Could you please check if the file changes I've made are correct? I will make changes to it if required.
Thanks a lot!

**Comment by cesswairimu** [comment]
Looks great @Manasa2850 ...I will confirm with @jywarren about the removal of the sidebar on this page..looks like it will remove a lot of crucial access tools and also confirm which specific templates we want to remove the sidebar from if not. Thanks

**Comment by jywarren** [comment]
Hi @Manasa2850 thank you for this pull request! I'm afraid we had a slight miscommunication -- this use of the sidebar is actually desired, it's another sidebar that we think is unnecessary -- the "featured" sidebar, shown in the first two results on this page:

https://github.com/publiclab/plots2/search?q=sidebar%2Ffeatured

I'm so sorry this mixup happened and i should've been more helpful in composing it. Would you be willing to modify this PR to remove the other sidebar code instead of this? Thank you for your help!

**Comment by Manasa2850** [comment]
No problem at all @jywarren. I'll modify this PR to remove the featured sidebar.
Thank you!

**Pull request closed without merging**
