### PR TITLE
Improve pagination for mobile view

### LINKED ISSUE #4314: improve pagination of dashboard page for mobile view
when open https://publiclab.org/dashboard this page in mobile view then it's pagination not looking good.I think this page need to improve.
It look like this.
pub2

Thank you : )

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #4314 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Changes made:
search

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
@divyabaid16 Can we have the gif or screenshot of the changes done ?
Thanks :)

**Comment by divyabaid16** [comment]
I have updated :)

**Comment by CleverFool77** [comment]
The working in gif looks great :+1:

**Comment by gauravano** [comment]
@divyabaid16 please claim the issue first(from the next time) before raising PR. 

@jywarren for mobile view only previous and next buttons would be sufficient I guess?  If you think the same, feel free to merge this one. Thanks!

**Comment by divyabaid16** [comment]
@gauravano 
I forgot to claim this one. I will remember it next time :)

**Comment by jywarren** [comment]
This is great! Actually there are some issues with pagination in mapknitter too, did you have any interest in taking a look?

https://github.com/publiclab/mapknitter/

Thanks so much!!!

**Comment by divyabaid16** [comment]
Ya sure! I will look at them.

**Pull request merged**
