### PR TITLE
Add rubocop (resolves #1729)

### LINKED ISSUE #1729: Setup linting in the project
A lot of the code in the plots2 codebase doesn't exactly conform to a specific set of design guidelines and therefore might be difficult to read and comprehend. Also, because a chunk of the code is unlinted, it opens it up to things like trailing whitespaces which more often than not leads to noise in new PRs when smarter text editors try to auto remove them. I personally believe a good linting setup would add up to our already huge set of tests, further improving our sanity checks to make sure that the submitted code doesn't only "not break the code", the newly written code is formatted cleanly and according to our guidelines and thus in a consistent manner.

P.S. We will also be able to easily churn out a ton of easy linting FTOs.

/cc @jywarren what do you say about this?

### PR DESCRIPTION
**Pull request by ryzokuken**
@jywarren `263 files inspected, 10980 offenses detected` 😅 

It seems it was high time we fixed a few.

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, so this doesn't display any messages in the PR, but is doing that part of your plan too? Thanks!

**Comment by ryzokuken** [comment]
Not for this one. If we make the PRs fail for linting errors, we'll have to
fix all of them first. Rather, let's first bring those down to 0 and then
we'll block any PRs with linting errors.

**Comment by jywarren** [comment]
Cool; what's the goal with adding rubocop here -- is it so that we can ask
people to go in and run it, on their own local? Or is there some way that
we could have Rubocop output a listing that we could link to from a FTO
issue? Just thinking about how we can work on this efficiently!

BTW did you see we installed https://github.com/hoodiehq/first-timers-bot
-- very clever!

**Comment by jywarren** [comment]
OK, so I don't see this creating output in Travis, but I wonder if you could add some documentation on how to use this, as part of the PR. Perhaps in `/doc/LINTING.md`? Thanks!!!

**Comment by ryzokuken** [comment]
@jywarren Sure, I will!

**Comment by ryzokuken** [comment]
@jywarren Let's get this one merged.

**Comment by jywarren** [comment]
Looks great -- happy new year! 🎉 

Great to be back!

**Pull request merged**
