### PR TITLE
Replaced count with size

### PR DESCRIPTION
**Pull request by AC-BOSS**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, can you point us at the original issue for your PR? Thank you so much!!!

**Review by Tlazypanda — APPROVED** [review]
@AC-BOSS LGTM :raised_hands: Welcome to Public Lab :balloon:
 
Can you also edit the issue description to add 'fixes #8224' instead of 'fixes #0000' ? Thanks :v:

**Review by sagarpreet-chadha — APPROVED** [review]
Niceee 🎉 🎉 🎉

**Comment by jywarren** [comment]
I think we should be OK to merge this since we haven't heard back. Thank you, all!!!

**Pull request merged**
