### PR TITLE
Fixes #4422 login modal not working at /profile page

### LINKED ISSUE #4422: Login modal not working at /profile
### Please describe the problem (or idea)
The login modal is not working when clicked through the header on /profile.
> What happened just before the problem occurred? Or what problem could this idea solve?

profile login modal

### Please show us where to look

https://publiclab.org/profile

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by IshaGupta18**
Fixes #4422 #4299  

On clicking on login button in navbar in /profile page (this page can be viewd to logged out user if he logged out from /profile page only)

image

### CODE REVIEW

**Comment by IshaGupta18** [comment]
Also, this will close #4299 

image

**Comment by gauravano** [comment]
Hey, have you checked access token modal? I think it's alignment is little disrupted, could you solve that in this PR? Thanks!

**Comment by IshaGupta18** [comment]
Yes I saw, let me see what I can do!

**Comment by IshaGupta18** [comment]
@gauravano what I am seeing here is, if I try to re position the access token modal, all other modals get shifted from there position. I will try to find a fix, but I believe that the other modals are dependent on this _token file, because that's why the opacity could be changed for all of them. You can merge this PR if you feel it's right the way it is now. Thanks a lot.

**Comment by IshaGupta18** [comment]
Hey @gauravano I think I figure it out, does this look good?
image

**Comment by IshaGupta18** [comment]
Hey @gauravano is it ready to be merged? Thanks a lot.

**Comment by gauravano** [comment]
Hi @IshaGupta18 I tested it locally and in mobile view access-token modal is not shown properly

mobview_modal

We can also handle this in a separate issue if you want. What do you think? 

Thanks!

**Comment by IshaGupta18** [comment]
Yes I see the issue, I am so sorry it didn't work out like the way it should have... Can I take one more shot at it, otherwise I would remove my changes for this part and push it, so that you can merge this PR and open a new one for the other issue, but I do want to try again once on it... Will that be okay @gauravano ? I am sorry again.

**Comment by gauravano** [comment]
Hi @IshaGupta18, sure take your time and no need to be sorry, you did a great job :+1: . Thanks!

**Comment by IshaGupta18** [comment]
@gauravano I think you should merge this one, we'll take up the access token modal issue as a separate issue! Thanks a lot for your patience and I am sorry I wasn't able to do it completely.

**Comment by gauravano** [comment]
Both modals after local testing:
access_token_modal

**Comment by gauravano** [comment]
Thanks @IshaGupta18 for amazing work :tada: :balloon: !

**Comment by gauravano** [comment]
It was that same fix which you committed earlier. Let's keep it for now. Thanks!

**Pull request merged**
