### PR TITLE
Replace blog link with stories from Read Stories button (Fixes issue …

### PR DESCRIPTION
**Pull request by mirzabob**
Changed blog link with stories.(#2454 )

### CODE REVIEW

**Comment by mirzabob** [comment]
@amitsin6h Did what you said but got a wrong tick for issue#2454. Thanks for the suggestion.

**Comment by amitsin6h** [comment]
@mirzabob are you able to run plots2 project locally ?? and why are you making PR from master branch create a separate branch whenever you work on any issues always remember keep your master branch clean.

**Comment by mirzabob** [comment]
Ok got it.

**Comment by jywarren** [comment]
Hi! I was thinking, we actually do want a link to the blog on the front page, but @amitsin6h is right that this link is unclear. Can we make the change to the button text, instead of to the link itself? 

What about making the button say `Read stories on the blog`?

**Comment by jywarren** [comment]
Thanks for your help with this!!!

**Comment by amitsin6h** [comment]
@jywarren sure I will ask @mirzabob to make changes to the button rather than the link.

@jywarren can you please look to https://github.com/publiclab/plots2/pull/2431

**Comment by Gauravano** [comment]
retriggering build

**Comment by amitsin6h** [comment]
@mirzabob don't change the link as asked by @jywarren just make button say  `Read blog stories` .
Once done, We will merge it :+1:

**Comment by jywarren** [comment]
Moving over to #2484 -- thank you!

**Pull request closed without merging**
