### PR TITLE
Update PR#7076 --feature-request.md

### PR DESCRIPTION
**Pull request by scottwedge**
Change $REPO to "plots2" as requested in PR #7076.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by anthony-zhou** [comment]
@scottwedge Thanks for contributing! Your change looks good. Just make sure you put the keywords "Fixes #7076" somewhere in your pull request description so that the issue gets closed automatically when this PR is merged.

**Comment by scottwedge** [comment]
Anthony, Thanks for the quick feedback.

I included "PR#7076" in the title and "PR #7076." in the Description but
left " Fixes #0000" as it was -  I did not understand that it should have
been changed but now I understand. I will follow your convention in the
future.

I also found another grammar mistake involving this sentence and will write
that PR and fix it later today.

Scott


On Wed, Jan 1, 2020 at 4:02 PM anthony-zhou <notifications@github.com>
wrote:
>
> @scottwedge Thanks for contributing! Your change looks good. Just make
sure you put the keywords "Fixes #7076" somewhere in your pull request
description so that the issue gets closed automatically when this PR is
merged.

**Comment by anthony-zhou** [comment]
@scottwedge In case you are making more changes to this PR, you can always edit this PR's initial description, and any commits you push to this branch will automatically appear here on this existing pull request. If you're working on a separate issue then it does make sense to open a new PR.

**Comment by cesswairimu** [comment]
Thank you for working on this @scottwedge and welcome to PublicLab :balloon: 
Thanks @ananyaarun and @anthony-zhou for the reviews :heart:

**Pull request merged**
