### PR TITLE
Update _title_suggestion.html.erb

### PR DESCRIPTION
**Pull request by rclarent**
Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @rclarent, could you add the issue number? Thanks!

**Comment by TildaDares** [comment]
@DalilaBA Some tests are failing because of the `translation` method. I think we need to change `translation` to `t`. That should fix it
```
Progress: |==ERROR CommentControllerTest#test_render_propose_title_template_when_author_is_logged_in (13.26s)
Minitest::UnexpectedError:         ActionView::Template::Error: undefined local variable or method `current_user' for #<#<Class:0x0000559cd250cca0>:0x0000559cd2512c40>
            app/helpers/application_helper.rb:163:in `translation'
            app/views/notes/_title_suggestion.html.erb:4:in `_app_views_notes__title_suggestion_html_erb__3515358254616513433_47066015904960'
            app/helpers/application_helper.rb:125:in `block in title_suggestion'
            app/helpers/application_helper.rb:121:in `gsub'
            app/helpers/application_helper.rb:121:in `title_suggestion'
            test/functional/comment_controller_test.rb:352:in `block in <class:CommentControllerTest>'
```

**Comment by DalilaBA** [comment]
@TildaDares why whats the difference?? I mean okey I will change it I just wana know what's not working

**Comment by TildaDares** [comment]
@DalilaBA I'm not familiar with this particular bug but this issue should be able to explain https://github.com/publiclab/plots2/issues/7798

**Comment by TildaDares** [comment]
Hi @rclarent, we appreciate you taking the time to work on this PR but this issue needs a little more work so we'll have to close this PR for now. In the meantime, there's an open issue in #10465 you can work on. Leave a comment there and I'll assign you. Thanks!

**Pull request closed without merging**
