### PR TITLE
Fix "Show 0 more" on inline people lists

### LINKED ISSUE #2151: Fix "Show 0 more" on inline people lists
### Please describe the problem (or idea)
Show 0 more is present in the people's list
> What happened just before the problem occurred? Or what problem could this idea solve?
If there is no more stuff, the text should not appear

> What did you expect to see that you didn't?

image

### How to Solve:
You can check out @kevinzluo's work in https://github.com/publiclab/plots2/pull/3980 for solving this. 

The file which would require changes will be https://github.com/publiclab/plots2/blob/master/app/views/grids/_people.html.erb

### Please show us where to look
https://publiclab.org/w/power-tags#Inline+power+tags

### PR DESCRIPTION
**Pull request by vansjyo**
Fixes #2151 
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by gauravano** [comment]
hey @vansjyo, I tried your PR but the show more is just expanding the list but not shrinking it. You can refer to https://github.com/publiclab/plots2/pull/3980, here the similar fix is done.

**Comment by vansjyo** [comment]
@gauravano Can you tell me how I can reproduce it in my local. As in get such a list to reproduce.

**Comment by gauravano** [comment]
You can get the list of people by using power tag [people:organizer] like shown in the image https://github.com/publiclab/plots2/issues/2151#issue-292186533. The list will show all the users which have organizer tag on their profile, so you need to add this tag to their profile by signing-in.
Thanks!

**Comment by SidharthBansal** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by vansjyo** [comment]
@SidharthBansal hey, I was actually not able to reproduce it on my local.

**Comment by SidharthBansal** [comment]
Yeah its tough to replicate. Please see Jonathan's PR. May be that will help you.

**Comment by jywarren** [comment]
Hi, it's been a while -- perhaps someone else can give this a try! Thank you!

**Pull request closed without merging**
