### PR TITLE
add child page link to sidebar

### LINKED ISSUE #3566: List number of "sub-pages" with link in sidebar
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

Pages like https://publiclab.org/wiki/contributing-to-public-lab-software have a power tag that says `parent:developers` (https://publiclab.org/wiki/power-tags) which gives them a nice breadcrumb link leading them back to the `developers` page at https://publiclab.org/developers:

image

We should have a link leading to child pages. You can view child pages like this:

https://publiclab.org/wiki/tag/parent:developers

So, the link should just be, in ruby:

```ruby
<% subpage_count = Tag.find_pages("parent:#{@node.slug}", 100).count %>
<% if subpage_count > 0 %>
  <a href="/wiki/tag/parent:<%= @node.slug %>"><%= subpage_count %> sub-pages</a>
<% end %>
```

Note that we're setting `limit` to 100... we can think about this later because there are definitely no pages with anywhere near 100 sub-pages. 

This could go right above these lines: 

https://github.com/publiclab/plots2/blob/2898e6380677386c62c3e673cd381d4d2319d33e/app/views/sidebar/_related.html.erb#L53-L58

### PR DESCRIPTION
**Pull request by wgoh**
Fixes #3566

Hi @publiclab/reviewers, it's my first time contributing to this project. Let me know if I have missed anything out. Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
You should be able to mark some wiki pages as "children" using the `parent:_____` tag, and see this feature working locally on the parent page!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by wgoh** [comment]
@sagarpreet-chadha @jywarren hi guys sorry I have been really busy previously.

here is the error when I tried `yarn install`.
screen shot 2018-10-28 at 2 44 47 pm

here is a screenshot when I tried `bundle exec passenger start`.
screen shot 2018-10-28 at 2 41 34 pm

pls advise, thanks!

**Comment by jywarren** [comment]
Hmm, can you post your Yarn error in text as a new issue? I'd like to try
to get others' take on it. Searching for that specific error text may also
help!

**Comment by jywarren** [comment]
Just added a little formatting... should pass and then we can merge this! I'd love to help you resolve the yarn issue, however -- if you have a moment to post your full yarn error output that'd be great. In the meantime we're happy to take this PR as I tested it locally!

**Pull request merged**
