### PR TITLE
Create a text note to appear next to username for first time posters only.

### PR DESCRIPTION
**Pull request by robotscissors**
Fixes issue #2722 

I created a few methods for simplicity that will check the author or current user and see how many postings they have done. If it is only one, they will get the status [new contributor] next to their username.

def new_contributor
def new_author_contributor

screen shot 2018-05-22 at 9 08 47 pm

screen shot 2018-05-22 at 9 11 51 pm

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks super. You might also use the `label` style, with `<span class="label label-success"></span>` -- that'll make it green and kind of in a pill -- like `New Contributor` -- using Bootstrap! https://getbootstrap.com/docs/3.3/components/

**Comment by robotscissors** [comment]
I submitted a PR, but I would be happy to change it. It's good practice!!

**Comment by jywarren** [comment]
That would be great, thank you! It'll look super good. :-)

**Comment by robotscissors** [comment]
@jywarren I have updated the PR for your review and added a screen shot as well.

Christopher

screen shot 2018-05-23 at 8 35 56 pm

**Comment by jywarren** [comment]
Looks super! I think we can drop the square brackets and that'll be it!
Thanks!!!

**Comment by robotscissors** [comment]
@jywarren Sorry for the trouble. I am not sure why the PR had the .tags in it. I have since uploaded it without the .tags (not included them in the commit).

Any feedback is appreciated.

**Comment by robotscissors** [comment]
This is all great info and I appreciate you taking the time. Let me make these changes and recommit.

**Comment by jywarren** [comment]
We're tracking some kind of issue with the test runner - not related to your work! Thanks for your patience!

**Comment by jywarren** [comment]
Resolved the upstream issues and we are all good! Congrats and thanks so much! We'd love to work more with you if you're interested :-)

**Pull request merged**
