### PR TITLE
Update_comment_moderate.html.erb

### PR DESCRIPTION
**Pull request by saivoleti17**
Changed function name 't' to 'translation'

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @saivoleti17, could you please add the issue number on the description. Thanks

**Comment by SidharthBansal** [comment]
@nstjean did you see the localhost before approving?

**Comment by nstjean** [comment]
I do not remember, so I fetched and checked. Here you go!

FireShot Capture 127 - 🎈 Public Lab_ Dashboard - localhost

**Comment by SidharthBansal** [comment]
So is it good to merge?

**Comment by nstjean** [comment]
I don't know why that test is failing? Does that need to be investigated? Or the test restarted?

**Comment by SidharthBansal** [comment]
Let's restart the test first.

**Comment by SidharthBansal** [comment]
@jywarren i think we had same error in some other prs. Can you please recall the fix?
Thanks

**Comment by jywarren** [comment]
Could we try rebasing this to see if it passes?

**Comment by nstjean** [comment]
Closing this as it's been a long while.

**Pull request closed without merging**
