### PR TITLE
test revision spam flows

### PR DESCRIPTION
**Pull request by jywarren**
This should fail for the same reason as #2647 -- spamming the sole revision of a wiki page! 

Looking for, to resolve this:

redirect to the Revisions view with a notice that: 

`You can't delete the last remaining revision of a page; try deleting the wiki page itself (if you're an admin) or contacting moderators@publiclab.org for assistance.`

### CODE REVIEW

**Comment by jywarren** [comment]
Awesome, I added a test for the `flash[:warning]` -- let's see!

**Comment by jywarren** [comment]
Wow, our revision spam tests are not great, i.e. had been non-existent! We should build them out.

**Comment by Gauravano** [comment]
I guess it's complete now :smile: !!! What do you think @jywarren ?

**Comment by sagarpreet-chadha** [comment]
I think we cannot used `assert_select` in integration tests or can we ?
What do you think @Gauravano ?

@jywarren ... All tests pass if we remove assert_select statement .

**Comment by Gauravano** [comment]
hi @sagarpreet-chadha, we can use assert_select in integration tests, actually in our codebase we are using. hmm, ok I am gonna try one more time with assert_select.

**Comment by Souravirus** [comment]
@Gauravano assert_select gives some problems in rails 4.2. So, what I have used during rails 4.2 update is that I css_selected the element and saw what was the number of elements by storing it in a variable. 
Something like this 
selector = css_select 'div.note'
 assert_equal selector.size, 15
So, here just print the selector.size once to see the number of elements and then use assert_equal. I guess this is helpful!!

**Comment by Souravirus** [comment]
In your guess I guess this will not work just remove the class name alert warning and test with alert. That will work as ruby tests will find assert with the sentence you want to find. Something like this:

`assert_select ".alert" , "× You can't delete the last remaining revision of a page; try deleting the wiki page itself (if you're an admin) or contacting moderators@publiclab.org for assistance."`

This would work.

**Comment by sagarpreet-chadha** [comment]
Also one thing ...as that node does not have any tag , so there would be two alerts on the page after we delete that node , hence `assert_select` will select two alerts (no tag alert and only 1 revision alert) .
I wonder if we have to loop over this selection and check for both the alerts , but we can open another PR for this .
What do you think @Gauravano , @Souravirus ?

**Comment by Souravirus** [comment]
Did that work what I said above?

**Comment by jywarren** [comment]
I think we have to keep the alert-warning class because it's a specific yellow Bootstrap style. I think for now we can skip the assert_select for now although I appreciate the idea! 

Wow, a real collaboration here :-)

**Comment by jywarren** [comment]
I'm going to merge especially because we should do our best to prevent another error from the original issue. 

Thanks everyone!!!! Great work. :raised_hands:

**Pull request merged**
