### PR TITLE
Delete lines 6-8 on package.json related to Bower

### LINKED ISSUE #5037: Remove Postinstall Script
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We are moving away from using Bower to manage our application dependencies, as it has been deprecated. We would like to remove a postinstall script in our `package.json` file that is still creating symlinks to bower components. 

## Solution

This one is simple - lets remove the following lines: 

https://github.com/publiclab/plots2/blob/205653b9e10eed21716f3f61281bc9c4574933f2/package.json#L6-L8

What to change them to:

Nothing. We may eventually add a new postinstall script but for now we are just removing it altogether. 

Thanks!!

## Steps to Fix
 
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by emestabillo**
Fixes #5037  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by emestabillo** [comment]
Hi @gauravano @sashadev-sky! Kindly review and let me know if I need to incorporate changes. Thank you!

**Comment by siaw23** [comment]
Hi @emestabillo... I'm wondering why you're removing this...?

**Comment by gauravano** [comment]
Hi @siaw23, check out https://github.com/publiclab/plots2/issues/5037. Thoughts?

**Comment by sashadev-sky** [comment]
@siaw23 via #4849 we're removing it because we're no longer using bower in our setup and it creates symlinks to bower components

**Comment by sashadev-sky** [comment]
@emestabillo hi, this looks good to me! You are receiving a travis error because our travis testing setup still invokes a postinstall script and now there is no longer one. To fix this, you will need to remove  `yarn postinstall` from a few additional lines:

https://github.com/publiclab/plots2/blob/6d10661b2fda1720e6dee0316124097ce64354a5/install_cloudnine.sh#L11

https://github.com/publiclab/plots2/blob/6d10661b2fda1720e6dee0316124097ce64354a5/Dockerfile#L39

https://github.com/publiclab/plots2/blob/6d10661b2fda1720e6dee0316124097ce64354a5/.travis.yml#L25

Then you should be all set! Let me know if you have any questions.

**Comment by sashadev-sky** [comment]
mentioning @Souravirus because he works with Docker configs

**Comment by emestabillo** [comment]
Hi @sashadev-sky, I made the changes requested but still getting a build error. Please advise. Thank you!!

**Comment by Souravirus** [comment]
Hi @emestabillo, the error is coming as you have removed the whole lines. You just had to remove the postinstall command from those commands. You have to keep those lines though. 
Thank you!!

**Comment by emestabillo** [comment]
> Hi @emestabillo, the error is coming as you have removed the whole lines. You just had to remove the postinstall command from those commands. You have to keep those lines though.
> Thank you!!

Thank you for the tip @Souravirus !! 🎉

**Comment by Souravirus** [comment]
No problem @emestabillo. Just wanted to say try to rebase the commits than merging it, because the changes which are done by others are also mixed up with yours. 
Thank you!!

**Comment by emestabillo** [comment]
Hi @Souravirus , I hope I did this correctly. I'm a newbie with a complicated rebase. Thank you once again!

**Comment by Souravirus** [comment]
Wow nice work @emestabillo.

**Comment by sashadev-sky** [comment]
@Souravirus could you leave a review please so we can ping jeff to get it merged next

**Comment by Souravirus** [comment]
Hi @emestabillo, can you post these changes to unstable? Just to make sure everything's OK? 
Thank you!!

**Comment by emestabillo** [comment]
Hi @Souravirus , just to clarify: did you mean change the branch where it will be merged from ‘master’ to ‘unstable’ correct?

**Comment by gauravano** [comment]
Hi @emestabillo, actually we have unstable.publiclab.org where we test our work. It builds from `unstable` branch. @Souravirus actually only some people have push access to `unstable` so I am pushing this PR to `unstable` for testing. Thanks!

**Comment by gauravano** [comment]
Build completed smoothly :+1: . Great work @emestabillo. Thanks everyone :100: !

**Comment by Souravirus** [comment]
Thanks @gauravano for your help

**Comment by emestabillo** [comment]
Thank you everyone @gauravano @Souravirus @sashadev-sky!!

**Comment by jywarren** [comment]
Great work!!! And thanks everyone for a good collaboration! 🎉 🙌

**Pull request merged**
