### PR TITLE
fixed table headers

### LINKED ISSUE #7298: Fixed table headers
I feel that tables will be much more interactive if table headers are kind of fixed at the top of table as it sometimes become difficult to see which column defines what
Screenshot from 2020-01-19 04-34-30
here we can't differentiate which 0 is for like and which is for comments 
link [https://publiclab.org/newsletter](url)

### PR DESCRIPTION
**Pull request by keshavsethi**
Fixes #7298 (<=== Add issue number here)
I am not able to find html.erb file of Newsletter where table is there, can anybody suggest me how to edit that table.
But I made Headers of other table fixed as shown
Screenshot from 2020-01-23 16-37-37
This is from https://publiclab.org/wiki/projects

 
Thanks!

### CODE REVIEW

**Comment by nstjean** [comment]
This looks good! I will see if I can find where the newsletter template is for you.

**Comment by nstjean** [comment]
Taking a look at the Newsletter page... I think it's just a wiki or a note with a list of notes. So I suspect this PR will correct it!

**Comment by keshavsethi** [comment]
@nstjean thanks

**Comment by keshavsethi** [comment]
@nstjean @SidharthBansal can you merge this.
Thanks

**Comment by keshavsethi** [comment]
@nstjean @SidharthBansal can we merge this?

**Comment by nstjean** [comment]
@keshavsethi I don't have merging rights. Maybe @cesswairimu can?

**Comment by cesswairimu** [comment]
This is fantastic...thanks @nstjean and @keshavsethi

**Comment by cesswairimu** [comment]
Thanks @vinitshahdeo too

**Pull request merged**
