### PR TITLE
Email Digest follow up changes

### LINKED ISSUE #4732: Email digest follow-up changes list
Our daily email digest is now working! Now we have a few follow ups to do. 

* [x] Images seem broken
* [x] dates on posts don't seem right (https://github.com/publiclab/plots2/pull/4851)
* [x] daily digest is labeled weekly (https://github.com/publiclab/plots2/issues/4822) (solved in https://github.com/publiclab/plots2/pull/4955)
* [x] some page width oddities on a smartphone
* [x] images not loading https://github.com/publiclab/plots2/issues/5230
* [x] item content is in Markdown and needs to be parsed to HTML
* [x] looks like maybe updated wiki pages are included? For now let's just show notes (https://github.com/publiclab/plots2/pull/5568)
* [x] are we sure the same posts aren't being sent out multiple times? #5907
* [x] adding today's date to the heading title of the digest email https://github.com/publiclab/plots2/pull/5331/

Overall this is very exciting!

### PR DESCRIPTION
**Pull request by arungoel123456**
Fixes #4732 
A new pr for why date are not appearing right in E-mails
@jywarren 
Thanks!

### CODE REVIEW

**Comment by arungoel123456** [comment]
@jywarren  please check

**Comment by shubhscoder** [comment]
@arungoel123456 can you please add a screenshot of the corresponding view? Thank you so much !

**Comment by shubhscoder** [comment]
Also one more suggestion, when you make a PR please make sure to have those defaults checks, its very easy for reviewers to guess the status of the pr. Thank you!

**Comment by jywarren** [comment]
Hi! I'm going to merge this as it seems simple enough. But please try to help us review PRs -- screenshots are really helpful! Thank you!!!

**Pull request merged**
