### PR TITLE
All content search results bug

### PR DESCRIPTION
**Pull request by cesswairimu**
Quick fix for #4070  
As I figure out a better fix for this.

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
search
Tested it in unstable :point_up:

**Comment by cesswairimu** [comment]
@publiclab/reviewers kindly review this

**Comment by cesswairimu** [comment]
@jywarren this was a quick fix for the all content bug before I get a better fix for this. please take a look. Thanks

**Comment by jywarren** [comment]
OK! Just be sure to open a new issue for the follow-up. Thank you!!!!

**Pull request merged**
