### PR TITLE
Modified functional scope to block scope in javascript

### PR DESCRIPTION
**Pull request by Josephsanya**
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @Josephsanya, can you add a link to the issue? 

> One thing that can help to get started is to make sure you've included a link back to the original issue you're solving, in the
> format fixes #0000 (for example)

**Comment by Josephsanya** [comment]
Hello @TildaDares , I didn't fix it from an issue. It was just some improvements I made while going through the code.

**Comment by TildaDares** [comment]
Hi @Josephsanya, we prefer to create issues first so that other contributors don't try to solve the same issues. It also gives the maintainers time to review the issue before you open a PR for it.

**Comment by TildaDares** [comment]
For example, it looks like @ijayhub has opened a PR for one of the files you've added in this PR #11524.

**Pull request closed without merging**
