### PR TITLE
Menu icon wrapping

### LINKED ISSUE #4502: Menu width issues due to new icons
I think we need to hide the icon in full width views, so it shows /either/ text or icon - as we're seeing some wrapping issues at certain page widths. Related to #4199 -- thanks! Any help appreciated!

screen shot 2019-01-02 at 1 20 26 pm

### PR DESCRIPTION
**Pull request by Chrisyee22**
Fixes #4502 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

screen shot 2019-01-04 at 2 07 53 am

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, would you mind sharing a gif? I am not sure I'm following here but
perhaps we still need it to be in horizontal form at that width.

Thank you for your help!

**Comment by Chrisyee22** [comment]
Yeah I can set it so that the full menu is visible at a horizontal width.

**Comment by Chrisyee22** [comment]
Did my last PR show up??

**Comment by Chrisyee22** [comment]
I see what you mean with the two icons. I will have a look at that. For the only wanting to see icons, are you referring to the home and  profile icons?

**Comment by gauravano** [comment]
Although, we can show icons only for all the nav items on small screen but let's try icon-only look on profile and home only for small screen. Thanks!

cc @jywarren you want to add anything? Thanks!

**Comment by gauravano** [comment]
@Chrisyee22 you can also refer to @jywarren's comment at #4690. Thanks!

**Pull request closed without merging**
