### PR TITLE
Issue#407 : fix file field spreading in User#edit

### PR DESCRIPTION
**Pull request by ujithaperera**
issue #407

### CODE REVIEW

**Comment by ujithaperera** [comment]
@jywarren All the test are passed !

**Comment by jywarren** [comment]
Hmm, great - have you run tests on this code? Thanks!

**Comment by jywarren** [comment]
Ah excellent. Wow, did you post just before I asked?

I'm working on getting this merged first then will ask you to rebase: https://github.com/publiclab/plots2/pull/415

Can you name this issue a bit more descriptively?

Thanks, eager to pull it in! Looks like a great fix and tidier code.

**Comment by ujithaperera** [comment]
yeah sure. I will rename.

**Comment by jywarren** [comment]
Tests passing; checking the profile edit page by hand too...

**Comment by jywarren** [comment]
Hmm, the layout is a bit odd at 875px wide. I'm making some additional layout changes on top of yours, and merging. Thanks!

**Comment by ujithaperera** [comment]
OK. Thanks for reviewing. :)

**Pull request merged**
