### PR TITLE
Set sql_mode for MySQL version in Gitpod

### LINKED ISSUE #8177: Duplicate records due to .group() changes for gitpod mysql fixes
I'm concerned that the expansion of `.group()` calls in https://github.com/publiclab/plots2/pull/8152 has created some incorrect outcomes. 

Responding to errors such as:

> Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'plots.node.nid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by: SELECT  node.nid, node.status, term_data.*, community_tags.* FROM `term_data` INNER JOIN `community_tags` ON `community_tags`.`tid` = `term_data`.`tid` INNER JOIN `community_tags` `node_tags_term_data_join` ON `node_tags_term_data_join`.`tid` = `term_data`.`tid` INNER JOIN `node` ON `node`.`nid` = `node_tags_term_data_join`.`nid` WHERE (node.status = 1) AND (community_tags.date > 1592278988) AND (name NOT LIKE '%:%') GROUP BY `term_data`.`name` ORDER BY count DESC LIMIT 24 OFFSET 0

we expanded the `.group()` terms by a lot: 

https://github.com/publiclab/plots2/pull/8152/files#diff-4e05ad0d64e6100656b63ad1e78f32c5R141

When doing this in #8048 i realized that doing something similar there (`.group('term_data.name, node.nid, term_data.tid, community_tags.nid, community_tags.uid, 
community_tags.date, community_tags.created_at, community_tags.updated_at')` in each instance of `.group()` in `tag_controller.rb`) caused tags to show up multiple times (duh!):

image

### PR DESCRIPTION
**Pull request by icarito**
Fixes #8177  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Just checked in case, but sorry to say it's still showing:

```
Showing /workspace/plots2/app/views/tag/_topicCard.html.erb where line #4 raised:

Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'plots.node.nid'
```

For `/tags` route. Thanks for working on this, though, Sebastian!

**Comment by icarito** [comment]
It's interesting. I tried changing the global sql_mode in the mysql console, and it still failed. Until I stopped and restarted passenger...

**Comment by icarito** [comment]
So it seems the sql_mode needs to be set _before_. So I tried with https://github.com/publiclab/plots2/pull/8281 to alter the docker container for the mysql database and include our customized my.cnf. It's currently builiding.

**Comment by jywarren** [comment]
Trying a new approach in https://github.com/publiclab/plots2/pull/8856 based on success in #8793 !

**Pull request closed without merging**
