### PR TITLE
changed tools_places.html.erb

### PR DESCRIPTION
**Pull request by Kirti2502**
Changed  plots2/app/views/notes/tools_places.html.erb

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@Kirti2502 can you link the issue which this pr is solving? Thanks :v:

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Comment by jywarren** [comment]
AH, found this is linked to #7449 by searching @Kirti2502's username!

**Comment by jywarren** [comment]
Great!!! Let's merge! Thanks a ton!!!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Thanks again!!!!

**Pull request merged**
