### PR TITLE
optimize people api in search_service.rb

### PR DESCRIPTION
**Pull request by jywarren**
Re: https://github.com/publiclab/plots2/issues/7556

...i hope this still works and is faster???

### CODE REVIEW

**Comment by SidharthBansal** [comment]
I think it is faster than previous. Lets see.

**Comment by jywarren** [comment]
Oops:

```
Minitest::UnexpectedError:         ActiveRecord::StatementInvalid: Mysql2::Error: Column 'value' in where clause is ambiguous: SELECT  DISTINCT `rusers`.* FROM `rusers` INNER JOIN `user_tags` ON `user_tags`.`uid` = `rusers`.`id` INNER JOIN user_tags AS lontags ON lontags.uid = rusers.id WHERE (rusers.status <> 0) AND (value LIKE 'lat%') AND (REPLACE(value, "lat:", "") BETWEEN 0.0 AND 31.0) AND (lontags.value LIKE 'lon%') AND (REPLACE(lontags.value, "lon:", "") BETWEEN 0.0 AND 40.0) LIMIT 5
```

**Comment by jywarren** [comment]
Uh oh, something different! 

`Minitest::UnexpectedError:         ActiveRecord::StatementInvalid: Mysql2::Error: This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery': SELECT  `rusers`.* FROM `rusers` INNER JOIN `user_tags` ON `user_tags`.`uid` = `rusers`.`id` WHERE (rusers.status <> 0) AND (user_tags.value = 'spectrometer') AND (`rusers`.`id`) IN (SELECT  DISTINCT rusers.id FROM `rusers` INNER JOIN `user_tags` ON `user_tags`.`uid` = `rusers`.`id` INNER JOIN user_tags AS lontags ON lontags.uid = rusers.id WHERE (rusers.status <> 0) AND (user_tags.value LIKE 'lat%') AND (REPLACE(user_tags.value, "lat:", "") BETWEEN 0.0 AND 31.0) AND (lontags.value LIKE 'lon%') AND (REPLACE(lontags.value, "lon:", "") BETWEEN 0.0 AND 40.0) LIMIT 5) LIMIT 5`

**Comment by jywarren** [comment]
I removed the first `.limit(limit)` -- less efficient but since it has to go in a subquery, yeah...

**Pull request merged**
