### PR TITLE
wiki controller file (If wiki page doesn't exist)

### PR DESCRIPTION
**Pull request by nataliyah123**
@Gauravano .please review the PR . I have made the changes you asked in 
app/controllers/wiki_controller.rb. Lines #67 -#73.

Thanks!
#3027

### CODE REVIEW

**Comment by nataliyah123** [comment]
@Gauravano .should i close the pull the request , since all the tests are cleared

**Comment by Gauravano** [comment]
hi, @nataliyah123 actually all tests have failed, as you can see the message on the page in Red. The first step was to change the code. Now, we need to fix the test. Although, I was going to fix the tests but @CoderJolly has also shown interest in solving this issue so for tests I have made an issue for him. Hopefully, he will commit to this PR soon. Thanks!

**Comment by nataliyah123** [comment]
When i wrote cleared , i didn't mean my tests were cleared . I was referencing the pr #3036 and #3056 , as they were referenced on my page and the pr was closed , #3036 is the same issue as was mine .

**Comment by nataliyah123** [comment]
@jywarren hi, really happy to help

**Comment by Gauravano** [comment]
Hi @nataliyah123 , your part is done, the other part of this issue is assigned to @CoderJolly as he also wants to help, he'll push the commit shortly and after that PR will be merged.
We would love to have your help on other issues, so if you are looking for a new task, you can check out here https://publiclab.github.io/community-toolbox/#r=all . Thanks :smiley: !

**Comment by Gauravano** [comment]
hi @jywarren please have a final review!

**Comment by jywarren** [comment]
Hmm, it's saying:

> Avoid too many return statements within this method. 

On line 60 something... Do you think we can tweak that to improve a little? 

Thanks everyone for collaborating on this! Very exciting. 🙌🏼

**Comment by Gauravano** [comment]
No @jywarren that `return` is required as we are redirecting in line 59 to tag page.

**Comment by jywarren** [comment]
Fantastic work!

**Pull request merged**
