### PR TITLE
Added pagy to user tags

### LINKED ISSUE #8426: Migrate to pagy
**Please describe the desired behavior.**
Currently we are using will_paginate gem for pagination but pagy offers better performance and saves memory.  
Follow up to #8326 

https://ddnexus.github.io/pagy/migration-guide
https://github.com/ddnexus/pagy

Implemented routes

**wiki**
- [x] stale
- [x] index
- [x] revisions
- [x] author

**tag**
- [x] blog
- [x] show

**notes**
- [x] places
- [x] author

### PR DESCRIPTION
**Pull request by stacytonui**
Fixes #8426 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by stacytonui** [comment]
Hello @cesswairimu I found another paginate usage in user tags. Also, I need help in understanding the failed test. Thankyou

**Comment by cesswairimu** [comment]
Lets try and restart @stacytonui

**Comment by RuthNjeri** [comment]
Hi @stacytonui the [build error](https://travis-ci.com/github/publiclab/plots2/jobs/402403529) is related to the pagination changes.. where `pagy` is trying to paginate an array collection..for example
```
      @pagy, @user_tags = pagy(UserTag
        .select('value')
        .where("value LIKE :keyword", keyword: "%#{keyword}%")
        .group(:value)
        .order('value ASC')
        .count('value').to_a, items: 24)
```
When I tried running your changes on the Gitpod, I encountered the same thing...
Screenshot 2020-10-20 at 16 05 05

I looked at the [documentation](https://ddnexus.github.io/pagy/extras/array.html) and `pagy` uses a different method to paginate an array collection..
Screenshot 2020-10-20 at 16 23 30

I made those changes on your files on Gitpod and the error I encountered was no longer there
```
  @pagy, @user_tags = pagy_array(UserTag
        .select('value')
        .where("value LIKE :keyword", keyword: "%#{keyword}%")
        .group(:value)
        .order('value ASC')
        .count('value').to_a, items: 24)
    elsif @toggle == "value"
      @pagy, @user_tags = pagy_array(UserTag.group(:value)
        .select('value')
        .order('value ASC')
        .count('value').to_a, items: 24)
    else # @toggle == "uses"
      @pagy, @user_tags = pagy_array(UserTag.group(:value)
        .select('value')
        .order('count_value DESC')
        .count('value').to_a, items: 24)
    end
```

Screenshot 2020-10-20 at 16 19 52

Note that `require 'pagy/extras/array'` has already been required in the pagy.rb file, all you need to do is change the methods from `pagy` to `pagy_array`

Once you do that the build will stop failing 🎉

**Comment by stacytonui** [comment]
Wow @RuthNjeri such a lifesaver!..Thank you so much

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Wow, tremendous!  A tough set of changes and you got it passing the tests! 

Many thanks also to @RuthNjeri for the deep research here. Great work both of you!

**Comment by jywarren** [comment]
Congrats!!!

**Comment by KarenEfereyan** [comment]
Nice one @stacytonui @RuthNjeri

**Pull request merged**
