### PR TITLE
Added Github button for OAuth login

### LINKED ISSUE #2975: Github button for OAuth login
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

**Introduce font awesome icons for github provider to multiple pages.** 

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Insert**  font-awesome icons into following four files and link them to https://publiclab.org/auth/github. Please add the icons horizontally. They should appear after google icons, in the format:

`<a href="/auth/github" id="connect-github"><span class="btn btn-default"><i class="fa fa-github" style="font-size:20px;color:green;"></i></span></div></a>`

1)https://github.com/publiclab/plots2/blob/57533a44739d85c33f16d3253aea29399f5aed7f/app/views/users/edit.html.erb#L8-L12
2)https://github.com/publiclab/plots2/blob/57533a44739d85c33f16d3253aea29399f5aed7f/app/views/layouts/_header.html.erb#L187-L190
3)https://github.com/publiclab/plots2/blob/57533a44739d85c33f16d3253aea29399f5aed7f/app/views/users/new.html.erb#L27-L31
4)https://github.com/publiclab/plots2/blob/57533a44739d85c33f16d3253aea29399f5aed7f/app/views/user_sessions/new.html.erb#L41-L44
Please make sure that all the four icons are same.
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)
Part of #2676.

### PR DESCRIPTION
**Pull request by Sensational-Code**
fixes #2975

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Sensational-Code** [comment]
Hey @SidharthBansal @jywarren! Can you please take a look to make sure everything here is correct? Thanks!

**Comment by SidharthBansal** [comment]
Can we have screenshots for all 4 pages?
Thanks a lot for contributing here

**Comment by Sensational-Code** [comment]
Sure! Here you go:
plots2 app views users edit html erb
plots2 app views layouts _header html erb
plots2 app views users new html erb
plots2 app views user_sessions new html erb

**Comment by SidharthBansal** [comment]
Can we have them in straight line please?

**Comment by Sensational-Code** [comment]
I'm unsure what you mean by straight line, would you like me to style the buttons horizontally?

**Comment by SidharthBansal** [comment]
Yeah I want them to be horizontally

**Comment by Sensational-Code** [comment]
Does this look better? I increased the size of the google auth button to 20px to match the github button, as it looks too small to me at 17px and otherwise they are mismatched in size.
plots2 app views users new html erb - 2
plots2 app views layouts _header html erb - 2
plots2 app views users edit html erb - 2
plots2 app views user_sessions new html erb - 2

**Comment by SidharthBansal** [comment]
Can you please add a little space between the two icons?
Otherwise they are looking awesome

**Comment by Sensational-Code** [comment]
Like this?
screen shot 2018-07-04 at 3 01 03 pm

**Comment by Sensational-Code** [comment]
Or I could make it match the spacing of the buttons above it:
screen shot 2018-07-04 at 3 05 33 pm

**Comment by SidharthBansal** [comment]
> Or I could make it match the spacing of the buttons above it:

is better option

**Comment by SidharthBansal** [comment]
@jywarren can you please review it and merge?
Thanks

**Comment by Sensational-Code** [comment]
Thanks guys! I'd love to help with anything else if you need it!

**Comment by jywarren** [comment]
This is fantastic. Thanks so much!!!!

**Comment by jywarren** [comment]
We'd love your help! We're working on some bugs if you want to try solving #2529 ? Thanks so much!

**Pull request merged**
