### PR TITLE
Add explanatory text while searching by profiles

### PR DESCRIPTION
**Pull request by cesswairimu**
Issue [#3505](https://github.com/publiclab/plots2/issues/3505)
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

Fixes #[Add issue number here.]

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
@publiclab/reviewers  please review.

**Comment by SidharthBansal** [comment]
Can you please add a screenshot?

**Comment by cesswairimu** [comment]
plots

**Comment by jywarren** [comment]
Thanks a lot Cess! And Sidharth!!!!

**Pull request merged**
