### PR TITLE
Added 'requireLogin' to subscribe button

### PR DESCRIPTION
**Pull request by omasso1**
git1
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by omasso1** [comment]
> Hi @omasso1! Welcome to PublicLab. Mind sending a screenshot of the result?
> Thanks!

Ok, is it right now? :)

**Comment by kevinzluo** [comment]
@omasso1 I was referring to a gif of the modal opening on your localhost to show that the changes worked.

**Comment by omasso1** [comment]
> @omasso1 I was referring to a gif of the modal opening on your localhost to show that the changes worked.
Ooo, unfortunatly I am not able to do that today, so I'll try tomorrow

**Comment by SidharthBansal** [comment]
No problem.
Take your time.

**Comment by oorjitchowdhary** [comment]
Also, add the issue number in the PR body.. #4433 in this case

**Comment by SidharthBansal** [comment]
I tested it on development before merging @jywarren 
Thanks everyone
@omasso1 you can do some help wanted issues if you want. Thanks

**Pull request merged**
