### PR TITLE
Added pagination for answered questions

### LINKED ISSUE #2271: Missing pagination for answered questions under profile page
### Please describe the problem (or idea)
On https://publiclab.org/profile/warren under questions tab, on clicking answered the page shows all the answered questions instead of some and paginating others

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #2271 and a part of #2173
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@Gauravano can you please review this one

**Comment by Gauravano** [comment]
Hey, @SidharthBansal can you add a screenshot or gif as we discussed in #2231.Thanks.

**Comment by SidharthBansal** [comment]
Now it looks like this
image

image
image

**Comment by SidharthBansal** [comment]
@jywarren can you please review it?

**Comment by jywarren** [comment]
Great work! Thanks, all! :+1:

**Pull request merged**
