### PR TITLE
Moved all files from app/views/comment to app/view/comments

### LINKED ISSUE #3339: Remove redundant code
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Move files from https://github.com/publiclab/plots2/tree/master/app/views/comment/ to https://github.com/publiclab/plots2/tree/master/app/views/comments/ to consolidate these very similar folders, and find any references to `/comment/` to change to `/comments/`.

### PR DESCRIPTION
**Pull request by okonek**
peek 2018-11-22 17-32
Fixes #3339 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by okonek** [comment]
Hi, what do I have to do for those tests to pass? I didn't even edit those files. Please help @publiclab/reviewers

**Comment by gauravano** [comment]
It's fine, you don't have to worry about codeclimate errors.

**Comment by gauravano** [comment]
Hey @okonek just a suggestion, like you can see in the PR body, in checklist we ask contributors to open PR on feature-branch, so that master branch remain clean.

**Comment by okonek** [comment]
Thanks, so what do I have to do in there?

**Comment by gauravano** [comment]
You cant do anything for now, but for next PR you can do the work on a feature branch instead of master

**Comment by jywarren** [comment]
Great work here!!! Thanks so much!!

**Pull request merged**
