### PR TITLE
Align download as buttons on smaller screens

### LINKED ISSUE #4972: Align download as buttons on smaller screens
Created specifically for @karunagoyalk
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
At https://publiclab.org/stats the download as buttons are not well aligned(To see this locally login as admin) are not aligned  well on smaller screens.
download

https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L32-L94

Update 
* Remove https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L32-L33 and replace with
```
 <div class="row">
 <div class="col-md-4 col-md-offset-2">
```

* Replace https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L64-L66
```
</div>
&emsp;
<div class="col-md-3">
```
* Add two divs after line https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L94
```
 </div>
</div>
```

After changing the view, also attach the screenshot of updated view in the PR. (You probably have to go on responsive design mode by pressing Ctrl+shift+M)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by karunagoyalk**
Fixes #4972  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by ananyaarun** [comment]
@karunagoyalk , Can u add screenshots/gifs to show the changes ? Thanks :)

**Comment by cesswairimu** [comment]
kay

**Comment by cesswairimu** [comment]
@karunagoyalk the changes look great thanks for pressing on with this. But there is a small issue..on  browser view the `arrow links` and `download as` button do not align. Lets fix this by having same offset as that for arrows. i.e on line 32 lets change to this  `<div class="col-md-4 col-md-offset-1">` and then we should be done.

**Comment by cesswairimu** [comment]
Awesome this looks great. Good job @karunagoyalk :tada:

**Comment by jywarren** [comment]
Awesome. Thank you so much!!! 🎉

**Pull request merged**
