### PR TITLE
Increase Limit and Debounce Queries

### PR DESCRIPTION
**Pull request by daemon1024**
Ref #9946 
#9698

### CODE REVIEW

**Review by jywarren — APPROVED** [review]

**Comment by daemon1024** [comment]
https://user-images.githubusercontent.com/47106543/129971172-de37ff32-ecfc-4d93-b83b-dae71bd1505e.mp4

Working as intended I believe :)
Try it out at https://unstable.publiclab.org/map

**Comment by daemon1024** [comment]
I will try implementing the map clustering here, probably will look nicer? instead of overlapping markers. Wdyt @jywarren

**Comment by jywarren** [comment]
This looks great, why dont we try this as in and do clustering in another pr? Could I merge this now?

Great work today!!

**Comment by jywarren** [comment]
Hmm, the UI freezes up a bit for me on mobile. Is it trying to crunch too much data?

**Comment by jywarren** [comment]
Also I worry a bit about overloading the server. What if we enabled these higher limits only if there's a secret GET parameter like limit= in /map?limit=50 for example. Then we can get a controlled sense of the server load in a live environment.

**Comment by daemon1024** [comment]
It's doable, fetching the limit from query param. 
But,
Just wondering why would it overload the server 🤔

We have been dealing with a lot heavier queries and while having the number of heavy queries higher too. 

From what I can estimate currently limit=100 would be equivalent to earlier limit=5. 

Let me know if I misunderstood something.

**Comment by jywarren** [comment]
I'm just always cautious and would like to monitor a little bit in the production environment. Would you mind making it a parameter? Thanks!!

**Comment by jywarren** [comment]
You know, just don't want to make assumptions!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Ok awesome. We can do some load tests and then change the default.

**Comment by jywarren** [comment]
Very nice! Let's try to stress this for a week after publishing to the live site on Monday and then we'll lift the limit!

image

**Pull request merged**
