### PR TITLE
Update filter on dashboard

### LINKED ISSUE #7809: All updates filter in dashboard
1.) "All update" filter in the dashboard does not work properly. Even after selecting the filter as shown in the image, the dashboard shows all the updates like wiki, comments, notes, etc.
2.)There is also an issue in its css as All update text color becomes grey instead of white as shown.
3.) select all button is not working properly as shown.
https://publiclab.org/dashboard
Screenshot from 2020-04-13 00-24-50

@jywarren @SidharthBansal please review it
Thanks

### PR DESCRIPTION
**Pull request by keshavsethi**
Fixes #7809
Here update checkbox is filtering content and select all button is also working fine which is shown in the following images 
SELECT ALL
Screenshot from 2020-04-28 03-50-58
NO QUESTIONS
Screenshot from 2020-04-28 03-51-15
NO COMMENTS
Screenshot from 2020-04-28 03-51-22
@jywarren @cesswairimu @SidharthBansal 
Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Can you please see to the travis issues ?
Also, please write a system test to ensure the correctness of your code. Thanks

**Comment by SidharthBansal** [comment]
please write a system test to ensure the correctness of your code. Thanks

**Comment by jywarren** [comment]
As we may soon be making big changes to the dashboard, i think we can skip system tests in this instance. Thank you very much!!!

**Comment by jywarren** [comment]
Thank you!!! Can you give it one more try at stable.publiclab.org once it rebuilds? Awesome!

**Pull request merged**
