### PR TITLE
updated line 64 of ar.yml

### LINKED ISSUE #10850: Change translation key for distance_of_time_on_words
Hi everyone, we are having translation errors with our user profile page on publiclab.org. This issue and #10849 are meant to resolve part of the issue in #10765. There are a series of translation files that their translation keys that need to be changed. I would have created separate FTOs for them but the changes are the same and would seem repetitive. I'll list the files that need changes and the lines that need to be changed.

- [ar.yml](https://github.com/publiclab/plots2/blob/main/config/locales/ar.yml) (Line 64) - Reserved for @akanbifatimah https://github.com/publiclab/plots2/pull/10857
- [de.yml](https://github.com/publiclab/plots2/blob/main/config/locales/de.yml) (Line 65) - Reserved for @BRB3D https://github.com/publiclab/plots2/pull/10864
- [es.yml](https://github.com/publiclab/plots2/blob/main/config/locales/es.yml) (Line 64) - Reserved for @siddhi-244 https://github.com/publiclab/plots2/pull/10903
- [gr.yml](https://github.com/publiclab/plots2/blob/main/config/locales/gr.yml) (Line 65) - Reserved for @marshatiisa https://github.com/publiclab/plots2/pull/10929
- [hi-IN.yml](https://github.com/publiclab/plots2/blob/main/config/locales/hi-IN.yml) (Line 61) - Reserved for @barcha47 https://github.com/publiclab/plots2/pull/10852
- [it.yml](https://github.com/publiclab/plots2/blob/main/config/locales/it.yml) (Line 66) - Reserved for @Ms-Error https://github.com/publiclab/plots2/pull/10851
- [ko.yml](https://github.com/publiclab/plots2/blob/main/config/locales/ko.yml) (Line 64) - Reserved for @pranayrauni https://github.com/publiclab/plots2/pull/10856
- [pt-BR.yml](https://github.com/publiclab/plots2/blob/main/config/locales/pt-BR.yml) (Line 64) - Reserved for @kachifako https://github.com/publiclab/plots2/pull/10861
- [ru.yml](https://github.com/publiclab/plots2/blob/main/config/locales/ru.yml) (Line 64) - Reserved for @nuilewis https://github.com/publiclab/plots2/pull/10906
- [zh-CN.yml](https://github.com/publiclab/plots2/blob/main/config/locales/zh-CN.yml) (Line 64) - Reserved for @anushkachauhxn https://github.com/publiclab/plots2/pull/10858

Required Change:
```diff
-    distance_in_words:
+    time_ago_in_words:
```

### PR DESCRIPTION
**Pull request by akanbifatimah**
Fixes #10850 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by akanbifatimah** [comment]
Please I need help with running the Gitpod check. This is the error I get each time I run the workplace.
image

**Review by TildaDares — APPROVED** [review]
Thank you @akanbifatimah!! Great work.

**Comment by TildaDares** [comment]
Congratulations on merging your first Public Lab PR 🎉

**Comment by akanbifatimah** [comment]
Thank you @TildaDares , I enjoyed working on the issue

**Pull request merged**
