### PR TITLE
 Fix typo in html tag

### LINKED ISSUE #10989: Fix typo in html tag
### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [public/404.html](https://github.com/publiclab/plots2/tree/main/public) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
line 44:
     -        <hr />
     +         <hr>

```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

### PR DESCRIPTION
**Pull request by Ishhha**
I fixed the typo in hr tag in line 44 in public/404.html.

fixes #10989

### CODE REVIEW

**Review by kachifako — CHANGES_REQUESTED** [review]
Hello @Ishhha , the only change required is that of line 44. 
Kindly undo the change in line 74 (remove the semi-colon you added before the equals sign)

Thanks.

**Comment by Ishhha** [comment]
@kachifako Can u please check it now and give me the feedback?

**Comment by on2onyekachi** [comment]
Hi @Ishhha 

was this PR raised as an issue? 
If yes, then you should add the issue number to your PR in the description. and It should be in the format `fixes #0000` Thanks!

**Comment by kachifako** [comment]
Thanks @on2onyekachi.

One last correction and you're good @Ishhha. Remove "fixes#10989" from the title.

**Comment by on2onyekachi** [comment]
@kachifako Yeah, thanks

The self-closing tags with the backslash I thought it's a followed pattern. cause I have seen a lot of self-closing tags with backslash probably in some HTML files. will be great to raise them up as an issue too?

**Comment by TildaDares** [comment]
@on2onyekachi It’s a great idea but it’d be better to do all of the changes in one issue since it’s a really small change.

**Comment by Ishhha** [comment]
I have corrected the title @kachifako. I think you can merge the PR now. :)

**Review by TildaDares — APPROVED** [review]
Thanks for working on this @Ishhha!!!

**Comment by TildaDares** [comment]
Thanks for reviewing @on2onyekachi, @kachifako!!

**Comment by TildaDares** [comment]
Congratulations @Ishhha 🎉

**Comment by Ishhha** [comment]
@TildaDares Can u please suggest some issues in Design a new full-screen user interface for Infragram.org project?

**Comment by TildaDares** [comment]
Hi @Ishhha, you can take a look at the infragram site and look for issues to work on.

**Comment by on2onyekachi** [comment]
> @on2onyekachi It’s a great idea but it’d be better to do all of the changes in one issue since it’s a really small change.

Okay Thanks @TildaDares . It has been handled by @kachifako

**Comment by Ishhha** [comment]
> Hi @Ishhha, you can take a look at the infragram site and look for issues to work on.

Thank you❤ @TildaDares. I am starting to search and create new issues to work on. :)

**Pull request merged**
