### PR TITLE
[WIP] #1358 MathJax interferes with markdown fences

### PR DESCRIPTION
**Pull request by aspriya**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, what's wrong, did this not work out?

**Comment by aspriya** [comment]
Working on it. But I'm not sure if any thing with markdown fences is working properly. For a example when I enter a code block sorrounded with fences in a comment and previewed it before submiting they are rendered correctly. But after submitted, they are showed as inline codes.

**Comment by jywarren** [comment]
I think the renderer for markdown is different in preview than in the
actual rendering -- in preview, it's JavaScript based. On published notes,
it's based on... maybe RedCarpet? It's a different renderer, in any case,
so we may want to look at that.

**Comment by aspriya** [comment]
Thnx @jywarren for info. On published notes, it's based on RDiscount. Reaserching now where the issue is.

**Pull request closed without merging**
