### PR TITLE
bootstrap classes integration

### LINKED ISSUE #7532: Including Bootstrap in plots2/editor
Bootstrap files are not included in plots2 Editor leading to various style issue like inconsistency in style of the toolbar , quoted text and code doesn't show the style

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes https://github.com/publiclab/PublicLab.Editor/issues/443 Fixes #7532 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@jywaren I have added only classes being used from Bootstrap.

**Comment by nicoleiocana** [comment]
Since plots2 utilizes Bootstrap 4, I think we should refrain from using the `.btn-default` class since it is no longer being utilized. [Source](https://getbootstrap.com/docs/4.1/components/buttons/). Furthermore, if we just added the class `.btn-secondary` to the button element, the bootstrap styling would automatically be applied, making our code more efficient.

**Comment by keshav234156** [comment]
@nicoleiocana You are right. But the problem arises as https://github.com/publiclab/PublicLab.Editor/ uses bootstrap version 3.4 and plots2 uses version 4 there are class mismatches so they are not interchangeable

**Comment by keshav234156** [comment]
Screenshot from 2020-04-10 18-55-32
Screenshot from 2020-04-10 18-55-21
Screenshot from 2020-04-10 18-55-11

**Comment by keshav234156** [comment]
@jywarren Please review!!

**Comment by jywarren** [comment]
Ah, hmm, so is the solution here that it now has some CSS customizations that make it compatible with both Bootstrap 3 and 4? Would you mind adding some documentation to the README accordingly, so folks know what's going on, and maybe linking to it from a comment in the stylesheet? 

Thank you! Such great work!!!

**Comment by keshav234156** [comment]
@jywarren included the comments

**Comment by jywarren** [comment]
Awesome, thank you!!!

**Pull request merged**
