### PR TITLE
Add links for different sorting options in searches (#2544)

### LINKED ISSUE #2544: Create links on /search/_____ for search sorting options
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

It's not easy to switch search sorting order among the available options:

* https://publiclab.org/search/pumpkins?order=natural for natural language match ordering
* https://publiclab.org/search/pumpkins?order=likes for ordering by likes
* https://publiclab.org/search/pumpkins?order=views for ordering by views
* https://publiclab.org/search/pumpkins for ordering by original page creation dates

## Solution

Create links (such as the 4 options above) at the top of the search page to order results by the following possibilities. (of course replacing "pumkpin" with the actual search term)

So when you arrive at https://publiclab.org/search/pumpkins, you can then click to get to any other type of sorting, as above. 

Mockup screenshot:

screen shot 2018-03-26 at 5 43 51 pm

These links should go below this line on the searches `results.html.erb` template:

https://github.com/publiclab/plots2/blob/ea2b5ba1ded2b23a156091cd0add5df9234ae650/app/views/searches/results.html.erb#L3-L4

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page](https://publiclab.github.io/community-toolbox/#r=all)!

****

(This issue broken out from https://github.com/publiclab/plots2/issues/2421)

**Follow-up (or extra)**

- [ ] Set the default ordering for results shown on https://publiclab.org/search/keyword to be by "natural language match" instead of the current default.

### PR DESCRIPTION
**Pull request by gSanchezCiarrocchi**
Fixes #2544
 @jywarren hope somebody can review this, thanks

### CODE REVIEW

**Comment by gSanchezCiarrocchi** [comment]
@publiclab/reviewers Hello, waiting for a review, thanks

**Comment by gauravano** [comment]
Hi, @gSanchezCiarrocchi thanks for solving this, as this PR include changes in view, so if you could include screenshot or GIF of the new view, then it would be great. Thanks!

**Comment by gSanchezCiarrocchi** [comment]
@gauravano Here's the screenshot
publiclab-sort-links

**Comment by jywarren** [comment]
This looks great! I'm going to merge it now. Would you have an interest in an additional project of making the *current* ordering not appear as a link, so you know which is the current one?

**Comment by jywarren** [comment]
@milaaraujo @stefannibrasil check out what @gSanchezCiarrocchi just completed! Looking great!

**Comment by gSanchezCiarrocchi** [comment]
@jywarren  Sure, no problem. Are you going to create an issue for it? I'll take a look at it when I have some free time this week

**Comment by jywarren** [comment]
would you mind opening an issue? Or if you like you could go directly to a
PR. Thanks a million!

**Comment by stefannibrasil** [comment]
well done!! we will be using that soon :D

**Pull request merged**
