### PR TITLE
Added tooltip for banned users

### LINKED ISSUE #1721: Add an indicator for red colored banned users and a hover over the username to check for spammers quickly
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
When you go to page:

[http://localhost:3000/likes](url)

You see something like this: 

image

Here, The recent likes are listed with banned users depicted in red colour and black otherwise. There should be an indicator as to what red indicates. Secondly,  a hover for admin and moderators is required over the username  so that they can read peoples' bio quickly to check if they're spammers.

## Solution

The changes are required to be made in the following template:

[https://github.com/publiclab/plots2/blob/master/app/views/like/index.html.erb](url)

Add the indicator for red coloured banned user in `<p>` tags below the heading **Recent Likes** in this template something like this:

```HTML
<p>Username in red indicates <b><i>banned user</i></b>.</p><br>
```
Secondly, a hover over the username for moderators and admin only could be implemented by adding an if else condition to check for admin and moderators like this:
````ruby
<% if current_user && (current_user.role == "admin" || current_user.role == "moderator") %>

<a rel="tooltip" title="<%= like.user.bio %>" class="user" href="/profile/<%= like.user.name %>" style = "color: <%= like.drupal_users.status.zero? ? 'red' : 'black' %>"" > <i class="fa fa-user" aria-hidden="true"></i> <%= like.user.name %></a>

<% else %>

<a href="/profile/<%= like.user.name %>" style = "color: <%= like.drupal_users.status.zero? ? 'red' : 'black' %>"><i class="fa fa-user" aria-hidden="true"></i> <%= like.user.name %></a>

<% end %>
````
replacing this line of code https://github.com/publiclab/plots2/blob/3955e17ad30eda37854d97d7813a862060d2bbfd/app/views/like/index.html.erb#L16

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #1721

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Whoa, awesome, @Diksha2008 how's this look to you?

**Comment by ViditChitkara** [comment]
Is there a need of adding an indicator to identify red colour, since one could easily identify a banned user by looking at the "action" column associated with that particular user. @jywarren , @Diksha2008 thoughts?

**Comment by jywarren** [comment]
Maybe @ebarry has a thought on this too?

**Comment by Diksha2008** [comment]
This seems perfect! :)

**Comment by Diksha2008** [comment]
The action column won't show up for people other than admin or moderators so maybe an indicator as to what red indicates would be helpful for them!

**Comment by ebarry** [comment]
+1 looks great as far as i can tell!

**Comment by jywarren** [comment]
I think the red looks good -- and yes, maybe a message like:

`Users marked in red have been banned!`

And displaying this only for moderators and admins, otherwise it may be confusing for people who don't see any red marks :-)

**Comment by jywarren** [comment]
Which is to say - this looks fantastic. If you're interested in adding that one additional line, we'd love it too!

**Comment by ViditChitkara** [comment]
Sure @jywarren I'll make the changes right away!

**Comment by ViditChitkara** [comment]
screenshot from 2017-10-26 01 42 18
@jywarren added it just under the heading "Recent Likes", would this be fine?

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks so much -- both to @ViditChitkara and to @Diksha2008 for making this issue! I hope we can keep working with you both!

**Pull request merged**
