### PR TITLE
Disable Drag & Drop Upload on the Image Toolbar Button

### PR DESCRIPTION
**Pull request by noi5e**
103472308-f5ae0400-4d40-11eb-8d18-88099b4addfd

Small change: This PR disables drag & drop onto **A** in the above image.

It seems unintentional that user would be able to drop an image onto the image upload button. Most users probably don't expect to be able to do this. I think it's a good idea to take away this functionality. Because it leads to unintended user behavior, which we would have to write system tests for, guard against, etc.

(FYI Both A and B have the class `.dropzone`.)

---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #9069 for more context)

### CODE REVIEW

**Comment by noi5e** [comment]
Ready to merge! Merge these before this one (in order)

1. refactor editor.js with object-oriented principles #9104
2. rewrite $E.setState for single ID parameter #9107
3. prune editor state management #9108
4. refactor editor constructor with new parameter; write editor getters #9110
5. remove functionality for DRAG onto edit form's .dropzone to upload image #9118

The above list is also present at my planning issue #9069

**Review by cesswairimu — APPROVED** [review]
Suberb :tada: :tada: Thanks @noi5e

**Comment by cesswairimu** [comment]
Hi @noi5e ping me to merge once you resolve the conflicts, really glad we have this weird behavior removed  :rocket: thanks

**Comment by noi5e** [comment]
@cesswairimu Thank you for the review!! Ready to merge again, tests passing!

**Comment by cesswairimu** [comment]
Awesome :tada:

**Pull request merged**
