### PR TITLE
Changed 'you all are set' to 'you are all set'

### PR DESCRIPTION
**Pull request by TildaDares**
Fixes #9387 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

- [x] PR is descriptively titled 📑 and links the original issue above 🔗
- [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
- [x] code is in uniquely-named feature branch and has no merge conflicts 📁
- [ ] screenshots/GIFs are attached 📎 in case of UI updation
- [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by cesswairimu — APPROVED** [review]
Looks good :tada: ...Thanks so much @TildaDares for working on this...was there an issue for this? if so kindly link me to it. Thanks

**Comment by TildaDares** [comment]
@cesswairimu There's no issue for this. I was going through the docs to set up my local environment for the outreachy contributing period when I saw it. It was a small change so I didn't see any reason to open an issue. I don't know if that's okay.

**Comment by cesswairimu** [comment]
its okay, and many thanks for this :tada: ..next time kindly create an issue too for better tracking. Merging this :rocket:

**Comment by cesswairimu** [comment]
welcome bot misbehaving a little here :thinking:

Welcome to PublicLab @TildaDares :balloon:

**Comment by cesswairimu** [comment]
yeah it sure does

**Pull request merged**
