### PR TITLE
fix docker compose stable dependency bug

### PR DESCRIPTION
**Pull request by ViditChitkara**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
@jywarren hope this resolves circular dependency error.

**Comment by icarito** [comment]
Sorry @ViditChitkara actually this is the fix here pls switch it and we can merge it

**Comment by icarito** [comment]
Tested!

**Comment by ViditChitkara** [comment]
Cool!! Did it show any error?

**Comment by icarito** [comment]
Not at building https://jenkins.laboratoriopublico.org/job/Plots-Unstable/218/console - try it at https://unstable.publiclab.org/

**Comment by icarito** [comment]
not yet published to stable but should be the same

**Comment by ViditChitkara** [comment]
okay

**Comment by ViditChitkara** [comment]
I tried on unstable, however it enqueues only and doesn't process the mails. Maybe sidekiq server is not started. Is the line network-mode: "host" mandatory? Being in testing container it worked perfectly

**Comment by ViditChitkara** [comment]
@icarito thoughts on this?

**Comment by icarito** [comment]
```
sidekiq_1  | Could not locate Gemfile or .bundle/ directory
```

**Comment by icarito** [comment]
i'll fix it!

**Comment by icarito** [comment]
```
Attaching to containers_sidekiq_1 
sidekiq_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant TagNodeAssociationExtension 
sidekiq_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of TagNodeAssociationExtension was here 
sidekiq_1  | Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit` 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:585:in `validate_secret_key_base' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:432:in `secret_key_base' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:176:in `key_generator' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:205:in `message_verifier' 
sidekiq_1  | /usr/local/bundle/gems/activestorage-5.2.0/lib/active_storage/engine.rb:67:in `block (2 levels) in <class:Engine>' 
sidekiq_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook' 
sidekiq_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control' 
sidekiq_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook' 
sidekiq_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks' 
sidekiq_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `each' 
sidekiq_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `call' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each' 
sidekiq_1  | /usr/local/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send' 
sidekiq_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing' 
sidekiq_1  | /app/config/environment.rb:5:in `<top (required)>' 
sidekiq_1  | /usr/local/bundle/gems/sidekiq-5.1.3/lib/sidekiq/cli.rb:272:in `require' 
sidekiq_1  | /usr/local/bundle/gems/sidekiq-5.1.3/lib/sidekiq/cli.rb:272:in `boot_system' 
sidekiq_1  | /usr/local/bundle/gems/sidekiq-5.1.3/lib/sidekiq/cli.rb:53:in `run' 
sidekiq_1  | /usr/local/bundle/gems/sidekiq-5.1.3/bin/sidekiq:12:in `<top (required)>' 
sidekiq_1  | /usr/local/bundle/bin/sidekiq:17:in `load' 
sidekiq_1  | /usr/local/bundle/bin/sidekiq:17:in `<top (required)>' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors' 
sidekiq_1  | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>' 
sidekiq_1  | /usr/local/bin/bundle:23:in `load' 
sidekiq_1  | /usr/local/bin/bundle:23:in `<main>' 
jenkins@tycho:/srv/plots_unstable/plots2$  
```

**Comment by icarito** [comment]
Okay, unstable should have sidekiq running now! 
https://github.com/publiclab/plots2/pull/2979

**Comment by ViditChitkara** [comment]
yes it's working.

**Comment by ViditChitkara** [comment]
`SocketError: getaddrinfo: Name or service not known` (from [sidekiq dashboard](https://unstable.publiclab.org/sidekiq/retries))
Got this error when tried digest mail.
Found some similar sort of error here:- https://github.com/dokku/dokku-redis/issues/69
@icarito any ideas?

**Pull request merged**
