### PR TITLE
Update blog.html.erb

### PR DESCRIPTION
**Pull request by gptshubham595**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gptshubham595** [comment]
plz review

**Comment by CodeSarthak** [comment]
Hello @gptshubham595 , please add the issue number in the PR description, otherwise looks good!

**Comment by SidharthBansal** [comment]
Please remove the conflicts and add the issue number so that we can review it.
Thanks for contributing at Public Lab.

**Comment by SidharthBansal** [comment]
As the person is inactive for more than 3 weeks, I am closing the PR. In case you want to push changes please feel free to open a new PR.
Thanks for contributing at Public Lab

**Pull request closed without merging**
