### PR TITLE
Add tag input field to wiki editor

### LINKED ISSUE #8229: add tags input (matching legacy editor of note editor) to new wiki form and wiki editing page.
**Please describe the desired behavior.**
Describe the solution you'd like.

This is a feature request by the PL staffs, to have the new wiki form and wiki editing page include field for tag input.

will be working on this soon.

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
Fixes #8229 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
@jywarren  @sagarpreet-chadha i can't see the wiki editing page on passenger start. I don't know any other way to see if my changes are working?

**Comment by jywarren** [comment]
Ah i commented some ideas and Qs in the originating issue! #8229, hope that helps!

**Comment by jywarren** [comment]
Also, strangely GitPod failed. Related maybe?

**Comment by Shulammite-Aso** [comment]
Oh, using admin worked @jywarren and the tag field is actually there:
wiki-tag

i just need to style it so that there is space between it and the buttons below.

**Comment by Shulammite-Aso** [comment]
Just saw the space in legacy editor is actually  `<br>` will just use the same here!

**Comment by Shulammite-Aso** [comment]
@jywarren @sagarpreet-chadha please review. This should work now

**Comment by Shulammite-Aso** [comment]
I think this can be merged now @sagarpreet-chadha @jywarren @cesswairimu

**Comment by jywarren** [comment]
Fantastic I just confirmed this by testing in GitPod:

image

Perhaps @Shulammite-Aso you'd like to try writing a functional test for this? I'll merge this now but you could look at this as a reference:

https://github.com/publiclab/plots2/blob/5fedc09c1970011e08dd9c79be5be82f7c0648fc/test/functional/notes_controller_test.rb#L499-L513

although it would exist in the `wiki_controller_test.rb` file instead. If you're interested, that would be great! You could even test to ensure the new tags were added.

**Comment by Shulammite-Aso** [comment]
> Perhaps @Shulammite-Aso you'd like to try writing a functional test for this? I'll merge this now but you could look at this as a reference:

Okay! will try to do this soon.

**Comment by cesswairimu** [comment]
:tada:

**Pull request merged**
