### PR TITLE
Adding new locales "de.yml" and "zh-CN.yml"

### LINKED ISSUE #4583: Adding Locale files for Deutsch and Chinese
Currently, we only have one locale i.e., for English language. Locales for Deutsch and Chinese can be 
added from https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #4583  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Ah, where did these translations come from? We've had some complaints sometimes that they are not very good if automatically done. So perhaps we should leave them undone until they are submitted by community? 

OR, we could have the little globe icon that we'll be showing also show a popover that says "This translation needs help; it was auto-translated"? Either way perhaps we should start with a more minimal set.

**Comment by gauravano** [comment]
These translations came from https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/ which is rails-i18n gem repo. By default, when we change the language to some other, the translation is taken from these files only. I have copied these in locales so we can expand the translations of other languages too. 

And, I don't think these translation would need any review as these are translations for date, time, error messages, month, etc.

**Comment by gauravano** [comment]
@jywarren regarding globe icon next to the translation, we need to decide on the way we would be handling our translation system, what would be the flow,where we would be redirecting the user to on link press, that's major question. 

Please check here - https://github.com/publiclab/plots2/issues/3262#issuecomment-452457100 . Thanks!

**Comment by jywarren** [comment]
Oh i see! Great. merging.

**Pull request merged**
