### PR TITLE
added password_placeholder

### PR DESCRIPTION
**Pull request by gurpreet9001**

### CODE REVIEW

**Comment by gurpreet9001** [comment]
it is working but my installation has crashed so cant provide screenshot
it is a simple update therefore it is not hard to notice

**Comment by gurpreet9001** [comment]
capture

this is the simple change

**Comment by gurpreet9001** [comment]
i am not able to execute because my local copy is not working

**Comment by SidharthBansal** [comment]
You can try out to debug it.

**Pull request merged**
