### PR TITLE
Changed Power-tag tool to method

### LINKED ISSUE #1545: Power tag change from "tool" to "method"
I was wondering if we could switch the tag that compiles materials on the /methods page to "method" instead of "tool" 

www.publiclab.org/methods

### PR DESCRIPTION
**Pull request by devaman**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!
Fixes #1545

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great; merging now! @steviepubliclab your issue got solved, kudos.

This will be published to the site pretty soon. @devaman - was this your first open source contribution, just curious? Thanks!

**Comment by steviepubliclab** [comment]
Thank you!

**Comment by devaman** [comment]
This was my second open source contribution! The first was also for Public Labs.

**Comment by jywarren** [comment]
Oh, i'm sorry i didn't connect the dots! We're very glad to have your
contributions and look forward to working more with you if you're
interested!

Thanks again :-)

**Comment by devaman** [comment]
Yes, I am really interested in working with you and I will try to contribute more.

**Comment by jywarren** [comment]
This is live now! https://publiclab.org/methods

**Pull request merged**
