### PR TITLE
Change the message when the note is a question

### PR DESCRIPTION
**Pull request by neliojrr**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] In progress 
* [ ] reviewed/confirmed/tested by another contributor or maintainer

My vim remove blank spaces when I save a file. I think that it's good, right!?

### CODE REVIEW

**Comment by jywarren** [comment]
Hello - i hope to review and merge in the next two days -- apologies, but I'm currently in a staff retreat and won't be able to today! Thank you very much for your contribution.

**Comment by jywarren** [comment]
Almost there -- today or tomorrow, and apologies for the lateness. Now back from staff retreat and catching up. Your patience is much appreciated!

**Comment by jywarren** [comment]
Oh, this looks super -- thanks! Merging now.

**Comment by jywarren** [comment]
Thanks and if you're looking to tackle a new issue, there are plenty we'd be happy to help out with at https://github.com/publiclab/plots2/labels/help-wanted

**Comment by neliojrr** [comment]
Yes! I would like to do more! Thank you!

**Pull request merged**
