### PR TITLE
Changed all deliver_now to deliver_later

### LINKED ISSUE #9313: Change deliver_now to deliver_later
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Part of #6126 Change deliver_now to deliver_later:
https://github.com/publiclab/plots2/blob/7e663aa59c4aed5b90ac6122c2d83b409d83323b/app/models/comment.rb

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by DBailie96**
Fixes #9313

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
I'm sorry -- it looks like there are a few tests we actually need to modify here. I think we need to trigger the enqueued mails to send, by wrapping the failing tests in a block like this:

https://github.com/publiclab/plots2/blob/876d0fc084064aaecc23f8003630d7d1ab858fa1/test/functional/admin_controller_test.rb#L115-L127

You can see which tests need to be modified here -- would you be able to make this change? Thank you! Maybe @SidharthBansal would be able to support too if you get in trouble! 

```
FAIL CommentControllerTest#test_should_not_send_notification_email_to_another_commenter_if_notify-comment-indirect:false_usertag_is_present (33.56s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:387:in `block in <class:CommentControllerTest>'

 FAIL CommentControllerTest#test_should_send_mail_to_moderator_if_comment_has_status_4 (33.80s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:294:in `block in <class:CommentControllerTest>'

 FAIL CommentControllerTest#test_should_send_mail_to_multiple_tag_followers_in_the_comment (33.88s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:315:in `block in <class:CommentControllerTest>'

 FAIL CommentControllerTest#test_should_send_mail_to_tag_followers_in_the_comment (33.96s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:308:in `block in <class:CommentControllerTest>'

 FAIL CommentControllerTest#test_should_send_notification_email_upon_a_new_wiki_comment (34.03s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:323:in `block in <class:CommentControllerTest>'
```

**Comment by jywarren** [comment]
Oh, sorry, i think some of these may relate to https://github.com/publiclab/plots2/issues/9247, and not to your code. Let me try to fix that and then we'll circle back here. Sorry and thanks for your patience!!!

**Comment by jywarren** [comment]
OK, i tried rebasing your work over the fixes we just did. I hope this works! Thanks for your patience!!!

**Comment by jywarren** [comment]
Hmm. This still got stuck at these two tests:

```

Progress: |== FAIL CommentControllerTest#test_should_not_send_notification_email_to_another_commenter_if_notify-comment-indirect:false_usertag_is_present (12.30s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:406:in `block in <class:CommentControllerTest>'

 FAIL CommentControllerTest#test_should_send_mail_to_moderator_if_comment_has_status_4 (12.85s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:298:in `block in <class:CommentControllerTest>'

```

@SidharthBansal @cesswairimu any thoughts on this? 

https://github.com/publiclab/plots2/blob/0908bfda7ef2462e6b6b61fd8c4654d60f3c3ada/test/functional/comment_controller_test.rb#L298

Shouldn't moderator still get these emails? ☹️

**Comment by cesswairimu** [comment]
hi, I think if we wrap the content of the second test inside `perform_enqueued_jobs` it should work fine...the first one I think it fails because the session created is for the moderator user  and they created the comment so hence not emailed...I believe it should work if we use another user as the author of the comment...would you like to fix these @DBailie96?

This would involve changing this line https://github.com/DBailie96/plots2/blob/%239313/test/functional/comment_controller_test.rb#L292 to 
`UserSession.create(users(:bob))`

and adding this line of code `perform_enqueued_jobs  do` after this line  https://github.com/DBailie96/plots2/edit/%239313/test/functional/comment_controller_test.rb and an `end` after the last 'assert'

I am available to make these changes if you are not in a position to just ping me...thanks a lot for your patience and on working on this

**Comment by DBailie96** [comment]
Hi, yes I'd love to do this. Thanks for the guidance.

**Review by cesswairimu — APPROVED** [review]
Fantastic :tada: thanks again @DBailie96

**Pull request merged**
