### PR TITLE
Ensure formatting toolbars on comments appear in all variations

### PR DESCRIPTION
**Pull request by Sagarpreet**
Fixes: https://github.com/publiclab/plots2/issues/8475

🔜

### CODE REVIEW

**Comment by Sagarpreet** [comment]
```
 FAIL["test_comment_deletion", #<Minitest::Reporters::Suite:0x00007f37ca25c868 @name="CommentTest">, 256.499083343]
 test_comment_deletion#CommentTest (256.50s)
        expected to find css "#comments-list .comment" 1 time but there were no matches
        test/system/comment_test.rb:229:in `block in <class:CommentTest>'
[Screenshot]: tmp/screenshots/failures_test_comment_editing.png
ERROR["test_comment_editing", #<Minitest::Reporters::Suite:0x00007f37ca82f538 @name="CommentTest">, 258.861415905]
 test_comment_editing#CommentTest (258.86s)
Minitest::UnexpectedError:         Selenium::WebDriver::Error::JavascriptError: javascript error: Cannot read property 'id' of undefined
          (Session info: headless chrome=86.0.4240.75)
            test/system/comment_test.rb:251:in `block in <class:CommentTest>'
  96/96: [=================================] 100% Time: 00:04:34, Time: 00:04:34
Finished in 274.94103s
96 tests, 85 assertions, 1 failures, 1 errors, 0 skips

```

**Comment by Sagarpreet** [comment]
@cesswairimu @jywarren where can I see the screenshot results? Thanks!

**Comment by jywarren** [comment]
Oof, unfortunately the screenshots are not linked to anymore as our Dangerbot script broke. They used to be stored in Google Cloud here:

https://github.com/publiclab/plots2/blob/3664a280d660f6f059fbadfcd38f059129f7645f/Dangerfile#L67-L81

However, this script is not really running any more 😭 

You can, however, open GitPod and check there. I do wish at some point to remake that script, maybe using the JS version of Dangerbot? https://danger.systems/

However, bots via Github Actions have become far more powerful recently so maybe it's something we could just build into a Probot bot or something... https://probot.github.io/

Feel free to spin out this comment into its own issue!

**Comment by sagarpreet-chadha** [comment]
Okay cool Jeff 👍 
I will need to debug in that case why the tests are failing.

**Comment by Sagarpreet** [comment]
Okay now `deletion` system test is passing but `editing` system test is still giving error:

```
ERROR["test_comment_editing", #<Minitest::Reporters::Suite:0x00007fc7a1377178 @name="CommentTest">, 131.42664090699998]
 test_comment_editing#CommentTest (131.43s)
Minitest::UnexpectedError:         Selenium::WebDriver::Error::JavascriptError: javascript error: Cannot read property 'id' of undefined
          (Session info: headless chrome=86.0.4240.75)
            test/system/comment_test.rb:251:in `block in <class:CommentTest>'

```

**Comment by Sagarpreet** [comment]
Yayyy tests passed 🎉 
@jywarren kindly test it on gitpod, otherwise it is ready to me merged 😄 
The system tests can be sometimes difficult to debug without screenshots, we should work on fixing that script 👍

**Comment by Sagarpreet** [comment]
Moved to https://github.com/publiclab/plots2/pull/8636

**Pull request closed without merging**
