### PR TITLE
Current wiki search tab highlight

### LINKED ISSUE #3526: Highlight selected tab
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

### Please describe the problem (or idea)
It will be good if the selected tab is highlighted.
> What happened just before the problem occurred? Or what problem could this idea solve?

tab

> What did you expect to see that you didn't?
I expect to highlight selected tab as above 

### Please show us where to look

https://publiclab.org/search/science%20community?order=default

### What's your PublicLab.org username?
igniteeng000
> This can help us diagnose the issue: 

https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/search/notes.html.erb
https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/search/wikis.html.erb

### Browser, version, and operating system
windows 10, chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by handlerug**
Fixes #3526

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by handlerug** [comment]
oct-26-2018 21-51-15
@singhalkirtika, @igniteeng000, check this PR, please

**Comment by handlerug** [comment]
@singhalkirtika @igniteeng00 ?

**Comment by singhalkirtika** [comment]
Please provide the link of your GCI task and submit the link of pull request there also.

**Comment by handlerug** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5803680986038272/

**Comment by handlerug** [comment]
@singhalkirtika @igniteeng000 ???

**Comment by singhalkirtika** [comment]
Sorry for being so late. I will review it by today.

**Comment by handlerug** [comment]
Thanks for approving! 👍

**Comment by jywarren** [comment]
Oh, what happened here, was this ready to be merged? How did it get closed? Thanks for your help!

**Comment by handlerug** [comment]
I closed this because my task was approved. Do I need to open it again?

**Comment by handlerug** [comment]
Will someone review this code, comment and maybe merge pull request?

**Comment by handlerug** [comment]
@singhalkirtika @igniteeng000 @jywarren ?

**Comment by jywarren** [comment]
Sorry, this got missed as we have had a lot more activity than we'd anticipated! This looks really good. I'm going to merge it - thank you!

**Comment by handlerug** [comment]
Thanks! :+1:

**Pull request merged**
