### PR TITLE
Update bundler before bundle install

### PR DESCRIPTION
**Pull request by icarito**
Another attempt this time at upgrading bundler to bundler2.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
Okay one of the issues that I think may want some discussion is that we were doing `bundle update` during Docker build phase, but not in Travis. Is running `bundle update` at deployment time desired, or rather the point of Gemfile.lock is to warrant a specific locked version known to work?

**Comment by icarito** [comment]
Eliminating the `bundle update` step in `Dockerfile` and adding `bundle exec` prefix allowed Jenkins and Travis to agree to build and test correctly. :tada:

**Comment by cesswairimu** [comment]
Awesome thanks @icarito  :rocket:

**Comment by Tlazypanda** [comment]
Thanks @icarito :tada: :100: !!

**Comment by jywarren** [comment]
Thank you so much!!! This is awesome.

**Pull request merged**
