### PR TITLE
Changed get to post 

### LINKED ISSUE #2787: Rails 5 follow-up fixes
Just compiling some things from the #2726 #278 Rails 5 upgrades now that it's in stable!

* [x] `POST https://stable.publiclab.org/tag/suggested/tag 404 (Not Found)` - did route change? A GET route exists: https://github.com/publiclab/plots2/blob/9172df4efdcb67995f88ad770fc6c71a22684c2e/config/routes.rb#L173
* [x] ~top navbar search autocomplete doesn't work (doesn't seem to trigger a request at all?)~ (existing bug!)

@Souravirus any help appreciated but I imagine it's late there!

### PR DESCRIPTION
**Pull request by Souravirus**
Fixes #2787 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oof, what's this? Hmm..... this is a bit troubling. Maybe we need to do some research to see what this could be caused by?

**Comment by Souravirus** [comment]
Are you talking about the tests?

**Comment by Souravirus** [comment]
Yeah these tests are frustrating

**Comment by jywarren** [comment]
Yeah, the junit parsing message...

**Comment by jywarren** [comment]
Oh what? i had seen an error!

**Comment by jywarren** [comment]
Uhhhhhh that's so weird. It's gone now.

**Comment by jywarren** [comment]
Did you? It was the Junit parsing error... but there's no trace of it!

**Comment by Souravirus** [comment]
I have seen an error before. And because of that, I restarted the build

**Comment by Souravirus** [comment]
I will surely notify you about that error if I see that again

**Pull request merged**
