### PR TITLE
added gem lemmatizer and  wrapped it up in module

### LINKED ISSUE #3666: Search: "query expansion" or "thesauruses" or "stemming" in full-text search
### Please describe the problem (or idea)

> What problem could this idea solve?

@bronwen9 and I were observing that searching for `trawl`, `trawls`, and `trawling` all yield different search results. This is actually a similar pattern seen in words like `sample`, `samples`, `sampling`.

Because we're not using a controlled vocabulary, or defining how people can tag, it's currently possible for a newcomer to search for a term, find nothing, and never know they were just a single `s` away from finding an entire research area. 

> What did you expect to see that you didn't?

We should have a way to group common variations on the term so that several closely related or common misspellings would yield the same high quality search results. 

Alternatively, we could have a way to show people what similar term to what they are currently searching for might yield more results. Perhaps at the autosuggest moment where we show "similar" terms along with a "count" of how many times they are used. 

We are willing to work on this manually to create lists of associated words or phrases that could assist the search on our site. 

### Please show us where to look

https://publiclab.org/search

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz, bronwen

### PR DESCRIPTION
**Pull request by shubhscoder**
Fixes #3666 

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

I have locally checked the results for around 35-40 words taken from random public lab notes
lemmatize_1
lemmatize_2

Thanks!

### CODE REVIEW

**Comment by shubhscoder** [comment]
Someone please add the in-progress label to this. Thank you so much!

**Comment by shubhscoder** [comment]
@ebarry do you this could solve our issue? Or we need to implement something more?

**Comment by jywarren** [comment]
This is cool, would you like to try integrating it into the search API? Perhaps you could write an API test using one of the examples @ebarry suggested?

**Comment by shubhscoder** [comment]
Yes sure I would love to do that. Can you just tell me where should I look
in order to understand the search api part (I never worked on it before )🙈
. Thank you so much ! 😁

**Comment by jywarren** [comment]
I think this would be the place!
https://github.com/publiclab/plots2/blob/master/app/services/search_service.rb

**Comment by shubhscoder** [comment]
@jywarren I think this is ready now. Thank you so much !

**Comment by jywarren** [comment]
This is really nice! I'm going to publish this code so that we can try it out :-)

**Pull request merged**
