### PR TITLE
Signup icons position changed #3012

### PR DESCRIPTION
**Pull request by dewanhimanshu**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by dewanhimanshu** [comment]
screenshot from 2018-07-10 14-40-42
screenshot from 2018-07-10 14-40-21

**Comment by SidharthBansal** [comment]
@jywarren can you kindly review this and suggest changes? Is there anything else we want in signup view?

**Comment by steviepubliclab** [comment]
This looks great to me!

**Comment by jywarren** [comment]
Awesome, thank you so much!!! 🎉 🎉 🎉

**Comment by jywarren** [comment]
We'd love to have more help from you if you're interested! We're working on a couple bugs at https://github.com/publiclab/plots2/issues/2969 or #3013 ?

**Comment by SidharthBansal** [comment]
@jywarren so we are completed with the signup page frontend work??? OR any other changes are needed?

**Comment by dewanhimanshu** [comment]
Thank you everyone

**Pull request merged**
