### PR TITLE
login/logout flash message language changed #701

### PR DESCRIPTION
**Pull request by ykl7**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ykl7** [comment]
@jywarren Please review this PR as a fix to issue #701

**Comment by jywarren** [comment]
Thanks! I'm going through all PRs in the next couple hours, so thanks a lot!

**Comment by jywarren** [comment]
Perfect, rebasing and merged in 85822ad. Thanks so much! If you're interested in further contributing, please always feel welcome to ask for input or help. We'll be posting more soon and there are a variety available at https://github.com/publiclab/plots2/labels/help-wanted -- some better documented than others. Thanks also to @jiteshjha and @ananyo2012 for creating and documenting the original issue.

@ykl7 - I'm curious -- how did you find our project? We're trying to improve our ability to welcome new contributors, and like to better understand what works and doesn't.

**Comment by ykl7** [comment]
@jywarren I found this through up-for-grabs.net

**Comment by jywarren** [comment]
This change is now live on PublicLab.org -- thanks!

**Pull request closed without merging**
