### PR TITLE
Add Link Login Modal to Join a Group

### LINKED ISSUE #4221: Link Login Modal to Join a Group
This is a continuation of #4132. Currently, when someone wants to join a group and is prompted to signup/login, they are sent to the /login page. We want them to use the modal!
https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/grids/_people.html.erb#L35

### PR DESCRIPTION
**Pull request by dinaelhanan**
Fixes #4221 
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by dinaelhanan** [comment]
@publiclab/reviewers please review and add #4221 to GCI tasks please! :)

**Comment by SidharthBansal** [comment]
After gifs are provided, please claim the task so that you can get rewarded.
This is your similar PR 2.

**Comment by SidharthBansal** [comment]
You can submit 3 more PRS of this kind with 5 more first timer issues of similar kind with all gifs.

**Comment by dinaelhanan** [comment]
@SidharthBansal OK, I will add the gif and continue working on this tomorrow since it's getting late here. Thanks for all the help

**Comment by dinaelhanan** [comment]
@SidharthBansal I do not know where to find this feature on the website..

**Comment by dinaelhanan** [comment]
@jywarren if you've got a sec, I'm having issues finding this feature on the site so that I can prove it with a gif, do you where I would find it ?

**Comment by jywarren** [comment]
Ah - I believe you can make it appear by entering on a new line: `[people:tagname]` when at least one person has the profile tag "tagname" -- make sense? Thank you!

**Comment by dinaelhanan** [comment]
@jywarren I tried to first search using that after adding a tag to admin and it didn't work. I then tried to post and use that but it also didn't work.

**Comment by dinaelhanan** [comment]
@SidharthBansal it worked as you can see below but the return to took me to an error page:
vlcrecord2018121117h36m37s

**Comment by SidharthBansal** [comment]
>>see below 

where? I think you missed to attach gif. Please sign up with email and password. Don't use OAuth Providers.

**Comment by dinaelhanan** [comment]
@SidharthBansal I tried to attach gif but it was too large, I signed up using username and password for admin but it wouldn't work

**Comment by SidharthBansal** [comment]
Please upload on google drive and provide sharable link so that we can help

**Comment by dinaelhanan** [comment]
@SidharthBansal ok so this is what I'm getting:
https://drive.google.com/file/d/13XZ2wdlIuxs4Y34DkWut5IeV6KBi7Xqd/view?usp=sharing

**Comment by dinaelhanan** [comment]
@SidharthBansal I've linked the video outlining the changes. I think this can be merged. Thanks!

**Comment by SidharthBansal** [comment]
Please wait. We will be merging the integration of modals first.

**Comment by SidharthBansal** [comment]
@dinaelhanan  can now continue to work on this issue.
#4902 is merged now. Please merge master into this branch before proposing your changes.

**Comment by dinaelhanan** [comment]
@SidharthBansal Ok I tried to. If I did it wrong please let me know :+1:

**Comment by SidharthBansal** [comment]
Please merge master and check the behaviour again

**Comment by dinaelhanan** [comment]
@SidharthBansal OK here's the link to the video of it working:
https://drive.google.com/file/d/1aQqtYxpYDxWvnieTxo7i21xERCCbKbhj/view?usp=sharing

**Comment by gauravano** [comment]
Hi @SidharthBansal @dinaelhanan I can't see any change related to "Join this group" button. There is only one minor change present. @SidharthBansal please review the changes. Thanks!

**Comment by dinaelhanan** [comment]
@SidharthBansal I thought I did that for the video? I added  [people:water] to the post, then tried to join without being logged in and was sent to the modal. Then, I used the button and on the admin profile it showed it was following the water tag. Is that what I was supposed to do?

**Comment by SidharthBansal** [comment]
In the recent week we have many merged for the `OAuth` milestone.
So, I will suggest you to please start working on this issue from very beginning. I think the issue is solved in some other PR.

**Comment by dinaelhanan** [comment]
@SidharthBansal it was fixed in #4246. I have closed the issue. Thanks!

**Comment by SidharthBansal** [comment]
Thanks

**Pull request closed without merging**
