### PR TITLE
refactor line 216 in profile.html.erb

### LINKED ISSUE #4342: Refactoring profile.html.erb code pt.2
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

Our code in `app/views/users/profile.html.erb` is very verbose... we could use some refactoring

We can start by refactoring out a re-occuring line from the code. For now, the 1st line of:

https://github.com/publiclab/plots2/blob/1931439c0c799b3e3420a9dcaace7a54cf895bd4/app/views/users/profile.html.erb#L216-L223

## Solution

What to change it to: 

Refactor the line in the code block found in the "The Problem" section to use your new helper method instead. 

That line can be updated to `<% if current_profile_user %>`

Thanks!!

## Steps to Fix
 
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by dave-light**
Fixes #4342 

* [✔️  ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✔️ ] PR is descriptively titled 📑
* [✔️ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by dave-light** [comment]
Hi @publiclab/reviewer, my build is failing. Travis doesn't show why?

**Comment by oorjitchowdhary** [comment]
Checks passed! 🎉
@publiclab/reviewers please review this one

**Comment by SidharthBansal** [comment]
Current_profile_user can you explain where this function is implemented?

**Comment by SidharthBansal** [comment]
So that I can verify that it is working properly.
Well done both of you.
Thanks all

**Comment by dave-light** [comment]
Hi @SidharthBansal, I'm a little confused, sorry. Looks like @capedcrusader23 has implemented it in Application controller? Would I need to do this also?

**Comment by SidharthBansal** [comment]
Just give me the link to the implementation
Thanks

**Comment by SidharthBansal** [comment]
No need to implement.

**Comment by dave-light** [comment]
https://github.com/publiclab/plots2/pull/4355/files/6b330f43b5cf279897d5b3d40e3174eeeec1e2af

**Comment by SidharthBansal** [comment]
@shashadev-sky can you please help me. You created the issue so you know
better of code.

**Comment by SidharthBansal** [comment]
This looks good to me.
You can try out help wanted issues from the issue tracker.
Thanks

**Comment by gauravano** [comment]
Nice work @dave-light! We would love to have your help on other issues, if you are interested in solving more issues, you can find them at https://code.publiclab.org/#r=all

**Pull request merged**
