### PR TITLE
Draft display on Dashboard

### LINKED ISSUE #2667: PLANNING ISSUE: Draft Feature
Hi @jywarren @steviepubliclab,

**I want to inform you guys that my exams are scheduled from 21st May to 6th June, so I wouldn't be able to do much in that time period. I would be available for task discussions/calls/messages. I will try to open and solve small issues in-between exams. So, I would try to do as much work as possible till 18th May and possibly we would be done with this issue till then.** 

Issue progress: #2307 contains checklist but some more points need to be added and discussed that's why I opened this issue. Most of Back-end for this feature is ready #2308. 

Remaining Tasks:

1. [x] Displaying Draft on author's, moderator and admin's dashboard (Solved in #2666 )
2. [x] Change in `_node_default.html.erb` and `_node_meta.html.erb` to distinguish draft from normal notes as we do for first-timer posts (Solved in #2747 )
3. [x] Addition of "draft" field in output data of PublicLab editor object (Solved in https://github.com/publiclab/PublicLab.Editor/pull/138 ) 
4. [x] Addition of checkbox and JavaScript function in `rich.html.erb` (Solved in #2747 )
5. [x] Addition of "Draft" label on `notes/show.html.erb`  (Solved in #2682 )
6. [x] Publish_draft method in the controller (Solved in #2747 ) 
7. [x] Addition of Publish button on `notes/show.html.erb`   (Solved in #2747 ) 
8. [x] Adding tests for publish method and the overall test of feature (In progress in #2747 )
9. [x] Writing wiki page about the draft feature
10. [x] An alert at the top of a draft page that offers a shareable link to the post for sending around
11. [x] Like, a secret URL token that allows access to the post even if someone doesn't have an account?

I have tried to divide the issue in minimum part as possible, I can solve 2,4,5,6 and 7 in a single PR or multiple, but I see that some parts can be good FTO candidates like 2,3,5 and 7. What do you guys think, should I open FTO's or not ? Thanks.

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2667 (1st part) 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! Awesome. Could you post a screenshot?

Also maybe we could get dangerbot to ask for a screenshot if any views have
changed!

**Comment by Gauravano** [comment]
@jywarren no view is changed in this PR, I just changed a query so that research note would be visible to the author, moderator and admin only on their dashboard. Although, a warning would be displayed at top of research note which would be like 

warn_top
Suggestions about warning text are welcome : ) 

Nice idea, we can check if `.html.erb` is changed in PR and then generate message accordingly.

**Comment by jywarren** [comment]
Oh ah cool! Could we make "publish draft" the text be a button itself? Let
me think on the text. Awesome!

**Comment by Gauravano** [comment]
yes, that would go as a button like we show approve button to the moderators.

**Comment by Gauravano** [comment]
hi @jywarren, please review this one, after merging this PR and https://github.com/publiclab/PublicLab.Editor/pull/138/ . I would like to push some commits on `unstable` branch, which would be last step of draft feature. Thanks.

**Comment by jywarren** [comment]
This looks good - do you think we should add an override for admins? Or maybe more importantly for coauthors, so people can share drafts? 

THANKS! The idea of testing this out on `unstable` is great. 👍 👍 👍

**Comment by jywarren** [comment]
Agreed!

**Comment by Gauravano** [comment]
Can we merge this now?

**Comment by jywarren** [comment]
Fantastic!!! 🎉

**Comment by Gauravano** [comment]
hi @jywarren @icartio, I guess I have messed up a little on `unstable`, the commits you pushed are over-ridden by this PR. Could you help me there? :disappointed:

**Comment by jywarren** [comment]
Hi, @Gauravano so `unstable` is a "throwaway" branch - we regularly delete things that've been pushed there. The idea is to push things there for testing and then if we like them, merge them into master. Usually `unstable` has a few throwaway commits on top of the latest `master`.  Make sense? No problem - usually people force push commits to `unstable`, try it out, and then don't care what happens after. Just communicate in the chatroom before pushing to `unstable` to see if anyone else is using it.

**Comment by Gauravano** [comment]
hmm... thanks @jywarren for clarifying :sweat_smile: :relieved:  . Ok, then I am pushing all parts of the draft feature on `unstable`. And, yes, notifying others in the chatroom. Thanks again !!

**Pull request merged**
