### PR TITLE
Follow user by Follow button on notes

### LINKED ISSUE #2088: Author subscription system
### Please describe the problem (or idea)
We cant follow a node author even though it states that we can follow by tag or author.

> What did you expect to see that you didn't?

Clicking on author name did not do anything , it should either redirect to user's profile or directly make the current user follower of the author.

### Please show us where to look

https://publiclab.org/ ...
screenshot from 2018-01-24 19-45-22

### What's your PublicLab.org username?

> This can help us diagnose the issue: rish

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2088 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
Hi @jywarren , please review the changes. Thanks.

**Comment by jywarren** [comment]
Looks great -- have you tried it out locally? I think the user following system is little-used. 

Thanks!!!

**Comment by Gauravano** [comment]
Yes! it's working fine, locally. 

follow_user2

We can expand use of this system by sending notifications to followers about the activity of person they follow. What do you think?

**Comment by jywarren** [comment]
> sending notifications to followers about the activity of person they follow

That sounds GREAT!

**Comment by jywarren** [comment]
But perhaps we need to start listing `people you follow` on `/subscriptions` first?

**Comment by Gauravano** [comment]
Any idea where on subscriptions page we should add a section to display Followers?

**Comment by jywarren** [comment]
maybe we need 2 tabs on that page? Tags and People ?

**Pull request merged**
