### PR TITLE
Added a route to redirect requests to /question to /questions (fixes #3247)

### LINKED ISSUE #3247: redirect /question to /questions
I'm worried people are ending up on the www.publiclab.org/question which redirects you to www.publiclab.org/tag/questions. I think people who go to this page are probably trying to get to www.publiclab.org/questions. Can we get a redirect set up for that page?

### PR DESCRIPTION
**Pull request by shubhscoder**
Initially www.publiclab.org/question took the user to www.publiclab.org/tag/questions which was not expected. After the addition of the route the user is appropriately redirected to www.publiclab.org/tag/questions

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
@steviepubliclab does this look OK, that /question will just ALSO display the same content, rather than redirect?

**Comment by jywarren** [comment]
Let's go ahead and merge this and we can do something different later if it doesn't work out! Thanks so much for your contribution! We'd love to work more with you if you're interested. This was great. 👍 👍 👍

**Comment by shubhscoder** [comment]
Thank You! I ll pick up some more issues and try to resolve them!

**Comment by jywarren** [comment]
Oh awesome. I just posted a couple bugs I would love some help with if
you're interested!!

**Pull request merged**
