### PR TITLE
Updated-2-wiki-controller.rb

### PR DESCRIPTION
**Pull request by CoderJolly**
The changes are done as proposed

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by CoderJolly** [comment]
PR generated for #3027 aftr doing the changes as follows:

screen shot 2018-07-12 at 3 28 35 am

**Comment by Gauravano** [comment]
@CoderJolly you need to push these changes to #3037

**Comment by Gauravano** [comment]
the above changes are for resolving travis errors as shown in #3037

**Comment by CoderJolly** [comment]
My Bad.....can i do it by d morning ?

**Comment by Gauravano** [comment]
Sure! Do you know how to add commits to other's PR?

**Comment by CoderJolly** [comment]
I dont bt i want to figure it out by myself first, den i will ask u....

**Comment by Gauravano** [comment]
Ok, give it a try -- just breaking it for you
1. You need to fetch #3037 
2. Do changes to it as mentioned here https://github.com/publiclab/plots2/issues/3027#issuecomment-404321676
3. push the changes

You can ask me anytime. Thanks!

**Comment by Gauravano** [comment]
Please close this PR.

**Comment by CoderJolly** [comment]
Done @Gauravano , thnks for ur esteemed support....

**Pull request closed without merging**
