### PR TITLE
Add dropdown for spam button in questions tag page

### LINKED ISSUE #7543: popover stays on screen after clicking spam
In some tag link like  https://publiclab.org/questions/tag/air-quality
on clicking on spam button a popover appears which stays there even after clicking. It gets removed only after scrolling as shown 
Screenshot from 2020-02-20 01-58-29
 
Thanks

### PR DESCRIPTION
**Pull request by sakshi-2412**
Fixes #7543 

Added a dropdown for spam button in questions tag page (eg: https://publiclab.org/questions/tag/air-quality)

https://user-images.githubusercontent.com/85152262/151198404-69eaf084-c92c-44b8-93b8-585d5a22ba73.mp4

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by govindgoel** [comment]
@sakshi-2412 can u verify that it is responsive in diff. screen sizes. Thanks

**Comment by govindgoel** [comment]
Also I have restarted all the jobs

**Comment by sakshi-2412** [comment]
@govindgoel the parent dropdown seems to be overflowing in the right for smaller screens. 

https://user-images.githubusercontent.com/85152262/151295026-d2ec8188-8b53-4893-b3cd-6502014dc6da.mp4

Maybe we can make it a [right-aligned menu](https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment)

https://user-images.githubusercontent.com/85152262/151293730-b0387ffa-89f4-422e-8e7f-144de28f6b88.mp4

**Comment by sakshi-2412** [comment]
Also, I am not able to understand where comment-system-tests are failing 🤔 can you please help me with that
It says 
`/home/runner/work/_temp/9f817bcd-5155-4eb3-b893-8f414b284269.sh: line 3:  2552 Aborted                 (core dumped) bundle exec rails test `

**Comment by govindgoel** [comment]
right-aligned-menu approach looks better.

**Comment by sakshi-2412** [comment]
> right-aligned-menu approach looks better.

Okay, I'll make the changes ✨

**Review by TildaDares — APPROVED** [review]
This looks good. Thanks @sakshi-2412

**Review by govindgoel — APPROVED** [review]
LGTM!

**Pull request merged**
