### PR TITLE
temp Fix for popover overflow with ellipsis

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5609 https://github.com/publiclab/plots2/issues/5610

### Earlier 
Screenshot from 2019-06-07 16-09-51

Screenshot from 2019-06-07 16-59-26

### After Changes
Screenshot from 2019-06-07 16-09-33

Screenshot from 2019-06-07 16-55-06

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @sashadev-sky 
For now, This would be a temporary fix using css property overflow. What do you say ?

**Comment by sashadev-sky** [comment]
@publiclab/reviewers

**Comment by CleverFool77** [comment]
> Ran this locally and confirming your update :) I think its ready for merge. Would you like to open a new issue in the meantime addressing a backend character limit, or maybe adding a way to see whole the tag on hover?
> 
> Just noticed that long tag names will also extend the width of the page! So we could mention this there too
> 
> Screen Shot 2019-06-07 at 6 57 45 AM

Oh yes!! Thanks @sashadev-sky I'll look into the matter of tags on page and fix it. Regarding the matter of adding a way to see whole the tag on hover?. How about I open this Issue once this PR gets merged. What do you say ?

**Comment by CleverFool77** [comment]
@sashadev-sky Just updated the temp fix for sidebar tags. So it won't overflow leading to increase in width of page.

**Comment by sashadev-sky** [comment]
@CleverFool77 Yeah I know thats perfect! I was just pointing things out we could create for a followup issue

**Comment by jywarren** [comment]
Is this one good to merge now? Thanks!!

**Comment by CleverFool77** [comment]
Hi @jywarren This is ready for merge I guess.
Thanks !!

**Pull request merged**
