### PR TITLE
Fix text overflow bug in editor

### LINKED ISSUE #9476: Text overflows in editor (rich mode)
### Problem

When using the editor's Rich mode (i.e. wysiwyg) the text does not wrap around inside of the text area, but instead overflows and causes visual bugs.

image

### Where to find this bug

https://publiclab.org/post

### How to reproduce

Use the editor's "Rich" mode and type in a long string of characters (no new lines)

### PR DESCRIPTION
**Pull request by eightballocto**
Fixes #9476 (text did not wrap before addition of CSS rule), thanks @aliciapaz

### CODE REVIEW

**Review by sahilsaha7773 — COMMENTED** [review]
Hi @eightballocto! Thanks for opening this! Can you please attach a screenshot?

**Comment by eightballocto** [comment]
@sahilsaha7773 Sure, here's the result after adding the rule 
image

However, it seems like this only *partially* fixes the issue, because I notice that long strings of something like say, ellipses,
..results in this.
image

My initial theory is that this is an issue with margins, and so I will further investigate when I can.

**Comment by eightballocto** [comment]
Turns out I had added the rule to the wrong selector, latest commits should fix this definitively :) 
image

**Comment by jywarren** [comment]
Awesome work!!!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Congrats!!! Thank you!!!

**Pull request merged**
