### PR TITLE
migration for changing following to true for all rows of NodeSelection

### PR DESCRIPTION
**Pull request by gauravano**
Part 2 of #1610 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
OK, i'll run `NodeSelection.where(following: true).count`!

**Comment by gauravano** [comment]
You mean `NodeSelection.where(following: false).count` as we need to ensure that there are 0 nodeSelection entries with following = false

**Comment by gauravano** [comment]
Thanks!

**Comment by jywarren** [comment]
Great, `NodeSelection.where(following: false).count` returned 0!

**Comment by gauravano** [comment]
Awesome :tada: ! Creating PR for completing this setting then. Thanks!

**Comment by jywarren** [comment]
This is published!

**Comment by gauravano** [comment]
Hi @jywarren! Hope you had great vacations. Good to see you back. Sorry, I wasn't able to complete my last setting until now, due to the college placement going on. I will try to complete it as soon as I get some free time. Thanks!

**Comment by jywarren** [comment]
ok, and good luck! Thanks, it's good to be back in touch with you all.

**Pull request merged**
