### PR TITLE
Update _wikis.html.erb

### PR DESCRIPTION
**Pull request by Atifirshad**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
Hey @Atifirshad, you were supposed to claim the issue before making a PR. I have asked the contributor who've claimed this issue and if they are fine giving-up on this one, then we'll consider your PR. Thanks!

**Comment by SidharthBansal** [comment]
@gauravano what is the pr number?

**Comment by SidharthBansal** [comment]
Oh it is #5385 
Can we merge this pr?

**Comment by SidharthBansal** [comment]
LGTM 
@jywarren can we merge this pr?

**Comment by jywarren** [comment]
Looks great!!! Thank you so much!

**Pull request merged**
