### PR TITLE
Display RTE when editing notes by default (Fixes #1141)

### LINKED ISSUE #1141: Display rich editor when editing a research note
We now default to the rich editor on https://publiclab.org/post (needs login), but not when editing a note. 

We have a switch in the controller to use the rich editor:

https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L154

We should now reverse this, so that the rich editor is default, and the legacy editor is only used if the URL includes `params[:legacy]` -- as we've done here:

https://github.com/publiclab/plots2/blob/master/app/controllers/editor_controller.rb#L34

We should display a notice on the edit page inviting authors to use the legacy editor, too, placing this line just before the `render` line in the controller:

```ruby
    flash.now[:notice] = "This is the new rich editor. For the legacy editor, <a href='/notes/edit/#{@node.id}?#{request.env['QUERY_STRING']}&legacy=true'>click here</a>."
```

These changes will break some tests, most likely, but that's a good thing -- it'll confirm that we've made the changes. When submitting a pull request for this, observe the tests fail, then I'm happy to help you adjust the tests to the new behavior. 

Thanks!

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Will now look into the test results from the CI. In the meantime, please look if the changes look alright?
Thanks

**Comment by ryzokuken** [comment]
Fixes #1141

**Comment by jywarren** [comment]
Looks great!

**Comment by ryzokuken** [comment]
1. `test_should_display_/post_template_when_editing_a_note(NotesControllerTest)`
2. `test_should_display_/post_template_when_editing_a_question(NotesControllerTest)`

Are the tests that failed.

`  Expected at least 1 element matching "input#taginput[value='blog']", found 0. `
Quite naturally, the test looks for inputs with id `taginput`. I suppose we keep both the tests for legacy controllers, and write new tests for the RTE, right?

**Comment by jywarren** [comment]
Sure, and perhaps you could look at the /post tests to see how we changed
those. Thanks!

**Comment by ryzokuken** [comment]
@jywarren Changed the tests to work in legacy mode. Let's hope all tests pass now. In the meantime, i'll look into the tests for /post

**Comment by ryzokuken** [comment]
@jywarren Would probably need some help finding which specific tests for the editor_controller are specific to the RTE

**Comment by ryzokuken** [comment]
@jywarren Aaand... they passed. So the legacy option seems to be working fine, but I'd probably need your help making the new tests

**Comment by jywarren** [comment]
I believe you can copy the tests you've changed but remove the legacy
parameter -- and adjust the assert_select to the appropriate HTML for the
rich editor template, does that make sense? So I don't know if the rich
editor has the "taginput" selector, but the tags should still appear. Can
you confirm this by editing a note? Thanks!

**Comment by ryzokuken** [comment]
@jywarren The entire thing (the RTE) is a div with class `pl-editor`. I guess I could look if that div has been rendered?

**Comment by ryzokuken** [comment]
* grabs popcorn *

**Comment by ryzokuken** [comment]
@jywarren Finally, we made it. :P
Please look into it whenever you get the time. Looks like I'd be a Rails Jedi soon (I almost found and troubleshooted the issues myself)

**Comment by jywarren** [comment]
Super! Great work, you are indeed becoming a Jedi!

**Pull request merged**
