### PR TITLE
Change to https:// at app/models/drupal_content_type_map.rb

### LINKED ISSUE #8587: Change http:// to https:// in several places (Fix for #6391)
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing! This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :nerd_face: A little background:

Basically we need to remove http:// and replace it with https:// in multiple files, so that the site can continue to load content as normal. See below and issue #6391 for more information.

> Chrome will soon start blocking any http content loaded from an https page - not just scripts and iframes, but images, etc.
> [https://www.bleepingcomputer.com/news/google/google-chrome-to-gradually-start-blocking-mixed-content-by-default/](https://www.bleepingcomputer.com/news/google/google-chrome-to-gradually-start-blocking-mixed-content-by-default/)

### ✒️ What to Change

There are a few places in the codebase where we can make this change. Please select **ONE** file to make a pull request (more info below), and leave the rest for other first-timers!

- [ ] **tools_places.html.erb**:
https://github.com/publiclab/plots2/blob/76f000c8dcc82576910590f9699c92256179c20e/app/views/notes/tools_places.html.erb#L9
- [ ] **db/seeds.rb**:
https://github.com/publiclab/plots2/blob/76f000c8dcc82576910590f9699c92256179c20e/db/seeds.rb#L75
- [x] ~~**notify_moderators_of_comment_spam.html.erb**~~: claimed, awaiting merge in #8593 

### What Do I Do If Everything's Been Taken?
You can search this repository for instances of "http" like so:
Untitled 3

Leave a comment here if you find one!

### Completed - Please do not claim these! They have already been completed.
- [x] ~~**drupal_content_type_map.rb**: merged in #8666~~ 
- [x] ~~**notify_moderators_of_spam.html.erb**: merged in #8669~~
- [x] ~~**_history.html.erb**: merged in #8653~~

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Make a comment on this page, claiming one of the files above. If someone else has already claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file you've chosen by navigating to it. You can edit the line directly by clicking on the little pen icon.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by yashmohan100**
Fixes #8587  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by sagarpreet-chadha — APPROVED** [review]
Awesome 🎉

**Comment by cesswairimu** [comment]
restarting travis

**Review by RuthNjeri — APPROVED** [review]
Looks good to me @yashmohan100!

**Comment by jywarren** [comment]
Travis keeps getting stuck! 😱 

I'll restart it one more time, fingers 🤞 !!!

Thank you!

**Comment by cesswairimu** [comment]
Hi @yashmohan100 could you please try rebasing, or create a branch and make the PR from there? we normally don't create PRs off of one's main branch. Thanks

**Comment by yashmohan100** [comment]
> Hi @yashmohan100 could you please try rebasing, or create a branch and make the PR from there? we normally don't create PRs off of one's main branch. Thanks

Sure wont be an issue, will make a branch.

**Comment by cesswairimu** [comment]
Accepted this PR https://github.com/publiclab/plots2/pull/8666 because there has been no update here for a while. Thanks everyone. Closing this

**Pull request closed without merging**
