### PR TITLE
Upgrade bootstrap-lightbox to v0.7.0

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Ah, i believe we have to adjust the includes too:

```
ActionView::Template::Error: couldn't find file 'bootstrap-lightbox/build/bootstrap-lightbox.min.js'
  (in /app/app/assets/javascripts/application.js:18)
/app/lib/tasks/test.rake:10:in `block (2 levels) in <top (required)>'
Sprockets::FileNotFound: couldn't find file 'bootstrap-lightbox/build/bootstrap-lightbox.min.js'
  (in /app/app/assets/javascripts/application.js:18)
```

**Comment by ryzokuken** [comment]
@jywarren Fixed it :)

Sorry for the delay.

**Comment by jywarren** [comment]
Hi, I'm going to merge to stable so we can see it build -- can you test it out?

**Comment by jywarren** [comment]
As soon as it's done building here: https://staging.laboratoriopublico.org

You can try it out here: https://testing.laboratoriopublico.org

**Comment by jywarren** [comment]
https://testing.laboratoriopublico.org/notes/elainechoi89/7-5-2012/tyvekbamboo-kite-workshop-pfizer-building-brooklyn-ny

**Comment by ryzokuken** [comment]
@jywarren looks like something went wrong... Perhaps you could post the log in here? I could check if I'm missing something. This version of bootstrap-lightbox does not contain a CSS. I think that might be our problem.

**Comment by ryzokuken** [comment]
Oh, or it could be that the testing server doesn't have the pictures locally :P

**Comment by jywarren** [comment]
I think perhaps we should just go ahead with this -- it can't get worse than broken :-)

we can monitor it once it's published later this week, and close/reopen as needed. Thanks!

**Comment by ryzokuken** [comment]
@jywarren Sure, sounds great.

**Pull request merged**
