### PR TITLE
RSS feed on tagged content for author pages

### LINKED ISSUE #2149: RSS feed on tagged-content-for-author pages needs to be built
Profile pages like https://publiclab.org/profile/cfastie now show some great links to, for example, all content tagged as an activity for a given user --

https://publiclab.org/tag/activity:*/author/cfastie

However, the RSS feed on that page is a generic feed for activities, not just `cfastie`'s:

https://publiclab.org/feed/tag/activity:*.rss

We need an RSS feed for this. It can be based on this one, which is the generic "all content for this tag" feed:

https://github.com/publiclab/plots2/blob/34935fb011a2982968c6a2e0b049eeb2aa791c78/app/controllers/tag_controller.rb#L324-L347

Any help with this would be appreciated! The new feed should probably be at: 

`https://publiclab.org/feed/tag/activity:*/author/_AUTHORNAME_.rss`

Thanks!

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #2149

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Hi @SidharthBansal  , this looks great !

However take a look at PR #2162 , for correct format of **IMAGES** . Thanks !

**Comment by SidharthBansal** [comment]
@sagarpreet-chadha Thanks will change it now.

**Comment by SidharthBansal** [comment]
@sagarpreet-chadha shall I also change the images in the views/tag/rss.rss.builder? or are you working on it?

**Comment by sagarpreet-chadha** [comment]
@SidharthBansal , thanks for asking 😄 ! 
No i am not currently working on that file 👍 .

**Comment by SidharthBansal** [comment]
Ok then I will also change it in other pr. Thanks @sagarpreet-chadha

**Comment by SidharthBansal** [comment]
@sagarpreet-chadha I have made the changes in accordance with your pr's images.
Please review them
Thanks

**Comment by sagarpreet-chadha** [comment]
Awesome !

**Comment by jywarren** [comment]
This looks super. Maybe at some point we should look at using partials to reduce redundancy between RSS templates... i've never done that but i'm thinking of the DRY (don't repeat yourself) principle here. But this looks great and thanks for good tests!

**Comment by SidharthBansal** [comment]
@jywarren Yeah we should do the DRY thing. I will make a new PR for the views/tag/RSS.RSS.builder and this one as soon as I can. Also, I have encountered many places where we should use helpers inside the views for making our code clean. May be these are not necessary now.

**Pull request merged**
