### PR TITLE
blog page pagination aligned to center

### LINKED ISSUE #3957: https://publiclab.org/blog in this page pagination is not center to the body
https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/tag/blog.html.erb#L77

### PR DESCRIPTION
**Pull request by abizerlokhandwala**
Fixes #3957  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@abizerlokhandwala Could you please attach a screenshot/gif to display and confirm your changes..

**Comment by oorjitchowdhary** [comment]
Thanks for your PR..

**Comment by abizerlokhandwala** [comment]
> @abizerlokhandwala Could you please attach a screenshot/gif to display and confirm your changes..

Sure, here is a screenshot showing the center align of the pagination  
screenshot from 2018-11-22 23-46-44

**Comment by jywarren** [comment]
🎉

**Comment by jywarren** [comment]
Thanks so much!!!

**Pull request merged**
