### PR TITLE
Building profile page as per new style guide

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5891 part

- [x] Change column span and bring map to right
- [x] Add topic cards for profile page
- [x] Add information in right column

### CODE REVIEW

**Comment by CleverFool77** [comment]
HI Jeff !!!
before merging this I guess we have to wait till we have another PR for notes card as right now decreasing the first column had made them way too smaller.

Screenshot from 2019-07-06 18-04-43

**Comment by jywarren** [comment]
Looks awesome. Shall we build on this before merging? Thanks! You can
actually open pull requests against this branch and we can group them
(merge them into each other) before merging to master!

**Comment by CleverFool77** [comment]
> Looks awesome. Shall we build on this before merging? Thanks! You can actually open pull requests against this branch and we can group them (merge them into each other) before merging to master!

This is possible ? Like merging PRs together ?

**Comment by CleverFool77** [comment]
yes!! 
Even I wanted to say the same that we'll build this profile page first before merging them altogether.
Thanks !!

**Comment by jywarren** [comment]
Yes, it is possible - you can determine which branch you want a PR to be
opened against, and you can select a branch that is a second PR, actually!
Then they merge together, but the final PR is against the master branch.
Make sense?

**Comment by CleverFool77** [comment]
Hi @jywarren I wasn't able to understand that how we are suppose to make a new PR against a same branch. Instead I have added code for new topic cards for profile page in this PR only with a different commit.
Below is the gif: 

topiccard


cc: @gautamig54

**Comment by CleverFool77** [comment]
Hi @gautamig54 Can We take this PR as main PR for building the profile page and open the PR against this branch called `profile` with different commit.
What do you say ?

**Comment by CleverFool77** [comment]
Hi @gautamig54 @jywarren On what basis, do we want topic cards to be shown ? For now I've shown all the topic cards but we do have to filter them right !! So Is it based on no of notes ?

**Comment by CleverFool77** [comment]
For now, I would commit all the parts of profile page in this PR instead of making new PR every time. 
Is there any suggestions regarding topic cards that I have added for now ?
cc: @gautamig54 @jywarren

**Comment by CleverFool77** [comment]
Hi @jywarren ust pushed another change for info being shown in left sidebar.
Thanks !!
ss attached:
Screenshot from 2019-07-25 19-00-01

**Comment by jywarren** [comment]
Really great. Super! Ready for a final review and merge?

**Comment by CleverFool77** [comment]
Hi @jywarren I'll do some more fixes for test and then lets merge it.

**Comment by CleverFool77** [comment]
Awesome !! All test cases passed.

**Comment by CleverFool77** [comment]
Should I make the tags in right sidebar directly over left column above topic cards ? As they are chosen by user itself. or should I pick up most used tags for it ? :thinking:

**Comment by CleverFool77** [comment]
Hi @jywarren Even this PR is ready, Regarding further changes in profile section. Those will be followed up in next PR.
Thanks !!!

**Comment by jywarren** [comment]
Awesome!!! Great work.

**Pull request merged**
