### PR TITLE
Error messages for rich editor

### LINKED ISSUE #2141: Error in flash messages condition
### Please describe the problem (or idea)
The condition inside the if will give error if any of the @node or @revision is nil
> What happened just before the problem occurred? Or what problem could this idea solve?
We need to tackle this in separate if-else loop
### Please show us where to look
https://github.com/publiclab/plots2/blob/097605afe74fa63f6fa5c3de3fbd081fa0d2e2c1/app/views/editor/rich.html.erb#L221-L223
https://publiclab.org/ ...

### What's your PublicLab.org username?
bansal_sidharth2996

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by SidharthBansal**
resolved #2141
Without this it will give an error --> undefined method errors on nil object as it may be that one of the two is nil

### CODE REVIEW

**Comment by jywarren** [comment]
This looks cool but is a little tough to read! Do you think this is the most efficient way to implement it? Is there any way to merge them even if they're empty, and then display the merged errors no matter what, instead of having 3 possible options? 

Just an idea. If not, i'm happy to merge this. Thank you!!!

**Comment by SidharthBansal** [comment]
OK. I will redactor it.

**Comment by SidharthBansal** [comment]
The main problem is we cant apply the `.errors` on `nil`. If by any way I try to merge them together then I need to use the errors method which we should not.
One solution is to use ternary operator but for some, it is hard to read while others like it. Shall I use the ternary operator if you like them?

**Comment by jywarren** [comment]
No, i guess i agree this is more readable than ternary. Shall we go ahead and merge then?

**Comment by jywarren** [comment]
Thanks for giving it a little extra thought!

**Comment by SidharthBansal** [comment]
Yeah sure.

**Pull request merged**
