### PR TITLE
Loader indicator during page loads

### LINKED ISSUE #3734: a preloading page before every page loads
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

### Problem
Building a preloading page to enhance the behaviour of loading of html pages such that whenever a page loads a preloading page shows and on complete loading main html body shows.

## Solution
You may find solution here
http://www.marketingformavens.com/blog/create-a-page-loading-animation-with-ruby-on-rails-and-ajax

or here

https://stackoverflow.com/questions/31505506/how-to-show-page-loading-between-pages 
## Code here
https://github.com/publiclab/plots2/blob/cc2df02a63b72cca7b1129aa3044933abf614a50/app/views/layouts/application.html.erb#L57

## Thank you!

 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #3734 
@publiclab/mentors 

Here is the working
loading 1

loading 2

loading 3

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
Sorry for a 4th PR for a same issue.. I actually messed up in #4063, #4031 and #4020 through Git.. I was trying something which didn't work out...

**Comment by oorjitchowdhary** [comment]
@sidharthbansal @jywarren

**Comment by jywarren** [comment]
Just wondering, does this hide existing page content or is the spinner displayed over whatever page content has loaded so far? Thank you!

**Comment by oorjitchowdhary** [comment]
Until the page hasn't loaded fully, a div over the page comes up and shows the loader.

**Comment by jywarren** [comment]
Could we do 2 things, one is have the spinner overlay but the div be only
10% opacity, and second, have it disappear when you click it, in case it
gets stuck? Then I'll be much more confident about it not interfering in
case anything goes wrong. Thanks!!

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab
@jywarren @gauravano

**Pull request closed without merging**
