### PR TITLE
Added :edit to before filter in users_controller.rb

### PR DESCRIPTION
**Pull request by rob4abcba**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by rob4abcba** [comment]
I checked all 5 checkboxes.  Is that ok?

**Comment by rob4abcba** [comment]
Additional workflows 

Rewinding the master branch 

Sometimes you forget to make your commits on a named feature branch, and add commits to your master branch. You want to rewind the master branch back so you can pull in the latest changes from others, but you don't want to lose your work! It's all right, though -- you can follow these steps to rewind, update, and rebase your changes on top of the latest commits to Public Lab's master branch (shown here for the plots2 repository):
   
   - git checkout master - go back to your master branch (your work is saved in the feature branch)
   - git reset --hard 123456 -- rewind your master branch to a state before it diverged from our master (where 123456 is the commit hash just before your commits -- the latest one your history has in common with the publiclab/plots repository's history)
   - git pull https://github.com/publiclab/plots2.git master -- fetch publiclab's latest master
   - git checkout feature-branch-name -- go back to your saved feature branch, named something more descriptive than feature-branch-name
   - git rebase master -- this just detaches your latest changes (minus the deleted one) and reattaches or "replays" them onto the latest master. If you see merge errors, try following this guide to resolve them.
   - git push origin feature-branch-name -- push up your newly re-based changes! (you can use git push -f origin feature-branch-name forces, to overwrite a PR if you've already opened one)
   - Go to https://github.com/publiclab/plots2 to look for the prompt to open a PR if you haven't already.

 

    On Thursday, March 29, 2018, 3:29:35 PM PDT, PublicLabBot <notifications@github.com> wrote:  
 
 
|  |  1 Error  |
|  🚫 | There was a test failure at: Failure: test_edit_profile_route_when_user_logged_out_redirects_to_profile_page(Minitest::Result) [/app/test/integration/routes_test.rb:30]: Expected: “/profile/jeff” Actual: “/login” |


|  |  2 Messages  |
|  📖 | @rob4abcba Thank you for your pull request! I’m here to help with some tips and recommendations. Please take a look at the list provided and help us review and accept your contribution! And don’t be discouraged if you see errors – we’re here to help. |
|  📖 | Your pull request is on the master branch. Please make a separate feature branch) with a descriptive name like new-blog-design while making PRs in the future. |


 Generated by 🚫 Danger

**Comment by seafr** [comment]
The second commit is redundant. You can remove it with `git push --force ...`

**Comment by sagarpreet-chadha** [comment]
Fixes #2554 .

**Comment by seafr** [comment]
This PR is breaking 1 integration test for now, and will also break a functional test once #2545 is merged. I'll take care of this in a separate PR as this is a first-timers PR.

**Comment by seafr** [comment]
Please ignore this PR. It is related to #2562 which is ready to be merged.

**Comment by seafr** [comment]
@sagarpreet-chadha please review #2562 instead. Thank you.

**Pull request closed without merging**
