### PR TITLE
Keep grid image's original ascpect ratio

### LINKED ISSUE #4082: Images distorted in thumbnail grids
We have some great new thumbnail grids as shown on this page: https://publiclab.org/wiki/micro#Assembly

image

But as you can see, some images are distorted. This is solved in the dashboard templates -- https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_default.html.erb#L7 and the dashboard css:

https://github.com/publiclab/plots2/blob/e6608c89b3a7d1862d1e329e377ef8aea1e2ce90/app/assets/stylesheets/dashboard.css#L199-L204

Let's apply this to the new thumbnail grids too!

@ValentinaTironi would you mind linking to the thumbnail grid code? And would you be interested in making this into a first-timers-only issue to welcome someone else into the community? I'll paste in some guidance below:

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

### PR DESCRIPTION
**Pull request by dinaelhanan**
Fixes #4082 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by dinaelhanan** [comment]
@publiclab/reviewers :)

**Comment by jywarren** [comment]
Oh this is awesome. Could you share a screenshot to confirm? Thanks!!

**Comment by dinaelhanan** [comment]
@jywarren I'm not seeing that as a page when I go to http://localhost:3000/wiki. Here's what I get:
screenshot from 2018-12-03 15-59-39

**Comment by dinaelhanan** [comment]
@ValentinaTironi could you help me out here if you've got the chance? I'm not seeing the current posts on the wiki on my localhost..

**Comment by ValentinaTironi** [comment]
Hi @dinaelhanan, do you wanna see the thumbnail grids, right? Well, you must create or edit some note, and in the description section add `[notes:grid:tagname]`

**Comment by dinaelhanan** [comment]
ohhhh! I'll do that thanks!

**Comment by jywarren** [comment]
Ah, and per GCI rules, you can't claim 2 tasks at once, so although we're happy to have your contributions in general, please be sure you leave GCI tasks available for other. But that said, we have a bit of a backlog on reviewing, so thank you very much for your help!

**Comment by dinaelhanan** [comment]
Ok, I'll be sure to focus on the first-timers task, and I'll claim this one after that, so that I'm only working one at a time.. thanks! @jywarren

**Comment by jywarren** [comment]
No problem! Here's the task! https://codein.withgoogle.com/dashboard/tasks/6488940631556096/ 

Thank you!

**Comment by dinaelhanan** [comment]
closed because i made a new fork of the repo to work on, was having issues with the previous one. Waiting on completion of another GCI to complete this one :)

**Pull request closed without merging**
