### PR TITLE
sidebar individual tags page

### LINKED ISSUE #5890: UI Improvements Planning Issue : Individual tags page
Next we start with the implementation of individual tags page. 

Capture

**Checklist**

- [x] Divide the page into three sections(Main image and the introduction card, sidebar with map, activity cards) @gautamig54 
- [x] Adjust the main image and add the number of people following on to the right. @CleverFool77 
- [x] make an introduction card for the tag containing the subscribe and learn more options. @gautamig54 
- [x] Activity cards with new design of style guide @CleverFool77 
- [ ] ~Show map on the sidebar and people near options @gautamig54~
- [ ] Sort by name, users and people following  @CleverFool77  **Wait a bit**
- [ ] ~Post a question option with dropdown @gautamig54~
- [x] Implement type dropdown containing options for all, questions, wikis and notes related to the tag. @CleverFool77 
- [x] Add related tags @gautamig54 

cc : @CleverFool77

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5890  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
The screenshot generated here is : 

Screen Shot 2019-07-09 at 4 13 43 PM

**Comment by gautamig54** [comment]
Here it fails the system tests. Passes all the functional tests unlike the previous PR. Also, the oddness arising due to design conflicts is resolved. 
Regarding the map size, it has been fixed to `height:500px` in the map/_peopleLeaflet.html.erb
If I change it there, it will cause changed in the people's page as well.
@CleverFool77 Your reviews?

**Comment by jywarren** [comment]
It looks incredible! Hmm, maybe you can override the local height in the
template with a default? Look how I did a local variable with override in
this PR:
https://github.com/publiclab/plots2/pull/5979/files#diff-e7b109eaa2ac2beedada441b6a6a0373R2

**Comment by gautamig54** [comment]
I get something like this when I try resizing the height of the map. Its is such a small issue and I have no idea why this issue is occurring.

`<div class="people-map">`
    `<%= render :partial => "map/peopleLeaflet" , locals: {people: true , lat:23 , lon: 4} %>`
   `</div>`
    `<a href="/people" style="color:#666;"><u>See more people near here</u></a><br>`
    ` <%= render partial: "tag/show/related_tags" %>`

and I am resizing height for people-map class.

`.people-map{
   height: 200px;
   width: 100%;
   margin: 0;
   position: relative;
 }`

Screen Shot 2019-07-09 at 10 48 31 PM

@CleverFool77 Can you help here!

**Comment by CleverFool77** [comment]
Hi @gautamig54 I missed this. Now I'll fetch this PR and check it locally.

**Comment by gautamig54** [comment]
Hi @CleverFool77.  Did you try this?

**Comment by CleverFool77** [comment]
HI @gautamig54 I have some interviews recently, and because of that I was not able to check it. 
Do you mind, if I'll check it as soon as I get proper time.

**Comment by jywarren** [comment]
Wow this is a strange error, and I've actually seen something related before:

```
ERROR["test_tag_page", #<Minitest::Reporters::Suite:0x00007f4e296538c0 @name="ScreenshotsTest">, 32.924912457999994]
 test_tag_page#ScreenshotsTest (32.92s)
ActionController::UnknownFormat:         ActionController::UnknownFormat: ActionController::UnknownFormat
            app/controllers/tag_controller.rb:167:in `show'
```

```
2019-07-09 10:40:55 +0000: Rack app error handling request { GET /tag/owmloading.gif }
#<ActionController::UnknownFormat: ActionController::UnknownFormat>
/usr/local/bundle/gems/responders-3.0.0/lib/action_controller/respond_with.rb:215:in `respond_with'
/app/app/controllers/tag_controller.rb:167:in `show'
```

https://travis-ci.org/publiclab/plots2/jobs/556233903#L4184

I've seen this error appear from time to time in our logs, actually. I think somehow some component is trying to load `downloading.gif` but it's not in our repository. I really don't know how this is happening but we should search for any references to `downloading.gif` or watch the browser console to see where this request is sent out. That said, I don't think it's related to your code, and will try restarting the tests.

**Comment by jywarren** [comment]
Linking to https://github.com/publiclab/plots2/issues/5095

**Comment by jywarren** [comment]
Whew! Found the issue in #5095!!!

Let's comment out the map for the time being maybe just to merge this until that's solved... ? that way we can move forward on everything else? Or can we otherwise work past the issue for now? Maybe turning off environmental layers in https://github.com/publiclab/plots2/blob/master/app/views/map/_mapDependencies.html.erb ?

**Comment by gautamig54** [comment]
Hi @jywarren! Can we just leave the map size as it is for now so that this can be merged?

**Comment by jywarren** [comment]
Sure. Can you make a follow-up issue?

**Comment by jywarren** [comment]
But won't we need to remove the map for now to bypass this system test error?

**Comment by gautamig54** [comment]
Oh right! I'll comment the map out and then this can be merged. Once the
map system test issue is solved I'll add them. Thanks!

**Comment by gautamig54** [comment]
@jywarren @gauravano This is ready for merge!

**Comment by gauravano** [comment]
Please upload the screenshot of the updated view. @gautamig54

**Comment by gautamig54** [comment]
Here it is!

Screen Shot 2019-07-21 at 3 20 58 PM

**Comment by gauravano** [comment]
The link "see more people near here" points to /people. Shouldn't it focus on nearby location? Hmm, also do you think we should increase distance b/w left and right sections? Actually, let's wait for the map bug to be resolved and then, we can change the distance.

**Comment by gautamig54** [comment]
Yes, actually it will look better with the map and the spacing will also look fine. We wanted to get this one merged as the follow up issues are pending due to this one. I will add maps and the nearby places linked to the map after the bug is solved.

**Comment by gauravano** [comment]
Pushing on `unstable` for final check.

**Comment by gauravano** [comment]
Small bugs: 
1. Typo in show/_header.html.erb **discusssing** --> discussing 
2. The subscriber popup doesn't close
popup_closing

**Comment by gauravano** [comment]
ok, changes are live at https://unstable.publiclab.org/tag/spectrometer. Also, can you remove the underline of # people discussing as it presents that text as link.

**Comment by gautamig54** [comment]
I have corrected these bugs @gauravano!

ezgif com-video-to-gif (2)

**Comment by gautamig54** [comment]
All changes done!

**Comment by gautamig54** [comment]
Hi @jywarren! This can be merged now!

**Comment by jywarren** [comment]
Fantastic. Thanks!!!!

**Pull request merged**
