### PR TITLE
explanatory-text-for-search-tags

### LINKED ISSUE #3504: Add explanatory text for 'Tags' option on the search
Add more explanatory text for what the `Tags` option on the search page is actually searching/displaying: https://publiclab.org/search/tags/balloons/

### PR DESCRIPTION
**Pull request by kryptc**
Fixes #3504 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kryptc** [comment]
@publiclab/reviewers Do I need to make any further changes? Thanks!

**Comment by gauravano** [comment]
Hi @kryptc, thanks for working on this. You have to exclude changes done in `yarn.lock` file from your PR i.e. rollback that file to its original version. Thanks!

**Comment by kryptc** [comment]
@gauravano I deleted the yarn.lock file from my branch. Shall I just get the file from upstream and add it into my branch? 
Sorry, this is probably a really stupid thing to ask ;-;

**Comment by gauravano** [comment]
Yes, @kryptc, getting file back from master will solve the issue.

 And, it's totally fine, feel free to ask a y question. Thanks!

**Comment by kryptc** [comment]
@SidharthBansal I've added the old yarn.lock file (from master) to the branch. Does this look fine?

**Comment by jywarren** [comment]
This is fantastic. Thanks so much!!! Great teamwork, too, folks!

**Pull request merged**
