### PR TITLE
added rss for comments

### LINKED ISSUE #4882: Add RSS output for Comments listing
Our comments list page is here: https://publiclab.org/comments

https://github.com/publiclab/plots2/blob/05dcd2c382a1887275db029eb7c720b3f84392e7/app/controllers/comment_controller.rb#L18

We offer RSS feeds for other types, like notes; let's do this for comments too! We can probably build it into the same controller method as shown above, following this model:

https://github.com/publiclab/plots2/blob/05dcd2c382a1887275db029eb7c720b3f84392e7/app/controllers/notes_controller.rb#L347-L365

This will likely need:

1. a functional test in `/test/functional/comment_controller_test.rb`
2. a template in `/app/views/comments/rss.builder.erb` (i think that's the format; see equivalent in `/app/views/notes/` for reference!)

We'd love help with this!

### PR DESCRIPTION
**Pull request by Chrisyee22**
Fixes #4882  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! This is looking good... would you like to look through the Travis errors a bit to see if you can narrow down the issue? 

https://travis-ci.org/publiclab/plots2/builds/506996737?utm_source=github_status&utm_medium=notification

**Comment by jywarren** [comment]
If you get stuck, we're happy to help!

**Comment by Chrisyee22** [comment]
Yeah I will have a look and let you know if I run into any problems.

**Comment by SidharthBansal** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by Chrisyee22** [comment]
@SidharthBansal Sorry just had some other things pop up. Will get to this early next week.

**Comment by SidharthBansal** [comment]
Ok no problem

**Comment by SidharthBansal** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by jywarren** [comment]
Aha, cool! It looks like we need to add a route to `config/routes.rb` to make a route here!

```

ERROR["test_get_rss_feed", #<Minitest::Reporters::Suite:0x000056232558c200 @name="CommentControllerTest">, 65.89379426799997]
 test_get_rss_feed#CommentControllerTest (65.89s)
ActionController::UrlGenerationError:         ActionController::UrlGenerationError: No route matches {:action=>"rss", :controller=>"comment", :format=>"rss"}
            test/functional/comment_controller_test.rb:139:in `test_get_rss_feed'
```

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
