### PR TITLE
Make "Add a location" appear on all pages which have no location 

### LINKED ISSUE #6857: Make "Add a location" appear on all pages which have no location
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Pages like https://publiclab.org/wiki/london-uk have a prompt to add a location:

image

However, that little box only shows if a) there are no coordinates for that page, and b) there is a "place" tag on the page. Let's remove the 2nd condition so it appears on all pages that lack coordinates. We'll just need to remove the `@node&.has_power_tag('place')` part of the condition on this line:

https://github.com/publiclab/plots2/blob/1cfd91a87c7333718960a20b560857c88920c0d3/app/views/sidebar/_related.html.erb#L48

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by gabrielrumiranda**
Fixes #6857 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @gabrielrumiranda, Thank you so much for opening this. Do you mind adding a screenshot for this? Thanks

**Comment by jywarren** [comment]
Hi! Looks great, we'd love a screenshot! 

And, noting this relates also to #6856 that @kushaggarwal is working on! Let's merge these at the same time if we can. And if @gabrielrumiranda and @kushaggarwal want to coordinate or help one another out, all the better! Thanks all! 🙌

**Comment by kushaggarwal** [comment]
Hi @jywarren 
Yes, I am working with issue will update you soon as I am done with it

**Comment by chen-robert** [comment]
This is my first time uploading a screenshot, hopefully I did it right :smile: 

The PR seems to make the "Add Location" button display in the sidebar.

Old
image

New
image

**Comment by jywarren** [comment]
Hi! Can you confirm that the button opens up a modal to choose your location, and that if you complete it, the tags are saved in the tags (+) menu below? Thank you! It should appear as shown in this issue: https://github.com/publiclab/plots2/issues/6897

**Comment by chen-robert** [comment]
@jywarren Yup, the modal and tags work for me. I think we should be able to merge this now :tada:

**Comment by jywarren** [comment]
Oh fantastic. This is really awesome! Thank you!

**Pull request merged**
