### PR TITLE
View performance (+ memcached question)

### PR DESCRIPTION
**Pull request by siaw23**

### CODE REVIEW

**Comment by siaw23** [comment]
do with still have a problem with this Danger bot on Travis? @jywarren

**Comment by Souravirus** [comment]
Hi @siaw23, this is the same memory error which is still not solved (described in #2824). This can be removed by restarting the build

**Comment by siaw23** [comment]
thanks @Souravirus looks like a problem on Ruby trunk, i have seen similar problems elsewhere.

**Comment by Souravirus** [comment]
It would be nice if you can help us with that issue #2824

**Comment by siaw23** [comment]
can we have `memcached` set up on our servers? that way we can cache a good portion of the views for a significant amount of load speed. @jywarren (case of this similar memory issue is in a private repo, @icarito has done a lot tracking this issue, let's hope someone replies to his comment on Ruby's issue tracker)

**Comment by jywarren** [comment]
I'll ask @icarito about memcached... but this is now passing... is it ready to go?

**Comment by jywarren** [comment]
I'm not familiar with dalli -- will there be any server-side config or installs necessary beyond the gem?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR.
Thanks for contributing at Public Lab

**Pull request closed without merging**
