### PR TITLE
Fixes #668

### LINKED ISSUE #668: Profile page erroring after answering question
https://publiclab.org/profile/warren

I just asked and answered a question: https://publiclab.org/questions/warren/08-16-2016/does-the-new-question-feature-work

Several projects have touched this page, so it could be something for @ananyo2012, @lalithr95, or @jiteshjha to look at? I'm checking the logs.

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Testing

**Comment by ananyo2012** [comment]
@jywarren Fixed it! there was a parameter mismatch in the locale. You can publish this now. I will add a test for this later.

**Comment by jywarren** [comment]
Great work, thanks! will be a minute before tests pass, and I'll publish.

**Comment by jywarren** [comment]
Done -- publishing... and complete! https://publiclab.org/profile/warren

**Comment by jywarren** [comment]
Perfect, thanks a million, Ananyo!

**Comment by jiteshjha** [comment]
Thanks @ananyo2012  for looking out!

**Comment by ananyo2012** [comment]
@jiteshjha No probelm at all!

**Pull request merged**
