### PR TITLE
Migrated Rusers

### PR DESCRIPTION
**Pull request by SidharthBansal**
Part of #3032

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@publiclab/reviewers, @jywarren can you please review it?
This is my first time pushing migrations onto master.

**Comment by SidharthBansal** [comment]
Do I need to write anything else in Schema.rb.example

**Comment by jywarren** [comment]
Yes, i believe if you run `rake db:migrate` locally it'll add a line for the new column as well. This helps the Docker setup create the proper tables. Thanks!

**Comment by SidharthBansal** [comment]
Thanks @jywarren for the suggestions.

**Comment by SidharthBansal** [comment]
Locally it added the column into the table. If I push it in schema.rb.example then the Docker will change Schema.rb file at the local machines upon running rake db:migrate after git pull. Is it how migrations work in production @jywarren ?

I have made the changes. Thanks for the help.

**Comment by SidharthBansal** [comment]
I have added default value as 0. Zero indicates the account has a password already set.

**Comment by SidharthBansal** [comment]
If it will be non zero then password reset is required.
Make sense?
Thanks

**Comment by jywarren** [comment]
> If I push it in schema.rb.example then the Docker will change Schema.rb file at the local machines upon running rake db:migrate after git pull

Actually i believe travis doesn't run the migrate command, but Jenkins does; so the .example file is just for Travis... i believe! But this looks just right now. Thanks. 

Ready to merge? 👍

**Comment by SidharthBansal** [comment]
Thanks for the information.
Yes it is ready.
Thanks

**Pull request merged**
