### PR TITLE
Changes deliver_now to deliver_later

### LINKED ISSUE #5311: (not working yet) Change deliver_now to deliver_later for all emails
We just successfully converted the admin_controller to use `deliver_later` to enqueue email sending, which should really help keep the website running smoother -- it uses Redis automatically to send emails on another thread. 

https://github.com/publiclab/plots2/pull/4967/files shows how we did it -- it did involve wrapping all failing tests with:

```ruby
perform_enqueued_jobs do 
  # all test contents
end
```

Let's do this for each controller, and each time we use `deliver_now` -- you can find all instances using this search:

https://github.com/publiclab/plots2/search?q=deliver_now

We'd love help with this, and it's fine for it to be over a series of pull requests, one at a time!
- [ ] users_controller (@divyabaid16)
- [ ] answer_like_controller(@AnthoniaOkafor)
- [ ] notes_controller
- [ ] user_sessions_controller
- [x] answers_controller
- [x] admin_controller

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #5311  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Wow! Doing it all in one big PR -- ok ambitious but should be good! 

So, now, we have to correct each test in a new block starting with `perform_enqueued_jobs do` and `end`, as we did on this test PR:

https://github.com/publiclab/plots2/pull/4967/files

Do you think you can track each test that failed and do this on each?

**Comment by jywarren** [comment]
Thank you!!!

**Comment by divyabaid16** [comment]
@jywarren I am getting this kind of error after adding ```perform_enqueued_jobs do```
Selection_107
for
Selection_108

**Comment by jywarren** [comment]
Hmm, is `perform_enqueued_jobs` only for certain types of tests? Like,
functional tests only? Can you search a bit on the docs to see if this is
the case?

Thank you! Regards

**Comment by jywarren** [comment]
Lol autocomplete added "Regards" but yes, regards! :-)

**Comment by divyabaid16** [comment]
> Hmm, is `perform_enqueued_jobs` only for certain types of tests? Like, functional tests only? Can you search a bit on the docs to see if this is the case? Thank you! Regards

Yes @jywarren . As far as I have understood ```perform_enqueued_jobs``` can be used in functional and intergration tests.

**Comment by jywarren** [comment]
Ah! Hmm. So, does that mean we would need to move all tests of enqueued
mails to functional tests...? That's unfortunate!

Are there any alternatives, such as accessing the helper from a unit test,
as in `ActionDispatch::....helpers.perform_enqueued_jobs` -- maybe a clue
here?
https://stackoverflow.com/questions/4160417/how-to-import-rails-helpers-in-to-the-functional-tests

**Comment by jywarren** [comment]
Oops, @divyabaid16 did you move to a new PR? Just checking here!

**Comment by divyabaid16** [comment]
Yes @jywarren I will make a new PR.

**Pull request closed without merging**
