### PR TITLE
Rendering profile image along with username in comments section

### LINKED ISSUE #4373: Rendering profile image along with username in comments section
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

image

> What did you expect to see that you didn't?

Profile image should also be uploaded along with username in comment section

### What's your PublicLab.org username?

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by geekychaser**
Fixes #4373

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by geekychaser** [comment]
@jywarren @SidharthBansal @gauravano @sagarpreet-chadha it is giving error as ```undefined method `photo_file_name'``` while accessing profile pic, how can i access the same.?

**Comment by oorjitchowdhary** [comment]
Hey @geekychaser.. You can refer to the /people page on PL.. 
Here's the code which shows up the picture there.. 
https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/users/list.html.erb#L35-L37

**Comment by geekychaser** [comment]
@oorjitchowdhary thank u for the suggestion but i have tried the same before and its giving the same error as ```undefined method `profile_image'``` and in user schema its ```photo_file_name```  as parameter.
please correct me if i am wrong

**Comment by SidharthBansal** [comment]
Awesome folks

**Comment by geekychaser** [comment]
@oorjitchowdhary thank you, let me test on local and apply required changes

**Comment by geekychaser** [comment]
image

@oorjitchowdhary This is working perfect just by adding style and ```.user``` to previous reference

**Comment by oorjitchowdhary** [comment]
Great job! 
@publiclab/reviewers I think we can merge this!

**Comment by SidharthBansal** [comment]
It will be much appreciated if you create a gif having images of different
persons.
Thanks

**Comment by geekychaser** [comment]
image-insertion

@SidharthBansal i guess it is working perfectly?

**Comment by SidharthBansal** [comment]
Awesome!!!
Please check out some help wanted issues.
Thanks a lot

**Comment by SidharthBansal** [comment]
@oorjitchowdhary just to inform you that all the members of reviewers team doesn't have merge right.
Only Jeff, Gaurav and I have these special rights as this is very crucial part .
Thanks all

**Comment by oorjitchowdhary** [comment]
Yes, I understand....
Sorry

**Comment by SidharthBansal** [comment]
No need to be sorry. I am just telling you who are having the rights.
No need to apologies. I am telling you so that you will be able to call us at time of merging is requited.

**Comment by jywarren** [comment]
Thank you all, this looks beautiful!!!

**Pull request merged**
