### PR TITLE
Use I18n gem to internationalize application_controller [in-progress]

### PR DESCRIPTION
**Pull request by mzishtiaq**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by mzishtiaq** [comment]
Tried to run tests but it comes back as "`read': No such file or directory @ rb_sysopen" there appears to be no 'database.yml' file in config. Any tips would be really appreciated since I am new to this sort of testing. :)

**Comment by jywarren** [comment]
I'll take a look tomorrow mid day- thanks a lot!!

**Comment by jywarren** [comment]
This looks great so far! Have you tried rebasing it on top of the latest master? I think there may be a couple small new changes that you'd have to resolve. Happy to help.

**Comment by mzishtiaq** [comment]
I tried to pull last night before opening the pull request but there weren't any changes then. I'll try to do it again and then push again. I'll update you on my progress when I am done. :)

**Comment by mzishtiaq** [comment]
I pull the latest changes down and tried to rebase another time. Not sure how successful that was but please do let me know if I made any mistakes.

**Comment by mzishtiaq** [comment]
Oops, sorry, just saw your comment and a really helpful guide for doing this in the other pull request. I may have done it wrong, any tips on how I can correct it?

**Comment by jywarren** [comment]
Ah, uh oh -- you shouldn't have to merge in changes from publiclab's master -- so please run `git reset --hard 9b82abf` to rewind to just before you did that. Then you should be able to rebase all your changes onto the latest master using the steps here: https://publiclab.org/wiki/contributing-to-public-lab-software#A+sample+git+workflow (starting at step 5).

**Comment by jywarren** [comment]
Hopefully the changes to `config/database.yml.example` and `db/schema.rb.example` and other similar files are just a result of your having merged in -- so these changes may disappear when you follow the steps I linked to. Let's see!

**Comment by mzishtiaq** [comment]
Oh, I am so sorry but this is very new to me and I am having trouble getting this right. I am getting
"Current branch master is up to date." when I try to rebase the master. I followed the instructions from the contributor page and rebased the first time after I had completed the work on the feature so I am not sure what I am getting wrong.

**Comment by jywarren** [comment]
No problem at all, mzishtiaq -- happy to help. I think you may need to do `git checkout feature-branch-name` -- but swapping `feature-branch-name` for the actual name of your new branch, so that when you run the `git rebase ...` command, you're in the new branch, not your master branch. 

But if you paste your console output in here (also run `git status` so you can tell what branch you're on) I can help take a look at it.

**Comment by jywarren** [comment]
I'll be out for a bit but will keep an eye out here to help -- thanks for your patience!

**Comment by mzishtiaq** [comment]
Thanks a lot for all the help and for being patient. For some inexplicable reason, I was trying to rebase from master and didn't realise that. I think I have done it right this time so travis should pass. Slightly worried that the merge commits are still showing even though I ran ```it reset --hard 9b82abf```.

**Comment by jywarren** [comment]
Hm, did you run `git reset --hard 9b82abf` from within your feature branch? What was the output?

**Comment by mzishtiaq** [comment]
I ran it in both, master and the feature branch, just to be on the safe side. This was the output.
~~~
open_source/plots2 [internationalize-application-controller] » git reset --hard 9b82abf143bcd41abe5a9de1d4d4c51ce322ca03
HEAD is now at 9b82abf Use I18n gem to internationalize application_controller
~~~

**Comment by jywarren** [comment]
Super, and then 'git push -f origin
internationalize-application-controller' from in the
'internationalize-application-controller' branch to push that state up to
github.

**Comment by mzishtiaq** [comment]
Do you mean the current state or soon after running the git reset?

**Comment by jywarren** [comment]
1. `git checkout internationalize-application-controller`
1. `git reset  --hard 9b82abf` -- rewind until before your merges but after your actual changes
1. `git checkout master`
1. `git pull https://github.com/publiclab/plots2.git master` -- get latest
1. `git checkout internationalize-application-controller`
1. `git rebase master`
1. `git push -f origin internationalize-application-controller` -- push the newly rebased changes -- without the merges -- back up to github

Make sense? Thanks for hanging in there -- it's a bit obscure!

**Comment by mzishtiaq** [comment]
When I try do pull changes using ```git pull https://github.com/publiclab/plots2.git master```, it opens the vi editor and tries to merge changes with this commit message. ```Merge branch 'master' of https://github.com/publiclab/plots2```. I am sorry, I must be doing something wrong and I am conscious that you cannot spend all your time on this one pull request.

**Comment by jywarren** [comment]
No problem at all - hang on a sec and I'll add one more addition to the sequence.

**Comment by jywarren** [comment]
So what happened was that when you pulled, your master branch wasn't rewinded back to the last common commit with publiclab/plots2's master branch. So we'll insert one more line (bolded):

1. `git checkout internationalize-application-controller`
1. `git reset  --hard 9b82abf` -- rewind until before your merges but after your actual changes
1. `git checkout master`
1. **`git reset  --hard 75b21ec9ef2c3d14732f859bd6e479d818d2d19c` -- rewind until before any of your changes**
1. `git pull https://github.com/publiclab/plots2.git master` -- get latest
1. `git checkout internationalize-application-controller`
1. `git rebase master`
1. `git push -f origin internationalize-application-controller` -- push the newly rebased changes -- without the merges -- back up to github

I **think** that should work. Thanks for sticking with it!

**Comment by mzishtiaq** [comment]
It worked!!! Thank you so much for your patient, you're a very good teacher. :)

**Comment by jywarren** [comment]
Great, and thanks! push up your new code and lets see how it does on tests!

**Comment by mzishtiaq** [comment]
<phew> Finally passing. Never knew my git skills will be the ones to let me down but it was a great learning experience. Thank you very much for your patience. It has been a pleasure working with you. :)

**Comment by jywarren** [comment]
Oh, this looks super -- thanks! Are you going to keep adding to this PR or shall I merge it now?

**Comment by jywarren** [comment]
Ah, and OK -- `config/locales/controllers/application_controller/de.yml` should be left out until we can provide translations there, so it falls back to English. Tnx again!

**Comment by mzishtiaq** [comment]
Oh, I will try to arrange German translations, will remove the file if I can't and push it up again and let you know. :)

**Comment by mzishtiaq** [comment]
Added the German translation, please review and merge. :)

**Comment by jywarren** [comment]
Perfect! Thanks once again and please check out our other help-wanted issues if you're looking for a new challenge!

**Pull request merged**
