### PR TITLE
Followers/following page: avatar and grid

### LINKED ISSUE #9320: Followers/Following Page: Enhance Follower/following list
Enhance the follower/following list at  https://publiclab.org/people/liz/followers  

-  Instead of a using whole row for a user, reduce the width and use a grid or card for each user.
-  Show profile image along with follower/following name. If there is no profile image use gravatar.

### PR DESCRIPTION
**Pull request by 17sushmita**
Fixes  #9320

- Improved the followers/following list at https://publiclab.org/people/liz/followers. 
- Added Profile image or gravatar to the follower/following list.   

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

**test_user_2 is banned. Merging PR #9300 will remove banned users.
**Merging PR #9301 will add Follower/Following count to their respective tabs
Before
image

After
image
image

### CODE REVIEW

**Comment by 17sushmita** [comment]
@cesswairimu @jywarren Could you please check why codeclimate hasn't finished analyzing yet and also review the PR?

**Comment by cesswairimu** [comment]
Hi again, I will try and reopen to see if the test passes kindly refer to https://github.com/publiclab/plots2/pull/9301#issuecomment-800068142 and create an issue for the changes you did here...this is going great thanks a lot for your help with these :heart:

**Comment by 17sushmita** [comment]
> Hi again, I will try and reopen to see if the test passes kindly refer to [#9301 (comment)](https://github.com/publiclab/plots2/pull/9301#issuecomment-800068142) and create an issue for the changes you did here...this is going great, thanks a lot for your help with these

Sure, I'll create an issue for this. Thank You!! :smiley:

**Comment by jywarren** [comment]
I really love this, nice design and well coded! Doing a quick review and we'll hopefully merge today! 🎉

**Review by jywarren — APPROVED** [review]
Very nicely done!!!

**Pull request merged**
