### PR TITLE
map changes on selecting autocomplete option

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren Now map changes location as soon as you select the auto-complete option

**Comment by jywarren** [comment]
Oh, super! Merging.

**Comment by mridulnagpal** [comment]
@jywarren I am pushing more changes to this PR should I revert it?

**Comment by jywarren** [comment]
Oh, i'm sorry, i thought it was complete. Have I merged code that's not working? Apologies, let's try to communicate better. I'll ask more carefully in the future and please also try to mention if your code is ready for merging or not. Thanks!

Can you open a new pull request with the additional changes?

**Comment by mridulnagpal** [comment]
Yeah I have made one. Thanks

**Pull request merged**
