### PR TITLE
Ability to sort tags alphabetically #1704

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
This solves #1704 .
 @jywarren sir...kindly review this ! Thank you !

Sort By button added with two types of sorting methods :  
1.) By number of uses and
2.) Alphabetically
screen shot 2017-10-24 at 4 15 42 am

Search Box added to search Tags starting with any prefix ---% 
screen shot 2017-10-24 at 4 16 14 am
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
I made one small adjustment to the style of the input (following Bootstrap classnames) but this looks perfect -- merging now, and thanks!!!

**Comment by ebarry** [comment]
This is really exciting, a first in the 7 year history of the Public Lab community which we've been needing this whole time! **thank you**

**Comment by ebarry** [comment]
Hi @sagarpreet-chadha -- i love this feature so much! I use it all the time, but starting sometime last week (i'm not sure exactly when), the dropdown menu for sorting on the tags page went away -- do you know where it went? Thank you!!!!

**Comment by Gauravano** [comment]
hi @ebarry actually recently the sorting button has been removed and table headers are now used as buttons for sorting tags like this 
tagsort
I guess we need to make changes so users get to know about this thing -  how about adding tooltips?

**Comment by ebarry** [comment]
oh wow, thank you!!!!! I had missed that entirely!!!!! Thanks for bringing me back up to speed. 
I see there's also an issue going, i'll check in over there: https://github.com/publiclab/plots2/issues/2331 Have a great day!

**Comment by Gauravano** [comment]
> Have a great day!

you too :blush:

**Pull request merged**
