### PR TITLE
Fixes #4259 Logout always redirects to / (Home Page)

### LINKED ISSUE #4259: Logout always redirects to / (Home Page)
### Problem
The log out button in the dropdown redirects to the home page. It's a very annoying issue, which can cause users to dislike the whole webpage.
logout

### Solution
Pressing the log out button should log you out and then redirect to the same page you were on before the action. The solution to this problem would probably be very easy. You should start looking at the [_header.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb) and [user_sessions_controller.rb](https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb) especially the functions `destroy` and `logout_remotely`. The `return_to` statement could be useful.

Thanks for all your help!

### PR DESCRIPTION
**Pull request by IshaGupta18**
Fixes #4259 

Earlier, when the user logged out, he/she was redirected to the Home Page.

Now, logging out will redirect the user to the same page he/she was on. Although, if the user was on a page that required him/her to be logged in, on logging out, the redirection will be to the suitable page or to the login page, as specified before.

image

image

### CODE REVIEW

**Comment by IshaGupta18** [comment]
I am terribly sorry about this error, I will try my level best to resolve it.

**Comment by IshaGupta18** [comment]
I am closing this pull request. I request you all to kindly ignore this one, I will make another pull request for the same issue, once I have sorted it out. I sincerely apologise for all the trouble I may have caused.

**Comment by jywarren** [comment]
Not a problem at all, thanks for your help!! If you get stuck we can help!

**Comment by IshaGupta18** [comment]
Yes @jywarren could you please look here #4313 . This is my new PR and I am seeking help here. Thank you very much!

**Pull request closed without merging**
