### PR TITLE
api search profile query now returns user lat and lon for their locat…

### LINKED ISSUE #5774: Inclusion of lat and lon on API profile search query
The following issue on mapknitter requires this update to be able to return a profile user's location if they have added it on their profile
https://github.com/publiclab/mapknitter/issues/626

### PR DESCRIPTION
**Pull request by rarrunategu1**
…ion map

Fixes #5774  (<=== Add issue number here)

https://github.com/publiclab/plots2/issues/5774

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Previous to code modification it returned:
image

After code modification and testing it returns:
image

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by rarrunategu1** [comment]
I missed something.  I'm going back through the tests to see what happened.

**Comment by rarrunategu1** [comment]
the test is failing but it shouldn't be because the title "Dashboard" shows up just fine when logged in and "Community Research" shows up when logged out.  The code reflects this as well: 
image
But it seems the test can't read it.  I'm thinking the if else statement containing the information may have something to do with it.  Still looking into it.

**Comment by sagarpreet-chadha** [comment]
Hey @rarrunategu1 , the test which is failing is unrelated to your PR .There is certain issue with system tests which @jywarren is solving .

**Comment by sagarpreet-chadha** [comment]
We are tracking the timing failures in system tests here: #5683 :)

**Comment by rarrunategu1** [comment]
I see.  Thank you.  How long should I wait to follow up on this case to see if it passes?

**Comment by jywarren** [comment]
I think if you're able to rebase your work over the latest plots2 master
branch, this should resolve itself! Are you good rebasing, or need some
help with that? Thank you!!! This is exciting!

**Comment by rarrunategu1** [comment]
I've never rebased but googling I found -      git checkout my_branch     git rebase master    git checkout master    git merge my_branch         Is that right?

**Comment by jywarren** [comment]
Yes, that's the basics! Check out these resources, there's a great guide to
rebasing in there: http://publiclab.org/developers#Resources

**Comment by rarrunategu1** [comment]
Rebased and did another pull request 
https://github.com/publiclab/plots2/pull/5780

**Comment by gauravano** [comment]
Hi @rarrunategu1, as you have opened new PR at  #5780 so closing this one. Thanks!

**Pull request closed without merging**
