### PR TITLE
Update wiki_controller.rb for abtest fixes

### PR DESCRIPTION
**Pull request by jywarren**
Related to problem here:

http://testing.laboratoriopublico.org/wiki/time-machine

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

But we need to screen to ensure the node exists!

Just like we did for redirect tags, @ryzokuken

This is a follow-up for https://github.com/publiclab/plots2/pull/1353

### CODE REVIEW

**Comment by ryzokuken** [comment]
You fixed it already?

**Comment by jywarren** [comment]
I thought so, but it seems to still be broken on
testing.laboratoriopublico.org -- needs more followup before we publish
that code :-/

**Comment by jywarren** [comment]
OK, i see: 

```
Started GET "/wiki/time-machine" for 173.166.14.1 at 2017-04-04 22:28:39 +0000
Processing by WikiController#show as HTML
  Parameters: {"id"=>"time-machine"}
Completed 500 Internal Server Error in 61.4ms

NameError (uninitialized constant WikiController::DrupalNode):
  app/controllers/wiki_controller.rb:46:in `show'
```

**Comment by jywarren** [comment]
Oops, it's a DrupalNode issue.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/1364

**Pull request merged**
