### PR TITLE
fix research note comments repeating issue (Issue#413) and comments update issue (issue#414)

### LINKED ISSUE #413: Drag and drop image while editing research note comments fails
Drag and drop works when writing a comment but not when editing that comment after it has been published.
chrome in windows

### PR DESCRIPTION
**Pull request by ujithaperera**
* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes
* [x] review by maintainer (see comments checklist at bottom)

This pull request fixes #413 and #414:

particular xhr comment update request was dead. re-connect using html to existed structure.

### CODE REVIEW

**Comment by jywarren** [comment]
Ah, this looks great. Will try to merge in a bit. Thanks!!!

**Comment by jywarren** [comment]
Hmm, in this fix, I pulled it in to test, and the image isn't placed in the right box. For example, see below -- the image is still added to the new comment textarea, not the textarea of the comment being edited. 

screenshot 2016-03-16 at 2 51 43 pm

Also, the progress bar is run on both forms: 

screenshot 2016-03-16 at 2 51 24 pm

I think that it's possible to set the target textarea with an argument to `$E` -- with a `textarea: 'foo'` parameter as described on: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/editor.js#L4

That'd be the ID of the target textarea. But it may also require that we do better namespacing for `$E`, the editor object, as there is one instance for each comment, yet we seem to use a global namespace for it: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js#L65

**Comment by ujithaperera** [comment]
Yes I understood the issue. This is another bug that need a quick fix. because this problem already exist in the live site. "choose one" link in comment edit to upload an image in set text to the post comment form.

**Comment by jywarren** [comment]
OK, are you planning to rework this a bit? I'll stay away from commenting code for a bit if so. Thanks!

**Comment by ujithaperera** [comment]
Yes I'm working on this. Image repeating issue still exists here. But text comments repeating could be fixed using this update.

**Comment by jywarren** [comment]
I'm happy to merge this in, as it is not worse than the current state. But
i can also wait if you want and merge in the fixes together. I don't plan
to merge to stable again for a few days, so you have some time. Thanks!

**Comment by ujithaperera** [comment]
Yes there was something more than I fix in this update. I will fix this image drop issue asap. Thanks for waiting complete fix.

**Comment by jywarren** [comment]
no worries and many thanks for your efforts!

**Comment by ujithaperera** [comment]
@jywarren Here is my new update for issue #413  and this fix address issue #435 also. Thank you very much for trusting my effort.

**Comment by jywarren** [comment]
Super! Thanks -- I'm making a listing of bugs that were identified, and I'll try them out one by one before merging:

* [ ] image inserted multiple times into comment boxes
* [ ] image inserted into wrong comment box
* [ ] Drag and drop works when writing a comment but not when editing that comment after it has been published.
* [ ] select image link also failed
* [ ] when a user is trying to edit a comment with a image. image upload progress bar appear in create comment box also.
* [ ] via @cfastie: I just posted a comment on a note and the display immediately showed the published note and an empty comment box for a new comment. But when I was editing an existing comment and clicked publish, nothing happened. My editing window persisted with my edits in it, and there was no display of my newly edited comment. When I opened a new tab and navigated to the note, my newly edited comment was published.

**Comment by ujithaperera** [comment]
ok. waiting with results. :)

**Comment by jywarren** [comment]
Hi, Ujitha - it looks like this code isn't rebased on top of master, can you try? Thanks!

**Comment by ujithaperera** [comment]
Yes. Since there is no any conflicts, is it a big issue to merge ?

**Comment by jywarren** [comment]
It's not, but we prefer rebasing. I'll see if I can do that myself.

**Comment by ujithaperera** [comment]
No. Its no problem. Give me a second

**Comment by ujithaperera** [comment]
Hi Jeff, Can you check

**Comment by jywarren** [comment]
Hmm, I'm still seeing the need to rebase a few commits, but I was able to do so without issues and am now running tests. Thanks for trying! I know it's extra effort after working on a change for some days, and I appreciate it. 

Please hold while I run tests.

**Comment by ujithaperera** [comment]
sure

**Comment by jywarren** [comment]
Completed checks, everything works! Super, and many thanks. I did add one more change -- there was a tab put between the `<textarea></textarea>` tags, which displayed the empty textarea with a tab in it -- this hid the "placeholder" text. https://github.com/publiclab/plots2/commit/aeb9db472bee3d8db08285b4850959f351d376cf

Closing this PR as I rebased and merged it in manually. Thanks!

**Comment by ujithaperera** [comment]
Actually I did not try to change the structure of previous code here. Because it may affect to another process. I hope to move these inline js , css styles to external file to avoid element repeatings. Pleasure to work with you. Thanks.

**Comment by jywarren** [comment]
I agree, the js & css should be externalized. I think we may soon consider
spinning out the entire editor as a standalone JavaScript module, for
easier maintainability, and for re-use in other projects.

Thanks again!

**Pull request closed without merging**
