### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EmilyOng**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

Overview

The plots2 Readme has become too long since its introduction. We need to modularize the readme and transfer the contents in separate github wiki pages.

Objective

A long readme is really hard to read and also it is hard to search and traverse any topic. So it is better to create separate wiki pages in the github repository. Separate links can be given in the readme with some introduction.

Requirements

Learn git for getting started
Install the repository in your local
Create github wiki pages for each section
Update readme with the links to wiki pages and submit a pull request

Expected Outcome

Github wiki pages for various sections in readme
Suggest changes in readme
A pull request to update the readme

https://github.com/publiclab/plots2#publiclaborg

GCI 2016 Emily Ong

### CODE REVIEW

**Comment by EmilyOng** [comment]
@jywarren @ananyo2012

**Comment by ananyo2012** [comment]
Thanks for your contribution @EmilyOng. You may need to final change in the wiki page of the plots2 Repo itself. So we may need to give you permissions for that. So please have some patience till then.

@jywarren I think you should add her to our org to give her permissions to edit the wiki and put the final links as well. Also suggest changes to the readme. Here is the updated readme as per the PR https://github.com/EmilyOng/plots2/tree/patch-4#publiclaborg

**Comment by jywarren** [comment]
Hi, just a suggestion; should we have a GitHub wiki or a PublicLab.org
wiki, or additional markdown pages in the codebase itself?

**Comment by ananyo2012** [comment]
@jywarren Yes I think github wiki pages are a good way to keep information related to the code in the repository itself. That's what the task is for.

**Comment by EmilyOng** [comment]
:)

**Comment by jywarren** [comment]
Hi, I believe I added permissions! Can you check? Thanks!!

**Comment by jywarren** [comment]
Saw this: https://github.com/EmilyOng/plots2/wiki -- checking this out later today hopefully, but thanks!

**Comment by jywarren** [comment]
Hi, is it possible to add to https://github.com/publiclab/plots2/wiki instead of https://github.com/EmilyOng/plots2/wiki ? 

Thank you so much, this is looking amazing!

**Pull request closed without merging**
