### PR TITLE
Updated comment.rb

### PR DESCRIPTION
**Pull request by rajvidg**

### CODE REVIEW

**Comment by TildaDares** [comment]
@rajvidg The changes in this PR and #11000 should be in the same PR.

**Comment by rajvidg** [comment]
> @rajvidg The changes in this PR and #11000 should be in the same PR.

@TildaDares since I am new to this can you please tell me how can we put those changes in the same pr, or please give me some time I am working on it.

**Comment by rajvidg** [comment]
> @rajvidg The changes in this PR and #11000 should be in the same PR.

@TildaDares should I close both of my earlier prs and then raise a new one, and also I have created a pr in my forked repo.

**Comment by TildaDares** [comment]
@rajvidg What you need to do is run `git checkout patch-1` to start using `patch-1` branch and then run `git merge patch-2` to merge the changes in `patch-2` together with the changes in `patch-1`. After doing that you can do a push.

**Comment by rajvidg** [comment]
> @rajvidg What you need to do is run `git checkout patch-1` to start using `patch-1` branch and then run `git merge patch-2` to merge the changes in `patch-2` together with the changes in `patch-1`. After doing that you can do a push.

@TildaDares Okay thank you, working on it.

**Comment by rajvidg** [comment]
> @rajvidg What you need to do is run `git checkout patch-1` to start using `patch-1` branch and then run `git merge patch-2` to merge the changes in `patch-2` together with the changes in `patch-1`. After doing that you can do a push.

@TildaDares I am working on it but I think I made the changes and commit them before creating a branch in my local, so can you please suggest some tutorial or just please spare me some time, I shall be really very grateful for that, I am really trying to solve this and make them in the same pr.

**Comment by TildaDares** [comment]
Hi @rajvidg, you can just close these PRs and make a new one in a new PR.

**Comment by rajvidg** [comment]
> Hi @rajvidg, you can just close these PRs and make a new one in a new PR.

ok thank you @TildaDares , working on it.

**Comment by rajvidg** [comment]
plots2_Problem1
plots2_Problem2
@TildaDares I am still facing these problems, :(

**Comment by rajvidg** [comment]
> @rajvidg You can follow this guide @Somya-Singhal put together [publiclab/infragram#300](https://github.com/publiclab/infragram/issues/300). Skip the steps you’ve done.

ok thank you again, working on it @TildaDares

**Comment by rajvidg** [comment]
> @rajvidg You can follow this guide @Somya-Singhal put together [publiclab/infragram#300](https://github.com/publiclab/infragram/issues/300). Skip the steps you’ve done.

@TildaDares since I had already made those changes in my forked repo, after cloning the changes were already there in my local also, so will there be any effect after git diff or commit or push?

Also, I have made a single pull request from my forked repo, in GitHub itself, so please have a look at it.

**Pull request closed without merging**
