### PR TITLE
Redesigning the search bar

### LINKED ISSUE #4922: Planning implementation of new UI designs (work in progress!)
(this issue is not ready yet, as we're still finalizing UI design work!)

Coming out of a range of UI analysis and design projects from the past 6 months, Public Lab is now ready to begin implementing new designs across major pages of our PublicLab.org collaborative platform. This project will build on the Bootstrap 4 UI library and our upcoming Style Guide to implement new HTML templates within the Ruby on Rails website at PublicLab.org, focused on the following pages:

* [ ] Dashboard
* [x] People page
* [x] Tags/topics page
* [x] Individual tag pages
* [ ] Questions page
* [x] Profile page

The design work to date can be found in a series of mockups listed on this page: https://publiclab.org/tag/ui-designs.

### LINKED ISSUE #5090: Implement new design for Tags page (needs breaking up)
Building on #4922, we should work to rebuild the page at https://publiclab.org/tags following this design:

Screen Shot 2019-03-15 at 12 45 20 PM

There's discussion about this here: https://publiclab.org/notes/edie_blues/01-09-2019/the-tags-page-mockup-let-me-know-what-you-think#c22154

The current template is here: https://github.com/publiclab/plots2/tree/master/app/views/tag/index.html.erb

Steps that could be broken out include:

* [x] making it 2-column #5100
* [x] adding https://publiclab.org/stats/graph in an iframe to the 2nd column
* [x] adding the links below the graph
* [x] Redesigning the search bar (https://github.com/publiclab/plots2/pull/5121)
* [ ] redesigning the table to use a Card ui instead (starting with panels, here: https://getbootstrap.com/docs/3.3/components/#panels) in a template partial

I'd love help with this one!

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #5090  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Screenshot for the change:
Selection_073

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
Great work @divyabaid16 :tada:

**Comment by gauravano** [comment]
I tried your PR locally, but the width is smaller from the screenshot 
Screenshot from 2019-03-17 18-41-46

**Comment by divyabaid16** [comment]
Yes @gauravano 
Can you please suggest me how much should be the width?
I was actually not very sure in this case.
Like somewhere between 270px to 320px.

**Comment by divyabaid16** [comment]
@gauravano I have now changed the file and updated the screenshot.

**Comment by jywarren** [comment]
Yeah, really nice!

**Comment by CleverFool77** [comment]
@divyabaid16 It's showing this in mine. Should I fix it ?
Screenshot from 2019-03-19 11-47-35

**Comment by divyabaid16** [comment]
@CleverFool77 previously even in mine it was shown in that way. Then I had made some changes. Can you plz check it again?
Because I don't think there must be a problem.
Thanks!

**Comment by CleverFool77** [comment]
These were latest changes I fetched. I didn't checked your pr locally rather I was syncing the master repo with my local repo.

**Comment by divyabaid16** [comment]
@CleverFool77 
Oh!!! I now got the problem. In Mozilla Firefox it is working fine but in google chrome, this is the issue.
Can you please check it out one in Mozilla FireFox

Thank you so much for pointing out this!!

**Comment by CleverFool77** [comment]
No @divyabaid16. If you've got no problem, then I can fix it.

**Comment by CleverFool77** [comment]
I'll check it out in mozilla :+1:

**Comment by divyabaid16** [comment]
This issue is now fixed in Google Chrome too!
Thank you so much @CleverFool77

**Comment by CleverFool77** [comment]
Ahh I just fixed it locally too. 😅😅. I was thinking of making PR.
Great work though 👍

**Pull request merged**
