### PR TITLE
Align the enter tags input section in subscriptions #5191

### PR DESCRIPTION
**Pull request by techchic**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by techchic** [comment]
@jywarren lemme know if this is fine.

**Comment by jywarren** [comment]
Hi! It looks like you may have added a few changes that you didn't mean to include here - like deleting `config/database.yml.sqlite.example`, and Gemfile.lock additions.  I think you meant to be changing only the css files, right? Would you try keeping the rest the same (undeleting, reverting your Gemfile.lock in the PR)? Thanks!

And can you link us back to the original issue with a URL please? Don't worry we'll help get this prepped one step at a time. Thanks so much!

**Comment by divyabaid16** [comment]
And yes, in the pull request you must write the issue number for which you have made the changes.

**Comment by SidharthBansal** [comment]
Please resolve the conflicts. Thanks for your time and work here at PL

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
