### PR TITLE
Update _node_meta.html.erb --> Changing function t(...) to translation(...) on line 2

### PR DESCRIPTION
**Pull request by MarieSell**
Changing method "t" to "translation"

Fixes #6606   (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by MarieSell** [comment]
Dear Natalie,
Is my PR descriptively titled 📑 and links the original issue above? --> Is the link a "real" link, or just the ticket-number #6606?
Thank you

**Comment by nstjean** [comment]
Where it says Fixes #0000 you just need to change that to the issue number and it will automatically add a link for you!

**Comment by MarieSell** [comment]
> Where it says Fixes #0000 you just need to change that to the issue number and it will automatically add a link for you!

Thank you, for your help. My adventure as a contributor starts here, with you :)

**Comment by nstjean** [comment]
> > Where it says Fixes #0000 you just need to change that to the issue number and it will automatically add a link for you!
> 
> Thank you, for your help. My adventure as a contributor starts here, with you :)
> So here is nothing more to do, yet ?

The next step would be looking to make a FTO for someone else, or finding a small issue that you can work on. If you go to https://code.publiclab.org/ you can scroll down to "What's next?". You can also find info here https://github.com/publiclab/plots2 . We recommend installing the repository/ies on your development computer and trying to get it running! Then do some small pull requests.

**Comment by MarieSell** [comment]
> > > Where it says Fixes #0000 you just need to change that to the issue number and it will automatically add a link for you!
> > 
> > 
> > Thank you, for your help. My adventure as a contributor starts here, with you :)
> > So here is nothing more to do, yet ?
> 
> The next step would be looking to make a FTO for someone else, or finding a small issue that you can work on. If you go to https://code.publiclab.org/ you can scroll down to "What's next?". You can also find info here https://github.com/publiclab/plots2 . We recommend installing the repository/ies on your development computer and trying to get it running! Then do some small pull requests.

Thank you! I`ll make the next steps :)

**Pull request merged**
