### PR TITLE
Arranging tags in descending order & Adding link to tags

### LINKED ISSUE #5260: Refinements to new tag subscription statistics page
Following up on #5224, we can tackle a few more things in this follow-up issue, now that @GettyOrawo has done a great job getting this page created!

* [ ] let's sort this DESCENDING or `desc` so we start with the most-used tags
* [ ] let's hide anything more than 25 results and show a "View all" link to show them?
* [ ] let's make the tag names into links that go to `/tag/TAGNAME`

and we can do more too! This is a great start!

### PR DESCRIPTION
**Pull request by IshaGupta18**
Fixes #5260 

Arranging the stats in desc order for the most used to appear first and adding links to tags:

image

On clicking on a tag, redirected to tag's page:

image

### CODE REVIEW

**Comment by IshaGupta18** [comment]
@jywarren kindly review this PR and let me know what else can be done. Thanks!

**Comment by jywarren** [comment]
Ack, so sorry! I didn't see this PR and made one of my own, causing conflicts. Can you take a look? 

https://stable.publiclab.org/stats/subscriptions

I like @aSquare14's ideas! But this is a utility page that not TOO many people will use, so I don't want to add too much javascript that'll take maintaining. If it's a simple command, sure! I think there's a jQuery `reverse()` or `sort()` maybe?

Another thing might be to alphabetize the tags in each category?

Thanks, all!

**Comment by IshaGupta18** [comment]
Wow this looks really pretty! I thinkthe work is more or less done here then! I have just put the most recently used tags first. I think with that, after removing the conflicts, it will be good to go right?

**Comment by jywarren** [comment]
great!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by IshaGupta18** [comment]
Hey! So could you please tell me what more has to be done here? Kinda need a refresher here. Terribly sorry for this!

**Comment by jywarren** [comment]
No problem! I think we've solved a lot, but one issue is that both the rows
in the table, and the order of the tags in each row, is a bit mysterious. I
think it's just whatever ActiveRecord is sending back to us. So, we should
try ordering the table rows, as well as ordering the tags in each row.
Would you be able to help with that? Thanks!!!

**Comment by IshaGupta18** [comment]
I am alphabetizing the tags if it helps?

**Comment by IshaGupta18** [comment]
And I was just about to create a new PR, lets close this one and move there!

**Comment by IshaGupta18** [comment]
moved to #5769

**Pull request closed without merging**
