### PR TITLE
Forms page updated

### LINKED ISSUE #1107: Fill out new HTML form for location entry
Followup to #1035, @mridulnagpal asked for next steps. We now have a blank HTML template:

https://github.com/publiclab/plots2/blob/master/app/views/locations/form.html.erb

Now we need to add HTML markup for the location form itself, building from this image:

gif

And using elements from https://getbootstrap.com/components/ 

We can leave the map as a grey square at the top, for now!

### PR DESCRIPTION
**Pull request by mridulnagpal**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.
Closes #1107 
Thanks!

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren Please have a look. 
screenshot from 2016-12-17 20-35-45

**Comment by jywarren** [comment]
Great, and "obscure..." Should be a check box, not a radio button. Can you show a screenshot of how it looks in a narrow window like on mobile?

@ebarry may have more input but this is a good start!

**Comment by mridulnagpal** [comment]
@jywarren How do I check it on a mobile?

**Comment by jywarren** [comment]
There's a mobile simulator in chrome, but bootstrap styles are just based on page width so you can also just drag your window to be narrower.

**Comment by mridulnagpal** [comment]
@jywarren It didn't look good so I had to make some tweaks, the updated code looks like this.
screenshot from 2016-12-17 22-14-26

**Comment by jywarren** [comment]
Cool, yes, you may have to use smaller fonts in mobile view. You can do
this with a media selector:

https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/style.css#L501

I prefer you do this using a style element in the template itself. Thanks!

**Comment by mridulnagpal** [comment]
@jywarren I tried that but it doesn't seem to work as all the text becomes small even when the window is full screened

**Comment by jywarren** [comment]
Hmm, interesting -- can you link to documentation for `font-size: 3vw` ? And i think we'd better use a `<style>` block rather than inline styles, so that it's tidier and eaiser to change. Can you make that change and upload a screenshot of the smaller view? 

Thank you!

**Comment by mridulnagpal** [comment]
@jywarren Changed the inline thing. Here's the link from where I got the idea for font-size: 3vw.
http://mobile-desktop.xyz/class03.php
screenshot from 2016-12-18 22-35-37

**Comment by jywarren** [comment]
I think this is a good point to merge; next we'll probably have to start hooking up all the functions! 

Thanks, @mridulnagpal!!

**Comment by jywarren** [comment]
Found more docs on `vw` here: https://www.sitepoint.com/new-css3-relative-font-size/

great find! 

🎉

**Comment by jywarren** [comment]
Hi @mridulnagpal -- live now at https://publiclab.org/locations/form -- but some font-size issues. Mind taking a look?

**Comment by mridulnagpal** [comment]
@jywarren Is the font size too big?

**Comment by jywarren** [comment]
yes it is a bit -- i'll make a req in #1171

**Pull request merged**
