### PR TITLE
added buttons `fixes #3298`

### LINKED ISSUE #3298: Add range buttons to /tag/____ page
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

We have a nice way of displaying activity on a topic for just a given time period: https://publiclab.org/tag/data-logging?start=16-03-2016&end=14-04-2017 (from #2439) -- 

...but no easy way to get to such a range-limited page from the basic page of https://publiclab.org/tag/data-logging. So this adds some nice buttons!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/tag/show.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -51,7 +51,11 @@
   <% end %>
 
   <h3><% unless @tags.try(:first).try(:parent).nil? %><small>parent: <%= @tags.first.parent %></small><% end %></h3>
-  <%= render :partial => "notes/format_toggle" if @node_type == "note" %>
+  
+  <div class="btn-group visible-desktop" style="float:right;" id="note-format">
+    <a class="btn btn-default btn-sm" href="?start=<%= (@start || Time.now - 1.month).to_formatted_s(:long) %>&end=<%= (@end || Time.now).to_formatted_s(:long) %>">month</a>
+    <a class="btn btn-default btn-sm" href="?start=<%= (@start || Time.now - 1.year).to_formatted_s(:long) %>&end=<%= (@end || Time.now).to_formatted_s(:long) %>">year</a>
+  </div>
 
   <% if current_user %>
   <!-- AJAXify -->
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by AmanGarg97**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by AmanGarg97** [comment]
PR for issue #3298.
Please review this.

**Comment by AmanGarg97** [comment]
I am getting a error in this :  rake db:setup

I have attached the screenshot.

screenshot 555

Thanks

**Comment by jywarren** [comment]
From the error it looks like it is trying to find `python` installed. Perhaps try installing it and retrying?

**Comment by gauravano** [comment]
Hi @AmanGarg97 , you have to install mentioned dependency `libv8` using the mentioned command. If you have any doubt, feel free to ask. Thanks!

**Comment by AmanGarg97** [comment]
Hey ! I installed python first and then redone the tasks. Also run the command mentioned for **libv8**.
I also installed rubyracer (got recommended for this error through stackoverflow) but it didn't helped.


screenshot 559

screenshot 560

Thanks!

**Comment by jywarren** [comment]
Can you share your log output in gist.github.com and past a link here?

I think we could try to search for specific things with "extconf failed
rails libv8" because i think it can't seem to complete that. You might also
want to share the `gem_make.out` log output that it generated on the last
line, maybe there's a clue there too!

**Comment by AmanGarg97** [comment]
Yes sure !

gist.github link :-  https://gist.github.com/AmanGarg97/52d3241e83883e25ede3e4682230d0e5 

gem_make.out file is attached.


[gem_make.pdf](https://github.com/publiclab/plots2/files/2409003/gem_make.pdf)


Thanks !

**Comment by jywarren** [comment]
Hmm. I didn't make much of that error log to be honest! ☹️ But i noticed you're on Ruby 2.5 -- we are on 2.4.4 -- maybe changing that will help?

**Comment by AmanGarg97** [comment]
I changed that in gemlock file but it didn't changed the error log. Thanks!

**Comment by dinaelhanan** [comment]
Hey! @AmanGarg97, I know I'm just repeating what it says below, but just wanted to point out that this could be merged if you fix the conflicting file `app/views/tag/show.html.erb`!

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR.
Thanks for contributing at Public Lab

**Pull request closed without merging**
