### PR TITLE
Fix like count on post when pressed continously

### LINKED ISSUE #3524: Continuous like button press shows unexpected behavior
### Please describe the problem (or idea)
When like button is pressed continuously it shows unexpected behaviour. Like may go to negative values also. On refreshing page problem is solved.

> What happened just before the problem occurred? Or what problem could this idea solve?

like

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors

### What's your PublicLab.org username?
igniteeng000
> This can help us diagnose the issue: 

### Browser, version, and operating system
Windows 10, chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Radhikadua123**
Fixes #3524 #3869 #3870

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Radhikadua123** [comment]
@publiclab/reviewers I'm unable to understand tests workflow. I was considering the "inclusion of the like.js" in tests as black box part but seems like I'll need to understand it. 

Can anyone please help me in figuring this out ?

**Comment by Radhikadua123** [comment]
@Souravirus I saw you were author of those tests. Can you please give me a hint or refer me to some file ? :)

**Comment by Souravirus** [comment]
Actually, the tests that are currently failing are the teaspoon mocha tests. You can read about the tests we follow from [here](https://github.com/publiclab/plots2/blob/master/doc/TESTING.md). So, you can correct those by learning a little bit about mocha testing for javascript. Thank you!!

**Comment by Radhikadua123** [comment]
I tried to understand how `like.js` file has been included in the tests. But I didn't get it. Seems like I'm stuck on this one.

**Comment by jywarren** [comment]
The files are included in in this file: https://github.com/publiclab/plots2/blob/master/spec/teaspoon_env.rb

Perhaps we could open an issue to expand the documentation for Teaspoon/Mocha client-side tests? 

Thank you all! 👍

**Comment by jywarren** [comment]
However, our testing for this feature isn't super flexible -- it's based around these static fixture files: 

https://github.com/publiclab/plots2/tree/master/spec/javascripts/fixtures

Basically the JavaScript tests can't be run on dynamically generated Ruby code, so we run them on static "copies" of the Ruby-generated files. Not ideal! But in some ways, makes sense -- we want tests run against some fixed data, so if both Ruby and JavaScript both change, we don't miss something between them. The fixtures are like the "agreed-upon meeting point" between them. Make sense?

**Comment by Radhikadua123** [comment]
Hi @jywarren,

I see. Thanks a lot of the hint! I'll have a look at teaspoon_env.rb and will fix tests.

> we want tests run against some fixed data, so if both Ruby and JavaScript both change, we don't miss something between them. The fixtures are like the "agreed-upon meeting point" between them.

Yeah, we can't run javascript tests on the dynamically generated ruby views. So, this seems to be the best way to do unit testing for those components. I was also thinking what if we write up end-to-end tests instead of unit tests here. So, flow would be like this: We run the rails server in the backend and load up some data into the database. Then we launch the browser and try to test the functionality. So, this way, whole end to end testing would be performed making sure it functions as expected. Lot of projects use Selenium API for this usecase. Though bad thing about it is, it increases up test time.

**Comment by Radhikadua123** [comment]
@jywarren @Souravirus Please review this PR. Sorry, it also involves other changes. I realized those ones when I was trying to fix the tests and found that my tests are failing because of problem in the test framework configuration.

**Comment by Souravirus** [comment]
Nice work with the chromedriver @Radhikadua123 and the cleanups related to jasmine tests. Lets wait for the review of @jywarren. Thank you for all your hardwork!!

**Comment by SidharthBansal** [comment]
@Radhikadua123 there are some conflicts can you please remove them

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
