### PR TITLE
Comment and sent email when co-author added

### LINKED ISSUE #2028: send email to newly added coauthors explaining what it means
This could actually be relatively simply achieved via a comment -- by automatically leaving a comment as we do for the barnstar feature:

https://github.com/publiclab/plots2/blob/dccf61b4cf0aa816a3a906495ea6a0b2d5d847b0/app/controllers/tag_controller.rb#L178-L180

The comment could say `@_author_ has marked @_recipient_ as a co-author.` and everybody on the thread would get email notified.

This code would go just before the last line of this block:

https://github.com/publiclab/plots2/blob/033676b8abd28cd56a999e60934ff9f01bd0a9ac/app/models/node.rb#L660-L667

and the message could look like:

```ruby
"_@#{user.username} has marked @#{node.author.username} as a co-author._"
```

This should work but could take some troubleshooting -- happy to help, and any assistance in taking this task on is appreciated!

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2028 

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
Hey @jywarren, please give your input in finalizing the body of the mail.

coauth_mailer

Also, user has marked you as a co-author OR user has added you as a co-author.Which one sounds good?

**Comment by jywarren** [comment]
Let's go with `user has added you as a co-author` -- and we still need to remove `Suggest content for this area` -- thank you!!! This is exciting! :-) 👍

**Comment by Gauravano** [comment]
Ok @jywarren , I will do the required changes.Thanks!

**Comment by jywarren** [comment]
awesome, thanks!

**Comment by Gauravano** [comment]
hi, @jywarren I have done the changes and also added a test for it.

**Comment by jywarren** [comment]
Oof, sorry, i should have merged this one first, but now it has some conflicts. I'm sure it's nothing serious -- if you can rebase over them we'll merge this in! Thank you and apologies!!! 👍

**Comment by Gauravano** [comment]
hi, @jywarren I have resolved the conflict.

**Pull request merged**
