### PR TITLE
added unit tests for sort by follower count

### LINKED ISSUE #4570: Unit test for sort by follower count in tags model
Addition of unit test to check that tags get correctly ordered in ascending and descending order by use of function sort by follower count in tags model.

### PR DESCRIPTION
**Pull request by shubhscoder**
Fixes #4570

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
is it ready for review?

**Comment by gauravano** [comment]
Also, please mark the checklist as it gives some clarity about the progress just by hovering our PR link. Thanks!

**Comment by shubhscoder** [comment]
Yeah @gauravano , this is ready for review and yes I ll make sure that checklist is marked appropriately. Thank you so much !

**Comment by gauravano** [comment]
@jywarren @SidharthBansal please give one more review. Thanks!

**Comment by jywarren** [comment]
Nicely done!!!

**Pull request merged**
