### PR TITLE
Profile drop down menu gets cutoff on smaller screens

### LINKED ISSUE #6572: Make the SignUp popup responsive
#### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When you open https://publiclab.org/ in your mobile browser and click on the `Sign Up` button from the menu, a pop up modal appears which is not responsive.

dek

> What did you expect to see that you didn't?

The modal should be responsive like the login modal.

### Please show us where to look

https://publiclab.org/ 

### What's your PublicLab.org username?

       debasish_sahoo1998

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### LINKED ISSUE #6574: Profile dropdown menu gets cut off on smaller screens
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The dropdown menu, from profile picture on the top right corner, gets cut off on smaller screens in mobile devices. On further investigation with the device mode in chrome dev tools, it looks like the menu begins to get cut off when the device height goes under 735px.
<p><span>
screenshot of the issue

Screenshot of dashboard(iPhone 5_SE)
</span></p>

> What did you expect to see that you didn't?

I expected to be able to scroll down to access the rest of the menu

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

christie_reni

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome, android
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by nitish81299**
Fixes #6574 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by nitish81299** [comment]
screenshot

Here's the screenshot of the utility implemented.

**Comment by nitish81299** [comment]
@SidharthBansal 
@susanreenesaa 
Have a look.

**Comment by SidharthBansal** [comment]
Please remove `test.sqlite-journal` file.
Also, please add appropriate screenshot/gif to show it is responsive.

**Comment by SidharthBansal** [comment]
Thanks for contributing at PL

**Comment by nitish81299** [comment]
@SidharthBansal 
The required changes are done, have a look.

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
