### PR TITLE
drupal_node to node

### PR DESCRIPTION
**Pull request by aayushgupta1**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by aayushgupta1** [comment]
@jywarren Kindly look if this is working

**Comment by aayushgupta1** [comment]
@jywarren PR : #1100 has stopped due to an error in command "rake db: setup". Please tell me what I'm doing wrong or what might be the probable cause of it.

**Comment by jywarren** [comment]
The key is here: `LoadError: Expected /app/app/models/node.rb to define Node`

I think you need to change this line to just `Node`: https://github.com/aayushgupta1/plots2/blob/d8223cb7a0fa392305be714859e06338bd18a978/app/models/drupal_node.rb#L16

**Comment by aayushgupta1** [comment]
Okay, I'll do that. I didn't notice that part.

**Comment by jywarren** [comment]
Hi, @aayushgupta1 - no need to close this PR -- in fact, it's more helpful if you push additional changes to this branch and we keep working in the same PR; that way our discussion is preserved. I can "squash" all your commits together once it's all done. Thanks!

**Comment by jywarren** [comment]
Ah, but i see you're developing in the `master` branch -- no need to worry right now, but after this issue is totally complete, you may want to read over this page for how to work in a named feature branch for future work:

https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

Thanks!

**Pull request closed without merging**
