### PR TITLE
Following and Followers page UI 

### LINKED ISSUE #8277: Refine /followers page design
Currently the /followers route doesn't have design consistent with the rest of the website. 
It looks like this 
Screenshot from 2020-08-10 17-06-57

Link: https://publiclab.org/people/cess/followers
We could implement a design with the same table as the "People who are following" table - the farthest right hand table on https://publiclab.org/contributors/water-quality. But other designs are welcome

### PR DESCRIPTION
**Pull request by renugasaraswathy**
Fixes #8277 and #8278 
Hi,

I have worked on the UI for Followers & Following page of users

Following URL - /people/**username**/following
Followers URL - /people/**username**/followers
Pagination is implemented for the same with 10 items per page

Screenshots of the same are attached below. 

image

image

image

@publiclab/reviewers, Please review and provide feedback.

Thanks

### CODE REVIEW

**Review by sagarpreet-chadha — COMMENTED** [review]
Awesomeee looks great!!! 😄 
Would it look better if we show something like *you are not following anyone yet* and *you have no followrers* instead of blank space? Thoughts?

**Comment by cesswairimu** [comment]
@renugasaraswathy  kindly checkout @sagarpreet-chadha  comment above. Thanks

**Comment by HarshKhandeparkar** [comment]
Ig you should mention plots2-reviewers next time. I am of no use here :joy:

**Comment by renugasaraswathy** [comment]
Hi @cesswairimu @sagarpreet-chadha,

Apologies I missed the comment. 
I have updated the messages as given in the screenshots below. Please review.   

Screenshot 2020-09-30 at 9 55 30 AM

image

**Review by Tlazypanda — APPROVED** [review]
@renugasaraswathy LGTM :tada: Thanks for working on this!!

**Review by cesswairimu — APPROVED** [review]
Fantastic :tada: thanks for working on this. Looks great

**Comment by jywarren** [comment]
Wow, so great!!! Thanks so much, to everyone!!! 🎉

**Comment by jywarren** [comment]
This is so cool. Actually where is this page linked from? It's not on the profile page, so I wonder if we ought to open a first-timers issue to add a link there - maybe in the list of "stats" on bottom right of the profile page -- like at https://publiclab.org/profile/liz, we could add it here:

image


What do you think? And, @renugasaraswathy would you have any interest in welcoming someone else to the community by creating such an issue? Here is some info on the process, if you're interested!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping `@publiclab/reviewers` to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by renugasaraswathy** [comment]
sure @jywarren. Will create this as an issue for first timers to contribute. 

Thanks everyone for helping me in this pull request.

**Comment by renugasaraswathy** [comment]
Hi @cesswairimu, is my changes merged to the Public Lab website? I still see old UI in the [followers page](https://publiclab.org/people/liz/followers)

**Comment by cesswairimu** [comment]
Right now they are at staging, stable.publiclab.org they will go live during o the next deployment.

**Pull request merged**
