### PR TITLE
Update show.html.erb

### PR DESCRIPTION
**Pull request by aayushgupta1**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

I am a first timer and was asked to move the comments box to bottom.

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! Thanks so much! I'm about to board a plane and probably won't be able
to review this for a bit, but we really appreciate your contribution!

**Comment by jywarren** [comment]
Hi! Unfortunately another first time contributor already claimed this and I merged that PR today. But I see you've submitted another so I'll check that one out, thanks!

**Comment by aayushgupta1** [comment]
Hi,

Which PR is this regarding?


Regards,

Aayush Gupta

**Comment by aayushgupta1** [comment]
Okay cool.

**Comment by jywarren** [comment]
#960

**Pull request closed without merging**
