### PR TITLE
Update notes_controller_test.rb

### PR DESCRIPTION
**Pull request by belfarz**
[Update notes_controller_test.rb](https://github.com/publiclab/plots2/commit/6ba5ea0e17a340ef7ece450a800ba99024af29da)
Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Review by TildaDares — CHANGES_REQUESTED** [review]
Hi @belfarz, the changes in this PR and in #11460 needs to be in a single PR. Thank you!

**Comment by belfarz** [comment]
HELLO @TildaDares thanks for the feedback but please how would i merge the
two PR

**Comment by TildaDares** [comment]
Hi @belfarz, since you’re already working on one FTO in https://github.com/publiclab/Leaflet.DistortableImage/pull/1104, maybe we can leave this issue for someone else to work on. Thanks!

**Comment by TildaDares** [comment]
Hi @belfarz, contributors are only allowed to work on one FTO. I'll be closing this to give another first-timer a chance to make a contribution. Thank you for your time and effort. We appreciate your contributions. Thank you!

**Pull request closed without merging**
