### PR TITLE
Replication quiz

### PR DESCRIPTION
**Pull request by jywarren**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer

Addresses https://github.com/publiclab/PublicLab.Editor/issues/29#issuecomment-243235940 -- but still needs:

* [x] put bold text in a status box
* [x] don't display a row of buttons if a powertag of that type already exists
* [ ] show **something** if there are no rows left
* [ ] consider sequential "quiz"
* [ ] display list of replication attempts
* [ ] consider `Is this an activity you're showing others how to do? [Mark it as an activity] to invite replications.` prompt

### CODE REVIEW

**Comment by jywarren** [comment]
Check it out @steviepubliclab and @ebarry -- screenshot:

screenshot 2016-08-29 at 7 08 02 pm

**Comment by jywarren** [comment]
We could show them sequentially, too?

**Comment by jywarren** [comment]
And:

> What status do you think it is? `request` `proposal` `draft` `in-progress` `review-me` `complete`

**Comment by steviepubliclab** [comment]
This is great. I'm a bit removed from the overall structure you're all
working on, so I'm not sure if this is appropriate, but what do you think
of having an annotative spot for people to provide written feedback? It
could be helpful for others who are thinking about trying it, and
potentially go back to the person who posted the activity?

But perhaps this is all captured in a RN that people post after?

**Comment by jywarren** [comment]
Yes, that could be in comments on the activity itself, and that's a great idea.

**Comment by ebarry** [comment]
this all looks great and @steviepubliclab's comment too

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
Posting a new issue for `status` and `category` until those questions are resolved: #750

**Pull request merged**
