### PR TITLE
body parameter method change from 100 to 500 (re: issue #1144)

### PR DESCRIPTION
**Pull request by devinbalkind**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [?] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this looks good, but since `body_preview` is used in a couple places, we need to parameterize it:

```ruby
def body_preview(length = 100)
    newBody = self.body.gsub(/^#+.+/, "")
    newBody.truncate(length)
end
```

And then, in this file, we can say `node.body_preview(500)`:

https://github.com/devinbalkind/plots2/blob/master/app/controllers/tag_controller.rb#L59

If you can add these two things, I'd love to accept this PR!

**Comment by devinbalkind** [comment]
I tired. I added the 500s to the first file but the second file qwith
node.body seems to be in a different branch or something. I editted it but
there isn't pull request options. Maybe the link you sent me was in my fork
and I should be editting in yours/publiclabs?

**Comment by jywarren** [comment]
I think you opened a new PR; there should be an option to "add directly to ___ branch". But I can take a look at this in a bit, thanks!

**Comment by jywarren** [comment]
The other PR (which we could try merging into here) is at #1242 (note to self)

**Comment by jywarren** [comment]
OK, made some tweaks and we'll see how they do.

**Comment by jywarren** [comment]
This passed, and should be all right. Merging, thank you!

**Comment by jywarren** [comment]
Oh, sorry, it's still running tests. Didn't refresh. Waiting a little longer!

**Comment by jywarren** [comment]
OK done -- merged; we should be able to publish in the next week!

**Comment by devinbalkind** [comment]
Thanks. I just figured out how to aggregate different APIs using Zapier's
Webhooks into AirTable so will be able to playing with this soon.

**Comment by jywarren** [comment]
super. Should be running by end of day.

**Comment by devinbalkind** [comment]
Grand.

You wouldn't happen to recall or have saved somewhere the RESTFUL endpoint
for FarmHack's tool API would you? I searched my email and the web for an
hour last night trying to find it and had no luck.

**Comment by jywarren** [comment]
sorry, no -- but you should email RJ or Mike Stenta about it!

**Pull request merged**
