### PR TITLE
fixed error on edit page fixes #3060

### LINKED ISSUE #3060: Error on edit page
### Please describe the problem (or idea)
image

### PR DESCRIPTION
**Pull request by dewanhimanshu**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by dewanhimanshu** [comment]
screenshot from 2018-07-14 10-31-41

**Comment by SidharthBansal** [comment]
Please write the issue number in the PR body. Reason-- when PR is merged issue is automatically closed.

**Comment by SidharthBansal** [comment]
Use keyword ''Fixes #30...'' In PR body

**Comment by SidharthBansal** [comment]
Can you please wrap your code inside the condition if params[controller ] is users and params[;action] is edit then only the code will execute? We use the form partial for a number of views so that will create no conflicts on those pages.
Pls provide screenshot after commuting the changes.

**Comment by dewanhimanshu** [comment]
screenshot from 2018-07-14 17-45-20

**Comment by SidharthBansal** [comment]
@dewanhimanshu you can try other issues at the repository under help wanted or bug section if you wish.
Do you want to work on https://github.com/publiclab/plots2/issues/2866? Just ping me if you want to involve in a bigger issue.

**Comment by SidharthBansal** [comment]
You can try https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Abug
OR https://github.com/publiclab/plots2/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Ahelp-wanted+ also

**Comment by SidharthBansal** [comment]
@jywarren can you kindly review this and suggest changes? This looks good to me.
Himanshu is doing a great job at Public Labs

**Comment by jywarren** [comment]
Agreed, this looks fantastic. Thank to you both!

**Comment by dewanhimanshu** [comment]
@SidharthBansal  thank you . I will solve more issues . I am enjoying working with PublicLab Team

**Comment by dewanhimanshu** [comment]
@SidharthBansal  in #2866 do we need to make the modal on our own or we can use some js library?

**Comment by SidharthBansal** [comment]
If you are interested in #2866 please ping people there. 
You can use anything with which you are comfortable. 
Ping me there if you wish to do the issue else I can take it. I will assign you the issue there.

**Comment by SidharthBansal** [comment]
I am asking to ping us there because the issues should not be mixed up. Modularity comes with rails. 
Thanks

**Comment by dewanhimanshu** [comment]
@SidharthBansal ok

**Pull request merged**
