### PR TITLE
(partially complete, adopt me) added add_like function to users and wrote corresponding rspec tests

### PR DESCRIPTION
**Pull request by franktank**
**Update** -- this needs the rspec tests to be refactored into the standard test suite, and we can then adopt the "add_like" method which is much cleaner. Please adopt me and help resolve this PR!

---
- [ ] tests pass -- `rake test`
- [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
- [ ] pull request are descriptively named
- [x] if possible, multiple commits squashed if they're smaller changes
- [ ] reviewed/confirmed/tested by another contributor or maintainer
- [x] `development.sqlite.example` has been updated if any database migrations were added

Added add_like to DrupalUsers.

### CODE REVIEW

**Comment by jywarren** [comment]
Thanks, franktank -- i'll be reviewing this tomorrow morning!

**Comment by jywarren** [comment]
Hi, @franktank -- I get an error when I run `rspec`, what do you think?

````
Failures:

  1) banning a spammer changes liked_by value on a note
     Failure/Error: assert spam_user.save({})

     Test::Unit::AssertionFailedError:
       <false> is not true.
     # /home/warren/.rvm/gems/ruby-2.1.2/gems/test-unit-3.1.8/lib/test/unit/assertions.rb:55:in `block in assert_block'
     # /home/warren/.rvm/gems/ruby-2.1.2/gems/test-unit-3.1.8/lib/test/unit/assertions.rb:1626:in `call'
     # /home/warren/.rvm/gems/ruby-2.1.2/gems/test-unit-3.1.8/lib/test/unit/assertions.rb:1626:in `_wrap_assertion'
     # /home/warren/.rvm/gems/ruby-2.1.2/gems/test-unit-3.1.8/lib/test/unit/assertions.rb:53:in `assert_block'
     # /home/warren/.rvm/gems/ruby-2.1.2/gems/test-unit-3.1.8/lib/test/unit/assertions.rb:163:in `block in assert'
     # /home/warren/.rvm/gems/ruby-2.1.2/gems/test-unit-3.1.8/lib/test/unit/assertions.rb:1631:in `call'
     # /home/warren/.rvm/gems/ruby-2.1.2/gems/test-unit-3.1.8/lib/test/unit/assertions.rb:1631:in `_wrap_assertion'
     # /home/warren/.rvm/gems/ruby-2.1.2/gems/test-unit-3.1.8/lib/test/unit/assertions.rb:130:in `assert'
     # ./spec/models/drupal_node_spec.rb:8:in `block (2 levels) in <top (required)>'

Finished in 0.1395 seconds (files took 6.4 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/drupal_node_spec.rb:5 # banning a spammer changes liked_by value on a note
````

**Comment by franktank** [comment]
That's strange, the test is passing on my end. I'll look into it.

**Comment by franktank** [comment]
Hi @jywarren,

You said .save({}) was the proper way of creating a user correct? I am not sure why this would return a false value.

**Comment by jywarren** [comment]
Yes -- i'm seeing a `User exists` error in the log:

````
Connecting to database specified by database.yml
  ESC[1mESC[36m (1.6ms)ESC[0m  ESC[1mBEGINESC[0m
  ESC[1mESC[35m (0.2ms)ESC[0m  SAVEPOINT active_record_1
  ESC[1mESC[36mUser Exists (4.0ms)ESC[0m  ESC[1mSELECT 1 AS one FROM `rusers` WHERE `rusers`.`email` = 'test@test.com' LIMIT 1ESC[0m
  ESC[1mESC[35mUser Exists (0.4ms)ESC[0m  SELECT 1 AS one FROM `rusers` WHERE `rusers`.`username` = 'spammer' LIMIT 1
  ESC[1mESC[36mUser Exists (1.7ms)ESC[0m  ESC[1mSELECT 1 AS one FROM `rusers` WHERE `rusers`.`persistence_token` = BINARY '52583bac8242858cf5e209220ee1b75f7fc9f9f02f61c2abadcfe62f40dafda304685de52e7a983b6af77ac2f149be83f8341b119b3b23d6a7b6fef2fdd0f78c' LIMIT 1ESC[0m
  ESC[1mESC[35mDrupalUsers Load (1.0ms)ESC[0m  SELECT `users`.* FROM `users` WHERE `users`.`name` = 'spammer' LIMIT 1
  ESC[1mESC[36m (0.4ms)ESC[0m  ESC[1mROLLBACK TO SAVEPOINT active_record_1ESC[0m
  ESC[1mESC[35m (0.2ms)ESC[0m  ROLLBACK
Connecting to database specified by database.yml
  ESC[1mESC[36m (0.2ms)ESC[0m  ESC[1mBEGINESC[0m
  ESC[1mESC[35m (0.2ms)ESC[0m  SAVEPOINT active_record_1
  ESC[1mESC[36mUser Exists (0.3ms)ESC[0m  ESC[1mSELECT 1 AS one FROM `rusers` WHERE `rusers`.`email` = 'test@test.com' LIMIT 1ESC[0m
  ESC[1mESC[35mUser Exists (0.2ms)ESC[0m  SELECT 1 AS one FROM `rusers` WHERE `rusers`.`username` = 'spammer' LIMIT 1
  ESC[1mESC[36mUser Exists (0.5ms)ESC[0m  ESC[1mSELECT 1 AS one FROM `rusers` WHERE `rusers`.`persistence_token` = BINARY 'a8f256328c16cd3b24f9f0fa79df6249086cb6c3a578f59d53353c8f36f59c9e0e92a9ab806063c217c10ce7b8540393da4d4e087ef2eaba53e0e3a4a02a944f' LIMIT 1ESC[0m
  ESC[1mESC[35mDrupalUsers Load (0.1ms)ESC[0m  SELECT `users`.* FROM `users` WHERE `users`.`name` = 'spammer' LIMIT 1
  ESC[1mESC[36m (0.3ms)ESC[0m  ESC[1mROLLBACK TO SAVEPOINT active_record_1ESC[0m
  ESC[1mESC[35m (0.1ms)ESC[0m  SAVEPOINT active_record_1
  ESC[1mESC[36mUser Exists (0.3ms)ESC[0m  ESC[1mSELECT 1 AS one FROM `rusers` WHERE `rusers`.`email` = 'test@test.com' LIMIT 1ESC[0m
  ESC[1mESC[35mUser Exists (0.3ms)ESC[0m  SELECT 1 AS one FROM `rusers` WHERE `rusers`.`username` = 'spammer' LIMIT 1
  ESC[1mESC[36mUser Exists (1.2ms)ESC[0m  ESC[1mSELECT 1 AS one FROM `rusers` WHERE `rusers`.`persistence_token` = BINARY 'a8f256328c16cd3b24f9f0fa79df6249086cb6c3a578f59d53353c8f36f59c9e0e92a9ab806063c217c10ce7b8540393da4d4e087ef2eaba53e0e3a4a02a944f' LIMIT 1ESC[0m
  ESC[1mESC[35mDrupalUsers Load (0.2ms)ESC[0m  SELECT `users`.* FROM `users` WHERE `users`.`name` = 'spammer' LIMIT 1
  ESC[1mESC[36m (0.2ms)ESC[0m  ESC[1mROLLBACK TO SAVEPOINT active_record_1ESC[0m
  ESC[1mESC[35m (0.2ms)ESC[0m  ROLLBACK
````

Can you try using the existing fixtures instead of creating your own inline ones? I don't know if rspec can access them the same way, but in the tests I've written, you can say users(:moderator) to get the "moderator" entry in the ruser (rails user) fixtures: https://github.com/publiclab/plots2/blob/master/test/fixtures/rusers.yml

**Comment by franktank** [comment]
Ok when I try using the fixtures by `bob = users(:bob)`

I get the error

```
Failure/Error: stmt = SQLite3::Statement.new( self, sql )
     
     ActiveRecord::StatementInvalid:
       SQLite3::SQLException: table users has no column named id: INSERT INTO "users" ("uid", "name", "status", "id") VALUES (1, 'Bob', 1, 902541635)
     # /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
     # /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
     # /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
     # /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
     # ------------------
     # --- Caused by: ---
     # SQLite3::SQLException:
     #   table users has no column named id
     #   /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
```

**Comment by jywarren** [comment]
ah -- the primary key of users is `uid` -- it's a legacy drupal table. It's confusing:

* the `DrupalUsers` Rails model corresponds to the database table "users"
* the `User` Rails model corresponds to the database table "rusers"

This is due to legacy code which we're trying to slowly mitigate in https://github.com/publiclab/plots2/issues/227

**Comment by franktank** [comment]
So should I approach this by just making a user that doesn't conflict with the fixtures?

**Comment by jywarren** [comment]
Hmm, I'm not sure what's causing the error exactly -- I see `INSERT INTO "users" ("uid", "name", "status", "id") VALUES (1, 'Bob', 1, 902541635)` but the fixture only has:

````yml
bob:
  uid: 1
  name: Bob
  status: 1
  mail: bob@publiclab.org
````

We're able to access fixtures from the other tests in this way. What was your complete test where you used `bob = users(:bob)` ?

**Comment by franktank** [comment]
Full test is

`require 'rails_helper'

describe "banning a spammer" do
    fixtures :all
    it "changes liked_by value on a note" do
        bob = users(:bob)
        byebug
        bob_uid = bob.uid
        byebug
        assert bob.save({})
        
        spam_user = User.new({username:'spammer', email: 'test@test.com', password: 'publiclab', password_confirmation: 'publiclab'})
        assert spam_user.save({})
        spam_uid = spam_user.uid
    
        writer_user = User.new({username:"writer", email: "writer@test.com", password: "publiclab", password_confirmation: "publiclab"})
        assert writer_user.save({})
        writer_uid = writer_user.uid
        
        research_note = DrupalNode.new({type:"note", title: "NicePost", uid: writer_uid})
        assert research_note.save
        research_note_nid = research_note.nid
        
        bob.drupal_user.add_like(research_note_nid, true)
        expect { bob.drupal_user.ban }.to change {DrupalNode.where(nid: research_note_nid).first.liked_by(spam_uid)}
    end    
end`


error is

` Failure/Error: stmt = SQLite3::Statement.new( self, sql )
     
     ActiveRecord::StatementInvalid:
       SQLite3::SQLException: table users has no column named id: INSERT INTO "users" ("uid", "name", "status", "id") VALUES (1, 'Bob', 1, 902541635)
     # /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
     # /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
     # /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
     # /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
     # ------------------
     # --- Caused by: ---
     # SQLite3::SQLException:
     #   table users has no column named id
     #   /usr/local/rvm/gems/ruby-2.1.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
`

**Comment by jywarren** [comment]
Hmm, I'm not sure why an `id:` is being inserted there -- see the corresponding fixture:

https://github.com/publiclab/plots2/blob/master/test/fixtures/users.yml#L1-L5

However, it looks like you're trying to use User.new, which is a Rails user, so you'd instead say:

            bob = rusers(:bob)

Maybe this will bypass the error, whatever it is.

**Comment by franktank** [comment]
Just tried it, no luck. 

` SQLite3::SQLException: table users has no column named id: INSERT INTO "users" ("uid", "name", "status", "mail", "id") VALUES (1, 'Bob', 1, 'bob@publiclab.org', 902541635)
`

Not sure where the `902541635` comes from.

**Comment by jywarren** [comment]
That's so weird, because rusers should definitely not create a User. `id`
is being auto-generated because it's a default primary key in Rails. Hmm...

**Comment by jywarren** [comment]
I'm not that familiar with RSpec, but is it possible that you have to tell RSpec the table names or the primary key, the same way we do here? 

https://github.com/publiclab/plots2/blob/master/app/models/drupal_users.rb#L4

**Comment by franktank** [comment]
Hmm, I'm not sure, I think I might setup factorygirl because I have more experience with that.

**Comment by jywarren** [comment]
I think perhaps we should move the tests back into the basic testing
framework we're already using. I just removed factory girl a couple weeks
ago as it seemed to present unneeded complexity.

**Comment by franktank** [comment]
Okay sure, we can move back to unit tests.

**Comment by jywarren** [comment]
Sorry, FrankTank, I know this is frustrating, and I appreciate your persistence. I do have more experience with the basic test framework than with rspec + fixtures, so hopefully we can get this ironed out quickly.

**Comment by ebarry** [comment]
Thanks FrankTank!!!!!!!!!

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by ryzokuken** [comment]
Hello! You must've noticed that the unit tests failed unexpectedly on your PR. This was due to some issue in the Travis CI testing configuration which was fixed by @jywarren later tonight. In order to make them work again, please rebase your work on top of the current master and then try pushing to your remote branch. Do this by:

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <my-branch>
$ git rebase master
$ git push origin <my-branch>
```

Thanks for bearing with us,
Ujjwal

**Comment by ryzokuken** [comment]
@jywarren Any idea about the status on this one? :stuck_out_tongue:

**Comment by jywarren** [comment]
This is a very old one. I think we may want to close it, but there are some good bits which could be used (perhaps referenced from) an issue such as #607 (or a broken up sub-issue of that):

There's a good implementation of a `node.add_like()` method, similar to how we wanted to do `node.like()` and `node.unlike()`:

https://github.com/publiclab/plots2/pull/498/files#diff-6d19b06fe3aa2a81f4c92c199d8977cdR164

But it would need to be unit tested. I think this should be closed and we should focus on a clean, tested implementation. But its a good reference!

**Pull request closed without merging**
