### PR TITLE
Removing condition for multi-tag subscribe button

### LINKED ISSUE #5313: Removing Like condition from multi-tag subscribe button
Just a little change to #5246 .
Removing the condition whether the user has liked a node or not and displaying the multi-tag subscribe button irrespective of this.

### PR DESCRIPTION
**Pull request by IshaGupta18**
Fixes #5313 

Multi-tag subscribe button can now be visible to all users!

### CODE REVIEW

**Comment by IshaGupta18** [comment]
@jywarren @gauravano here's my PR for the follow up on #5246. Let me know what else can be done here. Thanks a lot!

**Comment by IshaGupta18** [comment]
Also, I feel that we don't need a follow button on tooltips anymore, so we can get rid of that. What do you think?
Screenshot from 2019-03-31 01-55-32

I could make an FTO for this if it's okay!

**Comment by gauravano** [comment]
It's your call @IshaGupta18, whether you want to open an FTO for this or not. I think work is complete here, so whatever it would be let me know. I am ready to merge this too. Thanks!

**Comment by IshaGupta18** [comment]
Actually, I realized the FTO thing a little late, so that's why I suggested
that I could make another FTO in it's place, for the follow button thing.
As for this one, since the work is complete here, I think this can be
merged. Would that be okay?

**Comment by gauravano** [comment]
Yes :+1:

**Comment by gauravano** [comment]
Merged :tada: . Thanks @IshaGupta18!

**Comment by IshaGupta18** [comment]
Thanks a lot 🎉

**Comment by jywarren** [comment]
Hi IshaGupta18! Thanks! Merging this now, but I think we should try keeping
the tooltips a bit longer to see how this does. We can also do some user
studies to see what people prefer, where they get stuck, using
https://lookback.io -- what do you think?

**Comment by IshaGupta18** [comment]
Hey, I think it makes sense. If we do this, we can also improve on the
button's design to make it more usable. We can keep the tooltip and explore
on how to make the multi-tag subscribe button more accessible. Thanks!

**Pull request merged**
