### PR TITLE
Changed toggle UI button CSS for conversation thread in comments. 

### LINKED ISSUE #3374: UI :: Add css to reply by email thread button
#### With the merge of https://github.com/publiclab/plots2/pull/2669 we have a reply by email feature. And reply by email is stable and working, so now we can start working on some ui improvement for it.
Starting with the basic improvement:
Email thread button on any comment page is a link on clicking which whole conversation thread open-up but the way link looks can be improved with a tooltip saying [click here to view the conversation thread] with some improvement of link button from :
screen shot 2018-09-21 at 2 08 35 pm
to:
screen shot 2018-09-21 at 2 08 57 pm

and also while hovering we can change the default link behaviour to not show underline on link while hovering and also we can show hand-pointer on hovering the link.
This is basic ui improvement so labeling it to `first-timers-issue`

Comment can be found at: https://publiclab.org/notes/namangupta/02-17-2018/gsoc-proposal#c20071

### PR DESCRIPTION
**Pull request by shivani-kapania**
Updated: app/views/notes/_comment.html.erb

Fixes #3374 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
Nice work @shivani-kapania !!!
Can you please add the screenshot?

**Comment by shivani-kapania** [comment]
Yes @namangupta01 I'll add a screenshot. Thanks!

**Comment by shivani-kapania** [comment]
> Nice work @shivani-kapania !!!
> Can you please add the screenshot?

This is how the earlier toggle button for reply threads looked like: 

screen shot 2018-09-24 at 2 18 53 pm

And now, it looks like this. On hovering, it shows a hand as the cursor pointer: 

screen shot 2018-09-24 at 2 16 45 pm

**Comment by namangupta01** [comment]
Nice work!

**Comment by shivani-kapania** [comment]
> Nice work!

Thanks!

**Comment by jywarren** [comment]
Awesome!!! Love this! 👍 🎉

**Comment by shivani-kapania** [comment]
> Congrats on merging your first pull request! 🙌🎉⚡️ Your code will likely be published to PublicLab.org in the next few days. In the meantime, can you tell us your Twitter handle so we can thank you properly?

Hi, thank you! My twitter handle is ShivaniKapania. 👍

**Pull request merged**
