### PR TITLE
Using new API in maps .

### LINKED ISSUE #4383: Add spinner to _leaflet.html.erb .
To be done once #4381 and #4382 are successfully completed 😄 !

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #4383  , #4382 , #4381 !

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
@milaaraujo 

In my **localhost** , Using this URL :

 http://localhost:3000/api/srch/nearbyPeople?nwlat=34.52466147177175&selat=10.401377554543553&nwlng=48.60351562500001&selng=121.11328125000001

gives no items :

screenshot 2019-01-05 at 4 15 08 pm

but i have a person named **URI**  within this rectangle : 

screenshot 2019-01-05 at 4 18 15 pm

having **Lat:22 and Lon:77** !

**Comment by sagarpreet-chadha** [comment]
The server log for above API call is : 

screenshot 2019-01-05 at 4 32 44 pm

**Comment by sagarpreet-chadha** [comment]
Super weird ! No , `location:blurred ` tag is not present .
I know it is a problem in localhost and not in production . I will try to figure it out later 😅 . Thanks you ! 
Closing PR  #4535 .

**Comment by jywarren** [comment]
Oh awesome is this good to merge then? 😁

**Comment by sagarpreet-chadha** [comment]
Yes . Thanks !

**Comment by jywarren** [comment]
Great, for which pages does this apply? Thank you!!!

**Pull request merged**
