### PR TITLE
Add all time stats option filter

### LINKED ISSUE #5904: Add 'all time' option for stats
I have also encountered this error when attempting to guestimate the start date for our website so that i could view data "For All Time". 

I'm wondering if it's really a bug or perhaps maybe it could be worked around by people not having to guess when we started logging data for our website? 

If it's the latter, here's an idea: 
On the "Choose a Start Date" interface, could we add the exact start date of our website as a "quick pick" OR perhaps make an option to choose "for all time" as the period of inquiry?

_Originally posted by @ebarry in https://github.com/publiclab/plots2/issues/5490#issuecomment-497454355_

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #5904
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
@skilfullycurled I think the data error still persists tried a query from Jan2013 - Dec 2013...same error #5490. So I have set it as from 2014 for the `all time option` for now until we can solve the data issue. What do you think?

**Comment by jywarren** [comment]
Hi @cesswairimu just marking this as in-progress until it's ready. thanks!

**Comment by skilfullycurled** [comment]
Sorry for the delay @cesswairimu, I was traveling.  I think what you did (limiting to 2014) is perfect for what I hope will be a short time being.  The good news is that I believe I've narrowed down the day of the problem and I have a theory as to it's cause.

**Short story:** _I believe one of the original offending dates (4/25/2013) is still causing trouble and although the post-fix test which ended in 4/25/2013 passed, this was only because the "start date" is inclusive but the "end date" is exclusive._ 

**Proposed Solution:** Assuming the problem is the same, the solution is the fix @jywarren found in #5490.  There must be remaining NodeTag record(s) which point to a non-existant tid(s) and need to be removed.

My reasoning is below, but you might as well go ahead and try the solution as @jywarren outlined in #5490 and it if doesn't work you can take a look at how I arrived there and see if there is a flaw in my logic.

||
||
||
\\/

**Reasoning:** In #5490, @cesswairimu had narrowed down the problem date to 4/25/13.  @jywarren successfully fixed the issue by removing [NodeTag records pointing at non-existent tids](https://github.com/publiclab/plots2/issues/5490#issuecomment-502931726) afterwhich the test case from [1/1/12 - 4/25/13](https://publiclab.org/stats?start=01-01-2012&end=25-04-2013 ) worked.  Therefore, I figured that the problem must be after that date.  To find the next offending date, I did a month by month query from 4/26/2013 through 12/31/2013 yet everything worked as expected.  

Then I did a series of queries with successively decreasing time windows starting at 4/25/2013 through 4/30/2013 by increasing the start date by one day each query (4/25/2013 - 4/30/2013, 4/26/2013 - 4/30/2013...).  The only query that did not work was the first one, 4/25/2013 - 4/30/2013).

Where it got strange was when I performed a day by day query starting at 4/25/2013 through 4/30/2013 (4/25/2013 - 4/25/2013, 4/26/2013 - 4/26/2013...) and in this case, 4/25/2013 _did_ work.

At this point, I suspected the issue might be one of start/end date inclusion/exclusion, so I repeated the day by day test but this time under the assumption that the start date was inclusive but the end date was exclusive (e.g., 4/25/13 - 4/26/13).  Once again, the date with 4/25/13 returned to causing a failure.  This would also explain why that 4/25/13-4/25/13 works because it doesn't return anything.

**Comment by cesswairimu** [comment]
Great investigation @skilfullycurled :100: ,  I believe your proposed solution will work. I guess we shall wait for Jeff to come back and so that he can remove the fault record(s). I could write a rake task that deletes the nodes with no tids..but I am not sure if its necessary will have to wait for Jeff on that too. Thanks  a lot :+1:

**Comment by jywarren** [comment]
Hi, all, just catching up here, thanks! So, is there a target date I should look for a tid-less NodeTag at? Could I simply look for ALL NodeTags with no tid, or no matching Tag, and delete them? I would hope there aren't many.

**Comment by skilfullycurled** [comment]
> So, is there a target date I should look for a tid-less NodeTag at? 

@jywarren, based upon my investigation (see logic above) I believe the only day that should have one is 4/25/13.  If it was not very time/computationally expensive, you could look from 4/25/13 (inclusive) to the end of the year (inclusive), but I believe the result of my analysis leaves only 4/25/13 as the offending time period.  Since I've downloaded every yearly set of data, I think running the inquiry on the entire database would be overkill but it's the only way to be sure.  I suppose we could split the difference and only look from the beginning until the point at which the tag setup changed in the database but I don't know when that was.  Or, perhaps until Plots2 was deployed.

> Could I simply look for ALL NodeTags with no tid, or no matching Tag, and delete them? 

I think this was your strategy last time.  You can see what you past @jywarren did [here](https://github.com/publiclab/plots2/issues/5490#issuecomment-502931726).

As an aside: I believe the reason why we missed this date was due to confusion over the end date being inclusive when it was exclusive.  Should we be making all dates inclusive?  Or perhaps stating on the page that the start date is inclusive but the end date is exclusive?  Not sure how hard the change is, but my expectation would be that when I ask for a collection of data, it will return that data through the specified end date.

**Comment by jywarren** [comment]
Finally merging this, thank you @cesswairimu !!!!

**Comment by ebarry** [comment]
This is super exciting, thanks @cesswairimu @jywarren @skilfullycurled !!!!

**Pull request merged**
