### PR TITLE
Solr search implementation

### PR DESCRIPTION
**Pull request by ujithaperera**
* [ ] All tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

### CODE REVIEW

**Comment by ujithaperera** [comment]
This PR is created to represent #663 with latest rebase

**Comment by jywarren** [comment]
Oh, cool - so is this ready to be merged? I'm about to merge a bunch of
smaller PRs, but I can hold off if that's helpful.

**Comment by ujithaperera** [comment]
Yes Jeff ! we can merge this PR. All the tests are passed in my local. have to run solr server in test environment to avoid solr connection errors. Instructions are in the README.md

**Comment by ujithaperera** [comment]
We have to add `RAILS_ENV=test bundle exec rake sunspot:solr:start` this line to the Cl script to run tests successfully, I think

**Comment by jywarren** [comment]
Ujitha - do you know which file to add that line to, or do you need to ask @icarito for guidance? It's either a Travis or Docker configuration, i think.

**Comment by ujithaperera** [comment]
we can add `docker-compose run web RAILS_ENV=test bundle exec rake sunspot:solr:start` line to [.travis.yml](https://github.com/publiclab/plots2/blob/master/.travis.yml#L13). 

As far as I know this should start solr in test env. Since solr is separate server running in different port in the server, perhaps docker may need additional configurations inside the server. 
let's verify from @icarito

**Comment by jywarren** [comment]
Ujitha - try adding that and pushing here, to see if it passes TravisCI
tests. If not, we can just roll back that commit.

**Comment by ujithaperera** [comment]
@jywarren I tried with several possibilities. But finally end up with this error `Sunspot::Solr::Server::JavaMissing: You need a Java Runtime Environment to run the Solr server`

@icarito ,  Can you have a look in this matter.

**Comment by jywarren** [comment]
Ok, that's great progress. I'm curious - if I continue accepting PRs, will
that cause a lot of trouble for rebasing for you?

**Comment by jywarren** [comment]
Noting that for me, I had to run:

`sudo apt-get install openjdk-7-jre openjdk-7-jdk icedtea-7-plugin`

on Ubuntu on ARM7

**Comment by jywarren** [comment]
Hmm, on the reindex command, i get: 

`RSolr::Error::ConnectionRefused: Connection refused - {:data=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><delete><query>type:DrupalNode</query></delete>", :headers=>{
"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update", :uri=>#<URI::HTTP:0x701b278 URL:http://localhost:8982/solr/dev
elopment/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}`

**Comment by jywarren** [comment]
but it seems if i start solr first, reindexing does work!

**Comment by ujithaperera** [comment]
yes Jeff, have to start solr first.

**Comment by jywarren** [comment]
yes - i think you need to reverse those steps in the README install instructions. And mention that you'll need a Java install!

**Comment by jywarren** [comment]
You can also probably include the install steps I mentioned in the `/Dockerfile` -- there's apt-get install steps there. 

I ran tests but got connection refused errors. I think I have to set this up for the test database too? It says Solr is running, why won't it connect?

**Comment by jywarren** [comment]
OK, trying `RAILS_ENV=test bundle exec rake sunspot:solr:start` before tests

**Comment by ujithaperera** [comment]
yes, for tests need to run solr in test env

**Comment by jywarren** [comment]
That worked, but new error:

```
Error: test_update_wiki_selecting_previous_image(WikiControllerTest):
  RSolr::Error::Http: RSolr::Error::Http - 500 Internal Server Error
  Error:     {msg=SolrCore &apos;test&apos; is not available due to init failure: Index locked for write for core &apos;test&apos;. Solr now longer supports forceful 
unlocking via &apos;unlockOnStartup&apos;. Please verify locks manually!,trace=org.apache.solr.common.SolrException: SolrCore &apos;test&apos; is not available due to
 init failure: Index locked for write for core &apos;test&apos;. Solr now longer supports forceful unlocking via &apos;unlockOnStartup&apos;. Please verify locks manu
ally!
        at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:974)
        at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:250)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:417)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:214)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:179)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)

  URI: http://localhost:8981/solr/test/update?wt=ruby
  Request Headers: {"Content-Type"=>"text/xml"}
  Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">DrupalNodeRevision 1027611808</field><field name=\"type\">DrupalNodeRevision</
field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">DrupalNodeRevision</field><field boost=\"5\" name=\"title_text\">New Title</field><fie
ld name=\"body_text\">Editing about Page</field><field name=\"teaser_text\"/></doc></add>"

  Backtrace: /home/warren/.rvm/gems/ruby-2.1.2/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/sunspot_rails-2.2.5/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `block in instrument'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `instrument'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/sunspot_rails-2.2.5/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
  (eval):2:in `post'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/rsolr-1.1.2/lib/rsolr/client.rb:84:in `update'
  /home/warren/.rvm/gems/ruby-2.1.2/gems/rsolr-1.1.2/lib/rsolr/client.rb:104:in `add'
app/controllers/wiki_controller.rb:141:in `block in update'
app/controllers/wiki_controller.rb:140:in `update'
test/functional/wiki_controller_test.rb:132:in `block in <class:WikiControllerTest>'
```

**Comment by jywarren** [comment]
Hi, Ujitha - it looks like you have some viable next steps:

* [ ] put java deps into `Dockerfile`
* [ ] put `RAILS_ENV=test bundle exec rake sunspot:solr:start` into `Dockerfile`
* [ ] rearrange README steps
* [ ] investigate Solr error (maybe to do with a deprecated version?)

I think we can get the tests to pass if we work through this checklist. And since all of your commits are your own, with none mixed in from master, rebasing should be pretty clean and straightforward, so I'm going to go ahead and merge other PRs while you work on this. Just ensure your commits (and only yours) are cleanly rebased and you can work on this a bit without holding things up. Thanks!

**Comment by ujithaperera** [comment]
Yes. we can follow this plan. I'll take care of these issues.

**Comment by ujithaperera** [comment]
Hi @jywarren, I tried by putting command (`sudo apt-get install -y openjdk-7-jre`)  for installing java in several places. Since I have very minor knowledge about docker and travis-cl, still figuring out the correct place to put this command. 

Can you or @icarito check my last commits and guide me to solve this matter.

Thank you.

**Comment by jywarren** [comment]
I'm not sure myself, but it makes most sense to me to put it after `#
Install dependencies` in the Dockerfile. Did that not work? Can you push
that up and we can look at the output?

Thanks!

**Comment by icarito** [comment]
I'll have a look today at the dockerfile / travis conf.

Regards,

Sebastian

**Comment by jywarren** [comment]
Hi, Ujitha - did you try pushing a version which puts the `apt-get` command in the Dockerfile where I suggested? I'd like to get this merged as soon as we can, and I think we're close!

**Comment by ujithaperera** [comment]
yes Jeff, you can find this change in https://github.com/publiclab/plots2/pull/781/commits/b10dfd5916f1188b8acbf6000af1f01291965b07

**Comment by icarito** [comment]
Hi,
Sorry I took so long. I reviewed your `.travis.yml` file and `Dockerfile` and, your dependencies should be installed inside the Docker container (defined in `Dockerfile`), not the test server (defined in `.travis.yml`).

I'll try it.

**Comment by icarito** [comment]
Hi,
I just tried it and it got further ahead:
https://travis-ci.org/icarito/plots2/builds/158369043

```
Successfully started Solr ...
(...)
rake aborted!
RSolr::Error::ConnectionRefused: Connection refused - {:data=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">DrupalUsers 1</field><field name=\"type\">DrupalUsers</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">DrupalUsers</field><field name=\"name_s\">admin</field><field name=\"mail_s\">admin@example.com</field><field name=\"status_s\">1</field></doc></add>", :headers=>{"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update", :uri=>#<URI::HTTP:0x005622dfe292c8 URL:http://localhost:8981/solr/test/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}
(eval):2:in `post'
/app/app/models/user.rb:63:in `create_drupal_user'
/app/db/seeds.rb:13:in `<top (required)>'
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 8981
(eval):2:in `post'
/app/app/models/user.rb:63:in `create_drupal_user'
/app/db/seeds.rb:13:in `<top (required)>'
Tasks: TOP => db:setup => db:seed
```
I'm guessing Solr requires some configuration to work?

Note Docker runs everything within a container. You can install Docker and docker-compose if you like and manually follow the steps detailed in the .travis.yml file.

@jywarren It might be worthwhile to add a section to the README for building and using a container for development/testing, or comments to the Dockerfile / travis.yml file.

**Comment by icarito** [comment]
@ujithaperera I've issued a pull request to your pull request (I didn't know you could do that!).

Here's the changes I made for reference:
https://github.com/david-days/plots2/pull/8/commits/5ee1f5827c8b5c59443b79d82d72e1c96a0d4401

It still seems to not find Solr, but at least Solr finds Java now. ;-)

**Comment by jywarren** [comment]
I'm poking through this now... going to try to see where/why the solr server doesn't start. This line looks fine: https://github.com/publiclab/plots2/pull/781/files#diff-3254677a7917c6c01f55212f86c57fbfR14 but isn't it missing `icedtea-7-plugin` ?

**Comment by jywarren** [comment]
OK -- I've rebased this entire PR on top of the latest master, in #810, adding the icedtea line. We'll see how this goes.

**Comment by jywarren** [comment]
All merged in #810!

**Pull request closed without merging**
