### PR TITLE
issue 2310 first time commit

### PR DESCRIPTION
**Pull request by milindra**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by seafr** [comment]
#2310 has already been claimed by @jsmayo.
@milindra please find another issue to claim [here](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only). Looking forward to your first contribution.

**Comment by seafr** [comment]
@jywarren this is a duplicate PR and it should be closed. See #2362, which has already been merged.

**Comment by jywarren** [comment]
Hi, @milindra -- thanks so much for your contribution. As the others have mentioned, this issue has already been solved, but we would love to help you make your first contribution -- maybe we can help you find one? 

I'm going to close this now but will make one you can try out instead.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/issues/2404 -- give this one a try!

**Pull request closed without merging**
