### PR TITLE
Trending tags showing duplicates

### LINKED ISSUE #3188: Trending tags showing duplicates
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

I think we're missing a `group()` or something on the https://publiclab.org/dashboard's trending tags area - i'm seeing 5 of the same:

screen shot 2018-08-02 at 12 29 19 pm

Here's the code - 

https://github.com/publiclab/plots2/blob/0663ac5f7ad7d047fc47e2b5b9ae59c943f354bc/app/models/tag.rb#L268-L277

And here's the test, where i'm not sure but maybe we should test to be sure they're unique? 

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/test/unit/tag_test.rb#L131-L137

Any help appreciated!

### PR DESCRIPTION
**Pull request by ValentinaTironi**
Fixes #3188

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, I wonder instead of `uniq` which will just eliminate duplicates, we might use `.distinct` which would query the database for only unique records. Would you want to give that a try? Thanks!!

**Comment by ValentinaTironi** [comment]
@jywarren Yes, of course!

**Comment by milaaraujo** [comment]
Hey @jywarren, can we merge this?

**Comment by jywarren** [comment]
Yes, excellent, thank you! Sorry, we have a bit of a PR backlog, thanks for your patience!!

**Pull request merged**
