### PR TITLE
docs: modifications to markdown files

### PR DESCRIPTION
**Pull request by rkpattnaik780**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by rkpattnaik780** [comment]
@publiclab/reviewers have a look!

**Comment by Manasa2850** [comment]
Amazing work @rkpattnaik780 :tada:

**Review by Manasa2850 — APPROVED** [review]

**Comment by cesswairimu** [comment]
HI @rkpattnaik780, could you please link me to the issue so that we can have it closed after this is merged?...thanks for  working on this

**Comment by rkpattnaik780** [comment]
> HI @rkpattnaik780, could you please link me to the issue so that we can have it closed after this is merged?...thanks for working on this

Thanks @cesswairimu ! I didn't create an issue for it. Should I create one now?

**Comment by cesswairimu** [comment]
no worries @rkpattnaik780, thanks again

**Pull request merged**
