### PR TITLE
Travis Fixes

### PR DESCRIPTION
**Pull request by cesswairimu**
Check if travis passes

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@cesswairimu I tried fixing it here can you check out #8085 Thanks :v:

**Comment by cesswairimu** [comment]
@Tlazypanda I rebased this and seems like its been running for an hour now.. also it looks like tests are not being ran on travis now...did we remove those from your PR that I just merged?

**Comment by Tlazypanda** [comment]
Hey @cesswairimu I actually reopened for one of my other prs #8076 and then it passed :sweat_smile: let us try this for this one as well :sweat_smile:

**Comment by cesswairimu** [comment]
Fantastic thanks :+1:

**Pull request closed without merging**
