### PR TITLE
Add methods to User model for verifying user roles

### PR DESCRIPTION
**Pull request by seafr**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by seafr** [comment]
If anyone can think of a better name for the `can_moderate?` method please let me know.

**Comment by seafr** [comment]
Any idea why this is failing? @jywarren @Gauravano

**Comment by Gauravano** [comment]
hi @seafr , all PR's are giving the same error from yesterday. I guess @jywarren or @icarito can help us.

**Comment by seafr** [comment]
OK, we'll wait for their feedback then. Thank you for letting me know.

**Comment by seafr** [comment]
Thank you for the kind words @jywarren :+1:

**Pull request merged**
