### PR TITLE
minor tweak

### PR DESCRIPTION
**Pull request by ViditChitkara**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

updates #919 

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by namangupta01** [comment]
Taken care in #2127

**Comment by ryzokuken** [comment]
@namangupta01 I see the changes you have made are different from those made by @ViditChitkara. Would you look at it and ensure that it works as intended?

**Comment by namangupta01** [comment]
@ryzokuken i already saw that and i have changed it accordingly. I just have to update the pr.

**Comment by ryzokuken** [comment]
Closing in favor of #2127

**Comment by jywarren** [comment]
Oops, ok folks, thanks for coordinating and let's remember to a) open PRs early, and maybe say hello in the chat (http://publiclab.org/chat) so we don't do redundant work. Thanks very much for this fix, @ViditChitkara -- and glad to see everyone's paying close attention to issues like this. Let's commit to some good teamwork! 

👍

**Comment by jywarren** [comment]
I'm going to re-run this since #2127 is not passing tests yet -- it's possible we'd pull this in first. It's important to do things in small chunks! Thank you!

**Comment by jywarren** [comment]
Merged! The in progress one will rebase over, i'm sure -- thank you!!!

**Pull request merged**
