### PR TITLE
new indices for impressionist

### LINKED ISSUE #2389: Cache impressions for optimizing SQL query
### Please describe the problem (or idea)

We are noticing that there's a query taking a lot of time and it could be causing small outages by consuming available threads.
The query is `publiclab@172.18.0.1: SELECT COUNT(*) FROM impressions WHERE impressions.impressionable_id = :int AND impressions.impressionable_type = :string` 

The suggestion by @jywarren is to **Optimize impressionist counts with a cache**:

- wrap this line in cache block: 
https://github.com/publiclab/plots2/blob/58bb6010e28d91106556b2cf07c9a100e3324c46/app/models/node.rb#L133

- example cache block that'll need a new "name":
https://github.com/publiclab/plots2/blob/245d6bc11383d220101f098d25b3843ce59e4c7d/app/views/home/home.html.erb#L133-L135

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by jywarren**
Maybe a better optimization than #2459, for fixes #2389

### CODE REVIEW

**Comment by jywarren** [comment]
@icarito we didn't have these -- for https://github.com/jywarren/web/issues/132 -- if this passes, we can deploy this and should see big improvement for #2459

**Comment by icarito** [comment]
Great, let me know and I can deploy in the evening!

Regards,

Sebastian

**Comment by jywarren** [comment]
Actually all Travis builds are failing right now. If you can poke around and see if it's a systemic issue on Travis, if we can do anything about it, that would be great... All PRs are affected!

**Comment by jywarren** [comment]
Fixed!!! OK, now this...

**Comment by jywarren** [comment]
If this passes, please deploy! Thank you!

**Comment by icarito** [comment]
This has been deployed! Thanks!
Have had to move out and regenerate `Gemfile.lock` which I think is not the right way to use the Gem locking... But sometimes deploying Rake refuses to work until I move Gemfile.lock out of the way. Not sure why this happens. Anyhow, this is deployed, hopefully will help with the performance issues.

**Pull request merged**
