### PR TITLE
Update app/controllers/tag_controller.rb

### PR DESCRIPTION
**Pull request by nwyll**
Issue #3419

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this is fantastic! 

Would you be interested in writing a test for this? It could be very much like this one: 

https://github.com/publiclab/plots2/blob/325d009b82258f8fd1b79fa47b4485eb354c836c/test/functional/tag_controller_test.rb#L143-L159

But adding the `order` parameter to check that that doesn't break anything?

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by nwyll** [comment]
> Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

Do we want to alter this test to include the order param or create a new test?

**Comment by jywarren** [comment]
I think a new test might be good - that way we are testing both the plain request and one with ordering. Lots of tests is good! 👍 

Thanks!!!

**Comment by jywarren** [comment]
Also, once this is merged, we can merge https://github.com/publiclab/plots2/pull/3468 !

**Comment by jywarren** [comment]
Hi, @nwyll -- we're happy to help you take the next step! If you're too busy at the moment you can always come back and we'll find you a new issue to work on as well. Thanks!

**Comment by nwyll** [comment]
Yes, sorry but  I am unable to work on this right now. 
    On Tuesday, October 16, 2018, 7:18:55 AM GMT+2, Jeffrey Warren <notifications@github.com> wrote:  
 
 
Hi, @nwyll -- we're happy to help you take the next step! If you're too busy at the moment you can always come back and we'll find you a new issue to work on as well. Thanks!

**Comment by jywarren** [comment]
No problem! We're happy to work with you on another issue if you'd like in the future!

**Pull request merged**
