### PR TITLE
Remove overlap between RSS icon and Sort button

### LINKED ISSUE #8970: Remove Overlap Between The RSS Icon and The Sort Button
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

If you Navigate to the `/notes` URL, then sort the notes according to Liked by using the Sort by button. You will notice that the RSS button overlaps with the sort button. There are steps below for you to follow and remove the overlap.

Screenshot 2021-01-07 at 19 30 16

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file below and edit the line as shown below. 
https://github.com/publiclab/plots2/blob/b3a9aec8d259807619bf9987679470be3bfc2234/app/views/notes/index.html.erb#L19

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
-  <% if params[:action] == "liked" %><a style="margin-right:9px;" class="float-right btn btn-outline-secondary btn-sm" href="/feed/liked.rss"><i class="fa fa-rss"></i></a><% end %>
+  <% if params[:action] == "liked" %><a style="margin-right:9px; margin-top: -33px;" class="float-right btn btn-outline-secondary btn-sm" href="/feed/liked.rss"><i class="fa fa-rss"></i></a><% end %>

```
Once You create a Pull Request, remember to take a screenshot of the change and attach it to the PR description.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by Iulia-H**
Fixes #8970 

Please review. Let me know if I should add anything else in the description.

image

### CODE REVIEW

**Review by Tlazypanda — COMMENTED** [review]
@Iulia-H The code changes look good :tada: Can you also add a screenshot of this from your local setup? I checked on gitpod and couldn't find the rss icon @RuthNjeri can you please also verify :sweat_smile: Thanks both!

**Comment by Iulia-H** [comment]
@Tlazypanda Is this what you mean? This is the screenshot from my forked repository. 

Screen Shot 2021-01-08 at 9 25 27 AM

**Comment by RuthNjeri** [comment]
Thanks @Tlazypanda 

@Iulia-H, thank you for creating this PR. I think what @Tlazypanda means is a screenshot of the application running that shows the buttons don't overlap.

**Comment by RuthNjeri** [comment]
I also tried testing it on Gitpod @Tlazypanda, and it seems that the database is broken on Gitpod, I'll follow it up with the other maintainers...

**Review by RuthNjeri — APPROVED** [review]

**Comment by RuthNjeri** [comment]
@jywarren this should be good to go 🚀 ...tested on Gitpod
Screenshot 2021-01-12 at 23 54 55

**Comment by jywarren** [comment]
Awesome, thank you!!!

**Pull request merged**
