### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by siaw23**

### CODE REVIEW

**Comment by siaw23** [comment]
BTW I'm making changes like this as part of fixing the speed issues from Skylight... there's a lot of refactoring to be done concerning issues on Skylight. But I'd rather do them in bits than a huge PR that won't be possible to review.

**Comment by siaw23** [comment]
@jywarren can you please check if this is OK?

I'm trying to finish all the TODOs in Rubocop while I wait for a decision on the one DB to start with Skylight issues.

**Comment by jywarren** [comment]
This looks all good at this point - it's reaching a size where it's hard to review though. Ready to merge as it is now? Thanks @siaw23 this is really great!!

**Comment by jywarren** [comment]
Small conflict now in user.rb, but once that's done I am cool with merging this! Epic!!! 👍

**Comment by siaw23** [comment]
Ready to merge.

**Comment by jywarren** [comment]
Awesome!!!!!

**Pull request merged**
