### PR TITLE
Patch for rake:test failure

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Let's see what Travis has to say about this. Meanwhile, sorry for the unneeded noise in the commit, but I cannot blame Atom for that. Plots2 is a pretty significantly large project IMO and must use a linter. Or maybe danger will do that for us?

**Comment by ryzokuken** [comment]
@jywarren The CI tests pass as well. What do you think about this? Is this wur to some issues in the DB generation code?

**Comment by jywarren** [comment]
I don't know -- but since tags cannot have capitals (on creation validation) this is a problem. 

But look how #1219 is not causing that test to fail: https://travis-ci.org/publiclab/plots2/builds/195768706

How do you account for that? Can you push your latest commit up to #1219 so we can see this test fail under those conditions?

**Comment by jywarren** [comment]
Hi, do you still think this is necessary? Thanks!

**Comment by ryzokuken** [comment]
@jywarren I'll rebase the current master to see if this issue is fixed. Thanks!

**Comment by ryzokuken** [comment]
@jywarren Rebased on top of latest master, still have that issue.

**Comment by jywarren** [comment]
Due to #1255, shall we close this then, and if we want to enforce case sensitivity etc, we can open a new issue and start on that with additional tests and such?

Thanks!

**Pull request closed without merging**
