### PR TITLE
Update default image for question cards on tag page #10880

### PR DESCRIPTION
**Pull request by codeamic**
Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @codeamic, can you add the issue number? Thanks!
`One thing that can help to get started is to make sure you've included a link back to the original issue you're solving, in the format fixes #0000 (for example).`

**Comment by codeamic** [comment]
Update default image for question cards on tag page #10880

**Comment by codeamic** [comment]
is it ok now @TildaDares ?

**Comment by codeamic** [comment]
PR #10815

**Review by TildaDares — APPROVED** [review]
Thanks @codeamic!! This is perfect.

**Comment by codeamic** [comment]
Thank you @TildaDares , looking forward to getting another task

**Pull request merged**
