### PR TITLE
Login modal for subscription buttons

### LINKED ISSUE #4160: Link Login Modal to Subscribe Tags
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Subscribe/Follow Tags
[publiclab.org/tags/](url)
`app/views/tag/index.html.erb`

screenshot 56

### LINKED ISSUE #4218: Login on alert bar doesn't work
Part of #4132
## Problem
The login button on the alert bar doesn't work.. On the browser console, it shows a SyntaxError.

image

@publiclab/mentors 
This issue should be resolved ASAP..

Thanks

### LINKED ISSUE #4231: Link Login Modal to Help Answer future questions
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to request an activity (The subscription link here). For modularity, this is separate from linking the button.
image

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #4218, Fixes #4160, Fixes #4231 
@publiclab/reviewers 
So this PR adds login modal at 4 places.

`Subscribe to answer questions` at tag pages
subscribe button login modal

`Alertbar`
alert bar login modal

`Help answer future questions` on grids
help answer future questions login

`Ask a question about tag` on tag pages
ask question login

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I'm gonna catch up on some sleep ..
If there are changes required, I'll do them tomm..
Thanks a lot

**Comment by SidharthBansal** [comment]
I am really sorry to close this PR @oorjitchowdhary. 
Today in the morning, I suggested you have 1 PR for 1 issue. We really emphasise on the modularity at Public Lab. Please read https://publiclab.org/notes/warren/01-18-2018/software-outreach-modularity-is-great-for-collaboration by @jywarren. 
Please open up different PRs for different issues. Paste related gifs and issue number.
Combining of issues into a single is not a good practice. I hope you will not mind.
Sorry for extra trouble.

**Comment by oorjitchowdhary** [comment]
Just gave it a read.. I really didn't know that it is a necessity.
Created 4 PRs #4428 #4429 #4430 #4432

**Comment by SidharthBansal** [comment]
Thanks a lot. I have merged all 4.

**Pull request closed without merging**
