### PR TITLE
fixed 5104 issue as instructed

### LINKED ISSUE #5104: Fix Pluralization Conditionals
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem
As shown below, the pluralization rules we have in place are incorrect. We want 1 _note_ and 0 research  _notes_.
Screen Shot 2019-03-16 at 7 16 00 AM

## Solution

The pluralization should look like this:
Screen Shot 2019-03-16 at 7 59 34 AM

This is a simple one -- let's change the following code:

1) In the below code, change the `<= 1` to just be `=== 1`. We don't want to include 0 in that conditional. This will change `0 research note` to `0 research notes`

https://github.com/publiclab/plots2/blob/d083415283dd89e0644e5bfe5ceb8e30b75dbecf/app/views/dashboard/_header.html.erb#L16

2) The below code is missing a condition all together:

https://github.com/publiclab/plots2/blob/d083415283dd89e0644e5bfe5ceb8e30b75dbecf/app/views/dashboard/_header.html.erb#L15

We want to change the first half of the line (the entire `<a></a>` element) to look like this:

```HTML
 <a href="/notes/recent"><%= @note_count %> <% if @note_count === 1 %> <%= t('dashboard._header.note') %><% else %> <%= t('dashboard._header.notes') %><% end %></a>

```
this will update `1 notes` to instead say `1 Note`. 

3) Why is the Note capitalized? While in the first fix we were dealing with `_header.research_note`, in the second we have `_header.note` 

Checking in the `en.yml` file, we find that: under, `_header`, there is a `notes` but no `note`:

https://github.com/publiclab/plots2/blob/d083415283dd89e0644e5bfe5ceb8e30b75dbecf/config/locales/en.yml#L312-L314

add a `note: "note"` key-value pair right below `notes: "notes"`

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by themonster2015**
Fixes #5104   fixed pluralization conditionals

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

Hi @publiclab/reviewers  attached is my screenshot of the app after fixing the problem. Hope to hear your feedback soon!
Screen Shot 2019-03-28 at 00 10 09

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@themonster2015 this looks great thank you for your work!!

Just one thing to update with your PR before I can approve it for merge: can you please checkout the `Gemfile.lock` file, we don't want to update that for the master branch! If its easiest you can just delete it locally and push another commit to this PR with it deleted.

And 1 tip for naming your PR in the future: you don't need to put the issue number in the PR title, just a description of what the PR is doing. This is because we already reference the original issue in the PR description.

**Comment by themonster2015** [comment]
Thanks for your feedback @sashadev-sky I just deleted the gemfile.lock file and committed it to the PR

**Comment by sashadev-sky** [comment]
@themonster2015 I expected it to just check out the file but instead its reading that you deleted the file. Try deleting it here in files changed then locally doing `git reset`, this will checkout all the files. Readding the files you need besides Gemfile.lock, and doing a `force` push back to this branch?

**Comment by themonster2015** [comment]
> @themonster2015 I expected it to just check out the file but instead its reading that you deleted the file. Try deleting it here in files changed then locally doing `git reset`, this will checkout all the files. Readding the files you need besides Gemfile.lock, and doing a `force` push back to this branch?

I'm sorry I think I just messed it up. I didn't understand your instructions fully so I reset git and reinitialized it in my local drive, then add back all the files, commit and force pushed, but now I think the PR has been automatically closed.

**Comment by sashadev-sky** [comment]
Thats ok! Not your fault. Would it be easier for you to just open a new PR with your changes?

**Comment by themonster2015** [comment]
I just started from scratch and created another PR.

**Comment by sashadev-sky** [comment]
@themonster2015 great thank you I see your PR and i'll review it there :)

**Pull request closed without merging**
