### PR TITLE
Updated share icon to link icon

### LINKED ISSUE #3592: Change share icon to link icon in questions page.
### Please describe the problem (or idea)
Change share icon to link icon in question page.

image

### Please show us where to look

https://publiclab.org/questions/TK_Siddharth/09-20-2018/what-would-be-the-day-to-day-use-of-spectroscopy

### What's your PublicLab.org username?
vikul1234
> This can help us diagnose the issue: 

### Browser, version, and operating system
windows 10 , chrome

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by vikul1234**
fixes #3592 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by vikul1234** [comment]
@publiclab/reviewers please review

**Comment by jywarren** [comment]
👍 👍 👍 🎉

**Comment by jywarren** [comment]
Hello, @vikul1234 -- i see you've applied to be a mentor in GCI -- and I love the first-timers-only issue you posted here. However, we're interested to see if you would like to welcome someone else new using a first-timers-only issue. You've definitely shown that you can make one -- would you be able to look through the `fto-candidates` to find one that you can "upgrade" into a first-timers-only issue and welcome someone else? Thank you!

**Comment by vikul1234** [comment]
Busy in mid-sem exams, free now.
Since almost all fto-candidates are solved or work in progress. So give me some another tasks.
Meanwhile i will try to create some fto-candidate tasks.

**Comment by vikul1234** [comment]
I have created two issues #3712 #3713. Please lable them. Should i change this issue to fto-candidate. what you think?

**Pull request merged**
