### PR TITLE
Commands to redeploy running container

### PR DESCRIPTION
**Pull request by icarito**
These are the commands to deploy in production. Once in I hope we can deploy using it.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
Oh! I'm affected by this issue too!

**Comment by icarito** [comment]
Anyhow I think it's safe to merge in any case at a convenient time I/we can try to deploy to production using `make redeploy-container`.

**Comment by jywarren** [comment]
If it's the octokit bug I'd really like to solve that first as it's
affecting all contributors... Any ideas?

**Comment by jywarren** [comment]
But this is awesome!

**Comment by jywarren** [comment]
Fixed! Merging. :tada:

**Pull request merged**
