### PR TITLE
Popup on tags display added

### PR DESCRIPTION
**Pull request by sukhbir-singh**
Fixes issue #2494 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by sukhbir-singh** [comment]
Screenshots:-

Node Tag
screenshot from 2018-04-01 00-31-50

User Tag
screenshot from 2018-04-01 00-31-36

**Comment by jywarren** [comment]
Oh this is looking really nice. Could we center and add a little padding?

**Comment by jywarren** [comment]
And let's make the date line a little smaller and #888 -- less emphasized! The title can also just be bold, not a header. It reads a bit more compactly then. 

And one more thing, could we add a "follow" button to the node tags? I think we can find logic for this on the subscriptions page!

Thanks, this is amazing!

**Comment by sukhbir-singh** [comment]
Updated popover:-

screenshot from 2018-04-01 01-59-43

**Comment by jywarren** [comment]
Oh, that's great. I think the button needs the `btn btn-primary` classes to get proper Bootstrap styles -- and i think the header of the popover is still an `h4` or something, where it could just be a `<b>` -- but looking great! And lets make "notes" and "people" lower case.

That should be the last thing! This is fantastic! Just confirming that this is displayed on click, not on hover, right? 

🎉

**Comment by sukhbir-singh** [comment]
@jywarren I did the remaining changes. Styled follow button using predefined class, changed popover appear on click rather than on hover, changed people and notes to lower case. The header of popover is set by `title` attribute of popover div, by default it is of type `<h3>`

We can change `<h3>` to simply `<b>` by specifying it in title attribute value string but that will make the label title on hover of mouse, to be non-user friendly. So, keeping the header as it is and have styled it using css to appear better on popover.

**Comment by jywarren** [comment]
This looks great, then. I'm going to merge it in! Thank you!!!

**Comment by jywarren** [comment]
👍 👍 👍 🎈 🎉

**Pull request merged**
