### PR TITLE
[WIP] Removed style-breaking classes from table

### LINKED ISSUE #6320: Table misaligned on /projects
Hello!

The table on the bottom of this page is showing up misaligned for me https://publiclab.org/wiki/projects. 
Screen Shot 2019-09-23 at 3 02 21 PM

I'm using Chrome.

### PR DESCRIPTION
**Pull request by dylmye**
Fixes #6320 

Removed classes, tested locally - screenshots to follow

* [x] tests pass
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this is looking good; can you share a screenshot of how it looks for you?

**Comment by jywarren** [comment]
You may need to use a power tag to create a table for testing: https://publiclab.org/wiki/power-tags

**Comment by dylmye** [comment]
Hi, I'm not at home but I've already got the project installed and everything, my aim is to get screenshots by end of day. Hope that's ok.

**Comment by dylmye** [comment]
Turns out I was wrong. I followed install instructions [here](https://github.com/publiclab/plots2#standard-installation) and I'm getting this issue (shortened for brevity):
```
Fetching libv8 3.16.14.19
Installing libv8 3.16.14.19 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:                                                                         
C:/Ruby/2.4/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8                            
C:/Ruby/2.4/bin/ruby.exe -r ./siteconf20191006-3476-48j0cm.rb extconf.rb                   
creating Makefile                                                                          
The system cannot find the path specified.                                                 
C:/Ruby/2.4/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8/builder.rb:86:in           
`setup_python!': libv8 requires python 2 to be installed in order to build, but            
it is currently 3.7.4 (RuntimeError)                                                       
from                                                                                       
C:/Ruby/2.4/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8/builder.rb:53:in           
`build_libv8!'                                                                             
from                                                                                       
C:/Ruby/2.4/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:24:in          
`install!'                                                                                 
        from extconf.rb:7:in `<main>'                                                      
                                                                                           
extconf failed, exit code 1                                                                
                                                                                           
Gem files will remain installed in                                                         
C:/Ruby/2.4/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19 for inspection.                      
Results logged to                                                                          
C:/Ruby/2.4/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/libv8-3.16.14.19/gem_make.out 
                                                                                           
An error occurred while installing libv8 (3.16.14.19), and Bundler                         
cannot continue.                                                                           
Make sure that `gem install libv8 -v '3.16.14.19' --source                                 
'https://rubygems.org/'` succeeds before bundling.                                         
                                                                                           
In Gemfile:                                                                                
  therubyracer was resolved to 0.12.3, which depends on                                    
    libv8                                             
```

I've had a look around for answers. Copying the v8.dll and v8preparser.dll into the ruby/bin folder hasn't fixed anything unfortunately. Not sure how to continue here. Could someone who has a working setup fetch this branch and generate the screenshots, pretty please? :) /cc @publiclab/reviewers

**Comment by dylmye** [comment]
bump /cc @jywarren

**Comment by dylmye** [comment]
bump /cc @steviepubliclab trying to get this in for hacktober so would appreciate a lookover if possible :) thank you

**Comment by dylmye** [comment]
Close in favour of #6405? Seems like neither of us can get your project to build in order to take a screenshot...

**Comment by jywarren** [comment]
Hi! Sorry, i'll try rebuilding this one more time and we can see if our automated screenshots work... otherwise i'll just merge it as it looks simple and well-done! Thanks!!!

**Comment by dylmye** [comment]
Thank you! Sorry for bumping this so much.

**Comment by dylmye** [comment]
LGTM

**Comment by jywarren** [comment]
Well, it looks like none of the automated screenshots capture this, but I think it's fine as the other PR also made the same changes. Merging now, thank you so much!

**Pull request merged**
