### PR TITLE
Adding question text area to the shadow question's page

### LINKED ISSUE #5733: UI Improvements PLanning Issue : Questions Page
cc : @gautamig54 

PublicLab_mockups

#### Checklists

- [x] Create shadow questions page @CleverFool77 
- [x] first design block with some relevant information @CleverFool77 
- [x] card of text area for questions with buttons and post options @gautamig54 
- [x] featured questions cards   @CleverFool77 
- [ ] Show recent questions on some topic - use same card as used in tags section @gautamig54 

Viewable at:

http://stable.publiclab.org/shadow_question

http://publiclab.org/shadow_question

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5733  (<=== Add issue number here)

Screen Shot 2019-05-30 at 3 07 11 AM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
@jywarren I don't understand where the test is failing. I don't think it is related to this.

**Comment by jywarren** [comment]
Is it in a system test? Those are still causing us some trouble, it seems.
Can you try restarting the tests? Sorry!!!!

**Comment by gautamig54** [comment]
Yes @jywarren it is in the system test.

**Comment by jywarren** [comment]
I /think/ you should be able to restart just the system tests, but if not,
ping me and I can. Or you can close the PR and re-open it and it should
re-trigger all of them!

**Comment by gautamig54** [comment]
@jywarren I have made the changes and the tests are running again. Thanks!

Screen Shot 2019-05-30 at 4 00 43 AM

**Comment by jywarren** [comment]
awesome - ping reviewers once it passes and let's get it merged!

**Comment by gautamig54** [comment]
@jywarren @CleverFool77 @gauravano Tests have passed and the PR is ready for review.
Thanks!

**Comment by jywarren** [comment]
Awesome! I'll merge this then.

**Pull request merged**
