### PR TITLE
Add first section for shadow question page

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5733 part

- [X] Added a shadow route
- [X] Added first section 

Screenshot from 2019-05-24 13-29-03

The screen appears darker due to screenshot but In real, it isn't. 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @jywarren I started off with questions page first section in shadow route.
Thanks !!

**Comment by jywarren** [comment]
Looks good - ready to merge, do you think? Great work!

**Comment by CleverFool77** [comment]
> Looks good - ready to merge, do you think? Great work!

I guess this is ready for merge.
Thanks !!

**Comment by gautamig54** [comment]
Looks great @CleverFool77. This is ready for merge @jywarren.

**Comment by jywarren** [comment]
Awesome! Thanks for the review, too, @gautamig54 ! Very helpful to make final review and merge quicker. 🙌

**Comment by jywarren** [comment]
Also you can always ask for more reviews in the chatroom! https://gitter.im/publiclab/publiclab

**Pull request merged**
