### PR TITLE
Implement helper function for encrypt/decrypt data

### PR DESCRIPTION
**Pull request by Radhikadua123**
Part of #3798

In this, I have added helper module which can be used to encrypt and decrypt data.

### CODE REVIEW

**Comment by Radhikadua123** [comment]
@publiclab/reviewers Please review this PR.

**Comment by jywarren** [comment]
Oh wow, very cool! OK, i'll merge it! thanks!!!!

**Comment by jywarren** [comment]
Awesome tests!!

**Comment by Radhikadua123** [comment]
@jywarren Thanks! :)

**Pull request merged**
