### PR TITLE
[WIP - Help wanted!] Ensure preservation of return_to through OAuth login flow

### LINKED ISSUE #3384: Ensure OAuth login preserves `return_to` parameter and goes there after logging in
In our regular signup process at https://publiclab.org/signup, we can set the destination AFTER signup using a `return_to` parameter, like this:

https://publiclab.org/signup?return_to=/post?title=My Title

This nice URL can even set a title on the post you are prompted to create! It works with this hidden input:

`<input type="hidden" name="return_to" value="/post?title=My Title" />` (code here: https://github.com/publiclab/plots2/blob/cdef0bd7978836212c112f2295b4561d3f6a57f0/app/views/user_sessions/new.html.erb#L35)

We even have a test for this:

https://github.com/publiclab/plots2/blob/a8e9ffaa34319a3c7924ff735dc5231cf69b05d9/test/integration/login_flow_test.rb#L33-L41

Here's the controller logic that drives that redirect after account creation:

https://github.com/publiclab/plots2/blob/010bb27741625269e8c73d68bc65dcb7325b88a2/app/controllers/user_sessions_controller.rb#L108-L121

But for OAuth login (using Twitter, FB, Google logins) this doesn't seem to work. 

I got the message on this line - but it didn't attempt to redirect me: 

https://github.com/publiclab/plots2/blob/010bb27741625269e8c73d68bc65dcb7325b88a2/app/controllers/user_sessions_controller.rb#L41

I think we should look in the `session[:return_to]` parameter to see if it's there -- and we may need to store it there so it persists past the redirects through the external OmniAuth service. 

I'd love some help with this one! I don't know if it'd be a quick one @SidharthBansal  but interested in your thoughts!

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #3384

I think this is only the beginning -- i'm not setting the `session[:return_to]` in the right places, nor am I setting up the redirects thoroughly... and it could probably use some refinement to not have redundant code.

### CODE REVIEW

**Comment by Radhikadua123** [comment]
@jywarren Wow, this seems to be quite interesting issue. I was thinking about approach to it.

What about this: 

1. All the third party login icons will point to `/redirect?from=#{url}&to=/auth/#{provider}`.
2. In that GET view:
    2.1 if user is already logged in, redirect user to `from` url. (handling edge case)
    2.2 if user is not logged in, just get the existing session or create new one. In that session, save the `return_to` url and redirect user to `to` url from get parameters.
3. When callback from third party login is called, on success, we check if `return_to` is set in session or not. If it is set, then just redirect user to that url.

I'm not sure how well would it address the issue. I might have missed something.

**Comment by jywarren** [comment]
That sounds like a great approach, although it did seem to me that we might
be able to set the session in the oath login route itself? But maybe I'm
mixed up. If you'd like to try this out, we'd love some help!!!

**Comment by Radhikadua123** [comment]
Sure, I'll try it out tomorrow. Thanks!

**Comment by jywarren** [comment]
Deferring to #3879

**Pull request closed without merging**
