### PR TITLE
Move commenting UI code into an independent .js file. Fixes #3831.

### LINKED ISSUE #3831: Move commenting UI code into an independent .js file
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

Our commenting code is quite long and is placed inline into the comments page. We should include it using a `<script>` tag, and move it into this folder with other JavaScript code:

https://github.com/publiclab/plots2/blob/f423719cc77948f0e2ceb27e1e0685115841a9a5/app/assets/javascripts/

Here's the segment that should be moved:

https://github.com/publiclab/plots2/blob/f423719cc77948f0e2ceb27e1e0685115841a9a5/app/views/comments/_form.html.erb#L80-L118

Once it's moved into `/app/assets/javascripts/comment.js`, we can re-include it with this line in the `_form.html.erb` template:

```ruby
  <%= javascript_include_tag "comment.js" %>
```

We'd love help with this one!

### PR DESCRIPTION
**Pull request by junhouse**
Fixes #3831  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by junhouse** [comment]
@publiclab/reviewers Q. How do I run rake test. When I run this command I get an error 
`rake aborted!
LoadError: cannot load such file -- bundler/setup
/Users/kykim/Desktop/Projects/Personal/OpenSourceProj/plots2/config/boot.rb:6:in `<top (required)>'
/Users/kykim/Desktop/Projects/Personal/OpenSourceProj/plots2/config/application.rb:1:in `<top (required)>'
/Users/kykim/Desktop/Projects/Personal/OpenSourceProj/plots2/Rakefile:5:in `<top (required)>'`

**Comment by junhouse** [comment]
@jywarren Can you accept my pull request? This issue is resolved.

**Comment by jywarren** [comment]
Hi KyungJun -- thanks! Would you mind renaming the issue to describe what it fixes? This is really helpful in reviewing. 👍 🎉

**Comment by jywarren** [comment]
Otherwise this looks good! Great work!

**Comment by junhouse** [comment]
@jywarren I changed the name of the issue. Let me know if it needs to be more descriptive. Thank you.

**Comment by jywarren** [comment]
Fantastic and you'll soon be able to test this at
https://stable.publiclab.org (although it may be stalled, hang on a bit
before trying). Thanks!!!

**Pull request merged**
