### PR TITLE
Add people tab to /spam page for moderators(Fixes #2079)

### LINKED ISSUE #2079: Add "people" tab to /spam page for moderators
We should add new user profiles to the moderate spam page:

https://publiclab.org/spam

image

We can add a new tab, but the tab would actually lead to http://publiclab.org/people (for now) since moderators can see recently active users and ban them from that page. 

This could be added as a new tab among these lines:

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/admin/spam.html.erb#L15-L19

This replaces #42. Any help welcomed, thanks!!!

### PR DESCRIPTION
**Pull request by biswesh456**
Fixes #2079
This commit adds active user tab to publiclab.org/spam.

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by biswesh456** [comment]
As was asked the tab right now redirects to https://publiclab.org/people. Please let me know about the further actions.

**Comment by jywarren** [comment]
Oops, looks like you've added an SQLite file! Would you mind removing that? Otherwise looks super!!! Thanks!

**Comment by biswesh456** [comment]
I have removed SQLite file.Thanks for pointing it out.
Is there anything else that needs to be done?

**Comment by jywarren** [comment]
No, this looks perfect. Thanks so much!

**Pull request merged**
