### PR TITLE
Login button for the modal fixed

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@oorjitchowdhary @JonathanXu1 I hope this will fix the problem.

**Comment by SidharthBansal** [comment]
@jywarren merging this small fix

**Comment by SidharthBansal** [comment]
@oorjitchowdhary can you please check the behaviour on the unstable branch
I have pushed the changes.

**Comment by oorjitchowdhary** [comment]
> @oorjitchowdhary @JonathanXu1 I hope this will fix the problem.

@SidharthBansal Sorry I couldn't do it... I was actually studying..

**Comment by oorjitchowdhary** [comment]
> @oorjitchowdhary can you please check the behaviour on the unstable branch
> I have pushed the changes.

I've to look at unstable.publiclab.org.. right? 
Let me see

**Comment by oorjitchowdhary** [comment]
It's about 50% done.. Still running

**Comment by SidharthBansal** [comment]
I have pushed the changes just you need to check that everything is working fine there

**Comment by oorjitchowdhary** [comment]
Yes sure..

**Comment by oorjitchowdhary** [comment]
screenshot 63

Success.. Everything's fine

**Comment by SidharthBansal** [comment]
I mean you need to check the functionality of the modal on the website

**Comment by oorjitchowdhary** [comment]
Yes.. It is working there too... 
Sorry for the misunderstanding..

**Comment by SidharthBansal** [comment]
Awesome....
I will be sending more changes tonight.
Working on return_to @jywarren

**Comment by oorjitchowdhary** [comment]
image

I can see a redundant link above the modal oauths...
We should remove that one..

**Comment by SidharthBansal** [comment]
Thanks, I pushed some more changes for return_to. We merged only the things which were working correctly. So, no need to worry.

**Comment by oorjitchowdhary** [comment]
Oh okay great

**Comment by SidharthBansal** [comment]
@JonathanXu1 #4196 please see the changes in this pr and try.

**Comment by SidharthBansal** [comment]
Moved to #4197

**Pull request merged**
