### PR TITLE
testing for replication entries

### LINKED ISSUE #1566: Replication count works, but examples not shown
### What happened just before the problem occurred

I visited https://publiclab.org/notes/liz/03-15-2017/host-a-balloon-mapping-workshop and noticed that replications weren't showing up anymore although the count was still 35. 

Did something change?

### PR DESCRIPTION
**Pull request by jywarren**
Testing for issue described in #1566, hopefully later fixes #1566

This should fail at first!

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Ok! I think we've reproduced it... Now to fix it.

**Comment by jywarren** [comment]
We also have to check that there /are/ replications for this tagname that ought to be displayed, to get the test right.

**Comment by jywarren** [comment]
Perfect! @ananyo2012 @publiclab/soc check out our new danger bot behavior which adds links to the specific line of code that failed tests and comments in the actual error! Very helpful. Thanks Ananyo!

Now to solving this bug!

**Comment by icarito** [comment]
Sounds awesome!

**Comment by jywarren** [comment]
Added another test assertion to try to narrow this down.

**Comment by jywarren** [comment]
I'm adding an additional unit test for double shortcodes, as this is an example of that, and it could be related. https://github.com/publiclab/plots2/pull/1618

**Comment by jywarren** [comment]
This does indeed rely on an upstream error: https://github.com/publiclab/plots2/pull/1618 so this is now pending that fix!

**Comment by jywarren** [comment]
reopening to trigger re-test! Fingers X.

**Pull request merged**
