### PR TITLE
fix 487 Adds timestamp as additional param to fix cache

### PR DESCRIPTION
**Pull request by lalithr95**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by lalithr95** [comment]
This PR fixes #487 by adding _ as additional timestamp which is the general convention used to prevent ajax requests not load from cache. A user validation has been added which will raise an error when user id doesn't exist. Tests were added for all the cases a user might occur.

cc @jywarren

**Comment by jywarren** [comment]
awesome, and thank you! I'll be looking at this on Friday for the bi-weekly
merge.

**Comment by lalithr95** [comment]
Sure no problem :)

**Comment by jywarren** [comment]
Awesome, thanks. And congrats on today's news!

**Comment by lalithr95** [comment]
Yes !! Thanks for selecting me 😄 I thought you would also be a mentor for my project.

**Pull request merged**
