### PR TITLE
Debian stretch (fixes #2811)

### LINKED ISSUE #2811: Upgrade Docker container to Stretch
Jessie (Debian 8) is going into Long Term Support outside of the Debian release support cycle.

I am upgrading underlying servers.

Containers need to be upgraded as well.
This will imply editing our `./Dockerfile` and switching the `ruby-2.4-jessie` container for `ruby-2.4-stretch` base image - and review apt package requirements.

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
I only checked tests pass, should deploy to `unstable` first or merge?

**Comment by jywarren** [comment]
Let's push to unstable to see first!

**Comment by jywarren** [comment]
pushed!

**Comment by jywarren** [comment]
It worked fine! https://unstable.publiclab.org/dashboard

Shall we merge and go to stable?

**Comment by jywarren** [comment]
wait i'm not sure that's correct... have to check, hang on

**Pull request merged**
