### PR TITLE
Eye icon added infront of followers name

### LINKED ISSUE #6304: Reorganize /contributors/___ pages
(follow-up to https://github.com/publiclab/plots2/pull/5632) cc @IshaGupta18 🙌 

We now show 2 types of users on our contributor pages like https://publiclab.org/contributors/water-quality

1. contributors - who have posted using this topic or commented on this topic
2. followers - who are following this topic and will get notified when new content is posted to it

They're a bit messily next to each other:

image

Let's:

* [ ] show contributors in a table on top, but in each row, mark if that person is ALSO following -- maybe, with an eye icon? In a column called `Following`, maybe?)
* [ ] then let's show people who are NOT in the first list, but ARE subscribed. This can be in a second table with the title `Following`. 

Should we have a short text explanation of the distinction?

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes #6304 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@cesswairimu Can you review this pr?

**Comment by VladimirMikulic** [comment]
Could you please post a screenshot of your change? Every time you do a UI change, you are required to provide a screenshot show casing the change.

**Comment by NitinBhasneria** [comment]
As it is a feature the UI change is not shown in screen as for server there are no followers!! @VladimirMikulic

**Comment by nstjean** [comment]
So what you will need to do is add some data to your local server so that you can test out the feature. When you open the website at localhost you can log in as user (password:password) and then follow a bunch of topics. Then as admin you can log in to see if it is showing up properly.

**Comment by NitinBhasneria** [comment]
eye
this is how it will look.

**Comment by cesswairimu** [comment]
Hi @NitinBhasneria , this is looking good... I think we can have the `>>` on the same line as the `Notes`  I think that would look more arranged What do you think?.  Also, would like to do the second part of the issue on this PR or should I open another issue for it. Thanks for working on this.

**Comment by cesswairimu** [comment]
Another thing, did you remove the other column? please add a screenshot of the whole page. Thanks

**Comment by NitinBhasneria** [comment]
> Hi @NitinBhasneria , this is looking good... I think we can have the `>>` on the same line as the `Notes` I think that would look more arranged What do you think?. Also, would like to do the second part of the issue on this PR or should I open another issue for it. Thanks for working on this.

Thanks, @cesswairimu I will arrange that `Notes` thing in this pr also for the second part please open another issue and close the previous one

**Comment by NitinBhasneria** [comment]
> Another thing, did you remove the other column? please add a screenshot of the whole page. Thanks

Ahh @cesswairimu  I am little confused, do we have to remove the follower's column?

**Comment by NitinBhasneria** [comment]
Also, I want to ask if these changes are looking good or we should make a column following and put the eye icon there??

**Comment by NitinBhasneria** [comment]
`Notes` arranged
Screenshot from 2020-02-19 21-33-42

**Comment by cesswairimu** [comment]
Great, the arrangement looks great...No, but we need to just show the followers who are following and are not part of the contributors..how that we have the eye icon showing the contributors who are subscribed..makes sense?

**Comment by NitinBhasneria** [comment]
Yea it does make sense in a way we don't have to check in the follower's list and match if the contributor is also following or not!! @cesswairimu

**Comment by cesswairimu** [comment]
Great...and Jeff suggestion was to rename that column to `Following`

**Comment by NitinBhasneria** [comment]
So should we make another coloum named following to show the eye icon?

**Comment by cesswairimu** [comment]
Mmmh I think we should rename the one with `people who are followers` to following and just leave the other one with just the eye icon.....or will it cause confusing?

**Comment by NitinBhasneria** [comment]
Actually, an eye icon without any heading or column can make it confusing. 
So, what I think is making the `following` column in table one which will have eye icons for the contributors who are following.
and renaming the column named `people who are following` to `following` in table two.

**Comment by cesswairimu** [comment]
sounds good. Thanks :+1:

**Comment by NitinBhasneria** [comment]
So, should I work on this?
@cesswairimu

**Comment by cesswairimu** [comment]
yeah id you are up for it...or we could sseparate it in another issue.totally your choice

**Comment by NitinBhasneria** [comment]
Yea, we should separate it in another issue.
This will be a less mess then.
Thanks @cesswairimu

**Comment by cesswairimu** [comment]
okay cool...then lets add column of the eye icon  and I will create another issue of having the followers exclude the contributors. Thanks

**Comment by NitinBhasneria** [comment]
@cesswairimu This pr work is done and this is how it will look 
Screenshot from 2020-02-20 02-13-22
but the `followers` table has shifted to down instead of right, so this also need to be fixed in another issue.
Thanks
Screenshot from 2020-02-20 02-13-13

**Comment by NitinBhasneria** [comment]
@nstjean @cesswairimu I am getting this error in travis. Any idea?
Screenshot from 2020-03-01 12-48-20

**Comment by cesswairimu** [comment]
Not sure why it is happenig...Is it failing locally?

**Comment by NitinBhasneria** [comment]
> Not sure why it is happening...Is it failing locally?
@cesswairimu 
Same travis error in pr #7445

**Comment by VladimirMikulic** [comment]
@cesswairimu all tests pass locally, but some of them like this one fail in production for some reason.

**Comment by cesswairimu** [comment]
I will restart travis one more time...Travis passed on the other PR

**Comment by NitinBhasneria** [comment]
@cesswairimu You can review it now as all checks have been passed also we can continue this.

**Comment by cesswairimu** [comment]
I will push up the alignment of the components so that we can merge it together. Thanks

**Comment by NitinBhasneria** [comment]
@cesswairimu Please merge this. Thanks

**Comment by cesswairimu** [comment]
@NitinBhasneria I found a PR that fixed the alignment issue here https://github.com/publiclab/plots2/pull/7331 you can see the new changes here https://stable.publiclab.org/contributors/soc please rebase and paste the final screenshot here. Thanks

**Comment by cesswairimu** [comment]
@NitinBhasneria could we please get a screenshot for this so that we can merge?  also kindly rebase. Thanks

**Comment by cesswairimu** [comment]
This PR has been open for a long time and no activity/ reviews requested has not been addressed. We understand you might be busy and engaged on other things. I am closing this for now...please  feel free to reopen if you get some time and would like to finish this. Rem to check if its still available before you reopen. Thanks

**Pull request closed without merging**
