### PR TITLE
Add sorting button options to tag show template

### PR DESCRIPTION
**Pull request by asiedubrempong**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by asiedubrempong** [comment]
fixes #3462; Merge AFTER #3419

**Comment by asiedubrempong** [comment]
@jywarren can you please check for me if everything is fine

**Comment by SidharthBansal** [comment]
@jywarren changes look good to me.

**Comment by SidharthBansal** [comment]
Thanks for contributing at Public Labs.
This issue seems to be completed by someone else. You can look at other issues to help us.
Thanks

**Pull request closed without merging**
