### PR TITLE
Activity buttons prompt for thumbnail grids

### LINKED ISSUE #4092: Activity prompt buttons on Thumbnail grids
We have some great new features by @ValentinaTironi -- a thumbnail grid -- see the Activities section of https://publiclab.org/micro 👍 

One thing that would be great is to have the built-in buttons below that we see on non-thumbnail Activity grids, such as at https://publiclab.org/coqui

image

Here is the code that auto-generates the button and notice:

https://github.com/publiclab/plots2/blob/e400bf711b6f432051d61be2d912476d55de7ca3/app/views/grids/_notes.html.erb#L66-L73

I think we could break it into a partial template and also include it into the new thumbnail template, so we don't have redundant code:

https://github.com/publiclab/plots2/blob/master/app/views/grids/_thumbnail.html.erb

We'd love help with this and it could become a GCI task too!

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #4092 
@publiclab/mentors Please review the code now... Thanks a ton 😄 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by ValentinaTironi** [comment]
You are using a variable that aren't defined. The solve that I found is passing local variables into the parcial. Something like that:
`<% render :partial =>"grids/activity_template", locals: { randomSeed: randomSeed } %>`

Hope this helps!

**Comment by oorjitchowdhary** [comment]
@publiclab/mentors I'm unable to insert the working of this code .. as it won't get to know the type.. bcoz on a wiki page, how do you detect the `question` type or `activity` type

**Comment by oorjitchowdhary** [comment]
@ValentinaTironi thanks that worked out..
but I'm still lost in few more issues..
1. The `add an activity/ask a question` code doesn't work when used as a partial template.. If i insert that simply in the code file, it works well..
2. The `if questions, elsif activity` code isn't working .. Just the embed table shows up when it is deployed..
I don't what's the fix here.. Kept trying many things, didn't work out..
@publiclab/reviewers Please help here.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal No errors now.. but nothing showing up too

**Comment by jywarren** [comment]
Ah, if it's helpful, wiki pages do not have different types. Only notes.

**Pull request closed without merging**
