### PR TITLE
Comment while creating coauthor tag

### LINKED ISSUE #2028: send email to newly added coauthors explaining what it means
This could actually be relatively simply achieved via a comment -- by automatically leaving a comment as we do for the barnstar feature:

https://github.com/publiclab/plots2/blob/dccf61b4cf0aa816a3a906495ea6a0b2d5d847b0/app/controllers/tag_controller.rb#L178-L180

The comment could say `@_author_ has marked @_recipient_ as a co-author.` and everybody on the thread would get email notified.

This code would go just before the last line of this block:

https://github.com/publiclab/plots2/blob/033676b8abd28cd56a999e60934ff9f01bd0a9ac/app/models/node.rb#L660-L667

and the message could look like:

```ruby
"_@#{user.username} has marked @#{node.author.username} as a co-author._"
```

This should work but could take some troubleshooting -- happy to help, and any assistance in taking this task on is appreciated!

### PR DESCRIPTION
**Pull request by Gauravano**
Fixes #2028 

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Gauravano** [comment]
I have taken care of the fact that if the user submits multiple tags at a time they are added as usual (barnstar also ) and comment will be added but not added via Javascript like for tag addition.Preview is here
barnstar_tag

**Comment by jywarren** [comment]
Awesome!

**Comment by Gauravano** [comment]
Actually, @jywarren it's not complete now, that's why I haven't removed `in-progress ` tag :sweat_smile: .I have just implemented commenting for barnstar tag, not for the coauthor, anyways I continue work on the same branch and will complete soon.

**Comment by jywarren** [comment]
oh no! sorry. i should've checked, but it looked good. Will there be any problem with this being published? Perhaps it's good to break it into 2 PRs anyways. Thank you and apologies!

**Comment by Gauravano** [comment]
No problem at all @jywarren.I will continue for the co-author in next PR and will also add tests for this there.

> Will there be any problem with this being published? 

No problem at all, I wanted to ask if its ok that only tag addition takes place on the page and comment will be seen after user visits next time or refresh the page

**Pull request merged**
