### PR TITLE
typo fix publically -> publicly

### LINKED ISSUE #6359: Tiny Typo fix!
Hello! 
### Please describe the problem (or idea)

As reported by @joyofsoy, when someone publishes their draft, the text has a typo “Your work is now visible publically”.  "Publically" should be spelled "publicly".

This may be in the general "Publish" popup message also, but we are not sure. Is there a way to search for that typo?

> What did you expect to see that you didn't?

"Publically" should be spelled "publicly"

### Please show us where to look

https://publiclab.org/post -- once a post goes live

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
Liz

Thank you!

### PR DESCRIPTION
**Pull request by wpnzach**
Fixes #6359  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by wpnzach** [comment]
@publiclab/reviewers please let me know if you need anything more!

**Comment by wpnzach** [comment]
@publiclab/reviewers there are no UI changes, so no screenshot is attached.  If i need to check the box, though, I will!

**Comment by wpnzach** [comment]
@ananyaarun I wasn't expecting more folks to be working on it that quickly or I would have, my apologies.  I will in the future.

**Comment by SidharthBansal** [comment]
Thanks for working on this. This issue is fixed in any other PR

**Pull request closed without merging**
