### PR TITLE
[WIP] fix reply to comment via email feature

### LINKED ISSUE #5916: Add message threading to reply-by-comment
I'm doing some refactoring in #5885, but noticed that when we removed answer-by-email, that we don't have email replies (that turn into comments) threading to the comment they replied to. This will take a few steps to fix:

1. checking for `(#c0000)` code in the email subject, as was removed for answers in this code:

https://github.com/namangupta01/plots2/blob/f375e10efa6aaed5c1e269307e02eb8555ce8141/app/models/comment.rb#L211-L220

See https://github.com/publiclab/plots2/pull/2982 as well

2. routing it to an `add_comment_reply()` method
3. ensuring that email notifications sent /out/ about comments use the `(#c0000)` code in their email subject.
4. maybe review/add tests for this? 

@ViditChitkara did you want to try this one?

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #5916

### CODE REVIEW

**Comment by jainaman224** [comment]
Please resolve conflicts else looks good to me. 😄

**Comment by ViditChitkara** [comment]
I think this is good to go now. Will fix the remaining code climate issues in another pr. @jywarren @jainaman224

**Comment by jywarren** [comment]
Awesome. I cleared the CC checks and will merge!

**Comment by jywarren** [comment]
Thanks a ton, @ViditChitkara !!

**Comment by ViditChitkara** [comment]
Great!!

**Pull request merged**
