### PR TITLE
Add larger image to profile page

### LINKED ISSUE #2414: Add larger image to profile page
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/users/profile.html.erb](https://github.com/publiclab/plots2/blob/master/profile.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -2,7 +2,7 @@
   <% if @user.user %>
     <img class="hidden-xs hidden-sm img-rounded" id="profile-photo" style="width:100%;margin-bottom:10px;" src="<%= @user.user.profile_image %>" />
     <div style="text-align:center;" class="visible-sm visible-xs">
-      <img class="img-circle" id="profile-photo" style="width:50%;margin-bottom:20px;" src="<%= @user.user.profile_image %>" />
+      <img class="img-circle" id="profile-photo" style="width:50%;margin-bottom:20px;" src="<%= @user.user.photo_path %>" />
     </div>
   <% end %>
 
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by Gayathrir1666**
Fixes #2414 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
@Gayathrir1666 Please remove the Gemfile.lock file from the PR as it is not required.

**Comment by Gauravano** [comment]
Hi @Gayathrir1666 , please mention , what issue this PR is targeting and if there is no issue related to this PR,mention details on what you are trying to do in PR body.As this PR is changing view , please attach the GIF or Screenshot of updated view that would be very helpful.Thanks !

**Comment by seafr** [comment]
Hi @Gayathrir1666, could you please let us know if this PR is related to PR #2409. Some of the changes appear to be similar. Thank you and we look forward to your first contribution.

**Comment by Gayathrir1666** [comment]
Hello@seafr, Yes it is related to PR#2409.

**Comment by seafr** [comment]
@Gayathrir1666 I think these were supposed to be two separate issues, each with its own PR. What do you think @Gauravano?

**Comment by Gayathrir1666** [comment]
I have sent the separate issue of #2409
And then when I am working on #2415. I modified the previous one too

**Comment by seafr** [comment]
The changes you made in #2409 are showing up in this PR. Did you merge you local branch `Gayathrir1666:spamusers` to `Gayathrir1666:master` before starting with this PR?

**Comment by Gauravano** [comment]
hi @Gayathrir1666 thanks for the changes, I am tagging the issue in PR body, for now, please remember to do this from next time. Awesome work !!!

**Comment by Gayathrir1666** [comment]
Thanks!  @Gauravano

**Comment by jywarren** [comment]
Super, thanks all!!! 👍 👍

**Pull request merged**
