### PR TITLE
Wrapping the failing tests logic with perform_enqueued_jobs

### PR DESCRIPTION
**Pull request by itshady**
Fixes #9335 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by itshady** [comment]
@cesswairimu Here is my new pull request.

**Comment by cesswairimu** [comment]
Hey @itshady  looks like you made the pull request from your main branch again, I am  sorry for the confusion
kindly go here https://github.com/itshady/plots2-1 click on the drop down where its labelled `main` and write a name for a new branch,  when done click on the part labeled `create a branch: .. `
Screenshot from 2021-03-24 20-53-12

After that please make the changes you did before changing `deliver_now` to `deliver_later` on the new branch and then make a pull request from that branch...does this make sense? you can get more details on branching here https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository and making a pull request from another branch here https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

please let me know if you have any question. Also if you are making the changes from your local and not github directly let me know so I can point you to resources on how to achieve this.Thanks

**Comment by itshady** [comment]
@cesswairimu sorry but which change am I doing? Is is the "wrapping the failing tests logic with perform_enqueued_jobs" or the "change deliver_now to deliver_later"?

**Comment by cesswairimu** [comment]
"deliver_now" to "deliver_later", you can leave the already changed test commit no prob

**Comment by itshady** [comment]
@cesswairimu sorry but which file did I change the deliver_now to deliver_later on?

**Comment by cesswairimu** [comment]
The one outlined here https://github.com/publiclab/plots2/issues/9311

**Comment by cesswairimu** [comment]
I believe it is this file https://github.com/publiclab/plots2/blob/8fe73233a83643c37ecc66bafc9aa6505ea80d5a/app/models/node.rb

**Comment by cesswairimu** [comment]
Lets close this one and leave the latest one. Thanks

**Pull request closed without merging**
