### PR TITLE
fix-three-column-format

### LINKED ISSUE #5758: Fix "3 column print format" post Bootstrap
in #1622 we did this, and it's worked really well, but post Bootstrap 4 update it needs some work. 

We're catching follow-up issues one by one in #5612, but this is a big enough one that I thought we should open an independent issue. 

image

I would guess we need to tweak these files:

https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/print.css

https://github.com/publiclab/plots2/blob/794df370264a605935483aa8d0e4946bfd14c37c/app/views/like/_like.html.erb#L98-L108

### PR DESCRIPTION
**Pull request by urvashigupta7**
Fixes #5758 

Screenshot from 2020-10-22 10-11-01

### CODE REVIEW

**Comment by urvashigupta7** [comment]
@cesswairimu, @jywarren Please let me know if any changes are needed. Thanks :smile:

**Comment by urvashigupta7** [comment]
@cesswairimu Can you please take a look why codeclimate check is failing? Thanks!!

**Comment by cesswairimu** [comment]
Oh wow, this are beautiful @urvashigupta7  :tada:
Codeclimate is failing for all the recent PRs I've created an issue here #8661 hopefully we will get a reason why soon

**Comment by cesswairimu** [comment]
@urvashigupta7 codeclimate just passed for a new Pr, could you please try rebasing we see if it will pass

**Comment by urvashigupta7** [comment]
Sure @cesswairimu

**Comment by urvashigupta7** [comment]
@cesswairimu It passed :tada:

**Comment by cesswairimu** [comment]
great :tada:

**Review by Tlazypanda — COMMENTED** [review]
Hey @urvashigupta7 This looks great :tada: Great work!! :100: 
Can you verify if adding the `d-print-none` class to some elements doesn't break other print templates :sweat_smile:? Also here the main image case is handled how do other images get rendered can you test that out as well? If there's any issues with the above we can consider making a separate route for this as well :v: Looping in @jywarren to share his thoughts

**Comment by urvashigupta7** [comment]
Hi @Tlazypanda This works with images other than main image. Also, I just tested it out with the tables too.

Screenshot from 2020-10-24 18-24-52

Also, I have done **d-print-none** changes in [/app/views/notes/show.html.erb](https://github.com/publiclab/plots2/blob/c1a2252b628008de93684e8eee2bcef2509390f8/app/views/notes/show.html.erb)
So, these changes are specific to notes page only. Therefore, I think it rules out the possibility of breaking anything up :smile:  Thanks !!

**Review by Tlazypanda — COMMENTED** [review]
Hey @urvashigupta7 Ohh sorry if I wasn't clear before I meant if this will break other print options that we have other than the 3 column one? :sweat_smile:

**Comment by urvashigupta7** [comment]
Screenshot from 2020-10-26 21-22-44
Screenshot from 2020-10-26 21-23-46
Screenshot from 2020-10-26 21-26-00

Hi @Tlazypanda , Added screenshot for all three print options :smile: Thanks!!

**Comment by urvashigupta7** [comment]
Hi @Tlazypanda Can you please review this? Wanted to record this in Outreachy contributions. Thanks 😄

**Comment by urvashigupta7** [comment]
Hi @cesswairimu. There is a field which asks for date on which PR was merges. So, I thought it would be necessary 🤔

**Comment by cesswairimu** [comment]
Okay cool, from your screenshots looks like it didn't broke the other pages. I will go ahead and merge this and we can check everything on https://stable.publiclab.org/ and open a new issue if anything breaks. Thanks

**Review by cesswairimu — APPROVED** [review]

**Comment by urvashigupta7** [comment]
Thanks @cesswairimu :smile:

**Comment by jywarren** [comment]
Hi!!! My apologies for missing this, it looks incredible. Thanks to @Tlazypanda @cesswairimu for careful and thorough checking and merging! Thank you @urvashigupta7 this is great work!

**Comment by urvashigupta7** [comment]
Thanks @jywarren 😄

**Pull request merged**
