### PR TITLE
Pop-up for link social media button (#3584)

### LINKED ISSUE #3584: Make pop-up for link social media button
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
In user profile page here is link social media button if we click on this button it' show alert and user type input in this alert form it would be better if there is any pop-up and user type input this form. It will make page very attractive

sociallink

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**   
some thing like this.
https://www.w3schools.com/bootstrap/bootstrap_modal.asp

Code links….
https://github.com/publiclab/plots2/blob/232907d9677ca6d5409bdd2834cfc41d4a97d1b4/app/views/users/profile.html.erb#L217

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by thesparks**
Fixes #3584 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by thesparks** [comment]
@rohan2599 @avsingh999, please check

**Comment by avsingh999** [comment]
@thesparks great work

**Comment by thesparks** [comment]
@avsingh999 please confirm my GCI report
image

**Comment by avsingh999** [comment]
@thesparks can you please check It's working after click on save changes
thanks :)

**Comment by thesparks** [comment]
deepin-screen-recorder_select area_20181025214917

**Comment by thesparks** [comment]
@avsingh999 i replaced <% user id %> and username with random in gif

**Comment by thesparks** [comment]
```
    $('#link_social_media').click(function(){
        sign = document.getElementById('social-name').value;
        $.post('/profile/tags/create/asd ',{"name": sign,"id":12345}, function(data) {
            window.location='/profile/zaharus000 ';
        });
     });
```

Like this

**Comment by avsingh999** [comment]
@thesparks ,you misjudged it, I want you to give a  screenshot that the input you are entering in the pop-up must ne included in the list of the tags. To do that- you can show me the name "facebook:instagram " being added in your tag list.
thanks :)

**Comment by thesparks** [comment]
@avsingh999 
deepin-screen-recorder_select area_20181025224201

**Comment by thesparks** [comment]
Facebook:
deepin-screen-recorder_select area_20181025230529
@avsingh999

**Comment by avsingh999** [comment]
@thesparks  great works 
thaks :)

**Comment by jywarren** [comment]
This looks good to me; @SidharthBansal what do you think? Does it work alongside the OAuth work?

**Comment by SidharthBansal** [comment]
Yes it will work.
We use 'oauth' prefix for oauth. These user tags does not have oauth prefix so I hope it should work

**Comment by jywarren** [comment]
Super!!!

**Pull request merged**
