### PR TITLE
Fix signup link at /login (#4457)

### LINKED ISSUE #4457: Fix signup link at /login
Currently at /login the signup link does not work. This is because in the user_sessions translation file the url1 argument has been removed. This means we need to add it back and, to prevent a redirect on the login modal, set the url on the modal to be `#`.

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all) built off #4412 . This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the following two files:

https://github.com/publiclab/plots2/blob/34d8073964ba7b70700ab5d05024d9d6a949ef58/app/views/user_sessions/_new.html.erb#L4-L6

https://github.com/publiclab/plots2/blob/34d8073964ba7b70700ab5d05024d9d6a949ef58/config/locales/views/user_sessions/new/en.yml#L6

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

For _new.html.erb:
```diff
-  <h2 id="toSignup"><%= raw t('user_sessions.new.log_in_or_sign_up') %></h2>
+  <h2 id="toSignup"><%= raw t('user_sessions.new.log_in_or_sign_up', :url1 => "#") %></h2>
  <% if f.error_messages != "" %><div class="alert alert-danger"><%= f.error_messages %></div><% end %>
  <br style="clear:both;"/>
```

For app/config/locales/views/user_sessions/new/en.yml
```diff
-      log_in_or_sign_up: "Log in <small> or <a>sign up to join</a> the Public Lab community</small>"
+      log_in_or_sign_up: "Log in <small> or <a href='%{url1}'>sign up to join</a> the Public Lab community</small>"
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by dhruvgupta167**
Fixes #4457  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Thanks for contributing at public lab. Can you please provide me the gifs for demonstrating the solution proposed by you actually works.
Thanks
Happy New Year

**Comment by SidharthBansal** [comment]
You don't have to make any further code changes

**Comment by kevinzluo** [comment]
@dhruvgupta167 Please add gifs showing that the fix works on your local server. I will close and reopen to restart the build.

**Comment by dhruvgupta167** [comment]
issue 4457

@SidharthBansal @kevinzluo please review.
Thanks

**Comment by kevinzluo** [comment]
@dhruvgupta167 Nice!! Please also show the behavior when the signup link is clicked on the login modal.

**Comment by dhruvgupta167** [comment]
> @dhruvgupta167 Nice!! Please also show the behavior when the signup link is clicked on the login modal.

loginmodal

**Comment by dhruvgupta167** [comment]
This is really exciting stuff, about to get my 1st pull request merged.

**Comment by dhruvgupta167** [comment]
This is really exciting stuff, about to get my first pull request merged.
Thanks @kevinzluo @SidharthBansal

**Comment by SidharthBansal** [comment]
Thanks everyone.
@dhruvgupta167 you can try other help wanted labelled issues now. 
Awesome work Dhruv.

**Comment by dhruvgupta167** [comment]
> Thanks everyone.
> @dhruvgupta167 you can try other help wanted labelled issues now.
> Awesome work Dhruv.

Yes absolutely, this is just a beginning. I will now definitely try to contribute to help wanted issues labelled now.
Thanks again

**Pull request merged**
