### PR TITLE
Map floats over the footer while scrolling! - UI Bug

### LINKED ISSUE #10306: Map floats over footer while scrolling! - UI Bug (1/3)
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

 ### Todo:
- [ ]  📝 Update:
On this file https://github.com/publiclab/plots2/blob/main/app/assets/stylesheets/map.css  add  this block of code

```
.leaflet-pane{
  position: initial !important;
}
.leaflet-bar, .leaflet-top{
  position: initial !important;
}
```
**This solution was worked on by @wajeehamushtaq  on #10358** 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

Original information about the issue
-------------------------------------------------
map floats over footer while scroling

map floats over footer

look here -> https://publiclab.org/post

### PR DESCRIPTION
**Pull request by wajeehamushtaq**
Fixes #10306
I try to fix the Map floats over the footer while scrolling! - UI Bug (1/3). The problem arise due to leaflet map styling. The position is set to absolute so this will create the problem.

Screenshot from 2021-10-12 20-34-37

Screenshot from 2021-10-12 20-34-59

### CODE REVIEW

**Comment by jywarren** [comment]
This looks really good, my apologies for missing it in my notifications! Just rebasing to get past the test issues, which i think are unrelated. Let's see! 🤞

**Comment by jywarren** [comment]
Hi, would you mind rebasing this over the latest main branch? i can't seem to do it easily from my end. That will resolve the test! Apologies and thanks!

**Comment by wajeehamushtaq** [comment]
Hi @jywarren , Can you please guide me about rebasing it to the main branch? Thank you!

**Comment by jywarren** [comment]
Hi @wajeehamushtaq of course, sorry for the slow response!

****

> It looks like you need to rebase your work on top of the latest main. You can do that by following the process outlined here, but you may be able to skip step 2 if your main is still in sync with publiclab's main: https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

> In general there are more tips and guides on rebasing here: https://publiclab.org/wiki/developers#Resources

Thanks!

**Comment by Tlazypanda** [comment]
Hey @wajeehamushtaq feel free to ping in case you are running into any issues. We are here to help :v:

**Comment by cesswairimu** [comment]
Hi @wajeehamushtaq, we are unable to move forward without a rebase here, we understand you might be busy and engaged on other things. The solution was great and I will use the solution to convert the issue to a first-timer issue - thanks  for working on this. Please feel free to come back anytime and ask for another issue to work on. Closing this. Thanks all

**Pull request closed without merging**
