### PR TITLE
Linked login modal to comments and answers

### LINKED ISSUE #4156: Link Login Modal to Comments page on notes
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Comments page on notes
[publiclab.org/notes/](url)
`app/views/notes/_comments.html.erb`
screenshot 54

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #4156 and #4157 
@publiclab/reviewers Please review this one.

Comments login modal on /note

comment on note

Answer login modal on /question

answer on question

Comment login modal on /question

comment on question

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Please review this .. Thanks

**Comment by SidharthBansal** [comment]
Please close this pr and create separate PRs for separate issues.
We want modular work.
The login & sign up modal is created in such a manner because it is highly interlinked. I don't think this work is interlinked. So please create different PRs.

**Comment by SidharthBansal** [comment]
As per your suggestion @jywarren closing this pr

**Comment by oorjitchowdhary** [comment]
Okay sure.. I'll make different PRs

**Comment by SidharthBansal** [comment]
Wait a minute

**Comment by oorjitchowdhary** [comment]
Yes?

**Comment by SidharthBansal** [comment]
Yes. You need to create different prs. No more than 5 linking tasks please. As they are similar.

**Comment by oorjitchowdhary** [comment]
Okay.. I'm creating 2 PRs then

**Pull request closed without merging**
