### PR TITLE
Update profile.html.erb - show the cancel button only to logged in users, admins/moderators and profile users.

### LINKED ISSUE #10888: show the cancel button only to logged in users, admins/moderators and profile users.
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.
 
 If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!
 
 We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝
 
 If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!
 
 ### 🤔 What you will need to know.
 Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
 
 ### 📋 Step by Step
 * [ ]  🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
 
 💡 Learn how to claim 🙋
 * [ ]  📝 **Update** the file [app/views/users/profile.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/users/profile.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.
 
 [See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!
 
 Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
 
 ```diff
        <div id="social-links-list" class="profile_icons d-flex justify-content-center" style="gap: 8px">
          <% if @twitter_user.nil? == false %>
          <span>
+           <% if logged_in_as(['admin', 'moderator']) || (current_user && current_user.uid == @profile_user.uid) %>            
             <a aria-label="Delete tag" data-confirm="Are you sure you want to delete it?" class="tag-delete" data-remote="true" href="/profile/tags/delete/<%= @profile_user.id %>?name=twitter:<%= @twitter_user %>" data-method="delete">
              <span class="badge badge-secondary delete_badge mb-1">
                x
              </span>
             </a>    
+           <% end %>            
            <a href="<%= social_link('twitter', @twitter_user)%>">
              <i class="fa fa-twitter fa-3x"></i>
            </a>
          </span>         
          <% end %>
          <% if @facebook_user.nil? == false %>
          <span> 
+            <% if logged_in_as(['admin', 'moderator']) || (current_user && current_user.uid == @profile_user.uid) %>                        
             <a aria-label="Delete tag" data-confirm="Are you sure you want to delete it?" class="tag-delete" data-remote="true" href="/profile/tags/delete/<%= @profile_user.id %>?name=facebook:<%= @facebook_user %>" data-method="delete">
              <span class="badge badge-secondary delete_badge mb-1">
                x
              </span>
             </a>
+           <% end %>            
            <a href="<%= social_link('facebook', @facebook_user)%>">
              <i class="fa fa-facebook fa-3x"></i>
            </a>
	@@ -133,23 +137,27 @@
          <% end %>
          <% if @github_user.nil? == false %>
          <span>
+            <% if logged_in_as(['admin', 'moderator']) || (current_user && current_user.uid == @profile_user.uid) %>                        
             <a aria-label="Delete tag" data-confirm="Are you sure you want to delete it?" class="tag-delete" data-remote="true" href="/profile/tags/delete/<%= @profile_user.id %>?name=github:<%= @github_user %>" data-method="delete">
              <span class="badge badge-secondary delete_badge mb-1">
                x
              </span>
             </a> 
+           <% end %>            
            <a href="<%= social_link('github', @github_user)%>">
              <i class="fa fa-github fa-3x"></i>
            </a>
          </span>     
          <% end %>
          <% if @instagram_user.nil? == false %>
          <span>
+           <% if logged_in_as(['admin', 'moderator']) || (current_user && current_user.uid == @profile_user.uid) %>                        
             <a aria-label="Delete tag" data-confirm="Are you sure you want to delete it?" class="tag-delete" data-remote="true" href="/profile/tags/delete/<%= @profile_user.id %>?name=instagram:<%= @instagram_user %>" data-method="delete">
              <span class="badge badge-secondary delete_badge mb-1">
                x
              </span>
             </a>
+           <% end %>            
            <a href="<%= social_link('instagram', @instagram_user)%>">
              <i  class="fa fa-instagram fa-3x"></i>
            </a>
 ```
 
 * [ ]  💾 **Commit** your changes
 * [ ]  🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
 
 1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
 2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.
 
 * [ ]  🏁 **Done** Ask in comments for a review :)
 
 ### Please keep us updated
 💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!
 
 If this happens to you, don't sweat it! Grab another open issue.
 
 ### Is someone else already working on this?
 🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.
 
 👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!
 
 ### 🤔❓ Questions?
 Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

### PR DESCRIPTION
**Pull request by ShivraniAJ**
I have done the required changes according to the issue.

Fixes #10888  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Review by TildaDares — APPROVED** [review]
Great job @ShivraniAJ. Thank you!!

**Comment by ShivraniAJ** [comment]
> Great job @ShivraniAJ. Thank you!!

I am pleased that I could start with this issue.

**Comment by cesswairimu** [comment]
Hi @ShivraniAJ , could you  please add a link to the  issue this pull request fixes on the description --- On this this line`Fixes #0000` _(replace 0000 with the issue number)_  It  helps in automatically closing the issue when the pull request is merged. Thanks for working on this, and thanks @TildaDares  for the reviews.

**Comment by ShivraniAJ** [comment]
> Hi @ShivraniAJ , could you please add a link to the issue this pull request fixes on the description --- On this this line`Fixes #0000` _(replace 0000 with the issue number)_ It helps in automatically closing the issue when the pull request is merged. Thanks for working on this, and thanks @TildaDares for the reviews.

Yes, I have linked the issue in the description.

**Comment by ShivraniAJ** [comment]
> Excellent work, thank you so much!

Thank you, This issue is a stepping stone for me in the open-source world.

**Pull request merged**
