### PR TITLE
Fix schema-rb-example file for SQLite

### PR DESCRIPTION
**Pull request by stefannibrasil**
@milaaraujo  and I have found an error today on the `schema-example.rb` file.

When we were trying to understand what was happening with the Travis error on #3134, we tried several things to connect the app with MySQL and that might have caused it... and since I haven't updated my project to use SQLite, I didn't see the error before.

We realized today that it created a `schema.rb` that only works with MySQL and that was pushed to the master... So this PR fix this. It also fixes an error caused that only happens on SQLite (which we didn't find before because we are using MySQL from now on and Travis as well).

We hope this didn't cause much trouble, but it's really tricky to catch all these things.

Thanks!

### CODE REVIEW

**Comment by stefannibrasil** [comment]
@publiclab/reviewers

**Comment by jywarren** [comment]
Ah, ok - great. Can you resolve the conflicts here and rebase if needed, and then try `git push -f https://github.com/publiclab/plots2.git HEAD:unstable` or `git push -f git@github.com:publiclab/plots2.git HEAD:unstable` to push this onto the experimental `unstable` branch and test it out at https://unstable.publiclab.org to be sure it works in the exact production environment. `@icarito` can also help if `unstable` gets stuck so do reach out to him in that case.

Thanks!

**Comment by stefannibrasil** [comment]
hi @jywarren, @icarito helped me and the https://unstable.publiclab.org  is running with this commit. I believe this is ready to merge when you approve? Thanks!

**Comment by jywarren** [comment]
Great, thanks! Perhaps related to fully switching to mariadb, we had thought of the possibility of adding a second run of tests that run everything in sqlite... good to consider in #3170

**Pull request merged**
