### PR TITLE
Adjust stats page range error, fixes #1678

### LINKED ISSUE #1678: Search Query Out of Range Error
### What happened just before the problem occurred
On clicking this link : 
screen shot 2017-10-12 at 7 13 09 pm

Takes time for loading the page and then (see image):
screen shot 2017-10-12 at 7 09 12 pm
  

screen shot 2017-10-12 at 7 06 35 pm

### Relevant URLs

https://publiclab.org/stats
https://publiclab.org/stats/range/1-1-2010/12-31-2016/

### Browser, version, and operating system
Browser : Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Operating system : macOS

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this looks good but I think it may be including the past changes as well; let me see and be sure it's only the new adjustment to the range query. Also - i tweaked the title to help keep track of what each PR is for. Thanks!

**Comment by jywarren** [comment]
Just reopening to re-run the tests!

**Comment by jywarren** [comment]
Also please note Dangerbot's suggestion about not using your master branch when developing new contributions -- I think that's what happened here... not a big deal but it'll simplify things a lot in your workflow if you open a named feature branch to work in. Thank you!

**Comment by jywarren** [comment]
ugh - sorry! I think i made a mistake. Could you open a new PR with the changes, in a named feature branch? Apologies for this, and thanks!

**Comment by jywarren** [comment]
So sorry about this! I was trying to help out. But your change was mostly on a single line, no? Hopefully it won't be too much work to reopen a new PR?

**Comment by sagarpreet-chadha** [comment]
No Problem sir...sure will reopen it .

**Pull request closed without merging**
