### PR TITLE
Config for dump&restore to UTF8MB4 for emojis

### PR DESCRIPTION
**Pull request by icarito**
Following
https://docs.moodle.org/32/en/Converting_your_MySQL_database_to_UTF8

This is an attempt to tackle #3007 with a new approach.
I'm deploying this to `unstable`. Then the default encoding will be `utf8mb4`.

I've exported a dump with ` --default-character-set=utf8mb4 ` and `--skip-character-set`.
With the setting in this PR it should be possible to import this dump and it should be encoded correctly.

This is a manual process that, if it works, will need to be repeated in production. I'm not sure trying to automate it is worth it.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by ebarry** [comment]
oh heck yes! Good luck to this experiment, @icarito ! 😃

**Comment by icarito** [comment]
Okay currently the import of an updated staging database is in progress, with the character encoding converted manually. Hopefully it will work :crossed_fingers: 

I'm documenting here the manual conversion process commands that I took.

1. First I dumped the data as root in production:
`# docker-compose exec db ionice -c2 -n7 nice -n19 bash -c "mysqldump -vv -h localhost -S /var/lib/mysql/mysqld.sock  --default-character-set=utf8mb4 -u publiclab --password=tr1bbl3s --skip-character-set --single-transaction --quick --lock-tables=false publiclab_production"`

2. Following commands will change the sql file the way we need:
```
sed -i.bak '1d' ../dump/publiclab_production_NOCHARSET.sql
sed -i.bak -e 's/DEFAULT CHARACTER SET latin1/DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci/' -e 's/DEFAULT CHARSET=latin1/DEFAULT CHARSET=utf8mb4/' schema.sql
sed -i.bak -e 's/= latin1_swedish_ci/= utf8mb4_unicode_ci/' -e 's/= latin1/= utf8mb4/' publiclab_production_NOCHARSET.sql
sed -i.bak -e 's/= utf8_general_ci/= utf8mb4_unicode_ci/' ../dump/publiclab_production_NOCHARSET.sql
sed -i.bak -e 's/= utf8 /= utf8mb4 /' ../dump/publiclab_production_NOCHARSET.sql
```

3. Stop the container. Clear the database data (rm -rf ../mysql/*). Put the SQL file in ../dump. Start the database. It will begin to import.

This is where we are at in unstable, waiting for the process end.

**Comment by icarito** [comment]
When the data import finishes, we'll have to make sure that emojis and international characters _currently in the database_ display correctly and _then_ test whether or not inserting new records that include extended characters will work.

**Comment by icarito** [comment]
Hi,
The data was imported.
All the settings in the MySQL server seem to be correct:
```
MariaDB [plots]> SHOW WARNINGS;                                        
Empty set (0.00 sec)                                                   
                                                                       
MariaDB [plots]> SHOW VARIABLES WHERE Variable_name LIKE 'character\_se
t\_%' OR Variable_name LIKE 'collation%';                              
+--------------------------+--------------------+                      
| Variable_name            | Value              |                      
+--------------------------+--------------------+                      
| character_set_client     | utf8mb4            |                      
| character_set_connection | utf8mb4            |                      
| character_set_database   | utf8mb4            |                      
| character_set_filesystem | binary             |                      
| character_set_results    | utf8mb4            |                      
| character_set_server     | utf8mb4            |                      
| character_set_system     | utf8               |                      
| collation_connection     | utf8mb4_general_ci |                      
| collation_database       | utf8mb4_unicode_ci |                      
| collation_server         | utf8mb4_unicode_ci |                      
+--------------------------+--------------------+                      
10 rows in set (0.01 sec)                                              
```
However my tests still result in an interrogation sign instead of a the 𝌆 symbol.
I get this result even when updating the record from the MySQL terminal console.

**Comment by icarito** [comment]
Okay I think I know what went wrong, in inspecting the database and the data dump, it looks like not all instances of `utf8` were converted to `utf8mb4`. I'm going to review the database dump again and re-import it tonight.

**Comment by icarito** [comment]
In addition to the previous `sed` statements I've just issued:
```
sed -i.bak -e 's/CHARSET=utf8/CHARSET=utf8mb4/' ../dump/publiclab_production_NOCHARSET.sql
```
Hopefully that will be the last needed.

**Comment by icarito** [comment]
Hmm somehow I managed to mangle some lines now it says `utf8mb4`.
I'm issueing
```
sed -i.bak -e 's/utf8mb4mb4/utf8mb4/' ../dump/publiclab_production_NOCHARSET.sq
```
To fix. I'll need to streamline the sed script for the actual deployment, this is good for testing.

**Comment by icarito** [comment]
image

Unstable instance supports all emojis now!
I will streamline the process (try to make it into one script) and then run it in Stable.
If it works well, we can schedule downtime to do this in production!

**Comment by icarito** [comment]
I've performed this operation semi-manually a couple of times now in a couple of different ways:

## Importing on Tycho

Took 9 hours.
Using MariaDB 10.2

## Importing on Google Cloud SQL

Took 2 hours
Using MySQL 5.7

In order to be able to point to GCloud SQL cleanly we'll need to finish https://github.com/publiclab/plots2/issues/2757 first.

One issue I found is that some database queries would fail in MySQL 5.7, this was traced back to a change in configuration between 5.7 and 5.6. I had to set `sql_mode` tag to `TRADITIONAL`. This seems to have made it work. But in order to test it thoroughly we need #2757 - then we should check it out in staging and then I can do the migration either on a weekday or wait until the weekend again.

**Comment by icarito** [comment]
Just a not for the future, that I also tried yesterday to load the data with the 5.6 engine that is also available with GCloud, but it failed saying that our index keys are too long. That's when I found I could tweak the 5.7 configuration `sql_mode` to "TRADITIONAL" and it worked.

**Comment by icarito** [comment]
It wasn't necessary to change the configuration of the mysql file because we've also migrated to Cloud SQL.

**Comment by ebarry** [comment]
thanks for working on this Sebastian! Excited to hear updates

**Comment by icarito** [comment]
Hello @ebarry,

The operation went as planned. However we are experiencing degraded performance since we did it.

I've taken a few measures including increasing the memory and processing power of the database instance, plus increasing the process count and database connection pool.

I am adding "fine tuning" that we had in our managed DB (in `config/my.cnf`) to the Google hosted database, hoping it will help.

**Pull request closed without merging**
