### PR TITLE
Contributing.md page updated to include pointers for first-timers. Fixes #1048

### LINKED ISSUE #1048: Assorted help-file and template changes
This is a collection (please add if you have more!) of small changes to various templates. This is a good candidate for several distinct first-timers-only issues. 

@publiclab/reviewers -- input appreciated!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

https://github.com/publiclab/plots2/blob/master/CONTRIBUTING.md

Add a First-Timers-Only section using text from README (https://github.com/publiclab/plots2/#first-time) with link to https://github.com/publiclab/plots2/projects/2

https://github.com/publiclab/plots2/blob/master/ISSUE_TEMPLATE.md

Add: "Suggested steps to resolve"

https://github.com/publiclab/plots2/blob/master/PULL_REQUEST_TEMPLATE.md

Add: "fixes `#number`" to show how you can auto-close issues

### PR DESCRIPTION
**Pull request by Pk13055**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
First, just a note -- i see your first commit was from your previous PR -- because you're working on your master branch and weren't able to begin again from the latest publiclab master. 

There's some guidance on how to rewind your (now out of sync) master branch and play out your new contributions in relation to `publiclab`'s newest changes -- 

https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

Does this make sense? I believe all you really want is the last commit on this branch -- 59af934

**Comment by jywarren** [comment]
If this sounds confusing I can explain more -- but it's important to work on a named feature branch -- see this guide: https://publiclab.org/wiki/contributing-to-public-lab-software#A+sample+git+workflow

Thanks!

**Comment by Pk13055** [comment]
I've created a branch and applied changes there after pulling from the plots2:master. How can I get these changes to reflect in this PR?

**Comment by jywarren** [comment]
Unfortunately this PR is based on your master branch, and I don't believe you can change that -- so if you open a new PR, link to that one from here (while closing this one), we can look at your newly applied changes over there. Thank you very much! 👍

**Comment by Pk13055** [comment]
#1059

**Pull request closed without merging**
