### PR TITLE
Basic/Normal User not able to delete own wiki page

### LINKED ISSUE #2013: Basic/Normal User not able to delete own wiki page
Hi, this is a [first-timers-only](https://github.com/publiclab/plots2/projects/2) issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

# The Problem

When normal/basic user deletes the wiki page created by him/her , the login screen is shown .

# Solution

The delete button on wiki page   links to `/notes/delete/` .
https://github.com/publiclab/plots2/blob/ac0f56fff35d9a62d7bcc1d0726260b8d7187a31/app/views/like/_like.html.erb#L52
However the if condition in **notes#delete method** is incorrect here . 
We need to change **if** condition in line :  
https://github.com/publiclab/plots2/blob/ac0f56fff35d9a62d7bcc1d0726260b8d7187a31/app/controllers/notes_controller.rb#L237

to : 
`if current_user && (current_user.uid == @node.uid || current_user.role == "moderator" || current_user.role == "admin")`

### Feel free to ask any doubt regarding the issue ! Thank you !

# Steps to Fix 

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ]  set up a repository locally following the README instructions, and make sure that all tests pass
 - [ ] try to fix the issue following the steps above, but even before you're done, you can:
 commit your changes and start a pull request (see contributing to Public Lab software) but mark it as "in progress" if you have questions or if you haven't finished
- [ ]  alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see [https://publiclab.org/wiki/developers](https://publiclab.org/wiki/developers)) or go to the [chatroom](http://publiclab.org/chat) if you have questions, and take a look at our [first-timers landing page for more information!](https://github.com/publiclab/plots2/projects/2)

### PR DESCRIPTION
**Pull request by ankitbhardwaj78**
Fixes #2013
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ankitbhardwaj78** [comment]
@jywarren  please take a review.

**Comment by jywarren** [comment]
This looks good. Do you think you could write a functional test to demonstrate and ensure these rules are solid? Thanks!!!

**Comment by ankitbhardwaj78** [comment]
Sure

**Comment by jywarren** [comment]
No rush, but just checking if you needed any help with this, or got stuck? For reference, here are some example functional tests -- there are even some disabled tests for deletion privileges from an earlier version, which you might be able to revive:

https://github.com/publiclab/plots2/blob/ed1ef3b72c8a45bfd1d7b842d1d747db391b2a7f/test/functional/wiki_controller_test.rb#L228-L263

**Comment by jywarren** [comment]
And thanks!!!

**Comment by jywarren** [comment]
Hi, @ankitbhardwaj78 -- do you need some help with this one to finish things up? We're happy to take over if you're no longer able to contribute, or to offer some tips if you'd like!

Thank you!!

**Comment by ankitbhardwaj78** [comment]
Thanks @jywarren ,sorry for not replying on time as i was busy in doing some stuff i will do this.

**Comment by ankitbhardwaj78** [comment]
@jywarren please take a review.

**Comment by jywarren** [comment]
Oh, this looks great. Just one more request, if you have time -- and no worries if you don't! 

See how on this block of code we assert a change of 1 in a given # of records:

https://github.com/ankitbhardwaj78/plots2/blob/2cae454b6866566b1dce889f0274b3c62fe3e199/test/functional/notes_controller_test.rb#L54-L59

We could do `assert_difference 'Node.count', -1 do` here to show that a node (the wiki) was deleted. And for the anti-test, we could do:

```ruby
assert_difference 'Node.count', -1 do
```

What do you think?

Also, sorry to be so detail-oriented, but would you mind tidying up all the indentation -- we use a "two spaces per indent" convention and it really helps keep our codebase clean over the long term!

Thanks so much for your help on this! We really appreciated it and we're almost done!

**Comment by ankitbhardwaj78** [comment]
@jywarren I have made changes as you said please have a look.

**Comment by jywarren** [comment]
@ankitbhardwaj78 this looks great to me. @sagarpreet-chadha what do you think? Shall we merge this in?

Thanks to both of you!!!

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren , looks perfect to me !
Thank you @ankitbhardwaj78  🙌  .

**Comment by jywarren** [comment]
Super. :-))))) 👍

**Pull request merged**
