### PR TITLE
ADD: System test for comments

### PR DESCRIPTION
**Pull request by Uzay-G**
For part of #5316.

I have added a system test for commenting on a note. The test verifies that the UI reacts properly to the comment and that the preview button works well.

Are there any other comment tests you think would be useful? What do you think @VladimirMikulic @publiclab/reviewers?

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Nice one @Uzay-G. The test fails on my server, we'll see what Travis says.

**Comment by Uzay-G** [comment]
Yeah you are right. There is a problem I hadn't noticed. I will fix it :+1:

**Comment by Uzay-G** [comment]
Alright I fixed it. I also refactored things to a `setup` method that will login before each test instead of putting the commands in the tests each time.

**Comment by Uzay-G** [comment]
Does this work for you @VladimirMikulic?

**Comment by SidharthBansal** [comment]
You both have to complete tests for 6 features. Then I will approve tasks
for both of you. And you both will get 15 points each. After that we can
repeat this activity as many times as you want.
I hope this will give you a lot of points and learning too

**Comment by VladimirMikulic** [comment]
@SidharthBansal it will for sure :)

**Comment by jywarren** [comment]
Thank you!!!!

**Comment by SidharthBansal** [comment]
5th test here 
We just need to approve at the GCI dashboard now

**Pull request merged**
