### PR TITLE
Load some maps near people's marked location if it exists #3965

### LINKED ISSUE #3965: Load some maps near people's marked location if it exists
If someone has entered a location on their profile page using user tags, we should default to a view of their location when they load pages like:

* https://publiclab.org/maps
* https://publiclab.org/people
* https://publiclab.org/questions (will soon have a map)

And follow-up: load data for just those regions (coming soon via API-based map queries)

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #3965

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Screenshot : 

**The zoom level is set to 3 if User location is present else default is 2 .**

screenshot 2018-11-15 at 12 19 23 am

**Comment by jywarren** [comment]
This looks amazing. Perhaps we could have a small text under it that says "Current view based on your shared location. [Click here]() to adjust."

**Comment by jywarren** [comment]
And if they haven't entered their location, we show the current "Share your own location on..."

**Comment by sagarpreet-chadha** [comment]
Screenshot : 

screenshot 2018-11-15 at 12 59 50 am

**Comment by jywarren** [comment]
perfect! Ready to merge?

**Comment by sagarpreet-chadha** [comment]
Yes . Thanks !

**Comment by jywarren** [comment]
Great! This should be testable at stable.publiclab.org shortly after it builds.

**Pull request merged**
