### PR TITLE
Added variables for SMTP

### PR DESCRIPTION
**Pull request by icarito**
This allows to set SMTP host in env vars. Solves https://github.com/steviepubliclab/web/issues/227

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by jywarren — APPROVED** [review]
This looks great @icarito pls feel free to merge!

**Review by pydevsg — APPROVED** [review]
Good work @icarito :)

**Comment by pydevsg** [comment]
@publiclab/maintainers please merge this merge, this is left to be merged for a while.

**Comment by icarito** [comment]
Okay, this needed me to edit the environment.sh files. I've added the following to all instances `environment.sh` files:

```
export SMTP_HOST=smtp
export SMTP_PORT=25
```
To reproduce the setup that we currently have (we will change this later to use Google smtp directly and avoid setting up a MTA).
This can be merged now and check how it works on staging.

**Comment by icarito** [comment]
I'm not finding the platform emails in staging, nor errors in the logs. Not sure where the mails are going, they should be routed to `testing` account on tycho.

**Pull request merged**
