### PR TITLE
Updating fetch_comments in:

### LINKED ISSUE #6814: Rename fetch_comments method
`fetch_comments` method should be named something more descriptive, like `comments_viewable_by(user)` or `comments_approved_for(user)`!

_Originally posted by @jywarren in https://github.com/publiclab/plots2/pull/6718#issuecomment-555569444_

The method is here 
https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L1063-L1071

And you need to replace on the new method these files and lines

1. https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L58
2. https://github.com/publiclab/plots2/blob/master/app/views/questions/_new_question.html.erb#L71

3. https://github.com/publiclab/plots2/blob/master/app/views//notes/_comments.html.erb#L3

4. https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_comment.html.erb#L6

5. https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb#L18

### PR DESCRIPTION
**Pull request by govindgoel**
apps/views/dashboard/_node_meta.html.erb

Fixes #6814  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by govindgoel** [comment]
@publiclab/reviewers  Please review this and There are more files to be changed in the issue#6814  so should I do PR for them as well..

**Comment by vaibhavmatta** [comment]
@govindgoel please make all the changes altogether. We will review them all at once. Thanks

**Comment by govindgoel** [comment]
@vaibhavmatta  These are all different files in issue#6814 that need to be changed so I have to do different PR for every file.. Then how would I present the changes altogether.

**Comment by vaibhavmatta** [comment]
Oh Okay.! So make different PRs for different files. I will review this PR within few hours. Please ping me up on Gitter as well. Thanks

**Comment by cesswairimu** [comment]
Hi @govindgoel, we advise to check if someone is working on the issue before getting started and if so, please check-in with them(comment on theissue) and see if they are still working on it before you make a PR..to avoid duplicates PRs for solving the same issue. Hello @vaibhavmatta, we usually want to have one PR for an issue and have all the file changes included in that single pull request. Thanks all

**Comment by vaibhavmatta** [comment]
@cesswairimu Yes! 
Hey @govindgoel please make a single PR which includes all the changes altogether (as I asked you to do initially)

**Comment by govindgoel** [comment]
@cesswairimu  @vaibhavmatta   Ok I apologise for that and will be surely doing them in a single pr and I will make sure that this will not happen again,Thanks for your review 
Happy Coding!

**Comment by cesswairimu** [comment]
Great...thanks all

**Comment by cesswairimu** [comment]
This PR has been open for a long time and no activity/ reviews requested has not been addressed. We understand you might be busy and engaged on other things. I am closing this for now...please  feel free to reopen if you get some time and would like to finish this. Rem to check if its still available before you reopen. Thanks

**Pull request closed without merging**
