### PR TITLE
Change cursor to pointer on hover

### LINKED ISSUE #4979: Change cursor to pointer on hover over the wiki "changes" link
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
On /dashboard while viewing wiki changes/updates, you might have hovered over the changes link, the below one 
Screenshot from 2019-03-10 01-24-32

Update this line of code https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_wiki.html.erb#L40 such that cursor changes to pointer on hovering over the link
 
After changing the view, also attach the screenshot of the updated view of the dashboard in the PR.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by shreyateeza**
Fixes #4979  (<=== Add issue number here)

cursor-to-pointer

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by shreyateeza** [comment]
@gauravano @jywarren @SidharthBansal @cesswairimu Please review the PR!

**Comment by shreyateeza** [comment]
Please review the PR! @cesswairimu

**Comment by shubhscoder** [comment]
@shreyateeza also it seems that your pull request is from your master. It is advisable to have a unique branch named with the feature you add . This is a very good guide to start (https://publiclab.org/notes/warren/11-22-2017/use-git-and-github-to-contribute-and-improve-public-lab-software) 
And yes awesome work!
Thank you so much!

**Comment by shreyateeza** [comment]
@shubhscoder I apologise for creating PR from master branch. In my early two PRs I created a different branch and then sent the PR. This happened by mistake.

**Comment by shreyateeza** [comment]
@shubhscoder Shall I close this PR and then create a new one if this can't be merged?

**Comment by gauravano** [comment]
@shreyateeza this PR is fine. Just add a screenshot/GIF of the /dashboard showing the cursor changing to pointer on hovering over the changes link. Thanks!

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Comment by gauravano** [comment]
Hey @SidharthBansal, as  the PR is against a FTO, so I have tested the PR:
Screenshot from 2019-04-15 20-59-04

Thanks!

**Comment by gauravano** [comment]
Merged :tada: :+1: :balloon:

**Pull request merged**
