### PR TITLE
encoding issue resolved for migrating DrupalUsers to User records

### LINKED ISSUE #2209: Encoding issues with migrating old DrupalUser accounts to User records
We're seeing an issue with a recent migration https://github.com/publiclab/plots2/pull/2157 which tries to mitigate User vs DrupalUser status records. I tried to fix it here: https://github.com/publiclab/plots2/pull/2208 but we have a new problem. 

I believe it's due to this error from the [Jenkins build log](https://jenkins.laboratoriopublico.org/job/Plots-Stable/lastFailedBuild/console):

```
ActiveRecord::StatementInvalid: Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `rusers`.* FROM `rusers`  WHERE `rusers`.`username` = 'トリーバーチ クラッチ'  ORDER BY `rusers`.`id` ASC LIMIT 1
```

The username in question is: `トリーバーチ クラッチ`

Can we convert the string or otherwise mitigate when a username is ... not utf-8?

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #2209

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
@jywarren How about these changes?? I'm not 100% sure if this will work on production, please suggest any necessary changes.

**Comment by ViditChitkara** [comment]
@jywarren any thoughts on this?

**Comment by jywarren** [comment]
Oh WOW! Let me see if this runs on the unstable server.

**Comment by jywarren** [comment]
Sorry i'd missed this -- let's see how it does here:

http://jenkins.laboratoriopublico.org

http://unstable.publiclab.org

**Comment by jywarren** [comment]
Please mark this as ready if it builds properly and passes!

**Comment by ViditChitkara** [comment]
:+1:

**Comment by jywarren** [comment]
Hmm, this failed due to mail not being sent -- see #2095 -- https://jenkins.laboratoriopublico.org/job/Plots-Unstable/68/

I think we can't confirm this in the container unless we fix that -- maybe @icarito and @namangupta01 can use your help with the next step on #2095?

```
Network is unreachable - connect(2) for "localhost" port 25/usr/local/bundle/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:2160:in `do_delivery'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:260:in `block in deliver'
/usr/local/bundle/gems/actionmailer-4.1.16/lib/action_mailer/base.rb:527:in `block in deliver_mail'
/usr/local/bundle/gems/activesupport-4.1.16/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/local/bundle/gems/activesupport-4.1.16/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activesupport-4.1.16/lib/active_support/notifications.rb:159:in `instrument'
/usr/local/bundle/gems/actionmailer-4.1.16/lib/action_mailer/base.rb:525:in `deliver_mail'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:260:in `deliver'
/app/app/mailers/password_reset_mailer.rb:12:in `reset_notify'
```

**Comment by jywarren** [comment]
All passing! Want to try this on `unstable` now?

**Comment by ViditChitkara** [comment]
Yeah, I will do!!

**Comment by jywarren** [comment]
hi @ViditChitkara -- try pushing this to unstable and giving it a last check and then we can merge it -- that'll be great to have done!

**Comment by ViditChitkara** [comment]
Pushed on unstable, it's building. Taking a bit longer though

**Comment by ViditChitkara** [comment]
@jywarren the build went well, it's working on unstable.

**Comment by jywarren** [comment]
Fantastic. Merged!!!

**Comment by jywarren** [comment]
OK awesome. So now we can continue with #956 i believe!!! :-)

**Comment by jywarren** [comment]
Uh oh! I got this error on running this on production -- not sure how it happened there but not in stable or unstable!

```
Caused by:
Mysql2::Error: Incorrect string value: '\xE3\x83\x88\xE3\x83\xAA...' for column 'username' at row 1
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/mysql/database_statements.rb:36:in `exec_query'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:92:in `exec_insert'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:124:in `insert'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `insert'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/relation.rb:65:in `insert'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/persistence.rb:572:in `_create_record'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/counter_cache.rb:128:in `_create_record'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/locking/optimistic.rb:75:in `_create_record'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/attribute_methods/dirty.rb:123:in `_create_record'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/callbacks.rb:302:in `block in _create_record'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:126:in `call'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/callbacks.rb:302:in `_create_record'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/timestamp.rb:68:in `_create_record'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/persistence.rb:548:in `create_or_update'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/callbacks.rb:298:in `block in create_or_update'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:126:in `call'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/callbacks.rb:298:in `create_or_update'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/persistence.rb:129:in `save'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/validations.rb:44:in `save'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/attribute_methods/dirty.rb:22:in `save'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/transactions.rb:319:in `block (2 levels) in save'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/transactions.rb:319:in `block in save'
/usr/local/bundle/gems/activerecord-5.0.6/lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
```

**Comment by jywarren** [comment]
Moving to #2846

**Pull request merged**
