### PR TITLE
Remove useless variable assignment

### PR DESCRIPTION
**Pull request by siaw23**

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, know why it's not passing? Maybe once it is we should look to @SidharthBansal to review, thanks!

**Comment by siaw23** [comment]
I thought this was fixed:

```
The command "docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rails test -d"" exited with 1.
0.00s$ echo -e '<?xml version="1.0" encoding="UTF-8"?>' > output.xml
The command "echo -e '<?xml version="1.0" encoding="UTF-8"?>' > output.xml" exited with 0.
0.01s$ tail -n +2 -q ./test/reports/TEST*.xml >> output.xml
The command "tail -n +2 -q ./test/reports/TEST*.xml >> output.xml" exited with 0.
2.23s$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi
Results:
Messages:
- [ ] @siaw23 Thank you for your pull request! I'm here to help with some tips and recommendations. Please take a look at the list provided and help us review and accept your contribution! And **don't be discouraged if you see errors** -- we're here to help.
- [ ] This pull request doesn't link to a issue number. Please refer to the issue it fixes (if any) in the body of your PR, in the format: `Fixes #123`.
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi" exited with 0.
Done. Your build exited with 1.
```

BTW it's hard to get tests running locally for me because of [this](https://github.com/publiclab/plots2/issues/2712)

I wonder how many people have this problem. I'll pause a bit with this PR and see what I can do with the local testing and db issue. @jywarren

**Comment by jywarren** [comment]
ok, thank you!

**Comment by siaw23** [comment]
Please review @jywarren @SidharthBansal

**Comment by SidharthBansal** [comment]
Code looks good. It will be great if we can test it on the unstable branch before the merge.
Thanks for increasing the readability.

**Comment by jywarren** [comment]
I agree it'd be great to test on unstable. But it's such a small change and I read it over very carefully. Let it fall upon my head if it fails 😟 😋

**Comment by SidharthBansal** [comment]
It will not fail for sure as we have oauth integration tests. Travis has
not failed so no need to worry. :-)
Was being extra careful that is why I suggested unstable testing.
Thanks

**Pull request merged**
