### PR TITLE
Update node_test.rb for shorter title validations

### LINKED ISSUE #10808: Resolve failing tests resulting from the change made in #10784
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

Follow up to #10784 

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [test/functional/notes_controller_test.rb](https://github.com/publiclab/plots2/tree/main/test/functional/notes_controller_test.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -444,7 +444,7 @@ class NotesControllerTest < ActionController::TestCase
     assert_response :success
     assert_not_nil @response.body
     json = JSON.parse(@response.body)
-    assert_equal ["can't be blank", "is too short (minimum is 3 characters)", "can only include letters, numbers, and dashes"], json['title']
+    assert_equal ["can't be blank", "is too short (minimum is 2 characters)", "can only include letters, numbers, and dashes"], json['title']
     assert !json['title'].empty?
   end
```

- [ ] 📝 **Update** the file [test/unit/node_test.rb](https://github.com/publiclab/plots2/tree/main/test/unit/node_test.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -255,9 +255,10 @@ class NodeTest < ActiveSupport::TestCase
   test 'title should not be too short' do
     node = Node.new(uid: users(:bob).id,
                     type: 'note',
-                    title: 'ok')
+                    title: 'o')
     assert_not node.valid?
   end
+
   test 'create a node_revision' do
     # in testing, uid and id should be matched, although this is not yet true in production db
     revision_count = nodes(:one).revisions.length
```
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by Yavnikaa**
Fixes #10808 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great! @TildaDares do we need to wait for https://github.com/publiclab/plots2/issues/10784 to merge this? I think possibly not? Thank you!

**Comment by Yavnikaa** [comment]
@TildaDares @jywarren I have done the changes in the other file on the same PR, but I think these checks are again failing because of #10784 not getting merged. Please look into this :))
Also, are there any more significant issues which I can take up? I am very much comfortable with frontend, and would love to try out my hands at backend too :))

**Review by TildaDares — APPROVED** [review]
Thanks @Yavnikaa. Great work!!

**Comment by TildaDares** [comment]
@Yavnikaa You can take a look at our fto-candidate  issues
https://github.com/publiclab/plots2/labels/fto-candidate

**Comment by TildaDares** [comment]
@jywarren You might need to merge this PR and #10809 manually.

**Comment by jywarren** [comment]
Hi all! I'm going to try merging this and https://github.com/publiclab/plots2/pull/10805 in a single action. Fingers 🤞 !!

**Comment by jywarren** [comment]
OK, i've merged in both @Yavnikaa and @mehul89's changes from https://github.com/publiclab/plots2/pull/10805 into this PR. Let's see how it passes tests! 🤞

**Comment by jywarren** [comment]
Hmm, that's mysterious... let's see:

```
Progress: |====================================== FAIL NodeTest#test_title_should_not_be_too_short (3.75s)
        Expected true to be nil or false
        test/unit/node_test.rb:259:in `block in <class:NodeTest>'

FAIL NotesControllerTest#test_post_note_error_no_title_xhr (100.02s)
        --- expected
        +++ actual
        @@ -1 +1 @@
        -["can't be blank", "is too short (minimum is 3 characters)", "can only include letters, numbers, and dashes"]
        +["can't be blank", "is too short (minimum is 2 characters)", "can only include letters, numbers, and dashes"]
        test/functional/notes_controller_test.rb:447:in `block in <class:NotesControllerTest>'

```

**Comment by jywarren** [comment]
Hmm, i can see your commits in GitPod but they aren't appearing here. Let me see, i must've done this wrong... sorry, hang on and thanks for your patience!

**Comment by jywarren** [comment]
Phew, sorry about that. Got stuck in some rough git tangled up stuff! I think i got it now. Let's see how the tests do now. 🤞

**Comment by jywarren** [comment]
Looks good - an unrelated error stopped system tests but i am re-running them!

**Comment by jywarren** [comment]
Yay it worked!!!! Merging this now, congrats @Yavnikaa @mehul89 !!!

**Pull request merged**
