### PR TITLE
Adding post button and modal for template options

### LINKED ISSUE #5890: UI Improvements Planning Issue : Individual tags page
Next we start with the implementation of individual tags page. 

Capture

**Checklist**

- [x] Divide the page into three sections(Main image and the introduction card, sidebar with map, activity cards) @gautamig54 
- [x] Adjust the main image and add the number of people following on to the right. @CleverFool77 
- [x] make an introduction card for the tag containing the subscribe and learn more options. @gautamig54 
- [x] Activity cards with new design of style guide @CleverFool77 
- [ ] ~Show map on the sidebar and people near options @gautamig54~
- [ ] Sort by name, users and people following  @CleverFool77  **Wait a bit**
- [ ] ~Post a question option with dropdown @gautamig54~
- [x] Implement type dropdown containing options for all, questions, wikis and notes related to the tag. @CleverFool77 
- [x] Add related tags @gautamig54 

cc : @CleverFool77

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5890  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Screen Shot 2019-08-08 at 11 47 48 AM

Screen Shot 2019-08-08 at 11 47 55 AM

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
The modified screenshot : 

Screen Shot 2019-08-08 at 12 24 08 PM

**Comment by CleverFool77** [comment]
Maybe like the template we can lighter grey and the thick border for the templates ?

**Comment by gautamig54** [comment]
I have made a story or a  project as a simple post. Whereas issue is the one with tag as issue-brief. I looked at it on the website. https://publiclab.org/wiki/issue-brief


> Maybe like the template we can lighter grey and the thick border for the templates ?

Both are of the same color

**Comment by gautamig54** [comment]
Also, there were no font awesome icons as displayed in the style guide. So, I just have put these.
@CleverFool77 You can suggest any other icons? https://fontawesome.com/v4.7.0/icons/

**Comment by CleverFool77** [comment]
Hi @gautamig54 I'm in my class right now, I'll go through it in evening. Cool. !!

**Comment by CleverFool77** [comment]
And this modals open towards top. Can we have it in centre ? What do you say ?

**Comment by CleverFool77** [comment]
Though this one is `clip-board` but would look cool is story too I guess 
https://fontawesome.com/v4.7.0/icon/clipboard
What do you say ?

**Comment by gautamig54** [comment]
> Hi @gautamig54 Can I have the screenshot of the modal in tab or mobile view ?

About that, I am not sure how to display that. I can change it to vertical modal but then it will occupy the entire screen. How do you think we can do this, because there is no design for the modal in the mobile view. 
cc : @jywarren

**Comment by gautamig54** [comment]
> And this modals open towards top. Can we have it in centre ? What do you say ?

I'll do that! Thanks!

**Comment by jywarren** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There was an error with Danger bot’s Junit parsing: No JUnit file was found at output.xml</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          3 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">@gautamig54 Thank you for your pull request! I’m here to help with some tips and recommendations. Please take a look at the list provided and help us review and accept your contribution! And <strong>don’t be discouraged if you see errors</strong> – we’re here to help.</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">It looks like you haven’t marked all the checkboxes. Help us review and accept your suggested changes by going through the steps one by one. If it is still a ‘Work in progress’, please include ‘[WIP]’ in the title.</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">#<RuntimeError: No="" JUnit="" file="" was="" found="" at="" output.xml=""></RuntimeError:></td>
    </tr>
  </tbody>
</table>

<details><summary>Screenshots :camera_flash: (click to expand)</summary><h3>6114-test_viewing_question_post.png</h3><p></p><h3>6114-test_wiki.png</h3><p></p><h3>6114-test_tag_page.png</h3><p></p><h3>6114-test_blog_page_with_location_modal.png</h3><p></p><h3>6114-test_login.png</h3><p></p><h3>6114-test_wiki_page_with_inline_grids.png</h3><p></p><h3>6114-test_questions.png</h3><p></p><h3>6114-test_methods.png</h3><p></p><h3>6114-test_tag_by_author_page.png</h3><p></p><h3>6114-test_viewing_the_dropdown_menu.png</h3><p></p><h3>6114-test_viewing_the_settings_page.png</h3><p></p><h3>6114-test_comments.png</h3><p></p><h3>6114-test_stats.png</h3><p></p><h3>6114-test_tags.png</h3><p></p><h3>6114-test_people.png</h3><p></p><h3>6114-test_front.png</h3><p></p><h3>6114-test_signup.png</h3><p></p><h3>6114-test_questions_shadow.png</h3><p></p><h3>6114-test_blog.png</h3><p></p><h3>6114-test_question_page.png</h3><p></p><h3>6114-test_front_page_with_navbar_search_autocomplete.png</h3><p></p><h3>6114-test_viewing_the_dashboard.png</h3><p></p></details><p><a href='https://github.com/publiclab/plots2/issues/5316'>Learn about automated screenshots</a></p>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jywarren** [comment]
Just noting i got tests to pass now! :-)

**Comment by jywarren** [comment]
Also we could use things like this if we attribute properly: https://thenounproject.com/search/?q=clipboard

Would we be able to have a link like "Read more about templates" and "Skip using a template" as two links below the 3 options? The first could go to `/templates`, and the second to just `/post`. What do you think?

**Comment by gautamig54** [comment]
> Also we could use things like this if we attribute properly: https://thenounproject.com/search/?q=clipboard
> 
> Would we be able to have a link like "Read more about templates" and "Skip using a template" as two links below the 3 options? The first could go to `/templates`, and the second to just `/post`. What do you think?

Yes, we can add the links here. Also, @jywarren can you suggest us the mobile/tab view for this modal?

**Comment by jywarren** [comment]
In mobile, maybe we stack vertically? Let's just be sure more than one appear per "screen" so people know there are options. Thanks!

**Comment by jywarren** [comment]
Hi! How does this sound to folks? Thanks!

**Comment by gautamig54** [comment]
Hi @jywarren! I am trying the vertical modal!

**Comment by gautamig54** [comment]
Regarding the `/templates`, it will be a wiki page?

**Comment by gautamig54** [comment]
The updates design is : 

Screen Shot 2019-08-24 at 5 22 08 PM

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
