### PR TITLE
Fix "Show 0 more" on inline people lists

### LINKED ISSUE #2151: Fix "Show 0 more" on inline people lists
### Please describe the problem (or idea)
Show 0 more is present in the people's list
> What happened just before the problem occurred? Or what problem could this idea solve?
If there is no more stuff, the text should not appear

> What did you expect to see that you didn't?

image

### How to Solve:
You can check out @kevinzluo's work in https://github.com/publiclab/plots2/pull/3980 for solving this. 

The file which would require changes will be https://github.com/publiclab/plots2/blob/master/app/views/grids/_people.html.erb

### Please show us where to look
https://publiclab.org/w/power-tags#Inline+power+tags

### PR DESCRIPTION
**Pull request by JonathanXu1**
Fixes #2151

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

This PR should fix the error of a toggle that says "show 0 more"
image
I increased the index at which toggle would appear.

I'm unable to test this on localhost as this page https://publiclab.org/w/power-tags#Inline+power+tags seems to be hosted on a database.

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Can you please explain why was it happening?

**Comment by SidharthBansal** [comment]
Please take the task on the dashboard, and tell us the link here we will approve it if your solution works.

**Comment by JonathanXu1** [comment]
https://github.com/publiclab/plots2/blob/1d9658367407e178a2fa8b8c0a06b461e1c7adcd/app/views/grids/_people.html.erb#L13-L29
As you can see on line 21, the comparative used to be <% if index == 9%>
This would cause the show X more tag to show when there on the 10th listing. However if there are only 10 listings, it would say show 0 more.

**Comment by JonathanXu1** [comment]
@SidharthBansal could I get a link to the task? Don't think I can find it

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/4861439278841856/

**Comment by jywarren** [comment]
Ah, but you should be able to copy the short code which generates the table
into a wiki page on your own local copy. Should be something like:
[people:____] -- hope that helps!

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab
@jywarren @gauravano

**Pull request closed without merging**
