### PR TITLE
added-title-to-table-columns

### LINKED ISSUE #5345: Add title to the first column
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

**Update**
Current there is no heading in the first column at [the search pages](https://publiclab.org/search/chat)
Add ```Title``` to the first column simply how ```Posted by``` and ```Views``` are for second and third column respectively.
Screenshot for the same:
Selection_109

Changes need to be done in ```app/views/search/all_content.html.erb``` and ```app/views/search/_wikis_blank.html.erb``` file.

- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by atjustbeinghumaid**
Fixes #5345 

#5345  (<=== Add issue number here)
edits

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by atjustbeinghumaid** [comment]
@justbeinghumaid is my twitter handle Thank you for being so welcoming 😁Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [publiclab/plots2] Hey I've added the Title in 1st column! (#5355)From: "welcome[bot]" To: publiclab/plots2 CC: Humaid Imran ,Author Thanks for opening this pull request!  This space is protected by our Code of Conduct - and we're here to help.

Dangerbot will test out your code and reply in a bit with some pointers and requests.

Also please refer here for installation help 💿

There may be some errors, but don't worry! We'll work through them with you! 👍🎉😄

It would be great if you can tell us your Twitter handle so we can thank you properly?

**Comment by atjustbeinghumaid** [comment]
Should I make any changes now?

**Comment by CleverFool77** [comment]
Hi,
Is it possible to provide the issue no?

**Comment by atjustbeinghumaid** [comment]
#5345

**Comment by GettyOrawo** [comment]
Hey @atjustbeinghumaid Interesting PR title. Though would it be okay if you changed your Merge Request title to be abit more relatable with the changes you made. You could have it as `Add title to table column header ` maybe?
Then as @CleverFool77 was saying you could reference the issue number on the PR description. Edit where it says `Fixes #0000 (<=== Add issue number here)`  to be `Fixes #5345`

**Comment by atjustbeinghumaid** [comment]
> Hey @atjustbeinghumaid Interesting PR title. Though would it be okay if you changed your Merge Request title to be abit more relatable with the changes you made. You could have it as `Add title to table column header ` maybe?
> Then as @CleverFool77 was saying you could reference the issue number on the PR description. Edit where it says `Fixes #0000 (<=== Add issue number here)` to be `Fixes #5345`

Is it fine now?

**Comment by namangupta01** [comment]
@atjustbeinghumaid, someone was already working on the #5355. I think you can try another one we have plenty of them. And please let others know that you are working on the issue by claiming by commenting on it. 
Thanks!!

**Comment by atjustbeinghumaid** [comment]
Okay :(

**Pull request closed without merging**
