### PR TITLE
Fix bug in accept answer button and add tests to verify it

### PR DESCRIPTION
**Pull request by ananyo2012**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ananyo2012** [comment]
@jywarren Sorry Jeff I left a bug in the code while ammending the commit. The accept answer button should not be visible to an user who is not the author of the question or isn't logged in which isn't happening now. I have fixed it and added enough tests to prove the same. Sorry I should have written tests for it in the first place.

**Comment by jywarren** [comment]
Ah ok - is it rebased over latest master? I'm boarding now so can't just
yet.

**Comment by ananyo2012** [comment]
Ok sure don't be in a hurry. Yes it is rebased om the latest master

ᐧ

**Comment by jywarren** [comment]
Great, merged!

**Pull request merged**
