### PR TITLE
Showing message at the top of upgrade page #2369

### LINKED ISSUE #2369: Showing message at the top of upgrade page
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labeled.

****

Pages like this:

https://publiclab.org/notes/stoft/09-16-2016/stability-upgrade-mockup-for-plab-spectrometer-3-0

...are proposed upgrades for a specific project (they have the tag `upgrade:dssk` where "dssk" is the tag name for the project they're upgrading, so we should show a message similar to the one shown on this page:

https://publiclab.org/notes/warren/09-20-2016/building-the-stoft-stability-upgrade-for-desktop-spectrometry-starter-kit-3-0

The notification could be shown on this line, triggering on the power tag `upgrade` instead of `replication`:

https://github.com/publiclab/plots2/blob/3702e83c8f50c86ab6d6a197579990d334a12d90/app/views/notes/show.html.erb#L8

`This is an upgrade for ___________. Try building it and _report back how it goes_.`

"report back..." should link to `#Upgrades` which appears lower on the page. 

[ ] Addition of notice to top of page by adding following condition

`<% if @node.has_power_tag('upgrade') %><div class="alert alert-info"><%= raw t('notes.show.upgrade') %> <a href="/n/<%= @node.power_tag('upgrade') %>"><%= raw t('notes.show.replication_link') %></a>.</div><% end %> `

[ ] Replace `t('notes.show.upgrade')` and `t('notes.show.replication_link')` to match the following text `This is an upgrade for ___________. Try building it and _report back how it goes_.`

[ ] Adding link to upgrades in report back

Feel free to ask for any help...

### PR DESCRIPTION
**Pull request by James-N-M**
Fixes #2369 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

I'm unclear of the instructions on how to change things, I;m wondering if t('notes.etc etc') is a file somewhere i modfiy or am i actually hardcoding those strings in

### CODE REVIEW

**Comment by Gauravano** [comment]
hi @James-N-M sorry for late reply, I am just between mid-term exams.

**Comment by Gauravano** [comment]
First of all, let's tag the issue this PR is solving.I am doing it, for now,plz take care from next time.

**Comment by Gauravano** [comment]
okay, I have gone through your project setup and these errors are due to some commits which you have done on master and then made a new branch.So, for solving this run following commands:- 
1. `git checkout master` -  To ensure you are on the master branch 
2. `git reset --hard b2b9390cf22a86c11001a64d1b6d5d65e7b5538a`   - checkout old commit where the files are fine to nullify effect of your commits
3. `git pull https://github.com/publiclab/plots2.git master` -  pulling all changes from plots2

For reference check https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch.It should solve the issues.

**Comment by jywarren** [comment]
Don't worry @James-N-M we'll help you with this -- @Gauravano thanks for taking time from your exams and good luck!!!

**Comment by James-N-M** [comment]
I got plots2 working again with @ryzokuken help haha ! but Yes Im definitely gonna need a more step by step guide on what to change for this :P hoping to actually learn some rails after my midterms as well 🏆

**Comment by seafr** [comment]
Too many files have changed IMO. See `Files changed` at the top.

**Comment by jywarren** [comment]
Hi, @James-N-M -- i'm having trouble finding the exact lines you made your changes on -- can you paste that into the comments here? I'd like to help you resolve this; i think it's possible you may want to re-add your changes to a fresh copy (branch) so that you aren't pulling in a zillion extra files. No worries though, we'll get this!

**Comment by Gauravano** [comment]
Closing this one as @James-N-M is busy https://github.com/publiclab/plots2/issues/2369#issuecomment-374822902 . Although, Thanks so much for trying James.

**Comment by James-N-M** [comment]
@Gauravano Thanks man! @jywarren I havnt touched this and kinda forgot about it for the last little while, youll find me back here after school things !

**Pull request closed without merging**
