### PR TITLE
Updated image shortlinks

### LINKED ISSUE #9979: Image shortlinks aren't redirecting to correct image size
https://publiclab.org/i/44535.png?s=t is supposed to redirect to 

https://storage.googleapis.com/publiclab-production/public/system/images/photos/000/044/535/thumb/Screen_Shot_2021-05-28_at_1.29.16_PM.png

but is instead pointed at:

https://storage.googleapis.com/publiclab-production/public/system/images/photos/000/044/535/original/Screen_Shot_2021-05-28_at_1.29.16_PM.png

Relevant code:

https://github.com/publiclab/plots2/blob/5c8fd13d726d99f43ae87fad873e639bcc5aec79/app/controllers/images_controller.rb#L7-L17

You should be able to set sizes using this syntax - https://publiclab.org/i/44534.png?s=t, https://publiclab.org/i/44534.png?s=m, https://publiclab.org/i/44534.png?s=l (for small, medium, large) but I think the new file storage we published may be routing everything to original size?

We may need (a)icarito's help on this but he may not be available right now.

### PR DESCRIPTION
**Pull request by anirudhprabhakaran3**
Fixes #9979 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Review by Tlazypanda — APPROVED** [review]
Hey @anirudhprabhakaran3  This is looking good :tada: can we get a gif to show that the redirect is working fine now?

**Comment by anirudhprabhakaran3** [comment]
Hi! I am so sorry for such the late reply, I'll upload a video ASAP

**Comment by anirudhprabhakaran3** [comment]
Video showing the correct format

https://user-images.githubusercontent.com/76864239/130360978-4466aeba-1c18-4fd8-b639-f71a3343387e.mp4

@jywarren @ebarry @Tlazypanda review please

**Review by jywarren — APPROVED** [review]
Nice! Thank you!!

**Comment by jywarren** [comment]
This is awesome! Let's check on stable too.

**Comment by jywarren** [comment]
Great this works!

https://stable.publiclab.org/i/39731.jpeg?s=t goes to https://storage.googleapis.com/publiclab-production/public/system/images/photos/000/039/731/thumb/squamous_3_flat_lst.jpeg now.

**Pull request merged**
