### PR TITLE
Fixed /stats page margin

### PR DESCRIPTION
**Pull request by chen-robert**
Fixes https://github.com/publiclab/plots2/issues/6853

By decreasing the column width to `col-lg-10`, the stats panel now fits entirely on the screen. 

image

In addition, I removed the redundant `offset-lg-1` class, because the `margin-left` property was already being set with the inline style. 

Could you please take a look @gauravano @SidharthBansal @IshaGupta18 @cesswairimu @jywarren @ananyaarun @pydevsg @sashadev-sky? Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Just checking, have you completed a task labelled with `first-timers-only` ?
The medium/hard/fall-of-fame needs to be done after these types of tasks

**Comment by chen-robert** [comment]
Yes, I made my `first-timers-only` PR here https://github.com/publiclab/plots2/pull/6901

**Comment by SidharthBansal** [comment]
@nstjean please review this pr.
Thanks

**Comment by nstjean** [comment]
@chen-robert It does fix it now, fantastic! However I notice that at small screen sizes that margin on the left makes it look squished. Can you figure out a way to have no margin at small screen sizes?

FireShot Capture 092 - 🎈 Public Lab_ Stats - localhost

**Comment by VladimirMikulic** [comment]
@SidharthBansal I've claimed this task, but PR for it is here. Shouldn't have @chen-robert claimed it first(so others can't claim it), then start working on it and then submit a PR.

Instructors from Metabrainz Foundation have warned me that this is against the rules because it creates confusion.

Please correct me if I am wrong.

**Comment by chen-robert** [comment]
@VladimirMikulic sorry for the confusion, I was unable to claim this task on GCI because I had another task waiting for approval. If you checked the issue associated with the task https://github.com/publiclab/plots2/issues/6853, you should find the PR mentioned.

**Comment by chen-robert** [comment]
@nstjean I have pushed a commit that centers the div with `margin: 20px auto`, which should remove the excessive margin on smaller screen sizes. Can you please test again? 

image

**Comment by VladimirMikulic** [comment]
Well, you broke the rule. https://codein.withgoogle.com/student-terms/
4.2. "To work on a task, you must first claim it by clicking the “Claim this task” button..."

That's why this is not allowed. in order for a task to count, you need to claim it, submit the work and get it approved. Apparently you can't claim since I claimed it first and you broke the rule by submitting the PR before claiming the task.

@SidharthBansal How should we resolve this?

**Comment by chen-robert** [comment]
@VladimirMikulic I can close this PR if you would like to work on it instead.

**Comment by VladimirMikulic** [comment]
> @VladimirMikulic I can close this PR if you would like to work on it instead.

Don't get me wrong, my intention was not to discredit you in any way.
Since you've already figured out the solution, I think it wouldn't be fair that I score the points for work that you did.

I'll abandon this task and let you claim it, but don't repeat this mistake again.
Also, read the rules they exist for a reason.

I wish you the best of luck & fair play :)

**Comment by chen-robert** [comment]
@VladimirMikulic Okay, thanks! Sorry again for this mistake, best of luck in your future PRs :tada:

**Comment by VladimirMikulic** [comment]
I've just abandoned the task, go claim it before someone else does :)
I hope that now you understand why this is against the rules.

**Comment by cesswairimu** [comment]
Awesome :tada:

**Comment by cesswairimu** [comment]
@chen-robert could you please also add a screenshot for the whole page just to see how the elements looks on a browser. Thanks all

**Comment by chen-robert** [comment]
@cesswairimu Here's what it looks like on mobile
image

And this is the full width browser view
image

**Comment by sashadev-sky** [comment]
@ananyaarun @cesswairimu  Im actually not a mentor for this one of the dashboard so all u guys

**Comment by SidharthBansal** [comment]
I have to go through the discussions and resolve the conflict. Please wait
for sometimes. You can't send a pr before claiming the issue. However if
there is a pr then anyone else can't claim it.
Please wait. I will have a detailed look at this matter.

**Comment by SidharthBansal** [comment]
Actually open source rule says only one issue at a time. The reason for this rule is simple. People should be able to focus on their single piece of work.
Chen was waiting for approval for one task yesterday. So, he was free. So, he did this task in the meantime. GCI dashboard doesn't allowed him to claim this task as he has claimed another task and was waiting for review for claimed task. Chen should write claiming statement at least at the issue. I agree with vladirmin that he should not take any other task when one task was waiting for approval.
Sorry folks for the confusion. I hope Chen will not repeat the mistake again.

**Comment by chen-robert** [comment]
Okay, sorry for the confusion everyone, I won't make this mistake again in the future.

**Comment by SidharthBansal** [comment]
No problem at all. We all learn from our mistakes.

**Comment by chen-robert** [comment]
@jywarren Can we get this merged please? Thanks!

**Comment by jywarren** [comment]
Excellent, thank you so much!!! 🎉 🙌

**Comment by jywarren** [comment]
And, I just wanted to say, thank you for the cooperation here. We're all of us learning to work together every day, and the important thing is that people have a good experience and help one another out. So thank you to everyone for understanding and working through this with respect and friendliness. 🙌 ❤️

**Comment by sashadev-sky** [comment]
also @chen-robert the part 2 task is published on GCI now if you want to grab it after your done with your current one

**Comment by SidharthBansal** [comment]
Only one issue at a time Chen.
If you have some free time then open FTO or convert fto candidates labelled
issue to First timer only labelled issue by using fto template or do or
reviews.
If still you have time I can help you suggesting more things so that it
will not interfare with other student and also you can get points.
Thanks
Sidharth

**Comment by cesswairimu** [comment]
Hey @chen-robert, I just saw you didn't claim the issue on the dashboard. It is not now marked abandoned...Would you like to claim it? Or rather are you able to claim it? Thanks

**Pull request merged**
