### PR TITLE
Google Oauth 

### PR DESCRIPTION
**Pull request by SidharthBansal**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@jywarren the changes are pushed to unstable. But I think there are some error in placing the environment cariables. Have you removed the unnecessary information present in app_id?

**Comment by SidharthBansal** [comment]
Have you @jywarren removed ``.apps.googleusercontent.com`` from client id?
If not please remove it and then push the changes again.

**Comment by jywarren** [comment]
oh sorry i missed that! doing now.

**Comment by jywarren** [comment]
ok just pressed "rebuild"

**Comment by jywarren** [comment]
We should be able to close this PR too.

**Comment by SidharthBansal** [comment]
502 Bad Gateway on unstable.publiclab.org

**Comment by SidharthBansal** [comment]
@jywarren we are getting the same error.
This error comes when we have not set the app_id and app_secret properly

**Comment by SidharthBansal** [comment]
``Missing required parameter: client_id`` means client id and secret is not accessed or they are broken.

**Comment by jywarren** [comment]
Hmm, @icarito what do you think? See our discussion at https://github.com/publiclab/plots2/pull/2771#issuecomment-398204237

**Pull request closed without merging**
