### PR TITLE
Issue code #7737 Change function t to translation in app/views/user_sessions/_form.html.erb

### PR DESCRIPTION
**Pull request by Rohit-786**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, sorry, can you help us get caught up on this? what issue is it in reference to? I do want to be careful about any changes to the login sequence. Can you test this out in a different language using, for example, http://localhost/change_locale/hi-IN ?

**Comment by Rohit-786** [comment]
> Hi, sorry, can you help us get caught up on this? what issue is it in reference to? I do want to be careful about any changes to the login sequence. Can you test this out in a different language using, for example, http://localhost/change_locale/hi-IN ?

Issue code #7703  opened on Mar 21 by Shulammite-Aso 
change function t to translation in app/views/tag/show/_nav_tabs.html.erb first-timers-only

**Comment by Rohit-786** [comment]
> Hey the issue you have linked asks for changes in app/views/notes/_card.html.erb
> But it seems like you have changed another file.
> Can you please chk again so that we can review ?
> Thanks !

My bad..
Change function t to translation in app/views/user_sessions/_form.html.erb #7737

**Comment by SidharthBansal** [comment]
Can you please resolve the conflicts? Thanks

**Comment by cesswairimu** [comment]
Hi all, seems like the issue was solved in another PR https://github.com/publiclab/plots2/blob/master/app/views/user_sessions/_form.html.erb
so sorry @Rohit-786 for the inconvenience ...We will try and get another fto for you within the week

**Comment by cesswairimu** [comment]
Hello, I am sorry but it seems like this was solved in another PR. Closing this...Let me know if you need help finding another issue. Thanks

**Pull request closed without merging**
