### PR TITLE
Fix - 3660 - Added Space between Asking a Question And Exploring Projects Button

### LINKED ISSUE #3660: Adding Space between Asking a Question And Exploring Projects Button
Hi , this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋Solution

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Steps to be done:

### Create a new branch and checkout using this
```sh
git branch SolvesSpacing
git checkout SolvesSpacing
```
- [x] 📝 **Update**
### Code up this
```sh
@media (max-width:269px) {
  .btn.btn-sm.btn-default
  {
    margin-top:10px;
  }
}
```
- [x] 💾 **Commit** using given syntax

### Finally Commit  and push code
```sh
git commit -am SolvesSpacing
```

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by sal2701**
Fixes #3660

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sk9331657** [comment]
Thanks @sal2701 .
My fto has been solved. @jywarren @SidharthBansal

**Comment by sal2701** [comment]
Thanks for letting me do this. @sk9331657 @SidharthBansal

**Comment by jywarren** [comment]
Hi! Thanks so much! Would you be able to share a screenshot of this?

**Comment by sk9331657** [comment]
@sal2701 Add a screenshot so that this pull request can be closed. Are u facing any problem??

**Comment by sal2701** [comment]
using given syntax by giladtamam pull request 3678 publiclab_plots2

@jywarren @sk9331657  I hope this is the required screenshot. Sorry for the delay.

**Comment by sk9331657** [comment]
@sal2701 The screenshot will show that you have added the space between buttons and the code is working . Run the updated code and go to dashboard route and take a screenshot for mobile  view in google chrome.

**Comment by sal2701** [comment]
@sk9331657  Hey , sorry for the delay. Being a beginner I don't have much knowledge about Ruby so I tried following the guide in the README. I am facing some problems while doing it. Can you please help me with this? I am sorry for the inconvenience

**Comment by sk9331657** [comment]
@sal2701 After you setup the project , run the project and go to dashboard section by clicking dashboard button .Are u done with these steps??

**Comment by jywarren** [comment]
Hi, we just need a screenshot to close this one up - any way we can help with that? Thank you!

**Comment by jywarren** [comment]
Thanks so much, this looks wonderful! If you have suggestions for how we
might make initial setup easier we'd love to hear!

**Pull request merged**
