### PR TITLE
Fixes #3429

### LINKED ISSUE #3429: Move an integration test to integration test folder which is present in Unit test file [PART 3]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

Currently some integration tests are present in unit test folder, so we can move them from this folder and add them to integration test folder.
https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/test/unit/comment_test.rb#L226

### PR DESCRIPTION
**Pull request by CodeSarthak**
Fixes #3429 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by CodeSarthak** [comment]
@publiclab/reviewers Any suggestions?

**Comment by CodeSarthak** [comment]
@namangupta01 @rockstar777 Please review.

**Comment by SidharthBansal** [comment]
Please remove conflicts

**Comment by CodeSarthak** [comment]
Removed. @SidharthBansal

**Comment by jywarren** [comment]
Oops, perhaps this conflicted with another person's work on the same segment of code... are you able to resolve the conflicts, or has the task now been completed? Thank you for your contribution!!!

**Comment by jywarren** [comment]
And sorry, conflicts can happen, and I apologize if I merged someone else's work before yours. The best way to avoid this is to communicate clearly in comments with others who are tackling the same issue. We really appreciate your help!

**Comment by jywarren** [comment]
Going to close this, apologies for the mixup and thank you for your contribution!!!

**Pull request closed without merging**
