### PR TITLE
Added back button if user input is wrong in edit profile page

### LINKED ISSUE #3523: There is no save button on edit profile page if you once save wrong
### Please describe the problem (or idea)
There is no button on edit profile page if you save wrong format email or password and confirm-password not match.You can't go back or forward and can't change anythong at that time.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
screenshot 7

I want a button on profile edit page ,because if once we save wrong email or password then we can change email and password at same time.

### Please show us where to look

https://publiclab.org/profile/edit

### What's your PublicLab.org username?
caiptanamerica234
> This can help us diagnose the issue: 

### Browser, version, and operating system
windows 10-chrome

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by 14Richa**
Fixes #3523 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by 14Richa** [comment]
GIF showing how it works after the fix
plots_backbutton

**Comment by ebarry** [comment]
Thanks in advance for taking a look, @publiclab/reviewers!

**Comment by Souravirus** [comment]
@14Richa won't it be good if the user can submit the corrected fields in the same page, instead of going back to a page. What do you think  about this?

**Comment by 14Richa** [comment]
Any feedback, @jywarren @SidharthBansal  and @vishalka98 ?

**Comment by sagarpreet-chadha** [comment]
Hi @14Richa ...your solution looks valid and seems to solve the issue 😄  .
But i guess as pointed out by @Souravirus , it would be more easy from user point of perspective to make the edits on that same page and not go to previous page .

What do you think ?

Thank you 🎈 !

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by SidharthBansal** [comment]
Do you require any help?

**Comment by SidharthBansal** [comment]
As the person is inactive for more than a month, I am closing the PR. In case you want to push changes please feel free to open a new PR OR reopen this PR and add additional changes to it.
Thanks for contributing on Public Lab

**Pull request closed without merging**
