### PR TITLE
Login modal spam wiki

### LINKED ISSUE #4165: Link Login Modal to Spam on wiki pages
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Spam on wiki pages
image
On clicking on the spam icon, modal should be shown

### PR DESCRIPTION
**Pull request by okonek**
Fixes #4165 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

markspam

### CODE REVIEW

**Comment by okonek** [comment]
@SidharthBansal Is it ok? Wow the deadline is in an hour I'm so stressed.

**Comment by SidharthBansal** [comment]
Don't be stressed.

**Comment by okonek** [comment]
Ok, but is this ok?

**Comment by SidharthBansal** [comment]
Please test and provide the gifs while travis is running.

**Comment by okonek** [comment]
There is a gif on top. Do you wnat any more? If so, what should they show?

**Comment by SidharthBansal** [comment]
Through the gif please verify that the after logging in the post is spammed if it has not been marked.
also detect after logging in the post the spammed becomes unspammed.

**Comment by okonek** [comment]
Thank you @SidharthBansal for approving. About that checking, I think there is no way to currently check if wiki was already marked as spam by a user, because it's just an email popup.

**Comment by SidharthBansal** [comment]
@jywarren @gauravano may suggest something.

**Comment by oorjitchowdhary** [comment]
@okonek I think you inverted the changes.. you put the if code in `else` and the else code in `if`

**Comment by jywarren** [comment]
Hi! there is actually a spam button shown here;

image

If we don't know if a user is a moderator, we don't show it. And it's a feature that we offer an email link even if you're not. So maybe if you are logged in and you are an admin or moderator (in user.role) then we can show the spam button that's currently hidden under the like menu? 

So how about... this modal really should show up if you open the like menu in order to spam the page, and you see the 🚯 icon inside that menu. Clicking on it would prompt you to log in if you're not.

**Comment by gauravano** [comment]
Hi @okonek thanks for working on this issue, but unfortunately, it's not required. See https://github.com/publiclab/plots2/issues/4165#issuecomment-445855441 for reference. Thanks!

**Pull request closed without merging**
