### PR TITLE
Changed function t to translation in dashboard/_node_question

### PR DESCRIPTION
**Pull request by Devang-25**
Changed function t to translation in dashboard/_node_question by Devang Sharma for GCI Mentorship Task.
Task Category- First Timers Only.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Please provide issue number and screenshot to demonstrate correct functioning.

**Comment by nstjean** [comment]
@Devang-25 This is for issue #6603, which already had a Pull Request submitted.

This PR can be closed.

**Comment by SidharthBansal** [comment]
@Devang-25  Please try other issues

**Comment by Devang-25** [comment]
Can you suggest me some more please?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
11/07/19,
02:52:20 AM

**Comment by SidharthBansal** [comment]
You can write a comment at https://github.com/publiclab/plots2/issues/6206
We will try to assign you a fto asap

**Pull request closed without merging**
