### PR TITLE
Fixes #4304 -- Suggestions out of parent element

### LINKED ISSUE #4304: Improper css formatting of 'Ask a question' suggestions
**Problem:** The suggestions appear to be out of the parent element. I think this is a responsiveness issue, because on adjusting the width of the viewport, the issue ceases to exist.

screenshot from 2018-12-15 03-56-12

screenshot from 2018-12-15 03-29-58

**Fix:** I think removing the 'width' attribute entirely from the #questions_searchform .dropdown-menu would fix this.

screenshot from 2018-12-15 03-32-13

**Also, I think maybe we should mark this as a `first-timers-only` issue.**

### PR DESCRIPTION
**Pull request by rexagod**
Fixes #4304 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by rexagod** [comment]
@publiclab/reviewers This fixes #4304 (and implements @sashadev-sky's idea).

**Comment by sashadev-sky** [comment]
@rexagod thank you for your work. Can you post a screenshot of the page please :)

For now I checked by making your edits in Chrome Dev Tools and it looks good! I didn't know about the text-overflow: ellipsis feature so thank you for showing me that

**Comment by rexagod** [comment]
@sashadev-sky Here goes.

screenshot from 2018-12-17 17-15-21

**Comment by rexagod** [comment]
@publiclab/reviewers Can we merge this now?

**Comment by sashadev-sky** [comment]
Looks good to me! Thanks for your work.
@jywarren @gauravano can you please review this and merge this?

**Comment by gauravano** [comment]
Merged :balloon:

**Comment by gauravano** [comment]
Thanks @rexagod and @sashadev-sky!

**Pull request merged**
