### PR TITLE
Added padding for dropdowns in stats page

### LINKED ISSUE #7577: Dropdown not spaced properly in Stats page
### Please describe the problem (or idea)
 The elements in the dropdown are not spaced properly in Stats page.This needs to be modified to make the UI more appealing.  
image8

### Please show us where to look

https://publiclab.org/stats

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #7577 
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

#Screenshot  
Screenshot from 2020-02-29 14-01-56

Thanks!

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@VladimirMikulic @jywarren can you kindly review? Thanks :v:

**Comment by Tlazypanda** [comment]
@VladimirMikulic Ohh sorry about that :sweat_smile:  since there was no existing class in the li tag I thought the simple solution would be to just add padding for it but it makes more sense to add the `dropdown-item` class to it so that code remains maintanable further ahead.Thanks for the guidance and mentoring :v: I have made the changes can you kindly review? Thanks :smile:

**Comment by VladimirMikulic** [comment]
It's been my pleasure to work with you! You are doing really awesome work!
Could you post a screenshot of this change for others as well? Thanks.

**Comment by Tlazypanda** [comment]
@VladimirMikulic Thanks a lot that means a lot ..this community has been absolutely amazing with great mentors who want to see you progress but at your own pace ..really appreciate it :100: :tada: 
Here's the screenshot :  
image

**Comment by Tlazypanda** [comment]
@cesswairimu Is this ready for a merge? Thanks :v:

**Pull request merged**
