### PR TITLE
Center Align Images on /wiki page

### LINKED ISSUE #10755: Images on /wiki are not center aligned
### Please describe the problem (or idea)
After the recent change in the look of the `/wiki` page via #10731, the images in the _Image_ column are not center aligned. 

image

The relevant code can can be found in [this file](https://github.com/publiclab/plots2/blob/main/app/views/wiki/_wikis.html.erb)

### Please show us where to look

https://publiclab.org/wiki

### Browser, version, and operating system
Browser: Chrome
Version 98.0.4758.102
OS: Ubuntu 20.04.3 LTS via WSL 2 on Windows 11

****

### PR DESCRIPTION
**Pull request by AbihaFatima**
Fixes #10755  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

#### Type of Change:
- Code
- User Interface

#### Screenshots:
Before
Before-2

After
After-2

### CODE REVIEW

**Comment by AbihaFatima** [comment]
> a. Should we have this same class that you have added, for the [scraped image](https://github.com/publiclab/plots2/blob/main/app/views/wiki/_wikis.html.erb#L25) as well? 

Oh yes! This can be done.

> b. Should we keep some text like _NA_ to signify that there is no image associated with the wiki page, in case there is no image attached for the wiki page?

I think you're right. Thanks @mittal-parth for pointing this out, I think it would be better to open a seperate issue for this. As this PR primarily focuses on to fix the alignment of the already existing image. Always open for suggesstions!

wdyt @cesswairimu

**Comment by TildaDares** [comment]
> I think you're right. Thanks @mittal-parth for pointing this out, I think it would be better to open a seperate issue for this. As this PR primarily focuses on to fix the alignment of the already existing image. Always open for suggesstions!

@AbihaFatima You can open an FTO for this if you like.

**Comment by AbihaFatima** [comment]
> @AbihaFatima You can open an FTO for this if you like.

Hey @TildaDares, I have opened the FTO issue #10776 . Let me know if any changes are required. Thanks!

**Comment by cesswairimu** [comment]
Thanks all, I will try to close and reopen to see if the failing test will pass

**Review by cesswairimu — APPROVED** [review]
Looks good :tada:

**Comment by cesswairimu** [comment]
Merging this now. Thanks everyone

**Pull request merged**
