### PR TITLE
Blog's page read-more button implemented

### LINKED ISSUE #5352: Blog redesign next steps and discussion
We're looking to improve the blog template again with some design inspiration from this WordPress template:

image

We'd like to keep it really minimal but want to:

* add a sidebar including recent posts
* show only the first 300px of the post content, with a `Read more` button that toggles the rest to be visible
* include social media links in sidebar
* include a list of recent tweets in sidebar

We'd love help chopping this up into pieces to implement! This is a pretty simple set of changes that would make some good first-timers-only issues!

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #5352  (<=== Add issue number here)

GIF for the change:
Peek 2019-04-10 23-31

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by divyabaid16** [comment]
@jywarren how does this look?

**Comment by divyabaid16** [comment]
@gauravano @jywarren can you please review this?
And how do I get the label rights so that I can add ```review me``` label to the PRs?

**Comment by gauravano** [comment]
Hi @divyabaid16, I think @publiclab/plots2-reviewers have that access and some other people. If you like to join reviewers team then comment here - https://github.com/publiclab/plots2/issues/4707

Thanks!

**Comment by gauravano** [comment]
Merged :tada: :+1:

**Pull request merged**
