### PR TITLE
Add tests for Node

### PR DESCRIPTION
**Pull request by seabl**
Fixes #0000

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Hi @seabl -- this just needs to be rebased over the latest master branch, as we've fixed the unrelated issue which is causing the tests to fail! 

You can do that by following the process outlined here, but you may be able to skip step 2 if your master branch is still in sync with publiclab's master branch: https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

Thanks!

**Comment by jywarren** [comment]
OK, i've just rebased this!

**Comment by jywarren** [comment]
Great! Thank you!!!

**Comment by seabl** [comment]
@jywarren Thanks a lot for this, and sorry for the terrible delay. Thank you :+1:

**Comment by jywarren** [comment]
No problem at all! Thanks for your help!

**Pull request merged**
