### PR TITLE
Adjust formatting of inline thumbnail grids

### PR DESCRIPTION
**Pull request by ValentinaTironi**
Fixes #3970 

Gif showing the `show more` button (I added a `show less` too but I couldn't upload it because Github just allows 10MB)
more

And, here is a static image of grids of notes
screen shot 2018-11-26 at 11 16 41 pm

### CODE REVIEW

**Comment by jywarren** [comment]
This is great. Could you show a gif where you narrow the window to show the display on mobile width screens? Thank you!!!

**Comment by ValentinaTironi** [comment]
Hey! I'm gonna do some changes to adapt better to mobile. If you are agree, of course!

**Comment by ValentinaTironi** [comment]
Well, What do you think?

**Web screen:**
screen shot 2018-11-27 at 2 55 29 pm

**Middle screen:**
screen shot 2018-11-27 at 2 54 43 pm

**Mobile screen:**
screen shot 2018-11-27 at 2 55 16 pm

**Comment by jywarren** [comment]
This is fantastic. Merging and approving now! Thank you!!!!

Would you be interested in https://github.com/publiclab/plots2/issues/3384 ? I'd be happy to make a task from it!

**Comment by ValentinaTironi** [comment]
Hi! Sorry for my absence. Thank you too much! I'm gonna to look the issue and if I think I can help you of course I'll. Thank you too much to the opportunity

**Comment by ValentinaTironi** [comment]
@jywarren Ready! Don't worry about creating a Google code for that, I really didn't do anything, it's fine with me! Thank you very much for thinking of me to help you, it's a pleasure

**Comment by jywarren** [comment]
This is amazing, the inline thumbnail grids look great! https://publiclab.org/micro

However I'm reading about how the breakpoints need a "clearfix" like this:

`<div class="clearfix visible-lg-block"></div>`

after the first 3 items. To avoid the odd wrapping shown here:

image


Read a bit about this here: https://getbootstrap.com/docs/3.3/css/#grid-responsive-resets

I was wondering if you'd mind making that tweak, adding that in -- you should be able to insert it by using an `each_with_index` iterator as in this line:

https://github.com/publiclab/plots2/blob/58db2b8cc6ba72e650c25e4767553bbc9fcc07b6/app/views/notes/_notes.html.erb#L4

Does that make sense? So, if index == 2, you'd know it's the third column, and you'd insert this little clearfix object. I tested it in the Google console on the page, and it properly wraps the items. What do you think?

**Comment by ValentinaTironi** [comment]
Hello @jywarren 
I'm so sorry for the error, I didn't see it locally. Of course I'll resolve it! 
Give a couple of minutes

**Comment by ValentinaTironi** [comment]
What do you thing about that `if index + 1 % 3 == 0`? Because if you do `if index == 2` you just are gonna put a `<div class="clearfix"></div>` in the first third column and not in every third (for row). I don't know if I'm being clear :/

**Comment by jywarren** [comment]
oh, i see -- right, yes, i think the % operator makes sense. Good catch!

**Comment by ValentinaTironi** [comment]
Ready! Everything is fine. I'm gonna do the pr right now
screen shot 2018-11-29 at 1 14 54 pm
screen shot 2018-11-29 at 1 14 44 pm

**Comment by ValentinaTironi** [comment]
@jywarren I had to do a new pull request :/ forked repository, you know

**Pull request merged**
