### PR TITLE
Darken text under tags visualization

### PR DESCRIPTION
**Pull request by ChamuMutezva**
font color changed to be darker

Fixes ##6532
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by nstjean** [comment]
Hi, this looks great! Can you just edit the post and include the issue #6532 at the top there? That will update the other thread so everyone can see that this pull request fixes that issue. Thanks so much! :relaxed:

**Comment by cesswairimu** [comment]
Hi @ChamuMutezva could you please provide a screenshot for this? thanks for working on this

**Comment by nstjean** [comment]
I'm not sure what the procedure is here. @cesswairimu there was a PR submitted but it wasn't merged.

**Comment by cesswairimu** [comment]
@nstjean we are still waiting for the screenshot from @ChamuMutezva...what was the color change from and  to? Thanks all

**Comment by nstjean** [comment]
Here's a screenshot. It's the text underneath the image map, made a little darker for visibility.

FireShot Capture 062 - 🎈 Public Lab_ Tags - localhost

**Comment by jywarren** [comment]
Awesome, thanks so much!!!! This is super, both of you!

**Comment by jywarren** [comment]
Just changed the title to be a bit more descriptive so that when we skim the PRs list we know what this is! Thanks again!!!

**Pull request merged**
