### PR TITLE
Updated redirect path

### LINKED ISSUE #7186: Change URL redirect after moderating a spam comment
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/controllers/admin_controller.rb](https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -153,7 +153,7 @@ def mark_comment_spam
     else
       flash[:error] = 'Only moderators can moderate comments.'
     end
-    redirect_back(fallback_location: root_path)
+    redirect_to @comment.node.path + '?_=' + Time.now.to_i.to_s
   end
 
   def publish_comment
@@ -176,7 +176,7 @@ def publish_comment
         end
       end
       @node = @comment.node
-      redirect_to @node.path
+      redirect_to @node.path + '?_=' + Time.now.to_i.to_s
     else
       flash[:error] = 'Only moderators can publish comments.'
       redirect_to '/dashboard'
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by sssash18**
Fixes #7186  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sssash18** [comment]
@publiclab/reviewers  Can you help me with the code climate test fails?

**Comment by sssash18** [comment]
@publiclab/reviewers  Could you help me with the tests?

**Comment by SidharthBansal** [comment]
@Uzay-G kindly review

**Comment by Uzay-G** [comment]
Yeah I will help you out :+1:. Basically, there are several tests that assert the redirection goes to the node without the `'?_=' + Time.now.to_i.to_s` you added. So we need to modify the tests to reflect these changes.

**Comment by Uzay-G** [comment]
I will send you the lines you need to edit, and could you kindly add `+ '?_=' + Time.now.to_i.to_s` at the end of each one? I can't edit your pull request unfortunately but I will guide you :+1:.
So for example this: https://github.com/publiclab/plots2/blob/8991718e6ff603688513e60ece6497afaec36f5e/test/functional/admin_controller_test.rb#L626 becomes `assert_redirected_to node.path ` becomes  ` '?_=' + Time.now.to_i.to_s`.
You need to also do that for:
- https://github.com/publiclab/plots2/blob/8991718e6ff603688513e60ece6497afaec36f5e/test/functional/admin_controller_test.rb#L547
- https://github.com/publiclab/plots2/blob/8991718e6ff603688513e60ece6497afaec36f5e/test/functional/admin_controller_test.rb#L577
- https://github.com/publiclab/plots2/blob/8991718e6ff603688513e60ece6497afaec36f5e/test/functional/admin_controller_test.rb#L565
- https://github.com/publiclab/plots2/blob/8991718e6ff603688513e60ece6497afaec36f5e/test/functional/admin_controller_test.rb#L593

**Comment by sssash18** [comment]
@Uzay-G Done that!

**Comment by SidharthBansal** [comment]
@Uzay-G are there any remaining changes?

**Comment by Uzay-G** [comment]
No everything is good @SidharthBansal!

**Comment by SidharthBansal** [comment]
Can you please apply `login and signup milestone` on each redirection or
login or modal or signup or authentication issue and pr. ?

**Comment by Uzay-G** [comment]
> Can you please apply `login and signup milestone` on each redirection or
login or modal or signup or authentication issue and pr. ?

I don't think I have the permission to add milestones.

**Comment by SidharthBansal** [comment]
Please comment so that I can if it is missing milestones

**Comment by SidharthBansal** [comment]
Have you received points for this task?

**Comment by Uzay-G** [comment]
Oh this was just a review for @sssash18.

**Comment by SidharthBansal** [comment]
Oh sorry.
1 points/week for all pr reviews until review is GIGANTIC.

**Comment by SidharthBansal** [comment]
Thanks for extra help. We really like it
Thanks both of you

**Pull request merged**
