### PR TITLE
Same format to delete comment and answer

### LINKED ISSUE #3540: Inconsistent alert for same page
### Please describe the problem (or idea)
When we delete any comment the alert looks nice but while deleting any answer alert is the default alert.
answer

comment

### Please show us where to look
https://publiclab.org/questions/jradheshyam96/09-28-2018/may-i-know-more-about-how-exactly-this-will-this-work

### What's your PublicLab.org username?
vikul1234
> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome, windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by ValentinaTironi**
Fixes #3540  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

Here is the gif when you click the delete button in answer.

alert_format_2

### CODE REVIEW

**Comment by avsingh999** [comment]
hi @ValentinaTironi  great work , can you post a gif/screenshot 😄 
thank you

**Comment by ValentinaTironi** [comment]
@avsingh999 Yes! Of course!

**Comment by ValentinaTironi** [comment]
Thank you so much!

**Comment by kevinzluo** [comment]
This looks cool!

I just have one question:
Would it be better to change `$("#a<%= answer.id %>delete-btn").remove()` [(here)](https://github.com/publiclab/plots2/pull/4010/files#diff-1cd76cef3f128d5207b3d5d8afc09584R139) to `$("#a<%= answer.id %>").remove()` so the user sees the whole answer being removed instead of just the delete button?

**Comment by gauravano** [comment]
Actually, that is left intentionally so that a beginner GCI task can be formed.  Any @publiclab/mentors feel free to open a new task and notify here to avoid any task duplication

**Comment by jywarren** [comment]
Excellent here too!!! Great work. 👍

**Pull request merged**
