### PR TITLE
Improve code to match Ruby Style Guide

### LINKED ISSUE #1348: Ruby style guide
There are many violations against the Ruby style guide. Is it OK to fix these violations using tools such as Rubocop? I can slowly complete this because there are over 10K violations.

### PR DESCRIPTION
**Pull request by siaw23**
This make simple code improvements for a more readable code
Closes #1348 (part of)

All tests pass.

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great; merging. Thanks! So, perhaps we could try /all controllers/? How do you suggest we approach this gradually? I'm very open to suggestions!

**Comment by siaw23** [comment]
i'm going to fix all of the files in the controller tonight, run tests and make one big push for the controller, if it gets merged, i'll submit the fixes folder by folder... how about that?

**Comment by jywarren** [comment]
I think that sounds reasonable. We should also link to the style guide from
the readme and perhaps we could integrate some automated feedback via
Danger as well, as long as it's friendly!

Thank you!!

**Comment by siaw23** [comment]
yes, i'd like to include the README and gems for checking style guide after i have checked everything on my end. the reason is some tests failures are triggered and i wanted to fix them before so others can concentrate on contributing code instead of fixing test failures. so yeah, i'm on it... thanks @jywarren

**Pull request merged**
