### PR TITLE
Improved the gap in sidebar

### LINKED ISSUE #7619: Lack of gap in sidebar on dashboard
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
When the user is not logged in the sidebar looks like this and lacks a gap.
**Current behaviour**
Screenshot 2020-03-10 at 10 26 14 AM

> What did you expect to see that you didn't?
**Expected Behaviour**
Screenshot 2020-03-10 at 10 26 31 AM

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by sssash18**
Fixes #7619  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below
**New Behaviour(Not logged in)**
Screenshot 2020-03-12 at 9 59 27 AM

**Logged in**
Screenshot 2020-03-10 at 7 13 30 PM

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sssash18** [comment]
@VladimirMikulic @SidharthBansal @Uzay-G Please review the changes.

**Comment by VladimirMikulic** [comment]
Hi @sssash18! Thank you for solving the issue.
You've implied that this only occurs when the user is not logged in.
Could you please post another screenshot that shows how the change looks when the user is logged in?

**Comment by sssash18** [comment]
@VladimirMikulic I made the required changes.Thanks!

**Comment by sssash18** [comment]
@VladimirMikulic Please have a look on the changes.Thanks!

**Comment by sssash18** [comment]
@VladimirMikulic Please review the changes made

**Comment by sssash18** [comment]
@VladimirMikulic Please review it now. Thanks for your patience!

**Comment by VladimirMikulic** [comment]
Could you post new screenshots? Thanks.

**Comment by sssash18** [comment]
@VladimirMikulic  The above scrrenshots are the latest ones.

**Comment by VladimirMikulic** [comment]
@sssash18 no they are not :)
Github shows they are 2 days old.

**Comment by sssash18** [comment]
@VladimirMikulic Actually here are the screen shots:
Screenshot 2020-03-14 at 9 49 05 AM
Screenshot 2020-03-14 at 9 49 25 AM
As they were same as before therefore I told so.
Sorry for misleading you

**Comment by VladimirMikulic** [comment]
@sssash18 no problem, really! It's nice to see that it works.

**Pull request merged**
