### PR TITLE
Update _notes.html.erb

### LINKED ISSUE #4937: Improve view of  /notes page
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
At https://publiclab.org/notes the Spam and Read more buttons are rendering on the different lines as visible in the screen shot
notes_view

Update https://github.com/publiclab/plots2/blob/master/app/views/notes/_notes.html.erb#L49-L52 so as to show both buttons in a single line enhancing the page design

After changing the view, also attach the screenshot of updated view in the PR.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by AnthoniaOkafor**
Update_notes

Fixes #4937 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
hey @AnthoniaOkafor, please add the issue number in the PR  comment - https://github.com/publiclab/plots2/pull/4961#issue-259593726. 

Regarding screenshot, you need to run local server, then go to /notes and take the screenshot of that page so that we can verify that buttons are appearing on the same line.

Any doubt?

**Comment by AnthoniaOkafor** [comment]
Issue number #4961

**Comment by AnthoniaOkafor** [comment]
@gauravano 
I chose cloud9 because I don't have the server installed locally. I've been unable to run  the notes file successfully. Any help on running it on cloud9?

**Comment by gauravano** [comment]
Ok, so were you able to run app on cloud9 yet or need help with that too?

**Comment by gauravano** [comment]
Prefer to mention the issue number as `Fixes [issue-number]` in the PR's 1st comment, as including that automatically closes the issue when PR gets merged. Thanks!

**Comment by AnthoniaOkafor** [comment]
Please I also need help running the app on Cloud9. I always get 'Cloud9 can't get you to your requested workspace...'

**Comment by gauravano** [comment]
I have never ran plots2 on cloud9 myself so don't know much about this. Let's ask @jywarren and @publiclab/plots2-reviewers if they can help. 

Also, @jywarren can you send me cloud9 invite so I can setup, understand and help others better with cloud9. Thanks!

**Comment by jywarren** [comment]
OK, adding you now! I wonder if it's changed somehow... sorry Anthonia, for
the trouble!

**Comment by AnthoniaOkafor** [comment]
Hello @gauravano 
Were you able to run the app on cloud9?

**Comment by gauravano** [comment]
I got the invite from @jywarren but haven't done the setup yet. I will respond here in an hour. Thanks and sorry for the delay.

**Comment by gauravano** [comment]
I did the whole setup and wasn't able to figure out the issue. Getting same page - https://plots2-gauravano.c9users.io/

Although, server is running fine - 
cloud_9

@jywarren we need to run server via cmd right on cloud9?

**Comment by gauravano** [comment]
ok I solved it for me.

Although, now facing a little diff error

**Comment by jywarren** [comment]
Hmm, i'm not sure, as I haven't run it recently. I believe @siaw23 has done
so a little more recently but I could be wrong?

**Comment by gauravano** [comment]
@AnthoniaOkafor run server by this command only - `rails s -b $IP -p $PORT` .

I ran server by `rails s` and that's why not able to reach the page

**Comment by gauravano** [comment]
And, got it running :tada: 

running

**Comment by gauravano** [comment]
I ignored the message generated by this https://github.com/publiclab/plots2/blob/master/install_cloudnine.sh#L18  command and that's why it took time to run the app running.

@AnthoniaOkafor at any step you feel, the documentation can be improved? I think we can explicitly write there to run the server via - `rails s -b $IP -p $PORT` only?

**Comment by AnthoniaOkafor** [comment]
Thanks @gauravano . I used rails s -b $IP -p $PORT but running it doesn't give me same result as yours.  See attached photo. Can I share my workspace with you?
Screenshot_Index

**Comment by AnthoniaOkafor** [comment]
I created a new workspace, installed it but I still cannot run the app. Please see the photo.

Screenshot (210)

**Comment by gauravano** [comment]
> Can I share my workspace with you?

yes @AnthoniaOkafor!

**Comment by gauravano** [comment]
I saw you ran project via run project button. Try running by entering ` rails s -b $IP -p $PORT ` on terminal too.

**Comment by AnthoniaOkafor** [comment]
I get the same result when I use either the terminal or the button. I have shared my workspace with you.

**Comment by gauravano** [comment]
You were getting this error - #4936. This has been resolved some days ago so updated the master branch of your fork. 

After that, I got `@' is not allowed as an instance variable name` error, so I navigated to some routes and suspected that database is not created. After trying some commands in `rails c`, it got confirmed that database was not created so I ran `rake db:setup`. After that I ran app and it worked but I got missing debounce package error which was also introduced some days ago so I ran `yarn install` to install the dependent package.

After that, app is running just fine :point_down: 
running_cloud9_2

You can now run directly using `rails s -b $IP -p $PORT` and it will work. Any questions?

**Comment by AnthoniaOkafor** [comment]
Thank you, thank you, I'm so happy it is running. Yes, I have a question please.

To continue my FTO issue, how do I go to /notes and run it on cloud9? I went to 'Goto' tab and searched '/notes' but a lot of notes came up and I don't know which is the right one.

**Comment by AnthoniaOkafor** [comment]
Thank you, thank you, I'm so happy it is running. Yes, I have a question please.

To continue my FTO issue, I followed the path plots2/app/views/notes/_notes.html.erb but the changes I made to the '_notes.html.erb' isn't in this present workspace, whereas it automatically got updated in my previous workspace. Could you direct me on how to update the changes in this PR to reflect on cloud9 so I can run it.
Many thanks.

**Comment by AnthoniaOkafor** [comment]
When I run the note page on cloud9, only the read button shows, the spam button is not visible. I also manually added the code to make the two buttons render on same line, but the spam button doesn't show when run. I don't know if making the spam button visible is among my FTO issue because I have been unable to make it show. @gauravano 

Screenshot (211)

**Comment by gauravano** [comment]
hey @AnthoniaOkafor, you have to login as moderator/admin to see spam button. Log in with test usernames "moderator", or "admin", and password "password" for both accounts.

I guess, your cloud9 setup is cloned from your Git repo only so you can just push and pull the changes like normal system.

Thanks!

**Comment by AnthoniaOkafor** [comment]
Hello @gauravano. I have successfully made the two buttons to be on same line and have pushed to my fork of plots2. Do I open a new PR or should I continue with this present PR?
Screenshot (217)

**Comment by gauravano** [comment]
This PR is fine @AnthoniaOkafor.

**Comment by gauravano** [comment]
Hey @AnthoniaOkafor, I ran this PR locally but issue still exists.I guess you haven't pushed new commits on this branch. Please update it. Thanks!

**Comment by AnthoniaOkafor** [comment]
Ok @guaravano. I will do that

**Comment by AnthoniaOkafor** [comment]
Hello @gauravano 
Please see the update on the PR

**Comment by gauravano** [comment]
But, there is no new commit in this PR as I can see. have you opened new PR? @AnthoniaOkafor

**Comment by AnthoniaOkafor** [comment]
No I didn't open new PR. I committed my fork AnthoniaOkafor/plots2 thinking it would reflect on the PR. I used these commands:
git commit -a
git merge upstream master
git push origin master

**Comment by AnthoniaOkafor** [comment]
Hello @gauravano, when I opened this PR, I edited the notes file through github without running the app to see the result but then you directed me to run the app and take the screenshot of the notes page. Could it be that I'm unable to update this PR because I first edited it on GitHub instead of the server.

**Comment by gauravano** [comment]
> No I didn't open new PR. I committed my fork AnthoniaOkafor/plots2 thinking it would reflect on the PR. I used these commands:
git init
git remote add upstream https://github.com/publiclab/plots2
git fetch upstream
git checkout master
git commit -a
git merge upstream master
git push origin master
Kindly let me know how to update the PR

In above steps, you have updated `master` branch, whereas your PR is on `patch-3` branch.

**Comment by gauravano** [comment]
> Hello @gauravano, when I opened this PR, I edited the notes file through github without running the app to see the result but then you directed me to run the app and take the screenshot of the notes page. Could it be that I'm unable to update this PR because I first edited it on GitHub instead of the server.

You have to fetch the branch `patch-3` on your system(cloud 9 in your case), checkout that branch and then see changes on the page after running server.

You can do this by:

`git stash` -- for removing all minor changes, if any
`git fetch https://github.com/publiclab/plots2/ pull/4961/head:pr-4961` -- this will create a branch pr-4961 on your system
`git checkout pr-4961` -- for checking out that branch
`rails s` -- running the server

Now, navigate to the /notes page and ensure that you are logged in as admin

**Comment by gauravano** [comment]
Give above steps a try and if you face any trouble then let me know, I will do the above steps for you and record them too so that you can observe it closely?

I know, it can be hard and maybe frustating but once you get it to work, it's an awesome feeling :+1: 

@AnthoniaOkafor

**Comment by AnthoniaOkafor** [comment]
After I checkout pr--4961, I entered rails s -b $IP -p $PORT which instead of running gives me this:
/usr/local/rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/parser/arguments.rb:133:in `parse_numeric': Expected numeric value for '--port'; got "0.0.0.0" (Thor::MalformattedArgumentError)
Could you help me resolve this @gauravano ?

**Comment by AnthoniaOkafor** [comment]
> Give the above steps a try and if you face any trouble then let me know, I will do the above steps for you and record them too so that you can observe it closely?
> 
> I know, it can be hard and maybe frustrating but once you get it to work, it's an awesome feeling 
> 
> @AnthoniaOkafor

I have tried but could not get it to run. Please help me out on this. Thanks

**Comment by gauravano** [comment]
ok, are changes on cloud9?

**Comment by AnthoniaOkafor** [comment]
Yes but my clone doesn't run again, I now get same error when I run the app as I got when I run pr-4961

**Comment by gauravano** [comment]
Checking your cloud9 setup now

**Comment by gauravano** [comment]
Your branch was outdated so I rebased it. You can do changes on cloud9 now and whenever you want to push the changes do it by

`git push origin pr-4916:patch-3`  as pr-4916 is the name of that branch locally and at origin ie., your repo know it by name patch-3

**Comment by AnthoniaOkafor** [comment]
Thank you @gauravano . I have now updated my PR.

**Comment by gauravano** [comment]
**Adding screenshots:**

Master view:
Screenshot from 2019-03-22 20-11-29

PR view:
Screenshot from 2019-03-22 20-13-21

**Comment by AnthoniaOkafor** [comment]
Thank you so so m

**Comment by jywarren** [comment]
Awesome!!! Thanks so much!

**Pull request merged**
