### PR TITLE
Wiki pages with CRUD as title should not be published

### LINKED ISSUE #2322: Wiki pages should not be created with CRUD titles
### Please describe the problem (or idea)
A user can create a wiki page with create, new, update, edit, delete etc as title

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #2322
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
image

image

image

image

are the snapshots

**Comment by SidharthBansal** [comment]
@Gauravano yeah you are correct. Sorry @jywarren @ebarry I did not ask you both. I just found an error and made a fix for that. What all changes I need to push into this pr??

**Comment by jywarren** [comment]
This is great! Very clever catch! But is there any way to reduce redundancy by iterating over a list of forbidden names in both controller and test, so like `['create','delete'...]`?

**Comment by SidharthBansal** [comment]
Yeah sure. I will change it

**Comment by jywarren** [comment]
Awesome. Thanks so much! 🎉 🎈 👍 👍

**Pull request merged**
