### PR TITLE
Auto-set wiki slug

### PR DESCRIPTION
**Pull request by jywarren**

### CODE REVIEW

**Comment by jywarren** [comment]
Hm, @icarito i'm seeing:

`E: Package 'libmysqlclient-dev' has no installation candidate`

And at top, also:

```
Running apt-get update by default has been disabled.
You can opt into running apt-get update by setting this in your .travis.yml file:
  addons:
    apt:
      update: true
```

I wonder if a Travis setting just changed and we're seeing more failures now? @publiclab/reviewers anyone also notice this?

**Comment by icarito** [comment]
Hi Jeff,
I am facing the exact same issue. I think we are referencing `ruby-2.3` image and it has just been set to run on `stretch` by default instead of `jessie`. I'm getting some success by explicitly setting the base image like this https://github.com/publiclab/plots2/commit/f4b8452572bc1dd9e21cf0cbc2da5836adb28fb7#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by jywarren** [comment]
OK cool - what PR are you working in there? I can't seem to navigate to the PR. 

Thanks!!!

**Comment by icarito** [comment]
I'm trying to get https://github.com/publiclab/plots2/pull/2593 to be merged so we can start using the Makefile to build/deploy. But running into this.

**Pull request merged**
