### PR TITLE
closes #1345 questions fix - hotfix - [in-testing]

### LINKED ISSUE #1345: Question links not functioning
### What happened just before the problem occurred
I clicked on a question link and received "There was an error. Are you sure you have the right address?"

It appears to apply to all questions.  While they appear on the dashboard, questions page, etc, all links are dead:
https://publiclab.org/questions

### PR DESCRIPTION
**Pull request by jywarren**
urgent - also we need to view-test question `show` template, or the `app/assets/javascripts/question.js` file, which would've caught this. Closes #1345.

* [ ] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, so the error would only have been caught in a JavaScript test, I guess. I'll try adding one...

**Comment by jywarren** [comment]
OK, I introduced an intentional bug into `question.js` to see if this new Jasmine test catches it.

**Comment by jywarren** [comment]
Hmm, @ananyo2012 - I see:

`Danger does not have write access to the PR to set a PR status.` (this probably affects all PRs, and can I help by giving permission?)

I also don't see Jasmine test output : https://travis-ci.org/publiclab/plots2/builds/213534306

Compare to: https://travis-ci.org/publiclab/plots2/builds/215187186

I think perhaps a syntax error is causing them to not run... but silently, which is too bad.

**Comment by jywarren** [comment]
Hmm, @icarito - I introduced a parsing error into the JavaScript file (see how I just removed it, here: https://github.com/publiclab/plots2/pull/1346/commits/df3a4fac2db031eadc3a1735bf175bdcae072a2b) but it did not cause the tests to fail; they merely did not load the Jasmine tests, and showed 0 tests and 0 failures. Is there any way we can get a syntax error in a JavaScript file to actually cause Travis tests to return a failure? Thanks!

**Comment by jywarren** [comment]
Hmm, upon removing that offending line, I now see a JavaScript error:

```
Running jasmine tests headlessly
Running `"/usr/local/bin/phantomjs" "" "/usr/local/lib/ruby/gems/2.1.0/gems/jasmine-rails-0.12.6/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///app/tmp/jasmine/runner.html?spec="`
Running: file:///app/tmp/jasmine/runner.html?spec=
Killed
rake aborted!
Error executing command: "/usr/local/bin/phantomjs" "" "/usr/local/lib/ruby/gems/2.1.0/gems/jasmine-rails-0.12.6/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///app/tmp/jasmine/runner.html?spec="
/app/lib/tasks/test.rake:12:in `block (2 levels) in <top (required)>'
Tasks: TOP => test:all
(See full trace by running task with --trace)
```

Odd. But I can't see what it is. I'll try to set this up to run locally, but have been having some trouble with phantomjs tests on my local machine.

**Comment by icarito** [comment]
Maybe it's related to https://github.com/jywarren/web/issues/70 (Solr test suite not failing TravisCI checks when there are failures #70). I'll have a look!

**Comment by jywarren** [comment]
Merging as the failure is due only to a very very slight reduction in test coverage for a test that didn't actually test anything.

**Pull request merged**
