### PR TITLE
Profile page likes rendered on the same page

### PR DESCRIPTION
**Pull request by SidharthBansal**
Part of #2173

### CODE REVIEW

**Comment by SidharthBansal** [comment]
image
Now the likes are on the profile page

**Comment by jywarren** [comment]
Hi @publiclab/reviewers -- could someone take a look at this one and give a 👍 ? Thanks!

**Comment by SidharthBansal** [comment]
@Gauravano I have done the required patch. Can you please review it ?

**Comment by SidharthBansal** [comment]
The screenshots are available in this PR. Can you kindly see top?

**Comment by Gauravano** [comment]
Oops, I missed it.

**Comment by SidharthBansal** [comment]
@jywarren can you kindly review this?

**Comment by jywarren** [comment]
Looks great! Thanks so much, this is really nice :-) 👍

**Pull request merged**
