### PR TITLE
Unicode filenames

### PR DESCRIPTION
**Pull request by jywarren**
Attempting to write a test for #547 

Still needs a solution!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, the error here is:

```
ERROR["test_image_creation_with_unicode_filename", #<Minitest::Reporters::Suite:0x00005654eb1d8e40 @name="ImagesControllerTest">, 63.142930936000084]
 test_image_creation_with_unicode_filename#ImagesControllerTest (63.14s)
RuntimeError:         RuntimeError: /app/test/fixtures/图片17.jpg file does not exist
            test/functional/images_controller_test.rb:47:in `block in <class:ImagesControllerTest>'
```

but we wanted an encoding error... not ready for a fix yet! but the fix would hopefully be as in https://github.com/publiclab/plots2/pull/3007/ --

```ruby
class ChangeImageTableToUtf8mb4 < ActiveRecord::Migration[5.2]
   def change
    # changing table that will store unicode execute:
    execute "ALTER TABLE images CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
    # changing string/text column with unicode content execute:
    execute "ALTER TABLE images MODIFY title VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
     # changing string/text column with unicode content execute:
    execute "ALTER TABLE images MODIFY photo_file_name VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
 end
end
```

**Comment by jywarren** [comment]
Ah -- method `ImagesController#create as JSON

**Comment by jywarren** [comment]
Hmm, still can't reproduce the error! ☹️

**Comment by gauravano** [comment]
The image is stored in the db 

Screenshot from 2019-03-22 22-49-44

So, should we focus on giving a push at https://github.com/publiclab/plots2/pull/3007 @jywarren?

**Comment by jywarren** [comment]
Hm, part of the problem was that we weren't able to reproduce the error we saw on production for any of these encoding bugs. I think we can go ahead with all the merges but we have no easy way to track if the solution was related to our fixes. But, we've been stuck on this for some time... so maybe?

What do you think, should we merge this?

**Comment by gauravano** [comment]
Actually, the screenshot I copied here https://github.com/publiclab/plots2/pull/4118#issuecomment-475706615 was from master and not for this PR. 

What do you think about https://github.com/publiclab/plots2/pull/3007?

**Comment by jywarren** [comment]
😢 yeah, we are stuck because although we can add the db encoding, we can't "catch" the error itself in tests at all. Not sure why this is the case! https://github.com/publiclab/plots2/pull/3007#issuecomment-461898604

Do you think we should just go ahead and do this encoding fix on all tables and just live with the fact that we can't protect it with a test?

**Comment by jywarren** [comment]
Closing in favor of @icarito fixes...

**Pull request closed without merging**
