### PR TITLE
Implementation of Rich profile tags in Publiclab - in progress

### PR DESCRIPTION
**Pull request by lalithr95**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by lalithr95** [comment]
Added rails model UserTag and basic unit tests for model.

**Comment by jywarren** [comment]
This looks great. Do you think you'll be further modifying the user tags table? 

Also, can you test `user.user_tags` as well? 

And, any validations on user tag value?

Are you going to store key and value in the same field, as in community_tags, or are you going to add a key field later?

Thanks!

**Comment by lalithr95** [comment]
Don't merge this PR. I think I will need to change user tags table a little not much. I will write tests for user.user_tags as well. As of now tag value can only contain key:value and : as delimiter. It should be a string. May be we can a regular expression with string:string in tests for value.

Key and value are stored in same field as done in community_tags. If the retrieval is very difficult and leads to performance then we can separate into 2 columns key, value

Thanks !

**Comment by jywarren** [comment]
Perfect, thanks, that's very helpful. And in the future please mark such
"placeholder" PRs with a message at the top not to merge. Thanks, it's
great to see this progress!

**Comment by lalithr95** [comment]
@jywarren here are the screenshots of work above commits
different tags
tags in profile

**Comment by lalithr95** [comment]
For location tag a separate model LocationTag would be optimal solution. As location has many columns lat, long, location, uid. Even if we use a foreign key to UserTag autocomplete and retrival for other tags would be effected.

**Comment by lalithr95** [comment]
@jywarren I need your review for this PR. Tests are passing and ready for merge. 
How can I update development.sqlite.example as there are few migrations ?

Looking forward for your views on PR. I will start a new PR with location functionality 😃

**Comment by ananyo2012** [comment]
With respect to the sqlite database the current development.sqlite.example seems to be buggy as when I tried to used that it was causing an error. It was missing a `status` field in `node_revisions` table. It didn't work even after I tried to run `rake db:migrate`. I simple solution to this was to use the schema.rb.example dile, renaming it to schema.rb to create a fresh database by running `rake db:setup` and them `rake db:migrate ` for the unrun migrations.

**Comment by ananyo2012** [comment]
I think it would be better to version control the schema.rb file instead of everytime updating the database file. The schema file contains the structure of the entire database and doesn't contain the records. It is much better than maintaining a database file since we can't actually see the changes as it is a binary file. Also it contains all the records and needless to say there can be similar errors in the future. Also most of us use the sqlite database in our development and it contains all the records so we can accidentally rename it to development.sqlite.example and commit and we can't keep track    of what is actually changed.

@jywarren I can open a issue for this if you suggest.

**Comment by lalithr95** [comment]
@ananyo2012 Thanks for the information. Renaming schema.rb works but we have to rename file, create fresh database. A rake task which automates this task can be another alternative.

**Comment by ananyo2012** [comment]
@lalithr95 What I mean we can create we can version control the schema.rb file and delete the current schema.rb.example file.Then every time some new migrations are made we can push the updated schema.rb too.

**Comment by jywarren** [comment]
Hi, all - good thoughts here. The intent of the updated database file is that new developers just joining in will be able to start with a clean database with as little hassle as possible, as in the [install instructions](https://github.com/publiclab/plots2#installation). 

> Renaming schema.rb works but we have to rename file, create fresh database. A rake task which automates this task can be another alternative.

I like the idea of a rake task to generate the clean example database, and whatever up to date schema.rb.example file necessary. I would appreciate a new issue/PR for this. Can you confirm that this PR has both an up-to-date schema.rb.example and development.sqlite.example so that new contributors can get started without trouble?

**Comment by lalithr95** [comment]
@ananyo2012 Got your point nice idea 👍 

@jywarren I updated schema.rb.example file in last commit. I use a mysql in my development, test environments. I will have a look into approach for rake task. How can I update development.sqlite.example ?

Thanks !

**Comment by jywarren** [comment]
You need to switch your development database to sqlite, at least temporarily, and run rake db:migrate.

**Comment by lalithr95** [comment]
@jywarren Thanks updated. Ready for merge 👍

**Comment by jywarren** [comment]
This looks great. I'm going to hide the new functionality under a `?preview=true` flag, and add a button to "activate" it. But not actually turn any functionality off. 

I think we need:

* [ ] some text to explain what this is for (@ebarry and @steviepubliclab - can you help Lalith with this?)
  * both for the profile page itself
  * and for the "edit profile tags" page, so that people have a better idea of what this interface helps you do
* [ ] when i added "organizer" to "roles" i got: `jquery.js?body=1:9632 POST http://localhost:3000/info/suggested/role/organiz 500 (Internal Server Error)`

However, all tests pass, so I'm going to merge this, so followup changes can be on top of it. 

Lalith, can you open a new issue and mention @ebarry and @steviepubliclab and ask for input on the textual content for these two interfaces, and include these screenshots? Thanks!

They currently look like this:

screenshot 2016-06-07 at 12 24 28 pm
screenshot 2016-06-07 at 12 24 17 pm

**Comment by jywarren** [comment]
* [ ] I also think we need to consider validation. Can you try some functional tests of entering odd tags like "
* [ ] Finally, `app/views/users/_tags_form.html.erb` has inline javascript -- can you break that out into `app/assets/javascripts/user_tags.js` and include it with an irb script tag? 

One note -- to make a whole file for `app/views/user_tags/delete.js.erb` seems a bit much. I think this could be done in a more compact constructor in the relevant page, as here: https://github.com/publiclab/spectral-workbench/blob/master/app/views/spectrums/show2.html.erb#L18-L38

That way the bulk of the JS is in its own file, but the needed variables like `id` are passed in a compact manner. I'm still going to merge this, but can you consider this in your next pull request? Thank you!

**Comment by jywarren** [comment]
Once you've moved the checklists I created into new issues, please close this one; the code is merged. Thanks again, this is a lot of good work and it's great to see it merged!

**Comment by lalithr95** [comment]
@jywarren I made the changes and improvements in #576 and also created an issue for content #571 
Thanks !

**Pull request merged**
