### PR TITLE
Solve Don't search for " " (spacebar character) in navbar typeahead s…

### LINKED ISSUE #3409: Don't search for " " (spacebar character) in navbar typeahead search
### Please describe the problem (or idea)
In header there is search, It's searching also space which is not good.
search

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
first char in search cann't be space

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?
999_avsingh999
> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome ubuntu 16
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by avsingh999**
…earch
Fixed #3409 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #3409`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by avsingh999** [comment]
@jywarren  Please review

**Comment by avsingh999** [comment]
@publiclab/reviewers Please review

**Comment by jywarren** [comment]
Wow, interesting! Could you attach a screenshot (or even a gif) to help us see how this works?

**Comment by avsingh999** [comment]
when I type first char space


scrren4


when type text


screend5

**Comment by igniteeng000** [comment]
I think you must use bootstrap alert in place of this.

**Comment by avsingh999** [comment]
But I was thinking I should remove alert because there is no need to show to alert this is only blocking the space char.

**Comment by igniteeng000** [comment]
Remove the alert.

**Comment by stefannibrasil** [comment]
hello! is it possible to move that code to the typeahead script on the assets/javascripts folder instead of placing it on the view? And add that to the searchform script on the same folder? They both do the same thing but in different places right now. I don't know if that would be much work or anything, just wondering. thanks!

**Comment by avsingh999** [comment]
remove alert

**Comment by avsingh999** [comment]
@jywarren @stefannibrasil  Now Please check it

**Comment by igniteeng000** [comment]
@avsingh999 Please squash your commits.

**Comment by avsingh999** [comment]
@jywarren  merge it

**Comment by SidharthBansal** [comment]
@avsingh999 as per @jywarren suggestion I am closing this PR, in case you want to reopen it feel free to reopen it

**Pull request closed without merging**
