### PR TITLE
Enable UI Part for Browser  Notification

### LINKED ISSUE #6039: Add Notification Enabling UI part
Add Notification Enabling UI part same as we have for Email. Let's first discuss what are the possible types which we can add.
- notifications:all
- notification:like
- notification:mentioned
Any more suggesstion @jywarren ?

### PR DESCRIPTION
**Pull request by namangupta01**
Closes #6039

### CODE REVIEW

**Comment by namangupta01** [comment]
Restarted Build

**Comment by namangupta01** [comment]
@jywarren lets gets this merge.

**Comment by jywarren** [comment]
Looks awesome. Can you upload a gif, and would you mind adding this page to the auto-screenshot system tests so we can see that page too? Thank you!!!

**Comment by namangupta01** [comment]
Yeah sure! Will do it.

**Comment by namangupta01** [comment]
ezgif com-video-to-gif

**Comment by namangupta01** [comment]
Adding this in system test screenshot as well.

**Comment by namangupta01** [comment]
Added auto screenshot system test for the settings page.

**Comment by namangupta01** [comment]
Restarting Build.

**Comment by namangupta01** [comment]
Finally test passed. Can we merge this? @jywarren

**Comment by jywarren** [comment]
Awesome!!! Great work!

**Comment by jywarren** [comment]
This seems to be working for `@warren` notifications on stable! Just tested! However I got 2 duplicate notifications. Can we catch that? 

image

Let's open a new issue to track that!

Also, I didn't seem to get `Do you want to receive browser notification for all ?` as I tried leaving a few comments at https://stable.publiclab.org/questions/mimiss/08-05-2019/testing-a-question but only the one with the @ actually triggered it.

**Comment by namangupta01** [comment]
Yeah! it is currently working for mentioned username, I will add it to all the rest cases. It won't be much work since I only have to add just one line of code in every case. Will add it today. Thanks

**Comment by jywarren** [comment]
Awesome. Great!

**Pull request merged**
