### PR TITLE
horizontal cards for people section

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes https://github.com/publiclab/plots2/issues/5707 part 

#### User Desktop
Screenshot from 2019-05-19 17-43-02

#### User mobile
Screenshot from 2019-05-19 17-44-23

#### Admin Desktop
Screenshot from 2019-05-19 17-58-25

#### Admin Mobile
Screenshot from 2019-05-19 17-58-52

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @jywarren @gauravano @gautamig54 
Now that as we are beginning the work.
I started off with changing the people section user cards to horizontal.

**Comment by CleverFool77** [comment]
The failing test of dashboard doesn't seem to be related to this. I guess.
Thanks !!!!

**Comment by CleverFool77** [comment]
The failing test of dashboard doesn't seem to be related to this. I guess.
Thanks !!!!

**Comment by sagarpreet-chadha** [comment]
Agreed the failing test is not changes due to this PR . Lets start the build again on this PR .

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren , 
How can we see the screenshot `tmp/screenshots/test_viewing_the_dashboard.png` ?  
PS : After reopening the PR , now there are 2 system tests failing instead of 1 initially .

**Comment by CleverFool77** [comment]
> The changes are great  !!!
> Do you think we should update/remove the CSS of `/peopleleaflet` here ?
> https://github.com/publiclab/plots2/blob/ddf92c982a8eea4f15e8aef3ac190bf1b94d17cd/app/views/map/_peopleLeaflet.html.erb#L5

Hi @sagarpreet-chadha 
May I know what change you are mentioning about ? 
If it's about width and height , then they are required. 
Maybe we can look into the matter of margin ,position and remove it.
Thanks !!!

**Comment by sagarpreet-chadha** [comment]
Just noting a couple of things :

1. When we scroll-down , should the map also move downwards ? I think we have plenty of space in that column to do that , currently it kinds of feel like lots of empty space . 

2. In mobile view , i think the map should come at the top (currently it goes at the bottom , right ?) . 

I would love to hear your thoughts @CleverFool77 , @jywarren .

**Comment by jywarren** [comment]
This looks great! We can address some of these other items in follow-up,
and we'll want to reconcile this page design with the new style guide, but
that'll be a process. Re: mobile view map at top, though, yeah that makes
sense! That can be part of this, or another PR, either way is fine!

We are tracking the timing failures in system tests here:
https://github.com/publiclab/plots2/issues/5683 -- it's pretty bad, we're
looking for a solution!

**Comment by CleverFool77** [comment]
Hi @jywarren @sagarpreet-chadha I'll fix the map position and other features in next PR.
For now, Is there any other changes required in this PR?
Thanks!!

**Comment by gautamig54** [comment]
This looks great @CleverFool77. 
Regarding making the map sticky and positioning it on top in mobile view, I'll add them to the checklist and implement them in the next PR. Thanks!

**Comment by gautamig54** [comment]
I would like to mention one thing, as per the design, there is a decrease in the left and right margin of the people's page, due which the width of the cards has be increased, resulting in a cleaner card. 
What do you think about this @jywarren @CleverFool77 ?

**Comment by CleverFool77** [comment]
Hi @gautamig54 regarding side margins you are talking about. I guess it's being followed everywhere in new design due to bootstrap4 container. You can notice it in every page whether it's dashboard or other. 
Thanks !!!

**Comment by CleverFool77** [comment]
Just Fixed map margins and Updated the PR:
Screenshot from 2019-05-21 16-30-09

**Comment by jywarren** [comment]
I think this looks great! Shall we merge it for now? Thanks!!!

**Comment by gautamig54** [comment]
It looks great @CleverFool77. 
This is ready to be merged @jywarren 
Thanks!

**Comment by CleverFool77** [comment]
yes @jywarren It's ready for merge.
Thanks !!!
cc : @gautamig54

**Comment by gautamig54** [comment]
I am ready with adding "add your location" button. Since, you have fixed map margins, I will push a PR,  when this PR gets merged.

**Comment by jywarren** [comment]
Awesome!!!

**Pull request merged**
