### PR TITLE
Debugged Development Error for OAuth

### LINKED ISSUE #2856: Create Github OAuth App
Github settings as given on https://www.natashatherobot.com/rails-omniauth-github-tutorial/ are functional as tested in test app.
image
image
image
We need to verify that the following will work properly for all users:
* [ ] localhost:3000/auth/github
* [ ] localhost:3001/auth/github
* [x] unstable.publiclab.org/auth/github
* [x] stable.publiclab.org/auth/github
* [x] publiclab.org/auth/github

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes #2856 concerns discussed about localhost:30000
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by SidharthBansal** [comment]
I have made the buttons for the providers only available to the production. This will prevent the new developers to sign in via providers and get errors.
Also, I have added the documentation for inserting the client id and secret.

**Comment by jywarren** [comment]
I think this looks great. Is it ready for a merge?

**Comment by SidharthBansal** [comment]
Yes. I will be working on font awesome icons for github now. 
Thanks

**Comment by jywarren** [comment]
Awesome!

**Comment by jywarren** [comment]
Font Awesome! 😆

**Pull request merged**
