### PR TITLE
Feature lead image and first paragraph of text from a wiki page on the corresponding tag index page (resolves #973)

### LINKED ISSUE #973: Feature lead image and first paragraph of text from a wiki page on the corresponding tag index page
We have great tag-based listing pages, such as:

https://publiclab.org/tag/balloon-mapping
https://publiclab.org/tag/spectrometry

However, they just kind of dump a bunch of recent content from the site onto the page, without much context. But many of these tag names have a corresponding top-level wiki page; for example:

https://publiclab.org/wiki/balloon-mapping
https://publiclab.org/wiki/spectrometry

If, for a given tag listing page, like https://publiclab.org/tag/balloon-mapping, there's a matching wiki page, we should feature the lead image, and the first paragraph of content from that page, at the top of the tags listing, above the graph. 

I think if we showed two columns, with the image to the left and the title and first paragraph to the right, we could do this without sacrificing too much of the page space:

```           
[ image ] [ title          ]
          [ 1st paragraph ]
=====================
[ item ] [ item ] [ item ] [ item ]
[ item ] [ item ] [ item ] [ item ]
```

We could find the wiki page by checking if there's a DrupalNode with the appropriate path: 

```ruby
# controller code:
@wiki = DrupalNode.where(path: "/wiki/#{tagname}"
```

And, though this is just roughly sketched out,  could then use this `@wiki` instance variable to display the relevant content on the tag show page (on this page just before the graph code: https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L4).

(as a first step, you could just show the image and title, since the first-paragraph code may be a bit more complex)

```ruby
<!-- view code: -->
<% if @wiki %>
  <!-- some HTML layout code -->
  <%= @wiki.main_image.path if @wiki.main_image %>
  <!-- some HTML layout code -->
  <%= @wiki.latest.title %>
  <!-- some HTML layout code -->
  <%= @wiki.latest.render_body.split('\n').first %>
<% end %>
```

A functional test for this would also be a good independent task; for example, it could copy this test and adapt it to work with a tagname for which we have test fixture data for a matching wiki page: https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb#L85-L100

### PR DESCRIPTION
**Pull request by ryzokuken**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

Preview: 
screenshot_2016-11-14_19-27-29

### CODE REVIEW

**Comment by ryzokuken** [comment]
@jywarren Please look into this one when free, I made a simple 1:2 grid for the image and content, which shows up for medium and larger screen sizes. (On smaller screens like phones, the layout will fallback to a single-column one)

**Comment by ryzokuken** [comment]
Resolves #973

**Comment by jywarren** [comment]
Oh this looks great  -- could you move the new area to the very top, as I think that might make more sense? And what happens when there is no wiki page, do you think we should add a test for that?

Finally, the title should be a link to the wiki page if it isn't already, and perhaps a "Read more" link below the paragraph would help people realize there's more content there?

Thanks, this looks fantastic. I should be able to plug back in and review other submissions too today.

**Comment by ryzokuken** [comment]
1) I'd move the content to the VERY top, no problems with that (Now I do come to realize that It'd make more sense)

2) Nothing shows up if there's not a corresponding wiki page (it would look just like it looks right now I suppose)

3) What would the "Read More" link point to? Some clever DOM manipulation that makes the rest of the content appear, perhaps?

**Comment by jywarren** [comment]
I think read more could go to the page itself, so in your example, /wiki/stats

Thanks!!

**Comment by ryzokuken** [comment]
But the link at the title points to the wiki page as well?

**Comment by jywarren** [comment]
Just in case people don't realize the title is a link. Thanks!

**Comment by ryzokuken** [comment]
`<%= link_to("Read More", "/wiki/#{params[:id]}") if @wiki.latest.render_body.split('\n').length > 1 %>`

Sounds good?

**Comment by jywarren** [comment]
Hmm, so this only shows if there's more than one paragraph? I think we can
safely assume there will more than one paragraph, no? But yes, this looks
fine.

**Comment by ryzokuken** [comment]
I personally think displaying a "Read More" wouldn't really have a point unless there's really something *more to read*. I could remove it though.

**Comment by ryzokuken** [comment]
Actually, there was something wrong with your code. As you did a `render_body`, there weren't any `\n`s anymore, rather content inside `<p></p>` tags, so `split('\n')` does not really do anything anyway and `<%= @wiki.latest.render_body.split('\n').first.html_safe %>` displays the entire content, not just the first paragraph.

**Comment by ryzokuken** [comment]
@jywarren Finalized the PR. Please look into it and tell me if there's something I missed.

**Comment by ryzokuken** [comment]
@jywarren The checks passed. Could you look into this one?

**Comment by jywarren** [comment]
Hi, just one more q: what happened to the graph, is it still there, above?

Thanks!

**Comment by jywarren** [comment]
Hi, I'd like to suggest we add a couple very brief tests to ensure this continues to work; similarly to this test:

https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb#L85-L100

We should not expect a featured post at the top of this page, so you could assert absence, with (i think):

```ruby
        assert_select "#featured-post", 0 # zero matches
```

And a copy of that using a node which /does/ have a matching wiki page, like, say, `/wiki/organizers` -- 

https://github.com/publiclab/plots2/blob/master/test/fixtures/node.yml#L49

So:

```ruby

  test "should have active Research tab for notes" do
    tag = tags(:test)

    get :show, id: node(:organizers).slug

    assert_select '#featured-page', 1
  end
```

Both of these changes would rely on a `<div id="featured-page">...</div>` around the featured content, starting on this line: https://github.com/publiclab/plots2/pull/985/files#diff-6455ffb69b78f14dca36ebdfe953d97dR39

Make sense? This kind of thing will also ensure that nobody in the future accidentally breaks the work you've done here, so it's well worth it. 

Thanks!!

**Comment by ryzokuken** [comment]
@jywarren Yes, the tests do make sense and I'd make sure to add them. 

Concerning the graph, I had been using a tag which didn't really existed (no posts tagged with it) but having a corresponding wiki page (So it didn't show a graph back then). Actually creating a research note revealed that the wiki content showed up **after** the graph. Should I move it above?

Thanks. 

Also, if I wanted to privately have a word with you, was there a way to do that?

**Comment by jywarren** [comment]
Yes - perhaps the graph could go below the wiki content, that's good.

Yes, you can contact me via jeff@publiclab.org.

Thank you for your hard work in this issue, people are excited about it!

We are still just coming out of the Barnraising event and I was able to
show your latest contributions to others there, and we're looking forward
to publishing it!

On Nov 16, 2016 9:31 AM, "Ujjwal Sharma" <notifications@github.com> wrote:

@jywarren <https://github.com/jywarren> Yes, the tests do make sense and
I'd make sure to add them.

Concerning the graph, I had been using a tag which didn't really existed
(no posts tagged with it) but having a corresponding wiki page (So it
didn't show a graph back then). Actually creating a research note revealed
that the wiki content showed up *after* the graph. Should I move it above?

Thanks.

Also, if I wanted to privately have a word with you, was there a way to do
that?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/pull/985#issuecomment-260961169>, or mute
the thread

**Comment by ryzokuken** [comment]
Done. Just give me a little more specifics over the tests and I'll add those too.

**Comment by jywarren** [comment]
Super. I think for tests it's just adding an assertion that the existing test here does not show the wiki div:

https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb#L85-L100

Then make a copy of it for the "organizers" tag which has a wiki page equivalent, and change the assertion to check that the wiki div **does** exist. Make sense? Thanks!

**Comment by ryzokuken** [comment]
@jywarren Did try making appropriate changes. Let's see if the tests pass.

**Comment by ryzokuken** [comment]
@jywarren Aww. Although I did spot almost instantly what was wrong. Will fix that in a minute.

**Comment by ryzokuken** [comment]
@jywarren All tests passed this time! :tada: Could you take the time to review the changes I've made?

**Comment by jywarren** [comment]
Thanks, this is great!!! 🎉🎉

**Pull request merged**
