### PR TITLE
Translation prompt improvement

### LINKED ISSUE #5651: Translation prompt improvement
Currently, we show Translation prompts on /subscriptions page, some on /dashboard and /blog page. 

Conditions for translation prompt:
1. translated_string.length > 3 - If translated string has length greater than 3 
2. current_user &.has_tag('translation-helper') - User has tag `translation-helper` on their profile
3. !translated_string.include?("translation missing") - There shouldn't be "translation missing" in the translated_string. This effectively means we show translation prompt only in case where translation is present.

The condition 3 is buggy or I would say totally wrong. Why? Because, previously we were running only 3 langs and in those while testing I got a span with translation missing, something like `"<span class=\"translation_missing\" title=\"translation missing: ru.home.subscriptions.notes, fallback: false\">Notes</span>"` but this would be returned when the translation key is not found in any locale yes, not in en.yml too but in all other cases we would get something i.e., either a translated value in the Russian. japan, etc or a English string because we fallback to English.

Let's say, we want to show prompt only in case a translation is missing in the language we are browsing publiclab.org 

then, it would be something like:

Subscription page in English:

eng_as_lang
 
Subscription page in Russian:

russian_as_a_lang

So, you can see so many prompts because we have less Russian translations. So, what should be the conditions in which prompt should be visible?

Bugs to solve: currently, we directly wrap the returned translation in the span(prompt is made using span element), but we don't get string always in translated value some times it is code too and in those cases, :boom: :point_down: :sweat_smile: 

bug

Let's collect ideas and issues about improving translation prompts here. Thanks!

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #5651 #5749 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
If code is returned from translation, prompt not shown as per https://github.com/publiclab/plots2/issues/5651#issuecomment-488789810

Screenshot from 2019-05-19 02-50-19

Page in Spanish -- prompts shown as translations missing
Screenshot from 2019-05-19 02-51-47

Page in English -- Prompts not shown as translation are there 
Screenshot from 2019-05-19 02-51-33

**Comment by jywarren** [comment]
Aha you're way ahead of me! Awesome. Will try to get the test to pass.

**Comment by gauravano** [comment]
Hey @jywarren, you just restarted the test and it passed? But, why it errored in initial builds? :confused:

**Comment by jywarren** [comment]
This is related to the issues in #5683 -- but should be good now? Let's merge!

**Comment by gauravano** [comment]
Done!!

**Comment by gauravano** [comment]
@jywarren let me know when you push it to production as after that we can add more languages to the footer :smiley:

**Pull request merged**
