### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jscastanos**
Added `Windows Subsystem for linux` option for windows user and marked it as recommended. 

Fixes N/A (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jscastanos** [comment]
@publiclab/reviewers please review changes.

**Comment by cesswairimu** [comment]
Splendid @jscastanos :tada: :tada:  great job finding that great documentation and opening this PR 
 Thanks :rocket: 

Thanks also @Uzay-G @VladimirMikulic and @govindgoel  for the reviews :tada: :tada:

**Comment by jscastanos** [comment]
@cesswairimu There's still a problem with `passenger` in WSL1, so I'm planning on creating a full windows installation guide once the WSL2 will publicly release.

**Comment by cesswairimu** [comment]
Great :+1: maybe we can add a recommendation for Windows folks to use puma in development for the time being?

**Comment by jscastanos** [comment]
@cesswairimu I'm not familiar with `puma` but if it works then that would be useful.

**Pull request merged**
