### PR TITLE
bulk moderation-sample

### LINKED ISSUE #7440: Batch first time posters on spam page.
Hi all, 
I've been having an issue with spam moderation this week where first time posters are posting multiple times from the same account and continuing to be held in moderation. So far, these have all been spam accounts. Wondering if there is a way to batch posts together from new users until they go through moderation instead of needing to mark each post as spam from the wiki page: https://publiclab.org/spam

Here's an example, same post, same account, multiple entries to mark as spam from the webpage: 
Screen Shot 2020-02-05 at 9 27 53 AM

### PR DESCRIPTION
**Pull request by keshavsethi**
Fixes #7440 
Here, I tried to implement bulk moderation feature. Moderator can search any word and can sort of comments and posts as shown below. This will help in bulk moderation and faster approvals.
Screenshot from 2020-02-11 00-28-16
Screenshot from 2020-02-11 00-28-08
Screenshot from 2020-02-11 00-27-57
This code has some issues which will take some time.

@SidharthBansal @nstjean @cesswairimu @steviepubliclab @jywarren @Uzay-G 
 Should I continue with this??

Thanks!

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
It would be useful to have functionality like "Publish all posts" or "Publish selected posts". We could apply this principle to other functionalities as well (banning user, marking posts as spam...).

**Comment by sssash18** [comment]
@keshavsethi  Could you please describe about what will be the need for the moderator to search for a particular spam from a list of all spams. Moderator in my opinion would not search for a particular spam to ban it or publish it .What are your views @VladimirMikulic ?

**Comment by VladimirMikulic** [comment]
We could have search functionality or some filters. In my opinion they are useful.
@steviepubliclab is this something that you would like to have as an admin?

**Comment by keshavsethi** [comment]
@sssash18 As mentioned in Issue #7440, @steviepubliclab wants to batch all first time posters But I think that rather than going for grouping them we can make a search option, where moderator can just search first time posts or something and then by clicking on select all moderator can approve or reject them. It can be used in other areas of bulk moderation as well like suppose a spam ID is posting something and there are n number of comments by that ID then rather than scrolling and finding comments moderator can  just search for spam profile and ban or hide that comment in one go.

**Comment by keshavsethi** [comment]
@VladimirMikulic @SidharthBansal @jywarren can you please give review on this?

**Comment by VladimirMikulic** [comment]
@keshavsethi as I said, this idea makes sense. Let's just wait what others say, maybe you'll have to implement the additional changes.

**Comment by cesswairimu** [comment]
Hi @keshavsethi thanks for opening this...could you please rebase this to resolve the conflicts

**Comment by SidharthBansal** [comment]
@keshavsethi kindly rebase

**Comment by cesswairimu** [comment]
@keshavsethi did you include this in the new project or do we still require this? if so, kindly rebase when you get some time., Thanks

**Comment by cesswairimu** [comment]
This PR has been open for a long time and no activity/ reviews requested has not been addressed. We understand you might be busy and engaged on other things. I am closing this for now...please  feel free to reopen if you get some time and would like to finish this. Rem to check if its still available before you reopen. Thanks

**Pull request closed without merging**
