### PR TITLE
Footer I18n with custom translation missing exception

### PR DESCRIPTION
**Pull request by jiteshjha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer
* [ ] `development.sqlite.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

---

Update : Added tests.

### CODE REVIEW

**Comment by jiteshjha** [comment]
@ebarry @jywarren

**Comment by jywarren** [comment]
Hi, thanks -- I'm going to review and merge tomorrow -- thanks! If you can rebase over master in the meantime that'd be great, but it's not a big deal either way. Thanks again!

**Comment by jywarren** [comment]
Excellent -- rebased and merged manually! Thanks, it looks super and I much appreciate the tests.

**Comment by jywarren** [comment]
@ebarry - you can test this once it publishes (probably tomorrow?) by adding `?locale=de` to the end of a URL, and looking at the footer. However, note that we don't yet have any translations for the footer.

**Comment by jiteshjha** [comment]
Thanks, Jeff!

**Pull request closed without merging**
