### PR TITLE
Re-order comment options and messages

### LINKED ISSUE #2833: Updating comment options order
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/notes/_comment.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -23,26 +23,6 @@
       <% end %>
     </div>
 
-      <div class="hidden-print btn-toolbar pull-right" style="margin-left:10px;">
-        <ul class="btn-group" style="margin-top: 16px; margin-right: 16px;">
-          <% if !current_user %>
-            <li rel="tooltip" title="Helpful? Like it and get updates!" class="btn btn-default btn-sm btn-like">
-            <%= link_to  new_user_session_path( return_to: request.path ), style: "text-decoration: none; color: black;" do %>
-              <span class="fa fa-star-o"></span>
-              <span><%= comment.likers.count %></span>
-            <% end %>
-          <% else %>
-            <% str = "/comment/like?comment_id=#{comment.cid}&user_id=#{current_user.uid}" %>
-            <li rel="tooltip" title="Helpful? Like it and get updates!" class="btn btn-default btn-sm btn-like">
-            <%= link_to str, data: { method: "post", remote: true }, style: "text-decoration: none; color: black;" do %>
-              <span id="comment-like-star-<%= comment.cid %>-<%= current_user.uid %>" class="fa fa-star<% if !comment.liked_by(current_user.uid) %>-o<% end %>"></span>
-              <span id="comment-like-count-<%= comment.cid %>-<%= current_user.uid %>"><%= comment.likers.count %></span>                
-            <% end %>
-          <% end %>
-          </li>
-        </ul>
-      </div>
-
     <div class="navbar-text navbar-right pull-right" style="padding-right:10px;">
       <% if comment.author && comment.author.user && comment.author.user.role %>
       <!-- Role icon for admins & moderators
@@ -54,18 +34,35 @@
       -->
       <% end %>
 
-      <a rel="tooltip" title="Flag as spam" class="btn btn-sm btn-default btn-flag-spam-<%= comment.id %>" href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+Lab&body=Hi,+I+found+this+comment+that+looks+like+spam+or+needs+to+be+moderated:+https://publiclab.org/<%= comment.parent.path %>#c<%= comment.cid %>+by+https://publiclab.org/profile/<% if comment.author %><%= comment.author.name %><% end %>+Thanks!">
-        <i class="fa fa-flag"></i>
-      </a>
-      <% if comment.comment_via == 1 %>
-        <a href="#" onclick="return false;" class="btn btn-default btn-sm"><i class="fa fa-envelope"></i></a>
-      <% end %>
+        <ul class="btn-group" style="margin-top: 10px;">
+          <% if !current_user %>
+              <li rel="tooltip" title="Helpful? Like it and get updates!" class="btn btn-default btn-sm btn-like">
+                <%= link_to  new_user_session_path( return_to: request.path ), style: "text-decoration: none; color: black;" do %>
+                    <span class="fa fa-star-o"></span>
+                    <span><%= comment.likers.count %></span>
+                <% end %>
+          <% else %>
+              <% str = "/comment/like?comment_id=#{comment.cid}&user_id=#{current_user.uid}" %>
+              <li rel="tooltip" title="Helpful? Like it and get updates!" class="btn btn-default btn-sm btn-like">
+                <%= link_to str, data: { method: "post", remote: true }, style: "text-decoration: none; color: black;" do %>
+                    <span id="comment-like-star-<%= comment.cid %>-<%= current_user.uid %>" class="fa fa-star<% if !comment.liked_by(current_user.uid) %>-o<% end %>"></span>
+                    <span id="comment-like-count-<%= comment.cid %>-<%= current_user.uid %>"><%= comment.likers.count %></span>
+                <% end %>
+          <% end %>
+          </li>
+        </ul>
 
       <% if current_user && comment.uid == current_user.uid %>
-        <a class="btn btn-default btn-sm" href="javascript:void(0)" onClick="$('#c<%= comment.cid %>edit').toggle();$('#c<%= comment.cid %>show').toggle();setInit(<%= comment.cid %>);">
-          <i class="fa fa-pencil"></i>
-        </a>
+          <a class="btn btn-default btn-sm" href="javascript:void(0)" onClick="$('#c<%= comment.cid %>edit').toggle();$('#c<%= comment.cid %>show').toggle();setInit(<%= comment.cid %>);">
+            <i class="fa fa-pencil"></i>
+          </a>
       <% end %>
+      <% if comment.comment_via == 1 %>
+          <a href="#" onclick="return false;" class="btn btn-default btn-sm"><i class="fa fa-envelope"></i></a>
+      <% end %>
+      <a rel="tooltip" title="Flag as spam" class="btn btn-sm btn-default btn-flag-spam-<%= comment.id %>" href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+Lab&body=Hi,+I+found+this+comment+that+looks+like+spam+or+needs+to+be+moderated:+https://publiclab.org/<%= comment.parent.path %>#c<%= comment.cid %>+by+https://publiclab.org/profile/<% if comment.author %><%= comment.author.name %><% end %>+Thanks!">
+        <i class="fa fa-flag"></i>
+      </a>
       <% if current_user && (current_user.role == "admin" || current_user.role == "moderator" || comment.uid == current_user.uid || comment.parent.uid == current_user.uid) %>
         <a data-remote="true" data-confirm="<%= t('notes._comment.are_you_sure') %> <% if current_user && comment.uid != current_user.uid %><%= t('notes._comment.please_exercise_caution') %><% end %>" href="/comment/delete/<%= comment.cid %>" class="btn btn-default btn-sm" id="c<%= comment.cid %>delete-btn">
           <i class='icon fa fa-trash'></i>
```

#### The comment would look something like this after the changes:
 
res_comment

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by Neidley**
Fixes #2833 (@Neidley This will close the corresponding issue automatically, once this is merged. Also, you can give title of PR to be descriptive.)

Requested changes have been made to app/views/notes/_comment.html.erb

### CODE REVIEW

**Comment by Gauravano** [comment]
@Neidley changes look good! Could you please attach a screenshot of the updated view? Thanks.

**Comment by Neidley** [comment]
Having some issues running `bundle install --without production mysql` in the terminal is returning `-bash: bundle: command not found` via the README.md > Installation instructions. Is there a better/easier way for me to obtain the screenshot of the updated view?

**Comment by Gauravano** [comment]
Hmm, That's strange! Is bundler installed on your device?

**Comment by Neidley** [comment]
Hey was busy last few hours. Just got past that previous error and am installing dependencies now.

**Comment by Gauravano** [comment]
Hi, @Neidley as the changes in `views/notes/_comment.html.erb` are verified by your PR #2836 image, let's merge this one, so you don't have to go through the troubles of excluding file in #2836. So, you can close #2836 . Thanks.

**Comment by jywarren** [comment]
And adding screenshot for reference!

image

**Comment by jywarren** [comment]
Looks great, thank you!!!! 👍 👍 

Much appreciated and we'd love a chance to work with you more!

**Pull request merged**
