### PR TITLE
Fixed first part of Issue #2352 Sorting headers added in wiki index page

### PR DESCRIPTION
**Pull request by sukhbir-singh**
Fixes first part of Issue #2352 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

save

### CODE REVIEW

**Comment by Gauravano** [comment]
hi @sukhbir-singh ,how about changing icon to   
sorticon

What you think @jywarren, is icon in above image fine for our purpose?

**Comment by sukhbir-singh** [comment]
Yeah I think the icon is good enough for its purpose. What do you suggest @jywarren ??

**Comment by jywarren** [comment]
Oops, I missed this! That's a perfect icon. Great find!

**Comment by SidharthBansal** [comment]
I also think. It is good to have this icon

**Comment by sukhbir-singh** [comment]
@jywarren Please review this PR.  I have now replaced standard header icon with the one @Gauravano suggested :smiley:

**Comment by ebarry** [comment]
Also very excited about this one!!!

**Pull request merged**
