### PR TITLE
Add modal for ask question on wikis page

### LINKED ISSUE #4230: Link Login Modal to Ask a Question on Wikis
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to request an activity (The primary button here). For modularity, this is separate from linking the "help answer questions" link.
image

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #4230 

Ask Question Basic Flow:
askquestionbasic

Ask Question Alternate Flow:
askquestionalternate

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kevinzluo** [comment]
@SidharthBansal Could you take a look and add the issue (#4230) to the GCI dashboard?
Thanks!

**Comment by SidharthBansal** [comment]
Please take this task on gci so that @publiclab/mentors can reward you on this.

**Comment by kevinzluo** [comment]
@SidharthBansal I can't seem to find the task. Could you give me a link? Thanks.

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/6462885212454912/
Will approve it right now.
Sorry, I was having lunch that time.

**Comment by kevinzluo** [comment]
No problem, and thank you! I am awake now 😄

**Comment by jywarren** [comment]
This is perfect!!!

**Comment by kevinzluo** [comment]
Redone in #4403 with new changes.

**Comment by SidharthBansal** [comment]
Oh thanks.

**Pull request merged**
