### PR TITLE
Drop DrupalUsers "users" table

### PR DESCRIPTION
**Pull request by jywarren**
Follow-up to https://github.com/publiclab/plots2/pull/2857 once we confirm we have a backup and all is running smoothly.

### CODE REVIEW

**Comment by gauravano** [comment]
@jywarren can we complete this now or we still need some more time? Thanks!

**Comment by jywarren** [comment]
I think we can... it's been pretty good, no? What do you think?

**Comment by gauravano** [comment]
@jywarren I agree on dropping table as we haven't faced any issue from a while.

**Comment by jywarren** [comment]
OK, this should be good if it passes!

**Comment by alonpeer** [comment]
@jywarren this PR causes a `db:migrate` error on master, because it's looking for a class named `RemoveDrupalUsers` (due to the file name), but the class is called `DropDrupalUsers`.
It can be fixed just by renaming the class.

**Comment by gauravano** [comment]
@alonpeer interested in raising a PR?

**Comment by alonpeer** [comment]
I would, but I'm pretty busy in the coming days so not sure I'll get around to doing that soon. If this can wait a bit, I'll be happy to do so.

**Comment by gauravano** [comment]
Actually, I will fix it as this might trouble other contributors. Thanks @alonpeer for reporting :+1:

**Comment by gauravano** [comment]
I've raised the fix at https://github.com/publiclab/plots2/pull/5330. Can you review it @alonpeer? Thanks!

**Pull request merged**
