### PR TITLE
[WIP]Sorting in subscription digest

### LINKED ISSUE #7390: Sorting does not work in digest
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Sorting doe not work in digest
**Current Behaviour**
sorting

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by gauravahlawat81**
Fixes #7390  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

This is a PR in progress, I will be adding tests also for the changes I have made till now are approved. Thanks!

### CODE REVIEW

**Comment by gauravahlawat81** [comment]
@cesswairimu , can you please review this. According to my limited knowledge of rails, we should prefer `order` over `sort_by`, so I have tried to use that in this PR. Let me know if these changes make any sense or any changes that I need to make here. Thanks!

**Comment by coder645** [comment]
@gauravahlawat81 you have taken most of the code from @sssash18 PR https://github.com/publiclab/plots2/pull/7481
It would be great if you could give @sssash18  credit by mentioning the original author's name in your first comment. Let's make this community a wonderful one by crediting original authors.
Cheers!

**Comment by cesswairimu** [comment]
rebuilding

**Comment by cesswairimu** [comment]
Hi @gauravahlawat81 the changes looks superb!! :tada:  :tada: 
I have pushed a commit to  solve the failing test...once your are back you could solve the code climate issues then we are good to merge...Thanks a bunch and fantastic work  :rocket:

**Comment by gauravahlawat81** [comment]
@cesswairimu thanks for solving the failing tests. I have also tried to solve most of Code climate issues. Please review it again, thanks :smile:

**Comment by cesswairimu** [comment]
Looks good ... I will try to find a way to solve the remaining code climate issue and open a fto for it...thanks

**Review by cesswairimu — APPROVED** [review]
:tada: :tada:

**Comment by gauravahlawat81** [comment]
Thank you so much @cesswairimu :tada:

**Pull request merged**
