### PR TITLE
Update talk_controller.rb

### PR DESCRIPTION
**Pull request by Teslimsama**
rubocop fixes: talk-controller #11497

* [x] made changes to a line of code which is below

<li>"-    @node = Node.find_by_path 'wiki/' + params[:id] if @node.nil?"</li>
<li>"+    @node = Node.find_by_path "wiki/#{params[:id]}" if @node.nil?"</li>

### CODE REVIEW

**Comment by Teslimsama** [comment]
@TildaDares @cesswairimu i am done is there anything else to do

**Review by TildaDares — APPROVED** [review]
Amazing work @Teslimsama. Thank you!!

**Comment by TildaDares** [comment]
Congratulations on merging your PR @Teslimsama 🎉🎉

**Comment by Teslimsama** [comment]
Thanks 🙏

**Comment by Teslimsama** [comment]
@TildaDares  will I be added to contributors

**Comment by TildaDares** [comment]
Adding a commit automatically includes your name as a contributor @Teslimsama.

**Pull request merged**
