### PR TITLE
changing configurations, addition to gemfile

### LINKED ISSUE #4374: Solving the N+1 query problem

### PR DESCRIPTION
**Pull request by shubhscoder**
Fixes #4374
This is a sample of a javascript alert that occurs in case it detects that eager-loading can be used. 
bullet1

Also a log file is created where we can see the trace of the lines causing n+1 queries or anything of that sort. 
Thanks!

### CODE REVIEW

**Comment by shubhscoder** [comment]
Also we can somehow integrate this with our testing enviroment. The documentation has details regarding integration with rpsec, but I am searching of how we can somehow integrate this with minitest. The advantage of this would be, that any n+1 query would fail the test itself and thus we can fix it, then and there. Thank you!

**Comment by jywarren** [comment]
oh wow, this is cool! Is it possible to have a link to a page with more
information, perhaps saying "We've detected a potential for optimization.
Read more to learn how... etc... or open an issue to get this improved"

I'm wondering if an alert is the right way to do this - perhaps integration
with the testing environment and Travis is better?

**Comment by shubhscoder** [comment]
So, there are multiple ways in which we can get alerts regarding potential optimization. Alerts is one of them. But we also have a log file that is generated in bullet/log which contains detail trace of the line of the code that caused the problem so we can use that instead of alerts. One of the other methods is checking logs in the console every time we load a page. Or one of the other options this gem offers is that we could directly log the warnings in rails logs. So we could use anyone and disable alerts.

Also it is possible to integrate this with our testing environment. However the official documentation (https://github.com/flyerhzm/bullet) guides on integrating this with rspec and not with minitest, however I have found a gist(https://github.com/flyerhzm/bullet) that guides on integrating bullet with minitest, however I am not sure of how reliable the gist is. I will make the changes on my local machine and check how it works then we can integrate this here.

**Comment by shubhscoder** [comment]
@jywarren So I have integrated bullet with tests. This is how the output would like:
error_log_bullet. But now the problem is, travis would keep failing for all PR's until we fix all the unoptimized queries. So what we would do is for now we could refrain from failing tests if unoptimized queries are detected, instead we will just log the errors and then start fixing them one by one. So I need your suggestion here. Thank you so much!

**Comment by jywarren** [comment]
Oh wow! Ok, we need some brainstorming. How many queries are there?

**Comment by gauravano** [comment]
@shubhscoder you want to work on this or we can close this? Thanks!

**Comment by shubhscoder** [comment]
Sorry gauravano for the delay! But I want to work on this. Will try to get
this running asap.

**Comment by gauravano** [comment]
Ok! Thanks!

**Comment by SidharthBansal** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by gauravano** [comment]
As @shubhscoder mentioned he would be busy with GSoC, so closing this for now. And, we can take this up again when he is free? 

Thanks!!

**Pull request closed without merging**
