### PR TITLE
Fix main image select field not functioning issue. (fix issue#468)

### PR DESCRIPTION
**Pull request by ujithaperera**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

This PR fix issue #468 
  - uploaded image is shown in select field
  - change image name displayed in select field to avoid bad user experience
  - main image change with select field
  - selected image set as note/wiki main image when submitting by clicking publish button
  - fix style issue - edit select field width to locate with in range.

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, Ujitha - thanks, this looks really good. Can I ask you to please:

* [ ] update the development.sqlite.example file with the new migration
* [ ] move simple.js into setup.js -- or a more topically named file, such as perhaps post.js? 
* [ ] squash this into a single commit

Thank you - I think this'll be merge-able on Tuesday if everything goes smoothly. Thanks again for your contribution!

**Comment by ujithaperera** [comment]
Ok. I will complete these changes. Thanks for reviewing my code.

On Saturday, 9 April 2016, Jeffrey Warren <notifications@github.com> wrote:

> Hi, Ujitha - thanks, this looks really good. Can I ask you to please:
>
>    - update the development.sqlite.example file with the new migration
>    - move simple.js into setup.js -- or a more topically named file, such
>    as perhaps post.js?
>    - squash this into a single commit
>
> Thank you - I think this'll be merge-able on Tuesday if everything goes
> smoothly. Thanks again for your contribution!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/pull/491#issuecomment-207564263>
>


-- 
Sent from Gmail Mobile

**Comment by ujithaperera** [comment]
Hi Jeffery,
I updated the development.sqllite.example. when you got time, review this update.
Thanks.

**Comment by jywarren** [comment]
Thanks! will test out and publish probably on Saturday instead of the usual Friday.

**Comment by ujithaperera** [comment]
okay. thanks !

**Pull request merged**
