### PR TITLE
(On Hold) Search view translation

### PR DESCRIPTION
**Pull request by jiteshjha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
- [x] All tests pass -- `rake test:all`
- [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
- [x] pull request are descriptively named
- [x] if possible, multiple commits squashed if they're smaller changes
- [ ] reviewed/confirmed/tested by another contributor or maintainer
- [x] `schema.rb.example` has been updated if any database migrations were added

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by jiteshjha** [comment]
Hi @jywarren, small PR for search view I18n. 
Thanks!

**Comment by jywarren** [comment]
This looks good, but will probably overlap the work of @david-days and @ujithaperera -- can you three just sync up and tell me what order I should merge PRs in? I wouldn't want to create an especially bad merge conflict. Thanks!

**Comment by ujithaperera** [comment]
@jywarren and @jiteshjha actually this views are won't be available with our update. David and I designed two different search pages called `advanced search` and `dynamic search`. Yes, this may generate few unnecessary merge conflicts. @david-days what do you suggest ?

**Comment by jywarren** [comment]
I think a lot of the actual translations may be very helpful on the new
pages. Perhaps we could wait on this PR until the big search merge is
complete, then try to re-apply these translations to the new page?

**Comment by ujithaperera** [comment]
Yes, It's good.

**Comment by jiteshjha** [comment]
We can merge this in after @ujithaperera's work has been merged.

**Comment by jywarren** [comment]
Hi, Jitesh - don't know if you're too busy or what, but we've just merged in all the search code in #810 and could revisit this now if you have any time. Thanks and hope you're well!

**Comment by ryzokuken** [comment]
Hello! You must've noticed that the unit tests failed unexpectedly on your PR. This was due to some issue in the Travis CI testing configuration which was fixed by @jywarren later tonight. In order to make them work again, please rebase your work on top of the current master and then try pushing to your remote branch. Do this by:

```
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout <my-branch>
$ git rebase master
$ git push origin <my-branch>
```

Thanks for bearing with us,
Ujjwal

**Comment by jywarren** [comment]
Going to close this as we're making some bigger changes to search, so this would need to be rewired. Thank you though!!!

**Pull request closed without merging**
