### PR TITLE
3-column layout option for printing notes, issue #1622

### PR DESCRIPTION
**Pull request by priyansh1161**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] all tests pass -- `rake test:all`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by priyansh1161** [comment]
@jywarren can you please review this?

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Comment by priyansh1161** [comment]
@jywarren Thanks:)

**Comment by ebarry** [comment]
so awesome!

**Comment by jywarren** [comment]
I made some extra changes, mostly to turn off the 3-columns after printing is done, but this is now live!

It looks great, especially on pages like https://publiclab.org/notes/ashkaya/09-17-2016/build-a-coqui-a-simple-water-conductivity-sensor

screenshot 2017-09-26 at 5 52 25 pm

**Comment by priyansh1161** [comment]
@jywarren should we work on this?

**Pull request merged**
