### PR TITLE
Add doc for running plots2 with MySQL

### PR DESCRIPTION
**Pull request by stefannibrasil**
This is a doc improvement to help anyone that might have problems like this #3170 so they can run plots2 with MySQL on both development and test environments.

### CODE REVIEW

**Comment by jywarren** [comment]
This is great! Anything you wanted to say about `mariadb` too?

**Comment by stefannibrasil** [comment]
not really, do you have something? I can add here :)

I installed `mariadb` on my pc because I use fedora and it was easier, but I don't really know what to put there about this :D any help would be appreciated :D

**Comment by jywarren** [comment]
ah, i think we can probably just say you can use either MySQL or MariaDB,
near the top?

**Comment by stefannibrasil** [comment]
done :+1: :shipit:

**Comment by jywarren** [comment]
Awesome 👍

**Pull request merged**
