### PR TITLE
Update README testing section

### PR DESCRIPTION
**Pull request by aamarill**
Issue #440 has been resolved, so this line can be removed?

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by aamarill** [comment]
@publiclab/reviewers I do apologize if I was supposed to make this an issue before submitting a PR. But it's a short enough PR that I though it would be appropriate 😄

**Comment by SidharthBansal** [comment]
Thanks @aamarill for contributing at public lab. Yeah, the link is obsolete now.

@jywarren can you please merge this one?

**Comment by aamarill** [comment]
🙏 Thank you 🙌

**Comment by jywarren** [comment]
Hooray!!!! 🎉 🎊  🕺

**Pull request merged**
