### PR TITLE
Fixes the bug of logging out of already logged out account

### LINKED ISSUE #7433: Back Button takes User back to Dashboard even after logging out
There is no check to stop user from getting back to Dashboard after logging out.
ezgif com-video-to-gif(1)
Process I do in the gif
 - I logged into my account and then 'Logout of all devices'.
 - After that I click on 'Back' button of browser and I can go back to my dashboard even after I have logged out .
 - Also when I now try to 'Logout' then error occurs.

The logout can first verify current status of user before logging out .

### PR DESCRIPTION
**Pull request by imajit**
Fixes #7433 
The current bug on the site is similar to the gif below
ezgif com-video-to-gif(1)
After the changes the bug is solved 
ezgif com-video-to-gif(2)

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Travis is failing. Kindly check it

**Comment by SidharthBansal** [comment]
Still travis is failing. Kindly check

**Comment by imajit** [comment]
@SidharthBansal can you please review this

**Comment by SidharthBansal** [comment]
Please check Travis. Your changes doesn't fix the issue

**Pull request closed without merging**
