### PR TITLE
Powertag modal

### LINKED ISSUE #4155: Link Login Modal to power tag wiki page
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to ``login ``text on https://publiclab.org/w/power-tags#Inline+power+tags
image

### PR DESCRIPTION
**Pull request by JonathanXu1**
Fixes  #4155

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 I already made a PR.. Sorry

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 Absolutely, Sorry for the inconvenience..

**Comment by JonathanXu1** [comment]
Thanks for understanding :) You're a good guy

**Comment by SidharthBansal** [comment]
Oorjit please don't do this again. Be careful. Don't take it as a competition. Take it as learning.
Jonathan is correct.
He claimed the issue before you.
Jonathan don't worry I am closing this issue but will reward you for work work.

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/6284621252657152/ Jonathan please submit this

**Pull request closed without merging**
