### PR TITLE
Rename main_image.js to mainImage.js

### LINKED ISSUE #9148: camelCase main_image.js filename
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### ❓ Why are we doing this?

See Issue #9140 for more information!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** these files below:

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below are some "diffs" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add for each file:

`/app/assets/javascripts/application.js`
```diff
+ //= require mainImage.js
- //= require main_image.js
```

`/app/assets/javascripts`:
```diff
+ mainImage.js
- main_image.js
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by larabee7777**
Fixes #9148 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by larabee7777** [comment]
@noi5e please review when you get a chance thanks :)

**Comment by Manasa2850** [comment]
Hi @larabee7777 could you please add the issue number at `Fixes #0000 (<=== Add issue number here)`. It'll help us to automatically close the issue once this PR is merged.
Thank you!

**Comment by noi5e** [comment]
@Manasa2850 Ah yeah, good catch! @larabee7777 I didn't know you had this PR open because it wasn't linked to the issue. Putting the issue number in the PR links it back there.

It looks like the tests are failing, so we won't be able to merge this yet:
Screen Shot 2021-02-15 at 7 11 57 PM

If I look under _Files Changed_...
Screen Shot 2021-02-15 at 7 13 16 PM

I see that you renamed the file, but didn't do the other change that was in the issue. Please make another commit to include that change! Thanks.

**Comment by larabee7777** [comment]
Hi, I think I separated the two issues into 2 pull requests because it looked like two issuse - one code change and one file name change. So I thought I did both issues, but let me look again and see what I missed. 

/app/assets/javascripts/application.js - went to this file and edited the code

+ //= require mainImage.js
- //= require main_image.js
/app/assets/javascripts: - i went to this list of file names and edited the file name to match my previous change so that the names match

+ mainImage.js
- main_image.js

So I think I at least understood what was expected of me but I made a mistake somewhere and I must check again

**Comment by larabee7777** [comment]
So I checked both pull requests and linked them as requested, in that main description area. 

So these two PR's fix #9148

publiclab/plots2 Rename main_image.js to mainImage.js 
#9201 opened 15 hours ago by larabee7777 • Review required 0 of 5
 1
 7
publiclab/plots2 Update application.js 
#9200 opened 15 hours ago by larabee7777 • Review required 0 of 5

Should it be one PR per issue? If so how would I have done that because I thought I had to branch off each filename and each change so that if one fix is right and the rest wrong we can approve the one right action and work on the incorrect ones. 

Please let me know what I did wrong and how I can improve, thanks so much for your help!

**Comment by larabee7777** [comment]
**It looks like the tests are failing, so we won't be able to merge this yet:**

I dont know what those tests mean please help me with that. The code is commented out so I thought I had to leave it as is and the errors would be fixed as other issues

**Comment by noi5e** [comment]
@larabee7777 Thanks for hanging in there and asking for clarification! 

It has to be 1 PR containing both changes simultaneously. If the changes are spread out over 2 PRs, it's like there are 2 different versions of the app. Each pull request has its own version of the app, and they have no relation with each other.

If you rename `main_image.js` to `mainImage.js`, then `application.js` needs to be updated as well. If you don't update `application.js`, then what happens is it will try to look up `main_image.js` like always... And won't find anything (because the file has been renamed).

If you look through the failed tests (click on Details in the screenshot I took above), you can get a sense for this by looking at the readout:
Screen Shot 2021-02-16 at 12 37 33 AM

Aha! It says `ActionView::Template::Error: couldn't find file 'main_image.js' with type 'application/javascript'`. That shows me that the theory above is probably correct. I know that it can be kind of confusing sifting through failed tests, but you really can learn a lot that way! 😊 

I was also confused about lines looking like they were commented out in `application.js`. For confusing things like that, I always find it's helpful to Google documentation to learn about it. Searching for "application.js rails" comes up with [this](https://guides.rubyonrails.org/asset_pipeline.html#search-paths) for example. I still don't really understand why Rails does it this way, but it does tell me that it's working, and is not just a comment.

Hope that helps! So definitely make 1 PR with both changes and we'll take it from there. Actually you don't need to open up a new PR, you can just push the commit to the PR you already have open. Let me know if you need clarification there.

**Comment by larabee7777** [comment]
$(document).ready(function(){
  $('#image_revision').change(function(){
    $('#main_image').val($('#image_revision option:selected').attr("id"));
    $('#leadImage').attr("src",$('#image_revision option:selected').val());
  });
});


this is the code in mainImage,js - the filename was changed, must I change that main_image code in line 3 with the correct camel case mainImage too?

**Comment by noi5e** [comment]
@larabee7777 Ah no, that's different. That's an example of a [jQuery selector](https://api.jquery.com/category/selectors/). jQuery is referring to an HTML element that has an ID `#main_image`, different from this file that we're renaming.

Come to think of it, this is probably a good example of why programmers have naming conventions. Usually HTML elements follow the convention of `#main-image` instead of `#main_image`, which is the Ruby on Rails convention. In this case, it's confusing! 😕 

Otherwise, this looks good! Your tests are all passing! That means this is ready to merge!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Great work folks! Thanks so much @larabee7777 and thanks @noi5e for the support!!!

**Pull request merged**
