### PR TITLE
Search ui improvement

### PR DESCRIPTION
**Pull request by stefannibrasil**
Moved from #3295

### CODE REVIEW

**Comment by stefannibrasil** [comment]
@jywarren I got how to add a button the input. I was looking for Bootstrap 4 docs before, that's why it was breaking on mobile xD

so I added the button to the search, as you requested:

desktop

^desktop

mobile

^mobile

**Comment by jywarren** [comment]
This is looking good -- can you upload a final screenshot and we'll try to merge? Thanks!!!

**Comment by stefannibrasil** [comment]
sure!

pl1

pl2

pl3

pl4

:) thank you!

**Comment by jywarren** [comment]
Ok, merging now! Thanks and great work!

**Comment by jywarren** [comment]
Hi, is there a "tag" type here? I'm testing at https://stable.publiclab.org and not seeing those in the results for things like "Balloon mapping"...

**Comment by jywarren** [comment]
Ah, yes - here

image

Odd that it doesn't show for everything... just some tags!

**Comment by stefannibrasil** [comment]
@jywarren  Ok, so I have an idea about what is happening:

1) this line returns 5 items in general not for category as I expected :( . I'll move back to 15. It may be messing with the tags because it is returning only 5 items.

https://github.com/publiclab/plots2/blob/e98cf75c7bbac731f36981ac9d555ee51b21f01b/app/assets/javascripts/restful_typeahead.js#L12

2) I will change the order of the items added to the `SearchService.textSearch_all` method so the categories don't get messed like this.

I'll push them in a minute, thanks for the help!!!

**Comment by jywarren** [comment]
thank you too!

**Comment by stefannibrasil** [comment]
ok, so I opened a new one.

I put some limits on the methods, the results were almost 200! Maybe we can create an issue to standardize those limits, but I guess should make it better for now.

One thing that I don't know is why it isn't grouping the categories. If you search by 'oil' and see the results on Console > Networks, it is grouped by category:

```
{
  "items": [{
    "docId": 16591,
    "docType": "file",
    "docUrl": "/notes/pfhs/06-29-2018/video-describing-basics-of-launching-regular-mini-balloon-kits",
    "docTitle": "Video describing basics of launching regular/mini balloon kits?",
    "category": "NOTES",
    "docScore": 0
  }, {
    "docId": 16588,
    "docType": "file",
    "docUrl": "/notes/pfhs/06-28-2018/sample-aerial-balloon-or-kite-images-from-mobius-action-camera",
    "docTitle": "Sample aerial (balloon or kite) images from Mobius Action Camera?",
    "category": "NOTES",
    "docScore": 0
  }, {
    "docId": 16426,
    "docType": "file",
    "docUrl": "/notes/pfhs/06-03-2018/how-long-does-an-inflated-neoprene-balloon-last-mylar-balloons-better-for-summer-camp",
    "docTitle": "How long does an inflated neoprene balloon last? Mylar balloons better for summer camp?",
    "category": "NOTES",
    "docScore": 0
  }, {
    "docId": 16357,
    "docType": "file",
    "docUrl": "/notes/tmclean1/05-17-2018/mapknitter-map-of-fontainebleau-state-park-balloon-nir",
    "docTitle": "MapKnitter map of Fontainebleau State Park Balloon NIR",
    "category": "NOTES",
    "docScore": 0
  }
}
```

Let's see what happens now with those changes and then I can investigate later the groupying problem, @jywarren

**Comment by stefannibrasil** [comment]
#3310

**Comment by jywarren** [comment]
Great. I'll merge and hope to publish tonight.

Will these limits affect the main /search/______ page too?

**Pull request merged**
