### PR TITLE
Comment listing on dashboard

### LINKED ISSUE #4447: A 'pending for approval' comment shows up on the website
### Please describe the problem (or idea)
A comment which is pending for approval shouldn't be shown right?
The comment still comes up with the `moderated view` but is visible on the website.
It can be viewed on /research as well as /dashboard.

> What happened just before the problem occurred? Or what problem could this idea solve?

image1

image2

### Please show us where to look

https://publiclab.org/research
https://publiclab.org/dashboard

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #4447

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts 📁
* [x] PR is descriptively titled 📑
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Looks great! Will these appear greyed out or otherwise marked as unapproved? If so, go ahead and merge, thank you!!!

**Comment by gauravano** [comment]
**Here's the current status of comments in moderation process:** 
Commenter - comment visible at note and on dashboard with message
No user session - comment visible at note and on dashboard with message
Moderator - comment visible at note and on dashboard with moderation options
Normal user - comment visible at note and on dashboard with message

So, normal and logged out users are also able to see the comment on their dashboard in this view:
mode_view

This PR fixes the dashboard view for all the users. I will focus on the moderated comment view in another PR as it would require designing the view and brainstorming about flow too.

**Comment by gauravano** [comment]
Hi @jywarren, merging this one. Please let me know if you suspect any moderated comment at a wrong place.

Status of moderated comments after merging this PR should be:
* Commenter - comment visible on dashboard with message
* No user session - comment not visible
* Moderator - comment visible on dashboard with moderation options
* Normal user - comment not visible at dashboard

Checking at unstable for different users: https://drive.google.com/open?id=12E4n_xvlSfaXXrFc05oMWMnYbT9LqSAk

Thanks!

**Comment by gauravano** [comment]
@jywarren from next time, i would call you or sidharth for merging my PR. It wasn't that fun merging own PR :sweat_smile: .

**Comment by jywarren** [comment]
Oh, sorry! It's awesome to see this fixed though!

**Comment by gauravano** [comment]
No worries!

**Pull request merged**
