### PR TITLE
Combined wiki/note grids

### LINKED ISSUE #3758: Combined wiki/note grids using [node:_____] syntax, for inline grids
This may be a bit more complex, but we'd love some help. 

We have inline grids on pages like this: https://publiclab.org/wiki/air-sensors

This means we have different ways to include inline tables of other pages, using syntax like:

`[notes:______]` or `[wikis:________]`

The templates for these are here:

https://github.com/publiclab/plots2/tree/master/app/views/grids

But sometimes you want to have both wikis and notes displayed. It'd be great to have a combined grid type for any node (see our /docs/ folder and the DATA MODEL) - with format:

`[node:_____]`

See how I've kind of done a broken version of this by just using one grid tag after the other -- showing 2 tables one after the other (a hack! Not very nice but... kind of works):

image

One issue is that notes and wikis have different columns - like the timestamp or author column. Let's try to find what overlaps and display those columns so it makes some sense -- but we can tweak this later.

### PR DESCRIPTION
**Pull request by ValentinaTironi**
Fixes #3758 

Here is a gif showing how it works.
wiki_notes

Test works:
screen shot 2018-11-26 at 5 23 00 pm

### CODE REVIEW

**Comment by ValentinaTironi** [comment]
Here @jywarren

**Comment by jywarren** [comment]
Fantastic work! And so fast!

**Comment by jywarren** [comment]
I'm not sure if they're still working on it but there was an issue with thumbnail grid display -- formatting it with Bootstrap -- maybe you'd be interested in helping out? 

https://github.com/publiclab/plots2/pull/3970#issuecomment-439167488

Right now the table CSS they were using is actually disrupting other table display, so it'd be preferable to move that to a bootstrap-based layout as in the comment i left. If you're interested, we could definitely use your help!

**Comment by jywarren** [comment]
if you'd like we can make a google code-in issue for it?

**Comment by ValentinaTironi** [comment]
Omg, it would be really great! Thank u 💯

**Comment by jywarren** [comment]
https://codein.withgoogle.com/dashboard/tasks/4957100062015488/ go for it! 👍

**Comment by ValentinaTironi** [comment]
I can't claim that task without approve this in gci! (COMBINED WIKI/NOTE GRIDS USING [NODE:_____] SYNTAX, FOR INLINE GRIDS)

**Comment by jywarren** [comment]
Approving now!

**Comment by ValentinaTironi** [comment]
Thank you Jeff! I'm gonna work in that issue now!

**Pull request merged**
