### PR TITLE
Add icon to copy URL of the wiki page and deleting the URL column

### LINKED ISSUE #5467: Remove URL column from the wiki table
Since a user can directly visit any wiki by clicking on the name which is the link to the wiki, I think that the URL column in the wiki's table is redundant. 
Removing the URL column will provide space for the other columns which for now look crowded.

Screen Shot 2019-04-12 at 6 46 33 PM

### PR DESCRIPTION
**Pull request by gautamig54**
Fixes #5467  (<=== Add issue number here)

Screen Shot 2019-04-18 at 7 09 51 PM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gautamig54** [comment]
@publiclab/reviewers Kindly review this PR! Thanks!

**Comment by gautamig54** [comment]
@gauravano What do you think about this?

**Comment by gauravano** [comment]
It looks cleaner now. I think, using a link instead of copy would be better. Hmm, having a dedicated column would be better or showing the icon only on hovering over the row? Or, no change required? @jywarren thoughts. Thanks!

**Comment by gautamig54** [comment]
Thanks for the review @gauravano.
I can even design the copy icon in the first column if it looks abrupt.

**Comment by gauravano** [comment]
I am sure you can @gautamig54. But, let's wait for @jywarren or @publiclab/community-reps as this is design issue and requires their input. Also, I don't want to waste your efforts and time. Thanks!

**Comment by aSquare14** [comment]
@gautamig54 Please resolve conflicts. @jywarren What are your thoughts ?

**Comment by jywarren** [comment]
Just looking back to the purpose of this path originally, i see:

https://github.com/publiclab/plots2/pull/3776
https://github.com/publiclab/plots2/issues/3744

I can't remember why we wanted this! 

What if we put the extra information under a `...` menu? Then the whole table would be simpler, and we could still add extra details in there, like # of revisions, # of authors, things like that?

**Comment by aSquare14** [comment]
@jywarren Sounds better :D

**Comment by aSquare14** [comment]
Any updates ?

**Comment by gautamig54** [comment]
hi @aSquare14! Actually the design for the wiki page is not yet finalised. So we are not working on this rn. Thanks!

**Comment by aSquare14** [comment]
Should we maybe close this PR as we won't be working on it anymore ?

**Comment by gautamig54** [comment]
Sure @aSquare14! I'll close this PR for now.

**Pull request closed without merging**
