### PR TITLE
Move yarn configuration into yarnrc

### PR DESCRIPTION
**Pull request by Radhikadua123**
Move out yarn configuration into separate file. It's easy to forget passing those options when ran after adding new module. So, it's a small fix by which dev won't have to pass those options every time.

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`

### CODE REVIEW

**Comment by Souravirus** [comment]
Nice work @Radhikadua123. It would be very easy for developers to `yarn install` command.

**Comment by Radhikadua123** [comment]
@Souravirus Thanks! :)

**Comment by Radhikadua123** [comment]
@jywarren @Souravirus I have pushed changes related to https://github.com/publiclab/plots2/issues/3727 here.

**Comment by Souravirus** [comment]
ok I am pushing this to unstable branch. Thanks @Radhikadua123 !!

**Comment by Souravirus** [comment]
@Radhikadua123 It worked. Nice work. @jywarren please see this PR.

**Comment by jywarren** [comment]
Oh WOW!!! @icarito take a look! 

@Radhikadua123 this is so awesome. Thank you so much!!!

**Comment by jywarren** [comment]
We'll try this today!!

**Pull request merged**
