### PR TITLE
Highlights the selected tab on the page

### LINKED ISSUE #3526: Highlight selected tab
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

### Please describe the problem (or idea)
It will be good if the selected tab is highlighted.
> What happened just before the problem occurred? Or what problem could this idea solve?

tab

> What did you expect to see that you didn't?
I expect to highlight selected tab as above 

### Please show us where to look

https://publiclab.org/search/science%20community?order=default

### What's your PublicLab.org username?
igniteeng000
> This can help us diagnose the issue: 

https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/search/notes.html.erb
https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/search/wikis.html.erb

### Browser, version, and operating system
windows 10, chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #3526 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@SidharthBansal @jywarren @igniteeng000 Pls review my PR.
This resolves issue #3526

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I'm afraid I don't understand. How can I open the page using my code and provide the screenshot?

**Comment by SidharthBansal** [comment]
Have you set up/install the plots 2 repo on the local machine?

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Yes..

**Comment by SidharthBansal** [comment]
So you need to create some pages with lorem ipsum text and add some tags to
them on the local host.
Then go to /search/tag_name which you have created. It will show the
buttons. Click on the buttons. If they get highlighted that means your code
is working. Have a screenshot with the Print Screen Command.

**Comment by oorjitchowdhary** [comment]
ok

**Comment by oorjitchowdhary** [comment]
image

**Comment by oorjitchowdhary** [comment]
I have to create a page here?

**Comment by oorjitchowdhary** [comment]
I'm confused.. how will the code get updated? I actually edited the code online on my forked repo..

**Comment by SidharthBansal** [comment]
It's your first time. No need to worry about it. We are here to help you.
The above screenshot posted by you is for the creation of wiki pages.
You need to create research notes for this issue by going to the
localhost:3000/post.

**Comment by oorjitchowdhary** [comment]
Ok and to create the page.. I can put any random info?

**Comment by oorjitchowdhary** [comment]
I created the page.. I can view it and I can see the buttons too.. But the button isn't working.. How will the code get updated ? As i mentioned earlier, I edited the code file online on my forked repo

**Comment by SidharthBansal** [comment]
>>Ok and to create the page.. I can put any random info?

Yeah

>>But the button isn't working.. How will the code get updated ?

Make changes in the cloned repo at your desktop. Push the changes through
git.
Still if you face any trouble, please contact @publiclab/mentors. We are
here to help you.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I've uploaded the screenshot on the GCI platform... Pls review and approve my task.. Thanks

**Comment by SidharthBansal** [comment]
please upload it here.

**Comment by oorjitchowdhary** [comment]
6643609588727808_1541961003_virtualbox_oorjit_11_11_2018_23_58_37

**Comment by oorjitchowdhary** [comment]
Here you go

**Comment by SidharthBansal** [comment]
Please load the page properly and then send the screenshot.
Also send highlighted screenshot for other tabs.

**Comment by oorjitchowdhary** [comment]
screenshot 20
screenshot 21
screenshot 22
screenshot 23
screenshot 24
Here you go.. I'm really sorry for the delay.. Had an exam today

**Comment by oorjitchowdhary** [comment]
What's with the merging? WIll this be merged or I can close this PR?

**Comment by oorjitchowdhary** [comment]
@SidharthBansal @jywarren @gauravano

**Comment by jywarren** [comment]
Hi, @oorjitchowdhary -- i'm sorry, this took a bit longer to review; actually, it turns out there was already a solution proposed in https://github.com/publiclab/plots2/pull/3797, and it successfully highlighted the tabs. While we really appreciate your contribution as well, if you look at the solution there, the layout of the page seemed not to be changed other than the highlight, whereas your changes seem to be distorting the buttons. See the screenshot from #3797:



But do notice -- that solution was only implemented for the wikis page, not the notes search results. If you look carefully at that solution, and re-implement how it works on the notes search results page, we would be very happy to accept your pull request too!

Thank you!

**Comment by jywarren** [comment]
Also, it looks like, since we recently merged in some new changes to the master branch, you need to rebase your work on top of the latest master. You can do that by following the process outlined here, but you may be able to skip step 2 if your master is still in sync with publiclab's master: https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

Thanks!

**Comment by jywarren** [comment]
Or, if you'd like to remove the changes to wikis.html.erb from this PR, you can revert just that file, and keep your changes to `search/notes.html.erb` to resolve the issue as I described above.

https://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git

**Comment by jywarren** [comment]
Thanks for your hard work, and we're so glad to have your help!!

**Comment by oorjitchowdhary** [comment]
@jywarren Ok I get it.. So I'll remove the wikis file which I edited and I'll only change the notes file..

**Comment by oorjitchowdhary** [comment]
> Also, it looks like, since we recently merged in some new changes to the master branch, you need to rebase your work on top of the latest master. You can do that by following the process outlined here, but you may be able to skip step 2 if your master is still in sync with publiclab's master: https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch
> 
> Thanks!

I don't understand the steps there .. I'm 29 commits behind publiclab:master

**Comment by oorjitchowdhary** [comment]
I think I'll simply close this PR.. create a new one and only for the notes file.. What say?

**Comment by SidharthBansal** [comment]
No problem

**Pull request closed without merging**
